<!--STYLE-->
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css';?>"/>
<style>
.panel {
	border-radius:0px !important;
}
.panel-info {
	border:none;
	border-top:none;
}
.chat_content {
	float:left;
	width:100%;
}
</style>
<!--content-->

<div class="content_wrapper padlr0">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h1>Land Bank - Due Diligence</h1>
      </div>
      <!--form start-->
      <div class="col-lg-12 top_ct" >
        <div class="col-lg-4 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-8 col-sm-offset-2">
          <div class="form-group col-lg-12">
            <input type="text" name="lead_date" class="form-control lbl_move" label="Name of Property" />
          </div>
        </div>
      </div>
      <!--form end--> 
      <!--accordion start-->
      <div class="col-lg-12 clear">
        <div id="accordion" class="panel-group">
          <div class="panel panel-info">
            <div data-target="#collapseOne" data-parent="#accordion" data-toggle="collapse" class="panel-heading collapsed panel_heads">
              <h4 class="panel-title accordion-toggle defa_panels">Legal Check List</h4>
            </div>
            <div class="panel-collapse collapse" id="collapseOne" style="height: 0px;">
              <div class="panel-body bgcolr">
                <div class="checklisters clear">
                  <ul>
                    <li><span class="cheched"> <span class="users_det"> <img src="<?php echo $this->basePath(); ?>/images/pro_user.png" width="50" height="50p"/>
                      <p>Raju Kumar</p>
                      </span> <span class="dons">Done</span> <span class="checklistnames">
                      <p>Check List Name</p>
                      </span> <span class="time_datelist"> <a href="#" onclick="showComments(event, 1)" class="comments cd-btn">Comments <i class="fa fa-comment"></i></a>
                      <p>06/01/2015 &nbsp; / &nbsp;11.42Am</p>
                      </span> </span></li>
                    <li><span class="cheched"> <span class="users_det"> <img src="<?php echo $this->basePath(); ?>/images/pro_img.jpg" width="50" height="50p"/>
                      <p>Irfan</p>
                      </span> <span class="dons_prog">Progress</span> <span class="checklistnames">
                      <p>Check List Name</p>
                      </span><span class="time_datelist"> <a href="#" class="comments">Comments <i class="fa fa-comment"></i></a>
                      <p>06/01/2015 &nbsp; / &nbsp;11.42Am</p>
                      </span> </span></li>
                    <li><span class="cheched"> <span class="users_det"> <img src="<?php echo $this->basePath(); ?>/images/profile/profile1.jpg" width="50" height="50p"/>
                      <p>Raju Kumar</p>
                      </span> <span class="dons">Done</span> <span class="checklistnames">
                      <p>Check List Name</p>
                      </span> <span class="time_datelist"> <a href="#" class="comments">Comments <i class="fa fa-comment"></i></a>
                      <p>06/01/2015 &nbsp; / &nbsp;11.42Am</p>
                      </span> </span></li>
                    <li><span class="cheched"> <span class="users_det"> <img src="<?php echo $this->basePath(); ?>/images/pro_user.png" width="50" height="50p"/>
                      <p>Raju Kumar</p>
                      </span> <span class="dons">Done</span> <span class="checklistnames">
                      <p>Check List Name</p>
                      </span> <span class="time_datelist"> <a href="#" class="comments">Comments <i class="fa fa-comment"></i></a>
                      <p>06/01/2015 &nbsp; / &nbsp;11.42Am</p>
                      </span> </span></li>
                    <li><span class="cheched"> <span class="users_det"> <img src="<?php echo $this->basePath(); ?>/images/pro_user.png" width="50" height="50p"/>
                      <p>Raju Kumar</p>
                      </span> <span class="dons_prog">Progress</span> <span class="checklistnames">
                      <p>Check List Name</p>
                      </span><span class="time_datelist"> <a href="#" class="comments">Comments <i class="fa fa-comment"></i></a>
                      <p>06/01/2015 &nbsp; / &nbsp;11.42Am</p>
                      </span> </span></li>
                    <li><span class="cheched"> <span class="users_det"> <img src="<?php echo $this->basePath(); ?>/images/pro_user.png" width="50" height="50p"/>
                      <p>Raju Kumar</p>
                      </span> <span class="dons">Done</span> <span class="checklistnames">
                      <p>Check List Name</p>
                      </span> <span class="time_datelist"> <a href="#" class="comments">Comments <i class="fa fa-comment"></i></a>
                      <p>06/01/2015 &nbsp; / &nbsp;11.42Am</p>
                      </span> </span></li>
                    <li><span class="cheched"> <span class="users_det"> <img src="<?php echo $this->basePath(); ?>/images/profile/profile2.jpg" width="50" height="50p"/>
                      <p>Balaji</p>
                      </span> <span class="dons_prog">Progress</span> <span class="checklistnames">
                      <p>Check List Name</p>
                      </span> <span class="time_datelist"> <a href="#" class="comments">Comments <i class="fa fa-comment"></i></a>
                      <p>06/01/2015 &nbsp; / &nbsp;11.42Am</p>
                      </span> </span></li>
                    <li><span class="cheched"> <span class="users_det"> <img src="<?php echo $this->basePath(); ?>/images/pro_user.png" width="50" height="50p"/>
                      <p>Raju Kumar</p>
                      </span> <span class="dons_prog">Progress</span> <span class="checklistnames">
                      <p>Check List Name</p>
                      </span> <span class="time_datelist"> <a href="#" class="comments">Comments <i class="fa fa-comment"></i></a>
                      <p>06/01/2015 &nbsp; / &nbsp;11.42Am</p>
                      </span> </span></li>
                  </ul>
                </div>
                <div class="col-lg-12">
                  <div class="add_newlist">
                    <ul>
                      <li>
                        <div class="manual_seletc" style="margin-top:0px; ">
                          <label>Filter By :</label>
                          <div class="select-style select-inline" style="border:1px solid #c2c2c2;">
                            <select onchange="return IOWRateUpdate(this.id)" id="ratetype_1" name="ratetype_1" style="height:33px;">
                              <option value="">Select status</option>
                              <option value="">Done</option>
                              <option selected="" value="S">Progress</option>
                            </select>
                          </div>
                        </div>
                      </li>
                      <li>
                        <input type="text" name="name" placeholder="Check List Name">
                        <input type="submit" value="Add New">
                      </li>
                    </ul>
                  </div>
                </div>
                <div class="cont_bt col-lg-5 col-lg-offset-7 col-md-9 col-md-offset-3 col-sm-7 col-sm-offset-3 col-xs-7 col-xs-offset-4">
                  <ul>
                    <li><a href="#">Continue</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="panel panel-info">
            <div data-target="#collapseTwo" data-parent="#accordion" data-toggle="collapse" class="panel-heading collapsed panel_heads">
              <h4 class="panel-title accordion-toggle defa_panels">Financial - Check List</h4>
            </div>
            <div class="panel-collapse collapse" id="collapseTwo" style="height: 0px;">
              <div class="panel-body bgcolr">
                <div class="checklisters clear">
                  <ul>
                    <li><span class="cheched"> <span class="users_det"> <img src="<?php echo $this->basePath(); ?>/images/pro_user.png" width="50" height="50p"/>
                      <p>Raju Kumar</p>
                      </span> <span class="dons">Done</span> <span class="checklistnames">
                      <p>Check List Name</p>
                      </span> <span class="time_datelist"> <a href="#" onclick="showComments(event, 1)" class="comments cd-btn">Comments <i class="fa fa-comment"></i></a>
                      <p>06/01/2015 &nbsp; / &nbsp;11.42Am</p>
                      </span> </span></li>
                    <li><span class="cheched"> <span class="users_det"> <img src="<?php echo $this->basePath(); ?>/images/pro_img.jpg" width="50" height="50p"/>
                      <p>Irfan</p>
                      </span> <span class="dons_prog">Progress</span> <span class="checklistnames">
                      <p>Check List Name</p>
                      </span><span class="time_datelist"> <a href="#" class="comments">Comments <i class="fa fa-comment"></i></a>
                      <p>06/01/2015 &nbsp; / &nbsp;11.42Am</p>
                      </span> </span></li>
                    <li><span class="cheched"> <span class="users_det"> <img src="<?php echo $this->basePath(); ?>/images/profile/profile1.jpg" width="50" height="50p"/>
                      <p>Raju Kumar</p>
                      </span> <span class="dons">Done</span> <span class="checklistnames">
                      <p>Check List Name</p>
                      </span> <span class="time_datelist"> <a href="#" class="comments">Comments <i class="fa fa-comment"></i></a>
                      <p>06/01/2015 &nbsp; / &nbsp;11.42Am</p>
                      </span> </span></li>
                    <li><span class="cheched"> <span class="users_det"> <img src="<?php echo $this->basePath(); ?>/images/pro_user.png" width="50" height="50p"/>
                      <p>Raju Kumar</p>
                      </span> <span class="dons">Done</span> <span class="checklistnames">
                      <p>Check List Name</p>
                      </span> <span class="time_datelist"> <a href="#" class="comments">Comments <i class="fa fa-comment"></i></a>
                      <p>06/01/2015 &nbsp; / &nbsp;11.42Am</p>
                      </span> </span></li>
                    <li><span class="cheched"> <span class="users_det"> <img src="<?php echo $this->basePath(); ?>/images/pro_user.png" width="50" height="50p"/>
                      <p>Raju Kumar</p>
                      </span> <span class="dons_prog">Progress</span> <span class="checklistnames">
                      <p>Check List Name</p>
                      </span><span class="time_datelist"> <a href="#" class="comments">Comments <i class="fa fa-comment"></i></a>
                      <p>06/01/2015 &nbsp; / &nbsp;11.42Am</p>
                      </span> </span></li>
                    <li><span class="cheched"> <span class="users_det"> <img src="<?php echo $this->basePath(); ?>/images/pro_user.png" width="50" height="50p"/>
                      <p>Raju Kumar</p>
                      </span> <span class="dons">Done</span> <span class="checklistnames">
                      <p>Check List Name</p>
                      </span> <span class="time_datelist"> <a href="#" class="comments">Comments <i class="fa fa-comment"></i></a>
                      <p>06/01/2015 &nbsp; / &nbsp;11.42Am</p>
                      </span> </span></li>
                    <li><span class="cheched"> <span class="users_det"> <img src="<?php echo $this->basePath(); ?>/images/profile/profile2.jpg" width="50" height="50p"/>
                      <p>Balaji</p>
                      </span> <span class="dons_prog">Progress</span> <span class="checklistnames">
                      <p>Check List Name</p>
                      </span> <span class="time_datelist"> <a href="#" class="comments">Comments <i class="fa fa-comment"></i></a>
                      <p>06/01/2015 &nbsp; / &nbsp;11.42Am</p>
                      </span> </span></li>
                    <li><span class="cheched"> <span class="users_det"> <img src="<?php echo $this->basePath(); ?>/images/pro_user.png" width="50" height="50p"/>
                      <p>Raju Kumar</p>
                      </span> <span class="dons_prog">Progress</span> <span class="checklistnames">
                      <p>Check List Name</p>
                      </span> <span class="time_datelist"> <a href="#" class="comments">Comments <i class="fa fa-comment"></i></a>
                      <p>06/01/2015 &nbsp; / &nbsp;11.42Am</p>
                      </span> </span></li>
                  </ul>
                </div>
                <div class="col-lg-12">
                  <div class="add_newlist">
                    <ul>
                      <li>
                        <div class="manual_seletc" style="margin-top:0px; ">
                          <label>Filter By :</label>
                          <div class="select-style select-inline" style="border:1px solid #c2c2c2;">
                            <select onchange="return IOWRateUpdate(this.id)" id="ratetype_1" name="ratetype_1" style="height:33px;">
                              <option value="">Select status</option>
                              <option value="">Done</option>
                              <option selected="" value="S">Progress</option>
                            </select>
                          </div>
                        </div>
                      </li>
                      <li>
                        <input type="text" name="name" placeholder="Check List Name">
                        <input type="submit" value="Add New">
                      </li>
                    </ul>
                  </div>
                </div>
                <div class="cont_bt col-lg-5 col-lg-offset-7 col-md-9 col-md-offset-3 col-sm-7 col-sm-offset-3 col-xs-7 col-xs-offset-4">
                  <ul>
                    <li><a href="#">Continue</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="panel panel-info">
            <div data-target="#collapsethree" data-parent="#accordion" data-toggle="collapse" class="panel-heading collapsed panel_heads">
              <h4 class="panel-title accordion-toggle defa_panels">Encumbrance Certificate</h4>
            </div>
            <div class="panel-collapse collapse" id="collapsethree" style="height: 0px;">
              <div class="panel-body bgcolr">
                <div class="table-responsive topsp">
                  <table class="table tableWithFloatingHeader" style=" margin-bottom:0px;">
                    <thead>
                      <tr>
                        <th>Survey No</th>
                        <th>Patta No</th>
                        <th>Patta Name</th>
                        <th>Area of Land</th>
                        <th>Owner Name</th>
                        <th>Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td width="10%"><input class="parent_text" type="text" readonly /></td>
                        <td width="10%"><input class="parent_text" type="text" readonly /></td>
                        <td width="12%"><input class="parent_text" type="text" readonly /></td>
                        <td width="12%"><input class="parent_text" type="text" readonly /></td>
                        <td width="12%"><input class="parent_text" type="text" readonly /></td>
                        <td width="3%" align="center"><a href="#" class="mainTr"> <i class="fa fa-chevron-circle-down ctls" data-toggle="tooltip" data-placement="top" data-original-title="Expand" ></i></a></td>
                      </tr>
                      <!--expand table-->
                      <tr style="display:none;" class="subTr">
                        <td colspan="9" style="padding:0px !important; "><div class="subDiv" style="display:none;">
                            <div class="col-lg-12">
                              <div class="table-responsive topsp">
                                <table class="table tableWithFloatingHeader" style=" margin-bottom:0px;">
                                  <thead>
                                    <tr>
                                      <th>S-No</th>
                                      <th>Description of Documents</th>
                                      <th>DOC No / Dt.</th>
                                      <th>Exec / Vendor</th>
                                      <th>Climant/ Owner</th>
                                      <th>S.No / Exnt.</th>
                                      <th>Parent Doc. Ref</th>
                                    </tr>
                                  </thead>
                                  <tbody>
                                    <tr>
                                      <td width="10%"><input class="parent_text" type="text"/></td>
                                      <td width="30%"><input class="parent_texts" type="text"/></td>
                                      <td width="30%"><input class="parent_text" type="text"/></td>
                                      <td width="10%"><input class="parent_text" type="text"/></td>
                                      <td width="30%"><input class="parent_text" type="text"/></td>
                                      <td width="30%"><input class="parent_text" type="text"/></td>
                                      <td width="10%"><input class="parent_text" type="text"/></td>
                                    </tr>
                                  </tbody>
                                </table>
                              </div>
                            </div>
                          </div></td>
                      </tr>
                      <!--expand table-->
                      <tr style="display:none;" class="subTr">
                        <td colspan="9" style="padding:0px !important; "><div class="subDiv" style="display:none;"> 
                            <!-- Nav tabs -->
                            <div class="table-responsive">
                              <table style=" margin-bottom:0px;background:#E8FAFD!important; " class="table">
                                <tbody>
                                  <tr>
                                    <td style="padding:0px !important; border:none;" colspan="9"><div class="subDiv">
                                        <div style=" margin-top:10px;" class="col-lg-12">
                                          <ul class="nav nav-tabs navs-tabs">
                                            <li class="active"><a href="#owner" data-toggle="tab" aria-expanded="true">Co Owner Details</a></li>
                                            <li class=""><a href="#landinfo" data-toggle="tab" aria-expanded="false">Land Information</a></li>
                                          </ul>
                                        </div>
                                        <div class="tab-content">
                                          <div class="tab-pane fade active in" id="owner">
                                            <div class="col-lg-12">
                                              <div class="table-responsive topsp">
                                                <table style=" margin-bottom:0px;" class="table tableWithFloatingHeader">
                                                  <thead>
                                                    <tr>
                                                      <th class="bg_clo">Co Owner Name</th>
                                                      <th class="bg_clo">Father Name</th>
                                                      <th class="bg_clo">DOB</th>
                                                      <th class="bg_clo">Contact No</th>
                                                      <th class="bg_clo">Passport No</th>
                                                      <th class="bg_clo">Relationship with Owner</th>
                                                    </tr>
                                                  </thead>
                                                  <tbody>
                                                    <tr>
                                                      <td width="8%"><input type="text" class="parent_text"></td>
                                                      <td width="8%"><input type="text" class="parent_text"></td>
                                                      <td width="5%"><input type="text" class="parent_text"></td>
                                                      <td width="5%"><input type="text" class="parent_text"></td>
                                                      <td width="5%"><input type="text" class="parent_text"></td>
                                                      <td width="8%"><input type="text" class="parent_text"></td>
                                                    </tr>
                                                  </tbody>
                                                </table>
                                              </div>
                                            </div>
                                          </div>
                                          <div class="tab-pane fade" id="landinfo">
                                            <div class="col-lg-12">
                                              <div class="table-responsive topsp">
                                                <table style=" margin-bottom:0px;" class="table tableWithFloatingHeader">
                                                  <thead>
                                                    <tr>
                                                      <th class="bg_clo">Survey No</th>
                                                      <th class="bg_clo">Patta No</th>
                                                      <th class="bg_clo">Patta Name</th>
                                                      <th class="bg_clo">Area</th>
                                                    </tr>
                                                  </thead>
                                                  <tbody>
                                                    <tr>
                                                      <td width="5%"><input type="text" class="parent_text"></td>
                                                      <td width="5%"><input class="parent_text"></td>
                                                      <td width="10%"><input type="text" class="parent_text"></td>
                                                      <td width="10%"><input class="parent_text" type="text"/></td>
                                                    </tr>
                                                    <tr>
                                                      <td colspan="4"><div class="col-lg-12">
                                                          <div class="col-lg-12 tap_work">
                                                            <ul>
                                                              <li>
                                                                <label>East Side Details</label>
                                                                <input type="text" class="parent_text">
                                                              </li>
                                                              <li>
                                                                <label>West Side Details</label>
                                                                <input type="text" class="parent_text">
                                                              </li>
                                                              <li>
                                                                <label>North Side Details</label>
                                                                <input type="text" class="parent_text">
                                                              </li>
                                                              <li>
                                                                <label>South Side Details</label>
                                                                <input type="text" class="parent_text">
                                                              </li>
                                                            </ul>
                                                          </div>
                                                        </div></td>
                                                    </tr>
                                                </table>
                                              </div>
                                            </div>
                                          </div>
                                        </div>
                                      </div></td>
                                  </tr>
                                </tbody>
                              </table>
                            </div>
                            <!-- Tab panes --> 
                          </div></td>
                      </tr>
                      <!--expand end-->
                      
                    </tbody>
                      </tbody>
                    
                  </table>
                </div>
                <div class="cont_bt col-lg-5 col-lg-offset-7 col-md-9 col-md-offset-3 col-sm-7 col-sm-offset-3 col-xs-7 col-xs-offset-4">
                  <ul>
                    <li><a href="#">Save</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!--accordion end--> 
    </div>
    <!--Comments area-->
    <div class="comments_content" id="comments">
      <div class="comments_content_full">
        <div class="comments_heade">
          <h1>Check List Name</h1>
          <a href="javascript:closeComment();"><i class="fa fa-times"></i></a></div>
        <div class="content_commt">
          <div class="content_detaliss toolbar_ddown">
            <ul>
              <li> <span class="chat_content">
                <div class="avatars">
                  <div class="ava_img"> <img src="<?php echo $this->basePath(); ?>/images/pro_user.png" width="50" height="50p"/></div>
                  <div class="username_detalis">
                    <p>K.Raj kumr</p>
                    <strong>06/01/2015 &nbsp;&nbsp;11.42Am</strong> </div>
                </div>
                <div class="bubble bubble-left"> <strong>Done</strong>
                  <p>AngularJs & Spike Engine are a great team!</p>
                </div>
                </span> </li>
              <li> <span class="chat_content">
                <div class="avatars">
                  <div class="ava_img"> <img src="<?php echo $this->basePath(); ?>/images/pro_user.png" width="50" height="50p"/></div>
                  <div class="username_detalis">
                    <p>K.Raj kumr</p>
                    <strong>06/01/2015 &nbsp;&nbsp;11.42Am</strong> </div>
                </div>
                <div class="bubble bubble-left"> <strong>Done</strong>
                  <p>AngularJs & Spike Engine are a great team!</p>
                </div>
                </span> </li>
              <li> <span class="chat_content">
                <div class="avatars">
                  <div class="ava_img"> <img src="<?php echo $this->basePath(); ?>/images/pro_user.png" width="50" height="50p"/></div>
                  <div class="username_detalis">
                    <p>K.Raj kumr</p>
                    <strong>06/01/2015 &nbsp;&nbsp;11.42Am</strong> </div>
                </div>
                <div class="bubble bubble-left"> <strong>Done</strong>
                  <p>AngularJs & Spike Engine are a great team!</p>
                </div>
                </span> </li>
              <li> <span class="chat_content">
                <div class="avatars">
                  <div class="ava_img"> <img src="<?php echo $this->basePath(); ?>/images/pro_user.png" width="50" height="50p"/></div>
                  <div class="username_detalis">
                    <p>K.Raj kumr</p>
                    <strong>06/01/2015 &nbsp;&nbsp;11.42Am</strong> </div>
                </div>
                <div class="bubble bubble-left"> <strong>Done</strong>
                  <p>AngularJs & Spike Engine are a great team!</p>
                </div>
                </span> </li>
              <li> <span class="chat_content">
                <div class="avatars">
                  <div class="ava_img"> <img src="<?php echo $this->basePath(); ?>/images/pro_user.png" width="50" height="50p"/></div>
                  <div class="username_detalis">
                    <p>K.Raj kumr</p>
                    <strong>06/01/2015 &nbsp;&nbsp;11.42Am</strong> </div>
                </div>
                <div class="bubble bubble-left"> <strong>Done</strong>
                  <p>AngularJs & Spike Engine are a great team!</p>
                </div>
                </span> </li>
            </ul>
          </div>
        </div>
        <div class="comments_footer">
          <ul>
            <li>
              <div class="select-style select-status">
                <select onchange="return MainRateUpdate(this)" id="analrate" name="analrate">
                  <option value="L">Select Status </option>
                  <option value="M">Done </option>
                  <option value="A">Progress</option>
                </select>
              </div>
            </li>
            <li>
              <textarea class="commentstext" placeholder="Comment....."></textarea>
            </li>
            <li>
              <input type="submit" value="Submit">
            </li>
          </ul>
        </div>
      </div>
    </div>
    <!--Comments area--> 
  </div>
</div>

<!--table expand end--> 
<!--datepicker--> 
<script type="text/javascript">


  function showComments(e, id) {
        e.preventDefault();
        $('#comments').addClass('show');
    }

    function closeComment() {
        $('#comments').removeClass('show');
    }

</script> 
<!--datepicker--> 

