<!--STYLE-->
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css';?>"/>
<!--content-->
<style>
.progress {
	margin-left: 10px;
	height:12px !important;
}
.progress-bar {
	line-height:14px !important;
	font-size:12px !important;
	color:#fff!important;
	font-weight:600 !important;
}
</style>
<script type="text/javascript">
$(document).ready(function() {
	$(".lightGallery").lightGallery({
		loop             : true 	
	});
});
</script>

<div class="content_wrapper padlr0">
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-12 clear">
      <h1>Land Bank - Register</h1>
    </div>
    <!--form start-->
    <div class="col-lg-12 top_ct" >
      <div class="col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-4 col-sm-offset-0">
        <div class="form-group frms">
          <select name="named[]" id="unit_type" class="form-control selectpicker show-tick" data-size="5" title="Check List Type..">
            <option>Select Option</option>
            <option>All</option>
            <option>First Level </option>
            <option>Last Level </option>
          </select>
        </div>
      </div>
      <div class="col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-4 col-sm-offset-0">
        <div class="form-group">
          <input type="text" name="lead_date" class="form-control lbl_move" label="Email Address" />
          <a href="#" class="searchs" title="Search"><span class="glyphicon glyphicon-search"></span></a> </div>
      </div>
      
      <!--form end--> 
      
      <!--content--> 
      <!--<div class="col-lg-12 clear">
        <div class="land-regi">
          <div class="col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-4 col-sm-offset-0" style="padding:0px !important;">
            <div class="site-img sliderarea lightGallery"> 
              <div class="pro-land effects-pro pn" data-src="<?php echo $this->basePath(); ?>/images/test_img2.jpg" data-sub-html="#html1">
              		<div class="img" style="background-image:url('<?php echo $this->basePath(); ?>/images/test_img2.jpg');"></div>
                	<div class="read-pl"> <a class="infos" href="#myModal" data-toggle="modal"></a></div>
              </div>
              <div class="pro-land effects-pro pn" data-src="<?php echo $this->basePath(); ?>/images/flat-img2.jpg" data-sub-html="#html2">
              		<div class="img" style="background-image:url('<?php echo $this->basePath(); ?>/images/flat-img2.jpg');"></div>
                	<div class="read-pl"> <a class="infos" href="#myModal" data-toggle="modal"></a></div>
              </div>
              <div class="pro-land effects-pro pn" data-src="<?php echo $this->basePath(); ?>/images/flat-img1.jpg" data-sub-html="#html2">
              		<div class="img" style="background-image:url('<?php echo $this->basePath(); ?>/images/flat-img1.jpg');"></div>
                	<div class="read-pl"> <a class="infos" href="#myModal" data-toggle="modal"></a></div>
              </div>
            </div>
          </div>
          <div class="col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-4 col-sm-offset-0">
           <span class="info-dets">
            <h1>General Info </h1>
            <ul>
              <li>
                <label>Enquiry No</label>
                <span>EQ2358</span></li>
              <li>
                <label>Date</label>
                <span>12/12/215</span></li>
              <li>
                <label>Source</label>
                <span>Arun Kumar</span></li>
              <li>
                <label>Price</label>
                <span>Rs 1.75 Crores</span></li>
              <li>
                <label>Total Area</label>
                <span>2,00,000 Sft</span></li>
                
            </ul>
         <a href="#" class="read-mr">Read more <i class="fa fa-caret-right"></i></a>
            </span>    </div>
          <div class="col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-4 col-sm-offset-0"> <span class="info-dets" style=" border:none;">
            <h1>Status</h1>
            <div class="progress clear">
              <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:40%"> 40% </div>
            </div>
            <h1>Location</h1>
            <ul>
              <li> <strong> Egmore, PH Road, Chennai - Central</strong></li>
              <li> <strong>Phone No : 044 2569871</strong></li>
              <li> <strong>Cell No : +91 9786828238</strong></li>
            </ul>
            <ul style="padding:0px;">
              <li><a href="#" class="mapss"><i class="fa fa-map-marker" style="color:#999; font-size:18px !important;"></i> Map</a></li>
            </ul>
            </span> </div>
        </div>
          
      </div>-->
      
      <div class="col-lg-12 clear">
        <div class="land-regi">
          <div class="col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-4 col-sm-offset-0" style="padding:0px !important;">
            <div class="imgs" style="background-image:url('<?php echo $this->basePath(); ?>/images/test_img2.jpg'); min-height:250px;" ></div>
          </div>
          <div class="col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-4 col-sm-offset-0"> <span class="info-dets">
            <h1>General Info </h1>
            <ul>
              <li>
                <label>Enquiry No</label>
                <span>EQ2358</span></li>
              <li>
                <label>Date</label>
                <span>12/12/215</span></li>
              <li>
                <label>Source</label>
                <span>Arun Kumar</span></li>
              <li>
                <label>Price</label>
                <span>Rs 1.75 Crores</span></li>
              <li>
                <label>Total Area</label>
                <span>2,00,000 Sft</span></li>
            </ul>
            <a href="#" class="read-mr">Read more <i class="fa fa-caret-right"></i></a> </span> </div>
          <div class="col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-4 col-sm-offset-0"> <span class="info-dets" style=" border:none;">
            <h1>Status</h1>
            <div class="progress clear">
              <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:40%"> 40% </div>
            </div>
            <h1>Location</h1>
            <ul>
              <li> <strong> Egmore, PH Road, Chennai - Central</strong></li>
              <li> <strong>Phone No : 044 2569871</strong></li>
              <li> <strong>Cell No : +91 9786828238</strong></li>
            </ul>
            <ul style="padding:0px;">
              <li><a href="#" class="mapss"><i class="fa fa-map-marker" style="color:#999; font-size:18px !important;"></i> Map</a></li>
            </ul>
            </span> </div>
        </div>
      </div>
      <!--content end-->
      <div class="clearfix"></div>
      <!--Tab content-->
      
      <div class="col-lg-12">
        <div class="tab-contants clear">
          <ul class="nav nav-tabs" id="maincontent" role="tablist">
            <li class="active"><a href="#enquiry" role="tab" data-toggle="tab">Enquiry Detalis</a></li>
            <li class="re-tab"><a href="#initial" role="tab" data-toggle="tab">Initial Feasibility</a></li>
            <li class="re-tab"><a href="#business" role="tab" data-toggle="tab">Business Feasibility</a></li>
            <li class="re-tab"><a href="#duediligence" role="tab" data-toggle="tab">Duediligence</a></li>
            <li class="re-tab"><a href="#finalisation" role="tab" data-toggle="tab">Finalisation</a></li>
            <!--drop down buton-->
            <li class="dropdown mor-tab"> <a href="#" id="myTabDrop1" class="dropdown-toggle" data-toggle="dropdown">More<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu" aria-labelledby="myTabDrop1">
                <li><a href="#business" role="tab" data-toggle="tab">Business Feasibility</a></li>
                <li><a href="#duediligence" role="tab" data-toggle="tab">Duediligence</a></li>
                <li><a href="#finalisation" role="tab" data-toggle="tab">Finalisation</a></li>
              </ul>
            </li>
            <!--drop down buton-->
          </ul>
          <div class="tab-content">
            <div class="tab-pane fade in active" id="enquiry">
              <div class="tabcont">
                <ul>
                  <li>
                    <label>Enquiry No</label>
                    <span>EQ2358</span></li>
                  <li>
                    <label>Date</label>
                    <span>12/12/215</span></li>
                  <li>
                    <label>Source</label>
                    <span>Arun Kumar</span></li>
                  <li>
                    <label>Price</label>
                    <span>Rs 1.75 Crores</span></li>
                  <li>
                    <label>Total Area</label>
                    <span>2,00,000 Sft</span></li>
                </ul>
                <a href="#" class="read-mr">Read more <i class="fa fa-caret-right"></i></a>
                </ul>
              </div>
            </div>
            <div class="tab-pane fade" id="initial">
              <p>Profile Content : ...</p>
            </div>
            <div class="tab-pane fade" id="business">
              <p>Profile Content : ...</p>
            </div>
            <div class="tab-pane fade" id="duediligence">
              <p>Profile Content : ...</p>
            </div>
            <div class="tab-pane fade" id="finalisation">
              <p>Profile Content : ...</p>
            </div>
          </div>
        </div>
      </div>
      
      <!--Tab content end--> 
      
    </div>
    <div class="clearfix"></div>
  </div>
</div>

<!--slider top head-->
<div id="html1" style="display:none">
  <div class="custom-html">
    <h4>Gallery 1</h4>
    <p>Provide custom html inside data-sub-html attribute or just id or class name of an object(div) which contain your html.</p>
  </div>
</div>
<div id="html2" style="display:none">
  <div class="custom-html">
    <h4>Gallery 2</h4>
    <p>Local videos content will be taken from data-html attribute..</p>
  </div>
</div>
<div id="html3" style="display:none">
  <div class="custom-html">
    <h4>Gallery 3</h4>
    <p>if you set attribute data-iframe="true" .. src will be desplayed in an iframe</p>
  </div>
</div>
<div id="html4" style="display:none">
  <div class="custom-html">
    <h4>Gallery 4</h4>
    <p>Local videos content will be taken from data-html attribute..</p>
  </div>
</div>
<!--slider top head-->