<!--STYLE-->
<?php /*?><link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css';?>"/><?php */?>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/amcharts/landbank-chart.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/amcharts/landbank-lightchart.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/amcharts/landbank-serialchart.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/amcharts/landbank-piechart.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/amcharts/landbank-radarchart.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/amcharts/landbank-xychart.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/Highcharts-4.2.3/js/highcharts.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/Highcharts-4.2.3/js/modules/exporting.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/Highcharts-4.2.3/js/modules/funnel.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/jquery.easy-ticker.js"></script>


<style>
#land-chart1, #land-chart2, #land-chart3, #land-chart4, #land-chart5, #land-chart6, #land-chart7, #land-chart8, #land-chart9, #land-chart10, #land-chart11, #land-chart12 {
	width : 100% !important;
	height : 400px !important;
	font-size : 11px;
}
#highcharts-0, #highcharts-11, #highcharts-3, #highcharts-25 {
	width:100% !important
}
.top_rfc {
	background:#fff;
	padding:5px 0;
	margin-bottom:20px;
	box-shadow: 1px 1px 0 0 rgba(50, 50, 50, 0.23);
}
.rfc-primary {
	border-bottom:2px solid #337ab7 !important;
	background:#d9edf7 !important;
}
 .panel1:hover::before, .panel1:focus::before, .panel1:active::before {
 left: 0;
 right: 0;
}
.panel1::before {
 background: #2098d1 none repeat scroll 0 0;
 content: "";
 height: 2px;
 left: 50%;
 position: absolute;
 right: 50%;
 top: 0;
 transition-duration: 0.3s;
 transition-property: left, right;
 transition-timing-function: ease-out;
 z-index: -1;
}
.panel1 {
	backface-visibility: hidden;
	box-shadow: 0 0 1px rgba(0, 0, 0, 0);
	display: inline-block;
	overflow: hidden;
	position: relative;
	transform: translateZ(0px);
	vertical-align: middle;
}
.panel {
	background-color: #fff;
	border: 1px solid #e8e8e8;
	border-radius: 4px;
	box-shadow: 0 1px 1px rgba(0, 0, 0, 0.05);
	margin:20px 0 30px 0;
	box-shadow: 1px 1px 0 0 rgba(50, 50, 50, 0.23);
	width:100%;
}
.rfc-primary > .panel-heading {
	border-bottom:2px solid #337ab7;
	background:none;
	color: #000 !important;
}
.panel-heading {
	border-bottom: 1px solid transparent;
	border-top-left-radius: 3px;
	border-top-right-radius: 3px;
	padding: 10px 15px;
}
.pull-left {
	float: left !important;
}
.pull-right {
	float: right;
}
.panel-green {
	border-bottom:2px solid #5cb85c;
	background:#dff0d8;
}
.panel-red {
	border-bottom:2px solid #d9534f;
	background:#f2dede;
}
.rfc-primary > .panel-heading {
	color: #fff;
}
.huge {
	font-size: 40px;
	color:#000;
}
.text-right {
	font-size:15px;
	color:#666;
	font-family: "Open Sans", sans-serif;
}
.panel-yellow {
	border-bottom:2px solid #f0ad4e;
	background:#fcf8e3;
}
.panel-body {
/*border:1px solid #e7e7e7;
	box-shadow: 1px 1px 0 0 rgba(50, 50, 50, 0.23);*/
}
.panel1 > .panel-heading {
	background:none;
	border:none
}
.panel-heading {
	border: 1px solid #ddd;
	border-top-left-radius: 3px;
	border-top-right-radius: 3px;
	color: #06528c;
	font-size: 20px;
	padding: 10px 15px;
	background:#fff;
	transition: margin 0.5s ease-out 0s;
}
.fa-5x {
	color: #fff;
	font-size: 55px;
	line-height: 69px;
	margin-left: 18px;
	overflow: hidden;
	transition: all 0.3s ease 0s;
}
.fa-5x:hover {
	-moz-transform: scale(1.7);
	-webkit-transform: scale(1.7);
	transform: scale(1.7);
}
.circle-icon {
	width:70px;
	height:70px;
	border-radius:100%;
	background:#337ab7
}
.circle-icon1 {
	background:#5cb85c
}
.circle-icon2 {
	background:#f0ad4e
}
.circle-icon3 {
	background:#d9534f
}
/*-----message list--*/
.message-list {
	list-style-type: none;
	margin: 0;
	padding: 0;
}
.flat-blue a {
	color: #363c46;
}
.message-list > li {
	border-bottom: 1px dotted #eee;
	padding:10px;
}
.message-list > li .profile-img {
	height: 60px;
	width: 60px;
	border: 2px solid rgba(0, 112, 255, 0.4);
	border-radius:50%;
}
.message-list > li .profile-img:hover {
	border: 2px solid rgba(0, 112, 255, 0.9);
}
.pull-left {
	float: left;
}
.message-list > li > .message-block {
	min-height: 60px;
	padding-left: 70px;
}
.message-list > li > .message-block .username {
	font-size: 12px;
	font-weight: bold;
	color:#333;
}
.message-list > li > .message-block .message-datetime {
	color: #aaa;
	font-size: 10px;
}
.message-list > li > .message-block .message {
	font-size: 12px;
	color:#333;
}
/*--icon animation css--*/

.chart-icon {
	width:30px;
}
.chart-scale {
	stroke: #173753;
}
.chart-line {
	transform-origin: bottom;
}
.chart-icon .chart-line:first-child, .chart-icon:focus .chart-line:first-child, .chart-icon:active .chart-line:first-child {
	animation: 0.4s cubic-bezier(0.49, 0.86, 0.59, 0.95) infinite chartlines;
}
.chart-icon .chart-line:nth-child(2), .chart-icon:focus .chart-line:nth-child(2), .chart-icon:active .chart-line:nth-child(2) {
 animation: 1.22s cubic-bezier(0.49, 0.86, 0.59, 0.95) infinite reverse chartlines;
}
.chart-icon .chart-line:nth-child(3), .chart-icon:focus .chart-line:nth-child(3), .chart-icon:active .chart-line:nth-child(3) {
 animation: 0.94s cubic-bezier(0.49, 0.86, 0.59, 0.95) infinite reverse chartlines;
}
.chart-icon .chart-line:nth-child(4), .chart-icon:focus .chart-line:nth-child(4), .chart-icon:active .chart-line:nth-child(4) {
 animation: 1.70s cubic-bezier(0.49, 0.86, 0.59, 0.95) infinite chartlines;
}
 @keyframes chartlines {
 0% {
 transform: scaleY(1.10);
}
 32% {
 transform: scaleY(0.85);
}
 79% {
 transform: scaleY(0.12);
}
 100% {
 transform: scaleY(0.50);
}
}
/*--icon animation css--*/
</style>
<!--content-->

<div class="content_wrapper padlr0">
  <div class="container-fluid padlr0">
    <div class="col-lg-12">
      <h1 class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0">Dashboard</h1>
      
      <!--Short by-->
      <div class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0" style="margin-bottom:10px; padding-right:0px !important;">
        <label class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0 control-label text-right">Select by</label>
        <div class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0" style="padding-right:0px !important;">
          <select class="form-control single_dropdown lbl_move sortoption" style="width:100%;">
            <option></option>
            <option selected>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
            <option>6</option>
          </select>
        </div>
        
        <!--Short by end--> 
      </div>
      
      <!--three feild start-->
      <div class="col-sm-3">
        <div class="panel panel1 rfc-primary">
          <div class="panel-heading pnl-overflow ">
            <div class="row">
              <div class="col-xs-3"> <i style="color:#337ab7"class="fa fa-comments fa-5x"></i> </div>
              <div class="col-xs-9 text-right">
                <div class="huge">26</div>
                <div>New Comments!</div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="panel panel1 panel-green">
          <div class="panel-heading pnl-overflow ">
            <div class="row">
              <div class="col-xs-3"> <i style="color:#5cb85c"class="fa fa-tasks fa-5x"></i> </div>
              <div class="col-xs-9 text-right">
                <div class="huge">12</div>
                <div>New Tasks!</div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="panel panel1 panel-yellow">
          <div class="panel-heading  pnl-overflow ">
            <div class="row">
              <div class="col-xs-3"> <i style="color:#f0ad4e"class="fa fa-shopping-cart fa-5x"></i> </div>
              <div class="col-xs-9 text-right">
                <div class="huge">124</div>
                <div>New Orders!</div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="panel panel1 panel-red">
          <div class="panel-heading pnl-overflow ">
            <div class="row">
              <div class="col-xs-3"> <i style="color:#d9534f"class="fa fa-support fa-5x"></i> </div>
              <div class="col-xs-9 text-right">
                <div class="huge">13</div>
                <div>Support Tickets</div>
              </div>
            </div>
          </div>
        </div>
        
        <!--box end--> 
       
      </div>
      <!--box end--> 
    </div>
     <div class="clear clearfix"></div>
    <!--chart1 start-->
    <div class="col-lg-12">
      <header class="panel-heading">
        <svg
     class="chart-icon"
     version="1.1"
     baseProfile="full"
     viewBox="0 0 100 100"
     xmlns="http://www.w3.org/2000/svg">
          <line stroke="#088208" x1="22.5" y1="91" x2="22.5" y2="62" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#f57b04" x1="42.5" y1="91" x2="42.5" y2="37" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#0600ff" x1="62.5" y1="91" x2="62.5" y2="46" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#ff0000" x1="82.5" y1="91" x2="82.5" y2="23" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#48ff00"  x1="5" y1="95" x2="5" y2="5" stroke-width="5" class="chart-scale" />
          <line stroke="#ff3000" x1="2.5" y1="95" x2="100" y2="95" stroke-width="5" class="chart-scale" />
        </svg>
        &nbsp;&nbsp;Total No of Enquiries</header>
      <div id="land-chart1" class="top_rfc"></div>
    </div>
    <!--chart2 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <svg
     class="chart-icon"
     version="1.1"
     baseProfile="full"
     viewBox="0 0 100 100"
     xmlns="http://www.w3.org/2000/svg">
          <line stroke="#088208" x1="22.5" y1="91" x2="22.5" y2="62" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#f57b04" x1="42.5" y1="91" x2="42.5" y2="37" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#0600ff" x1="62.5" y1="91" x2="62.5" y2="46" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#ff0000" x1="82.5" y1="91" x2="82.5" y2="23" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#48ff00"  x1="5" y1="95" x2="5" y2="5" stroke-width="5" class="chart-scale" />
          <line stroke="#ff3000" x1="2.5" y1="95" x2="100" y2="95" stroke-width="5" class="chart-scale" />
        </svg>
        &nbsp; &nbsp;Total No of Finalise</header>
      <div id="land-chart2" class="top_rfc"></div>
    </div>
    <!--chart2 complete--> 
    <!--chart3 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <svg
     class="chart-icon"
     version="1.1"
     baseProfile="full"
     viewBox="0 0 100 100"
     xmlns="http://www.w3.org/2000/svg">
          <line stroke="#088208" x1="22.5" y1="91" x2="22.5" y2="62" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#f57b04" x1="42.5" y1="91" x2="42.5" y2="37" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#0600ff" x1="62.5" y1="91" x2="62.5" y2="46" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#ff0000" x1="82.5" y1="91" x2="82.5" y2="23" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#48ff00"  x1="5" y1="95" x2="5" y2="5" stroke-width="5" class="chart-scale" />
          <line stroke="#ff3000" x1="2.5" y1="95" x2="100" y2="95" stroke-width="5" class="chart-scale" />
        </svg>
        &nbsp; &nbsp;Total No of Conceptions</header>
      <div id="land-chart3" class="top_rfc"></div>
    </div>
    <!--chart4 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <svg
     class="chart-icon"
     version="1.1"
     baseProfile="full"
     viewBox="0 0 100 100"
     xmlns="http://www.w3.org/2000/svg">
          <line stroke="#088208" x1="22.5" y1="91" x2="22.5" y2="62" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#f57b04" x1="42.5" y1="91" x2="42.5" y2="37" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#0600ff" x1="62.5" y1="91" x2="62.5" y2="46" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#ff0000" x1="82.5" y1="91" x2="82.5" y2="23" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#48ff00"  x1="5" y1="95" x2="5" y2="5" stroke-width="5" class="chart-scale" />
          <line stroke="#ff3000" x1="2.5" y1="95" x2="100" y2="95" stroke-width="5" class="chart-scale" />
        </svg>
        &nbsp; &nbsp;Total No of Projects</header>
      <div id="land-chart4" class="top_rfc"></div>
    </div>
    <!--chart4 complete--> 
    <!--chart5 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <svg
     class="chart-icon"
     version="1.1"
     baseProfile="full"
     viewBox="0 0 100 100"
     xmlns="http://www.w3.org/2000/svg">
          <line stroke="#088208" x1="22.5" y1="91" x2="22.5" y2="62" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#f57b04" x1="42.5" y1="91" x2="42.5" y2="37" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#0600ff" x1="62.5" y1="91" x2="62.5" y2="46" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#ff0000" x1="82.5" y1="91" x2="82.5" y2="23" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#48ff00"  x1="5" y1="95" x2="5" y2="5" stroke-width="5" class="chart-scale" />
          <line stroke="#ff3000" x1="2.5" y1="95" x2="100" y2="95" stroke-width="5" class="chart-scale" />
        </svg>
        &nbsp; &nbsp;City wise Projects</header>
      <div id="land-chart5" class="top_rfc"></div>
    </div>
    <!--chart6 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <svg
     class="chart-icon"
     version="1.1"
     baseProfile="full"
     viewBox="0 0 100 100"
     xmlns="http://www.w3.org/2000/svg">
          <line stroke="#088208" x1="22.5" y1="91" x2="22.5" y2="62" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#f57b04" x1="42.5" y1="91" x2="42.5" y2="37" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#0600ff" x1="62.5" y1="91" x2="62.5" y2="46" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#ff0000" x1="82.5" y1="91" x2="82.5" y2="23" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#48ff00"  x1="5" y1="95" x2="5" y2="5" stroke-width="5" class="chart-scale" />
          <line stroke="#ff3000" x1="2.5" y1="95" x2="100" y2="95" stroke-width="5" class="chart-scale" />
        </svg>
        &nbsp; &nbsp;Enquiry Vs Finalise</header>
      <div id="land-chart6" class="top_rfc"></div>
    </div>
    <!--chart6 complete--> 
    <!--chart7 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <svg
     class="chart-icon"
     version="1.1"
     baseProfile="full"
     viewBox="0 0 100 100"
     xmlns="http://www.w3.org/2000/svg">
          <line stroke="#088208" x1="22.5" y1="91" x2="22.5" y2="62" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#f57b04" x1="42.5" y1="91" x2="42.5" y2="37" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#0600ff" x1="62.5" y1="91" x2="62.5" y2="46" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#ff0000" x1="82.5" y1="91" x2="82.5" y2="23" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#48ff00"  x1="5" y1="95" x2="5" y2="5" stroke-width="5" class="chart-scale" />
          <line stroke="#ff3000" x1="2.5" y1="95" x2="100" y2="95" stroke-width="5" class="chart-scale" />
        </svg>
        &nbsp; &nbsp;Project Type</header>
      <div id="land-chart7" class="top_rfc"></div>
    </div>
    
    <!--chart7 complete--> 
    <!--chart8 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <svg
     class="chart-icon"
     version="1.1"
     baseProfile="full"
     viewBox="0 0 100 100"
     xmlns="http://www.w3.org/2000/svg">
          <line stroke="#088208" x1="22.5" y1="91" x2="22.5" y2="62" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#f57b04" x1="42.5" y1="91" x2="42.5" y2="37" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#0600ff" x1="62.5" y1="91" x2="62.5" y2="46" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#ff0000" x1="82.5" y1="91" x2="82.5" y2="23" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#48ff00"  x1="5" y1="95" x2="5" y2="5" stroke-width="5" class="chart-scale" />
          <line stroke="#ff3000" x1="2.5" y1="95" x2="100" y2="95" stroke-width="5" class="chart-scale" />
        </svg>
        &nbsp; &nbsp;Sale Type</header>
      <div id="land-chart8" class="top_rfc"></div>
    </div>
    <!--chart8 complete--> 
    <!--chart9 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <svg
     class="chart-icon"
     version="1.1"
     baseProfile="full"
     viewBox="0 0 100 100"
     xmlns="http://www.w3.org/2000/svg">
          <line stroke="#088208" x1="22.5" y1="91" x2="22.5" y2="62" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#f57b04" x1="42.5" y1="91" x2="42.5" y2="37" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#0600ff" x1="62.5" y1="91" x2="62.5" y2="46" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#ff0000" x1="82.5" y1="91" x2="82.5" y2="23" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#48ff00"  x1="5" y1="95" x2="5" y2="5" stroke-width="5" class="chart-scale" />
          <line stroke="#ff3000" x1="2.5" y1="95" x2="100" y2="95" stroke-width="5" class="chart-scale" />
        </svg>
        &nbsp; &nbsp;Source Type</header>
      <div id="land-chart9" class="top_rfc"></div>
    </div>
    <!--chart9 complete--> 
    <!--chart10 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <svg
     class="chart-icon"
     version="1.1"
     baseProfile="full"
     viewBox="0 0 100 100"
     xmlns="http://www.w3.org/2000/svg">
          <line stroke="#088208" x1="22.5" y1="91" x2="22.5" y2="62" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#f57b04" x1="42.5" y1="91" x2="42.5" y2="37" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#0600ff" x1="62.5" y1="91" x2="62.5" y2="46" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#ff0000" x1="82.5" y1="91" x2="82.5" y2="23" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#48ff00"  x1="5" y1="95" x2="5" y2="5" stroke-width="5" class="chart-scale" />
          <line stroke="#ff3000" x1="2.5" y1="95" x2="100" y2="95" stroke-width="5" class="chart-scale" />
        </svg>
        &nbsp; &nbsp;Enquiry Pending</header>
      <div id="land-chart10" class="top_rfc"></div>
    </div>
    <!--chart11 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <svg
     class="chart-icon"
     version="1.1"
     baseProfile="full"
     viewBox="0 0 100 100"
     xmlns="http://www.w3.org/2000/svg">
          <line stroke="#088208" x1="22.5" y1="91" x2="22.5" y2="62" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#f57b04" x1="42.5" y1="91" x2="42.5" y2="37" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#0600ff" x1="62.5" y1="91" x2="62.5" y2="46" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#ff0000" x1="82.5" y1="91" x2="82.5" y2="23" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#48ff00"  x1="5" y1="95" x2="5" y2="5" stroke-width="5" class="chart-scale" />
          <line stroke="#ff3000" x1="2.5" y1="95" x2="100" y2="95" stroke-width="5" class="chart-scale" />
        </svg>
        &nbsp; &nbsp;Alerts</header>
      <div id="land-chart11" class="top_rfc"></div>
    </div>
    <!--chart12 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <svg
     class="chart-icon"
     version="1.1"
     baseProfile="full"
     viewBox="0 0 100 100"
     xmlns="http://www.w3.org/2000/svg">
          <line stroke="#088208" x1="22.5" y1="91" x2="22.5" y2="62" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#f57b04" x1="42.5" y1="91" x2="42.5" y2="37" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#0600ff" x1="62.5" y1="91" x2="62.5" y2="46" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#ff0000" x1="82.5" y1="91" x2="82.5" y2="23" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#48ff00"  x1="5" y1="95" x2="5" y2="5" stroke-width="5" class="chart-scale" />
          <line stroke="#ff3000" x1="2.5" y1="95" x2="100" y2="95" stroke-width="5" class="chart-scale" />
        </svg>
        &nbsp; &nbsp;Reminders</header>
      <div id="land-chart12" class="top_rfc"></div>
    </div>
    <!--chart5 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <svg
     class="chart-icon"
     version="1.1"
     baseProfile="full"
     viewBox="0 0 100 100"
     xmlns="http://www.w3.org/2000/svg">
          <line stroke="#088208" x1="22.5" y1="91" x2="22.5" y2="62" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#f57b04" x1="42.5" y1="91" x2="42.5" y2="37" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#0600ff" x1="62.5" y1="91" x2="62.5" y2="46" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#ff0000" x1="82.5" y1="91" x2="82.5" y2="23" stroke-width="10" stroke-linecap="butt" class="chart-line" />
          <line stroke="#48ff00"  x1="5" y1="95" x2="5" y2="5" stroke-width="5" class="chart-scale" />
          <line stroke="#ff3000" x1="2.5" y1="95" x2="100" y2="95" stroke-width="5" class="chart-scale" />
        </svg>
        &nbsp; &nbsp;Latest News</header>
      <div class="top_rfc" style="height:400px !important">
        <div class="panel-body">
          <ul class="message-list" id="vertical-ticker1">
            <li> <img class="profile-img pull-left" src="<?php echo $this->basePath(); ?>/images/flwup_proimg.png">
              <div class="message-block">
                <div> <span class="username">Tui2Tone</span> <span class="message-datetime">12 min ago</span> </div>
                <div class="message">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales.</div>
              </div>
            </li>
            <li> <img class="profile-img pull-left" src="<?php echo $this->basePath(); ?>/images/flwup_proimg.png">
              <div class="message-block">
                <div> <span class="username">Tui2Tone</span> <span class="message-datetime">15 min ago</span> </div>
                <div class="message">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales.  Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales.</div>
              </div>
            </li>
            <li> <img class="profile-img pull-left" src="<?php echo $this->basePath(); ?>/images/flwup_proimg.png">
              <div class="message-block">
                <div> <span class="username">Tui2Tone</span> <span class="message-datetime">15 min ago</span> </div>
                <div class="message">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales.  Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales.</div>
              </div>
            </li>
            <li> <img class="profile-img pull-left" src="<?php echo $this->basePath(); ?>/images/flwup_proimg.png">
              <div class="message-block">
                <div> <span class="username">Tui2Tone</span> <span class="message-datetime">1 day ago</span> </div>
                <div class="message">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales.</div>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<!--datepicker--> 
<!--chart1 start--> 

<script>
var chart = AmCharts.makeChart("land-chart1", {
    "theme": "light",
    "type": "serial",
    "dataProvider": [{
        "country": "USA",
        "year2004": 3.5,
        "year2005": 4.2
    }, {
        "country": "UK",
        "year2004": 1.7,
        "year2005": 3.1
    }, {
        "country": "Canada",
        "year2004": 2.8,
        "year2005": 2.9
    }, {
        "country": "Japan",
        "year2004": 2.6,
        "year2005": 2.3
    }, {
        "country": "France",
        "year2004": 1.4,
        "year2005": 2.1
    }, {
        "country": "Brazil",
        "year2004": 2.6,
        "year2005": 4.9
    }],
    "valueAxes": [{
        "unit": "%",
        "position": "left",
        "title": "GDP growth rate",
    }],
    "startDuration": 1,
    "graphs": [{
        "balloonText": "GDP grow in [[category]] (2004): <b>[[value]]</b>",
        "fillAlphas": 0.9,
        "lineAlpha": 0.2,
        "title": "2004",
        "type": "column",
        "valueField": "year2004"
    }, {
        "balloonText": "GDP grow in [[category]] (2005): <b>[[value]]</b>",
        "fillAlphas": 0.9,
        "lineAlpha": 0.2,
        "title": "2005",
        "type": "column",
        "clustered":false,
        "columnWidth":0.5,
        "valueField": "year2005"
    }],
    "plotAreaFillAlphas": 0.1,
    "categoryField": "country",
    "categoryAxis": {
        "gridPosition": "start"
    },
    "export": {
    	"enabled": true
     }

});
</script> 
<!--chart2 start--> 
<script>
var chart = AmCharts.makeChart( "land-chart2", {
  "type": "serial",
  "theme": "light",
  "depth3D": 20,
  "angle": 30,
  "legend": {
    "horizontalGap": 10,
    "useGraphSettings": true,
    "markerSize": 10
  },
  "dataProvider": [ {
    "year": 2003,
    "europe": 2.5,
    "namerica": 2.5,
    "asia": 2.1,
    "lamerica": 1.2,
    "meast": 0.2,
    "africa": 0.1
  }, {
    "year": 2004,
    "europe": 2.6,
    "namerica": 2.7,
    "asia": 2.2,
    "lamerica": 1.3,
    "meast": 0.3,
    "africa": 0.1
  }, {
    "year": 2005,
    "europe": 2.8,
    "namerica": 2.9,
    "asia": 2.4,
    "lamerica": 1.4,
    "meast": 0.3,
    "africa": 0.1
  } ],
  "valueAxes": [ {
    "stackType": "regular",
    "axisAlpha": 0,
    "gridAlpha": 0
  } ],
  "graphs": [ {
    "balloonText": "<b>[[title]]</b><br><span style='font-size:14px'>[[category]]: <b>[[value]]</b></span>",
    "fillAlphas": 0.8,
    "labelText": "[[value]]",
    "lineAlpha": 0.3,
    "title": "Europe",
    "type": "column",
    "color": "#000000",
    "valueField": "europe"
  }, {
    "balloonText": "<b>[[title]]</b><br><span style='font-size:14px'>[[category]]: <b>[[value]]</b></span>",
    "fillAlphas": 0.8,
    "labelText": "[[value]]",
    "lineAlpha": 0.3,
    "title": "North America",
    "type": "column",
    "color": "#000000",
    "valueField": "namerica"
  }, {
    "balloonText": "<b>[[title]]</b><br><span style='font-size:14px'>[[category]]: <b>[[value]]</b></span>",
    "fillAlphas": 0.8,
    "labelText": "[[value]]",
    "lineAlpha": 0.3,
    "title": "Asia-Pacific",
    "type": "column",
    "newStack": true,
    "color": "#000000",
    "valueField": "asia"
  }, {
    "balloonText": "<b>[[title]]</b><br><span style='font-size:14px'>[[category]]: <b>[[value]]</b></span>",
    "fillAlphas": 0.8,
    "labelText": "[[value]]",
    "lineAlpha": 0.3,
    "title": "Latin America",
    "type": "column",
    "color": "#000000",
    "valueField": "lamerica"
  }, {
    "balloonText": "<b>[[title]]</b><br><span style='font-size:14px'>[[category]]: <b>[[value]]</b></span>",
    "fillAlphas": 0.8,
    "labelText": "[[value]]",
    "lineAlpha": 0.3,
    "title": "Middle-East",
    "type": "column",
    "color": "#000000",
    "valueField": "meast"
  }, {
    "balloonText": "<b>[[title]]</b><br><span style='font-size:14px'>[[category]]: <b>[[value]]</b></span>",
    "fillAlphas": 0.8,
    "labelText": "[[value]]",
    "lineAlpha": 0.3,
    "title": "Africa",
    "type": "column",
    "color": "#000000",
    "valueField": "africa"
  } ],
  "categoryField": "year",
  "categoryAxis": {
    "gridPosition": "start",
    "axisAlpha": 0,
    "gridAlpha": 0,
    "position": "left"
  },
  "export": {
    "enabled": true
  }

} );
jQuery( '.chart-input' ).off().on( 'input change', function() {
  var property = jQuery( this ).data( 'property' );
  var target = chart;
  chart.startDuration = 0;

  if ( property == 'topRadius' ) {
    target = chart.graphs[ 0 ];
    if ( this.value == 0 ) {
      this.value = undefined;
    }
  }

  target[ property ] = this.value;
  chart.validateNow();
} );
</script> 
<!--chart3 start--> 
<script>
var chart = AmCharts.makeChart("land-chart3", {
    "type": "serial",
    "theme": "light",
    "marginRight": 80,
    "marginTop": 17,
    "autoMarginOffset": 20,
    "dataProvider": [{
        "date": "2012-03-01",
        "price": 20
    }, {
        "date": "2012-03-02",
        "price": 75
    }, {
        "date": "2012-03-03",
        "price": 15
    }, {
        "date": "2012-03-04",
        "price": 75
    }, {
        "date": "2012-03-05",
        "price": 158
    }, {
        "date": "2012-03-06",
        "price": 57
    }, {
        "date": "2012-03-07",
        "price": 107
    }, {
        "date": "2012-03-08",
        "price": 89
    }, {
        "date": "2012-03-09",
        "price": 75
    }, {
        "date": "2012-03-10",
        "price": 132
    }, {
        "date": "2012-03-11",
        "price": 158
    }, {
        "date": "2012-03-12",
        "price": 56
    }, {
        "date": "2012-03-13",
        "price": 169
    }, {
        "date": "2012-03-14",
        "price": 24
    }, {
        "date": "2012-03-15",
        "price": 147
    }],
    "valueAxes": [{
        "logarithmic": true,
        "dashLength": 1,
        "guides": [{
            "dashLength": 6,
            "inside": true,
            "label": "average",
            "lineAlpha": 1,
            "value": 90.4
        }],
        "position": "left"
    }],
    "graphs": [{
        "bullet": "round",
        "id": "g1",
        "bulletBorderAlpha": 1,
        "bulletColor": "#FFFFFF",
        "bulletSize": 7,
        "lineThickness": 2,
        "title": "Price",
        "type": "smoothedLine",
        "useLineColorForBulletBorder": true,
        "valueField": "price"
    }],
    "chartScrollbar": {},
    "chartCursor": {
        "valueLineEnabled": true,
        "valueLineBalloonEnabled": true,
        "valueLineAlpha": 0.5,
        "fullWidth": true,
        "cursorAlpha": 0.05
    },
    "dataDateFormat": "YYYY-MM-DD",
    "categoryField": "date",
    "categoryAxis": {
        "parseDates": true
    },
    "export": {
        "enabled": true
    }
});

chart.addListener("dataUpdated", zoomChart);

function zoomChart() {
    chart.zoomToDates(new Date(2012, 2, 2), new Date(2012, 2, 10));
}

</script> 
<!--chart4 start--> 
<script>
var chart = AmCharts.makeChart("land-chart4", {
    "type": "serial",
    "theme": "light",
    "legend": {
        "equalWidths": false,
        "useGraphSettings": true,
        "valueAlign": "left",
        "valueWidth": 120
    },
    "dataProvider": [{
        "date": "2012-01-01",
        "distance": 227,
        "townName": "New York",
        "townName2": "New York",
        "townSize": 25,
        "latitude": 40.71,
        "duration": 408
    }, {
        "date": "2012-01-02",
        "distance": 371,
        "townName": "Washington",
        "townSize": 14,
        "latitude": 38.89,
        "duration": 482
    }, {
        "date": "2012-01-03",
        "distance": 433,
        "townName": "Wilmington",
        "townSize": 6,
        "latitude": 34.22,
        "duration": 562
    }, {
        "date": "2012-01-04",
        "distance": 345,
        "townName": "Jacksonville",
        "townSize": 7,
        "latitude": 30.35,
        "duration": 379
    }, {
        "date": "2012-01-05",
        "distance": 480,
        "townName": "Miami",
        "townName2": "Miami",
        "townSize": 10,
        "latitude": 25.83,
        "duration": 501
    }, {
        "date": "2012-01-06",
        "distance": 386,
        "townName": "Tallahassee",
        "townSize": 7,
        "latitude": 30.46,
        "duration": 443
    }, {
        "date": "2012-01-07",
        "distance": 348,
        "townName": "New Orleans",
        "townSize": 10,
        "latitude": 29.94,
        "duration": 405
    }, {
        "date": "2012-01-08",
        "distance": 238,
        "townName": "Houston",
        "townName2": "Houston",
        "townSize": 16,
        "latitude": 29.76,
        "duration": 309
    }, {
        "date": "2012-01-09",
        "distance": 218,
        "townName": "Dalas",
        "townSize": 17,
        "latitude": 32.8,
        "duration": 287
    }, {
        "date": "2012-01-10",
        "distance": 349,
        "townName": "Oklahoma City",
        "townSize": 11,
        "latitude": 35.49,
        "duration": 485
    }, {
        "date": "2012-01-11",
        "distance": 603,
        "townName": "Kansas City",
        "townSize": 10,
        "latitude": 39.1,
        "duration": 890
    }, {
        "date": "2012-01-12",
        "distance": 534,
        "townName": "Denver",
        "townName2": "Denver",
        "townSize": 18,
        "latitude": 39.74,
        "duration": 810
    }, {
        "date": "2012-01-13",
        "townName": "Salt Lake City",
        "townSize": 12,
        "distance": 425,
        "duration": 670,
        "latitude": 40.75,
        "dashLength": 8,
        "alpha": 0.4
    }, {
        "date": "2012-01-14",
        "latitude": 36.1,
        "duration": 470,
        "townName": "Las Vegas",
        "townName2": "Las Vegas"
    }, {
        "date": "2012-01-15"
    }, {
        "date": "2012-01-16"
    }, {
        "date": "2012-01-17"
    }, {
        "date": "2012-01-18"
    }, {
        "date": "2012-01-19"
    }],
    "valueAxes": [{
        "id": "distanceAxis",
        "axisAlpha": 0,
        "gridAlpha": 0,
        "position": "left",
        "title": "distance"
    }, {
        "id": "latitudeAxis",
        "axisAlpha": 0,
        "gridAlpha": 0,
        "labelsEnabled": false,
        "position": "right"
    }, {
        "id": "durationAxis",
        "duration": "mm",
        "durationUnits": {
            "hh": "h ",
            "mm": "min"
        },
        "axisAlpha": 0,
        "gridAlpha": 0,
        "inside": true,
        "position": "right",
        "title": "duration"
    }],
    "graphs": [{
        "alphaField": "alpha",
        "balloonText": "[[value]] miles",
        "dashLengthField": "dashLength",
        "fillAlphas": 0.7,
        "legendPeriodValueText": "total: [[value.sum]] mi",
        "legendValueText": "[[value]] mi",
        "title": "distance",
        "type": "column",
        "valueField": "distance",
        "valueAxis": "distanceAxis"
    }, {
        "balloonText": "latitude:[[value]]",
        "bullet": "round",
        "bulletBorderAlpha": 1,
        "useLineColorForBulletBorder": true,
        "bulletColor": "#FFFFFF",
        "bulletSizeField": "townSize",
        "dashLengthField": "dashLength",
        "descriptionField": "townName",
        "labelPosition": "right",
        "labelText": "[[townName2]]",
        "legendValueText": "[[description]]/[[value]]",
        "title": "latitude/city",
        "fillAlphas": 0,
        "valueField": "latitude",
        "valueAxis": "latitudeAxis"
    }, {
        "bullet": "square",
        "bulletBorderAlpha": 1,
        "bulletBorderThickness": 1,
        "dashLengthField": "dashLength",
        "legendValueText": "[[value]]",
        "title": "duration",
        "fillAlphas": 0,
        "valueField": "duration",
        "valueAxis": "durationAxis"
    }],
    "chartCursor": {
        "categoryBalloonDateFormat": "DD",
        "cursorAlpha": 0.1,
        "cursorColor":"#000000",
         "fullWidth":true,
        "valueBalloonsEnabled": false,
        "zoomable": false
    },
    "dataDateFormat": "YYYY-MM-DD",
    "categoryField": "date",
    "categoryAxis": {
        "dateFormats": [{
            "period": "DD",
            "format": "DD"
        }, {
            "period": "WW",
            "format": "MMM DD"
        }, {
            "period": "MM",
            "format": "MMM"
        }, {
            "period": "YYYY",
            "format": "YYYY"
        }],
        "parseDates": true,
        "autoGridCount": false,
        "axisColor": "#555555",
        "gridAlpha": 0.1,
        "gridColor": "#FFFFFF",
        "gridCount": 50
    },
    "export": {
    	"enabled": true
     }
});
</script> 
<!--chart5 start--> 
<script>
var chart = AmCharts.makeChart("land-chart5", {
    "type": "serial",
	"theme": "light",
    "legend": {
        "horizontalGap": 10,
        "maxColumns": 1,
        "position": "right",
		"useGraphSettings": true,
		"markerSize": 10
    },
    "dataProvider": [{
        "year": 2003,
        "europe": 2.5,
        "namerica": 2.5,
        "asia": 2.1,
        "lamerica": 0.3,
        "meast": 0.2,
        "africa": 0.1
    }, {
        "year": 2004,
        "europe": 2.6,
        "namerica": 2.7,
        "asia": 2.2,
        "lamerica": 0.3,
        "meast": 0.3,
        "africa": 0.1
    }, {
        "year": 2005,
        "europe": 2.8,
        "namerica": 2.9,
        "asia": 2.4,
        "lamerica": 0.3,
        "meast": 0.3,
        "africa": 0.1
    }],
    "valueAxes": [{
        "stackType": "regular",
        "axisAlpha": 0.5,
        "gridAlpha": 0
    }],
    "graphs": [{
        "balloonText": "<b>[[title]]</b><br><span style='font-size:14px'>[[category]]: <b>[[value]]</b></span>",
        "fillAlphas": 0.8,
        "labelText": "[[value]]",
        "lineAlpha": 0.3,
        "title": "Europe",
        "type": "column",
		"color": "#000000",
        "valueField": "europe"
    }, {
        "balloonText": "<b>[[title]]</b><br><span style='font-size:14px'>[[category]]: <b>[[value]]</b></span>",
        "fillAlphas": 0.8,
        "labelText": "[[value]]",
        "lineAlpha": 0.3,
        "title": "North America",
        "type": "column",
		"color": "#000000",
        "valueField": "namerica"
    }, {
        "balloonText": "<b>[[title]]</b><br><span style='font-size:14px'>[[category]]: <b>[[value]]</b></span>",
        "fillAlphas": 0.8,
        "labelText": "[[value]]",
        "lineAlpha": 0.3,
        "title": "Asia-Pacific",
        "type": "column",
		"color": "#000000",
        "valueField": "asia"
    }, {
        "balloonText": "<b>[[title]]</b><br><span style='font-size:14px'>[[category]]: <b>[[value]]</b></span>",
        "fillAlphas": 0.8,
        "labelText": "[[value]]",
        "lineAlpha": 0.3,
        "title": "Latin America",
        "type": "column",
		"color": "#000000",
        "valueField": "lamerica"
    }, {
        "balloonText": "<b>[[title]]</b><br><span style='font-size:14px'>[[category]]: <b>[[value]]</b></span>",
        "fillAlphas": 0.8,
        "labelText": "[[value]]",
        "lineAlpha": 0.3,
        "title": "Middle-East",
        "type": "column",
		"color": "#000000",
        "valueField": "meast"
    }, {
        "balloonText": "<b>[[title]]</b><br><span style='font-size:14px'>[[category]]: <b>[[value]]</b></span>",
        "fillAlphas": 0.8,
        "labelText": "[[value]]",
        "lineAlpha": 0.3,
        "title": "Africa",
        "type": "column",
		"color": "#000000",
        "valueField": "africa"
    }],
    "rotate": true,
    "categoryField": "year",
    "categoryAxis": {
        "gridPosition": "start",
        "axisAlpha": 0,
        "gridAlpha": 0,
        "position": "left"
    },
    "export": {
    	"enabled": true
     }
});
</script> 
<!--chart6 start--> 
<script>
$(function () {

    $('#land-chart6').highcharts({
        chart: {
            type: 'pyramid',
            marginRight: 100
        },
        title: {
            text: 'Sales pyramid',
            x: -50
        },
        plotOptions: {
            series: {
                dataLabels: {
                    enabled: true,
                    format: '<b>{point.name}</b> ({point.y:,.0f})',
                    color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black',
                    softConnector: true
                }
            }
        },
        legend: {
            enabled: false
        },
        series: [{
            name: 'Unique users',
            data: [
                ['Website visits',      15654],
                ['Downloads',            4064],
                ['Requested price list', 1987],
                ['Invoice sent',          976],
                ['Finalized',             846]
            ]
        }]
    });
});
</script> 
<!--chart7 start--> 
<script>
var chart;
var legend;
var selected;

var types = [{
  type: "Fossil Energy",
  percent: 70,
  color: "#ff9e01",
  subs: [{
    type: "Oil",
    percent: 15
  }, {
    type: "Coal",
    percent: 35
  }, {
    type: "Nuclear",
    percent: 20
  }]
}, {
  type: "Green Energy",
  percent: 30,
  color: "#b0de09",
  subs: [{
    type: "Hydro",
    percent: 15
  }, {
    type: "Wind",
    percent: 10
  }, {
    type: "Other",
    percent: 5
  }]
}];

function generateChartData() {
  var chartData = [];
  for (var i = 0; i < types.length; i++) {
    if (i == selected) {
      for (var x = 0; x < types[i].subs.length; x++) {
        chartData.push({
          type: types[i].subs[x].type,
          percent: types[i].subs[x].percent,
          color: types[i].color,
          pulled: true
        });
      }
    } else {
      chartData.push({
        type: types[i].type,
        percent: types[i].percent,
        color: types[i].color,
        id: i
      });
    }
  }
  return chartData;
}

AmCharts.makeChart("land-chart7", {
  "type": "pie",
  "dataProvider": generateChartData(),
  "labelText": "[[title]]: [[value]]",
  "balloonText": "[[title]]: [[value]]",
  "titleField": "type",
  "valueField": "percent",
  "outlineColor": "#FFFFFF",
  "outlineAlpha": 0.8,
  "outlineThickness": 2,
  "colorField": "color",
  "pulledField": "pulled",
  "titles": [{
    "text": "Click a slice to see the details"
  }],
  "listeners": [{
    "event": "clickSlice",
    "method": function(event) {
      var chart = event.chart;
      if (event.dataItem.dataContext.id != undefined) {
        selected = event.dataItem.dataContext.id;
      } else {
        selected = undefined;
      }
      chart.dataProvider = generateChartData();
      chart.validateData();
    }
  }]
});
</script> 
<!--chart8 start--> 
<script>
$(function () {
    $('#land-chart8').highcharts({
        chart: {
            type: 'pie',
            options3d: {
                enabled: true,
                alpha: 45,
                beta: 0
            }
        },
        title: {
            text: 'Browser market shares at a specific website, 2014'
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                depth: 35,
                dataLabels: {
                    enabled: true,
                    format: '{point.name}'
                }
            }
        },
        series: [{
            type: 'pie',
            name: 'Browser share',
            data: [
                ['Firefox', 45.0],
                ['IE', 26.8],
                {
                    name: 'Chrome',
                    y: 12.8,
                    sliced: true,
                    selected: true
                },
                ['Safari', 8.5],
                ['Opera', 6.2],
                ['Others', 0.7]
            ]
        }]
    });
});
</script> 
<!--chart9 start--> 
<script>
var chart = AmCharts.makeChart( "land-chart9", {
  "type": "serial",
  "theme": "light",
  "dataProvider": [ {
    "country": "USA",
    "visits": 2025
  }, {
    "country": "China",
    "visits": 1882
  }, {
    "country": "Japan",
    "visits": 1809
  }, {
    "country": "Germany",
    "visits": 1322
  }, {
    "country": "UK",
    "visits": 1122
  }, {
    "country": "France",
    "visits": 1114
  }, {
    "country": "India",
    "visits": 984
  }, {
    "country": "Spain",
    "visits": 711
  }, {
    "country": "Netherlands",
    "visits": 665
  }, {
    "country": "Russia",
    "visits": 580
  }, {
    "country": "South Korea",
    "visits": 443
  }, {
    "country": "Canada",
    "visits": 441
  }, {
    "country": "Brazil",
    "visits": 395
  } ],
  "valueAxes": [ {
    "gridColor": "#FFFFFF",
    "gridAlpha": 0.2,
    "dashLength": 0
  } ],
  "gridAboveGraphs": true,
  "startDuration": 1,
  "graphs": [ {
    "balloonText": "[[category]]: <b>[[value]]</b>",
    "fillAlphas": 0.8,
    "lineAlpha": 0.2,
    "type": "column",
    "valueField": "visits"
  } ],
  "chartCursor": {
    "categoryBalloonEnabled": false,
    "cursorAlpha": 0,
    "zoomable": false
  },
  "categoryField": "country",
  "categoryAxis": {
    "gridPosition": "start",
    "gridAlpha": 0,
    "tickPosition": "start",
    "tickLength": 20
  },
  "export": {
    "enabled": true
  }

} );
</script> 
<!--chart10 start--> 
<script>
var chart = AmCharts.makeChart("land-chart10",
{
    "type": "serial",
	"theme": "light",
    "dataProvider": [{
        "name": "John",
        "points": 35654,
        "color": "#7F8DA9",
        "bullet": "//www.amcharts.com/lib/3/images/0.gif"
    }, {
        "name": "Damon",
        "points": 65456,
        "color": "#FEC514",
        "bullet": "//www.amcharts.com/lib/3/images/1.gif"
    }, {
        "name": "Patrick",
        "points": 45724,
        "color": "#DB4C3C",
        "bullet": "//www.amcharts.com/lib/3/images/2.gif"
    }, {
        "name": "Mark",
        "points": 13654,
        "color": "#DAF0FD",
        "bullet": "//www.amcharts.com//lib/3/images/3.gif"
    }],
    "valueAxes": [{
        "maximum": 80000,
        "minimum": 0,
        "axisAlpha": 0,
        "dashLength": 4,
        "position": "left"
    }],
    "startDuration": 1,
    "graphs": [{
        "balloonText": "<span style='font-size:13px;'>[[category]]: <b>[[value]]</b></span>",
        "bulletOffset": 16,
        "bulletSize": 34,
        "colorField": "color",
        "cornerRadiusTop": 8,
        "customBulletField": "bullet",
        "fillAlphas": 0.8,
        "lineAlpha": 0,
        "type": "column",
        "valueField": "points"
    }],
    "marginTop": 0,
    "marginRight": 0,
    "marginLeft": 0,
    "marginBottom": 0,
    "autoMargins": false,
    "categoryField": "name",
    "categoryAxis": {
        "axisAlpha": 0,
        "gridAlpha": 0,
        "inside": true,
        "tickLength": 0
    },
    "export": {
    	"enabled": true
     }
});
</script> 
<!--chart11 start--> 
<script>
var chart = AmCharts.makeChart( "land-chart11", {
  "type": "serial",
  "theme": "light",
  "dataProvider": [ {
    "name": "Income A",
    "open": 0,
    "close": 11.13,
    "color": "#54cb6a",
    "balloonValue": 11.13
  }, {
    "name": "Income B",
    "open": 11.13,
    "close": 15.81,
    "color": "#54cb6a",
    "balloonValue": 4.68
  }, {
    "name": "Total Income",
    "open": 0,
    "close": 15.81,
    "color": "#169b2f",
    "balloonValue": 15.81
  }, {
    "name": "Expenses A",
    "open": 12.92,
    "close": 15.81,
    "color": "#cc4b48",
    "balloonValue": 2.89
  }, {
    "name": "Expenses B",
    "open": 8.64,
    "close": 12.92,
    "color": "#cc4b48",
    "balloonValue": 4.24
  }, {
    "name": "Revenue",
    "open": 0,
    "close": 8.64,
    "color": "#1c8ceb",
    "balloonValue": 11.13
  } ],
  "valueAxes": [ {
    "axisAlpha": 0,
    "gridAlpha": 0.1,
    "position": "left"
  } ],
  "startDuration": 1,
  "graphs": [ {
    "balloonText": "<span style='color:[[color]]'>[[category]]</span><br><b>$[[balloonValue]] Mln</b>",
    "colorField": "color",
    "fillAlphas": 0.8,
    "labelText": "$[[balloonValue]]",
    "lineColor": "#BBBBBB",
    "openField": "open",
    "type": "column",
    "valueField": "close"
  } ],
  "trendLines": [ {
    "dashLength": 3,
    "finalCategory": "Income B",
    "finalValue": 11.13,
    "initialCategory": "Income A",
    "initialValue": 11.13,
    "lineColor": "#888888"
  }, {
    "dashLength": 3,
    "finalCategory": "Expenses A",
    "finalValue": 15.81,
    "initialCategory": "Income B",
    "initialValue": 15.81,
    "lineColor": "#888888"
  }, {
    "dashLength": 3,
    "finalCategory": "Expenses B",
    "finalValue": 12.92,
    "initialCategory": "Expenses A",
    "initialValue": 12.92,
    "lineColor": "#888888"
  }, {
    "dashLength": 3,
    "finalCategory": "Revenue",
    "finalValue": 8.64,
    "initialCategory": "Expenses B",
    "initialValue": 8.64,
    "lineColor": "#888888"
  } ],
  "columnWidth": 0.6,
  "categoryField": "name",
  "categoryAxis": {
    "gridPosition": "start",
    "axisAlpha": 0,
    "gridAlpha": 0.1
  },
  "export": {
    "enabled": true
  }
} );
</script> 
<!--chart12 start--> 
<script>
$(function () {
    $('#land-chart12').highcharts({

        chart: {
            type: 'column'
        },

        title: {
            text: 'Total fruit consumtion, grouped by gender'
        },

        xAxis: {
            categories: ['Apples', 'Oranges', 'Pears', 'Grapes', 'Bananas']
        },

        yAxis: {
            allowDecimals: false,
            min: 0,
            title: {
                text: 'Number of fruits'
            }
        },

        tooltip: {
            formatter: function () {
                return '<b>' + this.x + '</b><br/>' +
                    this.series.name + ': ' + this.y + '<br/>' +
                    'Total: ' + this.point.stackTotal;
            }
        },

        plotOptions: {
            column: {
                stacking: 'normal'
            }
        },

        series: [{
            name: 'John',
            data: [5, 3, 4, 7, 2],
            stack: 'male'
        }, {
            name: 'Joe',
            data: [3, 4, 4, 2, 5],
            stack: 'male'
        }, {
            name: 'Jane',
            data: [2, 5, 6, 2, 1],
            stack: 'female'
        }, {
            name: 'Janet',
            data: [3, 0, 4, 4, 3],
            stack: 'female'
        }]
    });
});
</script> 

<!--top to bottom scroll--> 
<script type="text/javascript">
		$(function(){
			$('#vertical-ticker1').totemticker({
				row_height	:	'100px',
				next		:	'#ticker-next',
				previous	:	'#ticker-previous',
				stop		:	'#stop',
				start		:	'#start',
				mousestop	:	true
			});
		});
	</script>