<!--STYLE-->
<?php /*?><link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css';?>"/><?php */?>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/amcharts/landbank-chart.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/amcharts/landbank-lightchart.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/amcharts/landbank-serialchart.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/amcharts/landbank-piechart.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/amcharts/landbank-radarchart.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/amcharts/landbank-xychart.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/amcharts/gauge.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/amcharts/landbank-amstock.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/Highcharts-4.2.3/js/highcharts.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/Highcharts-4.2.3/js/modules/exporting.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/Highcharts-4.2.3/js/modules/funnel.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/jquery.easy-ticker.js"></script>


<style>
#land-chart1, #land-chart2, #land-chart3, #land-chart4, #land-chart5, #land-chart6, #land-chart7, #land-chart8, #land-chart9,  #land-chart10, #land-chart11, #land-chart12,#land-chart13, #land-chart14, #land-chart15, #land-chart16, #land-chart17, #land-chart18, #land-chart19, #land-chart20, #land-chart21, #land-chart22, #land-chart23, #land-chart24 {
	width : 100% !important;
	height : 400px !important;
	font-size : 11px;
	overflow:hidden;
}
 
#highcharts-0, #highcharts-11, #highcharts-3, #highcharts-25 {
	width:100% !important
}
.top_rfc {
	background:#fff;
	padding:5px 0;
	margin-bottom:20px;
	box-shadow: 1px 1px 0 0 rgba(50, 50, 50, 0.23);
}
.rfc-primary {
	border-bottom:2px solid #337ab7 !important;
	
}
 .panel1:hover::before, .panel1:focus::before, .panel1:active::before {
 left: 0;
 right: 0;
}
.panel1::before {
 background: #2098d1 none repeat scroll 0 0;
 content: "";
 height: 2px;
 left: 50%;
 position: absolute;
 right: 50%;
 top: 0;
 transition-duration: 0.3s;
 transition-property: left, right;
 transition-timing-function: ease-out;
 z-index: -1;
}
.panel1 {
	backface-visibility: hidden;
	box-shadow: 0 0 1px rgba(0, 0, 0, 0);
	display: inline-block;
	overflow: hidden;
	position: relative;
	transform: translateZ(0px);
	vertical-align: middle;
}
.panel {
	background-color: #fff;
	border: 1px solid #e8e8e8;
	border-radius: 4px;
	box-shadow: 0 1px 1px rgba(0, 0, 0, 0.05);
	margin:20px 0 30px 0;
	box-shadow: 1px 1px 0 0 rgba(50, 50, 50, 0.23);
	width:100%;
}
.rfc-primary > .panel-heading {
	border-bottom:2px solid #337ab7;
	background:none;
	color: #000 !important;
}
.panel-heading {
	border-bottom: 1px solid transparent;
	border-top-left-radius: 3px;
	border-top-right-radius: 3px;
	padding: 10px 15px;
}
.pull-left {
	float: left !important;
}
.pull-right {
	float: right;
}
.panel-green {
	border-bottom:2px solid #5cb85c;
	
}
.panel-red {
	border-bottom:2px solid #d9534f;
	
}
.rfc-primary > .panel-heading {
	color: #fff;
}
.huge {
	font-size: 40px;
	color:#000;
}
.text-right {
	font-size:15px;
	color:#666;
	font-family: "Open Sans", sans-serif;
}
.panel-yellow {
	border-bottom:2px solid #f0ad4e;
	
}
.panel-body {
/*border:1px solid #e7e7e7;
	box-shadow: 1px 1px 0 0 rgba(50, 50, 50, 0.23);*/
}
.panel1 > .panel-heading {
	background:none;
	border:none
}
.panel-heading {
	border: 1px solid #ddd;
	border-top-left-radius: 3px;
	border-top-right-radius: 3px;
	color: #06528c;
	font-size: 20px;
	padding: 10px 15px;
	background:#fff;
	transition: margin 0.5s ease-out 0s;
}
.fa-5x {
	color: #000;
	font-size: 40px;
	line-height: 64px;
	margin-left: 12px;
	overflow: hidden;
}
/*--icon anmation---*/
.sk-spinner-wave.sk-spinner {
 float:left;
  width: 45px;
  height: 30px;
  text-align: center;
  font-size: 10px; }
.sk-spinner-wave div {
  background-color: #ff6000;
  height: 100%;
  width: 3px;
  display: inline-block;
  -webkit-animation: sk-waveStretchDelay 1.2s infinite ease-in-out;
          animation: sk-waveStretchDelay 1.2s infinite ease-in-out; }
.sk-spinner-wave > .sk-rect2 {
  -webkit-animation-delay: -1.1s;
          animation-delay: -1.1s; background:#c000ff }
		  
.sk-spinner-wave > .sk-rect3 {
  -webkit-animation-delay: -1s;
          animation-delay: -1s; background:#0207c2  }
.sk-spinner-wave > .sk-rect4 {
  -webkit-animation-delay: -0.9s;
          animation-delay: -0.9s; background:#099102  }
.sk-spinner-wave > .sk-rect5 {
  -webkit-animation-delay: -0.8s;
          animation-delay: -0.8s; background:#c20202  }

@-webkit-keyframes sk-waveStretchDelay {
  0%, 40%, 100% {
    -webkit-transform: scaleY(0.4);
            transform: scaleY(0.4); }

  20% {
    -webkit-transform: scaleY(1);
            transform: scaleY(1); } }

@keyframes sk-waveStretchDelay {
  0%, 40%, 100% {
    -webkit-transform: scaleY(0.4);
            transform: scaleY(0.4); }

  20% {
    -webkit-transform: scaleY(1);
            transform: scaleY(1); } }


/*--three box css--*/

.circle-icon {
	width:70px;
	height:70px;
	border-radius:100%;
	border:3px solid #337ab7
}
.circle-icon1 {
	border:3px solid #5cb85c
}
.circle-icon2 {
	border:3px solid #f0ad4e
}
.circle-icon3 {
	border:3px solid #d9534f
}
/*-----message list--*/
.message-list {
	list-style-type: none;
	margin: 0;
	padding: 0;
}
.flat-blue a {
	color: #363c46;
}
.message-list > li {
	border-bottom: 1px dotted #eee;
	padding:10px;
}
.message-list > li .profile-img {
	height: 60px;
	width: 60px;
	border: 2px solid rgba(0, 112, 255, 0.4);
	border-radius:50%;
}
.message-list > li .profile-img:hover {
	border: 2px solid rgba(0, 112, 255, 0.9);
}
.pull-left {
	float: left;
}
.message-list > li > .message-block {
	min-height: 60px;
	padding-left: 70px;
}
.message-list > li > .message-block .username {
	font-size: 12px;
	font-weight: bold;
	color:#333;
}
.message-list > li > .message-block .message-datetime {
	color: #aaa;
	font-size: 10px;
}
.message-list > li > .message-block .message {
	font-size: 12px;
	color:#333;
}
/*--icon animation css--*/


/*--icon animation css--*/
</style>
<!--content-->

<div class="content_wrapper padlr0">
  <div class="container-fluid padlr0">
    <div class="col-lg-12">
      <h1 class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0">Dashboard</h1>
      
      <!--Short by-->
      <div class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0" style="margin-bottom:10px; padding-right:0px !important;">
        <label class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0 control-label text-right">Select by</label>
        <div class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0" style="padding-right:0px !important;">
          <select class="form-control single_dropdown lbl_move sortoption" style="width:100%;">
            <option></option>
            <option selected>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
            <option>6</option>
          </select>
        </div>
        
        <!--Short by end--> 
      </div>
      
      <!--three feild start-->
    <div class="col-sm-3">
      <div class="panel panel1 rfc-primary">
        <div class="panel-heading pnl-overflow ">
          <div class="row">
            <div class="col-xs-3">
              <div class="set-5">
<div class="hi-icon-wrap hi-icon-effect-5 circle-icon hi-icon-effect-5a"><i style="color:#337ab7" class="fa fa-comments hi-icon fa-5x"></i></div></div>
            </div>
            <div class="col-xs-9 text-right">
              <div class="huge">26</div>
              <div>New Comments!</div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-3">
      <div class="panel panel1 panel-green">
        <div class="panel-heading pnl-overflow ">
          <div class="row">
            <div class="col-xs-3">
            <div class="set-5">
<div class="hi-icon-wrap hi-icon-effect-5 circle-icon circle-icon1 hi-icon-effect-5a"><i style="color:#5cb85c" class="fa fa-tasks hi-icon fa-5x"></i></div></div>
              
            </div>
            <div class="col-xs-9 text-right">
              <div class="huge">12</div>
              <div>New Tasks!</div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-3">
      <div class="panel panel1 panel-yellow">
        <div class="panel-heading  pnl-overflow ">
          <div class="row">
            <div class="col-xs-3">
               <div class="set-5">
<div class="hi-icon-wrap hi-icon-effect-5 circle-icon circle-icon2 hi-icon-effect-5a"><i style="color:#f0ad4e" class="fa fa-shopping-cart hi-icon fa-5x"></i></div></div>
              
            </div>
            <div class="col-xs-9 text-right">
              <div class="huge">124</div>
              <div>New Orders!</div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-3">
      <div class="panel panel1 panel-red">
        <div class="panel-heading pnl-overflow ">
          <div class="row">
            <div class="col-xs-3">
            <div class="set-5">
<div class="hi-icon-wrap hi-icon-effect-5 circle-icon circle-icon3 hi-icon-effect-5a"><i style="color:#d9534f" class="fa fa-support hi-icon fa-5x"></i></div></div>
              
            </div>
            <div class="col-xs-9 text-right">
              <div class="huge">13</div>
              <div>Support Tickets</div>
            </div>
          </div>
        </div>
      </div>
      
      <!--box start--> 
     
    </div>
    <!--box end-->
    </div>
     <div class="clear clearfix"></div>
    <!--chart1 start-->
    <div class="col-lg-12">
      <header class="panel-heading">
        <div class="sk-spinner sk-spinner-wave">
     <div class="sk-rect1"></div>
     <div class="sk-rect2"></div>
      <div class="sk-rect3"></div>
     <div class="sk-rect4"></div>
    <div class="sk-rect5"></div>     
   </div>
       Total No of Enquires</header>
      <div id="land-chart1" class="top_rfc"></div>
    </div>
    <!--chart2 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <div class="sk-spinner sk-spinner-wave">
     <div class="sk-rect1"></div>
     <div class="sk-rect2"></div>
      <div class="sk-rect3"></div>
     <div class="sk-rect4"></div>
    <div class="sk-rect5"></div>     
   </div>
        Total No of Tender Document Purchase</header>
      <div id="land-chart2" class="top_rfc"></div>
    </div>
    <!--chart2 complete--> 
    <!--chart3 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <div class="sk-spinner sk-spinner-wave">
     <div class="sk-rect1"></div>
     <div class="sk-rect2"></div>
      <div class="sk-rect3"></div>
     <div class="sk-rect4"></div>
    <div class="sk-rect5"></div>     
   </div>
        Total No of Quoted</header>
      <div id="land-chart3" class="top_rfc"></div>
    </div>
    <!--chart4 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <div class="sk-spinner sk-spinner-wave">
     <div class="sk-rect1"></div>
     <div class="sk-rect2"></div>
      <div class="sk-rect3"></div>
     <div class="sk-rect4"></div>
    <div class="sk-rect5"></div>     
   </div>
       Total No of Win</header>
      <div id="land-chart4" class="top_rfc"></div>
    </div>
    <!--chart4 complete--> 
    <!--chart5 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <div class="sk-spinner sk-spinner-wave">
     <div class="sk-rect1"></div>
     <div class="sk-rect2"></div>
      <div class="sk-rect3"></div>
     <div class="sk-rect4"></div>
    <div class="sk-rect5"></div>     
   </div>
        Total No of Orders Received</header>
      <div id="land-chart5" class="top_rfc"></div>
    </div>
    <!--chart6 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <div class="sk-spinner sk-spinner-wave">
     <div class="sk-rect1"></div>
     <div class="sk-rect2"></div>
      <div class="sk-rect3"></div>
     <div class="sk-rect4"></div>
    <div class="sk-rect5"></div>     
   </div>
       Total No of Projects</header>
      <div id="land-chart6" class="top_rfc"></div>
    </div>
    <!--chart6 complete--> 
    <!--chart7 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <div class="sk-spinner sk-spinner-wave">
     <div class="sk-rect1"></div>
     <div class="sk-rect2"></div>
      <div class="sk-rect3"></div>
     <div class="sk-rect4"></div>
    <div class="sk-rect5"></div>     
   </div>
       Win Ratio</header>
      <div id="land-chart7" class="top_rfc"></div>
    </div>
    
    <!--chart7 complete--> 
    <!--chart8 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <div class="sk-spinner sk-spinner-wave">
     <div class="sk-rect1"></div>
     <div class="sk-rect2"></div>
      <div class="sk-rect3"></div>
     <div class="sk-rect4"></div>
    <div class="sk-rect5"></div>     
   </div>
       Lose Ratio Reason wise</header>
      <div id="land-chart8" class="top_rfc"></div>
    </div>
    <!--chart8 complete--> 
    <!--chart9 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <div class="sk-spinner sk-spinner-wave">
     <div class="sk-rect1"></div>
     <div class="sk-rect2"></div>
      <div class="sk-rect3"></div>
     <div class="sk-rect4"></div>
    <div class="sk-rect5"></div>     
   </div>
       Period wise Quote, Win Chart (Values/ Nos)</header>
      <div id="land-chart9" class="top_rfc"></div>
    </div>
    <!--chart9 complete--> 
    <!--chart10 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <div class="sk-spinner sk-spinner-wave">
     <div class="sk-rect1"></div>
     <div class="sk-rect2"></div>
      <div class="sk-rect3"></div>
     <div class="sk-rect4"></div>
    <div class="sk-rect5"></div>     
   </div>
       Quote vs Win </header>
      <div id="land-chart10" class="top_rfc"></div>
    </div>
    <!--chart11 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <div class="sk-spinner sk-spinner-wave">
     <div class="sk-rect1"></div>
     <div class="sk-rect2"></div>
      <div class="sk-rect3"></div>
     <div class="sk-rect4"></div>
    <div class="sk-rect5"></div>     
   </div>
       Enquiry vs Quote</header>
      <div id="land-chart11" class="top_rfc"></div>
    </div>
    <!--chart12 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <div class="sk-spinner sk-spinner-wave">
     <div class="sk-rect1"></div>
     <div class="sk-rect2"></div>
      <div class="sk-rect3"></div>
     <div class="sk-rect4"></div>
    <div class="sk-rect5"></div>     
   </div>
        Enquiry vs Win</header>
      <div id="land-chart12" class="top_rfc"></div>
    </div>
    <!--chart12 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <div class="sk-spinner sk-spinner-wave">
     <div class="sk-rect1"></div>
     <div class="sk-rect2"></div>
      <div class="sk-rect3"></div>
     <div class="sk-rect4"></div>
    <div class="sk-rect5"></div>     
   </div>
       Client wise Tender</header>
      <div id="land-chart13" class="top_rfc"></div>
    </div>
    <!--chart13 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <div class="sk-spinner sk-spinner-wave">
     <div class="sk-rect1"></div>
     <div class="sk-rect2"></div>
      <div class="sk-rect3"></div>
     <div class="sk-rect4"></div>
    <div class="sk-rect5"></div>     
   </div>
        Client wise Orders</header>
      <div id="land-chart14" class="top_rfc"></div>
    </div>
    <!--chart14 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <div class="sk-spinner sk-spinner-wave">
     <div class="sk-rect1"></div>
     <div class="sk-rect2"></div>
      <div class="sk-rect3"></div>
     <div class="sk-rect4"></div>
    <div class="sk-rect5"></div>     
   </div>
       Client wise Win Ratio</header>
      <div id="land-chart15" class="top_rfc"></div>
    </div>
    <!--chart15 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <div class="sk-spinner sk-spinner-wave">
     <div class="sk-rect1"></div>
     <div class="sk-rect2"></div>
      <div class="sk-rect3"></div>
     <div class="sk-rect4"></div>
    <div class="sk-rect5"></div>     
   </div>
       Consultant wise Win Ratio</header>
      <div id="land-chart16" class="top_rfc"></div>
    </div>
    <!--chart16 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <div class="sk-spinner sk-spinner-wave">
     <div class="sk-rect1"></div>
     <div class="sk-rect2"></div>
      <div class="sk-rect3"></div>
     <div class="sk-rect4"></div>
    <div class="sk-rect5"></div>     
   </div>
       City wise win ratios</header>
      <div id="land-chart17" class="top_rfc"></div>
    </div>
    <!--chart17 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <div class="sk-spinner sk-spinner-wave">
     <div class="sk-rect1"></div>
     <div class="sk-rect2"></div>
      <div class="sk-rect3"></div>
     <div class="sk-rect4"></div>
    <div class="sk-rect5"></div>     
   </div>
       Project Type (Pie)</header>
      <div id="land-chart18" class="top_rfc"></div>
    </div>
    <!--chart18 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <div class="sk-spinner sk-spinner-wave">
     <div class="sk-rect1"></div>
     <div class="sk-rect2"></div>
      <div class="sk-rect3"></div>
     <div class="sk-rect4"></div>
    <div class="sk-rect5"></div>     
   </div>
       Tender Type (Pie)</header>
      <div id="land-chart19" class="top_rfc"></div>
    </div>
    <!--chart19 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <div class="sk-spinner sk-spinner-wave">
     <div class="sk-rect1"></div>
     <div class="sk-rect2"></div>
      <div class="sk-rect3"></div>
     <div class="sk-rect4"></div>
    <div class="sk-rect5"></div>     
   </div>
        Tender in Hand</header>
      <div id="land-chart20" class="top_rfc"></div>
    </div>
    <!--chart20 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <div class="sk-spinner sk-spinner-wave">
     <div class="sk-rect1"></div>
     <div class="sk-rect2"></div>
      <div class="sk-rect3"></div>
     <div class="sk-rect4"></div>
    <div class="sk-rect5"></div>     
   </div>
       Alerts</header>
      <div id="land-chart21" class="top_rfc"></div>
    </div>
    <!--chart21 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <div class="sk-spinner sk-spinner-wave">
     <div class="sk-rect1"></div>
     <div class="sk-rect2"></div>
      <div class="sk-rect3"></div>
     <div class="sk-rect4"></div>
    <div class="sk-rect5"></div>     
   </div>
       Reminders</header>
      <div id="land-chart22" class="top_rfc"></div>
    </div>
    
    <!--chart5 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <div class="sk-spinner sk-spinner-wave">
     <div class="sk-rect1"></div>
     <div class="sk-rect2"></div>
      <div class="sk-rect3"></div>
     <div class="sk-rect4"></div>
    <div class="sk-rect5"></div>     
   </div>
       Latest News</header>
      <div class="top_rfc" style="height:400px !important">
        <div class="panel-body">
          <ul class="message-list" id="vertical-ticker1">
            <li> <img class="profile-img pull-left" src="<?php echo $this->basePath(); ?>/images/flwup_proimg.png">
              <div class="message-block">
                <div> <span class="username">Tui2Tone</span> <span class="message-datetime">12 min ago</span> </div>
                <div class="message">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales.</div>
              </div>
            </li>
            <li> <img class="profile-img pull-left" src="<?php echo $this->basePath(); ?>/images/flwup_proimg.png">
              <div class="message-block">
                <div> <span class="username">Tui2Tone</span> <span class="message-datetime">15 min ago</span> </div>
                <div class="message">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales.  Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales.</div>
              </div>
            </li>
            <li> <img class="profile-img pull-left" src="<?php echo $this->basePath(); ?>/images/flwup_proimg.png">
              <div class="message-block">
                <div> <span class="username">Tui2Tone</span> <span class="message-datetime">15 min ago</span> </div>
                <div class="message">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales.  Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales.</div>
              </div>
            </li>
            <li> <img class="profile-img pull-left" src="<?php echo $this->basePath(); ?>/images/flwup_proimg.png">
              <div class="message-block">
                <div> <span class="username">Tui2Tone</span> <span class="message-datetime">1 day ago</span> </div>
                <div class="message">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales.</div>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <!--chart23 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <div class="sk-spinner sk-spinner-wave">
     <div class="sk-rect1"></div>
     <div class="sk-rect2"></div>
      <div class="sk-rect3"></div>
     <div class="sk-rect4"></div>
    <div class="sk-rect5"></div>     
   </div>
       Most win Competitor</header>
      <div id="land-chart23" class="top_rfc"></div>
    </div>
    <!--chart21 start-->
    <div class="col-lg-6">
      <header class="panel-heading">
        <div class="sk-spinner sk-spinner-wave">
     <div class="sk-rect1"></div>
     <div class="sk-rect2"></div>
      <div class="sk-rect3"></div>
     <div class="sk-rect4"></div>
    <div class="sk-rect5"></div>     
   </div>
         Most L2 Competitor</header>
      <div id="land-chart24" class="top_rfc"></div>
    </div>
  </div>
</div>
<!--datepicker--> 
<!--chart1 start--> 

<script>
var chartData = [
    {
        "date": "2012-01-01",
        "distance": 227,
        "townName": "New York",
        "townName2": "New York",
        "townSize": 25,
        "latitude": 40.71,
        "duration": 408
    },
    {
        "date": "2012-01-02",
        "distance": 371,
        "townName": "Washington",
        "townSize": 14,
        "latitude": 38.89,
        "duration": 482
    },
    {
        "date": "2012-01-03",
        "distance": 433,
        "townName": "Wilmington",
        "townSize": 6,
        "latitude": 34.22,
        "duration": 562
    },
    {
        "date": "2012-01-04",
        "distance": 345,
        "townName": "Jacksonville",
        "townSize": 7,
        "latitude": 30.35,
        "duration": 379
    },
    {
        "date": "2012-01-05",
        "distance": 480,
        "townName": "Miami",
        "townName2": "Miami",
        "townSize": 10,
        "latitude": 25.83,
        "duration": 501
    },
    {
        "date": "2012-01-06",
        "distance": 386,
        "townName": "Tallahassee",
        "townSize": 7,
        "latitude": 30.46,
        "duration": 443
    },
    {
        "date": "2012-01-07",
        "distance": 348,
        "townName": "New Orleans",
        "townSize": 10,
        "latitude": 29.94,
        "duration": 405
    },
    {
        "date": "2012-01-08",
        "distance": 238,
        "townName": "Houston",
        "townName2": "Houston",
        "townSize": 16,
        "latitude": 29.76,
        "duration": 309
    },
    {
        "date": "2012-01-09",
        "distance": 218,
        "townName": "Dalas",
        "townSize": 17,
        "latitude": 32.8,
        "duration": 287
    },
    {
        "date": "2012-01-10",
        "distance": 349,
        "townName": "Oklahoma City",
        "townSize": 11,
        "latitude": 35.49,
        "duration": 485
    },
    {
        "date": "2012-01-11",
        "distance": 603,
        "townName": "Kansas City",
        "townSize": 10,
        "latitude": 39.1,
        "duration": 890
    },
    {
        "date": "2012-01-12",
        "distance": 534,
        "townName": "Denver",
        "townName2": "Denver",
        "townSize": 18,
        "latitude": 39.74,
        "duration": 810
    },
    {
        "date": "2012-01-13",
        "townName": "Salt Lake City",
        "townSize": 12,
        "distance": 425,
        "duration": 670,
        "latitude": 40.75,
        "alpha":0.4
    },
    {
        "date": "2012-01-14",
        "latitude": 36.1,
        "duration": 470,
        "townName": "Las Vegas",
        "townName2": "Las Vegas",
        "bulletClass": "lastBullet"
    },
    {
        "date": "2012-01-15"
    },
    {
        "date": "2012-01-16"
    },
    {
        "date": "2012-01-17"
    },
    {
        "date": "2012-01-18"
    },
    {
        "date": "2012-01-19"
    }
];
var chart = AmCharts.makeChart("land-chart1", {
  type: "serial",
  dataDateFormat: "YYYY-MM-DD",
  dataProvider: chartData,

  addClassNames: true,
  startDuration: 1,
  color: "#000",
  marginLeft: 0,

  categoryField: "date",
  categoryAxis: {
    parseDates: true,
    minPeriod: "DD",
    autoGridCount: false,
    gridCount: 50,
    gridAlpha: 0.1,
    gridColor: "#000",
    axisColor: "#263138",
    dateFormats: [{
        period: 'DD',
        format: 'DD'
    }, {
        period: 'WW',
        format: 'MMM DD'
    }, {
        period: 'MM',
        format: 'MMM'
    }, {
        period: 'YYYY',
        format: 'YYYY'
    }]
  },

  valueAxes: [{
    id: "a1",
    title: "distance",
    gridAlpha: 0,
    axisAlpha: 0
  },{
    id: "a2",
    position: "right",
    gridAlpha: 0,
    axisAlpha: 0,
    labelsEnabled: false
  },{
    id: "a3",
    title: "duration",
    position: "right",
    gridAlpha: 0,
    axisAlpha: 0,
    inside: true,
    duration: "mm",
    durationUnits: {
        DD: "d. ",
        hh: "h ",
        mm: "min",
        ss: ""
    }
  }],
  graphs: [{
    id: "g1",
    valueField:  "distance",
    title:  "distance",
    type:  "column",
    fillAlphas:  0.9,
    valueAxis:  "a1",
    balloonText:  "[[value]] miles",
    legendValueText:  "[[value]] mi",
    legendPeriodValueText:  "total: [[value.sum]] mi",
    lineColor:  "#263138",
    alphaField:  "alpha",
  },{
    id: "g2",
    valueField: "latitude",
    classNameField: "bulletClass",
    title: "latitude/city",
    type: "line",
    valueAxis: "a2",
    lineColor: "#786c56",
    lineThickness: 1,
    legendValueText: "[[description]]/[[value]]",
    descriptionField: "townName",
    bullet: "round",
    bulletSizeField: "townSize",
    bulletBorderColor: "#786c56",
    bulletBorderAlpha: 1,
    bulletBorderThickness: 2,
    bulletColor: "#000000",
    labelText: "[[townName2]]",
    labelPosition: "right",
    balloonText: "latitude:[[value]]",
    showBalloon: true,
    animationPlayed: true,
  },{
    id: "g3",
    title: "duration",
    valueField: "duration",
    type: "line",
    valueAxis: "a3",
    lineColor: "#ff5755",
    balloonText: "[[value]]",
    lineThickness: 1,
    legendValueText: "[[value]]",
    bullet: "square",
    bulletBorderColor: "#ff5755",
    bulletBorderThickness: 1,
    bulletBorderAlpha: 1,
    dashLengthField: "dashLength",
    animationPlayed: true
  }],

  chartCursor: {
    zoomable: false,
    categoryBalloonDateFormat: "DD",
    cursorAlpha: 0,
    valueBalloonsEnabled: false
  },
  legend: {
    bulletType: "round",
    equalWidths: false,
    valueWidth: 120,
    useGraphSettings: true,
    color: "#000"
  }
});
</script> 
<!--chart2 start--> 
<script>
var chart = AmCharts.makeChart("land-chart2", {
	"type": "serial",
     "theme": "light",
	"categoryField": "year",
	"rotate": true,
	"startDuration": 1,
	"categoryAxis": {
		"gridPosition": "start",
		"position": "left"
	},
	"trendLines": [],
	"graphs": [
		{
			"balloonText": "Income:[[value]]",
			"fillAlphas": 0.8,
			"id": "AmGraph-1",
			"lineAlpha": 0.2,
			"title": "Income",
			"type": "column",
			"valueField": "income"
		},
		{
			"balloonText": "Expenses:[[value]]",
			"fillAlphas": 0.8,
			"id": "AmGraph-2",
			"lineAlpha": 0.2,
			"title": "Expenses",
			"type": "column",
			"valueField": "expenses"
		}
	],
	"guides": [],
	"valueAxes": [
		{
			"id": "ValueAxis-1",
			"position": "top",
			"axisAlpha": 0
		}
	],
	"allLabels": [],
	"balloon": {},
	"titles": [],
	"dataProvider": [
		{
			"year": 2005,
			"income": 23.5,
			"expenses": 18.1
		},
		{
			"year": 2006,
			"income": 26.2,
			"expenses": 22.8
		},
		{
			"year": 2007,
			"income": 30.1,
			"expenses": 23.9
		},
		{
			"year": 2008,
			"income": 29.5,
			"expenses": 25.1
		},
		{
			"year": 2009,
			"income": 24.6,
			"expenses": 25
		}
	],
    "export": {
    	"enabled": true
     }

});
</script> 
<!--chart3 start--> 
<script>
var chart = AmCharts.makeChart("land-chart3", {
    "type": "serial",
    "theme": "light",
    "marginRight": 80,
    "marginTop": 17,
    "autoMarginOffset": 20,
    "dataProvider": [{
        "date": "2012-03-01",
        "price": 20
    }, {
        "date": "2012-03-02",
        "price": 75
    }, {
        "date": "2012-03-03",
        "price": 15
    }, {
        "date": "2012-03-04",
        "price": 75
    }, {
        "date": "2012-03-05",
        "price": 158
    }, {
        "date": "2012-03-06",
        "price": 57
    }, {
        "date": "2012-03-07",
        "price": 107
    }, {
        "date": "2012-03-08",
        "price": 89
    }, {
        "date": "2012-03-09",
        "price": 75
    }, {
        "date": "2012-03-10",
        "price": 132
    }, {
        "date": "2012-03-11",
        "price": 158
    }, {
        "date": "2012-03-12",
        "price": 56
    }, {
        "date": "2012-03-13",
        "price": 169
    }, {
        "date": "2012-03-14",
        "price": 24
    }, {
        "date": "2012-03-15",
        "price": 147
    }],
    "valueAxes": [{
        "logarithmic": true,
        "dashLength": 1,
        "guides": [{
            "dashLength": 6,
            "inside": true,
            "label": "average",
            "lineAlpha": 1,
            "value": 90.4
        }],
        "position": "left"
    }],
    "graphs": [{
        "bullet": "round",
        "id": "g1",
        "bulletBorderAlpha": 1,
        "bulletColor": "#FFFFFF",
        "bulletSize": 7,
        "lineThickness": 2,
        "title": "Price",
        "type": "smoothedLine",
        "useLineColorForBulletBorder": true,
        "valueField": "price"
    }],
    "chartScrollbar": {},
    "chartCursor": {
        "valueLineEnabled": true,
        "valueLineBalloonEnabled": true,
        "valueLineAlpha": 0.5,
        "fullWidth": true,
        "cursorAlpha": 0.05
    },
    "dataDateFormat": "YYYY-MM-DD",
    "categoryField": "date",
    "categoryAxis": {
        "parseDates": true
    },
    "export": {
        "enabled": true
    }
});

chart.addListener("dataUpdated", zoomChart);

function zoomChart() {
    chart.zoomToDates(new Date(2012, 2, 2), new Date(2012, 2, 10));
}

</script> 
<!--chart4 start--> 
<script>
// generate data
var chartData = [];

function generateChartData() {
    var firstDate = new Date();
    firstDate.setTime(firstDate.getTime() - 10 * 24 * 60 * 60 * 1000);

    for (var i = firstDate.getTime(); i < (firstDate.getTime() + 10 * 24 * 60 * 60 * 1000); i += 60 * 60 * 1000) {
        var newDate = new Date(i);

        if (i == firstDate.getTime()) {
            var value1 = Math.round(Math.random() * 10) + 1;
        } else {
            var value1 = Math.round(chartData[chartData.length - 1].value1 / 100 * (90 + Math.round(Math.random() * 20)) * 100) / 100;
        }

        if (newDate.getHours() == 12) {
            // we set daily data on 12th hour only
            var value2 = Math.round(Math.random() * 12) + 1;
            chartData.push({
                date: newDate,
                value1: value1,
                value2: value2
            });
        } else {
            chartData.push({
                date: newDate,
                value1: value1
            });
        }
    }
}

generateChartData();

var chart = AmCharts.makeChart("land-chart4", {
    "type": "serial",
    "theme": "light",
    "marginRight": 80,
    "dataProvider": chartData,
    "valueAxes": [{
        "axisAlpha": 0.1
    }],

    "graphs": [{
        "balloonText": "[[title]]: [[value]]",
        "columnWidth": 20,
        "fillAlphas": 1,
        "title": "daily",
        "type": "column",
        "valueField": "value2"
    }, {
        "balloonText": "[[title]]: [[value]]",
        "lineThickness": 2,
        "title": "intra-day",
        "valueField": "value1"
    }],
    "zoomOutButtonRollOverAlpha": 0.15,
    "chartCursor": {
        "categoryBalloonDateFormat": "MMM DD JJ:NN",
        "cursorPosition": "mouse",
        "showNextAvailable": true
    },
    "autoMarginOffset": 5,
    "columnWidth": 1,
    "categoryField": "date",
    "categoryAxis": {
        "minPeriod": "hh",
        "parseDates": true
    },
    "export": {
        "enabled": true
    }
});
</script> 
<!--chart5 start--> 
<script>
var chart = AmCharts.makeChart("land-chart5", {
    "theme": "light",
    "type": "serial",
	"startDuration": 2,
    "dataProvider": [{
        "country": "USA",
        "visits": 4025,
        "color": "#FF0F00"
    }, {
        "country": "China",
        "visits": 1882,
        "color": "#FF6600"
    }, {
        "country": "Japan",
        "visits": 1809,
        "color": "#FF9E01"
    }, {
        "country": "Germany",
        "visits": 1322,
        "color": "#FCD202"
    }, {
        "country": "UK",
        "visits": 1122,
        "color": "#F8FF01"
    }, {
        "country": "France",
        "visits": 1114,
        "color": "#B0DE09"
    }, {
        "country": "India",
        "visits": 984,
        "color": "#04D215"
    }, {
        "country": "Spain",
        "visits": 711,
        "color": "#0D8ECF"
    }, {
        "country": "Netherlands",
        "visits": 665,
        "color": "#0D52D1"
    }, {
        "country": "Russia",
        "visits": 580,
        "color": "#2A0CD0"
    }, {
        "country": "South Korea",
        "visits": 443,
        "color": "#8A0CCF"
    }, {
        "country": "Canada",
        "visits": 441,
        "color": "#CD0D74"
    }, {
        "country": "Brazil",
        "visits": 395,
        "color": "#754DEB"
    }, {
        "country": "Italy",
        "visits": 386,
        "color": "#DDDDDD"
    }, {
        "country": "Australia",
        "visits": 384,
        "color": "#999999"
    }, {
        "country": "Taiwan",
        "visits": 338,
        "color": "#333333"
    }, {
        "country": "Poland",
        "visits": 328,
        "color": "#000000"
    }],
    "valueAxes": [{
        "position": "left",
        "title": "Visitors"
    }],
    "graphs": [{
        "balloonText": "[[category]]: <b>[[value]]</b>",
        "fillColorsField": "color",
        "fillAlphas": 1,
        "lineAlpha": 0.1,
        "type": "column",
        "valueField": "visits"
    }],
    "depth3D": 20,
	"angle": 30,
    "chartCursor": {
        "categoryBalloonEnabled": false,
        "cursorAlpha": 0,
        "zoomable": false
    },    
    "categoryField": "country",
    "categoryAxis": {
        "gridPosition": "start",
        "labelRotation": 90
    },
    "export": {
    	"enabled": true
     }

});
jQuery('.chart-input').off().on('input change',function() {
	var property	= jQuery(this).data('property');
	var target		= chart;
	chart.startDuration = 0;

	if ( property == 'topRadius') {
		target = chart.graphs[0];
      	if ( this.value == 0 ) {
          this.value = undefined;
      	}
	}

	target[property] = this.value;
	chart.validateNow();
});
</script> 
<!--chart6 start--> 
<script>
var chart = AmCharts.makeChart("land-chart6", {
  "type": "serial",
  "theme": "light",
  "dataDateFormat": "YYYY-MM-DD",
  "precision": 2,
  "valueAxes": [{
    "id": "v1",
    "title": "Sales",
    "position": "left",
    "autoGridCount": false,
    "labelFunction": function(value) {
      return "$" + Math.round(value) + "M";
    }
  }, {
    "id": "v2",
    "title": "Market Days",
    "gridAlpha": 0,
    "position": "right",
    "autoGridCount": false
  }],
  "graphs": [{
    "id": "g3",
    "valueAxis": "v1",
    "lineColor": "#e1ede9",
    "fillColors": "#e1ede9",
    "fillAlphas": 1,
    "type": "column",
    "title": "Actual Sales",
    "valueField": "sales2",
    "clustered": false,
    "columnWidth": 0.5,
    "legendValueText": "$[[value]]M",
    "balloonText": "[[title]]<br/><b style='font-size: 130%'>$[[value]]M</b>"
  }, {
    "id": "g4",
    "valueAxis": "v1",
    "lineColor": "#62cf73",
    "fillColors": "#62cf73",
    "fillAlphas": 1,
    "type": "column",
    "title": "Target Sales",
    "valueField": "sales1",
    "clustered": false,
    "columnWidth": 0.3,
    "legendValueText": "$[[value]]M",
    "balloonText": "[[title]]<br/><b style='font-size: 130%'>$[[value]]M</b>"
  }, {
    "id": "g1",
    "valueAxis": "v2",
    "bullet": "round",
    "bulletBorderAlpha": 1,
    "bulletColor": "#FFFFFF",
    "bulletSize": 5,
    "hideBulletsCount": 50,
    "lineThickness": 2,
    "lineColor": "#20acd4",
    "type": "smoothedLine",
    "title": "Market Days",
    "useLineColorForBulletBorder": true,
    "valueField": "market1",
    "balloonText": "[[title]]<br/><b style='font-size: 130%'>[[value]]</b>"
  }, {
    "id": "g2",
    "valueAxis": "v2",
    "bullet": "round",
    "bulletBorderAlpha": 1,
    "bulletColor": "#FFFFFF",
    "bulletSize": 5,
    "hideBulletsCount": 50,
    "lineThickness": 2,
    "lineColor": "#e1ede9",
    "type": "smoothedLine",
    "dashLength": 5,
    "title": "Market Days ALL",
    "useLineColorForBulletBorder": true,
    "valueField": "market2",
    "balloonText": "[[title]]<br/><b style='font-size: 130%'>[[value]]</b>"
  }],
  "chartScrollbar": {
    "graph": "g1",
    "oppositeAxis": false,
    "offset": 30,
    "scrollbarHeight": 50,
    "backgroundAlpha": 0,
    "selectedBackgroundAlpha": 0.1,
    "selectedBackgroundColor": "#888888",
    "graphFillAlpha": 0,
    "graphLineAlpha": 0.5,
    "selectedGraphFillAlpha": 0,
    "selectedGraphLineAlpha": 1,
    "autoGridCount": true,
    "color": "#AAAAAA"
  },
  "chartCursor": {
    "pan": true,
    "valueLineEnabled": true,
    "valueLineBalloonEnabled": true,
    "cursorAlpha": 0,
    "valueLineAlpha": 0.2
  },
  "categoryField": "date",
  "categoryAxis": {
    "parseDates": true,
    "dashLength": 1,
    "minorGridEnabled": true
  },
  "legend": {
    "useGraphSettings": true,
    "position": "top"
  },
  "balloon": {
    "borderThickness": 1,
    "shadowAlpha": 0
  },
  "export": {
   "enabled": true
  },
  "dataProvider": [{
    "date": "2013-01-16",
    "market1": 71,
    "market2": 75,
    "sales1": 5,
    "sales2": 8
  }, {
    "date": "2013-01-17",
    "market1": 74,
    "market2": 78,
    "sales1": 4,
    "sales2": 6
  }, {
    "date": "2013-01-18",
    "market1": 78,
    "market2": 88,
    "sales1": 5,
    "sales2": 2
  }, {
    "date": "2013-01-19",
    "market1": 85,
    "market2": 89,
    "sales1": 8,
    "sales2": 9
  }, {
    "date": "2013-01-20",
    "market1": 82,
    "market2": 89,
    "sales1": 9,
    "sales2": 6
  }, {
    "date": "2013-01-21",
    "market1": 83,
    "market2": 85,
    "sales1": 3,
    "sales2": 5
  }, {
    "date": "2013-01-22",
    "market1": 88,
    "market2": 92,
    "sales1": 5,
    "sales2": 7
  }, {
    "date": "2013-01-23",
    "market1": 85,
    "market2": 90,
    "sales1": 7,
    "sales2": 6
  }, {
    "date": "2013-01-24",
    "market1": 85,
    "market2": 91,
    "sales1": 9,
    "sales2": 5
  }, {
    "date": "2013-01-25",
    "market1": 80,
    "market2": 84,
    "sales1": 5,
    "sales2": 8
  }, {
    "date": "2013-01-26",
    "market1": 87,
    "market2": 92,
    "sales1": 4,
    "sales2": 8
  }, {
    "date": "2013-01-27",
    "market1": 84,
    "market2": 87,
    "sales1": 3,
    "sales2": 4
  }, {
    "date": "2013-01-28",
    "market1": 83,
    "market2": 88,
    "sales1": 5,
    "sales2": 7
  }, {
    "date": "2013-01-29",
    "market1": 84,
    "market2": 87,
    "sales1": 5,
    "sales2": 8
  }, {
    "date": "2013-01-30",
    "market1": 81,
    "market2": 85,
    "sales1": 4,
    "sales2": 7
  }]
});
</script> 
<!--chart7 start--> 
<script type="text/javascript">
			AmCharts.makeChart("land-chart7",
				{
					"type": "serial",
					"categoryField": "category",
					"startDuration": 1,
					"path": "http://www.amcharts.com/lib/3/",
					"categoryAxis": {
						"gridPosition": "start"
					},
					"trendLines": [],
					"graphs": [
						{
							"balloonText": "[[title]] of [[category]]:[[value]]",
							"bullet": "round",
							"id": "AmGraph-1",
							"lineColor": "#F58025",
							"title": "graph 1",
							"valueField": "column-1"
						}
					],
					"guides": [],
					"valueAxes": [
						{
							"id": "ValueAxis-1",
							"title": "Ratio"
						}
					],
					"allLabels": [],
					"balloon": {},
					"titles": [
						{
							"id": "Title-1",
							"size": 15,
							"text": "Computer-Student Ratios"
						}
					],
					"dataProvider": [
						{
							"category": "2011",
							"column-1": "1.8"
						},
						{
							"category": "2012",
							"column-1": "1.3"
						},
						{
							"category": "2013",
							"column-1": "1.4"
						}
					]
				}
			);
		</script>
<!--chart8 start--> 
<script>
var chart = AmCharts.makeChart("land-chart8", {
  type: "serial",
  theme: "light",
  dataProvider: [{
    "date": "2012-01-01",
    "value": 8
  }, {
    "date": "2012-01-01",
    "value": 8
  }, {
    "date": "2012-01-02",
    "value": 10
  }, {
    "date": "2012-01-03",
    "value": 12
  }, {
    "date": "2012-01-04",
    "value": 14
  }, {
    "date": "2012-01-05",
    "value": 11
  }, {
    "date": "2012-01-06",
    "value": 6
  }, {
    "date": "2012-01-07",
    "value": 7
  }, {
    "date": "2012-01-08",
    "value": 9
  }, {
    "date": "2012-01-09",
    "value": 13
  }, {
    "date": "2012-01-10",
    "value": 15
  }, {
    "date": "2012-01-11",
    "value": 19
  }, {
    "date": "2012-01-12",
    "value": 21
  }, {
    "date": "2012-01-13",
    "value": 22
  }, {
    "date": "2012-01-14",
    "value": 20
  }, {
    "date": "2012-01-15",
    "value": 18
  }, {
    "date": "2012-01-16",
    "value": 14
  }, {
    "date": "2012-01-17",
    "value": 16
  }, {
    "date": "2012-01-18",
    "value": 18
  }, {
    "date": "2012-01-19",
    "value": 17
  }, {
    "date": "2012-01-20",
    "value": 15
  }, {
    "date": "2012-01-21",
    "value": 12
  }, {
    "date": "2012-01-22",
    "value": 10
  }, {
    "date": "2012-01-23",
    "value": 8
  }],

  pathToImages: "//cdn.amcharts.com/lib/3/images/",
  dataDateFormat: "YYYY-MM-DD",
  categoryField: "date",

  categoryAxis: {
    parseDates: true,
    minPeriod: "DD",
    gridAlpha: 0.1,
    minorGridAlpha: 0.1,
    axisAlpha: 0,
    minorGridEnabled: true,
    inside: true
  },

  valueAxes: [{

    tickLength: 0,
    axisAlpha: 0,
    showFirstLabel: false,
    showLastLabel: false,

    guides: [{
      value: 10,
      toValue: 20,
      fillColor: "#00CC00",
      inside: true,
      fillAlpha: 0.2,
      lineAlpha: 0
    }]

  }],


  graphs: [{
    lineColor: "#00CC00",
    valueField: "value",
    dashLength: 3,
    bullet: "round",
    balloonText: "[[category]]<br><b><span style='font-size:14px;'>value:[[value]]</span></b>"
  }],

  chartCursor: {},
  chartScrollbar: {}
});
jQuery(document).ready(function() {
  jQuery(".btn-add").on("click",function() {
    var chartData = chart.dataProvider;
    var rnd       = parseInt(Math.random() * chartData.length);
    var date      = chartData[rnd].date;
    var guide     = new AmCharts.Guide();
    var exist     = false;

    // Get previous instance
    for ( i in chart.categoryAxis.guides ) {
      if ( chart.categoryAxis.guides[i].label == date ) {
        guide = chart.categoryAxis.guides[i];
      }
    }

    // Change some settings
    guide.label = date;
    guide.position = "top";
    guide.lineAlpha = 1;
    guide.labelRotation = 90;
    guide.lineColor = AmCharts.randomColor();

    // Add new guide and validate chart
    if ( !guide.date ) {
      guide.date = date;
      chart.categoryAxis.addGuide(guide);
    }
    chart.validateNow();
  });

  jQuery(".btn-remove").on("click",function() {
    chart.categoryAxis.guides.pop();
    chart.validateNow();
  });
});
</script>
<!--chart9 start-->
<script>var chart = AmCharts.makeChart( "land-chart9", {
  "type": "serial",
  "theme": "light",
  "dataProvider": [ {
    "country": "USA",
    "visits": 2025
  }, {
    "country": "China",
    "visits": 1882
  }, {
    "country": "Japan",
    "visits": 1809
  }, {
    "country": "Germany",
    "visits": 1322
  }, {
    "country": "UK",
    "visits": 1122
  }, {
    "country": "France",
    "visits": 1114
  }, {
    "country": "India",
    "visits": 984
  }, {
    "country": "Spain",
    "visits": 711
  }, {
    "country": "Netherlands",
    "visits": 665
  }, {
    "country": "Russia",
    "visits": 580
  }, {
    "country": "South Korea",
    "visits": 443
  }, {
    "country": "Canada",
    "visits": 441
  }, {
    "country": "Brazil",
    "visits": 395
  } ],
  "valueAxes": [ {
    "gridColor": "#FFFFFF",
    "gridAlpha": 0.2,
    "dashLength": 0
  } ],
  "gridAboveGraphs": true,
  "startDuration": 1,
  "graphs": [ {
    "balloonText": "[[category]]: <b>[[value]]</b>",
    "fillAlphas": 0.8,
    "lineAlpha": 0.2,
    "type": "column",
    "valueField": "visits"
  } ],
  "chartCursor": {
    "categoryBalloonEnabled": false,
    "cursorAlpha": 0,
    "zoomable": false
  },
  "categoryField": "country",
  "categoryAxis": {
    "gridPosition": "start",
    "gridAlpha": 0,
    "tickPosition": "start",
    "tickLength": 20
  },
  "export": {
    "enabled": true
  }

} );</script>
<!--chart10 start--> 
<script type="text/javascript">
			AmCharts.makeChart("land-chart10",
				{
					"type": "serial",
					"categoryField": "date",
					"autoMarginOffset": 40,
					"marginRight": 60,
					"marginTop": 60,
					"fontSize": 13,
					"theme": "light",
					"categoryAxis": {
						"parseDates": true
					},
					"chartCursor": {
						"enabled": true
					},
					"chartScrollbar": {
						"enabled": true,
						"graph": "g1",
						"graphType": "line",
						"scrollbarHeight": 30
					},
					"trendLines": [],
					"graphs": [
						{
							"balloonText": "Open:<b>[[open]]</b><br>Low:<b>[[low]]</b><br>High:<b>[[high]]</b><br>Close:<b>[[close]]</b><br>",
							"closeField": "close",
							"fillAlphas": 0.9,
							"fillColors": "#7f8da9",
							"highField": "high",
							"id": "g1",
							"lineColor": "#7f8da9",
							"lowField": "low",
							"negativeFillColors": "#db4c3c",
							"negativeLineColor": "#db4c3c",
							"openField": "open",
							"title": "Price:",
							"type": "candlestick",
							"valueField": "close"
						}
					],
					"guides": [
						{
							"id": "Guide-1"
						},
						{
							"id": "Guide-2"
						}
					],
					"valueAxes": [
						{
							"id": "ValueAxis-1"
						}
					],
					"allLabels": [],
					"balloon": {},
					"titles": [],
					"dataProvider": [
						{
							"date": "2011-08-01",
							"open": "136.65",
							"high": "136.96",
							"low": "134.15",
							"close": "136.49"
						},
						{
							"date": "2011-08-02",
							"open": "135.26",
							"high": "135.95",
							"low": "131.50",
							"close": "131.85"
						},
						{
							"date": "2011-08-05",
							"open": "132.90",
							"high": "135.27",
							"low": "128.30",
							"close": "135.25"
						},
						{
							"date": "2011-08-06",
							"open": "134.94",
							"high": "137.24",
							"low": "132.63",
							"close": "135.03"
						},
						{
							"date": "2011-08-07",
							"open": "136.76",
							"high": "136.86",
							"low": "132.00",
							"close": "134.01"
						},
						{
							"date": "2011-08-08",
							"open": "131.11",
							"high": "133.00",
							"low": "125.09",
							"close": "126.39"
						},
						{
							"date": "2011-08-09",
							"open": "123.12",
							"high": "127.75",
							"low": "120.30",
							"close": "125.00"
						},
						{
							"date": "2011-08-12",
							"open": "128.32",
							"high": "129.35",
							"low": "126.50",
							"close": "127.79"
						},
						{
							"date": "2011-08-13",
							"open": "128.29",
							"high": "128.30",
							"low": "123.71",
							"close": "124.03"
						}
					]
				}
			);
		</script>
<!--chart11 start-->
<script>
var chartData = generateChartData();

function generateChartData() {
  var chartData = [];
  var firstDate = new Date( 2012, 0, 1 );
  firstDate.setDate( firstDate.getDate() - 500 );
  firstDate.setHours( 0, 0, 0, 0 );

  for ( var i = 0; i < 500; i++ ) {
    var newDate = new Date( firstDate );
    newDate.setDate( newDate.getDate() + i );

    var value = Math.round( Math.random() * ( 40 + i ) ) + 100 + i;

    chartData.push( {
      date: newDate,
      value: value
    } );
  }
  return chartData;
}


var chart = AmCharts.makeChart( "land-chart11", {

  type: "stock",
  "theme": "light",
 
  dataSets: [ {
    color: "#b0de09",
    fieldMappings: [ {
      fromField: "value",
      toField: "value"
    } ],
    dataProvider: chartData,
    categoryField: "date"
  } ],

  panels: [ {
    showCategoryAxis: true,
    title: "Value",
    eraseAll: false,
    allLabels: [ {
      x: 0,
      y: 115,
      text: "Click on the pencil icon on top-right to start drawing",
      align: "center",
      size: 16
    } ],

    stockGraphs: [ {
      id: "g1",
      valueField: "value",
      useDataSetColors: false
    } ],


    stockLegend: {
      valueTextRegular: " ",
      markerType: "none"
    },

    drawingIconsEnabled: true
  } ],

  chartScrollbarSettings: {
    graph: "g1"
  },
  chartCursorSettings: {
    valueBalloonsEnabled: true
  },
  
} );</script>
<!--chart12 start-->   
<script>var chartData = generateChartData();

function generateChartData() {
  var chartData = [];
  var firstDate = new Date( 2012, 0, 1 );
  firstDate.setDate( firstDate.getDate() - 1000 );
  firstDate.setHours( 0, 0, 0, 0 );

  for ( var i = 0; i < 1000; i++ ) {
    var newDate = new Date( firstDate );
    newDate.setHours( 0, i, 0, 0 );

    var a = Math.round( Math.random() * ( 40 + i ) ) + 100 + i;
    var b = Math.round( Math.random() * 100000000 );

    chartData.push( {
      date: newDate,
      value: a,
      volume: b
    } );
  }
  return chartData;
}

var chart = AmCharts.makeChart( "land-chart12", {
  "type": "stock",
  "theme": "light",

  "categoryAxesSettings": {
    "minPeriod": "mm"
  },

  "dataSets": [ {
    "color": "#b0de09",
    "fieldMappings": [ {
      "fromField": "value",
      "toField": "value"
    }, {
      "fromField": "volume",
      "toField": "volume"
    } ],

    "dataProvider": chartData,
    "categoryField": "date"
  } ],

  "panels": [ {
    "showCategoryAxis": false,
    "title": "Value",
    "percentHeight": 70,

    "stockGraphs": [ {
      "id": "g1",
      "valueField": "value",
      "type": "smoothedLine",
      "lineThickness": 2,
      "bullet": "round"
    } ],


    "stockLegend": {
      "valueTextRegular": " ",
      "markerType": "none"
    }
  }, {
    "title": "Volume",
    "percentHeight": 30,
    "stockGraphs": [ {
      "valueField": "volume",
      "type": "column",
      "cornerRadiusTop": 2,
      "fillAlphas": 1
    } ],

    "stockLegend": {
      "valueTextRegular": " ",
      "markerType": "none"
    }
  } ],

  "chartScrollbarSettings": {
    "graph": "g1",
    "usePeriod": "10mm",
    "position": "top"
  },

  "chartCursorSettings": {
    "valueBalloonsEnabled": true
  },


  "panelsSettings": {
    "usePrefixes": true
  },

  "export": {
    "enabled": true,
    "position": "bottom-right"
  }
} );</script> 

<!--chart13 start-->
<script>
var gaugeChart = AmCharts.makeChart( "land-chart13", {
  "type": "gauge",
  "theme": "light",
  "axes": [ {
    "axisThickness": 1,
    "axisAlpha": 0.2,
    "tickAlpha": 0.2,
    "valueInterval": 20,
    "bands": [ {
      "color": "#84b761",
      "endValue": 90,
      "startValue": 0
    }, {
      "color": "#fdd400",
      "endValue": 130,
      "startValue": 90
    }, {
      "color": "#cc4748",
      "endValue": 220,
      "innerRadius": "95%",
      "startValue": 130
    } ],
    "bottomText": "0 km/h",
    "bottomTextYOffset": -20,
    "endValue": 220
  } ],
  "arrows": [ {} ],
  "export": {
    "enabled": true
  }
} );

setInterval( randomValue, 2000 );

// set random value
function randomValue() {
  var value = Math.round( Math.random() * 200 );
  if ( gaugeChart ) {
    if ( gaugeChart.arrows ) {
      if ( gaugeChart.arrows[ 0 ] ) {
        if ( gaugeChart.arrows[ 0 ].setValue ) {
          gaugeChart.arrows[ 0 ].setValue( value );
          gaugeChart.axes[ 0 ].setBottomText( value + " km/h" );
        }
      }
    }
  }
}</script> 
<!--chart14 start-->
<script>var gaugeChart = AmCharts.makeChart("land-chart14", {
  "type": "gauge",
  "theme": "light",
  "axes": [{
    "axisAlpha": 0,
    "tickAlpha": 0,
    "labelsEnabled": false,
    "startValue": 0,
    "endValue": 100,
    "startAngle": 0,
    "endAngle": 270,
    "bands": [{
      "color": "#eee",
      "startValue": 0,
      "endValue": 100,
      "radius": "100%",
      "innerRadius": "85%"
    }, {
      "color": "#84b761",
      "startValue": 0,
      "endValue": 80,
      "radius": "100%",
      "innerRadius": "85%",
      "balloonText": "90%"
    }, {
      "color": "#eee",
      "startValue": 0,
      "endValue": 100,
      "radius": "80%",
      "innerRadius": "65%"
    }, {
      "color": "#fdd400",
      "startValue": 0,
      "endValue": 35,
      "radius": "80%",
      "innerRadius": "65%",
      "balloonText": "35%"
    }, {
      "color": "#eee",
      "startValue": 0,
      "endValue": 100,
      "radius": "60%",
      "innerRadius": "45%"
    }, {
      "color": "#cc4748",
      "startValue": 0,
      "endValue": 92,
      "radius": "60%",
      "innerRadius": "45%",
      "balloonText": "92%"
    }, {
      "color": "#eee",
      "startValue": 0,
      "endValue": 100,
      "radius": "40%",
      "innerRadius": "25%"
    }, {
      "color": "#67b7dc",
      "startValue": 0,
      "endValue": 68,
      "radius": "40%",
      "innerRadius": "25%",
      "balloonText": "68%"
    }]
  }],
  "allLabels": [{
    "text": "First option",
    "x": "49%",
    "y": "5%",
    "size": 15,
    "bold": true,
    "color": "#84b761",
    "align": "right"
  }, {
    "text": "Second option",
    "x": "49%",
    "y": "15%",
    "size": 15,
    "bold": true,
    "color": "#fdd400",
    "align": "right"
  }, {
    "text": "Third option",
    "x": "49%",
    "y": "24%",
    "size": 15,
    "bold": true,
    "color": "#cc4748",
    "align": "right"
  }, {
    "text": "Fourth option",
    "x": "49%",
    "y": "33%",
    "size": 15,
    "bold": true,
    "color": "#67b7dc",
    "align": "right"
  }],
  "export": {
    "enabled": true
  }
});</script> 
<!--chart15 start-->
<script>
var chart = AmCharts.makeChart( "land-chart15", {
  "theme": "light",
  "type": "gauge",
  "axes": [ {
    "axisColor": "#67b7dc",
    "axisThickness": 3,
    "endValue": 240,
    "gridInside": false,
    "inside": false,
    "radius": "100%",
    "valueInterval": 20,
    "tickColor": "#67b7dc"
  }, {
    "axisColor": "#fdd400",
    "axisThickness": 3,
    "endValue": 160,
    "radius": "80%",
    "valueInterval": 20,
    "tickColor": "#fdd400"
  } ],
  "arrows": [ {
    "color": "#67b7dc",
    "innerRadius": "20%",
    "nailRadius": 0,
    "radius": "85%"
  } ],
  "export": {
    "enabled": true
  }
} );

setInterval( randomValue, 2000 );

// set random value
function randomValue() {
  var value = Math.round( Math.random() * 240 );
  chart.arrows[ 0 ].setValue( value );
}</script> 
<!--chart16 start--> 
<script>var chart = AmCharts.makeChart("land-chart16", {
    "type": "serial",
    "theme": "patterns",
    "marginRight": 40,
    "marginLeft": 40,
    "autoMarginOffset": 20,
    "dataDateFormat": "YYYY-MM-DD",
    "valueAxes": [{
        "id": "v1",
        "axisAlpha": 0,
        "position": "left",
        "ignoreAxisWidth":true
    }],
    "balloon": {
        "borderThickness": 1,
        "shadowAlpha": 0
    },
    "graphs": [{
        "id": "g1",
        "balloon":{
          "drop":true,
          "adjustBorderColor":false,
          "color":"#ffffff",
          "type":"smoothedLine"
        },
        "fillAlphas":0.2,
        "bullet": "round",
        "bulletBorderAlpha": 1,
        "bulletColor": "#FFFFFF",
        "bulletSize": 5,
        "hideBulletsCount": 50,
        "lineThickness": 2,
        "title": "red line",
        "useLineColorForBulletBorder": true,
        "valueField": "value",
        "balloonText": "<span style='font-size:18px;'>[[value]]</span>"
    }],

    "chartCursor": {
        "valueLineEnabled": true,
        "valueLineBalloonEnabled": true,
        "cursorAlpha":0,
        "zoomable":false,
        "valueZoomable":true,
        "valueLineAlpha":0.5
    },
    "valueScrollbar":{
     "autoGridCount":true,
      "color":"#000000",
      "scrollbarHeight":50
    },
    "categoryField": "date",
    "categoryAxis": {
        "parseDates": true,
        "dashLength": 1,
        "minorGridEnabled": true
    },

    "dataProvider": [{
        "date": "2012-07-27",
        "value": 13
    }, {
        "date": "2012-07-28",
        "value": 11
    }, {
        "date": "2012-07-29",
        "value": 15
    }, {
        "date": "2012-07-30",
        "value": 16
    }, {
        "date": "2012-07-31",
        "value": 18
    }, {
        "date": "2012-08-01",
        "value": 13
    }, {
        "date": "2012-08-02",
        "value": 22
    }, {
        "date": "2012-08-03",
        "value": 23
    }, {
        "date": "2012-08-04",
        "value": 20
    }, {
        "date": "2012-08-05",
        "value": 17
    }, {
        "date": "2012-08-06",
        "value": 16
    }, {
        "date": "2012-08-07",
        "value": 18
    }, {
        "date": "2012-08-08",
        "value": 21
    }, {
        "date": "2012-08-09",
        "value": 26
    }, {
        "date": "2012-08-10",
        "value": 24
    }, {
        "date": "2012-08-11",
        "value": 29
    }, {
        "date": "2012-08-12",
        "value": 32
    }, {
        "date": "2012-08-13",
        "value": 18
    }, {
        "date": "2012-08-14",
        "value": 24
    }, {
        "date": "2012-08-15",
        "value": 22
    }, {
        "date": "2012-08-16",
        "value": 18
    }, {
        "date": "2012-08-17",
        "value": 19
    }, {
        "date": "2012-08-18",
        "value": 14
    }, {
        "date": "2012-08-19",
        "value": 15
    }, {
        "date": "2012-08-20",
        "value": 12
    }, {
        "date": "2012-08-21",
        "value": 8
    }, {
        "date": "2012-08-22",
        "value": 9
    }, {
        "date": "2012-08-23",
        "value": 8
    }, {
        "date": "2012-08-24",
        "value": 7
    }, {
        "date": "2012-08-25",
        "value": 5
    }, {
        "date": "2012-08-26",
        "value": 11
    }, {
        "date": "2012-08-27",
        "value": 13
    }, {
        "date": "2012-08-28",
        "value": 18
    }, {
        "date": "2012-08-29",
        "value": 20
    }, {
        "date": "2012-08-30",
        "value": 29
    }, {
        "date": "2012-08-31",
        "value": 33
    }, {
        "date": "2012-09-01",
        "value": 42
    }, {
        "date": "2012-09-02",
        "value": 35
    }, {
        "date": "2012-09-03",
        "value": 31
    }, {
        "date": "2012-09-04",
        "value": 47
    }, {
        "date": "2012-09-05",
        "value": 52
    }, {
        "date": "2012-09-06",
        "value": 46
    }, {
        "date": "2012-09-07",
        "value": 41
    }, {
        "date": "2012-09-08",
        "value": 43
    }, {
        "date": "2012-09-09",
        "value": 40
    }, {
        "date": "2012-09-10",
        "value": 39
    }, {
        "date": "2012-09-11",
        "value": 34
    }, {
        "date": "2012-09-12",
        "value": 29
    }, {
        "date": "2012-09-13",
        "value": 34
    }, {
        "date": "2012-09-14",
        "value": 37
    }, {
        "date": "2012-09-15",
        "value": 42
    }, {
        "date": "2012-09-16",
        "value": 49
    }, {
        "date": "2012-09-17",
        "value": 46
    }, {
        "date": "2012-09-18",
        "value": 47
    }, {
        "date": "2012-09-19",
        "value": 55
    }, {
        "date": "2012-09-20",
        "value": 59
    }, {
        "date": "2012-09-21",
        "value": 58
    }, {
        "date": "2012-09-22",
        "value": 57
    }, {
        "date": "2012-09-23",
        "value": 61
    }, {
        "date": "2012-09-24",
        "value": 59
    }, {
        "date": "2012-09-25",
        "value": 67
    }, {
        "date": "2012-09-26",
        "value": 65
    }, {
        "date": "2012-09-27",
        "value": 61
    }, {
        "date": "2012-09-28",
        "value": 66
    }, {
        "date": "2012-09-29",
        "value": 69
    }, {
        "date": "2012-09-30",
        "value": 71
    }, {
        "date": "2012-10-01",
        "value": 67
    }, {
        "date": "2012-10-02",
        "value": 63
    }, {
        "date": "2012-10-03",
        "value": 46
    }, {
        "date": "2012-10-04",
        "value": 32
    }, {
        "date": "2012-10-05",
        "value": 21
    }, {
        "date": "2012-10-06",
        "value": 18
    }, {
        "date": "2012-10-07",
        "value": 21
    }, {
        "date": "2012-10-08",
        "value": 28
    }, {
        "date": "2012-10-09",
        "value": 27
    }, {
        "date": "2012-10-10",
        "value": 36
    }, {
        "date": "2012-10-11",
        "value": 33
    }, {
        "date": "2012-10-12",
        "value": 31
    }, {
        "date": "2012-10-13",
        "value": 30
    }, {
        "date": "2012-10-14",
        "value": 34
    }, {
        "date": "2012-10-15",
        "value": 38
    }, {
        "date": "2012-10-16",
        "value": 37
    }, {
        "date": "2012-10-17",
        "value": 44
    }, {
        "date": "2012-10-18",
        "value": 49
    }, {
        "date": "2012-10-19",
        "value": 53
    }, {
        "date": "2012-10-20",
        "value": 57
    }, {
        "date": "2012-10-21",
        "value": 60
    }, {
        "date": "2012-10-22",
        "value": 61
    }, {
        "date": "2012-10-23",
        "value": 69
    }, {
        "date": "2012-10-24",
        "value": 67
    }, {
        "date": "2012-10-25",
        "value": 72
    }, {
        "date": "2012-10-26",
        "value": 77
    }, {
        "date": "2012-10-27",
        "value": 75
    }, {
        "date": "2012-10-28",
        "value": 70
    }, {
        "date": "2012-10-29",
        "value": 72
    }, {
        "date": "2012-10-30",
        "value": 70
    }, {
        "date": "2012-10-31",
        "value": 72
    }, {
        "date": "2012-11-01",
        "value": 73
    }, {
        "date": "2012-11-02",
        "value": 67
    }, {
        "date": "2012-11-03",
        "value": 68
    }, {
        "date": "2012-11-04",
        "value": 65
    }, {
        "date": "2012-11-05",
        "value": 71
    }, {
        "date": "2012-11-06",
        "value": 75
    }, {
        "date": "2012-11-07",
        "value": 74
    }, {
        "date": "2012-11-08",
        "value": 71
    }, {
        "date": "2012-11-09",
        "value": 76
    }, {
        "date": "2012-11-10",
        "value": 77
    }, {
        "date": "2012-11-11",
        "value": 81
    }, {
        "date": "2012-11-12",
        "value": 83
    }, {
        "date": "2012-11-13",
        "value": 80
    }, {
        "date": "2012-11-14",
        "value": 81
    }, {
        "date": "2012-11-15",
        "value": 87
    }, {
        "date": "2012-11-16",
        "value": 82
    }, {
        "date": "2012-11-17",
        "value": 86
    }, {
        "date": "2012-11-18",
        "value": 80
    }, {
        "date": "2012-11-19",
        "value": 87
    }, {
        "date": "2012-11-20",
        "value": 83
    }, {
        "date": "2012-11-21",
        "value": 85
    }, {
        "date": "2012-11-22",
        "value": 84
    }, {
        "date": "2012-11-23",
        "value": 82
    }, {
        "date": "2012-11-24",
        "value": 73
    }, {
        "date": "2012-11-25",
        "value": 71
    }, {
        "date": "2012-11-26",
        "value": 75
    }, {
        "date": "2012-11-27",
        "value": 79
    }, {
        "date": "2012-11-28",
        "value": 70
    }, {
        "date": "2012-11-29",
        "value": 73
    }, {
        "date": "2012-11-30",
        "value": 61
    }, {
        "date": "2012-12-01",
        "value": 62
    }, {
        "date": "2012-12-02",
        "value": 66
    }, {
        "date": "2012-12-03",
        "value": 65
    }, {
        "date": "2012-12-04",
        "value": 73
    }, {
        "date": "2012-12-05",
        "value": 79
    }, {
        "date": "2012-12-06",
        "value": 78
    }, {
        "date": "2012-12-07",
        "value": 78
    }, {
        "date": "2012-12-08",
        "value": 78
    }, {
        "date": "2012-12-09",
        "value": 74
    }, {
        "date": "2012-12-10",
        "value": 73
    }, {
        "date": "2012-12-11",
        "value": 75
    }, {
        "date": "2012-12-12",
        "value": 70
    }, {
        "date": "2012-12-13",
        "value": 77
    }, {
        "date": "2012-12-14",
        "value": 67
    }, {
        "date": "2012-12-15",
        "value": 62
    }, {
        "date": "2012-12-16",
        "value": 64
    }, {
        "date": "2012-12-17",
        "value": 61
    }, {
        "date": "2012-12-18",
        "value": 59
    }, {
        "date": "2012-12-19",
        "value": 53
    }, {
        "date": "2012-12-20",
        "value": 54
    }, {
        "date": "2012-12-21",
        "value": 56
    }, {
        "date": "2012-12-22",
        "value": 59
    }, {
        "date": "2012-12-23",
        "value": 58
    }, {
        "date": "2012-12-24",
        "value": 55
    }, {
        "date": "2012-12-25",
        "value": 52
    }, {
        "date": "2012-12-26",
        "value": 54
    }, {
        "date": "2012-12-27",
        "value": 50
    }, {
        "date": "2012-12-28",
        "value": 50
    }, {
        "date": "2012-12-29",
        "value": 51
    }, {
        "date": "2012-12-30",
        "value": 52
    }, {
        "date": "2012-12-31",
        "value": 58
    }, {
        "date": "2013-01-01",
        "value": 60
    }, {
        "date": "2013-01-02",
        "value": 67
    }, {
        "date": "2013-01-03",
        "value": 64
    }, {
        "date": "2013-01-04",
        "value": 66
    }, {
        "date": "2013-01-05",
        "value": 60
    }, {
        "date": "2013-01-06",
        "value": 63
    }, {
        "date": "2013-01-07",
        "value": 61
    }, {
        "date": "2013-01-08",
        "value": 60
    }, {
        "date": "2013-01-09",
        "value": 65
    }, {
        "date": "2013-01-10",
        "value": 75
    }, {
        "date": "2013-01-11",
        "value": 77
    }, {
        "date": "2013-01-12",
        "value": 78
    }, {
        "date": "2013-01-13",
        "value": 70
    }, {
        "date": "2013-01-14",
        "value": 70
    }, {
        "date": "2013-01-15",
        "value": 73
    }, {
        "date": "2013-01-16",
        "value": 71
    }, {
        "date": "2013-01-17",
        "value": 74
    }, {
        "date": "2013-01-18",
        "value": 78
    }, {
        "date": "2013-01-19",
        "value": 85
    }, {
        "date": "2013-01-20",
        "value": 82
    }, {
        "date": "2013-01-21",
        "value": 83
    }, {
        "date": "2013-01-22",
        "value": 88
    }, {
        "date": "2013-01-23",
        "value": 85
    }, {
        "date": "2013-01-24",
        "value": 85
    }, {
        "date": "2013-01-25",
        "value": 80
    }, {
        "date": "2013-01-26",
        "value": 87
    }, {
        "date": "2013-01-27",
        "value": 84
    }, {
        "date": "2013-01-28",
        "value": 83
    }, {
        "date": "2013-01-29",
        "value": 84
    }, {
        "date": "2013-01-30",
        "value": 81
    }]
});</script>
<!--chart17 start-->
<script>var chart = AmCharts.makeChart("land-chart17", {
    "type": "serial",
    "theme": "light",
    "marginRight": 40,
    "marginLeft": 40,
    "autoMarginOffset": 20,
    "mouseWheelZoomEnabled":true,
    "dataDateFormat": "YYYY-MM-DD",
    "valueAxes": [{
        "id": "v1",
        "axisAlpha": 0,
        "position": "left",
        "ignoreAxisWidth":true
    }],
    "balloon": {
        "borderThickness": 1,
        "shadowAlpha": 0
    },
    "graphs": [{
        "id": "g1",
        "balloon":{
          "drop":true,
          "adjustBorderColor":false,
          "color":"#ffffff"
        },
        "bullet": "round",
        "bulletBorderAlpha": 1,
        "bulletColor": "#FFFFFF",
        "bulletSize": 5,
        "hideBulletsCount": 50,
        "lineThickness": 2,
        "title": "red line",
        "useLineColorForBulletBorder": true,
        "valueField": "value",
        "balloonText": "<span style='font-size:18px;'>[[value]]</span>"
    }],
    "chartScrollbar": {
        "graph": "g1",
        "oppositeAxis":false,
        "offset":30,
        "scrollbarHeight": 80,
        "backgroundAlpha": 0,
        "selectedBackgroundAlpha": 0.1,
        "selectedBackgroundColor": "#888888",
        "graphFillAlpha": 0,
        "graphLineAlpha": 0.5,
        "selectedGraphFillAlpha": 0,
        "selectedGraphLineAlpha": 1,
        "autoGridCount":true,
        "color":"#AAAAAA"
    },
    "chartCursor": {
        "pan": true,
        "valueLineEnabled": true,
        "valueLineBalloonEnabled": true,
        "cursorAlpha":1,
        "cursorColor":"#258cbb",
        "limitToGraph":"g1",
        "valueLineAlpha":0.2,
        "valueZoomable":true
    },
    "valueScrollbar":{
      "oppositeAxis":false,
      "offset":50,
      "scrollbarHeight":10
    },
    "categoryField": "date",
    "categoryAxis": {
        "parseDates": true,
        "dashLength": 1,
        "minorGridEnabled": true
    },
    "export": {
        "enabled": true
    },
    "dataProvider": [{
        "date": "2012-07-27",
        "value": 13
    }, {
        "date": "2012-07-28",
        "value": 11
    }, {
        "date": "2012-07-29",
        "value": 15
    }, {
        "date": "2012-07-30",
        "value": 16
    }, {
        "date": "2012-07-31",
        "value": 18
    }, {
        "date": "2012-08-01",
        "value": 13
    }, {
        "date": "2012-08-02",
        "value": 22
    }, {
        "date": "2012-08-03",
        "value": 23
    }, {
        "date": "2012-08-04",
        "value": 20
    }, {
        "date": "2012-08-05",
        "value": 17
    }, {
        "date": "2012-08-06",
        "value": 16
    }, {
        "date": "2012-08-07",
        "value": 18
    }, {
        "date": "2012-08-08",
        "value": 21
    }, {
        "date": "2012-08-09",
        "value": 26
    }, {
        "date": "2012-08-10",
        "value": 24
    }, {
        "date": "2012-08-11",
        "value": 29
    }, {
        "date": "2012-08-12",
        "value": 32
    }, {
        "date": "2012-08-13",
        "value": 18
    }, {
        "date": "2012-08-14",
        "value": 24
    }, {
        "date": "2012-08-15",
        "value": 22
    }, {
        "date": "2012-08-16",
        "value": 18
    }, {
        "date": "2012-08-17",
        "value": 19
    }, {
        "date": "2012-08-18",
        "value": 14
    }, {
        "date": "2012-08-19",
        "value": 15
    }, {
        "date": "2012-08-20",
        "value": 12
    }, {
        "date": "2012-08-21",
        "value": 8
    }, {
        "date": "2012-08-22",
        "value": 9
    }, {
        "date": "2012-08-23",
        "value": 8
    }, {
        "date": "2012-08-24",
        "value": 7
    }, {
        "date": "2012-08-25",
        "value": 5
    }, {
        "date": "2012-08-26",
        "value": 11
    }, {
        "date": "2012-08-27",
        "value": 13
    }, {
        "date": "2012-08-28",
        "value": 18
    }, {
        "date": "2012-08-29",
        "value": 20
    }, {
        "date": "2012-08-30",
        "value": 29
    }, {
        "date": "2012-08-31",
        "value": 33
    }, {
        "date": "2012-09-01",
        "value": 42
    }, {
        "date": "2012-09-02",
        "value": 35
    }, {
        "date": "2012-09-03",
        "value": 31
    }, {
        "date": "2012-09-04",
        "value": 47
    }, {
        "date": "2012-09-05",
        "value": 52
    }, {
        "date": "2012-09-06",
        "value": 46
    }, {
        "date": "2012-09-07",
        "value": 41
    }, {
        "date": "2012-09-08",
        "value": 43
    }, {
        "date": "2012-09-09",
        "value": 40
    }, {
        "date": "2012-09-10",
        "value": 39
    }, {
        "date": "2012-09-11",
        "value": 34
    }, {
        "date": "2012-09-12",
        "value": 29
    }, {
        "date": "2012-09-13",
        "value": 34
    }, {
        "date": "2012-09-14",
        "value": 37
    }, {
        "date": "2012-09-15",
        "value": 42
    }, {
        "date": "2012-09-16",
        "value": 49
    }, {
        "date": "2012-09-17",
        "value": 46
    }, {
        "date": "2012-09-18",
        "value": 47
    }, {
        "date": "2012-09-19",
        "value": 55
    }, {
        "date": "2012-09-20",
        "value": 59
    }, {
        "date": "2012-09-21",
        "value": 58
    }, {
        "date": "2012-09-22",
        "value": 57
    }, {
        "date": "2012-09-23",
        "value": 61
    }, {
        "date": "2012-09-24",
        "value": 59
    }, {
        "date": "2012-09-25",
        "value": 67
    }, {
        "date": "2012-09-26",
        "value": 65
    }, {
        "date": "2012-09-27",
        "value": 61
    }, {
        "date": "2012-09-28",
        "value": 66
    }, {
        "date": "2012-09-29",
        "value": 69
    }, {
        "date": "2012-09-30",
        "value": 71
    }, {
        "date": "2012-10-01",
        "value": 67
    }, {
        "date": "2012-10-02",
        "value": 63
    }, {
        "date": "2012-10-03",
        "value": 46
    }, {
        "date": "2012-10-04",
        "value": 32
    }, {
        "date": "2012-10-05",
        "value": 21
    }, {
        "date": "2012-10-06",
        "value": 18
    }, {
        "date": "2012-10-07",
        "value": 21
    }, {
        "date": "2012-10-08",
        "value": 28
    }, {
        "date": "2012-10-09",
        "value": 27
    }, {
        "date": "2012-10-10",
        "value": 36
    }, {
        "date": "2012-10-11",
        "value": 33
    }, {
        "date": "2012-10-12",
        "value": 31
    }, {
        "date": "2012-10-13",
        "value": 30
    }, {
        "date": "2012-10-14",
        "value": 34
    }, {
        "date": "2012-10-15",
        "value": 38
    }, {
        "date": "2012-10-16",
        "value": 37
    }, {
        "date": "2012-10-17",
        "value": 44
    }, {
        "date": "2012-10-18",
        "value": 49
    }, {
        "date": "2012-10-19",
        "value": 53
    }, {
        "date": "2012-10-20",
        "value": 57
    }, {
        "date": "2012-10-21",
        "value": 60
    }, {
        "date": "2012-10-22",
        "value": 61
    }, {
        "date": "2012-10-23",
        "value": 69
    }, {
        "date": "2012-10-24",
        "value": 67
    }, {
        "date": "2012-10-25",
        "value": 72
    }, {
        "date": "2012-10-26",
        "value": 77
    }, {
        "date": "2012-10-27",
        "value": 75
    }, {
        "date": "2012-10-28",
        "value": 70
    }, {
        "date": "2012-10-29",
        "value": 72
    }, {
        "date": "2012-10-30",
        "value": 70
    }, {
        "date": "2012-10-31",
        "value": 72
    }, {
        "date": "2012-11-01",
        "value": 73
    }, {
        "date": "2012-11-02",
        "value": 67
    }, {
        "date": "2012-11-03",
        "value": 68
    }, {
        "date": "2012-11-04",
        "value": 65
    }, {
        "date": "2012-11-05",
        "value": 71
    }, {
        "date": "2012-11-06",
        "value": 75
    }, {
        "date": "2012-11-07",
        "value": 74
    }, {
        "date": "2012-11-08",
        "value": 71
    }, {
        "date": "2012-11-09",
        "value": 76
    }, {
        "date": "2012-11-10",
        "value": 77
    }, {
        "date": "2012-11-11",
        "value": 81
    }, {
        "date": "2012-11-12",
        "value": 83
    }, {
        "date": "2012-11-13",
        "value": 80
    }, {
        "date": "2012-11-14",
        "value": 81
    }, {
        "date": "2012-11-15",
        "value": 87
    }, {
        "date": "2012-11-16",
        "value": 82
    }, {
        "date": "2012-11-17",
        "value": 86
    }, {
        "date": "2012-11-18",
        "value": 80
    }, {
        "date": "2012-11-19",
        "value": 87
    }, {
        "date": "2012-11-20",
        "value": 83
    }, {
        "date": "2012-11-21",
        "value": 85
    }, {
        "date": "2012-11-22",
        "value": 84
    }, {
        "date": "2012-11-23",
        "value": 82
    }, {
        "date": "2012-11-24",
        "value": 73
    }, {
        "date": "2012-11-25",
        "value": 71
    }, {
        "date": "2012-11-26",
        "value": 75
    }, {
        "date": "2012-11-27",
        "value": 79
    }, {
        "date": "2012-11-28",
        "value": 70
    }, {
        "date": "2012-11-29",
        "value": 73
    }, {
        "date": "2012-11-30",
        "value": 61
    }, {
        "date": "2012-12-01",
        "value": 62
    }, {
        "date": "2012-12-02",
        "value": 66
    }, {
        "date": "2012-12-03",
        "value": 65
    }, {
        "date": "2012-12-04",
        "value": 73
    }, {
        "date": "2012-12-05",
        "value": 79
    }, {
        "date": "2012-12-06",
        "value": 78
    }, {
        "date": "2012-12-07",
        "value": 78
    }, {
        "date": "2012-12-08",
        "value": 78
    }, {
        "date": "2012-12-09",
        "value": 74
    }, {
        "date": "2012-12-10",
        "value": 73
    }, {
        "date": "2012-12-11",
        "value": 75
    }, {
        "date": "2012-12-12",
        "value": 70
    }, {
        "date": "2012-12-13",
        "value": 77
    }, {
        "date": "2012-12-14",
        "value": 67
    }, {
        "date": "2012-12-15",
        "value": 62
    }, {
        "date": "2012-12-16",
        "value": 64
    }, {
        "date": "2012-12-17",
        "value": 61
    }, {
        "date": "2012-12-18",
        "value": 59
    }, {
        "date": "2012-12-19",
        "value": 53
    }, {
        "date": "2012-12-20",
        "value": 54
    }, {
        "date": "2012-12-21",
        "value": 56
    }, {
        "date": "2012-12-22",
        "value": 59
    }, {
        "date": "2012-12-23",
        "value": 58
    }, {
        "date": "2012-12-24",
        "value": 55
    }, {
        "date": "2012-12-25",
        "value": 52
    }, {
        "date": "2012-12-26",
        "value": 54
    }, {
        "date": "2012-12-27",
        "value": 50
    }, {
        "date": "2012-12-28",
        "value": 50
    }, {
        "date": "2012-12-29",
        "value": 51
    }, {
        "date": "2012-12-30",
        "value": 52
    }, {
        "date": "2012-12-31",
        "value": 58
    }, {
        "date": "2013-01-01",
        "value": 60
    }, {
        "date": "2013-01-02",
        "value": 67
    }, {
        "date": "2013-01-03",
        "value": 64
    }, {
        "date": "2013-01-04",
        "value": 66
    }, {
        "date": "2013-01-05",
        "value": 60
    }, {
        "date": "2013-01-06",
        "value": 63
    }, {
        "date": "2013-01-07",
        "value": 61
    }, {
        "date": "2013-01-08",
        "value": 60
    }, {
        "date": "2013-01-09",
        "value": 65
    }, {
        "date": "2013-01-10",
        "value": 75
    }, {
        "date": "2013-01-11",
        "value": 77
    }, {
        "date": "2013-01-12",
        "value": 78
    }, {
        "date": "2013-01-13",
        "value": 70
    }, {
        "date": "2013-01-14",
        "value": 70
    }, {
        "date": "2013-01-15",
        "value": 73
    }, {
        "date": "2013-01-16",
        "value": 71
    }, {
        "date": "2013-01-17",
        "value": 74
    }, {
        "date": "2013-01-18",
        "value": 78
    }, {
        "date": "2013-01-19",
        "value": 85
    }, {
        "date": "2013-01-20",
        "value": 82
    }, {
        "date": "2013-01-21",
        "value": 83
    }, {
        "date": "2013-01-22",
        "value": 88
    }, {
        "date": "2013-01-23",
        "value": 85
    }, {
        "date": "2013-01-24",
        "value": 85
    }, {
        "date": "2013-01-25",
        "value": 80
    }, {
        "date": "2013-01-26",
        "value": 87
    }, {
        "date": "2013-01-27",
        "value": 84
    }, {
        "date": "2013-01-28",
        "value": 83
    }, {
        "date": "2013-01-29",
        "value": 84
    }, {
        "date": "2013-01-30",
        "value": 81
    }]
});

chart.addListener("rendered", zoomChart);

zoomChart();

function zoomChart() {
    chart.zoomToIndexes(chart.dataProvider.length - 40, chart.dataProvider.length - 1);
}</script>
<!--chart18 start-->  
<script>
$(function () {
    $('#land-chart18').highcharts({
        chart: {
            type: 'pie',
            options3d: {
                enabled: true,
                alpha: 45,
                beta: 0
            }
        },
        title: {
            text: 'Browser market shares at a specific website, 2014'
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                depth: 35,
                dataLabels: {
                    enabled: true,
                    format: '{point.name}'
                }
            }
        },
        series: [{
            type: 'pie',
            name: 'Browser share',
            data: [
                ['Firefox', 45.0],
                ['IE', 26.8],
                {
                    name: 'Chrome',
                    y: 12.8,
                    sliced: true,
                    selected: true
                },
                ['Safari', 8.5],
                ['Opera', 6.2],
                ['Others', 0.7]
            ]
        }]
    });
});
</script> 
<!--chart19 start--> 
<script>
var chart;
var legend;
var selected;

var types = [{
  type: "Fossil Energy",
  percent: 70,
  color: "#ff9e01",
  subs: [{
    type: "Oil",
    percent: 15
  }, {
    type: "Coal",
    percent: 35
  }, {
    type: "Nuclear",
    percent: 20
  }]
}, {
  type: "Green Energy",
  percent: 30,
  color: "#b0de09",
  subs: [{
    type: "Hydro",
    percent: 15
  }, {
    type: "Wind",
    percent: 10
  }, {
    type: "Other",
    percent: 5
  }]
}];

function generateChartData() {
  var chartData = [];
  for (var i = 0; i < types.length; i++) {
    if (i == selected) {
      for (var x = 0; x < types[i].subs.length; x++) {
        chartData.push({
          type: types[i].subs[x].type,
          percent: types[i].subs[x].percent,
          color: types[i].color,
          pulled: true
        });
      }
    } else {
      chartData.push({
        type: types[i].type,
        percent: types[i].percent,
        color: types[i].color,
        id: i
      });
    }
  }
  return chartData;
}

AmCharts.makeChart("land-chart19", {
  "type": "pie",
  "dataProvider": generateChartData(),
  "labelText": "[[title]]: [[value]]",
  "balloonText": "[[title]]: [[value]]",
  "titleField": "type",
  "valueField": "percent",
  "outlineColor": "#FFFFFF",
  "outlineAlpha": 0.8,
  "outlineThickness": 2,
  "colorField": "color",
  "pulledField": "pulled",
  "titles": [{
    "text": "Click a slice to see the details"
  }],
  "listeners": [{
    "event": "clickSlice",
    "method": function(event) {
      var chart = event.chart;
      if (event.dataItem.dataContext.id != undefined) {
        selected = event.dataItem.dataContext.id;
      } else {
        selected = undefined;
      }
      chart.dataProvider = generateChartData();
      chart.validateData();
    }
  }]
});
</script> 
<!--chart20 start--> 
<script>
var chart = AmCharts.makeChart("land-chart20",
{
    "type": "serial",
	"theme": "light",
    "dataProvider": [{
        "name": "John",
        "points": 35654,
        "color": "#7F8DA9",
        "bullet": "//www.amcharts.com/lib/3/images/0.gif"
    }, {
        "name": "Damon",
        "points": 65456,
        "color": "#FEC514",
        "bullet": "//www.amcharts.com/lib/3/images/1.gif"
    }, {
        "name": "Patrick",
        "points": 45724,
        "color": "#DB4C3C",
        "bullet": "//www.amcharts.com/lib/3/images/2.gif"
    }, {
        "name": "Mark",
        "points": 13654,
        "color": "#DAF0FD",
        "bullet": "//www.amcharts.com//lib/3/images/3.gif"
    }],
    "valueAxes": [{
        "maximum": 80000,
        "minimum": 0,
        "axisAlpha": 0,
        "dashLength": 4,
        "position": "left"
    }],
    "startDuration": 1,
    "graphs": [{
        "balloonText": "<span style='font-size:13px;'>[[category]]: <b>[[value]]</b></span>",
        "bulletOffset": 16,
        "bulletSize": 34,
        "colorField": "color",
        "cornerRadiusTop": 8,
        "customBulletField": "bullet",
        "fillAlphas": 0.8,
        "lineAlpha": 0,
        "type": "column",
        "valueField": "points"
    }],
    "marginTop": 0,
    "marginRight": 0,
    "marginLeft": 0,
    "marginBottom": 0,
    "autoMargins": false,
    "categoryField": "name",
    "categoryAxis": {
        "axisAlpha": 0,
        "gridAlpha": 0,
        "inside": true,
        "tickLength": 0
    },
    "export": {
    	"enabled": true
     }
});
</script> 
<!--chart21 start--> 
<script>
var chart = AmCharts.makeChart( "land-chart21", {
  "type": "serial",
  "theme": "light",
  "dataProvider": [ {
    "name": "Income A",
    "open": 0,
    "close": 11.13,
    "color": "#54cb6a",
    "balloonValue": 11.13
  }, {
    "name": "Income B",
    "open": 11.13,
    "close": 15.81,
    "color": "#54cb6a",
    "balloonValue": 4.68
  }, {
    "name": "Total Income",
    "open": 0,
    "close": 15.81,
    "color": "#169b2f",
    "balloonValue": 15.81
  }, {
    "name": "Expenses A",
    "open": 12.92,
    "close": 15.81,
    "color": "#cc4b48",
    "balloonValue": 2.89
  }, {
    "name": "Expenses B",
    "open": 8.64,
    "close": 12.92,
    "color": "#cc4b48",
    "balloonValue": 4.24
  }, {
    "name": "Revenue",
    "open": 0,
    "close": 8.64,
    "color": "#1c8ceb",
    "balloonValue": 11.13
  } ],
  "valueAxes": [ {
    "axisAlpha": 0,
    "gridAlpha": 0.1,
    "position": "left"
  } ],
  "startDuration": 1,
  "graphs": [ {
    "balloonText": "<span style='color:[[color]]'>[[category]]</span><br><b>$[[balloonValue]] Mln</b>",
    "colorField": "color",
    "fillAlphas": 0.8,
    "labelText": "$[[balloonValue]]",
    "lineColor": "#BBBBBB",
    "openField": "open",
    "type": "column",
    "valueField": "close"
  } ],
  "trendLines": [ {
    "dashLength": 3,
    "finalCategory": "Income B",
    "finalValue": 11.13,
    "initialCategory": "Income A",
    "initialValue": 11.13,
    "lineColor": "#888888"
  }, {
    "dashLength": 3,
    "finalCategory": "Expenses A",
    "finalValue": 15.81,
    "initialCategory": "Income B",
    "initialValue": 15.81,
    "lineColor": "#888888"
  }, {
    "dashLength": 3,
    "finalCategory": "Expenses B",
    "finalValue": 12.92,
    "initialCategory": "Expenses A",
    "initialValue": 12.92,
    "lineColor": "#888888"
  }, {
    "dashLength": 3,
    "finalCategory": "Revenue",
    "finalValue": 8.64,
    "initialCategory": "Expenses B",
    "initialValue": 8.64,
    "lineColor": "#888888"
  } ],
  "columnWidth": 0.6,
  "categoryField": "name",
  "categoryAxis": {
    "gridPosition": "start",
    "axisAlpha": 0,
    "gridAlpha": 0.1
  },
  "export": {
    "enabled": true
  }
} );
</script> 
<!--chart22 start--> 
<script>
$(function () {
    $('#land-chart22').highcharts({

        chart: {
            type: 'column'
        },

        title: {
            text: 'Total fruit consumtion, grouped by gender'
        },

        xAxis: {
            categories: ['Apples', 'Oranges', 'Pears', 'Grapes', 'Bananas']
        },

        yAxis: {
            allowDecimals: false,
            min: 0,
            title: {
                text: 'Number of fruits'
            }
        },

        tooltip: {
            formatter: function () {
                return '<b>' + this.x + '</b><br/>' +
                    this.series.name + ': ' + this.y + '<br/>' +
                    'Total: ' + this.point.stackTotal;
            }
        },

        plotOptions: {
            column: {
                stacking: 'normal'
            }
        },

        series: [{
            name: 'John',
            data: [5, 3, 4, 7, 2],
            stack: 'male'
        }, {
            name: 'Joe',
            data: [3, 4, 4, 2, 5],
            stack: 'male'
        }, {
            name: 'Jane',
            data: [2, 5, 6, 2, 1],
            stack: 'female'
        }, {
            name: 'Janet',
            data: [3, 0, 4, 4, 3],
            stack: 'female'
        }]
    });
});
</script> 
<!--chart23 start--> 
<script type="text/javascript">
			var chart = AmCharts.makeChart( "land-chart23", {
  "type": "serial",
  "theme": "light",
  "dataProvider": [ {
    "year": 2005,
    "value": 11.5,
    "error": 5
  }, {
    "year": 2006,
    "value": 26.2,
    "error": 5
  }, {
    "year": 2007,
    "value": 30.1,
    "error": 5
  }, {
    "year": 2008,
    "value": 29.5,
    "error": 7
  }, {
    "year": 2009,
    "value": 24.6,
    "error": 10
  } ],
  "balloon": {
    "textAlign": "left"
  },
  "valueAxes": [ {
    "id": "v1",
    "axisAlpha": 0
  } ],
  "startDuration": 1,
  "graphs": [ {
    "balloonText": "value:<b>[[value]]</b><br>error:<b>[[error]]</b>",
    "bullet": "yError",
    "bulletSize": 10,
    "errorField": "error",
    "lineThickness": 2,
    "valueField": "value",
    "bulletAxis": "v1",
    "fillAlphas": 0
  }, {
    "bullet": "round",
    "bulletBorderAlpha": 1,
    "bulletBorderColor": "#FFFFFF",
    "lineAlpha": 0,
    "lineThickness": 2,
    "showBalloon": false,
    "valueField": "value"

  } ],
  "chartCursor": {
    "cursorAlpha": 0,
    "cursorPosition": "mouse",
    "graphBulletSize": 1,
    "zoomable": false
  },
  "categoryField": "year",
  "categoryAxis": {
    "gridPosition": "start",
    "axisAlpha": 0
  },
  "export": {
    "enabled": true
  }
} );
		</script>
<!--chart24 start--> 
<script>var chart;

var chartData = [{
    country: "USA",
    year2004: 3.5,
    year2005: 4.2},
{
    country: "UK",
    year2004: 1.7,
    year2005: 3.1},
{
    country: "Canada",
    year2004: 2.8,
    year2005: 2.9},
{
    country: "Japan",
    year2004: 2.6,
    year2005: 2.3},
{
    country: "France",
    year2004: 1.4,
    year2005: 2.1},
{
    country: "Brazil",
    year2004: 2.6,
    year2005: 4.9},
{
    country: "Russia",
    year2004: 6.4,
    year2005: 7.2},
{
    country: "India",
    year2004: 8.0,
    year2005: 7.1},
{
    country: "China",
    year2004: 9.9,
    year2005: 10.1}];


AmCharts.ready(function() {
    // SERIAL CHART
    chart = new AmCharts.AmSerialChart();
    chart.dataProvider = chartData;
    chart.categoryField = "country";
    chart.fontSize = 14;
    chart.startDuration = 1;
    chart.plotAreaFillAlphas = 0.2;
    // the following two lines makes chart 3D
    chart.angle = 30;
    chart.depth3D = 40;

    // AXES
    // category
    var categoryAxis = chart.categoryAxis;
    categoryAxis.gridAlpha = 0.2;
    categoryAxis.gridPosition = "start";
    categoryAxis.axisColor = "#DADADA";
    categoryAxis.axisAlpha = 1;
    categoryAxis.dashLength = 5;

    // value
    var valueAxis = new AmCharts.ValueAxis();
    valueAxis.stackType = "3d"; // This line makes chart 3D stacked (columns are placed one behind another)
    valueAxis.gridAlpha = 0.2;
    valueAxis.axisColor = "#DADADA";
    valueAxis.axisAlpha = 1;
    valueAxis.dashLength = 5;
    valueAxis.unit = "%";
    chart.addValueAxis(valueAxis);

    // GRAPHS         
    // first graph
    var graph1 = new AmCharts.AmGraph();
    graph1.title = "2004";
    graph1.valueField = "year2004";
    graph1.type = "column";
    graph1.lineAlpha = 0;
    graph1.lineColor = "#D2CB00";
    graph1.fillAlphas = 1;
    graph1.balloonText = "GDP grow in [[category]] (2004): [[value]]";
    chart.addGraph(graph1);

    // second graph
    var graph2 = new AmCharts.AmGraph();
    graph2.title = "2005";
    graph2.valueField = "year2005";
    graph2.type = "column";
    graph2.lineAlpha = 0;
    graph2.lineColor = "#BEDF66";
    graph2.fillAlphas = 1;
    graph2.balloonText = "GDP grow in [[category]] (2005): [[value]]";
    chart.addGraph(graph2);

    chart.write("land-chart24");
});</script>
<!--top to bottom scroll--> 
<script type="text/javascript">
		$(function(){
			$('#vertical-ticker1').totemticker({
				row_height	:	'100px',
				next		:	'#ticker-next',
				previous	:	'#ticker-previous',
				stop		:	'#stop',
				start		:	'#start',
				mousestop	:	true
			});
		});
	</script>