<!--STYLE-->
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css';?>"/>
<!--content-->
<div class="content_wrapper padlr0">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h1>Project Conception</h1>
      </div>
      <!--form start-->
      <div class="col-lg-12 top_ct" >
        <div class="col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-4 col-sm-offset-0">
          <div class="form-group">
            <input type="text" class="form-control lbl_move" label="Name of Property" />
          </div>
        </div>
        <div class="col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-4 col-sm-offset-0">
          <div class="form-group">
            <input type="text" class="form-control lbl_move" label="Option Name" />
          </div>
        </div>
      </div>
      <!--form end-->
      <div class="col-lg-12 clear">
        <div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0">
          <div class="col-lg-12">
            <div class="row">
              <div class="step_by_liner animated slideInDown"></div>
              <ul class="step_by stepby_mb60">
                <li>
                  <div class="step_by_sep stepsep_active animated_0_4s slideInRight" id="tag-step-1">
                    <p>1</p>
                  </div>
                  <p class="stepli_p1">Specification & Amenities</p>
                </li>
                <li>
                  <div class="step_by_sep animated slideInRight" id="tag-step-2">
                    <p>2</p>
                  </div>
                  <p class="stepli_p2">Drawings & Documents</p>
                </li>
                <li class="opacity_08">
                  <div class="step_by_sep animated_1_5s slideInRight" id="tag-step-3">
                    <p>3</p>
                  </div>
                  <p class="stepli_p3">Action</p>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0 cnt_sliders">
          <div id="carousel-example-generic" class="carousel slide" data-ride="carousel"> 
            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox"> 
              <!--step 1-->
              <div class="item active">
                <div class="list-div">
                  <div class="col-lg-6 col-md-6">
                    <h2 class="sp-tl">Special Features</h2>
                    <div class="table-responsive topsp" style="border:none !important;">
                      <table class="table">
                        <tbody>
                          <tr>
                            <td width="10%" style="border-top:none !important;"><input class="parent_text" type="text" /></td>
                            <td width="1%" class="action_btns_td" style="border-top:none !important;"><ul class="action_btns">
                                <li> <a class="mainTr_1" href="#"> <span data-toggle="tooltip" data-placement="left" data-original-title="Delete"> <i class="fa fa-trash-o"></i></span></a> </li>
                              </ul></td>
                          </tr>
                          <tr>
                            <td width="10%"  style="border-top:none !important;"><input class="parent_text" type="text" /></td>
                            <td width="1%" class="action_btns_td"  style="border-top:none !important;"><ul class="action_btns">
                                <li> <a class="mainTr_1" href="#"> <span data-toggle="tooltip" data-placement="left" data-original-title="Delete"><i class="fa fa-trash-o"></i></span> </a> </li>
                              </ul></td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                  </div>
                  <div class="col-lg-6 col-md-6">
                    <h2 class="sp-tl">Amenities</h2>
                    <div class="table-responsive topsp" style="border:none !important;">
                      <table class="table">
                        <tbody>
                          <tr>
                            <td width="10%" style="border-top:none !important;"><input class="parent_text" type="text" /></td>
                            <td width="1%" class="action_btns_td" style="border-top:none !important;"><ul class="action_btns">
                                <li> <a class="mainTr_1" href="#"> <span data-toggle="tooltip" data-placement="left" data-original-title="Delete"> <i class="fa fa-trash-o"></i></span></a> </li>
                              </ul></td>
                          </tr>
                          <tr>
                            <td width="10%"  style="border-top:none !important;"><input class="parent_text" type="text" /></td>
                            <td width="1%" class="action_btns_td"  style="border-top:none !important;"><ul class="action_btns">
                                <li> <a class="mainTr_1" href="#"> <span data-toggle="tooltip" data-placement="left" data-original-title="Delete"><i class="fa fa-trash-o"></i></span> </a> </li>
                              </ul></td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
                <div class="cont_bt-list">
                  <ul>
                    <!--<li><a href="#carousel-example-generic" data-slide="prev">Back</a></li>-->
                    <li><a href="#carousel-example-generic" data-slide="next" class="cbtn">Continue <i class="fa fa-chevron-circle-right"></i></a></li>
                  </ul>
                </div>
              </div>
              
              <!--step 1--> 
              <!--step 2-->
              <div class="item">
                <div class="col-lg-6 col-md-6">
                  <h2 class="sp-tl">Drawings</h2>
                  <div class="table-responsive topsp">
                    <table class="table" style=" margin-bottom:0px;">
                      <thead>
                        <tr>
                          <th>Drawing Name</th>
                          <th>Document Description</th>
                          <th>Action</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td width="7%"><input class="parent_text" type="text" /></td>
                          <td width="10%"><textarea class="parent_texts"></textarea></td>
                          <td width="7%" class="action_btns_td"><ul class="action_btns">
                              <li> <a class="mainTrDelete_1" href="#"> <span  data-toggle="tooltip" data-placement="left" data-original-title="Documents Attached" class="btn-file butclr_imp"><i class="fa fa-paperclip dcm_atch"></i>
                                <input type="file">
                                </span> </a> </li>
                              <li> <a class="mainTr_1" href="#"> <span data-toggle="tooltip" data-placement="left" data-original-title="Document Views"><i class="fa fa-eye"></i></span> </a> </li>
                              <li> <a class="mainTr_1" href="#"> <span data-toggle="tooltip" data-placement="left" data-original-title="Document Delete"><i class="fa fa-trash-o"></i></span> </a> </li>
                            </ul></td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
                <div class="col-lg-6 col-md-6">
                  <h2 class="sp-tl">Documents</h2>
                  <div class="table-responsive topsp">
                    <table class="table" style=" margin-bottom:0px;">
                      <thead>
                        <tr>
                          <th>Document Type</th>
                          <th>Document Description</th>
                          <th>Action</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td width="7%"><input class="parent_text" type="text" /></td>
                          <td width="10%"><textarea class="parent_texts"></textarea></td>
                          <td width="8%" class="action_btns_td"><ul class="action_btns">
                              <li> <a class="mainTrDelete_1" href="#"> <span  data-toggle="tooltip" data-placement="left" data-original-title="Documents Attached" class="btn-file butclr_imp"><i class="fa fa-paperclip dcm_atch"></i>
                                <input type="file">
                                </span> </a> </li>
                              <li> <a class="mainTr_1" href="#"> <span data-toggle="tooltip" data-placement="left" data-original-title="Document Views"><i class="fa fa-eye"></i></span> </a> </li>
                              <li> <a class="mainTr_1" href="#"> <span data-toggle="tooltip" data-placement="left" data-original-title="Document Delete"><i class="fa fa-trash-o"></i></span> </a> </li>
                            </ul></td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
                <div class="drawings-full">
                  <h2 class="sp-tl">Consultants</h2>
                  <div class="table-responsive topsp" style="margin-top:10px; float:left;">
                    <table class="table" style=" margin-bottom:0px;">
                      <thead>
                        <tr>
                          <th>Consultant Name</th>
                          <th>Consultant Type</th>
                          <th>Fees %</th>
                          <th>Fees Amount</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td width="10%"><input class="parent_text" type="text" /></td>
                          <td width="10%"><input class="parent_text" type="text" /></td>
                          <td width="5%"><input class="parent_text" type="text" /></td>
                          <td width="5%"><input class="parent_text" type="text" /></td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
                <div class="cont_bt-list">
                  <ul>
                    <!-- <li><a href="#carousel-example-generic" data-slide="prev">Back</a></li>-->
                    <li><a href="#carousel-example-generic" data-slide="next" class="cbtn">Continue <i class="fa fa-chevron-circle-right"></i></a></li>
                  </ul>
                </div>
              </div>
              <!--step 2--> 
              <!--step 3-->
              <div class="item">
                <div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0">
                  <div class="maps-lis"> </div>
                  <div class="soil-type lbgs-soil">
                    <ul>
                      <li> <span>Soil Type</span>
                        <input class="parent_text" type="text" />
                      </li>
                      <li> <span>Ground Water Level</span>
                        <div class="select-style">
                          <select>
                            <option value="0">Good</option>
                            <option value="0">Normal</option>
                          </select>
                        </div>
                      </li>
                      <li>
                        <div class="radio_check top-mids">
                          <p>
                            <input type="checkbox" id="create-activitys" value="1" name="SoilTestReport">
                            <label style="position: relative; overflow: hidden;" class="ripple has-ripple" for="create-activitys">Govt Water Supply<span class="ripple-wrapper"></span><span class="ripple-wrapper"></span></label>
                          </p>
                        </div>
                      </li>
                      <li>
                        <div class="radio_check top-mids">
                          <p>
                            <input type="checkbox" id="elt" value="1" name="SoilTestReport">
                            <label style="position: relative; overflow: hidden;" class="ripple has-ripple" for="elt">Electricity<span class="ripple-wrapper"></span><span class="ripple-wrapper"></span></label>
                          </p>
                        </div>
                      </li>
                    </ul>
                  </div>
                  <div class="soil-type">
                    <h2 class="sp-tl">Government Norms</h2>
                    <ul>
                      <li> <span>FSI</span>
                        <input class="parent_text" type="text" />
                      </li>
                      <li> <span>Premium FSI</span>
                        <input class="parent_text" type="text" />
                      </li>
                      <li> <span>Guide Line Value</span>
                        <input class="parent_text" type="text" />
                      </li>
                      <li> <span>No of Floors</span>
                        <input class="parent_text" type="text" />
                      </li>
                      <li> <span>Expandable FSI %</span>
                        <input class="parent_text" type="text" />
                      </li>
                    </ul>
                  </div>
                  <div class="drawings-full">
                    <h2 class="sp-tl">Approval Details</h2>
                    <div class="table-responsive topsp" style="margin-top:10px;">
                      <table class="table tableWithFloatingHeader" style=" margin-bottom:0px;">
                        <thead>
                          <tr>
                            <th>Autority of Approval</th>
                            <th>Approval Date</th>
                            <th>Approval No</th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <td width="10%"><input class="parent_text" type="text" /></td>
                            <td width="10%"><input class="parent_text" type="text" /></td>
                            <td width="5%"><input class="parent_text" type="text" /></td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                  </div>
                  <div class="cont_bt-list">
                    <ul>
                      <!--<li><a href="#carousel-example-generic" data-slide="prev">Back</a></li>-->
                      <li><a href="#carousel-example-generic" data-slide="next" class="cbtn" onclick="maximizeDiv()">Continue <i class="fa fa-chevron-circle-right"></i></a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <!--step 3--> 
              <!--step 4-->
              <div class="item">
                <div class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0">
                  <h2 class="sp-tl">Expected Income</h2>
                  <div class="table-responsive topsp">
                    <table class="table">
                      <thead>
                        <tr>
                          <th>Description</th>
                          <th>Amount</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td width="8%"><input class="parent_text" type="text" /></td>
                          <td width="8%"><input class="parent_text"/></td>
                        </tr>
                        <tr>
                          <td align="right" class="rate_pri">Total Income</td>
                          <td style="border-right:none;"><input class="parent_text" type="text" placeholder="00.0"/></td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                  <h2 class="sp-tl">Expected Expenses</h2>
                  <div class="table-responsive topsp">
                    <table class="table">
                      <thead>
                        <tr>
                          <th>Description</th>
                          <th>Amount</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td width="8%"><input class="parent_text" type="text" /></td>
                          <td width="8%"><input class="parent_text"/></td>
                        </tr>
                        <tr>
                          <td align="right" class="rate_pri">Total Expenses</td>
                          <td style="border-right:none;"><input class="parent_text" type="text" placeholder="00.0"/></td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                  <h2 class="sp-tl">Net Profit</h2>
                  <div class="table-responsive topsp">
                    <table class="table">
                      <tbody>
                        <tr>
                          <td align="right" class="rate_pri" width="52%">Total</td>
                          <td style="border-right:none;"><input class="parent_text" type="text" placeholder="00.0"/></td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
                <div class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0">
                  <div class="chats-lft">
                    <h2 class="sp-tl">Construction Schedule</h2>
                    <div class="table-responsive topsp">
                    <table class="table">
                      <thead>
                        <tr>
                          <th>Year</th>
                          <th>Amount</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td width="2%"><input class="parent_text" type="text" /></td>
                          <td width="5%"><input class="parent_text"/></td>
                        </tr>
                    
                      </tbody>
                    </table>
                  </div>
                  
                    <div class="livechat"></div>
                  </div>
                  <div class="chats-lft">
                    <h2 class="sp-tl">Ratio Analysis</h2>
                    <div class="livechat"></div>
                  </div>
                </div>
                <div class="cont_bt-list">
                  <ul>
                    <!--<li><a href="#carousel-example-generic" data-slide="prev" onclick="maximizeDiv(false)">Back</a></li>-->
                    <li><a href="#carousel-example-generic" class="cbtn">Submit</a></li>
                  </ul>
                </div>
              </div>
              <!--step 4--> 
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!--table expand start--> 

<!--datepicker--> 
<script type="text/javascript">
$('.cnt_sliders .carousel').carousel({
 interval: false
})
</script> 
