<ul class="modl_lmenu">
	<h2>Vendor Portal</h2>
	<li><a href="javascript:void(0);" class="ripple modlsub_open"><i class="fa fa-university"></i> <span class="nav-label">Master Setup</span></a>
		<ul>
			<li><a href="dashboard.php" class="ripple">RFQ</a></li>
			<li><a href="javascript:void(0);" class="ripple">Received</a></li>
			<li><a href="javascript:void(0);" class="ripple">Sent</a></li>
		</ul>
	</li>
	<li><a href="javascript:void(0);" class="ripple"><i class="fa fa-camera"></i><span class="nav-label">Project images</span></a></li>
</ul>