<!--STYLE-->
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css';?>"/>
<style>
.panel {
	border-radius:0px !important;
}
.panel-info {
	border:none;
	border-top:none;
}
.ios_checkbox + div span::before {
color:#fff;
content:"No";
display:inline-block;
font-size:11px;
font-weight:600;
padding-top:3px;
position:absolute;
right:8px;
z-index:1;
}
.ios_checkbox:checked + div span::before {
color:#fff;
content:"Yes";
display:inline-block;
font-size:11px;
font-weight:600;
left:8px;
padding-top:3px;
position:absolute;
 z-index: 1;
}

</style>
<!--content-->
<div class="content_wrapper padlr0">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h1>Tender Enquiry</h1>
      </div>
      <!--form start-->
      <div class="col-lg-12 top_ct" >
        <div class="col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-4 col-sm-offset-0">
          <div class="form-group"> <span class="date_icon"><i class="fa fa-calendar"></i></span>
            <input type="text" name="lead_date" id="lead_date" class="form-control date_picker lbl_move" label="Reference Date" />
          </div>
        </div>
        <div class="col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-4 col-sm-offset-0">
          <div class="form-group">
            <input type="text" class="form-control lbl_move" label="Reference No" />
          </div>
        </div>
      </div>
      <!--form end--> 
      <!--accordion start-->
      
      <div class="col-lg-12 clear">
        <div id="accordion" class="panel-group"> 
          <!--General-->
          <div class="panel panel-info">
            <div data-target="#collapseOne" data-parent="#accordion" data-toggle="collapse" class="panel-heading collapsed panel_heads" id="panelheading-1">
              <h4 class="panel-title accordion-toggle defa_panels">General</h4>
            </div>
            <div class="panel-collapse collapse" id="collapseOne" style="height: 0px;">
              <div class="panel-body bgcolr">
                <div class="deft_act">
                  <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-12 col-sm-offset-0 clear">
                    <div class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0">
                      <div class="form-group">
                        <input type="text" class="form-control lbl_move" label="Name Of Work" />
                      </div>
                      <div class="form-group">
                        <input type="text" class="form-control lbl_move" label="Source Type" />
                      </div>
                      <div class="form-group">
                        <input type="text" class="form-control lbl_move" label="Source Name" />
                      </div>
                      <div class="form-group">
                        <input type="text" class="form-control lbl_move" label="Client Name" />
                      </div>
                    </div>
                    <div class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0">
                      <div class="form-group">
                        <input type="text" class="form-control lbl_move" label="Contact No" />
                      </div>
                      <div class="form-group">
                        <input type="text" class="form-control lbl_move" label="Project Location" />
                      </div>
                      <div class="form-group">
                        <input type="text" class="form-control lbl_move" label="Proposal Cost" />
                      </div>
                      <div class="form-group">
                        <input type="text" class="form-control lbl_move" label="Project Duration" />
                      </div>
                    </div>
                    <div class="cont_bt col-lg-5 col-lg-offset-7 col-md-9 col-md-offset-3 col-sm-7 col-sm-offset-5 col-xs-7 col-xs-offset-5">
                      <ul>
                        <li><a href="javascript:nextAccordian(2)">Continue &nbsp;<i class="fa fa-chevron-circle-right"></i></a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!--General end--> 
          <!--Tender Details-->
          <div class="panel panel-info">
            <div data-target="#collapseTwo" data-parent="#accordion" data-toggle="collapse" class="panel-heading collapsed panel_heads" id="panelheading-2">
              <h4 class="panel-title accordion-toggle defa_panels">Tender Details</h4>
            </div>
            <div class="panel-collapse collapse" id="collapseTwo" style="height: 0px;">
              <div class="panel-body bgcolr">
                <div class="deft_act">
                  <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-12 col-sm-offset-0">
                    <div class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0">
                      <div class="form-group">
                        <input type="text" class="form-control lbl_move" label="Tender No">
                      </div>
                      <div class="form-group">
                        <input type="text" class="form-control lbl_move" label="Tender Process Type">
                      </div>
                      <div class="form-group">
                        <input type="text" class="form-control lbl_move" label="Project Address">
                      </div>
                      <div class="form-group">
                        <input type="text" class="form-control lbl_move" label="Contact Person">
                      </div>
                      <div class="form-group">
                        <input type="text" class="form-control lbl_move" label="Contact No">
                      </div>
                      <div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0" style="padding-left:0px !important; padding-right:0px !important;">
                        <label for="exampleInputEmail1" class="clear lba col-md-12">It's Include With Existing Contract</label>
                        <div class="sects">
                          <div class="form-group">
                            <select name="named[]" id="status" class="form-control selectpicker show-tick" data-size="5" title="Choose Status">
                              <option>Select Status</option>
                              <option>No</option>
                              <option>Yes</option>
                            </select>
                          </div>
                        </div>
                        <div class="sectss">
                          <div class="form-group">
                            <select name="named[]" id="status" class="form-control selectpicker show-tick" data-size="5" title="Choose Status">
                              <option>Work Order No</option>
                              <option>1</option>
                              <option>2</option>
                              <option>3</option>
                              <option>4</option>
                            </select>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0">
                      <div class="form-group">
                        <input type="text" class="form-control lbl_move" label="Tender Date">
                      </div>
                      <div class="form-group">
                        <input type="text" class="form-control lbl_move" label="Tender Type">
                      </div>
                      <div class="form-group">
                        <input type="text" class="form-control lbl_move" label="Project Type">
                      </div>
                      <div class="form-group">
                        <input type="text" class="form-control lbl_move" label="Designation of Contact Person">
                      </div>
                      <div class="form-group">
                        <input type="text" class="form-control lbl_move" label="E-Mail">
                      </div>
                      <div class="form-group">
                        <textarea class="form-control lbl_move" label="Office Address" ></textarea>
                      </div>
                    </div>
                    <div class="cont_bt col-lg-5 col-lg-offset-7 col-md-9 col-md-offset-3 col-sm-7 col-sm-offset-5 col-xs-7 col-xs-offset-5">
                      <ul>
                        <li><a href="javascript:nextAccordian(3)">Continue &nbsp;<i class="fa fa-chevron-circle-right"></i></a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!--Tender Details end--> 
          <!--Cost Details-->
          <div class="panel panel-info">
            <div data-target="#collapsethree" data-parent="#accordion" data-toggle="collapse" class="panel-heading collapsed panel_heads" id="panelheading-3">
              <h4 class="panel-title accordion-toggle defa_panels">Cost Details</h4>
            </div>
            <div class="panel-collapse collapse" id="collapsethree" style="height: 0px;">
              <div class="panel-body bgcolr">
                <div class="eng-div clear">
                  <div class="col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-6 col-sm-offset-0"><b class="regs">Require any Cost for Documents ?</b>
                    <label>
                    <input type="checkbox" class="ios_checkbox" name="checkbox">
                    <div class="ios_switch"><span></span></div>
                    </label>
                  </div>
                  <div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0 div-rgs">
                    <div class="col-sm-2">
                      <div class="form-group">
                        <input type="text" class="form-control lbl_move" label="Cost" />
                      </div>
                    </div>
                    <div class="col-sm-3">
                      <div class="form-group">
                        <input type="text" class="form-control lbl_move" label="Mode of Payment" />
                      </div>
                    </div>
                    <div class="col-sm-3">
                      <div class="form-group">
                        <input type="text" class="form-control lbl_move" label="In favour of" />
                      </div>
                    </div>
                  </div>
                </div>
                <div class="eng-div clear">
                  <div class="col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-6 col-sm-offset-0"><b class="regs">Require Earnest Money Deposit ?</b>
                    <label>
                    <input type="checkbox" class="ios_checkbox" name="checkbox">
                    <div class="ios_switch"><span></span></div>
                    </label>
                  </div>
                  <div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0 div-rgs">
                    <div class="col-sm-2">
                      <div class="form-group">
                        <input type="text" class="form-control lbl_move" label="Cost" />
                      </div>
                    </div>
                    <div class="col-sm-3">
                      <div class="form-group">
                        <input type="text" class="form-control lbl_move" label="Mode of Payment" />
                      </div>
                    </div>
                    <div class="col-sm-3">
                      <div class="form-group">
                        <input type="text" class="form-control lbl_move" label="In favour of" />
                      </div>
                    </div>
                    <div class="col-sm-3">
                      <div class="form-group"> <span class="date_icon"><i class="fa fa-calendar"></i></span>
                        <input type="text" name="lead_date" id="lead_date" class="form-control date_picker lbl_move" label="Valid Upto" />
                      </div>
                    </div>
                  </div>
                </div>
                <div class="eng-div clear">
                  <div class="col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-6 col-sm-offset-0"><b class="regs">Require Security Deposit ?</b>
                    <label>
                    <input type="checkbox" class="ios_checkbox" name="checkbox">
                    <div class="ios_switch"><span></span></div>
                    </label>
                  </div>
                  <div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0 div-rgs">
                    <div class="col-sm-2">
                      <div class="form-group">
                        <input type="text" class="form-control lbl_move" label="Cost" />
                      </div>
                    </div>
                    <div class="col-sm-3">
                      <div class="form-group">
                        <input type="text" class="form-control lbl_move" label="Mode of Payment" />
                      </div>
                    </div>
                    <div class="col-sm-3">
                      <div class="form-group">
                        <input type="text" class="form-control lbl_move" label="In favour of" />
                      </div>
                    </div>
                    <div class="col-sm-3">
                      <div class="form-group"> <span class="date_icon"><i class="fa fa-calendar"></i></span>
                        <input type="text" name="lead_date" id="lead_date" class="form-control date_picker lbl_move" label="Valid Upto" />
                      </div>
                    </div>
                  </div>
                </div>
                <div class="eng-div clear">
                  <div class="col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-6 col-sm-offset-0"><b class="regs">Mobilisation Advance available ?</b>
                    <label>
                    <input type="checkbox" class="ios_checkbox" name="checkbox">
                    <div class="ios_switch"><span></span></div>
                    </label>
                  </div>
                  <div class="ccol-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0 div-rgs">
                    <div class="col-sm-2">
                      <div class="form-group">
                        <input type="text" class="form-control lbl_move" label="Value" />
                      </div>
                    </div>
                    <div class="col-sm-9">
                      <div class="form-group">
                        <textarea class="form-control lbl_move" label="Remarks" ></textarea>
                      </div>
                    </div>
                  </div>
                </div>
                
                      <div class="cont_bt col-lg-5 col-lg-offset-7 col-md-9 col-md-offset-3 col-sm-7 col-sm-offset-5 col-xs-7 col-xs-offset-5">
                      <ul>
                        <li><a href="javascript:nextAccordian(4)">Continue &nbsp;<i class="fa fa-chevron-circle-right"></i></a></li>
                      </ul>
                    </div>
              </div>
            </div>
          </div>
          <!--Cost Details end--> 
          <!--Important Dates-->
          <div class="panel panel-info">
            <div data-target="#collapsefour" data-parent="#accordion" data-toggle="collapse" class="panel-heading collapsed panel_heads" id="panelheading-4">
              <h4 class="panel-title accordion-toggle defa_panels">Important Dates</h4>
            </div>
            <div class="panel-collapse collapse" id="collapsefour" style="height: 0px;">
              <div class="panel-body bgcolr">
                <div class="deft_act">
                  <div class="col-lg-12 col-lg-offset-0 col-md-10 col-md-offset-1 col-sm-12 col-sm-offset-0">
                    <div class="dept">
                      <div class="table-responsive topsp">
                        <table class="table" style=" margin-bottom:0px;">
                          <tbody>
                            <tr>
                              <th width="28%" class="bgstab"><b class="sept">Last Date of Document Purchase</b></th>
                              <td><input type="text" name="lead_date" id="lead_date" class="date_picker parent_text" placeholder="dd-mm-yyyy" /></td>
                              <th class="bgstab"><b class="sept">Place of Address</b></th>
                              <td><textarea class="parent_texts"></textarea></td>
                            </tr>
                            <tr>
                              <th width="28%" class="bgstab"><b class="sept">PreBid Meeting Date</b></th>
                              <td><input type="text" name="lead_date" id="lead_date" class="date_picker parent_text" placeholder="dd-mm-yyyy" /></td>
                              <th class="bgstab"><b class="sept">Place of Address</b></th>
                              <td><textarea class="parent_texts"></textarea></td>
                            </tr>
                            <tr>
                              <th width="28%" class="bgstab"><b class="sept">Last Date of Bid Submission</b></th>
                              <td><input type="text" name="lead_date" id="lead_date" class="date_picker parent_text" placeholder="dd-mm-yyyy" /></td>
                              <th class="bgstab"><b class="sept">Place of Address</b></th>
                              <td><textarea class="parent_texts"></textarea></td>
                            </tr>
                            <tr>
                              <th width="28%" class="bgstab"><b class="sept">Bid Opening Date</b></th>
                              <td><input type="text" name="lead_date" id="lead_date" class="date_picker parent_text" placeholder="dd-mm-yyyy" /></td>
                              <th class="bgstab"><b class="sept">Place of Address</b></th>
                              <td><textarea class="parent_texts"></textarea></td>
                            </tr>
                            <tr>
                              <th width="28%" class="bgstab"><b class="sept">Last Date of Technical Bid Submision</b></th>
                              <td><input type="text" name="lead_date" id="lead_date" class="date_picker parent_text" placeholder="dd-mm-yyyy" /></td>
                              <th class="bgstab"><b class="sept">Place of Address</b></th>
                              <td><textarea class="parent_texts"></textarea></td>
                            </tr>
                          </tbody>
                        </table>
                      </div>
                      <div class="cont_bt col-lg-5 col-lg-offset-7 col-md-9 col-md-offset-3 col-sm-7 col-sm-offset-5 col-xs-7 col-xs-offset-5">
                        <ul>
                          <li><a href="javascript:nextAccordian(5)">Continue &nbsp;<i class="fa fa-chevron-circle-right"></i></a></li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          
          <!--Important Dates end--> 
          <!--Consultant Details-->
          <div class="panel panel-info">
            <div data-target="#collapsefive" data-parent="#accordion" data-toggle="collapse" class="panel-heading collapsed panel_heads" id="panelheading-5">
              <h4 class="panel-title accordion-toggle defa_panels">Consultant Details</h4>
            </div>
            <div class="panel-collapse collapse" id="collapsefive" style="height: 0px;">
              <div class="panel-body bgcolr">
                <div class="deft_act">
                  <div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0">
                    <div class="table-responsive topsp">
                      <table class="table tableWithFloatingHeader" style=" margin-bottom:0px;">
                        <thead>
                          <tr>
                            <th>Consultant Name</th>
                            <th>Consultant Type</th>
                            <th>Address of the Consultant</th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <td width="5%"><input class="parent_text" type="text" readonly /></td>
                            <td width="5%"><input class="parent_text" type="text" readonly /></td>
                            <td width="15%"><textarea class="parent_texts" ></textarea></td>
                          </tr>
                        </tbody>
                          </tbody>
                        
                      </table>
                    </div>
                    <div class="cont_bt col-lg-5 col-lg-offset-7 col-md-9 col-md-offset-3 col-sm-7 col-sm-offset-5 col-xs-7 col-xs-offset-5">
                      <ul>
                        <li><a href="javascript:nextAccordian(6)">Continue &nbsp;<i class="fa fa-chevron-circle-right"></i></a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!--Consultant Details end-->
          <div class="panel panel-info">
            <div data-target="#collapsesix" data-parent="#accordion" data-toggle="collapse" class="panel-heading collapsed panel_heads" id="panelheading-6">
              <h4 class="panel-title accordion-toggle defa_panels">Note</h4>
            </div>
            <div class="panel-collapse collapse" id="collapsesix" style="height: 0px;">
              <div class="panel-body bgcolr">
                <div class="deft_act col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">
                  <div class="form-group">
                    <textarea class="form-control lbl_move" label="Enter Note" ></textarea>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!--accordion end--> 
      
    </div>
  </div>
</div>
<div class="col-lg-12 savebtn_area">
  <ul>
    <li class="dropdown save_btn float_r"><a href="javascript:void(0);" data-toggle="tooltip" class="ripple" title="Save">Save</a> 
      <!-- <li class="cancel_btn float_r"><a href="javascript:void(0);" data-toggle="tooltip" class="ripple" title="Go back!">Back</a></li>-->
      
  </ul>
</div>

<!--table expand start--> 
<script>
$(function () 
   {nextAccordian(1);
});
    function nextAccordian(id) {
	$('#panelheading-' + id).trigger('click');
}
</script> 
<!--table expand end--> 

