<style>
.subDiv                         {margin-left:10px; margin-top:10px;}
.abt-iowt2 thead tr th          {background:#CAE1F9!important;font-size:11px; margin-top:20px;}
.fntst                          {font-size:14px;font-family:'Open Sans', sans-serif !important;display:block !important;padding-left:12px !important;}
.thscss 					    {font-family:'Open Sans', sans-serif !important;background-color:#E2EBEF !important;border-bottom:1px solid #5D9BB6 !important;	padding:8px !important;font-size:11px;}
.tdpds 						    {border-top: 1px solid #EFEFEF!important;line-height:1.42857!important;padding:8px!important;vertical-align:top!important;font-family:'Open Sans', sans-serif !important;font-size:12px;}
.bill-det 					    {font-size:14px;font-family:'Open Sans', sans-serif !important;display:block;padding-left:5px !important;}
.date-bills					    { }
.str-bill 					    {display:block !important;width:10px;padding-left:10px;}
.date-shw 					    {font-size:14px;font-family:'Open Sans', sans-serif !important;display:block !important;padding-left:12px !important;}
p							    {color:#000;font-size:14px;text-align:left;padding-top:-8px; line-height:24px !important;font-family:'Open Sans', sans-serif !important;}
.su-t 						    {margin-left:13px !important}
.sel-wets 					    {border:thin solid #c2c2c2 !important;margin-bottom:10px !important;width:95% !important;border-radius:0px !important;}
.sel-wets select option 	    {padding-left:10px !important;padding-top:3px;padding-bottom:3px;}
.sel-wets select option.thin    {outline-width:thin !important;}
.sel-wets select option.thick   {outline-width:thick !important;}
.sel-wets select option.thicker {outline-width:thicker !important;}
.abst-curt                      {margin-left:13px;}
.bill-cum                       {margin-left:10px;}
.abt-iow                        {margin-left:10px;}
.abt-all                        {margin-left:10px;}

/*
.thscss 					    {font-family:'Open Sans', sans-serif !important;background-color:#E2EBEF !important;border-bottom:1px solid #5D9BB6 !important;	padding:8px !important;font-size:11px;}
.tdpds 						    {border-top: 1px solid #EFEFEF!important;line-height:1.42857!important;padding:8px!important;vertical-align:top!important;font-family:'Open Sans', sans-serif !important;font-size:12px;}
.bill-det 					    {font-size:14px;font-family:'Open Sans', sans-serif !important;display:block;padding-left:5px !important;}
.date-bills					    {display:inline;clear:both;font-family:'Open Sans', sans-serif !important; }
.str-bill 					    {display:block !important;width:10px;padding-left:10px;}
.date-shw 					    {font-size:14px;font-family:'Open Sans', sans-serif !important;display:block !important;padding-left:12px !important;}
p							    {color:#000;font-size:13px;text-align:left;padding-top:-8px; font-weight:600;}
.su-t 						    {margin-left:13px !important}
.sel-wets 					    {border:thin solid #c2c2c2 !important;margin-bottom:10px !important;width:95% !important;border-radius:0px !important;}
.sel-wets select option 	    {padding-left:10px !important;padding-top:3px;padding-bottom:3px;}
.sel-wets select option.thin    {outline-width:thin !important;}
.sel-wets select option.thick   {outline-width:thick !important;}
.sel-wets select option.thicker {outline-width:thicker !important;}
.abst-curt                      {margin-left:13px;}
.bill-cum                       {margin-left:10px;}
.abt-iow                        {margin-left:10px;}
.abt-all                        {margin-left:10px;}
.abt-all3                       {margin-left:10px;}
.subDiv                         {margin-left:10px; margin-top:10px;}
.abt-iowt2 thead tr th          {background:#CAE1F9!important;font-size:11px; margin-top:20px;}
.fntst                          {font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:13px;font-weight:600;}
.drsElement                     {padding-left:5px;padding-right:5px;padding-top:8px;}

.sel-wets select option.dotteds  {border-style:dotted;}	
.sel-wets select option.dasheds  {border-style:dashed;}	
.sel-wets select option.solids   {border-style:solid;}	
.sel-wets select option.doubles  {border-style:double;}	
.sel-wets select option.hiddens  {border-style:hidden;}	*/
</style>
<div id="p_scents" style="height:630px; margin-top:10px; position:relative;">
  <div class="drsElement drsMoveHandle drsItem" data-name="Header Info" style="left:10px;top:8px;width:680px;height:30px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
    <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">Receipt Details</p>
    <button type="button" class="remScnt"><i class="fa fa-trash-o"></i></button>
  </div>
  <div class="drsElement drsMoveHandle drsItem" data-name="Date Info" style="left:545px;top:37px;width:145px;height:30px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
    <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">Date :</p>
    <span id="receipt_Date" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
    <button type="button" class="remScnt"><i class="fa fa-trash-o"></i></button>
  </div>
  <div class="drsElement drsMoveHandle drsItem" data-name="Logo" style="left:10px;top:38px;width:200px;height:130px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border: 1px solid rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
    <p class="not-editable" style="text-align:center !important; vertical-align:middle !important;">
     <img id="receipt_Logo" src="http://localhost/bsf_v1.0/public/images/nolgo.jpg"> </p>
    <button type="button" class="remScnt"><i class="fa fa-trash-o"></i></button>
  </div>
  <div class="drsElement drsMoveHandle drsItem" data-name="Workorder Info" style="left:10px;top:168px;width:300px;height:80px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border: 1px solid rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
    <div class="drsElement drsMoveHandle drsGroupItem" data-name="Workorderno field" style="left:10px;top:5px;width:260px;height:30px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border: 1px solid rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
      <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">WONo :</p>
      <span id="receipt_WONo" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
      <button type="button" class="remScnt"><i class="fa fa-trash-o"></i></button>
    </div>
    <div class="drsElement drsMoveHandle drsGroupItem" data-name="Workorderdate field" style="left:10px;top:40px;width:260px;height:30px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border: 1px solid rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
      <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">WODate :</p>
      <span id="receipt_WODate" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
      <button type="button" class="remScnt"><i class="fa fa-trash-o"></i></button>
    </div>
    <button type="button" class="remScnt"><i class="fa fa-trash-o"></i></button>
  </div>
  <div class="drsElement drsMoveHandle drsItem" data-name="Project det" style="left:10px;top:260px;width:300px;height:150px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
    <div class="drsElement drsMoveHandle drsGroupItem" data-name="Projectname field" style="left:10px;top:5px;width:260px;height:30px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
      <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">Project Name :</p>
      <span id="receipt_ProjectName" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
      <button type="button" class="remScnt"><i class="fa fa-trash-o"></i></button>
    </div>
    <div class="drsElement drsMoveHandle drsGroupItem" data-name="Projectdesc field" style="left:10px;top:40px;width:260px;height:100px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
      <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">Project Description :</p>
      <span id="receipt_ProjectDescription" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
      <button type="button" class="remScnt"><i class="fa fa-trash-o"></i></button>
    </div>
    <button type="button" class="remScnt"><i class="fa fa-trash-o"></i></button>
  </div>
  <div class="drsElement drsMoveHandle drsItem" data-name="Client det" style="left:10px;top:419px;width:300px;height:180px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);">
    <div class="drsElement drsMoveHandle drsGroupItem" data-name="clientname field" style="left:10px;top:5px;width:260px;height:30px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
      <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">ClientName :</p>
      <span id="receipt_ClientName" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
      <button type="button" class="remScnt"><i class="fa fa-trash-o"></i></button>
    </div>
    <div class="drsElement drsMoveHandle drsGroupItem" data-name="clientaddress field" style="left:10px;top:40px;width:260px;height:110px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);"> <span id="receipt_ClientAddress" class="fntst"></span>
      <button type="button" class="remScnt"><i class="fa fa-trash-o"></i></button>
    </div>
    <button type="button" class="remScnt"><i class="fa fa-trash-o"></i></button>
  </div>
  <div class="drsElement drsMoveHandle drsItem" data-name="Receipt det" style="left:310px;top:168px;width:380px;height:265px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
    <div class="drsElement drsMoveHandle drsGroupItem" data-name="ReceiptNo field" style="left:10px;top:5px;width:330px;height:30px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
      <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">ReceiptNo :</p>
      <span id="receipt_ReceiptNo" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
      <button type="button" class="remScnt"><i class="fa fa-trash-o" style="!important"></i></button>
    </div>
    <div class="drsElement drsMoveHandle drsGroupItem" data-name="ReceiptDate field" style="left:10px;top:40px;width:330px;height:30px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
      <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">ReceiptDate :</p>
      <span id="receipt_ReceiptDate" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
      <button type="button" class="remScnt"><i class="fa fa-trash-o" style="!important"></i></button>
    </div>
    <div class="drsElement drsMoveHandle drsGroupItem" data-name="ReceiptAgainst field" style="left:10px;top:75px;width:330px;height:30px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
      <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">ReceiptAgainst :</p>
      <span id="receipt_ReceiptAgainst" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
      <button type="button" class="remScnt"><i class="fa fa-trash-o" style="!important"></i></button>
    </div>
    <div class="drsElement drsMoveHandle drsGroupItem" data-name="ReceiptMode field" style="left:10px;top:110px;width:330px;height:30px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
      <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">ReceiptMode :</p>
      <span id="receipt_ReceiptMode" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
      <button type="button" class="remScnt"><i class="fa fa-trash-o" style="!important"></i></button>
    </div>
    <div class="drsElement drsMoveHandle drsGroupItem" data-name="TransactionNo field" style="left:10px;top:145px;width:330px;height:30px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
      <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">TransactionNo :</p>
      <span id="receipt_TransactionNo" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
      <button type="button" class="remScnt"><i class="fa fa-trash-o" style="!important"></i></button>
    </div>
    <div class="drsElement drsMoveHandle drsGroupItem" data-name="TransactionDate field" style="left:10px;top:180px;width:330px;height:30px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
      <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">TransactionDate :</p>
      <span id="receipt_TransactionDate" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
      <button type="button" class="remScnt"><i class="fa fa-trash-o" style="!important"></i></button>
    </div>
    <div class="drsElement drsMoveHandle drsGroupItem" data-name="Amount field" style="left:10px;top:215px;width:330px;height:30px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
      <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">Amount :</p>
      <span id="receipt_Amount" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
      <button type="button" class="remScnt"><i class="fa fa-trash-o" style="!important"></i></button>
    </div>
    <button type="button" class="remScnt"><i class="fa fa-trash-o"></i></button>
  </div>
  <div class="drsElement drsMoveHandle drsItem" data-name="Company det" style="left:310px;top:432px;width:380px;height:130px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
    <div class="drsElement drsMoveHandle drsGroupItem" data-name="Companyaddress field" style="left:10px;top:5px;width:330px;height:110px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
      <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;"> Company Address :</p>
      <span id="receipt_Address" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
      <button type="button" class="remScnt"><i class="fa fa-trash-o" style="!important"></i></button>
    </div>
    <button type="button" class="remScnt"><i class="fa fa-trash-o"></i></button>
  </div>
</div>
<!--Test 2 --> 
<!-- <div id="test2">
    <div class="list-group">
     
    </div>


  </div>
  <!--/Test 2
<script src="https://cdn.rawgit.com/AndreaLombardo/BootSideMenu/master/js/BootSideMenu.js"></script>

  <script type="text/javascript">
  $(document).ready(function(){
      $('#test').BootSideMenu({side:"left", autoClose:false});
      $('#test2').BootSideMenu({side:"right"});
  });
  </script>-->