<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
    	<div class="col-lg-12">
            <h1 class="float_l">Bank Register</h1>
            <div class="col-lg-12">
            
                <div id="subGrid">
                </div>
            </div>
            <div class="col-lg-12">
                <div id="jqxgrid">
                </div>
            </div>
		</div>
    </div>
</div>
<div class="modal fade" id="mdlDelete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h1>Please provide a reason for Deleting Details</h1>
            </div>
            <div class="modal-body">
                <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">
                    <form class="form-horizontal">
                        <div class="row m_tb40">
                            <div class="col-lg-12 form-group req_flds">
                                <textarea id="remarks" maxlength="250" class="form-control lbl_move" label="Enter the remarks"/></textarea>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="modal-footer clear">
                <div class="col-lg-12 savebtn_area no_border">
                    <ul>
                        <li class="save_btn float_r">
                            <a href="javascript:void(0);" id="btnDelete" class="ripple">Delete</a>
                        </li>
                        <li class="cancel_btn float_r"><a href="javascript:void(0);" aria-hidden="true" data-dismiss="modal" class="ripple">Cancel</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function (){
        $.ajax({
            url:getBaseURL()+"crm/bank/bankregister",
            type:"post",
            data:"mode=first",
            dataType:"json",
            success:function(data, textStatus, jqXHR){
                //alert(JSON.stringify(data))
                var source =
                {
                    dataFields: [
                        { name: 'Bank', type: 'string' },
                        { name: 'Branch', type: 'string' },
                        { name: 'Address', type: 'string' },
                        { name: 'City', type: 'string' },
                        { name: 'State', type: 'string' },
                        { name: 'Country', type: 'string' },
                        { name: 'Mobile', type: 'string' },
                        { name: 'ContactPerson', type: 'string' }

                    ],
                    localdata:data,
                    id: 'BranchId',
                    datatype: "json",
                    async: false

                };

                var employeesAdapter = new $.jqx.dataAdapter(source);

                // creage jqxgrid
                $("#subGrid").jqxGrid({
                    width: '100%',
                    autoheight:true,
                    source: employeesAdapter,
                    sortable: true,
                    filterable: true,
                    pageable: true,
                    ready: function () {
                        //$("#subGrid").jqxGrid('showrowdetails', 1);
                    },
                    columns: [

                        { text: 'Bank', dataField: 'Bank'},
                        { text: 'Branch', dataField: 'Branch' },
                        { text: 'Address', dataField: 'Address' },
                        { text: 'City', dataField: 'City' },
                        { text: 'State', dataField: 'State' },
                        { text: 'Country', dataField: 'Country' },
                        { text: 'Mobile', dataField: 'Mobile' },
                        { text: 'ContactPerson', dataField: 'ContactPerson' },
                        { text: 'Action',sortable: false, filterable: false, align: 'left', width: '15%',
                            cellsrenderer: function (row)
                            {
                                //var AnalysisRegId = $("#dataTable").jqxGrid('getCellValue', row, 'AnalysisRegId'),
                                var rowData = $("#subGrid").jqxGrid('getrowdata', row);
                                var  editLink = '<a title="Edit" href="'+ getBaseURL() + 'crm/bank/bankinfo/'+rowData.uid+'" style="padding-left: 15px; margin-top:8px;"><i class="fa fa-pencil-square-o reg-icon"></i></a>';
                                return editLink + "&nbsp;&nbsp;" + '<a href="javascript:void(0);" title="Delete" onclick="payRowDelete(' + row + '); return false;"><i class="fa fa-trash-o reg-icon"></i></a>';
                            }
                        }
                    ]
                });
//                $("#subGrid").on('rowselect', function(event){
//                    // event arguments.
//                    var args = event.args;
//                    // row's bound index.
//                    var rowBoundIndex = args.rowindex;
//                    // row's data. The row's data object or null(when all rows are being selected or unselected with a single action). If you have a datafield called "firstName", to access the row's firstName, use var firstName = rowData.firstName;
//                    var rowData = args.row;
//                    location.replace("detailed/"+rowData.uid);
//                });
            },
            error:function(jqXHR, textStatus, errorThrown){
                alert(textStatus+"-----"+errorThrown);
            }
        });
    });

    $('#btnDelete').on('click', function () {
        //alert("1");
        var remarks = $("#remarks").val();
        if(remarks.length == 0) {
            showError($("#remarks"), 'Required!');
            return;
        } else{
            removeError($("#remarks"));

            $('#mdlDelete').modal('hide');}
        var rowData =$('#subGrid').jqxGrid('getrowdata', $('#mdlDelete').data('row'));


        $.ajax({
            url: getBaseURL() + 'crm/bank/delete',
            type: 'POST',
            async: false,
            data: {"BankId": rowData.uid,"Remarks": remarks},
            success:function(data, textStatus, jqXHR){
                if (jqXHR.status == 200) {
                    $('#subGrid').jqxGrid("deleterow", rowData.uid);
                    $('#alertMsg').html('The Unit was successfully unblocked !!!');
                    $("#msgBox").modal('show');
                } else{
                    alert('Failed to delete!');
                }
            },
            error:function(jqXHR, textStatus, errorThrown){
                alert('Failed to delete!');
            }
        });
        $("#remarks").val('');
    });
    function payRowDelete(row) {
        var rowData = $('#subGrid').jqxGrid('getrowdata', row);
        $('#mdlDelete').data('row', row).modal('show');
        $("#remarks").val('');
    }
</script>