<style>
	.form-group1 {margin-bottom:5px; }
    /*.upload-pf {border: 1px solid #ddd; box-shadow: 0 0 0 2px #ffffff, 0 0 0 3px #7B7EBA; height: 118px; margin: 25px 10px 0 20px;overflow: hidden;float: left;position: relative;width: 80%;}*/
	.upload-pf {border: 1px solid #ddd;box-shadow: 0 0 0 2px #ffffff, 0 0 0 3px #7b7eba;float: left;height: 113px;margin: -4px 10px 0 -9px;overflow: hidden;position: relative;width: 91%;}
    .upload-pf img {width: 100% !important;height: 118px !important;background:#fff; }
    .upload-pf .ovrly {position: absolute;background: rgba(0, 0, 0, 0.5);height: 100%;right: 100%;top: 0;width: 100%;     -webkit-transition: all 0.5s;-moz-transition: all 0.5s; -o-transition: all 0.5s;transition: all 0.5s;}
    .upload-pf .buttons {position: absolute;top: 50%;right: -100%;-webkit-transition: all 0.5s;-moz-transition: all 0.5s;
        -o-transition: all 0.5s;transition: all 0.5s;-webkit-transform: translate(50%, -50%);-moz-transform: translate(50%, -50%);-ms-transform: translate(50%, -50%);-o-transform: translate(50%, -50%);transform: translate(50%, -50%);}
    .upload-pf .buttons .fa {margin: 0 1px;background: rgba(256, 256, 256, 0.9);-webkit-box-shadow: 0 0 1px rgba(0, 0, 0, 0.3);-moz-box-shadow: 0 0 1px rgba(0, 0, 0, 0.3);box-shadow: 0 0 1px rgba(0, 0, 0, 0.3);-webkit-border-radius: 50%;  -moz-border-radius: 50%;border-radius: 50%;color: rgba(50, 50, 50, 0.9);display: inline-block;line-height: 40px;     font-size: 16px;text-align: center;text-decoration: none;width: 40px;cursor:pointer;height: 40px;}
    .upload-pf:hover .buttons {right: 50%;}
    .upload-pf:hover .ovrly {right: 0;}
    .proname_btn a{ color: #112c45; font-weight:600}
    .subs a:hover{color:#333 !important;}
	
    .subDiv                         {margin-left:10px; margin-top:10px;}
    .abt-iowt2 thead tr th          {background:#CAE1F9!important;font-size:11px; margin-top:20px;}
    .fntst                          {font-size:14px;font-family:'Open Sans', sans-serif !important;display:block !important;padding-left:12px !important;}
    .thscss 					    {font-family:'Open Sans', sans-serif !important;background-color:#E2EBEF !important;border-bottom:1px solid #5D9BB6 !important;	padding:8px !important;font-size:11px;}
    .tdpds 						    {border-top: 1px solid #EFEFEF!important;line-height:1.42857!important;padding:8px!important;vertical-align:top!important;font-family:'Open Sans', sans-serif !important;font-size:12px;}
    .bill-det 					    {font-size:14px;font-family:'Open Sans', sans-serif !important;display:block;padding-left:5px !important;}
    .date-bills					    { }
    .str-bill 					    {display:block !important;width:10px;padding-left:10px;}
    .date-shw 					    {font-size:14px;font-family:'Open Sans', sans-serif !important;display:block !important;padding-left:12px !important;}
    p							    {color:#000;font-size:14px;text-align:left;padding-top:-8px; line-height:24px !important;font-family:'Open Sans', sans-serif !important;}
    .su-t 						    {margin-left:13px !important}
    .sel-wets 					    {border:thin solid #c2c2c2 !important;margin-bottom:10px !important;width:95% !important;border-radius:0px !important;}
    .sel-wets select option 	    {padding-left:10px !important;padding-top:3px;padding-bottom:3px;}
    .sel-wets select option.thin    {outline-width:thin !important;}
    .sel-wets select option.thick   {outline-width:thick !important;}
    .sel-wets select option.thicker {outline-width:thicker !important;}
    .abst-curt                      {margin-left:13px;}
    .bill-cum                       {margin-left:10px;}
    .abt-iow                        {margin-left:10px;}
    .abt-all                        {margin-left:10px;}
    /*
    .thscss 					    {font-family:'Open Sans', sans-serif !important;background-color:#E2EBEF !important;border-bottom:1px solid #5D9BB6 !important;	padding:8px !important;font-size:11px;}
    .tdpds 						    {border-top: 1px solid #EFEFEF!important;line-height:1.42857!important;padding:8px!important;vertical-align:top!important;font-family:'Open Sans', sans-serif !important;font-size:12px;}
    .bill-det 					    {font-size:14px;font-family:'Open Sans', sans-serif !important;display:block;padding-left:5px !important;}
    .date-bills					    {font-family:'Open Sans', sans-serif !important;display:inline;clear:both; color:#000; }
    .str-bill 					    {display:block !important;width:10px;padding-left:10px;}
    .date-shw 					    {font-size:14px;font-family:'Open Sans', sans-serif !important;display:block !important;padding-left:12px !important;}
    p							    {color:#000;font-size:14px;text-align:left;padding-top:-8px;font-family:'Open Sans', sans-serif !important;}
    .su-t 						    {margin-left:13px !important}
    .sel-wets 					    {border:thin solid #c2c2c2 !important;margin-bottom:10px !important;width:95% !important;border-radius:0px !important;}
    .sel-wets select option 	    {padding-left:10px !important;padding-top:3px;padding-bottom:3px;}
    .sel-wets select option.thin    {outline-width:thin !important;}
    .sel-wets select option.thick   {outline-width:thick !important;}
    .sel-wets select option.thicker {outline-width:thicker !important;}
    .abst-curt                      {margin-left:13px;}
    .bill-cum                       {margin-left:10px;}
    .abt-iow                        {margin-left:10px;}
    .abt-all                        {margin-left:10px;}
    .abt-all3                       {margin-left:10px;}
    .subDiv                         {margin-left:10px; margin-top:10px;}
    .abt-iowt2 thead tr th          {background:#CAE1F9!important;font-size:11px; margin-top:20px;}
    .fntst                          {font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;}
    .drsElement                     {padding-left:5px;padding-right:5px;padding-top:8px;}

    .sel-wets select option.dotteds  {border-style:dotted;}
    .sel-wets select option.dasheds  {border-style:dashed;}
    .sel-wets select option.solids   {border-style:solid;}
    .sel-wets select option.doubles  {border-style:double;}
    .sel-wets select option.hiddens  {border-style:hidden;}	*/
</style>
<!---sample rabill report--->
<div id="p_scents" style="height: 300.5px; position: relative; margin-top: 10px;">
	<div class="drsElement drsMoveHandle drsItem" data-name="Register Details" style="left: 9px; top: 8px; width: 683px; height: 123px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border: 1px solid rgb(0, 0, 0); z-index: 2;">
		<div class="drsElement drsMoveHandle drsItem" data-name="Logo" style="left: 8px; top: 8px; width: 136px; height: 84px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border: 0px solid rgb(0, 0, 0); z-index: 2;">
			<div class="col-md-4 col-sm-5" id="browse_1" style="padding:0px !important; width:130px;" onclick="Imagebrowse(this);">
				<div class="upload-pf"> <img id="showpic_1" onerror="this.src='<?php echo $this->basePath(); ?>/images/nolgo.jpg';"> <img id="req_LogoPath" src="http://localhost/bsf_v1.1/public/images/nolgo.jpg" style="display:block;width:258px;height:280px">
					<input name="imageurl_1" id="imageurl_1" value="" type="hidden">
					<div class="ovrly"></div>
					<div class="buttons">
						<a href="#" class="fa fa-link"></a>
					</div>
				</div>
			</div>
			<input id="myfile_1" name="myfile_1" class="imageupload" accept="image/*" style="display: none;" type="file">
			<button style="font-size: 17px; display: none;" type="button" class="remScnt">
				<i style="font-size: 17px;" class="fa fa-trash-o"></i>
			</button>
		</div>
		<div class="drsElement drsMoveHandle drsItem" data-name="Requistion Voucher" style="left: 231px; top: 91px; width: 237px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 1px; border-style: hidden; border-color: rgb(0, 0, 0); z-index: 3; font-size: 17px;">
			<p style="display: inline; clear: both; font-family: &quot;Open Sans&quot;,sans-serif ! important; padding-left: 5px; font-weight: normal; font-size: 17px;">Requistion Voucher</p>
			<button style="font-size: 17px; display: none;" type="button" class="remScnt">
				<i style="font-size: 17px;" class="fa fa-trash-o"></i>
			</button>
		</div>
		<button style="font-size: 17px; display: none;" type="button" class="remScnt">
			<i style="font-size: 17px;" class="fa fa-trash-o"></i>
		</button>
	</div>
	<div class="drsElement drsMoveHandle drsGroupItem" data-name="Request Date" style="left: 392px; top: 220px; width: 300px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 0px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 2;">
		<p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">Request Date :</p>
		<span id="req_RequestDate" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
		<button style="display: none;" type="button" class="remScnt">
			<i class="fa fa-trash-o"></i>
		</button>
	</div>
	
	<div class="drsElement drsMoveHandle drsGroupItem" data-name="CCReq No" style="left: 8px; top: 184px; width: 300px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 0px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 2;">
		<p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">CCReq No :</p>
		<span id="req_CCReqNo" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
		<button style="display: none;" type="button" class="remScnt">
			<i class="fa fa-trash-o"></i>
		</button>
	</div>
	
	<div class="drsElement drsMoveHandle drsGroupItem" data-name="Request Type" style="left: 392px; top: 179px; width: 300px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 0px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 2;">
		<p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">Request Type :</p>
		<span id="req_RequestType" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
		<button style="display: none;" type="button" class="remScnt">
			<i class="fa fa-trash-o"></i>
		</button>
	</div>

	<div class="drsElement drsMoveHandle drsGroupItem" data-name="CostCentre Name" style="left: 8px; top: 143px; width: 300px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border: 0px solid rgb(0, 0, 0); z-index: 2;">
		<p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">Project :</p>
		<span id="req_CostCentreName" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
		<button style="display: none;" type="button" class="remScnt">
			<i class="fa fa-trash-o"></i>
		</button>
	</div>
	<div class="drsElement drsMoveHandle drsGroupItem" data-name="Request No" style="left: 391px; top: 140px; width: 300px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 0px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 2;">
		<p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">Request No:</p>
		<span id="req_RequestNo" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
		<button style="display: none;" type="button" class="remScnt">
			<i class="fa fa-trash-o"></i>
		</button>
	</div>
	<div class="drsElement drsMoveHandle drsGroupItem" data-name="City" style="left: 459px; top: 19px; width: 222px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 0px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 2;">
		<p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">City :</p>
		<span id="req_CityName" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
		<button style="display: none;" type="button" class="remScnt">
			<i class="fa fa-trash-o"></i>
		</button>
	</div>
	<div class="drsElement drsMoveHandle drsGroupItem" data-name="State" style="left: 459px; top: 51px; width: 221px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 0px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 2;">
		<p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">State :</p>
		<span id="req_StateName" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
		<button style="display: none;" type="button" class="remScnt">
			<i class="fa fa-trash-o"></i>
		</button>
	</div>
	<div class="drsElement drsMoveHandle drsGroupItem" data-name="Country" style="left: 459px; top: 84px; width: 223px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 0px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 2;">
		<p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">Country :</p>
		<span id="req_CountryName" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
		<button style="display: none;" type="button" class="remScnt">
			<i class="fa fa-trash-o"></i>
		</button>
	</div>
	<div class="drsElement drsMoveHandle drsGroupItem" data-name="CompanyName" style="left: 157px; top: 18px; width: 297px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 0px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 2;">
		<p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">Company Name :</p>
		<span id="req_CompanyName" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
		<button style="display: none;" type="button" class="remScnt">
			<i class="fa fa-trash-o"></i>
		</button>
	</div>
	<div class="drsElement drsMoveHandle drsGroupItem" data-name="Address" style="left: 157px; top: 52px; width: 300px; height: 53px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 0px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 2;">
		<p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">Address :</p>
		<span id="req_Address" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
		<button style="display: none;" type="button" class="remScnt">
			<i class="fa fa-trash-o"></i>
		</button>
	</div>
</div>
<script>
    function Imagebrowse(id) {
        var id = $(id)[0].id;
		
        var arr = id.split('_')[1];
		console.log(arr);
		console.log( $("#myfile_1"));
		$("#myfile_1").click();
        $('#myfile_1').change(function() {
            readURL(this,arr);
        });
    }
	function readURL(input, value) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            //var id = value;
            reader.onload = function(e) {
                $("#showpic_1").hide();
                $("#req_LogoPath").show();
                $('#req_LogoPath').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>
<!--table-->                                                                                                                                                                                                                                                                                                                                                                                                