<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css';?>"/>
<style>.rf-fixed			{margin-top:0px;}</style>
<div class="content_wrapper padlr0">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1>Item of Work List</h1>
                <div class="col-lg-6">
                    <div class="fixed-action-btn active rf-fixed">
                        <a class="btn-floating btn-large">
                            <i class="fa fa-print"></i>
                        </a>
                        <ul>
                            <li>
                                <a class="btn-floating hide-input-file" id="print" href="javascript:void(0);" data-toggle="tooltip" data-placement="top" data-original-title="Print Report">
                                    <i class="fa fa-print"></i>

                                </a>
                            </li>
                            <li>
                                <a class="btn-floating" id="excelExport" href="javascript:void(0);" data-toggle="tooltip" data-placement="top" data-original-title="Download Excel">
                                    <i class="fa fa-download"></i>
                                </a>
                            </li>
                            <li>
                                <a class="btn-floating" id="csvExport" href="javascript:void(0);" data-toggle="tooltip" data-placement="top" data-original-title="Export CSV">
                                    <i class="fa fa-file-archive-o"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-12 col-lg-offset-0 tmss">
                <div class="table-responsive clear">
                    <div id="treeGrid"> </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    var $treeGrid = $("#treeGrid");
    $(function () {
        var source = {
            async: false,
            dataType: "json",
            dataFields: [
                { name: 'IOWId'},
                { name: 'ParentId'},
                { name: 'Specification'},
                { name: 'WorkGroupName'},
                { name: 'SerialNo'}
            ],
            hierarchy:
            {
                keyDataField: { name: 'IOWId' },
                parentDataField: { name: 'ParentId' }
            },
            id: 'ResourceGroupId',
            url: getBaseURL() + "project/report/getiowlist"
        };

        var dataAdapter = new $.jqx.dataAdapter(source);

        $treeGrid.jqxTreeGrid({
            width: "100%",
            source: dataAdapter,
            exportSettings: {fileName: null},
            height:"490",
            pageable:true,
            columns: [
                { text: 'SerialNo', dataField: 'SerialNo'},
                { text: 'Specification', dataField: 'Specification'},
                { text: 'WorkGroupName', dataField: 'WorkGroupName'}
            ]
        });
    });

    //Print option
    $("#excelExport").click(function () {
        $("#treeGrid").jqxTreeGrid('exportData', 'xls', 'jqxGrid');
    });
    $("#csvExport").click(function () {
        $("#treeGrid").jqxTreeGrid('exportData', 'csv', 'jqxGrid');
    });
    $("#htmlExport").click(function () {
        $("#treeGrid").jqxTreeGrid('exportData', 'html', 'jqxGrid');
    });

    $("#print").click(function () {
        var gridContent = $("#treeGrid").jqxTreeGrid('exportData', 'html');
        var newWindow = window.open('', '', 'width=800, height=500'),
            document = newWindow.document.open(),
            pageContent =
                '<!DOCTYPE html>' +
                '<html>' +
                '<head>' +
                '<meta charset="utf-8" />' +
                '<title>Item of Work List</title>' +
                '<h1>Item of Work List</h1>' +
                '</head>' +
                '<body>' + gridContent + '</body></html>';
        document.write(pageContent);
        document.close();
        newWindow.print();
    });

    //    function  printTable() {
    //        $("#treeGrid").jqxTreeGrid('exportData', 'pdf', 'ResourceList');
    //    }
</script>