<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css';?>"/>

<!--Start-->
<script src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqxcore.js"></script>
<script src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqxbuttons.js"></script>
<script src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqxscrollbar.js"></script>
<script type="text/javascript" src="https://jqwidgets.com/public/jqwidgets/jqx-all.js"></script>
<script type="text/javascript" src="https://jqwidgets.com/public/jqwidgets/jqxdatatable.js"></script>
<script type="text/javascript" src="https://jqwidgets.com/public/jqwidgets/jqxtreegrid.js"></script>
<script type="text/javascript" src="https://jqwidgets.com/public/jqwidgets/jqxdata.js"></script>
<script type="text/javascript" src="https://jqwidgets.com/public/jqwidgets/jqxdata.export.js"></script>
<script type="text/javascript" src="http://jqwidgets.com/jquery-widgets-demo/scripts/demos.js"></script>
<!--End-->
<style>
.jqx-grid-header								    {height: 75px !important;}
.sel-type											{font-size:13px;}
.frmwrk_div{margin:10% 0}
</style>
<div class="content_wrapper padlr0">
  <div class="container-fluid">
    <div class="row">
      <?php if ($projectId !=0) { ?>
      <div class="col-lg-12 page_tittle" id="pagetittle">
        <h1 class="col-lg-4 col-sm-4">Item Wise WBS Abstract</h1>
        <div class="col-lg-4 col-sm-4">
          <div class="form-group">
            <label class="col-sm-7 sel-type">Select Project</label>
            <div class="col-lg-12 form-group">
              <select name="project_id" id="project_id" onChange="ChangeProject();" class="form-control multiple_dropdown lbl_move" style="width:100%;">
                <?php if(isset($projectlists)):?>
                <?php foreach ( $projectlists as $project ):?>
                <option value="<?php echo $project['ProjectId'];?>"<?php echo ($project['ProjectId'] == $projectId) ? 'selected' : '';?>><?php echo $project[ 'ProjectName' ];?></option>
                <?php endforeach; ?>
                <?php  endif; ?>
              </select>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-4">
          <div class="form-group">
            <label class="col-sm-7 sel-type">Select Type</label>
            <div class="col-lg-12 form-group">
              <select name="revtype" id="revtype" onChange="ChangeProject();" class="form-control multiple_dropdown lbl_move" style="width:100%;">
                <option value="B" <?php echo $revtype=='B' ? 'selected' : ''; ?>>Budget</option>
                <option value="P" <?php echo $revtype=='P' ? 'selected' : ''; ?>>Plan</option>
              </select>
            </div>
          </div>
        </div>
      </div>
      <div class="row" data-visibility="hide">
        <div class="col-lg-9 col-lg-offset-3 col-sm-9 col-sm-offset-3 edit_del">
          <div class="col-lg-12">
            <ul>
              <li>
                <button type="button" class="edit-btn form-group edit_al" id="print-btn"><i class="fa fa-print"></i> Print</button>
              </li>
              <li>
                <button type="button" class="edit-btn form-group edit_al" id="expand-all">Expand All</button>
              </li>
              <li>
                <button type="button" class="edit-btn form-group edit_al" id="collapse-all">Collapse All</button>
              </li>
            </ul>
          </div>
          <div class="clearfix"></div>
        </div>
      </div>
      <div class="col-lg-12 clear" id="gridWrapper" >
        <div class="table-responsive clear">
          <div id="grid"></div>
          <div id='pager'></div>
        </div>
      </div>
      <?php } else { ?>
      <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 prt-next">
        <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 top-nexts" id="formWrapper">
          <div class="col-lg-12 frmwrk_div" id="projects_list">
            <select name="newproject_id" id="newproject_id" class="form-control multiple_dropdown lbl_move" data-size="6" label="Select Project" style="width:100%">
              <?php if(isset($projectlists)):?>
              <?php foreach ( $projectlists as $project ):?>
              <option value="<?php echo $project[ 'ProjectId' ];?>"><?php echo $project[ 'ProjectName' ];?></option>
              <?php endforeach; ?>
              <?php  endif; ?>
            </select>
          </div>
          <div class="col-lg-12 frmwrk_div" id="types_list" style="display: none;">
            <select name="newrevtype" id="newrevtype" class="form-control multiple_dropdown lbl_move" data-size="6" label="Select Type" style="width:100%">
              <option value="B">Budget</option>
              <option value="P">Plan</option>
            </select>
          </div>
          <div class="savebtn_areas col-lg-7 col-lg-offset-4 col-md-7 col-md-offset-4 col-sm-7 col-sm-offset-4 col-xs-7 col-xs-offset-4">
            <ul>
              <li class="subs"><a href="javascript:void(0);" onClick="submitForm();" id="continue">Submit</a></li>
            </ul>
          </div>
        </div>
      </div>
      <?php } ?>
    </div>
  </div>
</div>
<script>

    var $project = $('#project_select'),
        $projectNew = $('#newproject_id'),
        $type_list = $('#types_list'),
        $type = $('#type_select');

    $(function () {
        $projectNew.on('change', function() {
            var  nproj_id= parseInt(isNullCheck($('#newproject_id').val(),'number'));
            if (nproj_id !=0) $type_list.show();
            else $type_list.hide();
        });
    });


    $dataGrid = $("#grid");
    $(function () {
        /*$("#grid").jqxTreeGrid('expandAll');*/
        var data = <?php echo (isset($itemwisewbs)) ? json_encode($itemwisewbs) : '[]'?>;
        var projectId = <?php if(isset($projectId)) echo json_encode($projectId); else echo '""';?>;
        var revtype = <?php if(isset($revtype)) echo json_encode($revtype); else echo '""'?>;
        if(projectId != 0) {
            var source = {
                localdata:data,
                dataType: "json",
                dataFields: [
                    { name: 'ParentText', type:'string'},
                    { name: 'WBSName', type:'string'},
                    { name: 'Specification', type:'string'},
                    { name: 'Qty', type:'number'},
                    { name: 'Rate', type:'number'},
                    { name: 'Amount', type:'number'}

                ]
            };

            var dataAdapter = new $.jqx.dataAdapter(source);

            var aggregatesrenderer = function (aggregates, column, element, summaryData) {
                var renderstring = "<div class='jqx-widget-content jqx-widget-content-" + theme + "' style='float: left; width: 100%; height: 100%;'>";
                $.each(aggregates, function (key, value) {
//                    var name = key == 'sum' ? 'Sum' : 'Avg';
                    /*var color = 'green';*/
                    if (key == 'sum' && summaryData['sum'] < 650) {
                        color = 'red';
                    }
                  /*  if (key == 'avg' && summaryData['avg'] < 4) {
                        color = 'red';
                    }*/
//                    renderstring += '<div style="position: relative; margin: 6px; text-align: right; overflow: hidden;">' + name + ': ' + value + '</div>';
                    renderstring += '<div style="position: relative; margin: 6px; text-align: right; overflow: hidden;"><strong>' + value + '</strong></div>';
                });
                renderstring += "</div>";
                return renderstring;
            }

            $("#grid").jqxGrid({
                width: '100%',
                pageable: true,
                rowsheight: 35,
                filterable: true,
                showfilterrow: true,
                selectionMode: 'singleRow',
                pagerButtonsCount: 6,
                showaggregates: true,
                showstatusbar: true,
                statusbarheight: 50,
                autoheight:true,
                source: dataAdapter,
                altrows: true,
                enabletooltips: true,
                groupable:true,
                selectionmode: 'singlerow',
                editmode: 'selectedcell',
                columns: [
                    { text: 'ParentName', datafield: 'ParentText',width:'50%'},
                    { text: 'WBSName', datafield: 'WBSName',width:'20%'},
                    { text: 'Specification', dataField: 'Specification',hidden:true},
                    { text: 'Qty', dataField: 'Qty',width:'10%',
                        cellsrenderer: function (row) {
                            return '<div class="text-right" style="margin-top: 10px;">' +sanitizeNumberZeroEmpty($dataGrid.jqxGrid('getCellValue', row, 'Qty'),3) + '</div>';
                        }
                    },
                    { text: 'Rate', dataField: 'Rate',editable:false, width:'10%',
                        cellsrenderer: function (row) {
                            return '<div class="text-right" style="margin-top: 10px;">' +sanitizeNumberZeroEmpty($dataGrid.jqxGrid('getCellValue', row, 'Rate'),2, true) + '</div>';
                        }
                    },
                    { text: 'Amount', dataField: 'Amount',editable:false, width:'10%',cellsformat: 'd2', aggregates: ['sum'],aggregatesrenderer:aggregatesrenderer,
                        cellsrenderer: function (row) {
                            return '<div class="text-right" style="margin-top: 10px;">' +sanitizeNumberZeroEmpty($dataGrid.jqxGrid('getCellValue', row, 'Amount'),2, true) + '</div>';
                        }
                    }
                ],
                groups: ['Specification'],
                groupsrenderer: function (defaultText, group, state, params) {
                    return "<div style='margin: 5px;font-weight: bold;'>" + group +  "</div>";
                },
                ready: function () {
                    $("#grid").jqxGrid('expandallgroups');
                }
            });
        }
    });

    function submitForm() {
        var  nproj_id= parseInt(isNullCheck($('#newproject_id').val(),'number'));
        var  nrevtype= isNullCheck($('#newrevtype').val(),'string');

        if (nproj_id ==0) {
            alert("select Project");
            return;
        }
        if (nrevtype =="") {
            alert("Select Type");
            return;
        }

        window.location.href = getBaseURL() + "project/report/itemwisewbs-report/" + nproj_id + "/" + nrevtype;
    }

    function ChangeProject() {
        var iProjectId = isNullCheck($('#project_id').val(),'number');
        var sType= isNullCheck($('#revtype').val(),'string');
        window.location.href = getBaseURL() + "project/report/itemwisewbs-report/" + iProjectId + "/" + sType;
    }

    $('#expand-all').click(function () {
        $("#grid").jqxGrid('expandallgroups');
    });

    $('#collapse-all').click(function () {
        $("#grid").jqxGrid('collapseallgroups');
    });

    $('#print-btn').click(function () {
        var gridContent = $("#grid").jqxGrid('exportdata', 'html');
        //var gridContent = $("#jqxgrid").jqxGrid('exportdata', 'html', 'jqxGrid', true, null, false);
        var newWindow = window.open('', '', 'width=800, height=500'),
            document = newWindow.document.open(),
            pageContent =
                '<!DOCTYPE html>\n' +
                '<html>\n' +
                '<head>\n' +
                '<meta charset="utf-8" />\n' +
                '<title>Item Wise WBS Abstract</title>\n' +
                '<h1>Item Wise WBS Abstract</h1>\n' +
                '</head>\n' +
                '<body>\n' + gridContent + '\n</body>\n</html>';
        document.write(pageContent);
        document.close();
        newWindow.print();

    });

</script> 
