<!--<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/library/jqgrid/css/ui.jqgrid.css"/>-->
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/library/jqgrid/css/ui.jqgrid-bootstrap.css"/>
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/library/jqgrid/css/ui.jqgrid-bootstrap-ui.css"/>

<!--<script src="-->
<?php //echo $this->basePath(); ?>
<!--/library/jqgrid/src/grid.base.js"></script>-->
<!--<script src="-->
<?php //echo $this->basePath(); ?>
<!--/library/jqgrid/src/grid.celledit.js"></script>-->
<!--<script src="-->
<?php //echo $this->basePath(); ?>
<!--/library/jqgrid/src/grid.celledit.js"></script>-->
<!--<script src="-->
<?php //echo $this->basePath(); ?>
<!--/library/jqgrid/src/grid.common.js"></script>-->
<!--<script src="-->
<?php //echo $this->basePath(); ?>
<!--/library/jqgrid/src/grid.filter.js"></script>-->
<!--<script src="-->
<?php //echo $this->basePath(); ?>
<!--/library/jqgrid/src/grid.formedit.js"></script>-->
<!--<script src="-->
<?php //echo $this->basePath(); ?>
<!--/library/jqgrid/src/grid.grouping.js"></script>-->
<!--<script src="-->
<?php //echo $this->basePath(); ?>
<!--/library/jqgrid/src/grid.import.js"></script>-->
<!--<script src="-->
<?php //echo $this->basePath(); ?>
<!--/library/jqgrid/src/grid.inlinedit.js"></script>-->
<!--<script src="-->
<?php //echo $this->basePath(); ?>
<!--/library/jqgrid/src/grid.jqueryui.js"></script>-->
<!--<script src="-->
<?php //echo $this->basePath(); ?>
<!--/library/jqgrid/src/grid.pivot.js"></script>-->
<!--<script src="-->
<?php //echo $this->basePath(); ?>
<!--/library/jqgrid/src/grid.subgrid.js"></script>-->
<!--<script src="-->
<?php //echo $this->basePath(); ?>
<!--/library/jqgrid/src/grid.treegrid.js"></script>-->
<!--<script src="-->
<?php //echo $this->basePath(); ?>
<!--/library/jqgrid/src/grid.utils.js"></script>-->
<!--<script src="-->
<?php //echo $this->basePath(); ?>
<!--/library/jqgrid/src/jqDnR.js"></script>-->
<!--<script src="-->
<?php //echo $this->basePath(); ?>
<!--/library/jqgrid/src/jqModal.js"></script>-->
<script src="<?php echo $this->basePath(); ?>/library/jqgrid/src/jquery.fmatter.js"></script>
<script src="<?php echo $this->basePath(); ?>/library/jqgrid/src/jquery.jqGrid.js"></script>
<!--<script src="-->
<?php //echo $this->basePath(); ?>
<!--/library/jqgrid/src/jquery.sortable.js"></script>-->
<script src="<?php echo $this->basePath(); ?>/library/jqgrid/src/i18n/grid.locale-en.js"></script>
</head><body>

<!--content-->
<div class="content_wrapper padlr0">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h1>Schedule</h1>
      </div>
      <!--form start-->
      <div class="col-lg-12 top_ct" >
        <table id='grid'></table>
            <div id='pager'></div>
            
      </div>
      <!--table end--> 
    </div>
  </div>
</div>
<div class="col-lg-12 savebtn_area">
  <ul>
    <li class="dropdown save_btn float_r"><a href="javascript:void(0);" data-toggle="tooltip" class="ripple" title="Go to continue !">Continue</a>
    <li class="cancel_btn float_r"><a href="javascript:void(0);" data-toggle="tooltip" class="ripple" title="Go back!">Back</a></li>
    </ul>
</div>
<!--content-->

</body>
</html><script>
    var grid = $("#grid");
    var mydata = <?php echo json_encode($reslists); ?>;

//    Select A.ShTransId,B.Specification,A.sDate,A.Qty from Proj_ScheduleDetails A
//    Inner join Proj_Schedule B on A.ShTransId=B.ShTransId


//    var mydata = [
//        {id: "1", emp:"Michelle", product:"A A", sold:"8"},
//        {id: "2", emp:"Tania", product:"A A", sold:"3"},
//        {id: "6", emp:"Mark", product:"A B", sold:"1"},
//        {id: "3", emp:"Tommy", product:"A B", sold:"5"},
//        {id: "4", emp:"Dave", product:"B B", sold:"2"},
//        {id: "5", emp:"Carol", product:"B B", sold:"5"},
//    ];

    jQuery(document).ready(function(){

//        grid.jqGrid('jqPivot',
//            mydata, {
//                xDimension: [{
//                    dataName: 'ShTransId',
//                    label: 'ID',
//                    width: 90
//                }, {
//                    dataName: 'emp',
//                    label: 'Employee',
//                    width: 90
//                }, ],
//                yDimension: [{
//                    dataName: 'product',
//                    converter: function (val) {return val.replace(/\s/g, '&nbsp;');}
//                }],
//                aggregates: [{
//                    member: 'sold',
//                    aggregator: 'sum',
//                    width: 50,
//                    label: 'Sold'
//                }, ],
//                colTotals: true
//
//            }, {
//                width: "100%",
//                height: "100%",
//                pager: "#pager",
//                caption: "Daily Sales"
//            });


        jQuery("#grid").jqGrid('jqPivot',
            mydata,
            // pivot options
            {
                xDimension : [
                    {dataName: 'Specification', label : 'Specification', width:180}
                ],
                yDimension : [
                    {dataName: 'sDate' , width:180}
                ],
                aggregates : [
                    {member : 'Qty', aggregator : 'sum', width:180, label:'Qty'}
                ],
                rowTotals: true,
                colTotals : true
               // frozenStaticCols : true
            },

            // grid options
            {
               // width:700,
                rowNum : 10,
                pager: "#pager"
               // shrinkToFit: true
                //caption: "Schedule"
            });
    });

//    $('#container-fluid div:not(.ui-jqgrid-titlebar)').width("100%");

    //    $(window).on("resize", function () {
//        var $grid = $("#grid"),
//            newWidth = $grid.closest(".ui-jqgrid").parent().width();
//        $grid.jqGrid("setGridWidth", newWidth, true);
//    }).resize();
	
	

</script>