<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/library/jqgrid/css/ui.jqgrid.css"/>
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/library/jqgrid/css/ui.jqgrid-bootstrap.css"/>
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/library/jqgrid/css/ui.jqgrid-bootstrap-ui.css"/>
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css';?>"/>
<script src="<?php echo $this->basePath(); ?>/library/jqgrid/src/jquery.fmatter.js"></script>
<script src="<?php echo $this->basePath(); ?>/library/jqgrid/src/jquery.jqGrid.js"></script>
<script src="<?php echo $this->basePath(); ?>/library/jqgrid/src/i18n/grid.locale-en.js"></script>
<script src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqxcore.js"></script>
<script type="text/javascript" src="https://jqwidgets.com/public/jqwidgets/jqx-all.js"></script>

<style>.rf-fixed			{margin-top:0px;}</style>
<div class="content_wrapper padlr0">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1><?php echo $shtitle; ?></h1>
                <div class="col-lg-6">
                    <div class="fixed-action-btn active rf-fixed">
                        <a class="btn-floating btn-large">
                            <i class="fa fa-print"></i>
                        </a>
                        <ul>
                            <li>
                                <a class="btn-floating hide-input-file" id="print" href="javascript:void(0);" data-toggle="tooltip" data-placement="top" data-original-title="Print Report">
                                    <i class="fa fa-print"></i>

                                </a>
                            </li>
                            <li>
                                <a class="btn-floating" id="excelExport" href="javascript:void(0);" data-toggle="tooltip" data-placement="top" data-original-title="Download Excel">
                                    <i class="fa fa-download"></i>
                                </a>
                            </li>
                            <li>
                                <a class="btn-floating" id="csvExport" href="javascript:void(0);" data-toggle="tooltip" data-placement="top" data-original-title="Export CSV">
                                    <i class="fa fa-file-archive-o"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-12 col-lg-offset-0 tmss">
                <div class="table-responsive clear">
                    <div id="treeGrid"> </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-lg-12">
	<form method="post" action="<?php echo $this->basePath(); ?>/project/schedule/scheduleview" id="scheduleviewForm">
		<input type="hidden" name="projectId" value="<?php echo $projectId;?>" />
		<input type="hidden" name="typeName" value="<?php echo $revtype;?>" />
	</form>
	<a href="javascript:void(0);" data-text="Go to Schedule" class="gobacklist" onclick="return gotoSchedule();"><i class="fa fa-chevron-circle-left" aria-hidden="true"></i> Go to Schedule</a>
</div>

<script type="text/javascript">

    var shdata = <?php echo json_encode($shdata); ?>;
    var shtitle = <?php echo json_encode($shtitle); ?>;

    var $treeGrid = $("#treeGrid");
    $(function () {

        var source = {
            localdata:shdata,
            dataType: "json",
            dataFields: [
                { name: 'Id'},
                { name: 'Parent'},
                { name: 'Specification'},
                { name: 'StartDate'},
                { name: 'EndDate'},
                { name: 'Duration'},
                { name: 'Predecessor'},
            ],
            hierarchy:
            {
                keyDataField: { name: 'Id' },
                parentDataField: { name: 'Parent' }
            },
            id: 'Id'
        };

        var dataAdapter = new $.jqx.dataAdapter(source);

        var cellsRenderer = function (row, column, value, rowData)
        {
            if (rowData.records !== undefined)
            {
                return '<span style="font-weight: bold;">' + value + '</span>';
            } else
            {
                return '<span>' + value + '</span>';
            }
        };

        $treeGrid.jqxTreeGrid({
            width: "100%",
            source: dataAdapter,
            exportSettings: {fileName: null},
            height:"490",
            pageable:true,
            columns: [
                { text: 'TaskId', dataField: 'Id',width:'10%', cellsRenderer: cellsRenderer },
                { text: 'Specification', dataField: 'Specification',width:'40%', cellsRenderer: cellsRenderer },
                { text: 'Duration', dataField: 'Duration',width:'10%', cellsRenderer: cellsRenderer },
                { text: 'StartDate', dataField: 'StartDate',width:'15%', cellsRenderer: cellsRenderer },
                { text: 'EndDate', dataField: 'EndDate',width:'15%', cellsRenderer: cellsRenderer },
                { text: 'Predecessor', dataField: 'Predecessor',width:'10%', cellsRenderer: cellsRenderer }
            ]
        });

        //$treeGrid.jqxTreeGrid('expandAll');
        $("#treeGrid").jqxTreeGrid('expandAll');
    });

    //Print option
    $("#excelExport").click(function () {
        $("#treeGrid").jqxTreeGrid('exportData', 'xls', 'jqxGrid');
    });
    $("#csvExport").click(function () {
        $("#treeGrid").jqxTreeGrid('exportData', 'csv', 'jqxGrid');
    });
    $("#htmlExport").click(function () {
        $("#treeGrid").jqxTreeGrid('exportData', 'html', 'jqxGrid');
    });

    $("#print").click(function () {
        var gridContent = $("#treeGrid").jqxTreeGrid('exportData', 'html');
        var newWindow = window.open('', '', 'width=800, height=500'),
            document = newWindow.document.open(),
            pageContent =
                '<!DOCTYPE html>' +
                '<html>' +
                '<head>' +
                '<meta charset="utf-8" />' +
                '<title>' + shtitle +  '</title>' +
                '<h1>' + shtitle + '</h1>' +
                '</head>' +
                '<body>' + gridContent + '</body></html>';
        document.write(pageContent);
        document.close();
        newWindow.print();
    });

    //    function  printTable() {
    //        $("#treeGrid").jqxTreeGrid('exportData', 'pdf', 'ResourceList');
    //    }
	
function gotoSchedule()
{
	$('#scheduleviewForm').submit();
}
</script>