<ul class="modl_lmenu">
    <h2>Project</h2>
    <li><a href="<?php echo $this->basePath(); ?>/project/dashboard/projectmain" class="ripple"><i class="fa fa-tachometer"></i><span class="nav-label">Project Dashboard</span></a></li>
    <li><a href="<?php echo $this->basePath(); ?>/project/dashboard/landbank" class="ripple"><i class="fa fa-tachometer"></i><span class="nav-label">LandBank Dashboard</span></a></li>
    <li><a href="<?php echo $this->basePath(); ?>/project/dashboard/contract" class="ripple"><i class="fa fa-tachometer"></i><span class="nav-label">Contract Dashboard</span></a></li>
    <li><a href="<?php echo $this->basePath(); ?>/project/communication/useractivities" class="ripple"><i class="fa fa-tachometer"></i><span class="nav-label">Communication</span></a></li>
    <li><a href="javascript:void(0);" class="ripple modlsub_open"><i class="fa fa-cogs" aria-hidden="true"></i><span class="nav-label">Setup</span></a>
        <ul>
            <li><a href="<?php echo $this->basePath(); ?>/project/main/codesetup" class="ripple">Resource Code</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/main/rgcodesetup" class="ripple">Resource Group Code</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/main/restypecode" class="ripple">Resource Type Code</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/main/worktypecodesetup" class="ripple">Work Type Code</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/main/workgroupcodesetup" class="ripple">Work Group Code</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/main/revisionnamesetup" class="ripple">Revision Name</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/main/schedulenamesetup" class="ripple">Schedule Name</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/main/measurement-template" class="ripple">Measurement Template</a></li>
        </ul>
    </li>
    <li><a href="javascript:void(0);" class="ripple modlsub_open"><i class="fa fa-clone" aria-hidden="true"></i> <span class="nav-label">Land Bank</span></a>
        <ul>
            <li><a href="<?php echo $this->basePath(); ?>/project/landbank/enquiry" class="ripple">Enquiry</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/landbank/followup" class="ripple">Followup</a></li>
            <!--            <li><a href="--><?php //echo $this->basePath(); ?><!--/project/landbank/initialfeasibility" class="ripple">Initial Feasibility</a></li>-->
            <!--            <li><a href="--><?php //echo $this->basePath(); ?><!--/project/landbank/businessfeasibility" class="ripple">Business Feasibility</a></li>-->
            <!--            <li><a href="--><?php //echo $this->basePath(); ?><!--/project/landbank/financialfeasibility" class="ripple">Financial Feasibility</a></li>-->
            <!--            <li><a href="--><?php //echo $this->basePath(); ?><!--/project/landbank/duediligence" class="ripple">Due Diligence</a></li>-->
            <!--            <li><a href="--><?php //echo $this->basePath(); ?><!--/project/landbank/finalization" class="ripple">Finalization</a></li>-->
            <!--            <li><a href="--><?php //echo $this->basePath(); ?><!--/project/landbank/projectconception" class="ripple">Project Conception</a></li>-->
            <li><a href="<?php echo $this->basePath(); ?>/kickoff/index/project-kickoff" class="ripple">Project Kickoff</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/landbank/register" class="ripple">Land Bank Register</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/landbank/followup-register" class="ripple">Followup Register</a></li>
        </ul>
    </li>
    <li><a href="javascript:void(0);" class="ripple modlsub_open"><i class="fa fa-folder-o" aria-hidden="true"></i> <span class="nav-label">Contract</span></a>
        <ul>
            <li><a href="<?php echo $this->basePath(); ?>/project/tender/enquiry" class="ripple">Enquiry</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/followup/followup" class="ripple">Followup</a></li>
<!--            <li><a href="--><?php //echo $this->basePath(); ?><!--/project/tender/quotation" class="ripple">Quotation</a></li>-->
<!--            <li><a href="--><?php //echo $this->basePath(); ?><!--/project/tender/workorder" class="ripple">Work Order</a></li>-->
            <li><a href="<?php echo $this->basePath(); ?>/project/tender/tenderregister" class="ripple">Enquiry Register</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/followup/register" class="ripple">Followup Register</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/tender/quotationregister" class="ripple">Quotation Register</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/tender/workorderregister" class="ripple">Work Order Register</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/tender/emdregister" class="ripple">EMD Register</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/tender/clientmaster" class="ripple">Client Master</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/tender/consultantmaster" class="ripple">Consultant Master</a></li>
        </ul>
    </li>
    <li><a href="javascript:void(0);" class="ripple modlsub_open"><i class="fa fa-file-text-o" aria-hidden="true"></i> <span class="nav-label">Request for Creation</span></a>
        <ul>
            <li><a href="<?php echo $this->basePath(); ?>/project/rfc/rfc-what" class="ripple">Entry</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/rfc/rfcregister" class="ripple">Register</a></li>
        </ul>
    </li>
    <li><a href="javascript:void(0);" class="ripple modlsub_open"><i class="fa fa-book" aria-hidden="true"></i><span class="nav-label">Library</span></a>
        <ul>
            <li><a href="<?php echo $this->basePath(); ?>/project/main/uomregister" class="ripple">UOM Register</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/qualifier/qualifiermaster" class="ripple">Qualifier</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/main/resgroupmaster" class="ripple">Resource Group</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/main/resourcemaster" class="ripple">Resource</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/main/worktypemaster" class="ripple">Work Type</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/main/workgroupmaster" class="ripple">Work Group</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/main/iowmasterview" class="ripple">Item of Work</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/main/servicemaster" class="ripple">Service</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/main/adminexpense" class="ripple">Admin Expense</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/main/othercostmaster" class="ripple">Other Cost</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/landbank/checklist" class="ripple">CheckList</a></li>
        </ul>
    </li>
    <li><a href="javascript:void(0);" class="ripple modlsub_open"><i class="fa fa-building-o" aria-hidden="true"></i> <span class="nav-label">Project</span></a>
        <ul>
            <li><a href="<?php echo $this->basePath(); ?>/project/rfc/projectboq" class="ripple">Bill of Quantity</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/rfc/projectwbs" class="ripple">Work BreakDown Structure</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/rfc/resourcerateview" class="ripple">Resource Rate</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/main/othercost" class="ripple">Other Cost</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/main/revisionmaster" class="ripple">Revision Master</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/main/wbsmaster" class="ripple">WBS Master</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/schedule/scheduleview" class="ripple">Schedule</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/rfc/wbsbudget" class="ripple">WBS Budget</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/schedule/wbsscheduleview" class="ripple">WBS Schedule</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/communication/index" class="ripple">Communication Setting</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/main/photo-progress" class="ripple">Photo Progress</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/rfc/reminder" class="ripple">Reminders</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/rfc/highlights" class="ripple">News/Highlights</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/main/holidaysetting" class="ripple">Holiday Setting</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/project/main/copyprojectboq" class="ripple">Copy Other Project BOQ</a></li>
        </ul>
    </li>
    <li><a href="<?php echo $this->basePath(); ?>/project/report/reportlist" class="ripple"><i class="fa fa-flag "></i><span class="nav-label">Reports</span></a></li>
</ul>
