<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/request.css';?>"/>

<style>
#allReqDecisionList .jqx-grid-header 	{height:75px !important;}
#allTermList .jqx-grid-header 	{height:75px !important;}
#allVendorList .jqx-grid-header 	{height:75px !important;}
.blubg{background : #B0C3EB !important;}
.error{
	border: 1px solid #fa8072 !important;
	color: red !important;
}
.jqx-grid-column-header .jqx-checkbox-default{
	display:none;
}
</style>

<?php 
	echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
			->appendStylesheet($this->basePath() . '/library/fileupload/css/demo.css')
			->appendStylesheet($this->basePath() . '/library/fileupload/css/uploader.css')
			->appendStylesheet($this->basePath() . '/css/select2.min.css');
?>
<div class="content_wrapper  padlr0">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
		<form class="form-horizontal" method="post" enctype="multipart/form-data">
			<div class="panel-group" id="accordion9" role="tablist" aria-multiselectable="true">
			  <div class="panel panel-default" id="firstStep">
				<div class="panel-heading accordion_head" style="cursor:pointer" role="tab" id="heading20" data-toggle="collapse" data-parent="#accordion9" href="#collapse20" aria-expanded="true" aria-controls="collapse20">
				  <h4>Rfq Details<?php echo ($genType) ? '-'.$voucherNo: ''; ?>
					<span class="vendor_grade float_r" id="materialSpan">&nbsp</span>
					<span class="vendor_grades float_r">Quotation Type :</span>
				  </h4>
				</div>
				<div id="collapse20" class="panel-collapse collapse in" role="tabpanel" style="overflow: hidden;" aria-labelledby="heading20">
				  <div class="panel-body">
					<div class="col-lg-12">
					  <h1 class="txt_center form_main_h1 frmwrk_h1">Request For Quotation <?php echo ($genType) ? '- '.$voucherNo: ''; ?></h1>
					</div>
					<div class="col-lg-4 col-lg-offset-8 col-md-2 col-lg-offset-10 col-sm-2 col-sm-offset-10 col-xm-offset-10 col-xm-2 ">
					  <p style="text-align:right; color:#00aeef; font-style:italic;"><i class="fa fa-calendar"></i>&nbsp;Date :  <input class="date_picker" type="text" name="rfq_date" id="rfq_date" value="<?php echo date('d-m-Y');?>" readonly /></p>
					</div>
					<div class="form-group">
					  <div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 req_flds">
						<div class="row" style="<?php echo ($genType) ? 'display:none' : ''; ?>">
							<div class="form-group req_flds col-lg-12">
								<input type="text" class="form-control lbl_move modalInput" label="Voucher No" name="VoucherNo" id="VoucherNo" value="<?php echo $voucherNo; ?>" >
								<div class="error_message"><p>Please enter voucher no...</p> </div>
							</div>
						</div>					  
						  <div class="row">
							<div class="form-group col-lg-12">
							  <input type="text" class="form-control  lbl_move modalInput " label="Quotation Type" name="autocomplete-qtnType" id="autocomplete-qtnType">
							  <input type="hidden" name="qtn_type" id="qtn_type" class="form-control nextVal">
							  <input type="hidden" name="qtnType" id="qtnType" class="form-control nextVal">
							  <input type="hidden" name="qtype" id="qtype" class="form-control nextVal" value="<?php echo (isset($quotType)) ? $quotType : '';?>" >
							  <div class="error_message"><p>Please select quotation type...</p> </div>
							</div>
						  </div>
						  <!--<div class="row">
							<div class="form-group req_flds col-lg-12">heading21
							  <input type="text" class="form-control nextVal" label="Select One or More Projects" name="project_name" id="project_name" >
							  <div class="error_message"><p>Please select project name...</p> </div>
							</div>
						  </div>-->
                          <?php
                           if($quotType == 'Q'){?>
							<div class="row">
								<div class="form-group req_flds col-lg-12">
									<select name="project_name[]" id="project_name" class="form-control multiple_dropdown lbl_move nextVal"  multiple="multiple" label="Projects" style="width:100%;">
										<?php
											foreach($projects as $type){
												echo "<option value='".$type['id']."' >".$type['name']."</option>";
											}
										?>
									</select>
									<div class="error_message"><p>Please Select Projects...</p></div>
								</div>
							</div>
                          <?php }
                          else{ ?>
                              <div class="row">
                                  <div class="form-group req_flds col-lg-12">
                                      <select name="project_name[]" id="project_name" class="form-control multiple_dropdown lbl_move nextVal"  multiple="multiple" label="Enquiry" style="width:100%;">
                                          <?php
                                          foreach($tenderProjects as $type1){
                                              echo "<option value='".$type1['id']."' >".$type1['name']."</option>";
                                          }
                                          ?>
                                      </select>
                                      <div class="error_message"><p>Please Select Projects...</p></div>
                                  </div>
                              </div>
                          <?php } ?>
							<!--div class="form-group req_flds col-lg-12">
								<!--<select class="js-example-data-array lbl_move" name="project_name" label="Quotation Type"  project_name multiple="multiple" id="project_name" style="width:100%;"></select>-->
								<!--input type="text" class="form-control multiple_dropdown nextVal" label="Select One or More Projects"  name="project_name[]" id="project_name" >
								<div class="error_message"><p>Please select project name...</p> </div>
							</div-->
						   
						  <div class="row">
							<div class="form-group col-lg-12 req_flds"> <span class="date_icon"><i class="fa fa-calendar"></i></span>
							  <input type="text" name="biddue_date" id="biddue_date" class="form-control lbl_move datepickerinput modalInput" value="<?php echo date('d-m-Y');?>" label="Bid Due Date" />
							  <div class="error_message"><p>Please enter bid due date...</p> </div>
							</div>
						  </div>
						  <div class="row col-lg-12">
							<ul>
							  <li class="col-lg-9">
								<p style="color: #222222;font-size:15px;padding-top: 5px;">Need technical verification</p>
							  </li>
							  <li class="col-lg-2 col-lg-offset-1">
								<span class="float_r"><label class="ripple"><input class="ios_checkbox" type="checkbox" name="verify_yes" id="verify_yes" value="1" checked /><div class="ios_switch"><span></span></div></label></span>
							  </li>
							</ul>
						  </div>
					  </div>
					  <div class="col-lg-12">
						  <ul>
							<li class="dropdown save_btn float_r"> <a href="javascript:void(0);" class="ripple continueButton">Continue</a> </li>
						  </ul>
						</div>
					</div>
				  </div>
				</div>
			  </div>
			<div class="panel panel-default" id="techVerify">
				<div class="panel-heading accordion_head" style="cursor:pointer" role="tab" id="heading33"  data-toggle="collapse" data-parent="#accordion9" href="#collapse33" aria-expanded="false" aria-controls="collapse33">
				  <h4>Ask for required technical specification documents</h4>
				</div>
				<div id="collapse33" class="panel-collapse collapse" role="tabpanel" style="height:485px; overflow: hidden;" aria-labelledby="heading33">
					<div class="panel-body">
						<div class="col-lg-12 clear">
						<h1 class="form_main_h1 frmwrk_h1">Required Documents name </h1>
						<div class="col-lg-10 col-lg-offset-1 clear">
							<div class="table-responsive clear">
								<table class="table table-hover clear" id="documentTable">
									<tbody>
										<tr>
											<td width="11%">
												<input class="parent_txts newRow delFirst" placeholder="Document Name" type="text" id="Document_name_1" name="Document_name_1" tagname="Document_name" />
											</td>
											<td width="11%">
												<input class="parent_txts delFirst" placeholder="Description about the docment" type="text" id="Description_doc_1" name="Description_doc_1" tagname="Description_doc" />
											</td>
											<td width="11%"><input class="parent_txts delFirst" placeholder="File format" type="text" id="File_format_doc_1" name="File_format_doc_1" tagname="File_format_doc" /></td>
											<td width="4%"><a href="#" class="remove vendar_styles"><span class="glyphicon glyphicon-trash" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></span></a></td>
										</tr>                                           
									</tbody>
								</table>
								<input type="hidden" class="parent_txts" name="RowCountdoc" id="RowCountdoc" value="1" />
							</div>
						</div>
						</div>
						<div class="col-lg-12 commargin_bottom commargin_top clear">
							<h1 class="form_main_h1 frmwrk_h1">Detailed Description</h1>
							<div class="col-lg-6 col-lg-offset-3">
								<div class="row">
									<div class="form-group req_flds">
										<textarea id="detailed_description" name="detailed_description" class="form-control lbl_move modalInput" label="Enter detail description or information about this bid.."/></textarea>
										<div class="error_message"><p>Please enter description about bid...</p> </div>
									</div>
									<div class="radio_check">
										<p>
										   <input type="checkbox" id="web_finalization" name="web_finalization" />
										   <label for="web_finalization" class="ripple">Send Bid Detail after Verification</label>
										</p>
									</div>
								</div>
							</div>
						</div>
						<div class="col-lg-12 commargin_bottom commargin_top">
							<ul>
								<li class="dropdown save_btn float_r"> <a href="javascript:void(0);" class="ripple continueButton">Continue</a> </li>
							</ul>
						</div>
					</div>
				</div>
			</div>
              <!--- Project-start ---->
              <?php
              if($quotType == 'Q'){?>
			<div class="panel panel-default">
				<div class="panel-heading accordion_head" style="cursor:pointer" role="tab" id="heading21"  data-toggle="collapse" data-parent="#accordion9" href="#collapse21" aria-expanded="false" aria-controls="collapse21">
					<h4 id="reqHead">Select required Request for this rfq!
						<span class="vendor_grade float_r" id="totaldecision">0</span>
						<span class="vendor_grades float_r">Total No Request/Decision : </span>
					</h4>
				</div>
				<div id="collapse21" class="panel-collapse collapse" role="tabpanel" style="height:485px; overflow: hidden;" aria-labelledby="heading21">
					<div class="panel-body">
						<div class="col-lg-12 clear">
							<h1 id='reqHead1' class="txt_center commargin_top commargin_bottom">List of all Request/Decision from selected projects</h1>
							<div class="table-responsive clear">
								<div id='jqxWidget'>
									<div id="allReqDecisionList"> </div>
								</div>
							</div>
							<input type="hidden" name="decisionId" id="decisionId">
						</div>
						<div class="col-lg-12 commargin_bottom commargin_top">
							<ul>
								<li class="col-lg-2 commargin_top" style="width:300px;">
									<p id="reqHead2" style="background:#c2ecfd;text-align:center;width:300px;">Selected<span class="vendortoc-number float_r" id="countdecision">0</span></p>
								</li>
								<li class="dropdown save_btn float_r"> <a href="javascript:void(0);" class="ripple continueButton">Continue</a> </li>
							</ul>
						</div>
					</div>
				</div>
			</div>
                  <!--- end of project ----->
              <?php } else{ ?>
              <!----- start-tender ----->

              <div class="panel panel-default">
                  <div class="panel-heading accordion_head" style="cursor:pointer" role="tab" id="heading21"  data-toggle="collapse" data-parent="#accordion9" href="#collapse21" aria-expanded="false" aria-controls="collapse21">
                      <h4>Select required Request for this rfq!
                          <span class="vendor_grade float_r" id="totalrequest">0</span>
                          <span class="vendor_grades float_r">Total No Request : </span>
                      </h4>
                  </div>
                  <div id="collapse21" class="panel-collapse collapse" role="tabpanel" style="height:485px; overflow: hidden;" aria-labelledby="heading21">
                      <div class="panel-body">
                          <div class="col-lg-12 clear">
                              <h1 class="txt_center commargin_top commargin_bottom">List of all Request from selected projects</h1>
                              <div class="table-responsive clear">
                                  <div id='jqxWidget'>
                                      <div id="allReqRequestList"> </div>
                                  </div>
                              </div>
                              <input type="hidden" name="requestId" id="requestId">
                          </div>
                          <div class="col-lg-12 commargin_bottom commargin_top">
                              <ul>
                                  <li class="col-lg-2 commargin_top">
                                      <p style="background:#c2ecfd;text-align:center;">Request Selected<span class="vendortoc-number float_r" id="countrequest">0</span></p>
                                  </li>
                                  <li class="dropdown save_btn float_r"> <a href="javascript:void(0);" class="ripple continueButton">Continue</a> </li>
                              </ul>
                          </div>
                      </div>
                  </div>
              </div>
              <!---- end of tender ----->
              <?php } ?>

              <!----- project decision --->
              <?php
              if($quotType == 'Q'){?>
			  <div class="panel panel-default">
				<div class="panel-heading accordion_head" style="cursor:pointer" role="tab" id="heading22" data-toggle="collapse" data-parent="#accordion9" href="#collapse22" aria-expanded="false" aria-controls="collapse22">
				  <h4>Select Resources and Enter Quantity
					<span class="vendor_grade float_r">Selected</span>
					<span class="vendor_grades float_r"><strong id="resourceList">0</strong></span>
					<span class="vendor_grades float_r">Resources are listed from </span>
				  </h4>
				</div>
				<div id="collapse22" class="panel-collapse collapse" role="tabpanel" style="height:485px; overflow: hidden;" aria-labelledby="heading22">
				  <div class="panel-body">
					<div class="col-lg-12 ">
					  <h1 id="reqHead3" class="txt_center commargin_top commargin_bottom">All Resources from the Request/Decisions</h1>
					  </div> 
						 <div class="col-lg-12 clear">
					<div class="table-responsive clear">
						<div id="thirdStep" style="">		
								<div class="form-group" style="margin-top:20px;">
									<div id="sequentialViewDiv">
										<table id="sequentialView" class="table table-bordered tableView" style="margin-top:20px;">
											<thead>
												<tr>
													<th>Code</th>
													<th>Description</th>
													<th>Unit</th>
													<th style="text-align:center;">Balance Quantity</th>
													<th style="text-align:center;">Quantity</th>
												</tr>
											</thead>
											<tbody class="appendData">
											</tbody>
										</table>
									</div>
									<div id="subtableView" style="display:none;">
										<table id="sequentialViewSub" class="table table-bordered tableView" style="margin-top:20px;">
											<thead>
												<tr>
													<th>Sample</th>
												</tr>
											</thead>
											<tbody class="subTable">
											</tbody>
										</table>
										<table id="cloneTable" class="table table-bordered tableView" style="margin-top:20px;">
										</table>
										<table id="resourceTable" class="table request_poptable table-hover clear" style="margin-top:20px;">
											<thead>
												<tr>
													<th width="20%">Code</th>
													<th width="30%">Description</th>
													<th width="10%">Unit</th>
													<th width="20%" style="text-align:right;">Balance Quantity</th>
													<th width="20%" style="text-align:right;">Quantity</th>
												</tr>
											</thead>
											<tbody class="appendResource">
											</tbody>
										</table>
									</div>		
									<input type="hidden" name="hidJson" id="hidJson">
								</div>
							</div>
					</div>
				</div>
					<div class="col-lg-12">
					  <ul>
						<li class="dropdown save_btn float_r"> <a href="javascript:void(0)" class="ripple continueButton">Continue</a> </li>
					  </ul>
					</div>
				  </div>
				</div>
			  </div>
              <!---- end of projectdecision ---->
              <?php } else{ ?>
              <!----- tender --->
              <div class="panel panel-default">
                  <div class="panel-heading accordion_head" style="cursor:pointer" role="tab" id="heading22" data-toggle="collapse" data-parent="#accordion9" href="#collapse22" aria-expanded="false" aria-controls="collapse22">
                      <h4>Select Resources and Enter Quantity
                          <span class="vendor_grade float_r">Selected Requests</span>
                          <span class="vendor_grades float_r"><strong id="resourceList1">0</strong></span>
                          <span class="vendor_grades float_r">Resources are listed from </span>
                      </h4>
                  </div>
                  <div id="collapse22" class="panel-collapse collapse" role="tabpanel" style="height:485px; overflow: hidden;" aria-labelledby="heading22">
                      <div class="panel-body">
                          <div class="col-lg-12 ">
                              <h1 class="txt_center commargin_top commargin_bottom">All Resources from the Requests</h1>
                          </div>
                          <div class="col-lg-12 clear">
                              <div class="table-responsive clear">
                                  <div id="thirdStep" style="">
                                      <div class="form-group" style="margin-top:20px;">
                                          <div id="sequentialViewDiv">
                                              <table id="sequentialView" class="table table-bordered tableView" style="margin-top:20px;">
                                                  <thead>
                                                  <tr>
                                                      <th>Code</th>
                                                      <th>Description</th>
                                                      <th>Unit</th>
                                                      <th style="text-align:center;">Balance Quantity</th>
                                                      <th style="text-align:center;">Quantity</th>
                                                  </tr>
                                                  </thead>
                                                  <tbody class="appendData">
                                                  </tbody>
                                              </table>
                                          </div>
                                          <div id="subtableView" style="display:none;">
                                              <table id="sequentialViewSub1" class="table table-bordered tableView" style="margin-top:20px;">
                                                  <thead>
                                                  <tr>
                                                      <th>Sample</th>
                                                  </tr>
                                                  </thead>
                                                  <tbody class="subTable">
                                                  </tbody>
                                              </table>
                                              <table id="cloneTable" class="table table-bordered tableView" style="margin-top:20px;">
                                              </table>
                                              <table id="resourceTable1" class="table request_poptable table-hover clear" style="margin-top:20px;">
                                                  <thead>
                                                  <tr>
                                                      <th>Code</th>
                                                      <th>Description</th>
                                                      <th>Unit</th>
                                                      <th style="text-align:center;">Balance Quantity</th>
                                                      <th style="text-align:center;">Quantity</th>
                                                  </tr>
                                                  </thead>
                                                  <tbody class="appendResource">
                                                  </tbody>
                                              </table>
                                          </div>
                                          <input type="hidden" name="hidJson" id="hidJson">
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div class="col-lg-12">
                              <ul>
                                  <li class="dropdown save_btn float_r"> <a href="javascript:void(0)" class="ripple continueButton">Continue</a> </li>
                              </ul>
                          </div>
                      </div>
                  </div>
              </div>
              <?php } ?>
              <!----- end of tender---->

			  <div class="panel panel-default">
				<div class="panel-heading accordion_head" style="cursor:pointer" role="tab" id="heading26" data-toggle="collapse" data-parent="#accordion9" href="#collapse26" aria-expanded="false" aria-controls="collapse26">
				  <h4>Enter additional details about this Bid
					  <span class="vendor_grade float_r" id="totalResourse">0</span>
					  <span class="vendor_grades float_r">Total No of Resources :</span>
				  </h4>
				</div>
				<div id="collapse26" class="panel-collapse collapse" role="tabpanel" style="height:485px; overflow: hidden;" aria-labelledby="heading26">
				  <div class="panel-body">
					<div class="col-lg-12 clear">
					
					
						<div class="row demo-columns">
							<div class="col-md-6">
								<!-- D&D Zone-->
								<input type="hidden" name="fileList" id="fileList">
								<div id="drag-and-drop-zone" class="uploader">
									<div>Drag &amp; Drop Files Bid Related Documents Here</div>
									<div class="or">-or-</div>
									<div class="browser">
										<label>
											<span>Click to upload the Bid Related Documents</span>
											<input type="file" name="files[]"  multiple="multiple" title='Click to add Images'>
										</label>
									</div>
								</div>
								<!-- /D&D Zone -->
							</div>
							<!-- / Left column -->

							<div class="col-md-6">
								<div class="panel panel-default">
									<div class="panel-heading">
										<h3 class="panel-title">Bid documents</h3>
									</div>
									<div class="panel-body demo-panel-files" id='demo-files' file-counter="0">
										<span class="demo-note">No Files have been selected/droped yet...</span>
									</div>
								</div>
							</div>
							<!-- / Right column -->
						</div>					
						<div class="col-lg-6" id="contact">
							<h1 class="vendorrequest_text commargin_bottom">Contact Information</h1>
							 <div class="col-lg-9 col-lg-offset-1">
								<div class="row">
									<div class="commargin_bottom">
									  <input type="text" class="form-control lbl_move modalInput" placeholder="Contact Name" name="contact_name" id="contact_name">
									</div>
								</div>
								<div class="row">
								<div class="commargin_bottom">
									  <input type="text" class="form-control lbl_move modalInput" maxlength="10" onkeypress="return isNumberKey(event);" placeholder="Contact Number" name="contact_number" id="contact_number">
                                    <div class="error_message"><p>Please type correct 10 digit Contact No...</p> </div>
									</div>
								</div>
								 <div class="row">
									<div class="commargin_bottom">
									  <input type="text" class="form-control lbl_move modalInput" placeholder="Designation" name="contact_designation" id="contact_designation">
									</div>
								 </div>
							 </div>     	
						</div>  
						<div class="col-lg-6" id="delivery">        
							<h1 class="vendorrequest_text commargin_bottom">Delivery Location</h1>
							<div class="col-lg-9 col-lg-offset-1"> 
								<div class="row">
									<div class="commargin_bottom">
									  <input type="text" class="form-control lbl_move modalInput" placeholder="Address Line1" name="delivery_address1" id="delivery_address1">
									</div>
								</div>
								<div class="row">
								<div class="commargin_bottom">
									  <input type="text" class="form-control lbl_move modalInput" placeholder="Address Line2" name="delivery_address2" id="delivery_address2">
									</div>
								</div>
								 <div class="row">
								  <div class="commargin_bottom">  
									  <input type="text" class="form-control lbl_move modalInput" placeholder="Address Line3" name="delivery_address3" id="delivery_address3">
								  </div>  
								 </div>
							 </div>    	
						 </div>
						 <div class="col-lg-12 commargin_top">         	 
							 <h1 class="vendorrequest_text commargin_bottom">Bid Information</h1>
							  <div class="col-lg-10 col-lg-offset-1">
									<div class="row">
										  <textarea id="bid_description" name="bid_description" class="form-control lbl_move modalInput" placeholder="Enter detail description or information about this bid.."/></textarea>
									</div>
							   </div>   
							 </div>     	      		
					  </div>
					<div class="col-lg-12">
					  <ul>
						<li class="dropdown save_btn float_r"> <a href="javascript:void(0);" class="ripple continueButton">Continue</a> </li>
					  </ul>
					</div>
				  </div>
				</div>
			  </div>

			  
			  
			  
			  
			<!-- Terms and condition details --->
			<div class="panel panel-default">
				<div class="panel-heading accordion_head" style="cursor:pointer" role="tab" id="heading28" data-toggle="collapse" data-parent="#accordion9" href="#collapse28" aria-expanded="false" aria-controls="collapse28">
					<h4>Enter Required details for this Bid and Terms and Condition </h4>
				</div>
				<div id="collapse28" class="panel-collapse collapse" role="tabpanel" style="height:485px; overflow: hidden;" aria-labelledby="heading28">
					<div class="panel-body bgcolr">
						<div class="col-lg-12">
							<div class="col-lg-3" style="margin-top:10px;">
								<select name="valuefrom" id="valuefrom" class="form-control single_dropdown sortoption" data-placeholder="Amount" style="width:100%;">
									<option value="BaseAmount">Base Amount</option>
									<option value="NetAmount">Net Amount</option>
									<option value="GrossAmount">Gross Amount</option>
								</select>
								<script>
									$(document).ready(function(){

										var tCount =  $('#termsTable tbody tr').length;
										if(tCount > 1){
											$('#valuefrom').attr("disabled", true);
										} else {
											$('#valuefrom').attr("disabled", false);
										}
									});
								</script>
							</div>
						</div>
						<div class="col-lg-12">
							<div class="top-30 bot-20">
								<table class="table table-bordered tableView dataTable no-footer" style=" margin-bottom:0px;" id="termsTable" >
									<thead>
									<tr>
										<th class="blubg">Sl.No</th>
										<th class="blubg">Terms</th>
										<th class="blubg">Percentage</th>
										<th class="blubg">Value</th>
										<th class="blubg">Period</th>
										<th class="blubg">Date</th>
										<th class="blubg">Description</th>
										<th class="blubg"></th>
									</tr>
									</thead>
									<tbody class="main"></tbody>
								</table>
								<input type="hidden" name="trowid" id="trowid" value="0"/>
							</div>
							<div class="col-lg-12">
								<ul>
									<li class="dropdown save_btn float_r"> <a href="javascript:void(0);" class="ripple continueButton">Continue</a> </li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
            <!--- stop ---->
			

              <!-- final panel details --->
			<div class="panel panel-default">
				<div class="panel-heading accordion_head" style="cursor:pointer" role="tab" id="heading27" data-toggle="collapse" data-parent="#accordion9" href="#collapse27" aria-expanded="false" aria-controls="collapse27">
					<h4>Enter Required details for this Bid and select Vendors </h4>
				</div>
				<div id="collapse27" class="panel-collapse collapse" role="tabpanel" style="height:485px; overflow: hidden;" aria-labelledby="heading27">
					<div class="panel-body">
						<div class="col-lg-12">
						<h1 class="txt_center commargin_top commargin_bottom">Terms & Conditions</h1>
							<div class="table-responsive" style="min-height:200px; max-height:500px;">
								<div class="col-lg-6 col-md-6">
									<div id='jqxWidget'>
										<div id="allVendorList"> </div>
									</div>
									<input type="hidden" name="vendorListId" id="vendorListId">
								</div>
								<div class="col-lg-6 col-md-6">
									<div id='jqxWidget'>
										<div id="allTermList"> </div>
									</div>
									<input type="hidden" name="termListId" id="termListId">
								</div>
								<div class="col-lg-6 col-md-6 col-sm-6 vendor_request_areabackground commargin_top">
									<div class="form-group">
										<div class="col-lg-12 commargin_top_20">
											<textarea label="Narration about the quotation" class="form-control lbl_move modalInput" id="narration_submittal" name="narration_submittal"></textarea>
										</div>
									</div>
								</div>
								<div class="col-lg-6 col-md-6 vendor_request_areabackground commargin_bottom commargin_top">
									<div class="commargin_top col-lg-12">
										<ul>
											<li class="float_l">
												<p style="color: #222222;font-weight: 600 !important; font-size:15px;padding-top: 5px;">Submittals</p>
											</li>
											<li class="float_l">
												<span class="float_r"><label class="ripple"><input class="ios_checkbox" type="checkbox" name="submittal_yes" id="submittal_yes" checked /><div class="ios_switch"><span></span></div></label></span>
											</li>
										</ul>
									</div>
									<div class="col-lg-12 commargin_top_20">
										<!--<form class="form-horizontal col-lg-10">
											<div class="row">
												<div class="form-group req_flds">
													<input type="text" class="form-control lbl_move" label="Enter submittal name">
												</div>
											</div>
										</form>
										<div> 
											<a href="#" data-placement="top" data-toggle="tooltip" class="ripple has-ripple" data-original-title="AddNewsubmittal">
												<span class="edit_symbols" style="display: block; margin-top: 8px !important;">
													<i class="fa fa-plus"></i>
												</span>
											</a>
										</div>-->
										<div class="table-responsive clear">
											<table class="table table-hover clear" id="submittalTable">
												<tbody>
													<tr>
														<td width="11%">
															<input class="parent_txts newRowsubmittal" placeholder="Enter submittal name" type="text" id="submittal_name_" name="submittal_name_" tagname="submittal_name" />
														</td>
														<td width="4%"><a href="javascript:void(0);" class="removesubmittal vendar_styles"><span class="glyphicon glyphicon-trash" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></span></a></td>
													</tr>                                           
												</tbody>
											</table>
											<input type="hidden" class="parent_txts" name="RowCountsubmittal" id="RowCountsubmittal" value="1" />
										</div>
									</div>
								</div>
								
							</div>
							</div>
							<div class="col-lg-12">
								<ul>
									<li class="dropdown save_btn float_r"> <a href="javascript:void(0)" class="ripple continueButton">Continue</a> </li>
								</ul>
							</div>
						</div>
					</div>
				</div>
            <!--- stop ---->
			
			</div>
		</form>
      </div>
    </div>
  </div>
  <div class="col-lg-12 savebtn_area">
      <ul>
          <li class="cancel_btn float_r">

                <a href="<?php echo $this->basePath();?>/ats/rfq/index" data-toggle="tooltip" class="ripple" title="Go Back!">Back</a>
          </li>
      </ul>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="totalpage" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal_vendorwidth" role="document">
        <div class="modal-content">
			<div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h1 class="modal-title" id="myModalLabel">Confirmation</h1>
            </div>
            <div class="modal-body">
                <div class="content_wrapper  padlr0">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="col-lg-12">
                                	<h1 class="vendorrequest_textclr">Request For Quotation - <span class="VoucherNo"></span></span></h1>
                                </div>
                                <div class="col-lg-12 clear">
                                    <div class="col-lg-4 col-lg-offset-8 col-md-4 col-md-offset-8 col-sm-4 col-sm-offset-8 col-xm-offset-8 col-xm-4">
                                    	<p style="text-align:center; color:#00aeef; font-style:italic;"><i class="fa fa-calendar"></i>&nbsp;Date : <input type="text" name="rfqc_date" id="rfqc_date" value="<?php echo date('d-m-Y');?>" readonly /></p>
                                    </div>
                                </div>
                                <div class="col-lg-12 clear">
                                    <div class="col-lg-10 col-lg-offset-2 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                                        <div class="row">
                                            <div class=" col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p">Quotation Type<span class="colon_r">:</span></p></div>
                                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p autocomplete-qtnType"></p></div> 
                                        </div>
                                        <?php
                                        if($quotType == 'Q'){?>
                                        <div class="row">
                                            <div class=" col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p">Selected Project<span class="colon_r">:</span></p></div>
                                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p projectList"></p></div> 
                                        </div>
                                        <?php } else{?>
                                            <div class="row">
                                                <div class=" col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p">Selected Enquiry<span class="colon_r">:</span></p></div>
                                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p projectList"></p></div>
                                            </div>
                                        <?php } ?>
                                        <div class="row">
                                            <div class=" col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p">Bit Due Date<span class="colon_r">:</span></p></div>
                                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p biddue_date"></p></div> 
                                        </div>
                                        <div class="row">
                                            <div class=" col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p">Need technical verification<span class="colon_r">:</span></p></div>
                                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p verify_yes"></p></div>  
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-12 clear" id="techVerifyMod1" >
                                	<h1 class="vendorrequest_textclr commargin_bottom">Required Documents name </h1>
                                    <div class="col-lg-10 col-lg-offset-1 clear">
                                        <div class="table-responsive clear">
                                            <table class="table request_poptable table-hover clear" id="table">
                                                <thead>
                                                    <tr>
                                                        <th>Document Name</th>
                                                        <th>Description about the document</th>
                                                        <th>File format</th>
                                                    </tr>
                                                </thead>
                                                <tbody id="document_tbody">
                                                    
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>								
                                <div class="col-lg-12 clear " id="techVerifyMod2" >
                                	<h1 class="vendorrequest_textclr commargin_bottom">Detailed Description</h1>
                                    <div class="col-lg-10 col-lg-offset-1 clear">
                                        <div class="row">
                                            <div class=" col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p">Entered detail description or information about this bid<span class="colon_r">:</span></p></div>
                                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p detailed_description"></p></div> 
                                        </div>
                                        <div class="row">
                                            <div class=" col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p">Send Bid Detail after Verification<span class="colon_r">:</span></p></div>
                                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p web_finalization"></p></div>  
                                        </div>
                                    </div>
                                </div>
                                <!---- decison- start----->
                                <?php
                                if($quotType == 'Q'){?>
                                <div class="col-lg-12 clear">
                                	<h1 class="vendorrequest_textclr">List of all selected request/decisions</h1>
									<div class="col-lg-10 col-lg-offset-1 clear">
										<ul>
											<li class="col-lg-3 commargin_bottom float_r">
												<p style="background:#c2ecfd;text-align:center;">Selected<span class="vendortoc-number float_r decision_list">0</span></p>
											</li>
										</ul>
									</div>
                                    <div class="col-lg-10 col-lg-offset-1  table-responsive clear">
                                        <table class="table request_poptable table-hover clear" id="table">
                                            <thead>
                                                <tr>
                                                    <th>Selected Request/Decision No.</th>
                                                    <th>Selected Request/Decision Date</th>
                                                    <th>Description</th>
                                                    <th>Quantity</th>
                                                </tr>
                                            </thead>
                                            <tbody id="decision_body">
                                              
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <!--- end of decision -->
                                <?php }else{
                                 ?>
                                <!---- request start ---->
                                    <div class="col-lg-12 clear">
                                        <h1 class="vendorrequest_textclr">List of all selected Requests</h1>
                                        <div class="col-lg-10 col-lg-offset-1 clear">
                                            <ul>
                                                <li class="col-lg-3 commargin_bottom float_r">
                                                    <p style="background:#c2ecfd;text-align:center;">Selected Request No.<span class="vendortoc-number float_r request_list">0</span></p>
                                                </li>
                                            </ul>
                                        </div>
                                        <div class="col-lg-10 col-lg-offset-1  table-responsive clear">
                                            <table class="table request_poptable table-hover clear" id="table">
                                                <thead>
                                                <tr>
                                                    <th>Selected Request no.</th>
                                                    <th>Selected Request date</th>
                                                </tr>
                                                </thead>
                                                <tbody id="request_body">

                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                <?php } ?>
                                <!-- end of request ------>
                                <?php
                                if($quotType == 'Q'){?>
                                <div class="col-lg-12 clear">
                                	<h1 class="vendorrequest_textclr commargin_bottom">Resources from the selected Request/Decisions</h1>
                                    <div class="col-lg-10 col-lg-offset-1 clear">
                                        <div class="table request_poptable table-hover clear" id="decquantityTable">
                                            
                                        </div>
                                    </div>
                                </div>
                                <?php }else{ ?>
                                    <div class="col-lg-12 clear">
                                        <h1 class="vendorrequest_textclr commargin_bottom">Resources from the selected Requests</h1>
                                        <div class="col-lg-10 col-lg-offset-1 clear">
                                            <div class="table request_poptable table-hover clear" id="reqquantityTable">

                                            </div>
                                        </div>
                                    </div>
                                <?php } ?>
								<div class="col-lg-12 clear">
                                	<div class="col-lg-6" id="contactinfo">
                                        <h1 class="vendorrequest_textclr commargin_bottom">Contact Information</h1>
                                    </div> 
                                    <div class="col-lg-6" id="deliveryloc">
                                        <h1 class="vendorrequest_textclr commargin_bottom">Delivery Location</h1>
                                    </div>
								</div>
								<div class="col-lg-10 col-lg-offset-1 clear">         
                                    <div class="col-lg-6" id="contact1">
                                         <div class="col-lg-10">
                                            <div class="row">
                                            <div class=" col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p">Contact Name<span class="colon_r">:</span></p></div>
                                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p contact_name"></p></div>
                                            </div>
                                            <div class="row">
                                            <div class=" col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                                <p class="space_p">Contact Number<span class="colon_r">:</span></p>
                                            </div>
                                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p contact_number"></p></div>
                                            </div>
                                            <div class="row">
                                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p">Designation<span class="colon_r">:</span></p></div>
                                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p contact_designation"></p></div>
                                            </div>
                                         </div>    
                                    </div>  
                                    <div class="col-lg-6" id="delivery1">
                                          <div class="col-lg-10">
                                            <div class="row">
                                            <div class=" col-lg-3 col-md-6 col-sm-6 col-xs-6"><p class="space_p">Address<span class="colon_r">:</span></p></div>
                                            <div class="col-lg-9 col-md-6 col-sm-6 col-xs-6"><p class="space_p delivery_addressList"></p></div>
                                            </div>                                           
                                         </div>      	      		
                                    </div>
								</div>
								<div class="col-lg-12 clear" id="bidInfo">
									<div class="col-lg-12 clear">
										<h1 class="vendorrequest_textclr commargin_bottom">Bid Information</h1>
									</div>  
									<div class="col-lg-10 col-lg-offset-1 commargin_top commargin_bottom">    
										<div class="col-lg-12">
											<div class="commargin_top">
												<div class="  col-lg-4 col-md-4 col-sm-4 col-xs-4"><p class="space_p">Bid Information<span class="colon_r">:</span></p></div>
												<div class="col-lg-7 col-md-7 col-sm-7 col-xs-7"><p class="space_p bid_description"></p></div> 
											</div> 
										</div>   
									</div>
								</div>
								<div class="col-lg-12 clear">
                                    <div class="col-lg-12">
										<h1 class="vendorrequest_textclr commargin_bottom">Selected vendors</h1>
                                    </div> 
								</div>
                                <div class="col-lg-10 col-lg-offset-1">
                                    <div class="table-responsive clear">
										<div class="col-lg-12 col-md-6">
                                            <table class="table request_poptable table-hover clear" id="table">
                                                <thead>
                                                    <tr>
                                                        <th>Selected Vendor Name</th>
                                                    </tr>
                                                </thead>
                                                <tbody id="vendor_tbody">
                                                    
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
								<div class="col-lg-12 clear">
									<div class="col-lg-12" id="tremscondition">
										<h1 class="vendorrequest_textclr commargin_bottom">Terms & Conditions</h1>
									</div>
								</div>
								<div class="col-lg-10 col-lg-offset-1">
                                    <div class="table-responsive clear">
                                        <div class="col-lg-12 col-md-6" id="selterm">
                                            <table class="table request_poptable table-hover clear" id="table">
                                                <thead>
                                                    <tr>
                                                        <th class="blubg">Sl.No</th>
														<th class="blubg">Terms</th>
														<th class="blubg">Percentage</th>
														<th class="blubg">Value</th>
														<th class="blubg">Period</th>
														<th class="blubg">Date</th>
														<th class="blubg">Description</th>
                                                    </tr>
                                                </thead>
                                                <tbody id="term_tbody">
                                                   
                                                </tbody>
                                            </table>
                                        </div>                                       
                                        <div class="col-lg-12 col-md-12 padlr0 vendor_request_areabackground">
                                            <div class="commargin_top">
                                                <div class=" col-lg-4 col-md-4 col-sm-4 col-xs-4"><p class="space_p">Need Submittals<span class="colon_r">:</span></p></div>
                                                <div class="col-lg-7 col-md-7 col-sm-7 col-xs-7"><p class="space_p submittal_yes">Yes &nbsp;<span class="request_yescheck"><i class="fa fa-check"></i></span></p></div> 
                                            </div>
                                            <div class="commargin_top" id="submittalDet">
                                                <div class=" col-lg-4 col-md-4 col-sm-4 col-xs-4"><p class="space_p">Entered submittal name<span class="colon_r">:</span></p></div>
                                                <div class="col-lg-7 col-md-7 col-sm-7 col-xs-7"><p class="space_p submittal_value"></p></div>
                                            </div>
                                            <div class="commargin_top" id="narraTion">
                                                <div class="  col-lg-4 col-md-4 col-sm-4 col-xs-4"><p class="space_p">Narration about the quotation<span class="colon_r">:</span></p></div>
                                                <div class="col-lg-7 col-md-7 col-sm-7 col-xs-7"><p class="space_p narration_submittal"></p></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>                              
                            </div>
                        </div>
                    </div>
                </div>	
            <!--table header script end-->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" style="color:#06C;">Edit</button>
        		<button type="button" class="btn btn-primary" id="submitButton">Submit changes</button>
            </div>
        </div>
    </div>
</div>
<?php
	echo $this->InlineScript()
		->appendFile($this->basePath() . '/library/fileupload/js/demo-preview.min.js')
		->appendFile($this->basePath() . '/library/fileupload/js/dmuploader.min.js')
		->appendFile($this->basePath() . '/js/select2.full.min.js')
?>
<script id="terms-template"  type="text/template" class="hide">
    <tr class="dont-hide">
        <td width="10%">
            <input class="parent_text border-none" type="text" name="slno__" id="slno__" />
        </td>
        <td width="26%">
            <input class="parent_text resourceSuggest" type="text" name="terms__" id="terms__"  onfocus="checkTermsUsed(this);" />
            <input type="hidden" name="termsid__" id="termsid__"/>
            <input type="hidden"  name="isper__" id="isper__"/>
            <input type="hidden"  name="isvalue__" id="isvalue__"/>
            <input type="hidden"  name="isperiod__" id="isperiod__"/>
            <input type="hidden"  name="istdate__" id="istdate__"/>
            <input type="hidden"  name="iststring__" id="iststring__"/>
            <input type="hidden"  name="includegross__" id="includegross__"/>
        </td>
        <td width="10%">
            <input class="parent_text border-none" type="text" name="per__" id="per__" style="text-align:right;" onkeypress="return isDecimal(event,this)" onblur="return FormatNum(this, 2, true)" onchange="TermsCalculation(this.id);"/>
        </td>
        <td width="15%"><input class="parent_text border-none" type="text" name="value__" style="text-align:right;" id="value__" onkeypress="return isDecimal(event,this)" onblur="return FormatNum(this, 2, true)" onchange="TermsCalculation(this.id);"/></td>
        <td width="10%"><input class="parent_text border-none" type="text" name="period__" style="text-align:right;" onkeypress="return isDecimal(event,this)" onblur="return FormatNum(this, 1, true)" id="period__"/></td>
        <td width="14%">
            <div class="col-lg-12 padlr0">
                <input type="text" name="date__" id="date__" class="tbl_input date_picker" value="<?php echo date("d/m/Y"); ?>" onkeypress="return isNumberKey(event);" readonly/>
                <span class="date_icon"><i class="fa fa-calendar"></i></span>
            </div>
        </td>
        <td width="15%"><input class="parent_text border-none" type="text" name="string__" id="string__"/></td>
        <td width="15%" align="center" class="action_btns_td">
            <ul class="action_btns">
                <li> <a onclick="deleteRow(this, event);"  id="termsdeleteTr__" style="display:none;"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i> </a> </li>
            </ul>
        </td>
    </tr>
</script>
<script>
	$(function() {
		$("#rfq_date").datepicker();
		$("#rfq_date").on("change",function(){
			var selected = $(this).val();
			$('#rfqc_date').val(selected);
		});
	});
	$('#rfq_date').datepicker({
		format: "dd-mm-yyyy"
	});
    var qutype = <?php echo (isset($quotType)) ? json_encode($quotType) : '';?>;
	var orgVal = '';
	$('#submitButton').click(function(){
		$('#fileList').val(JSON.stringify(fileList));
		$('form').submit();
	});
	function arrequal(arr1, arr2){
		var is_equal = arr1.length==arr2.length && arr1.every(function(v,i) { return ($.inArray(v,arr2) != -1)});
		return is_equal;
	}

	$.fn.materialripple = function(options) {
		var defaults = {
			rippleClass: 'ripple-wrapper'
		};
		$.extend(defaults, options);
		// add Ripple-Wrapper to all Elements
		$(this).append('<span class="'+defaults.rippleClass+'"></span>');
		$(this).addClass('has-ripple').css({'position': 'relative', 'overflow': 'hidden'});

		if($(this).hasClass("slideshow_button") === true) {
			$('.slideshow_button').css({'position': 'absolute'});
		}
		// Let it ripple on click
		$(this).bind('click', function(e){
			$(this).find('.'+defaults.rippleClass).removeClass('animated');
			// get Mouse Position
			var mouseX = e.clientX;
			var mouseY = e.clientY;
			// for each ripple element, set sizes
			elementWidth = $(this).outerWidth();
			elementHeight = $(this).outerHeight();
			d = Math.max(elementWidth, elementHeight);
			$(this).find('.'+defaults.rippleClass).css({'width': d, 'height': d});
			var rippleX = e.clientX - $(this).offset().left - d/2;
			var rippleY = e.clientY - $(this).offset().top - d/2;
			// Position the Ripple Element
			$(this).find('.'+defaults.rippleClass).css('top', rippleY+'px').css('left', rippleX+'px').addClass('animated');
		});
	};

	$('.error_message').hide();
	var oldFormData = [];
    var olddFormData = [];
	var decId = [];
	var oldDecId = [];
	var oldReqId = [];
	var totResId = [];
	var totTransId = [];
    var oldReqId = [];
    var reqId = [];
	var mouseClick = true;
	var quotation_type = ['Material', 'Asset','Activity','IOW','Service'];
	var fileList = [];
	
	function formatNumber(num){
		var firstChar = num.charAt(0);
		if(firstChar == '.')
			return parseFloat("0");
		else
			return parseFloat(num).toFixed(3);
	}
	
	$('#verify_yes').change(function(){
		if($(this).is(':checked'))
			$('#techVerify').show();
		else
			$('#techVerify').hide();
	});
	
   
	$('#autocomplete-qtnType').autocomplete({
		lookup: <?php echo json_encode($quotationType); ?>,
		lookupFilter: function(suggestion, originalQuery, queryLowerCase) {
			if (queryLowerCase == '*') {
                return suggestion.value;
            } else {
                var re = new RegExp($.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
                return re.test(suggestion.value);
            }
		},
		onSelect: function(suggestion){
			request = suggestion.data;
			$("#qtn_type").val(suggestion.data);
			$("#qtnType").val(suggestion.value);
			$("#materialSpan").text(suggestion.value);
		},
		onHint: function (hint) {
			$(this).val(hint);
		},
		onSearchComplete: function (query, suggestion){
		}
	});

	$('.datepickerinput').datepicker({
		format: "dd-mm-yyyy",
		startDate: new Date(),
		todayBtn: true,
		orientation: "top auto",
		autoclose: true
	});
	$('.date_icon').click(function() {
		var input = $(this).parent().find('input').datepicker('show');
	});

    /*project grid*/
    if(qutype == "Q") {
        /*ReqDecisionlist grid start*/
        var resSource =
        {
            localData: [],
            dataType: "json",
            dataFields: [
                {name: 'RDecisionNo', type: 'string'},
             //   {name: 'DecDate', type: 'date', format: 'DD-MM-yyyy'}
                {name: 'DecDate', type: 'string' },
                {name: 'Description', type: 'string' },
                {name: 'Quantity', type: 'string' }
            ],
            id: 'DecisionId'
        };

        var dataAdapterRes = new $.jqx.dataAdapter(resSource, {
            autoBind: true,
            loadComplete: function (data) {

            },
            loadError: function (xhr, status, error) {

            }
        });


        $("#allReqDecisionList").jqxGrid({
            width: '100%',
            pageable: true,
            selectionMode: 'singleRow',
            pagerButtonsCount: 6,
            autoheight: true,
            autorowheight: true,
            filterable: true,
            sortable: true,
            columnsResize: true,
            showfilterrow: true,
            ready: function () {
                var localizationobj = {};
                localizationobj.emptydatastring = "No request decision to display";
                $("#allReqDecisionList").jqxGrid('localizestrings', localizationobj);
            },
            selectionmode: 'checkbox',
            source: dataAdapterRes,
            columns: [
                {text: 'Request/Decision No.', editable: false, datafield: 'RDecisionNo'},
                {text: 'Request/Decision Date', dataField: 'DecDate',width:'25%', editable:false},
                {text: 'Description', dataField: 'Description',width:'25%', editable:false},
                {text: 'Quantity', dataField: 'Quantity',width:'25%', editable:false,align:'center',cellsalign: 'right'}
               // {text: 'DecDate', editable: false, datafield: 'DecDate', filtertype: 'date', cellsformat: 'dd-MM-yyyy'}
            ]
        });

        $('#allReqDecisionList').on('rowselect', function (event) {
            // event arguments.
            var args = event.args;
            // row's bound index.
            var rowBoundIndex = args.rowindex;
            // row's data. The row's data object or null(when all rows are being selected or unselected with a single action). If you have a datafield called "firstName", to access the row's firstName, use var firstName = rowData.firstName;
            var rowData = args.row;

            $('#countdecision').text($('#allReqDecisionList').jqxGrid('selectedrowindexes').length);

        });
        $('#allReqDecisionList').on('rowunselect', function (event) {
            // event arguments.
            var args = event.args;
            // row's bound index.
            var rowBoundIndex = args.rowindex;
            // row's data. The row's data object or null(when all rows are being selected or unselected with a single action). If you have a datafield called "firstName", to access the row's firstName, use var firstName = rowData.firstName;
            var rowData = args.row;
            $('#countdecision').text($('#allReqDecisionList').jqxGrid('selectedrowindexes').length);
        });

        $('#allReqDecisionList').on('rowclick', function (event) {
            var args = event.args;
            // row's bound index.
            var boundIndex = args.rowindex;
            var index = $('#allReqDecisionList').jqxGrid('selectedrowindexes');
            //alert($.inArray(boundIndex, index))
            if ($.inArray(boundIndex, index) == -1)
                $('#allReqDecisionList').jqxGrid('selectrow', boundIndex);
            else
                $('#allReqDecisionList').jqxGrid('unselectrow', boundIndex);
        });
        /*ReqDecisionlist grid end*/
    }else {
        /*ReqRequestlist grid start*/
        var Source =
        {
            localData: [],
            dataType: "json",
            dataFields: [
                {name: 'RequestNo', type: 'string'},
            //    {name: 'RequestDate', type: 'date', format: 'DD-MM-yyyy'}
                {name: 'RequestDate', type: 'string', format: 'DD-MM-yyyy'}
            ],
            id: 'RequestId'
        };

        var dataAdapterReq = new $.jqx.dataAdapter(Source, {
            autoBind: true,
            loadComplete: function (data) {
            },
            loadError: function (xhr, status, error) {
            }
        });

        $("#allReqRequestList").jqxGrid({
            width: '100%',
            pageable: true,
            selectionMode: 'singleRow',
            pagerButtonsCount: 6,
            autoheight: true,
            autorowheight: true,
            filterable: true,
            sortable: true,
            columnsResize: true,
            showfilterrow: true,
            ready: function () {
                var localizationobj = {};
                localizationobj.emptydatastring = "No request to display";
                $("#allReqRequestList").jqxGrid('localizestrings', localizationobj);
            },
            selectionmode: 'checkbox',
            source: dataAdapterReq,
            columns: [
                {text: 'RequestNo', editable: false, datafield: 'RequestNo'},
                {text: 'RequestDate', editable: false, datafield: 'RequestDate'}
//                {
//                    text: 'RequestDate',
//                    editable: false,
//                    datafield: 'RequestDate',
//                    filtertype: 'date',
//                    cellsformat: 'dd-MM-yyyy'
//                }
            ]
        });

        $('#allReqRequestList').on('rowselect', function (event) {
            // event arguments.
            var args = event.args;
            // row's bound index.
            var rowBoundIndex = args.rowindex;
            // row's data. The row's data object or null(when all rows are being selected or unselected with a single action). If you have a datafield called "firstName", to access the row's firstName, use var firstName = rowData.firstName;
            var rowData = args.row;

            $('#countrequest').text($('#allReqRequestList').jqxGrid('selectedrowindexes').length);

        });
        $('#allReqRequestList').on('rowunselect', function (event) {
            // event arguments.
            var args = event.args;
            // row's bound index.
            var rowBoundIndex = args.rowindex;
            // row's data. The row's data object or null(when all rows are being selected or unselected with a single action). If you have a datafield called "firstName", to access the row's firstName, use var firstName = rowData.firstName;
            var rowData = args.row;
            $('#countrequest').text($('#allReqRequestList').jqxGrid('selectedrowindexes').length);
        });

        $('#allReqRequestList').on('rowclick', function (event) {
            var args = event.args;
            // row's bound index.
            var boundIndex = args.rowindex;
            var index = $('#allReqRequestList').jqxGrid('selectedrowindexes');
            //alert($.inArray(boundIndex, index))
            if ($.inArray(boundIndex, index) == -1)
                $('#allReqRequestList').jqxGrid('selectrow', boundIndex);
            else
                $('#allReqRequestList').jqxGrid('unselectrow', boundIndex);
        });
    }
    /*ReqRequestlist grid end*/

	LoadDecisionDet();
	function LoadDecisionDet(){
		bool=true;
		if(bool){
		}
	}
	/* start document submit*/
	removetr();
	function removetr(){
		$('.remove').click(function(){
			if($(this).closest('tr').parent().find('tr').length != 1){
				$(this).closest('tr').remove();
				$('#documentTable tbody tr').each(function(){
					var index=$(this).index() + 1;
					$(this).find('select, input:text').each(function(){
						$(this).attr('name', $(this).attr('tagname')+'_'+index);
						$(this).attr('id', $(this).attr('tagname')+'_'+index);		
					})
					
				});		
			} else {
				$('.delFirst').val('');
			}
		});
	}

	addRow();
	function addRow(){
		$( ".newRow" ).unbind();
		$( ".newRow" ).bind('keyup', function() {
		//alert($(this).closest("tr").index()+"------------"+$("#contactTable tbody tr:last").index())
			if($(this).val().length>0 && $(this).closest("tr").index() == $("#documentTable tbody tr:last").index()){
				$("#documentTable tbody").append("<tr>"+$("#documentTable tbody tr:first").html()+"</tr>");
					$("#documentTable tbody tr").each(function(){
					var index=$(this).index() + 1;
					var lastIndex=$("#documentTable tbody tr:last").index() + 1;
					$(this).find("select, input:text").each(function(){
						if(index==lastIndex){
							if($(this).prop("tagName").toLowerCase() == 'input')
								$(this).val("");
							else
								$(this).val("1");
						}
						$(this).attr("name", $(this).attr("tagname")+'_'+index);
						$(this).attr("id", $(this).attr("tagname")+'_'+index);		
					})
				});	
				removetr();
				addRow();
			}
		});
	}
	
	/* start Submittal Det*/
	removeSubmittaltr();
	function removeSubmittaltr(){
		$('.removesubmittal').click(function(){
			if($(this).closest('tr').parent().find('tr').length != 1){
			// if($(this).closest('tr').index() != 0){
				$(this).closest('tr').remove();
				$('#submittalTable tbody tr').each(function(){
					var index=$(this).index() + 1;
					$(this).find('select, input:text').each(function(){
						$(this).attr('name', $(this).attr('tagname')+'_'+index);
						$(this).attr('id', $(this).attr('tagname')+'_'+index);		
					})
					
				});		
			}
		});
	}

	addsubmittalRow();
	function addsubmittalRow(){
		$( ".newRowsubmittal" ).unbind();
		$( ".newRowsubmittal" ).bind('keyup', function() {
		//alert($(this).closest("tr").index()+"------------"+$("#contactTable tbody tr:last").index())
			if($(this).val().length>0 && $(this).closest("tr").index() == $("#submittalTable tbody tr:last").index()){
				$("#submittalTable tbody").append("<tr>"+$("#submittalTable tbody tr:first").html()+"</tr>");
					$("#submittalTable tbody tr").each(function(){
					var index=$(this).index() + 1;
					var lastIndex=$("#submittalTable tbody tr:last").index() + 1;
					$(this).find("select, input:text").each(function(){
						if(index==lastIndex){
							if($(this).prop("tagName").toLowerCase() == 'input')
								$(this).val("");
							else
								$(this).val("1");
						}
						$(this).attr("name", $(this).attr("tagname")+'_'+index);
						$(this).attr("id", $(this).attr("tagname")+'_'+index);		
					})
				});	
				removeSubmittaltr();
				addsubmittalRow();
			}
		});
	}

    function decisionEntry(){
		var resId = [];
		var transId = [];
        var rtype = $('#autocomplete-qtnType').val();

		$.ajax({
			url:getBaseURL()+"ats/rfq/new-rfq",
			type:"post",
			data:'mode=decisionEntry&decId='+decId+'&rtype='+rtype,
			dataType:"json",
			success:function(data, textStatus, jqXHR){
				oTable.fnClearTable();
				$("#cloneTable").html($("#sequentialViewSub").html());
				$("#sequentialViewSub tbody:first").html("");
				$('.appendResource').html('');
				var json=[];
				$('#totalResourse').text(data.length);
				$.each(data, function(i,v){

                    if(rtype == 'Material' || rtype == 'Asset')
                    {
                        var resObj={};
                        resId.push(v.ResourceId);
                        resObj.resourceId = v.ResourceId;
                        resObj.itemId = v.ItemId;
                        resObj.decTrans = [];
                        var ai = oTable.fnAddData([v.Code+"<input type='hidden' name='resourceCode_"+v.ResourceId+"_"+ v.ItemId +"' id='resourceCode_"+v.ResourceId+"_"+ v.ItemId +"' value='"+v.Code+"'>",
                            v.ResourceName+"<input type='hidden' name='resourceName_"+v.ResourceId+"_"+ v.ItemId +"' id='resourceName_"+v.ResourceId+"_"+ v.ItemId +"' value='"+v.ResourceName+"'>",
                            v.UnitName+"<input type='hidden' name='unitName_"+v.ResourceId+"_"+ v.ItemId +"' id='unitName_"+v.ResourceId+"_"+ v.ItemId +"' value='"+v.UnitName+"'><input type='hidden' name='unitId_"+v.ResourceId+"_"+ v.ItemId +"' id='unitId_"+v.ResourceId+"_"+ v.ItemId +"' value='"+v.UnitId+" '>",
                            "<input type='text' style='text-align:right;' class='tbl_input totQuantity' value="+ sanitizeNumber(v.Quantity,3,true) +" disabled name='bquantity_"+v.ResourceId+"_"+ v.ItemId +"' id='bquantity_"+v.ResourceId+"_"+ v.ItemId +"'>",
                            "<input type='text' style='text-align:right;' class='tbl_input totQuantity' value='0' readonly name='quantity_"+v.ResourceId+"_"+ v.ItemId +"' id='quantity_"+v.ResourceId+"_"+ v.ItemId +"'>"
                        ]);

                        var n = oTable.fnSettings().aoData[ai[0]].nTr;
                        n.setAttribute('id', v.ResourceId + "_" + v.ItemId);
                        n.setAttribute('class', 'mainTr deleteTr_'+v.ResourceId + '_' + v.ItemId);
                        $('.appendResource').append('<tr>'+
                        '<td>'+v.Code+'<input type="hidden" name="resourceCode_'+v.ResourceId+'_'+ v.ItemId+'" id="resourceCode_'+v.ResourceId+'_'+ v.ItemId+'" value="'+v.Code+'"></td>'+
                        '<td>'+v.ResourceName+'<input type="hidden" name="resourceName_'+v.ResourceId+'_'+ v.ItemId+'" id="resourceName_'+v.ResourceId+'_'+ v.ItemId+'" value="'+v.UnitId+'"></td>'+
                        '<td>'+v.UnitName+'<input type="hidden" name="unitName_'+v.ResourceId+'_'+ v.ItemId+'" id="unitName_'+v.ResourceId+'_'+ v.ItemId+'" value="'+v.UnitName+'"></td>'+
                        '<td align="right">'+sanitizeNumber(v.Quantity,3,true)+'</td>'+
                        '<td align="right"><input type="text" style="border:none;text-align:right;" class="tbl_input totQuantity" value="0" readonly name="quantity_'+v.ResourceId+'_'+ v.ItemId+'" id="quantity_'+v.ResourceId+'_'+ v.ItemId+'"></td>'+
                        '</tr>');

                        $("#sequentialViewSub tbody:first").append('<tr class="subTr_' + v.ResourceId + '_'+ v.ItemId +' deleteTr_' + v.ResourceId + '_'+ v.ItemId+'">' +
                        '<td colspan=5>' +
                        '<div class="subDiv">' +
                        '<table class="table table-bordered">' +
                        '<thead>' +
                        '<tr>' +
                        '<th>Decision No</th>' +
                        '<th>Balance Qty</th>' +
                        '<th>Qty</th>' +
                        '</tr>' +
                        '</thead>' +
                        '<tbody>');

                        $.each(v.decision, function(deci,decv){ console.log(decv);
                            transId.push(decv.TransId);
                            if($.inArray(decv.TransId, totTransId) == -1 || $.inArray(v.ResourceId, totResId) == -1){

                                    $("#sequentialViewSub .subTr_" + v.ResourceId + "_"+ v.ItemId+" tbody:first").append('<tr style="background-color:#f0f2f2;" id="requestTr_' + decv.TransId + '">' +
                                    '<td width="50%">' + decv.RDecisionNo + '<input type="hidden" name="decisionId_' + decv.TransId + '" id="decisionId_' + decv.TransId + '" value="' + decv.DecisionId + '"></td>' +
                                    '<td align="right" width="25%">' + sanitizeNumber(decv.IndentQty,3,true) + '</td>' +
                                    '<td align="right" class="tbl_input_td" width="25%"><input type="text" style="text-align:right;" elename="quantity_' + v.ResourceId + '_'+ v.ItemId+'" class="tbl_input quantityVal"  onblur="return FormatNum(this, 3, true)" name="decQuantity_' + decv.TransId + '" value="' + sanitizeNumber(decv.IndentQty,3,true) + '" data-toggle="tooltip" data-title="zsdfzdf" data-placement="top" data-trigger=""></td>' +
                                    '</tr>');

                                    var val = parseFloat(oTable.$("tr.mainTr").find("input[name=quantity_" + v.ResourceId + "_" + v.ItemId +"]").val()) + sanitizeNumber(parseFloat(formatNumber(decv.IndentQty)),3,true);
                                    oTable.$("tr.mainTr").find("input[name=quantity_" + v.ResourceId + "_"+ v.ItemId + "]").val(sanitizeNumber(val,3,true));
                                    $("input[name=quantity_" + v.ResourceId + "_" + v.ItemId + "]").val(sanitizeNumber(val,3,true));

                            }
                            else {
                                    $("#sequentialViewSub .subTr_" + v.ResourceId + "_"+ v.ItemId+" tbody:first").append($("#cloneTable #requestTr_" + decv.TransId).clone());
                                    var val = parseFloat(oTable.$("tr.mainTr").find("input[name=quantity_" + v.ResourceId + "_" + v.ItemId +"]").val()) + parseFloat($("#cloneTable #requestTr_" + decv.TransId + " .quantityVal").val());
                                    oTable.$("tr.mainTr").find("input[name=quantity_" + v.ResourceId + "_" + v.ItemId +"]").val(sanitizeNumber(val,3,true));
                                    $("input[name=quantity_" + v.ResourceId + "_" + v.ItemId + "]").val(sanitizeNumber(val,3,true));

                            }
                            resObj.decTrans.push(decv.TransId);
                        });
                        $("#sequentialViewSub .subTr_"+v.ResourceId+ "_"+ v.ItemId+" tbody:first").append('</tbody>'+
                        '</table>'+
                        '</div>'+
                        '</td>'+
                        '</tr>');
                        json.push(resObj);
                    }
                    else if(rtype == 'Activity' || rtype == 'IOW' || rtype == 'Service') {
                        var resObj={};
                        resId.push(v.ResourceId);
                        resObj.resourceId = v.ResourceId;
                        resObj.decTrans = [];
                        var ai = oTable.fnAddData([v.Code+"<input type='hidden' name='resourceCode_"+v.ResourceId+"' id='resourceCode_"+v.ResourceId+"' value='"+v.Code+"'>",
                            v.ResourceName+"<input type='hidden' name='resourceName_"+v.ResourceId+"' id='resourceName_"+v.ResourceId+"' value='"+v.ResourceName+"'>",
                            v.UnitName+"<input type='hidden' name='unitName_"+v.ResourceId+"' id='unitName_"+v.ResourceId+"' value='"+v.UnitName+"'><input type='hidden' name='unitId_"+v.ResourceId+"' id='unitId_"+v.ResourceId+"' value='"+v.UnitId+" '>",
                            "<input type='text' style='text-align:right;' class='tbl_input totQuantity' value="+ sanitizeNumber(v.Quantity,3,true) +" disabled name='bquantity_"+v.ResourceId+"' id='bquantity_"+v.ResourceId+"'>",
                            "<input type='text' style='text-align:right;' class='tbl_input totQuantity' value='0' disabled name='quantity_"+v.ResourceId+"' id='quantity_"+v.ResourceId+"'>"
                        ]);

                        var n = oTable.fnSettings().aoData[ai[0]].nTr;
                        n.setAttribute('id', v.ResourceId);
                        n.setAttribute('class', 'mainTr deleteTr_'+v.ResourceId);
                        $('.appendResource').append('<tr>'+
                        '<td>'+v.Code+'<input type="hidden" name="resourceCode_'+v.ResourceId+'" id="resourceCode_'+v.ResourceId+'" value="'+v.Code+'"></td>'+
                        '<td>'+v.ResourceName+'<input type="hidden" name="resourceName_'+v.ResourceId+'" id="resourceName_'+v.ResourceId+'" value="'+v.UnitId+'"></td>'+
                        '<td>'+v.UnitName+'<input type="hidden" name="unitName_'+v.ResourceId+'" id="unitName_'+v.ResourceId+'" value="'+v.UnitName+'"></td>'+
                        '<td align="right">'+sanitizeNumber(v.Quantity,3,true)+'</td>'+
                        '<td align="right"><input type="text" style="border:none;text-align:right;" class="tbl_input totQuantity" value="0" disabled name="quantity_'+v.ResourceId+'" id="quantity_'+v.ResourceId+'"></td>'+
                        '</tr>');

                        $("#sequentialViewSub tbody:first").append('<tr class="subTr_' + v.ResourceId + ' deleteTr_' + v.ResourceId + '">' +
                        '<td colspan=5>' +
                        '<div class="subDiv">' +
                        '<table class="table table-bordered">' +
                        '<thead>' +
                        '<tr>' +
                        '<th>Request No</th>' +
                        '<th>Balance Qty</th>' +
                        '<th>Qty</th>' +
                        '</tr>' +
                        '</thead>' +
                        '<tbody>');

                        $.each(v.decision, function(deci,decv){ console.log(decv);
                            transId.push(decv.TransId);
                            if($.inArray(decv.TransId, totTransId) == -1 || $.inArray(v.ResourceId, totResId) == -1){

                                $("#sequentialViewSub .subTr_"+v.ResourceId+" tbody:first").append('<tr style="background-color:#f0f2f2;" id="requestTr_'+decv.TransId+'">'+
                                '<td width="50%">'+decv.RDecisionNo+'<input type="hidden" name="decisionId_'+decv.TransId+'" id="decisionId_'+decv.TransId+'" value="'+decv.DecisionId+'"></td>'+
                                '<td align="right" width="25%">'+sanitizeNumber(decv.IndentQty,3,true)+'</td>'+
                                '<td align="right" class="tbl_input_td" width="25%"><input type="text" style="text-align:right;" readonly elename="quantity_'+v.ResourceId+'" class="tbl_input quantityVal" name="decQuantity_'+decv.TransId+'" value="'+sanitizeNumber(decv.IndentQty,3,true)+'" data-toggle="tooltip" data-title="zsdfzdf" data-placement="top" data-trigger=""></td>'+
                                '</tr>');

                                var val = parseFloat(oTable.$("tr.mainTr").find("input[name=quantity_"+v.ResourceId+"]").val()) + sanitizeNumber(parseFloat(formatNumber(decv.IndentQty)),3,true);
                                oTable.$("tr.mainTr").find("input[name=quantity_"+v.ResourceId+"]").val(val);
                                $("input[name=quantity_"+v.ResourceId+"]").val(sanitizeNumber(val,3,true));
                            }
                            else{
                                $("#sequentialViewSub .subTr_"+v.ResourceId+" tbody:first").append($("#cloneTable #requestTr_"+decv.TransId).clone());
                                var val = parseFloat(oTable.$("tr.mainTr").find("input[name=quantity_"+v.ResourceId+"]").val()) + parseFloat($("#cloneTable #requestTr_"+decv.TransId+" .quantityVal").val());
                                oTable.$("tr.mainTr").find("input[name=quantity_"+v.ResourceId+"]").val(val);
                                $("input[name=quantity_"+v.ResourceId+"]").val(sanitizeNumber(val,3,true));
                            }
                            resObj.decTrans.push(decv.TransId);
                        });
                        $("#sequentialViewSub .subTr_"+v.ResourceId+" tbody:first").append('</tbody>'+
                        '</table>'+
                        '</div>'+
                        '</td>'+
                        '</tr>');
                        json.push(resObj);
                    }


				});
				$('#hidJson').val(JSON.stringify(json));
			},
			complete:function(data){
				oldDecId = decId;
				totResId = resId;
				totTransId = transId;
				trClick();
				oTable.$("tr.mainTr").trigger("click");
				$("#cloneTable").html('');
				$('input[data-toggle="tooltip"]').tooltip();
			},				
			error:function(jqXHR, textStatus, errorThrown){
				alert(textStatus+"-----"+errorThrown);
			}		
	
		});
	}
    function requestEntry(){
        var ressId = [];
        var transsId = [];
        $.ajax({
            url:getBaseURL()+"ats/rfq/new-rfq",
            type:"post",
            data:'mode=requestEntry&reqId='+reqId,
            dataType:"json",
            success:function(data, textStatus, jqXHR){
                oTable.fnClearTable();
                $("#cloneTable").html($("#sequentialViewSub1").html());
                $("#sequentialViewSub1 tbody:first").html("");
                $('.appendResource').html('');
                var json=[];
                $('#totalResourse').text(data.length);
                $.each(data, function(i,v){

                    var resObj={};
                    ressId.push(v.ResourceId);
                    resObj.resourceId = v.ResourceId;
                    resObj.reqTrans = [];
                    var ai = oTable.fnAddData([v.Code+"<input type='hidden' name='resourceCode_"+v.ResourceId+"' id='resourceCode_"+v.ResourceId+"' value='"+v.Code+"'>",
                        v.ResourceName+"<input type='hidden' name='resourceName_"+v.ResourceId+"' id='resourceName_"+v.ResourceId+"' value='"+v.ResourceName+"'>",
                        v.UnitName+"<input type='hidden' name='unitName_"+v.ResourceId+"' id='unitName_"+v.ResourceId+"' value='"+v.UnitName+"'><input type='hidden' name='unitId_"+v.ResourceId+"' id='unitId_"+v.ResourceId+"' value='"+v.UnitId+" '>",
                        sanitizeNumber(v.Quantity,3,true) ,
                        "<input type='text' class='tbl_input totQuantity' value='0' readonly name='quantity_"+v.ResourceId+"' id='quantity_"+v.ResourceId+"'>"
                    ]);

                    var n = oTable.fnSettings().aoData[ai[0]].nTr;
                    n.setAttribute('id', v.ResourceId);
                    n.setAttribute('class', 'mainTr deleteTr_'+v.ResourceId);
                    $('.appendResource').append('<tr>'+
                    '<td>'+v.Code+'<input type="hidden" name="resourceCode_'+v.ResourceId+'" id="resourceCode_'+v.ResourceId+'" value="'+v.Code+'"></td>'+
                    '<td>'+v.ResourceName+'<input type="hidden" name="resourceName_'+v.ResourceId+'" id="resourceName_'+v.ResourceId+'" value="'+v.UnitId+'"></td>'+
                    '<td>'+v.UnitName+'<input type="hidden" name="unitName_'+v.ResourceId+'" id="unitName_'+v.ResourceId+'" value="'+v.UnitName+'"></td>'+
                    '<td align="right">'+sanitizeNumber(v.Quantity,3,true)+'</td>'+
                    '<td ><input type="text" style="border:none;text-align:right;" class="tbl_input totQuantity" value="0" readonly name="quantity_'+v.ResourceId+'" id="quantity_'+v.ResourceId+'"></td>'+
                    '</tr>');

                    $("#sequentialViewSub1 tbody:first").append('<tr class="subTr_'+v.ResourceId+' deleteTr_'+v.ResourceId+'">'+
                    '<td colspan=5>'+
                    '<div class="subDiv">'+
                    '<table class="table table-bordered">'+
                    '<thead>'+
                    '<tr>'+
                    '<th>Request No</th>'+
                    '<th>Balance Qty</th>'+
                    '<th>Qty</th>'+
                    '</tr>'+
                    '</thead>'+
                    '<tbody>');
                    // check this
                    $.each(v.request, function(deci,decv){
                        transsId.push(decv.RequestTransId);
                        if($.inArray(decv.RequestTransId, totTransId) == -1 || $.inArray(v.ResourceId, totResId) == -1){
                            $("#sequentialViewSub1 .subTr_"+v.ResourceId+" tbody:first").append('<tr style="background-color:#f0f2f2;" id="requestTr_'+decv.RequestTransId+'">'+
                            '<td width="50%">'+decv.RequestNo+'<input type="hidden" name="requestId_'+decv.RequestTransId+'" id="requestId_'+decv.RequestTransId+'" value="'+decv.RequestId+'"></td>'+
                            '<td width="25%">'+sanitizeNumber(decv.Quantity,3,true)+'</td>'+
                            '<td class="tbl_input_td" width="25%"><input type="text" elename="quantity_'+v.ResourceId+'" class="tbl_input quantityVal" name="reqQuantity_'+decv.RequestTransId+'" value="'+sanitizeNumber(decv.Quantity,3,true)+'" data-toggle="tooltip" data-title="zsdfzdf" data-placement="top" data-trigger=""></td>'+
                            '</tr>');

                            var val = parseFloat(oTable.$("tr.mainTr").find("input[name=quantity_"+v.ResourceId+"]").val()) + sanitizeNumber(parseFloat(formatNumber(decv.Quantity)),3,true);
                            oTable.$("tr.mainTr").find("input[name=quantity_"+v.ResourceId+"]").val(val);
                            $("input[name=quantity_"+v.ResourceId+"]").val(sanitizeNumber(val,3,true));
                        }
                        else{
                            $("#sequentialViewSub1 .subTr_"+v.ResourceId+" tbody:first").append($("#cloneTable #requestTr_"+decv.RequestTransId).clone());
                            var val = parseFloat(oTable.$("tr.mainTr").find("input[name=quantity_"+v.ResourceId+"]").val()) + parseFloat($("#cloneTable #requestTr_"+decv.RequestTransId+" .quantityVal").val());
                            oTable.$("tr.mainTr").find("input[name=quantity_"+v.ResourceId+"]").val(val);
                            $("input[name=quantity_"+v.ResourceId+"]").val(sanitizeNumber(val,3,true));
                        }
                        resObj.reqTrans.push(decv.RequestTransId);
                    });
                    $("#sequentialViewSub1 .subTr_"+v.ResourceId+" tbody:first").append('</tbody>'+
                    '</table>'+
                    '</div>'+
                    '</td>'+
                    '</tr>');
                    json.push(resObj);
                });
                $('#hidJson').val(JSON.stringify(json));
            },
            complete:function(data){
                oldReqId = reqId;
                totResId = ressId;
                totTransId = transsId;
                trClick();
                oTable.$("tr.mainTr").trigger("click");
                $("#cloneTable").html('');
                $('input[data-toggle="tooltip"]').tooltip();
            },
            error:function(jqXHR, textStatus, errorThrown){
                alert(textStatus+"-----"+errorThrown);
            }

        });
    }
	function decisionPicklist(mode){
        var rtype = $('#autocomplete-qtnType').val();

		var formData = $("#firstStep").find(".nextVal").serializeArray();

		if(JSON.stringify(formData) != JSON.stringify(oldFormData)){
			$("#allReqDecisionList").jqxGrid("showloadelement");
			$('#countdecision').text(0);
			formData.push({name:"mode", value:"decisionPicklist"});
            formData.push({name:"rtype", value:rtype});
			$.ajax({
				url:getBaseURL()+"ats/rfq/new-rfq",
				type:"post",
				data:formData,
				dataType:"json",
				success:function(data, textStatus, jqXHR){
					if(data['data'].length == 0){
						alert("There is no more pending for selected Project,select different Project to Continue.");
					} else {
						if(mode == 0 && !$('#collapse21').is(':visible'))
								$('#collapse21').closest('.panel-default').find('.panel-heading').trigger('click');							
						
						var rowDecId = [];
						var decIndex = $('#allReqDecisionList').jqxGrid('selectedrowindexes'); 
						for(var i in decIndex){
							rowDecId.push($('#allReqDecisionList').jqxGrid('getrowid', decIndex[i]));
						}
						
						resSource.localdata = data;
						dataAdapterRes.dataBind();
						$('#allReqDecisionList').jqxGrid({ source: dataAdapterRes });
						
						var index1 = $('#allReqDecisionList').jqxGrid('selectedrowindexes'); 
						if(index1.length > 0)
							$('#allReqDecisionList').jqxGrid('clearselection');

						for(var id in rowDecId){
							var ind = $('#allReqDecisionList').jqxGrid('getrowboundindexbyid', rowDecId[id]);
							if(ind != -1)
								$('#allReqDecisionList').jqxGrid('selectrow', ind);
						}
					}
				},
				complete:function(data){
					$("#allReqDecisionList").jqxGrid("hideloadelement");
					if(data.responseJSON['data'].length != 0){
						$('#totaldecision').text($('#allReqDecisionList').jqxGrid('getrows').length);
						oldFormData = $("#firstStep").find(".nextVal").serializeArray();
					}
				},				
				error:function(jqXHR, textStatus, errorThrown){
					alert(textStatus+"-----"+errorThrown);
				}		
		
			});	
		}		
	}

    function requestPicklist(mode){
        var formData = $("#firstStep").find(".nextVal").serializeArray();
        if(JSON.stringify(formData) != JSON.stringify(olddFormData)){
            $("#allReqRequestList").jqxGrid("showloadelement");
            $('#countrequest').text(0);
            var qtype = $('#qtnType').val();
            formData.push({name:"mode", value:"requestPicklist"},{name:"qtype",value:qtype});
            $.ajax({
                url:getBaseURL()+"ats/rfq/new-rfq",
                type:"post",
                data:formData,
                dataType:"json",
                success:function(data, textStatus, jqXHR){
                    if(data['data'].length == 0){
                        alert("There is no more request pending for selected Project,select different Project to Continue.");
                    } else {
                        if(mode == 0 && !$('#collapse21').is(':visible'))
                            $('#collapse21').closest('.panel-default').find('.panel-heading').trigger('click');

                        var rowDecId = [];
                        var decIndex = $('#allReqRequestList').jqxGrid('selectedrowindexes');
                        for(var i in decIndex){
                            rowDecId.push($('#allReqRequestList').jqxGrid('getrowid', decIndex[i]));
                        }

                        Source.localdata = data;
                        dataAdapterReq.dataBind();
                        $('#allReqRequestList').jqxGrid({ source: dataAdapterReq });

                        var index1 = $('#allReqRequestList').jqxGrid('selectedrowindexes');
                        if(index1.length > 0)
                            $('#allReqRequestList').jqxGrid('clearselection');

                        for(var id in rowDecId){
                            var ind = $('#allReqRequestList').jqxGrid('getrowboundindexbyid', rowDecId[id]);
                            if(ind != -1)
                                $('#allReqRequestList').jqxGrid('selectrow', ind);
                        }
                    }
                },
                complete:function(data){
                    $("#allReqRequestList").jqxGrid("hideloadelement");
                    if(data.responseJSON['data'].length != 0){
                        $('#totalrequest').text($('#allReqRequestList').jqxGrid('getrows').length);
                        olddFormData = $("#firstStep").find(".nextVal").serializeArray();
                    }
                },
                error:function(jqXHR, textStatus, errorThrown){
                    alert(textStatus+"-----"+errorThrown);
                }

            });
        }
    }

	$(".panel-collapse").on("shown.bs.collapse", function(e){
		$('.panel-heading').removeClass('accordion_head_crnt');
		$(this).prev('div').addClass('accordion_head_crnt');

	});
	$(".panel-collapse").on("show.bs.collapse", function(e){
		if(mouseClick){
			$(".error_message").hide();
			var bool = true;
			if($(this).attr('id') != 'collapse20'){
				if($('.panel-collapse:visible').closest('.panel-default').index() < $(this).closest('.panel-default').index() && $('#collapse20').index() < $(this).closest('.panel-default').index()){
					if($.inArray($('#autocomplete-qtnType').val(), quotation_type) == -1){
						$("#autocomplete-qtnType").closest(".req_flds").find(".error_message").show();
						bool = false;
						$('#autocomplete-qtnType').focus();
						
						if(!$('#collapse20').is(':visible'))
							$('#collapse20').closest('.panel-default').find('.panel-heading').trigger('click');
						
						return false;
					}
					else if($("#VoucherNo").val() == ''){
						$("#VoucherNo").closest(".req_flds").find(".error_message").text("Enter voucher no...").show();
						$("#VoucherNo").focus();
						if(!$('#collapse20').is(':visible'))
							$('#collapse20').closest('.panel-default').find('.panel-heading').trigger('click');
							
						return false;
					}
					else if($('#project_name option:selected').length == 0){
						$("#project_name").closest(".req_flds").find(".error_message").show();
						bool = false;
						$('#token-input-project_name').focus();
						
						if(!$('#collapse20').is(':visible'))
							$('#collapse20').closest('.panel-default').find('.panel-heading').trigger('click');
						
						return false;
					}
					else if($('#biddue_date').val().length == 0){
						$("#biddue_date").closest(".req_flds").find(".error_message").show();
						bool = false;
						$('#biddue_date').focus();
						
						if(!$('#collapse20').is(':visible'))
							$('#collapse20').closest('.panel-default').find('.panel-heading').trigger('click');
						
						return false;
					}
					else if($("#VoucherNo").val() != '' && !<?php echo $genType; ?>){
						$.ajax({
							url:getBaseURL()+"ats/rfq/new-rfq",
							type:"post",
							data:"voucherno="+$('#VoucherNo').val()+"&mode=voucherValid",
							dataType:"json",
							success:function(data, textStatus, jqXHR){
								if(data['data'].length != 0){
									$("#VoucherNo").closest(".req_flds").find(".error_message").text("The voucher no already used").show();
									$("#VoucherNo").focus();
								}
								else{
									var formData = $("#firstStep").find(".nextVal").serializeArray();
									if(JSON.stringify(formData) != JSON.stringify(oldFormData)){
										decisionPicklist(0);
										return false;
									}else{
                                        if(JSON.stringify(formData) != JSON.stringify(olddFormData)){
                                            requestPicklist(0);
                                            return false;
                                        }
                                    }
								}
							},
							error:function(jqXHR, textStatus, errorThrown){
								alert(textStatus+"-----"+errorThrown);
							}
						});				
					}						
					else{
						var formData = $("#firstStep").find(".nextVal").serializeArray();
						if(JSON.stringify(formData) != JSON.stringify(oldFormData)){
							decisionPicklist(0);
							return false;
						}else{
                            if(JSON.stringify(formData) != JSON.stringify(olddFormData)){
                                requestPicklist(0);
                                return false;
                            }
                        }
					}
				}
			}
			if($(this).attr('id') != 'collapse33'){
				if($('.panel-collapse:visible').closest('.panel-default').index() < $(this).closest('.panel-default').index() && $('#collapse33').index() < $(this).closest('.panel-default').index() && $('#collapse33').is(':visible')){
					if($('#detailed_description').val().trim().length == 0){
						if(!$('#collapse33').is(':visible'))
							$('#collapse33').closest('.panel-default').find('.panel-heading').trigger('click');
						
						$('#detailed_description').focus();
						$('#detailed_description').closest(".req_flds").find(".error_message").show();
						return false;						
					}					
				}
			}			
			if($(this).attr('id') != 'collapse21'){
				//if($('.panel-collapse:visible').closest('.panel-default').index() < $(this).closest('.panel-default').index() && $('#collapse21').index() < $(this).closest('.panel-default').index()){
                if($('.panel-collapse:visible').closest('.panel-default').index() < $(this).closest('.panel-default').index() && $('#collapse21').index() < $(this).closest('.panel-default').index() && $('#collapse21').is(':visible')){
                    var qType = $('#qtype').val();

                    if(qType == 'Q'){
                        //decison
                        var index = $('#allReqDecisionList').jqxGrid('getselectedrowindex');

                        if(index==-1){
                            if(!$('#collapse21').is(':visible'))
                                $('#collapse21').closest('.panel-default').find('.panel-heading').trigger('click');

                            alert('Atleast select one decision to proceed further');
                            return false;
                        }
                        else{
                            decId=[];
                            var index = $("#allReqDecisionList").jqxGrid("getselectedrowindexes");
                            $('#resourceList').text(index.length);
                            for(var i in index){
                                decId.push($("#allReqDecisionList").jqxGrid("getrowid", index[i]));
                            }
                            $("#decisionId").val(decId);
                            if(!arrequal(oldDecId, decId)){
                                decisionEntry();
                            }
                        }
                    }else{
                        //request
                        var index = $('#allReqRequestList').jqxGrid('getselectedrowindex');
                        if(index==-1){
                            if(!$('#collapse21').is(':visible'))
                                $('#collapse21').closest('.panel-default').find('.panel-heading').trigger('click');

                            alert('Atleast select one Request to proceed further');
                            return false;
                        }
                        else{
                            reqId=[];
                            var index = $("#allReqRequestList").jqxGrid("getselectedrowindexes");
                            $('#resourceList1').text(index.length);
                            for(var i in index){
                                reqId.push($("#allReqRequestList").jqxGrid("getrowid", index[i]));
                            }
                            $("#RequestId").val(reqId);
                            if(!arrequal(oldReqId, reqId)){
                                requestEntry();
                            }
                        }

                    }
				}

			}
			if($(this).attr('id') != 'collapse22'){
				if($('.panel-collapse:visible').closest('.panel-default').index() < $(this).closest('.panel-default').index() && $('#collapse22').index() < $(this).closest('.panel-default').index()){
	
				}						
			}
		}
	});
	$('.panel-heading').click(function(e){
		if(e.which)
			mouseClick = true;
		else
			mouseClick = false;
	});
	function showPanel(){
		$('.error_message').hide();
		if($('#collapse20').is(':visible')){ 
			var bool = true;
			if($.inArray($('#autocomplete-qtnType').val(), quotation_type) == -1){
				$("#autocomplete-qtnType").closest(".req_flds").find(".error_message").show();
				bool = false;
				$('#autocomplete-qtnType').focus();
			}
			else if($("#VoucherNo").val() == ''){
				$("#VoucherNo").closest(".req_flds").find(".error_message").text("Enter voucher no...").show();
				$("#VoucherNo").focus();
			}
			else if($('#project_name option:selected').length == 0){
				$("#project_name").closest(".req_flds").find(".error_message").show();
				bool = false;
				$('#token-input-project_name').focus();
			}
			else if($('#biddue_date').val().length == 0){
				$("#biddue_date").closest(".req_flds").find(".error_message").show();
				bool = false;
				$('#biddue_date').focus();
			}
			else if($("#VoucherNo").val() != '' && !<?php echo $genType; ?>){

                var type1 =
				$.ajax({
					url:getBaseURL()+"ats/rfq/new-rfq",
					type:"post",
					data:"voucherno="+$('#VoucherNo').val()+"&mode=voucherValid",
					dataType:"json",
					success:function(data, textStatus, jqXHR){
						if(data['data'].length != 0){
							$("#VoucherNo").closest(".req_flds").find(".error_message").text("The voucher no already used").show();
							$("#VoucherNo").focus();
						}
						else{
							//$('.panel-collapse:visible').closest('.panel-default').nextAll('.panel-default:visible:first').find('.panel-heading').trigger('click');
							if(qutype == 'Q'){
                                decisionPicklist(1);
                            }
                            else{
                                requestPicklist(1);
                            }

						}
					},
					error:function(jqXHR, textStatus, errorThrown){
						alert(textStatus+"-----"+errorThrown);
					}
				});				
			}			
			else{
				$('.panel-collapse:visible').closest('.panel-default').nextAll('.panel-default:visible:first').find('.panel-heading').trigger('click');
				if($('#collapse33').is(':hidden')){
					if(qutype == 'Q'){

						decisionPicklist(1);
					}
					else{
						requestPicklist(1);
					}
				}
			}
		}
		else if($('#collapse33').is(':visible')){
			var bool = true;

			if($('#detailed_description').val().trim().length == 0){
				bool = false;
				$('#detailed_description').focus();
				$('#detailed_description').closest(".req_flds").find(".error_message").show();				
			}
			if(bool){

                $('.panel-collapse:visible').closest('.panel-default').next('.panel-default').find('.panel-heading').trigger('click');
                if(qutype == 'Q'){
				    decisionPicklist(1);
                }
                else{
                    requestPicklist(1);
                }
			}
		}
		else if($('#collapse21').is(':visible')){
            var qType = $('#qtype').val();
            if(qType == 'Q'){
                //decison
                var index = $('#allReqDecisionList').jqxGrid('getselectedrowindex');
                if(index==-1){
                    alert('Atleast select one decision to proceed further')
                }
                else{
                    $('.panel-collapse:visible').closest('.panel-default').nextAll('.panel-default:visible').find('.panel-heading').trigger('click');
                    decId=[];
                    var index = $("#allReqDecisionList").jqxGrid("getselectedrowindexes");
                    $('#resourceList').text(index.length);
                    for(var i in index){
                        decId.push($("#allReqDecisionList").jqxGrid("getrowid", index[i]));
                    }
                    $("#decisionId").val(decId);
                    if(!arrequal(oldDecId, decId)){
                        decisionEntry();
                    }
                }
            }
            else{
                var index = $('#allReqRequestList').jqxGrid('getselectedrowindex');
                if(index==-1){
                    alert('Atleast select one request to proceed further')
                }
                else{
                    $('.panel-collapse:visible').closest('.panel-default').nextAll('.panel-default:visible').find('.panel-heading').trigger('click');
                    reqId=[];
                    var index = $("#allReqRequestList").jqxGrid("getselectedrowindexes");
                    $('#resourceList1').text(index.length);
                    for(var i in index){
                        reqId.push($("#allReqRequestList").jqxGrid("getrowid", index[i]));
                    }
                    $("#requestId").val(reqId);
                    if(!arrequal(oldReqId, reqId)){
                        requestEntry();
                    }
                }
            }
		}
		else if($('#collapse22').is(':visible')){
			$('.panel-collapse:visible').closest('.panel-default').nextAll('.panel-default:visible').find('.panel-heading').trigger('click');				
		}		
		else if($('#collapse26').is(':visible')){
			$('.panel-collapse:visible').closest('.panel-default').nextAll('.panel-default:visible').find('.panel-heading').trigger('click');		
			var bid = $("#bid_description").val();
			if(bid==''||bid==null){
				$("#bidInfo").hide();
			}else{
				$("#bidInfo").show();
			}	
			var name = $('#contact_name').val();
			var number = $('#contact_number').val();
			var designation = $('#contact_designation').val();
			if(name!='' || number!='' || designation!='' ){
				$('#contact1').show();
				$('#delivery1').show();
				$('#contactinfo').show();
				$('#deliveryloc').show();
			}else{
				$('#contact1').hide();
				$('#delivery1').hide();
				$('#contactinfo').hide();
				$('#deliveryloc').hide();
			}
 		}
		else if($('#collapse28').is(':visible')) {
			$('.panel-collapse:visible').closest('.panel-default').nextAll('.panel-default:visible').find('.panel-heading').trigger('click');		
		}
		else if($('#collapse27').is(':visible')) {
            var rowCountdoc = $('#documentTable tbody tr').length;
            $('#RowCountdoc').val(rowCountdoc);

            var rowCountsubmittal = $('#submittalTable tbody tr').length;
            $('#RowCountsubmittal').val(rowCountsubmittal);

            var vendorsListId = [];
            var index = $("#allVendorList").jqxGrid("getselectedrowindexes");
			//console.log(index);
            if (index == '') {
                alert("Kindly select the Vendor");
                return false;
            } else {
                for (var i in index) {
                    vendorsListId.push($("#allVendorList").jqxGrid("getrowid", index[i]));
                }
                $("#vendorListId").val(vendorsListId);
            }
			
				if(tCount == 1){
				   alert('Add Resource');
				   return false;
				}
			var tCount =  $('#submittalTable tbody tr').length;
			var $type = $('input[type=checkbox][name=submittal_yes]:checked');
			if($type.length==1){ 
				if(tCount == 1){
				   alert('Enter Submittal Name');
				   return false;
				}
			}
			// var termsListId=[];
			// var index1 = $("#allTermList").jqxGrid("getselectedrowindexes");
			// if(index1==''){
				// $("#selterm").hide();
				// $("#tremscondition").hide();
			// }else{
				// $("#selterm").show();
				// $("#tremscondition").show();
			// }
			// for(var i in index1){
				// termsListId.push($("#allTermList").jqxGrid("getrowid", index1[i]));
			// }
			// $("#termListId").val(termsListId);
			var narration = $('#narration_submittal').val();
			if(narration==''||narration==null){
				$('#narraTion').hide();
			}else{
				$('#narraTion').show();
			}
			modalContent();
			$('#totalpage').modal('show');
			//$('form').submit();
		}			
	}
	
	function modalContent(){
		$('.modalInput').each(function(){
			$('.'+$(this).attr('id')).text($(this).val());
		});
		
		var addr=[];
		$('#delivery_address1').val().trim().length > 0?addr.push($('#delivery_address1').val()):'';
		$('#delivery_address2').val().trim().length > 0?addr.push($('#delivery_address2').val()):'';
		$('#delivery_address3').val().trim().length > 0?addr.push($('#delivery_address3').val()):'';
		
		$('.delivery_addressList').text(addr.join(', '));
		
		$('input:checkbox').each(function(){
			if($(this).is(':checked')){
				$('.'+$(this).attr('id')).html('Yes &nbsp;<span class="request_yescheck"><i class="fa fa-check"></i></span>');
				if($(this).attr('id') == 'verify_yes'){
					$('#techVerifyMod1').show();
					$('#techVerifyMod2').show();
				}
				else if($(this).attr('id') == 'submittal_yes'){
					$('#submittalDet').show();
				}
			} else {
				$('.'+$(this).attr('id')).html('No &nbsp;<span class="request_yescheckno"><i class="fa fa-times"></i></span>');
				if($(this).attr('id') == 'verify_yes'){
					$('#techVerifyMod1').hide();
					$('#techVerifyMod2').hide();
				}
				else if($(this).attr('id') == 'submittal_yes'){
					$('#submittalDet').hide();
				}
			}
		});
		var tCount =  $('#documentTable tbody tr').length;
		if(tCount==1){
			$('#techVerifyMod1').hide();
		}
		var projList = '';
		//$('.token-input-list-facebook li:not(:last-child)').each(function(){
		//	projList.push($(this).find('p').text());
		//});
		$.each($('#project_name').find('option:selected'), function() {
			projList += $(this).html() + ', ';
		});
		projList = projList.substr(0, projList.length - 2);
		$('.projectList').text(projList);
		$('#document_tbody').html('');
		$('#documentTable tbody tr').each(function(){
			if($(this).find('td:first input:text').val().trim().length != 0){
				$('#document_tbody').append('<tr>'+
												'<td>'+$(this).find('td:first input:text').val()+'</td>'+
												'<td>'+$(this).find('td:nth-child(2) input:text').val()+'</td>'+
												'<td>'+$(this).find('td:nth-child(3) input:text').val()+'</td>'+
											'</tr>');
			}
		});
        var qType = $('#qtype').val();
        var quotType = $('#autocomplete-qtnType').val();
        if(qType == 'Q') {
            var selIndex = $('#allReqDecisionList').jqxGrid('getselectedrowindexes');

            $('.decision_list').text($('#countdecision').text());
            $('#decision_body').html('');
            for (var i in selIndex) {
                var selectedRowData = $('#allReqDecisionList').jqxGrid('getrowdata', selIndex[i]);
                var decDate='';
                if(quotType == 'Material') {
                    $('#decision_body').append('<tr>' +
                    '<td>' + selectedRowData.RDecisionNo + '</td>' +
                    '<td>' + selectedRowData.DecDate + '</td>' +
                    '<td>' + selectedRowData.Description + '</td>' +
                    '<td>' + selectedRowData.Quantity + '</td>' +
                    '</tr>');
                }
                else {
                    $('#decision_body').append('<tr>' +
                    '<td>' + selectedRowData.RDecisionNo + '</td>' +
                    '<td>' + $.datepicker.formatDate('dd-mm-yy', new Date(selectedRowData.DecDate)) + '</td>' +
                    '<td>' + selectedRowData.Description + '</td>' +
                    '<td>' + selectedRowData.Quantity + '</td>' +
                    '</tr>');
                }
                //alert(selectedRowData.DecDate);
            }
            /*Decision quantity*/
            $('#decquantityTable').html($('#resourceTable').clone());
        }else{
            var selIndex1 = $('#allReqRequestList').jqxGrid('getselectedrowindexes');
            $('.request_list').text($('#countrequest').text());
            $('#request_body').html('');
            for(var i in selIndex1){
                var selectedRowData = $('#allReqRequestList').jqxGrid('getrowdata', selIndex1[i]);
                $('#request_body').append('<tr>'+
                '<td>'+selectedRowData.RequestNo+'</td>'+
                '<td>'+selectedRowData.RequestDate+'</td>'+
                '</tr>');
            }
            /*Request quantity*/
            $('#reqquantityTable').html($('#resourceTable1').clone());
        }
		var vendorIndex = $('#allVendorList').jqxGrid('getselectedrowindexes');
		$('#vendor_tbody').html('');
		for(var i in vendorIndex){
			var selectedRowData = $('#allVendorList').jqxGrid('getrowdata', vendorIndex[i]);
			$('#vendor_tbody').append('<tr>'+
											'<td>'+selectedRowData.VendorName+'</td>'+
										'</tr>');			
		}
		
		// var termIndex = $('#allTermList').jqxGrid('getselectedrowindexes');
		// $('#term_tbody').html('');
		// for(var i in termIndex){
			// var selectedRowData = $('#allTermList').jqxGrid('getrowdata', termIndex[i]);
			// $('#term_tbody').append('<tr>'+
										// '<td>'+selectedRowData.Title+'</td>'+
									// '</tr>');			
		// }
		

		$('#term_tbody').html('');
		$('#termsTable tbody tr').each(function(){
			if($(this).find('td:first input:text').val().trim().length != 0){
				$('#term_tbody').append('<tr>'+
												'<td>'+$(this).find('td:first input:text').val()+'</td>'+
												'<td>'+$(this).find('td:nth-child(2) input:text').val()+'</td>'+
												'<td>'+$(this).find('td:nth-child(3) input:text').val()+'</td>'+
												'<td>'+$(this).find('td:nth-child(4) input:text').val()+'</td>'+
												'<td>'+$(this).find('td:nth-child(5) input:text').val()+'</td>'+
												'<td>'+$(this).find('td:nth-child(6) input:text').val()+'</td>'+
												'<td>'+$(this).find('td:nth-child(7) input:text').val()+'</td>'+
											'</tr>');
			}
		})

		
		var submittal = [];
		$('#submittalTable tbody tr').each(function(){
			if($(this).find('input:text').val().trim().length != 0){
				submittal.push($(this).find('input:text').val());
			}
		});
		$('.submittal_value').text(submittal.join(', '));
	}
	
	$('.continueButton').click(function(){
		showPanel();
	});
		
	/*Vendorlist grid start*/	
	var vendorSource =
	{
		localData: <?php echo json_encode($vendorList); ?>,
		dataType: "json",
		dataFields:
		[
			{ name: 'VendorName', type: 'string' }
		],
		id:'VendorId'
	};

	var dataAdapterVendor = new $.jqx.dataAdapter(vendorSource,{
		autoBind: true,
		loadComplete: function (data) {
			
		},
		loadError: function (xhr, status, error) {
			
		}
	});


	$("#allVendorList").jqxGrid({
		width: '100%',
		pageable: true,
		selectionMode: 'singleRow',
		pagerButtonsCount: 6,
		autoheight:true,
		autorowheight: true,
		filterable: true,
		sortable: true,

		columnsResize: true,
		showfilterrow: true,
		ready: function(){
			var localizationobj = {};
			localizationobj.emptydatastring = "No vendor to display";
			$("#allVendorList").jqxGrid('localizestrings', localizationobj);
		},			
		selectionmode: 'checkbox',						
		source: dataAdapterVendor,
		columns: [
			  { text: 'VendorName', editable: false,datafield: 'VendorName'}
		]
	});
	
	$('#allVendorList').on('rowselect', function (event){
		// event arguments.
		var args = event.args;
		// row's bound index.
		var rowBoundIndex = args.rowindex;
		// row's data. The row's data object or null(when all rows are being selected or unselected with a single action). If you have a datafield called "firstName", to access the row's firstName, use var firstName = rowData.firstName;
		var rowData = args.row;
		resSelect = true;
	});	
	$('#allVendorList').on('rowunselect', function (event){
		// event arguments.
		var args = event.args;
		// row's bound index.
		var rowBoundIndex = args.rowindex;
		// row's data. The row's data object or null(when all rows are being selected or unselected with a single action). If you have a datafield called "firstName", to access the row's firstName, use var firstName = rowData.firstName;
		var rowData = args.row;
		resSelect = true;		
	});	
		
	$('#allVendorList').on('rowclick', function (event){
		var args = event.args;
		// row's bound index.
		var boundIndex = args.rowindex;
		var index = $('#allVendorList').jqxGrid('selectedrowindexes');
		if($.inArray(boundIndex, index) == -1)
			$('#allVendorList').jqxGrid('selectrow', boundIndex);
		else
			$('#allVendorList').jqxGrid('unselectrow', boundIndex);
						
	});	
	/*Vendorlist grid end*/
	
	
	/*Termlist grid start*/	
	/*var termSource =
	{
		localData: <?php echo json_encode($termList); ?>,
		dataType: "json",
		dataFields:
		[
			{ name: 'Title', type: 'string' }
		],
		id:'TermsId'
	};

	var dataAdapterTerm = new $.jqx.dataAdapter(termSource,{
		autoBind: true,
		loadComplete: function (data) {
			
		},
		loadError: function (xhr, status, error) {
			
		}
	});


	$("#allTermList").jqxGrid({
		width: '100%',
		pageable: true,
		selectionMode: 'singleRow',
		pagerButtonsCount: 6,
		autoheight:true,
		autorowheight: true,
		filterable: true,
		sortable: true,
		columnsResize: true,
		showfilterrow: true,
		ready: function(){
			var localizationobj = {};
			localizationobj.emptydatastring = "No terms to display";
			$("#allTermList").jqxGrid('localizestrings', localizationobj);
		},			
		selectionmode: 'checkbox',						
		source: dataAdapterTerm,
		columns: [
			  { text: 'Term Description', editable: false,datafield: 'Title'}
		]
	});
	
	$('#allTermList').on('rowselect', function (event){
		// event arguments.
		var args = event.args;
		// row's bound index.
		var rowBoundIndex = args.rowindex;
		// row's data. The row's data object or null(when all rows are being selected or unselected with a single action). If you have a datafield called "firstName", to access the row's firstName, use var firstName = rowData.firstName;
		var rowData = args.row;
		resSelect = true;
	});	
	$('#allTermList').on('rowunselect', function (event){
		// event arguments.
		var args = event.args;
		// row's bound index.
		var rowBoundIndex = args.rowindex;
		// row's data. The row's data object or null(when all rows are being selected or unselected with a single action). If you have a datafield called "firstName", to access the row's firstName, use var firstName = rowData.firstName;
		var rowData = args.row;
		resSelect = true;		
	});	
		
	$('#allTermList').on('rowclick', function (event){
		var args = event.args;
		// row's bound index.
		var boundIndex = args.rowindex;
		var index = $('#allTermList').jqxGrid('selectedrowindexes'); 
		//alert($.inArray(boundIndex, index))
		if($.inArray(boundIndex, index) == -1)
			$('#allTermList').jqxGrid('selectrow', boundIndex);
		else
			$('#allTermList').jqxGrid('unselectrow', boundIndex);
						
	});	*/
	/*Vendorlist grid end*/
	
	
	var oTable = $("#sequentialView").dataTable({"aLengthMenu": [[1, 5, 10], [1, 5, 10]],  "order": [],
		"initComplete": function(settings, json) {
			$("select[name=sequentialView_length]").addClass('show-tick').selectpicker();
		},	
		"drawCallback": function( settings ){
			$(this).find("tr.mainTr").trigger('click');
		}
	});
	function trimNumber(s){
	  while (s.substr(0,1) == '0' && s.length>1) { s = s.substr(1,9999); }
	  return s;
	}
	function changePage(){
		$(".quantityVal").unbind();
		$(".quantityVal").bind('focusin', function(e){
			var totDecVal = $(this).closest("tr").find("td:nth-child(2)").text();
			$(this).attr('data-original-title', 'Enter the value less than or equal to '+totDecVal);
			$(this).tooltip('show');
		});
		$(".quantityVal").bind('keyup keydown', function(e){
			var name = $(this).attr("name");
			var eleName = $(this).attr("elename");
			var key = e.which || e.keyCode;
			if(key != 9){
				var sum = 0;
				if($(this).val().indexOf(' ') > -1){
					$(this).val($(this).val().trim());
				}				
				if (isNaN($(this).val())){
					this.value = this.value.replace(/[^0-9\.]/g,'');
					if($(this).val().indexOf('.') > -1){
						var index = $(this).val().indexOf( '.' );
						this.value = this.value.substr( 0, index + 1 ) + this.value.slice( index ).replace( /\./g, '' );
					}
				}
				var ex = /^\d*(\.\d{0,6})?$/;
				if(!ex.test($(this).val())){
					$(this).val($(this).val().substring(0,$(this).val().length-1));
				}
				var currVal = $(this).val();
				
				var totDecVal = $(this).closest("tr").find("td:nth-child(2)").text();
				if(parseFloat(totDecVal) < parseFloat(currVal)){
					$(this).val(orgVal);
				}
				else{
					orgVal = $(this).val();
					$(this).closest('table').find(".quantityVal").each(function(){
						//add only if the value is number
						if (!isNaN(this.value) && this.value.length != 0) {
							sum += parseFloat(this.value);
						}
					});
					$("input[name="+eleName+"]").val(sum.toFixed(3));
				}
			}
		});
		$(".quantityVal").bind('change', function(){
			var name = $(this).attr("name");
			var eleName = $(this).attr("elename");
			
			var sum = 0;
			if (!isNaN($(this).val()) && $(this).val().length != 0) {

			}
			else{
				$(this).val($(this).val().substring(0,$(this).val().length-1));
			}
			var ex = /^\d*(\.\d{0,6})?$/;
			if(!ex.test($(this).val())){
				$(this).val($(this).val().substring(0,$(this).val().length-1));
			}
			var currVal = $(this).val();
			var totDecVal = $(this).closest("tr").find("td:nth-child(2)").text();
			if(parseFloat(totDecVal) < parseFloat(currVal)){
				 $(this).val(orgVal);
			}
			else{
				orgVal = $(this).val();
				$(this).closest('table').find(".quantityVal").each(function(){
					//add only if the value is number
					if (!isNaN(this.value) && this.value.length != 0) {
						sum += parseFloat(this.value);
					}
				});
				$("input[name="+eleName+"]").val(sum.toFixed(3));
			}
			//$(this).val(parseInput($(this).val()));
			var val = '0';
			if($(this).val() == '' || $(this).val() == 0){
				val = val+'.000000';
			}
			else{
				$(this).val(trimNumber($(this).val()));
				val1 = $(this).val();
				var str = '000000';
				var splitVal = val1.split('.');
				var len = 6;
				if(splitVal[1]){
					len -= splitVal[1].length;
				}
				if(len == 6)
					val = val1+'.000000';
				else if(len < 0)
					val = splitVal[0]+'.'+splitVal[1].substring(0,6);
				else
					val = val1+str.substring(0,len);
				
				if(val.substring(0,1) == '.')
					val = '0' + val;				
			}
			
			$("input[name="+name+"]").attr("value", val);
			$("input[name="+name+"]").val(val);			
		});
	}
	function trClick(){
		oTable.$("tr.mainTr").unbind();
		oTable.$("tr.mainTr").bind('click', function(){
			if(!($(this).next("tr").hasClass("duplicateTr"))){
				$(this).after("<tr class='duplicateTr'>"+$(".subTr_"+$(this).attr("id")).html()+"</tr>");
				$(this).next(".subTr_"+$(this).attr("id")).show();
				$(this).next("tr").find('.subDiv').slideDown("slow");
				changePage();
			}
		});
	}
	trClick();
	oTable.$("tr.mainTr").trigger("click");
	
	function removeFile(){
		$('.vq').unbind('click');
		$('.vq').bind('click', function(){
			var ele = $(this);
			var fname = ele.attr('fname');
			$.ajax({
				url:getBaseURL()+"ats/rfq/uploadfile/0",
				type:'post',
				data:'mode=delete&fname='+fname,
				success:function(data, textStatus, errorThrown){
					fileList.splice($.inArray(fname, fileList),1);
					ele.closest('div.file_content').fadeOut(500, function(){
						$(this).remove();
					})
				},
				erorr:function(jqXHR, textStatus, errorThrown){
					
				}
			});	
		});
	}
	
	$('#drag-and-drop-zone').dmUploader({
		url:getBaseURL()+"ats/rfq/uploadfile/0",
		dataType: 'json',
		//allowedTypes: 'image/*',
		onInit: function(){
		  
		},
		onBeforeUpload: function(id){
		  
		},
		onNewFile: function(id, file){
		  $.danidemo.addFile('#demo-files', id, file);

		  /*** Begins Image preview loader ***/
		  if (typeof FileReader !== "undefined"){
			
			var reader = new FileReader();

			// Last image added
			var img = $('#demo-files').find('.demo-image-preview').eq(0);

			reader.onload = function (e) {
			  img.attr('src', e.target.result);
			},

			reader.readAsDataURL(file);

		  } else {
			// Hide/Remove all Images if FileReader isn't supported
			$('#demo-files').find('.demo-image-preview').remove();
		  }
		  /*** Ends Image preview loader ***/

		},
		onComplete: function(){
		  $.danidemo.addLog('#demo-debug', 'default', 'All pending tranfers completed');
		  removeFile();
		},
		onUploadProgress: function(id, percent){
		  var percentStr = percent + '%';

		  $.danidemo.updateFileProgress(id, percentStr);
		},
		onUploadSuccess: function(id, data){
			fileList.push(data.fname);
			$.danidemo.updateFileProgress(id, '100%');
			$('#demo-file'+id).find('a').attr('href', '<?php echo $this->basePath(); ?>/uploads/doc_files/'+data.fname);
			$('#demo-file'+id).find('a').attr('download', data.fname);
			$('#demo-file'+id).find('a').text((data.fname.length > 50)?data.fname.substring(0, 50)+'...':data.fname);
			$('#demo-file'+id).find('.vq').attr('fname', data.fname);
		},
		onUploadError: function(id, message){
		  
		},
		onFileTypeError: function(file){
		  
		},
		onFileSizeError: function(file){
		  
		},
		onFallbackMode: function(message){
		  
		}
	});
	$(document).ready(function() {
		$(".multiple_dropdown").select2({
		});
	});
    $('#contact_number').on('change',function(){
        var len = $(this).val().length;
        if( len < 10){
            $('.error_message').show();
            return false;
        }
        else{
            $('.error_message').hide();
        }
    });
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////
 //terms &condition end
    var $trowid = $('#trowid');
    var template = $('#terms-template').html();
    var trowid = 0;
    var $tbody = $('#termsTable').find('> tbody');
    trowid += 1;
    $tbody.append(template.replace(/__/g, '_' + trowid));
    $trowid.val(trowid);
	
	
	// var arr_terms=<?php echo (isset($arr_terms)) ? json_encode($arr_terms) : '[]';?>;
	// var tmp_arr_terms=arr_terms;
	
	function bindTermsAutocomplete() {
		var type = $('#qtn_type').val();
		if(type==2){
			var arr_terms=<?php echo (isset($arr_terms)) ? json_encode($arr_terms) : '[]';?>;
		}else{
			var arr_terms=<?php echo (isset($arr_termsType)) ? json_encode($arr_termsType) : '[]';?>;
		}

		var tmp_arr_terms=arr_terms;

		// bind resource autocomplete
		$('#termsTable .resourceSuggest').autocomplete({
			lookup: tmp_arr_terms,
			lookupFilter: function (suggestion, originalQuery, queryLowerCase) {
				if (queryLowerCase == '*') {
					return suggestion.value;
				} else {
					var re = new RegExp($.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
					return re.test(suggestion.value);
				}
			}, onSelect: function (suggestion) {
				if (suggestion) {
					var $this = $(this);
					var rowid = $this[0].id.split('_')[1];
					$this.prop('readonly', true).addClass('border-none');
					$('#termsid_' + rowid).val(suggestion.data);
					$('#slno_' + rowid).val(suggestion.SlNo).attr("readonly",true);
					$('#terms_' + rowid).val(suggestion.value);
					$('#per_' + rowid).val(sanitizeNumber(suggestion.Per,2,true));
					$('#value_' + rowid).val(sanitizeNumber(suggestion.Val,2,true));
					$('#period_' + rowid).val(sanitizeNumber(suggestion.Period,1,true));
				//    $('#date_' + rowid).val(suggestion.Dte);
					$('#string_' + rowid).val(suggestion.Strg);
					$('#isper_' + rowid).val(suggestion.IsPer);
					$('#isvalue_' + rowid).val(suggestion.IsValue);
					$('#isperiod_' + rowid).val(suggestion.IsPeriod);
					$('#istdate_' + rowid).val(suggestion.IsTDate);
					$('#iststring_' + rowid).val(suggestion.IsTString);
					$('#includegross_' + rowid).val(suggestion.IncludeGross);
					$('#termsdeleteTr_' + rowid).show();
					if(parseInt($('#isper_' + rowid).val())==0){$('#per_' + rowid).attr("readonly",true);}
					if(parseInt($('#isvalue_' + rowid).val())==0) {$('#value_' + rowid).attr("readonly",true);}
					if(parseInt($('#isperiod_' + rowid).val())==0) {$('#period_' + rowid).attr("readonly",true);}
					if(parseInt($('#istdate_' + rowid).val())==0) {$('#date_' + rowid).attr("readonly",true);}
					if(parseInt($('#iststring_' + rowid).val())==0) {$('#string_' + rowid).attr("readonly",true);}
					addNewTermsRow($this);
				}
			}, onSearchStart: function (suggestion) {
				//var rowid = $(this)[0].id.split('_')[1];
				////$('#terms_' + rowid).val('');
			}, onSearchComplete: function (query, suggestions) {
				if(!suggestions.length) {
					// var rowid = $(this)[0].id.split('_')[1];
					// $('#terms_' + rowid).val('');
				}
			}
		});
	}
	function checkTermsUsed(x) {
		var type = $('#qtn_type').val();
		if(type==2){
			var arr_terms=<?php echo (isset($arr_terms)) ? json_encode($arr_terms) : '[]';?>;
		}else{
			var arr_terms=<?php echo (isset($arr_termsType)) ? json_encode($arr_termsType) : '[]';?>;
		}

		var tmp_arr_terms=arr_terms;
		
		var id = $(x)[0].id.split('_')[1];
		var termkeyid = $('input[id*=termsid_]');
		tmp_arr_terms = arr_terms;
		tmp_arr_terms = $.grep(arr_terms, function (element, index) {
			var is_selected = true;
			$.each(termkeyid, function (i, obj) { 
				var $this = $(this),
					name = $this[0].id;
				var arrname = name.split('_');
				var key1 = arrname[1];
				if (key1 != id) {
					if (element.data == $this.val()) { 
						is_selected = false;
						return false;
					}
				}
			});
			return is_selected;
		});
		bindTermsAutocomplete();
	}
	function addNewTermsRow(x) {
		var $tr = $(x).closest('tr');
		if ($tr.next('tr:not(.subTr)').length != 0)
			return;

		var $trowid = $('#trowid'),
			trowid = parseInt($trowid.val()),
			$tbody = $('#termsTable').find('> tbody.main');

		$('#deleteTr_' + trowid).show();
		var count = trowid + 1,
			template = $('#terms-template').html();

		template = template.replace(/__/g, '_' + count);
		$tbody.append(template);

		$trowid.val(count);
		var tCount =  $('#termsTable tbody tr').length;
		if(tCount > 1){
			$('#valuefrom').attr("disabled", true);
		}
		else {
			$('#valuefrom').attr("disabled", false);
		}
		bindTermsAutocomplete();
	}	

	function deleteRow(x,e) {
		e.preventDefault();
		var $x = $(x),
			key = $x[0].className.split('_')[1];

		if (!confirm('Do you want to Delete'))
			return false;

		var $tr = $x.closest('tr');
		$tr.next('.subTr').remove();
		$tr.next('.subTr').remove();
		$tr.remove();
		var rId = $('#rowid').val();
		rId--;
		if(rId == 1){
			document.getElementById("vendor").disabled = false;
		}
		$('#rowid').val(rId);
		calcTotal();
		bindTermsAutocomplete();
		TermsAutoRefresh();
		return false;
	}

</script>