<style xmlns="http://www.w3.org/1999/html">
.check{
	background-color:#77F8CC;
}
.rt_cmpr:focus, .rt_cmpr.active {
	border: 1px solid #4767aa;
}
.rt_cmpr { margin-left:20px !important;border:1px solid #ccc;padding:6px 4px;font-size:15px!important; color:#333;font-weight:normal !important;width:250px !important; height:32px !important;-webkit-transition: border-color 1s ease;-moz-transition:border-color 1s ease; -o-transition: border-color 1s ease;-ms-transition: border-color 1s ease;transition: border-color 1s ease;background:#fff;}
.blubg{background : #B0C3EB !important;}
.checkbox, .radio{margin:0 !important}
.table-fixed tbody td, .table-fixed thead > tr > th{height:43px}
#ratingWrapper .table > tbody > tr > td{padding-top:0;padding-bottom:0}
    .triangle-4{padding:1px 0px;top:2px;left:36%;text-align:center;float:left;width:80px; margin-bottom:8px; border:2px solid #3399ff;background: #e9f4fa;border-radius:5px; color:#333;font-size:10px;position:relative;font-weight:500}
    .triangle-4:before{border-top: solid 8px #3399ff;border-left: solid 8px transparent;border-right: solid 8px transparent;
     content:"";bottom:-33%; position: absolute;left:35%; }
    .rate {display:inline-block; border: 0;}
   .rate > input {display: none;}
    .rate > label {float: right;position:relative;}
   .rate > label:before {display: block;font-size: 25px;padding: .3rem .2rem;margin: 0;cursor: pointer;font-family: FontAwesome;content: "\f005 "; text-shadow: 0 0 1px #333333;}
   .rate .half:before {content: "\f089 "; text-shadow:-1px 0 1px #333333;position: absolute;padding-right: 0;}
    input:checked ~ label  { color: #FBB202;  }
.para-star{text-align:left;float:left;font:600 15px/25px 'roboto', sans-serif; color: #666;margin-top:20px;}	
   /* label:hover ~ label,
    label:hover
    input:checked + label:hover, input:checked ~ label:hover,
    input:checked ~ label:hover ~ label,
    label:hover ~ input:checked ~ label { color: #FBB202;  }*/
.label-txt > label:before{font-size:13px; padding:2px;}
a:hover,a{color:#666}
.hole-ratting{ width:100%}
.hole-ratting a{ display:block;}
ul.laste-save {margin-top:25px}
.table-responsive table.table tr td{border-bottom:1px solid #ddd;}
.list-detail span{width:70%; text-align:right !important;  margin-bottom:3px; font-weight:600 !important; padding-right:10px}
.bor-bttm{background:#ededed}
.modal-body{padding:5px 10px 4px 10px; margin-bottom:20px;}
.slink{float:left}
.paro-top{ position:absolute; top:-26px; margin-left: 18px; }
.top_move1{margin-top:0px;background: rgba(0, 0, 0, 0) none repeat scroll 0 0;
    border-bottom: medium none;}
.hvr-shutter-in-horizontal:hover, .hvr-shutter-in-horizontal:focus, .hvr-shutter-in-horizontal:active{ background:#3399ff; color:#3399ff}
/*** scroll bar styles */

.inliner                   {height: 100%;}
.inliner,.inliner + .inlined {display: inline-block;vertical-align: middle;}
.inlined                   {width: 90%;}
.progress-meter            {padding:30px 0 95px;}
.progress-meter            {counter-reset: point;}
.progress-meter .progress-point:before {-moz-transition: all 1s;-o-transition: all 1s;-webkit-transition: all 1s;transition: all 1s;-moz-border-radius: 24px; -webkit-border-radius: 24px;border-radius: 24px;-moz-box-shadow: 0 0 0 2px white;-webkit-box-shadow: 0 0 0 2px white;box-shadow: 0 0 0 2px white;content: "\2713";display: block;width: 24px;margin: 0 auto 12px;border: 2px solid #dddddd;text-align: center;background-color: white;color: #fff;}
.progress-meter .track {position: relative;height: 4px;background: #ddd;}
.progress-meter .progress  {-moz-transition: width 1s;-o-transition: width 1s;-webkit-transition: width 1s;transition: width 1s;display: block;position: absolute;left: 0; top: 0; width: 0;height: 4px;background: #f49706;}
.progress-meter .progress-points {position: relative;margin: -14px 0 0;padding: 0;list-style: none;}
.progress-meter .progress-points li.step-1{position:absolute}
.step-1:nth-child(1) { left: 0%;}
.step-1:nth-child(2) { left: 50%;}
.step-1:nth-child(3) { left: 100%;}
.progress-point a{color:#999}
.progress-point {-moz-transition: color 1s;-o-transition: color 1s;-webkit-transition: color 1s;transition: color 1s;position: absolute;display: block;width: 100px;margin-left: -50px;text-align: center;cursor: pointer;color: #999;}
.progress-point.completed {color: #f49706 !important;}
.progress-point.active {color: #3399ff !important;}
.progress-point.completed:before { border:2px solid #f49706 !important;background-color: #f49706 !important;}
.progress-point.active:before {-moz-transition-delay: 1s;-o-transition-delay: 1s;-webkit-transition-delay: 1s;
    transition-delay: 1s;border:2px solid #3399ff !important;background-color: #3399ff!important;color: #3399ff}
/*** scroll bar styles end */

.Table{overflow:auto;width:100%; border:1px solid #ddd;box-shadow: 0 1px 0 rgba(0, 0, 0, 0.12), 0 1px 1px rgba(0, 0, 0, 0.16);}
.cel-width{ width:300px !important;}
.Heading{display: table-row;background: #e7e7e7 none repeat scroll 0 0;color: #333333;line-height: 25px;}
.Heading >.inner-content,.Heading >.Cell { border-bottom: 2px solid #6fc8f1 !important;font-size:14px;font-weight: 500; text-align:center; color:#333;display: table-cell; padding:3px;}
.Row{display: table-row;border-bottom:1px solid #ddd;}
.Row >.Cell{display: table-cell;text-align:center;border-bottom:1px solid #ddd;line-height: 25px;padding:3px; color:#787882;text-align:center; font-weight:400}
.tab-cell{ width:1980px;}
.Row >.inner-content {display: table-cell;width: 3%;padding:1px;border-bottom:1px solid #ddd;}
</style>
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/mms.css';?>"/>
<div class="content_wrapper padlr0" >
    <div class="container-fluid">
		<form method="post" enctype="multipart/form-data">
			<input type="hidden" name="rfqId" id="rfqId" value="<?php echo $RfqId; ?>">
			<input type="hidden" name="regId" id="regId" value="<?php echo $RegId; ?>">
			<div class="row">
				<div class="col-lg-12 clear">
					<div class="col-lg-12">

						<h1>Rate Comparison<?php
                            if(isset($RegId) && $RegId!=0){
                                if ($vNo['genType']==true){
                                    echo '-' .$sAnalVNo['AnalysisRegNo'];?>
        					<input type="hidden" name="voucherNo" id="vhrno" class="rt_cmpr" value="<?php echo (isset($sAnalVNo['AnalysisRegNo'])) ? $sAnalVNo['AnalysisRegNo'] : ''; ?>" />
      							<?php } else { ?>
                            <input type="text" name="voucherNo" id="vhrno" class="rt_cmpr" value="<?php echo (isset($sAnalVNo['AnalysisRegNo'])) ? $sAnalVNo['AnalysisRegNo'] : ''; ?>" />
                                <?php }
     							} else {
                                	if ($vNo['genType']==true){
                                        echo '-' .$vNo['voucherNo'];?>
                          	<input type="hidden" name="voucherNo" id="vhrno" class="rt_cmpr" value="<?php echo (isset($sAnalVNo['AnalysisRegNo'])) ? $sAnalVNo['AnalysisRegNo'] : ''; ?>" />
      							<?php } else { ?>
                            <input type="text" name="voucherNo" id="vhrno" class="rt_cmpr" value="<?php echo (isset($sAnalVNo['AnalysisRegNo'])) ? $sAnalVNo['AnalysisRegNo'] : ''; ?>" />
                                <?php }
								} ?>
                        </h1>
					</div>
					<div class="col-lg-12 clear">
						<div class="col-lg-6 col-md-6">
                            <?php if($qtype == 'Q'){?>
							<div class="row">
								<div class=" col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p">Project Info<span class="colon_r">:</span></p></div>
								<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p"><?php echo $results['multiCC']; ?></p></div> 
							</div>
                            <?php }else{?>
                            <div class="row">
                                <div class=" col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p">Enquiry Info<span class="colon_r">:</span></p></div>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p"><?php echo $results['multiEN']; ?></p></div>
                            </div>
                            <?php } ?>

							<div class="row">
								<div class=" col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p">Location<span class="colon_r">:</span></p></div>
								<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p">Chennai</p></div> 
							</div>
						</div>
						<div class="col-lg-6 col-md-6">
							<div class="row">
								<div class=" col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p"> Quotation Detail<span class="colon_r">:</span></p></div>
								<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p"><?php echo $results['RFQNo']; ?></p></div> 
							</div>
							<div class="row">
								<div class=" col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p">Quotation sent on<span class="colon_r">:</span></p></div>
								<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p"><?php echo $results['RFQDate']; ?></p></div>  
							</div>
						</div>
					</div>

					
					
					
					
					
					
					
					
					<!-- table start -->
					<div class="col-lg-12 col-lg-offset-0 form-group" style="padding:0 !important display:none" id="firstDiv">
						<div class="Table">
							<div class="">
								<div class="Heading">
									<div class="Cell blubg" width="2%">Sno</div>
									<div class="Cell cel-width blubg" width="15%">Description</div>
									<div class="Cell cel-width blubg" width="10%">Quantity</div>
									<div class="Cell cel-width blubg" width="10%">Unit</div>
									<?php $ic=0;
									foreach($rsRFQVendorList as $vendorList){
										$ic=$ic+1;
										?>
										<div class="Cell blubg" width="25%"><?php echo $vendorList['VendorName'];?>
											<div class="Heading" style="clear:both">
												<div class="Cell cel-width inner-content blubg" style="border-bottom:none !important;">Rate</div>
												<div class="Cell cel-width inner-content blubg" style="border-bottom:none !important;">Amount</div>
											</div>
										</div>
										<?php } ?><input type="hidden" name="vendorCount" id="vendorCount" value="<?php echo $ic;?>"/>
										<div class="Cell text-right blubg" width="20%">Lowest quoted rate</div>
										<div class="Cell blubg" width="20%">Lowest quoted by</div>
								</div>	

								<?php $i=0;
								foreach($rsRFQResList1 as $rsRFQResList) { $i++;
								  $MResourceId= $rsRFQResList['ResourceId'];
								?>
								<div class="Row">
									<div class="Cell cel-width"><?php echo $i; ?></div>
									<div class="Cell cel-width"><?php echo $rsRFQResList['ResourceName']; ?></div>
									<div class="Cell cel-width"><?php echo $rsRFQResList['Quantity']; ?> </div>
									<div class="Cell cel-width"><?php echo $rsRFQResList['UnitName']; ?> </div>
									<?php $ic=0;
										foreach($rsRFQVendorList as $vendorList){
											$ic=$ic+1;
											$resourceId = $rsRFQResList['ResourceId'];
											$vendorId = $vendorList['VendorId'];
                                            $itemId = $rsRFQResList['ItemId'];

											$rate = 0;
											$status = 0;
											if(isset($resourceTrans[$resourceId][$vendorId])) {
												$rataArr = $resourceTrans[$resourceId][$vendorId];
												$rate = $rataArr['rate'];
												$status = $rataArr['status'];
												$Amt= $rsRFQResList['Quantity']* $rate;
											}
										?>	
										<div class="Cell cel-width text-right">
											<div class="Row checkClick <?php echo ($status == 1)?'check':''; ?>">
												<div class="inner-content"><input id="myCheckbox" type="checkbox" style="display: none;" <?php echo ($status == 1)?'checked':''; ?> class="checkChange" name="rate_<?php echo $resourceId; ?>_<?php echo $vendorId; ?>_<?php echo $itemId; ?>" value="<?php echo $rate; ?>"><?php echo $rate; ?></div>
												<div class="inner-content"><span class="Amount_<?php echo $ic;?>"><?php echo $this->commonHelper()->sanitizeNumber($Amt,2,true); ?></span></div>
											</div>
										</div>
									<?php }?>
									
									<?php 
									foreach ($rsRFQrank as $rsRFQrankord) {
										if($rsRFQrankord['ResourceId']==$resourceId){
											$Amount=$rsRFQrankord['Amount'];
											$VendorName=$rsRFQrankord['VName'];
									?>
									<?php }} ?>
									<div class="Cell cel-width text-right"><?php echo $Amount; ?>  </div>	
									<div class="Cell cel-width text-right"><?php echo $VendorName; ?>  </div>	
									
								</div>
								<?php }	?>	
								<div class="Row">
									<div class="Cell cel-width"></div>
									<div class="Cell cel-width"><b>Terms And Conditions</b></div>
									<div class="Cell cel-width"> </div>
									<div class="Cell text-right"> </div>

									 <?php $j=0;
									 foreach($rsRFQVendorList as $vendorList){
										$j=$j+1;
											$vendorId = $vendorList['VendorId']; ?>			
										<div class="Cell cel-width text-right">
											<a href="javascript: LoadTermsHistory(<?php  echo $RfqId. "," .$vendorId; ?>)" style="text-decoration: underline !important; color:#3399ff; line-height:38px; cursor:pointer; display:block" ><i class="fa fa-eye"></i>&nbsp; View Terms</a>

										</div>

										<?php } ?>
								</div>
								
								<div class="Row">
									<div class="Cell cel-width"></div>
									<div class="Cell cel-width"><b>Terms Amount</b></div>
									<div class="Cell cel-width"> </div>
									<div class="Cell cel-width"> </div>
									
									<?php if(isset($rsRFQTermtrans) && count($rsRFQTermtrans) != 0) {
                                    $ic=0;
									foreach($rsRFQVendorList as $vendorsList){
										$ifound=0;
										$ic=$ic+1;
										$amount=0;
									foreach ($rsRFQTermtrans as $terms) {

										$lVendorId= $vendorsList['VendorId'];
										if($lVendorId == $terms['VendorId'] && $terms['IncludeGross']==1) {
											$amount = $amount + $terms['Value'];
											$ifound=1; ?>
										<?php } }	?>
										<div class="Cell cel-width text-right"><span class="TAmount_<?php echo $ic;?>"><?php echo $this->commonHelper()->sanitizeNumber($amount,2,true); ?></span></div>
									<?php
									   if ($ifound==0) { ?>
										   <div class="Cell cel-width text-right">0.00</div>
										<?php } } ?>
									<?php } else {
									foreach($rsRFQVendorList as $vendorsList){
										?>
										<div class="Cell cel-width text-right">0.00</div>
									<?php } } ?>
								</div>
								
								<div class="Row">
									<div class="Cell cel-width"></div>
									<div class="Cell cel-width"><b>Total</b></div>
									<div class="Cell cel-width"> </div>
									<div class="Cell text-right"> </div>

									<?php $j=0;
										foreach($rsRFQVendorList as $vendorList){ 
										$j=$j+1;
											$vendorId = $vendorList['VendorId']; ?>						
										<div class="Cell cel-width text-right"><span class="Total_<?php echo $j;?>"></div> 
									<?php }	?>
								</div>
								
								<div class="Row">
									<div class="Cell cel-width"></div>
									<div class="Cell cel-width"><b>Rank</b></div>
									<div class="Cell cel-width"> </div>
									<div class="Cell cel-width"></div>

									<?php $ic=0;
									foreach($rsRFQVendorList as $vendorList){
										$ic=$ic+1;
										$lVendorId= $vendorList['VendorId'];?>
										<div class="Cell cel-width text-right rank_colr_<?php echo $ic;?>"><span class="rank_<?php echo $ic;?>"></span></div>

									<?php } ?>
								</div>
								
							</div>
							<input type="hidden" name="selectedResource" id="selectedResource">
							<input type="hidden" name="selectedTerms" id="selectedTerms">
						</div>
					</div>
					<!-- table start -->
					
					
					<!----------------modal popup---------------->
					<div class="modal fade" id="largequicker1" tabindex="-1" role="dialog" aria-labelledby="largeModal" aria-hidden="true">
						<div class="modal-dialog modal-lg">
							<div class="modal-content">
								<div class="modal-header">
									<button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times-circle-o cls-icon"></i></button>
									<h4 class="modal-title" id="myModalLabel"><sapn id="popupTxt">Terms & Conditions</sapn></h4>
								</div>
								<div class="modal-body" >
									<article class="temrs">
										<div class="table-responsive" id="enquiryWrapper">
										
										</div>
									</article>
								</div>
								<div class="modal-footer clear">
								</div>
							</div>
						</div>
					</div>
					<!----------------modal popup end---------------->
					
					
					
					
					
					<div class="col-lg-12">
						<ul>
							<li class="dropdown save_btn thumbsbck float_r" style="width:177px;"> <a href="javascript:void(0);" class="ripple continueButton" style="padding:3px;"><span style="font-size:20px;"></span>&nbsp;Submit</a> </li>
						<!--	<li class="dropdown cancel_btn  float_r"> <a href="javascript:void(0);" class="ripple backButton" style="font-size:18px;display:none;">Back</a> </li>-->
						</ul>
					</div>
				</div>
			</div>
		</form>	
    </div>
</div>
<script>
$(document).ready(function(){
	tdClick();
	function tdClick(){
		$('td.wishList div').unbind('click');
		$('td.wishList div').bind('click', function(){
			if($(this).hasClass('addinrate')){
				$(this).closest('td').html('<div class="wishlistinrate"><span class="wishlistinrateicon"><i class="fa fa-gratipay"></i></span>&nbsp;&nbsp;Wishlist</div>');
			}
			else{
				$(this).closest('td').html('<div class="addinrate"><span class="addinrateicon"><i class="fa fa-thumbs-up"></i></span>&nbsp;&nbsp;okay</div>');
			}
			tdClick();
		});
	}

	
	$('.checkClick').click(function(){
		var id = $(this).find('input:checkbox').attr('name').split('_');
		if($(this).find('input:checkbox').is(':checked')){
			$(this).find('input:checkbox').prop('checked', false);
			$(this).removeClass('check');
		}
		else{
			$(this).find('input:checkbox').prop('checked', true);
			$(this).addClass('check');
		}
	});
	// $('.backButton').click(function(){
		// if($('#secondDiv').is(':visible')){
			// $('#secondDiv').hide();
			// $('#firstDiv').show();
			// $('.backButton').hide();
			// $('.continueButton').html('<span style="font-size:20px;"></span>&nbsp;Continue');
		// }
	// });
	$('.continueButton').click(function(){
		if($('#firstDiv').is(':visible')){
			var json = [];
			var check = false;
			$('.checkChange').each(function(){
				if($(this).is(':checked')){
					check = true;
				}
			});
			$('.checkChange').each(function(){
				var res = {};
				var id = $(this).attr('name').split('_');
				console.log(id);
				res.resource = id[1];
				res.vendor = id[2];
                res.itemid = id[3];
				res.rate = $(this).val();

				if($(this).is(':checked')){ 
					res.status = 1;
				}
				else
                {
					res.status = 0;
				}
				json.push(res);
			});

			$('#selectedResource').val(JSON.stringify(json));
			
			var terms=[];
			$('.getlist').each(function(){
				var id = $(this).attr('id').split('_');
				var sub={};
				sub.vendor = id[1];
				if($(this).find('i').hasClass('fa-thumbs-up'))
					sub.termStatus = 0;
				else
					sub.termStatus = 1;

				if($('#submittal_'+id[1]).find('i').hasClass('fa-thumbs-up'))
					sub.subStatus = 0;
				else
					sub.subStatus = 1;
				
				terms.push(sub);
			});

			$('#selectedTerms').val(JSON.stringify(terms));
			if (check == true) { 
				$('form').submit();
			}else{
				alert('Finalize Any Vendor Rate');
				return false;
			}
		}
	});
	$('.locReplace').click(function(){
		var rfqId = $(this).attr('regId');
		if(rfqId != 0)
			location.replace("<?php echo $this->basePath(); ?>/ats/response/response-details/"+rfqId);
	});
})
$('.content_wrapper').on('click','.mainTr',function(e){
	e.preventDefault();
	if(!$(this).closest("tr").next(".subTr").is(":visible")){
		$(this).closest("tr").next(".subTr").show();
		$(this).closest("tr").next(".subTr").find(".subDiv").slideDown("slow");
		$(this).find("i").addClass("tform");
	}
	else{
		$(this).closest("tr").next(".subTr").find(".subDiv").slideUp("slow");
		$(this).closest("tr").next(".subTr").slideUp("slow");
		$(this).find("i").removeClass("tform");
	}
});
</script>
<script>
    $(document).ready(function() {
        var ivencount=$('#vendorCount').val();
        var arrSort=[];
		for(var i=1;i<=ivencount; i++){
            var amt=0;
            $.each($('.Amount_'+i), function(j,o) {
                amt += parseFloatVal($(this).html());
            });

            var tmpArr = [];
            tmpArr.push(i);
            tmpArr.push(amt); 
            arrSort.push(tmpArr);
			$('.Total_'+i).html(sanitizeNumber(amt,2,true));
        }
		
        $.each(arrSort.sort(function(a, b) {
            return a[1] - b[1];
        }), function(k, arr) {
            if(k+1 == 1){
                $( ".rank_colr_"+arr[0] ).css({"background-color": "#C7C7C7", "border": "1px solid #666","color": "#000000"});
				//$('.Amount_'+arr[0]).parent().parent().addClass('check');
				//$('#myCheckbox').prop('checked', true);
            }
            $('.rank_'+arr[0]).html('L'+ (k+1));
        });


    });
	function LoadTermsHistory(rfqId,vendId) {
		var vendId=vendId;
        var rfqId=rfqId;
        $('#largequicker1').modal('show');
		$('#popupTxt').html('Terms & Conditions');
        $.ajax({
            url:getBaseURL()+"ats/rfq/request-analysis",
            type:"post",
            data:{"VendorId": vendId,"RFQId": rfqId},
            async: false,
            //dataType:"json",
            success:function(data, textStatus, jqXHR){
                //console.log(data);
                $('#enquiryWrapper').html('');
                $('#enquiryWrapper').html(data);
            },
            error:function(jqXHR, textStatus, errorThrown){
            }
        });
    }
	
</script>