<!--STYLE-->
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/workorder.css';?>"/>
<style>
.form-control {
	box-shadow:none !important
}
</style>

<div class="content_wrapper padlr0">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h1>Qualifier</h1>
      </div>
      <!--form start-->
      <div class="col-lg-12 top_ct" >
        <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2  prt-next">
          <div class="col-sm-8 col-sm-offset-2 top-next">
            <form class="form-horizontal">
              <div class="row">
                <div class="form-group">
                  <div class="col-lg-12">
                    <input type="text" name="LeadDate" id="date" class="form-control lbl_move" label="Project Name"/>
                  </div>
                </div>
                        <div class="form-group">
                  <div class="col-lg-12">
                    <select name="named[]" id="lead_type" class="form-control selectpicker show-tick" data-size="5" title="Order No">
                      <option>Order No</option>
                      <option>Order No</option>
                      <option>Order No</option>
                    </select>
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-lg-12">
                    <select name="named[]" id="lead_type" class="form-control selectpicker show-tick" data-size="5" title="Bill No">
                      <option>Bill No</option>
                      <option>Bill No</option>
                      <option>Bill No</option>
                    </select>
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-lg-12">
                    <select name="named[]" id="lead_type" class="form-control selectpicker show-tick" data-size="5" title="Order No">
                      <option>Submit Bill</option>
                      <option>Submit Bill</option>
                      <option>Submit Bill</option>
                    </select>
                  </div>
                </div>
              </div>
            </form>
            <div class="next-bt"><a href="#">Next <i class="fa fa-chevron-circle-right"></i></a></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


