<!--STYLE-->
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/workorder.css';?>"/>
<style>
.pagination-lg > li > a, .pagination-lg > li > span {
	font-size:15px !important;
	padding:5px 15px !important;
}
/*.stats_box{ float:left; width:100%; margin-top:2%; margin-bottom:2%;}
.stats_box li {
    background:#EEEEEE;
    box-shadow: 0 0 0 1px hsl(0, 0%, 97%) inset, 0 0 0 1px hsl(0, 0%, 80%);
    display: inline-block;
    float: left;
    line-height: 18px;
    margin:9px;
    padding: 0 10px;
    text-shadow: 0 1px 0 hsla(0, 0%, 100%, 0.6);
}
.stats_box-left{ border-right: 1px solid hsl(0, 0%, 86%);
    box-shadow: 1px 0 0 0 hsl(0, 0%, 100%);
    float: left;
    line-height: 52px;
    margin-right: 9pt;
    min-width: 50px;
    padding: 10px 14px 0 4px; font-size:40px !important; color:#BEBEBE;}
.stats_box-right{ float: left;
    font-size: 9pt;
    min-width: 150px;
    padding:5px 10px 7px 0;
    position: relative;
    text-align: left;}
.stats_box-right p{ font-size:16px !important; font-weight:600; color:#1A5A94; padding-bottom:8px !important;}
.stats_box-right span{ font-size:15px !important; font-weight:normal; color:#C52F61;}*/
</style>
<!--content-->
<div class="content_wrapper padlr0">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h1>Client Billing Register</h1>
      </div>
      <!--panel-->
      <div class="col-lg-12 top_ct">
    <!--<div class="row c-reg">
   <div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0 clear">
 
   
   <ul class="stats_box">
   <li>
<div class="stats_box-left"><i class="fa fa-list-alt"></i></div>
<div class="stats_box-right"> <p>Projects</p>
              <span>152</span></div>
   
   </li>
     <li>
<div class="stats_box-left"><i class="fa fa-file-text"></i></div>
<div class="stats_box-right"> <p>Order Received</p>
              <span>Rs : 658 Crores</span></div>
   
   </li>
     <li>
<div class="stats_box-left"><i class="fa fa-check"></i></div>
<div class="stats_box-right"> <p>Bill Submited</p>
              <span>Rs : 123 Crores</span></div>
   
   </li>
     <li>
<div class="stats_box-left"><i class="fa fa-archive"></i></div>
<div class="stats_box-right"> <p>Payment Received</p>
              <span>Rs : 155</span></div>
   
   </li>
  
   </ul>
   
   
   
   </div>
      
      
      </div>-->
       <div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0 clear">
          <div class="col-lg-3 col-lg-offset-0 col-md-3 col-md-offset-0 col-sm-3 col-sm-offset-0">
            <div class="panelbody">
              <p>Projects</p>
              <span>152</span> <b><i class="fa fa-list-alt"></i></b> </div>
          </div>
          <div class="col-lg-3 col-lg-offset-0 col-md-3 col-md-offset-0 col-sm-3 col-sm-offset-0">
            <div class="panelbody colr-1">
              <p>Order Received</p>
              <span>Rs : 658 Crores</span> <b><i class="fa fa-file-text"></i></b> </div>
          </div>
          <div class="col-lg-3 col-lg-offset-0 col-md-3 col-md-offset-0 col-sm-3 col-sm-offset-0">
            <div class="panelbody colr-2">
              <p>Bill Submited</p>
              <span>Rs : 123 Crores</span> <b><i class="fa fa-check"></i></b> </div>
          </div>
          <div class="col-lg-3 col-lg-offset-0 col-md-3 col-md-offset-0 col-sm-3 col-sm-offset-0">
            <div class="panelbody colr-3">
              <p>Bill Certified</p>
              <span>Rs : 155</span> <b><i class="fa fa-file"></i></b> </div>
          </div>
          <div class="col-lg-3 col-lg-offset-0 col-md-3 col-md-offset-0 col-sm-3 col-sm-offset-0">
            <div class="panelbody colr-4">
              <p>Payment Received</p>
              <span>Rs : 155</span> <b><i class="fa fa-archive"></i></b> </div>
          </div>
        </div>
        <!--Panel End-->
        <div class="clearfix"></div>
        <div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0 clear">
          <div class="table-responsive topsp">
            <table class="table table-striped table-hover" id="simple-table">
              <thead>
                <tr>
                  <th class="center" colspan="7"> <div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0 clear">
                      <div class="col-lg-5 col-lg-offset-0 col-md-5 col-md-offset-0 col-sm-5 col-sm-offset-0 col-xs-5 col-xs-offset-0">
                        <div class="input-group line-bor">
                          <div class="input-group-btn search-panel">
                            <button type="button" class="btn btn-default dropdown-toggle conts" data-toggle="dropdown"> <span id="search_concept">Filter by</span> <span class="caret"></span> </button>
                            <ul class="dropdown-menu" role="menu">
                              <li><a href="#">Work Order No</a></li>
                              <li><a href="#">Start Date</a></li>
                              <li><a href="#">Completed Date</a></li>
                              <li><a href="#">Commercial Complex</a></li>
                            </ul>
                          </div>
                          <input type="hidden" name="search_param" value="all" id="search_param">
                          <input type="text" class="form-control conts" placeholder="Search term...">
                          <span class="input-group-btn">
                          <button class="btn btn-default searchs-pal conts" type="button"><span class="glyphicon glyphicon-search ic-colr"></span></button>
                          </span> </div>
                      </div>
                      <div class="col-lg-7 col-lg-offset-0 col-md-7 col-md-offset-0 col-sm-7 col-sm-offset-0 col-xs-7 col-xs-offset-0">
                        <div class="show-pages"> <b>Show</b>
                          <div class="select-style show-opt">
                            <select>
                              <option value="0">10</option>
                              <option value="1">25</option>
                              <option value="2">50</option>
                              <option value="3">100</option>
                            </select>
                          </div>
                          <b>Entries</b> </div>
                      </div>
                    </div>
                  </th>
                </tr>
              </thead>
              <tbody>
                <!--mani table-->
                <tr>
                  <td class="center" width="5%" valign="top"><span class="pr-ti">20/03/2015 </span>
                    <p class="cm-cps">AF1256</p></td>
                  <td width="20%"><span class="pr-ti">Proposal Complex Building at Chennai for Indian Oil Corporation Limited</span></td>
                  <td width="13%"><span class="pr-ti">Rs : 552565</span>
                    <p class="cm-cp">Submitted</p></td>
                  <td width="13%"><span class="pr-ti">Rs : 552565</span>
                    <p class="cm-cp">Certified</p></td>
                  <td width="13%"><span class="pr-ti">Rs : 552565</span>
                    <p class="cm-cp">Payment Recived</p></td>
                  <td width="2%"><a href="#" class="mainTr check-st"> Check status</a></td>
                </tr>
                <!--mani end--> 
                <!--expand-->
                <tr style="display:none;" class="subTr">
                  <td colspan="8" style="padding:0px !important; "><div class="subDiv status-main" style="display:none;">
                      <div class="col-lg-8 col-lg-offset-4 col-md-8 col-md-offset-4 col-sm-8 col-sm-offset-4 col-xs-8 col-xs-offset-4">
                        <div class="bs-wizard" style="border-bottom:0;">
                          <div class="col-xs-2 bs-wizard-step complete">
                            <div class="text-center bs-wizard-stepnum">Submitted</div>
                            <div class="progress">
                              <div class="progress-bar"></div>
                            </div>
                            <a href="#" class="bs-wizard-dot"></a> </div>
                          <div class="col-xs-2 bs-wizard-step complete"><!-- complete -->
                            <div class="text-center bs-wizard-stepnum">Certified</div>
                            <div class="progress">
                              <div class="progress-bar"></div>
                            </div>
                            <a href="#" class="bs-wizard-dot"></a> </div>
                          <div class="col-xs-2 bs-wizard-step disabled"><!-- active -->
                            <div class="text-center bs-wizard-stepnum">Receipt</div>
                            <div class="progress">
                              <div class="progress-bar"></div>
                            </div>
                            <a href="#" class="bs-wizard-dot"></a> </div>
                        </div>
                      </div>
                    </div></td>
                </tr>
                <!--expand-->
                   <!--mani table-->
                <tr>
                  <td class="center" width="5%" valign="top"><span class="pr-ti">20/03/2015 </span>
                    <p class="cm-cps">AF1256</p></td>
                  <td width="20%"><span class="pr-ti">Proposal Complex Building at Chennai for Indian Oil Corporation Limited</span></td>
                  <td width="13%"><span class="pr-ti">Rs : 552565</span>
                    <p class="cm-cp">Submitted</p></td>
                  <td width="13%"><span class="pr-ti">Rs : 552565</span>
                    <p class="cm-cp">Certified</p></td>
                  <td width="13%"><span class="pr-ti">Rs : 552565</span>
                    <p class="cm-cp">Payment Recived</p></td>
                  <td width="2%"><a href="#" class="mainTr check-st"> Check status</a></td>
                </tr>
                <!--mani end--> 
                <!--expand-->
                <tr style="display:none;" class="subTr">
                  <td colspan="8" style="padding:0px !important; "><div class="subDiv status-main" style="display:none;">
                      <div class="col-lg-8 col-lg-offset-4 col-md-8 col-md-offset-4 col-sm-8 col-sm-offset-4 col-xs-8 col-xs-offset-4">
                        <div class="bs-wizard" style="border-bottom:0;">
                          <div class="col-xs-2 bs-wizard-step complete">
                            <div class="text-center bs-wizard-stepnum">Submitted</div>
                            <div class="progress">
                              <div class="progress-bar"></div>
                            </div>
                            <a href="#" class="bs-wizard-dot"></a> </div>
                          <div class="col-xs-2 bs-wizard-step complete"><!-- complete -->
                            <div class="text-center bs-wizard-stepnum">Certified</div>
                            <div class="progress">
                              <div class="progress-bar"></div>
                            </div>
                            <a href="#" class="bs-wizard-dot"></a> </div>
                          <div class="col-xs-2 bs-wizard-step disabled"><!-- active -->
                            <div class="text-center bs-wizard-stepnum">Receipt</div>
                            <div class="progress">
                              <div class="progress-bar"></div>
                            </div>
                            <a href="#" class="bs-wizard-dot"></a> </div>
                        </div>
                      </div>
                    </div></td>
                </tr>
                <!--expand-->
                   <!--mani table-->
                <tr>
                  <td class="center" width="5%" valign="top"><span class="pr-ti">20/03/2015 </span>
                    <p class="cm-cps">AF1256</p></td>
                  <td width="20%"><span class="pr-ti">Proposal Complex Building at Chennai for Indian Oil Corporation Limited</span></td>
                  <td width="13%"><span class="pr-ti">Rs : 552565</span>
                    <p class="cm-cp">Submitted</p></td>
                  <td width="13%"><span class="pr-ti">Rs : 552565</span>
                    <p class="cm-cp">Certified</p></td>
                  <td width="13%"><span class="pr-ti">Rs : 552565</span>
                    <p class="cm-cp">Payment Recived</p></td>
                  <td width="2%"><a href="#" class="mainTr check-st"> Check status</a></td>
                </tr>
                <!--mani end--> 
                <!--expand-->
                <tr style="display:none;" class="subTr">
                  <td colspan="8" style="padding:0px !important; "><div class="subDiv status-main" style="display:none;">
                      <div class="col-lg-8 col-lg-offset-4 col-md-8 col-md-offset-4 col-sm-8 col-sm-offset-4 col-xs-8 col-xs-offset-4">
                        <div class="bs-wizard" style="border-bottom:0;">
                          <div class="col-xs-2 bs-wizard-step complete">
                            <div class="text-center bs-wizard-stepnum">Submitted</div>
                            <div class="progress">
                              <div class="progress-bar"></div>
                            </div>
                            <a href="#" class="bs-wizard-dot"></a> </div>
                          <div class="col-xs-2 bs-wizard-step complete"><!-- complete -->
                            <div class="text-center bs-wizard-stepnum">Certified</div>
                            <div class="progress">
                              <div class="progress-bar"></div>
                            </div>
                            <a href="#" class="bs-wizard-dot"></a> </div>
                          <div class="col-xs-2 bs-wizard-step disabled"><!-- active -->
                            <div class="text-center bs-wizard-stepnum">Receipt</div>
                            <div class="progress">
                              <div class="progress-bar"></div>
                            </div>
                            <a href="#" class="bs-wizard-dot"></a> </div>
                        </div>
                      </div>
                    </div></td>
                </tr>
                <!--expand-->
                
              </tbody>
            </table>
          </div>
        </div>
        <div class="clearfix"></div>
        <div class="text-center col-lg-5 col-lg-offset-7 col-md-5 col-md-offset-7 col-sm-5 col-sm-offset-7">
          <ul class="pagination pagination-lg">
            <li> <a href="#" aria-label="Previous"> <span aria-hidden="true">Previous</span> </a> </li>
            <li><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
            <li> <a href="#" aria-label="Next"> <span aria-hidden="true">Next</span> </a> </li>
          </ul>
        </div>
        <!--Chat-->
        <div class="clearfix"></div>
        <div class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0">
          <div class="reg-chats">
            <h2>Project Types</h2>
            <div id="chartdiv"></div>
          </div>
        </div>
        <div class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0">
          <div class="reg-chats">
            <h2>Yearly Turn Over</h2>
          </div>
        </div>
        <!--Chat--> 
      </div>
    </div>
  </div>
</div>
<div class="col-lg-12 savebtn_area">
  <ul>
    <li class="dropdown save_btn float_r ripple"><a href="javascript:void(0);">Submit</a> 
      <!--<li class="cancel_btn float_r"><a href="javascript:void(0);">Back</a></li>-->
  </ul>
</div>
<!--content end--> 
<script>
$(".mainTr").click(function(e){
	e.preventDefault();
	if(!$(this).closest("tr").next(".subTr").is(":visible")){
		$(this).closest("tr").next(".subTr").show();
		$(this).closest("tr").next(".subTr").find(".subDiv").slideDown("slow");	
		$(this).find("i").addClass("tform");
	}
		else{
		$(this).closest("tr").next(".subTr").find(".subDiv").slideUp("slow");
		$(this).closest("tr").next(".subTr").slideUp("slow");
		$(this).find("i").removeClass("tform");
	}
})
</script> 
<!--table expand end--> 
