<!--STYLE-->
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/workorder.css';?>"/>
<!--STYLE-->
<style>
.panel {
	border-radius:0px !important;
}
.panel-info {
	border:none;
	border-top:none;
}
</style>

<!--content-->
<div class="content_wrapper padlr0">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h1>Project Name</h1>
      </div>

      <div class="clearfix"></div>
      <!--table start-->
      
      <div class="col-lg-12 col-lg-offset-0">
        <div class="table-responsive topsp animated-panel zoomIn" style="animation-delay: 0.2s;">
          <table class="table" style=" margin-bottom:0px;">
            <thead>
              <tr>
                <th>&nbsp;</th>
                <th>Description</th>
                <th>Cumulative</th>
                <th>Previous</th>
                <th>Current</th>
                <th>&nbsp; </th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td width="3%"><b class="ra-t">R1</b></td>
                <td width="10%"><p class="dec-ptr">Agreement Items</p></td>
                <td width="10%" ><input class="parent_text" type="text"/></td>
                <td width="10%"><input class="parent_text" type="text" /></td>
                <td width="10%"><input class="parent_text" type="text" /></td>
                <td width="3%" align="center" class="action_btns_td"><ul class="action_btns">
                    <li> <a href="#" class="mainTr"> <i class="fa fa-chevron-circle-down" data-toggle="tooltip" data-placement="top" data-original-title="Add lines" ></i></a> </li>
                    <li> <a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i> </a> </li>
                  </ul></td>
              </tr>
              
              <!--Add lines table-->
              <tr style="display:none;" class="subTr">
                <td colspan="9" style="padding:0px !important; "><div class="subDiv" style="display:none;">
                    <div class="col-lg-12 col-lg-offset-0 rdbt" style="margin-top:5px;"> </div>
                    <div class="col-lg-12">
                      <div class="table-responsive topsp">
                        <table class="table" style="margin-bottom:0px;">
                          <thead>
                            <tr>
                              <th>Agt No</th>
                              <th>Specification</th>
                              <th>Unit</th>
                              <th>Qty</th>
                              <th>Rate</th>
                              <th>Amount</th>
                              <th>&nbsp; </th>
                            </tr>
                          </thead>
                          <tbody>
                            <tr>
                              <td width="5%"><input class="parent_text" type="text" /></td>
                              <td width="15%"><input class="parent_text" type="text" /></td>
                              <td width="5%"><input class="parent_text" type="text" /></td>
                              <td width="5%"><input class="parent_text" type="text" /></td>
                              <td width="6%"><input class="parent_text" type="text" /></td>
                              <td width="10%"><input class="parent_text" type="text" /></td>
                              <td width="3%" align="center" class="action_btns_td"><ul class="action_btns">
                                  <li> <a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i> </a> </li>
                                </ul></td>
                            </tr>
                            <tr>
                              <td colspan="4"></td>
                              <td align="right" class="rate_pri">Total</td>
                              <td width="5%"><input class="parent_text" type="text" /></td>
                              <td>&nbsp;</td>
                            </tr>
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div></td>
              </tr>
              <!--Add lines end-->
            </tbody>
            <tbody>
              <tr>
                <td width="3%"><b class="ra-t">R2</b></td>
                <td width="10%"><p class="dec-ptr">Non Agreement Items</p></td>
                <td width="10%" ><input class="parent_text" type="text"/></td>
                <td width="10%"><input class="parent_text" type="text" /></td>
                <td width="10%"><input class="parent_text" type="text" /></td>
                <td width="3%" align="center" class="action_btns_td"><ul class="action_btns">
                    <li> <a href="#" class="mainTr"> <i class="fa fa-chevron-circle-down" data-toggle="tooltip" data-placement="top" data-original-title="Add lines" ></i></a> </li>
                    <li> <a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i> </a> </li>
                  </ul></td>
              </tr>
              
              <!--Add lines table-->
              <tr style="display:none;" class="subTr">
                <td colspan="9" style="padding:0px !important; "><div class="subDiv" style="display:none;">
                    <div class="col-lg-12 col-lg-offset-0 rdbt" style="margin-top:5px;"> </div>
                    <div class="col-lg-12">
                      <div class="table-responsive topsp">
                        <table class="table" style="margin-bottom:0px;">
                          <thead>
                            <tr>
                              <th>Agt No</th>
                              <th>Specification</th>
                              <th>Unit</th>
                              <th>Qty</th>
                              <th>Rate</th>
                              <th>Amount</th>
                              <th>&nbsp; </th>
                            </tr>
                          </thead>
                          <tbody>
                            <tr>
                              <td width="5%"><input class="parent_text" type="text" /></td>
                              <td width="15%"><input class="parent_text" type="text" /></td>
                              <td width="5%"><input class="parent_text" type="text" /></td>
                              <td width="5%"><input class="parent_text" type="text" /></td>
                              <td width="6%"><input class="parent_text" type="text" /></td>
                              <td width="10%"><input class="parent_text" type="text" /></td>
                              <td width="3%" align="center" class="action_btns_td"><ul class="action_btns">
                                  <li> <a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i> </a> </li>
                                </ul></td>
                            </tr>
                            <tr>
                              <td colspan="4"></td>
                              <td align="right" class="rate_pri">Total</td>
                              <td width="5%"><input class="parent_text" type="text" /></td>
                              <td>&nbsp;</td>
                            </tr>
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div></td>
              </tr>
              <!--Add lines end-->
            </tbody>
            <tbody>
              <tr>
                <td width="3%"><b class="ra-t">R3</b></td>
                <td width="10%"><p class="dec-ptr">Material Advance</p></td>
                <td width="10%" ><input class="parent_text" type="text"/></td>
                <td width="10%"><input class="parent_text" type="text" /></td>
                <td width="10%"><input class="parent_text" type="text" /></td>
                <td width="3%" align="center" class="action_btns_td"><ul class="action_btns">
                    <li> <a href="#" class="mainTr"> <i class="fa fa-chevron-circle-down" data-toggle="tooltip" data-placement="top" data-original-title="Add lines" ></i></a> </li>
                    <li> <a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i> </a> </li>
                  </ul></td>
              </tr>
              
              <!--Add lines table-->
              <tr style="display:none;" class="subTr">
                <td colspan="9" style="padding:0px !important; "><div class="subDiv" style="display:none;">
                    <div class="col-lg-12 col-lg-offset-0 rdbt" style="margin-top:5px;"> </div>
                    <div class="col-lg-12">
                      <div class="table-responsive topsp">
                        <table class="table" style="margin-bottom:0px;">
                          <thead>
                            <tr>
                              <th>Material Name</th>
                              <th>Unit</th>
                              <th>Qty</th>
                              <th>Rate</th>
                              <th>Amount</th>
                              <th>Advance %</th>
                              <th>Advance Amount</th>
                              <th>&nbsp; </th>
                            </tr>
                          </thead>
                          <tbody>
                            <tr>
                              <td width="13%"><input class="parent_text" type="text" /></td>
                              <td width="5%"><input class="parent_text" type="text" /></td>
                              <td width="5%"><input class="parent_text" type="text" /></td>
                              <td width="6%"><input class="parent_text" type="text" /></td>
                              <td width="6%"><input class="parent_text" type="text" /></td>
                              <td width="10%"><input class="parent_text" type="text" /></td>
                              <td width="10%"><input class="parent_text" type="text" /></td>
                              <td width="3%" align="center" class="action_btns_td"><ul class="action_btns">
                                  <li> <a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i> </a> </li>
                                </ul></td>
                            </tr>
                            <tr>
                              <td colspan="5"></td>
                              <td align="right" class="rate_pri">Total</td>
                              <td width="5%"><input class="parent_text" type="text" /></td>
                              <td>&nbsp;</td>
                            </tr>
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div></td>
              </tr>
              <!--Add lines end-->
            </tbody>
            <tbody>
              <tr>
                <td width="3%"><b class="ra-t">R4</b></td>
                <td width="10%"><p class="dec-ptr">Price Escalation</p></td>
                <td width="10%" ><input class="parent_text" type="text"/></td>
                <td width="10%"><input class="parent_text" type="text" /></td>
                <td width="10%"><input class="parent_text" type="text" /></td>
                <td width="3%" align="center" class="action_btns_td"><ul class="action_btns">
                    <li> <a href="#" class="mainTr"> <i class="fa fa-chevron-circle-down" data-toggle="tooltip" data-placement="top" data-original-title="Add lines" ></i></a> </li>
                    <li> <a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i> </a> </li>
                  </ul></td>
              </tr>
              
              <!--Add lines table-->
              <tr style="display:none;" class="subTr">
                <td colspan="9" style="padding:0px !important; "><div class="subDiv" style="display:none;">
                    <div class="col-lg-12 col-lg-offset-0 rdbt" style="margin-top:5px;"> </div>
                    <div class="col-lg-12">
                      <div class="table-responsive topsp">
                        <table class="table" style="margin-bottom:0px;">
                          <thead>
                            <tr>
                              <th>Material Name</th>
                              <th>Unit</th>
                              <th>Qty</th>
                              <th>Base Rate</th>
                              <th>Escalation %</th>
                              <th>Actual Rate</th>
                              <th>Amount</th>
                              <th>&nbsp; </th>
                            </tr>
                          </thead>
                          <tbody>
                            <tr>
                              <td width="13%"><input class="parent_text" type="text" /></td>
                              <td width="5%"><input class="parent_text" type="text" /></td>
                              <td width="5%"><input class="parent_text" type="text" /></td>
                              <td width="6%"><input class="parent_text" type="text" /></td>
                              <td width="6%"><input class="parent_text" type="text" /></td>
                              <td width="10%"><input class="parent_text" type="text" /></td>
                              <td width="10%"><input class="parent_text" type="text" /></td>
                              <td width="4%" align="center" class="action_btns_td"><ul class="action_btns">
                                  <li> <a href="#" class="mainTr"> <i class="fa fa-chevron-circle-down" data-toggle="tooltip" data-placement="top" data-original-title="Add lines" ></i></a> </li>
                                  <li> <a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i> </a> </li>
                                </ul></td>
                            </tr>
                            <!--Add lines-->
                            <tr style="display:none;" class="subTr">
                              <td colspan="9" style="padding:0px !important; "><div class="subDiv" style="display:none;">
                                  <div class="col-lg-12 col-lg-offset-0 rdbt" style="margin-top:5px;"> </div>
                                  <div class="col-lg-12">
                                    <div class="table-responsive topsp">
                                      <table class="table" style="margin-bottom:0px;">
                                        <thead>
                                          <tr>
                                            <th>Bill Date</th>
                                            <th>Bill No</th>
                                            <th>Supplier Name</th>
                                            <th>Qty</th>
                                            <th>Rate</th>
                                            <th>Amount</th>
                                            <th>&nbsp; </th>
                                          </tr>
                                        </thead>
                                        <tbody>
                                          <tr>
                                            <td width="5%"><input class="parent_text" type="text" /></td>
                                            <td width="5%"><input class="parent_text" type="text" /></td>
                                            <td width="10%"><input class="parent_text" type="text" /></td>
                                            <td width="6%"><input class="parent_text" type="text" /></td>
                                            <td width="6%"><input class="parent_text" type="text" /></td>
                                            <td width="10%"><input class="parent_text" type="text" /></td>
                                            <td width="1%" align="center" class="action_btns_td"><ul class="action_btns">
                                                <li> <a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i> </a> </li>
                                              </ul></td>
                                          </tr>
                                        </tbody>
                                        <tbody>
                                          <tr>
                                            <td width="5%">&nbsp;</td>
                                            <td width="5%">&nbsp;</td>
                                            <td width="10%" class="rate_pri" align="right">Total</td>
                                            <td width="6%"><input class="parent_text" type="text" /></td>
                                            <td width="6%"><input class="parent_text" type="text" /></td>
                                            <td width="10%"><input class="parent_text" type="text" /></td>
                                            <td width="1%">&nbsp;</td>
                                          </tr>
                                        </tbody>
                                      </table>
                                    </div>
                                  </div>
                                </div></td>
                            </tr>
                            <!--Add lines-->
                            <tr>
                              <td class="nt-am" align="right" width="5%"><span>Purchase Rate</span></td>
                              <td width="8%"><input class="parent_text" type="text" /></td>
                              <td class="nt-am" align="right" width="3%"><span>Base Rate</span></td>
                              <td width="8%"><input class="parent_text" type="text" /></td>
                              <td class="nt-am" align="right" width="5%"><span>Escalation %</span></td>
                              <td width="8%"><input class="parent_text" type="text" /></td>
                              <td class="nt-am" align="right" width="5%"><span>Actual Rate</span></td>
                              <td width="8%"><input class="parent_text" type="text" /></td>
                            </tr>
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div></td>
              </tr>
              <!--Add lines end-->
            </tbody>
            <tbody>
              <tr>
                <td width="3%"><b class="ra-t">R5</b></td>
                <td width="10%"><p class="dec-ptr">Advance Recovery</p></td>
                <td width="10%" ><input class="parent_text" type="text"/></td>
                <td width="10%"><input class="parent_text" type="text" /></td>
                <td width="10%"><input class="parent_text" type="text" /></td>
                <td width="3%" align="center" class="action_btns_td"><ul class="action_btns">
                    <li> <a href="#" class="mainTr"> <i class="fa fa-chevron-circle-down" data-toggle="tooltip" data-placement="top" data-original-title="Add lines" ></i></a> </li>
                    <li> <a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i> </a> </li>
                  </ul></td>
              </tr>
              
              <!--Add lines table-->
              <tr style="display:none;" class="subTr">
                <td colspan="9" style="padding:0px !important; "><div class="subDiv" style="display:none;">
                    <div class="col-lg-12 col-lg-offset-0 rdbt" style="margin-top:5px;"> </div>
                    <div class="col-lg-12">
                      <div class="table-responsive topsp">
                        <table class="table" style="margin-bottom:0px;">
                          <thead>
                            <tr>
                              <th>Date</th>
                              <th>Description</th>
                              <th>Total Advance</th>
                              <th>Recovered</th>
                              <th>Balance</th>
                              <th>Current</th>
                              <th>&nbsp; </th>
                            </tr>
                          </thead>
                          <tbody>
                            <tr>
                              <td width="3%"><input class="parent_text" type="text" /></td>
                              <td width="10%"><input class="parent_text" type="text" /></td>
                              <td width="6%"><input class="parent_text" type="text" /></td>
                              <td width="6%"><input class="parent_text" type="text" /></td>
                              <td width="7%"><input class="parent_text" type="text" /></td>
                              <td width="10%"><input class="parent_text" type="text" /></td>
                              <td width="1%" align="center" class="action_btns_td"><ul class="action_btns">
                                  <li> <a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i> </a> </li>
                                </ul></td>
                            </tr>
                            <tr>
                              <td colspan="4"></td>
                              <td align="right" class="rate_pri">Total</td>
                              <td width="5%"><input class="parent_text" type="text" /></td>
                              <td>&nbsp;</td>
                            </tr>
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div></td>
              </tr>
              <!--Add lines end-->
            </tbody>
            <tbody>
              <tr>
                <td width="3%"><b class="ra-t">R6</b></td>
                <td width="10%"><p class="dec-ptr">TDS</p></td>
                <td width="10%" ><input class="parent_text" type="text"/></td>
                <td width="10%"><input class="parent_text" type="text" /></td>
                <td width="10%"><input class="parent_text" type="text" /></td>
                <td width="3%" align="center" class="action_btns_td"><ul class="action_btns">
                    <li> <a href="#" class="mainTr"> <i class="fa fa-chevron-circle-down" data-toggle="tooltip" data-placement="top" data-original-title="Add lines" ></i></a> </li>
                    <li> <a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i> </a> </li>
                  </ul></td>
              </tr>
              
              <!--Add lines table--> 
              <!-- <tr style="display:none;" class="subTr">
                <td colspan="9" style="padding:0px !important; "><div class="subDiv" style="display:none;">
                    <div class="col-lg-12 col-lg-offset-0 rdbt" style="margin-top:5px;"> </div>
                    <div class="col-lg-12">
                      <div class="table-responsive topsp">
                        <table class="table" style="margin-bottom:0px;">
                          <thead>
                            <tr>
                              <th>Date</th>
                              <th>Description</th>
                              <th>Total Advance</th>
                              <th>Recovered</th>
                              <th>Balance</th>
                              <th>Current</th>
                              <th>&nbsp; </th>
                            </tr>
                          </thead>
                          <tbody>
                            <tr>
                              <td width="3%"><input class="parent_text" type="text" /></td>
                              <td width="10%"><input class="parent_text" type="text" /></td>
                              <td width="6%"><input class="parent_text" type="text" /></td>
                              <td width="6%"><input class="parent_text" type="text" /></td>
                              <td width="7%"><input class="parent_text" type="text" /></td>
                              <td width="10%"><input class="parent_text" type="text" /></td>
                              <td width="1%" align="center" class="action_btns_td"><ul class="action_btns">
                                  <li> <a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i> </a> </li>
                                </ul></td>
                            </tr>
                            <tr>
                              <td colspan="4"></td>
                              <td align="right" class="rate_pri">Total</td>
                              <td width="5%"><input class="parent_text" type="text" /></td>
                              <td>&nbsp;</td>
                            </tr>
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div></td>
              </tr>--> 
              <!--Add lines end-->
            </tbody>
            <tbody>
              <tr>
                <td>&nbsp;</td>
                <td width="10%" align="right" class="nt-am"><b>Net Amount</b></td>
                <td width="10%" ><input class="parent_text" type="text"/></td>
                <td width="10%"><input class="parent_text" type="text" /></td>
                <td width="10%"><input class="parent_text" type="text" /></td>
                <td>&nbsp;</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="clearfix"></div>
      <!--listed-dis-->
      <div class="col-lg-12">
        <ul class="listed-dis">
          <li>
            <div class="radio_check">
              <p>
                <input type="checkbox" checked="" id="auto_generate" value="">
                <label class="ripple" for="auto_generate">Auto Generate Progress bill</label>
              </p>
            </div>
          </li>
          <li>
            <input class="parent_text" type="text" />
          </li>
          <li>
            <input class="parent_texts" type="text" />
          </li>
        </ul>
        <div class="notefic">
        <h1>Notes .......</h1>
     <ul>
     <li><p>Billing software has never looked this good or been this simple to operate. The intuitive design makes it one of the most accessible billing software available.</p></li>
     <li><p>Billing software has never looked this good or been this simple to operate. The intuitive design makes it one of the most accessible billing software available.</p></li>
     <li><p>Billing software has never looked this good or been this simple to operate. The intuitive design makes it one of the most accessible billing software available.</p></li>
     <li><p>Billing software has never looked this good or been this simple to operate. The intuitive design makes it one of the most accessible billing software available.</p></li>
     <li><p>Billing software has never looked this good or been this simple to operate. The intuitive design makes it one of the most accessible billing software available.</p></li>
     <li><p>Billing software has never looked this good or been this simple to operate. The intuitive design makes it one of the most accessible billing software available.</p></li>
     
     </ul>
       
        
        
        </div>
      </div>
        <!--listed-dis-->
      <!--table end-->
      <div class="col-lg-12"> 
        <!--Receipt Details-->
        <div class="panel panel-info">
          <div data-target="#collapseTwo" data-parent="#accordion" data-toggle="collapse" class="panel-heading collapsed panel_heads">
            <h4 class="panel-title accordion-toggle defa_panels">Receipt Details</h4>
          </div>
          <div class="panel-collapse collapse" id="collapseTwo" style="height: 0px;">
            <div class="panel-body bgcolr bg-bdy">
              <div class="deft_act">
                <div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0">
                  <div class="table-responsive topsp animated-panel zoomIn" style="animation-delay: 0.2s;">
                    <table class="table" style=" margin-bottom:0px;">
                      <thead>
                        <tr>
                          <th>Date</th>
                          <th>Mode of Payment</th>
                          <th>Transaction No</th>
                          <th>Payment Description</th>
                          <th>Amount</th>
                          <th>&nbsp;</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td width="5%"><input class="parent_text" type="text" /></td>
                          <td width="8%"><input class="parent_text" type="text" /></td>
                          <td width="8%"><input class="parent_text" type="text" /></td>
                          <td width="8%"><input class="parent_text" type="text" /></td>
                          <td width="8%" align="right"><input class="parent_text" type="text" /></td>
                          <td width="1%" align="center" class="action_btns_td"><ul class="action_btns">
                              <li> <a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i> </a> </li>
                            </ul></td>
                        </tr>
                        <tr>
                          <td width="5%"><input class="parent_text" type="text" /></td>
                          <td width="8%"><input class="parent_text" type="text" /></td>
                          <td width="8%"><input class="parent_text" type="text" /></td>
                          <td width="8%"><input class="parent_text" type="text" /></td>
                          <td width="8%" align="right"><input class="parent_text" type="text" /></td>
                          <td width="1%" align="center" class="action_btns_td"><ul class="action_btns">
                              <li> <a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i> </a> </li>
                            </ul></td>
                        </tr>
                        <tr>
                          <td width="5%"><input class="parent_text" type="text" /></td>
                          <td width="8%"><input class="parent_text" type="text" /></td>
                          <td width="8%"><input class="parent_text" type="text" /></td>
                          <td width="8%"><input class="parent_text" type="text" /></td>
                          <td width="8%" align="right"><input class="parent_text" type="text" /></td>
                          <td width="1%" align="center" class="action_btns_td"><ul class="action_btns">
                              <li> <a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i> </a> </li>
                            </ul></td>
                        </tr>
                        <tr>
                          <td width="5%"><input class="parent_text" type="text" /></td>
                          <td width="8%"><input class="parent_text" type="text" /></td>
                          <td width="8%"><input class="parent_text" type="text" /></td>
                          <td width="8%"><input class="parent_text" type="text" /></td>
                          <td width="8%" align="right"><input class="parent_text" type="text" /></td>
                          <td width="1%" align="center" class="action_btns_td"><ul class="action_btns">
                              <li> <a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i> </a> </li>
                            </ul></td>
                        </tr>
                      </tbody>
                      <tbody>
                        <tr>
                          <td width="5%" colspan="3"></td>
                          <td width="10%" class="rate_pri" align="right">Total</td>
                          <td width="10%" align="right"><input class="parent_text" type="text" /></td>
                          <td>&nbsp;</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!--Receipt Details--> 
        
      </div>
    </div>
  </div>
</div>
<div class="col-lg-12 savebtn_area">
  <ul>
    <li class="dropdown save_btn float_r"><a href="javascript:void(0);" data-toggle="tooltip" class="ripple" title="Submit">Submit</a>
    <li class="cancel_btn float_r"><a href="javascript:void(0);" data-toggle="tooltip" class="ripple" title="Go back!">Back</a></li>
  </ul>
</div>
<!--content--> 
<!--table Add lines start--> 
<script>
$(".mainTr").click(function(e){
	e.preventDefault();
	if(!$(this).closest("tr").next(".subTr").is(":visible")){
		$(this).closest("tr").next(".subTr").show();
		$(this).closest("tr").next(".subTr").find(".subDiv").slideDown("slow");	
		$(this).find("i").addClass("tform");
	}
		else{
		$(this).closest("tr").next(".subTr").find(".subDiv").slideUp("slow");
		$(this).closest("tr").next(".subTr").slideUp("slow");
		$(this).find("i").removeClass("tform");
	}
})
</script> 
<!--table Add lines end--> 
<!--datepicker--> 
<script type="text/javascript">
$(function(){
	$('.ripple').materialripple();
	var dp1 = $('.date_picker').datepicker().on('changeDate', function() {
		$('.datepicker').hide();
	}).data('datepicker');
	$('.toolbar_ddown ul').slimScroll({
		height : '100%',
		alwaysVisible: false,
		railVisible: true,
		railColor: '#cececd',
		railOpacity: 1
	});
});

</script> 
<!--datepicker--> 

