<!--STYLE-->
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/workorder.css';?>"/>

<!--content-->
<div class="content_wrapper padlr0">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12"> 
        <!--<h1>Qualifier</h1>--> 
      </div>
      
      <!--table start-->
      
      <div class="col-lg-12 col-lg-offset-0  top_ct">
        <div class="table-responsive topsp animated-panel zoomIn" style="animation-delay: 0.2s;">
          <table class="table" style=" margin-bottom:0px;">
            <thead>
              <tr>
                <th>&nbsp;</th>
                <th>Ref no</th>
                <th>Description</th>
                <th>Expression</th>
                <th>Percentage (%)</th>
                <th>Amount</th>
                <th>&nbsp;</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td width="1%"><label>
                  <input type="checkbox" name="checkbox" class="ios_checkbox"/>
                  <div class="ios_switch"><span></span></div>
                  </label></td>
                <td width="5%">HZQW568</td>
                <td width="13%" >Corlate is a free responsive business html template</td>
                <td width="10%"><input class="parent_text" type="text" /></td>
                <td width="1%"><input class="parent_text" type="text" /></td>
                <td width="10%"><input class="parent_text" type="text" /></td>
                <td width="1%" class="action_btns_td"><ul class="action_btns">
                    <li> <a href="#" class="mainTr"> <span data-original-title="Add lines" data-placement="left" data-toggle="tooltip"><i class="fa fa-chevron-circle-down"></i></span></a> </li>
                  </ul></td>
              </tr>
              
              <!--expand table-->

              <tr style="display:none;" class="subTr">
                <td colspan="9" style="padding:0px !important; "><div class="subDiv" style="display:none;">
                    <div class="col-lg-12">
                      <div class="table-responsive topsp">
                        <table class="table" style="margin-bottom:0px;">
                          <thead>
                            <tr>
                              <th>&nbsp;</th>
                              <th>Base Amount</th>
                              <th>Taxable</th>
                              <th>Tax</th>
                              <th>Cess</th>
                              <th>Educess</th>
                              <th>Hdcess</th>
                              <th>Net</th>
                            </tr>
                          </thead>
                          <tbody>
                            <tr>
                              <td width="8%">Percentage (%)</td>
                              <td width="3%">&nbsp;</td>
                              <td width="8%"><input class="parent_text" type="text" /></td>
                              <td width="8%"><input class="parent_text"/></td>
                              <td width="8%"><input class="parent_text" type="text" /></td>
                              <td width="8%"><input class="parent_text" type="text" /></td>
                              <td width="10%"><input class="parent_text" type="text" /></td>
                              <td width="10%"><input class="parent_text" type="text" /></td>
                            </tr>
                            <tr>
                              <td width="8%">Amount</td>
                              <td width="3%"><input class="parent_text" type="text" /></td>
                              <td width="8%"><input class="parent_text" type="text" /></td>
                              <td width="8%"><input class="parent_text"/></td>
                              <td width="8%"><input class="parent_text" type="text" /></td>
                              <td width="8%"><input class="parent_text" type="text" /></td>
                              <td width="10%"><input class="parent_text" type="text" /></td>
                              <td width="10%"><input class="parent_text" type="text" /></td>
                            </tr>
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div></td>
              </tr>
              <!--expand end-->
            </tbody>
          </table>
        </div>
      </div>
      <!--table end-->
    </div>
  </div>
</div>
<div class="col-lg-12 savebtn_area">
  <ul>
    <li class="dropdown save_btn float_r"><a href="javascript:void(0);" data-toggle="tooltip" class="ripple" title="Go to continue !">Continue</a>
    <li class="cancel_btn float_r"><a href="javascript:void(0);" data-toggle="tooltip" class="ripple" title="Go back!">Back</a></li>
  </ul>
</div>
<!--content--> 

<script>
$(".mainTr").click(function(e){
	e.preventDefault();
	if(!$(this).closest("tr").next(".subTr").is(":visible")){
		$(this).closest("tr").next(".subTr").show();
		$(this).closest("tr").next(".subTr").find(".subDiv").slideDown("slow");	
		$(this).find("i").addClass("tform");
	}
		else{
		$(this).closest("tr").next(".subTr").find(".subDiv").slideUp("slow");
		$(this).closest("tr").next(".subTr").slideUp("slow");
		$(this).find("i").removeClass("tform");
	}
})
</script> 
<!--table expand end--> 

<!--datepicker--> 

