<!--STYLE-->
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/workorder.css';?>"/>
<style>
.form-control {
	box-shadow:none !important
}
</style>

<div class="content_wrapper padlr0">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="text-center">Receipt</h1>
      </div>
      <!--form start-->
      <div class="col-lg-12 top_ct" >
          <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2  prt-next">
                  <div class="col-sm-6 col-sm-offset-3 top-next">
                    <form class="form-horizontal">
                      <div class="row">
                        <div class="form-group">
                          <div class="col-lg-12">
                            <input type="text" name="LeadDate" id="date" class="form-control lbl_move" label="Project Name"/>
                          </div>
                        </div>
                        <div class="form-group">
                          <div class="col-lg-12">
                            <select name="named[]" id="lead_type" class="form-control selectpicker show-tick" data-size="5" title="Order No">
                              <option>Order No</option>
                              <option>Order No</option>
                              <option>Order No</option>
                            </select>
                          </div>
                        </div>
                        <div class="form-group">
                          <div class="col-lg-12">
                            <select name="named[]" id="lead_type" class="form-control selectpicker show-tick" data-size="5" title="Bill No">
                              <option>Receipt Against</option>
                              <option>Receipt Against</option>
                              <option>Receipt Against</option>
                            </select>
                          </div>
                        </div>
                        <div class="form-group">
                          <div class="col-lg-12">
                            <input type="text" name="LeadDate" id="date" class="form-control lbl_move" label="Payment Mode"/>
                          </div>
                        </div>
                        <div class="form-group">
                          <div class="col-lg-12">
                            <input type="text" name="LeadDate" id="date" class="form-control lbl_move" label="Trasaction No"/>
                          </div>
                        </div>
                        <div class="form-group">
                          <div class="col-lg-12"> <span class="date_icon"><i class="fa fa-calendar"></i></span>
                            <input type="text" name="lead_date" id="lead_date" class="form-control date_picker lbl_move" label="Trasaction Date" />
                          </div>
                        </div>
                        <div class="form-group">
                          <div class="col-lg-12">
                            <input type="text" name="LeadDate" id="date" class="form-control lbl_move" label="Amount"/>
                          </div>
                        </div>
                      </div>
                    </form>
                    <div class="next-bt"><a href="#carousel-example-generic" data-slide="next" class="cbtn">Next <i class="fa fa-chevron-circle-right"></i></a></div>
                  </div>
                </div>
      </div>
    </div>
  </div>
</div>

<!--datepicker--> 
<script type="text/javascript">
$(function(){
	$('.ripple').materialripple();
	var dp1 = $('.date_picker').datepicker().on('changeDate', function() {
		$('.datepicker').hide();
	}).data('datepicker');
	$('.toolbar_ddown ul').slimScroll({
		height : '100%',
		alwaysVisible: false,
		railVisible: true,
		railColor: '#cececd',
		railOpacity: 1
	});
});



</script> 
<!--datepicker--> 

