<!--STYLE-->
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/workorder.css';?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/wpm.css';?>"/>
<!--STYLE-->
<style>
.butclr {
	margin-top:0px !important;
	margin-left:5px;
}
</style>
<!--content-->
<div class="content_wrapper padlr0">
  <div class="container-fluid">
    <div class="col-lg-12">
      <h1 class="col-lg-6">Bill Format</h1>    <div class="col-lg-6"> <span class="butclr btn-file"> <i class="fa fa-folder-open sap"></i>
        <p class="sam-up" >Format Copy From</p>
        </span> <span class="butclr btn-file"> <i class="glyphicon glyphicon-remove sap"></i>
        <p class="sam-up" >Clear All</p>
        </span> </div>
    </div>
    <div class="col-lg-12 clear animated fadeInUp">
  
      <div class="table-responsive topsp">
        <table class="table" style=" margin-bottom:0px;">
          <thead>
            <tr>
              <th>&nbsp;</th>
              <th>Sl No</th>
              <th>Description</th>
              <th>Type Name</th>
              <th>Formula</th>
              <th>&nbsp;</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td width="3%"><label>R10</label></td>
              <td width="5%"><input class="parent_text" type="text" /></td>
              <td width="12%"><div class="on-focus clearfix" style="position:relative;">
                  <textarea class="parent_texts"></textarea>
                  <div class="tool-tip slideIn ch-b">
                    <div class="bin">
                      <ul>
                        <li> 
                          <span class="checked-b">
                              <label>
                                 <input type="checkbox"/>
                                   <span>Bold</span> 
                                    </label>
                             </span> 
                            </li>
                        <li> 
                           <span class="checked-b">
                            <label>
                            <input type="checkbox" />
                               <span>Italic</span> 
                               </label>
                             </span> 
                          </li>
                        <li> 
                           <span class="checked-b">
                             <label>
                            <input type="checkbox"/>
                            <span>Underline</span> 
                            </label>
                          </span> 
                          </li>
                      </ul>
                    </div>
                  </div>
                </div></td>
              <td width="10%"><input class="parent_text" type="text" /></td>
              <td width="5%"><input class="parent_text" type="text" /></td>
              <td width="1%">
              <ul class="action_btns">
               <li>
                  <a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete" ></i></a>
                   </li>
                </ul>
                </td>
            </tr>
            <tr>
              <td width="3%"><label>R10</label></td>
              <td width="5%"><input class="parent_text" type="text" /></td>
              <td width="12%"><div class="on-focus clearfix" style="position:relative;">
                  <textarea class="parent_texts"></textarea>
                  <div class="tool-tip slideIn ch-b">
                    <div class="bin">
                      <ul>
                        <li> 
                          <span class="checked-b">
                              <label>
                                 <input type="checkbox"/>
                                   <span>Bold</span> 
                                    </label>
                             </span> 
                            </li>
                        <li> 
                           <span class="checked-b">
                            <label>
                            <input type="checkbox" />
                               <span>Italic</span> 
                               </label>
                             </span> 
                          </li>
                        <li> 
                           <span class="checked-b">
                             <label>
                            <input type="checkbox"/>
                            <span>Underline</span> 
                            </label>
                          </span> 
                          </li>
                      </ul>
                    </div>
                  </div>
                </div></td>
              <td width="10%"><input class="parent_text" type="text" /></td>
              <td width="5%"><input class="parent_text" type="text" /></td>
              <td width="1%">
              <ul class="action_btns">
               <li>
                  <a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete" ></i></a>
                   </li>
                </ul>
                </td>
            </tr>
            <tr>
              <td width="3%"><label>R10</label></td>
              <td width="5%"><input class="parent_text" type="text" /></td>
              <td width="12%"><div class="on-focus clearfix" style="position:relative;">
                  <textarea class="parent_texts"></textarea>
                  <div class="tool-tip slideIn ch-b">
                    <div class="bin">
                      <ul>
                        <li> 
                          <span class="checked-b">
                              <label>
                                 <input type="checkbox"/>
                                   <span>Bold</span> 
                                    </label>
                             </span> 
                            </li>
                        <li> 
                           <span class="checked-b">
                            <label>
                            <input type="checkbox" />
                               <span>Italic</span> 
                               </label>
                             </span> 
                          </li>
                        <li> 
                           <span class="checked-b">
                             <label>
                            <input type="checkbox"/>
                            <span>Underline</span> 
                            </label>
                          </span> 
                          </li>
                      </ul>
                    </div>
                  </div>
                </div></td>
              <td width="10%"><input class="parent_text" type="text" /></td>
              <td width="5%"><input class="parent_text" type="text" /></td>
              <td width="1%">
              <ul class="action_btns">
               <li>
                  <a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete" ></i></a>
                   </li>
                </ul>
                </td>
            </tr>
            <tr>
              <td width="3%"><label>R10</label></td>
              <td width="5%"><input class="parent_text" type="text" /></td>
              <td width="12%"><div class="on-focus clearfix" style="position:relative;">
                  <textarea class="parent_texts"></textarea>
                  <div class="tool-tip slideIn ch-b">
                    <div class="bin">
                      <ul>
                        <li> 
                          <span class="checked-b">
                              <label>
                                 <input type="checkbox"/>
                                   <span>Bold</span> 
                                    </label>
                             </span> 
                            </li>
                        <li> 
                           <span class="checked-b">
                            <label>
                            <input type="checkbox" />
                               <span>Italic</span> 
                               </label>
                             </span> 
                          </li>
                        <li> 
                           <span class="checked-b">
                             <label>
                            <input type="checkbox"/>
                            <span>Underline</span> 
                            </label>
                          </span> 
                          </li>
                      </ul>
                    </div>
                  </div>
                </div></td>
              <td width="10%"><input class="parent_text" type="text" /></td>
              <td width="5%"><input class="parent_text" type="text" /></td>
              <td width="1%">
              <ul class="action_btns">
               <li>
                  <a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete" ></i></a>
                   </li>
                </ul>
                </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<div class="col-lg-12 savebtn_area">
  <ul>
    <li class="dropdown save_btn float_r"><a href="javascript:void(0);" data-toggle="tooltip" class="ripple" title="Submit">Submit</a>
    <li class="cancel_btn float_r"><a href="javascript:void(0);" data-toggle="tooltip" class="ripple" title="Go back!">Back</a></li>
  </ul>
</div>
