<!--STYLE-->
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/workorder.css';?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/wpm.css';?>"/>
<!--STYLE-->
<style>
.panel {
	border-radius:0px !important;
}
.panel-info {
	border:none;
	border-top:none;
}
.fixed-full-screen.fullscreen {
	z-index: 9999;
	background:#EFEFEF;
	width: 100%;
	height: 100%;
	position:fixed;
	top:-5px;
	left: 0;  -webkit-transition: all 0.3s ease;
  -moz-transition: all 0.3s ease;
  -o-transition: all 0.3s ease;
  -ms-transition: all 0.3s ease;
  transition: all 0.3s ease;
}
.fixed-full-screen a.expanded {
	position:absolute;
	right:50px;
	background:#DDE7F1;
	padding:5px;
	font-size:14px;
	color:#317EB0;
	top:-12px;
}
/* Pie Chart */
/*.progress-pie-chart {
width:200px;
height: 200px;
border-radius: 50%;
background-color: #E5E5E5;
position: relative;
}
.progress-pie-chart.gt-50 {
background-color: #81CE97;
}

.ppc-progress {
content: "";
position: absolute;
border-radius: 50%;
left: calc(50% - 100px);
top: calc(50% - 100px);
width: 200px;
height: 200px;
clip: rect(0, 200px, 200px, 100px);
}
.ppc-progress .ppc-progress-fill {
content: "";
position: absolute;
border-radius: 50%;
left: calc(50% - 100px);
top: calc(50% - 100px);
width: 200px;
height: 200px;
clip: rect(0, 100px, 200px, 0);
background: #81CE97;
transform: rotate(60deg);
}
.gt-50 .ppc-progress {
clip: rect(0, 100px, 200px, 0);
}
.gt-50 .ppc-progress .ppc-progress-fill {
clip: rect(0, 200px, 200px, 100px);
background: #E5E5E5;
}

.ppc-percents {
content: "";
position: absolute;
border-radius: 50%;
left: calc(50% - 173.91304px/2);
top: calc(50% - 173.91304px/2);
width: 173.91304px;
height: 173.91304px;
background: #fff;
text-align: center;
display: table;
}
.ppc-percents span {
display: block;
font-size: 2.6em;
font-weight: bold;
color: #81CE97;
}

.pcc-percents-wrapper {
display: table-cell;
vertical-align: middle;
}

.progress-pie-chart {
margin: 50px auto 0;
}*/
</style>

<!--content-->
<div class="content_wrapper padlr0">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h1>Workorder</h1>
      </div>
      <div class="col-lg-12">
        <div class="col-lg-4">
          <div class="panel-box">
            <ul>
              <li>
                <label>Cost Centre Name</label>
                <span>Bill of Quantities</span> </li>
              <li>
                <label>Contractor Name</label>
                <span>Udhaya</span> </li>
              <li>
                <label>Work Type</label>
                <span>Bill of Quantities</span> </li>
            </ul>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="panel-box box2th">
            <ul>
              <li>
                <label>Work order Date</label>
                <span>
                <input type="text" placeholder="10/06/2016" class="date_picker" />
                </span> </li>
              <li>
                <label>Ref Date</label>
                <span>
                <input type="text" placeholder="10/06/2016" class="date_picker" />
                </span> </li>
              <li>
                <label>From Date</label>
                <span>
                <input type="text" placeholder="10/06/2016" class="date_picker" />
                </span> </li>
              <li>
                <label>To Date</label>
                <span>
                <input type="text" placeholder="10/06/2016" class="date_picker" />
                </span> </li>
            </ul>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="panel-box box3th">
            <ul>
              <li>
                <label>Work Order No </label>
                <span>
                <input type="text" placeholder="ASD2546"/>
                </span> </li>
              <li>
                <label>CC Work Order No</label>
                <span>
                <input type="text" placeholder="FFH8745"/>
                </span> </li>
              <li>
                <label>Comp Work Order No</label>
                <span>
                <input type="text" placeholder="Bill of Quantities"/>
                </span> </li>
              <li>
                <label>Ref No</label>
                <span>
                <input type="text" placeholder="JH445552"/>
                </span> </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="clearfix"></div>
      <div class="col-lg-12 clear top-20 fixed-full-screen"> <a href="#" class="expanded"><i class="fa fa-arrows-alt"></i> Expand</a>
        <div id="accordion" class="panel-group"> 
          <!-------------------------------Bill of Quantities------------------------------->
          <div class="panel panel-info">
            <div data-target="#collapseOne" data-parent="#accordion" data-toggle="collapse" class="panel-heading collapsed panel_heads" id="panelheading-1">
              <h4 class="panel-title accordion-toggle defa_panels">Bill of Quantity</h4>
            </div>
            <div class="panel-collapse collapse" id="collapseOne" style="height: 0px;">
              <div class="panel-body bgcolr">
                <div class="col-lg-12">
                  <div class="table-responsive top-30">
                    <table class="table" style=" margin-bottom:0px;">
                      <thead>
                        <tr>
                          <th>Code</th>
                          <th>Description</th>
                          <th>Unit</th>
                          <th>Qty</th>
                          <th>Rate</th>
                          <th>Amount</th>
                          <th>&nbsp; </th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td width="8%"><input class="parent_text" type="text"/></td>
                          <td width="12%"><textarea class="parent_texts"></textarea></td>
                          <td width="5%" ><input class="parent_text" type="text"/></td>
                          <td width="5%"><input class="parent_text" type="text" /></td>
                          <td width="8%"><input class="parent_text" type="text" /></td>
                          <td width="8%"><input class="parent_text" type="text" /></td>
                          <td width="4%" align="center" class="action_btns_td"><ul class="action_btns">
                              <li> <a href="#" class="mainTr"> <i class="fa fa-chevron-circle-down" data-toggle="tooltip" data-placement="left" data-original-title="Add lines" ></i></a> </li>
                              <li> <a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i> </a> </li>
                            </ul></td>
                        </tr>
                        
                        <!--Add lines table-->
                        <tr style="display:none;" class="subTr">
                          <td colspan="9" style="padding:0px !important; "><div class="subDiv" style="display:none;">
                              <div class="col-lg-12 col-lg-offset-0 rdbt" style="margin-top:5px;"> </div>
                              <div class="col-lg-12">
                                <div class="table-responsive topsp">
                                  <table class="table" style="margin-bottom:0px;">
                                    <thead>
                                      <tr>
                                        <th>Agt No</th>
                                        <th>Specification</th>
                                        <th>WBS Name</th>
                                        <th>Unit</th>
                                        <th>Qty</th>
                                        <th>&nbsp;</th>
                                      </tr>
                                    </thead>
                                    <tbody>
                                      <tr>
                                        <td width="10%"><input class="parent_text border-none" type="text" /></td>
                                        <td width="13%"><textarea class="parent_texts border-none"></textarea></td>
                                        <td width="10%"><input class="parent_text border-none" type="text" /></td>
                                        <td width="5%"><input class="parent_text border-none" type="text" /></td>
                                        <td width="5%"><input class="parent_text" type="text" /></td>
                                        <td width="4%" align="center" class="action_btns_td"><ul class="action_btns">
                                            <li> <a href="#" class="mainTr"> <i class="fa fa-chevron-circle-down" data-toggle="tooltip" data-placement="left" data-original-title="Add lines" ></i></a> </li>
                                            <li> <a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i> </a> </li>
                                          </ul></td>
                                      </tr>
                                      <!--Add lines table-->
                                      <tr style="display:none;" class="subTr">
                                        <td colspan="9" style="padding:0px !important; "><div class="subDiv" style="display:none;">
                                            <div class="col-lg-12 col-lg-offset-0 rdbt" style="margin-top:5px;"> </div>
                                            <div class="col-lg-12">
                                              <div class="table-responsive topsp">
                                                <table class="table" style="margin-bottom:0px;">
                                                  <thead>
                                                    <tr>
                                                      <th>Req No</th>
                                                      <th>Req Qty</th>
                                                      <th>Order Qty</th>
                                                      <th>Bal Qty</th>
                                                      <th>Cur Qty</th>
                                                    </tr>
                                                  </thead>
                                                  <tbody>
                                                    <tr>
                                                      <td width="10%"><input class="parent_text" type="text" /></td>
                                                      <td width="10%"><input class="parent_text" type="text" /></td>
                                                      <td width="10%"><input class="parent_text" type="text" /></td>
                                                      <td width="10%"><input class="parent_text" type="text" /></td>
                                                      <td width="10%"><input class="parent_text" type="text" /></td>
                                                    </tr>
                                                  </tbody>
                                                  <tbody>
                                                    <tr>
                                                      <td colspan="5"><ul class="total-qty">
                                                          <li>
                                                            <label>Estimate Qty : </label>
                                                            <span>5887444</span> </li>
                                                          <li>
                                                            <label>Workorder Qty : </label>
                                                            <span>5887444</span> </li>
                                                          <li>
                                                            <label>Total Billed Qty : </label>
                                                            <span>5887444</span> </li>
                                                        </ul></td>
                                                    </tr>
                                                  </tbody>
                                                </table>
                                              </div>
                                            </div>
                                          </div></td>
                                      </tr>
                                      <!--Add lines table-->
                                      
                                    </tbody>
                                  </table>
                                </div>
                              </div>
                            </div></td>
                        </tr>
                        <!--Add lines end-->
                      </tbody>
                      <tbody>
                        <tr>
                          <td colspan="4">&nbsp;</td>
                          <td align="right" class="rate_pri">Total Amount</td>
                          <td width="10%" ><input class="parent_text" type="text"/></td>
                          <td>&nbsp;</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                  <div class="cont_bt col-lg-5 col-lg-offset-7 col-md-9 col-md-offset-3 col-sm-7 col-sm-offset-5 col-xs-7 col-xs-offset-5">
                    <ul>
                      <li><a href="javascript:nextAccordian(2)">Continue &nbsp;<i class="fa fa-chevron-circle-right"></i></a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-------------------------------Bill of Quantities end-------------------------------> 
          <!-------------------------------Terms and Condition------------------------------->
          <div class="panel panel-info">
            <div data-target="#collapseTwo" data-parent="#accordion" data-toggle="collapse" class="panel-heading collapsed panel_heads" id="panelheading-2">
              <h4 class="panel-title accordion-toggle defa_panels">Terms and Condition</h4>
            </div>
            <div class="panel-collapse collapse" id="collapseTwo" style="height: 0px;">
              <div class="panel-body bgcolr"> 
                <!----Terms and Condition detalis ---->
                <div class="col-lg-12">
                  <div class="cont_bt col-lg-5 col-lg-offset-7 col-md-9 col-md-offset-3 col-sm-7 col-sm-offset-5 col-xs-7 col-xs-offset-5">
                    <ul>
                      <li><a href="javascript:nextAccordian(3)">Continue &nbsp;<i class="fa fa-chevron-circle-right"></i></a></li>
                    </ul>
                  </div>
                </div>
                
                <!----Terms and Condition detalis----> 
              </div>
            </div>
          </div>
          
          <!-------------------------------Terms and Condition-------------------------------> 
          
        </div>
      </div>
      <div class="clearfix"></div>
      <!--table end--> 
      <!--<div class="bar_container">
<div id="main_container">
<div id="pbar" class="progress-pie-chart" data-percent="0">
<div class="ppc-progress">
<div class="ppc-progress-fill"></div>
</div>
<div class="ppc-percents">
<div class="pcc-percents-wrapper">
<span>%</span>
</div>
</div>
</div>

<progress style="display: none" id="progress_bar" value="0" max="100"></progress>
</div>
</div>--> 
    </div>
  </div>
</div>
<div class="col-lg-12 savebtn_area">
  <ul>
    <li class="dropdown save_btn float_r"><a href="javascript:void(0);" data-toggle="tooltip" class="ripple" title="Submit">Submit</a>
    <li class="cancel_btn float_r"><a href="javascript:void(0);" data-toggle="tooltip" class="ripple" title="Go back!">Back</a></li>
  </ul>
</div>
<!--content--> 
<!--table Add lines start--> 
<script>
$(".mainTr").click(function(e){
	e.preventDefault();
	if(!$(this).closest("tr").next(".subTr").is(":visible")){
		$(this).closest("tr").next(".subTr").show();
		$(this).closest("tr").next(".subTr").find(".subDiv").slideDown("slow");	
		$(this).find("i").addClass("tform");
	}
		else{
		$(this).closest("tr").next(".subTr").find(".subDiv").slideUp("slow");
		$(this).closest("tr").next(".subTr").slideUp("slow");
		$(this).find("i").removeClass("tform");
	}
})
</script> 
<!--table Add lines end--> 
<!--datepicker--> 
<script type="text/javascript">
$(function(){
	$('.ripple').materialripple();
	var dp1 = $('.date_picker').datepicker().on('changeDate', function() {
		$('.datepicker').hide();
	}).data('datepicker');
	$('.toolbar_ddown ul').slimScroll({
		height : '100%',
		alwaysVisible: false,
		railVisible: true,
		railColor: '#cececd',
		railOpacity: 1
	});
});

</script> 
<!--datepicker--> 
<script>
$(function () 
   {nextAccordian(1);
});
    function nextAccordian(id) {
	$('#panelheading-' + id).trigger('click');
}
$('input[name="textStyle"]').change(function(){
    if ($(this).val() == 'bold'){
        if ($(this).is(':checked')) $('input[name="Textbold"]').css('font-weight', 'bold');
        else $('input[name="Textbold"]').css('font-weight', 'normal');
    }
    else if ($(this).val() == 'italic'){
        if ($(this).is(':checked')) $('input[name="Textbold"]').css('font-style', 'italic');
        else $('input[name="Textbold"]').css('font-style', 'normal');
    }
    else if ($(this).val() == 'underline'){
        if ($(this).is(':checked')) $('input[name="Textbold"]').css('text-decoration', 'underline');
        else $('input[name="Textbold"]').css('text-decoration', 'none');
    }
});


</script> 
<script>
$(window).scroll(function(){
  var sticky = $('.sticky'),
      scroll = $(window).scrollTop();

  if (scroll >= 100) sticky.addClass('topfixingheade');
  else sticky.removeClass('topfixingheade');
});
$('.expanded').click(function(e){
    $('.fixed-full-screen').toggleClass('fullscreen'); 
});
</script> 
<!--<script>
$(document).ready(function() {
var progressbar = $('#progress_bar');
max = progressbar.attr('max');
time = (1000 / max) * 5;
value = progressbar.val();

var loading = function() {
value += 1;
addValue = progressbar.val(value);

$('.progress-value').html(value + '%');
var $ppc = $('.progress-pie-chart'),
deg = 360 * value / 100;
if (value > 50) {
$ppc.addClass('gt-50');
}

$('.ppc-progress-fill').css('transform', 'rotate(' + deg + 'deg)');
$('.ppc-percents span').html(value + '%');

if (value == max) {
clearInterval(animate);
}
};

var animate = setInterval(function() {
loading();
}, time);
});
</script>--> 
<script>
$(document).ready(function(){
	var w = $(window).width();
	var h = $(window).height();
	var pl = $('.player');
	pl.css('top', h/2);
	//FULL SCREEN 
	var c = 1;
	$('.fa-expand').click(function() {
		c++;
		
		$(this).toggleClass('fa-compress');	
		
		//odd -> Full Screen 
		if(c%2==0){
			
			pl.animate({width:w}, 300, function(){
				$(this).animate({height:h}, 300	);
				pl.addClass('active');				
			});		
		}
		//even -> Exit Full Screen 
		if (c%2!=0){
			
			pl.animate({height:'480'}, 300, function(){
				$(this).animate({width:'850'}, 300);
				pl.removeClass('active');								
			});
		}
	});
	//PLAY BTN
	$('.fa-play').click(function(){
		$(this).toggleClass('fa-pause');
	});
});
</script> 
