<!--STYLE-->
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/workorder.css';?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/wpm.css';?>"/>
<!--STYLE-->

<!--content-->
<div class="content_wrapper padlr0">
  <div class="container-fluid">
    <div class="col-lg-12">
      <h1 class="text-center">Welcome To Labour Strength</h1>
    </div>
    <div class="col-lg-12 clear">
      <div class="row">
        <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 cnt_slider back-img">
          <div class="col-lg-4 col-lg-offset-8 col-md-4 col-md-offset-8 col-sm-4 col-sm-offset-8">
            <div class="form-group col-lg-12"> <span class="date_icon wmp-date"><i class="fa fa-calendar"></i></span>
              <input type="text" name="lead_date" id="lead_date" class="date_picker parnt-text" placeholder="dd/mm/yyyy" />
            </div>
          </div>
          <div class="clearfix"></div>
          <div id="carousel-example-generic" class="carousel slide" data-ride="carousel"> 
            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
              <div class="item active"> 
                <!--<h2 class="text-center">Select the Project to make Labour Strength?</h2>-->
                <div class="col-lg-9 col-lg-offset-3 col-md-9 col-md-offset-3 col-sm-9 col-sm-offset-3 col-xs-12  top-sl-10">
                  <div class="col-lg-8 col-lg-offset-0 col-md-8 col-md-offset-0 col-sm-8 col-sm-offset-0 col-xs-12 form-group">
                    <select class="form-control single_dropdown lbl_move" label="Select Project" style="width:100%;">
                      <option></option>
                      <option>Block A</option>
                      <option>Formula-based Manufacturers</option>
                      <option>Practical ERP </option>
                      <option>Evolving ERP Strategy</option>
                      <option>Maximum usability</option>
                      <option>Practical Guide454</option>
                      <option>Formulas4545</option>
                      <option>Prac ERP4545 </option>
                      <option>Evoltegytrt445</option>
                      <option>Mait45454y</option>
                    </select>
                  </div>
                </div>
              </div>
              <div class="item min_h550">
                <div class="col-lg-9 col-lg-offset-3 col-md-9 col-md-offset-3 col-sm-9 col-sm-offset-3 col-xs-12  top-sl-10">
                  <div class="col-lg-8 col-lg-offset-0 col-md-8 col-md-offset-0 col-sm-8 col-sm-offset-0 col-xs-12 form-group">
                    <input type="text" class="form-control lbl_move" label="Project Name">
                  </div>
                  <div class="col-lg-8 form-group">
                    <label class="radio-sele">Which type of form you choose to Make the Entry?</label>
                    <div class="radio_check">
                      <p style="padding-top:10px;">
                        <input type="radio" name="uds_carper" id="uds" value="uds" checked="checked">
                        <label for="uds">Direct Entry</label>
                      </p>
                      <p style="padding-top:10px;">
                        <input type="radio" name="uds_carper" id="carper" value="carper">
                        <label for="carper">From Excel Import</label>
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="item">
                <div class="col-lg-9 col-lg-offset-3 col-md-9 col-md-offset-3 col-sm-9 col-sm-offset-3 col-xs-12  top-sl-10">
                  <div class="col-lg-8 col-lg-offset-0 col-md-8 col-md-offset-0 col-sm-8 col-sm-offset-0 col-xs-12 form-group">
                    <input type="text" class="form-control lbl_move" label="Project Name">
                  </div>
                  <div class="col-lg-8 form-group">
                    <label class="radio-sele">Customize what you want</label>
                    <div class="radio_check">
                      <p style="text-align:left;" class="padd-radio">
                        <input type="checkbox" name="uds_carper" id="type" value="type" checked="checked">
                        <label for="type">Yes,I like to make with Work Break Done Strucutre</label>
                      </p>
                      <p style="text-align:left;">
                        <input type="checkbox" name="uds_carper" id="group" value="group">
                        <label for="group">Yes,I like to make with Individual Labour Names</label>
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <!---fileupload--->
              <div class="item min_h550">
                <div class="col-lg-9 col-lg-offset-3 col-md-9 col-md-offset-3 col-sm-9 col-sm-offset-3 col-xs-12  top-sl-10">
                  <div class="col-lg-8 col-lg-offset-0 col-md-8 col-md-offset-0 col-sm-8 col-sm-offset-0 col-xs-12 form-group">
                    <input type="text" class="form-control lbl_move" label="Project Name">
                  </div>
                  <div class="col-lg-4 col-lg-offset-3 col-md-4 col-md-offset-3 col-sm-4 col-sm-offset-2 col-xs-12 form-group"> <span class="lab-str btn-file-str"> <i class="fa fa-folder-open"></i>Upload File
                    <input type="file"/>
                    </span> </div>
                </div>
              </div>
              <!---fileupload--->
              <div class="item min_h550">
                <div class="col-lg-9 col-lg-offset-3 col-md-9 col-md-offset-3 col-sm-9 col-sm-offset-3 col-xs-12  top-sl-10">
                  <div class="col-lg-8 col-lg-offset-0 col-md-8 col-md-offset-0 col-sm-8 col-sm-offset-0 col-xs-12 form-group">
                    <input type="text" class="form-control lbl_move" label="Project Name">
                  </div>
                </div>
                <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-12 form-group">
                  <div class="table-responsive topsp">
                    <table class="table" style=" margin-bottom:0px;">
                      <thead>
                        <tr>
                          <th>Excel Sheet Header</th>
                          <th>Assign To</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td width="8%">Label</td>
                          <td width="13%"><input class="parent_text" type="text" placeholder="Enter resource group" /></td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
              
              <!-- Indicators --> 
              <!--<ol class="carousel-indicators">
                                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="3"></li>
                            </ol>--> 
              <!-- Controls -->
              <ul class="prev_next wpm-next col-lg-7 col-lg-offset-5 col-md-7 col-md-offset-5 col-sm-7 col-sm-offset-5 col-xs-7 col-xs-offset-3">
                <li> <a href="#carousel-example-generic" data-slide="prev"><span><i class="fa fa-arrow-left"></i></span> Back </a> </li>
                <li> <a href="#carousel-example-generic" role="button" data-slide="next">Next <span><i class="fa fa-arrow-right"></i></span> </a> </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="col-lg-12 savebtn_area">
  <ul>
    <li class="dropdown save_btn float_r"><a href="javascript:void(0);" data-toggle="tooltip" class="ripple" title="Submit">Submit</a>
    <li class="cancel_btn float_r"><a href="javascript:void(0);" data-toggle="tooltip" class="ripple" title="Go back!">Back</a></li>
  </ul>
</div>
<!--content--> 
<!--datepicker--> 
<script type="text/javascript">
$(function(){
	$('.ripple').materialripple();
	var dp1 = $('.date_picker').datepicker().on('changeDate', function() {
		$('.datepicker').hide();
	}).data('datepicker');
	$('.toolbar_ddown ul').slimScroll({
		height : '100%',
		alwaysVisible: false,
		railVisible: true,
		railColor: '#cececd',
		railOpacity: 1
	});
});

</script> 
<!--datepicker--> 
<script type="text/javascript">
$('.cnt_slider .carousel').carousel({
 interval: false
})
</script> 
