<!--STYLE-->
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/workorder.css';?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/wpm.css';?>"/>
<!--STYLE-->
<style>
.butclr 					{margin-top:0px !important;margin-left:5px;}
.slidingDiv1 				{background:#E6E6FA;padding:10px;margin-bottom:20px;border:1px solid #FFF8DC;float:left;width:100%;}
.slidingDiv2 				{background:#E6E6FA;padding:10px;margin-bottom:20px;border:1px solid #FFF8DC;float:left;}
.mar-35 					{margin-top:20px;}
.radio_check p 				{padding: 11px 12px 11px 0px !important;}
.mas-add 					{width:100%;}

</style>
<!--content-->
<div class="content_wrapper padlr0">
  <div class="container-fluid">
    <div class="col-lg-12">
      <h1>Labour Master</h1>
   <div class="import-div">
        <a href="#" class="btn-file" data-toggle="tooltip" data-placement="bottom" data-original-title="Import From Excel"> 
            <i class="fa fa-file-excel-o imp-ex"></i>  <input type="file"/>
        </a>
   
    </div>
       <!--<div class="fixed-action-btn active">
        <a class="btn-floating btn-large">
            <i class="fa fa-paperclip"></i>
        </a>
        <ul>
            <li>
                <a class="btn-floating hide-input-file" data-toggle="tooltip" data-placement="bottom" data-original-title="Import From Excel">
                    <i class="fa fa-file-excel-o"></i>
                    <input type="file" name="myfile" id="myfile" class="input-large" accept=".xls, .xlsx, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" onchange="fileupload(this)">
                </a>
            </li>
            <li>
                <a class="btn-floating" href="/bsf_v1.0/public/uploads/project/sample/iow.xlsx" download data-toggle="tooltip" data-placement="bottom" data-original-title="Download Sample">
                    <i class="fa fa-download"></i>
                </a>
            </li>
        </ul>
    </div>-->
    
    </div>
    <div class="col-lg-12">
      <div class="col-lg-3 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-4 col-sm-offset-0 form-group">
        <div class="radio_check check-p">
          <p>
            <input type="radio" name="uds_carper" id="uds" value="uds" checked="checked">
            <label for="uds">Labour Group</label>
          </p>
          <p>
            <input type="radio" name="uds_carper" id="carper" value="carper">
            <label for="carper">Vendor</label>
          </p>
        </div>
      </div>
      <div class="col-lg-3 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-4 col-sm-offset-0 form-group top-cont320">
        <select class="form-control single_dropdown lbl_move" label="Labour Group" style="width:100%;">
          <option></option>
          <option>Block A</option>
          <option>Formula-based Manufacturers</option>
          <option>Practical ERP </option>
          <option>Evolving ERP Strategy</option>
          <option>Maximum usability</option>
          <option>Practical Guide454</option>
          <option>Formulas4545</option>
          <option>Prac ERP4545 </option>
          <option>Evoltegytrt445</option>
          <option>Mait45454y</option>
        </select>
      </div>
      <div class="col-lg-3 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-4 col-sm-offset-0 form-group"><a title="Add Checklist" href="#" onclick="checklistAddEdit('add'); return false;" class="mas-add show_hide1" style=" display:block;"><i class="fa fa-plus"></i> Add Labour Master</a></div>
      <div class="col-lg-3 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-4 col-sm-offset-0 form-group"><a title="Add Checklist" href="#" onclick="checklistAddEdit('add'); return false;" class="mas-add show_hide2" style=" display:block;"><i class="fa fa-plus"></i> Add Labour Group</a></div>
    </div>
    <div class="clearfix"></div>
    <div class="col-lg-12 slidingDiv1">
      <div class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0 mar-35">
        <div class="col-lg-12 form-group">
          <input type="text"  id="lead_date" class="form-control lbl_move" label="Labour Name" />
        </div>
        <div class="col-lg-12  form-group">
          <input type="text"  id="lead_date" class="form-control lbl_move" label="Id No" />
        </div>
        <div class="col-lg-12 form-group">
          <textarea  class="form-control lbl_move height-50" label="Address"></textarea>
        </div>
        <div class="col-lg-12  form-group">
          <select class="form-control single_dropdown lbl_move" label="City" style="width:100%; height:50px;">
            <option></option>
            <option>Chennai</option>
          </select>
        </div>
        <div class="col-lg-12  form-group">
          <input type="text" class="form-control lbl_move" label="State" />
        </div>
        <div class="col-lg-12  form-group">
          <input type="text" class="form-control lbl_move" label="Country" />
        </div>
      </div>
      <div class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0 mar-35 mar-35">
        <div class="col-lg-12  form-group">
          <input type="text"  class="form-control lbl_move" label="Pic Code" />
        </div>
        <div class="col-lg-12  form-group">
          <input type="text"  class="form-control lbl_move" label="Mobile" />
        </div>
        <div class="col-lg-12  form-group">
          <input type="text" class="form-control lbl_move" label="Email" />
        </div>
        <div class="col-lg-12  form-group">
          <input type="text" class="form-control lbl_move" label="PF No" />
        </div>
        <div class="col-lg-12  form-group">
          <input type="text" class="form-control lbl_move" label="ESI No" />
        </div>
        <div class="col-lg-12  form-group">
          <select class="form-control single_dropdown lbl_move hei-34" label="Labour Type" style="width:100%;">
            <option></option>
            <option>Chennai</option>
          </select>
        </div>
        <div class="col-lg-12  form-group">
          <select class="form-control single_dropdown lbl_move hei-34" label="Vendor Name" style="width:100%;">
            <option></option>
            <option>Chennai</option>
          </select>
        </div>
      </div>
      <div class="col-lg-12">
        <ul class="can-sub">
          <li><a href="#"><i class="fa fa-times-circle"></i> Cancel</a></li>
          <li>
            <button type="submit"><i class="fa fa-check-circle-o"></i> Submit</button>
          </li>
        </ul>
      </div>
    </div>
    <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 slidingDiv2">
      <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 mar-35">
        <input type="text"  id="lead_date" class="form-control lbl_move" label="Add Labour Group" />
      </div>
      <div class="col-lg-8 col-lg-offset-4 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 ">
        <ul class="can-sub add-group-bt">
          <li><a href="#"><i class="fa fa-times-circle"></i> Cancel</a></li>
          <li>
            <button type="submit"><i class="fa fa-check-circle-o"></i> Submit</button>
          </li>
        </ul>
      </div>
    </div>
    <div id="dataTable"></div>
  </div>
</div>
<div class="col-lg-12 savebtn_area">
  <ul>
    <li class="dropdown save_btn float_r"><a href="javascript:void(0);" data-toggle="tooltip" class="ripple" title="Submit">Submit</a>
    <li class="cancel_btn float_r"><a href="javascript:void(0);" data-toggle="tooltip" class="ripple" title="Go back!">Back</a></li>
  </ul>
</div>
<script>
$(document).ready(function () {
//var url = "displayRegister";
var data = [
{Labourname:"Raj Kumar","ID No":"NDF2546","City":"Chennai","Email":"kumar@gmail.com","Mobile No":"089744 456644",},
{Labourname:"Vel","ID No":"NDF2546","City":"Covai","Email":"vel@gmail.com","Mobile No":"086544 457744",},
           ]
// prepare the data
var source =
{	
	localdata:data,
	dataType: "json",
	dataFields: [

    {name: 'Labourname', type: 'string' },
	{name: 'ID No', type: 'string' },
	{name: 'City', type: 'string' },
	{name: 'Email', type: 'string' },
	{name: 'Mobile No', type: 'string' },
	],
	id: 'RequestId',
};
var dataAdapter = new $.jqx.dataAdapter(source);
$("#dataTable").jqxGrid(
{
	width: '100%',
	pageable: true,
	rowsheight: 35,
	selectionMode: 'singleRow',	
	pagerButtonsCount: 6,
	autoheight: true,
	sortable: true,
	source: dataAdapter,
	statusbarheight:25,
    altrows: true,
	editable:true,
	columnsResize: true,
	columns: [
	

	  { text: 'Labourname', dataField: 'Labourname',width:'20%',editable:false,},
	  { text: 'ID No', dataField: 'ID No',width:'10%',editable:false,},
	   { text: 'City', dataField: 'City',width:'10%',editable:false,},
	     { text: 'Email', dataField: 'Email',width:'30%',editable:false,},
		   { text: 'Mobile No', dataField: 'Mobile No',width:'20%',editable:false,},
		   { text: 'Action', sortable: false, filterable: false, align: 'left', width:'10%',
                cellsrenderer: function (row) {
                    var editLink = '<a title="Edit" href="#" style="padding-left: 15px;"><i class="fa fa-pencil-square-o reg-icon"></i></a>';
                    return editLink + "&nbsp;&nbsp;" + '<button style="background: transparent;" title="Delete"><i class="fa fa-trash-o reg-icon"></i></button>';
                }
            }
  ],
});
$("#dataTable").bind('rowselect', function (event) {
});
});
</script> 
<script>
$(document).ready(function(){
	 $(".slidingDiv1").hide();
	$(".show_hide1").show();

	$('.show_hide1').click(function(){
	$(".slidingDiv1").slideToggle();

	});
	 $(".slidingDiv2").hide();
	$(".show_hide2").show();

	$('.show_hide2').click(function(){
	$(".slidingDiv2").slideToggle();

	});
});

</script>