<!--STYLE-->
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/wpm.css';?>"/>

<!--content-->
<div class="content_wrapper padlr0">
  <div class="container-fluid">
    <div class="col-lg-12">
      <h1 class="col-lg-3 col-lg-offset-0 col-md-3 col-md-offset-0 col-sm-3 col-sm-offset-0 col-xs-12 col-xs-offset-0">Work Order</h1>
      <div class="col-lg-3 col-lg-offset-0 col-md-3 col-md-offset-0 col-sm-3 col-sm-offset-0 col-xs-12 col-xs-offset-0  form-group">
        <select data-placeholder=" Bear"class="form-control single_dropdown lbl_move sortoption" tabindex="7" style="width:100%;">
          <option value=""></option>
          <option>American Black Bear</option>
        </select>
      </div>
      <div class="col-lg-3 col-lg-offset-0 col-md-3 col-md-offset-0 col-sm-3 col-sm-offset-0 col-xs-12 col-xs-offset-0 form-group">
        <select data-placeholder="Your " class="form-control single_dropdown lbl_move sortoption" tabindex="7" style="width:100%;">
          <option value=""></option>
          <option>American Black Bear</option>
        </select>
      </div>
      <div class="col-lg-3 col-lg-offset-0 col-md-3 col-md-offset-0 col-sm-3 col-sm-offset-0 col-xs-12 col-xs-offset-0 form-group">
        <select data-placeholder="Type of Bear" class="form-control single_dropdown lbl_move sortoption" tabindex="7" style="width:100%;">
          <option value=""></option>
          <option>American Black Bear</option>
        </select>
      </div>
    </div>
    <div class="clearfix"></div>
    <!--<div class="col-lg-12 feed-in">

   
    </div>-->
    <div class="col-md-12 feed-bg">
      <div class="top-conts animated fadeInLeft col-lg-8 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0">
        <h2>List of resources from the selected decisions.</h2>
        <p>Selected Requests</p>
        <span>10</span> </div>
      <div class="col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-8 col-sm-4 col-sm-offset-8 col-xs-12 col-xs-offset-0">
        <div class="cf search-wrapper">
          <input type="text" class="search-btns form-group"  placeholder="Search here..." required="" style="width:100%;">
          <button type="submit"><i class="fa fa-search"></i></button>
        </div>
      </div>
      <div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0">
        <div class="col-lg-3 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-6 col-sm-offset-0 col-xs-12 col-xs-offset-0">
          <div class="three-box hvr-overline-from-center">
            <ul>
              <li><span>Decision No</span>:&nbsp;Dc-001</li>
              <li><span>CC Name</span>:&nbsp;Project1</li>
              <li><span>Approved On</span>:&nbsp;13.05.2015</li>
            </ul>
            <span class="high-lit">A</span> </div>
        </div>
        <div class="col-lg-3 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-6 col-sm-offset-0 col-xs-12 col-xs-offset-0">
          <div class="three-box hvr-overline-from-center">
            <ul>
              <li><span>Decision No</span>:&nbsp;Dc-001</li>
              <li><span>CC Name</span>:&nbsp;Project1</li>
              <li><span>Approved On</span>:&nbsp;13.05.2015</li>
            </ul>
            <span class="high-lit">A</span> </div>
        </div>
        <div class="col-lg-3 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-6 col-sm-offset-0 col-xs-12 col-xs-offset-0">
          <div class="three-box hvr-overline-from-center">
            <ul>
              <li><span>Decision No</span>:&nbsp;Dc-001</li>
              <li><span>CC Name</span>:&nbsp;Project1</li>
              <li><span>Approved On</span>:&nbsp;13.05.2015</li>
            </ul>
            <span class="high-lit">A</span> </div>
        </div>
        <div class="col-lg-3 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-6 col-sm-offset-0 col-xs-12 col-xs-offset-0">
          <div class="three-box hvr-overline-from-center">
            <ul>
              <li><span>Decision No</span>:&nbsp;Dc-001</li>
              <li><span>CC Name</span>:&nbsp;Project1</li>
              <li><span>Approved On</span>:&nbsp;13.05.2015</li>
            </ul>
            <span class="high-lit">A</span> </div>
        </div>
        <div class="col-lg-3 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-6 col-sm-offset-0 col-xs-12 col-xs-offset-0">
          <div class="three-box hvr-overline-from-center">
            <ul>
              <li><span>Decision No</span>:&nbsp;Dc-001</li>
              <li><span>CC Name</span>:&nbsp;Project1</li>
              <li><span>Approved On</span>:&nbsp;13.05.2015</li>
            </ul>
            <span class="high-lit">A</span> </div>
        </div>
        <div class="col-lg-3 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-6 col-sm-offset-0 col-xs-12 col-xs-offset-0">
          <div class="three-box hvr-overline-from-center">
            <ul>
              <li><span>Decision No</span>:&nbsp;Dc-001</li>
              <li><span>CC Name</span>:&nbsp;Project1</li>
              <li><span>Approved On</span>:&nbsp;13.05.2015</li>
            </ul>
            <span class="high-lit">A</span> </div>
        </div>
        <div class="col-lg-3 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-6 col-sm-offset-0 col-xs-12 col-xs-offset-0">
          <div class="three-box hvr-overline-from-center">
            <ul>
              <li><span>Decision No</span>:&nbsp;Dc-001</li>
              <li><span>CC Name</span>:&nbsp;Project1</li>
              <li><span>Approved On</span>:&nbsp;13.05.2015</li>
            </ul>
            <span class="high-lit">A</span> </div>
        </div>
        <div class="col-lg-3 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-6 col-sm-offset-0 col-xs-12 col-xs-offset-0">
          <div class="three-box hvr-overline-from-center">
            <ul>
              <li><span>Decision No</span>:&nbsp;Dc-001</li>
              <li><span>CC Name</span>:&nbsp;Project1</li>
              <li><span>Approved On</span>:&nbsp;13.05.2015</li>
            </ul>
            <span class="high-lit">A</span> </div>
        </div>
        <div class="col-lg-3 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-6 col-sm-offset-0 col-xs-12 col-xs-offset-0">
          <div class="three-box hvr-overline-from-center">
            <ul>
              <li><span>Decision No</span>:&nbsp;Dc-001</li>
              <li><span>CC Name</span>:&nbsp;Project1</li>
              <li><span>Approved On</span>:&nbsp;13.05.2015</li>
            </ul>
            <span class="high-lit">A</span> </div>
        </div>
        <div class="col-lg-3 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-6 col-sm-offset-0 col-xs-12 col-xs-offset-0">
          <div class="three-box hvr-overline-from-center">
            <ul>
              <li><span>Decision No</span>:&nbsp;Dc-001</li>
              <li><span>CC Name</span>:&nbsp;Project1</li>
              <li><span>Approved On</span>:&nbsp;13.05.2015</li>
            </ul>
            <span class="high-lit">A</span> </div>
        </div>
        <div class="col-lg-3 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-6 col-sm-offset-0 col-xs-12 col-xs-offset-0">
          <div class="three-box hvr-overline-from-center">
            <ul>
              <li><span>Decision No</span>:&nbsp;Dc-001</li>
              <li><span>CC Name</span>:&nbsp;Project1</li>
              <li><span>Approved On</span>:&nbsp;13.05.2015</li>
            </ul>
            <span class="high-lit">A</span> </div>
        </div>
        <div class="col-lg-3 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-6 col-sm-offset-0 col-xs-12 col-xs-offset-0">
          <div class="three-box hvr-overline-from-center">
            <ul>
              <li><span>Decision No</span>:&nbsp;Dc-001</li>
              <li><span>CC Name</span>:&nbsp;Project1</li>
              <li><span>Approved On</span>:&nbsp;13.05.2015</li>
            </ul>
            <span class="high-lit">A</span> </div>
        </div>
        <div class="col-lg-3 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-6 col-sm-offset-0 col-xs-12 col-xs-offset-0">
          <div class="three-box hvr-overline-from-center">
            <ul>
              <li><span>Decision No</span>:&nbsp;Dc-001</li>
              <li><span>CC Name</span>:&nbsp;Project1</li>
              <li><span>Approved On</span>:&nbsp;13.05.2015</li>
            </ul>
            <span class="high-lit">A</span> </div>
        </div>
        <div class="col-lg-3 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-6 col-sm-offset-0 col-xs-12 col-xs-offset-0">
          <div class="three-box hvr-overline-from-center">
            <ul>
              <li><span>Decision No</span>:&nbsp;Dc-001</li>
              <li><span>CC Name</span>:&nbsp;Project1</li>
              <li><span>Approved On</span>:&nbsp;13.05.2015</li>
            </ul>
            <span class="high-lit">A</span> </div>
        </div>
        <div class="col-lg-3 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-6 col-sm-offset-0 col-xs-12 col-xs-offset-0">
          <div class="three-box hvr-overline-from-center">
            <ul>
              <li><span>Decision No</span>:&nbsp;Dc-001</li>
              <li><span>CC Name</span>:&nbsp;Project1</li>
              <li><span>Approved On</span>:&nbsp;13.05.2015</li>
            </ul>
            <span class="high-lit">A</span> </div>
        </div>
        <div class="col-lg-3 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-6 col-sm-offset-0 col-xs-12 col-xs-offset-0">
          <div class="three-box hvr-overline-from-center">
            <ul>
              <li><span>Decision No</span>:&nbsp;Dc-001</li>
              <li><span>CC Name</span>:&nbsp;Project1</li>
              <li><span>Approved On</span>:&nbsp;13.05.2015</li>
            </ul>
            <span class="high-lit">A</span> </div>
        </div>
        <div class="col-lg-3 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-6 col-sm-offset-0 col-xs-12 col-xs-offset-0">
          <div class="three-box hvr-overline-from-center">
            <ul>
              <li><span>Decision No</span>:&nbsp;Dc-001</li>
              <li><span>CC Name</span>:&nbsp;Project1</li>
              <li><span>Approved On</span>:&nbsp;13.05.2015</li>
            </ul>
            <span class="high-lit">A</span> </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="col-md-12 feed-bg">
      <div class="top-conts animated fadeInLeft col-lg-8 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0">
        <h2>List of resources from the selected decisions.</h2>
        <p>Selected Requests</p>
        <span>10</span> </div>
      <div class="col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-8 col-sm-4 col-sm-offset-8 col-xs-12 col-xs-offset-0 form group top-45">
      
        <select class="form-control single_dropdown lbl_move" name="vendorId" style="width:100%;" label="Select Service Provider">
        <option data-image='none' value='0'>Select Service Provider</option>
        <option>Option</option>
       <option>Option</option>
        </select>
      </div>
      <div class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0 col-xs-12 col-xs-offset-0">
      <div class="col-lg-12">
        <div id="dataTable"></div>
        </div>
      </div>
      <div class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0 col-xs-12">
       <div class="col-lg-12">
        <div class="bubble">
          <div class="rectangle">
            <h2>Preferred Vendor</h2>
          </div>
          <div class="triangle-l"></div>
          <div class="triangle-r"></div>
          <div class="info">
            <div align="center"><img align="baseline" src="<?php echo $this->basePath() . '/images/avatar.jpg';?>"></div>
            <h2>Hi <b>Friends</b></h2>
            <address>
            <b>Address :</b> Micromen Systems & Software Pvt. Ltd,
            # 2, Sardar Patel Road, Adyar,
            Chennai - 600 020.
            </address>
          </div>
        </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>
  </div>
</div>
<div class="col-lg-12 savebtn_area">
  <ul>
    <li class="dropdown save_btn float_r" id="continueButton"> <a class="ripple has-ripple" onclick="validateOnSubmit();" style="position: relative; overflow: hidden;">Continue<span class="ripple-wrapper"></span></a> </li>
    <li class="cancel_btn cancel_btn_bluecolor float_l"><a class="ripple has-ripple" href="/bsf_v1.1/public/wpm/workorder/index" style="position: relative; overflow: hidden;">Cancel <i aria-hidden="true" class="fa fa-times-circle-o"></i><span class="ripple-wrapper"></span></a></li>
  </ul>
</div>
<!--table header script--> 

<script>
$(document).ready(function () {
//var url = "displayRegister";
var data = [
{Description:"Activity",RequestNo:"A00011", RequestDate:"A00011 ",Quantity:"5",Code:"True"},
{Description:"Material",RequestNo:"A00022", RequestDate:"A00011",Unit:"Sqm",Quantity:"110",Code:"false"},
{Description:"Activity",RequestNo:"A00050", RequestDate:"A00011",Unit:"Nos",Quantity:"200",Code:"false"},
{Description:"Activity",RequestNo:"A00221", RequestDate:"Excavation",Unit:"Ls",Quantity:"320",Code:"false"},
{Description:"Material",RequestNo:"A00012", RequestDate:"Cement",Unit:"Cum",Quantity:"546",Code:"false"},
{Description:"Activity",RequestNo:"A00061", RequestDate:"Earth Work",Unit:"Ls",Quantity:"333",Code:"false"},
{Description:"Activity",RequestNo:"A00011", RequestDate:"Excavation",Unit:"Nos",Quantity:"789",Code:"false"},
		]
// prepare the data
var source =
{	
	localdata:data,
	dataType: "json",
	dataFields: [
	{ name: 'Code', type: 'boolean' },
		{ name: 'Description', type: 'string' },
		{ name: 'Quantity', type: 'string' },
		{ name: 'RequestNo', type: 'string' },
		{ name: 'RequestDate', type: 'string' },
],
	id: 'RequestId',
};

var dataAdapter = new $.jqx.dataAdapter(source);

$("#dataTable").jqxGrid(
{
	width: '100%',
	pageable: true,
	rowsheight: 35,
	selectionMode: 'singleRow',	
	pagerButtonsCount: 6,
	autoheight:true,
	source: dataAdapter,
    altrows: true,
	editable:true,
	
	columnsResize: true,
	columns: [
	{ text: 'Code', dataField: 'Code', columngroup: 'Current',columntype: 'checkbox',align:'center',},
	  { text: 'Description', dataField: 'Description',width:'12%',editable:false,},
	  { text: 'Quantity', dataField: 'Quantity',editable:false,},
	  { text: 'RequestNo', dataField: 'RequestNo',editable:false,},
	  { text: 'RequestDate', dataField: 'RequestDate',width:'12%',editable:false,},
  ],
  columngroups: 
                [
                  { text: 'Revised', align: 'center', name: 'Revised' },
				 
                ]
});
$("#dataTable").bind('rowselect', function (event) {
	
	
});

});
</script> 
<script>
$(function(){
    $('.div-overallscroll').slimScroll({
		position: 'right',
        height: '100%',
		alwaysVisible: false,
		railVisible: true,
		railColor: '#d7dabd',
		color: '#009688',
	    railOpacity: 1
    });
});

</script> 
<!--datepicker--> 