<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath(); ?>/library/handsontable/css/handsontable.full.min.css">
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/handsontable/js/handsontable.full.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/handsontable/js/RuleJS/lodash.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/handsontable/js/RuleJS/underscore.string.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/handsontable/js/RuleJS/numeral.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/handsontable/js/RuleJS/numeric.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/handsontable/js/formula.js"></script>
<script type="text/javascript"src="<?php echo $this->basePath(); ?>/library/handsontable/js/parser.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/handsontable/js/ruleJS.all.full.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/handsontable/js/handsontable.formula.js"></script>
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css'; ?>" />
<style type="text/css">
    #jqxTree{margin-top: 15px;max-height: 450px; min-height:400px !important; border:none}
    .jqx-tree-dropdown{padding:0 0 0 5px}
    .jqx-tree-dropdown-root{min-width:100% !important; width:100% !important}
    .jqxgrid{background:#fff;border:1px solid #ddd;box-shadow:0 1px 0 rgba(0, 0, 0, 0.12), 0 1px 1px rgba(0, 0, 0, 0.24);padding:30px 6px 20px;width:100% !important; /*height:490px !important; overflow-y:scroll*/}
    .jqx-draggable{ border-bottom:1px solid #ddd; width:97%;margin-bottom:4px; padding:8px 0 8px 8px;background:#f1f1f1}
    .jqx-fill-state-pressed,.jqx-item:hover,.jqx-draggable:hover{background:#3399ff !important;color:#fff !important}
    .jqx-tree-item-li{display:block; width:90%}
    .ctls {font-size:18px !important}
    .list .tile .checkbox-styled:not(ie8) input ~ span, .list .tile .radio-styled:not(ie8) input ~ span{padding-left:35px}
    .list .tile{border-radius: 4px;}
    .vendor_checkboxborder_gray{border:none !important; border-radius:none;}
    .list .tile .checkbox-styled:not(ie8) input ~ span, .list .tile .radio-styled:not(ie8) input ~ span{text-overflow:ellipsis;overflow:hidden;display:inline-block;white-space:nowrap;}
    .tr-header input[type=text] {font-weight:600 !important; font-size:15px !important; border:none !important; color: #015de6;}
    .innermdl_tabs{ border-bottom: 2px solid #2d74b4 !important;}
    .innermdl_tabs > li > a:hover, .innermdl_tabs > li.active > a, .innermdl_tabs > li.active > a:focus, .innermdl_tabs > li.active > a:hover{background:#F7E8C6 !important;border-bottom:1px solid #6B3D0C !important; color:#6B3D0C}
    .nav-tabs > li > a{background:#E8F1FA;border-bottom:1px solid #2d74b4 !important; color:#0B4480}
    .innermdl_tabs > li.active::after{content: ""; display: block; width: 0; height: 0; border-bottom: 8px solid #6B3D0C;  border-right: 8px solid transparent; border-left: 8px solid transparent; position: absolute; bottom:0px; right:38%;z-index:1; background:none}
    .btn_newlist {background: #e3edf1 none repeat scroll 0 0;  border: 2px solid #93cee5; border-radius: 50%;color: #000;font-size: 11px;line-height: 36px;margin-bottom: 15px;padding: 0 4px;text-align: center;}
    .btn_newlist a i{ text-align:center; font-size:20px; color:#000; padding-left:16px; line-height:45px; transition:all 0.3s ease;}
    .btn_newlist a i:hover{-webkit-transform: scale(1.3);-ms-transform: scale(1.3);transform: scale(1.3); padding-left:14px}
    .heading_checkbox                       {line-height:40px;}
    .search-container label {right: 10px;position: absolute;top: 30px;z-index:999;color:#ccc;}
    .sr-only {border: 0 none;clip: rect(0px, 0px, 0px, 0px);height: 1px;margin: -1px;overflow: hidden;padding: 0;position: absolute;width: 1px;}
    .search-container {font-size: 18px;margin: -20px auto 0;padding-top: 20px;position: relative;}
    .card {margin: 15px 0;padding: 11px;}
    .card-body {padding: 0;}
    .over-all-hide {display:none; background: rgba(255, 255, 255, 0.6) none repeat scroll 0 0;cursor:no-drop;height: 100%;left: 0;position: absolute; top: 0;width: 100%;z-index: 999;}

 .work-frq{padding:5px 0 !important}
 .work-frq >.critical >.checkbox label{padding:20px 4px 12px 6px !important}
 .table-fixed tbody{max-height:459px;min-height:20px; overflow-y:auto;width:100%}
    .table-fixed thead,.table-fixed tbody,.table-fixed tr,.table-fixed td,.table-fixed th{display:block}
    .table-fixed tbody td,.table-fixed thead>tr>th{float:left; border-bottom:0;position:relative;text-overflow:ellipsis;overflow:hidden;display:inline-block;white-space:nowrap}
</style>
<div class="content_wrapper padlr0">
    <div class="container-fluid">
        <h1 class="col-md-12 text-left animated growIn form-group">Project Communication</h1>
        <div class="col-lg-12 form-group">
            <div class="col-lg-4 col-md-5" >
                <div class="col-md-12 jqxgrid">
                    <div class="col-md-12" style="padding:0 !important">
                        <select class="form-control single_dropdown lbl_move" label="Select Project" style="width:100%;" id="ProjectList">
                            <option></option>
                            <?php if(isset($projectlists)):
                                foreach($projectlists as $list): ?>
                                    <option value="<?php echo $list['ProjectId']?>"><?php echo $list['ProjectName']?></option>
                                <?php endforeach;
                            endif;?>
                        </select>
                    </div>
                    <div class="clearfix"></div>
                    <div class="slimScroll" id='jqxTree'></div>
                    <div class="over-all-hide" id="treeOverlay"></div>
                </div>
            </div>
            <div class="col-lg-8 col-md-7">
                <form id="formWrapper">
                    <input type="hidden" id="ProjectId" name="ProjectId" value="0"/>
                    <input type="hidden" name="Type" value="savechks"/>
                    <div class="table-responsive col-md-12">
                        <table class="table table-fixed" width="100%">
                            <thead>
                            <tr class="col-xs-12" style="padding:0 !important">
                                <th class="col-xs-2" width="15%">SerialNo</th>
                                <th class="col-xs-5" width="25%">Description</th>
                                <th  class="col-xs-2">Unit</th>
                                <th  class="col-xs-2">Qty</th>
                                <th  class="col-xs-1">&nbsp;</th>
                            </tr>
                            </thead>
                            <tbody id="tbodyWrapper"></tbody>
                        </table>
                        <input type="hidden" name="rowcount" id="rowcount" value="0">
                    </div>
                </form>
                <div class="col-lg-12 savebtn_area">
                    <ul>
                        <li id="submit-btn" class="dropdown save_btn float_r" style="">
                            <a class="ripple has-ripple" onclick="saveChanges();" data-toggle="tooltip" title="" data-original-title="Save" style="position: relative; overflow: hidden;">Save<span class="ripple-wrapper"></span></a>
                        </li>
                        <li class="can_btn float_l" style="padding-bottom:10px;">
                            <a style="padding:6px 15px !important;" onclick="discardChanges();">Cancel</a>
                        </li>
                    </ul>
                </div>
                <div class="over-all-hide" id="tableOverlay"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<script id="workgroupTemplate" type="text/template">
    <tr>
        <input type="hidden" name="WBSId__" id="WBSId__" value="{{WBSId}}"/>
        <input type="hidden" name="ProjectIOWId__" id="ProjectIOWId__" value="{{ProjectIOWId}}"/>
        <td class="col-xs-2" width="15%">{{serialno}}</td>
        <td class="col-xs-5" width="25%">{{spec}}</td>
        <td class="col-xs-2" width="8%">{{unitname}}</td>
        <td class="col-xs-2" width="8%">{{qty}}</td>
        <td class="col-xs-1" class="action_btns_td" width="5%">
            <a href="#" class="mainTr"> <i class="fa fa-chevron-circle-down ctls" data-toggle="tooltip" data-placement="left" data-original-title="Expand" ></i></a>
        </td>
    </tr>
    <tr style="display:none;" class="subTr col-xs-12">
        <td colspan="12" class="col-xs-12">
            <div class="subDiv col-xs-12"  style="animation-delay: 0.2s;padding:0 !important">
                <div class="col-lg-12 padlr0">
                    <nav class="navbar inrmdltab_navbar navbar-default">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle mdlnvbr_tgl collapsed ripple" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
                            <a class="navbar-brand inrmdl_navbrand ripple" href="javascript:void(0);">Select Menus</a>
                        </div>
                        <div id="navbar" class="navbar-collapse padlr0 collapse">
                            <ul class="nav nav-tabs innermdl_tabs">
                                <li class="active"><a href="#worktab__" data-toggle="tab" class="ripple">Works</a></li>
                                <li><a href="#safetytab__" data-toggle="tab" class="ripple">Safety</a></li>
                                <li><a href="#qualitytab__" data-toggle="tab" class="ripple">Quality</a></li>
                            </ul>
                        </div>
                    </nav>
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="worktab__">
                            <div class="deft_act col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0">
                                <div class="col-lg-12 col-md-12" style="padding:0 !important">
                                    <div class="headingWrapper">
                                        <p class="heading_checkbox">CheckList</p>
                                        <section class="search-container">
                                            <label> <i class="fa fa-search" aria-hidden="true"></i> <span class="sr-only">Search icons</span> </label>
                                            <input class="form-control lbl_move height25" type="text" placeholder="Search... "  onkeyup="chkSearch(this)">
                                        </section>
                                    </div>
                                    <div class="card workChecklistWrapper">
                                        <div class="card-body" style="min-height:50px; max-height:310px;">
                                            <ul class="sampleUI list workChecklists"></ul>
                                            <input type="hidden" id="wtype___workchklist" name="wtype___workchklist"/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="safetytab__">
                            <div class="deft_act col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0">
                                <div class="col-lg-12 col-md-12">
                                    <div class="headingWrapper">
                                        <p class="heading_checkbox">CheckList</p>
                                        <section class="search-container">
                                            <label> <i class="fa fa-search" aria-hidden="true"></i> <span class="sr-only">Search icons</span> </label>
                                            <input class="form-control lbl_move height25" type="text" placeholder="Search... "  onkeyup="chkSearch(this)">
                                        </section>
                                    </div>

                                    <div class="card workChecklistWrapper">
                                        <div class="card-body" style="min-height:50px; max-height:310px;">
                                            <ul class="sampleUI list safetyChecklists"></ul>
                                            <input type="hidden" id="wtype___safetychklist" name="wtype___safetychklist"/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="qualitytab__">
                            <div class="deft_act col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0">
                                <div class="col-lg-12 col-md-12">
                                    <div class="headingWrapper">
                                        <p class="heading_checkbox">CheckList</p>
                                        <section class="search-container">
                                            <label> <i class="fa fa-search" aria-hidden="true"></i> <span class="sr-only">Search icons</span> </label>
                                            <input class="form-control lbl_move height25" type="text" placeholder="Search... "  onkeyup="chkSearch(this)">
                                        </section>
                                    </div>
                                    <div class="card workChecklistWrapper">
                                        <div class="card-body" style="min-height:50px; max-height:310px;">
                                            <ul class="sampleUI list qualityChecklists"></ul>
                                            <input type="hidden" id="wtype___qualitychklist" name="wtype___qualitychklist"/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </td>
    </tr>
</script>
<script type="text/template" id="checklist-template">
    <li class="tile search-item">
        <div class="col-md-7 show_hide11" style="padding:0 !important;border-bottom:1px solid #ddd">
            <div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">
                <label style="display: inline-block;padding-right:0">
                    <input class="search-element" name="wtype__0_{{typelabel}}chklist__1" id="wtype__0_{{typelabel}}chklist__1" type="checkbox" data-name="{{name}}" value="{{value}}">
                    <span>&nbsp;</span>
                </label>
				<span class="chk-name">{{name}}</span>
            </div>
        </div>
        <div class="col-md-5" style="border-bottom:1px solid #ddd">
            <select class="form-control single_dropdown lbl_move" name="wtype__0_{{typelabel}}chkuser__1" id="wtype__0_{{typelabel}}chkuser__1" style="width:100%;">
                <option value="">Select User</option>
                <?php if(isset($userlists)):
                    foreach($userlists as $list): ?>
                <option value="<?php echo $list['UserId'];?>"><?php echo $list['UserName'];?></option>
                <?php endforeach;
                    endif;?>
            </select>
        </div>
        <div class="work-frq col-md-12 slidingDiv11">
            <div class="col-md-2 critical">
                <label class="col-md-12">Priority</label>
                <div class="col-md-12">
                    <select class="form-control single_dropdown lbl_move " name ="wtype__0_{{typelabel}}priority__1"  id = "wtype__0_{{typelabel}}priority__1" style="width:100%;" >
                        <option value="H">High</option>
                        <option value="M">Middle</option>
                        <option value="L">Low</option>
                    </select>
                </div>
<!--			<label class="col-md-12">Critical</label>-->
<!--                <div class="checkbox checkbox-styled">-->
<!--                    <label>-->
<!--                        <input type="checkbox" name="wtype__0_{{typelabel}}critical__1" id="wtype__0_{{typelabel}}critical__1" value="1">-->
<!--                        <span></span>-->
<!--                    </label>-->
<!--                </div>-->
            </div>
            <div class="col-md-6" style="padding-right:0 !important">
                <div class="col-md-12 critical">
                    <label class="col-md-12">When</label>
                    <div class="col-md-5" style="padding-right:0 !important">
                        <select class="form-control single_dropdown lbl_move " style="width:100%;" name="wtype__0_{{typelabel}}whentype__1" id="wtype__0_{{typelabel}}whentype__1">
                            <option></option>
                            <option value="A">After</option>
                            <option value="B">Before</option>
                            <option value="D">During</option>
                        </select>
                    </div>
                    <div class="col-md-3" style="padding-right:0 !important">
                        <input type="text" class="form-control lbl_move" name="wtype__0_{{typelabel}}whenperiod__1" id="wtype__0_{{typelabel}}whenperiod__1" onkeypress="return isNumberKey(event,this)" maxlength="3"/>
                    </div>
                    <div class="col-md-4">
                        <select class="form-control single_dropdown lbl_move " style="width:100%;"  name="wtype__0_{{typelabel}}whenperiodtype__1" id="wtype__0_{{typelabel}}whenperiodtype__1">
                            <option></option>
                            <option value="D">Day</option>
                            <option value="H">Hours</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-md-4" style="padding-right:0 !important">
                <div class="col-md-12 critical">
                    <label class="col-md-12">Frequency</label>
                    <div class="col-md-4" style="padding-right:0 !important">
                        <input type="text" class="form-control lbl_move" name="wtype__0_{{typelabel}}freqperiod__1" id="wtype__0_{{typelabel}}freqperiod__1" onkeypress="return isNumberKey(event,this)" maxlength="3"/>
                    </div>
                    <div class="col-md-8">
                        <select class="form-control single_dropdown lbl_move " style="width:100%;" name="wtype__0_{{typelabel}}freqperiodtype__1" id="wtype__0_{{typelabel}}freqperiodtype__1">
                            <option></option>
                            <option value="D">Day</option>
                            <option value="H">Hours</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </li>
</script>
<script type="text/javascript">
    var arr_wbslist = [],
        $jqxTree = $('#jqxTree'),
        $formWrapper = $('#formWrapper'),
        $tbodyWrapper = $('#tbodyWrapper'),
        $rowcount = $('#rowcount'),
        workgroupTemplate = $('#workgroupTemplate').html();
        chklistTemplate = $('#checklist-template').html();
    var projectwbs = [],
        projectwbsiows = [];
    $(function () {
        $('.slimScroll').slimScroll({
            height : '100%',
            alwaysVisible: false,
            railVisible: true,
            railColor: '#cececd',
            railOpacity: 1
        });

        $('#ProjectList').on('change', function () {
            $tbodyWrapper.html('');
            var projectId = $(this).val();
            $('#ProjectId').val(projectId);
            if(projectId == '' || projectId == 0)
                return;

            if(projectwbs.hasOwnProperty(projectId)) {
                $('.loading_area').show();
                arr_wbslist = projectwbs[projectId];
                bindTreeGrid();
                return;
            }

            $('.loading_area').show();
            $.ajax({
                url: getBaseURL() + "project/communication/index",
                type: 'post',
                data: {'Type': 'getwbs','ProjectId': projectId},
                success: function (data,status, xhr) {
                    if(xhr.status == 200) {
                        data = JSON.parse(data);
                        projectwbs[projectId] = data;
                        arr_wbslist = data;
                    } else {
                        projectwbs[projectId] = [];
                        arr_wbslist = [];
                    }
                    bindTreeGrid();
                },
                error: function (status, error, xhr) {
                    arr_wbslist = [];
                    bindTreeGrid();
                }
            });
        });

        bindTreeGrid();

        $jqxTree.on('select', function (event) {
            var item = $('#jqxTree').jqxTree('getItem', event.args.element);
            if(item.hasItems)
                return;

            $('.loading_area').show();
//            if(projectwbsiows.hasOwnProperty(item.id)) {
//                renderIOWs(projectwbsiows[item.id]);
//                return;
//            }

            $.ajax({
                url: getBaseURL() + "project/communication/index",
                type: 'post',
                data: {'Type': 'getiows','WBSId': item.id},
                success: function (data,status, xhr) {
                    $tbodyWrapper.html('');
                    $('.loading_area').hide();
                    if(xhr.status == 200) {
                        data = JSON.parse(data);
                        projectwbsiows[item.id] = data;
                        renderIOWs(data);
                    }
                },
                error: function (status, error, xhr) {
                    $tbodyWrapper.html('');
                    $('.loading_area').hide();
                }
            });
        });
        
        $('.content_wrapper').on('click', '.show_hide11',function(e){
            if($(e.target).is('span:not(.chk-name)') || $(e.target).is('.search-element')) {
                return;
            }

            var $slideDiv = $(this).nextAll(".slidingDiv11");
            $('.slidingDiv11:visible').not($slideDiv).slideUp();
            $slideDiv.slideToggle();
        });
    });

    function renderIOWs(data) {
        $tbodyWrapper.html('');
        $('#treeOverlay').show();
        $('#tableOverlay').hide();
        var rowid = 0;
        $.each(data.wbs, function (i, o) {
            rowid++;
            $tbodyWrapper.append(workgroupTemplate.replace(/\_\_/g, '_'+rowid)
                .replace(/\{\{WBSId\}\}/g, o.WBSId)
                .replace(/\{\{ProjectIOWId\}\}/g, o.ProjectIOWId)
                .replace(/\{\{serialno\}\}/g, o.SerialNo)
                .replace(/\{\{spec\}\}/g, o.Specification)
                .replace(/\{\{unitname\}\}/g, o.UnitName)
                .replace(/\{\{qty\}\}/g, o.Qty));


            // work chks
            var chkrowid = 0;
            $.each(data.workchks, function (j,chk) {
                if (o.WorkGroupId != chk.WorkGroupId)
                    return;

                chkrowid++;
                $tbodyWrapper.find('> tr.subTr:last-child .workChecklists').append(chklistTemplate
                    .replace(/\_\_0/g, '_'+rowid)
                    .replace(/\{\{value\}\}/g,chk.CheckListId)
                    .replace(/\{\{name\}\}/g,chk.CheckListName)
                    .replace(/\_\_1/g, '_'+chkrowid)
                    .replace(/\{\{typelabel\}\}/g,'work')
                );

                $.each(data.selchks, function (k, selchk) {
                    if(o.ProjectIOWId != selchk.ProjectIOWId || o.WBSId != selchk.WBSId || selchk.CheckListId != chk.CheckListId)
                        return;

                    $('#wtype_'+rowid+'_workchklist_'+chkrowid).prop('checked', true);
                    $('#wtype_'+rowid+'_workchkuser_'+chkrowid).val(selchk.UserId).trigger('change');
//                    if(selchk.IsCritical == '1')
//                        $('#wtype_'+rowid+'_workcritical_'+chkrowid).prop('checked', true);
                    $('#wtype_'+rowid+'_workpriority_'+chkrowid).val(selchk.Priority).trigger('change');
                    $('#wtype_'+rowid+'_workwhentype_'+chkrowid).val(selchk.WhenType).trigger('change');
                    $('#wtype_'+rowid+'_workwhenperiod_'+chkrowid).val(selchk.WhenPeriod);
                    $('#wtype_'+rowid+'_workwhenperiodtype_'+chkrowid).val(selchk.WhenPeriodType).trigger('change');
                    $('#wtype_'+rowid+'_workfreqperiod_'+chkrowid).val(selchk.FrequencyPeriod);
                    $('#wtype_'+rowid+'_workfreqperiodtype_'+chkrowid).val(selchk.FrequencyPeriodType).trigger('change');
                });
            });
            $('#wtype_'+rowid+'_workchklist').val(chkrowid);

            // safety chks
            var chkrowid = 0;
            $.each(data.safetychks, function (j,chk) {
                if (o.WorkGroupId != chk.WorkGroupId)
                    return;

                chkrowid++;
                $tbodyWrapper.find('> tr.subTr:last-child .safetyChecklists')
                    .append(chklistTemplate
                        .replace(/\_\_0/g, '_'+rowid)
                        .replace(/\{\{value\}\}/g,chk.CheckListId)
                        .replace(/\{\{name\}\}/g,chk.CheckListName)
                        .replace(/\_\_1/g, '_'+chkrowid)
                        .replace(/\{\{typelabel\}\}/g,'safety')
                );

                $.each(data.selchks, function (k, selchk) {
                    if(o.ProjectIOWId != selchk.ProjectIOWId || o.WBSId != selchk.WBSId || selchk.CheckListId != chk.CheckListId)
                        return;

                    $('#wtype_'+rowid+'_safetychklist_'+chkrowid).prop('checked', true).trigger('change');
                    $('#wtype_'+rowid+'_safetychkuser_'+chkrowid).val(selchk.UserId).trigger('change');

//                    if(selchk.IsCritical == '1')
//                        $('#wtype_'+rowid+'_safetycritical_'+chkrowid).prop('checked', true);

                    $('#wtype_'+rowid+'_safetypriority_'+chkrowid).val(selchk.Priority).trigger('change');
                    $('#wtype_'+rowid+'_safetywhentype_'+chkrowid).val(selchk.WhenType).trigger('change');
                    $('#wtype_'+rowid+'_safetywhenperiod_'+chkrowid).val(selchk.WhenPeriod);
                    $('#wtype_'+rowid+'_safetywhenperiodtype_'+chkrowid).val(selchk.WhenPeriodType).trigger('change');
                    $('#wtype_'+rowid+'_safetyfreqperiod_'+chkrowid).val(selchk.FrequencyPeriod);
                    $('#wtype_'+rowid+'_safetyfreqperiodtype_'+chkrowid).val(selchk.FrequencyPeriodType).trigger('change');
                });
            });
            $('#wtype_'+rowid+'_safetychklist').val(chkrowid);

            // quality chks
            var chkrowid = 0;
            $.each(data.qualitychks, function (j,chk) {
                if (o.WorkGroupId != chk.WorkGroupId)
                    return;

                chkrowid++;
                $tbodyWrapper.find('> tr.subTr:last-child .qualityChecklists')
                    .append(chklistTemplate
                        .replace(/\_\_0/g, '_'+rowid)
                        .replace(/\{\{value\}\}/g,chk.CheckListId)
                        .replace(/\{\{name\}\}/g,chk.CheckListName)
                        .replace(/\_\_1/g, '_'+chkrowid)
                        .replace(/\{\{typelabel\}\}/g,'quality')
                );

                $.each(data.selchks, function (k, selchk) {
                    if(o.ProjectIOWId != selchk.ProjectIOWId || o.WBSId != selchk.WBSId || selchk.CheckListId != chk.CheckListId)
                        return;

                    $('#wtype_'+rowid+'_qualitychklist_'+chkrowid).prop('checked', true).trigger('change');
                    $('#wtype_'+rowid+'_qualitychkuser_'+chkrowid).val(selchk.UserId).trigger('change');

//                    if(selchk.IsCritical == '1')
//                        $('#wtype_'+rowid+'_qualitycritical_'+chkrowid).prop('checked', true);

                    $('#wtype_'+rowid+'_qualitypriority_'+chkrowid).val(selchk.Priority).trigger('change');
                    $('#wtype_'+rowid+'_qualitywhentype_'+chkrowid).val(selchk.WhenType).trigger('change');
                    $('#wtype_'+rowid+'_qualitywhenperiod_'+chkrowid).val(selchk.WhenPeriod);
                    $('#wtype_'+rowid+'_qualitywhenperiodtype_'+chkrowid).val(selchk.WhenPeriodType).trigger('change');
                    $('#wtype_'+rowid+'_qualityfreqperiod_'+chkrowid).val(selchk.FrequencyPeriod);
                    $('#wtype_'+rowid+'_qualityfreqperiodtype_'+chkrowid).val(selchk.FrequencyPeriodType).trigger('change');
                });
            });
            $('#wtype_'+rowid+'_qualitychklist').val(chkrowid);
        });
        $rowcount.val(rowid);

        $("#tbodyWrapper .single_dropdown").select2({
            placeholder: "",
            allowClear: true
        });
        $('.loading_area').hide();
    }

    function discardChanges() {
        $tbodyWrapper.html('');
        $('#treeOverlay').hide();
        $('#tableOverlay').show();
    }

    function saveChanges() {
        $('#treeOverlay').show();
        $('#tableOverlay').show();
        $('.loading_area').show();
        $.ajax({
            url: getBaseURL() + "project/communication/index",
            type: 'post',
            data: $formWrapper.serialize(),
            success: function (data,status, xhr) {
                $tbodyWrapper.html('');
                $('#treeOverlay').hide();
                $('#tableOverlay').show();
                alert('Changes Saved Successfully!');
                $('.loading_area').hide();
            },
            error: function (status, error, xhr) {
                alert('Error Occured, While saving data!');
                $('.loading_area').hide();
                $('#tableOverlay').hide();
            }
        });
    }

    function bindTreeGrid() {
        var source = {
            async: false,
            datatype: "json",
            editable:false,
            datafields: [
                { name: 'id' },
                { name: 'parentid' },
                { name: 'text' }
            ],
            id: 'id',
            localdata: arr_wbslist
        };

        var dataAdapter = new $.jqx.dataAdapter(source);
        dataAdapter.dataBind();
        var records = dataAdapter.getRecordsHierarchy('id', 'parentid', 'items', [{ name: 'text', map: 'label'}]);

        $jqxTree.jqxTree({ source: records, width: '100%' });
        $('.loading_area').hide();
    }

    $(".content_wrapper").on('click', '.mainTr',function(e){
        e.preventDefault();
        if(!$(this).closest("tr").next(".subTr").is(":visible")){
            $(this).closest("tr").next(".subTr").show();
            $(this).closest("tr").next(".subTr").find(".subDiv").slideDown("slow");
            $(this).find("i").addClass("tform");
        }
        else{
            $(this).closest("tr").next(".subTr").find(".subDiv").slideUp("slow");
            $(this).closest("tr").next(".subTr").slideUp("slow");
            $(this).find("i").removeClass("tform");
        }
    });


    function chkSearch(x) {
        var $x = $(x),
            searchText = $.trim($x.val()),
            $checklistWrapper = $x.parents('.headingWrapper').next('.card'),
            delayTimer = 0;

        clearTimeout(delayTimer);
        delayTimer = setTimeout(function () {
            if(searchText.length == 0) {
                $checklistWrapper.find('.search-element').closest('.search-item').show();
                return;
            }

            var $foundChks = $checklistWrapper.find('.search-element');
            $.each($foundChks, function () {
                var name = $(this).attr('data-name').toLowerCase();
                if(name.indexOf(searchText.toLowerCase()) == -1) {
                    $(this).closest('.search-item').fadeOut(100);
                    return;
                }

                $(this).closest('.search-item').fadeIn(100);
            });
        }, 300);
    }
</script> 
