<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css';?>"/>
<style>
.filter-1{background:#fff; box-shadow:0 1px 0 rgba(0, 0, 0, 0.12), 0 1px 1px rgba(0, 0, 0, 0.24);overflow:hidden}
.circle-icon {background:none;box-sizing: content-box;color: #ffffff;height: 70px;margin-left: -24px;width: 100%;}
.circle-icon1::before { border-color: #526D85  rgba(0, 0, 0, 0) #526D85  #526D85 !important;}
.circle-icon2::before { border-color: #845285  rgba(0, 0, 0, 0) #845285  #845285 !important;}
.circle-icon3::before { border-color: #538552  rgba(0, 0, 0, 0) #538552  #538552 !important;}
.circle-icon::before {-moz-border-bottom-colors: none;-moz-border-left-colors: none;-moz-border-right-colors: none; -moz-border-top-colors: none; border-color: #856B52 rgba(0, 0, 0, 0) #856B52 #856B52; border-image: none; border-style: solid; border-width:45px 24px 48px 163px; bottom: -10px;content: "";position: absolute;right: -185px;transform: rotate(179deg);width:4.2em;opacity:0.2;}
.fa-5x {color: #ffffff;font-size: 36px;line-height: 35px; position: absolute;right: 17px;text-align: center;top: 17px;text-shadow: 2px 1px 1px #fff; z-index: 999;transition:all 2s ease-in-out;}
.fa-5x:hover{transform:rotate(360deg) scale(1.7);cursor:pointer}
.filter-1 h6{font-size:18px; color:#062638;line-height:35px; text-align:right}
.filter-1 p{font:700 13px/30px "roboto"; color:#666; text-align:right}
.form-group { margin-bottom: 15px;}
.head-4{font-size:21px; color:#0C407A;line-height:35px; text-align:left}
label{width:100%; padding:5px 0}
.butclr-ns1{margin:0 25px 10px 0}
.lbl_move{height:40px !important}
#datagrid .jqx-grid-header 	{ height:75px !important;}
</style>
<!--content-->
<div class="content_wrapper padlr0">
    <div class="container-fluid">
        <!--three feild start-->
        <h1 class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0">Task Details</h1>
        <div class="col-md-12">
            <div class="form-group col-md-2" style="padding:0 !important">
                <label>From</label>
                <input type="text"  id="fromDate" class="form-control date_picker lbl_move" value="<?php echo (isset($arrDate) && !is_null($arrDate['FDate'])) ? date("d-m-Y", strtotime($arrDate['FDate'])) : date('d-m-Y');?>" onchange="bindData();"/>
                <span class="date_icon" style="top:inherit;bottom:17px"><i class="fa fa-calendar"></i></span>
            </div>
            <div class="form-group col-md-2" style="padding-right:0 !important">
                <label>To</label>
                <input type="text"  id="toDate" class="form-control date_picker lbl_move" value="<?php echo (isset($arrDate) && !is_null($arrDate['EDate'])) ? date("d-m-Y", strtotime($arrDate['EDate'])) : date('d-m-Y');?>" onchange="bindData();"/>
                <span class="date_icon"style="top:inherit;bottom:17px"><i class="fa fa-calendar"></i></span>
            </div>
            <div class="form-group col-md-2"style="padding-right:0 !important">
                <label>Task Type</label>
                <select class="form-control single_dropdown lbl_move" id="tasktypeId" style="width:100%;" onchange="bindData();">
                    <option value="0">All</option>
                    <?php foreach($arrCheckListType as $trans) { ?>
                        <option value="<?php echo $trans['TypeId']; ?>"><?php echo $trans['CheckListTypeName']; ?></option>
                    <?php } ?>
                </select>
            </div>
            <div class="form-group col-md-3" style="padding-right:0 !important">
                <label>Project</label>
                <select class="form-control single_dropdown lbl_move" id="projectId" style="width:100%;" onchange="bindData();">
                    <option value="0">All</option>
                    <?php foreach($arrProject as $trans) { ?>
                        <option value="<?php echo $trans['ProjectId']; ?>"><?php echo $trans['ProjectName']; ?></option>
                    <?php } ?>
                </select>
            </div>
            <div class="form-group col-md-3" style="padding-right:0 !important">
                <label>User</label>
                <select class="form-control single_dropdown lbl_move" id="userId" style="width:100%;" onchange="bindData();">
                    <option value="0">All</option>
                    <?php foreach($arrUser as $trans) { ?>
                        <option value="<?php echo $trans['UserId']; ?>"><?php echo $trans['UserName']; ?></option>
                    <?php } ?>
                </select>
            </div>
        </div>
        <div class="col-md-12" style="padding:0 !important">
            <div class="col-sm-3 form-group">
                <div class="filter-1 col-md-12" style="border-left:3px solid #5E2709;">
                    <div class="col-xs-3">
                        <div class="circle-icon"><i class="fa fa-tasks fa-5x" style="color:#5E2709"></i></div>
                    </div>
                    <div class="col-xs-9 pull-right">
                        <h6>Total Task</h6>
                        <p id="totTask"></p>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 form-group">
                <div class="filter-1 col-md-12" style="border-left:3px solid #0A3852;">
                    <div class="col-xs-3">
                        <div class="circle-icon circle-icon1"><i class="fa fa-gavel fa-5x" style="color:#0A3852"></i></div>
                    </div>
                    <div class="col-xs-9 pull-right">
                        <h6>To Do</h6>
                        <p id="todo"></p>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 form-group">
                <div class="filter-1 col-md-12" style="border-left:3px solid #480A52;">
                    <div class="col-xs-3">
                        <div class="circle-icon circle-icon2"><i class="fa fa-flask fa-5x" style="color:#480A52"></i></div>
                    </div>
                    <div class="col-xs-9 pull-right">
                        <h6>In Progress</h6>
                        <p id="progress"></p>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 form-group">
                <div class="filter-1 col-md-12" style="border-left:3px solid #14520A;">
                    <div class="col-xs-3">
                        <div class="circle-icon circle-icon3"><i class="fa fa-check-square-o fa-5x" style="color:#14520A"></i></div>
                    </div>
                    <div class="col-xs-9 pull-right">
                        <h6>Complete</h6>
                        <p id="completed"></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-12" style="padding:0 !important">
            <h4 class="head-4 col-md-8">List of Task</h4>
            <div class="col-md-4"> <a href="javascript:void(0);" class="butclr-ns1" id="print"><i class="fa fa-print"></i></a></div>
            <div class="col-md-12" style="padding:0 !important">
                <div id="datagrid"></div>
            </div>
        </div>
        <div class="clear clearfix"></div>
    </div>
</div>
<div class="col-lg-12">
    <a  data-text="Go Back" href="<?php echo $this->basePath(); ?>/project/communication/useractivities" class="gobacklist"><i class="fa fa-chevron-circle-left" aria-hidden="true"></i>Go Back</a>
</div>

<script>
    var arrData=[];
    $(function () {
        bindData();
    });

    function bindData() {
        var fromDate = isNullCheck($('#fromDate').val(),'date'),
            toDate = isNullCheck($('#toDate').val(),'date'),
            itasktypeId = isNullCheck($('#tasktypeId').val(),'number'),
            iProjectId = isNullCheck($('#projectId').val(),'number'),
            iUserId = isNullCheck($('#userId').val(),'number');

        arrData=[];
        $.ajax({
            url: getBaseURL() + "project/communication/gettaskdetails",
            async: false,
            type: 'post',
            data: {'fromDate': fromDate,'toDate' :toDate,'tasktypeId' : itasktypeId,'projectId' : iProjectId,'userId': iUserId},
            success: function(data,status) {
                var obj = JSON.parse(data);
                arrData = obj['details'];
                $('#totTask').text(obj['totTask']);
                $('#todo').text(obj['todo']);
                $('#progress').text(obj['progress']);
                $('#completed').text(obj['completed']);
                bindGrid();
            }
        });
    }

    function bindGrid() {
        if (arrData.length ==0) return;
        var arrtask =
        {
            async: false,
            dataType: "json",
            localdata: arrData,
            dataFields: [
                {name: 'TaskId', type: 'TaskId'},
                {name: 'CheckListTypeName', type: 'string'},
                {name: 'CheckListName', type: 'string'},
                {name: 'ProjectName', type: 'string'},
                {name: 'Specification', type: 'string'},
                {name: 'WBSName', type: 'string'},
                {name: 'Qty', type: 'number'},
                {name: 'UserName', type: 'string'},
                {name: 'CDate', type: 'date'},
                {name: 'Status', type: 'string'}
            ],
            id: 'TaskId'
        };
        var arrtasks = new $.jqx.dataAdapter(arrtask);

        $("#datagrid").jqxGrid({
            width: '100%',
            theme: 'bootstrap',
            pagerButtonsCount: 6,
            source: arrtasks,
            pageable: true,
            sortable: true,
            filterable:true,
            altrows: true,
            enabletooltips: true,
            autoheight: true,
            editable: false,
            selectionmode: 'singlerow',
            showfilterrow: true,
            columns: [
                { text: 'TaskId', datafield: 'TaskId', hidden: true},
                { text: 'Type', datafield: 'CheckListTypeName', width: '10%'  },
                { text: 'CheckListName', datafield: 'CheckListName', width: '20%'  },
                { text: 'ProjectName', datafield: 'ProjectName', width: '10%'  },
                { text: 'Specification', datafield: 'Specification', width: '15%'  },
                { text: 'WBSName', datafield: 'WBSName', width: '10%'  },
                { text: 'Qty', datafield: 'Qty', width: '5%'  },
                { text: 'UserName', datafield: 'UserName', width: '10%'  },
                { text: 'TargetDate', filtertype: 'date', datafield: 'CDate', width: '10%', cellsformat: 'dd-MM-yyyy'},
                { text: 'Status', datafield: 'Status', width: '10%'  }
            ]
        });
    }

    $("#print").click(function () {
        var repName ='Task Details';
        var gridContent = $("#datagrid").jqxGrid('exportdata', 'html');
        var newWindow = window.open('', '', 'width=800, height=500'),
            document = newWindow.document.open(),
            pageContent =
                '<!DOCTYPE html>\n' +
                '<html>\n' +
                '<head>\n' +
                '<meta charset="utf-8" />\n' +
                '<title>'+repName+'</title>\n' +
                '<h1>'+repName+'</h1>\n' +
                '</head>\n' +
                '<body>\n' + gridContent + '\n</body>\n</html>';
        document.write(pageContent);
        document.close();
        newWindow.print();

        /*$("#jqxgrid").jqxGrid('exportdata', 'html', 'jqxGrid', true, null, false);*/
    });

</script>