<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css';?>" />
<!-----scheduler js----->
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/jqxwindow.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/jqxdatetimeinput.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/jqxcalendar.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqxdate.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqxradiobutton.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqxscheduler.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqxscheduler.api.js"></script>
<!-----scheduler js end----->
<style type="text/css">
    .parent_text{height:38px !important}
    .form-control:hover, .form-control:focus{box-shadow:0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 3px 1px -2px rgba(0, 0, 0, 0.2), 0 1px 5px 0 rgba(0, 0, 0, 0.12);border:1px solid #237540}
    .action_btns {
        margin: 10px 0px 0px 0;float:right;
    }
    .butclr-ns {
        background-color: #fff;
        border: 1px solid #3399ff;
        box-shadow: none;
        border-radius: none;
        width: 35px;
        height: 35px;
    }
    .butclr {
        background: none;
        border: none;
        color: #3399ff;
        box-shadow: none;
    }
    .butclr-ns p.sam-up i {
        color: #3399ff !important;
        line-height: 34px;
        font-weight: 700
    }
    .butclr:hover,  .butclr-ns:hover {
        box-shadow: none;
    }
    .savebtn_area {
        margin: 0
    }
    .butclr-ns, .dcm_atch {
        padding:4px 0 0 5px;
    }
    .goal-bg {
        max-height: 400px;
        min-height: 200px;
        overflow-y: auto;
        padding:0 !important
    }
    .goal-bg1 {
        background:#f1f1f1;
        padding:2px 10px !important
    }
    h6.head-tt{margin-bottom: 5px;}
    .md_ok,.can_btn{ cursor: pointer;}
    .can_btn a:hover{ background:#3399ff !important; color:#fff}
    .table-fixed tbody{max-height: 300px;min-height: 200px;overflow-y: auto;width:100%}
    .table-fixed thead,.table-fixed tbody,.table-fixed tr,.table-fixed td,.table-fixed th{display:block}
    .table-fixed tbody td,.table-fixed thead>tr>th{float:left; border-bottom:0;position:relative;text-overflow:ellipsis;overflow:hidden;display:inline-block;white-space:nowrap}
    .modal-lg{width:700px}
    .tab-content{background:#fff; padding:10px 20px; border:1px solid #ddd}
    .filter-group label{width:100%; padding:5px 0}
    .form-group{margin-bottom:10px !important}
    .lbl_move{height:40px !important}
    .butclr-ns1{background: #FC3D7C;color:#fff;text-shadow: 0 0 1px #546082;width:39px; height:39px; border-radius:50%;text-align: center;padding-top:6px;float:right;font-size:16px;
        background: -webkit-linear-gradient(25deg, #FC3D7C 0%, #F76A34 80%, #F76A34 100%);
        background: -webkit-linear-gradient(65deg, #FC3D7C 0%, #F76A34 80%, #F76A34 100%);
        background: linear-gradient(25deg, #FC3D7C 0%, #F76A34 80%, #F76A34 100%);box-shadow: 0 0 0 2px #fff, 0 0 0 3px #FC3D7C;}

                    .jqx-fill-state-normal{background:#fff !important; padding:3px 6px !important;}

    .jqx-scheduler-legend-label	{color:#1070c7;font-size:14px;font-weight:400;float:left;margin-right:15px;margin-top:2px;}
    .jqx-scheduler-legend				{float:left; border:1px solid #DCDCDC!important; margin-right:5px !important;}
    .jqx-scheduler-legend 				{border-style:solid;border-width:1px;cursor:pointer;float:left;height:14px;margin-right:3px;margin-top:4px;vertical-align:middle;width:14px;}
    .jqx-scheduler-cell-hover 	    	{background:#D18EC9!important;border-color:#B56BAC!important;}
    .jqx-grid-table .jqx-grid-cell 		{border-width:0 0 1px 1px;}
    .jqx-widget .jqx-grid-cell, .jqx-widget .jqx-grid-column-header, .jqx-widget .jqx-grid-group-cell{border-color:#aaa;}
    .jqx-widget .jqx-grid-cell 			{border-color:#c2c2c2 !important;}
    .jqx-scheduler-month-weekend-cell 	{background:#DDDCE8 !important;border:1px solid #B7B6DB !important;}
    .jqx-scheduler-month-cell			{color:#000 !important;  text-align:center !important;}
    .jqx-widget-content					{background:#fff !important;;}
    .jqx-fill-state-pressed				{background:#fff !important; border-color:#3399ff; color:#3399ff!important;}
    .jqx-window-content					{padding:10px;}
    .jqx-scheduler-edit-dialog-label 	{clear:both;float:left;line-height:25px;margin-left:2%;padding:4px;text-align:right;width:20%;}
    .jqx-scheduler-edit-dialog-field 	{clear:right;float:right;margin-right:2%;padding:4px;width:70%;}
    .jqx-listitem-element				{background-color:#fff; color:#333;}
    .jqx-timepicker-hour				{width:30px;text-align:center; float:left; margin-left:5px;}
    .jqx-timepicker-minute 				{width:30px;text-align:center; float:left; }
    .jqx-timepicker-meridian			{width:30px;text-align:center; float:left; }
    .jqx-date-time-input-popup			{background:#9CF; margin:5px;}
    .jqx-popu							{background:#fff;}
    .jqx-fill-state-hover				{border:1px solid #c2c2c2; font-size:13px;}
    .jqx-combobox-content-focus-arctic, .jqx-combobox-state-focus-arctic, .jqx-fill-state-focus-arctic, .jqx-numberinput-focus-arctic {border-color:#959595;outline:medium none;}
    .jqx-icon-time:before 				{font-family:FontAwesome;content:"\f017";display:inline-block;font-size:15px;font-weight:400;color:#999A99;padding-right:3px;}
    .jqx-popup-arctic 					{border:1px solid #ccc; background:#fff;}
    .jqx-scheduler-appointment-inner-content{ font-size:14px; font-weight:400px;}
    .jqx-popup 							{box-sizing:content-box;}
    .jqx-date-time-input-popup table td a {border:1px solid transparent;color:#333;display:inline-block;margin:0;outline:0 none;padding:0;width:100%;}
    .jqx-date-time-input-popup .jqx-icon {margin-top: 0;}
    .jqx-radiobutton-check-checked-arctic {background:#808080 !important;border-radius:100%;filter:none;}
    .jqx-menu-item-top-arctic { color:#060 !important; font-size:13px;}
</style>
<div class="content_wrapper padlr0">
    <div class="container-fluid">
        <h1 class="col-md-8 text-left animated growIn">User Activities -
            <div class="btn-group proname_btn"> <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"><span id="userName"><?php echo ucfirst($userName);?></span><span class="edit_symbols" data-placement="right" data-toggle="tooltip" data-original-title="Change&nbsp;User&nbsp;Name"><i class="fa fa-caret-down "></i></span></a>
                <div class="dropdown-menu toolbar_ddown proname_ddown arrow" role="menu">
                    <ul>
                        <?php
                        if(isset($userlists)):
                            foreach($userlists as $trans):?>
                            <li><a onclick="selUser(this);" class="followupId" data-index="<?php echo $trans['UserId'];?>"><?php echo ucfirst($trans['UserName']);?></a></li>
                        <?php endforeach;
                            endif;?>
                    </ul>
                    <input type="hidden" value="<?php echo (isset($userId)) ? $userId : '0'; ?>" id="userId"/>
                </div>
            </div>
        </h1>
        <div class="col-md-4"> <a href="<?php echo $this->basePath() . '/project/communication/pcreport';?>" class="butclr-ns1"><i class="fa fa-files-o"></i></a></div>
        <div class="col-md-12 filter-group">

            <div class="form-group col-md-4" style="padding-right:0 !important">
                <label>Project</label>
                <select class="form-control single_dropdown lbl_move" style="width:100%;" id="projectId" onchange="bindData();">
                    <option value="0" selected>All</option>
                    <?php if(isset($projectlist)):
                        foreach($projectlist as $proj): ?>
                        <option value="<?php echo $proj['ProjectId'];?>"><?php echo $proj['ProjectName'];?></option>
                    <?php endforeach;
                    endif;?>
                </select>
            </div>
            <div class="form-group col-md-4"style="padding-right:0 !important">
                <label>Task Type</label>
                <select class="form-control single_dropdown lbl_move" style="width:100%;" id="tasktypeId" onchange="bindData();">
                    <option value="0" selected>All</option>
                    <?php if(isset($arrCheckListType)):
                        foreach($arrCheckListType as $trans): ?>
                        <option value="<?php echo $trans['TypeId']; ?>"><?php echo $trans['CheckListTypeName']; ?></option>
                    <?php endforeach;
                    endif;?>
                </select>
            </div>
            <div class="form-group col-md-4"style="padding-right:0 !important">
                <label>Task</label>
                <select class="form-control single_dropdown lbl_move" style="width:100%;" id="taskId" onchange="bindData();">
                    <option value="0" selected>All</option>
                </select>
            </div>
        </div>
        <!-- Nav tabs -->
        <ul class="nav nav-tabs nav-controls" role="tablist">
            <li role="presentation" class="active"><a href="#task-view" aria-controls="task-view" role="tab" data-toggle="tab">Task View</a></li>
            <li role="presentation"><a href="#calc-view" aria-controls="calc-view" role="tab" data-toggle="tab">Calendar</a></li> </ul>
        <div class="tab-content col-md-12">
            <div class="col-md-12 tab-pane active" role="tabpanel" id="task-view">
                <div class="col-md-5">
                    <div class="form-group col-md-6">
                        <label class="col-sm-4 control-label"style="text-align:right">From</label>
                        <div class="col-md-8" style="padding:0 !important">
                            <input type="text" class="form-control date_picker parent_text" id="fromDate" onchange="bindData();" value="<?php echo (isset($arrDate)) ? date('d-m-Y',strtotime($arrDate['FDate'])): date('d-m-Y');?>"/>
                            <span class="date_icon" style="top:inherit;bottom:11px"><i class="fa fa-calendar"></i></span>
                        </div>
                    </div>
                    <div class="form-group col-md-6">
                        <label class="col-sm-4 control-label" style="text-align:right">To</label>
                        <div class="col-md-8" style="padding:0 !important">
                            <input type="text" class="form-control date_picker parent_text" id="toDate" onchange="bindData();" value="<?php echo (isset($arrDate)) ? date('d-m-Y',strtotime($arrDate['EDate'])): date('d-m-Y');?>"/>
                            <span class="date_icon" style="top:inherit;bottom:11px"><i class="fa fa-calendar"></i></span>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="col-md-4 col-sm-4 animated-panel zoomIn task-wrapper">
                        <div class="col-md-12 goal-bg1">
                            <h6 class="head-tt">To Do &nbsp;(<span class="task-counter" id="todo-tasks-count"></span>)</h6>
                        </div>
                        <div class="col-md-12 goal-bg">
                            <ul class="todo" id="todo-tasks"></ul>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4 animated-panel zoomIn task-wrapper">
                        <div class="col-md-12 goal-bg1">
                            <h6 class="head-tt">In Progress &nbsp;(<span class="task-counter" id="inprogress-tasks-count"></span>)</h6>
                        </div>
                        <div class="col-md-12 goal-bg form-group ">
                            <ul class="todo" id="inprogress-tasks">
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4 animated-panel zoomIn task-wrapper">
                        <div class="col-md-12 goal-bg1">
                            <h6 class="head-tt">Completed &nbsp;(<span class="task-counter" id="completed-tasks-count"></span>)</h6>
                        </div>
                        <div class="col-md-12 goal-bg form-group ">
                            <ul class="todo" id="completed-tasks">
                            </ul>
                        </div>
                    </div>
                </div>
            </div><!---tab-1---------------->
            <div class="col-md-12 tab-pane" role="tabpanel" id="calc-view">
                <div class="col-lg-12 animated-panel zoomIn" style="margin-bottom:10px;">
                    <div id="scheduler" class="matbt-25"></div>
                </div>
            </div>
            <!--tab-2--->
        </div>
    </div>
</div>
<div class="modal fade" id="modal-taskdetail" tabindex="-1" role="dialog" aria-labelledby="largeModal" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                <h1>User Task Details</h1>
            </div>
            <div class="modal-body modal_body_min_h200" style="padding:0; background:#F0F2F2">
                <form class="form-horizontal" id="task-form" enctype="multipart/form-data">
                    <input type="hidden" name="Type" value="savehistory"/>
                    <input type="hidden" id="task-recentstatus"/>
                    <input type="hidden" name="taskid" id="task-taskid"/>
                    <input type="hidden" name="userid" id="task-userid"/>
                    <div class="col-lg-12">
                        <div class="col-md-6">
                            <div class="col-md-12" style="padding:0 !important"> <span class="hd-3" style="margin:5px 0"><b><i class="fa fa-calendar-o"></i>&nbsp;Reference:</b><span id="task-timestamp"></span></span></div>
                            <div class="col-md-12" style="padding:0 !important"> <span class="hd-3" style="margin:13px 0"><b><i class="fa fa-sort-amount-asc"></i>&nbsp;Quantity:</b><span id="task-qty"></span></span></div>
                        </div>
                        <div class="col-md-6" style=";">
                            <div class="col-md-12" style="padding:0 !important" align="right"><span class="hd-3" style="margin:5px 0;text-align:right"><b id="task-users"></b></span></div>
                            <div class="col-md-12" style="padding:0 !important;margin-bottom:15px">
                                <select class="form-control single_dropdown lbl_move" style="width:100%;" name="status" id="task-status">
                                    <option value="">None</option>
                                    <option value="P">In-Progress</option>
                                    <option value="C">Completed</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-12" style="padding:0 !important">
                            <div class="col-md-8" style="margin-bottom:5px;">
                                <label>Remarks</label>
                                <textarea class="parent_texts" name="remarks" id="task-remarks"></textarea>
                            </div>
                            <div class="col-md-4">
                                <ul class="action_btns">
                                    <li class="lft-doc atta-cls">
                                        <a style="cursor:pointer"> <span data-toggle="tooltip" data-placement="right" data-original-title="Click to attach documents" class="btn-file">
                                      <p class="sam-up butclr-ns"> <i class="fa fa-paperclip dcm_atch"></i></p>
                                      <input type="file" name="file" id="task-file"/>
                                      <label style="color:#333; font-size:13px;">Attached File</label>
                                      </span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-md-12" style="padding:0 !important">
                            <div class="col-md-4"><span class="cmd-hide"> <i class="fa fa-commenting" style="margin-right:5px; color:#3399ff; font-weight:400;font-size:18px"></i><label style="color:#333; font-size:13px;">comments</label></span></div>
                            <div class="col-lg-8 savebtn_area" style="border-top:none">
                                <ul>
                                    <li class="float_r" style="margin:11px 15px;"> <a class="md_ok" onclick="submitTaskDetails();" data-toggle="tooltip" title="" data-original-title="Submit" style="float:left">Submit <span class="ripple-wrapper"></span></a> </li>
                                    <li class="can_btn float_r" style="padding-bottom:10px;"> <a style="padding:6px 15px !important;" onclick="clearTaskDetails();">Clear</a> </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-md-12 cmd-show" style="display:none">
                            <div class="table-responsive">
                                <table class="table tab-attach table-fixed" width="100%" data-toolbar="#transform-buttons">
                                    <thead>
                                    <tr class="col-xs-12" style="padding:0 !important">
                                        <th class="col-xs-1" width="10%">User</th>
                                        <th class="col-xs-5" width="35%">Description</th>
                                        <th class="col-xs-3" width="20%">Date</th>
                                        <th class="col-xs-2" width="8%">Status</th>
                                        <th class="col-xs-1" width="2%">&nbsp;</th>
                                    </tr>
                                    </thead>
                                    <tbody id="task-history"></tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </form>
                <div class="modal-footer clear"></div>
            </div>
        </div>
    </div>
</div>
<script type="text/template" id="task-template">
    <li data-id="{{id}}" data-index="{{index}}">
        <a class="toggle-task-modal">{{name}}<p style="color:#666; font-size:13px;">{{desc}}</p></a>
        <p>{{timestamp}}</p>
    </li>
</script>
<script type="text/template" id="task-history-template" style="display:none">
    <tr class="col-xs-12">
        <td class="col-xs-1" align="center">
            <div align="center">
                <img class="circle-task" src="{{imgsrc}}"  onerror="this.src='<?php echo $this->basePath(); ?>/images/avatar.jpg';"/>
                <p style="display:block;width:100%;float:left;line-height:12px; font-size:10px;">{{username}}</p>
            </div>
        </td>
        <td class="col-xs-5"><div class="task-cnt">{{name}}<p style="font-size:13px;">{{desc}}</p></div></td>
        <td class="col-xs-3" style="color:#666">{{timestamp}}</td>
        <td class="col-xs-2"><b style="font-weight:600; color:#C60">{{status}}</b></td>
        <td class="col-xs-1" width="1%" align="center">
            <ul class="action_btns" style="margin: 0;">
                <li>
                    <a class="butclr btn-file" href="{{attachmenturl}}" data-toggle="tooltip" data-placement="top" data-original-title="Download Attachment" style="display: {{attachvisibility}}" download><i class="fa fa-download"></i></a>
                </li>
            </ul>
        </td>
    </tr>
</script>
<script type="text/javascript">
var arr_usertasklists = <?php echo(isset($usertasklists) && count($usertasklists) > 0) ? json_encode($usertasklists) : '[]'; ?>;
var $task_timestamp = $('#task-timestamp'),
    $task_qty = $('#task-qty'),
    $task_taskid = $('#task-taskid'),
    $task_userid = $('#task-userid'),
    $task_status = $('#task-status'),
    $task_users = $('#task-users'),
    $task_history = $('#task-history'),
    $task_remarks = $('#task-remarks'),
    $task_file = $('#task-file'),
    $task_recentstatus = $('#task-recentstatus');

var jqxSchedulerSource = {
    dataType: "array",
    dataFields: [
        { name: 'TaskId', type: 'string' },
        { name: 'Desc', type: 'string' },
        { name: 'location', type: 'string' },
        { name: 'CheckListName', type: 'string' },
        { name: 'UserName', type: 'string' },
        { name: 'CDate', type: 'date' },
        { name: 'Status', type: 'string' },
        { name: 'RecentStatus', type: 'string' },
        { name: 'ArrIndex', type: 'string' }
    ],
    id: 'id',
    localData: []
};

$(function() {
    renderUserTasks();

    $('.content_wrapper').on('click', '.toggle-task-modal', function () {
        var index = $(this).closest('li').attr('data-index');
        toggleTaskModal(index);
    });

    $(".cmd-show").hide();
    $(".cmd-hide").show();
    $('.cmd-hide').click(function(){
        $(".cmd-show").slideToggle();
    });

    jqxSchedulerSource.localData = [];
    $.each(arr_usertasklists, function (i,o) {
        var status = ($.trim(o.RecentStatus) == '') ? o.Status : o.RecentStatus;
        if($.trim(status) == 'C')
            return;

        o.ArrIndex = i;
        jqxSchedulerSource.localData.push(o);
    });
    var adapter = new $.jqx.dataAdapter(jqxSchedulerSource);
    $("#scheduler").jqxScheduler({
        date: new $.jqx.date('todayDate'),
        width:'100%',
        height:445,
        source: adapter,
        view: 'monthView',
        showLegend: true,
        editDialog: false,
        contextMenu: false,
        theme: 'arctic',
        timeZone:'UTC',
        ready: function () {
            $("#scheduler").jqxScheduler('ensureAppointmentVisible', 'id1');
        },
        renderAppointment: function(data) {
            var status = $.trim(data.appointment.Status);
            if(status == 'P')
                data.style = 'background: #309b46';
            else
                data.style = 'background: #25a0da';
        },
        resources:
        {
            colorScheme: "scheme05",
            dataField: "calendar",
            source:  new $.jqx.dataAdapter(jqxSchedulerSource)
        },
        appointmentDataFields:
        {
            from: "CDate",
            to: "CDate",
            id: "TaskId",
            description: "Desc",
            subject: "CheckListName",
            resourceId: "UserName",
            recentstatus: "RecentStatus",
            status: "Status",
            arrindex: "ArrIndex"
        },
        views: [
            'dayView',
            'weekView',
            { type: 'monthView', showWeekNumbers: true }
        ]
    });
    $("#scheduler").on('appointmentClick', function (event) {
        toggleTaskModal(event.args.appointment.originalData.ArrIndex);
    });
});

function renderScheduler() {
    jqxSchedulerSource.localData = [];
    $.each(arr_usertasklists, function (i,o) {
        var status = ($.trim(o.RecentStatus) == '') ? o.Status : o.RecentStatus;
        if($.trim(status) == 'C')
            return;

        o.ArrIndex = i;
        jqxSchedulerSource.localData.push(o);
    });
    var adapter = new $.jqx.dataAdapter(jqxSchedulerSource);
    $("#scheduler").jqxScheduler({source: adapter});
}

function toggleTaskModal(index) {
    if(!arr_usertasklists.hasOwnProperty(index)) {
        alert('No task details.');
        return;
    }

    $('.loading_area').show();
    $task_taskid.val(arr_usertasklists[index].TaskId);
    $task_userid.val(arr_usertasklists[index].UserId);
    $task_status.val(arr_usertasklists[index].RecentStatus).trigger('change');
    $task_users.html(arr_usertasklists[index].UserName);
    $task_timestamp.html(arr_usertasklists[index].CDate);
    $task_qty.html(sanitizeNumber(arr_usertasklists[index].Qty,3));
    $task_recentstatus.val(arr_usertasklists[index].RecentStatus);
    $task_history.html('');
    // get task history
    $.ajax({
        'url': getBaseURL() + 'project/communication/useractivities',
        'type': 'POST',
        'data': {'Type': 'gethistory','TaskId': arr_usertasklists[index].TaskId},
        success: function (data,status,xhr) {
            if(xhr.status == 200) {
                data = JSON.parse(data);
                var taskHistoryTemplate = $('#task-history-template').html();
                var arr_status = {'P': 'In-Progress', 'C': 'Completed'};
                $.each(data, function (i,o) {
                    var status = (o.Status != '') ? arr_status[o.Status] : '';
                    var fileVisibility = ($.trim(o.FileURL).length == 0) ? 'none' : 'block';
                    $task_history.append(taskHistoryTemplate.replace(/\{\{username\}\}/g, o.UserName)
                        .replace(/\{\{imgsrc\}\}/g, getBaseURL()+o.UserLogo)
                        .replace(/\{\{name\}\}/g, '')
                        .replace(/\{\{desc\}\}/g, o.Remarks)
                        .replace(/\{\{timestamp\}\}/g, o.TDate)
                        .replace(/\{\{qty\}\}/g, o.Qty)
                        .replace(/\{\{attachvisibility\}\}/g, fileVisibility)
                        .replace(/\{\{attachmenturl\}\}/g, ($.trim(o.FileURL).length != 0) ? getBaseURL().slice(0, -1)+o.FileURL : '#' )
                        .replace(/\{\{status\}\}/g, status));
                });
            }
            $('.loading_area').hide();
            $('#modal-taskdetail').modal('show');
        },
        error: function (status, error, xhr) {
            $('.loading_area').hide();
            $('#modal-taskdetail').modal('show');
        }
    });
}

function renderUserTasks() {
    // bind tasks
    var $todoTasks = $('#todo-tasks'),
        $inprogressTasks = $('#inprogress-tasks'),
        $completedTasks = $('#completed-tasks'),
        taskTemplate = $('#task-template').html();

    var todoCount= 0,
        inprogressCount = 0,
        completedCount = 0;

    $('.loading_area').show();
    $todoTasks.html('');
    $inprogressTasks.html('');
    $completedTasks.html('');
    $.each(arr_usertasklists, function(i, o) {
        var status = $.trim(o.Status);
        var recentStatus = $.trim(o.RecentStatus);
        if (recentStatus != '')
            status = recentStatus;

        switch (status) {
            case 'P':
                inprogressCount++;
                $inprogressTasks.append(taskTemplate.replace(/\{\{id\}\}/g, o.TaskId)
                    .replace(/\{\{name\}\}/g, o.CheckListName)
                    .replace(/\{\{desc\}\}/g, o.Desc)
                    .replace(/\{\{timestamp\}\}/g, o.CDate)
                    .replace(/\{\{index\}\}/g, i));
                break;
            case 'C':
                completedCount++;
                $completedTasks.append(taskTemplate.replace(/\{\{id\}\}/g, o.TaskId)
                    .replace(/\{\{name\}\}/g, o.CheckListName)
                    .replace(/\{\{desc\}\}/g, o.Desc)
                    .replace(/\{\{timestamp\}\}/g, o.CDate)
                    .replace(/\{\{index\}\}/g, i));
                break;
            default:
                todoCount++;
                $todoTasks.append(taskTemplate.replace(/\{\{id\}\}/g, o.TaskId)
                    .replace(/\{\{name\}\}/g, o.CheckListName)
                    .replace(/\{\{desc\}\}/g, o.Desc)
                    .replace(/\{\{timestamp\}\}/g, o.CDate)
                    .replace(/\{\{index\}\}/g, i));
                break;
        }
    });
    $('#todo-tasks-count').html(todoCount);
    $('#inprogress-tasks-count').html(inprogressCount);
    $('#completed-tasks-count').html(completedCount);
    $('.loading_area').hide();
}

function submitTaskDetails() {
    var remarks = $.trim($task_remarks.val());
    if(remarks.length == 0) {
        alert('Remarks is required!');
        return;
    }

    $('.loading_area').show();
    $.ajax({
        url: getBaseURL() + 'project/communication/useractivities',
        type: 'POST',
        cache: false,
        contentType: false,
        processData: false,
        data: new FormData($('#task-form')[0]),
        success: function (data,status,xhr) {
            if(xhr.status == 200) {
                alert('Saved successfully!');
                data = JSON.parse(data);
                var arr_status = {'P': 'In-Progress', 'C': 'Completed'};
                $task_history.append($('#task-history-template').html().replace(/\{\{username\}\}/g, data.UserName)
                    .replace(/\{\{imgsrc\}\}/g, data.UserLogo)
                    .replace(/\{\{name\}\}/g, '')
                    .replace(/\{\{desc\}\}/g, data.Remarks)
                    .replace(/\{\{timestamp\}\}/g, data.TDate)
                    .replace(/\{\{qty\}\}/g, data.Qty)
                    .replace(/\{\{attachvisibility\}\}/g, ($.trim(data.FileURL).length == 0) ? 'none' : 'block')
                    .replace(/\{\{attachmenturl\}\}/g, ($.trim(data.FileURL).length != 0) ? getBaseURL().slice(0, -1)+data.FileURL : '#' )
                    .replace(/\{\{status\}\}/g, (data.Status != '') ? arr_status[data.Status] : ''));

                $task_remarks.val('');
                clearInputFile($task_file);

                // on changed task status
                if($task_recentstatus.val() != data.Status) {
                    var $li = $('li[data-id='+$task_taskid.val()+']');
                    var index = $li.attr('data-index');
                    var $counter = $li.closest('.task-wrapper').find('.task-counter');
                    $counter.html(parseIntVal($counter.html()) - 1);
                    $li.remove();

                    // bind tasks
                    var $todoTasks = $('#todo-tasks'),
                        $inprogressTasks = $('#inprogress-tasks'),
                        $completedTasks = $('#completed-tasks');
                    var taskTemplate = $('#task-template').html();
                    var todoCount= $('#todo-tasks-count').html(),
                        inprogressCount = $('#inprogress-tasks-count').html(),
                        completedCount = $('#completed-tasks-count').html();

                    arr_usertasklists[index].RecentStatus = data.Status;
                    switch (data.Status) {
                        case 'P':
                            inprogressCount++;
                            $inprogressTasks.append(taskTemplate.replace(/\{\{id\}\}/g, arr_usertasklists[index].TaskId)
                                .replace(/\{\{name\}\}/g, arr_usertasklists[index].CheckListName)
                                .replace(/\{\{desc\}\}/g, arr_usertasklists[index].Desc)
                                .replace(/\{\{timestamp\}\}/g, arr_usertasklists[index].CDate)
                                .replace(/\{\{index\}\}/g, index));
                            break;
                        case 'C':
                            completedCount++;
                            $completedTasks.append(taskTemplate.replace(/\{\{id\}\}/g, arr_usertasklists[index].TaskId)
                                .replace(/\{\{name\}\}/g, arr_usertasklists[index].CheckListName)
                                .replace(/\{\{desc\}\}/g, arr_usertasklists[index].Desc)
                                .replace(/\{\{timestamp\}\}/g, arr_usertasklists[index].CDate)
                                .replace(/\{\{index\}\}/g, index));
                            break;
                        default:
                            todoCount++;
                            $todoTasks.append(taskTemplate.replace(/\{\{id\}\}/g, arr_usertasklists[index].TaskId)
                                .replace(/\{\{name\}\}/g, arr_usertasklists[index].CheckListName)
                                .replace(/\{\{desc\}\}/g, arr_usertasklists[index].Desc)
                                .replace(/\{\{timestamp\}\}/g, arr_usertasklists[index].CDate)
                                .replace(/\{\{index\}\}/g, index));
                            break;
                    }
                    $('#todo-tasks-count').html(todoCount);
                    $('#inprogress-tasks-count').html(inprogressCount);
                    $('#completed-tasks-count').html(completedCount);
                }
            } else
                alert('Error, Try again!');

            $('.loading_area').hide();
        },
        error: function (status, error, xhr) {
            alert('Error, Try again!');
            $('.loading_area').hide();
        }
    });
}

function clearTaskDetails() {
    $task_remarks.val('');
    clearInputFile($task_file);
}

function toogleTooltip() {
    var $expandDivs = $('.expandDiv');
    if ($expandDivs.length == 0)
        return;

    var $focused_el = $('textarea').filter(':focus');
    if ($focused_el.length == 0) {
        $expandDivs.removeClass('expandDiv').find('textarea').trigger('blur');
        return;
    }

    var $parent_focus = $focused_el.parents('.on-focus');
    if ($parent_focus.length != 0) {
        $expandDivs.not($parent_focus).removeClass('expandDiv');
        $expandDivs.not($parent_focus).find('textarea').trigger('blur');
        return;
    }
}

function bindData() {
    var FromDate = isNullCheck($('#fromDate').val(),'date'),
        ToDate = isNullCheck($('#toDate').val(),'date'),
        TaskTypeId = isNullCheck($('#tasktypeId').val(),'number'),
        ProjectId = isNullCheck($('#projectId').val(),'number'),
        TaskId = isNullCheck($('#taskId').val(),'number'),
        UserId = isNullCheck($('#userId').val(),'number');

    $('.loading_area').show();
    $.ajax({
        url: getBaseURL() + "project/communication/useractivities",
        async: false,
        type: 'POST',
        data: {'Type': 'getusertasklists','FromDate': FromDate,'ToDate' :ToDate,'TaskTypeId' : TaskTypeId,
            'ProjectId' : ProjectId,'TaskId': TaskId, 'UserId': UserId},
        success: function(data,status,xhr) {
            if(xhr.status == 200) {
                arr_usertasklists = JSON.parse(data);
            } else {
                arr_usertasklists = [];
            }
            renderUserTasks();
            renderScheduler();
            $('.loading_area').hide();
        },
        error: function () {
            arr_usertasklists = [];
            renderUserTasks();
            renderScheduler();
            $('.loading_area').hide();
        }
    });
}

    function selUser(x) {
        var $x = $(x);
        $('#userId').val($x.attr('data-index'));
        $('#userName').html($x.html());
        bindData();
    }
</script>