<div class="cb_login_body"></div>
<div class="cb_login_area login_area">
    <img src="<?php echo $this->basePath(); ?>/images/rabills_logo.png" class="login_logo" alt="" title="Ra-Bills" />
    <h1 class="txt_center">Payment</h1>
    <div class="success_box animated fadeIn">
        <div class="icon icon-success svg">
            <svg xmlns="http://www.w3.org/2000/svg" width="72px" height="72px">
                <g fill="none" stroke="#8EC343" stroke-width="2">
                    <circle cx="36" cy="36" r="35" style="stroke-dasharray:240px, 240px; stroke-dashoffset: 480px;"></circle>
                    <path d="M17.417,37.778l9.93,9.909l25.444-25.393" style="stroke-dasharray:50px, 50px; stroke-dashoffset: 0px;"></path>
                </g>
            </svg>
        </div>
        <h1 class="txt_center animated fadeInDown clear">
            <?php if(!isset($response)): ?>
                Sorry, Bad request!
            <?php elseif($response == '200'):?>
                Your plan has been upgraded successfully!<br /><br />
            <?php elseif($response == '404'):?>
                Sorry, Payment request not found!
            <?php elseif($response == '400'):?>
                Sorry, Internal server error occured!
            <?php endif; ?>
            <a class="gosignin_btn brad_2 ripple" href="<?php echo $this->basePath(); ?>/cb/index/dashboard">Go Dashboard</a>
        </h1>
    </div>
</div>
<div class="cb_login_footer">
    <p class="txt_center">Copyright © <?php echo date('Y'); ?> RA-Bills.com. All Rights Reserved <img class="float_r" src="<?php echo $this->basePath(); ?>/images/bsf_flogo.jpg" alt="" /></p>
</div>