<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/cb.css" />
<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
        <div class="col-lg-12">
            <h1 class="txt_center">Our pricing</h1>
            <div class="pricing_table m_btm30">
                <div class="pricing_table_inner upgrade_inner">
                    <ul class="pricetbl_column basic <?php echo (isset($UserPlan) && $UserPlan == 'a') ? 'current_plan' : ''?> <?php echo (isset($UserPlan) && ($UserPlan == 'b' || $UserPlan == 'c')) ? 'plan_disabled' : ''?>">
                        <li class="pad_t0">
                            <h2>Basic</h2>
                            <p>Best For Small Business</p>
                        </li>
                        <li class="price">
                            <p>
                                <sup>&#8377;</sup>
                                <span>2500</span>
                                <sub>/mo.</sub>
                            </p>
                        </li>
                        <li class="txt_left"><span class="pt_spanicon"><i class="fa fa-user"></i></span>1 User</li>
                        <li class="txt_left"><span class="pt_spanicon"><i class="fa fa-user-secret"></i></span>1 Clients</li>
                        <li class="txt_left"><span class="pt_spanicon"><i class="fa fa-file-text-o"></i></span>2 Bills</li>
<!--                        <li><p>Features</p></li>-->
<!--                        <li class="txt_left"><span class="pt_spanicon"><i class="fa fa-phone"></i></span>Support</li>-->
<!--                        <li class="txt_left"><span class="pt_spanicon"><i class="fa fa-newspaper-o"></i></span>Presentations</li>-->
<!--                        <li class="txt_left"><span class="pt_spanicon"><i class="fa fa-cubes"></i></span>Channels</li>-->
<!--                        <li class="txt_left"><span class="pt_spanicon"><i class="fa fa-tachometer"></i></span>Bonus Chart Side-Pack</li>-->
<!--                        <li class="txt_left"><span class="pt_spanicon"><i class="fa fa-phone"></i></span>Support</li>-->
                        <li class="selectplan_btn <?php echo (isset($UserPlan) && $UserPlan == 'a') ? 'noUpgrade' : ''?>">
                            <a href="javascript:void(0);" data-plan="a" class="btnUpgrade"><?php echo (isset($UserPlan) && $UserPlan == 'a') ? 'Current plan' : 'Upgrade'?></a>
                        </li>
                    </ul>
                    <ul class="pricetbl_column <?php echo (isset($UserPlan) && $UserPlan == 'b') ? 'current_plan' : ''?> <?php echo (isset($UserPlan) && $UserPlan == 'c') ? 'plan_disabled' : ''?>">
                        <li class="pad_t0">
                            <h2>Value</h2>
                            <p>Best For Medium Business</p>
                        </li>
                        <li class="price"
                            ><p>
                                <sup>&#8377;</sup>
                                <span>5000</span>
                                <sub>/mo.</sub>
                            </p>
                        </li>
                        <li class="txt_left"><span class="pt_spanicon"><i class="fa fa-user"></i></span>1 User</li>
                        <li class="txt_left"><span class="pt_spanicon"><i class="fa fa-user-secret"></i></span>3 Clients</li>
                        <li class="txt_left"><span class="pt_spanicon"><i class="fa fa-file-text-o"></i></span>5 Bills</li>
<!--                        <li><p>Features</p></li>-->
<!--                        <li class="txt_left"><span class="pt_spanicon"><i class="fa fa-phone"></i></span>Support</li>-->
<!--                        <li class="txt_left"><span class="pt_spanicon"><i class="fa fa-newspaper-o"></i></span>Presentations</li>-->
<!--                        <li class="txt_left"><span class="pt_spanicon"><i class="fa fa-cubes"></i></span>Channels</li>-->
<!--                        <li class="txt_left"><span class="pt_spanicon"><i class="fa fa-tachometer"></i></span>Bonus Chart Side-Pack</li>-->
<!--                        <li class="txt_left"><span class="pt_spanicon"><i class="fa fa-phone"></i></span>Support</li>-->
                        <li class="selectplan_btn <?php echo (isset($UserPlan) && $UserPlan == 'b') ? 'noUpgrade' : ''?>">
                            <a href="javascript:void(0);" data-plan="b" class="btnUpgrade <?php echo (isset($UserPlan) && $UserPlan == 'a') ? 'ripple' : '';?>"><?php echo (isset($UserPlan) && $UserPlan == 'b') ? 'Current plan' : 'Upgrade'?></a>
                        </li>
                    </ul>
                    <ul class="pricetbl_column premium <?php echo (isset($UserPlan) && $UserPlan == 'c') ? 'current_plan' : ''?>">
                        <li class="pad_t0">
                            <h2>Premium</h2>
                            <p>Best For Large Business</p>
                        </li>
                        <li class="price">
                            <p>
                                <sup>&#8377;</sup>
                                <span>10000</span>
                                <sub>/mo.</sub>
                            </p>
                        </li>
                        <li class="txt_left"><span class="pt_spanicon"><i class="fa fa-user"></i></span>1 User</li>
                        <li class="txt_left"><span class="pt_spanicon"><i class="fa fa-user-secret"></i></span>5 Clients</li>
                        <li class="txt_left"><span class="pt_spanicon"><i class="fa fa-file-text-o"></i></span>10 Bills</li>
<!--                        <li><p>Features</p></li>-->
<!--                        <li class="txt_left"><span class="pt_spanicon"><i class="fa fa-phone"></i></span>Support</li>-->
<!--                        <li class="txt_left"><span class="pt_spanicon"><i class="fa fa-newspaper-o"></i></span>Presentations</li>-->
<!--                        <li class="txt_left"><span class="pt_spanicon"><i class="fa fa-cubes"></i></span>Channels</li>-->
<!--                        <li class="txt_left"><span class="pt_spanicon"><i class="fa fa-tachometer"></i></span>Bonus Chart Side-Pack</li>-->
<!--                        <li class="txt_left"><span class="pt_spanicon"><i class="fa fa-phone"></i></span>Support</li>-->
                        <li class="selectplan_btn <?php echo (isset($UserPlan) && $UserPlan == 'c') ? 'noUpgrade' : ''?>">
                            <a href="javascript:void(0);" data-plan="c" class="btnUpgrade <?php echo (isset($UserPlan) && ($UserPlan == 'b' || $UserPlan == 'a')) ? 'ripple' : '';?>"><?php echo (isset($UserPlan) && $UserPlan == 'c') ? 'Current plan' : 'Upgrade'?></a>
                        </li>
                    </ul>
                </div>
            </div>
            <form id="upgradeForm" method="post" autocomplete="off">
                <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 m_top10 m_btm20 clear">
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        <label for="subcDuration_6m" class="col-lg-12 subcDuration_label">Subscription Duration</label>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        <div class="radio_check">
                            <p>
                                <input type="radio" value="1" name="subcriptionDuration" id="subcDuration_1m" <?php echo (isset($SubcriptionDuration) && $SubcriptionDuration == '1') ? 'checked' : 'disabled';?>/>
                                <label for="subcDuration_1m" class="ripple">1 Month</label>
                            </p>
                            <p>
                                <input type="radio" value="6" name="subcriptionDuration" id="subcDuration_6m" <?php echo (isset($SubcriptionDuration) && $SubcriptionDuration == '6') ? 'checked' : 'disabled';?>/>
                                <label for="subcDuration_6m" class="ripple">6 Months (5% Off)</label>
                            </p>
                            <p>
                                <input type="radio" value="12" name="subcriptionDuration" id="subcDuration_12m" <?php echo (isset($SubcriptionDuration) && $SubcriptionDuration == '12') ? 'checked' : 'disabled';?>/>
                                <label for="subcDuration_12m" class="ripple">12 Months (10% Off)</label>
                            </p>
                        </div>
                        <input type="hidden" name="upgradePlan" id="input-plan" value=""/>
                    </div>
                </div>
                <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 m_top10 m_btm20 clear">
                    <h1 class="text-center" id="discount_amount" style="display: none;"></h1>
                    <h1 class="text-center" id="reduce_amount" style="display: none;">(-) &#8377; <?php echo (isset($reduc_amt)) ? $reduc_amt : '';?></h1>
                    <h1 class="text-center" id="payable_amount" style="display: none;"></h1>
                    <input type="hidden" name="reduce_amt" value="<?php echo (isset($reduc_amt)) ? $reduc_amt : '';?>"/>
                </div>
                <div class="col-lg-12 m_top10 m_btm20 clear text-center">
                    <button type="button" id="btn-pay" name="pay" class="signup_btn brad_2 ripple">Pay</button>
                </div>

                <input type="hidden" name="curPlan" value="<?php echo (isset($UserPlan)) ? strtolower($UserPlan) : '';?>"/>
                <input type="hidden" name="reduceAmount" id="input-reduceamount" value="<?php echo (isset($reduc_amt)) ? $reduc_amt : '';?>"/>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    var plan = '<?php echo (isset($UserPlan)) ? strtolower($UserPlan) : '';?>';

    $(function () {
        var sysHeight = $(window).height();
        $('.success_box').css('min-height',sysHeight - 170);

        $('.selectplan_btn:not(.noUpgrade)').on('click', 'a', function () {
            $(this).closest('ul').addClass('plus_column').siblings('ul').removeClass('plus_column');
            $('#input-plan').val($(this).attr('data-plan'));
            calcDiscount();
        });

        $('input[type=radio][name=subcriptionDuration]').on('click', function () {
            calcDiscount();
        });

        $('#btn-pay').on('click', function () {
            var plan = $('#input-plan').val();
            if(plan.length == 0 || plan == "") {
                alert('Please select a plan!');
                return false;
            }

            var duration = $('input[type=radio][name=subcriptionDuration]');
            if(!duration.is(':checked')) {
                alert('Please select a duration!');
                return false;
            }

            $('.loading_area').show();
            $("#upgradeForm").submit();
        });

//        $('.btnUpgrade').on('click', function (e) {
//            e.preventDefault();
//            var upgradePlan = $(this).data('plan');
//            if((plan == 'b' && upgradePlan == 'a') || (plan == 'c' && (upgradePlan == 'b' || upgradePlan == 'a'))) {
//                return false;
//            }
//
//            $.ajax({
//                url: getBaseURL() + 'cb/plan/upgrade',
//                type: 'POST',
//                data: {'upgradePlan': upgradePlan, 'curPlan': plan},
//                success:function(data, textStatus, jqXHR){
//                    if (jqXHR.status == 200){
//                        alert('You plan has been upgraded! Thank you for purchasing!');
//                        location.reload();
//                    }
//                },
//                error:function(jqXHR, textStatus, errorThrown){
//                    alert('Failed to Add Client!');
//                }
//            });
//            return false;
//        });
    });

    function calcDiscount() {
        var plan = $('#input-plan').val();
        var $duration = $('input[type=radio][name=subcriptionDuration]');

        if(plan.length == 0 || plan == "" || !$duration.is(':checked')) {
            $('#discount_amount').html('').hide();
            return;
        }

        var subcriptionDuration = parseFloatVal($('input[type=radio][name=subcriptionDuration]:checked').val()),
            discount = 0;

        if(subcriptionDuration == 6)
            discount = 5;
        else if(subcriptionDuration == 12)
            discount = 10;

        var plan_amount = 0;
        if (plan == 'a')
            plan_amount = ((2500) * subcriptionDuration) - (((2500) * subcriptionDuration) * (discount / 100));
        else if (plan == 'b')
            plan_amount = ((5000) * subcriptionDuration) - (((5000) * subcriptionDuration) * (discount / 100));
        else if (plan == 'c')
            plan_amount = ((10000) * subcriptionDuration) - (((10000) * subcriptionDuration) * (discount / 100));

        $('#discount_amount').html('&#8377; ' + plan_amount).show();

        var reduce_amt = parseFloatVal($('#input-reduceamount').val());
        if(reduce_amt != 0) {
            $('#reduce_amount').show();
            $('#payable_amount').html('&#8377; ' + (plan_amount - reduce_amt)).show();
        } else {
            $('#reduce_amount').hide();
            $('#payable_amount').html('').hide();
        }

    }
</script>