<style>
    .jqx-grid-content {
        z-index:11!important;
    }
    .tr-header input[type=text] {font-weight:600 !important; font-size:15px !important; border:none !important; color: #015de6;}
</style>
<div class="col-lg-12">
    <form class='form-horizontal'>
        <div class='table-responsive'>
            <table class='table' style='margin-bottom:0px; background:#DAEAFF !important'>
                <tbody>
                <tr>
                    <td colspan='9' style='padding:0px !important; border:none;'><div class='subDiv'>
                            <div class="col-lg-12 col-lg-offset-0" style="margin-top:5px;">
                                <div class="radio_check createds firstStep hideStep" style="display: none">
                                    <p>
                                        <input type="checkbox" value="Concrete" <?php echo ($details['ConcreteMix'] == 1) ? 'checked' : ''; ?>>
                                        <label>Concrete Mix </label>
                                    </p>
                                    <p>
                                        <input type="checkbox" value="Cement" <?php echo ($details['Cement'] == 1) ? 'checked' : ''; ?>>
                                        <label>Cement </label>
                                    </p>
                                    <p>
                                        <input type="checkbox" value="Sand" <?php echo ($details['Sand'] == 1) ? 'checked' : ''; ?>>
                                        <label>Sand </label>
                                    </p>
                                    <p>
                                        <input type="checkbox" value="Metal" <?php echo ($details['Metal'] == 1) ? 'checked' : ''; ?>>
                                        <label>Metal </label>
                                    </p>
                                    <p>
                                        <input type="checkbox" value="Thickness" <?php echo ($details['Thickness'] == 1) ? 'checked' : ''; ?>>
                                        <label>Thickness </label>
                                    </p>
                                </div>
                                <!-- Nav tabs -->
                                <?php if($details['ConcreteMix'] == '1'): ?>
                                    <div class="darkmenu">
                                        <ul>
                                            <li class="active"><a data-toggle='tab' href="#sitemix-<?php echo $details['WorkTypeId'];?>"><i class="fa fa-caret-right"></i> Sitemix</a></li>
                                            <li><a data-toggle='tab' href="#readymix-<?php echo $details['WorkTypeId'];?>"><i class="fa fa-caret-right"></i> Readymix</a></li>
                                        </ul>
                                    </div>
                                <?php endif; ?>
                                <div class="tab-content">
                                    <!-- SiteMix-->
                                    <div class="tab-pane fade in active" id="sitemix-<?php echo $details['WorkTypeId'];?>">
                                        <!-- Tab panes -->
                                        <div class="lstate worktype_listed">
                                            <ul>
                                                <li>
                                                    <label class="lbl_style">Working Qty</label>
                                                    <input type="text" class="col-lg-2 parent_texters text-right" title="Working Qty" value="<?php echo $this->commonHelper()->sanitizeNumber($details['WorkingQty'],3);?>" readonly/>
                                                </li>
                                                <li style="display:<?php echo ($details['Cement'] == 1) ? 'block' : 'none';?>">
                                                    <label>Cement <span class="wrktype_label_span">(C)</span></label>
                                                    <input type="text" class="col-lg-2 parent_texters text-right" title="Cement (A)" value="<?php echo $this->commonHelper()->sanitizeNumber($details['CementRatio'],3);?>" readonly/>
                                                </li>
                                                <li style="display:<?php echo ($details['Sand'] == 1) ? 'block' : 'none';?>">
                                                    <label>Sand<span class="wrktype_label_span">(S)</span></label>
                                                    <input type="text" class="col-lg-2 parent_texters text-right" title="Sand (B)" value="<?php echo $this->commonHelper()->sanitizeNumber($details['SandRatio'],3);?>" readonly/>
                                                </li>
                                                <li style="display:<?php echo ($details['Metal'] == 1) ? 'block' : 'none';?>">
                                                    <label>Aggregate<span class="wrktype_label_span">(A)</span></label>
                                                    <input type="text" class="col-lg-2 parent_texters text-right" title="Metal (C)" value="<?php echo $this->commonHelper()->sanitizeNumber($details['MetalRatio'],3);?>" readonly/>
                                                </li>
                                                <li id="rateanal_<?php echo $i; ?>_thick_li" style="display:<?php echo ($details['Thickness'] == 1) ? 'block' : 'none';?>">
                                                    <label>Thickness (mm)<span class="wrktype_label_span">(T)</span></label>
                                                    <input type="text" class="col-lg-2 parent_texters text-right" title="Thickness (mm) (T)" value="<?php echo $this->commonHelper()->sanitizeNumber($details['ThickQty'],3);?>" readonly/>
                                                </li>
                                            </ul>
                                        </div>
                                        <div class="col-lg-12">
                                            <div class="table-responsive topsp animated-panel zoomIn" style="overflow: visible;animation-delay: 0.2s;">
                                                <table class="table" style="margin-bottom:0px;">
                                                    <thead>
                                                    <tr>
                                                        <th class="bg_clo_subTr">RefNo</th>
                                                        <th class="bg_clo_subTr">Resource</th>
                                                        <th class="bg_clo_subTr">Unit</th>
                                                        <th class="bg_clo_subTr">Coefficient</th>
                                                        <th class="bg_clo_subTr">Formula</th>
                                                    </tr>
                                                    </thead>
                                                    <tbody >
                                                    <?php foreach($worktypeanal as $detailsanal):
                                                        if($detailsanal['Type'] !='S')
                                                            continue;
                                                        ?>
                                                    <tr <?php if($detailsanal['TransType'] == 'H') { echo 'class="tr-header"'; } else if ($detailsanal['IncludeFlag'] == 0) { echo 'class="tr_excluded"';  } ?>>
                                                        <?php if($detailsanal['TransType'] == 'H'): ?>
                                                        <td colspan="5"><input type="text" class="parent_text" style="font-weight:bold" value="<?php echo $detailsanal['Description'];?>"></td>
                                                    <?php else: ?>
                                                        <tr <?php echo ($detailsanal['IncludeFlag'] == 0) ? 'class="tr_excluded"' : '';?>>
                                                            <td width="3%"><label>R<?php echo $detailsanal['ReferenceId'];?></label></td>
                                                            <td width="15%"><input class="parent_text" value="<?php echo $detailsanal['Code'] .' '.$detailsanal['ResourceName']; ?>" readonly/></td>
                                                            <td width="5%"><label><?php echo $detailsanal['UnitName'];?></label></td>
                                                            <td width="5%"><input type="text" class="parent_text text-right" value = "<?php echo $this->commonHelper()->sanitizeNumber($detailsanal['Qty'],3);?>" readonly/></td>
                                                            <td width="5%"><input type="text" class="parent_text" value = "<?php echo $detailsanal['CFormula'];?>" readonly /></td>
                                                        </tr>
                                                    <?php endif; ?>
                                                    <?php endforeach;?>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                    <?php if($details['ConcreteMix'] == '1'): ?>
                                        <!-- ReadyMix-->
                                        <div class="tab-pane fade" id="readymix-<?php echo $details['WorkTypeId'];?>">
                                            <!-- Tab panes -->
                                            <div class="lstate worktype_listed">
                                                <ul>
                                                    <li>
                                                        <label class="lbl_style">Working Qty</label>
                                                        <input type="text" class="col-lg-2 parent_texters text-right" title="Working Qty" value="<?php echo $this->commonHelper()->sanitizeNumber($details['RWorkingQty'],3); ?>" readonly/>
                                                    </li>
                                                </ul>
                                            </div>
                                            <div class="col-lg-12">
                                                <div class="table-responsive topsp animated-panel zoomIn" style="overflow: visible;animation-delay: 0.2s;">
                                                    <table class="table" style="margin-bottom:0px;">
                                                        <thead>
                                                        <tr>
                                                            <th class="bg_clo_subTr">RefNo</th>
                                                            <th class="bg_clo_subTr">Resource</th>
                                                            <th class="bg_clo_subTr">Unit</th>
                                                            <th class="bg_clo_subTr">Coefficient</th>
                                                            <th class="bg_clo_subTr">Formula</th>
                                                        </tr>
                                                        </thead>
                                                        <tbody >
                                                        <?php foreach($worktypeanal as $detailsanal):
                                                            if($detailsanal['Type'] !='R')
                                                                continue;?>
                                                        <tr <?php if($detailsanal['TransType'] == 'H') { echo 'class="tr-header"'; } else if ($detailsanal['IncludeFlag'] == 0) { echo 'class="tr_excluded"';  } ?>>
                                                            <?php if($detailsanal['TransType'] == 'H'): ?>
                                                            <td colspan="5"><input type="text" class="parent_text" style="font-weight:bold" value="<?php echo $detailsanal['Description'];?>"></td>
                                                        <?php else: ?>
                                                            <tr <?php echo ($detailsanal['IncludeFlag'] == 0) ? 'class="tr_excluded"' : '';?>>
                                                                <td width="3%"><label>R<?php echo $detailsanal['ReferenceId'];?></label></td>
                                                                <td width="15%"><input class="parent_text" value="<?php echo $detailsanal['Code'] .' '.$detailsanal['ResourceName']; ?>" readonly/></td>
                                                                <td width="5%"><label><?php echo $detailsanal['UnitName'];?></label></td>
                                                                <td width="5%"><input type="text" class="parent_text text-right" value = "<?php echo $this->commonHelper()->sanitizeNumber($detailsanal['Qty'],3);?>" readonly></td>
                                                                <td width="5%"><input type="text" class="parent_text" value = "<?php echo $detailsanal['CFormula'];?>" readonly></td>
                                                            </tr>
                                                        <?php endif; ?>
                                                        <?php endforeach; ?>
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </form>
</div>
