<!--STYLE-->
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css';?>"/>
<!--STYLE-->
<style>
    .savebtn_areas {
        margin-bottom:25px !important;
    }
</style>
<div class="content_wrapper padlr0">
    <div class="container-fluid">
        <div class="col-lg-12 page_tittle">
            <h1 class="text-center">Work Group Code Setup</h1>
        </div>
        <div class="col-lg-12 clear top-mar">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-2 col-md-10 col-md-offset-2 col-sm-10 col-sm-offset-2 inbotom">
                    <form class="form-horizontal" method="post" role="form" >
                        <input type="hidden" name="codefound" id="codefound" value="<?php echo ($codefound);?>">
                        <div class="row">
                            <div class="form-group">
                                <label for="inputEmail3" class="col-sm-3 control-label">Generation type</label>
                                <div class="col-sm-8">
                                    <div class="radio_check">
                                        <p style="padding-top:10px;">
                                            <input type="radio" name="gentype" id="gentypem" value="manual" <?php if ($codefound ==0 || $code['GenType']==0) echo 'checked';?> onchange="gentypeChange()">
                                            <label for="gentypem">Manual</label>
                                        </p>
                                        <p style="padding-top:10px;">
                                            <input type="radio" name="gentype" id="gentypea" value="auto" <?php if ($codefound !=0 && $code['GenType']==1) echo 'checked';?> onchange="gentypeChange()">
                                            <label for="gentypea">Auto</label>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div id="rowdiv" style="<?php echo ($code['GenType']==0) ? 'display: none' : '' ?>">
                            <div class="row">
                                <div class="form-group">
                                    <label for="prefix" class="col-sm-3 control-label">Prefix</label>
                                    <div class="col-sm-5 "> <!--req_flds class is removed-->
                                        <input type="text" class="form-control lbl_move" maxlength="10" name="prefix" value="<?php if ($codefound !=0)  echo  $code['Prefix']; else ''; ?>" id="prefix">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group" style="margin-bottom: 20px;">
                                    <label for="inputEmail3" class="col-sm-3 control-label">Include prefix of</label>
                                    <div class="col-sm-8">
                                        <div class="radio_check">
                                            <p style="padding-top:10px;">
                                                <input type="checkbox" name="ptype" id="ptype" value = "ptype" <?php if ($codefound !=0 && $code['PType']==1) echo 'checked';?>>
                                                <label for="ptype">Work Type</label>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group">
                                    <label for="suffix" class="col-sm-3 control-label">Suffix</label>
                                    <div class="col-sm-5">
                                        <input type="text" class="form-control lbl_move" maxlength="10" name="suffix" value="<?php if ($codefound !=0)  echo  $code['Suffix']; else ''; ?>" id="suffix">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group">
                                    <label for="width" class="col-sm-3 control-label">Width</label>
                                    <div class="col-sm-2 "><!--req_flds class is removed-->
                                        <input type="text" class="form-control lbl_move" name="width" value="<?php if ($codefound !=0)  echo  $code['Width']; else ''; ?>" id="width" onkeypress="return isNumberKey(event)" maxlength="1">
                                    </div>
                                    <label for="separator" class="col-sm-1 control-label" style=" text-align:left">Separator</label>
                                    <div class="col-sm-2">
                                        <input type="text" class="form-control lbl_move" name="separator" value="<?php if ($codefound !=0)  echo  $code['Separator']; else ''; ?>" id="separator" maxlength="1" onkeypress="return isSeparator(event)">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="savebtn_areas col-lg-8 col-lg-offset-4 col-md-8 col-md-offset-4 col-sm-8 col-sm-offset-3 col-xs-9 col-xs-offset-2 clear" style="border:none;">
                                <ul>
                                    <li><a href="<?php echo $this->basePath(); ?>/project/dashboard/projectmain" class="ripple">Cancel</a></li>
                                    <li class="subs"> <a href="javascript:submitForm();" class="ripple">Submit</a> </li>
                                </ul>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!--
<div class="col-lg-12 savebtn_area">
    <ul>
        <li class="dropdown save_btn float_r">
            <a href="javascript:submitForm();" data-toggle="tooltip" class="ripple" title="Submit!">Submit</a>
        </li>
        <li class="cancel_btn float_r"><a href="codesetup" class="ripple">Cancel</a></li>

    </ul>
</div>-->
<script type="text/javascript">

    function gentypeChange() {
        if ($('#gentypea').is(':checked') == true) $('#rowdiv').show();
        else $('#rowdiv').hide();
    }

    function isNumberKey(evt) {
        var charCode = (evt.which) ? evt.which : event.keyCode;

        if (charCode > 31 && (charCode < 48 || charCode > 57))
            return false;

        return true;
    }
    function submitForm() {
        $('form').submit();
    }
</script>