<style>
.company_grid li{width:30%;font-family: 'roboto', sans-serif;}
</style>
<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
        <div class="col-lg-12">
            <h1 class="col-lg-6 col-md-6 col-sm-5 padlr0">Company
            	<div class="stgedit_btn req_addbtn brad_50">
                    <a href="new-company" class="ripple" data-toggle="tooltip" data-placement="right" title="Add&nbsp;New&nbsp;Company"><i class="fa fa-plus"></i></a>
                </div>
            </h1>
            <div class="col-lg-6 col-md-6 col-sm-7 padlr0">
                <label class="col-lg-3 col-lg-offset-1 col-md-3 col-md-offset-1 col-sm-4 col-sm-offset-1 control-label text-right">Filter</label>
                <div class="col-lg-6 col-md-6 col-sm-6 m_btm10">
                	<div class="input-group col-md-12">
                        <input name="search_all" id="search_all" type="text" onkeyup="companySearch($(this).val());" class="form-control grid_search_input"/>
                        <span class="input-group-btn">
                            <button class="btn grid_search_btn" type="button">
                                <span><i class="fa fa-search" aria-hidden="true"></i></span>
                            </button>
                        </span>
                    </div>
                </div>
                <ul class="grid_change m_top10 float_r">
                    <li><a class="grid_change_line grid_change_active" href="company-grid"><span><i class="fa fa-th"></i></span></a></li>
                    <li><a class="grid_change_box" href="company-gridlist"><span><i class="fa fa-list-ul"></i></span></a></li>
                </ul>
            </div>
        </div>
        <div class="col-lg-12 clear">
            <div class="row">
                <ul class="col-lg-12 company_grid animated fadeIn">
                    <?php
                    foreach($resultsMain as $i) {?>
                        <li class="col-lg-4 col-md-6 col-sm-6 padlr0">
                            <div class="compgrid_image" style='background: url("<?php if(isset($i['CoverPhoto']) && trim($i['CoverPhoto'])!='') { echo $this->basePath(); ?>/<?php echo $i['CoverPhoto']; } else { echo $this->basePath();?>/images/companyview_cover.jpg<?php }?>");' >
                                <span class="comp_arrowlink"><a href="company-view/<?php echo $i['CompanyId'] ?>" class="ripple brad_50" data-toggle="tooltip" data-placement="right" title="View&nbsp;Profile"><i class="fa fa-gg"></i></a></span>
                                <div class="compgrid_logo brad_50 m_auto">
                                    <span><img class="brad_50" src="<?php if(isset($i['LogoPath']) && trim($i['LogoPath'])!='') { echo $this->basePath(); ?>/<?php echo $i['LogoPath']; } else { echo $this->basePath(); ?>/images/avatar.jpg<?php } ?>" /></span>
                                </div>
                                <h3 class="compgrid_title"><?php echo $i['CompanyName'];?></h3>
                            </div>
                            <div class="comp_editlink brad_50"><a href="new-company/<?php echo $i['CompanyId'] ?>" class="ripple brad_50" data-toggle="tooltip" data-placement="bottom" title="Edit&nbsp;Profile"><i class="fa fa-pencil"></i></a></div>
                            <div class="compgrid_content">
                                <div class="col-lg-6 col-sm-6 col-xs-6 padlr0">
                                    <p class="comp_address"><?php echo $i['Address'];?>,<br />

                                    </p>
									<p class="clear address-det"><span class="col-md-12 col-xs-12" style="padding:0 !important"><i class="fa fa-user"></i> &nbsp;&nbsp;<?php echo $i['ContactPerson'];?> </span><span class="vendor_phone col-md-12 col-xs-12" style="padding:0 !important"><i class="fa fa-phone"></i> &nbsp;&nbsp;<?php echo $i['Mobile'];?></span></p>
                                </div>
                                <div class="col-lg-6 col-sm-6 col-xs-6 padlr0">
                                    <div class="comp_map" style="background-image:url(<?php echo $this->basePath();?>/images/company-map1.jpg)">
                                    </div>
                                </div>
                                
                               <a href="#" class="vwstrtr_btn ripple">View Structure</a>
                            </div>
                        </li>
                    <?php
                    } ?>
                </ul>
            </div>
        </div>
    </div>
</div>
<script>
    globalTimeout = null;
    function companySearch(strSearch) {
        if (globalTimeout != null) {
            clearTimeout(globalTimeout);
        }
        globalTimeout = setTimeout(function() {
        $.ajax({
            url: getBaseURL() + 'workflow/index/company-grid',
            type: 'POST',
            data: {"searchStr": $.trim(strSearch)},
            success:function(data, textStatus, jqXHR){
                if (jqXHR.status == 200) {
                    $('.row').html('');
                    $('.row').html(data);
                } else
                    alert('Failed...');
            },
            error:function(jqXHR, textStatus, errorThrown){
                alert('Failed....');
            }
        });
            globalTimeout=null;
        }, 500);
    }
</script>