<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/vertical-timeline.css"> <!-- vertical timeline css -->
<script src="<?php echo $this->basePath(); ?>/js/vertical-timeline.js"></script> <!-- vertical timeline js-->
<script src="<?php echo $this->basePath(); ?>/js/modernizr.js"></script> <!-- Modernizr -->
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/mediaelementplayer.min.css" />
<script src="<?php echo $this->basePath(); ?>/js/mediaelement-and-player.min.js"></script>
<style>
.text-uppercase 	{text-transform:uppercase;}
</style>
<div class="content_wrapper padlr0 padtop0">
    <div class="container-fluid padlr0">
        <div class="col-lg-12 clear padlr0">
            <div class="comp_view_cover" style='background: url("<?php if(isset($resultCostCenter['CostCentreCover']) && trim($resultCostCenter['CostCentreCover'])!='') { echo $this->basePath(); ?>/<?php echo $resultCostCenter['CostCentreCover']; } else { echo $this->basePath();?>/images/companyview_cover.jpg<?php }?>");' >
                
                <div class="comp_view_logo brad_200 photomask">
                    <div class="comp_view_logo_inner brad_200">
                        <div class="blur_bg"></div>
                        <div class="brad_200 comp_vlogo">
                            <img src="<?php if(isset($resultCostCenter['CostCentreLogo']) && trim($resultCostCenter['CostCentreLogo'])!='') { echo $this->basePath(); ?>/<?php echo $resultCostCenter['CostCentreLogo']; } else { echo $this->basePath(); ?>/images/no_logo.png<?php } ?>"  class="brad_200" alt="" title=""/>
                        </div>
                        
                    </div>
                </div>
                <div class="comp_view_cnt">
                    <div class="col-lg-7 col-md-7 col-sm-7 padlr0" data-bsfshare="ContactPerson">
                        <div class="col-lg-10 col-md-10 comp_view_user">
                            <h1 data-bsfhead="CostCentreName"><span><?php echo (isset($resultCostCenter['CostCentreName'])) ? $resultCostCenter['CostCentreName'] : '';?></span></h1>
                            <p data-bsfshare="ContactPerson" class="clear"><span><i class="fa fa-user"></i></span><span><?php echo (isset($resultCostCenter['ContactPerson'])) ? $resultCostCenter['ContactPerson'] : '';?></span><span><i class="fa fa-phone"></i></span><span><?php echo (isset($resultCostCenter['Mobile'])) ? $resultCostCenter['Mobile'] : '';?></span></p>
                        </div>
                        <div class="col-lg-2 col-md-2 col-sm-2 comp_view_map padlr0">
                            <div class="comp_map" style="background-image:url(<?php echo $this->basePath();?>/images/company-map1.jpg)"></div>
                        </div>
                    </div>
                    <div class="col-lg-5 col-md-4 col-sm-4 comp_view_detail">
                        <p data-bsfshare="Address"><span class="mapaddress_icon"><i class="fa fa-map-marker"></i></span><span><?php echo (isset($resultCostCenter['Address'])) ? $resultCostCenter['Address'] : '';?></span></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-12 clear">
        <h1 data-bsfhead="Time line" class="float_l head">Time line</h1>
        <ul class="float_r cnt_innermenu">
            <li><a href="javascript:void(0);" id="timeline" class="ripple current" data-placement="bottom" data-toggle="tooltip" onclick="newInfo(this);" data-original-title="Timeline"><span class="glyphicon glyphicon-calendar"></span></a></li>
            <li><a href="javascript:void(0);" id="about" class="ripple" data-placement="bottom" data-toggle="tooltip" onclick="newInfo(this);" data-original-title="About"><span class="glyphicon glyphicon-user"></span></a></li>
            <li><a href="javascript:void(0);" id="contacts" class="ripple" data-placement="bottom" data-toggle="tooltip" onclick="newInfo(this);" data-original-title="Contacts"><span><i class="fa fa-book"></i></span></a></li>
        
            <li class="dropdown"><a href="javascript:void(0);" class="ripple dropdown-toggle" data-toggle="dropdown" title="Settings"><span class="glyphicon glyphicon-cog"></span></a>
                <!-- Link or button to toggle dropdown -->
                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                </ul>
            </li>
        </ul>
        <div class="timeline">
            <div class="cd-top-year clear">2015</div>
            <section class="cd-timeline cd-container">
                <div class="cd-timeline-block" id="testing_link1">
                    <div class="cd-timeline-main_circle cd-followup">
                        <p><i class="fa fa-phone"></i></p>
                    </div> <!-- cd-timeline-main_circle -->
        
                    <div class="cd-timeline-content">
                        <h2 data-bsfhead="Balaji Ulagananathan"><img src="<?php echo $this->basePath(); ?>/images/flwup_proimg.png" class="brad_50"> Balaji Ulagananathan</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora..</p>
                        <audio id="player1" src="http://download.tamiltunes.com/songs/2014/__A_E_By_Movies/Darling%20%282014%29/Un%20Vizhigalil%20-%20TamilTunes.com.mp3" type="audio/mp3" style="width:100%;" height="30">
                        </audio>
                        <span class="cd-date">AUG <span class="cd-date_hightlight">15</span> <span class="cd-date_time">12.45 am</span></span>
                    </div> <!-- cd-timeline-content -->
                </div> <!-- cd-timeline-block -->
        
                <div class="cd-timeline-block" id="testing_link2">
                    <div class="cd-timeline-main_circle cd-email">
                        <p><i class="fa fa-envelope"></i></p>
                    </div> <!-- cd-timeline-main_circle -->
        
                    <div class="cd-timeline-content">
                        <h2 data-bsfhead="Ranganathan Mohanraj"><img src="<?php echo $this->basePath(); ?>/images/flwup_proimg.png" class="brad_50"> Ranganathan Mohanraj</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde?</p>
                        <video height="203" id="player2" style="width:100%;" controls="controls">
                            <source src="http://clips.vorwaerts-gmbh.de/VfE_html5.mp4" type="video/mp4">
                            <source src="../media/echo-hereweare.webm" type="video/webm">
                            <p>Your browser leaves much to be desired.</p>
                        </video>
                        <span class="cd-date">JUN <span class="cd-date_hightlight">22</span> <span class="cd-date_time">11.34 pm</span></span>
                    </div> <!-- cd-timeline-content -->
                </div> <!-- cd-timeline-block -->
        
                <div class="cd-timeline-block" id="testing_link3">
                    <div class="cd-timeline-main_circle cd-sitevisit">
                        <p><i class="fa fa-desktop"></i></p>
                    </div> <!-- cd-timeline-main_circle -->
        
                    <div class="cd-timeline-content">
                        <h2 data-bsfhead="Flarexrider Mugesh"><img src="<?php echo $this->basePath(); ?>/images/flwup_proimg.png"class="brad_50"> Flarexrider Mugesh</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi, obcaecati, quisquam id molestias eaque asperiores voluptatibus cupiditate error assumenda delectus odit similique earum voluptatem doloremque dolorem ipsam quae rerum quis. Odit, itaque, deserunt corporis vero ipsum nisi eius odio natus ullam provident pariatur temporibus quia eos repellat consequuntur perferendis enim amet quae quasi repudiandae sed quod veniam dolore possimus rem voluptatum eveniet eligendi quis fugiat aliquam sunt similique aut adipisci.</p>
                        <span class="cd-date">AUG <span class="cd-date_hightlight">15</span> <span class="cd-date_time">08.21 am</span></span>
                    </div> <!-- cd-timeline-content -->
                </div> <!-- cd-timeline-block -->
        
                <div class="cd-timeline-block">
                    <div class="cd-timeline-main_circle cd-block">
                        <p><i class="fa fa-life-ring"></i></p>
                    </div> <!-- cd-timeline-main_circle -->
        
                    <div class="cd-timeline-content">
                        <h2 data-bsfhead="Harish Dhananjayan"><img src="<?php echo $this->basePath(); ?>/images/flwup_proimg.png" class="brad_50"> Harish Dhananjayan</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut.</p>
                        <span class="cd-date">FEB <span class="cd-date_hightlight">14</span> <span class="cd-date_time">2.45 pm</span></span>
                    </div> <!-- cd-timeline-content -->
                </div> <!-- cd-timeline-block -->
            </section> <!-- cd-timeline -->
        </div>
        <div class="col-lg-12 about">
            <div class="col-lg-8 col-lg-offset-2 wrkflw_cmpny_contact">
                <div class="col-lg-12">
                    <p class="txt_center">Company</p>
                    <h1 data-bsfhead="Company" class="txt_center padtop10" style="cursor:pointer;" onclick="redirectCompany();"><?php echo (isset($resultCompany)) ? $resultCompany['CompanyName'] : ''; ?></h1>
                </div>
                <div class="col-lg-12 padtop20">
                    <div class="col-lg-12">
                        <p>Branch</p>
                        <h1 data-bsfhead="Branch" class="txt_center padtop10"><?php echo (isset($resultBranch)) ? $resultBranch['BranchName'] : ''; ?></h1>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-12 padtop20 clear contacts">
            <div class="col-lg-10 col-lg-offset-1 wrkflw_cmpny_contact">
                <div class="col-lg-12">
                    <p>Contact Person</p>
                    <h1 data-bsfhead="ContactPerson" class="txt_center padtop10"><?php echo (isset($resultCostCenter)) ? $resultCostCenter['ContactPerson'] : '';?></h1>
                </div>
                <div class="col-lg-12 padtop20">
                    <div class="col-lg-4 col-md-4 col-sm-4">
                        <p>
                            <span class="wrkflw_p_spanicon"><i class="fa fa-phone"></i></span><br/>
                            <?php echo (isset($resultCostCenter)) ? $resultCostCenter['Phone'] : '';?>
                        </p>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-3">
                        <p>
                            <span class="wrkflw_p_spanicon"><i class="fa fa-fax"></i></span><br />
                            <?php echo (isset($resultCostCenter)) ? $resultCostCenter['Fax'] : '';?>
                        </p>
                    </div>
                    <div class="col-lg-5 col-md-5 col-sm-5">
                        <p>
                            <span class="wrkflw_p_spanicon"><i class="fa fa-globe "></i></span><br />
                            <a href="<?php echo (isset($resultCostCenter)) ? $resultCostCenter['Website'] : '';?>"><?php echo (isset($resultCostCenter)) ? $resultCostCenter['Website'] : '';?></a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div><input type="hidden" id="companyid" value="<?php echo (isset($companyId)) ? $companyId : '';?>" /></div>
</div>
<div id="back-top" data-toggle="tooltip" data-placement="left" title="Lift Top"><a href="#top"><i class="fa fa fa-arrow-up"></i></a></div>
<script>
    $('audio,video').mediaelementplayer({
        audioVolume:'vertical'
    });
    //top scroll
    $(document).ready(function(){
        $('a[href^="#"]').on('click',function (e) {
            e.preventDefault();
            var target = this.hash,
                $target = $(target);

            $('html, body').stop().animate({
                'scrollTop': $target.offset().top - 80
            }, 900, 'swing', function () {
                if (windscroll > 80)
                    window.location.hash = target;
            });
        });

        $("#back-top").fadeOut();
        $(window).scroll(function(){
            if ($(this).scrollTop() > 100) {
                $("#back-top").fadeIn();
            } else {
                $("#back-top").fadeOut();
            }
        });
        $("#back-top").click(function(){
            $("html, body").animate({ scrollTop: 0 }, 1000);
            return false;
        });

        $('.timeline').show();
        $('.about').hide();
        $('.contacts').hide();
    });
    function newInfo(ele) {
        var inform = $(ele)[0].id;
        $('.'+inform).show();
        $('#'+inform).addClass('current');
        switch (inform) {
            case 'about':
                $('.head').html('About');
                $('.timeline').hide();
                $('.contacts').hide();
                $('#timeline').removeClass('current');
                $('#contacts').removeClass('current');
                break;
            case 'timeline':
                $('.head').html('Time Line');
                $('.about').hide();
                $('.contacts').hide();
                $('#about').removeClass('current');
                $('#contacts').removeClass('current');
                break;
            case 'contacts':
                $('.head').html('Contacts');
                $('.timeline').hide();
                $('.about').hide();
                $('#timeline').removeClass('current');
                $('#about').removeClass('current');
                break;
            default:
                $('.head').html('Time Line');
                $('.timeline').show();
                $('.about').hide();
                $('.contacts').hide();
                $('#timeline').addClass('current');
                $('#about').removeClass('current');
                $('#contacts').removeClass('current');
                break;
        }

    }
function redirectCompany() {
    var id = $('#companyid').val();
    if(id!=0) {
        $(location).attr('href',"<?php echo $this->basePath(); ?>/workflow/index/company-view/"+id);
    } else {
        $(location).attr('href',"<?php echo $this->basePath(); ?>/workflow/index/costcenter-view");

    }
}
</script>