<?php if ($levelId !=0) { ?>
<tr id="rtDivDept" class="close_tr">
    <td colspan="3">
        <?php } else { ?>
        <div class="col-lg-12 clear" id="ocDivDept_1" style="display:none;">
            <?php } ?>
            <form method="post" action="<?php echo $this->basePath();?>/workflow/index/leveledit" id="editform">
                <input type="hidden" name="levelId" id="levelId" value="<?php echo $levelId; ?>" />
                <div class="adddprtmnt_box col-lg-12 padlr0 animated fadeInUp">
                    <button type="button" class="close mainTr" rel="rt" data-dismiss="modal" aria-label="Close"><span><i class="fa fa-times"></i></span></button>
                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <div class="col-lg-12 req_flds" style="margin-bottom:10px;margin-top:-15px">
                            <label class="col-md-2 col-sm-offset-6 col-sm-6" style="text-align:left; padding-top:16px">Level Name</label>
                            <div class="col-md-4 col-sm-offset-6 col-sm-6">
                                <input type="text" name="levelName" id="levelName" class="form-control lbl_move"  value="<?php echo $resultLevelReg['LevelName']; ?>"/>
                                <div class="error_message"><p>Please enter Level Name...</p> </div>
                            </div>
                        </div>
                    </div>
                    <div id="accordion" class="col-md-12 col-sm-12">
                        <div class="panel panel-default col-md-12 col-sm-12" style="padding:0 !important">
                            <div class="panel-heading accordion_head" role="tab" data-toggle="collapse" data-parent="#accordion" href="#ckcollapse" aria-expanded="false" aria-controls="ckcollapse">
                                <h4>Value Based Approval</h4>
                            </div>
                            <div id="ckcollapse" class="panel-collapse collapse" role="tabpanel" aria-labelledby="ckheading">
                                <div class="panel-body">
                                    <div class="col-lg-12 padlr0">
                                        <div class="col-lg-12 col-md-12 clear">
                                            <div class="headingWrapper">
                                                <section class="col-md-12" style="padding:0 !important">
                                                    <div class="input-group col-md-4 col-sm-12" style="padding:0 !important">
                                                        <input name="search_all" id="search_all" type="text" onkeyup="chkSearch(this)" class="form-control grid_search_input"/>
                                                <span class="input-group-btn">
                                                    <button class="btn grid_search_btn" type="button">
                                                        <span><i class="fa fa-search" aria-hidden="true"></i></span>
                                                    </button>
                                                </span>
                                                    </div>
                                                </section>
                                            </div>
                                            <div class="card col-xs-12"style="padding:0 !important">
                                                <div class="table-responsive" style="min-height:200px;">
                                                    <table class="table table-fixed" style="margin-bottom: 0;">
                                                        <thead>
                                                        <tr class="col-xs-12" style="padding:0 !important">
                                                            <th class="col-xs-1">&nbsp;</th>
                                                            <th class="col-xs-7">Name</th>
                                                            <th class="col-xs-2">From Value</th>
                                                            <th class="col-xs-2">To Value</th>
                                                        </tr>
                                                        </thead>
                                                        <tbody>
                                                        <?php if(isset($valueApprovalMaster)) { $irow=1;
                                                            foreach ($valueApprovalMaster as $sData) {
                                                                $iRoleId = $sData['RoleId'];
                                                                $bFound=false; $dfvalue=0;$dtvalue=0;
                                                                $arrTrans = array_filter($valueLevelTrans, function($v) use($iRoleId) { return $v['RoleId'] == $iRoleId; });
                                                                $arrkey = array_keys($arrTrans);
                                                                if (!empty($arrkey)) {
                                                                    $akey = $arrkey[0];
                                                                    $bFound = true; $dfvalue = $arrTrans[$akey]['ValueFrom'];   $dtvalue = $arrTrans[$akey]['ValueTo'];
                                                                }?>
                                                                <tr class="col-xs-12" style="padding:0 !important">
                                                                    <td class="col-xs-1"> <div class="checkbox checkbox-styled">
                                                                            <label>
                                                                                <input class="search-element"  value="1" data-name="<?php echo $sData['RoleName']; ?>" type="checkbox" id="chkcriticalrole_<?php echo $sData['RoleId'];?>" name="chkcriticalrole_<?php echo $sData['RoleId'];?>" onchange="checkValueRole(this.id)" <?php echo ($bFound==true) ? 'checked' : '';?> >
                                                                                <span>&nbsp;</span> </label>
                                                                        </div></td>
                                                                    <td class="col-xs-7"><?php echo $sData['RoleName']; ?></td>
                                                                    <td class="col-xs-2"><input class="parent_text text-right" type="text" maxlength="15" id="fromvalue_<?php echo $sData['RoleId'];?>" name="fromvalue_<?php echo $sData['RoleId'];?>" value = "<?php  echo $this->commonHelper()->sanitizeNumber($dfvalue,2); ?>" onblur="return FormatNum(this, 2,true)" onkeypress="return isDecimal(event,this)" onchange="checkfromValue(this.id)" <?php echo ($bFound==false) ? 'disabled' : '';?>/></td>
                                                                    <td class="col-xs-2"><input class="parent_text text-right" type="text" maxlength="15" id="tovalue_<?php echo $sData['RoleId'];?>" name="tovalue_<?php echo $sData['RoleId'];?>" value = "<?php  echo $this->commonHelper()->sanitizeNumber($dtvalue,2); ?>" onblur="return FormatNum(this, 2,true)" onkeypress="return isDecimal(event,this)" onchange="checktoValue(this.id)"  <?php echo ($bFound==false) ? 'disabled' : '';?>/></td>
                                                                    <input type='hidden' name='criticalroleid_<?php echo $irow; ?>' id='criticalroleid_<?php echo $irow; ?>' value='<?php echo $sData['RoleId']; ?>'>
                                                                </tr>
                                                                <?php $irow = $irow+1;}} ?>
                                                        </tbody>
                                                    </table>
                                                    <input type='hidden' name='criticalrowid' id='criticalrowid' value='<?php echo $irow; ?>'>
                                                </div>
                                            </div>
                                        </div>
                                        <!--end of scrollbar-->
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default col-md-12 col-sm-12" style="padding:0 !important">
                            <div class="panel-heading accordion_head" role="tab" data-toggle="collapse" data-parent="#accordion" href="#ckcollapse1" aria-expanded="false" aria-controls="ckcollapse1">
                                <h4>Approval for Variance</h4>
                            </div>
                            <div id="ckcollapse1" class="panel-collapse collapse" role="tabpanel" aria-labelledby="ckheading">
                                <div class="panel-body">
                                    <div class="col-lg-12 padlr0">
                                        <div class="col-lg-12 col-md-12 clear">
                                            <div class="headingWrapper">
                                                <section class="col-md-12" style="padding:0 !important">
                                                    <div class="input-group col-md-4"style="padding:0 !important">
                                                        <input name="search_all" id="search_all" type="text" onkeyup="chkSearch(this)" class="form-control grid_search_input"/>
                                <span class="input-group-btn">
                                    <button class="btn grid_search_btn" type="button">
                                        <span><i class="fa fa-search" aria-hidden="true"></i></span>
                                    </button>
                                </span>
                                                    </div>
                                                </section>
                                            </div>
                                            <div class="card col-xs-12"style="padding:0 !important">
                                                <div class="table-responsive" style="min-height:200px;">
                                                    <table class="table table-fixed" style="margin-bottom: 0;">
                                                        <thead>
                                                        <tr class="col-xs-12" style="padding:0 !important">
                                                            <th class="col-xs-1">&nbsp;</th>
                                                            <th class="col-xs-9">Name</th>
                                                            <th class="col-xs-2">Variance</th>
                                                        </tr>
                                                        </thead>
                                                        <tbody>
                                                        <?php if(isset($varianceApprovalMaster)) { $irow=1;
                                                            foreach ($varianceApprovalMaster as $sData) {
                                                                $iRoleId = $sData['RoleId'];
                                                                $bFound=false; $dvariance=0;
                                                                $arrTrans = array_filter($varianceLevelTrans, function($v) use($iRoleId) { return $v['RoleId'] == $iRoleId; });
                                                                $arrkey = array_keys($arrTrans);
                                                                if (!empty($arrkey)) {
                                                                    $akey = $arrkey[0];
                                                                    $bFound = true; $dvariance = $arrTrans[$akey]['Variant'];
                                                                }?>
                                                                <tr class="col-xs-12" style="padding:0 !important">
                                                                    <td class="col-xs-1"> <div class="checkbox checkbox-styled">
                                                                            <label>
                                                                                <input class="search-element"  value="1" data-name="<?php echo $sData['RoleName']; ?>" type="checkbox" id="chkvariancerole_<?php echo $sData['RoleId'];?>" name="chkvariancerole_<?php echo $sData['RoleId'];?>" onchange="checkVarianceRole(this.id)" <?php echo ($bFound==true) ? 'checked' : '';?> >
                                                                                <span>&nbsp;</span> </label>
                                                                        </div></td>
                                                                    <td class="col-xs-9"><?php echo $sData['RoleName']; ?></td>
                                                                    <td class="col-xs-2"><input class="parent_text text-right" type="text" maxlength="3" id="variance_<?php echo $sData['RoleId'];?>" name="variance_<?php echo $sData['RoleId'];?>" value = "<?php  echo $this->commonHelper()->sanitizeNumber($dvariance,2); ?>" onblur="return FormatNum(this, 2,true)" onkeypress="return isDecimal(event,this)" onchange="checkvarianceValue(this.id)" <?php echo ($bFound==false) ? 'disabled' : '';?> /></td>
                                                                    <input type='hidden' name='varianceroleid_<?php echo $irow; ?>' id='varianceroleid_<?php echo $irow; ?>' value='<?php echo $sData['RoleId']; ?>'>
                                                                </tr>
                                                                <?php $irow = $irow+1;}} ?>
                                                        </tbody>
                                                    </table>
                                                    <input type='hidden' name='variancerowid' id='variancerowid' value='<?php echo $irow; ?>'>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12 savebtn_area padlr0 marg0 clear">
                            <ul>
                                <li class="save_btn float_r">
                                    <button type="button" data-slide="next" data-stepno="4" data-toggle="tooltip" data-placement="left" class="ripple editSubmitBtn" title="Update">Update</button>
                                </li>
                            </ul>
                        </div>
                    </div>
            </form>
            <?php if ($levelId !=0) { ?>
    </td>
</tr>
<?php } else { ?>
    </div>
    </div>
<?php } ?>
<script>
    function checkValueRole(x) {
        var key = x.split('_')[1];
        if ($('#'+ x).is(':checked')) {
            $('#fromvalue_' + key).prop('disabled',false);
            $('#tovalue_' + key).prop('disabled',false);
        } else {
            $('#fromvalue_' + key).val('');
            $('#tovalue_' + key).val('');
            $('#fromvalue_' + key).prop('disabled',true);
            $('#tovalue_' + key).prop('disabled',true);
        }
    }
    function checkVarianceRole(x) {
        var key = x.split('_')[1];
        if ($('#'+ x).is(':checked')) {
            $('#variance_' + key).prop('disabled',false);
        } else {
            $('#variance_' + key).val('');
            $('#variance_' + key).prop('disabled',true);
        }
    }
    $(document).on('click','.editSubmitBtn',function() {
        $("#editform").submit();
    });

</script>