<style>
    .form-group{margin-bottom:10px}
    .search-container label {right: 10px;position: absolute;top: 30px;z-index:999;color:#ccc;}
    .sr-only {border: 0 none;clip: rect(0px, 0px, 0px, 0px);height: 1px; margin: -1px;overflow: hidden;padding: 0;position: absolute;      width: 1px;}
    .search-container {font-size: 18px;margin: -20px auto 0;padding-top: 20px;position: relative}
    .card {margin: 15px 0;padding: 11px;}
    .panel {margin-bottom:5px}
    .select2-container{/*border-bottom:2px solid #ccc;*/height:47px}
    .select2-container--default .select2-selection--multiple{max-height:47px}
    .accordion_head{background:#DDE3F0 !important; border-bottom:1px solid #2d74b4 !important;}
    .panel{margin-bottom:5px; box-shadow:none;background:#F0F0F5 !important; border:1px solid #DFDFE8}
    .nav > li > a:focus, .nav > li > a:hover{border:none !important}
    .nav > li > a:focus, .nav > li > a:hover,.nav-pills > li.active > a, .nav-pills > li.active > a:focus, .nav-pills > li.active > a:hover{border-bottom:2px solid #940D51 !important; background:#E6DAE0 !important;border-radius:0; font-weight:600;color:#940D51 !important}
    ul.list-head li a.active { background-color: #EBE6DD;border-bottom:2px solid #AD9568; font-weight:600;color:#523502}
    .nav-pills{background:#EBE9D8; border:1px solid #D4D496}
    .nav-pills > li > a{color:#333302}
    .table-fixed tbody{max-height:459px;min-height:20px; overflow-y:auto;width:100%}
    .table-fixed thead,.table-fixed tbody,.table-fixed tr,.table-fixed td,.table-fixed th{display:block;font-size:12px;font-family: 'roboto', sans-serif;}
    .table-fixed tbody td,.table-fixed thead>tr>th{float:left;height:50px; border-bottom:0;position:relative;overflow:hidden;display:inline-block;/*text-overflow:ellipsis;white-space:nowrap*/}
    .checkbox-styled:not(ie8) input ~ span::before, .radio-styled:not(ie8) input ~ span::before{border:2px solid #ccc}
    .back-btn{background:#fff; padding:7px 12px;color:#333; border:1px solid #ddd}
    .back-btn:hover{background:#EDE8DD;border:1px solid #9E8141; color:#523904}
    .next-bt a {background: #3580c4 none repeat scroll 0 0;border: 1px solid #3580c4; color: #ffffff;font-size: 14px;font-weight: 600;padding: 5px 10px;text-align: center;transition: all 0.4s ease 0s;}
</style>
<script id="dummy-role"  type="text/template" class="hide">
    <li class="tile ui-sortable-handle">
        <div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">
            <label>
                <input type="checkbox" data-id="" name="Role_customize__" cid="" tagname='cid1' id="Role_customize__" value="" />
                <span id="Role_name__"></span>
            </label>
        </div>
    </li>
</script>
<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
        <div class="col-lg-12">
            <h1 class="col-lg-6 col-md-6 col-sm-5 padlr0" data-bsfhead="Department">Department
                <div class="stgedit_btn req_addbtn brad_50">
                    <a href="javascript:void(0);" class="ripple mainTr" rel="oc" data-expandid="0" data-toggle="tooltip" data-placement="right" title="Add&nbsp;New&nbsp;Department" onclick="getDeptId(this);"><i class="fa fa-plus"></i></a>
                </div>
            </h1>
            <div class="col-lg-3 col-lg-offset-3 col-md-3 col-md-offset-3 col-sm-4 col-sm-offset-2 padlr0">
                <div class="input-group col-md-12">
                    <input name="search_all" id="search_all" type="text" onkeyup="departmentSearch($(this).val());" class="form-control grid_search_input"/>
                        <span class="input-group-btn">
                            <button class="btn grid_search_btn" type="button">
                                <span><i class="fa fa-search" aria-hidden="true"></i></span>
                            </button>
                        </span>
                </div>
            </div>
        </div>
        <div id="add_data">


        </div>
        <div class="col-lg-12 clear">
            <div class="table-responsive" style="min-height:200px;">
                <table class="table table-hover tbltop_bdr0">
                    <thead>
                    <tr>
                        <th width="5%">S.No</th>
                        <th width="50%">Department Name</th>
                        <th width="30%">Department Type</th>
                        <th width="15%">&nbsp;</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $k=0;
                    foreach($resultDeptReg as $resultDeptRegs):
                        $curRowDep_id =$resultDeptRegs['DeptId'];
                        $k+=1;?>
                        <tr id="index_<?php echo $k; ?>">
                            <td><?php echo $k; ?></td>
                            <td><?php echo $resultDeptRegs['Dept_Name']; ?></td>
                            <td><?php echo $resultDeptRegs['Dept_Type']; ?></td>
                            <td class="action_btns_td">
                                <ul class="action_btns">
                                    <li>
                                        <a href="javascript:void(0);" data-toggle="tooltip" data-placement="left" data-original-title="Delete" onclick="clientDelete(this, '<?php echo $resultDeptRegs['DeptId']; ?>', '<?php echo $resultDeptRegs['Dept_Name']; ?>', '<?php echo $k; ?>');">
                                            <span><i class="fa fa-trash-o"></i></span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:void(0);" data-toggle="tooltip" class="mainTr" data-expandid="<?php echo $resultDeptRegs['DeptId']; ?>" onclick="editDept('<?php echo $resultDeptRegs['DeptId']; ?>',$(this));getDeptId(this);" rel="rt" data-placement="left" data-original-title="Edit">
                                            <span><i class="fa fa-edit"></i></span>
                                        </a>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div id="AddPositionModal" class="modal fade" role="dialog" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><i class="fa fa-times-circle-o clpot"></i></button>
                <h1>Create New Position</h1>
            </div>
            <div class="modal-body col-md-12" style="background:#F0F0F5">
                <div class="col-md-8 col-md-offset-2">
                    <div class="form-group col-lg-12">
                        <label style="margin-bottom: 10px;">Position Name</label>
                        <input type="text" class="parent_text" style="height:40px;" id="newpositionname" onchange="checkPositionFound(this.value)">
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="modal-footer" style="background:#e6f2f9; border:1px solid #d8e8f1">
                <a href="javascript:void(0);" class="md_cance" data-dismiss="modal" style="position: relative; overflow: hidden;">Cancel<span class="ripple-wrapper"></span><span class="ripple-wrapper"></span></a>
                <button type="button" class="md_ok" onclick="return createNewPosition()" data-toggle="tooltip" data-original-title="Create">Create</button>
            </div>
        </div>
    </div>
</div>
<!--Delete Confirmation Modal-->
<div class="modal fade" id="DeleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h1>Why do you want to delete <span id="delDeptName" class="bld-txt"></span>?</h1>
                <input type="hidden" name="deleteDeptId" id="deleteDeptId" value="" />
            </div>
            <div class="modal-body">
                <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">
                    <form class="form-horizontal">
                        <div class="row m_tb40">
                            <div class="col-lg-12 form-group req_flds">
                                <textarea id="remarks" maxlength="250" class="form-control lbl_move" label="Enter the remarks"/>
                                </textarea>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="modal-footer clear">
                <div class="col-lg-12 savebtn_area no_border">
                    <ul>
                        <li class="save_btn float_r"> <a href="javascript:void(0);" id="btnDeleteYes" class="ripple">Delete</a> </li>
                        <li class="cancel_btn float_r"><a href="javascript:void(0);" aria-hidden="true" data-dismiss="modal" class="ripple">Cancel</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        $(".single_dropdown").select2({
            placeholder: "",
            allowClear: true
        });
        $(".multiple_dropdown").select2({
            placeholder: ""
        });
    });
</script>
<script>
$(".error_message").hide();
var $deleteModal = $('#DeleteModal'),
    $remarks = $('#remarks');
var cid = [];
var cid1 = [];
var cid2 = [];
var globalTimeout = null;
var arrPositionMaster = [];
var arrPositionTrans = [];


$(document).on('click','.mainTr',function() {
    var relDiv = $(this);
    cid = [];
    cid1 = [];
    cid2 = [];

    if(relDiv.attr('rel')=='oc') {
        $('.close_tr').remove();
        $('#add_data').html('');
        $.ajax({
            url: getBaseURL() + 'workflow/index/orgdepartmentupdate',
            type: 'POST',
            async: false,
            data: {"DepId": 0,"mode":'edit'},
            success:function(data, textStatus, jqXHR) {
                $('#add_data').html(data);
                $('.card-body').slimScroll({
                    height : '100%',
                    alwaysVisible: false,
                    railVisible: true,
                    railColor: '#cececd',
                    railOpacity: 1
                });
                $(".lbl_move").polymerForm();
                $(".lbl_move").each(function() {
                    if($(this).val() != '' && $(this).val() != null) {
                        $(this).closest('div').addClass('dirty');
                    }
                });

                $(".single_dropdown").select2({
                    placeholder: "",
                    allowClear: true
                });


                $('#ocDivDept_1').show("slow");
            },
            error:function(jqXHR, textStatus, errorThrown){
                alert('Request Failed');
            }
        });
    }
});

$(document).on('click','.panel-heading',function() {
    $('.panel-heading').removeClass('accordion_head_crnt');
    if($(this).next('div.in'))
        $(this).addClass('accordion_head_crnt');
    else
        $(this).removeClass('accordion_head_crnt');
});




$(document).on('click','input:checkbox',function() {
//    var id = $(this).attr("data-id");
//    console.log($(this).attr("tagname"),id);
//    if($(this).is(":checked")) {
//        if ($(this).attr("tagname") == 'positioncid') {
//            getPositionId(id);
//        }
//    } else {
//        if ($(this).attr("tagname") == 'positioncid') {
//            getPositionId(id);
//        }
//    }

//    var rowid = parseInt($(this).data('id'));
//    rowid++;
//    if($(this).is(":checked")){
//        if($(this).attr("tagname") == 'cid'){
//            cid.push(id);
//            $(this).closest("li").addClass('check_vendor_background');
//            $.ajax({
//                url: getBaseURL() + "workflow/index/organisationdepartment",
//                type: "POST",
//                data: {'cId': JSON.stringify(cid),'uMode' : 'role','deptId' : curDeptId},
//                success: function (data, textStatus, jqXHR) {
//                    var data = JSON.parse(data);
//                    var roleNames = data[0];
//                    var template = $('#dummy-role').html();
//                    var $tbody = $('#unCheckedUl_' + rowid);
//
//                    $('#unCheckedUl_' + rowid).html('');
//                    $('#checkedUl_' + rowid).html('');
//                    cid1=[];
//
//                    if (roleNames.length != 0) {
//                        $.each(roleNames, function (i, o) {
//                            $tbody.append(template.replace(/__/g, '_' + o.RoleId));
//                            $('#Role_customize_' + o.RoleId).val(o.RoleId);
//                            $('#Role_customize_' + o.RoleId).attr('data-id',rowid);
//                            $('#Role_customize_' + o.RoleId).attr('cid',o.RoleId);
//                            $('#Role_customize_' + o.RoleId).attr('onclick','checkSelectAll('+rowid+');');
//                            $('#Role_name_' + o.RoleId).html(o.RoleName);
//                        });
//                    } else {
//                        $('#unCheckedUl_' + rowid).html('');
//                        $('#checkedUl_' + rowid).html('');
//                    }
//
//                }
//
//            });
//        }
//        else if($(this).attr("tagname") == 'cid1'){
//            cid1.push(id);
//            $(this).closest("li").addClass('check_vendor_background');
//        }
//        else if($(this).attr("tagname") == 'cid2'){
//            cid2.push(id);
//            $(this).closest("li").addClass('check_vendor_background');
//        }
//    }
//    else{
//        //cid.splice($.inArray($(this).attr("resurceid"), resourceId),1)
//        if($(this).attr("tagname") == 'cid'){
//            cid.splice($.inArray(id, cid), 1);
//            $(this).closest("li").removeClass('check_vendor_background');
//            $.ajax({
//                url: getBaseURL() + "workflow/index/organisationdepartment",
//                type: "POST",
//                data: {'cId': JSON.stringify(cid),'uMode' : 'role','deptId' : curDeptId},
//                success: function (data, textStatus, jqXHR) {
//                    var data = JSON.parse(data);
//                    var roleNames = data[0];
//                    var template = $('#dummy-role').html();
//                    var $tbody = $('#unCheckedUl_' + rowid);
//                    $('#unCheckedUl_' + rowid).html('');
//                    $('#checkedUl_' + rowid).html('');
//                    cid1=[];
//                    if (roleNames.length != 0) {
//                        $.each(roleNames, function (i, o) {
//                            $tbody.append(template.replace(/__/g, '_' + o.RoleId));
//                            $('#Role_customize_' + o.RoleId).val(o.RoleId);
//                            $('#Role_customize_' + o.RoleId).attr('data-id',rowid);
//                            $('#Role_customize_' + o.RoleId).attr('cid',o.RoleId);
//                            $('#Role_customize_' + o.RoleId).attr('onclick','checkSelectAll('+rowid+');');
//                            $('#Role_name_' + o.RoleId).html(o.RoleName);
//                        });
//                    } else {
//                        $('#unCheckedUl_' + rowid).html('');
//                        $('#checkedUl_' + rowid).html('');
//                    }
//                }
//
//            });
//        }
//        else if($(this).attr("tagname") == 'cid1'){
//            cid1.splice($.inArray(id, cid1), 1);
//            $(this).closest("li").removeClass('check_vendor_background');
//        }
//        else if($(this).attr("tagname") == 'cid2'){
//            cid2.splice($.inArray(id, cid2), 1);
//            $(this).closest("li").removeClass('check_vendor_background');
//        }
//    }
});


$(document).on('click','#submitData',function(){
    $('#sub-hide').hide();
    $('#dept-submit-loader').show();


    $(".error_message").hide();
    if($("#deptName_0").val() == ""){
        $("#deptName_0").closest(".req_flds").find(".error_message").show();
        $("#deptName_0").focus();
        $('#sub-hide').show();
        $('#dept-submit-loader').hide();
        return;
    }

//    if($("#emailId_0").val() == ""){
//        $("#emailId_0").closest(".req_flds").find(".error_message").show();
//        $("#emailId_0").focus();
//        $('#sub-hide').show();
//        $('#dept-submit-loader').hide();
//        return;
//    }

//    if($("#emailId_0").val() != ""){
//        var emailaddress = $('#emailId_0').val();
//        var emailReg = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;
//        if(!emailReg.test(emailaddress)) {
//            $("#emailId_0").closest(".req_flds").find(".error_message").show();
//            $("#emailId_0").focus();
//            $('#sub-hide').show();
//            $('#dept-submit-loader').hide();
//            return;
//        }
//    }
    if($("#deptName_0").val() != ""){
        $valid=1;
        $.ajax({
            url: getBaseURL() + 'workflow/index/deleteorgdepartment',
            type: 'POST',
            data: {"DepId": 0, "Remarks": "", "Type": 'check',"deptName": $('#deptName_0').val() },
            async: false,
            success:function(data, textStatus, jqXHR){
                if (jqXHR.status != 200) {
                    $valid=0;
                    alert('Already Exists Department Name!');
                }
            },
            error:function(jqXHR, textStatus, errorThrown){
                //alert('Failed to delete the Department!');
                alert(textStatus+"-----"+errorThrown);
                $valid=0;
            }
        });

        if($valid==0){
            $("#deptName_0").closest(".req_flds").find(".error_message").show();
            $("#deptName_0").focus();
            $('#sub-hide').show();
            $('#dept-submit-loader').hide();
            return;
        }
    }
    //console.log(cid);
    //console.log(cid1);
    //console.log(cid2);
    $("#hidcid").val(cid);
    $("#hidcid1").val(cid1);
    $("#hidcid2").val(cid2);
    $("#addForm").submit();
});



$('#btnDeleteYes').on('click', function () {
    var remarks = $remarks.val();
    //console.log($('#delDeptName').val())
    if(remarks.length == 0) {
        showError($remarks, 'Required!');
        return;
    } else {
        removeError($remarks);
    }

    $.ajax({
        url: getBaseURL() + 'workflow/index/deleteorgdepartment',
        type: 'POST',
        data: {"DepId": $('#deleteDeptId').val(), "Remarks": remarks, "Type": 'update'},
        async: false,
        success:function(data, textStatus, jqXHR){
            if (jqXHR.status == 200) {
                $('#index_'+$deleteModal.attr('data-rowid')).remove();
                $('#rtDivDept_'+$deleteModal.attr('data-rowid')).remove();
            } else
                alert('Cannot delete this Department, it is already in use!');
        },
        error:function(jqXHR, textStatus, errorThrown){
            alert('Failed to delete the Department!');
        }
    });
    $deleteModal.modal('hide');
    $remarks.val('');
});

function clientDelete(x, id, name, indexrowId) {
    $deleteModal.attr('data-rowid', indexrowId).modal('show');
    $("#remarks").val('');
    $("#deleteDeptId").val(id);
    $('#delDeptName').html(name);
}
function getDeptId(data) {
    curDeptId = $(data).attr('data-expandid');
}

function editDept(depId,_this) {
    $('.close_tr').remove();
    $('#add_data').html('');
    $.ajax({
        url: getBaseURL() + 'workflow/index/orgdepartmentupdate',
        type: 'POST',
        async: false,
        data: {"DepId": depId,"mode":'edit'},
        success:function(data, textStatus, jqXHR){
            $(data).insertAfter(_this.closest('tr'));
            $('.card-body').slimScroll({
                height : '100%',
                alwaysVisible: false,
                railVisible: true,
                railColor: '#cececd',
                railOpacity: 1
            });
            $(".lbl_move").polymerForm();
            $(".lbl_move").each(function() {
                if($(this).val() != '' && $(this).val() != null) {
                    $(this).closest('div').addClass('dirty');
                }
            });

            $(".single_dropdown").select2({
                placeholder: "",
                allowClear: true
            });

            _this.closest('tr').next('tr').show("slow");
        },
        error:function(jqXHR, textStatus, errorThrown){
        }
    });
}
$(document).on('click','.close',function() {
    $('.close_tr').remove();
    $('#add_data').html('');
});
function selectAll(dId) {
    if($("#select_all_"+dId).is(':checked') ) {
        $('*[data-id='+dId+']:not(:checked)').trigger('click');
    }else {
        $('*[data-id='+dId+']:checked').trigger('click');
    }
}
function checkSelectAll(cId) {
    if($('*[data-id='+cId+']:checked').length != $('*[data-id='+cId+']').length) {
        $("#select_all_"+cId).prop('checked',false);
    } else {
        $("#select_all_"+cId).prop('checked',true);
    }
}
function createNewPosition() {
    var sPositionName = isNullCheck($('#newpositionname').val(),'string');
    if (sPositionName=="") { showError($('#newpositionname'), 'Enter PositionName'); return; }
    checkPositionFound(sPositionName);
    if ($('#newpositionname').hasClass('error')) return;
    newPositionUpdate(sPositionName);
    $('#AddPositionModal').modal('hide');
}

function addNewPosition() {
    $('#newpositionname').val('');
    $('#AddPositionModal').modal('show');
}

function departmentSearch(positionDetails) {
    if (globalTimeout != null) {
        clearTimeout(globalTimeout);
    }
    globalTimeout = setTimeout(function() {

        $.ajax({
            url: getBaseURL() + 'workflow/index/organisationdepartment',
            type: 'POST',
            data: {'uMode': 'searchpos','searchVal' : $.trim(positionDetails)},
            async:false,
            success: function (data, textStatus, jqXHR) {
                var posDetail = JSON.parse(data);
                $('.table tbody').html('');
                var sHtml="";
                if(posDetail.length>0) {
                    $.each(posDetail,function(j,o) {
                        var i = +j+1;
                        sHtml = sHtml + '<tr id="index_' + i + '">'+
                        '<td>' + i + '</td>' +
                        '<td>' + o.Dept_Name + '</td> ' +
                        '<td>' + o.Dept_Type + '</td> ' +
                        '<td class="action_btns_td">' +
                        '<ul class="action_btns">'+
                        '<li>'+
                        '<a href="javascript:void(0);" data-toggle="tooltip" data-placement="left" data-original-title="Delete" onclick="clientDelete(this,' + o.DeptId + ',' + o.Dept_Name + ',' + i + ');">' +
                        '<span><i class="fa fa-trash-o"></i></span>' +
                        '</a>'+
                        '</li>'+
                        '<li>'+
                        '<a href="javascript:void(0);" data-toggle="tooltip" class="mainTr" data-expandid="' + o.DeptId + '" onclick="editDept(' + o.DeptId + ',$(this));getDeptId(this);" rel="rt" data-placement="left" data-original-title="Edit">'+
                        '<span><i class="fa fa-edit"></i></span>'+
                        '</a></li></ul></td></tr>';
                    });
                }
                $('.table tbody').html(sHtml);
            },
            error: function (jqXHR, textStatus, errorThrown) {
                if (jqXHR.status == 400)
                    alert(jqXHR.responseText);
                else
                    alert("Request Failed");

            }
        });
        globalTimeout=null;
    }, 500);
}

function checkPositionFound(argPosition) {
    removeError($('#newpositionname'));
    $.ajax({
        url:getBaseURL()+ 'workflow/index/checkpositionFound',
        type:"post",
        data: {'positionId':0,'positionName':argPosition},
        async: false,
        success:function(data, textStatus, jqXHR){
            if(data == 'Y'){
                showError($('#newpositionname'), 'Position Name already found!');
                return false;
            } else{
                removeError($('#newpositionname'));
            }
        },
        error:function(jqXHR, textStatus, errorThrown){
            return false;
        }
    });
}

function newPositionUpdate(argPosition) {
    arrPositionMaster = [];
    $.ajax({
        url:getBaseURL()+ 'workflow/index/addnewposition',
        type:"post",
        data: {'positionId':0,'positionName':argPosition},
        async: false,
        success:function(data, textStatus, jqXHR){
            arrPositionMaster = JSON.parse(data);
            showPosition();
        },
        error:function(jqXHR, textStatus, errorThrown){
            return false;
        }
    });
}
function getPositionArr(id) {
    arrPositionTrans = [];
    var $ids  = $("#checkedUl_" + id + " .selId");
    $.each($ids, function (i, obj) {
        var $this = $(this),
            iPositionId = $this[0].value,
            sPositionName= "";
        var arr = $.grep(arrPositionMaster, function (element, index) {
            return element.PositionId == PositionId});
        if (arr.length >0) sPositionName = arr[0]['PositionName'];

        arrPositionTrans.push({
            PositionId: iPositionId,
            PositionName: sPositionName
        });
    });
}
function showPosition() {
    getPositionArr(1);
    var arrMPosPosition = [];
    for (var i in arrPositionMaster) {
        var arr = $.grep(arrPositionTrans, function (element, index) {
            return element.PositionId == arrPositionMaster[i].PositionId});
        if (arr.length ==0) {
            arrMPosPosition.push({
                PositionId: arrPositionMaster[i].PositionId,
                PositionName: arrPositionMaster[i].PositionName
            });
        }
    }

    $('#unCheckedUl_1').html();
    var sHtml= "";
    for (var i in arrMPosPosition) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrMPosPosition[i].PositionName + '" data-id="1" name="customize_' +  arrMPosPosition[i].PositionId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrMPosPosition[i].PositionName + '" id="customize_' + arrMPosPosition[i].PositionName + '" value="' + arrMPosPosition[i].PositionName + '_S">' +
        '<span>' + arrMPosPosition[i].PositionName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrMPosPosition[i].PositionName + '" value="' + arrMPosPosition[i].PositionId + '">'+
        '</div></li>';
    }
    $('#unCheckedUl_1').html(sHtml);
    $('#checkedUl_1').html();
    sHtml= "";
    var argPositionIds="";
    for (var i in arrPositionTrans) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle check_vendor_background search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrPositionTrans[i].PositionName + '" data-id="1" name="customize_' +  arrPositionTrans[i].PositionId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrPositionTrans[i].PositionName + '" id="customize_' + arrPositionTrans[i].PositionName + '" value="' + arrPositionTrans[i].PositionName + '_S"  checked="checked">' +
        '<span>' + arrPositionTrans[i].PositionName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrPositionTrans[i].PositionName + '" value="' + arrPositionTrans[i].PositionId + '">'+
        '</div></li>';
    }
    $('#checkedUl_1').html(sHtml);
}
</script>
