<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/workorder.css"/>
<style>
.select2-container .select2-selection--multiple,.select2-container .select2-selection--single{height:40px !important;border:1px solid #ccc !important}
</style>
<form id="reminder" method="post">
<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
        <div class="col-lg-12">
            <h1 class="col-lg-6 col-md-6 col-sm-5 padlr0" data-bsfhead="Reminder">Reminders
            	<div class="stgedit_btn req_addbtn brad_50">
                    <a href="javascript:void(0);" class="ripple mainTr" rel="oc" data-expandid="0" data-toggle="tooltip" data-placement="right" title="Add&nbsp;New&nbsp;Reminder" onclick="getDeptId(this);"><i class="fa fa-plus"></i></a>
                </div>
            </h1>
            <div class="col-lg-3 col-lg-offset-3 col-md-3 col-md-offset-3 col-sm-4 col-sm-offset-2 padlr0">
                <div class="input-group col-md-12">
                    <input name="search_all" id="search_all" type="text" onkeyup="departmentSearch($(this).val());" class="form-control grid_search_input"/>
                        <span class="input-group-btn">
                            <button class="btn grid_search_btn" type="button">
                                <span><i class="fa fa-search" aria-hidden="true"></i></span>
                            </button>
                        </span>
                </div>
            </div>
        </div>
        <div id="add_data"></div>
        <div class="col-lg-12 clear">
            <div class="table-responsive" style="min-height:200px;">
                <table class="table table-hover tbltop_bdr0">
				<?php 
					if(!empty($reminders)) { 	
						$i=1;	?>
                    <thead>
                        <tr>
                            <th width="5%">LIVE</th>
                            <th>Reminder Descrption</th>
                            <th>Reminder Date</th>
                            <th>Users</th>
                            <th>Repeat</th>
                            <th width="8%">&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
					<?php					
					foreach($reminders as $remind){ ?>
                      <tr id="remd_<?php echo $i; ?>">
                            <td>
                                <label>
								    <input type="checkbox" name="recheck" id="recheck_<?php echo $i;?>" value="1" tagname='cid' cid="<?php echo $remind['ReminderId'];?>" <?php if($remind){ echo ($remind['Type'] == 1 ? 'checked':''); }?> class="ios_checkbox"/>
                                   <!-- <input type="checkbox"  value="1" class="ios_checkbox" <?php //if($remind){ echo ($remind['Type'] == 1 ? 'checked':''); }?> onchange="return checkval('<?php //echo $i;?>','<?php //echo $remind['ReminderId'];?>')" />-->
                                    <div class="ios_switch"><span></span></div>
                                </label>
							</td>
							<input type="hidden" name="reId_<?php echo $i;?>" id="reId_<?php echo $i;?>" value="<?php echo $remind['ReminderId'];?>" />
                            <td><?php echo $remind['RDescription'];?></td>
                            <td><?php echo date('d-m-Y',strtotime($remind['RDate']));?></td>
                            <td><?php echo $remind['UserName'];?></td>
                            <td><?php  if($remind['RepeatEvery']==1) { echo "Every Month"; } else if($remind['RepeatEvery']==2) { echo "Every Weekend"; } else if($remind['RepeatEvery']==3) { echo "Every Day"; } else { echo "No Repeat"; } ?></td>
                            <td class="action_btns_td">
                                <ul class="action_btns">
                                    <li><a href="javascript:void(0);" data-toggle="tooltip" data-placement="left" data-original-title="Delete" onclick="reminderDelete(this, '<?php echo $remind['ReminderId']; ?>','<?php echo $i; ?>')">
                                            <span><i class="fa fa-trash-o"></i></span>
                                        </a>
                                    </li>
									<li>
                                        <a href="javascript:void(0);" data-toggle="tooltip" class="mainTr" data-expandid="<?php echo $remind['ReminderId']; ?>" onclick="editDept('<?php echo $remind['ReminderId']; ?>',$(this));getDeptId(this);" rel="rt" data-placement="left" data-original-title="Edit">
                                            <span><i class="fa fa-edit"></i></span>
                                        </a>
                                    </li>
                                </ul>
                            </td>
                        </tr>
					<?php $i++;}
					}?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!--Delete Confirmation Modal-->
<div class="modal fade" id="DeleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h1 data-bsfhead="Delete">Why do you want to delete <span id="delDeptName" class="bld-txt"></span>?</h1>
		<input type="hidden" name="deleteremindId" id="deleteremindId" value="" />
      </div>
      <div class="modal-body">
        <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">
          <form class="form-horizontal" onsubmit="return false;">
            <div class="row m_tb40">
              <div class="col-lg-12 form-group req_flds">
                <textarea data-bsfshare="Remarks" id="remarks" maxlength="250" class="form-control lbl_move" label="Enter the remarks"/>
                </textarea>
              </div>
            </div>
          </form>
        </div>
      </div>
      <div class="modal-footer clear">
        <div class="col-lg-12 savebtn_area no_border">
          <ul>
            <li class="save_btn float_r"> <a href="javascript:void(0);" id="btnDeleteYes" class="ripple">Delete</a> </li>
            <li class="cancel_btn float_r"><a href="javascript:void(0);" aria-hidden="true" data-dismiss="modal" class="ripple">Cancel</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
</form>
<script>
$(document).ready(function() {
    $(".single_dropdown").select2({
        allowClear: false,
        placeholder: ""
    });
  });

$('.addnew_reminder').click(function (){
	$('.adddprtmnt_box').show("slow");
});
$('.close').click(function(){
	$('.adddprtmnt_box').hide();
});
</script>
<script>
//form validation//

$(".error_message").hide();
var $deleteModal = $('#DeleteModal'),
$remarks = $('#remarks');

//$('.save').click(function(){
//
//	if ($("#r_description").val() <= 0) {
//		showError($("#r_description"), 'Description is required!');
//		return false;
//    } else {
//        removeError($("#r_description"));
//    }
//    if ($("#r_date").val() <= 0) {
//		showError($("#r_date"), 'Date is required!');
//		return false;
//    } else {
//        removeError($("#r_date"));
//    }
//    if($("#r_users").val() <= 0) {
//		showError($("#r_users"), 'User is required!');
//		return false;
//    } else {
//        removeError($("#r_users"));
//    }
//    $("#reminder").submit();
//	$('.adddprtmnt_box').hide();
//});

$("input:checkbox").click(function(){
   var id = $(this).attr("cid");
	if($(this).is(":checked")){			
		var checkr=1;}
		else{
		var checkr=0;}
		$.ajax({
			url:getBaseURL()+"workflow/index/reminder",
			type:"post",
			data:"rCheck="+checkr+"&remindId="+id,
		success:function(data,textStatus,jqXHR){}});
	});

$(document).on('click','.close',function() {
    $('.close_tr').remove();
    $('#add_data').html('');
});


$('#btnDeleteYes').on('click', function () {
		var remarks = $("#remarks").val();
		
		if(remarks.length == 0) {
			showError($("#remarks"), 'Required!');
			return;
		} else {
			removeError($("#remarks"));
		}

		$.ajax({
			url: getBaseURL() + 'workflow/index/reminder-delete',
			type: 'POST',
			data: {"RegisterId":$('#deleteremindId').val(), "Remarks": remarks},
            async: false,
			success:function(data, textStatus, jqXHR){
				if (jqXHR.status == 200) {
					$('#remd_'+$('#DeleteModal').attr('data-rowid')).remove();
					
                } else
					alert('Cannot delete this reminder!');
			},
			error:function(jqXHR, textStatus, errorThrown){
                alert('Failed to delete the Department!');
			}
		});		
		$('#DeleteModal').modal('hide');
		$("#remarks").val('');		
	});
	
function reminderDelete(x, id,indexrowId) {
	$('#DeleteModal').attr('data-rowid', indexrowId).modal('show');
	$("#deleteremindId").val(id);
	$("#remarks").val('');
}
$(document).on('click','.mainTr',function() {
    var relDiv = $(this);
    if(relDiv.attr('rel')=='oc') {
        $('.close_tr').remove();
        $('#add_data').html('');
        $.ajax({
            url: getBaseURL() + 'workflow/index/reminderedit',
            type: 'POST',
            async: false,
            data: {"reminderId": 0,"ActionType":'Edit'},
            success:function(data, textStatus, jqXHR) {
                $('#add_data').html(data);
                $('.card-body').slimScroll({
                    height : '100%',
                    alwaysVisible: false,
                    railVisible: true,
                    railColor: '#cececd',
                    railOpacity: 1
                });
                $(".lbl_move").polymerForm();
                $(".lbl_move").each(function() {
                    if($(this).val() != '' && $(this).val() != null) {
                        $(this).closest('div').addClass('dirty');
                    }
                });
                $(".single_dropdown").select2({
                    placeholder: "",
                    allowClear: true
                });
                $('#ocDivDept_1').show("slow");
            },
            error:function(jqXHR, textStatus, errorThrown){
                alert('Request Failed');
            }
        });
    }
});
function getDeptId(data) {
    curDeptId = $(data).attr('data-expandid');
}
function editDept(Id,_this) {
    $('.close_tr').remove();
    $('#add_data').html('');
    $.ajax({
        url: getBaseURL() + 'workflow/index/reminderedit',
        type: 'POST',
        async: false,
        data: {'reminderId': Id,'ActionType':'Edit'},
        success:function(data, textStatus, jqXHR){
            $(data).insertAfter(_this.closest('tr'));
            $('.card-body').slimScroll({
                height : '100%',
                alwaysVisible: false,
                railVisible: true,
                railColor: '#cececd',
                railOpacity: 1
            });
            $(".lbl_move").polymerForm();
            $(".lbl_move").each(function() {
                if($(this).val() != '' && $(this).val() != null) {
                    $(this).closest('div').addClass('dirty');
                }
            });
            _this.closest('tr').next('tr').show("slow");
        },
        error:function(jqXHR, textStatus, errorThrown){
        }
    });
}
</script>