<style>
    .result{padding: 20px;font-size: 16px;background-color:  #ccc;color: #fff;}
    .search-container label {right: 10px;position: absolute;top: 30px;z-index:999;color:#ccc;}
    .sr-only {border: 0 none;clip: rect(0px, 0px, 0px, 0px);height: 1px;margin: -1px;overflow: hidden;padding: 0;position: absolute;     width: 1px;}
    .search-container {font-size: 18px;margin: -20px auto 10px;padding-top: 20px;position: relative;}
    .input-group{margin-bottom:15px}
    .card12{max-height:342px; min-height:342px; overflow-y:auto; margin-bottom:5px}
    .cont_bt,.savebtn_areas1{background:#fff;padding:0 0 10px 0;border:1px solid #ddd; border-top:none;border-left:none;margin-top:-10px}
    .cont_bt{border-top:none;float:left;margin-top:-14px; border-right:none;padding:0px 0;border-left:1px solid #ddd;z-index:999}
    .back-btn{background:#fff; padding:7px 12px;color:#333; border:1px solid #ddd}
    .back-btn:hover{background:#EDE8DD;border:1px solid #9E8141; color:#523904}
    .form-group1{margin-bottom:8px;}
    .form-group1 label{font-size:14px; margin-bottom:4px}
    .accordion_head{background:#DDE3F0 !important; border-bottom:1px solid #2d74b4 !important;}
    .panel{margin-bottom:5px; box-shadow:none;background:#F0F0F5 !important; border:1px solid #DFDFE8}
    ul.list-head li a.active { background-color: #EBE6DD;border-bottom:2px solid #AD9568; font-weight:600;box-shadow:none;color:#523502}
    .checkbox, .radio{margin:0 0 0 10px}
    .checkbox-styled:not(ie8) input ~ span::before, .radio-styled:not(ie8) input ~ span::before{border:2px solid #ccc}
    .table-fixed tbody{max-height:459px;min-height:20px; overflow-y:auto;width:100%}
	 .table-fixed tbody td{font-size:14px}
    .table-fixed thead,.table-fixed tbody,.table-fixed tr,.table-fixed td,.table-fixed th{display:block;font-size:12px;font-family: 'roboto', sans-serif;}
    .table-fixed tbody td,.table-fixed thead>tr>th{float:left;height:50px; border-bottom:0;position:relative;overflow:hidden;display:inline-block;/*text-overflow:ellipsis;white-space:nowrap*/}
</style>
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css';?>" />
<script src="<?php echo $this->basePath(); ?>/js/modernizr.js"></script><!-- Modernizr -->
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/css/component.css" />
<script id="dummy-role"  type="text/template" class="hide">
    <li class="tile ui-sortable-handle">
        <div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">
            <label>
                <input type="checkbox" data-id="" name="Role_customize__" cid="" tagname='cid1' id="Role_customize__" value="" />
                <span id="Role_name__"></span>
            </label>
        </div>
    </li>
</script>
<script id="dummy-alert"  type="text/template" class="hide">
    <li class="tile ui-sortable-handle">
        <div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">
            <label>
                <input type="checkbox" data-id="" name="Alert_customize__" tagname='cid2' cid="" id="Alert_customize__" value="" />
                <span id="Alert_name__" ></span>
            </label>
        </div>
    </li>
</script>
<script id="dummy-activity"  type="text/template" class="hide">
    <li class="tile ui-sortable-handle">
        <div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">
            <label>
                <input type="checkbox" data-id="" name="Activity_customize__" tagname='cid' cid="" id="Activity_customize__" value="" />
                <span id="Activity_name__" ></span>
            </label>
        </div>
    </li>
</script>
<div class="content_wrapper padlr0">
<div class="container-fluid padlr0">
<div class="col-lg-12">
    <h1 data-bsfhead="User Details">User Details &nbsp;
        <div class="btn-group prfon">
            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"><?php if(isset($userdtl)) { echo $UserName['UserName'];  } else{ echo "";} ?><span class="edit_symbols" data-placement="right" data-toggle="tooltip" data-original-title="User&nbsp;Name&nbsp"><i class="fa fa-caret-down "></i></span></a>
            <div class="dropdown-menu toolbar_ddown proname_ddown arrow" role="menu">
                <ul>
                    <?php foreach($arr_user as $user){?>
                        <li><a href="javascript:void(0);" class="urId" data-index="<?php echo $user['UserId'];?>"><?php echo ucfirst($user['UserName']);?></a></li>
                    <?php }	?>
                </ul>
            </div>
        </div>
    </h1>
</div>
<div class="col-lg-12 col-xs-12 col-sm-12 clear padlr0">
    <div id="cover_display" class="comp_view_cover" >
        <!--div class="compcover_change brad_50" style="opacity:1;">
                    <a class="file_link" href="javascript:void(0);"><span><i class="fa fa-camera"></i></span></a>
                    <input type="file" class="hide_file_input" name="comp_cover_photo" value="" id="comp_cover_photo" onchange="showcoverpreview(this);"/>
                </div-->
        <div class="comp_view_logo brad_200 photomask">
            <div class="comp_view_logo_inner brad_200">
                <div class="blur_bg camera_hide" style="opacity:1;"></div>
                <div class="brad_200 comp_vlogo"><img src="<?php if(isset($resultsMain['UserLogo']) && trim($resultsMain['UserLogo'])!='') { echo $this->basePath(); ?>/<?php echo $resultsMain['UserLogo']; } else { echo $this->basePath(); ?>/images/no-img1.jpg<?php } ?>" id="imgprvw"  class="brad_200" alt="" title=""/></div>
                <p> <a class="file_link" href="javascript:void(0);" style="opacity:1; left:50px;" ><span><i class="fa fa-camera camera_hide" ></i></span></a>
                    <input type="file" id="filephoto" class="hide_file_input" name="logo" value="" onchange="showimagepreview(this);"/>
                </p>
            </div>
        </div>
        <div class="comp_view_cnt">
            <div class="col-lg-6 col-md-6 col-sm-6 padlr0">
                <div class="col-lg-9 col-md-9 comp_view_user">
                    <h1 id="ename"><?php echo (isset($resultsMain['EmployeeName'])) ? $resultsMain['EmployeeName'] : 'Employee Name';?></h1>
                    <p class="clear"><span><i class="fa fa-suitcase"></i></span> <span id="pos">
                <?php if(isset($resultsMain['PositionId']) && isset($positionIdDetails)) { foreach($positionIdDetails as $posi) { if($posi['PositionId'] == $resultsMain['PositionId']) { echo $posi['PositionName']; } } } else { echo 'Position'; }?>
                </span><span class="vendor_phone"><i class="fa fa-flag-o"></i></span><span id="dept">
                <?php if(isset($resultsMain['Dept_Name'])) { echo $resultsMain['Dept_Name']; }  else { echo 'Department'; }?>
                </span></p>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-3 comp_view_map padlr0">
                    <div class="comp_map" style="background-image:url(<?php echo $this->basePath();?>/images/company-map1.jpg)"></div>
                </div>
            </div>
            <div class="col-lg-5 col-md-4 col-sm-4 comp_view_detail">
                <p class="clear"><span class="mapaddress_icon"><i class="fa fa-industry"></i></span><i class="fa fa-address" id="lev">
                        <?php if(isset($resultsMain['LevelName'])) { echo $resultsMain['LevelName']; } else { echo 'Level'; }?>
                    </i> </p>
            </div>
        </div>
    </div>
</div>
<div class="col-md-12 col-xs-12 col-sm-12" style="margin-top:40px">
<?php
$userDate = '';
if(isset($resultsMain['UserDob'])) {
    $userDate = date('d-m-Y', strtotime($resultsMain['UserDob']));
} ?>
<div id="accordion" class="panel-group">
<div class="panel panel-default col-md-12 col-xs-12 col-sm-12" style="padding:0 !important">
<div class="panel-heading accordion_head" role="tab" data-toggle="collapse" data-parent="#accordion" href="#ckcollapse" aria-expanded="true" aria-controls="ckcollapse" id="panelheading-1">
    <h4>General Details</h4>
</div>
<div id="ckcollapse" class="panel-collapse collapse" role="tabpanel" aria-labelledby="ckheading">
<div class="panel-body">
<div class="col-lg-12 col-xs-12 col-sm-12 padlr0" id="euser_details">
    <div class="form-horizontal form-group1">
        <div class="row">
            <div class="form-group1 col-lg-6 col-md-6 col-sm-6"  style="<?php echo ($userId==0) ? 'display:none' : ''; ?>">
                <div class="col-lg-10 col-lg-offset-1">
                    <label> User Name</label>
                    <input data-bsfshare=" User Name" type="text" name="euserName" id="euserName" class="form-control lbl_move" value="<?php echo (isset($resultsMain)) ? $resultsMain['UserName'] : '';?>"/>
                </div>
            </div>
            <div class="form-group1 col-lg-6 col-md-6 col-sm-6" style="<?php echo ($userId==0) ? 'display:none' : ''; ?>">
                <div class="col-lg-10 col-lg-offset-1">
                    <label>Employee Name</label>
                    <input data-bsfshare="Employee Name" type="text" name="eempname" id="eempname" class="form-control lbl_move" value="<?php echo (isset($resultsMain)) ? $resultsMain['EmployeeName'] : '';?>"/>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-group1 col-lg-6 col-md-6 col-sm-6" style="<?php echo ($userId==0) ? 'display:none' : ''; ?>">
                <div class="col-lg-10 col-lg-offset-1">
                    <label>Date of Birth</label>
                    <input data-bsfshare="Date of Birth" type="text" name="euser_dob" id="euser_dob" class="form-control lbl_move date_picker" value="<?php echo $userDate;?>"/>
                    <div class="error_message">
                        <p>Required</p>
                    </div>
                </div>
            </div>
            <div class="form-group1 col-lg-6 col-md-6 col-sm-6" style="<?php echo ($userId==0) ? 'display:none' : ''; ?>">
                <div class="col-lg-10 col-lg-offset-1 req_flds">
                    <label for="CostCentre_default">Department</label>
                    <select class="single_dropdown lbl_move" id="edepartment" style="width:100%;" >
                        <?php
                        if(isset($departmentDetails)) {
                            foreach ($departmentDetails as $posId) {
                                ?>
                                <option <?php if(isset($resultsMain) && $resultsMain['DeptId'] == $posId['DeptId']) { echo 'selected' ; } ?> value="<?php echo $posId['DeptId']; ?>"><?php echo $posId['Dept_Name']; ?></option>
                            <?php
                            }
                        }?>
                    </select>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-group1 col-lg-6 col-md-6 col-sm-6" style="<?php echo ($userId==0) ? 'display:none' : ''; ?>">
                <div class="col-lg-10 col-lg-offset-1 req_flds">
                    <label for="CostCentre_default">Position</label>
                    <select class="single_dropdown lbl_move" id="eposition" name="eposition" style="width:100%;" >
                        <?php
                        if(isset($positionIdDetails)) {
                            foreach ($positionIdDetails as $posId) {
                                ?>
                                <option <?php if(isset($resultsMain) && $resultsMain['PositionId'] == $posId['PositionId']) { echo 'selected' ; } ?> value="<?php echo $posId['PositionId']; ?>"><?php echo $posId['PositionName']; ?></option>
                            <?php
                            }
                        }?>
                    </select>
                </div>
            </div>
            <div class="form-group1 col-lg-6 col-md-6 col-sm-6" style="<?php echo ($userId==0) ? 'display:none' : ''; ?>">
                <div class="col-lg-10 col-lg-offset-1 req_flds">
                    <label>Level</label>
                    <select class="single_dropdown lbl_move" id="elevel" name="elevel" style="width:100%;" >
                        <?php
                        if(isset($levelDetails)) {
                            foreach ($levelDetails as $posId) {
                                ?>
                                <option <?php if(isset($resultsMain) && $resultsMain['LevelId'] == $posId['LevelId']) { echo 'selected' ; } ?> value="<?php echo $posId['LevelId']; ?>"><?php echo $posId['LevelName']; ?></option>
                            <?php
                            }
                        }?>
                    </select>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-group1 col-lg-6 col-md-6 col-sm-6" style="<?php echo ($userId==0) ? 'display:none' : ''; ?>">
                <div class="col-lg-10 col-lg-offset-1 req_flds">
                    <label for="CostCentre_default">Power User</label>
                    <select class="single_dropdown lbl_move" name="epoweruser" id="epoweruser" style="width:100%;" >
                        <option value="0" <?php if(isset($resultsMain) && $resultsMain['PowerUser'] == 0) { echo 'selected' ; } ?>>No</option>
                        <option value="1" <?php if(isset($resultsMain) && $resultsMain['PowerUser'] == 1) { echo 'selected' ; } ?>>Yes</option>
                    </select>
                </div>
            </div>
            <div class="form-group1 col-lg-6 col-md-6 col-sm-6" style="<?php echo ($userId==0) ? 'display:none' : ''; ?>">
                <div class="col-lg-10 col-lg-offset-1">
                    <label> Phone number</label>
                    <input data-bsfshare=" phone number" type="text" name="ephone_num" maxlength="10" onKeyPress="return isNumberKey(event)" id="ephone_num" class="form-control lbl_move" value="<?php echo (isset($resultsMain['Phone'])) ? $resultsMain['Phone'] : '';?>"/>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-group1 col-lg-6 col-md-6 col-sm-6" style="<?php echo ($userId==0) ? 'display:none' : ''; ?>">
                <div class="col-lg-10 col-lg-offset-1">
                    <label>Mobile number</label>
                    <input data-bsfshare="mobile number" type="text" name="emobile" id="emobile" maxlength="10" onKeyPress="return isNumberKey(event)" class="form-control lbl_move" value="<?php echo (isset($resultsMain['Mobile'])) ? $resultsMain['Mobile'] : '';?>"/>
                </div>
            </div>
            <div class="form-group1 col-lg-6 col-md-6 col-sm-6" style="<?php echo ($userId==0) ? 'display:none' : ''; ?>">
                <div class="col-lg-10 col-lg-offset-1">
                    <label>Address</label>
                    <input data-bsfshare="address" type="text" name="eaddress" id="eaddress" class="form-control lbl_move"  value="<?php echo (isset($resultsMain['Email'])) ? $resultsMain['Email'] : '';?>"/>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-group1 col-lg-6 col-md-6 col-sm-6" style="<?php echo ($userId==0) ? 'display:none' : ''; ?>">
                <div class="col-lg-10 col-lg-offset-1">
                    <label> Email address</label>
                    <input data-bsfshare="email address" type="text" name="eemail_address" id="eemail_address" class="form-control lbl_move" value="<?php echo (isset($resultsMain['Email'])) ? $resultsMain['Email'] : '';?>"/>
                </div>
            </div>
            <div class="form-group1 col-lg-6 col-md-6 col-sm-6" style="<?php echo ($userId==0) ? 'display:none' : ''; ?>">
                <div class="col-lg-10 col-lg-offset-1 req_flds">
                    <label>Default CostCentre</label>
                    <select name="edcostcentre" id="edcostcentre" class="single_dropdown lbl_move"  style="width:100%;">
                        <?php
                        if(isset($costcentreMaster)) {
                            foreach ($costcentreMaster as $trans) {
                                ?>
                                <option value="<?php echo $trans['CostCentreId']; ?>"><?php echo $trans['CostCentreName']; ?></option>
                            <?php
                            }
                        }?>
                    </select>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="savebtn_areas col-lg-8 col-lg-offset-4 col-md-8 col-md-offset-4 col-sm-8 col-sm-offset-3 col-xs-9 col-xs-offset-2 clear" style="border:none;">
                <ul>
                    <li class="subs" style="float:right"> <a class="ripple has-ripple" id = "enextid" href="javascript:clickNext();" style="<?php echo ($userId==0) ? 'display:none' : ''; ?>">Next</a> </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="col-lg-12 clear stephide">
    <div id="user_details" class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1" style="padding-bottom:90px;">
        <div class="row">
            <section>
                <form id="theForm" class="simform" autocomplete="off" method="post" enctype="multipart/form-data">
                    <div class="simform-inner">
                        <ul class="questions">
                            <li> <span>
                    <label for="userName">What is your User Name ?</label>
                    </span>
                                <input data-bsfshare="User Name" data-validate="usercheck" id="userName" onchange="nameCheck(this);" name="userName" value="<?php echo (isset($resultsMain)) ? $resultsMain['UserName'] : '';?>" type="text" />
                            </li>
                            <li> <span>
                    <label for="empname">Enter Employee Name</label>
                    </span>
                                <input data-bsfshare="Employee Name" id="empname" name="empname" value="<?php echo (isset($resultsMain)) ? $resultsMain['EmployeeName'] : '';?>" type="text"/>
                            </li>
                            <li> <span>
                    <label for="user_dob">Date of Birth</label>
                    </span>
                                <input data-bsfshare="User Dob" class="date_picker" id="user_dob" name="user_dob" data-validate="novalidate" value="<?php echo $userDate;?>" type="text" readonly />
                            </li>
                            <li> <span>
                    <label for="position">What is your Department?</label>
                    </span>
                                <select name="department" id="department" class="single_dropdown" onchange="loadPosition(this);" style="width:93%;" >
                                    <option></option>
                                    <?php
                                    if(isset($departmentDetails)) {
                                        foreach ($departmentDetails as $posId) {
                                            ?>
                                            <option <?php if(isset($resultsMain) && $resultsMain['DeptId'] == $posId['DeptId']) { echo 'selected' ; } ?> value="<?php echo $posId['DeptId']; ?>"><?php echo $posId['Dept_Name']; ?></option>
                                        <?php
                                        }
                                    }?>
                                </select>
                            </li>
                            <li> <span>
                    <label for="position">What is your Position?</label>
                    </span>
                                <select name="position" id="position" class="single_dropdown"  style="width:93%;" >
                                    <option></option>
                                    <?php
                                    if(isset($positionIdDetails)) {
                                        foreach ($positionIdDetails as $posId) {
                                            ?>
                                            <option <?php if(isset($resultsMain) && $resultsMain['PositionId'] == $posId['PositionId']) { echo 'selected' ; } ?> value="<?php echo $posId['PositionId']; ?>"><?php echo $posId['PositionName']; ?></option>
                                        <?php
                                        }
                                    }?>
                                </select>
                            </li>
                            <li> <span>
                    <label for="levelname">What is your Level?</label>
                    </span>
                                <select name="level" id="level" class="single_dropdown"  style="width:93%;" >
                                    <option></option>
                                    <?php
                                    if(isset($levelDetails)) {
                                        foreach ($levelDetails as $posId) {
                                            ?>
                                            <option <?php if(isset($resultsMain) && $resultsMain['LevelId'] == $posId['LevelId']) { echo 'selected' ; } ?> value="<?php echo $posId['LevelId']; ?>"><?php echo $posId['LevelName']; ?></option>
                                        <?php
                                        }
                                    }?>
                                </select>
                            </li>
                            <li> <span>
                    <label for="superior">Power User</label>
                    </span>
                                <select class="single_dropdown lbl_move" name="poweruser" id="poweruser" style="width:93%;" >
                                    <option></option>
                                    <option value="0">No</option>
                                    <option value="1">Yes</option>
                                </select>
                            </li>
                            <li> <span>
                    <label for="phone_num">What is your phone number ?</label>
                    </span>
                                <input data-bsfshare="Phone" id="phone_num" name="phone_num" value="<?php echo (isset($resultsMain['Phone'])) ? $resultsMain['Phone'] : '';?>" maxlength="10" onKeyPress="return isNumberKey(event)" data-validate="novalidate"  type="text"/>
                            </li>
                            <li> <span>
                    <label for="mobile">What is your mobile number ?</label>
                    </span>
                                <input data-bsfshare="Mobile" id="mobile" name="mobile" maxlength="10" onchange="numCheck(this);" onKeyPress="return isNumberKey(event)" value="<?php echo (isset($resultsMain['Mobile'])) ? $resultsMain['Mobile'] : '';?>"  type="text"/>
                            </li>
                            <li> <span>
                    <label for="address">What is your address ?</label>
                    </span>
                                <input data-bsfshare="Address" id="address" name="address" value="<?php echo (isset($resultsMain['Address'])) ? $resultsMain['Address'] : '';?>" type="text"/>
                            </li>
                            <li> <span>
                    <label for="email_address">What is your email address ?</label>
                    </span>
                                <input data-bsfshare="Email" id="email_address" name="email_address" value="<?php echo (isset($resultsMain['Email'])) ? $resultsMain['Email'] : '';?>" data-validate="novalidate" type="text"/>
                                <div class="error_message" id="hidewebsite" style="display: block;right:10%"><p style="text-align:right;padding:11px 0;color:#E66C02 !important;font-weight:600">(Sample: samplewf123@gmail.com)</p></div></li>
                            <li> <span>
                            <label for="superior">Default CostCentre</label>
                            </span>
                                <select name="dcostcentre" id="dcostcentre" class="single_dropdown"  style="width:93%;" >
                                    <option></option>
                                    <?php
                                    if(isset($costcentreMaster)) {
                                        foreach ($costcentreMaster as $trans) {
                                            ?>
                                            <option value="<?php echo $trans['CostCentreId']; ?>"><?php echo $trans['CostCentreName']; ?></option>
                                        <?php
                                        }
                                    }?>
                                </select>
                            </li>
                        </ul>
                        <!-- /questions -->
                        <button class="submit" type="button">Send answers</button>
                        <div class="controls">
                            <button class="next continue" onclick="formChange();" ></button>
                            <div class="progress"></div>
                            <span class="number"> <span class="number-current"></span> <span class="number-total"></span> </span> <span class="error-message"></span> </div>
                        <!-- / controls -->
                    </div>
                    <!-- /simform-inner -->
                    <span class="final-message"></span>
                    <!--                            </form>-->
                    <!-- /simform -->
                </form>
            </section>
        </div>
    </div>
</div>
</div>
</div>
</div>
<div class="panel panel-default col-md-12 col-xs-12 col-sm-12" style="padding:0 !important">
<div class="panel-heading accordion_head" role="tab" data-toggle="collapse" data-parent="#accordion" href="#ckcollapse1" aria-expanded="true" aria-controls="ckcollapse1" id="panelheading-2">
    <h4>Permission</h4>
</div>
<div id="ckcollapse1" class="panel-collapse collapse" role="tabpanel" aria-labelledby="ckheading">
<div class="panel-body">
<div class="col-lg-12 col-xs-12 col-sm-12 padlr0">
<div class="col-md-5 col-lg-3 col-sm-6">
    <ul class="list-head col-md-12" style="background:#fff">
        <li id="per_superior"><a href="javascript:showSuperior();">Superior Users</a></li>
        <li id="per_alternate"><a href="javascript:showAlternate();">Alternate Users</a></li>
        <li id="per_team"><a href="javascript:showTeam();">Team</a></li>
        <li id="per_activity"><a href="javascript:showActivity();">Activity</a></li>
        <li id="per_role"><a href="javascript:showRole();">Roles</a></li>
        <li id="per_permission"><a href="javascript:showRolePermission();">Permission</a></li>
        <li id="per_variance"><a href="javascript:showVariance();">Variance</a></li>
        <li id="per_alert"><a href="javascript:showAlert();">Alert</a></li>
        <li id="per_company"><a href="javascript:showCompany();">Company</a></li>
        <li id="per_costcentre"><a href="javascript:showCostCentre();">CostCentre</a></li>
        <li id="per_project"><a href="javascript:showProject();">Projects</a></li>
        <li id="per_worktype"><a href="javascript:showWorkType();">WorkType</a></li>
        <li id="per_resourcetype"><a href="javascript:showResourceType();">ResourceType</a></li>
        <li id="per_resourcegroup"><a href="javascript:showResourceGroup();">ResourceGroup</a></li>
        <li id="per_servicetype"><a href="javascript:showServiceType();">ServiceType</a></li>
        <li id="per_account"><a href="javascript:showAccount();">AccountHead</a></li>
        <li id="per_accounttype"><a href="javascript:showAccountType();">AccountType</a></li>
        <li id="per_subledgertype"><a href="javascript:showSubLedgerType();">SubLedgerType</a></li>
        <li id="per_informalert"><a href="javascript:showinformAlert();">Alert Inform by</a></li>
        <li id="per_informpendingwork"><a href="javascript:showinformPendingwork();">Pending Work Inform by</a></li>
    </ul>
</div>
<div class="col-md-7 col-lg-9 col-sm-6">
<div class="col-md-12 card card12">
<!--                        activity-->
<div class="col-lg-12 padlr0 divPermission" id="divactivity" style="display: none">
    <div class="col-lg-6 col-sm-12">
        <div class="headingWrapper">
            <p class="heading_checkbox" id="searchTitle1"></p>
            <section class="search-container">
                <label> <i class="fa fa-search" aria-hidden="true"></i> <span class="sr-only">Search icons</span> </label>
                <input class="form-control lbl_move height25" type="text" onkeyup="chkSearch(this)" placeholder="Search... ">
            </section>
        </div>
        <div class="card">
            <div class="card-body"style="min-height:50px; max-height:310px;">
                <!--checkboxtabel-->
                <ul class="sampleUI list ui-sortable lilen_1" data-sortable="true" id="unCheckedUl_1"></ul>
                <!--end of checkboxtabel-->
            </div>
            <div class="pull-right">
                <div class="radio_check">
                    <p>
                        <input type="checkbox" class="mycheck_1" value="1" id="select_all_1" onclick="selectAll('1');" />
                        <label for="select_all_1" class="ripple">Select all</label>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <!--end of scrollbar-->
    <div class="col-lg-6 col-sm-12">
        <div class="headingWrapper">
            <p class="heading_checkbox" id="searchTitle2"></p>
            <section class="search-container">
                <label> <i class="fa fa-search" aria-hidden="true"></i> <span class="sr-only">Search icons</span> </label>
                <input class="form-control lbl_move height25" onkeyup="chkSearch(this)" type="text" placeholder="Search... ">
            </section>
        </div>
        <div class="card">
            <div class="card-body" style="min-height:50px; max-height:310px;">
                <!--checkboxtabel-->
                <ul class="sampleUI list ui-sortable sellen_1" data-sortable="true" id="checkedUl_1"></ul>
                <!--end of checkboxtabel-->
            </div>
        </div>
    </div>

</div>

<!--                        Role-->
<div class="col-lg-12 padlr0 divPermission" id="divrole" style="display: none">
    <div class="headingWrapper">
        <section class="col-md-12">
            <div class="input-group col-md-4 col-md-offset-8" style="margin-bottom:15px;">
                <input name="search_all" id="search_all" type="text" onkeyup="chkSearchtr(this)" class="form-control grid_search_input"/>
                                <span class="input-group-btn">
                                    <button class="btn grid_search_btn" type="button">
                                        <span><i class="fa fa-search" aria-hidden="true"></i></span>
                                    </button>
                                </span>
            </div>
        </section>
    </div>
    <div class="card col-xs-12" style="padding:0 !important">
        <div class="table-responsive topsp">
            <table class="table table-fixed" style="margin-bottom:0px;" id="taskTable" >
                <thead>
                <tr class="col-xs-12" style="padding:0 !important">
                    <th class="col-xs-7" width="50%">Task Name</th>
                    <th class="col-xs-1" width="10%">Create</th>
                    <th class="col-xs-1" width="10%">Edit</th>
                    <th class="col-xs-1" width="10%">Delete</th>
                    <th class="col-xs-1" width="10%">Approve</th>
                    <th class="col-xs-1" width="10%">View</th>
                </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>

<!--                        Permission-->
<div class="col-lg-12 padlr0 divPermission" id="divpermissionrole" style="display: none">
    <div class="col-lg-12 col-md-12 clear">
        <div class="headingWrapper">
            <section class="col-md-12">
                <div class="input-group col-md-offset-8 col-md-4">
                    <input name="search_all" id="search_all" type="text" onkeyup="chkSearchtr(this)" class="form-control grid_search_input"/>
                                <span class="input-group-btn">
                                    <button class="btn grid_search_btn" type="button">
                                        <span><i class="fa fa-search" aria-hidden="true"></i></span>
                                    </button>
                                </span>
                </div>
            </section>
        </div>
        <div class="card col-xs-12" style="padding:0 !important">
            <div class="table-responsive" style="min-height:200px;">
                <table class="table table-fixed" style="margin-bottom: 0;" id="roleTable">
                    <thead>
                    <tr class="col-xs-12" style="padding:0 !important">
                        <th class="col-xs-1">&nbsp;</th>
                        <th class="col-xs-11">Name</th>
                    </tr>
                    </thead>
                    <tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!--                        Variance-->
<div class="col-lg-12 padlr0 divPermission" id="divvariance" style="display: none">
    <div class="col-lg-12 col-md-12 clear">
        <div class="headingWrapper">
            <section class="col-md-12">
                <div class="input-group col-md-offset-8 col-md-4">
                    <input name="search_all" id="search_all" type="text" onkeyup="chkSearchtr(this)" class="form-control grid_search_input"/>
                                <span class="input-group-btn">
                                    <button class="btn grid_search_btn" type="button">
                                        <span><i class="fa fa-search" aria-hidden="true"></i></span>
                                    </button>
                                </span>
                </div>
            </section>
        </div>
        <div class="card col-xs-12" style="padding:0 !important">
            <div class="table-responsive" style="min-height:200px;">
                <table class="table table-fixed" style="margin-bottom: 0;" id="varianceTable">
                    <thead>
                    <tr class="col-xs-12" style="padding:0 !important">
                        <th class="col-xs-1">&nbsp;</th>
                        <th class="col-xs-9">Name</th>
                        <th class="col-xs-2">Variance</th>
                    </tr>
                    </thead>
                    <tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!--                        MessageRole-->
<div class="col-lg-12 padlr0 divPermission" id="divinformpendingwork" style="display: none">
    <div class="headingWrapper">
        <section class="col-md-12">
            <div class="input-group col-md-4 col-md-offset-8" style="margin-bottom:15px;">
                <input name="search_all" id="search_all" type="text" onkeyup="chkSearchtr(this)" class="form-control grid_search_input"/>
                                <span class="input-group-btn">
                                    <button class="btn grid_search_btn" type="button">
                                        <span><i class="fa fa-search" aria-hidden="true"></i></span>
                                    </button>
                                </span>
            </div>
        </section>
    </div>
    <div class="card col-xs-12" style="padding:0 !important">
        <div class="table-responsive topsp parent-scroll">
            <table class="table table-fixed" style="margin-bottom:0px;" id="informpendingworkTable" >
                <thead>
                <tr class="col-xs-12" style="padding:0 !important">
                    <th class="col-xs-6">RoleName</th>
                    <th class="col-xs-2">Screen</th>
                    <th class="col-xs-2">Email</th>
                    <th class="col-xs-2">SMS</th>
                </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>

<!--                        MessageAlert-->
<div class="col-lg-12 padlr0 divPermission" id="divinformalert" style="display: none">
    <div class="headingWrapper">
        <section class="col-md-12">
            <div class="input-group col-md-4 col-md-offset-8" style="margin-bottom:15px;">
                <input name="search_all" id="search_all" type="text" onkeyup="chkSearchtr(this)" class="form-control grid_search_input"/>
                                <span class="input-group-btn">
                                    <button class="btn grid_search_btn" type="button">
                                        <span><i class="fa fa-search" aria-hidden="true"></i></span>
                                    </button>
                                </span>
            </div>
        </section>
    </div>
    <div class="card col-xs-12" style="padding:0 !important">
        <div class="table-responsive topsp parent-scroll">
            <table class="table table-fixed" style="margin-bottom:0px;" id="informalertTable" >
                <thead>
                <tr class="col-xs-12" style="padding:0 !important">
                    <th class="col-xs-6">Alert Name</th>
                    <th class="col-xs-2">Screen</th>
                    <th class="col-xs-2">Email</th>
                    <th class="col-xs-2">SMS</th>
                </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>

</div>
<div class="col-md-12 col-xs-12 col-sm-12" style="padding:0 !important">
    <div class="cont_bt col-md-6 col-xs-6 col-sm-6"><a class="ripple back-btn has-ripple" href="javascript:clickPerPrev();" style="float:left;position:relative; overflow: hidden;margin:0px 0 13px;"><i class="fa fa-backward" aria-hidden="true"></i>&nbsp; Back<span class="ripple-wrapper"></span></a></div>
    <div class="savebtn_areas savebtn_areas1 col-md-6 col-xs-6 col-sm-6">
        <ul>
            <li class="subs" id="divnext" style="float:right;margin-bottom:2px;margin-right:30px"> <a class="ripple has-ripple" href="javascript:clickPerNext();">Next</a> </li>
        </ul>
    </div>
</div>
</div>
</div>
</div>
</div>
</div>
<!--    <input type="hidden" name="cover_hide" id="cover_hide" value="--><?php //echo (isset($resultsMain['UserCover'])) ? $resultsMain['UserCover'] : '';?><!--" />-->
<input type="hidden" name="logo_hide" id="logo_hide" value="<?php echo (isset($resultsMain['UserLogo'])) ? $resultsMain['UserLogo'] : '';?>" />
<input type="hidden" id="userid" name="userid" value="<?php echo (isset($userId)) ? $userId : '0'; ?>" />
<!--<input type="hidden" id="cid" name="cid" value="" />-->
<!--<input type="hidden" id="cid1" name="cid1" value="" />-->
<!--<input type="hidden" id="cid2" name="cid2" value="" />-->
<input type="hidden" id="uMode" name="uMode" value="submit" />

<div class="col-lg-12 savebtn_area m_btm20 no_border clear statutory">
    <ul>
        <li class="col-sm-6"><a href="<?php echo $this->basePath().'/workflow/index/userlist'; ?>" class="ripple has-ripple" style="position: relative; overflow: hidden;background:#fff;border:1px solid #ddd; padding:6px 18px;margin-top:8px;float:left">Cancel<span class="ripple-wrapper"></span></a></li>
        <li class="save_btn float_r" id ="divsubmit">
            <button id="sub" class="ripple" data-toggle="tooltip" data-placement="left" title="Add&nbsp;User" onclick="validateAll();">Submit</button>
            <span id="post-loader" style="display:none;" class="post_loader brad_50"><img src="<?php echo $this->basePath(); ?>/images/post-loader.gif" alt="" title=""/></span> </li>
    </ul>
</div>
</div>
</div>
</div>

<script src="<?php echo $this->basePath(); ?>/js/classie.js"></script>
<script src="<?php echo $this->basePath(); ?>/js/stepsForm.js"></script>
<script>
    var theForm = document.getElementById('theForm');

    new stepsForm( theForm, {
        onSubmit : function(form) {
            // hide form
            classie.addClass( theForm.querySelector('.simform-inner'),'hide');
            //userPermissions();
        }
    });
</script>

<script>
var activeDiv ="",
    bActivity=false,
    bSuperior=false,
    bTeam=false,
    bAlternate=false,
    bRole=false,
    bAlert=false,
    bCompany=false,
    bCostCentre=false,
    bProject=false,
    bWorkType=false,
    bResourceType=false,
    bResourceGroup=false,
    bServiceType=false,
    bAccount=false,
    bAccountType=false,
    bSubLedgerType=false,
    bInformAlert=false,
    bInformPendingwork=false,

    arrUserList = <?php echo (isset($userList)) ? json_encode($userList) : '[]';?>,
    arrSuperiorTrans = <?php echo (isset($superiorTrans)) ? json_encode($superiorTrans) : '[]';?>;
arrAlternateTrans = <?php echo (isset($alternateTrans)) ? json_encode($alternateTrans) : '[]';?>;
arrTeamMaster = <?php echo (isset($teamMaster)) ? json_encode($teamMaster) : '[]';?>,
    arrTeamTrans = <?php echo (isset($teamTrans)) ? json_encode($teamTrans) : '[]';?>;
arrActivityMaster = <?php echo (isset($activityMaster)) ? json_encode($activityMaster) : '[]';?>,
    arrActivityTrans = <?php echo (isset($activityTrans)) ? json_encode($activityTrans) : '[]';?>,
    arrRoleMaster = <?php echo (isset($roleMaster)) ? json_encode($roleMaster) : '[]';?>,
    arrPermissionMaster = <?php echo (isset($permissionMaster)) ? json_encode($permissionMaster) : '[]';?>,
    arrVariantMaster = <?php echo (isset($variantMaster)) ? json_encode($variantMaster) : '[]';?>,
    arrTaskTransMaster = <?php echo (isset($ResultTaskTransMaster)) ? json_encode($ResultTaskTransMaster) : '[]';?>,
    arrRoleTrans = <?php echo (isset($roleTrans)) ? json_encode($roleTrans) : '[]';?>,
    arrPermissionTrans = <?php echo (isset($permissionTrans)) ? json_encode($permissionTrans) : '[]';?>,
    arrVariantTrans = <?php echo (isset($variantTrans)) ? json_encode($variantTrans) : '[]';?>,
    arrAlertMaster = <?php echo (isset($alertMaster)) ? json_encode($alertMaster) : '[]';?>,
    arrAlertTrans = <?php echo (isset($alertTrans)) ? json_encode($alertTrans) : '[]';?>,
    arrCompanyMaster = <?php echo (isset($companyMaster)) ? json_encode($companyMaster) : '[]';?>,
    arrCompanyTrans = <?php echo (isset($companyTrans)) ? json_encode($companyTrans) : '[]';?>,
    arrCostCentreMaster = <?php echo (isset($costcentreMaster)) ? json_encode($costcentreMaster) : '[]';?>,
    arrCostCentreTrans = <?php echo (isset($costcentreTrans)) ? json_encode($costcentreTrans) : '[]';?>,
    arrProjectMaster = <?php echo (isset($projectMaster)) ? json_encode($projectMaster) : '[]';?>,
    arrProjectTrans = <?php echo (isset($projectTrans)) ? json_encode($projectTrans) : '[]';?>,
    arrProjectMaster = <?php echo (isset($projectMaster)) ? json_encode($projectMaster) : '[]';?>,
    arrProjectTrans = <?php echo (isset($projectTrans)) ? json_encode($projectTrans) : '[]';?>,
    arrWorkTypeMaster = <?php echo (isset($worktypeMaster)) ? json_encode($worktypeMaster) : '[]';?>,
    arrWorkTypeTrans = <?php echo (isset($worktypeTrans)) ? json_encode($worktypeTrans) : '[]';?>,
    arrResourceTypeMaster = <?php echo (isset($resourcetypeMaster)) ? json_encode($resourcetypeMaster) : '[]';?>,
    arrResourceTypeTrans = <?php echo (isset($resourcetypeTrans)) ? json_encode($resourcetypeTrans) : '[]';?>,
    arrResourceGroupMaster = <?php echo (isset($resourcegroupMaster)) ? json_encode($resourcegroupMaster) : '[]';?>,
    arrResourceGroupTrans = <?php echo (isset($resourcegroupTrans)) ? json_encode($resourcegroupTrans) : '[]';?>,
    arrServiceTypeMaster = <?php echo (isset($servicetypeMaster)) ? json_encode($servicetypeMaster) : '[]';?>,
    arrServiceTypeTrans = <?php echo (isset($servicetypeTrans)) ? json_encode($servicetypeTrans) : '[]';?>,
    arrAccountMaster = <?php echo (isset($accountMaster)) ? json_encode($accountMaster) : '[]';?>,
    arrAccountTrans = <?php echo (isset($accountTrans)) ? json_encode($accountTrans) : '[]';?>,
    arrAccountTypeMaster = <?php echo (isset($accounttypeMaster)) ? json_encode($accounttypeMaster) : '[]';?>,
    arrAccountTypeTrans = <?php echo (isset($accounttypeTrans)) ? json_encode($accounttypeTrans) : '[]';?>,
    arrSubLedgerTypeMaster = <?php echo (isset($subledgertypeMaster)) ? json_encode($subledgertypeMaster) : '[]';?>,
    arrSubLedgerTypeTrans = <?php echo (isset($subledgertypeTrans)) ? json_encode($subledgertypeTrans) : '[]';?>,
    arrInformAlertTrans = <?php echo (isset($alertinformTrans)) ? json_encode($alertinformTrans) : '[]';?>,
    arrInformPendingworkTrans = <?php echo (isset($pendingworkinformTrans)) ? json_encode($pendingworkinformTrans) : '[]';?>;


$(document).ready(function() {
    $('#panelheading-1').trigger('click');
    if ($('#userid').val() ==0) {
        $('#panelheading-2').hide();
        $('#divsubmit').hide();
    } else {
        $('#user_details').hide();
        $('#divsubmit').show();
    }
    $("#step4").hide();
//        $(".save_btn").hide();
    $("#permission").hide();
    $('.camera_hide').hide();
    $(".single_dropdown").select2({
        placeholder: "",
        allowClear: true
    });
    $(".multiple_dropdown").select2({
        placeholder: ""
    });
});

$(document).on('keydown',function(event){
    var keyCode = (event.keyCode ? event.keyCode : event.which);
    if (keyCode == 13) {
        formChange();
    }
});
$('.photomask').on("mouseenter", function() {
    $('.camera_hide').show();
}).on( "mouseleave", function() {
    $('.camera_hide').hide();
});
$(document).on('keydown',function(event){
    var keyCode = (event.keyCode ? event.keyCode : event.which);
    if (keyCode == 13) {
        formChange();
    }
});
function showimagepreview(input){     //input=$companyId
    if (input.files && input.files[0]) {
        var filerdr = new FileReader();
        filerdr.onload = function(e) {
            $('#imgprvw').attr('src', e.target.result);
        };
        filerdr.readAsDataURL(input.files[0]);
    }
}
function showcoverpreview(input){     //input=$companyId
    if (input.files && input.files[0]) {
        var filerdr = new FileReader();
        filerdr.onload = function (e) {
            $("#cover_display").css('background-image', 'url('+e.target.result+')');
        };
        filerdr.readAsDataURL(input.files[0]);
    }
}

function loadPosition(val) {
    var deptId =  $(val).val();
    $.ajax({
        url: getBaseURL() + "workflow/index/user-entry",
        type: "POST",
        data: {'DeptId': deptId,'uMode' : 'Department'},
        success: function (data, textStatus, jqXHR) {
            var data = JSON.parse(data);
            var deptData = data[0];
            var options = $("#position");
            options.html('');
            $.each(deptData, function() {
                options.append($("<option />").val(this.PositionId).text(this.PositionName));
            });
        }
    });
}

function nameCheck(name) {
    var checkvalue =  $(name).val();
    $.ajax({
        url: getBaseURL() + "workflow/index/user-entry",
        type: "POST",
        data: {'UName': checkvalue,'uMode' : 'username'},
        success: function (data, textStatus, jqXHR) {
            if (data != 0) {
                alert("UserName Already Registered");
                return false;
            }
        },
        error: function (jqXHR, textStatus, errorThrown) {
            alert(textStatus + "-----" + errorThrown);
        }
    });
}


function numCheck(mbl) {
    var mblnum =  $(mbl).val();
    $.ajax({
        url: getBaseURL() + "workflow/index/user-entry",
        type: "POST",
        data: {'MblNum': mblnum,'uMode' : 'mblnumcheck'},
        success: function (data, textStatus, jqXHR) {
            if (data != 0) {
                alert("MobileNumber Already Registered");
                return false;
            }
        },
        error: function (jqXHR, textStatus, errorThrown) {
            alert(textStatus + "-----" + errorThrown);
        }
    });
}


//function deptLevel(val) {
//    var positionId =  $(val).val();
//    $.ajax({
//        url: getBaseURL() + "workflow/index/user-entry",
//        type: "POST",
//        data: {'uPositionId': positionId,'uMode' : 'position'},
//        success: function (data, textStatus, jqXHR) {
//            var data = JSON.parse(data);
//            var deptData = data[0];
//            var levelData = data[1];
//            var superiorUser = data[2];
//            if(levelData.length != 0 && levelData != "false") {
//                $('#levelname').val(levelData.LevelName);
//                $('#level').val(levelData.LevelId);
//            }
//            if(deptData.length != 0 && deptData != "false") {
//                $('#department').val(deptData.Dept_Name);
//                $('#department').val(deptData.DeptId);
//            }
//            if(superiorUser.length != 0 && superiorUser != "false") {
//                $('#superior').html('');
//                var toAppend = '<option value=""></option>';
//                $.each(superiorUser, function (i, o) {
//                    toAppend += '<option value="' + o.UserId + '">' + o.EmployeeName + '</option>';
//                });
//                $('#superior').append(toAppend);
//            }
//        }
//    });
//
//}

function formChange() {
    var iCount = $.trim($(".number-current").html());
    if(iCount == 1 && $('#userName').val() != "") {
        var text = $("#userName").val();
        $("#euserName").val(text);
        (($("#euserName").parent()).parent()).parent().show();
    }
    if(iCount == 2 && $("#empname").val() != "") {
        var text = $("#empname").val();
        $("#eempname").val(text);
        (($("#eempname").parent()).parent()).parent().show();
        $("#ename").html(text);
    }
    if(iCount == 3) {
        var text = $("#user_dob").val();
        $("#euser_dob").val(text);
        (($("#euser_dob").parent()).parent()).parent().show();
    }

    if(iCount == 4 && $("#department").val() != "") {
        var text = $("#department").val();
        $('#edepartment').val(text).prop('selected', true).trigger('change');
        (($("#edepartment").parent()).parent()).parent().show();
        $("#dept").html(text);
    }
    if(iCount == 5 && $("#position").val() != "") {
        var text1 = $("#position option:selected").text();
        var text = $("#position").val();
        $('#eposition').val(text).prop('selected', true).trigger('change');
        (($("#eposition").parent()).parent()).parent().show();
        $("#pos").html(text1);
    }
    if(iCount == 6 && $("#level").val() != "") {
        var text = $("#level").val();
        $('#elevel').val(text).prop('selected', true).trigger('change');
        (($("#elevel").parent()).parent()).parent().show();
        $("#lev").html(text);
    }
    if(iCount == 7) {
        var text = $("#poweruser").val();
        $('#epoweruser').val(text).prop('selected', true).trigger('change');
        (($("#epoweruser").parent()).parent()).parent().show();
    }
    if(iCount == 8) {
        var text = $("#phone_num").val();
        $("#ephone_num").val(text);
        (($("#ephone_num").parent()).parent()).parent().show();
    }

    if(iCount == 9 && $("#mobile").val() != "") {
        var text = $("#mobile").val();
        $("#emobile").val(text);
        (($("#emobile").parent()).parent()).parent().show();
    }
    if(iCount == 10 && $("#address").val() != "") {
        var text = $("#address").val();
        $("#eaddress").val(text);
        (($("#eaddress").parent()).parent()).parent().show();
    }
    if(iCount == 11 ) {
        var text = $("#email_address").val();
        $("#eemail_address").val(text);
        (($("#eemail_address").parent()).parent()).parent().show();
        //$('#enextid').show();
    }
    if(iCount == 12) {
        var text = $("#dcostcentre").val();
        $('#edcostcentre').val(text).prop('selected', true).trigger('change');
        ($("#edcostcentre").parent()).parent().show();
        $('#enextid').show();
    }
}

function clickNext() {
    if ($('#userid').val() == 0) {
        $('#panelheading-2').show();
        $('#divsubmit').show();
    }
    $('#panelheading-2').trigger('click');
    showSuperior();
}

function clickPerNext() {
    var sPerName = "";
    var $resnames = $('li[id*=per_]');
    $.each($resnames, function (i, obj) {
        var name = $(this)[0].id,
            sname = name.split('_')[1];
        if ($("#" + name + " > a").hasClass("active")) {
            sPerName =sname;
            return false;
        }
    });
    if (sPerName =="") return;
    $('#divnext').show();
    if (sPerName =="superior") showAlternate();
    else if (sPerName =="alternate") showTeam();
    else if (sPerName =="team") showActivity();
    else if (sPerName =="activity") showRole();
    else if (sPerName =="role") showRolePermission();
    else if (sPerName =="permission") showVariance();
    else if (sPerName =="variance") showAlert();
    else if (sPerName =="alert") showCompany();
    else if (sPerName =="company") showCostCentre();
    else if (sPerName =="costcentre") showProject();
    else if (sPerName =="project") showWorkType();
    else if (sPerName =="worktype") showResourceType();
    else if (sPerName =="resourcetype") showResourceGroup();
    else if (sPerName =="resourcegroup") showServiceType();
    else if (sPerName =="servicetype") showAccount();
    else if (sPerName =="account") showAccountType();
    else if (sPerName =="accounttype")  showSubLedgerType();
    else if (sPerName =="subledgertype")  showinformAlert();
    else if (sPerName =="informalert") { showinformPendingwork(); $('#divnext').hide(); }
}
function clickPerPrev() {
    var sPerName = "";
    var $resnames = $('li[id*=per_]');
    $.each($resnames, function (i, obj) {
        var name = $(this)[0].id,
            sname = name.split('_')[1];
        if ($("#" + name + " > a").hasClass("active")) {3
            sPerName =sname;
            return false;
        }
    });
    if (sPerName =="") return;
    $('#divnext').show();
    if (sPerName =="superior") $('#panelheading-1').trigger('click');
    else if (sPerName =="alternate") showSuperior();
    else if (sPerName =="team") showAlternate();
    else if (sPerName =="activity")  showTeam();
    else if (sPerName =="role") showActivity();
    else if (sPerName =="permission") showRole();
    else if (sPerName =="variance") showRolePermission();
    else if (sPerName =="alert") showVariance();
    else if (sPerName =="company") showAlert();
    else if (sPerName =="costcentre") showCompany();
    else if (sPerName =="project") showCostCentre();
    else if (sPerName =="worktype") showProject();
    else if (sPerName =="resourcetype") showWorkType();
    else if (sPerName =="resourcegroup") showResourceType();
    else if (sPerName =="servicetype") showResourceGroup();
    else if (sPerName =="account") showServiceType();
    else if (sPerName =="accounttype") showAccount();
    else if (sPerName =="subledgertype") showAccountType();
    else if (sPerName =="informalert") showSubLedgerType();
    else if (sPerName =="informpendingwork") showinformAlert();
}


$('.panel-heading').click(function(){
    $('.panel-heading').removeClass('accordion_head_crnt');
    if($(this).next('div.in'))
        $(this).addClass('accordion_head_crnt');
    else
        $(this).removeClass('accordion_head_crnt');
});


$(document).on('change','.sampleUI input:checkbox', function (){
    var current = $(this).closest('li'),
        $checkbox = current.find("input:checkbox"),
        key = $checkbox.data('id');
    if(key == 1) {
        var nxt = key+1;
        $('#checkedUl_' + nxt).html('');
        $('#unCheckedUl_' + nxt).html('');
    }
    if($checkbox.is(':checked')){
        var prependToDiv = $('#checkedUl_' + key);
        current.animate({
            top: -30,
            left: prependToDiv.offset().left
        }, 200, function() {
            current.prependTo(prependToDiv).css({
                top: 'auto',
                left: 'auto'
            });
        });
    }
    else{
        var prependToDiv = $('#unCheckedUl_' + key);
        current.animate({
            top: -30,
            left: -prependToDiv.offset().left

        }, 200, function() {
            current.prependTo(prependToDiv).css({
                top: 'auto',
                left: 'auto'
            });
        });
    }
    var delayTimer = 0;
    clearTimeout(delayTimer);
    delayTimer = setTimeout(function () {
        if (activeDiv=="superior")  updateSuperior();
        else if (activeDiv=="alternate")  updateAlternate();
        else if (activeDiv=="team")  updateTeam();
        else if (activeDiv=="activity")  updateActivity();
        else if (activeDiv=="alert")  updateAlert();
        else if (activeDiv=="company")  updateCompany();
        else if (activeDiv=="costcentre")  updateCostCentre();
        else if (activeDiv=="project")  updateProject();
        else if (activeDiv=="worktype")  updateWorkType();
        else if (activeDiv=="resourcetype")  updateResourceType();
        else if (activeDiv=="resourcegroup")  updateResourceGroup();
        else if (activeDiv=="servicetype")  updateServiceType();
        else if (activeDiv=="account")  updateAccount();
        else if (activeDiv=="accounttype")  updateAccountType();
        else if (activeDiv=="subledgertype")  updateSubLedgerType();
    },300);

});

//$(".content_wrapper").on('click', 'input:checkbox', function(){
//    var userId = $('#userid').val();
//    var id = $(this).attr('cid');
//    $('.loading_area').show();
//    if($(this).is(":checked")){
//        if($(this).attr("tagname") == 'cid'){
////            cid.push(id);
//            $(this).closest("li").addClass('check_vendor_background');
//            $.ajax({
//                url: getBaseURL() + "workflow/index/user-entry",
//                type: "POST",
//                data: {'cId': JSON.stringify(cid),'uMode' : 'role','userId' : userId},
//                success: function (data, textStatus, jqXHR) {
//                    var data = JSON.parse(data);
//                    var roleNames = data[0];
//                    var selectRoleNames = data[1];
//                    var template = $('#dummy-role').html();
//                    var rowid = 2;
//                    var $tbody = $('#unCheckedUl_' + rowid);
//                    $('#unCheckedUl_' + rowid).html('');
//                    $('#CheckedUl_' + rowid).html('');
//                    cid1=[];
//                    if (roleNames.length != 0) {
//                        $.each(roleNames, function (i, o) {
//                            $tbody.append(template.replace(/__/g, '_' + o.RoleId));
//                            $('#Role_customize_' + o.RoleId).val(o.RoleId);
//                            $('#Role_customize_' + o.RoleId).attr('data-id',rowid);
//                            $('#Role_customize_' + o.RoleId).attr('cid',o.RoleId);
//                            $('#Role_customize_' + o.RoleId).attr('onclick','checkSelectAll('+rowid+');');
//                            $('#Role_name_' + o.RoleId).html(o.RoleName);
//                        });
//                    } else {
//                        $('#unCheckedUl_' + rowid).html('');
//                        $('#CheckedUl_' + rowid).html('');
//                    }
//                }
//
//            });
//        }
//        else if($(this).attr("tagname") == 'cid1'){
//            cid1.push(id);
//            $(this).closest("li").addClass('check_vendor_background');
//        }
//        else if($(this).attr("tagname") == 'cid2'){
//            cid2.push(id);
//            $(this).closest("li").addClass('check_vendor_background');
//        }
//        $('.loading_area').hide();
//    }
//    else{
//        //cid.splice($.inArray($(this).attr("resurceid"), resourceId),1)
//        if($(this).attr("tagname") == 'cid') {
//            cid.splice($.inArray(id, cid), 1);
//            $(this).closest("li").removeClass('check_vendor_background');
//            $.ajax({
//                url: getBaseURL() + "workflow/index/user-entry",
//                type: "POST",
//                data: {'cId': JSON.stringify(cid),'uMode' : 'role','userId' : userId},
//                success: function (data, textStatus, jqXHR) {
//                    var data = JSON.parse(data);
//                    var roleNames = data[0];
//                    var template = $('#dummy-role').html();
//                    var rowid = 2;
//                    cid1=[];
//                    var $tbody = $('#unCheckedUl_' + rowid);
//                    $('#CheckedUl_' + rowid).html('');
//                    if (roleNames.length != 0) {
//                        $.each(roleNames, function (i, o) {
//                            $tbody.append(template.replace(/__/g, '_' + o.RoleId));
//                            $('#Role_customize_' + o.RoleId).val(o.RoleId);
//                            $('#Role_customize_' + o.RoleId).attr('data-id',rowid);
//                            $('#Role_customize_' + o.RoleId).attr('cid',o.RoleId);
//                            $('#Role_customize_' + o.RoleId).attr('onclick','checkSelectAll('+rowid+');');
//                            $('#Role_name_' + o.RoleId).html(o.RoleName);
//                        });
//                    } else {
//                        $('#CheckedUl_' + rowid).html('');
//                    }
//                }
//
//            });
//        }
//        else if($(this).attr("tagname") == 'cid1'){
//            cid1.splice($.inArray(id, cid1), 1);
//            $(this).closest("li").removeClass('check_vendor_background');
//        }
//        else if($(this).attr("tagname") == 'cid2'){
//            cid2.splice($.inArray(id, cid2), 1);
//            $(this).closest("li").removeClass('check_vendor_background');
//        }
//    }
//    $('.loading_area').hide();
//});

//function userPermissions() {
//    $("#step2").hide();
//    $(".stephide").hide();
//    $("#step3").addClass('opacity_08');
//    $("#step3").children("div").removeClass('stepsep_active');
//    $("#step4").removeClass('opacity_08');
//    $("#step4").children("div").addClass('stepsep_active');
//    $(".save_btn").show();
//    var uDeptId = $('#department').val();
//    var userId = parseInt($('#userid').val());
//
//    if(userId==0) {
//        $.ajax({
//            url: getBaseURL() + "workflow/index/user-entry",
//            type: "POST",
//            data: {'uDeptId': uDeptId,'uMode' : 'activity','userId' : userId},
//            success: function (data, textStatus, jqXHR) {
//                var data = JSON.parse(data);
//                var actNames = data[0];
//                var alertNames = data[1];
//                var template1 = $('#dummy-activity').html();
//                var template3 = $('#dummy-alert').html();
//                var rowid1 = 1;
//                var rowid3 = 3;
//                var $tbody1 = $('#unCheckedUl_' + rowid1);
//                $('#unCheckedUl_' + rowid1).html('');
//                if (actNames.length != 0) {
//                    $.each(actNames, function (i, o) {
//                        $tbody1.append(template1.replace(/__/g, '_' + o.ActivityId));
//                        $('#Activity_customize_' + o.ActivityId).val(o.ActivityId);
//                        $('#Activity_customize_' + o.ActivityId).attr('data-id',rowid1);
//                        $('#Activity_customize_' + o.ActivityId).attr('cid',o.ActivityId);
//                        $('#Activity_customize_' + o.ActivityId).attr('onclick','checkSelectAll('+rowid1+');');
//
//                        $('#Activity_name_' + o.ActivityId).html(o.ActivityName);
//                    });
//                } else {
//                    $('#unCheckedUl_' + rowid1).html('');
//                }
//                var $tbody3 = $('#unCheckedUl_' + rowid3);
//                $('#unCheckedUl_' + rowid3).html('');
//                if (alertNames.length != 0) {
//                    $.each(alertNames, function (i, o) {
//                        $tbody3.append(template3.replace(/__/g, '_' + o.AlertId));
//                        $('#Alert_customize_' + o.AlertId).val(o.AlertId);
//                        $('#Alert_customize_' + o.AlertId).attr('data-id',rowid3);
//                        $('#Alert_customize_' + o.AlertId).attr('cid',o.AlertId);
//                        $('#Alert_customize_' + o.AlertId).attr('onclick','checkSelectAll('+rowid3+');');
//                        $('#Alert_name_' + o.AlertId).html(o.AlertName);
//
//                    });
//                } else {
//                    $('#unCheckedUl_' + rowid3).html('');
//                }
//            }
//
//        });
//    }
//    $("#permission").show();
//}

function validateAll() {
    $('#sub').hide();
    $('#post-loader').show();

    var userId=$("#userid").val(),
        userName= $.trim($("#euserName").val()),
        empName= $.trim($("#eempname").val()),
        user_dob= $("#euser_dob").val(),
        poweruser = $("#epoweruser").val(),
        department = $("#edepartment").val(),
        position= $("#eposition").val(),
        level= $("#elevel").val(),
        phone_num= $("#ephone_num").val(),
        mobile= $("#emobile").val(),
        address= $("#eaddress").val(),
        email_address= $("#email_address").val(),
        logoImage = $('#filephoto').prop("files")[0];
//    coverImage = $('#comp_cover_photo').prop("files")[0],

    var form_data = new FormData();
    form_data.append("logo", logoImage);
//    form_data.append("coverImage", coverImage);
    form_data.append('userId', userId);
    form_data.append('userName', userName);
    form_data.append('empname', empName);
    form_data.append('user_dob', user_dob);
    form_data.append('poweruser', poweruser);
    form_data.append('department', department);
    form_data.append('position', position);
    form_data.append('level', level);
    form_data.append('phone', phone_num);
    form_data.append('mobile', mobile);
    form_data.append('address', address);
    form_data.append('email', email_address);
    form_data.append('bSuperior', bSuperior);
    form_data.append('bAlternate', bAlternate);
    form_data.append('bTeam', bTeam);
    form_data.append('bActivity', bActivity);
    form_data.append('bRole', bRole);
    form_data.append('bAlert', bAlert);
    form_data.append('bCompany', bCompany);
    form_data.append('bCostCentre', bCostCentre);
    form_data.append('bProject', bProject);
    form_data.append('bWorkType', bWorkType);
    form_data.append('bResourceType', bResourceType);
    form_data.append('bResourceGroup', bResourceGroup);
    form_data.append('bServiceType', bServiceType);
    form_data.append('bAccount', bAccount);
    form_data.append('bAccountType', bAccountType);
    form_data.append('bSubLedgerType', bSubLedgerType);
    form_data.append('bInformAlert', bInformAlert);
    form_data.append('bInformPendingwork', bInformPendingwork);
    form_data.append('superiorTrans', JSON.stringify(arrSuperiorTrans));
    form_data.append('alternateTrans', JSON.stringify(arrAlternateTrans));
    form_data.append('teamTrans', JSON.stringify(arrTeamTrans));
    form_data.append('activityTrans', JSON.stringify(arrActivityTrans));
    form_data.append('roleTrans', JSON.stringify(arrRoleTrans));
    form_data.append('permissionTrans', JSON.stringify(arrPermissionTrans));
    form_data.append('variantTrans', JSON.stringify(arrVariantTrans));
    form_data.append('alertTrans', JSON.stringify(arrAlertTrans));
    form_data.append('companyTrans', JSON.stringify(arrCompanyTrans));
    form_data.append('costcentreTrans', JSON.stringify(arrCostCentreTrans));
    form_data.append('projectTrans', JSON.stringify(arrProjectTrans));
    form_data.append('worktypeTrans', JSON.stringify(arrWorkTypeTrans));
    form_data.append('resourcetypeTrans', JSON.stringify(arrResourceTypeTrans));
    form_data.append('resourcegroupTrans', JSON.stringify(arrResourceGroupTrans));
    form_data.append('servicetypeTrans', JSON.stringify(arrServiceTypeTrans));
    form_data.append('accountTrans', JSON.stringify(arrAccountTrans));
    form_data.append('accounttypeTrans', JSON.stringify(arrAccountTypeTrans));
    form_data.append('subledgertypeTrans', JSON.stringify(arrSubLedgerTypeTrans));
    form_data.append('informalertTrans', JSON.stringify(arrInformAlertTrans));
    form_data.append('informpendingworkTrans', JSON.stringify(arrInformPendingworkTrans));

    $.ajax({
        url: getBaseURL() + "workflow/index/user-entry",
        type: "POST",
        data: form_data,
        enctype: "multipart/form-data",
        cache       : false,
        contentType : false,
        processData : false,
        success: function (data, textStatus, jqXHR) {
            $('#sub').show();
            $('#post-loader').hide();
            $(location).attr('href',"<?php echo $this->basePath(); ?>/workflow/index/userlist");
        },
        error:function(jqXHR, textStatus, errorThrown){
            $(".statutory").hide();
            $(".branch").hide();
            var messageEl = theForm.querySelector( '.final-message' );
            messageEl.innerHTML = 'ERROR Optain.';
            classie.addClass( messageEl, 'show' );
            $('#sub').show();
            $('#post-loader').hide();
        }
    });


//    var errorFlag = 0;
//    var errorFlagCount = 0;
//    if($('#Company_name').val() == "" || $('#Company_name').val() == null) {
//        $('#Company_name').next('span').addClass('red_bdr');
//        errorFlagCount = errorFlagCount + 1;
//        errorFlag = 1;
//        if(errorFlagCount == 1) {
//            $('#Company_name').next('span').focus();
//        }
//        $('#sub').show();
//        $('#post-loader').hide();
//        return;
//    } else {
//        $('#Company_name').next('span').removeClass('red_bdr');
//    }
//    if($('#CostCentre_name').val() == "" || $('#CostCentre_name').val() == null) {
//        $('#CostCentre_name').next('span').addClass('red_bdr');
//        errorFlagCount = errorFlagCount + 1;
//        errorFlag = 1;
//        if(errorFlagCount == 1) {
//            $('#CostCentre_name').next('span').focus();
//        }
//        $('#sub').show();
//        $('#post-loader').hide();
//        return;
//    } else {
//        $('#CostCentre_name').next('span').removeClass('red_bdr');
//    }
//    if($('#CostCentre_default').val() == "" || $('#CostCentre_default').val() == null) {
//        $('#CostCentre_default').next('span').addClass('red_bdr');
//        errorFlagCount = errorFlagCount + 1;
//        errorFlag = 1;
//        if(errorFlagCount == 1) {
//            $('#CostCentre_default').next('span').focus();
//        }
//        $('#sub').show();
//        $('#post-loader').hide();
//        return;
//    } else {
//        $('#CostCentre_default').next('span').removeClass('red_bdr');
//    }
//    if(errorFlag==0) {
//        if(cid.length != 0) {
//            var sCid = cid.join(',');
//            $('#cid').val(sCid);
//        }
//        if(cid1.length != 0) {
//            cid1.join(',');
//            var sCid1 = cid1.join(',');
//            $('#cid1').val(sCid1);
//        }
//        if(cid2.length != 0) {
//            cid2.join(',');
//            var sCid2 = cid2.join(',');
//            $('#cid2').val(sCid2);
//        }
//
//        var formData = new FormData();
//        formData.append("cover", $('#comp_cover_photo').prop("files")[0]);
//        formData.append("logo", $('#filephoto').prop("files")[0]);
//
//        var other_data = $('#theForm,#Form2').serializeArray();
//        $.each(other_data,function(key,input){
//            formData.append(input.name,input.value);
//        });
//
//        $.ajax({
//            url: getBaseURL() + "workflow/index/user_entry",
//            type: "POST",
//            data: formData,
//            enctype: "multipart/form-data",
//            cache       : false,
//            contentType : false,
//            processData : false,
//            success: function (data, textStatus, jqXHR) {
//                if(data=='success') {
//                    $(location).attr('href', "<?php //echo $this->basePath(); ?>///workflow/index/users");
//
//                } else {
//                    $('#sub').show();
//                    $('#post-loader').hide();
//                    alert('Insert Failed..!!! User Name Already Exist..!!');
//                    $(location).attr('href', "<?php //echo $this->basePath(); ?>///workflow/index/users");
//
//                }
//            },
//            error: function (jqXHR, textStatus, errorThrown) {
//                $(".permission").hide();
//                var messageEl = theForm.querySelector('.final-message');
//                messageEl.innerHTML = 'ERROR Optain.';
//                classie.addClass(messageEl, 'show');
//                $('#sub').show();
//                $('#post-loader').hide();
//            }
//        });
//    } else {
//        $('#sub').show();
//        $('#post-loader').hide();
//        return;
//    }

}
function selectAll(dId) {
    if($("#select_all_"+dId).is(':checked') ) {
        $('*[data-id='+dId+']:not(:checked)').trigger('click');
    }else {
        $('*[data-id='+dId+']:checked').trigger('click');
    }
}
function checkSelectAll(cId) {
    if($('*[data-id='+cId+']:checked').length != $('*[data-id='+cId+']').length) {
        $("#select_all_"+cId).prop('checked',false);
    } else {
        $("#select_all_"+cId).prop('checked',true);
    }
}
$(document).ready(function(){
    $('ul.list-head li a').click(function(){
        $('li a').removeClass("active");
        $(this).addClass("active");
    });
    $('ul.list-head li').click(function(){
        var name = $(this)[0].id;
        if (name == "per_informpendingwork")  $('#divnext').hide();
        else $('#divnext').show();
    });
    showSuperior();
});

//Permission

function showSuperior() {
    $('li a').removeClass("active");
    $("#per_superior > a").addClass("active");
    $('.list-head').animate({
        scrollTop : $("#per_superior").position().top
    });

    var arrMPosSuperior = [];
    for (var i in arrUserList) {
        var arr = $.grep(arrSuperiorTrans, function (element, index) {
            return element.SUserId == arrUserList[i].UserId});
        if (arr.length ==0) {
            arrMPosSuperior.push({
                SUserId: arrUserList[i].UserId,
                UserName: arrUserList[i].UserName
            });
        }
    }


    $('#unCheckedUl_1').html();
    var sHtml= "";
    for (var i in arrMPosSuperior) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrMPosSuperior[i].UserName + '" data-id="1" name="customize_' +  arrMPosSuperior[i].SUserId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrMPosSuperior[i].UserName + '" id="customize_' + arrMPosSuperior[i].UserName + '" value="' + arrMPosSuperior[i].UserName + '_S">' +
        '<span>' + arrMPosSuperior[i].UserName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrMPosSuperior[i].UserName + '" value="' + arrMPosSuperior[i].SUserId + '">'+
        '</div></li>';
    }
    $('#unCheckedUl_1').html(sHtml);
    $('#checkedUl_1').html();
    sHtml= "";
    for (var i in arrSuperiorTrans) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle check_vendor_background search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrSuperiorTrans[i].UserName + '" data-id="1" name="customize_' +  arrSuperiorTrans[i].SUserId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrSuperiorTrans[i].UserName + '" id="customize_' + arrSuperiorTrans[i].UserName + '" value="' + arrSuperiorTrans[i].UserName + '_S"  checked="checked">' +
        '<span>' + arrSuperiorTrans[i].UserName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrSuperiorTrans[i].UserName + '" value="' + arrSuperiorTrans[i].SUserId + '">'+
        '</div></li>';
    }
    $('#checkedUl_1').html(sHtml);
    $('#searchTitle1').html('Select Superior User');
    $('#searchTitle2').html('Selected Superior User');
    activeDiv = "superior";
    showPermission('divactivity');
}
function showAlternate() {
    $('li a').removeClass("active");
    $("#per_alternate > a").addClass("active");
    $('.list-head').animate({
        scrollTop : $("#per_alternate").position().top
    });

    var arrMPosAlternate = [];
    for (var i in arrUserList) {
        var arr = $.grep(arrAlternateTrans, function (element, index) {
            return element.AUserId == arrUserList[i].UserId});
        if (arr.length ==0) {
            arrMPosAlternate.push({
                AUserId: arrUserList[i].UserId,
                UserName: arrUserList[i].UserName
            });
        }
    }

    $('#unCheckedUl_1').html();
    var sHtml= "";
    for (var i in arrMPosAlternate) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrMPosAlternate[i].UserName + '" data-id="1" name="customize_' +  arrMPosAlternate[i].AUserId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrMPosAlternate[i].UserName + '" id="customize_' + arrMPosAlternate[i].UserName + '" value="' + arrMPosAlternate[i].UserName + '_S">' +
        '<span>' + arrMPosAlternate[i].UserName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrMPosAlternate[i].UserName + '" value="' + arrMPosAlternate[i].AUserId + '">'+
        '</div></li>';
    }
    $('#unCheckedUl_1').html(sHtml);
    $('#checkedUl_1').html();
    sHtml= "";
    for (var i in arrAlternateTrans) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle check_vendor_background search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrAlternateTrans[i].UserName + '" data-id="1" name="customize_' +  arrAlternateTrans[i].AUserId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrAlternateTrans[i].UserName + '" id="customize_' + arrAlternateTrans[i].UserName + '" value="' + arrAlternateTrans[i].UserName + '_S"  checked="checked">' +
        '<span>' + arrAlternateTrans[i].UserName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrAlternateTrans[i].UserName + '" value="' + arrAlternateTrans[i].AUserId + '">'+
        '</div></li>';
    }
    $('#checkedUl_1').html(sHtml);
    $('#searchTitle1').html('Select Alternate Users');
    $('#searchTitle2').html('Selected Alternate Users');
    activeDiv = "alternate";
    showPermission('divactivity');
}


function showActivity() {
    $('li a').removeClass("active");
    $("#per_activity > a").addClass("active");
    $('.list-head').animate({
        scrollTop : $("#per_activity").position().top
    });

    var arrMPosActivity = [];
    for (var i in arrActivityMaster) {
        var arr = $.grep(arrActivityTrans, function (element, index) {
            return element.ActivityId == arrActivityMaster[i].ActivityId});
        if (arr.length ==0) {
            arrMPosActivity.push({
                ActivityId: arrActivityMaster[i].ActivityId,
                ActivityName: arrActivityMaster[i].ActivityName
            });
        }
    }

    $('#unCheckedUl_1').html();
    var sHtml= "";
    for (var i in arrMPosActivity) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrMPosActivity[i].ActivityName + '" data-id="1" name="customize_' +  arrMPosActivity[i].ActivityId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrMPosActivity[i].ActivityName + '" id="customize_' + arrMPosActivity[i].ActivityName + '" value="' + arrMPosActivity[i].ActivityName + '_S">' +
        '<span>' + arrMPosActivity[i].ActivityName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrMPosActivity[i].ActivityName + '" value="' + arrMPosActivity[i].ActivityId + '">'+
        '</div></li>';
    }
    $('#unCheckedUl_1').html(sHtml);
    $('#checkedUl_1').html();
    sHtml= "";
    var argActivityIds="";
    for (var i in arrActivityTrans) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle check_vendor_background search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrActivityTrans[i].ActivityName + '" data-id="1" name="customize_' +  arrActivityTrans[i].ActivityId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrActivityTrans[i].ActivityName + '" id="customize_' + arrActivityTrans[i].ActivityName + '" value="' + arrActivityTrans[i].ActivityName + '_S"  checked="checked">' +
        '<span>' + arrActivityTrans[i].ActivityName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrActivityTrans[i].ActivityName + '" value="' + arrActivityTrans[i].ActivityId + '">'+
        '</div></li>';
        argActivityIds = argActivityIds + arrActivityTrans[i].ActivityId + ",";
    }
    $('#checkedUl_1').html(sHtml);
    $('#searchTitle1').html('Select Activity');
    $('#searchTitle2').html('Selected Activity');
    activeDiv = "activity";
    showPermission('divactivity');
}
function showTeam() {
    $('li a').removeClass("active");
    $("#per_team > a").addClass("active");
    $('.list-head').animate({
        scrollTop : $("#per_team").position().top
    });

    var arrMPosTeam = [];
    for (var i in arrTeamMaster) {
        var arr = $.grep(arrTeamTrans, function (element, index) {
            return element.TeamId == arrTeamMaster[i].TeamId});
        if (arr.length ==0) {
            arrMPosTeam.push({
                TeamId: arrTeamMaster[i].TeamId,
                TeamName: arrTeamMaster[i].TeamName
            });
        }
    }

    $('#unCheckedUl_1').html();
    var sHtml= "";
    for (var i in arrMPosTeam) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrMPosTeam[i].TeamName + '" data-id="1" name="customize_' +  arrMPosTeam[i].TeamId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrMPosTeam[i].TeamName + '" id="customize_' + arrMPosTeam[i].TeamName + '" value="' + arrMPosTeam[i].TeamName + '_S">' +
        '<span>' + arrMPosTeam[i].TeamName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrMPosTeam[i].TeamName + '" value="' + arrMPosTeam[i].TeamId + '">'+
        '</div></li>';
    }
    $('#unCheckedUl_1').html(sHtml);
    $('#checkedUl_1').html();
    sHtml= "";
    for (var i in arrTeamTrans) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle check_vendor_background search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrTeamTrans[i].TeamName + '" data-id="1" name="customize_' +  arrTeamTrans[i].TeamId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrTeamTrans[i].TeamName + '" id="customize_' + arrTeamTrans[i].TeamName + '" value="' + arrTeamTrans[i].TeamName + '_S"  checked="checked">' +
        '<span>' + arrTeamTrans[i].TeamName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrTeamTrans[i].TeamName + '" value="' + arrTeamTrans[i].TeamId + '">'+
        '</div></li>';
    }
    $('#checkedUl_1').html(sHtml);
    $('#searchTitle1').html('Select Team');
    $('#searchTitle2').html('Selected Team');
    activeDiv = "team";
    showPermission('divactivity');
}
function showAlert() {
    $('li a').removeClass("active");
    $("#per_alert > a").addClass("active");
    $('.list-head').animate({
        scrollTop : $("#per_alert").position().top
    });

    var arrMPosAlert = [];
    for (var i in arrAlertMaster) {
        var arr = $.grep(arrAlertTrans, function (element, index) {
            return element.AlertId == arrAlertMaster[i].AlertId});
        if (arr.length ==0) {
            arrMPosAlert.push({
                AlertId: arrAlertMaster[i].AlertId,
                AlertName: arrAlertMaster[i].AlertName
            });
        }
    }

    $('#unCheckedUl_1').html();
    var sHtml= "";
    for (var i in arrMPosAlert) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrMPosAlert[i].AlertName + '" data-id="1" name="customize_' +  arrMPosAlert[i].AlertId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrMPosAlert[i].AlertName + '" id="customize_' + arrMPosAlert[i].AlertName + '" value="' + arrMPosAlert[i].AlertName + '_S">' +
        '<span>' + arrMPosAlert[i].AlertName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrMPosAlert[i].AlertName + '" value="' + arrMPosAlert[i].AlertId + '">'+
        '</div></li>';
    }
    $('#unCheckedUl_1').html(sHtml);
    $('#checkedUl_1').html();
    sHtml= "";
    for (var i in arrAlertTrans) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle check_vendor_background search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrAlertTrans[i].AlertName + '" data-id="1" name="customize_' +  arrAlertTrans[i].AlertId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrAlertTrans[i].AlertName + '" id="customize_' + arrAlertTrans[i].AlertName + '" value="' + arrAlertTrans[i].AlertName + '_S"  checked="checked">' +
        '<span>' + arrAlertTrans[i].AlertName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrAlertTrans[i].AlertName + '" value="' + arrAlertTrans[i].AlertId + '">'+
        '</div></li>';
    }
    $('#checkedUl_1').html(sHtml);
    $('#searchTitle1').html('Select Alert');
    $('#searchTitle2').html('Selected Alert');
    activeDiv = "alert";
    showPermission('divactivity');
}

function showCompany() {
    $('li a').removeClass("active");
    $("#per_company > a").addClass("active");
    $('.list-head').animate({
        scrollTop : $("#per_company").position().top
    });

    var arrMPosCompany = [];
    for (var i in arrCompanyMaster) {
        var arr = $.grep(arrCompanyTrans, function (element, index) {
            return element.CompanyId == arrCompanyMaster[i].CompanyId});
        if (arr.length ==0) {
            arrMPosCompany.push({
                CompanyId: arrCompanyMaster[i].CompanyId,
                CompanyName: arrCompanyMaster[i].CompanyName
            });
        }
    }

    $('#unCheckedUl_1').html();
    var sHtml= "";
    for (var i in arrMPosCompany) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrMPosCompany[i].CompanyName + '" data-id="1" name="customize_' +  arrMPosCompany[i].CompanyId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrMPosCompany[i].CompanyName + '" id="customize_' + arrMPosCompany[i].CompanyName + '" value="' + arrMPosCompany[i].CompanyName + '_S">' +
        '<span>' + arrMPosCompany[i].CompanyName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrMPosCompany[i].CompanyName + '" value="' + arrMPosCompany[i].CompanyId + '">'+
        '</div></li>';
    }
    $('#unCheckedUl_1').html(sHtml);
    $('#checkedUl_1').html();
    sHtml= "";
    for (var i in arrCompanyTrans) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle check_vendor_background search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrCompanyTrans[i].CompanyName + '" data-id="1" name="customize_' +  arrCompanyTrans[i].CompanyId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrCompanyTrans[i].CompanyName + '" id="customize_' + arrCompanyTrans[i].CompanyName + '" value="' + arrCompanyTrans[i].CompanyName + '_S"  checked="checked">' +
        '<span>' + arrCompanyTrans[i].CompanyName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrCompanyTrans[i].CompanyName + '" value="' + arrCompanyTrans[i].CompanyId + '">'+
        '</div></li>';
    }
    $('#checkedUl_1').html(sHtml);
    $('#searchTitle1').html('Select Company');
    $('#searchTitle2').html('Selected Company');
    activeDiv = "company";
    showPermission('divactivity');
}
function showCostCentre() {
    $('li a').removeClass("active");
    $("#per_costcentre > a").addClass("active");
    $('.list-head').animate({
        scrollTop : $("#per_costcentre").position().top
    });

    var arrMPosCostCentre = [];
    for (var i in arrCostCentreMaster) {
        var arr = $.grep(arrCostCentreTrans, function (element, index) {
            return element.CostCentreId == arrCostCentreMaster[i].CostCentreId});
        if (arr.length ==0) {
            arrMPosCostCentre.push({
                CostCentreId: arrCostCentreMaster[i].CostCentreId,
                CostCentreName: arrCostCentreMaster[i].CostCentreName
            });
        }
    }

    $('#unCheckedUl_1').html();
    var sHtml= "";
    for (var i in arrMPosCostCentre) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrMPosCostCentre[i].CostCentreName + '" data-id="1" name="customize_' +  arrMPosCostCentre[i].CostCentreId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrMPosCostCentre[i].CostCentreName + '" id="customize_' + arrMPosCostCentre[i].CostCentreName + '" value="' + arrMPosCostCentre[i].CostCentreName + '_S">' +
        '<span>' + arrMPosCostCentre[i].CostCentreName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrMPosCostCentre[i].CostCentreName + '" value="' + arrMPosCostCentre[i].CostCentreId + '">'+
        '</div></li>';
    }
    $('#unCheckedUl_1').html(sHtml);
    $('#checkedUl_1').html();
    sHtml= "";
    for (var i in arrCostCentreTrans) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle check_vendor_background search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrCostCentreTrans[i].CostCentreName + '" data-id="1" name="customize_' +  arrCostCentreTrans[i].CostCentreId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrCostCentreTrans[i].CostCentreName + '" id="customize_' + arrCostCentreTrans[i].CostCentreName + '" value="' + arrCostCentreTrans[i].CostCentreName + '_S"  checked="checked">' +
        '<span>' + arrCostCentreTrans[i].CostCentreName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrCostCentreTrans[i].CostCentreName + '" value="' + arrCostCentreTrans[i].CostCentreId + '">'+
        '</div></li>';
    }
    $('#checkedUl_1').html(sHtml);
    $('#searchTitle1').html('Select CostCentre');
    $('#searchTitle2').html('Selected CostCentre');
    activeDiv = "costcentre";
    showPermission('divactivity');
}

function showProject() {
    $('li a').removeClass("active");
    $("#per_project > a").addClass("active");
    $('.list-head').animate({
        scrollTop : $("#per_project").position().top
    });

    var arrMPosProject = [];
    for (var i in arrProjectMaster) {
        var arr = $.grep(arrProjectTrans, function (element, index) {
            return element.ProjectId == arrProjectMaster[i].ProjectId});
        if (arr.length ==0) {
            arrMPosProject.push({
                ProjectId: arrProjectMaster[i].ProjectId,
                ProjectName: arrProjectMaster[i].ProjectName
            });
        }
    }

    $('#unCheckedUl_1').html();
    var sHtml= "";
    for (var i in arrMPosProject) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrMPosProject[i].ProjectName + '" data-id="1" name="customize_' +  arrMPosProject[i].ProjectId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrMPosProject[i].ProjectName + '" id="customize_' + arrMPosProject[i].ProjectName + '" value="' + arrMPosProject[i].ProjectName + '_S">' +
        '<span>' + arrMPosProject[i].ProjectName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrMPosProject[i].ProjectName + '" value="' + arrMPosProject[i].ProjectId + '">'+
        '</div></li>';
    }
    $('#unCheckedUl_1').html(sHtml);
    $('#checkedUl_1').html();
    sHtml= "";
    for (var i in arrProjectTrans) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle check_vendor_background search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrProjectTrans[i].ProjectName + '" data-id="1" name="customize_' +  arrProjectTrans[i].ProjectId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrProjectTrans[i].ProjectName + '" id="customize_' + arrProjectTrans[i].ProjectName + '" value="' + arrProjectTrans[i].ProjectName + '_S"  checked="checked">' +
        '<span>' + arrProjectTrans[i].ProjectName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrProjectTrans[i].ProjectName + '" value="' + arrProjectTrans[i].ProjectId + '">'+
        '</div></li>';
    }
    $('#checkedUl_1').html(sHtml);
    $('#searchTitle1').html('Select Project');
    $('#searchTitle2').html('Selected Project');
    activeDiv = "project";
    showPermission('divactivity');
}

function showWorkType() {
    $('li a').removeClass("active");
    $("#per_worktype > a").addClass("active");
    $('.list-head').animate({
        scrollTop : $("#per_worktype").position().top
    });

    var arrMPosWorkType = [];
    for (var i in arrWorkTypeMaster) {
        var arr = $.grep(arrWorkTypeTrans, function (element, index) {
            return element.WorkTypeId == arrWorkTypeMaster[i].WorkTypeId});
        if (arr.length ==0) {
            arrMPosWorkType.push({
                WorkTypeId: arrWorkTypeMaster[i].WorkTypeId,
                WorkTypeName: arrWorkTypeMaster[i].WorkTypeName
            });
        }
    }

    $('#unCheckedUl_1').html();
    var sHtml= "";
    for (var i in arrMPosWorkType) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrMPosWorkType[i].WorkTypeName + '" data-id="1" name="customize_' +  arrMPosWorkType[i].WorkTypeId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrMPosWorkType[i].WorkTypeName + '" id="customize_' + arrMPosWorkType[i].WorkTypeName + '" value="' + arrMPosWorkType[i].WorkTypeName + '_S">' +
        '<span>' + arrMPosWorkType[i].WorkTypeName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrMPosWorkType[i].WorkTypeName + '" value="' + arrMPosWorkType[i].WorkTypeId + '">'+
        '</div></li>';
    }
    $('#unCheckedUl_1').html(sHtml);
    $('#checkedUl_1').html();
    sHtml= "";
    for (var i in arrWorkTypeTrans) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle check_vendor_background search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrWorkTypeTrans[i].WorkTypeName + '" data-id="1" name="customize_' +  arrWorkTypeTrans[i].WorkTypeId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrWorkTypeTrans[i].WorkTypeName + '" id="customize_' + arrWorkTypeTrans[i].WorkTypeName + '" value="' + arrWorkTypeTrans[i].WorkTypeName + '_S"  checked="checked">' +
        '<span>' + arrWorkTypeTrans[i].WorkTypeName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrWorkTypeTrans[i].WorkTypeName + '" value="' + arrWorkTypeTrans[i].WorkTypeId + '">'+
        '</div></li>';
    }
    $('#checkedUl_1').html(sHtml);
    $('#searchTitle1').html('Select WorkType');
    $('#searchTitle2').html('Selected WorkType');
    activeDiv = "worktype";
    showPermission('divactivity');
}
function showResourceType() {
    $('li a').removeClass("active");
    $("#per_resourcetype > a").addClass("active");
    $('.list-head').animate({
        scrollTop : $("#per_resourcetype").position().top
    });


    var arrMPosResourceType = [];
    for (var i in arrResourceTypeMaster) {
        var arr = $.grep(arrResourceTypeTrans, function (element, index) {
            return element.ResourceTypeId == arrResourceTypeMaster[i].ResourceTypeId});
        if (arr.length ==0) {
            arrMPosResourceType.push({
                ResourceTypeId: arrResourceTypeMaster[i].ResourceTypeId,
                ResourceTypeName: arrResourceTypeMaster[i].ResourceTypeName
            });
        }
    }

    $('#unCheckedUl_1').html();
    var sHtml= "";
    for (var i in arrMPosResourceType) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrMPosResourceType[i].ResourceTypeName + '" data-id="1" name="customize_' +  arrMPosResourceType[i].ResourceTypeId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrMPosResourceType[i].ResourceTypeName + '" id="customize_' + arrMPosResourceType[i].ResourceTypeName + '" value="' + arrMPosResourceType[i].ResourceTypeName + '_S">' +
        '<span>' + arrMPosResourceType[i].ResourceTypeName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrMPosResourceType[i].ResourceTypeName + '" value="' + arrMPosResourceType[i].ResourceTypeId + '">'+
        '</div></li>';
    }
    $('#unCheckedUl_1').html(sHtml);
    $('#checkedUl_1').html();
    sHtml= "";
    for (var i in arrResourceTypeTrans) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle check_vendor_background search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrResourceTypeTrans[i].ResourceTypeName + '" data-id="1" name="customize_' +  arrResourceTypeTrans[i].ResourceTypeId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrResourceTypeTrans[i].ResourceTypeName + '" id="customize_' + arrResourceTypeTrans[i].ResourceTypeName + '" value="' + arrResourceTypeTrans[i].ResourceTypeName + '_S"  checked="checked">' +
        '<span>' + arrResourceTypeTrans[i].ResourceTypeName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrResourceTypeTrans[i].ResourceTypeName + '" value="' + arrResourceTypeTrans[i].ResourceTypeId + '">'+
        '</div></li>';
    }
    $('#checkedUl_1').html(sHtml);
    $('#searchTitle1').html('Select ResourceType');
    $('#searchTitle2').html('Selected ResourceType');
    activeDiv = "resourcetype";
    showPermission('divactivity');
}
function showResourceGroup() {
    $('li a').removeClass("active");
    $("#per_resourcegroup > a").addClass("active");
    $('.list-head').animate({
        scrollTop : $("#per_resourcegroup").position().top
    });


    var arrMPosResourceGroup = [];
    for (var i in arrResourceGroupMaster) {
        var arr = $.grep(arrResourceGroupTrans, function (element, index) {
            return element.ResourceGroupId == arrResourceGroupMaster[i].ResourceGroupId});
        if (arr.length ==0) {
            arrMPosResourceGroup.push({
                ResourceGroupId: arrResourceGroupMaster[i].ResourceGroupId,
                ResourceGroupName: arrResourceGroupMaster[i].ResourceGroupName
            });
        }
    }

    $('#unCheckedUl_1').html();
    var sHtml= "";
    for (var i in arrMPosResourceGroup) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrMPosResourceGroup[i].ResourceGroupName + '" data-id="1" name="customize_' +  arrMPosResourceGroup[i].ResourceGroupId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrMPosResourceGroup[i].ResourceGroupName + '" id="customize_' + arrMPosResourceGroup[i].ResourceGroupName + '" value="' + arrMPosResourceGroup[i].ResourceGroupName + '_S">' +
        '<span>' + arrMPosResourceGroup[i].ResourceGroupName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrMPosResourceGroup[i].ResourceGroupName + '" value="' + arrMPosResourceGroup[i].ResourceGroupId + '">'+
        '</div></li>';
    }
    $('#unCheckedUl_1').html(sHtml);
    $('#checkedUl_1').html();
    sHtml= "";
    for (var i in arrResourceGroupTrans) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle check_vendor_background search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrResourceGroupTrans[i].ResourceGroupName + '" data-id="1" name="customize_' +  arrResourceGroupTrans[i].ResourceGroupId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrResourceGroupTrans[i].ResourceGroupName + '" id="customize_' + arrResourceGroupTrans[i].ResourceGroupName + '" value="' + arrResourceGroupTrans[i].ResourceGroupName + '_S"  checked="checked">' +
        '<span>' + arrResourceGroupTrans[i].ResourceGroupName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrResourceGroupTrans[i].ResourceGroupName + '" value="' + arrResourceGroupTrans[i].ResourceGroupId + '">'+
        '</div></li>';
    }
    $('#checkedUl_1').html(sHtml);
    $('#searchTitle1').html('Select ResourceGroup');
    $('#searchTitle2').html('Selected ResourceGroup');
    activeDiv = "resourcegroup";
    showPermission('divactivity');
}
function showServiceType() {
    $('li a').removeClass("active");
    $("#per_servicetype > a").addClass("active");
    $('.list-head').animate({
        scrollTop : $("#per_servicetype").position().top
    });


    var arrMPosServiceType = [];
    for (var i in arrServiceTypeMaster) {
        var arr = $.grep(arrServiceTypeTrans, function (element, index) {
            return element.ServiceTypeId == arrServiceTypeMaster[i].ServiceTypeId});
        if (arr.length ==0) {
            arrMPosServiceType.push({
                ServiceTypeId: arrServiceTypeMaster[i].ServiceTypeId,
                ServiceTypeName: arrServiceTypeMaster[i].ServiceTypeName
            });
        }
    }

    $('#unCheckedUl_1').html();
    var sHtml= "";
    for (var i in arrMPosServiceType) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrMPosServiceType[i].ServiceTypeName + '" data-id="1" name="customize_' +  arrMPosServiceType[i].ServiceTypeId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrMPosServiceType[i].ServiceTypeName + '" id="customize_' + arrMPosServiceType[i].ServiceTypeName + '" value="' + arrMPosServiceType[i].ServiceTypeName + '_S">' +
        '<span>' + arrMPosServiceType[i].ServiceTypeName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrMPosServiceType[i].ServiceTypeName + '" value="' + arrMPosServiceType[i].ServiceTypeId + '">'+
        '</div></li>';
    }
    $('#unCheckedUl_1').html(sHtml);
    $('#checkedUl_1').html();
    sHtml= "";
    for (var i in arrServiceTypeTrans) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle check_vendor_background search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrServiceTypeTrans[i].ServiceTypeName + '" data-id="1" name="customize_' +  arrServiceTypeTrans[i].ServiceTypeId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrServiceTypeTrans[i].ServiceTypeName + '" id="customize_' + arrServiceTypeTrans[i].ServiceTypeName + '" value="' + arrServiceTypeTrans[i].ServiceTypeName + '_S"  checked="checked">' +
        '<span>' + arrServiceTypeTrans[i].ServiceTypeName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrServiceTypeTrans[i].ServiceTypeName + '" value="' + arrServiceTypeTrans[i].ServiceTypeId + '">'+
        '</div></li>';
    }
    $('#checkedUl_1').html(sHtml);
    $('#searchTitle1').html('Select ServiceType');
    $('#searchTitle2').html('Selected ServiceType');
    activeDiv = "servicetype";
    showPermission('divactivity');
}
function showAccount() {
    $('li a').removeClass("active");
    $("#per_account > a").addClass("active");
    $('.list-head').animate({
        scrollTop : $("#per_account").position().top
    });


    var arrMPosAccount = [];
    for (var i in arrAccountMaster) {
        var arr = $.grep(arrAccountTrans, function (element, index) {
            return element.AccountId == arrAccountMaster[i].AccountId});
        if (arr.length ==0) {
            arrMPosAccount.push({
                AccountId: arrAccountMaster[i].AccountId,
                AccountName: arrAccountMaster[i].AccountName
            });
        }
    }

    $('#unCheckedUl_1').html();
    var sHtml= "";
    for (var i in arrMPosAccount) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrMPosAccount[i].AccountName + '" data-id="1" name="customize_' +  arrMPosAccount[i].AccountId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrMPosAccount[i].AccountName + '" id="customize_' + arrMPosAccount[i].AccountName + '" value="' + arrMPosAccount[i].AccountName + '_S">' +
        '<span>' + arrMPosAccount[i].AccountName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrMPosAccount[i].AccountName + '" value="' + arrMPosAccount[i].AccountId + '">'+
        '</div></li>';
    }
    $('#unCheckedUl_1').html(sHtml);
    $('#checkedUl_1').html();
    sHtml= "";
    for (var i in arrAccountTrans) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle check_vendor_background search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrAccountTrans[i].AccountName + '" data-id="1" name="customize_' +  arrAccountTrans[i].AccountId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrAccountTrans[i].AccountName + '" id="customize_' + arrAccountTrans[i].AccountName + '" value="' + arrAccountTrans[i].AccountName + '_S"  checked="checked">' +
        '<span>' + arrAccountTrans[i].AccountName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrAccountTrans[i].AccountName + '" value="' + arrAccountTrans[i].AccountId + '">'+
        '</div></li>';
    }
    $('#checkedUl_1').html(sHtml);
    $('#searchTitle1').html('Select Account');
    $('#searchTitle2').html('Selected Account');
    activeDiv = "account";
    showPermission('divactivity');
}
function showAccountType() {
    $('li a').removeClass("active");
    $("#per_accounttype > a").addClass("active");
    $('.list-head').animate({
        scrollTop : $("#per_accounttype").position().top
    });


    var arrMPosAccountType = [];
    for (var i in arrAccountTypeMaster) {
        var arr = $.grep(arrAccountTypeTrans, function (element, index) {
            return element.AccountTypeId == arrAccountTypeMaster[i].AccountTypeId});
        if (arr.length ==0) {
            arrMPosAccountType.push({
                AccountTypeId: arrAccountTypeMaster[i].AccountTypeId,
                AccountTypeName: arrAccountTypeMaster[i].AccountTypeName
            });
        }
    }

    $('#unCheckedUl_1').html();
    var sHtml= "";
    for (var i in arrMPosAccountType) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrMPosAccountType[i].AccountTypeName + '" data-id="1" name="customize_' +  arrMPosAccountType[i].AccountTypeId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrMPosAccountType[i].AccountTypeName + '" id="customize_' + arrMPosAccountType[i].AccountTypeName + '" value="' + arrMPosAccountType[i].AccountTypeName + '_S">' +
        '<span>' + arrMPosAccountType[i].AccountTypeName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrMPosAccountType[i].AccountTypeName + '" value="' + arrMPosAccountType[i].AccountTypeId + '">'+
        '</div></li>';
    }
    $('#unCheckedUl_1').html(sHtml);
    $('#checkedUl_1').html();
    sHtml= "";
    for (var i in arrAccountTypeTrans) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle check_vendor_background search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrAccountTypeTrans[i].AccountTypeName + '" data-id="1" name="customize_' +  arrAccountTypeTrans[i].AccountTypeId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrAccountTypeTrans[i].AccountTypeName + '" id="customize_' + arrAccountTypeTrans[i].AccountTypeName + '" value="' + arrAccountTypeTrans[i].AccountTypeName + '_S"  checked="checked">' +
        '<span>' + arrAccountTypeTrans[i].AccountTypeName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrAccountTypeTrans[i].AccountTypeName + '" value="' + arrAccountTypeTrans[i].AccountTypeId + '">'+
        '</div></li>';
    }
    $('#checkedUl_1').html(sHtml);
    $('#searchTitle1').html('Select AccountType');
    $('#searchTitle2').html('Selected AccountType');
    activeDiv = "accounttype";
    showPermission('divactivity');
}
function showSubLedgerType() {
    $('li a').removeClass("active");
    $("#per_subledgertype > a").addClass("active");
    $('.list-head').animate({
        scrollTop : $("#per_subledgertype").position().top
    });

    var arrMPosSubLedgerType = [];
    for (var i in arrSubLedgerTypeMaster) {
        var arr = $.grep(arrSubLedgerTypeTrans, function (element, index) {
            return element.SubLedgerTypeId == arrSubLedgerTypeMaster[i].SubLedgerTypeId});
        if (arr.length ==0) {
            arrMPosSubLedgerType.push({
                SubLedgerTypeId: arrSubLedgerTypeMaster[i].SubLedgerTypeId,
                SubLedgerTypeName: arrSubLedgerTypeMaster[i].SubLedgerTypeName
            });
        }
    }

    $('#unCheckedUl_1').html();
    var sHtml= "";
    for (var i in arrMPosSubLedgerType) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrMPosSubLedgerType[i].SubLedgerTypeName + '" data-id="1" name="customize_' +  arrMPosSubLedgerType[i].SubLedgerTypeId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrMPosSubLedgerType[i].SubLedgerTypeName + '" id="customize_' + arrMPosSubLedgerType[i].SubLedgerTypeName + '" value="' + arrMPosSubLedgerType[i].SubLedgerTypeName + '_S">' +
        '<span>' + arrMPosSubLedgerType[i].SubLedgerTypeName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrMPosSubLedgerType[i].SubLedgerTypeName + '" value="' + arrMPosSubLedgerType[i].SubLedgerTypeId + '">'+
        '</div></li>';
    }
    $('#unCheckedUl_1').html(sHtml);
    $('#checkedUl_1').html();
    sHtml= "";
    for (var i in arrSubLedgerTypeTrans) {
        sHtml = sHtml + '<li class="tile ui-sortable-handle check_vendor_background search-item">' +
        '<div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">' +
        '<label>' +
        '<input type="checkbox" class="search-element" data-name="' + arrSubLedgerTypeTrans[i].SubLedgerTypeName + '" data-id="1" name="customize_' +  arrSubLedgerTypeTrans[i].SubLedgerTypeId + '" onclick="checkSelectAll(1);"' +
        'tagname="cid" cid="' + arrSubLedgerTypeTrans[i].SubLedgerTypeName + '" id="customize_' + arrSubLedgerTypeTrans[i].SubLedgerTypeName + '" value="' + arrSubLedgerTypeTrans[i].SubLedgerTypeName + '_S"  checked="checked">' +
        '<span>' + arrSubLedgerTypeTrans[i].SubLedgerTypeName + '</span> </label>' +
        '<input class="selId" type="hidden" data-name="' + arrSubLedgerTypeTrans[i].SubLedgerTypeName + '" value="' + arrSubLedgerTypeTrans[i].SubLedgerTypeId + '">'+
        '</div></li>';
    }
    $('#checkedUl_1').html(sHtml);
    $('#searchTitle1').html('Select SubLedgerType');
    $('#searchTitle2').html('Selected SubLedgerType');
    activeDiv = "subledgertype";
    showPermission('divactivity');
}
function updateTeam() {
    arrTeamTrans = [];
    var $ids  = $("#checkedUl_1 .selId");
    $.each($ids, function (i, obj) {
        var $this = $(this);
        var iTeamId = $this[0].value,
            sTeamName= "";
        var arr = $.grep(arrTeamMaster, function (element, index) {
            return element.TeamId == iTeamId});
        if (arr.length >0) sTeamName = arr[0]['TeamName'];

        arrTeamTrans.push({
            TeamId: iTeamId,
            TeamName: sTeamName
        });
    });
    bTeam=true;
}
function updateAlert() {
    arrAlertTrans = [];
    var $ids  = $("#checkedUl_1 .selId");
    $.each($ids, function (i, obj) {
        var $this = $(this);
        var iAlertId = $this[0].value,
            sAlertName= "";
        var arr = $.grep(arrAlertMaster, function (element, index) {
            return element.AlertId == iAlertId});
        if (arr.length >0) sAlertName = arr[0]['AlertName'];

        arrAlertTrans.push({
            AlertId: iAlertId,
            AlertName: sAlertName
        });
    });
    bAlert=true;
}
function updateSuperior() {
    arrSuperiorTrans = [];
    var $ids  = $("#checkedUl_1 .selId");
    $.each($ids, function (i, obj) {
        var $this = $(this);
        var iUserId = $this[0].value,
            sUserName= "";
        var arr = $.grep(arrUserList, function (element, index) {
            return element.UserId == iUserId});
        if (arr.length >0) sUserName= arr[0]['UserName'];

        arrSuperiorTrans.push({
            SUserId: iUserId,
            UserName: sUserName
        });
    });
    bSuperior=true;
}
function updateAlternate() {
    arralTrans = [];
    var $ids  = $("#checkedUl_1 .selId");
    $.each($ids, function (i, obj) {
        var $this = $(this);
        var iUserId = $this[0].value,
            sUserName= "";
        var arr = $.grep(arrUserList, function (element, index) {
            return element.UserId == iUserId});
        if (arr.length >0) sUserName= arr[0]['UserName'];

        arrAlternateTrans.push({
            AUserId: iUserId,
            UserName: sUserName
        });
    });
    bAlternate=true;
}

function updateCompany() {
    arrCompanyTrans = [];
    var $ids  = $("#checkedUl_1 .selId");
    $.each($ids, function (i, obj) {
        var $this = $(this);
        var iCompanyId = $this[0].value,
            sCompanyName= "";
        var arr = $.grep(arrCompanyMaster, function (element, index) {
            return element.CompanyId == iCompanyId});
        if (arr.length >0) sCompanyName = arr[0]['CompanyName'];

        arrCompanyTrans.push({
            CompanyId: iCompanyId,
            CompanyName: sCompanyName
        });
    });
    bCompany=true;
}
function updateCostCentre() {
    arrCostCentreTrans = [];
    var $ids  = $("#checkedUl_1 .selId");
    $.each($ids, function (i, obj) {
        var $this = $(this);
        var iCostCentreId = $this[0].value,
            sCostCentreName= "";
        var arr = $.grep(arrCostCentreMaster, function (element, index) {
            return element.CostCentreId == iCostCentreId});
        if (arr.length >0) sCostCentreName = arr[0]['CostCentreName'];

        arrCostCentreTrans.push({
            CostCentreId: iCostCentreId,
            CostCentreName: sCostCentreName
        });
    });
    bCostCentre=true;
}
function updateProject() {
    arrProjectTrans = [];
    var $ids  = $("#checkedUl_1 .selId");
    $.each($ids, function (i, obj) {
        var $this = $(this);
        var iProjectId = $this[0].value,
            sProjectName= "";
        var arr = $.grep(arrProjectMaster, function (element, index) {
            return element.ProjectId == iProjectId});
        if (arr.length >0) sProjectName = arr[0]['ProjectName'];

        arrProjectTrans.push({
            ProjectId: iProjectId,
            ProjectName: sProjectName
        });
    });
    bProject=true;
}
function updateWorkType() {
    arrWorkTypeTrans = [];
    var $ids  = $("#checkedUl_1 .selId");
    $.each($ids, function (i, obj) {
        var $this = $(this);
        var iWorkTypeId = $this[0].value,
            sWorkTypeName= "";
        var arr = $.grep(arrWorkTypeMaster, function (element, index) {
            return element.WorkTypeId == iWorkTypeId});
        if (arr.length >0) sWorkTypeName = arr[0]['WorkTypeName'];

        arrWorkTypeTrans.push({
            WorkTypeId: iWorkTypeId,
            WorkTypeName: sWorkTypeName
        });
    });
    bWorkType=true;
}
function updateResourceType() {
    arrResourceTypeTrans = [];
    var $ids  = $("#checkedUl_1 .selId");
    $.each($ids, function (i, obj) {
        var $this = $(this);
        var iResourceTypeId = $this[0].value,
            sResourceTypeName= "";
        var arr = $.grep(arrResourceTypeMaster, function (element, index) {
            return element.ResourceTypeId == iResourceTypeId});
        if (arr.length >0) sResourceTypeName = arr[0]['ResourceTypeName'];

        arrResourceTypeTrans.push({
            ResourceTypeId: iResourceTypeId,
            ResourceTypeName: sResourceTypeName
        });
    });
    bResourceType=true;
}
function updateResourceGroup() {
    arrResourceGroupTrans = [];
    var $ids  = $("#checkedUl_1 .selId");
    $.each($ids, function (i, obj) {
        var $this = $(this);
        var iResourceGroupId = $this[0].value,
            sResourceGroupName= "";
        var arr = $.grep(arrResourceGroupMaster, function (element, index) {
            return element.ResourceGroupId == iResourceGroupId});
        if (arr.length >0) sResourceGroupName = arr[0]['ResourceGroupName'];

        arrResourceGroupTrans.push({
            ResourceGroupId: iResourceGroupId,
            ResourceGroupName: sResourceGroupName
        });
    });
    bResourceGroup=true;
}
function updateServiceType() {
    arrServiceTypeTrans = [];
    var $ids  = $("#checkedUl_1 .selId");
    $.each($ids, function (i, obj) {
        var $this = $(this);
        var iServiceTypeId = $this[0].value,
            sServiceTypeName= "";
        var arr = $.grep(arrServiceTypeMaster, function (element, index) {
            return element.ServiceTypeId == iServiceTypeId});
        if (arr.length >0) sServiceTypeName = arr[0]['ServiceTypeName'];

        arrServiceTypeTrans.push({
            ServiceTypeId: iServiceTypeId,
            ServiceTypeName: sServiceTypeName
        });
    });
    bServiceType=true;
}
function updateAccount() {
    arrAccountTrans = [];
    var $ids  = $("#checkedUl_1 .selId");
    $.each($ids, function (i, obj) {
        var $this = $(this);
        var iAccountId = $this[0].value,
            sAccountName= "";
        var arr = $.grep(arrAccountMaster, function (element, index) {
            return element.AccountId == iAccountId});
        if (arr.length >0) sAccountName = arr[0]['AccountName'];

        arrAccountTrans.push({
            AccountId: iAccountId,
            AccountName: sAccountName
        });
    });
    bAccount=true;
}
function updateAccountType() {
    arrAccountTypeTrans = [];
    var $ids  = $("#checkedUl_1 .selId");
    $.each($ids, function (i, obj) {
        var $this = $(this);
        var iAccountTypeId = $this[0].value,
            sAccountTypeName= "";
        var arr = $.grep(arrAccountTypeMaster, function (element, index) {
            return element.AccountTypeId == iAccountTypeId});
        if (arr.length >0) sAccountTypeName = arr[0]['AccountTypeName'];

        arrAccountTypeTrans.push({
            AccountTypeId: iAccountTypeId,
            AccountTypeName: sAccountTypeName
        });
    });
    bAccountType=true;
}
function updateSubLedgerType() {
    arrSubLedgerTypeTrans = [];
    var $ids  = $("#checkedUl_1 .selId");
    $.each($ids, function (i, obj) {
        var $this = $(this);
        var iSubLedgerTypeId = $this[0].value,
            sSubLedgerTypeName= "";
        var arr = $.grep(arrSubLedgerTypeMaster, function (element, index) {
            return element.SubLedgerTypeId == iSubLedgerTypeId});
        if (arr.length >0) sSubLedgerTypeName = arr[0]['SubLedgerTypeName'];

        arrSubLedgerTypeTrans.push({
            SubLedgerTypeId: iSubLedgerTypeId,
            SubLedgerTypeName: sSubLedgerTypeName
        });
    });
    bSubLedgerType=true;
}
function updateActivity() {
    var argActivityIds="";
    arrActivityTrans = [];
    var $ids  = $("#checkedUl_1 .selId");
    $.each($ids, function (i, obj) {
        var $this = $(this);
        var iActivityId = $this[0].value,
            sActivityName= "";
        argActivityIds = argActivityIds + iActivityId + ",";
        var arr = $.grep(arrActivityMaster, function (element, index) {
            return element.ActivityId == iActivityId});
        if (arr.length >0) sActivityName = arr[0]['ActivityName'];

        arrActivityTrans.push({
            ActivityId: iActivityId,
            ActivityName: sActivityName
        });
    });
    if (argActivityIds !="") argActivityIds = argActivityIds.substring(0, argActivityIds.length - 1);
    bActivity=true;
    bRole=true;
    getRole(argActivityIds);
}

function showinformPendingwork() {
    $('li a').removeClass("active");
    $("#per_informpendingwork > a").addClass("active");
    $('.list-head').animate({
        scrollTop: $("#per_informpendingwork").position().top
    })


    var sHtml = "";
    for (var i in arrRoleTrans) {
        var sTaskName =  arrRoleTrans[i].TaskName,
            sRoleType =  arrRoleTrans[i].RoleType;

        if (sRoleType == 'N' || sRoleType == 'A') {

            var arr = $.grep(arrTaskTransMaster, function (element, index) {
                return element.TaskName == sTaskName && element.RoleType == sRoleType
            });

            for (var k in arr) {
                var iRoleId = 0, sRoleName = "";
                iRoleId = arr[k]['RoleId'];
                sRoleName = arr[k]['RoleName'];
                var bScreen = "", bEmail = "", bSMS = "";
                var arrN = [];

                arrN = $.grep(arrInformPendingworkTrans, function (element, index) {
                    return element.RoleId == iRoleId
                });

                if (arrN.length > 0) {
                    if (arrN[0].Screen == 1) bScreen = "checked";
                    if (arrN[0].EMail == 1) bEmail = "checked";
                    if (arrN[0].SMS == 1) bSMS = "checked";
                }

                sHtml = sHtml + '<tr class="col-xs-12" style="padding:0 !important">' +
                '<td class="col-xs-6">' + sRoleName +
                '</td>' +
                '<td class="col-xs-2"><div align="center" class="checkbox checkbox-styled tile-text">' +
                '<label>' +
                '<input  class="search-element" id="ptask_A_' + i + '" value="1" data-name="' + sRoleName + '" onchange="checkPendingworkChange(this.id)" ' + bScreen + ' type="checkbox">' +
                '<span></span>' +
                '</label>' +
                '</div></td>' +
                '<td class="col-xs-2"><div align="center" class="checkbox checkbox-styled tile-text">' +
                '<label>' +
                '<input id="ptask_B_' + i + '" value="1" onchange="checkPendingworkChange(this.id)" ' + bEmail + ' type="checkbox">' +
                '<span></span>' +
                '</label>' +
                '</div></td>' +
                '<td class="col-xs-2"><div align="center" class="checkbox checkbox-styled tile-text">' +
                '<label>' +
                '<input id="ptask_C_' + i + '" value="1" onchange="checkPendingworkChange(this.id)" ' + bSMS + ' type="checkbox">' +
                '<span></span>' +
                '</label>' +
                '</div></td>' +
                '<input type="hidden" id ="proleId_' + i + '" value="' + iRoleId + '">' +
                '<input type="hidden" id ="proleName_' + i + '" value="' + sRoleName + '">' +
                '</tr>';
            }
        }
    }
    $('#informpendingworkTable > tbody').html(sHtml);

    showPermission('divinformpendingwork');
}

function showinformAlert() {

    $('li a').removeClass("active");
    $("#per_informalert > a").addClass("active");
    $('.list-head').animate({
        scrollTop: $("#per_informalert").position().top
    });

    var sHtml = "";

    for (var i in arrAlertTrans) {
        var bScreen = "", bEmail = "", bSMS = "";
        var arr = [];

        arr = $.grep(arrInformAlertTrans, function (element, index) {
            return element.AlertId == arrAlertTrans[i].AlertId
        });

        if (arr.length > 0) {
            if (arr[0].Screen == 1) bScreen = "checked";
            if (arr[0].EMail == 1) bEmail = "checked";
            if (arr[0].SMS == 1) bSMS = "checked";

        }

        sHtml = sHtml + '<tr class="col-xs-12" style="padding:0 !important">' +
        '<td class="col-xs-6">' + arrAlertTrans[i].AlertName +
        '</td>' +
        '<td class="col-xs-2"><div align="center" class="checkbox checkbox-styled tile-text">' +
        '<label>' +
        '<input  class="search-element" id="atask_A_' + i + '" value="1" data-name="' + arrAlertTrans[i].AlertName + '" onchange="checkAlertChange(this.id)" ' + bScreen + ' type="checkbox">' +
        '<span></span>' +
        '</label>' +
        '</div></td>' +
        '<td class="col-xs-2"><div align="center" class="checkbox checkbox-styled tile-text">' +
        '<label>' +
        '<input id="atask_B_' + i + '" value="1" onchange="checkAlertChange(this.id)" ' + bEmail + ' type="checkbox">' +
        '<span></span>' +
        '</label>' +
        '</div></td>' +
        '<td class="col-xs-2"><div align="center" class="checkbox checkbox-styled tile-text">' +
        '<label>' +
        '<input id="atask_C_' + i + '" value="1" onchange="checkAlertChange(this.id)" ' + bSMS + ' type="checkbox">' +
        '<span></span>' +
        '</label>' +
        '</div></td>' +
        '<input type="hidden" id ="aalertName_' + i + '" value="' + arrAlertTrans[i].AlertName + '">' +
        '<input type="hidden" id ="aalertId_' + i + '" value="' + arrAlertTrans[i].AlertId + '">' +
        '</tr>';
    }
    $('#informalertTable > tbody').html(sHtml);

    showPermission('divinformalert');
}

function showRole () {
    $('li a').removeClass("active");
    $("#per_role > a").addClass("active");
    $('.list-head').animate({
        scrollTop : $("#per_role").position().top
    });

    var sHtml = "";

    for (var i in arrRoleMaster) {
        var bAdd = "",bEdit="",bDelete="",bApprove="",bView="";
        var arr= [];

        arr = $.grep(arrRoleTrans, function (element, index) {
            return element.TaskName == arrRoleMaster[i].TaskName && element.RoleType == 'N'});
        if (arr.length >0) bAdd = "checked";

        arr = $.grep(arrRoleTrans, function (element, index) {
            return element.TaskName == arrRoleMaster[i].TaskName && element.RoleType == 'E'});
        if (arr.length >0) bEdit = "checked";


        arr = $.grep(arrRoleTrans, function (element, index) {
            return element.TaskName == arrRoleMaster[i].TaskName && element.RoleType == 'D'});
        if (arr.length >0) bDelete = "checked";


        arr = $.grep(arrRoleTrans, function (element, index) {
            return element.TaskName == arrRoleMaster[i].TaskName && element.RoleType == 'A'});
        if (arr.length >0) bApprove = "checked";


        arr = $.grep(arrRoleTrans, function (element, index) {
            return element.TaskName == arrRoleMaster[i].TaskName && element.RoleType == 'S'});
        if (arr.length >0) bView = "checked";

        sHtml = sHtml + '<tr class="col-xs-12" style="padding:0 !important">' +
        '<td class="col-xs-7">' + arrRoleMaster[i].TaskName +
        '</td>' +
        '<td class="col-xs-1"><div align="center" class="checkbox checkbox-styled tile-text">' +
        '<label>' +
        '<input  class="search-element" id="task_N_' + i + '" value="1" data-name="' + arrRoleMaster[i].TaskName + '" onchange="checkRoleChange(this.id)" ' + bAdd + ' type="checkbox">' +
        '<span></span>' +
        '</label>' +
        '</div></td>' +
        '<td class="col-xs-1"><div align="center" class="checkbox checkbox-styled tile-text">' +
        '<label>' +
        '<input id="task_E_' + i + '" value="1" onchange="checkRoleChange(this.id)" ' + bEdit + ' type="checkbox">' +
        '<span></span>' +
        '</label>' +
        '</div></td>' +
        '<td class="col-xs-1"><div align="center" class="checkbox checkbox-styled tile-text">' +
        '<label>' +
        '<input id="task_D_' + i + '" value="1" onchange="checkRoleChange(this.id)" ' + bDelete + ' type="checkbox">' +
        '<span></span>' +
        '</label>' +
        '</div></td>' +
        '<td class="col-xs-1"><div align="center" class="checkbox checkbox-styled tile-text">' +
        '<label>' +
        '<input id="task_A_' + i + '" value="1" onchange="checkRoleChange(this.id)" ' + bApprove + ' type="checkbox">' +
        '<span></span>' +
        '</label>' +
        '</div></td>' +
        '<td class="col-xs-1"><div align="center" class="checkbox checkbox-styled tile-text">' +
        '<label>' +
        '<input id="task_S_' + i + '" value="1" onchange="checkRoleChange(this.id)" ' + bView + ' type="checkbox">' +
        '<span></span>' +
        '</label>' +
        '</div></td>' +
        '<input type="hidden" id ="taskRowName_'+ i + '" value="' + arrRoleMaster[i].TaskName + '">'+
        '</tr>';
    }
    $('#taskTable > tbody').html(sHtml);

    showPermission('divrole');
}

function showRolePermission() {
    $('li a').removeClass("active");
    $("#per_permission > a").addClass("active");
    $('.list-head').animate({
        scrollTop : $("#per_permission").position().top
    });


    var sHtml = "";
    for (var i in arrPermissionMaster) {
        var sChecked = "";

        arr = $.grep(arrPermissionTrans, function (element, index) {
            return element.RoleId == arrPermissionMaster[i].RoleId});
        if (arr.length >0) sChecked = "checked";

        sHtml = sHtml + '<tr class="col-xs-12" style="padding:0 !important">' +
        '<td class="col-xs-1"> <div class="checkbox checkbox-styled">' +
        '<label>' +
        '<input class="search-element"  value="1" data-name="' + arrPermissionMaster[i].RoleName + '" onchange="checkPerChange(this.id)" ' + sChecked + ' type="checkbox" id="per_' + arrPermissionMaster[i].RoleId + '">' +
        '<span>&nbsp;</span> </label>' +
        '</div></td>' +
        '<td class="col-xs-11">' + arrPermissionMaster[i].RoleName + '</td>' +
        '<input type="hidden" id ="perRoleName_'+ arrPermissionMaster[i].RoleId + '" value="' + arrPermissionMaster[i].RoleName + '">'+
        '</tr>';
    }

    $('#roleTable > tbody').html(sHtml);
    showPermission('divpermissionrole');
}

function showVariance() {
    $('li a').removeClass("active");
    $("#per_variance > a").addClass("active");
    $('.list-head').animate({
        scrollTop : $("#per_variance").position().top
    });

    var sHtml = "";

    for (var i in arrVariantMaster) {
        var sChecked = "";

        arr = $.grep(arrVariantTrans, function (element, index) {
            return element.RoleId == arrVariantMaster[i].RoleId});
        if (arr.length >0) sChecked = "checked";

        sHtml = sHtml + '<tr class="col-xs-12" style="padding:0 !important">' +
        '<td class="col-xs-1"> <div class="checkbox checkbox-styled">' +
        '<label>' +
        '<input class="search-element"  value="1" data-name="' + arrVariantMaster[i].RoleName + '" ' + sChecked + ' type="checkbox" id="per_' + arrVariantMaster[i].RoleId + '">' +
        '<span>&nbsp;</span> </label>' +
        '</div></td>' +
        '<td class="col-xs-9">' + arrVariantMaster[i].RoleName + '</td>' +
        '<td class="col-xs-2"><input class="parent_text text-right" type="text" maxlength="15" id="var_'+ arrVariantMaster[i].RoleId + '" value = "" onblur="return FormatNum(this, 2,true)" onkeypress="return isDecimal(event,this)" onchange="checkvarianceValue(this.id)" /></td>'+
        '<input type="hidden" id ="varRoleName_'+ arrVariantMaster[i].RoleId + '" value="' + arrPermissionMaster[i].RoleName + '">'+
        '</tr>';
    }

    $('#varianceTable > tbody').html(sHtml);
    showPermission('divvariance');
}

function checkAlertChange(x) {
    var sType = x.split('_')[1],
        key = x.split('_')[2],
        iAlertId = $('#aalertId_' + key).val(),
        bScreen=0,bEmail= 0,bSMS= 0, sAlertName=$('#aalertName_' + key).val();

    if ($('#atask_A_' + key).is(':checked')) bScreen=1;
    if ($('#atask_B_' + key).is(':checked')) bEmail=1;
    if ($('#atask_C_' + key).is(':checked')) bSMS=1;

    var arrN = $.grep(arrInformAlertTrans, function (element, index) {
        return element.AlertId != iAlertId});
    arrInformAlertTrans = [];
    arrInformAlertTrans = arrN;

    arrInformAlertTrans.push({
        AlertId: iAlertId,
        AlertName: sAlertName,
        Screen:bScreen,
        EMail:bEmail,
        SMS:bSMS
    });

    bInformAlert=true;
}

function checkPendingworkChange(x) {
    var sType = x.split('_')[1],
        key = x.split('_')[2],
        iRoleId = $('#proleId_' + key).val(),
        bScreen=0,bEmail= 0,bSMS= 0, sRoleName=$('#proleName_' + key).val();

    if ($('#ptask_A_' + key).is(':checked')) bScreen=1;
    if ($('#ptask_B_' + key).is(':checked')) bEmail=1;
    if ($('#ptask_C_' + key).is(':checked')) bSMS=1;

    var arrN = $.grep(arrInformPendingworkTrans, function (element, index) {
        return element.RoleId != iRoleId});
    arrInformPendingworkTrans = [];
    arrInformPendingworkTrans = arrN;

    arrInformPendingworkTrans.push({
        RoleId: iRoleId,
        RoleName: sRoleName,
        Screen:bScreen,
        EMail:bEmail,
        SMS:bSMS
    });

    bInformPendingwork=true;
}


function checkRoleChange(x) {
    var sRoleType = x.split('_')[1],
        key = x.split('_')[2],
        sTaskName = $('#taskRowName_' + key).val();
    if ($('#'+ x).is(':checked')) {
        var arr = $.grep(arrTaskTransMaster, function (element, index) {
            return element.TaskName == sTaskName && element.RoleType == sRoleType});
        var iRoleId = 0;
        if (arr.length >0) iRoleId = arr[0]['RoleId'];

        var arrN = $.grep(arrRoleTrans, function (element, index) {
            return element.TaskName != sTaskName || element.RoleType != sRoleType});
        arrRoleTrans = [];
        arrRoleTrans = arrN;

        arrRoleTrans.push({
            TaskName: sTaskName,
            RoleType: sRoleType,
            RoleId:iRoleId
        });
    } else {
        var arr = $.grep(arrRoleTrans, function (element, index) {
            return element.TaskName != sTaskName || element.RoleType != sRoleType});
        arrRoleTrans = [];
        arrRoleTrans = arr;
    }
    bRole=true;
}

function checkPerChange(x) {
    var iRoleId = x.split('_')[1],
        sRoleName = $('#perRoleName_' + iRoleId).val();
    if ($('#'+ x).is(':checked')) {
        arrPermissionTrans.push({
            RoleId:iRoleId,
            RoleName:sRoleName
        });
    } else {
        var arr = $.grep(arrPermissionTrans, function (element, index) {
            return element.RoleId != iRoleId});
        arrPermissionTrans = [];
        arrPermissionTrans = arr;
    }
    bRole=true;
}
function checkvarianceValue(x) {
    var iRoleId = x.split('_')[1],
        sRoleName = $('#varRoleName_' + iRoleId).val(),
        dVariant= $('#var_' + iRoleId).val();

    if ($('#'+ x).is(':checked')) {
        arrVariantTrans.push({
            RoleId:iRoleId,
            RoleName:sRoleName,
            Variant:dVariant
        });
    } else {
        var arr = $.grep(arrVariantTrans, function (element, index) {
            return element.RoleId != iRoleId});
        arrVariantTrans = [];
        arrVariantTrans = arr;
    }
    bRole=true;
}

function getRole(argActivityIds) {
    arrRoleMaster = [];
    arrPermissionMaster = [];
    arrVariantMaster = [];

    if (argActivityIds == "")  return;
    $.ajax({
        url: getBaseURL() + 'workflow/index/getUserActivityRoles',
        type: 'POST',
        async: false,
        data: {"ActivityId": argActivityIds},
        success: function (data, textStatus, jqXHR) {
            var sHtml = "";
            var obj = jQuery.parseJSON(data);
            arrRoleMaster = obj['roleTrans'];
            arrPermissionMaster = obj['permissionTrans'];
            arrVariantMaster = obj['variantTrans'];
        },
        error: function (jqXHR, textStatus, errorThrown) {
            alert('Request Failed');
        }
    });
}


function showPermission(x) {
    $('.divPermission').hide();
    $('#' + x).show();
}


function chkSearch(x) {
    var $x = $(x),
        searchText = $.trim($x.val()),
        $checklistWrapper = $x.parents('.headingWrapper').next('.card'),
        delayTimer = 0;
    clearTimeout(delayTimer);
    delayTimer = setTimeout(function () {
        if(searchText.length == 0) {
            $checklistWrapper.find('.search-element').closest('.search-item').show();
            return;
        }
        var $foundChks = $checklistWrapper.find('.search-element');

        $.each($foundChks, function () {
            var name = $(this).attr('data-name').toLowerCase();
//                console.log(name);
            if(name.indexOf(searchText.toLowerCase()) == -1) {
                $(this).closest('.search-item').fadeOut(100);
                return;
            }
            $(this).closest('.search-item').fadeIn(100);
//                $(this).closest('tr').fadeIn(100);
        });
    }, 300);
}

function chkSearchtr(x) {
    var $x = $(x),
        searchText = $.trim($x.val()),
        $checklistWrapper = $x.parents('.headingWrapper').next('.card'),
        delayTimer = 0;

    //console.log($checklistWrapper);
    clearTimeout(delayTimer);
    delayTimer = setTimeout(function () {
        if(searchText.length == 0) {
            $checklistWrapper.find('.search-element').closest('tr').show();
            return;
        }
        var $foundChks = $checklistWrapper.find('.search-element');
        $.each($foundChks, function () {
            var name = $(this).attr('data-name').toLowerCase();
            // console.log(name);
            if(name.indexOf(searchText.toLowerCase()) == -1) {
                $(this).closest('tr').fadeOut(100);
                return;
            }
            //$(this).closest('.search-item').fadeIn(100);
            $(this).closest('tr').fadeIn(100);
        });
    }, 300);
}

$('.urId').on('click',function(){
    var urlId = $(this).attr('data-index');
    location.replace("<?php echo $this->basePath(); ?>/workflow/index/user-entry/"+urlId);
});
</script>