<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css';?>"/>
<!-----scheduler js----->
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/jqxwindow.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/jqxdatetimeinput.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/jqxcalendar.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqxdate.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqxradiobutton.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqxscheduler.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqxscheduler.api.js"></script>
<!-----scheduler js end----->
<style>
.action_btns{margin:10px 0 15px 0}
.butclr-ns{background-color: #fff; border:1px solid #3399ff;box-shadow:none;border-radius:none;width:35px; height:35px;}
.butclr{background:none; border:none; color:#3399ff;box-shadow:none;}
.butclr-ns p.sam-up i{ color: #3399ff !important;line-height:34px;font-weight:700}
.butclr:hover,.butclr-ns:hover{box-shadow:none;}
.savebtn_area{margin:0}
.tab-content{background:#fff; padding:20px; border:1px solid #ddd}
.filter-group label{width:100%; padding:5px 0}
.filter-group .form-group{margin-bottom:10px !important}
.lbl_move{height:40px !important}
 /*---------------table- fixed--------------*/
.fixedTable .table {background-color: white; margin-bottom: 0;  width: auto;}
.fixedTable .table tr th{}
.fixedTable .table tr td,.fixedTable .table tr th {min-width: 110px;overflow: hidden;width: 100px;padding: 5px;}
.fixedTable-header {width: 100%; background: #DAEAF0 none repeat scroll 0 0; border-bottom: 2px solid #5d9bb6 !important;border-top: 1px solid #dddddd !important;color: #424141;line-height:30px;font-weight: 600;white-space: nowrap;overflow: hidden;height:40px;}
.fixedTable-sidebar .table tbody tr td{background:#DAEAF0;}
.fixedTable-sidebar {width: 10.5%;height: 310px;float: left;overflow: hidden;border-right: 1px solid #5d9bb6;}
.fixedTable-body {overflow: auto;width:89.5%;height: 310px;float: left;}
/*---------------Jqxscheduler style end---------------*/
    .jqx-fill-state-normal{background:#fff !important; padding:3px 6px !important;}
    .jqx-scheduler-legend-label	{color:#1070c7;font-size:14px;font-weight:400;float:left;margin-right:15px;margin-top:2px;}
    .jqx-scheduler-legend				{float:left; border:1px solid #DCDCDC!important; margin-right:5px !important;}
    .jqx-scheduler-legend 				{border-style:solid;border-width:1px;cursor:pointer;float:left;height:14px;margin-right:3px;margin-top:4px;vertical-align:middle;width:14px;}
    .jqx-scheduler-cell-hover 	    	{background:#D18EC9!important;border-color:#B56BAC!important;}
    .jqx-grid-table .jqx-grid-cell 		{border-width:0 0 1px 1px;}
    .jqx-widget .jqx-grid-cell, .jqx-widget .jqx-grid-column-header, .jqx-widget .jqx-grid-group-cell{border-color:#aaa;}
    .jqx-widget .jqx-grid-cell 			{border-color:#c2c2c2 !important;}
    .jqx-scheduler-month-weekend-cell 	{background:#DDDCE8 !important;border:1px solid #B7B6DB !important;}
    .jqx-scheduler-month-cell			{color:#000 !important;  text-align:center !important;}
    .jqx-widget-content					{background:#fff !important;;}
    .jqx-fill-state-pressed				{background:#fff !important; border-color:#3399ff; color:#3399ff!important;}
    .jqx-window-content					{padding:10px;}
    .jqx-scheduler-edit-dialog-label 	{clear:both;float:left;line-height:25px;margin-left:2%;padding:4px;text-align:right;width:20%;}
    .jqx-scheduler-edit-dialog-field 	{clear:right;float:right;margin-right:2%;padding:4px;width:70%;}
    .jqx-listitem-element				{background-color:#fff; color:#333;}
    .jqx-timepicker-hour				{width:30px;text-align:center; float:left; margin-left:5px;}
    .jqx-timepicker-minute 				{width:30px;text-align:center; float:left; }
    .jqx-timepicker-meridian			{width:30px;text-align:center; float:left; }
    .jqx-date-time-input-popup			{background:#9CF; margin:5px;}
    .jqx-popu							{background:#fff;}
    .jqx-fill-state-hover				{border:1px solid #c2c2c2; font-size:13px;}
    .jqx-combobox-content-focus-arctic, .jqx-combobox-state-focus-arctic, .jqx-fill-state-focus-arctic, .jqx-numberinput-focus-arctic {border-color:#959595;outline:medium none;}
    .jqx-icon-time:before 				{font-family:FontAwesome;content:"\f017";display:inline-block;font-size:15px;font-weight:400;color:#999A99;padding-right:3px;}
    .jqx-popup-arctic 					{border:1px solid #ccc; background:#fff;}
    .jqx-scheduler-appointment-inner-content{ font-size:14px; font-weight:400px;}
    .jqx-popup 							{box-sizing:content-box;}
    .jqx-date-time-input-popup table td a {border:1px solid transparent;color:#333;display:inline-block;margin:0;outline:0 none;padding:0;width:100%;}
    .jqx-date-time-input-popup .jqx-icon {margin-top: 0;}
    .jqx-radiobutton-check-checked-arctic {background:#808080 !important;border-radius:100%;filter:none;}
    .jqx-menu-item-top-arctic { color:#060 !important; font-size:13px;}
<!---------------Jqxscheduler style end--------------->

</style>
<div class="content_wrapper padlr0">
  <div class="container-fluid">
    <h1 class="col-md-8 text-left animated growIn">Request dicition approval</h1>
	<div class="col-md-4"> <a href="#" class="butclr-ns1"><i class="fa fa-files-o"></i></a></div>
	<div class="col-md-12 filter-group">
	 <div class="form-group col-md-3" style="padding:0 !important">
	 <label>From</label>
            <input type="text"  name="NewsDate" class="form-control date_picker lbl_move" />
            <span class="date_icon" style="top:inherit;bottom:17px"><i class="fa fa-calendar"></i></span>
        </div>
		 <div class="form-group col-md-2" style="padding-right:0 !important">
		  <label>to</label>
            <input type="text"  name="NewsDate" class="form-control date_picker lbl_move"/>
            <span class="date_icon"style="top:inherit;bottom:17px"><i class="fa fa-calendar"></i></span>
        </div>
		 <div class="form-group col-md-3" style="padding-right:0 !important">
		  <label>Project</label>
           <select class="form-control single_dropdown lbl_move" style="width:100%;">
                <option></option>
                <option selected>Most Recent</option>
              </select>
        </div>
		<div class="form-group col-md-2"style="padding-right:0 !important">
		 <label>Task Type</label>
          <select class="form-control single_dropdown lbl_move" style="width:100%;">
                <option></option>
                <option selected>Most Recent</option>
              </select>
        </div>
		<div class="form-group col-md-2"style="padding-right:0 !important">
		 <label>Task</label>
           <select class="form-control single_dropdown lbl_move" style="width:100%;">
                <option></option>
                <option selected>Most Recent</option>
              </select>
        </div>
		
	</div>
	<!-- Nav tabs -->
      <ul class="nav nav-tabs nav-controls" role="tablist">
        <li role="presentation" class="active"><a href="#task-view" aria-controls="task-view" role="tab" data-toggle="tab">Task View</a></li>
         <li role="presentation"><a href="#calc-view" aria-controls="calc-view" role="tab" data-toggle="tab">Calendar</a></li> </ul>                           
  <div class="tab-content col-md-12">                        
    <div class="col-md-12 tab-pane active" role="tabpanel" id="task-view">
      <div class="col-md-4 col-sm-4 animated-panel zoomIn">
        <div class="col-md-12 goal-bg form-group ">
          <h6 class="head-tt">TODO &nbsp;(5)</h6>
          <ul class="todo">
            <li><a href="#" data-toggle="modal" data-target="#largequicker1">Request dicition approval</a><span>today</span>
              <p>Ref No.1536 Dt. 15-Nov-16</p>
            </li>
            <li><a href="#" data-toggle="modal" data-target="#largequicker1">Request dicition approval</a><span>today</span>
              <p>Ref No.1536 Dt. 15-Nov-16</p>
            </li>
            <li><a href="#" data-toggle="modal" data-target="#largequicker1">Request dicition approval</a><span>today</span>
              <p>Ref No.1536 Dt. 15-Nov-16</p>
            </li>
            <li><a href="#" data-toggle="modal" data-target="#largequicker1">Request dicition approval</a><span>today</span>
              <p>Ref No.1536 Dt. 15-Nov-16</p>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-4 col-sm-4 animated-panel zoomIn">
        <div class="col-md-12 goal-bg form-group ">
          <h6 class="head-tt">In Progress &nbsp;(15)</h6>
          <ul class="todo">
            <li><a href="#" data-toggle="modal" data-target="#largequicker1">Request dicition approval</a><span>today</span>
              <p>Ref No.1536 Dt. 15-Nov-16</p>
            </li>
            <li><a href="#">Request dicition approval</a><span>today</span>
              <p>Ref No.1536 Dt. 15-Nov-16</p>
            </li>
            <li><a href="#">Request dicition approval</a><span>today</span>
              <p>Ref No.1536 Dt. 15-Nov-16</p>
            </li>
            <li><a href="#">Request dicition approval</a><span>today</span>
              <p>Ref No.1536 Dt. 15-Nov-16</p>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-4 col-sm-4 animated-panel zoomIn">
        <div class="col-md-12 goal-bg form-group ">
          <h6 class="head-tt">Completed &nbsp;(20)</h6>
          <ul class="todo">
            <li><a href="#">Request dicition approval</a><span>today</span>
              <p>Ref No.1536 Dt. 15-Nov-16</p>
            </li>
            <li><a href="#">Request dicition approval</a><span>today</span>
              <p>Ref No.1536 Dt. 15-Nov-16</p>
            </li>
            <li><a href="#">Request dicition approval</a><span>today</span>
              <p>Ref No.1536 Dt. 15-Nov-16</p>
            </li>
            <li><a href="#">Request dicition approval</a><span>today</span>
              <p>Ref No.1536 Dt. 15-Nov-16</p>
            </li>
          </ul>
        </div>
      </div>
    </div>
	<!--tab-1--->
	<div class="col-md-12 tab-pane" role="tabpanel" id="calc-view">
	<div class="col-lg-12 animated-panel zoomIn" style="margin-bottom:10px;">
    <div id="scheduler" class="matbt-25"></div>
</div>
	</div>
	<!--tab-2--->
	</div>
	
	<div class="col-md-12 form-group">
	<div class="fixedTable" id="demo">
  <header class="fixedTable-header">
    <table class="table table-bordered">
      <thead>
        <tr>
		 <th></th>
          <th>A</th>
          <th>B</th>
          <th>C</th>
          <th>D</th>
          <th>E</th>
          <th>F</th>
          <th>G</th>
          <th>H</th>
          <th>I</th>
          <th>J</th>
          <th>K</th>
          <th>L</th>
        </tr>
      </thead>
    </table>
  </header>
  <aside class="fixedTable-sidebar">
    <table class="table table-bordered">
      <tbody>
        <tr>
          <td>14567567465447567467</td>
        </tr>
        <tr>
          <td>2</td>
        </tr>
        <tr>
          <td>3</td>
        </tr>
        <tr>
          <td>4</td>
        </tr>
        <tr>
          <td>5</td>
        </tr>
        <tr>
          <td>6</td>
        </tr>
        <tr>
          <td>7</td>
        </tr>
        <tr>
          <td>8</td>
        </tr>
        <tr>
          <td>9</td>
        </tr>
        <tr>
          <td>10</td>
        </tr>
        <tr>
          <td>11</td>
        </tr>
        <tr>
          <td>12</td>
        </tr>
        <tr>
          <td>13</td>
        </tr>
        <tr>
          <td>14</td>
        </tr>
        <tr>
          <td>15</td>
        </tr>
        <tr>
          <td>16</td>
        </tr>
        <tr>
          <td>17</td>
        </tr>
       
        
      </tbody>
    </table>
  </aside>
  <div class="fixedTable-body">
    <table class="table table-bordered">
      <tbody>
        <tr>
          <td>a</td>
          <td>b</td>
          <td>c</td>
          <td>d</td>
          <td>e</td>
          <td>f</td>
          <td>g</td>
          <td>h</td>
          <td>i</td>
          <td>j</td>
          <td>k</td>
          <td>l</td>
        </tr>
        <tr>
          <td>a</td>
          <td>b</td>
          <td>c</td>
          <td>d</td>
          <td>e</td>
          <td>f</td>
          <td>g</td>
          <td>h</td>
          <td>i</td>
          <td>j</td>
          <td>k</td>
          <td>l</td>
        </tr>
        <tr>
          <td>a</td>
          <td>b</td>
          <td>c</td>
          <td>d</td>
          <td>e</td>
          <td>f</td>
          <td>g</td>
          <td>h</td>
          <td>i</td>
          <td>j</td>
          <td>k</td>
          <td>l</td>
        </tr>
        <tr>
          <td>a</td>
          <td>b</td>
          <td>c</td>
          <td>d</td>
          <td>e</td>
          <td>f</td>
          <td>g</td>
          <td>h</td>
          <td>i</td>
          <td>j</td>
          <td>k</td>
          <td>l</td>
        </tr>
        <tr>
          <td>a</td>
          <td>b</td>
          <td>c</td>
          <td>d</td>
          <td>e</td>
          <td>f</td>
          <td>g</td>
          <td>h</td>
          <td>i</td>
          <td>j</td>
          <td>k</td>
          <td>l</td>
        </tr>
        <tr>
          <td>a</td>
          <td>b</td>
          <td>c</td>
          <td>d</td>
          <td>e</td>
          <td>f</td>
          <td>g</td>
          <td>h</td>
          <td>i</td>
          <td>j</td>
          <td>k</td>
          <td>l</td>
        </tr>
        <tr>
          <td>a</td>
          <td>b</td>
          <td>c</td>
          <td>d</td>
          <td>e</td>
          <td>f</td>
          <td>g</td>
          <td>h</td>
          <td>i</td>
          <td>j</td>
          <td>k</td>
          <td>l</td>
        </tr>
        <tr>
          <td>a</td>
          <td>b</td>
          <td>c</td>
          <td>d</td>
          <td>e</td>
          <td>f</td>
          <td>g</td>
          <td>h</td>
          <td>i</td>
          <td>j</td>
          <td>k</td>
          <td>l</td>
        </tr>
        <tr>
          <td>a</td>
          <td>b</td>
          <td>c</td>
          <td>d</td>
          <td>e</td>
          <td>f</td>
          <td>g</td>
          <td>h</td>
          <td>i</td>
          <td>j</td>
          <td>k</td>
          <td>l</td>
        </tr>
        <tr>
          <td>a</td>
          <td>b</td>
          <td>c</td>
          <td>d</td>
          <td>e</td>
          <td>f</td>
          <td>g</td>
          <td>h</td>
          <td>i</td>
          <td>j</td>
          <td>k</td>
          <td>l</td>
        </tr>
        <tr>
          <td>a</td>
          <td>b</td>
          <td>c</td>
          <td>d</td>
          <td>e</td>
          <td>f</td>
          <td>g</td>
          <td>h</td>
          <td>i</td>
          <td>j</td>
          <td>k</td>
          <td>l</td>
        </tr>
        <tr>
          <td>a</td>
          <td>b</td>
          <td>c</td>
          <td>d</td>
          <td>e</td>
          <td>f</td>
          <td>g</td>
          <td>h</td>
          <td>i</td>
          <td>j</td>
          <td>k</td>
          <td>l</td>
        </tr>
        <tr>
          <td>a</td>
          <td>b</td>
          <td>c</td>
          <td>d</td>
          <td>e</td>
          <td>f</td>
          <td>g</td>
          <td>h</td>
          <td>i</td>
          <td>j</td>
          <td>k</td>
          <td>l</td>
        </tr>
        <tr>
          <td>a</td>
          <td>b</td>
          <td>c</td>
          <td>d</td>
          <td>e</td>
          <td>f</td>
          <td>g</td>
          <td>h</td>
          <td>i</td>
          <td>j</td>
          <td>k</td>
          <td>l</td>
        </tr>
        <tr>
          <td>a</td>
          <td>b</td>
          <td>c</td>
          <td>d</td>
          <td>e</td>
          <td>f</td>
          <td>g</td>
          <td>h</td>
          <td>i</td>
          <td>j</td>
          <td>k</td>
          <td>l</td>
        </tr>
        <tr>
          <td>a</td>
          <td>b</td>
          <td>c</td>
          <td>d</td>
          <td>e</td>
          <td>f</td>
          <td>g</td>
          <td>h</td>
          <td>i</td>
          <td>j</td>
          <td>k</td>
          <td>l</td>
        </tr>
        <tr>
          <td>a</td>
          <td>b</td>
          <td>c</td>
          <td>d</td>
          <td>e</td>
          <td>f</td>
          <td>g</td>
          <td>h</td>
          <td>i</td>
          <td>j</td>
          <td>k</td>
          <td>l</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
	</div>
	
  </div>
</div>

<!----------------modal popup end---------------->
<div class="modal fade" id="largequicker1" tabindex="-1" role="dialog" aria-labelledby="largeModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        <h1>Tender Document collection</h1>
      </div>
      <div class="modal-body modal_body_min_h200" style="padding:0; background:#F0F2F2">
        <form class="form-horizontal">
          <div class="col-lg-12">
            <div class="col-md-6"> <span class="hd-3" style="margin:5px 0"><b> <i class="fa fa-calendar-o"></i>&nbsp;Reference &nbsp;&nbsp;:</b> Date21-nov-2017</span>
            <div class="col-md-12" align="right" ><span class="hd-3" style="margin:5px 0"><b> &nbsp;Assign to Name1, Name2</b></span> </div> </div>
            <div class="col-md-6" style="margin-top:15px;">
              <select class="form-control single_dropdown lbl_move" style="width:100%;">
                <option></option>
                <option selected>Most Recent</option>
              </select>
            </div>
            <!--div class="col-md-6 form-group" align="right">
              <h2 class="comtex crmbrdrclrhed4" style="text-decoration: underline; font-weight:600">Ref.No : &nbsp;34687538</h2>
            </div-->
            <div class="col-md-12">
              <textarea style="height:100%" class="parent_texts"></textarea>
            </div>
            <div class="col-md-4">
              <ul class="action_btns">
                <li class="lft-doc atta-cls"> <a href="#"> <span data-toggle="tooltip" data-placement="right" data-original-title="Click to attach documents" class="butclr-ns btn-file">
                  <p class="sam-up"> <i class="fa fa-paperclip dcm_atch"></i></p>
                  <input name="Attached" type="file" />
                  </span>
                  <label style="color:#333; font-size:13px;">Attached File</label>
                  </a> </li>
              </ul>
            </div>
			<!---buttton-->
            <div class="col-lg-8 savebtn_area">
              <ul>
                <li class="float_r" style="margin:11px 15px;"> <a class="md_ok" href="#;" data-toggle="tooltip" title="" data-original-title="Submit!" style="float:left">Submit <span class="ripple-wrapper"></span></a> </li>
                <li class="can_btn float_r" style="padding-bottom:10px;"> <a style="padding:6px 15px !important;" href="#">Clear</a> </li>
              </ul>
            </div>
            <div class="col-md-12">
              <div class="table-responsive">
                <table class="table tab-attach" width="100%" data-toolbar="#transform-buttons">
                  <thead>
                    <tr>
                      <th width="10%">NO</th>
                      <th  width="35%">DCESCRIPTION</th>
                      <th  width="8%">UNIT</th>
                      <th  width="8%">QTY</th>
					  <th width="4%"></th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td><div align="center"> <img class="circle-task"src="<?php echo $this->basePath(); ?>/images/avatar.jpg" />
                          <p style="display:block; font-size:10px;"> Name 1</p>
                        </div></td>
                      <td><div class="task-cnt">Request decision Approval
                          <p>Request decisior</p>
                        </div></td>
                      <td style="color:#666">20-nav-2017</td>
                      <td><b style="font-weight:600; color:#C60">Progress</b></td>
					  <td width="1%" align="center"><ul class="action_btns">
                      <li><a href="#" data-toggle="tooltip" data-placement="top" data-original-title="Click to attach documents" > <span class="butclr btn-file"> <i class="fa fa-paperclip"></i>
                        <input type="file"/>
                        </span></a></li>
                    </ul></td>
                    </tr>
                    <tr>
                      <td><div align="center"> <img class="circle-task"src="<?php echo $this->basePath(); ?>/images/avatar.jpg" />
                          <p style="display:block; font-size:10px;"> Name 1</p>
                        </div></td>
                      <td><div class="task-cnt">Request decision Approval
                          <p>Request decisior</p>
                        </div></td>
                      <td style="color:#666">20-nav-2017</td>
                      <td><b style="font-weight:600; color:#C60">Progress</b></td>
					  <td width="1%" align="center"><ul class="action_btns">
                      <li><a href="#" data-toggle="tooltip" data-placement="top" data-original-title="Click to attach documents" > <span class="butclr btn-file"> <i class="fa fa-paperclip"></i>
                        <input type="file"/>
                        </span></a></li>
                    </ul></td>
                    </tr>
                    <tr>
                      <td><div align="center"> <img class="circle-task"src="<?php echo $this->basePath(); ?>/images/avatar.jpg" />
                          <p style="display:block; font-size:10px;"> Name 1</p>
                        </div></td>
                      <td><div class="task-cnt">Request decision Approval
                          <p>Request decisior</p>
                        </div></td>
                      <td style="color:#666">20-nav-2017</td>
                      <td><b style="font-weight:600; color:#C60">Progress</b></td>
					  <td width="1%" align="center"><ul class="action_btns">
                      <li><a href="#" data-toggle="tooltip" data-placement="top" data-original-title="Click to attach documents" > <span class="butclr btn-file"> <i class="fa fa-paperclip"></i>
                        <input type="file"/>
                        </span></a></li>
                    </ul></td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
            
          </div>
        </form>
        <div class="modal-footer clear"> 
        </div>
      </div>
    </div>
  </div>
</div>

<script>
 function toogleTooltip() {
    var $expandDivs = $('.expandDiv');
    if($expandDivs.length == 0)
        return;

    var $focused_el = $('textarea').filter(':focus');
    if ($focused_el.length == 0) {
        $expandDivs.removeClass('expandDiv').find('textarea').trigger('blur');
        return;
    }

    var $parent_focus = $focused_el.parents('.on-focus');
    if($parent_focus.length != 0) {
        $expandDivs.not($parent_focus).removeClass('expandDiv');
        $expandDivs.not($parent_focus).find('textarea').trigger('blur');
        return;
    }
}
	</script>
	<!---------------Jqxscheduler js--------------->
<script type="text/javascript">
    $(document).ready(function () {
        var appointments =  <?php echo (isset($enquiry_schedules)) ? json_encode($enquiry_schedules) : '[]'; ?>;
        var source = {
            dataType: "array",
            dataFields: [
                { name: 'id', type: 'string' },
                { name: 'description', type: 'string' },
                { name: 'location', type: 'string' },
                { name: 'subject', type: 'string' },
                { name: 'calendar', type: 'string' },
                { name: 'start', type: 'date' },
                { name: 'end', type: 'date' }
            ],
            id: 'id',
            localData: appointments
        };
        var adapter = new $.jqx.dataAdapter(source);
        $("#scheduler").jqxScheduler({
            date: new $.jqx.date(2016, 11, 23),
            width:'100%',
            height:445,
            source: adapter,
            view: 'monthView',
            showLegend: true,
            editDialog: false,
            contextMenu: false,
            theme: 'arctic',
            timeZone:'UTC',
            ready: function () {
                $("#scheduler").jqxScheduler('ensureAppointmentVisible', 'id1');
            },
            resources:
            {
                colorScheme: "scheme05",
                dataField: "calendar",
                source:  new $.jqx.dataAdapter(source)
            },
            appointmentDataFields:
            {
                from: "start",
                to: "end",
                id: "id",
                description: "description",
                location: "place",
                subject: "subject",
                resourceId: "calendar"
            },
            views:
                [
                    'dayView',
                    'weekView',
                    { type: 'monthView', showWeekNumbers: true }
                ]
        });
    });
</script>
<!---------------Jqxscheduler style end--------------->
<script>
(function() {
  var demo, fixedTable;

  fixedTable = function(el) {
    var $body, $header, $sidebar;
    $body = $(el).find('.fixedTable-body');
    $sidebar = $(el).find('.fixedTable-sidebar table');
    $header = $(el).find('.fixedTable-header table');
    return $($body).scroll(function() {
      $($sidebar).css('margin-top', -$($body).scrollTop());
      return $($header).css('margin-left', -$($body).scrollLeft());
    });
  };

  demo = new fixedTable($('#demo'));

}).call(this);
</script>
<script>
//delete to use default scroll
//js scroll library used: http://manos.malihu.gr/jquery-custom-content-scroller/
$(window).load(function(){

  $(".fixed_headers tbody").mCustomScrollbar({
    theme:"light-3",
    scrollButtons:{
      enable:false
    },
    mouseWheel:{ preventDefault: true },
    scrollbarPosition: 'inside',
    autoExpandScrollbar:true,
    theme: 'dark'
  });
});
</script>