<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/bootstrap-treefy.min.css"/>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/bootstrap-treefy.min.js"></script>
<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
        <div class="col-lg-12 clear padlr0">
            <div class="col-lg-12">
                <table class="table" id="table">
                    <thead>
                    <tr>	
	                    <th width="1%"></th>
                        <th>Column A</th>
                    </tr>
                    </thead>
                    <tbody>
                        <tr data-node="treetable-1">
                        	<td></td>
                            <td>Node1</td>
                        </tr>
                        <tr data-node="treetable-2" data-pnode="treetable-parent-1">
                        	<td></td>
                            <td>Node1.1</td>
                        </tr>
                        <tr data-node="treetable-3" data-pnode="treetable-parent-1">
                        	<td></td>
                            <td>Node1.2</td>
                        </tr>
                        <tr data-node="treetable-4" data-pnode="treetable-parent-3">
                            <td></td>
                            <td>Node1.2.1</td>
                        </tr>
                        <tr data-node="treetable-5">
                        	<td></td>
                            <td>Node2</td>
                        </tr>
                    </tbody>
                </table>
			</div>
		</div>
	</div>
</div>
<script>
$(function() {
	$("#table").treeFy({
		treeColumn: 1,
		collapseAnimateCallback: function(row) {
			row.fadeOut();
		},
		expandAnimateCallback: function(row) {
			row.fadeIn();
		}
	});
});
</script>