<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css';?>"/>
<style>
.jqx-grid-header {
	height: 80px !important;
}
.jqx-grid-column-header{
	border-bottom:1px solid red !important;
}
</style>
<script>
$(document).ready(function () {
//var url = "displayRegister";
var data = [
{ResourceType:"Activity",Code:"A00011", Type:"Earth Work ",Unit:"Cum",Qty:"5",Inc:"True" ,Rate:"213",Amount:"32100",CInc:"false" ,CRate:"655",CAmount:"659988"},
{ResourceType:"Material",Code:"A00022", Type:"Cement",Unit:"Sqm",Qty:"110",Inc:"false" ,Rate:"200",Amount:"4566",CInc:"false" ,CRate:"588",CAmount:"365855"},
{ResourceType:"Activity",Code:"A00050", Type:"Excavation",Unit:"Nos",Qty:"200",Inc:"false" ,Rate:"300",Amount:"7895",CInc:"false" ,CRate:"744",CAmount:"88554"},
{ResourceType:"Activity",Code:"A00221", Type:"Excavation",Unit:"Ls",Qty:"320",Inc:"false" ,Rate:"400",Amount:"3654",CInc:"false" ,CRate:"777",CAmount:"88599"},
{ResourceType:"Material",Code:"A00012", Type:"Cement",Unit:"Cum",Qty:"546",Inc:"false" ,Rate:"800",Amount:"69855",CInc:"false" ,CRate:"555",CAmount:"18855"},
{ResourceType:"Activity",Code:"A00061", Type:"Earth Work",Unit:"Ls",Qty:"333",Inc:"false" ,Rate:"450",Amount:"36544",CInc:"false" ,CRate:"365",CAmount:"78888"},
{ResourceType:"Activity",Code:"A00011", Type:"Excavation",Unit:"Nos",Qty:"789",Inc:"false" ,Rate:"300",Amount:"236548",CInc:"false" ,CRate:"230",CAmount:"10000"},
		]
// prepare the data
var source =
{	
	localdata:data,
	dataType: "json",
	dataFields: [
		{ name: 'ResourceType', type: 'string' },
		{ name: 'Code', type: 'string' },
		{ name: 'Type', type: 'string' },
		{ name: 'Unit', type: 'string' },
		{ name: 'Qty', type: 'string' },
		{ name: 'Inc', type: 'boolean' },
		{ name: 'Rate', type: 'string' },
		{ name: 'Amount', type: 'string' },
		{ name: 'CInc', type: 'boolean' },
		{ name: 'CRate', type: 'string' },
		{ name: 'CAmount', type: 'string' },
		{ name: 'ResourceName', type: 'string' },
		
	],
	id: 'RequestId',
};

var dataAdapter = new $.jqx.dataAdapter(source);

$("#dataTable").jqxGrid(
{
	width: '100%',
	pageable: true,
	rowsheight: 35,
	selectionMode: 'singleRow',	
	pagerButtonsCount: 6,
	autoheight:true,
	source: dataAdapter,
    altrows: true,
	editable:true,
	
	columnsResize: true,
	columns: [
	  { text: 'ResourceType', dataField: 'ResourceType',width:'12%',editable:false,},
	  { text: 'Code', dataField: 'Code',editable:false,},
	  { text: 'Type', dataField: 'Type',width:'12%',editable:false,},
	  { text: 'Unit', dataField: 'Unit',editable:false,},
	  { text: 'Qty', dataField: 'Qty',editable:false,},
	   { text: 'Inc', dataField: 'Inc', columngroup: 'Current',columntype: 'checkbox',align:'center',},
	    { text: 'Rate', dataField: 'Rate', columngroup: 'Current',editable:false,},
		{ text: 'Amount', dataField: 'Amount', columngroup: 'Current',editable:false,},
		{ text: 'Inc', dataField: 'CInc', columngroup: 'Revised',columntype: 'checkbox',align:'center',},
	    { text: 'Rate', dataField: 'CRate', columngroup: 'Revised',editable:false,},
		{ text: 'Amount', dataField: 'CAmount', columngroup: 'Revised',editable:false,},
		
		
	 
  ],
  columngroups: 
                [
                  { text: 'Revised', align: 'center', name: 'Revised' },
				  { text: 'Current', align: 'center', name: 'Current' }
                ]
});
$("#dataTable").bind('rowselect', function (event) {
	
	
});

});
</script>
<div class="content_wrapper padlr0">
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-12">
      <h1>Request for creation - Resource Rate</h1>
    </div>
    
    <!--table start-->
    <div class="col-lg-12 col-lg-offset-0"> 
      <!--table Jq Gride start-->
      <div id="dataTable"></div>
      <!--table Jq Gride end-->
      <div class="clearfix"></div>
      <div class="col-lg-12">
        <div class="table-responsive topsp">
          <table class="table tableWithFloatingHeader" style=" margin-bottom:0px;">
            <thead>
              <tr>
                <th>Resource Name</th>
                <th>Revision 1</th>
                <th>Revision 2</th>
                <th>Revision 3</th>
                <th>Revision 4</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td width="15%"><input class="parent_text" type="text" /></td>
                <td width="10%" ><input class="parent_text" type="text"/></td>
                <td width="10%"><input class="parent_text" type="text" /></td>
                <td width="10%"><input class="parent_text" type="text" /></td>
                <td width="10%"><input class="parent_text" type="text" /></td>
              </tr>
              <!--expand end-->
            </tbody>
          </table>
        </div>
      </div>
      <!--table end--> 
    </div>
  </div>
</div>

<div class="col-lg-12 savebtn_area">
  <ul>
    <li class="dropdown save_btn float_r"><a href="javascript:void(0);" data-toggle="tooltip" class="ripple" title="Go to continue !">Continue</a></li>
    <li class="cancel_btn float_r"><a href="javascript:void(0);" data-toggle="tooltip" class="ripple" title="Go back!">Back</a></li>
    </ul>
</div>
