<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath(); ?>/library/handsontable/css/handsontable.full.min.css">
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/handsontable/js/handsontable.full.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/handsontable/js/RuleJS/lodash.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/handsontable/js/RuleJS/underscore.string.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/handsontable/js/RuleJS/numeral.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/handsontable/js/RuleJS/numeric.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/handsontable/js/formula.js"></script>
<script type="text/javascript"src="<?php echo $this->basePath(); ?>/library/handsontable/js/parser.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/handsontable/js/ruleJS.all.full.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/handsontable/js/handsontable.formula.js"></script>
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css'; ?>" />
<style>
.jqxgrid{background:#fff;border:1px solid #f1f1f1;box-shadow:0 1px 0 rgba(0, 0, 0, 0.12), 0 1px 1px rgba(0, 0, 0, 0.24);padding:20px 6px;width:100% !important; height:490px !important; overflow-y:scroll}
.jqx-draggable{ border-bottom:1px solid #ddd; width:97%;margin-bottom:4px; padding:8px 0 8px 8px;background:#f1f1f1}
#paneljqxTree{width:100% !important}
.jqx-fill-state-pressed,.jqx-item:hover,.jqx-draggable:hover{background:#3399ff !important;color:#fff !important}
.jqx-tree-item-li{display:block; width:100%}
.ctls {font-size:18px !important}
.list .tile .checkbox-styled:not(ie8) input ~ span, .list .tile .radio-styled:not(ie8) input ~ span{padding-left:35px}
.list .tile{ border-bottom: 1px solid #c2d8e6 !important;border-radius: 4px;}
.vendor_checkboxborder_gray{border:none !important; border-radius:none;}
.list .tile .checkbox-styled:not(ie8) input ~ span, .list .tile .radio-styled:not(ie8) input ~ span{text-overflow:ellipsis;overflow:hidden;display:inline-block;white-space:nowrap;}
.tr-header input[type=text] {font-weight:600 !important; font-size:15px !important; border:none !important; color: #015de6;}
.innermdl_tabs{ border-bottom: 2px solid #2d74b4 !important;}
.innermdl_tabs > li > a:hover, .innermdl_tabs > li.active > a, .innermdl_tabs > li.active > a:focus, .innermdl_tabs > li.active > a:hover{background:#F7E8C6 !important;border-bottom:2px solid #6B3D0C !important; color:#6B3D0C}
.nav-tabs > li > a{background:#E8F1FA;border-bottom:2px solid #0B4480 !important; color:#0B4480}
 .innermdl_tabs > li.active::after{content: ""; display: block; width: 0; height: 0; border-bottom: 8px solid #6B3D0C;  border-right: 8px solid transparent; border-left: 8px solid transparent; position: absolute; bottom:0px; right:38%;z-index:1; background:none}
.btn_newlist {background: #e3edf1 none repeat scroll 0 0;  border: 2px solid #93cee5; border-radius: 50%;color: #000;font-size: 11px;line-height: 36px;margin-bottom: 15px;padding: 0 4px;text-align: center;}
.btn_newlist a i{ text-align:center; font-size:20px; color:#000; padding-left:16px; line-height:45px; transition:all 0.3s ease;}
.btn_newlist a i:hover{-webkit-transform: scale(1.3);-ms-transform: scale(1.3);transform: scale(1.3); padding-left:14px}
.heading_checkbox                       {line-height:40px;}
.search-container label {right: 10px;position: absolute;top: 30px;z-index:999;color:#ccc;}
.sr-only {border: 0 none;clip: rect(0px, 0px, 0px, 0px);height: 1px;margin: -1px;overflow: hidden;padding: 0;position: absolute;width: 1px;}
.search-container {font-size: 18px;margin: -20px auto 0;padding-top: 20px;position: relative;}
.card {margin: 15px 0;padding: 11px;}
.card-body {padding: 0}
/*checklist css*/
.card:hover .work-frq{visibility: visible;display:block;transform:translateX(0%);transition-delay:0s;}
.work-frq{padding:10px 0 !important;display:none;transform: translateZ(0);transform: translateY(10%);transition: all 0.5s ease 0s, visibility 0s linear 0.5s;}
.work-frq label{padding:1px 0; border-bottom:2px solid #C5D3E8; margin-bottom:6px; text-align:center}
.work-frq checkbox{margin-top:10px;}
.work-frq >.critical >.checkbox label{border-bottom:none; padding:18px;}
.work-frq >.critical >.checkbox{margin-bottom:0}
.critical{background:#e7e9ec;padding:0 0 2px 0 !important; box-shadow:0 1px 0 rgba(0, 0, 0, 0.12), 0 1px 1px rgba(0, 0, 0, 0.24);}
.work-frq .lbl_move,.work-frq .select2-container .select2-selection--single{height:30px !important; min-height:30px !important;max-height:30px !important;font-size:13px;}
.work-frq .select2-container .select2-selection--single .select2-selection__rendered{padding-top:0}
.work-frq .select2-container--default .select2-selection--single .select2-selection__arrow{top:1px}
</style>
<div class="content_wrapper padlr0">
  <div class="container-fluid">
    <h1 class="col-md-12 text-left animated growIn">Project Work Breakdown Structure</h1>
    
    <!--jqxGrid Wrapper--> 
    <!--jqxGrid Wrapper-->
    <div class="col-lg-12 form-group">
      <div class="col-lg-3 col-md-4" >
        <div class="jqxgrid" id='jqxTree'></div>
      </div>
      
      <!--WBS IOW Wrapper-->
      <div class="col-lg-9 col-md-8">
        <div class="table-responsive col-md-12">
          <table class="table" width="100%">
            <thead>
              <tr>
                <th width="15%">SerialNo</th>
                <th width="25%">Description</th>
                <th width="8%">Unit</th>
                <th width="8%">Qty</th>
                <th width="18%">Rate</th>
                <th width="22%">Amount</th>
                <th width="5%"> </th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td width="15%"><input class="parent_text" value="1.1.1" readonly="" type="text"></td>
                <td width="25%"><textarea class="parent_texts" readonly=""></textarea></td>
                <td width="8%"><input class="parent_text" value="Cum" readonly="" type="text"></td>
                <td width="8%"><input class="parent_text" value="100.0" readonly="" type="text"></td>
                <td width="18%"><input class="parent_text" value="5.000" readonly="" type="text"></td>
                <td width="22%"><input class="parent_text" value="500.000" readonly="" type="text"></td>
                <td class="action_btns_td" width="5%"><a href="#" class="mainTr"> <i class="fa fa-chevron-circle-down ctls" data-toggle="tooltip" data-placement="left" data-original-title="Expand" ></i></a>
                  </li>
                  </ul></td>
              </tr>
              <tr style="display:none;" class="subTr">
                <td colspan="12"><div class="subDiv animated-panel zoomIn"  style="animation-delay: 0.2s;">
                    <div class="col-lg-12 clear"> comming soon............. </div>
                  </div></td>
              </tr>
              <tr>
                <td width="15%"><input class="parent_text" value="1.1.1" readonly="" type="text"></td>
                <td width="25%"><textarea class="parent_texts" readonly=""></textarea></td>
                <td width="8%"><input class="parent_text" value="Cum" readonly="" type="text"></td>
                <td width="8%"><input class="parent_text" value="100.0" readonly="" type="text"></td>
                <td width="18%"><input class="parent_text" value="5.000" readonly="" type="text"></td>
                <td width="22%"><input class="parent_text" value="500.000" readonly="" type="text"></td>
                <td class="action_btns_td" width="5%"><a href="#" class="mainTr"> <i class="fa fa-chevron-circle-down ctls" data-toggle="tooltip" data-placement="left" data-original-title="Expand" ></i></a>
                  </li>
                  </ul></td>
              </tr>
               <!--sub detail-->
              <tr style="display:none;" class="subTr">
                <td colspan="12"><div class="subDiv animated-panel zoomIn"  style="animation-delay: 0.2s;">
                    <div class="col-lg-12 padlr0">
                      <nav class="navbar inrmdltab_navbar navbar-default">
                        <div class="navbar-header">
                          <button type="button" class="navbar-toggle mdlnvbr_tgl collapsed ripple" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
                          <a class="navbar-brand inrmdl_navbrand ripple" href="javascript:void(0);">Select Menus</a> </div>
                        <div id="navbar" class="navbar-collapse padlr0 collapse">
                          <ul class="nav nav-tabs innermdl_tabs">
                            <li class="active"><a href="#worktab__1" data-toggle="tab" class="ripple">Works</a></li>
                            <li><a href="#safetytab__1" data-toggle="tab" class="ripple">Safety</a></li>
                            <li><a href="#qualitytab__1" data-toggle="tab" class="ripple">Quality</a></li>
                          </ul>
                        </div>
                      </nav>
                       <!--tab body-->
                      <div class="tab-content"> 
                        <div class="tab-pane fade in active" id="worktab__1">
                          <div class="deft_act col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0">
                           <!--prework-->  <div class="col-lg-12 col-md-12">
                              <div class="headingWrapper">
                             <p class="heading_checkbox">Pre-Work CheckList</p>
                                <section class="search-container">
                                  <label> <i class="fa fa-search" aria-hidden="true"></i> <span class="sr-only">Search icons</span> </label>
                                  <input class="form-control lbl_move height25" type="text" placeholder="Search... "  onkeyup="chkSearch(this)">
                                </section>
                              </div>
                              <div class="card workChecklistWrapper">
                                <div class="card-body" style="min-height:50px; max-height:310px;">
                                  <ul class="sampleUI list workChecklists" id="workchecklist_1">
                                    <li class="tile search-item">
                                      <div class="col-md-7" style="padding:0 !important">
                                        <div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">
                                          <label>
                                            <input class="search-element" id="wtype_1_chkList_1" value="5109" data-name="Work1" onclick="selectList(this, &quot;chk-work&quot;);" type="checkbox">
                                            <span>Work1</span> </label>
                                        </div>
                                      </div>
                                      <div class="col-md-5">
                                        <select class="form-control single_dropdown lbl_move " style="width:100%;">
                                          <option></option>
                                          <option selected>After</option>
										  <option>Before</option>
										  <option>During</option>
                                        </select>
                                      </div>
                                    </li>
                                   
                                  </ul>
								  
                                </div>
  
								<!----checklist--->
								<div class="work-frq col-md-12">
								       <div class="col-md-2 critical">
                                        <div class="checkbox checkbox-styled">
                                          <label>
                                            <input class="search-element"  value="5109" data-name="Work1" type="checkbox">
                                            <span>Critical</span> </label>
                                        </div>
								      </div>
								       <div class="col-md-6" style="padding-right:0 !important">
								        <div class="col-md-12 critical">
								          <label class="col-md-12">When</label>
								            <div class="col-md-5" style="padding-right:0 !important">
                                             <select class="form-control single_dropdown lbl_move " style="width:100%;">
                                              <option></option>
                                             <option selected>After</option>
										     <option>Before</option>
										     <option>During</option>
                                            </select>
                                         </div>
									    <div class="col-md-3" style="padding-right:0 !important">
									      <input type="text" class="form-control lbl_move"  />
									    </div>
									     <div class="col-md-4">
                                           <select class="form-control single_dropdown lbl_move " style="width:100%;">
                                           <option></option>
                                           <option selected>Day</option>
										   <option>Hours</option>
                                        </select>
                                     </div>
								  </div>
								 </div>
								<div class="col-md-4" style="padding-right:0 !important">
								 <div class="col-md-12 critical">
								    <label class="col-md-12">Frequency</label>
								     <div class="col-md-4" style="padding-right:0 !important">
									  <input type="text" class="form-control lbl_move"  />
								    </div>
								    <div class="col-md-8">
                                     <select class="form-control single_dropdown lbl_move " style="width:100%;">
                                      <option></option>
                                      <option selected>Day</option>
								      <option>Hours</option>
                                     </select>
                                    </div>
								  </div>
								</div>
							</div><!----checklist--->
								
								
                             </div>
                           </div>
                             <!--postwork-->
                            <div class="col-lg-12 col-md-12">
                              <div class="headingWrapper">
                              <p class="heading_checkbox">Post-Work CheckList</p>
                                <section class="search-container">
                                  <label> <i class="fa fa-search" aria-hidden="true"></i> <span class="sr-only">Search icons</span> </label>
                                  <input class="form-control lbl_move height25" type="text" placeholder="Search... "  onkeyup="chkSearch(this)">
                                </section>
                              </div>
                              <div class="card workChecklistWrapper">
                                <div class="card-body" style="min-height:50px; max-height:310px;">
                                  <ul class="sampleUI list workChecklists" id="workchecklist_1">
                                    <li class="tile search-item">
                                      <div class="col-md-7" style="padding:0 !important">
                                        <div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">
                                          <label>
                                            <input class="search-element" id="wtype_1_chkList_1" value="5109" data-name="Work1" onclick="selectList(this, &quot;chk-work&quot;);" type="checkbox">
                                            <span>Work1</span> </label>
                                        </div>
                                      </div>
                                      <div class="col-md-5">
                                        <select class="form-control single_dropdown lbl_move " style="width:100%;">
                                          <option></option>
                                          <option selected>Most Recent</option>
                                        </select>
                                      </div>
                                    </li>
                                  </ul>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                         <!--2tab-->
                        <div class="tab-pane fade" id="safetytab__1">
                          <div class="deft_act col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0">
                            <div class="col-lg-12 col-md-12">
                              <div class="headingWrapper">
                               <!--2tab prework-->
                             <p class="heading_checkbox">Pre-Work CheckList</p>
                                <section class="search-container">
                                  <label> <i class="fa fa-search" aria-hidden="true"></i> <span class="sr-only">Search icons</span> </label>
                                  <input class="form-control lbl_move height25" type="text" placeholder="Search... "  onkeyup="chkSearch(this)">
                                </section>
                              </div>
                              <div class="card workChecklistWrapper">
                                <div class="card-body" style="min-height:50px; max-height:310px;">
                                  <ul class="sampleUI list workChecklists" id="workchecklist_1">
                                    <li class="tile search-item">
                                      <div class="col-md-7" style="padding:0 !important">
                                        <div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">
                                          <label>
                                            <input class="search-element" id="wtype_1_chkList_1" value="5109" data-name="Work1" onclick="selectList(this, &quot;chk-work&quot;);" type="checkbox">
                                            <span>Work1</span> </label>
                                        </div>
                                      </div>
                                      <div class="col-md-5">
                                        <select class="form-control single_dropdown lbl_move " style="width:100%;">
                                          <option></option>
                                          <option selected>Most Recent</option>
                                        </select>
                                      </div>
                                    </li>
                                    <li class="tile search-item">
                                      <div class="col-md-7" style="padding:0 !important">
                                        <div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">
                                          <label>
                                            <input class="search-element" id="wtype_1_chkList_1" value="5109" data-name="Work1" onclick="selectList(this, &quot;chk-work&quot;);" type="checkbox">
                                            <span>Work1</span> </label>
                                        </div>
                                      </div>
                                      <div class="col-md-5">
                                        <select class="form-control single_dropdown lbl_move " style="width:100%;">
                                          <option></option>
                                          <option selected>Most Recent</option>
                                        </select>
                                      </div>
                                    </li>
                                  </ul>
                                </div>
                              </div>
                            </div>
                            
                          </div>
                        </div>
                         <!--3tab-->
                        <div class="tab-pane fade" id="qualitytab__1">
                          <div class="deft_act col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0">
                           <div class="col-lg-12 col-md-12">
                              <div class="headingWrapper">
                               <!--3tab prework-->
                             <p class="heading_checkbox">Pre-Work CheckList</p>
                                <section class="search-container">
                                  <label> <i class="fa fa-search" aria-hidden="true"></i> <span class="sr-only">Search icons</span> </label>
                                  <input class="form-control lbl_move height25" type="text" placeholder="Search... "  onkeyup="chkSearch(this)">
                                </section>
                              </div>
                              <div class="card workChecklistWrapper">
                                <div class="card-body" style="min-height:50px; max-height:310px;">
                                  <ul class="sampleUI list workChecklists" id="workchecklist_1">
                                    <li class="tile search-item">
                                      <div class="col-md-7" style="padding:0 !important">
                                        <div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">
                                          <label>
                                            <input class="search-element" id="wtype_1_chkList_1" value="5109" data-name="Work1" onclick="selectList(this, &quot;chk-work&quot;);" type="checkbox">
                                            <span>Work1</span> </label>
                                        </div>
                                      </div>
                                      <div class="col-md-5">
                                        <select class="form-control single_dropdown lbl_move " style="width:100%;">
                                          <option></option>
                                          <option selected>Most Recent</option>
                                        </select>
                                      </div>
                                    </li>
                                    <li class="tile search-item">
                                      <div class="col-md-7" style="padding:0 !important">
                                        <div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">
                                          <label>
                                            <input class="search-element" id="wtype_1_chkList_1" value="5109" data-name="Work1" onclick="selectList(this, &quot;chk-work&quot;);" type="checkbox">
                                            <span>Work1</span> </label>
                                        </div>
                                      </div>
                                      <div class="col-md-5">
                                        <select class="form-control single_dropdown lbl_move " style="width:100%;">
                                          <option></option>
                                          <option selected>Most Recent</option>
                                        </select>
                                      </div>
                                    </li>
                                  </ul>
                                </div>
                              </div>
                            </div> 
                            
                          </div>
                        </div>
                      </div>
                    </div>
                  </div></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>
<div class="clearfix"></div>
<script type="text/javascript">
        $(document).ready(function () {
            var source = [
                { label: "Item 1", expanded: true, items: [
                    { label: "Item 1.1" },
                    { label: "Item 1.2", selected: true }
                ]
                },
                { label: "Item 2" },
                { label: "Item 3" },
                { label: "Item 4", items: [
                    { label: "Item 4.1" },
                    { label: "Item 4.2" }
                ]
                },
                { label: "Item 5" },
                { label: "Item 6" },
                { label: "Item 7" }
            ];
            // Create jqxTree.
            $('#jqxTree').jqxTree({ source: source, height: '300px', width: '300px' });
        });
    </script> 
<script>
$(".mainTr").click(function(e){
	e.preventDefault();
	if(!$(this).closest("tr").next(".subTr").is(":visible")){
		$(this).closest("tr").next(".subTr").show();
		$(this).closest("tr").next(".subTr").find(".subDiv").slideDown("slow");	
		$(this).find("i").addClass("tform");
	}
		else{
		$(this).closest("tr").next(".subTr").find(".subDiv").slideUp("slow");
		$(this).closest("tr").next(".subTr").slideUp("slow");
		$(this).find("i").removeClass("tform");
	}
})
</script> 
