<!---------style------------>
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css';?>"/>
<!---------style------------>
<div class="content_wrapper padlr0">
  <div class="container-fluid">
    <div class="col-lg-12 page_tittle">
      <h1>Request for Creation</h1>
    </div>
    <div class="col-lg-12 clear">
      <div class="row">
        <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">
          <div class="col-lg-12">
            <div class="row">
              <div class="step_by_liner animated slideInDown"></div>
              <ul class="step_by stepby_mb60">
                <li>
                  <div class="step_by_sep stepsep_active animated_0_4s slideInRight" id="tag-step-1">
                    <p>1</p>
                  </div>
                  <p class="stepli_p1">Library</p>
                </li>
                <li>
                  <div class="step_by_sep animated slideInRight" id="tag-step-2">
                    <p>2</p>
                  </div>
                  <p class="stepli_p2">Type</p>
                </li>
                <li class="opacity_08">
                  <div class="step_by_sep animated_1_5s slideInRight" id="tag-step-3">
                    <p>3</p>
                  </div>
                  <p class="stepli_p3">Action</p>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 cnt_slider">
          <div id="carousel-example-generic" class="carousel slide" data-ride="carousel"> 
            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox"> 
              <!--form 1st-->
              <div class="item active">
                <div class="rfc_reg col-lg-7 col-lg-offset-3 col-md-10 col-md-offset-2 col-sm-10 col-sm-offset-1">
                  <ul class="ca-menu">
                    <li data-target="#carousel-example-generic" data-slide-to="1" class="first-step"> <a href="#"> <span class="ca-icon rdo_box_icon brad_50"><i class="fa fa-book"></i></span>
                      <div class="ca-content">
                        <h2 class="ca-main">Library</h2>
                        <div class="rdo_box_link brad_50"><span><i class="fa fa-external-link"></i></span></div>
                      </div>
                      </a> </li>
                    <li data-target="#carousel-example-generic" data-slide-to="7" class="first-step"> <a href="#"> <span class="ca-icon rdo_box_icon brad_50"><i class="fa fa-building-o"></i></span>
                      <div class="ca-content">
                        <h2 class="ca-main">Project</h2>
                        <div class="rdo_box_link brad_50"><span><i class="fa fa-external-link"></i></span></div>
                      </div>
                      </a> </li>
                    <!-- <li data-target="#carousel-example-generic" data-slide-to="1"> <a href="#"> <span class="ca-icon rdo_box_icon brad_50"><i class="fa fa-list-alt"></i></span>
                         <div class="ca-content">
                           <h2 class="ca-main">RFC Register</h2>
                           <div class="rdo_box_link brad_50"><span><i class="fa fa-external-link"></i></span></div>
                         </div>
                         </a> </li>-->
                  </ul>
                </div>
              </div>
              <!--form 1st end--> 
              <!--form 2st-->
              <div class="item second-step-item">
                <div class="bck_but"><a href="#carousel-example-generic" data-toggle="tooltip" title="Back" data-placement="right" data-target="#carousel-example-generic" data-slide-to="0" id="back"><i class="fa fa-arrow-left bck"></i></a></div>
                <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                  <form class="form-horizontal">
                    <div class="row">
                      <div class="rfc_regs">
                        <ul>
                          <li cid="2" class="active"><i class="fa fa-user rgpa"></i><a>Resource</a></li>
                          <li cid="3"><i class="fa fa-users rgpa"></i><a>Resource Group</a></li>
                          <li cid="4"><i class="fa fa-briefcase rgpa"></i><a>Work Type</a></li>
                          <li cid="5"><i class="fa fa-cogs rgpa"></i><a>Work Group</a></li>
                          <li cid="6"><i class="fa fa-wrench rgpa"></i><a>Item of Work</a></li>
                        </ul>
                      </div>
                      
                      <!--button-->
                      <div class="savebtn_areas col-lg-7 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-9 col-sm-offset-3">
                        <ul>
                          <li><a href="#carousel-example-generic" data-target="#carousel-example-generic" data-slide-to="0" id="back">Back </a></li>
                          <li class="subs"><a href="#carousel-example-generic" data-target="#carousel-example-generic" data-slide-to="2" id="continue">Continue</a></li>
                        </ul>
                      </div>
                      <!--button--> 
                    </div>
                  </form>
                </div>
              </div>
              <!--form 2st end--> 
              <!--form 3st-->
              <div class="item">
                <div class="bck_but"> <a href="#carousel-example-generic" data-toggle="tooltip" title="Back" data-placement="right" data-target="#carousel-example-generic" data-slide-to="1" id="back"><i class="fa fa-arrow-left bck"></i></a> </div>
                <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                  <form class="form-horizontal">
                    <div class="row">
                      <div class="rfc_regs">
                        <ul>
                          <li><i class="fa fa-user-plus rgpa"></i><a url="<?php echo $this->basePath() . '/project/rfc/rfcresource';?>">Create New Resources</a></li>
                          <li><i class="fa fa-pencil-square-o rgpa"></i><a url="<?php echo $this->basePath() . '/project/rfc/rfcresource/0/edit/0';?>">Modify Existing Resources</a></li>
                          <li><i class="fa fa-trash-o rgpa"></i><a url="<?php echo $this->basePath() . '/project/rfc/rfcresourcedelete';?>">Delete Existing Resources</a></li>
                        </ul>
                      </div>
                      <!--button-->
                      <div class="savebtn_areas col-lg-7 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-9 col-sm-offset-3">
                        <ul>
                          <li><a href="#carousel-example-generic" data-target="#carousel-example-generic" data-slide-to="1" id="back">Back </a></li>
                          <li class="subs"><a href="#carousel-example-generic" id="continue">Continue</a></li>
                        </ul>
                      </div>
                      <!--button--> 
                    </div>
                  </form>
                </div>
              </div>
              
              <!--form Resource Group-->
              <div class="item">
                <div class="bck_but"> <a href="#carousel-example-generic" data-toggle="tooltip" title="Back" data-placement="right" data-target="#carousel-example-generic" data-slide-to="1" id="back"><i class="fa fa-arrow-left bck"></i></a> </div>
                <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                  <form class="form-horizontal">
                    <div class="row">
                      <div class="rfc_regs">
                        <ul>
                          <li><i class="fa fa-user-plus rgpa"></i><a url="<?php echo $this->basePath() . '/project/rfc/rfcresourcegroup';?>"> Create New Resource Groups</a></li>
                          <li><i class="fa fa-pencil-square-o rgpa"></i><a url="<?php echo $this->basePath() . '/project/rfc/rfcresourcegroup/0/edit/0';?>">Modify Existing Resource Groups</a></li>
                          <li><i class="fa fa-trash-o rgpa"></i><a url="<?php echo $this->basePath() . '/project/rfc/rfcresgroupdelete';?>">Delete Existing Resource Groups</a></li>
                        </ul>
                      </div>
                      <!--button-->
                      <div class="savebtn_areas col-lg-7 col-lg-offset-3">
                        <ul>
                          <li><a href="#carousel-example-generic" data-target="#carousel-example-generic" data-slide-to="1" id="back">Back </a></li>
                          <li class="subs"><a href="#carousel-example-generic" id="continue">Continue</a></li>
                        </ul>
                      </div>
                      <!--button--> 
                    </div>
                  </form>
                </div>
              </div>
              <!--form Resource Group end--> 
              <!--form Work Type-->
              <div class="item">
                <div class="bck_but"> <a href="#carousel-example-generic" data-toggle="tooltip" title="Back" data-placement="right" data-target="#carousel-example-generic" data-slide-to="1" id="back"><i class="fa fa-arrow-left bck"></i></a> </div>
                <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                  <form class="form-horizontal">
                    <div class="row">
                      <div class="rfc_regs">
                        <ul>
                          <li><i class="fa fa-pencil-square-o rgpa"></i><a url="<?php echo $this->basePath() . '/project/rfc/rfcworktype';?>">Modify Existing Work Type</a></li>
                        </ul>
                      </div>
                      <!--button-->
                      <div class="savebtn_areas col-lg-7 col-lg-offset-3">
                        <ul>
                          <li><a href="#carousel-example-generic" data-target="#carousel-example-generic" data-slide-to="1" id="back">Back</a></li>
                          <li class="subs"><a href="#carousel-example-generic" id="continue">Continue</a></li>
                        </ul>
                      </div>
                      <!--button--> 
                    </div>
                  </form>
                </div>
              </div>
              <!--form Work Type end--> 
              
              <!--form WorkGroup -->
              <div class="item">
                   <div class="bck_but"> 
                   <a href="#carousel-example-generic" data-toggle="tooltip" title="Back" data-placement="right" data-target="#carousel-example-generic" data-slide-to="1" id="back"><i class="fa fa-arrow-left bck"></i></a>
                  
                    </div>
                <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                  <form class="form-horizontal">
                    <div class="row">
                      <div class="rfc_regs">
                        <ul>
                          <li><i class="fa fa-user-plus rgpa"></i><a url="<?php echo $this->basePath() . '/project/rfc/rfcworkgroup';?>">Create New Work Groups</a></li>
                          <li><i class="fa fa-pencil-square-o rgpa"></i><a url="<?php echo $this->basePath() . '/project/rfc/rfcworkgroup/0/edit/0';?>">Modify Modify Existing Work Groups</a></li>
                          <li><i class="fa fa-trash-o rgpa"></i><a url="<?php echo $this->basePath() . '/project/rfc/rfcworkgroupdelete';?>">Delete Existing Work Groups</a></li>
                        </ul>
                      </div>
                      <!--button-->
                      <div class="savebtn_areas col-lg-7 col-lg-offset-3">
                        <ul>
                          <li><a href="#carousel-example-generic" data-target="#carousel-example-generic" data-slide-to="1" id="back">Back</a></li>
                          <li class="subs"><a href="#carousel-example-generic" id="continue">Continue</a></li>
                        </ul>
                      </div>
                      <!--button--> 
                    </div>
                  </form>
                </div>
              </div>
              
              <!--form WorkGroup end--> 
              
              <!--form Item of Works -->
              <div class="item">
                  <div class="bck_but"> 
                  <a href="#carousel-example-generic" data-toggle="tooltip" title="Back" data-placement="right"  data-target="#carousel-example-generic" data-slide-to="1" id="back"><i class="fa fa-arrow-left bck"></i> </a>
                  
                  
                    </div>
                <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                  <form class="form-horizontal">
                    <div class="row">
                      <div class="rfc_regs">
                        <ul>
                          <li><i class="fa fa-user-plus rgpa"></i><a href="<?php echo $this->basePath() . '/project/rfc/rfciow';?>"> Create New Item of Works</a></li>
                          <li><i class="fa fa-pencil-square-o rgpa"></i><a href="<?php echo $this->basePath() . '/project/rfc/rfciow/0/edit/0';?>"> Modify Existing Item of Works</a></li>
                          <li><i class="fa fa-trash-o rgpa"></i><a href="<?php echo $this->basePath() . '/project/rfc/rfciowdelete';?>">Delete Existing Item of Works</a></li>
                        </ul>
                      </div>
                      <!--button-->
                      <div class="savebtn_areas col-lg-7 col-lg-offset-3">
                        <ul>
                          <li><a href="#carousel-example-generic" data-target="#carousel-example-generic" data-slide-to="1" id="back">Back </a></li>
                          <li class="subs"><a href="#carousel-example-generic"  id="continue">Continue</a></li>
                        </ul>
                      </div>
                      <!--button--> 
                    </div>
                  </form>
                </div>
              </div>
              
              <!--form WorkGroup end--> 
              <!--project 1st step-->
              <div class="item second-step-item" id="projects_list">
                <div class="bck_but"><a href="#carousel-example-generic" data-toggle="tooltip" title="Back" data-placement="right" data-target="#carousel-example-generic" data-slide-to="0" id="back"><i class="fa fa-arrow-left bck"></i></a></div>
                <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                  <form class="form-horizontal">
                    <div class="row">
                      <div class="rfc_regs">
                      <h2>On Which Type do you want to Update ?</h2>
                        <ul>
                          <li cid="7" class="active"><i class="fa fa-user rgpa"></i><a>Bill of Quantity</a></li>
                          <li cid="8"><i class="fa fa-usd rgpa"></i><a>Other Cost</a></li>
                          <li cid="9"><i class="fa  fa-star rgpa"></i><a>Resource Rate</a></li>
                          <li cid="10"><i class="fa fa-building rgpa"></i><a>Work Breakdown Structure</a></li>
                          <li cid="11"><i class="fa fa-calendar rgpa"></i><a>Schedule</a></li>
                          <li cid="12"><i class="fa fa-picture-o rgpa"></i><a>Photo Progress</a></li>
                        </ul>
                      </div>
                      
                      <!--button-->
                      <div class="savebtn_areas col-lg-7 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-9 col-sm-offset-3">
                        <ul>
                          <li><a href="#carousel-example-generic" data-target="#carousel-example-generic" data-slide-to="0" id="back">Back </a></li>
                          <li class="subs"><a href="#carousel-example-generic" data-target="#carousel-example-generic" data-slide-to="7" id="continue">Continue</a></li>
                        </ul>
                      </div>
                      <!--button--> 
                    </div>
                  </form>
                </div>
              </div>
                 <!--project 1st step-->
                 
                 <!--Bill of Quantity-->
                      <div class="item">
                <div class="bck_but"> <a href="#carousel-example-generic" data-toggle="tooltip" title="Back" data-placement="right" data-target="#carousel-example-generic" data-slide-to="1" id="back"><i class="fa fa-arrow-left bck"></i></a> </div>
                <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                  <form class="form-horizontal">
                    <div class="row">
                      <div class="rfc_regs">
                        <ul>
                          <li><i class="fa fa-user-plus rgpa"></i><a href="#">Create New Resources</a></li>
                          <li><i class="fa fa-pencil-square-o rgpa"></i><a href="#">Modify Existing Resources</a></li>
                          <li><i class="fa fa-trash-o rgpa"></i><a href="#">Delete Existing Resources</a></li>
                        </ul>
                      </div>
                  
                    </div>
                  </form>
                </div>
              </div>
                 
                 
                 <!--Bill of Quantity-->
                 
                 
                           <!--Other Cost-->
                      <div class="item">
                <div class="bck_but"> <a href="#carousel-example-generic" data-toggle="tooltip" title="Back" data-placement="right" data-target="#carousel-example-generic" data-slide-to="1" id="back"><i class="fa fa-arrow-left bck"></i></a> </div>
                <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                  <form class="form-horizontal">
                    <div class="row">
                      <div class="rfc_regs">
                        <ul>
                          <li><i class="fa fa-user-plus rgpa"></i><a href="#">Create New Other Cost</a></li>
                          <li><i class="fa fa-pencil-square-o rgpa"></i><a href="#">Modify Existing Other Cost</a></li>
                          <li><i class="fa fa-trash-o rgpa"></i><a href="#">Delete Existing Other Cost</a></li>
                        </ul>
                      </div>
                
                    </div>
                  </form>
                </div>
              </div>
                 
                 
                 <!--Other Cost-->
                              
                 
                              <!--Wos-->
                      <div class="item">
                <div class="bck_but"> <a href="#carousel-example-generic" data-toggle="tooltip" title="Back" data-placement="right" data-target="#carousel-example-generic" data-slide-to="1" id="back"><i class="fa fa-arrow-left bck"></i></a> </div>
                <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                  <form class="form-horizontal">
                    <div class="row">
                      <div class="rfc_regs">
                        <ul>
                          <li><i class="fa fa-user-plus rgpa"></i><a href="#">Create New Work Breakdown Structure</a></li>
                          <li><i class="fa fa-pencil-square-o rgpa"></i><a href="#">Modify Existing Work Breakdown Structure</a></li>
                          <li><i class="fa fa-trash-o rgpa"></i><a href="#">Delete Existing Work Breakdown Structure</a></li>
                        </ul>
                      </div>
                
                    </div>
                  </form>
                </div>
              </div>
                 
                 
                 <!--Wos-->
                 
                 
                 
              
              
              
              
              <!-- Project Second Step Start -->
              <div class="item second-step-item">
                <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                  <form class="form-horizontal" action="rfcprojectiow" method="post">
                    <div class="col-lg-12 frmwrk_div" id="projects_list">
                      <select name="project_name" id="project_name" class="form-control selectpicker show-tick" data-size="6" title="Select Project...">
                        <option value="">Select Project</option>
                        <option value="project1">Project 1</option>
                        <option value="project2">Project 2</option>
                        <option value="project3">Project 3</option>
                        <option value="project4">Project 4</option>
                      </select>
                    </div>
                    <div class="col-lg-12 frmwrk_div" id="stages_list" style="display: none;">
                      <select name="stage" id="stage" class="form-control selectpicker show-tick" data-size="6" title="Select Stage...">
                        <option value="">Select Stage</option>
                        <option value="tender">Tender</option>
                        <option value="workorder">Work Order</option>
                        <option value="execution">Execution</option>
                      </select>
                    </div>
                    <div class="col-lg-12 frmwrk_div" id="types_list" style="display: none;">
                      <select name="type" id="type" class="form-control selectpicker show-tick" data-size="6" title="Select Type...">
                        <option value="">Select Type</option>
                        <option value="budget">Budget</option>
                        <option value="plan">Plan</option>
                      </select>
                    </div>
                    
                    <!--button-->
                    <div class="savebtn_areas col-lg-7 col-lg-offset-3">
                      <ul>
                        <li><a href="#carousel-example-generic" data-target="#carousel-example-generic" data-slide-to="0" id="back">Back </a></li>
                        <li class="subs"><a href="javascript: submitForm();"  id="continue">Submit</a></li>
                      </ul>
                    </div>
                    <!--button-->
                  </form>
                </div>
              </div>
              <!-- Project Second Step End --> 
              
              <!-- Indicators --> 
              <!--<ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            <li data-target="#carousel-example-generic" data-slide-to="3"></li>
          </ol>--> 
              <!-- Controls --> 
              
              <!--<ul class="prev_next">
            <li class="float_l"> <a href="#carousel-example-generic" data-slide="prev"> <span><i class="fa fa-arrow-left"></i></span> </a> </li>
            <li class="float_r"> <a href="#carousel-example-generic" role="button" data-slide="next"> <span><i class="fa fa-arrow-right"></i></span> </a> </li>
          </ul>--> 
            </div>
            <!-- Wrapper for slides end --> 
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--<div class="col-lg-12 savebtn_area">
  <ul>
  <li class="dropdown save_btn float_r">
                  <a href="landcost_calculation.php" class="ripple">Save</a>
                  <div class="save_trigger">
                      <a href="javascript:void(0);" class="ripple" data-toggle="dropdown">
                          <i class="fa fa-angle-down"></i>
                      </a>
                      <ul class="ang_down_ul save_down_ul dropdown-menu dropdown-menu-right">
                          <li><a href="javascript:void(0);">Save &amp; Next</a></li>
                          <li><a href="javascript:void(0);">Save &amp; Exit</a></li>
                      </ul>
                  </div>
              </li>
              <li class="cancel_btn float_r"><a href="javascript:void(0);" class="ripple">back</a></li>
    <li class="goto">
      <label class="float_l" for="go_to">Go to</label>
      <select title="Choose Page to go...." class="float_l goto_select" name="go_to" id="go_to">
        <option>Create Resource </option>
        <option>Edit Resource </option>
        <option>Delete Resource </option>
        <option>Create Resource Group </option>
        <option>Edit Resource Group </option>
        <option>Delete Resource Group </option>
        <option>Create Revision </option>
        <option>Edit Revision </option>
        <option>Delete Revision </option>
        <option>Create BOQ </option>
        <option>Edit BOQ </option>
        <option>Delete BOQ</option>
        <option>Edit Resource </option>
        <option>Create OverHeads </option>
        <option>Edit OverHeads </option>
        <option>Delete OverHeads</option>
      </select>
    </li>
  </ul>
</div>--> 

<!--slider start--> 
<script type="text/javascript">
        $(function () {
            $('.first-step').on('click', function(e) {
                $('.step_by_sep').removeClass('stepsep_active');
                $('#tag-step-2').addClass('stepsep_active');
            });
        });

        $('#continue').on('click', function () {
            $('.step_by_sep').removeClass('stepsep_active');
            if ($('.third-step-item').hasClass('active')) {
                $('#tag-step-3').addClass('stepsep_active');
            }else if ($('.second-step-item').hasClass('active')) {
                $('#tag-step-2').addClass('stepsep_active');
            }
        });

        $('#back').on('click', function () {
            $('.step_by_sep').removeClass('stepsep_active');

            if ($('.third-step-item').hasClass('active')) {
                $('#tag-step-3').addClass('stepsep_active');
            } else if ($('.second-step-item').hasClass('active')) {
                $('#tag-step-2').addClass('stepsep_active');
            } else {
                $('#tag-step-1').addClass('stepsep_active');
            }
        });

        // on change project option
        var $stages_list = $('#stages_list'),
            $types_list = $('#types_list');

        $('#project_name').on('change', function() {
            var value = $(this).val();

            if (value == '') {
                $stages_list.hide();
                $types_list.hide();
                return;
            }
            $stages_list.show();
        });

        $('#stage').on('change', function() {
            var value = $(this).val();

            if (value == 'execution') {
                $types_list.show();
                return;
            }
            $types_list.hide();
        });

      $('.cnt_slider .carousel').carousel({
          interval: false
      })
      $(".rfc_regs li").click(function(){
          var ele = $(this).closest('.item');
          ele.find('li').each(function(){
              $(this).removeClass("active");
          })
          $(this).addClass("active");
    
          if($(this).find('a').attr("url") != undefined){
              ele.find("#continue").attr("href", $(this).find('a').attr("url"))
          }
          else{
              ele.find("#continue").attr("data-slide-to", $(this).attr("cid"));
          }
      })
    
    </script> 
<!--slider end-->