<!--STYLE-->
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css';?>"/>
<!--STYLE-->
<!--content-->

<div class="content_wrapper padlr0">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h1>Request for creation - Work group add</h1>
      </div>
      <!--form start-->
      <div class="row">
        <div class="col-lg-12 top_ct" >
          <div class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-5 col-sm-offset-1">
            <div class="form-group col-lg-11 col-lg-offset-1">
              <input type="text" name="lead_name" id="lead_name" class="form-control lbl_move" placeholder="20/03/2015" />
            </div>
          </div>
          <div class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-5 col-sm-offset-0">
            <div class="form-group col-lg-11">
              <input type="text" name="lead_name" id="lead_name" class="form-control lbl_move" placeholder="RFC1225" />
            </div>
          </div>
        </div>
      </div>
      <!--form end--> 
      
      <!--table start-->
      
      <div class="col-lg-12 col-lg-offset-0">
        <div class="table-responsive topsp">
          <table class="table" style=" margin-bottom:0px;">
            <thead>
              <tr>
                <th>Work type</th>
                <th>Work group</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td width="45%"><div class="select-style">
                    <select>
                      <option value="0">Select work type</option>
                      <option value="1">Ls</option>
                      <option value="2">Manual</option>
                      <option value="3">Machinery </option>
                    </select>
                  </div></td>
                <td width="45%"><input class="parent_text" type="text" placeholder="Edit text" /></td>
                <td width="10%"><a href="#"><i class="fa fa-plus-circle ctls" data-toggle="tooltip" data-placement="top" data-original-title="Add new"></i></a> &nbsp;&nbsp; &nbsp; &nbsp; <a href="#" class="mainTr"><i class="fa fa-chevron-circle-down ctls" data-toggle="tooltip" data-placement="top" data-original-title="Expand"></i></a></td>
              </tr>
              
              <!--expand table-->
              <tr style="display:none;" class="subTr">
                <td colspan="8" style="padding:0px !important; "><div class="subDiv" style="display:none;">
                    <div class="col-lg-12 col-lg-offset-0"> 
                      
                      <!-- Nav tabs -->
                      <div id="navbar" class="navbar-collapse padlr0 collapse" style="margin-top:10px; margin-bottom:8px;">
                        <ul class="nav nav-tabs innermdl_tabs">
                          <!--<li><a href="#" data-toggle="tab" class="ripple">Activity analysis</a></li>-->
                          <li class="active sampletest" sid="firstStep"><a href="#" data-toggle="tab" class="ripple">Setting</a></li>
                          <li class="sampletest" sid="secondStep"><a href="#" data-toggle="tab" class="ripple">Analysis</a></li>
                        </ul>
                      </div>
                      <!-- Nav end --> 
                      <!--chexbox area-->
                      <div class="radio_check createds firstStep hideStep" style="border:1px solid #E6E6FA; width:100%;  padding-bottom:7px;">
                        <p style="margin-left:5px;">
                          <input type="checkbox" value="Concrete" id="Concrete" name="gender" checked/>
                          <label for="Concrete">Concrete Mix </label>
                        </p>
                        <p>
                          <input type="checkbox" value="Cement" id="Cement" name="gender" />
                          <label for="Cement">Cement</label>
                        </p>
                        <p>
                          <input type="checkbox" value="Sand" id="Sand" name="gender" />
                          <label for="Sand">Sand</label>
                        </p>
                        <p>
                          <input type="checkbox" value="Metal" id="Metal" name="gender" />
                          <label for="Metal">Metal</label>
                        </p>
                        <p>
                          <input type="checkbox" value="Thickness" id="Thickness" name="gender" />
                          <label for="Thickness">Thickness</label>
                        </p>
                      </div>
                      <!--chexbox area--> 
                      <!--chexbox area-->
                      
                      <div class="radio_check createds firstStep hideStep" style="clear:both; float:left; width:100%;">
                        <p class="multi_check">
                          <input type="checkbox" value="Activity" id="Activity" name="gender" checked/>
                          <label for="Activity">Create activity resource group same as work group</label>
                        </p>
                        <p class="multi_check">
                          <input type="checkbox" value="Activity1" id="Activity1" name="gender" />
                          <label for="Activity1">Automatically generate rate analysis for item of work based on work group analysis</label>
                        </p>
                        <p class="multi_check">
                          <input type="checkbox" value="Activity2" id="Activity2" name="gender" />
                          <label for="Activity2">Auto activity resource creation based on </label>
                        </p>
                        <p>
                          <input type="radio" value="Activity3" id="Activity3" name="gender" />
                          <label for="Activity3">Workgroup</label>
                        </p>
                        <p>
                          <input type="radio" value="Activity4" id="Activity4" name="gender" />
                          <label for="Activity4">Item of work </label>
                        </p>
                      </div>
                      
                      <!--chexbox area--> 
                    </div>
                    <!--expan sub table-->
                    <div class="col-lg-12 secondStep hideStep" style="display:none">
                      <div class="col-lg-12 radio_check createds">
                        <p>
                          <input type="radio" value="SiteMix" id="SiteMix" name="gender" />
                          <label for="SiteMix">SiteMix</label>
                        </p>
                        <p>
                          <input type="radio" value="ReadyMix" id="ReadyMix" name="gender" />
                          <label for="ReadyMix">ReadyMix</label>
                        </p>
                      </div>
                      <div class="col-lg-12 col-lg-offset-0">
                        <input class="exp_value" type="text" placeholder="0000.00" />
                        <input class="exp_value" type="text" placeholder="0000.00" />
                        <input class="exp_value" type="text" placeholder="0000.00" />
                        <input class="exp_value" type="text" placeholder="0000.00" />
                        <input class="exp_value" type="text" placeholder="0000.00" />
                      </div>
                      <div class="table-responsive topsp">
                        <table class="table" style="margin-bottom:0px;">
                          <thead>
                            <tr>
                              <th>Inc</th>
                              <th>Rfc</th>
                              <th>Code</th>
                              <th>Resource</th>
                              <th>Unit</th>
                              <th>Coefficient</th>
                              <th>Formula</th>
                              <th>Action</th>
                            </tr>
                          </thead>
                          <tbody>
                            <tr>
                              <td width="1%"><p>
                                  <input type="checkbox" value="Concrete" id="Concrete" name="gender" checked/>
                                </p></td>
                              <td width="8%"><input class="parent_text"/></td>
                              <td width="8%"><input class="parent_text"/></td>
                              <td width="10%"><div class="select-style">
                                  <select>
                                    <option value="">Select resource</option>
                                    <option value="1">resource</option>
                                    <option value="2">resource</option>
                                    <option value="10">resource</option>
                                  </select>
                                </div></td>
                              <td width="10%"><input class="parent_text" type="text" /></td>
                              <td width="10%"><input class="parent_text" type="text" /></td>
                              <td width="10%"><input class="parent_text" type="text" /></td>
                              <td width="1%" align="center"><a href="#"><i class="fa fa-plus-circle ctls" data-toggle="tooltip" data-placement="top" data-original-title="Add new"></i></a></td>
                            </tr>
                          </tbody>
                        </table>
                      </div>
                    </div>
                    
                    <!--expan sub table--> 
                  </div></td>
              </tr>
              <!--expand table end--> 
              <!--Remarks star-->
              <tr>
                <td colspan="5"><textarea placeholder="Enter remarks !" class="remrk element"></textarea></td>
              </tr>
              <!--Remarks end--> 
              
              <!--expand end-->
            </tbody>
          </table>
        </div>
      </div>
      <!--table end--> 
    </div>
  </div>
</div>
<div class="col-lg-12 savebtn_area">
  <ul>
    <li class="dropdown save_btn float_r"><a href="javascript:void(0);" data-toggle="tooltip" class="ripple" title="Go to continue !">Continue</a></li>
    <li class="cancel_btn float_r"><a href="javascript:void(0);" data-toggle="tooltip" class="ripple" title="Go back!">Back</a></li>
    <!--<li class="dropdown save_btn float_r">
                    <a href="javascript:void(0);" class="ripple">Save</a>
                    <div class="save_trigger">
                        <a href="javascript:void(0);" class="ripple" data-toggle="dropdown">
                            <i class="fa fa-angle-down"></i>
                        </a>
                        <ul class="ang_down_ul save_down_ul dropdown-menu dropdown-menu-right">
                            <li><a href="javascript:void(0);">Save As</a></li>
                            <li><a href="javascript:void(0);">Exit</a></li>
                        </ul>
                    </div>
                </li>
                <li class="cancel_btn float_r"><a href="javascript:void(0);" class="ripple">Cancel</a></li>-->
    
  </ul>
</div>
<!--content--> 
<!--expand start--> 
<script type="text/javascript">
$(function(){
	$('.ripple').materialripple();
	var dp1 = $('.date_picker').datepicker().on('changeDate', function() {
		$('.datepicker').hide();
	}).data('datepicker');
	$('.toolbar_ddown ul').slimScroll({
		height : '100%',
		alwaysVisible: false,
		railVisible: true,
		railColor: '#cececd',
		railOpacity: 1
	});
});
</script> 
<script>
$(".sampletest").click(function(){

	var step = $(this).attr("sid");
	if(step=='firstStep'){
		$(this).closest("td").find(".secondStep").fadeOut("2000", function(){
			$(this).closest("td").find("."+step).fadeIn("2000");
		});		
	}
	else{
		$(this).closest("td").find(".firstStep").fadeOut("2000", function(){
			$(this).closest("td").find("."+step).fadeIn("2000");
		});		
	}

	//alert($(this).closest("div").html()+"----"+step)
	

})
$(".mainTr").click(function(){
	//alert($(this).closest("tr").next(".subTr").html())
	if(!$(this).closest("tr").next(".subTr").is(":visible")){
		$(this).closest("tr").next(".subTr").show();
		$(this).closest("tr").next(".subTr").find(".subDiv").slideDown("slow");	
	}
		else{
		$(this).closest("tr").next(".subTr").find(".subDiv").slideUp("slow");
		$(this).closest("tr").next(".subTr").slideUp("slow");
	
	}
})
</script> 
<!--expand start-->