<!--STYLE-->
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css';?>"/>
<!--STYLE-->

<div class="content_wrapper padlr0">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h1>Request for creation - Work group edit</h1>
      </div>
      
      <!--form start-->
      <div class="row">
        <div class="col-lg-12 top_ct" >
          <div class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-5 col-sm-offset-1">
            <div class="form-group col-lg-11 col-lg-offset-1">
              <input type="text" name="lead_name" id="lead_name" class="form-control lbl_move" placeholder="20/03/2015" />
            </div>
          </div>
          <div class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-5 col-sm-offset-0">
            <div class="form-group col-lg-11">
              <input type="text" name="lead_name" id="lead_name" class="form-control lbl_move" placeholder="RFC1225" />
            </div>
          </div>
        </div>
      </div>
      <!--form end--> 
      <!--table Jq Gride start-->
      <div class="col-lg-12 col-lg-offset-0">
        <div class="col-lg-12 clear">
          <div class="table-responsive clear">
            <div id="dataTable"></div>
          </div>
        </div>
      </div>
      <!--table Jq Gride end--> 
    </div>
  </div>
</div>
<div class="col-lg-12 savebtn_area">
  <ul>
    <li class="dropdown save_btn float_r"><a href="javascript:void(0);" data-toggle="tooltip" class="ripple" title="Go to continue !">Continue</a></li>
    <li class="cancel_btn float_r"><a href="javascript:void(0);" data-toggle="tooltip" class="ripple" title="Go back!">Back</a></li>
    <!--<li class="dropdown save_btn float_r">
                    <a href="javascript:void(0);" class="ripple">Save</a>
                    <div class="save_trigger">
                        <a href="javascript:void(0);" class="ripple" data-toggle="dropdown">
                            <i class="fa fa-angle-down"></i>
                        </a>
                        <ul class="ang_down_ul save_down_ul dropdown-menu dropdown-menu-right">
                            <li><a href="javascript:void(0);">Save As</a></li>
                            <li><a href="javascript:void(0);">Exit</a></li>
                        </ul>
                    </div>
                </li>
                <li class="cancel_btn float_r"><a href="javascript:void(0);" class="ripple">Cancel</a></li>-->
  </ul>
</div>
<script>
$(document).ready(function () {
//var url = "displayRegister";
var data = [
{Serialno:"1",Worktype:"Cement", Select:false}, 
{Serialno:"1",Worktype:"Cement", Select:true}, 
{Serialno:"1",Worktype:"Cement", Select:true}]
// prepare the data
var source =
{	
	localdata:data,
	dataType: "json",
	dataFields: [
		{ name: 'Serialno', type: 'string' },
		{ name: 'Worktype', type: 'string' },
		{ name: 'Select', type: 'boolean' },
		
	],
	id: 'RequestId',
};

var dataAdapter = new $.jqx.dataAdapter(source);

$("#dataTable").jqxGrid(
{
	width: '100%',
	pageable: true,
	rowsheight: 35,
	selectionMode: 'singleRow',	
	pagerButtonsCount: 6,
	autoheight:true,
	editable:true,
	source: dataAdapter,
	columnsResize: true,
	columns: [
	  { text: 'Serial no', dataField: 'Serialno', columntype: 'number', width:'20%',editable:false,cellsalign:'left',align:'left', },
	  { text: 'Worktype', dataField: 'Worktype', width:'40%', editable:false,align:'left', cellsalign:'left'  },
      { text: 'Select', datafield: 'Select', columntype: 'checkbox', width: '40%', align:'center', classname: 'sample' },
	 
  ]
});
$("#dataTable").bind('rowselect', function (event) {
	
	
});

});
</script>
<script type="text/javascript">
function MM_preloadImages() { //v3.0
  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
    if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}
</script>
<script>
$(document).ready(function () {
//var url = "displayRegister";
var data = [
{Serialno:"1",Worktype:"Cement", Select:false}, 
{Serialno:"1",Worktype:"Cement", Select:true}, 
{Serialno:"1",Worktype:"Cement", Select:true}]
// prepare the data
var source =
{	
	localdata:data,
	dataType: "json",
	dataFields: [
		{ name: 'Serialno', type: 'string' },
		{ name: 'Worktype', type: 'string' },
		{ name: 'Select', type: 'boolean' },
		
	],
	id: 'RequestId',
};

var dataAdapter = new $.jqx.dataAdapter(source);

$("#dataTable").jqxGrid(
{
	width: '100%',
	pageable: true,
	rowsheight: 35,
	selectionMode: 'singleRow',	
	pagerButtonsCount: 6,
	autoheight:true,
	editable:true,
	source: dataAdapter,
	columnsResize: true,
	columns: [
	  { text: 'Serial no', dataField: 'Serialno', columntype: 'number', width:'20%',editable:false,cellsalign:'left',align:'left', },
	  { text: 'Worktype', dataField: 'Worktype', width:'40%', editable:false,align:'left', cellsalign:'left'  },
      { text: 'Select', datafield: 'Select', columntype: 'checkbox', width: '40%', align:'center', classname: 'sample' },
	 
  ]
});
$("#dataTable").bind('rowselect', function (event) {
	
	
});

});
</script>
<script type="text/javascript">
function MM_preloadImages() { //v3.0
  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
    if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}
</script>

<script type="text/javascript">
$(function(){
	$('.ripple').materialripple();
	var dp1 = $('.date_picker').datepicker().on('changeDate', function() {
		$('.datepicker').hide();
	}).data('datepicker');
	$('.toolbar_ddown ul').slimScroll({
		height : '100%',
		alwaysVisible: false,
		railVisible: true,
		railColor: '#cececd',
		railOpacity: 1
	});
});
</script>
