<!--STYLE-->
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css';?>"/>
<style>
.tableFloatingHeaderOriginal {
	margin-top:10% !important;
}
table {
	border-spacing: 0;
}
.head {
    display: none;
    position: fixed;
    top:0px;
}
.head1 {
    display: none;
    position: fixed;
    top:20px;
}
.head > div {
    display: inline-block;
    box-sizing: border-box;
    font-weight: bold;
}
.head1 > div {
    display: inline-block;
    box-sizing: border-box;
    font-weight: bold;
}
#Grid thead{ left:0px !important; z-index:99999 !important; }
.tableFloatingHeaderOriginal{ left:0px !important; }
</style>
<!--content-->
<div class="content_wrapper padlr0">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h1> Request for Creation - Project IOW Add</h1>
      </div>
      <!--form start-->
      <div class="col-lg-12 top_ct" >
        <div class="col-lg-3 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-8 col-sm-offset-2">
          <div class="form-group"> <span class="date_icon"><i class="fa fa-calendar"></i></span>
            <input type="text" name="lead_date" id="lead_date" class="form-control date_picker lbl_move" label="Reference Date" />
          </div>
        </div>
        <div class="col-lg-3 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-8 col-sm-offset-2">
          <div class="form-group">
            <input type="text" name="lead_name" id="lead_name" class="form-control lbl_move" label="Enter reference no" />
          </div>
        </div>
        <div class="col-lg-3 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-8 col-sm-offset-2">
          <div class="form-group"> <span class="date_icon"><i class="fa fa-calendar"></i></span>
            <input type="text" name="lead_date" id="lead_date" class="form-control date_picker lbl_move" label="Project Name" />
          </div>
        </div>
        <div class="col-lg-3 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-8 col-sm-offset-2">
          <div class="form-group">
            <input type="text" name="lead_name" id="lead_name" class="form-control lbl_move" label="Type" />
          </div>
        </div>
        <!--<div class="col-lg-4 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-8 col-sm-offset-2">
          <div class="form-group col-lg-12"> <span class="butclr btn-file"> <i class="fa fa-folder-open"></i> Import from Excel
            <input type="file"/>
            </span> </div>
        </div>--> 
      </div>
      <!--form end--> 
      <!--form start--> 
      
      <!--<div class="col-lg-12 top_ct" >
        <div class="col-lg-4 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-8 col-sm-offset-2">
          <div class="form-group col-lg-12"> <span class="date_icon"><i class="fa fa-calendar"></i></span>
            <input type="text" name="lead_date" id="lead_date" class="form-control date_picker lbl_move" label="Project Name" />
          </div>
        </div>
        <div class="col-lg-4 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-8 col-sm-offset-2">
          <div class="form-group col-lg-12">
            <input type="text" name="lead_name" id="lead_name" class="form-control lbl_move" label="Type" />
          </div>
        </div>
    
      </div>--> 
      
      <!--form end--> 
      <!--table start-->
      
      <div class="col-lg-12 col-lg-offset-0">
        <div class="table-responsive topsp animated-panel zoomIn" style="animation-delay: 0.2s;">
          <table class="table tableWithFloatingHeader" id="Grid" style=" margin-bottom:0px;">
            <thead>
              <tr>
              <tr>
                <th>Parent</th>
                <th>Ref no</th>
                <th>S-No</th>
                <th>Unit</th>
                <th>Rate</th>
                <th>Qty</th>
                <th>Amount</th>
                <th class="text-center">Action</th>
              </tr>
                </tr>
              
            </thead>
            <tbody>
              <tr>
                <td width="15%"><input class="parent_text" type="text" /></td>
                <td width="5%" ><input class="parent_text" type="text"/></td>
                <td width="4%"><input class="parent_text" type="text" /></td>
                <td width="4%"><input class="parent_text" type="text" /></td>
                <td width="4%"><input class="parent_text" type="text" /></td>
                <td width="5%"><input class="parent_text" type="text" /></td>
                <td width="5%"><input class="parent_text" type="text" /></td>
                <td width="3%" align="center"><a href="#"><i class="fa fa-trash-o ctls" data-toggle="tooltip" data-placement="top" data-original-title="Close"></i></a>&nbsp;&nbsp; <a href="#" class="mainTr"> <i class="fa fa-chevron-circle-down ctls" data-toggle="tooltip" data-placement="top" data-original-title="Expand" ></i></a></td>
              </tr>
              
              <!--expand table-->
              <tr style="display:none;" class="subTr">
                <td colspan="9" style="padding:0px !important; "><div class="subDiv" style="display:none;">
                    <div class="col-lg-12 col-lg-offset-0 rdbt" style="margin-top:5px;">
                      <form class="form-inline">
                        <div class="form-group">
                          <label style="vertical-align:top;">Specification</label>
                          <textarea class="form-control"></textarea>
                        </div>
                        <div class="form-group">
                          <label style="vertical-align:top;">Short Specification</label>
                          <textarea class="form-control"></textarea>
                        </div>
                      </form>
                      <!-- Nav tabs -->
                      <div class="darkmenu">
                        <ul>
                          <li class="active"><a href="#">Sitemix</a></li>
                          <li><a href="#">Readymix</a></li>
                        </ul>
                      </div>
                      <!-- Tab panes -->
                      <div class="tap_work">
                        <ul>
                          <li>
                            <label>Working qty</label>
                            <input type="text" class="parent_text"/>
                          </li>
                          <li>
                            <label>Cement</label>
                            <input type="text" class="parent_text"/>
                          </li>
                          <li>
                            <label>Sand</label>
                            <input type="text" class="parent_text"/>
                          </li>
                          <li>
                            <label>Metal</label>
                            <input type="text" class="parent_text"/>
                          </li>
                          <li>
                            <label>Thickness</label>
                            <input type="text" class="parent_text"/>
                          </li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-lg-12">
                      <div class="table-responsive topsp">
                        <table class="table" style="margin-bottom:0px;">
                          <thead>
                            <tr>
                              <th class="bg_clo">Include/Exclude</th>
                              <th class="bg_clo">Ref no</th>
                              <th class="bg_clo">Code</th>
                              <th class="bg_clo">Resource</th>
                              <th class="bg_clo">Coefficient</th>
                              <th class="bg_clo">Unit</th>
                              <th class="bg_clo">Rate</th>
                              <th class="bg_clo">Amount</th>
                              <th class="bg_clo">Action</th>
                            </tr>
                          </thead>
                          <tbody>
                            <tr>
                              <td width="3%"><label>
                                <input type="checkbox" name="checkbox" class="ios_checkbox"/>
                                <div class="ios_switch"><span></span></div>
                                </label></td>
                              <td width="8%"><input class="parent_text" type="text" /></td>
                              <td width="8%"><input class="parent_text"/></td>
                              <td width="15%"><div class="select-style">
                                  <select>
                                    <option value="0">Select resource</option>
                                    <option value="1">Cement</option>
                                    <option value="2">Sand</option>
                                    <option value="3">Oil</option>
                                    <option value="4">Electric Material</option>
                                    <option value="5">Batching Plant ( Concrete BP )</option>
                                    <option value="5">Batching plant operator</option>
                                    <option value="5">Bitumen sprayer</option>
                                  </select>
                                </div></td>
                              <td width="8%" align="center"><input type="text"  class="parent_text" data-toggle="modal" data-target="#myModal"/></td>
                              <td width="8%"><input class="parent_text" type="text" /></td>
                              <td width="8%"><input class="parent_text" type="text" /></td>
                              <td width="10%"><input class="parent_text" type="text" /></td>
                              <td width="1%" align="center"><a href="#"><i class="fa fa-times-circle ctls" data-toggle="tooltip" data-placement="top" data-original-title="Close"></i></a></td>
                            </tr>
                            <tr style="border-bottom:none;">
                              <td style="border-right:none;"></td>
                              <td style="border-right:none;"></td>
                              <td style="border-right:none;"></td>
                              <td style="border-right:none;"></td>
                              <td style="border-right:none;"></td>
                              <td style="border-right:none;"></td>
                              <td style="border-right:none; font-size:15px; color:#1d99d4;" align="right">Rate for</td>
                              <td style="border-right:none;"><input class="parent_text" type="text" placeholder="00.0"/></td>
                              <td style="border-right:none;">&nbsp;</td>
                            </tr>
                            <tr style="border-bottom:none;">
                              <td style="border-right:none; border-top:none;"></td>
                              <td style="border-right:none;border-top:none;"></td>
                              <td style="border-right:none;border-top:none;"></td>
                              <td style="border-right:none;border-top:none;"></td>
                              <td style="border-right:none;border-top:none;"></td>
                              <td style="border-right:none;border-top:none;"></td>
                              <td style="border-right:none;border-top:none; font-size:15px;color:#1d99d4;" align="right">Rate per</td>
                              <td style="border-right:none;border-top:none;"><input class="parent_text" type="text" placeholder="00.0" /></td>
                              <td style="border-right:none;border-top:none;">&nbsp;</td>
                            </tr>
                            <tr style="border-bottom:none;">
                              <td style="border-right:none; border-top:none;"></td>
                              <td style="border-right:none;border-top:none;"></td>
                              <td style="border-right:none;border-top:none;"></td>
                              <td style="border-right:none;border-top:none;"></td>
                              <td style="border-right:none;border-top:none;"></td>
                              <td style="border-right:none;border-top:none;"></td>
                              <td style="border-right:none;border-top:none; font-size:15px;color:#1d99d4;" align="right">Net rate</td>
                              <td style="border-right:none;border-top:none;"><input class="parent_text" type="text" placeholder="00.0" /></td>
                              <td style="border-right:none;border-top:none;">&nbsp;</td>
                            </tr>
                          </tbody>
                          <tbody>
                            <tr>
                              <td width="3%"><label>
                                <input type="checkbox" name="checkbox" class="ios_checkbox"/>
                                <div class="ios_switch"><span></span></div>
                                </label></td>
                              <td width="8%"><input class="parent_text" type="text" /></td>
                              <td width="8%"><input class="parent_text"/></td>
                              <td width="15%"><div class="select-style">
                                  <select>
                                    <option value="0">Select resource</option>
                                    <option value="1">Cement</option>
                                    <option value="2">Sand</option>
                                    <option value="3">Oil</option>
                                    <option value="4">Electric Material</option>
                                    <option value="5">Batching Plant ( Concrete BP )</option>
                                    <option value="5">Batching plant operator</option>
                                    <option value="5">Bitumen sprayer</option>
                                  </select>
                                </div></td>
                              <td width="8%" align="center"><input type="text"  class="parent_text" data-toggle="modal" data-target="#myModal"/></td>
                              <td width="8%"><input class="parent_text" type="text" /></td>
                              <td width="8%"><input class="parent_text" type="text" /></td>
                              <td width="10%"><input class="parent_text" type="text" /></td>
                              <td width="1%" align="center"><a href="#"><i class="fa fa-times-circle ctls" data-toggle="tooltip" data-placement="top" data-original-title="Close"></i></a></td>
                            </tr>
                            <tr style="border-bottom:none;">
                              <td style="border-right:none;"></td>
                              <td style="border-right:none;"></td>
                              <td style="border-right:none;"></td>
                              <td style="border-right:none;"></td>
                              <td style="border-right:none;"></td>
                              <td style="border-right:none;"></td>
                              <td style="border-right:none; font-size:15px; color:#1d99d4;" align="right">Rate for</td>
                              <td style="border-right:none;"><input class="parent_text" type="text" placeholder="00.0"/></td>
                              <td style="border-right:none;">&nbsp;</td>
                            </tr>
                            <tr style="border-bottom:none;">
                              <td style="border-right:none; border-top:none;"></td>
                              <td style="border-right:none;border-top:none;"></td>
                              <td style="border-right:none;border-top:none;"></td>
                              <td style="border-right:none;border-top:none;"></td>
                              <td style="border-right:none;border-top:none;"></td>
                              <td style="border-right:none;border-top:none;"></td>
                              <td style="border-right:none;border-top:none; font-size:15px;color:#1d99d4;" align="right">Rate per</td>
                              <td style="border-right:none;border-top:none;"><input class="parent_text" type="text" placeholder="00.0" /></td>
                              <td style="border-right:none;border-top:none;">&nbsp;</td>
                            </tr>
                            <tr style="border-bottom:none;">
                              <td style="border-right:none; border-top:none;"></td>
                              <td style="border-right:none;border-top:none;"></td>
                              <td style="border-right:none;border-top:none;"></td>
                              <td style="border-right:none;border-top:none;"></td>
                              <td style="border-right:none;border-top:none;"></td>
                              <td style="border-right:none;border-top:none;"></td>
                              <td style="border-right:none;border-top:none; font-size:15px;color:#1d99d4;" align="right">Net rate</td>
                              <td style="border-right:none;border-top:none;"><input class="parent_text" type="text" placeholder="00.0" /></td>
                              <td style="border-right:none;border-top:none;">&nbsp;</td>
                            </tr>
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div></td>
              </tr>
              
              <!--button--> 
              
              <!--button--> 
              <!--expand end-->
            </tbody>
          </table>
        </div>
        
        
            <div class="table-responsive topsp animated-panel zoomIn" style="animation-delay: 0.2s;">
          <table class="table tableWithFloatingHeader" id="Grid" style=" margin-bottom:0px;">
            <thead>
              <tr>
              <tr>
                <th>Parent</th>
                <th>Ref no</th>
                <th>S-No</th>
                <th>Unit</th>
                <th>Rate</th>
                <th>Qty</th>
                <th>Amount</th>
                <th class="text-center">Action</th>
              </tr>
                </tr>
              
            </thead>
            <tbody>
              <tr>
             
                <td colspan="100" align="center"><p style=" color:#686B6F; text-align:center;">No data to display</p></td>

           
                    </tr>

            </tbody>
          </table>
        </div>
      </div>
      
      <!--table end--> 
    </div>
  </div>
</div>
<div class="col-lg-12 savebtn_area">
  <ul>
    <li class="dropdown save_btn float_r"><a href="javascript:void(0);" data-toggle="tooltip" class="ripple" title="Go to continue !">Continue</a>
    <li class="cancel_btn float_r"><a href="javascript:void(0);" data-toggle="tooltip" class="ripple" title="Go back!">Back</a></li>
    <!--<li class="dropdown save_btn float_r">
                    <a href="javascript:void(0);" class="ripple">Save</a>
                    <div class="save_trigger">
                        <a href="javascript:void(0);" class="ripple" data-toggle="dropdown">
                            <i class="fa fa-angle-down"></i>
                        </a>
                        <ul class="ang_down_ul save_down_ul dropdown-menu dropdown-menu-right">
                            <li><a href="javascript:void(0);">Save As</a></li>
                            <li><a href="javascript:void(0);">Exit</a></li>
                        </ul>
                    </div>
                </li>
                <li class="cancel_btn float_r"><a href="javascript:void(0);" class="ripple">Cancel</a></li>-->
  </ul>
</div>
<!--content-->


<!--table header script--> 
<script src="<?php echo $this->basePath(); ?>/js/jquery.stickytableheaders.js"></script> 
<script>
	$("table").stickyTableHeaders();
</script> 
<!--table header script end--> 
<!--table expand start--> 
<script>
$(".mainTr").click(function(e){
	e.preventDefault();
	if(!$(this).closest("tr").next(".subTr").is(":visible")){
		$(this).closest("tr").next(".subTr").show();
		$(this).closest("tr").next(".subTr").find(".subDiv").slideDown("slow");	
		$(this).find("i").addClass("tform");
	}
		else{
		$(this).closest("tr").next(".subTr").find(".subDiv").slideUp("slow");
		$(this).closest("tr").next(".subTr").slideUp("slow");
		$(this).find("i").removeClass("tform");
	}
})
</script> 
<!--table expand end--> 
<!--datepicker--> 
<script type="text/javascript">
$(function(){
	$('.ripple').materialripple();
	var dp1 = $('.date_picker').datepicker().on('changeDate', function() {
		$('.datepicker').hide();
	}).data('datepicker');
	$('.toolbar_ddown ul').slimScroll({
		height : '100%',
		alwaysVisible: false,
		railVisible: true,
		railColor: '#cececd',
		railOpacity: 1
	});
});
(function ($) {
        $.fn.fixedHeader = function (vari) {
            return this.filter('table').each(function () {
                var that = this;
                var $head = $('<div></div>').addClass(vari);
                $(this).before($head);
                $('th', this).each(function () {
                    var $el = $(this);
                    var $div = $('<div></div>').width($el.outerWidth()).text(
                    $el.text());
                    $head.append($div);
                });
                $(window).on('scroll', function () {
                    var $that = $(that);
                    var w = $(window).scrollTop();
                    var o = $('th', that).first().offset().top;
                    var tableO = $that.offset().top + $that.height();
                    if (o < w && tableO > w) {
                        $head.show();
                    } else {
                        $head.hide();
                    }
                });
            });
        };
    })(jQuery);
    $('#Grid').fixedHeader('head');
     $('#Grid1').fixedHeader('head1');
</script> 
<!--datepicker--> 

