<!--Handson Table plugin-->
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath(); ?>/library/handsontable/css/handsontable.full.min.css">
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/handsontable/js/handsontable.full.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/handsontable/js/RuleJS/lodash.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/handsontable/js/RuleJS/underscore.string.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/handsontable/js/RuleJS/numeral.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/handsontable/js/RuleJS/numeric.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/handsontable/js/formula.js"></script>
<script type="text/javascript"src="<?php echo $this->basePath(); ?>/library/handsontable/js/parser.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/handsontable/js/ruleJS.all.full.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/handsontable/js/handsontable.formula.js"></script>
<!--Handson Table Plugin-->

<!--STYLE-->
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/workorder.css'; ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/wpm.css'; ?>"/>
<!--STYLE-->
<style>
.lab-natt label{padding-top:32px}
.lab-natt textarea{height:100px; overflow:auto}
    .panel {
        border-radius: 0px !important;
    }

    .panel-info {
        border: none;
        border-top: none;
    }

    #HandsonTableWrapper {height: 100%; width: 100%; overflow: hidden; }
    #HandsonWrapper {display: none;}
    .top-addtip{width: 168px;left: -80px;top: -58px;height: 90px;z-index: 1000001 !important;visibility: visible;}
    .top-addtip:after{content: ""; display: block; width: 0; height: 0; border-left: 6px solid #7d73b3; border-top: 6px solid transparent; border-bottom: 6px solid transparent; position: absolute; top:32px; left:104%;z-index:1}
</style>


<!--content-->
<div class="content_wrapper padlr0">
<div class="container-fluid">
<div class="row">
    <form method="post" id="formWrapper">
        <input type="hidden" name="WORegisterId" id="WORegisterId" value="<?php echo (isset($workorder)) ? $workorder['WORegisterId'] : '0';?>">
        <input type="hidden" name="CostCenterId" id="costCentreId" value="<?php echo (isset($costcenter)) ? $costcenter['CostCentreId'] : '0';?>">
        <input type="hidden" name="VendorId" value="<?php echo (isset($vendor)) ? $vendor['VendorId'] : '0';?>">
        <input type="hidden" name="WorkType" id="WorkType" value="<?php echo (isset($WorkType)) ? $WorkType : '';?>">
        <input type="hidden" name="wpTypeId" id="wpTypeId" value="<?php echo (isset($wpTypeId)) ? $wpTypeId : ''; ?>">
        <input type="hidden" name="wbsReq" id="wbsReq" value="<?php echo $wbsReq; ?>">
        <input type="hidden" name="projectId" id="projectId" value="<?php echo $projectId; ?>">
        <input type="hidden" name="CompanyId" id="CompanyId" value="<?php echo (isset($costcenter)) ? $costcenter['CompanyId'] : ''; ?>">
        <div class="col-lg-12">
            <h1 class="text-center">Work Progress</h1>
        </div>
        <div class="col-lg-12">
            <div class="col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-6 col-sm-offset-0 col-xs-12 col-xs-offset-0">
                <div class="panel-box">
                    <ul>
                        <li>
                            <label>Cost Centre</label>
                            <span><?php echo (isset($costcenter)) ? $costcenter['CostCentreName'] : ''; ?></span>
                        </li>
                        <li>
                            <label>Contractor</label>
                            <span><?php echo (isset($vendor)) ? $vendor['VendorName'] : ''; ?></span>
                        </li>
                        <li>
                            <label>Work Order No</label>
                            <span><?php echo (isset($workorder)) ? $workorder['WONo'] : ''; ?></span>
                        </li>
                        <li>
                            <label>Work Type</label>
                            <span><?php echo (isset($WorkTypeName)) ? $WorkTypeName : ''; ?></span>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-6 col-sm-offset-0 col-xs-12 col-xs-offset-0">
                <div class="panel-box box2th">
                    <ul>
                        <li>
                            <label>WPE Date</label>
                        <span>
                        <input type="text" placeholder="dd-mm-yyyy" class="date_picker" name="DPEDate" id="DPEDate"
                               value="<?php echo (isset($dperegister)) ? $dperegister['DPEDate'] : date('d-m-Y'); ?>"/>
                        </span></li>
                        <li>
                            <label>Ref Date</label>
                        <span>
                        <input type="text" placeholder="dd-mm-yyyy" class="date_picker" name="RefDate" id="RefDate"
                               value="<?php echo (isset($dperegister)) ? $dperegister['RefDate'] : date('d-m-Y'); ?>"/>
                        </span></li>
                        <li>
                            <label>From Date</label>
                        <span>
                        <input type="text" placeholder="dd-mm-yyyy" class="date_picker" name="FromDate" id="FromDate"
                               value="<?php echo (isset($dperegister)) ? $dperegister['FDate'] : date('d-m-Y'); ?>"/>
                        </span></li>
                        <li>
                            <label>To Date</label>
                        <span>
                        <input type="text" placeholder="dd-mm-yyyy" class="date_picker" name="ToDate" id="ToDate"
                               value="<?php echo (isset($dperegister)) ? $dperegister['TDate'] : date('d-m-Y'); ?>"/>
                        </span></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-6 col-sm-offset-0 col-xs-12 col-xs-offset-0">
                <div class="panel-box box3th">
                    <ul>
                        <li>
                            <label>WPE No</label>
                        <span><input type="text" placeholder="xxxxx" id="DPENo" name="DPENo" value="<?php echo (!isset($dperegister) && $genType) ? trim($woNo) : ''; echo (isset($dperegister)) ? trim($dperegister['DPENo']) : '';?>" <?php echo (isset($dperegister) || $genType) ? 'readonly': ''; ?>/></span>
                        </span>
                        </li>
                        <li>
                            <label>CC WPE No</label>
                            <span><input type="text" placeholder="xxxxx" id="CCDPENo" name="CCDPENo" value="<?php echo (isset($dperegister)) ? $dperegister['CCDPENo'] : '';?>"/></span>
                        </span>
                        </li>
                        <li>
                            <label>Comp WPE No</label>
                        <span>
                        <input type="text"  placeholder="xxxxx" id="CompDPENo" name="CompDPENo" value="<?php echo (isset($dperegister)) ? $dperegister['CompDPENo'] : '';?>"/>
                        </span>
                        </li>
                        <li>
                            <label>Ref No</label>
                            <span>
                                <input type="text"  placeholder="xxxxx" id="RefNo" name="RefNo" value="<?php echo (isset($dperegister)) ? $dperegister['RefNo'] : '';?>"/>
                            </span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-lg-12 clear top-20">
            <div id="accordion" class="panel-group">
                <!-------------------------------Works Executed------------------------------->
                <div class="panel panel-info">
                    <div data-target="#collapseOne" data-parent="#accordion" data-toggle="collapse"
                         class="panel-heading collapsed panel_heads" id="panelheading-1">
                        <h4 class="panel-title accordion-toggle defa_panels">Works Executed</h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapseOne" style="height: 0px;">
                        <div class="panel-body bgcolr">
                            <div class="col-lg-12">
                                <div class="table-responsive top-30">
                                    <table class="table" style=" margin-bottom:0px;" id="workorderTable">
                                        <thead>
                                        <tr>
                                            <th>Description</th>
                                            <th>Unit</th>
                                            <th class="text-right">Qty</th>
                                            <th>&nbsp; </th>
                                        </tr>
                                        </thead>
                                        <tbody class="main"></tbody>
                                    </table>
                                    <input type="hidden" name="rowid" id="rowid" value="0"/>
                                    <input type="hidden" name="deleteids" id="deleteids" value="0"/>
                                </div>
                                <div
                                    class="cont_bt col-lg-5 col-lg-offset-7 col-md-9 col-md-offset-3 col-sm-7 col-sm-offset-5 col-xs-7 col-xs-offset-5">
                                    <ul>
                                        <li><a href="javascript:nextAccordian(2)">Continue &nbsp;<i class="fa fa-chevron-circle-right"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-------------------------------Works Executed end------------------------------->
                <!-------------------------------Labour Strength------------------------------->
                <div class="panel panel-info">
                    <div data-target="#collapseTwo" data-parent="#accordion" data-toggle="collapse"
                         class="panel-heading collapsed panel_heads" id="panelheading-2">
                        <h4 class="panel-title accordion-toggle defa_panels">Labour Strength</h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapseTwo" style="height: 0px;">
                        <div class="panel-body bgcolr">
                            <!----Terms and Condition detalis ---->

                            <div class="col-lg-12">
                                <div class="table-responsive top-30">
                                    <table class="table" style=" margin-bottom:0px;">
                                        <thead>
                                        <tr>
                                            <th>Labour Type Name</th>
                                            <th>Unit</th>
                                            <th>Theoritical</th>
                                            <th>Actual</th>
                                            <th>Variation %</th>
                                            <th>&nbsp;</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td width="10%"><input class="parent_text" type="text"/></td>
                                            <td width="5%"><input class="parent_text" type="text"/></td>
                                            <td width="10%"><input class="parent_text" type="text" readonly /></td>
                                            <td width="10%"><input class="parent_text" type="text" readonly /></td>
                                            <td width="5%"><input class="parent_text" type="text" readonly /></td>
                                            <td width="4%" align="center" class="action_btns_td">
                                                <ul class="action_btns">
                                                    <li><a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top"
                                                                       data-original-title="Delete"></i> </a></li>
                                                </ul>
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div
                                    class="cont_bt col-lg-5 col-lg-offset-7 col-md-9 col-md-offset-3 col-sm-7 col-sm-offset-5 col-xs-7 col-xs-offset-5">
                                    <ul>
                                        <li><a href="javascript:nextAccordian(3)">Continue &nbsp;<i
                                                    class="fa fa-chevron-circle-right"></i></a></li>
                                    </ul>
                                </div>
                            </div>

                            <!----Terms and Condition detalis---->
                        </div>
                    </div>
                </div>

                <!-------------------------------Labour Strength------------------------------->
                <!-------------------------------Material Issue------------------------------->
                <div class="panel panel-info">
                    <div data-target="#collapsethree" data-parent="#accordion" data-toggle="collapse"
                         class="panel-heading collapsed panel_heads" id="panelheading-3">
                        <h4 class="panel-title accordion-toggle defa_panels">Material Issue</h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapsethree" style="height: 0px;">
                        <div class="panel-body bgcolr">
                            <div class="col-lg-12">
                                <div class="table-responsive top-30">
                                    <table class="table" style=" margin-bottom:0px;">
                                        <thead>
                                        <tr>
                                            <th>Material Name</th>
                                            <th>Unit</th>
                                            <th>Theoritical</th>
                                            <th>Actual</th>
                                            <th>Variation %</th>
                                            <th>&nbsp;</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td width="10%"><input class="parent_text" type="text"/></td>
                                            <td width="5%"><input class="parent_text" type="text"/></td>
                                            <td width="10%"><input class="parent_text" type="text" readonly /></td>
                                            <td width="10%"><input class="parent_text" type="text" readonly /></td>
                                            <td width="5%"><input class="parent_text" type="text" readonly /></td>
                                            <td width="4%" align="center" class="action_btns_td">
                                                <ul class="action_btns">
                                                    <li><a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top"
                                                                       data-original-title="Delete"></i> </a></li>
                                                </ul>
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div
                                    class="cont_bt col-lg-5 col-lg-offset-7 col-md-9 col-md-offset-3 col-sm-7 col-sm-offset-5 col-xs-7 col-xs-offset-5">
                                    <ul>
                                        <li><a href="javascript:nextAccordian(4)">Continue &nbsp;<i
                                                    class="fa fa-chevron-circle-right"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-------------------------------Material Issue------------------------------->
                <!-------------------------------Machinery Outturn------------------------------->
                <div class="panel panel-info">
                    <div data-target="#collapsefour" data-parent="#accordion" data-toggle="collapse"
                         class="panel-heading collapsed panel_heads" id="panelheading-4">
                        <h4 class="panel-title accordion-toggle defa_panels">Machinery Outturn</h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapsefour" style="height: 0px;">
                        <div class="panel-body bgcolr">
                            <div class="col-lg-12">
                                <div class="table-responsive top-30">
                                    <table class="table" style=" margin-bottom:0px;">
                                        <thead>
                                        <tr>
                                            <th>Machinery Outturn</th>
                                            <th>Unit</th>
                                            <th>Theoritical</th>
                                            <th>Actual</th>
                                            <th>Variation %</th>
                                            <th>&nbsp;</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td width="10%"><input class="parent_text" type="text"/></td>
                                            <td width="5%"><input class="parent_text" type="text"/></td>
                                            <td width="10%"><input class="parent_text" type="text" readonly /></td>
                                            <td width="10%"><input class="parent_text" type="text" readonly /></td>
                                            <td width="5%"><input class="parent_text" type="text" readonly /></td>
                                            <td width="4%" align="center" class="action_btns_td">
                                                <ul class="action_btns">
                                                    <li><a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i> </a></li>
                                                </ul>
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div
                                    class="cont_bt col-lg-5 col-lg-offset-7 col-md-9 col-md-offset-3 col-sm-7 col-sm-offset-5 col-xs-7 col-xs-offset-5">
                                    <ul>
                                        <li><a href="javascript:nextAccordian(5)">Continue &nbsp;<i class="fa fa-chevron-circle-right"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-------------------------------Machinery Outturn------------------------------->
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0 lab-natt" style="background:none;margin:0 0 10px;padding:0;">
            <div class="form-group">
                <label class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0 col-xs-12" style="text-align:right;">Narration</label>
                <textarea class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0 col-xs-12"></textarea>
            </div>
        </div>
        <div class="clearfix"></div>
        <!--table end-->
    </form>

    <!--Handson Table-->
    <div class="col-lg-12" id="HandsonWrapper">
        <div class="md-popup">
            <div id="HandsonTableModal">
                <h1>Measurement Sheet</h1>
                <div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0 excel-tbs" style="padding-left:0px !important;">
                    <div class="col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-4 col-sm-offset-0">
                        <div class="form-group">
                            <select id="ExcelTemplate" onChange="getExcelTemplate(this);"  style="width:100%;" class="form-control single_dropdown lbl_move hei-43" data-size="5" label="Chooose a Template">
                                <option></option>
                                <?php if($exceltemplates):
                                    foreach($exceltemplates as $template):?>
                                        <option value="<?php echo $template['TemplateId']; ?>"><?php echo $template['TemplateName']; ?></option>
                                    <?php endforeach; endif; ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-4 col-sm-offset-0">
                        <div class="form-group">
                            <select name="columns[]" id="totalcolumns"  style="width:100%;" class="form-control single_dropdown lbl_move sel-mul" data-size="5" label="Choose Column(s)" multiple onchange="summationColumns(true);">
                                <option></option>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-4 col-sm-offset-0">
                        <div class="form-group  remove-bt">
                            <a onClick="removeMSheet(); return false;">Remove Measurement Sheet</a>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0">
                    <div class="tabs-content" style="margin-top:20px;">
                        <div id="HandsonTableWrapper" class="hot handsontable"></div>
                    </div>
                </div>
            </div>
            <div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0">
                <div class="btn-group toal-disgr" data-toggle="buttons" id="summationColumnsWrapper"></div>
            </div>
            <div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0">
                <div class="HandsonModalBtns">
                    <button type="button" class="md_cance" onClick="return hideHandsonWrapper()">Cancel</button>
                    <button type="button" class="md_ok" onClick="return updateMSheet()">Update</button>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
<div class="col-lg-12 savebtn_area">
    <ul>
        <?php
        $show = 1;
        if(isset($dperegister) && $dperegister['Approve']=='Y') { $show = 0; }
        if($show == 1) {
        ?>
        <li class="dropdown save_btn float_r"><a onclick="submitForm()" data-toggle="tooltip" class="ripple" title="Submit">Submit</a>
        <?php } ?>
        <li class="cancel_btn float_r"><a href="<?php echo $this->basePath();?>/wpm/workprogress/<?php echo (isset($dperegister)) ? 'register' : 'index'; ?>" data-toggle="tooltip" class="ripple" title="Go back!">Back</a></li>
    </ul>
</div>
<script type="text/template" id="resource-template">
    <tr>
        <td width="30%">
            <input class="parent_text resourceSuggest" data-toggle="popover" type="text" name="desc__" id="desc__" onfocus="checkResourceUsed(this);" data-content="" />
            <input type="hidden" name="descid__" id="descid__"/>
            <input type="hidden" name="DPETransId__" id="DPETransId__" value="0"/>
            <input type="hidden" name="UpdateRow__" id="UpdateRow__" value="0"/>
        </td>
        <td width="15%">
            <input class="parent_text border-none" type="text" name="unitname__" id="unitname__" readonly/>
            <input type="hidden" name="unitid__" id="unitid__"/>
            <input type="hidden" name="ratetype__" id="ratetype__"/>
            <input type="hidden" name="rate__" id="rate__"/>
            <input type="hidden" name="amount__" id="amount__"/>
        </td>
        <td width="8%">
            <input class="parent_text border-none text-right <?php if($wbsReq != '' && $wbsReq == 1) { ?>mainTr<?php } ?>" type="text" name="qty__" id="qty__" <?php if($wbsReq != '' && $wbsReq == 1) { ?>readonly<?php } else { ?>onchange="calcQuantityWOWbs(this);" onkeypress="return isDecimal(event,this);" onfocus="return hideShow(this,'s','wo');" onblur="return hideShow(this,'h','wo');"<?php } ?> autocomplete="off" />
            <?php if($wbsReq != '' && $wbsReq == 1) { ?>
            <?php } else { ?>
                <div id="ewbqty__" style="position:relative;display:none;">
                    <div class="top-tip top-addtip">
                        <span>Estimate Qty : <i id="estimateqty__"></i></span>
                        <span>Work Order Qty : <i id="workorderqty__"></i></span>
                        <span>Work Progress Qty : <i id="wpqty__"></i></span>
                        <span>Total Billed Qty : <i id="totbilledqty__"></i></span>
                    </div>
                </div>
            <?php } ?>
        </td>
        <td width="5%" align="center" class="action_btns_td">
            <ul class="action_btns">
                <li> <a onclick="deleteRow(this, event);"  id="deleteTr__" style="display:none;"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i> </a> </li>
                <li> <a href="#" class="mainTr" id="expandTr__" style="display:none;"> <i class="fa fa-chevron-circle-down" data-toggle="tooltip" data-placement="left" data-original-title="Add lines" ></i></a> </li>
            </ul>
        </td>
    </tr>
    <tr style="display:none;" class="subTr">
        <td colspan="9" style="padding:0px !important; ">
            <div class="subDiv" style="display:none;">
                <div class="col-lg-12 col-lg-offset-0 rdbt" style="margin-top:5px;"></div>
                <div class="col-lg-12">
                    <div class="table-responsive topsp">
                        <table class="table" style="margin-bottom:0px;" id="iowTable__">
                            <thead>
                            <tr>
                                <th class="worktype-activity">Agt No</th>
                                <th class="worktype-activity">Specification</th>
                                <th>WBS</th>
                                <th class="text-right">Qty</th>
                            </tr>
                            </thead>
                            <tbody class="main"></tbody>
                            <input type="hidden" name="iow___rowid" id="iow___rowid" value="0"/>
                        </table>
                    </div>
                </div>
            </div>
        </td>
    </tr>
</script>
<script type="text/template" id="iow-template">
    <tr>
        <input type="hidden" name="iow___iowid_0" id="iow___iowid_0"/>
        <input type="hidden" name="iow___wbsid_0" id="iow___wbsid_0"/>
        <input type="hidden" name="iow___DPEIOWTransId_0" id="iow___DPEIOWTransId_0" value="0"/>
        <input type="hidden" name="iow___UpdateRow_0" id="iow___UpdateRow_0" value="0"/>
        <td width="10%" class="worktype-activity"><input class="parent_text border-none" type="text" name="iow___agtno_0" id="iow___agtno_0" readonly/></td>
        <td width="13%" class="worktype-activity"><input class="parent_text border-none" type="text" name="iow___spec_0" id="iow___spec_0" readonly/></td>
        <td width="10%"><input class="parent_text border-none" type="text" name="iow___wbs_0" id="iow___wbs_0" readonly/></td>
        <td width="5%">
            <input class="parent_text text-right" type="text" name="iow___qty_0" id="iow___qty_0" onkeypress="return isDecimal(event,this)" onchange="calcQuantity(this);" onfocus="showHandsonTableModal('1', this);" onblur="return hideShow(this,'h','w');" autocomplete="off" />
            <div id="iow___ewbqty_0" style="position:relative;display:none;">
                <div class="top-tip top-addtip">
                    <span>Estimate Qty : <i name="iow___estimateqty_0" id="iow___estimateqty_0"></i></span>
                    <span>Work Order Qty : <i name="iow___workorderqty_0" id="iow___workorderqty_0"></i></span>
                    <span>Work Progress Qty : <i name="iow___wpqty_0" id="iow___wpqty_0"></i></span>
                    <span>Total Billed Qty : <i name="iow___totbilledqty_0" id="iow___totbilledqty_0"></i></span>
                </div>
            </div>
        </td>
        <input type="hidden" name="iow___Measurement_0" id="iow___Measurement_0"/>
        <input type="hidden" name="iow___CellName_0" id="iow___CellName_0"/>
        <input type="hidden" name="iow___SelectedColumns_0" id="iow___SelectedColumns_0"/>
    </tr>
    <!--tr style="display:none;" class="subTr">
        <td colspan="4">
            <ul class="total-qty">
                <li>
                    <label>Estimate Qty : </label>
                    <input class="parent_text bold-text-clr text-right" type="text" name="iow___estimateqty_0" id="iow___estimateqty_0" value="" readonly/>
                </li>
                <li>
                    <label>Work Order Qty : </label>
                    <input class="parent_text bold-text-clr text-right" type="text" name="iow___workorderqty_0" id="iow___workorderqty_0" value="" readonly/>
                </li>
                <li>
                    <label>Total Billed Qty : </label>
                    <input class="parent_text bold-text-clr text-right" type="text" name="iow___totbilledqty_0" id="iow___totbilledqty_0" value="" readonly/>
                </li>
            </ul>
        </td>
    </tr-->
</script>
<script id="turnkey-table-template" type="text/template">
    <thead>
    <tr>
        <th>Description</th>
        <th class="text-right">Cumulative %</th>
        <th class="text-right">Previous %</th>
        <th class="text-right">Current %</th>
        <th>&nbsp; </th>
    </tr>
    </thead>
    <tbody class="main"></tbody>
    <tbody class="total">
    <tr>
        <td colspan="2">&nbsp;</td>
        <td align="right" class="rate_pri">Total</td>
        <td width="10%"><input class="parent_text border-none text-right bold-text-clr" type="text" name="total" id="total" readonly/></td>
        <td>&nbsp;</td>
    </tr>
    </tbody>
</script>
<script id="turnkey-template" type="text/template">
    <tr>
        <td width="20%">
            <input class="parent_text wbsSuggest" data-toggle="popover" type="text" name="desc__" id="desc__" onfocus="checkWBSUsed(this);" data-content=""/>
            <input type="hidden" name="descid__" id="descid__"/>
            <input type="hidden" name="wbsid__" id="wbsid__"/>
            <input type="hidden" name="DPETransId__" id="DPETransId__" value="0"/>
            <input type="hidden" name="UpdateRow__" id="UpdateRow__" value="0"/>
        </td>
        <td width="15%"><input class="parent_text border-none text-right" type="text" name="cumpercent__" id="cumpercent__" readonly/></td>
        <td width="15%"><input class="parent_text border-none text-right" type="text" name="prevpercent__" id="prevpercent__" readonly/></td>
        <td width="15%"><input class="parent_text border-none text-right" type="text" name="curpercent__" id="curpercent__" readonly/></td>
        <td width="10%" align="center" class="action_btns_td">
            <ul class="action_btns">
                <li> <a onclick="deleteRow(this, event);"  id="deleteTr__" style="display:none;"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i> </a> </li>
                <li> <a href="#" class="mainTr" id="expandTr__" style="display:none;"> <i class="fa fa-chevron-circle-down" data-toggle="tooltip" data-placement="left" data-original-title="Add lines" ></i></a> </li>
            </ul>
        </td>
    </tr>
    <tr style="display:none;" class="subTr">
        <td colspan="9" style="padding:0px !important; "><div class="subDiv" style="display:none;">
                <div class="col-lg-12 col-lg-offset-0 rdbt" style="margin-top:5px;"> </div>
                <div class="col-lg-12">
                    <div class="table-responsive topsp">
                        <table class="table" id="iowTable__">
                            <thead>
                            <tr>
                                <th>SlNo.</th>
                                <th>Specification</th>
                                <th>Unit</th>
                                <th>BOQ Qty</th>
                                <th>BOQ Rate</th>
                                <th>BOQ Amount</th>
                                <th>Variance</th>
                                <th>Qty</th>
                                <th class="text-right">Rate</th>
                                <th class="text-right">Amount</th>
                            </tr>
                            </thead>
                            <tbody class="main">
							</tbody>
							<tbody class="total">
								<tr>
									<td class="tbl_input_td txt_center" colspan="2">
										<strong>WO Amt</strong>
									</td>
									<td class="tbl_input_td txt_center">
										<strong>Current Amt</strong>
									</td>
									<td class="tbl_input_td txt_center" colspan="2">
										<strong>% as Per Qty</strong>
									</td>
									<td class="tbl_input_td txt_center" colspan="2">
										<strong>Current %</strong>
									</td>
									<td class="tbl_input_td txt_center">
										<strong>Previous %</strong>
									</td>
									<td class="tbl_input_td txt_center" colspan="2">
										<strong>Cumulative %</strong>
									</td>
								</tr>
								<tr>
									<td class="tbl_input_td" colspan="2">
										<input class="tbl_input border-none text-right" type="text" name="iowWOAmtTotal__" id="iowWOAmtTotal__" readonly/>
									</td>
									<td class="tbl_input_td" >
										<input class="tbl_input border-none text-right" type="text" name="iowCurAmtTotal__" id="iowCurAmtTotal__" readonly/>
									</td>
									<td class="tbl_input_td" colspan="2">
										<input class="tbl_input border-none text-right" type="text" name=iowPercentQtyTotal__"" id="iowPercentQtyTotal__" readonly/>
									</td>
									<td class="tbl_input_td" colspan="2">
										<input class="tbl_input border-none text-right" type="text" name="iowCurPercentTotal__" id="iowCurPercentTotal__" readonly/>
									</td>
									<td class="tbl_input_td">
										<input class="tbl_input border-none text-right" type="text" name="iowPrevPercentTotal__" id="iowPrevPercentTotal__" readonly/>
									</td>
									<td class="tbl_input_td"  colspan="2">
										<input class="tbl_input border-none text-right" type="text" name="iowCumPercentTotal__" id="iowCumPercentTotal__" readonly/>
									</td>
								</tr>
							</tbody>
                            <input type="hidden" name="iow___rowid" id="iow___rowid" value="0"/>
                        </table>
                    </div>
                </div>
            </div>
        </td>
    </tr>
</script>
<script id="turnkey-iow-template" type="text/template">
    <tr>
        <input type="hidden" name="iow___iowid_0" id="iow___iowid_0"/>
        <input type="hidden" name="iow___unitid_0" id="iow___unitid_0"/>
        <input type="hidden" name="iow___DPEIOWTransId_0" id="iow___DPEIOWTransId_0" value="0"/>
        <input type="hidden" name="iow___UpdateRow_0" id="iow___UpdateRow_0" value="0"/>
        <td width="3%">{{serialno}}</td>
        <td width="20%">{{spec}}</td>
        <td width="8%">{{unit}}</td>
        <td width="8%"><input class="parent_text border-none text-right" type="text" name="iow___boqqty_0" id="iow___boqqty_0" readonly/></td>
        <td width="12%"><input class="parent_text border-none text-right" type="text" name="iow___boqrate_0" id="iow___boqrate_0" readonly/></td>
        <td width="12%"><input class="parent_text border-none text-right" type="text" name="iow___boqamount_0" id="iow___boqamount_0" readonly/></td>
        <td width="8%"><input class="parent_text border-none text-right" type="text" name="iow___variance_0" id="iow___variance_0" readonly/></td>
        <td width="8%"><input class="parent_text text-right" type="text" name="iow___qty_0" id="iow___qty_0" onblur="return FormatNum(this, 3, true)" onkeypress="return isDecimal(event,this)" maxlength="18" onchange="calcTurnKey(this);" autocomplete="off" /></td>
        <td width="15%"><input class="parent_text border-none text-right" type="text" name="iow___rate_0" id="iow___rate_0" readonly/></td>
        <td width="20%"><input class="parent_text border-none text-right" type="text" name="iow___amount_0" id="iow___amount_0" readonly/></td>
    </tr>
</script>
<script type="text/javascript">
bindPopOver();
var arr_requestResources = <?php echo (isset($arr_requestResources)) ? json_encode($arr_requestResources) : '[]';?>;
var arr_resource_iows = <?php echo (isset($arr_resource_iows)) ? json_encode($arr_resource_iows) : '[]';?>;

var arr_resources = <?php echo (isset($arr_resources)) ? json_encode($arr_resources) : '[]';?>;
var tmp_arr_resources = arr_resources;

var WorkType = $('#WorkType').val();

var $mSheetConfirmToolTipTemplate = '<div class="on-focus clearfix" style="position:relative;" id="MSheetConfirmationToolTip">'
    + '<div class="top-tip">'
    + '<span>Do You Need Measurement Sheet?</span>'
    + '<a href="#" onclick="setMSheet(); return false;" class="colgreen"><i class="fa fa-check"></i> Yes</a>'
    + '<a href="#" onclick="removeTooltip(); return false;" class="colred"><i class="fa fa-times"></i> No</a>'
    + '</div>'
    +'</div>';
var $HandsonWrapper = $('#HandsonWrapper'),
    $formWrapper = $('#formWrapper');

$(function () {
    var $rowid = $('#rowid');
    var rowid = 0;

    if(WorkType == 'turn-key') {
        $('#workorderTable').html($('#turnkey-table-template').html()); // change main table template

        var template = $('#turnkey-template').html();
        var iowtemplate = $('#turnkey-iow-template').html();
        var $tbody = $('#workorderTable').find('> tbody.main');
        if (arr_requestResources.length != 0) {
            $.each(arr_requestResources, function (i, o) {
                rowid += 1;
                $tbody.append(template.replace(/__/g, '_' + rowid));
                $('#desc_' + rowid).val(o.Desc).addClass('border-none').prop('disabled', true);
                $('#desc_' + rowid).attr('data-content', o.Desc);
                $('#descid_' + rowid).val(o.DescId);
                $('#wbsid_' + rowid).val(o.WBSId);
                $('#iowWOAmtTotal_'+rowid).val(sanitizeNumber(o.WOAmount,2,true));
                $('#expandTr_' + rowid).show();
                $('#deleteTr_' + rowid).show();

                if (typeof o.DPETurnKeyTransId !== 'undefined') {
                    $('#DPETransId_' + rowid).val(o.DPETurnKeyTransId);
                }

                $.each(arr_resource_iows, function (j, l) {
                    if ((typeof o.DPETurnKeyTransId == 'undefined' && l.WOTurnKeyTransId != o.DescId)
                        || (typeof o.DPETurnKeyTransId !== 'undefined' && o.DPETurnKeyTransId != l.DPETurnKeyTransId)) {
                        return;
                    }

                    var $iowrowid = $('#iow_' + rowid + '_rowid'),
                        iowrowid = parseInt($iowrowid.val()) + 1;
                    $('#iowTable_' + rowid).find('> tbody.main').append(iowtemplate.replace(/__/g, '_' + rowid).replace(/_0/g, '_' + iowrowid)
                        .replace(/\{\{serialno\}\}/g, l.RefSerialNo)
                        .replace(/\{\{spec\}\}/g, l.Specification)
                        .replace(/\{\{unit\}\}/g, l.UnitName));
                    $('#iow_'+rowid+'_boqrate_'+iowrowid).val(sanitizeNumber(l.BOQRate,2,true));
                    $('#iow_'+rowid+'_boqqty_'+iowrowid).val(sanitizeNumber(l.BOQQty,2,true));
                    $('#iow_'+rowid+'_boqamount_'+iowrowid).val(sanitizeNumber(l.BOQAmount,2,true));
                    $('#iow_'+rowid+'_variance_'+iowrowid).val(sanitizeNumber(o.Variance,2,true));
                    $('#iow_'+rowid+'_rate_'+iowrowid).val(sanitizeNumber( ((l.Amount * o.Variance) / l.Qty) ,2,true));
                    $('#iow_'+rowid+'_unitid_'+iowrowid).val(l.UnitId);
                    $('#iow_'+rowid+'_iowid_'+iowrowid).val(l.ProjectIOWId);
                    $iowrowid.val(iowrowid);

                    if (typeof l.DPETurnKeyIOWTransId !== 'undefined') {
                        $('#iow_' + rowid + '_DPEIOWTransId_' + iowrowid).val(l.DPETurnKeyIOWTransId);
                        $('#iow_' + rowid + '_variance_' + iowrowid).val(sanitizeNumber(l.Variance,3,true));
                        $('#iow_' + rowid + '_rate_' + iowrowid).val(sanitizeNumber(l.Rate,2,true));
                        $('#iow_' + rowid + '_amount_' + iowrowid).val(sanitizeNumber(l.Amount,2,true));
                        $('#iow_' + rowid + '_qty_' + iowrowid).val(sanitizeNumber(l.Qty,3,true));
                    }
                });
            });
        }
        rowid += 1;
        $tbody.append(template.replace(/__/g, '_' + rowid));
        $rowid.val(rowid);
        bindTurnKeyDescAutocomplete();
    } else {
        var template = $('#resource-template').html();
        var iowtemplate = $('#iow-template').html();
        var $tbody = $('#workorderTable').find('> tbody.main');
        if (arr_requestResources.length != 0) {
            $.each(arr_requestResources, function (i, o) {
                rowid += 1;
                $tbody.append(template.replace(/__/g, '_' + rowid));
                $('#desc_' + rowid).val(o.Desc).addClass('border-none').prop('disabled', true);
                $('#desc_' + rowid).attr('data-content', o.Desc);
                $('#descid_' + rowid).val(o.DescId);
                //$('#wbsid_' + rowid).val(o.WBSId);
                $('#unitname_' + rowid).val(o.UnitName);
                $('#unitid_' + rowid).val(o.UnitId);
                $('#qty_' + rowid).val(sanitizeNumber(o.Qty, 3));
                $('#rate_' + rowid).val(sanitizeNumber(o.Rate, 2));

                if($('#wbsReq').val() != '' && $('#wbsReq').val() == 1) {
                    $('#expandTr_' + rowid).show();
                } else {
                    $('#estimateqty_' + rowid).html(parseFloatVal(o.EstQty));
                    bindWithoutWbs(rowid,2);
                }
                $('#deleteTr_' + rowid).show();

                if (WorkType == 'activity') {
                    $('#ratetype_' + rowid).val(o.RateType);
                }

                if (typeof o.DPETransId !== 'undefined') {
                    $('#DPETransId_' + rowid).val(o.DPETransId);
                    $('#amount_' + rowid).val(sanitizeNumber(o.Amount, 2));
                }

                if($('#wbsReq').val() != '' && $('#wbsReq').val() == 1) {
                    $.each(arr_resource_iows, function (j, l) {
                        if ((typeof o.DPETransId == 'undefined' && l.ResourceId != o.DescId && WorkType == 'activity')
                            || (typeof o.DPETransId == 'undefined' && l.ProjectIOWId != o.DescId && WorkType == 'iow')
                            || (typeof o.DPETransId !== 'undefined' && o.DPETransId != l.DPETransId)) {
                            return;
                        }

                        var estQty = 0;
                        var iowrowid = parseInt($('#iow_' + rowid + '_rowid').val()) + 1;
                        $('#iowTable_' + rowid).find('> tbody.main').append(iowtemplate.replace(/__/g, '_' + rowid).replace(/_0/g, '_' + iowrowid));
                        $('#iow_' + rowid + '_rowid').val(iowrowid);

                        $('#iow_' + rowid + '_wbsid_' + iowrowid).val(l.WBSId);
                        $('#iow_' + rowid + '_wbs_' + iowrowid).val(l.ParentText + '->' + l.WBSName);
                        //$('#iow_' + rowid + '_unitname_' + iowrowid).val(l.UnitName);

                        if (WorkType == 'activity') {
                            $('#iow_' + rowid + '_iowid_' + iowrowid).val(l.ProjectIOWId);
                            $('#iow_' + rowid + '_agtno_' + iowrowid).val(l.RefSerialNo);
                            $('#iow_' + rowid + '_spec_' + iowrowid).val(l.Specification);

                            estQty = ((l.Qty / l.bQty) * l.cQty);
                            $('#iow_' + rowid + '_estimateqty_' + iowrowid).html(parseFloatVal(estQty));
                        } else if (WorkType == 'iow') {
                            $('.worktype-activity').remove();

                            $('#iow_' + rowid + '_estimateqty_' + iowrowid).html(parseFloatVal(l.EstQty));
                        }

                        if (typeof l.DPEIOWTransId !== 'undefined') {
                            $('#iow_' + rowid + '_DPEIOWTransId_' + iowrowid).val(l.DPEIOWTransId);
                            $('#iow_' + rowid + '_Measurement_' + iowrowid).val(l.Measurement);
                            $('#iow_' + rowid + '_CellName_' + iowrowid).val(l.CellName);
                            $('#iow_' + rowid + '_SelectedColumns_' + iowrowid).val(l.SelectedColumns);
                            $('#iow_' + rowid + '_qty_' + iowrowid).val(sanitizeNumber(l.Qty, 3));//.trigger('change');
                        }

                        var woeQty = 0;
                        var wbeQty = 0;
                        var wpeQty = 0;
                        $.ajax({
                            url: getBaseURL() + 'wpm/workprogress/entry',
                            type: "post",
                            data: {
                                'ResourceId': o.DescId,
                                'ccId': $('#costCentreId').val(),
                                'IOWId': l.ProjectIOWId,
                                'WBSId': l.WBSId,
                                'Type': 'getwoqty',
                                'WOType': WorkType,
                                'woRegId': $('#WORegisterId').val()
                            },
                            async: false,
                            success: function (data, textStatus, jqXHR) {
                                if (jqXHR.status == 200) {
                                    data = JSON.parse(data);
                                    woeQty = data.WOQty;
                                    wbeQty = data.WBQty;
                                    wpeQty = data.WPQty;
                                    if (woeQty == null) {
                                        woeQty = 0;
                                    }
                                    if (wbeQty == null) {
                                        wbeQty = 0;
                                    }
                                    if (wpeQty == null) {
                                        wpeQty = 0;
                                    }
                                    $('#iow_' + rowid + '_workorderqty_' + iowrowid).html(parseFloatVal(woeQty));
                                    $('#iow_' + rowid + '_totbilledqty_' + iowrowid).html(parseFloatVal(wbeQty));
                                    $('#iow_' + rowid + '_wpqty_' + iowrowid).html(parseFloatVal(wpeQty));
                                }
                            }, error: function (jqXHR, textStatus, errorThrown) {
                            }
                        });
                    });
                }
            });
        }
        rowid += 1;
        $tbody.append(template.replace(/__/g, '_' + rowid));
        $rowid.val(rowid);
        bindDescAutocomplete();
        bindPopOver();
    }

    $(".content_wrapper").on('click','.mainTr', function (e) {
        e.preventDefault();
        if (!$(this).closest("tr").next(".subTr").is(":visible")) {
            $(this).closest("tr").next(".subTr").show();
            $(this).closest("tr").next(".subTr").find(".subDiv").slideDown("slow");
            $(this).find("i").addClass("tform");
        } else {
            $(this).closest("tr").next(".subTr").find(".subDiv").slideUp("slow");
            $(this).closest("tr").next(".subTr").slideUp("slow");
            $(this).find("i").removeClass("tform");
        }
    });

    nextAccordian(1);
});


function submitForm() {
    if(!validateLength($('#DPEDate')))
        return false;

    if(!validateLength($('#RefDate')))
        return false;

    if(!validateLength($('#FromDate')))
        return false;

    if(!validateLength($('#ToDate')))
        return false;

    if(!validateLength($('#CCDPENo')))
        return false;

    if(!validateLength($('#CompDPENo')))
        return false;

    if(!validateLength($('#RefNo')))
        return false;

    if($('#formWrapper .error').length != 0) {
        alert('Kindly notice the errors!');
        return false;
    }
    $('#formWrapper').submit();
}

function scrTop(divId)
{
    $('html, body').animate({
        scrollTop: divId.offset().top-100
    }, 'slow');
}

function validateLength($input) {
    if($.trim($input.val()).length == 0) {
        showError($input, 'required');
        scrTop($input);
        return false;
    }

    removeError($input);
    return true;
}

function closeMainTr()
{
    var $mainTr = $(".mainTr");
    $.each($mainTr, function () {
        $(this).closest("tr").next(".subTr").find(".subDiv").slideUp("slow");
        $(this).closest("tr").next(".subTr").slideUp("slow");
        $(this).find("i").removeClass("tform");
    });
}

function nextAccordian(id) {
    $('#panelheading-' + id).trigger('click');
}

function bindTurnKeyDescAutocomplete() {
    // bind wbs autocomplete
    $('#workorderTable .wbsSuggest').autocomplete({
        lookup: tmp_arr_resources,
        lookupFilter: function (suggestion, originalQuery, queryLowerCase) {
            if (queryLowerCase == '*') {
                return suggestion.value;
            } else {
                var re = new RegExp($.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
                return re.test(suggestion.value);
            }
        }, onSelect: function (suggestion) {
            if (suggestion) {
                var $this = $(this);
                var rowid = $this[0].id.split('_')[1];
                $this.prop('readonly', true).addClass('border-none');
                $('#descid_' + rowid).val(suggestion.data);
                $('#desc_' + rowid).attr('data-content', suggestion.value);
                $('#wbsid_' + rowid).val(suggestion.WBSId);
                $('#iowWOAmtTotal_' + rowid).val(sanitizeNumber(suggestion.WOAmount,2,true));
                $('#expandTr_' + rowid).show();
                addnewTurnKeyRow();
                // bind iows
                $('.loading_area').show();
                $.ajax({
                    url: getBaseURL() + 'wpm/workprogress/entry',
                    type: "post",
                    data: {'WOTurnKeyTransId': suggestion.data, 'Type': 'getwbsdetails'},
                    async: false,
                    success: function (data, textStatus, jqXHR) {
                        if(jqXHR.status == 200) {
                            data = JSON.parse(data);
                            var iowtemplate = $('#turnkey-iow-template').html();
                            var iowrowid = 0;
                            $.each(data, function (i,l) {
                                iowrowid++;
                                $('#iowTable_' + rowid).find('> tbody.main').append(iowtemplate.replace(/__/g, '_'+rowid)
                                    .replace(/_0/g, '_'+iowrowid)
                                    .replace(/\{\{serialno\}\}/g, l.RefSerialNo)
                                    .replace(/\{\{spec\}\}/g, l.Specification)
                                    .replace(/\{\{unit\}\}/g, l.UnitName));
                                $('#iow_'+rowid+'_boqrate_'+iowrowid).val(sanitizeNumber(l.Rate,2,true));
                                $('#iow_'+rowid+'_boqqty_'+iowrowid).val(sanitizeNumber(l.Qty,2,true));
                                $('#iow_'+rowid+'_boqamount_'+iowrowid).val(sanitizeNumber(l.Amount,2,true));
                                $('#iow_'+rowid+'_variance_'+iowrowid).val(sanitizeNumber(l.Variance,2,true));
                                $('#iow_'+rowid+'_rate_'+iowrowid).val(sanitizeNumber( ((l.Amount * l.Variance) / l.Qty) ,2,true));
                                $('#iow_'+rowid+'_unitid_'+iowrowid).val(l.UnitId);
                                $('#iow_'+rowid+'_iowid_'+iowrowid).val(l.ProjectIOWId);
                            });
                            $('#iow_'+rowid+'_rowid').val(iowrowid);
                        }
                        $('.loading_area').hide();
                    }, error: function (jqXHR, textStatus, errorThrown) {
                        $('.loading_area').hide();
                    }
                });
            }
        }, onSearchStart: function (suggestion) {
            var rowid = $(this)[0].id.split('_')[1];
            $('#unitname_' + rowid).val('');
            $('#rate_' + rowid).val('');
        }, onSearchComplete: function (query, suggestions) {
            if(!suggestions.length) {
                var rowid = $(this)[0].id.split('_')[1];
                $('#unitname_' + rowid).val('');
                $('#rate_' + rowid).val('');
            }
        }
    });
}
function checkWBSUsed(x) {
    closeMainTr();
    var id = $(x)[0].id.split('_')[1];
    var reskeyid = $('input[id*=descid_]');
    tmp_arr_resources = arr_resources;
    tmp_arr_resources = $.grep(arr_resources, function (element, index) {
        var is_selected = true;
        $.each(reskeyid, function (i, obj) {
            var $this = $(this),
                name = $this[0].id;
            var arrname = name.split('_');
            var key1 = arrname[1];
            if (key1 != id) {
                if (element.data == $this.val()) {
                    is_selected = false;
                    return false;
                }
            }
        });
        return is_selected;
    });
    bindTurnKeyDescAutocomplete();
}
function addnewTurnKeyRow(x) {
    var $tr = $(x).closest('tr');
    if ($tr.next('tr:not(.subTr)').length != 0)
        return;

    var $rowid = $('#rowid'),
        rowid = parseInt($rowid.val()),
        $tbody = $('#workorderTable').find('> tbody.main');

    $('#deleteTr_' + rowid).show();
    var count = rowid + 1,
        template = $('#turnkey-template').html();

    template = template.replace(/__/g, '_' + count);
    $tbody.append(template);
    $rowid.val(count);

    bindTurnKeyDescAutocomplete();
}
function calcTurnKey(x) {
    var $x = $(x);
    var ids = $x[0].id.split('_');
    var rowid = ids[1];
    var iowid = ids[3];

    if($('#iow_'+rowid+'_DPEIOWTransId_' + iowid).val() != 0) {
        $('#iow_'+rowid+'_UpdateRow_' + iowid).val(1);
        $('#UpdateRow_'+rowid).val(1);
    }

    var qty = parseFloatVal($('#iow_'+rowid+'_qty_'+iowid).val());
    var rate = parseFloatVal($('#iow_'+rowid+'_rate_'+iowid).val());
    $('#iow_'+rowid+'_amount_'+iowid).val(sanitizeNumber(qty*rate,2,true));

    // calc total amount
    var totalAmt=0;
    $.each($('input[id^=iow_'+rowid+'_amount_'), function (i,o) {
        totalAmt += parseFloatVal($(this).val());
    });

    $('#iowCurAmtTotal_'+rowid).val(sanitizeNumber(totalAmt,0));
    var curPer = totalAmt / parseFloatVal( $('#iowWOAmtTotal_'+rowid).val() ) * 100;
    $('#iowPercentQtyTotal_'+rowid).val(sanitizeNumber(curPer,3,true));
    $('#iowCurPercentTotal_'+rowid).val(sanitizeNumber(curPer,3,true));
    $('#iowCumPercentTotal_'+rowid).val(sanitizeNumber( ( parseFloatVal( $('#iowPrevPercentTotal_'+rowid).val() ) + parseFloatVal( $('#iowCurPercentTotal_'+rowid).val() ) ) ,3,true));
}

function bindDescAutocomplete() {
    // bind resource autocomplete
    $('#workorderTable .resourceSuggest').autocomplete({
        lookup: tmp_arr_resources,
        lookupFilter: function (suggestion, originalQuery, queryLowerCase) {
            if (queryLowerCase == '*') {
                return suggestion.value;
            } else {
                var re = new RegExp($.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
                return re.test(suggestion.value);
            }
        }, onSelect: function (suggestion) {
            if (suggestion) {
                var $this = $(this);
                var rowid = $this[0].id.split('_')[1];
                $this.prop('readonly', true).addClass('border-none');
                $('#descid_' + rowid).val(suggestion.data);
                $('#desc_' + rowid).attr('data-content', suggestion.value);
                $('#unitname_' + rowid).val(suggestion.UnitName);
                $('#ratetype_' + rowid).val(suggestion.RateType);
                $('#rate_' + rowid).val(suggestion.Rate);
                $('#estimateqty_' + rowid).html(parseFloatVal(suggestion.Qty));

                if($('#wbsReq').val() != '' && $('#wbsReq').val() == 1) {
                    $('#expandTr_' + rowid).show();
                    bindResourceIOW($this);
                } else {
                    bindWithoutWbs($this,1);
                }
                addNewResourceRow($this);
                bindPopOver();
            }
        }, onSearchStart: function (suggestion) {
            var rowid = $(this)[0].id.split('_')[1];
            $('#unitname_' + rowid).val('');
            $('#ratetype_' + rowid).val('');
        }, onSearchComplete: function (query, suggestions) {
            if(!suggestions.length) {
                var rowid = $(this)[0].id.split('_')[1];
                $('#unitname_' + rowid).val('');
                $('#ratetype_' + rowid).val('');
            }
        }
    });
}

function addNewResourceRow(x) {
    var $tr = $(x).closest('tr');
    if ($tr.next('tr:not(.subTr)').length != 0)
        return;

    var $rowid = $('#rowid'),
        rowid = parseInt($rowid.val()),
        $tbody = $('#workorderTable').find('> tbody.main');

    $('#deleteTr_' + rowid).show();
    var count = rowid + 1,
        template = $('#resource-template').html();

    template = template.replace(/__/g, '_' + count);
    $tbody.append(template);

    $rowid.val(count);
    bindDescAutocomplete();
    bindPopOver();
}

function deleteRow(x,e) {
    e.preventDefault();
    var $x = $(x),
        key = $x[0].id.split('_')[1];

    if (!confirm('Do you want to Delete?'))
        return false;

    var transid = $('#DPETransId_' + key).val();
    if(transid != 0) {
        $('#deleteids').val($('#deleteids').val() + ',' + transid);
    }

    var $tr = $x.closest('tr');
    $tr.next('.subTr').remove();
    $tr.remove();

    bindDescAutocomplete();
    return false;
}

function checkResourceUsed(x) {
    closeMainTr();
    var id = $(x)[0].id.split('_')[1];
    var reskeyid = $('input[id*=descid_]');
    tmp_arr_resources = arr_resources;
    tmp_arr_resources = $.grep(arr_resources, function (element, index) {
        var is_selected = true;
        $.each(reskeyid, function (i, obj) {
            var $this = $(this),
                name = $this[0].id;
            var arrname = name.split('_');
            var key1 = arrname[1];
            if (key1 != id) {
                if (element.data == $this.val()) {
                    is_selected = false;
                    return false;
                }
            }
        });
        return is_selected;
    });
    bindDescAutocomplete();
}

function calcQuantity(x) {
    var $x = $(x);
    var ids = $x[0].id.split('_');
    var rowid = ids[1];
    var iowid = ids[3];

    $('#iow_'+rowid+'_qty_' + iowid).removeClass('red_bdr');

    var thisQty = parseFloat($('#iow_'+rowid+'_qty_' + iowid).val());
    var estQty = parseFloat($('#iow_'+rowid+'_estimateqty_' + iowid).html());
    var wotQty = parseFloat($('#iow_'+rowid+'_workorderqty_' + iowid).html());
    var totbillQty = parseFloat($('#iow_'+rowid+'_totbilledqty_' + iowid).html());
    var wpQty = parseFloat($('#iow_'+rowid+'_wpqty_' + iowid).html());

    var chkQty = 0;
    var chk2Qty = 0;
    /*if(wotQty > totbillQty)
        chkQty = wotQty;
    else
        chkQty = totbillQty;*/

    chkQty = (wotQty - wpQty);
    chk2Qty = (wotQty - totbillQty);

    if((chkQty >= thisQty) && (chk2Qty >= thisQty)) {
        //if(chkQty >= thisQty) {
        $('#iow_'+rowid+'_qty_' + iowid).removeClass('red_bdr');
        $('#iow_'+rowid+'_qty_' + iowid).val(sanitizeNumber(thisQty, 3));
    } else {
        $('#iow_'+rowid+'_qty_' + iowid).addClass('red_bdr');
        $('#iow_'+rowid+'_qty_' + iowid).val('');
        alert('Qty exceeds');
    }

    if ($('#iow_' + rowid + '_DPEIOWTransId_' + iowid).val() != 0) {
        $('#iow_' + rowid + '_UpdateRow_' + iowid).val(1);
        $('#UpdateRow_' + rowid).val(1);
    }

    // calc total qty
    var totalQty = 0;
    $.each($('input[id^=iow_' + rowid + '_qty_'), function (i, o) {
        var qty = parseFloat($(this).val());
        if (isNaN(qty))
            qty = 0;

        totalQty += qty;
    });

    $('#qty_' + rowid).val(sanitizeNumber(totalQty, 3));
    var rate = parseFloatVal($('#rate_' + rowid).val());
    $('#amount_' + rowid).val(sanitizeNumber(totalQty * rate));
}

function calcQuantityWOWbs(x)
{
    var $x = $(x);
    var ids = $x[0].id.split('_');
    var rowid = ids[1];

    $('#qty_' + rowid).removeClass('red_bdr');

    var thisQty = parseFloat($('#qty_' + rowid).val());
    var estQty = parseFloat($('#estimateqty_' + rowid).html());
    var wotQty = parseFloat($('#workorderqty_' + rowid).html());
    var totbillQty = parseFloat($('#totbilledqty_' + rowid).html());
    var wpQty = parseFloat($('#wpqty_' + rowid).html());

    var chkQty = 0;
    var chk2Qty = 0;
    /*if(wotQty > totbillQty)
        chkQty = wotQty;
    else
        chkQty = totbillQty;*/

    chkQty = (wotQty - wpQty);
    chk2Qty = (wotQty - totbillQty);

    if((chkQty >= thisQty) && (chk2Qty >= thisQty)) {
        //if((estQty >= thisQty) && (thisQty >= chkQty)) {
        //if(chkQty >= thisQty) {
        $('#qty_' + rowid).removeClass('red_bdr');
        $('#qty_' + rowid).val(sanitizeNumber(thisQty, 3));
    } else {
        $('#qty_' + rowid).addClass('red_bdr');
        $('#qty_' + rowid).val('');
        alert('Qty exceeds');
    }

    var qty = parseFloatVal($('#qty_' + rowid).val());
    var rate = parseFloatVal($('#rate_' + rowid).val());
    $('#amount_' + rowid).val(sanitizeNumber(qty * rate));
}

function bindResourceIOW(x) {
    var rowid = $(x)[0].id.split('_')[1];
    var $iowrowid = $('#iow_' + rowid + '_rowid');
    var descId = $('#descid_' + rowid).val();
    var data = {};

    data.ProjectId = $('#projectId').val();
    if(WorkType == 'activity') {
        data.Type = 'getresourcedetails';
        data.ResourceId = descId;
    } else if (WorkType == 'iow') {
        data.Type = 'getiowdetails';
        data.IOWId = descId;
    }

    $('.loading_area').show();
    $.ajax({
        url: getBaseURL() + 'wpm/workprogress/entry',
        type: "post",
        data: data,
        async: false,
        success: function (data, textStatus, jqXHR) {
            if(jqXHR.status == 200) {
                data = JSON.parse(data);
                var iowtemplate = $('#iow-template').html();
                $.each(data, function (i,l) {
                    var iowrowid = parseInt($iowrowid.val()) + 1;
                    $('#iowTable_' + rowid).find('> tbody.main').append(iowtemplate.replace(/__/g, '_' + rowid).replace(/_0/g, '_' + iowrowid));
                    $iowrowid.val(iowrowid);

                    var estQty = 0;
                    if(WorkType == 'activity') {
                        $('#iow_' + rowid + '_agtno_' + iowrowid).val(l.RefSerialNo);
                        $('#iow_' + rowid + '_spec_' + iowrowid).val(l.Specification);

                        estQty = ((l.Qty / l.bQty) * l.cQty);
                        $('#iow_' + rowid + '_estimateqty_' + iowrowid).html(parseFloatVal(estQty));
                    } else {
                        $('.worktype-activity').remove();
                        $('#iow_' + rowid + '_estimateqty_' + iowrowid).html(parseFloatVal(l.Qty));
                    }
                    $('#iow_' + rowid + '_wbs_' + iowrowid).val(l.ParentText +'->'+ l.WBSName);
                    $('#iow_' + rowid + '_wbsid_' + iowrowid).val(l.WBSId);
                    //$('#iow_' + rowid + '_unitname_' + iowrowid).val();
                    $('#iow_' + rowid + '_iowid_' + iowrowid).val(l.ProjectIOWId);

                    var woeQty = 0;
                    var wbeQty = 0;
                    var wpeQty = 0;
                    $.ajax({
                        url: getBaseURL() + 'wpm/workprogress/entry',
                        type: "post",
                        data: {'ResourceId': descId, 'ccId': $('#costCentreId').val(), 'IOWId': l.ProjectIOWId, 'WBSId': l.WBSId, 'Type': 'getwoqty', 'WOType': WorkType, 'woRegId': $('#WORegisterId').val()},
                        async: false,
                        success: function (data, textStatus, jqXHR) {
                            if(jqXHR.status == 200) {
                                data = JSON.parse(data);
                                woeQty = data.WOQty;
                                wbeQty = data.WBQty;
                                wpeQty = data.WPQty;
                                if (woeQty == null) {
                                    woeQty = 0;
                                }
                                if (wbeQty == null) {
                                    wbeQty = 0;
                                }
                                if (wpeQty == null) {
                                    wpeQty = 0;
                                }
                                $('#iow_' + rowid + '_workorderqty_' + iowrowid).html(parseFloatVal(woeQty));
                                $('#iow_' + rowid + '_totbilledqty_' + iowrowid).html(parseFloatVal(wbeQty));
                                $('#iow_' + rowid + '_wpqty_' + iowrowid).html(parseFloatVal(wpeQty));
                            }
                        }, error: function (jqXHR, textStatus, errorThrown) {
                        }
                    });
                });
            }
            $('.loading_area').hide();
        }, error: function (jqXHR, textStatus, errorThrown) {
            $('.loading_area').hide();
        }
    });
}

function bindWithoutWbs(x,xty) {
    if(xty == 1) {
        var rowid = $(x)[0].id.split('_')[1];
    } else if(xty == 2) {
        var rowid = x;
    }
    var descId = $('#descid_' + rowid).val();

    var resId = 0;
    var wiowId = 0;
    var woeQty = 0;
    var wbeQty = 0;
    var wpeQty = 0;

    if(WorkType == 'activity') {
        resId = descId;
    } else if (WorkType == 'iow') {
        wiowId = descId;
    }

    $('.loading_area').show();
    $.ajax({
        url: getBaseURL() + 'wpm/workprogress/entry',
        type: "post",
        data: {'ResourceId': resId, 'ccId': $('#costCentreId').val(), 'IOWId': wiowId, 'Type': 'getqtywio'},
        async: false,
        success: function (data, textStatus, jqXHR) {
            if(jqXHR.status == 200) {
                data = JSON.parse(data);
                woeQty = data.WOQty;
                wbeQty = data.WBQty;
                wpeQty = data.WPQty;
                if (woeQty == null) {
                    woeQty = 0;
                }
                if (wbeQty == null) {
                    wbeQty = 0;
                }
                if (wpeQty == null) {
                    wpeQty = 0;
                }
                $('#workorderqty_' + rowid).html(parseFloatVal(woeQty));
                $('#totbilledqty_' + rowid).html(parseFloatVal(wbeQty));
                $('#wpqty_' + rowid).html(parseFloatVal(wpeQty));
            }
            $('.loading_area').hide();
        }, error: function (jqXHR, textStatus, errorThrown) {
            $('.loading_area').hide();
        }
    });
}

<!--Handson Script-->
var handsonTableData =  [[]],
    handsonTable = null,
    $HandsonTableWrapper = document.getElementById('HandsonTableWrapper'),
    HandsonTableSettings = {
        colHeaders:true,
        rowHeaders: true,
        contextMenu: true,
        minRows: 25,
        minCols: 10,
        minSpareRows: 1,
        stretchH: 'all',
        formulas: true,
        manualColumnResize: true,
        fixedRowsTop: 1,
        fixedRowsBottom: 1,
        manualRowResize: true,
        fillHandle: true,
        data: handsonTableData,
        beforeChange: function(changes, source) {
            if(source == 'paste') {
                var changesJSON = JSON.parse(JSON.stringify(changes));
                for(var i=0; i<changesJSON.length; i++) {
                    var row = changesJSON[i][0],
                        value = changesJSON[i][3];

                    if(value.indexOf('=') == -1)
                        return;

                    changes[i][3] = value.replace(/\d+/g, function(n){return  parseInt(row + 1, 10); });
                }
            }
        },
        afterRender: function() {
            summationColumns();
        },
        cells: function (row, col, prop) {
            var cellProperties = {};

            if (row === 0) {
                cellProperties.renderer = firstRowRenderer;
            }

            return cellProperties;
        }
    };
function firstRowRenderer(instance, td, row, col, prop, value, cellProperties) {
    Handsontable.renderers.TextRenderer.apply(this, arguments);
    td.style.fontWeight = 'bold';
}
var summationColumn = '',
    selColumns = [],
    tempSelectedCol = [];
function showHandsonTableModal(mtype, x, forceShowTable) {
    if(mtype == 1) {
        hideShow(x, 's', 'w');
    }
    var $x = $(x),
        spilts = $x[0].id.split('_'),
        iowid = spilts[1],
        rowid = spilts[3];

    var measurement = isNullCheck($.trim($('#iow_'+iowid+'_Measurement_'+rowid).val()), 'string');

    if(typeof forceShowTable == 'undefined' && measurement == '') {
        $x.prop('readonly', false);
        var $qty = $('#iow_'+iowid+'_qty_'+rowid);

        // show prompt
        removeTooltip();
        $qty.prop('readonly', false);
        $qty.after($mSheetConfirmToolTipTemplate);
        $('#MSheetConfirmationToolTip').data('iowid', iowid).data('rowid', rowid);
    } else {
        $x.prop('readonly', true);

        if(measurement == '')
            handsonTableData = [[]];
        else
            handsonTableData = $.parseJSON(measurement);

        summationColumn = $.trim($('#iow_'+iowid+'_CellName_' + rowid).val());
        selColumns = ($.trim($('#iow_'+iowid +'_SelectedColumns_' + rowid).val())).split(',');
        tempSelectedCol = [];
        renderHandsonTable();

        $('#ExcelTemplate').find('option:first-child').prop('selected', true).siblings('option').removeAttr('selected');
        $formWrapper.hide();
        $HandsonWrapper.data('iowid', iowid).data('rowid', rowid).fadeIn();
    }
}
function removeTooltip() {
    $('#MSheetConfirmationToolTip').remove();
}
// Measurement Sheet toptip
function setMSheet() {
    var $tooltip = $('#MSheetConfirmationToolTip'),
        id = '#iow_'+$tooltip.data('iowid')+'_Measurement_'+$tooltip.data('rowid');
    showHandsonTableModal('2', id, true);
    removeTooltip();
    handsonTableData  = [[]];
    renderHandsonTable();
}
function removeMSheet() {
    var rowid = $HandsonWrapper.data('rowid'),
        iowid = $HandsonWrapper.data('iowid'),
        $qty = $('#iow_'+iowid+'_qty_' + rowid);
    $qty.val('');
    $('#iow_'+iowid+'_Measurement_' + rowid).val('');
    $HandsonWrapper.hide();
    $formWrapper.fadeIn();
    $qty.focus();
}
document.addEventListener("DOMContentLoaded", function() {
    handsonTable = new Handsontable($HandsonTableWrapper, HandsonTableSettings);
});

function updateMSheet() {
    var $totalcolumns = $('#totalcolumns'),
        columns = $totalcolumns.val();

    if(columns == null) {
        alert('Choose aleast one Column!');
        return false;
    }

    var $checkedColumn = $('input[type=radio][name=summationColumns]:checked');
    if($checkedColumn.length == 0) {
        alert('Summation Column is Required!');
        return false;
    }

    var selColumn = $checkedColumn.val(),
        total = $checkedColumn.data('total');


    var rowid = $HandsonWrapper.data('rowid'),
        iowid = $HandsonWrapper.data('iowid'),
        data = filterArray(handsonTable.getData()),
        jsonData = JSON.stringify(data);
    if(jsonData == '[]')
        jsonData = '[[]]';

    $('#iow_'+iowid+'_Measurement_' + rowid).val(jsonData);
    $('#iow_'+iowid+'_qty_' + rowid).val(total).trigger('change');
    $('#iow_'+iowid+'_CellName_' + rowid).val(selColumn);
    $('#iow_'+iowid+'_SelectedColumns_' + rowid).val(columns.join());
    $HandsonWrapper.hide();
    $formWrapper.fadeIn();
}

function hideHandsonWrapper(){
    $HandsonWrapper.hide();
    $formWrapper.fadeIn();
}
// Filter all empty rows
function filterArray(arr) {
    var checkNull = true;
    arr =  $.grep($(arr).toArray().reverse(), function (n,i) {
        var isValid = false;

        if(!checkNull)
            return true;

        $.each(n, function(j,obj) {
            if(obj != null) {
                isValid = true;
                checkNull = false;
                return false;
            }
        });

        return isValid;
    });
    return arr.reverse();
}

function getExcelTemplate(x) {
    var templateId = $(x).val();
    $.ajax({
        url:getBaseURL()+ 'cb/clientbilling/getexceltemplate',
        type:"post",
        data: {'TemplateId': templateId, csrf: "<?php echo isset($csrf)?$csrf:''; ?>"},
        async: false,
        success:function(data, textStatus, jqXHR){
            if(data != '') {
                var json_data = $.parseJSON(data);
                handsonTableData = $.parseJSON(json_data.Description);
                selColumns = ($.trim(json_data.SelectedColumns)).split(',');
                summationColumn = json_data.CellName;
            } else {
                handsonTableData = [[]];
                selColumns = [];
                summationColumn = '';
            }

            renderHandsonTable();
        }, error:function(jqXHR, textStatus, errorThrown){
            return false;
        }
    });
}

function renderHandsonTable() {
    if(typeof handsonTableData != 'object')
        handsonTableData  = [[]];

    handsonTable.loadData(handsonTableData);
    handsonTable.render();

    summationColumns();
}

function summationColumns(calcOnly) {
    if(handsonTable == null)
        return;

    var $totalColumns = $('#totalcolumns'),
        rowCount = handsonTable.countRows();

    if(typeof calcOnly == 'undefined') {
        //set columns header
        var options = '';
        $.each(handsonTable.getDataAtRow (0), function (i, obj) {
            var value = $.trim(obj),
                sel = '';
            if (value.length == 0 || value == "" || value.indexOf('=') != -1)
                return;

            var colName = handsonTable.getColHeader(i);
            if($.inArray(colName, tempSelectedCol) != -1 || $.inArray(colName, selColumns) != -1)
                sel = 'selected';

            options += '<option value="' + colName + '" '+sel +'>' + value + '</option>';
        });
        $totalColumns.html(options).triggerHandler('change');
    }

    // calculate columns
    var arr_columns = $totalColumns.find(':selected');
    if(arr_columns.length == 0) {
        $('#summationColumnsWrapper').html('');
        return;
    }

    // selected summation columns
    tempSelectedCol = [];
    var totalLabels = '';
    $.each(arr_columns, function(i, obj) {
        var $this = $(this),
            col = $this.val(),
            columnData = handsonTable.plugin.helper.cellRangeValue(col+'1',col+ rowCount),
            total = 0;

        // push to temp sel col
        tempSelectedCol.push(col);

        // selected columns datas
        $.each(columnData[0], function(j, val) {
            if(/^[0-9\.]+$/.test(val) == false)
                return;

            total += parseFloatVal(val);
        });

        if(total == '')
            total = 0;

        if(col == summationColumn) {
            totalLabels += '<label class="btn btn-primary tot-dis active">'
            + '<input type="radio" name="summationColumns" autocomplete="off" value="'+col+'" data-total="'+total+'" checked><label>'+ $this.html() +' </label><p>'+total+'</p>'
            + '</label>';
        } else {
            totalLabels += '<label class="btn btn-primary tot-dis">'
            + '<input type="radio" name="summationColumns" autocomplete="off" value="'+col+'" data-total="'+total+'"><label>'+ $this.html() +' </label><p>'+total+'</p>'
            + '</label>';
        }
    });
    $('#summationColumnsWrapper').html(totalLabels);
}

if($('#wpTypeId').val() != '') {
    $.post(getBaseURL() + 'wpm/labourstrength/get-comp-cc-no', {
            typeId: $('#wpTypeId').val(),
            ccId: $('#costCentreId').val()
        },
        function (data) {
            var vNo = data.split('###');
            $('#CCDPENo').val($.trim(vNo[0]));
            $('#CompDPENo').val($.trim(vNo[1]));
            if($.trim(vNo[0]) != '')
                $('#CCDPENo').prop('readonly', true);
            if($.trim(vNo[1]) != '')
                $('#CompDPENo').prop('readonly', true);
        });
}
function bindPopOver() {
    var $inputs =  $('input[data-toggle="popover"]');
    $inputs.unbind('popover');
    $inputs.popover({
        placement : 'auto left',
        trigger : 'hover'
    });
}
function hideShow(x,hsType,wiType)
{
    var $x = $(x);
    var ids = $x[0].id.split('_');
    var rowid = ids[1];

    if(wiType == 'w') {
        var iowid = ids[3];

        if(hsType == 's')
            $('#iow_'+rowid+'_ewbqty_' + iowid).show();
        else if(hsType == 'h')
            $('#iow_'+rowid+'_ewbqty_' + iowid).hide();
    } else if(wiType == 'wo') {
        if($('#descid_' + rowid).val() != '') {
            if (hsType == 's')
                $('#ewbqty_' + rowid).show();
            else if (hsType == 'h')
                $('#ewbqty_' + rowid).hide();
        }
    }
}
</script>
