<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/cb.css" />
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/select2.full.min.js"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/select2.min.css" />
<script>
    $(document).ready(function() {
        $(".single_dropdown").select2({
            placeholder: "",
            allowClear: true
        });
    });
</script>
<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
        <div class="col-lg-12">
            <h1 class="txt_center">Property Management</h1>
        </div>
        <form method="post" action="" onsubmit = "return validation();">
            <div class="col-lg-12 clear">
                <div class="liner"></div>
            </div>
            <div class="col-lg-12 clear" style="background-color:#fff;">
                <div class="col-lg-6 padlr0 m_top10">
                    <div class="signup_onebyone_content">
                        <div class="setup_form prop_mnmt_form">
                            <div class="flwup_rightcnt"><h2>Deposits and Fees</h2></div>
                            <form method="post" action="" onsubmit = "return validation();">
                                <ul class="onebyone_form">
                                    <li id="q1" class="active focus">
                                        <div class="onebyone_wrapper">
                                            <div class="li_number">
                                                <span><i class="fa fa-flag-checkered" aria-hidden="true"></i></span>
                                                <div class="arrow">
                                                    <span><i class="fa fa-arrow-right"></i></span>
                                                </div>
                                            </div>
                                            <div class="onebyone_question">
                                                <span class="span_b">Has required any Deposit?</span>
                                            </div>
                                            <div class="onebyone_content">
                                                <div class="radio_check">
                                                    <p>
                                                        <input type="radio" value="1" id="DepAmountyes" name="availDeposite" <?php if(isset($regInfo) && $regInfo['IsDeposit'] == 1) { echo "checked"; } ?> />
                                                        <label for="DepAmountyes" class="ripple">Yes</label>
                                                    </p>
                                                    <p>
                                                        <input type="radio" value="0" id="DepAmountno" name="availDeposite" <?php if(isset($regInfo) && $regInfo['IsDeposit'] == 0) { echo "checked"; } if(!isset($regInfo)){ echo "checked";} ?> />
                                                        <label for="DepAmountno" class="ripple">No</label>
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </li>

                                    <li id="q2" class="" <?php if(isset($regInfo)&& $regInfo['IsDeposit'] == 0) { ?> style="display:none;" <?php } ?>>
                                        <div class="onebyone_wrapper">
                                            <div class="li_number">
                                                <span><i class="fa fa-flag-checkered" aria-hidden="true"></i></span>
                                                <div class="arrow">
                                                    <span><i class="fa fa-arrow-right"></i></span>
                                                </div>
                                            </div>
                                            <div class="onebyone_question">
                                                <span class="span_b">What is the Deposit Amount?</span>
                                            </div>
                                            <div class="onebyone_content">
                                                <div class="input">
                                                    <input type="text" id="depAmount" name="depAmount" onKeyPress="return isDecimal(event,this);" autocomplete="off" placeholder="Deposit Amount" value="<?php if(isset($regInfo) && $regInfo['DepositAmount']!="") { echo $regInfo['DepositAmount']; } ?>" class="inputSetup"/>
                                                </div>
                                                <div class="col-lg-12 error_message"><p>Required</p></div>
                                            </div>
                                        </div>
                                    </li>
                                    <li id="q3" class="">
                                        <div class="onebyone_wrapper">
                                            <div class="li_number">
                                                <span><i class="fa fa-flag-checkered" aria-hidden="true"></i></span>
                                                <div class="arrow">
                                                    <span><i class="fa fa-arrow-right"></i></span>
                                                </div>
                                            </div>
                                            <div class="onebyone_question">
                                                <span class="span_b">Has available any Maintenance Period?</span>
                                            </div>
                                            <div class="onebyone_content">
                                                <div class="radio_check">
                                                    <p>
                                                        <input type="radio" value="1" id="MainPeriodyes" name="availMainPeriod" <?php if(isset($regInfo) && $regInfo['IsMaintenance'] == 1) { echo "checked"; } ?> />
                                                        <label for="MainPeriodyes" class="ripple">Yes</label>
                                                    </p>
                                                    <p>
                                                        <input type="radio" value="0" id="MainPeriodno" name="availMainPeriod" <?php if(isset($regInfo) && $regInfo['IsMaintenance'] == 0) { echo "checked"; } if(!isset($regInfo)){ echo "checked";} ?>  />
                                                        <label for="MainPeriodno" class="ripple">No</label>
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                    <li id="q4" class="" <?php if(isset($regInfo)&& $regInfo['IsMaintenance'] == 0) { ?> style="display:none;" <?php } ?> >
                                        <div class="onebyone_wrapper">
                                            <div class="li_number">
                                                <span><i class="fa fa-flag-checkered" aria-hidden="true"></i></span>
                                                <div class="arrow">
                                                    <span><i class="fa fa-arrow-right"></i></span>
                                                </div>
                                            </div>
                                            <div class="onebyone_question">
                                                <span class="span_b">What is the Maintenance Period?</span>
                                            </div>
                                            <div class="onebyone_content">
                                                <div class="input">
                                                    <div class="col-lg-12 m_btm10 padlr0">
                                                        <div class="col-lg-9 col-md-9 col-sm-9 padlr0"><input type="text" id="mainPeriod" name="mainPeriod" autocomplete="off" onKeyPress="return isNumberKey(event);" placeholder="Maintenance Period" value="<?php if(isset($regInfo) && $regInfo['MaintenancePeriod']!="") { echo $regInfo['MaintenancePeriod']; } ?>" class="inputSetup" /></div>
                                                        <div class="col-lg-3 col-md-3 col-sm-3 padlr0">
                                                            <select style="width:100%;" name="main_terms" id="main_terms" class="single_dropdown">
                                                                <option <?php if (isset($regInfo) && strcmp(trim($regInfo['MaintenanceTerms']),"Y") == 0 ) echo 'selected' ; ?> value="Y">Years</option>
                                                                <option <?php if (isset($regInfo) && strcmp(trim($regInfo['MaintenanceTerms']),"M") == 0 ) echo 'selected' ; ?> value="M">Months</option>
                                                                <option <?php if (isset($regInfo) && strcmp(trim($regInfo['MaintenanceTerms']),"D") == 0 ) echo 'selected' ; ?> value="D">Days</option>
                                                            </select>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-lg-12 error_message position_rel"><p>Required</p></div>
                                            </div>
                                        </div>
                                    </li>
                                    <li id="q5" class="">
                                        <div class="onebyone_wrapper">
                                            <div class="li_number">
                                                <span><i class="fa fa-flag-checkered" aria-hidden="true"></i></span>
                                                <div class="arrow">
                                                    <span><i class="fa fa-arrow-right"></i></span>
                                                </div>
                                            </div>
                                            <div class="onebyone_question">
                                                <span class="span_b">Has available any Annual Maintenance Service after Maintenance Period?</span>
                                            </div>
                                            <div class="onebyone_content">
                                                <div class="radio_check">
                                                    <p>
                                                        <input type="radio" value="1" id="SerPeriodyes" name="availSerPeriod" <?php if(isset($regInfo) && $regInfo['IsAMC'] == 1) { echo "checked"; } ?>  />
                                                        <label for="SerPeriodyes" class="ripple">Yes</label>
                                                    </p>
                                                    <p>
                                                        <input type="radio" value="0" id="SerPeriodno" name="availSerPeriod" <?php if(isset($regInfo) && $regInfo['IsAMC'] == 0) { echo "checked"; } if(!isset($regInfo)){ echo "checked";} ?> />
                                                        <label for="SerPeriodno" class="ripple">No</label>
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                    <li id="q6" class="" <?php if(isset($regInfo)&& $regInfo['IsAMC'] == 0) { ?> style="display:none;" <?php } ?> >
                                        <div class="onebyone_wrapper">
                                            <div class="li_number">
                                                <span><i class="fa fa-flag-checkered" aria-hidden="true"></i></span>
                                                <div class="arrow">
                                                    <span><i class="fa fa-arrow-right"></i></span>
                                                </div>
                                            </div>
                                            <div class="onebyone_question">
                                                <span class="span_b">What is the Annual Maintenance Charges?</span>
                                            </div>
                                            <div class="onebyone_content">
                                                <div class="input">
                                                    <input type="text" id="mainCharge" name="mainCharge" autocomplete="off" onKeyPress="return isDecimal(event,this);" placeholder="Deposit Amount" value="<?php if(isset($regInfo) && $regInfo['AMCAmount']!="") { echo $regInfo['AMCAmount']; } ?>" class="inputSetup"/>
                                                </div>
                                                <div class="col-lg-12 error_message"><p>Required</p></div>
                                            </div>
                                        </div>
                                    </li>
                                    <li id="q7" class="">
                                        <div class="onebyone_wrapper">
                                            <div class="li_number">
                                                <span><i class="fa fa-flag-checkered" aria-hidden="true"></i></span>
                                                <div class="arrow">
                                                    <span><i class="fa fa-arrow-right"></i></span>
                                                </div>
                                            </div>
                                            <div class="onebyone_question">
                                                <span class="span_b">Has required any Monthly Maintenance Fees?</span>
                                            </div>
                                            <div class="onebyone_content">
                                                <div class="radio_check">
                                                    <p>
                                                        <input type="radio" value="1" id="availMainFeeYes" name="availMainFee" <?php if(isset($regInfo) && $regInfo['IsMMFees'] == 0) { echo "checked"; } ?> />
                                                        <label for="availMainFeeYes" class="ripple">Yes</label>
                                                    </p>
                                                    <p>
                                                        <input type="radio" value="0" id="availMainFeeNo" name="availMainFee" <?php if(isset($regInfo) && $regInfo['IsMMFees'] == 0) { echo "checked"; } if(!isset($regInfo)){ echo "checked";} ?> />
                                                        <label for="availMainFeeNo" class="ripple">No</label>
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                    <li id="q8" class="" <?php if(isset($regInfo)&& $regInfo['IsMMFees'] == 0) { ?> style="display:none;" <?php } ?>>
                                        <div class="onebyone_wrapper">
                                            <div class="li_number">
                                                <span><i class="fa fa-flag-checkered" aria-hidden="true"></i></span>
                                                <div class="arrow">
                                                    <span><i class="fa fa-arrow-right"></i></span>
                                                </div>
                                            </div>
                                            <div class="onebyone_question">
                                                <span class="span_b">What is the Monthly Maintenance Fees?</span>
                                            </div>
                                            <div class="onebyone_content">
                                                <div class="input">
                                                    <input type="text" id="MainFee" name="MainFee" autocomplete="off" placeholder="Maintenance Fees" onKeyPress="return isDecimal(event,this);" value="<?php if(isset($regInfo) && $regInfo['MMAmount']!="") { echo $regInfo['MMAmount']; } ?>" class="inputSetup"/>
                                                </div>
                                                <div class="col-lg-12 error_message"><p>Required</p></div>
                                            </div>
                                        </div>
                                    </li>
                                    <li id="q9" class="" <?php if(isset($regInfo)&& $regInfo['IsMMFees'] == 0) { ?> style="display:none;" <?php } ?>>
                                        <div class="onebyone_wrapper">
                                            <div class="li_number">
                                                <span><i class="fa fa-flag-checkered" aria-hidden="true"></i></span>
                                                <div class="arrow">
                                                    <span><i class="fa fa-arrow-right"></i></span>
                                                </div>
                                            </div>
                                            <div class="onebyone_question">
                                                <span class="span_b">What is the Due day of the Month?</span>
                                            </div>
                                            <div class="onebyone_content">
                                                <div class="input">
                                                    <input type="text" id="dueDay" name="dueDay" autocomplete="off" onKeyPress="return isNumberKey(event);" placeholder="Due day of the Month" value="<?php if(isset($regInfo) && $regInfo['MMDueDay']!="") { echo $regInfo['MMDueDay']; } ?>" class="inputSetup date_picker"/>
                                                </div>
                                                <div class="col-lg-12 error_message"><p>Required</p></div>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                                <div class="col-lg-12 savebtn_area m_btm20 no_border clear">
                                    <ul>
                                        <li class="save_btn float_l">
                                            <a class="ripple" href="<?php echo $this->basePath();?>/crm/property/entry/<?php echo $regId; ?>"  data-toggle="tooltip" data-placement="right" title="back">Back</a>
                                        </li>
                                        <li class="save_btn float_r">
                                            <input type="submit" class="ripple" href="javascript:void(0);" value="Continue"  data-toggle="tooltip" data-placement="left" title="Continue to fill Service" />
                                        </li>
                                    </ul>
                                </div>

                        </div>
                    </div>
                    <div class="clear"></div>
                </div>
        </form>
        <div class="col-lg-6 m_top20" id="ProjectDetail">
            <div class="form-group clear">
                <div class="col-lg-12">
                    <div class="row">
                        <div class="col-lg-12 clear">
                            <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label ">Project Name</label>
                            <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                <p id="dProjectName"><?php if(isset($unitInfo) && $unitInfo['ProjectName'] !=""){ echo $unitInfo['ProjectName']; } ?></p>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Block No</label>
                            <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                <p id="BlockName"><?php if(isset($unitInfo) && $unitInfo['BlockName'] !=""){ echo $unitInfo['BlockName']; } ?></p>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Floor No</label>
                            <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                <p id="FloorName" ><?php if(isset($unitInfo) && $unitInfo['FloorName'] !=""){ echo $unitInfo['FloorName']; } ?></p>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Unit Type</label>
                            <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                <p id="UnitType" ><?php if(isset($unitInfo) && $unitInfo['UnitTypeName'] !=""){ echo $unitInfo['UnitTypeName']; } ?></p>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Unit No</label>
                            <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                <p id="UnitNo"><?php if(isset($unitInfo) && $unitInfo['UnitNo'] !=""){ echo $unitInfo['UnitNo']; } ?></p>
                            </div>
                        </div>
                    </div>
                    <!--div class="row">
                        <div class="col-lg-12">
                            <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Area</label>
                            <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                <p id="Area" >1267</p>
                            </div>
                        </div>
                    </div-->
                    <div class="row">
                        <div class="col-lg-12">
                            <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Unit Area</label>
                            <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                <p id="UnitArea" ><?php if(isset($unitInfo) && $unitInfo['UnitArea'] !=""){ echo $unitInfo['UnitArea']; } ?></p>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Face</label>
                            <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                <p id="Facing"><?php if(isset($unitInfo) && $unitInfo['Description'] !=""){ echo $unitInfo['Description']; } ?></p>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Owner Name</label>
                            <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                <p id="BuyerName" ><?php if(isset($unitInfo) && $unitInfo['BuyerName'] !=""){ echo $unitInfo['BuyerName']; } ?></p>
                            </div>
                        </div>
                    </div>
                    <!--div class="row">
                        <div class="col-lg-12">
                            <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Address</label>
                            <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                <p id="BuyerAddress" >1355 Market Street, Suite 900 San Francisco, CA 94103</p>
                            </div>
                        </div>
                    </div-->
                </div>
            </div>
        </div>
    </div>

</div>
<script>
    $("li").hover(
        function () {
            $(this).addClass("active focus").parent().next().addClass("active focus");
        },
        function () {
            $(this).removeClass("active focus").parent().next().removeClass("active focus");
        }
    );

    $(".inputSetup").focus(function(){
        $('.focus').removeClass('active focus');
        $(this).closest('li').addClass('active focus');
        $('body,html').animate({
            scrollTop: scrollPoint
        }, 600);
    });
    <?php if(!isset($regInfo)){ ?>
    $('#q2 , #q4 , #q6 , #q8 , #q9').hide();
    <?php } ?>

    $('input[name="availDeposite"]').on('change', function() {
        if($(this).val() == 1){
            $('#q2').show();
        } else {
            $('#q2').hide();
        }
    });

    $('input[name="availMainPeriod"]').on('change', function() {
        if($(this).val() == 1){
            $('#q4').show();
        } else {
            $('#q4').hide();
        }
    });

    $('input[name="availSerPeriod"]').on('change', function() {
        if($(this).val() == 1){
            $('#q6').show();
        } else {
            $('#q6').hide();
        }
    });

    $('input[name="availMainFee"]').on('change', function() {
        if($(this).val() == 1){
            $('#q8,#q9').show();
        } else {
            $('#q8,#q9').hide();
        }
    });

    //newly addedd

    function validation(){
        var errorFlag = 0;
        var errorFlagCount = 0;

        if($('input[name="availDeposite"]:checked').val() == 1){
            if($('#depAmount').val() == ""){
                showErrorMsg($('#depAmount'), "Required");
                errorFlagCount = errorFlagCount + 1;
                errorFlag = 1;
                $('#depAmount').focus();
            } else {
                removeErrorMsg($('#depAmount'));
            }
        }
        if($('input[name="availMainPeriod"]:checked').val() == 1){
            if($('#mainPeriod').val() == ""){
                showErrorMsgNew($('#mainPeriod'), "Required");
                errorFlagCount = errorFlagCount + 1;
                errorFlag = 1;
                $('#mainPeriod').focus();
            } else if($('#main_terms').val() == null){
                showErrorMsgNew($('#mainPeriod'), "Required");
                errorFlagCount = errorFlagCount + 1;
                errorFlag = 1;
                $('#main_terms').focus();
            } else {
                removeErrorMsgNew($('#mainPeriod'));
            }
        }
        if($('input[name="availSerPeriod"]:checked').val() == 1){
            if($('#mainCharge').val() == ""){
                showErrorMsg($('#mainCharge'), "Required");
                errorFlagCount = errorFlagCount + 1;
                errorFlag = 1;
                $('#mainCharge').focus();
            } else {
                removeErrorMsg($('#mainCharge'));
            }
        }
        if($('input[name="availMainFee"]:checked').val() == 1){
            if($('#dueDay').val() == ""){
                showErrorMsg($('#dueDay'), "Required");
                errorFlagCount = errorFlagCount + 1;
                errorFlag = 1;
                $('#dueDay').focus();
            } else {
                removeErrorMsg($('#dueDay'));
            }
            if($('#MainFee').val() == ""){
                showErrorMsg($('#MainFee'), "Required");
                errorFlagCount = errorFlagCount + 1;
                errorFlag = 1;
                $('#MainFee').focus();
            } else {
                removeErrorMsg($('#MainFee'));
            }
        }

        if(errorFlag == 0) {
            return true;
        } else {
            return false;
        }
    }
    function showErrorMsg($tarIp, msg) {
        var $tarErrorMsg = $tarIp.closest('div').parent().find('.error_message');
        $tarErrorMsg.find('p').text(msg);
        $tarErrorMsg.show();
    }

    function removeErrorMsg($tarIp) {
        var $tarErrorMsg = $tarIp.closest('div').parent().find('.error_message');
        $tarErrorMsg.find('p').text('Please Enter ' + $tarIp.attr('label') + '...');
        $tarErrorMsg.hide();
    }
    function showErrorMsgNew($tarIp, msg) {
        var $tarErrorMsg = $tarIp.closest('.input').next('.error_message');
        $tarErrorMsg.find('p').text(msg);
        $tarErrorMsg.show();
    }

    function removeErrorMsgNew($tarIp) {
        var $tarErrorMsg = $tarIp.closest('.input').next('.error_message');
        $tarErrorMsg.hide();
    }
</script>