<div class="table-responsive topsp">
    <table class="table" style=" margin-bottom:0px;" id="sample12">
        <thead>
        <tr>
            <th width="20%">Description</th>
            <th width="20%">Unit</th>
            <th width="20%">Qty</th>
            <th width="20%">Rate</th>
            <th width="20%">Amount</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($sdServiceTrans as $sdServiceTran){?>
            <tr>
                <td width="20%"><input type="text" class="parent_text" value="<?php echo $sdServiceTran['ServiceName'];?>" readonly></td>
                <td width="20%"><input type="text" class="parent_text" value="<?php echo $sdServiceTran['UnitName'];?>" readonly></td>
                <td width="20%"><input type="text" class="parent_text text-right" value="<?php echo $this->commonHelper()->sanitizeNumber($sdServiceTran['Qty'],3);?>" readonly></td>
                <td width="20%"><input type="text" class="parent_text text-right" value="<?php echo $this->commonHelper()->sanitizeNumber($sdServiceTran['Rate'],2,true);?>" readonly></td>
                <td width="20%"><input type="text" class="parent_text text-right" value="<?php echo $this->commonHelper()->sanitizeNumber($sdServiceTran['Amount'],2,true);?>" readonly></td>
            </tr>
        <?php }?>
        </tbody>
        <tr>
            <td width="">&nbsp;</td>
            <td width="">&nbsp;</td>
            <td width="">&nbsp;</td>
            <td width="">&nbsp;</td>
<!--            <td width="20%" ><input type="text" class="parent_text text-right total-clr" value="--><?php //echo $this->commonHelper()->sanitizeNumber($sdRegister['Amount'],2,true);?><!--" readonly></td>-->
        </tr>
    </table>
</div>