<span class="gradientContainer">
    <a href="#" data-toggle="tooltip" data-placement="left" data-original-title="Amendment"><i class="fa fa-file-text-o"></i></a>
  </span>
<div class="table-responsive topsp">
    <table class="table" style=" margin-bottom:0px;" id="sample12">
        <thead>
        <tr>
            <th width="25%">Labour Type Name</th>
            <th width="25%">Unit</th>
            <th width="25%">Rate/Day</th>
            <th width="20%">OT Rate/Hr</th>
            <!--th width="5%"><a href="<?php echo $this->basePath() . '/wpm/labourstrength/rate-approval-entry/'.$Lrarow->LRARegisterId.'/ex'?>">Amendment</a></th-->
        </tr>
        </thead>
        <tbody>
        <?php foreach($lraTypeTrans as $lraTypeTran){?>
            <tr>
                <td width="25%"><input type="text" class="parent_text" value="<?php echo $lraTypeTran['ResourceName'];?>" readonly></td>
                <td width="25%"><input type="text" class="parent_text" value="<?php echo $lraTypeTran['UnitName'];?>" readonly></td>
                <td width="25%"><input type="text" class="parent_text text-right" value="<?php echo $this->commonHelper()->sanitizeNumber($lraTypeTran['Rate'],2,true);?>" readonly></td>
                <td width="25%"><input type="text" class="parent_text text-right" value="<?php echo $this->commonHelper()->sanitizeNumber($lraTypeTran['OTRate'],2,true);?>" readonly></td>
            </tr>
        <?php }?>
        </tbody>
        <tr>
            <td width="">&nbsp;</td>
            <td width="">&nbsp;</td>
            <td width="">&nbsp;</td>
            <td width="">&nbsp;</td>
        </tr>
    </table>
</div>