<style>
   .upload-pf {border: 1px solid #ddd; box-shadow: 0 0 0 2px #ffffff, 0 0 0 3px #7B7EBA; height: 118px; margin: 25px 10px 0 20px;overflow: hidden;float: left;position: relative;width: 80%;}
    .upload-pf img {width: 100% !important;height: 118px !important;background:#fff; }
    .upload-pf .ovrly {position: absolute;background: rgba(0, 0, 0, 0.5);height: 100%;right: 100%;top: 0;width: 100%;     -webkit-transition: all 0.5s;-moz-transition: all 0.5s; -o-transition: all 0.5s;transition: all 0.5s;}
    .upload-pf .buttons {position: absolute;top: 50%;right: -100%;-webkit-transition: all 0.5s;-moz-transition: all 0.5s;
        -o-transition: all 0.5s;transition: all 0.5s;-webkit-transform: translate(50%, -50%);-moz-transform: translate(50%, -50%);-ms-transform: translate(50%, -50%);-o-transform: translate(50%, -50%);transform: translate(50%, -50%);}
    .upload-pf .buttons .fa {margin: 0 1px;background: rgba(256, 256, 256, 0.9);-webkit-box-shadow: 0 0 1px rgba(0, 0, 0, 0.3);-moz-box-shadow: 0 0 1px rgba(0, 0, 0, 0.3);box-shadow: 0 0 1px rgba(0, 0, 0, 0.3);-webkit-border-radius: 50%;  -moz-border-radius: 50%;border-radius: 50%;color: rgba(50, 50, 50, 0.9);display: inline-block;line-height: 40px;     font-size: 16px;text-align: center;text-decoration: none;width: 40px;cursor:pointer;height: 40px;}
	.remrk                             				{border: 1px solid #ccc;resize: none;padding:7px 4px; width:36%; height:100px; }
.remrk:focus                       				{-moz-box-shadow: 0 0 5px #ccc;-webkit-box-shadow: 0 0 5px#ccc;box-shadow: 0 0 5px #ccc;border:1px solid #7EB6FF;}
.form-group1{margin-bottom:6px}
.lbl_move{height:40px !important; border: 1px solid #dddddd;}
</style>
<div class="table-responsive topsp animated-panel zoomIn" style="animation-delay: 0.2s;">
                    <table id="labourTable" class="table" style=" margin-bottom:0px; ">
                        <thead>
                            <tr class="popuptable-topfix">
                                <th width="11%">Group Name</th>
                                <th width="11%">Labour Name</th>
                                <th width="8%">Type Name</th>
                                <th width="3%">&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody id="mainBody">
                            <?php
                                $i = 0;
                            if (isset($labTrans)) {
                                foreach($labTrans as $lTrans) { $i++; $iltransid = $lTrans['LabourTransId']; ?>
                                <tr>
                                    <td width="11%">
                                        <input class="parent_text groupSuggest" type="text" name="groupName_<?php echo $i; ?>" id="groupName_<?php echo $i; ?>" value="<?php echo $lTrans['LabourGroupName']; ?>" readonly />
                                        <input type="hidden" name="groupId_<?php echo $i; ?>" id="groupId_<?php echo $i; ?>" value="<?php echo $lTrans['LabourGroupId']; ?>" />
                                        <input type="hidden" name="vendorId_<?php echo $i; ?>" id="vendorId_<?php echo $i; ?>" value="<?php echo $lTrans['VendorId']; ?>" />
                                        <input type="hidden" name="labourId_<?php echo $i; ?>" id="labourId_<?php echo $i; ?>" value="<?php echo $lTrans['LabourId']; ?>" />
                                    </td>
                                    <td width="11%" align="center">
                                        <input class="parent_text mainTrName" type="text" name="labourName_<?php echo $i; ?>" id="labourName_<?php echo $i; ?>" value="<?php echo $lTrans['LabourName']; ?>" readonly />
                                    </td>
                                    <td width="5%">
                                        <input class="parent_text typeSuggest" type="text" name="typeName_<?php echo $i; ?>" id="typeName_<?php echo $i; ?>" value="<?php echo $lTrans['ResourceName']; ?>" readonly />
                                        <input type="hidden" name="typeId_<?php echo $i; ?>" id="typeId_<?php echo $i; ?>" value="<?php echo $lTrans['LabourTypeId']; ?>" />
                                    </td>
                                     <td width="4%">
                                        <ul class="action_btns">
                                            <li> <a href="javascript:void(0);" class="mainTr"  id="exptr_<?php echo $i; ?>"><i style="text-align:center" class="fa fa-chevron-circle-down" data-toggle="tooltip" data-placement="top" data-original-title="Expand"></i></a> </li>
                                        </ul>
                                    </td>
                                   
                                </tr>
                                <tr class="subTr" style="display:none;">
                                    <td colspan="4">
                                        <div class="subDiv">
                                            <div class="col-lg-12 col-xs-12 slidingDiv1 animated fadeInUp" style="padding-top:30px;">
                                                <div class="col-lg-6 col-lg-offset-0 col-xs-12 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0 mar-35">
                                                    <div class="col-sm-12 col-xs-12 form-group1">
													 <label>Id No</label>
                                                        <input type="text" class="form-control lbl_move" id="idNo_<?php echo $i; ?>" data-idajax="" name="idNo_<?php echo $i; ?>" value="<?php echo $lTrans['Code']; ?>" readonly/>
                                                    </div>
                                                    <div class="col-sm-12 col-xs-12 form-group1">
													 <label>Address</label>
                                                        <input class="form-control lbl_move" style="width:100%; height:45px !important;" id="address_<?php echo $i; ?>" name="address_<?php echo $i; ?>"  value="<?php echo $lTrans['Address']; ?>" readonly>
                                                    </div>
                                                    <div class="col-sm-12 col-xs-12 form-group1">
													 <label>City</label>
                                                        <input type="text" class="form-control lbl_move citySuggest" name="city_<?php echo $i; ?>" id="city_<?php echo $i; ?>" value="<?php echo $lTrans['CityName']; ?>" readonly/>
                                                        <input type="hidden" name="cityId_<?php echo $i; ?>" id="cityId_<?php echo $i; ?>" value="<?php echo $lTrans['CityId']; ?>" data-name="locality"/>
                                                    </div>
                                                    <div class="col-sm-12 col-xs-12 form-group1">
													 <label>State</label>
                                                        <input type="text" class="form-control lbl_move" name="state_<?php echo $i; ?>" id="state_<?php echo $i; ?>" value="<?php echo $lTrans['StateName']; ?>" data-name="administrative_area_level_1"  readonly/>
                                                    </div>
                                                    <div class="col-sm-6 col-xs-6 form-group1">
													 <label>Country</label>
                                                        <input type="text" class="form-control lbl_move"  name="country_<?php echo $i; ?>" id="country_<?php echo $i; ?>" value="<?php echo $lTrans['CountryName']; ?>" data-name="country" readonly/>
                                                    </div>
													  <div class="col-sm-6 col-xs-6 form-group1">
													 <label>Pin Code</label>
                                                        <input type="text" class="form-control lbl_move" id="pinCode_<?php echo $i; ?>" name="pinCode_<?php echo $i; ?>" value="<?php echo $lTrans['PinCode']; ?>" 
                                                        data-name="postal_code" readonly />
                                                    </div>
                                                </div>
                                                <div class="col-lg-6 col-xs-12 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0 mar-35">  
                                                 <div class="col-md-8 col-xs-12 col-sm-7">    
                                                    <div class="col-sm-12 col-xs-12 form-group1" style="padding:0 !important">
													<label>Mobile</label>
                                                        <input type="text" class="form-control lbl_move" id="mobile_<?php echo $i; ?>" name="mobile_<?php echo $i; ?>" value="<?php echo $lTrans['Mobile']; ?>" readonly />
                                                    </div>
                                                    <div class="col-sm-12 col-xs-12 form-group1" style="padding:0 !important">
													 <label>Email</label>
                                                        <input type="text" class="form-control lbl_move" id="email_<?php echo $i; ?>" name="email_<?php echo $i; ?>" value="<?php echo $lTrans['Email']; ?>" readonly/>
                                                    </div>
                                                </div>
                                                      <div class="col-md-4 col-sm-5 col-xs-12" id="browse_<?php echo $i; ?>" style="padding:0 !important" >
                                                            <div class="upload-pf"> <img id="showpic_<?php echo $i; ?>" src="<?php echo $this->basePath(); ?><?php echo "/";?><?php echo $lTrans['LabourProfile'];?>" onerror="this.src='<?php echo $this->basePath(); ?>/images/avatar.jpg';" /> <img id="blah_<?php echo $i; ?>" src="#" alt="your image" style="display:none;width:258px;height:280px" />
                                                                <div class="ovrly"></div>
                                                                <div class="buttons">
                                                                    <a href="#" class="fa fa-link"></a>
                                                                </div>
                                                            </div>
                                                        </div>
                                                       
                                                    <div class="col-sm-12 col-xs-12 form-group1">
													 <label>PF No</label>
                                                        <input type="text" class="form-control lbl_move" id="pfNo_<?php echo $i; ?>" name="pfNo_<?php echo $i; ?>" value="<?php echo $lTrans['PFNo']; ?>" data-ajax="" readonly />
                                                    </div>
                                                    <div class="col-sm-12 col-xs-12 form-group1">
													 <label>Aadhaar No</label>
                                                        <input type="text" class="form-control lbl_move" id="adharNo_<?php echo $i; ?>" name="pfNo_<?php echo $i; ?>" value="<?php echo $lTrans['PFNo']; ?>" data-adharajax="" readonly />
                                                    </div>
                                                    <div class="col-sm-12 col-xs-12 form-group1">
													 <label>ESI No</label>
                                                        <input type="text" class="form-control lbl_move" id="esiNo_<?php echo $i; ?>" name="esiNo_<?php echo $i; ?>" value="<?php echo $lTrans['ESINo']; ?>" data-esnoajax=""  readonly />
                                                    </div>
                                                </div>

										<div class="col-lg-12 col-xs-12">
                                            <?php
                                            $arrDoc = array_filter($documents, function($v) use($iltransid) { return $v['LabourTransId'] == $iltransid; });
                                            $j=1;
                                            if (!empty($arrDoc)) { ?>
                                            <table class="table" style=" margin-bottom:10px;">
                                                <thead>
                                                 <tr>
                                                  <th>Document Type</th>
                                                   <th>Document Description</th>
                                                    <th>&nbsp;</th>
                                                     </tr>
                                                    </thead>
												   <tbody>
                                                 <?php foreach($arrDoc as $make) {
                                                    ?>
                                                   <tr>
                                                    <td width="45%">
                                                      <input class="parent_text docmentauto" name="document_<?php echo $i; ?>_type_<?php echo $j;?>" id="document_<?php echo $i; ?>_type_<?php echo $j;?>" type="text" value="<?php echo $make['Doc']; ?>" readonly>
                                                      <input type="hidden"  value="<?php echo $make['DocumentId']; ?>" id="doctype_<?php echo $i;?>_auto_<?php echo $j;?>" name="doctype_<?php echo $i; ?>_auto_<?php echo $j;?>">
                                                    </td>
													<td width="45%">
                                                      <textarea class="parent_texts"  name="document_<?php echo $i; ?>_desc_<?php echo $j;?>" id="document_<?php echo $i; ?>_desc_<?php echo $j;?>" readonly maxlength="255" ><?php echo $make['DocumentName'] ?></textarea></td>
                                                   </tr>
                                                   <?php $j++; } ?>
											  </table>
                                             <?php } ?>
										   </div>
										</div>                                
									</div> 
                                </td>
                                </tr>
                                <?php
                                } } ?>
                        </tbody>
                        <tbody>
                            <tr>
                                <td colspan="4">
                                    <textarea class="remrk element" placeholder="Enter Remarks" name="remarks" id="remarks" readonly>
                                        <?php echo (isset($labRegister)) ? $labRegister['Remarks'] : ''; ?>
                                    </textarea>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
<script>
        $('.mainTr').on('click',function(e) {
            e.preventDefault();
            if (!$(this).closest("tr").next(".subTr").is(":visible")) {
                $(this).closest("tr").next(".subTr").show();
                $(this).closest("tr").next(".subTr").find(".subDiv").slideDown("slow");
                $(this).find("i").addClass("tform");
                closedetails($(this)[0].id)
            } else {
                $(this).closest("tr").next(".subTr").find(".subDiv").slideUp("slow");
                $(this).closest("tr").next(".subTr").slideUp("slow");
                $(this).find("i").removeClass("tform");
            }
        });

        function closedetails(name) {
            var $mainTRs = $("a[class*=mainTr]");
            $.each($mainTRs, function (i, obj) {
                var $this = $(this);
                if (name != $this[0].id) {
                    if ($(this).closest("tr").next(".subTr").is(":visible")) {
                        $(this).closest("tr").next(".subTr").find(".subDiv").slideUp("slow");
                        $(this).closest("tr").next(".subTr").slideUp("slow");
                        $(this).find("i").removeClass("tform");
                    }
                }
            });
        }


</script>