<style>
    .subDiv                         {margin-left:10px; margin-top:10px;}

    .abt-iowt2 thead tr th          {background:#CAE1F9!important;font-size:11px; margin-top:20px;}
    .fntst                          {font-size:14px;font-family:'Open Sans', sans-serif !important;display:block !important;padding-left:12px !important;}
    .thscss 					    {font-family:'Open Sans', sans-serif !important;background-color:#E2EBEF !important;border-bottom:1px solid #5D9BB6 !important;	padding:8px !important;font-size:11px;}
    .tdpds 						    {border-top: 1px solid #EFEFEF!important;line-height:1.42857!important;padding:8px!important;vertical-align:top!important;font-family:'Open Sans', sans-serif !important;font-size:12px;}
    .bill-det 					    {font-size:14px;font-family:'Open Sans', sans-serif !important;display:block;padding-left:5px !important;}
    .date-bills					    { }
    .str-bill 					    {display:block !important;width:10px;padding-left:10px;}
    .date-shw 					    {font-size:14px;font-family:'Open Sans', sans-serif !important;display:block !important;padding-left:12px !important;}
    p							    {color:#000;font-size:14px;text-align:left;padding-top:-8px; line-height:24px !important;font-family:'Open Sans', sans-serif !important;}
    .su-t 						    {margin-left:13px !important}
    .sel-wets 					    {border:thin solid #c2c2c2 !important;margin-bottom:10px !important;width:95% !important;border-radius:0px !important;}
    .sel-wets select option 	    {padding-left:10px !important;padding-top:3px;padding-bottom:3px;}
    .sel-wets select option.thin    {outline-width:thin !important;}
    .sel-wets select option.thick   {outline-width:thick !important;}
    .sel-wets select option.thicker {outline-width:thicker !important;}
    .abst-curt                      {margin-left:13px;}
    .bill-cum                       {margin-left:10px;}
    .abt-iow                        {margin-left:10px;}
    .abt-all                        {margin-left:10px;}

    /*#htmlwrapper #p_scents p.bill-det{font-family:'Open Sans', sans-serif !important; font-size:14px; color:#F00;}
    #htmlwrapper #p_scents p.date-bills{font-family:'Open Sans', sans-serif !important; font-size:14px; color:#F00;}
    .sel-wets select option.dotteds  {border-style:dotted;}
    .sel-wets select option.dasheds  {border-style:dashed;}
    .sel-wets select option.solids   {border-style:solid;}
    .sel-wets select option.doubles  {border-style:double;}
    .sel-wets select option.hiddens  {border-style:hidden;}	*/
</style>
<div id="p_scents" style="height:630px; position:relative;">
    <div class="drsElement drsMoveHandle drsItem" data-name="Header Info" style="left:10px;top:8px;width:680px;height:30px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
        <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">Workorder Details</p>
        <button type="button" class="remScnt"><i class="fa fa-trash-o"></i></button>
    </div>
    <div class="drsElement drsMoveHandle drsItem" data-name="Date Info" style="left:545px;top:37px;width:145px;height:30px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
        <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">Date :</p>
        <span id="wo_Date" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
        <button type="button" class="remScnt"><i class="fa fa-trash-o"></i></button>
    </div>
    <div class="drsElement drsMoveHandle drsItem" data-name="Logo" style="left:10px;top:38px;width:200px;height:130px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border: 1px solid rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
        <p class="not-editable" style="text-align:center !important; vertical-align:middle !important;">
            <img id="wo_Logo" src="http://localhost/bsf_v1.0/public/images/nolgo.jpg">
        </p>
        <button type="button" class="remScnt"><i class="fa fa-trash-o"></i></button>
    </div>
    <div class="drsElement drsMoveHandle drsItem" data-name="Workorder Info" style="left:10px;top:168px;width:300px;height:80px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border: 1px solid rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
        <div class="drsElement drsMoveHandle drsGroupItem" data-name="Workorderno field" style="left:10px;top:5px;width:260px;height:30px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border: 1px solid rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
            <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">WONo :</p>
            <span id="wo_WONo" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
            <button type="button" class="remScnt"><i class="fa fa-trash-o"></i></button>
        </div>
        <div class="drsElement drsMoveHandle drsGroupItem" data-name="Workorderdate field" style="left:10px;top:40px;width:260px;height:30px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border: 1px solid rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
            <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">WODate :</p>
            <span id="wo_WODate" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
            <button type="button" class="remScnt"><i class="fa fa-trash-o"></i></button>
        </div>
        <button type="button" class="remScnt"><i class="fa fa-trash-o"></i></button>
    </div>
    <div class="drsElement drsMoveHandle drsItem" data-name="Project det" style="left:10px;top:260px;width:300px;height:150px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
        <div class="drsElement drsMoveHandle drsGroupItem" data-name="Projectname field" style="left:10px;top:5px;width:260px;height:30px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
            <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px;font-weight:normal;">Project Name :</p>

            <span id="wo_ProjectName" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
            <button type="button" class="remScnt"><i class="fa fa-trash-o"></i></button>
        </div>
        <div class="drsElement drsMoveHandle drsGroupItem" data-name="Projectdesc field" style="left:10px;top:40px;width:260px;height:100px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
            <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px;font-weight:normal;">Project Description :</p>
            <span id="wo_ProjectDescription" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
            <button type="button" class="remScnt"><i class="fa fa-trash-o"></i></button>
        </div>
        <button type="button" class="remScnt"><i class="fa fa-trash-o"></i></button>
    </div>
    <div class="drsElement drsMoveHandle drsItem" data-name="Client det" style="left:10px;top:419px;width:300px;height:180px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);">
        <div class="drsElement drsMoveHandle drsGroupItem" data-name="clientname field" style="left:10px;top:5px;width:260px;height:30px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
            <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">ClientName :</p>
            <span id="wo_ClientName" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
            <button type="button" class="remScnt"><i class="fa fa-trash-o"></i></button>
        </div>
        <div class="drsElement drsMoveHandle drsGroupItem" data-name="clientaddress field" style="left:10px;top:40px;width:260px;height:110px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
            <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;"></p>
            <span id="wo_ClientAddress" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
            <button type="button" class="remScnt"><i class="fa fa-trash-o"></i></button>
        </div>
        <button type="button" class="remScnt"><i class="fa fa-trash-o"></i></button>
    </div>
    <div class="drsElement drsMoveHandle drsItem" data-name="Agreement det" style="left:310px;top:118px;width:380px;height:355px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
        <div class="drsElement drsMoveHandle drsGroupItem" data-name="Agreementno field" style="left:10px;top:5px;width:330px;height:30px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
            <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">AgreementNo :</p>
            <span id="wo_AgreementNo"style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
            <button type="button" class="remScnt"><i class="fa fa-trash-o" style="!important"></i></button>
        </div>
        <div class="drsElement drsMoveHandle drsGroupItem" data-name="Agreementdate field" style="left:10px;top:40px;width:330px;height:30px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
            <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">Agreement Date :</p>
            <span id="wo_AgreementDate" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
            <button type="button" class="remScnt"><i class="fa fa-trash-o" style="!important"></i></button>
        </div>
        <div class="drsElement drsMoveHandle drsGroupItem" data-name="Authorityname field" style="left:10px;top:75px;width:330px;height:30px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
            <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">Authority Name :</p>
            <span id="wo_AuthorityName" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
            <button type="button" class="remScnt"><i class="fa fa-trash-o" style="!important"></i></button>
        </div>
        <div class="drsElement drsMoveHandle drsGroupItem" data-name="Projectdur field" style="left:10px;top:110px;width:330px;height:30px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
            <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">Project Duration :</p>
            <span id="wo_Duration" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
            <button type="button" class="remScnt"><i class="fa fa-trash-o" style="!important"></i></button>
        </div>
        <div class="drsElement drsMoveHandle drsGroupItem" data-name="ActualCommencement field" style="left:10px;top:145px;width:330px;height:30px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
            <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">Date of Actual Commencement :</p>
            <span id="wo_StartDate" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
            <button type="button" class="remScnt"><i class="fa fa-trash-o" style="!important"></i></button>
        </div>
        <div class="drsElement drsMoveHandle drsGroupItem" data-name="Stipulateddate field" style="left:10px;top:180px;width:330px;height:30px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
            <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">Stipulated Date of Completion :</p>
            <span id="wo_EndDate" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
            <button type="button" class="remScnt"><i class="fa fa-trash-o" style="!important"></i></button>
        </div>
        <div class="drsElement drsMoveHandle drsGroupItem" data-name="AgreementType field" style="left:10px;top:215px;width:330px;height:30px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
            <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">AgreementType :</p>
            <span id="wo_AgreementType" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
            <button type="button" class="remScnt"><i class="fa fa-trash-o" style="!important"></i></button>
        </div>
        <div class="drsElement drsMoveHandle drsGroupItem" data-name="AuthorityAddress field" style="left:10px;top:250px;width:330px;height:30px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
            <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">AuthorityAddress :</p>
            <span id="wo_AuthorityAddress" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px;font-weight:normal;"></span>
            <button type="button" class="remScnt"><i class="fa fa-trash-o" style="!important"></i></button>
        </div>
        <div class="drsElement drsMoveHandle drsGroupItem" data-name="Quotation% field" style="left:10px;top:285px;width:330px;height:30px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
            <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">Quotation % :</p>
            <span id="wo_OrderPercent" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
            <button type="button" class="remScnt"><i class="fa fa-trash-o" style="!important"></i></button>
        </div>
        <div class="drsElement drsMoveHandle drsGroupItem" data-name="QuotationAmt field" style="left:10px;top:320px;width:330px;height:30px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
            <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px;font-weight:normal;">Quotation Amount :</p>
            <span id="wo_OrderAmount" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
            <button type="button" class="remScnt"><i class="fa fa-trash-o" style="!important"></i></button>
        </div>
        <button type="button" class="remScnt"><i class="fa fa-trash-o"></i></button>
    </div>
    <div class="drsElement drsMoveHandle drsItem" data-name="Company det" style="left:310px;top:470px;width:380px;height:127px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
        <div class="drsElement drsMoveHandle drsGroupItem" data-name="Companyaddress field" style="left:10px;top:5px;width:330px;height:110px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);border-width:1px;border-style:solid;border-color:rgb(0, 0, 0);">
            <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;"> Company Address :</p>
            <span id="wo_Address" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px ;font-weight:normal;"></span>
            <button type="button" class="remScnt"><i class="fa fa-trash-o" style="!important"></i></button>
        </div>
        <button type="button" class="remScnt"><i class="fa fa-trash-o"></i></button>
    </div>
</div>

        