<!--STYLE-->
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css';?>"/>
<style>
.radio_check label {
	text-align:left !important;
}
</style>
<div class="content_wrapper padlr0">
  <div class="container-fluid padlr0">
    <div class="col-lg-12 clear">
      <h1 class="text-center">Bid Win</h1>
      <div class="col-lg-4 col-lg-offset-4 col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 top_ct">
        <form class="form-horizontal">
          <div class="row">
            <div class="form-group">
              <div class="col-lg-12">
                <input type="text" name="LeadDate" id="date" class="form-control lbl_move" label="Bid Value"/>
              </div>
            </div>
            <div class="form-group">
              <div class="col-lg-12">
                <input type="text" name="LeadDate" id="date" class="form-control lbl_move" label="Competitor Name"/>
              </div>
            </div>
            <div class="form-group">
              <div class="col-lg-12">
                <input type="text" name="LeadDate" id="date" class="form-control lbl_move" label="Competitor Price"/>
              </div>
            </div>
            <div class="form-group">
              <div class="col-lg-12">
                <textarea class="form-control lbl_move" label="Remarks"></textarea>
              </div>
            </div>
            <div class="radio_check col-lg-12">
              <p>
                <input type="checkbox" name="uds_carper" id="boq"  value="boq" checked="checked">
                <label for="boq" class="ripple has-ripple">Do you want to update all Competitors Price</label>
              </p>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<div class="col-lg-12 savebtn_area">
  <ul>
    <li class="dropdown save_btn float_r"><a href="javascript:void(0);" data-toggle="tooltip" class="ripple" title="continue ">continue </a>
    <li class="cancel_btn float_r"><a href="javascript:void(0);">Cancel</a></li>
  </ul>
</div>
