<!--STYLE-->
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css';?>"/>
<div class="content_wrapper padlr0">
  <div class="container-fluid padlr0">
    <div class="col-lg-12 clear">
      <h1 class="text-center">Document Purchase</h1>
      <div class="col-lg-4 col-lg-offset-4 col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 top_ct">
        <form class="form-horizontal">
          <div class="row">
            <div class="form-group">
              <div class="col-lg-12">
                <input type="text" name="LeadDate" id="date" class="form-control lbl_move" label="Document Type"/>
              </div>
            </div>
            <div class="form-group">
              <div class="col-lg-12">
                <input type="text" name="LeadDate" id="date" class="form-control lbl_move" label="Document Name"/>
              </div>
            </div>
            <div class="form-group">
              <div class="col-lg-12">
                <input type="text" name="LeadDate" id="date" class="form-control lbl_move" label="Document Cost"/>
              </div>
            </div>
            <div class="form-group col-lg-12"> <span class="date_icon"><i class="fa fa-calendar"></i></span>
              <input type="text" name="lead_date" id="lead_date" class="form-control date_picker lbl_move" label="Date Time of Purchase" />
            </div>
            <div class="form-group">
              <div class="col-lg-12">
                <input type="text" name="LeadDate" id="date" class="form-control lbl_move" label="Hand over to	"/>
              </div>
            </div>
            <div class="form-group">
              <div class="col-lg-12">
                <textarea class="form-control lbl_move" label="Remarks"></textarea>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<div class="col-lg-12 savebtn_area">
  <ul>
    <li class="dropdown save_btn float_r"><a href="javascript:void(0);" data-toggle="tooltip" class="ripple" title="Save">Save</a>
    <li class="cancel_btn float_r"><a href="javascript:void(0);">Cancel</a></li>
  </ul>
</div>
