<!--STYLE-->
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css';?>"/>

<div class="content_wrapper padlr0">
  <div class="container-fluid padlr0">
    <div class="col-lg-12 clear">
      <h1>Work Order (BOQ)</h1>
      <div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0 top_ct">
        <div class="table-responsive topsp">
          <table class="table tableWithFloatingHeader" style=" margin-bottom:0px;">
            <thead>
              <tr>
                <th>Work group</th>
                <th>Serial No</th>
                <th>Description</th>
                <th>Unit</th>
                <th>Qty</th>
                <th>Base Rate</th>
                <th>Base Amount</th>
                <th>Quote Rate</th>
                <th>Quote Amount</th>
                <th>&nbsp;</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td width="5%"><input class="parent_text" type="text" /></td>
                <td width="5%"><input class="parent_text" type="text"/></td>
                <td width="8%"><input class="parent_text" type="text" /></td>
                <td width="8%"><input class="parent_text" type="text" /></td>
                <td width="4%"><input class="parent_text" type="text" /></td>
                <td width="4%"><input class="parent_text" type="text" /></td>
                <td width="8%"><input class="parent_text" type="text" /></td>
                <td width="8%"><input class="parent_text" type="text" /></td>
                <td width="8%"><input class="parent_text" type="text" /></td>
                <td width="1%" align="center"><ul class="action_btns">
                    <li> <a href="#" class="mainTr"> <i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete" ></i></a> </li>
                  </ul></td>
              </tr>
              <tr>
                <td width="5%"><input class="parent_text" type="text" /></td>
                <td width="5%"><input class="parent_text" type="text"/></td>
                <td width="8%"><input class="parent_text" type="text" /></td>
                <td width="8%"><input class="parent_text" type="text" /></td>
                <td width="4%"><input class="parent_text" type="text" /></td>
                <td width="4%"><input class="parent_text" type="text" /></td>
                <td width="8%"><input class="parent_text" type="text" /></td>
                <td width="8%"><input class="parent_text" type="text" /></td>
                <td width="8%"><input class="parent_text" type="text" /></td>
                <td width="1%" align="center"><ul class="action_btns">
                    <li> <a href="#" class="mainTr"> <i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete" ></i></a> </li>
                  </ul></td>
              </tr>
              <tr>
                <td width="5%"><input class="parent_text" type="text" /></td>
                <td width="5%"><input class="parent_text" type="text"/></td>
                <td width="8%"><input class="parent_text" type="text" /></td>
                <td width="8%"><input class="parent_text" type="text" /></td>
                <td width="4%"><input class="parent_text" type="text" /></td>
                <td width="4%"><input class="parent_text" type="text" /></td>
                <td width="8%"><input class="parent_text" type="text" /></td>
                <td width="8%"><input class="parent_text" type="text" /></td>
                <td width="8%"><input class="parent_text" type="text" /></td>
                <td width="1%" align="center"><ul class="action_btns">
                    <li> <a href="#" class="mainTr"> <i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete" ></i></a> </li>
                  </ul></td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td class="rate_pri" align="right">Total</td>
                <td><input class="parent_text" type="text" /></td>
                <td>&nbsp;</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <!--Excel-->
      <div class="fixed-action-btn active"> <a class="btn-floating btn-large"> <i class="fa fa-paperclip"></i> </a>
        <ul>
          <li> <a class="btn-floating hide-input-file" data-toggle="tooltip" data-placement="top" data-original-title="Import From Excel"> <i class="fa fa-file-excel-o"></i>
            <input type="file" name="myfile" id="myfile" class="input-large" accept=".xls, .xlsx, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" onchange="fileupload(this)">
            </a> </li>
          <li> <a class="btn-floating" href="/bsf_v1.0/public/uploads/project/sample/iow.xlsx" download data-toggle="tooltip" data-placement="top" data-original-title="Download Sample"> <i class="fa fa-download"></i> </a> </li>
        </ul>
      </div>
      <!--Excel end-->
      <div class="cont_bt col-lg-5 col-lg-offset-7 col-md-9 col-md-offset-3 col-sm-7 col-sm-offset-3 col-xs-7 col-xs-offset-4">
        <ul>
          <li><a href="#"> <i class="fa fa-check-circle"></i> Done</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
