<!--STYLE-->
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/mms.css';?>"/>
<script src="<?php echo $this->basePath(); ?>/js/slimscroll.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqx-all.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqxgrid.grouping.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqxgrid.aggregates.js"></script>
<style type="text/css">
	.mar_tp{margin-top:20px;}
    .jqx-grid-header {height:75px !important;}
</style>
<!--content-->
<div class="content_wrapper padlr0">
    <div class="container-fluid">
        <form method="post" action="<?php echo $this->basePath(); ?>/mms/transfer/tventry/0/0" id="formWrapper">
            <h1 class="col-lg-3 col-lg-offset-0 col-md-3 col-md-offset-0 col-sm-3 col-sm-offset-0 col-xs-12 col-xs-offset-0">Transfer Entry</h1>
            <div class="col-lg-2 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-4 col-sm-offset-0 col-xs-12 col-xs-offset-0">
                    <div class="radio_check">
                        <p>
                            <input type="radio"  class="ripple" value="0" id="Own" name="OwnOrCsm" checked />
                            <label for="Own" class="clr_fff">Despatch</label>
                        </p>
                    </div>
                </div>
			<div class="col-lg-12 mar_tp">
                <div class="col-lg-6 form-group req_flds">
                    <select style="width:100%;" class="single_dropdown lbl_move" label="From Project" name="from_project" id="from_project" >
                        <option value=""></option>
                        <?php if(isset($arr_fcc)):
                            foreach($arr_fcc as $costcentre): ?>
                                <option value="<?php echo $costcentre['CostCentreId'];?>"><?php echo $costcentre['CostCentreName'];?></option>
                            <?php endforeach;
                        endif; ?>
                    </select>
                    <div class="error_message"><p>Please select From Project...</p> </div>
                </div>
                <div class="col-lg-6 form-group req_flds">
                    <select style="width:100%;" class="single_dropdown lbl_move" label="To Project" name="to_project" id="to_project" >
                        <option value=""></option>
                        <?php if(isset($arr_fcc)):
                            foreach($arr_fcc as $costcentre): ?>
                                <option value="<?php echo $costcentre['CostCentreId'];?>"><?php echo $costcentre['CostCentreName'];?></option>
                            <?php endforeach;
                        endif; ?>
                    </select>
                    <div class="error_message"><p>Please select To Project...</p> </div>
                </div>
<!--                <div class="col-lg-6 form-group req_flds">-->
<!--                    <select style="width:100%;" class="single_dropdown lbl_move" data-bsfshare="From Project" label="From Project" name="from_project" id="from_project">-->
<!--                        <option value="0">select From Project </option>-->
<!--                    </select>-->
<!--                    <div class="error_message"><p>Please select From Project ...</p></div>-->
<!--                </div>-->
<!--            </div>-->
<!--            <div class="col-lg-12">-->
<!--                <div class="col-lg-6 form-group req_flds">-->
<!--                    <select style="width:100%;" class="single_dropdown lbl_move" label="To Company" name="to_company" id="to_company">-->
<!--                        <option value=""></option>-->
<!--                        --><?php //if(isset($arr_company)):
//                            foreach($arr_company as $company): ?>
<!--                                <option value="--><?php //echo $company['CompanyId'];?><!--">--><?php //echo $company['CompanyName'];?><!--</option>-->
<!--                            --><?php //endforeach;
//                        endif; ?>
<!--                    </select>-->
<!--                    <div class="error_message"><p>Please select Company..</p></div>-->
<!--                </div>-->
<!--                <div class="col-lg-6 form-group req_flds">-->
<!--                    <select style="width:100%;" label="To Project" style="width:100%;" class="single_dropdown lbl_move" name="to_project" id="to_project" >-->
<!--                        <option value="0"> select To Project </option>-->
<!--                    </select>-->
<!--                    <div class="error_message"><p>Please select To Project ...</p></div>-->
<!--                </div>-->
            </div>
            <div class="col-lg-12">
                <div class="col-lg-4 form-group req_flds">
                    <select class="form-control selectpicker show-tick" name="gridtype" id="gridtype" >
                        <option value="0" selected="true">Sequential View</option>
                        <option value="1">List View</option>
                    </select>
                    <div class="error_message"><p>Please select the priority...</p></div>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="col-lg-12 feed-bg">
                <div class="top-conts animated fadeInLeft col-lg-8 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0">
                    <h2>List of Requests.</h2>
                    <p>Selected Requests</p>
                    <span id="NoOfSelRequest">0</span>
                </div>
                <div class="col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-8 col-sm-4 col-sm-offset-8 col-xs-12 col-xs-offset-0">
                    <div class="cf search-wrapper">
                        <input type="text" class="search-btns form-group"  placeholder="Search by request no." id="searchRequestNo" style="width:100%;">
<!--                        <button type="submit"><i class="fa fa-search"></i></button>-->
                    </div>
                </div>
                <div class="div-overallscroll">
                    <div id="requestWrapper">
                        <p style="text-align: center;padding: 88px;">No data to display</p>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="col-lg-12 feed-bg mar_20">
                <div class="fil-til push_btm_20">
                    <h2 class="h1-head">List of resources from the selected Requests.</h2>
                    <p class="h1-head push_15">Selected Resources</p>
                    <span class=" h1-head push_15" id="NoOfSelResource">0</span>
                </div>
                <div id="resourceGrid" class="animated fadeInUp"></div>
            </div>
            <div class="clearfix"></div>
            <div class="clearfix"></div>
            <div id="requestTransInputsWrapper" class="hide"></div>
            <input type="hidden" name="frm_index" value="1"/>
        </form>
    </div>
</div>
<div class="col-lg-12 savebtn_area">
    <ul>
        <li id="continueButton" class="dropdown save_btn float_r"> <a onclick="validateOnSubmit();" class="ripple">Continue</a> </li>
        <li class="cancel_btn cancel_btn_bluecolor float_l"><a href="<?php echo $this->basePath() . '/mms/purchase/order';?>" class="ripple">Cancel</a></li>
    </ul>
</div>
<script type="text/template" id="request-template">
    <div class="col-lg-3 col-lg-offset-0 col-md-3 col-md-offset-0 col-sm-4 col-sm-offset-0 col-xs-12 col-xs-offset-0">
        <div class="three-box hvr-overline-from-center request-box zoomIn animated">
            <ul data-id="{{RequestId}}">
                <li><span>Request No</span>:&nbsp;{{RequestNo}}</li>
                <li><span>Cost Centre</span>:&nbsp;{{CostCentreName}}</li>
                <li><span>Approved On</span>:&nbsp;{{RequestDate}}</li>
            </ul>
            <span class="high-lit">R</span>
        </div>
    </div>
</script>
<script>
var sel_resource_count = 0;
var tmpLocalData = [];
var arr_requestIds = [];
var $resourceGrid = $("#resourceGrid");
var $searchRequestNo = $('#searchRequestNo');
var resourceSource = {
    localdata: [],
    dataType: "json",
    dataFields: [
        { name: 'Include', type: 'boolean' },
        { name: 'Desc', type: 'string' },
        { name: 'Quantity', type: 'string' },
        { name: 'RequestNo', type: 'string' },
        { name: 'RequestDate', type: 'date' },
        { name: 'RequestId', type: 'int' }
    ],
    id: 'RequestTransId'
};
var resourceAdapter = new $.jqx.dataAdapter(resourceSource);

$(function () {
    $('.div-overallscroll').slimScroll({
        position: 'right',
        height: '100%',
        width: '100%',
        alwaysVisible: false,
        railVisible: true,
        railColor: '#d7dabd',
        color: '#009688',
        railOpacity: 1
    });

    $('#from_project').on('change',function(){
        arr_requestIds = [];
        $searchRequestNo.val('');
        bindRequests();
    });
    $('#to_project').on('change',function(){
        arr_requestIds = [];
        $searchRequestNo.val('');
        bindRequests();
    });

    $('#OrderType').on('change',function(){
        $searchRequestNo.val('');

        if($(this).val() == 'service') {
            $('#vendorServiceListWrapper').show();
            $('#vendorServiceList').prop('disabled', false);

            $('#vendorContractListWrapper').hide();
            $('#vendorContractList').prop('disabled', true);
        } else {
            $('#vendorServiceListWrapper').hide();
            $('#vendorServiceList').prop('disabled', true);

            $('#vendorContractListWrapper').show();
            $('#vendorContractList').prop('disabled', false);
        }

        bindRequests();
    });

    $('#WorkType').on('change',function(){
        $searchRequestNo.val('');
        bindRequests();
    });

    $resourceGrid.jqxGrid({
        width: '100%',
        pageable: true,
        rowsheight: 35,
        selectionMode: 'singleRow',
        pagerButtonsCount: 6,
        autoheight:true,
        filterable: true,
        source: resourceAdapter,
        editable: true,
        pagerMode: 'advanced',
        pagerHeight: 40,
        sortable: true,
        altrows: false,
        enabletooltips: true,
        showfilterrow: true,
        showaggregates: true,
        keyboardnavigation: true,
        autorowheight: true,

        columns: [
            { dataField: 'RequestTransId', hidden: true},
            { dataField: 'RequestId', hidden: true},
            { text: '', dataField: 'Include', columntype: 'checkbox', align:'center',width:'5%'},
            { text: 'Resource Name', dataField: 'Desc',width:'35%', editable:false},
            { text: 'Qty', dataField: 'Quantity',width:'15%', editable:false},
            { text: 'Request No', dataField: 'RequestNo',width:'20%', editable:false},
            { text: 'Request Date', dataField: 'RequestDate',width:'25%', filtertype: 'date', cellsformat: 'dd-MM-yyyy' }
        ]
    });
    $resourceGrid.on('cellvaluechanged', function (event) {
        var args = event.args;
        var datarow = $resourceGrid.jqxGrid('getrowdata', args.rowindex);
        if(args.newvalue === true)
            sel_resource_count++;
        else
            sel_resource_count--;
        $('#NoOfSelResource').html(sel_resource_count);
        generateSelResourceInputs();
    });

    $('#OrderType').on('change', function () {
        if($(this).val() == 'work') {
            $('#WorkTypeWrapper').show();
        } else {
            $('#WorkTypeWrapper').hide();
        }
    });

    // request check and uncheck
    $('#requestWrapper').on('click','.request-box', function () {
        $(this).toggleClass('selected');
        renderSelectedResources($(this));
    });

    // search by request no.
    $searchRequestNo.on('keyup', function () {
        var requestNo = $.trim($(this).val());
        if(requestNo.length != 0 && tmpLocalData.length != 0) {
            var filtered_data = $.grep(tmpLocalData, function (o) {
                return new RegExp('^.*'+requestNo+'.*$','gi').test(o.RequestNo);
            });
            renderRequests(filtered_data);
        } else {
            renderRequests(tmpLocalData);
        }
    });

    // vendor select2
    $(".single_dropdown_vendor").select2({
        placeholder: "",
        templateResult: formatState,
        templateSelection: formatState,
        allowClear: true
    });
});

function formatState (state) {
    if (!state.id) { return state.text; }
    var $state = $('<span class="img-select"><img src="<?php echo $this->basePath() . '/images/avatar.jpg';?>" class="img-flag" /> ' + state.text + '</span>');
    return $state;
}

function bindRequests() {
    var tcostCentreId = $('#to_project').val();
    var oType = 'getrequest';
    var fcostCentreId = $("#from_project").val();

        if(fcostCentreId == tcostCentreId){
            alert("Choose a Valid Project");
            $('#from_project').val('');
            $('#from_project').trigger('change');

            $('#requestWrapper').html('<p style="text-align: center;padding: 88px;">No data to display</p>');
        } else {
            if(tcostCentreId != '' && tcostCentreId != null ){
                $.ajax({
                    url:getBaseURL()+'mms/transfer/tvwizard',
                    type:"post",
                    data:{'CostCentreId':tcostCentreId, 'Type': oType},
                    dataType:"json",
                    success:function(data, textStatus, jqXHR){
                        if(jqXHR.status == 200) {
                            $resourceGrid.jqxGrid('clear');
                            tmpLocalData = data.requests;
                            renderRequests(data.requests);
                            renderRequestResources(data.resources);
                        }
                    }
                });
            } else{
                $resourceGrid.jqxGrid('clear');
                $('#requestWrapper').html('<p style="text-align: center;padding: 88px;">No data to display</p>');
            }
        }

}

function renderRequests(data) {
    var $requestWrapper = $('#requestWrapper');
    if(data.length == 0) {
        $requestWrapper.html('<p style="text-align: center;padding: 88px;">No data to display</p>');
    } else {
        var template = $('#request-template').html();
        $requestWrapper.html('');
        $.each(data, function (i,o) {
            $requestWrapper.append(template.replace(/\{\{RequestNo\}\}/g,o.RequestNo)
                .replace(/\{\{CostCentreName\}\}/g,o.CostCentreName)
                .replace(/\{\{RequestDate\}\}/g,o.RequestDate)
                .replace(/\{\{RequestId\}\}/g,o.RequestId));
            if($.inArray(o.RequestId , arr_requestIds) != -1){
                $('ul[data-id='+o.RequestId+']').parent().addClass('selected');
            }
        });
    }
}

function renderRequestResources(data) {
    resourceSource.localdata = data;
    resourceAdapter.dataBind();
}
function renderSelectedResources(el) {
    var $selRequests = $('.request-box.selected');
    $('#NoOfSelRequest').html($selRequests.length);
    var reqId = el.find('ul[data-id]').attr('data-id');


    // select resources in grid
    if(el.hasClass('selected')) {
        sel_resource_count++;
        $.each(resourceSource.localdata, function (i, o) {
            if(parseInt(o.RequestId)==parseInt(reqId)) {
                o.Include = '1';
                if ($.inArray(o.RequestId, arr_requestIds) == -1) {
                    arr_requestIds.push(o.RequestId);
                }
            }
        });
    } else {
        sel_resource_count--;
        $.each(resourceSource.localdata, function (i, o) {
            if(parseInt(o.RequestId)==parseInt(reqId)) {
                o.Include = '0';
                var key1 = $.inArray(o.RequestId,arr_requestIds);
                arr_requestIds.splice(key1);
            }
        });
    }
    $('#NoOfSelResource').html(sel_resource_count);
    resourceAdapter.dataBind();
    generateSelResourceInputs();
}

function generateSelResourceInputs() {
    var rows = $resourceGrid.jqxGrid('getrows');
    var $inputs = '';
    for(var i = 0; i < rows.length; i++) {
        var row = rows[i];
        if (row.Include === true) {
            $inputs += '<input type="hidden" name="requestTransIds[]" class="requestTransIds" value="' + row.uid + '"/>';
        }
    }

    $('#requestTransInputsWrapper').html($inputs);
}

//$('#from_company').change(function() {
//    var fcompanyId = $(this).val();
//    if(fcompanyId != '' && fcompanyId != null && fcompanyId != 0){
//        $.ajax({
//            type: "POST",
//            url: getBaseURL()+'mms/transfer/tvwizard',
//            data: "fcompanyid="+fcompanyId+"&Type=fromCC",
//            dataType: "json",
//            success: function(data){
//                $("#from_project").html('');
//                $("#from_project").append("<option value='0'>Select From Project</option>");
//                $.each(data, function(i,v){
//                    $("#from_project").append("<option value='"+v.data+"'>"+v.value+"</option>");
//                });
//                $("#from_project").selectpicker('refresh');
//            }
//        });
//    }else{
//        $("#from_project").html("<option value='0'>Select From Project</option>");
//        $("#from_project").val(0).trigger('change');
//    }
//
//
//});
//
//$('#to_company').change(function() {
//    var tcompanyId = $(this).val();
//    if(tcompanyId != '' && tcompanyId != null && tcompanyId != 0) {
//        $.ajax({
//            type: "POST",
//            url: getBaseURL() + 'mms/transfer/tvwizard',
//            data: "fcompanyid=" + tcompanyId + "&Type=fromCC",
//            dataType: "json",
//            success: function (data) {
//                $("#to_project").html('');
//                $("#to_project").append("<option value='0'>Select To Project</option>");
//                $.each(data, function (i, v) {
//                    $("#to_project").append("<option value='" + v.data + "'>" + v.value + "</option>");
//                });
//                $("#to_project").selectpicker('refresh');
//            }
//        });
//    }else{
//        $("#to_project").html("<option value='0'>Select To Project</option>");
//        $("#to_project").val(0).trigger('change');
//    }
//});



//function fromccvalidation()
//{
//    var fccid = $('#from_project').val();
//    var tccid = $('#to_project').val();
//    if(fccid === tccid & fccid > 0 & tccid > 0) {
//        alert('Choose a valid from project');
//        $('#from_project').val(0);
//        $('#from_project').trigger('change');
//    }
//    if(fccid>0 & tccid>0){
//        $.ajax({
//            url:getBaseURL()+"mms/transfer/tvwizard",
//            type:"post",
//            data: "fccid=" + fccid + "&Type=resourcelist",
//            dataType:"json",
//            success:function(data, textStatus, jqXHR){
//                //alert(JSON.stringify(data))
//                var source =
//                {
//                    dataFields: [
//                        { name: 'Include', type: 'boolean' },
//                        { name: 'Code', type: 'string' },
//                        { name: 'Resource', type: 'string' },
//                        { name: 'Unit', type: 'string' },
//                        { name: 'ResourceId', type: 'number' },
//                        { name: 'ItemId', type: 'number' }
//
//                    ],
//                    localdata:data,
//                    id: 'ResourceId',
//                    datatype: "json",
//                    async: false
//                };
//
//                var reslist = new $.jqx.dataAdapter(source);
//
//                // creage jqxgrid
//                $("#resourceGrid").jqxGrid({
//                    width: '100%',
//                    autoheight:true,
//                    source: reslist,
//                    sortable: true,
//                    filterable: true,
//                    pageable: true,
//                    ready: function () {
//                    },
//                    columns: [
//
//                        { text: 'Include', dataField: 'Include'},
//                        { text: 'Code', dataField: 'Code' },
//                        { text: 'Resource', dataField: 'Resource' },
//                        { text: 'Unit', dataField: 'Unit' },
//                        { text: 'ResourceId', dataField: 'ResourceId' },
//                        { text: 'ItemId', dataField: 'ItemId' }
//                    ]
//                });
//
//            },
//            error:function(jqXHR, textStatus, errorThrown){
//                alert(textStatus+"-----"+errorThrown);
//            }
//        });
//    }
//}
//
//function toccvalidation()
//{
//    var fccid = $('#from_project').val();
//    var tccid = $('#to_project').val();
//    if(fccid === tccid & fccid > 0 & tccid > 0) {
//        alert('Choose a valid to project');
//        $('#to_project').val(0);
//        $('#to_project').trigger('change');
//    }
//
//    if(fccid>0 & tccid>0){
//        $.ajax({
//            url:getBaseURL()+"mms/transfer/tvwizard",
//            type:"post",
//            data: "fccid=" + fccid + "&Type=resourcelist",
//            dataType:"json",
//            success:function(data, textStatus, jqXHR){
//                //alert(JSON.stringify(data))
//                var source =
//                {
//                    dataFields: [
//                        { name: 'Include', type: 'boolean' },
//                        { name: 'Code', type: 'string' },
//                        { name: 'Resource', type: 'string' },
//                        { name: 'Unit', type: 'string' },
//                        { name: 'ResourceId', type: 'number'},
//                        { name: 'ItemId', type: 'number' }
//
//                    ],
//                    localdata:data,
//                    id: 'RequestTransId',
//                    datatype: "json",
//                    async: false
//                };
//
//                var reslist = new $.jqx.dataAdapter(source);
//
//                // creage jqxgrid
//                $("#resourceGrid").jqxGrid({
//                    width: '100%',
//                    autoheight:true,
//                    source: reslist,
//                    sortable: true,
//                    filterable: true,
//                    pageable: true,
//                    ready: function () {
//                    },
//                    columns: [
//                        { text: '', dataField: 'Include', columntype: 'checkbox', align:'center',width:'5%'},
//                        { text: 'Code', dataField: 'Code',editable: false },
//                        { text: 'Resource', dataField: 'Resource',editable: false },
//                        { text: 'Unit', dataField: 'Unit',editable:false },
//                        { text: 'ResourceId', dataField: 'ResourceId',hidden: true  },
//                        { text: 'ItemId', dataField: 'ItemId',hidden: true }
//                    ]
//                });
//
//            },
//            error:function(jqXHR, textStatus, errorThrown){
//                alert(textStatus+"-----"+errorThrown);
//            }
//        });
//    }
//}

function validateOnSubmit() {
    if ($('#from_company').val() == '' || $('#from_company').val() == 0) {
        alert('Please select from-company');
        return false;
    }
    if ($('#from_project').val() == '' || $('#from_project').val() == 0) {
        alert('Please select from-project');
        return false;
    }

    if ($('#to_company').val() == '' || $('#to_company').val() == 0) {
        alert('Please select to-company');
        return false;
    }
    if ($('#to_project').val() == '' || $('#to_project').val() == 0) {
        alert('Please select to-project');
        return false;
    }

    var rows = $resourceGrid.jqxGrid('getrows');
    var $inputs = '';
    for (var i = 0; i < rows.length; i++) {
        var row = rows[i];
        if (row.Include === true) {
            $inputs += '<input type="hidden" name="resIds[]" class="resIds" value="' + row.ResourceId + '"/>';
            $inputs += '<input type="hidden" name="itemIds[]" class="itemIds" value="' + row.ItemId + '"/>';
        }
    }
    $('#resTransInputsWrapper').html($inputs);

    $('#formWrapper').submit();
}
</script>