<div class="cb_login_body"></div>
<div class="cb_login_area login_area">
	<img src="<?php echo $this->basePath(); ?>/images/rabills_logo.png" class="login_logo" alt="" title="Ra-Bills" />
	<h1 class="txt_center">Activation Code</h1>
	<form action="" method="post" onsubmit="return codeValidate();">
	    <input type="hidden" name="csrf" value="<?php echo isset($csrf)?$csrf:''; ?>">
		<ul class="login_form cb_login_form">
			<li>
				<p class="txt_center">Enter the activation code to activate the account.</p>
			</li>
			<li class="login_input">
				<input type="text" id="code" name="code" autocomplete="off" value="" maxlength="6" style="text-transform:uppercase;" />
				<?php if($message=='1') { ?>
				<div class="error_message position_rel" style="display:block;"><p>Invalid Code!</p></div>
				<?php } ?>
				<div class="error_message position_rel text_error"><p>Please enter activation code</p></div>
			</li>
            <li class="text-center">
                <a href="<?php echo $this->basePath(); ?>/cb/index/logout">I'll activate later</a>
            </li>
			<li>
				<div class="login_load brad_2"><p><img src="<?php echo $this->basePath(); ?>/images/loading.gif" alt="" />Loading &nbsp;&nbsp;&nbsp;Please Wait!</p></div>
				<button type="submit" name="submit" class="signin_btn brad_2 ripple" value=""><span><img src="<?php echo $this->basePath(); ?>/images/signin_key.png" class="signin_key" alt="" title="Sign in" /></span></button>
			</li>
		</ul>
	</form>
</div>
<div class="cb_login_footer">
	<p class="txt_center">Copyright © <?php echo date('Y'); ?> RA-Bills.com. All Rights Reserved <img class="float_r" src="<?php echo $this->basePath(); ?>/images/bsf_flogo.jpg" alt="" /></p>
</div>
<script>
function codeValidate()
{
	$('.error_message').hide();
	if($('#code').val() == '') {
		$('#code').closest('.login_input').find(".text_error").show();
		$('#code').focus();
		$('.login_load').hide();
		$('.signin_btn').show();
		$('.login_input').css('opacity','1');
		return false;
	}
	$("form").submit();
	return true;
}
</script>