<div class="cb_login_body"></div>
<div class="cb_login_area login_area">
	<img src="<?php echo $this->basePath(); ?>/images/rabills_logo.png" class="login_logo" alt="" title="Ra-Bills" />
	<?php if($success==0) { ?>
	<h1 class="txt_center">Forget Password?</h1>
	<form action="" method="post" onsubmit="return forgotValidate();" autocomplete="off">
		<ul class="login_form cb_login_form">
			<li>
				<p class="txt_center">Enter the email address associated with your RA Build account. We'll send you a link to a page where you can easily create a new password.</p>
			</li>
			<li class="login_input">
				<p class="label_p"><label for="email">Email ID</label></p>
				<input type="text" id="email" name="email" autocomplete="off" value="" />
				<div class="error_message position_rel text_error"></div>
				<?php if($message=='1') { ?>
				<div class="error_message position_rel" style="display:block;"><p>this email is not exists!</p></div>
				<?php } ?>
			</li>
			<li>
				<div class="login_load brad_2"><p><img src="<?php echo $this->basePath(); ?>/images/loading.gif" alt="" />Loading &nbsp;&nbsp;&nbsp;Please Wait!</p></div>
				<button type="submit" name="submit" class="signin_btn brad_2 ripple" value=""><span><img src="<?php echo $this->basePath(); ?>/images/signin_key.png" class="signin_key" alt="" title="Sign in" /></span></button>
			</li>
            <li class="text-center" style="min-height: auto;">
                <a href="<?php echo $this->basePath(); ?>/cb/index/login">Back to login</a>
            </li>
		</ul>
	</form>
	<?php } else { ?>
	<ul class="login_form cb_login_form">
    	<li>
        	<img class="mail_icon" src="<?php echo $this->basePath(); ?>/images/mail_icon.png" alt=""/>
        </li>
		<li>
			<p class="txt_center">Check your mail, we have sent you a link to a page where you can easily create a new password.</p>
		</li>
	</ul>
	<?php } ?>
</div>
<div class="cb_login_footer">
	<p class="txt_center">Copyright © <?php echo date('Y'); ?> RA-Bills.com. All Rights Reserved <img class="float_r" src="<?php echo $this->basePath(); ?>/images/bsf_flogo.jpg" alt="" /></p>
</div>
<script>
function forgotValidate()
{
	$('.error_message').hide();
	$('.login_load').hide();
	$('.signin_btn').show();
	$('.login_input').css('opacity','1');
	if($('#email').val() == '') {
		$('#email').closest('.login_input').find(".text_error").show();
		$('#email').closest('.login_input').find(".text_error").html('<p>Required</p>');
		$('#email').focus();
		return false;
	} else if($('#email').val() != '' && validateEmail($('#email').val())==false) {
		$('#email').closest('.login_input').find(".text_error").show();
		$('#email').closest('.login_input').find(".text_error").html('<p>Please enter valid email id</p>');
		$('#email').focus();
		return false;
	}
	return true;
}
</script>