<div class="cb_login_body"></div>
<div class="cb_login_area login_area">
	<img src="<?php echo $this->basePath(); ?>/images/rabills_logo.png" class="login_logo" alt="" title="Ra-Bills" />
	<h1 class="txt_center">Sign In</h1>
	<p class="txt_center">Use your credentials to login and get access</p>
	<?php if(isset($messages)) {
		foreach($messages as $message) {
			foreach($message as $key=>$flash) { ?>
				<p class="txt_center <?php echo $key; ?>"><?php echo $flash; ?></p>
	<?php 	} 
		}
	}
	?>
	<form action="" method="post" onsubmit="return loginValidate();" autocomplete="off">
	    <input type="hidden" name="csrf" value="<?php echo isset($csrf)?$csrf:''; ?>">
		<ul class="login_form cb_login_form">
			<li class="login_input">
				<p class="label_p"><label for="username">Username</label></p>
				<input type="text" id="username" autocomplete="off" name="username" />
				<div class="error_message position_rel"></div>
			</li>
			<li class="login_input">
				<p class="label_p"><label for="password">Password</label></p>
				<input type="password" id="password" autocomplete="off" name="password" />
				<div class="error_message position_rel"></div>
			</li>
			<li>
				<div class="keepme_area brad_50 float_l">
					<input type="checkbox" class="keepme" id="keepme_login" value="1" />
					<label for="keepme_login"></label>
				</div>
				<p class="keepme_log ripple"><label for="keepme_login">Remember me</label></p>
			</li>
			<li>
				<div class="login_load brad_2"><p><img src="<?php echo $this->basePath(); ?>/images/loading.gif" alt="" />Loading &nbsp;&nbsp;&nbsp;Please Wait!</p></div>
				<button type="submit" name="submit" class="signin_btn brad_2 ripple" value=""><span><img src="<?php echo $this->basePath(); ?>/images/signin_key.png" class="signin_key" alt="" title="Sign in" /></span></button>
			</li>
		</ul>
	</form>
	<p><a href="<?php echo $this->basePath(); ?>/cb/index/forgot-password" class="forgetpwd_p ripple">Forgot password?</a><a href="<?php echo $this->basePath(); ?>/cb/index/signup" class="forgetpwd_p ripple">Don't have a <span class="span_bsf_hl">RA-Bills</span> Account ? Sign up.</a></p>
</div>
<div class="cb_login_footer">
	<p class="txt_center">Copyright © <?php echo date('Y'); ?> RA-Bills.com. All Rights Reserved </p>
    <img class="float_r" src="<?php echo $this->basePath(); ?>/images/bsf_flogo.jpg" alt="" />
</div>
<script>
function loginValidate()
{
	$('.error_message').hide();
	$('.login_load').hide();
	$('.signin_btn').show();
	$('.login_input').css('opacity','1');
	if($('#username').val() == '') {
		$('#username').closest('.login_input').find(".error_message").show();
		$('#username').closest('.login_input').find(".error_message").html('<p>Required</p>');
		$('#username').focus();
		return false;
	}
	if($('#password').val() == '') {
		$('#password').closest('.login_input').find(".error_message").show();
		$('#password').closest('.login_input').find(".error_message").html('<p>Required</p>');
		$('#password').focus();
		return false;
	}
	$("form").submit();
	return true;
}
</script>