<div class="content_wrapper padlr0">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="txt_center form_main_h1 frmwrk_h1">Request Entry</h1>
                <div class="col-lg-12 clear" style="margin:10px;">
                    <div class="col-lg-5 col-md-8 col-lg-offset-4">
                        <div >
                            <div>
                            <!--checkboxtabel-->              
                                <ul class="list ui-sortable" data-sortable="true">
                                    <li class="tile ui-sortable-handle">
                                        <div class="checkbox checkbox-styled tile-text">
                                            <label>
                                                <input checked="checked" type="checkbox">
                                                <span>
                                                	Do you want to load all resources? 
                                                </span>
                                            </label>
                                        </div>
                                    </li>
                                    <li class="tile ui-sortable-handle">
                                        <div class="checkbox checkbox-styled tile-text">
                                            <label>
                                            <input type="checkbox">
                                            <span>
                                            Do you want to group resources by sub group? 
                                            </span>
                                            </label>
                                        </div>
                                    </li>
                                    <li class="tile ui-sortable-handle">
                                        <div class="checkbox checkbox-styled tile-text">
                                            <label>
                                            <input type="checkbox">
                                            <span>
                                            Yes,I like to select particular WBS for this request 
                                            </span>
                                            </label>
                                        </div>
                                    </li>
                                    <li class="tile ui-sortable-handle">
                                        <div class="checkbox checkbox-styled tile-text">
                                            <label>
                                            <input type="checkbox">
                                            <span>
                                            Yes,I like to add remarks for each material 
                                            </span>
                                            </label>
                                        </div>
                                    </li>
                                    <li class="tile ui-sortable-handle">
                                        <div class="checkbox checkbox-styled tile-text">
                                        <label>
                                        <input type="checkbox">
                                        <span>
                                        Yes,I like to add requried date for each material 
                                        </span>
                                        </label>
                                        </div>
                                    </li>
                                </ul>
                            <!--end of checkboxtabel-->               
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-5 col-md-8 col-lg-offset-4">
            <div class="form-group">
                <label class="col-lg-5 col-md-6" style="font-size: 16px; font-weight:normal !important;margin-left:19px;">Select Resources From</label>
                <div class="col-lg-6 col-md-6">
                    <label class="radio-inline radio-styled">
                        <input type="radio" name="inlineRadioOptions" value="option1"><span style="font-size: 16px; font-weight:normal !important;">Public</span>
                    </label>
                    <label class="radio-inline radio-styled">
                        <input type="radio" name="inlineRadioOptions" value="option2"><span style="font-size: 16px; font-weight:normal !important;">Private</span>
                    </label>
                </div><!--end .col -->
            </div>
            <div class="form-group">
									<select id="select1" name="select1" class="form-control">
										<option value="">&nbsp;</option>
										<option value="30">30</option>
										<option value="40">40</option>
										<option value="50">50</option>
										<option value="60">60</option>
										<option value="70">70</option>
									</select>
									<label for="select1">Select</label>
								</div>
       </div>
    </div>
</div>
<!--save button--->
<div class="col-lg-12 savebtn_area">
    <ul>
        <li class="dropdown save_btn float_r">
            <a href="requestentrytable" class="ripple">Continue</a>
        </li>
        <li class="cancel_btn float_r"><a href="requestentry" class="ripple">Back</a></li>
    </ul>
</div>  