<div class="content_wrapper  padlr0">
	<div class="container-fluid">
    	<div class="row">
        	<div class="col-lg-12">
            	<h1>Request Entry</h1> 
            </div>
            <div class="col-lg-12 clear">
            	<div class="table-responsive clear col-lg-12">
                    <div class="matrix_table_area">
                        <table class="table matrix_table clear">
                            <thead>
                                <tr>
                                    <th class="headcol_l headcol_l1">Resource Description</th>
                                    <th><span data-placement="bottom" data-toggle="tooltip" data-original-title="Ground floor">Ground floor</span></th>
                                    <th><span data-placement="bottom" data-toggle="tooltip" data-original-title="First floor">First floor</span></th>
                                    <th><span data-placement="bottom" data-toggle="tooltip" data-original-title="Second floor">Second floor</span></th>
                                    <th><span data-placement="bottom" data-toggle="tooltip" data-original-title="Three floor">Three floor</span></th>
                                    <th><span data-placement="bottom" data-toggle="tooltip" data-original-title="Fourth floor">Fourth floor</span></th>
                                    <th><span data-placement="bottom" data-toggle="tooltip" data-original-title="Fiveth floor">Fiveth floor</span></th>
                                    <th><span data-placement="bottom" data-toggle="tooltip" data-original-title="Sixth floor">Sixth floor</span></th>
                                    <th><span data-placement="bottom" data-toggle="tooltip" data-original-title="Seventh floor">Seventh floor</span></th>
                                    <th><span data-placement="bottom" data-toggle="tooltip" data-original-title="Eighth floor">Eighth floor</span></th>
                                    <th><span data-placement="bottom" data-toggle="tooltip" data-original-title="Unit">Unit</span></th>
                                    <th><span data-placement="bottom" data-toggle="tooltip" data-original-title="Date">Date</span></th>
                                    <th><span data-placement="bottom" data-toggle="tooltip" data-original-title="Remarks">Remarks</span></th>
                                    <th><span data-placement="bottom" data-toggle="tooltip" data-original-title="Total">Total</span></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="headcol_l">Electric Materials</td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0125"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="bdr_left1ddd">
                                        Sqm
                                    </td>
                                    <td class="tbl_input_td">
                                        <div class="col-lg-12">
                                            <span class="date_icon matrix_date_icon"><i class="fa fa-calendar"></i></span>
                                            <input type="text" class="date_picker matrix_date_input" />
                                        </div>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" class="matrix_remarks_input" value="Very good...!!"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" name="total" class="matrix_total_input" value="12,252.00" readonly />
                                    </td>
                                </tr>
                                <tr>
                                    <td class="headcol_l">Electric Materials</td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="bdr_left1ddd">
                                        Sqm
                                    </td>
                                    <td class="tbl_input_td">
                                        <div class="col-lg-12">
                                            <span class="date_icon matrix_date_icon"><i class="fa fa-calendar"></i></span>
                                            <input type="text" class="date_picker matrix_date_input" />
                                        </div>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" class="matrix_remarks_input" value="Good"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" name="total" class="matrix_total_input" value="12,252.00" readonly />
                                    </td> 
                                </tr>
                                <tr>
                                    <td class="headcol_l">Electric Materials</td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0125"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="bdr_left1ddd">
                                        Sqm
                                    </td>
                                    <td class="tbl_input_td">
                                        <div class="col-lg-12">
                                            <span class="date_icon matrix_date_icon"><i class="fa fa-calendar"></i></span>
                                            <input type="text" class="date_picker matrix_date_input" />
                                        </div>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" class="matrix_remarks_input" value="Very good...!!"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" name="total" class="matrix_total_input" value="12,252.00" readonly />
                                    </td>
                                </tr>
                                <tr>
                                    <td class="headcol_l">Electric Materials</td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="bdr_left1ddd">
                                        Sqm
                                    </td>
                                    <td class="tbl_input_td">
                                        <div class="col-lg-12">
                                            <span class="date_icon matrix_date_icon"><i class="fa fa-calendar"></i></span>
                                            <input type="text" class="date_picker matrix_date_input" />
                                        </div>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" class="matrix_remarks_input" value="Good"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" name="total" class="matrix_total_input" value="12,252.00" readonly />
                                    </td> 
                                </tr>
                                <tr>
                                    <td class="headcol_l">Electric Materials</td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0125"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="bdr_left1ddd">
                                        Sqm
                                    </td>
                                    <td class="tbl_input_td">
                                        <div class="col-lg-12">
                                            <span class="date_icon matrix_date_icon"><i class="fa fa-calendar"></i></span>
                                            <input type="text" class="date_picker matrix_date_input" />
                                        </div>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" class="matrix_remarks_input" value="Very good...!!"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" name="total" class="matrix_total_input" value="12,252.00" readonly />
                                    </td>
                                </tr>
                                <tr>
                                    <td class="headcol_l">Electric Materials</td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="bdr_left1ddd">
                                        Sqm
                                    </td>
                                    <td class="tbl_input_td">
                                        <div class="col-lg-12">
                                            <span class="date_icon matrix_date_icon"><i class="fa fa-calendar"></i></span>
                                            <input type="text" class="date_picker matrix_date_input" />
                                        </div>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" class="matrix_remarks_input" value="Good"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" name="total" class="matrix_total_input" value="12,252.00" readonly />
                                    </td> 
                                </tr>
                                <tr>
                                    <td class="headcol_l">Electric Materials</td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0125"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="bdr_left1ddd">
                                        Sqm
                                    </td>
                                    <td class="tbl_input_td">
                                        <div class="col-lg-12">
                                            <span class="date_icon matrix_date_icon"><i class="fa fa-calendar"></i></span>
                                            <input type="text" class="date_picker matrix_date_input" />
                                        </div>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" class="matrix_remarks_input" value="Very good...!!"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" name="total" class="matrix_total_input" value="12,252.00" readonly />
                                    </td>
                                </tr>
                                <tr>
                                    <td class="headcol_l">Electric Materials</td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="bdr_left1ddd">
                                        Sqm
                                    </td>
                                    <td class="tbl_input_td">
                                        <div class="col-lg-12">
                                            <span class="date_icon matrix_date_icon"><i class="fa fa-calendar"></i></span>
                                            <input type="text" class="date_picker matrix_date_input" />
                                        </div>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" class="matrix_remarks_input" value="Good"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" name="total" class="matrix_total_input" value="12,252.00" readonly />
                                    </td> 
                                </tr>
                                <tr>
                                    <td class="headcol_l">Electric Materials</td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0125"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="bdr_left1ddd">
                                        Sqm
                                    </td>
                                    <td class="tbl_input_td">
                                        <div class="col-lg-12">
                                            <span class="date_icon matrix_date_icon"><i class="fa fa-calendar"></i></span>
                                            <input type="text" class="date_picker matrix_date_input" />
                                        </div>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" class="matrix_remarks_input" value="Very good...!!"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" name="total" class="matrix_total_input" value="12,252.00" readonly />
                                    </td>
                                </tr>
                                <tr>
                                    <td class="headcol_l">Electric Materials</td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="bdr_left1ddd">
                                        Sqm
                                    </td>
                                    <td class="tbl_input_td">
                                        <div class="col-lg-12">
                                            <span class="date_icon matrix_date_icon"><i class="fa fa-calendar"></i></span>
                                            <input type="text" class="date_picker matrix_date_input" />
                                        </div>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" class="matrix_remarks_input" value="Good"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" name="total" class="matrix_total_input" value="12,252.00" readonly />
                                    </td> 
                                </tr>
                                <tr>
                                    <td class="headcol_l">Electric Materials</td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0125"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="bdr_left1ddd">
                                        Sqm
                                    </td>
                                    <td class="tbl_input_td">
                                        <div class="col-lg-12">
                                            <span class="date_icon matrix_date_icon"><i class="fa fa-calendar"></i></span>
                                            <input type="text" class="date_picker matrix_date_input" />
                                        </div>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" class="matrix_remarks_input" value="Very good...!!"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" name="total" class="matrix_total_input" value="12,252.00" readonly />
                                    </td>
                                </tr>
                                <tr>
                                    <td class="headcol_l">Electric Materials</td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" value="0"/>
                                    </td>
                                    <td class="bdr_left1ddd">
                                        Sqm
                                    </td>
                                    <td class="tbl_input_td">
                                        <div class="col-lg-12">
                                            <span class="date_icon matrix_date_icon"><i class="fa fa-calendar"></i></span>
                                            <input type="text" class="date_picker matrix_date_input" />
                                        </div>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" class="matrix_remarks_input" value="Good"/>
                                    </td>
                                    <td class="tbl_input_td">
                                        <input type="text" name="total" class="matrix_total_input" value="12,252.00" readonly />
                                    </td> 
                                </tr>
                            </tbody>
                        </table>
                	</div>
				</div>
			</div> 
		</div>
	</div>
</div>
<!--button-->
<div class="col-lg-12 savebtn_area">
    <ul>
        <li class="dropdown save_btn float_r">
            <a href="vendorcapability" class="ripple">Submit</a>
        </li>
        <li class="cancel_btn float_r"><a href="vendorBranchdetail" class="ripple">Back</a></li>
    </ul>
</div>



<!--<style>
.matrix_width {
    border: 1px solid #ccc;
    border-radius: 4px;
    padding: 8px 4px;
    transition: border-color 1s ease 0s;
	width:75px;
}
.matrix_width:focus {
    border-color: #66afe9;
    outline: 0 none;
}
                .mathi { 
            width: 750px; 
            overflow-x:scroll;  
            margin-left:5em; 
            overflow-y:visible;
            padding-bottom:1px;
        }
        .headcol {
            position:absolute; 
            width:5em; 
            left:0;
            top:auto;
            border-right: 0px none black; 
            border-top-width:3px; /*only relevant for first row*/
            margin-top:-3px; /*compensate for top border*/
        }
		.headcolumn {
            position:absolute; 
            width:5em; 
            left:1052px;
            top:auto;
            border-right: 0px none black; 
            border-top-width:3px; /*only relevant for first row*/
            margin-top:-1px; /*compensate for top border*/
        }
		.headcolumn3 {
            position:absolute; 
            width:5em; 
            left:962px;
            top:auto;
            border-right: 0px none black; 
            border-top-width:3px; /*only relevant for first row*/
            margin-top:-1px; /*compensate for top border*/
        }
		.headcolumn1 {
            position:absolute; 
            width:5em; 
            left:828px;
            top:auto;
            border-right: 0px none black; 
            border-top-width:3px; /*only relevant for first row*/
            margin-top:-1px; /*compensate for top border*/
        }
		.headcolumn2 {
            position:absolute; 
            width:5em; 
            left:865px;
            top:auto;
            border-right: 0px none black; 
            border-top-width:3px; /*only relevant for first row*/
            margin-top:-1px; /*compensate for top border*/
        }
 
</style>
<div class="content_wrapper  padlr0">
			<div class="container-fluid">
                 <div class="row">
                      <div class="col-lg-12">
                            <h1 class="padbtm0">Experience Detail </h1> 
                      </div>
                      <div class="col-lg-12 clear">
              			<div class="table-responsive clear">
                        	<div class="mathi">
                              <table class="table table-hover vendar_bottom clear" id="table">
                                    <thead>
                                              <tr>
                                                <th>Ground Floor</th>
                                                <th>First<br /> Floor</th>
                                                <th>Second Floor</th>
                                                <th>Fourth Floor</th>
                                                <th>Fifth<br /> Floor</th>
                                                <th>Sixth<br /> Floor</th>
                                                <th>seventh Floor</th>
                                                <th>Eigth<br /> Floor</th>
                                                <th>Ninth<br /> Floor</th>
                                                <th>Tenth<br /> Floor</th>
                                              </tr>
                                         </thead>
                                         <tbody>
                                    <tr><td class="headcol">material 1</td></tr>
                                    <tr><td class="headcol">material 2</td></tr>
                                    <tr><td class="headcol">material 3</td></tr>
                                    <tr><td class="headcol">material 4</td></tr>
                                    <tr><td class="headcol">material 5</td></tr>     
                                    <tr>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="headcolumn1">sqm</td>
                                        <td class="headcolumn2"><input class=" matrix_width" type="text" /></td>
                                        <td class="headcolumn3"><input class=" matrix_width" type="text" /></td>
                                        <td class="headcolumn"><input class=" matrix_width" type="text" /></td>
                                    </tr>
                                    <tr>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="headcolumn1">sqm</td>
                                        <td class="headcolumn2"><input class=" matrix_width" type="text" /></td>
                                        <td class="headcolumn3"><input class=" matrix_width" type="text" /></td>
                                        <td class="headcolumn"><input class=" matrix_width" type="text" /></td>
                                    </tr>
                                    <tr>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="headcolumn1">sqm</td>
                                        <td class="headcolumn2"><input class=" matrix_width" type="text" /></td>
                                        <td class="headcolumn3"><input class=" matrix_width" type="text" /></td>
                                        <td class="headcolumn"><input class=" matrix_width" type="text" /></td>
                                    </tr>
                                    <tr>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="headcolumn1">sqm</td>
                                        <td class="headcolumn2"><input class=" matrix_width" type="text" /></td>
                                        <td class="headcolumn3"><input class=" matrix_width" type="text" /></td>
                                        <td class="headcolumn"><input class=" matrix_width" type="text" /></td>
                                    </tr>
                                    <tr>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="long"><input class=" matrix_width" type="text" /></td>
                                        <td class="headcolumn1">sqm</td>
                                        <td class="headcolumn2"><input class=" matrix_width" type="text" /></td>
                                        <td class="headcolumn3"><input class=" matrix_width" type="text" /></td>
                                        <td class="headcolumn"><input class=" matrix_width" type="text" /></td>
                                    </tr>
                                    </tbody>
                               </table>
                            </div>     
                          </div>
                     </div> 
                </div>
             </div>
        </div>
<!--button--
<div class="col-lg-12 savebtn_area">
    <ul>
        <li class="dropdown save_btn float_r">
            <a href="vendorcapability" class="ripple">Submit</a>
        </li>
        <li class="cancel_btn float_r"><a href="vendorBranchdetail" class="ripple">Back</a></li>
    </ul>
</div>-->