<style type="text/css">
    .table-responsive {overflow-x: inherit !important;}
</style>
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/mms.css';?>"/>
<div class="content_wrapper">
    <div class="container-fluid">
        <form id="subLedgerForm" method="post">
            <div class="col-lg-12">
                <h1 class="txt_center">SubLedger Balance</h1>
                <input type="hidden"  name="accountId" id="accountId" value="<?php echo (isset($accountId)? $accountId : 0); ?>"/>
                <div class="row" id="divAccount">
                    <div class="col-lg-12 padlr0">
                        <div class="table-responsive top-20 mar_btm">
                            <table class="table" style=" margin-bottom:0px;">
                                <thead>
                                <tr>
                                    <th>SubLedger Name</th>
                                    <th>Debit</th>
                                    <th>Credit</th>
                                    <th>&nbsp;</th>
                                </tr>
                                </thead>
                                <tbody class="main" id="accountTable">
                                <tr>
                                    <td width="50%">
                                        <input class="parent_text border-none" type="text" id="" name="subledgername" value="0" onchange="" onkeypress="" onblur=""/>
                                    </td>
                                    <td width="20%">
                                        <input  class="parent_text border-none"type="text" id="" name="debit" value="0" onchange="" onkeypress="" onblur=""/>
                                    </td>
                                    <td width="20%">
                                        <input class="parent_text border-none" style="text-align:right;" type="text" name="credit" id="" value="0.0" readonly>
                                    </td>
                                    <td width="6%" align="center" class="action_btns_td" style="border:none !important;">
                                        <ul class="action_btns">
                                            <li><a href="#" class="mainTr" id="expandTr__" style="cursor:pointer;"><i class="fa fa-chevron-circle-down" data-toggle="tooltip" data-placement="left" data-original-title="" ></i></a> </li>
                                        </ul>
                                    </td>
                                </tr>
                                <tr class="subTr" style="display: none;">
                                    <td colspan="9" style="padding:0px !important;">
                                        <div class="subDiv" style="display: none;">
                                            <div class="col-lg-12 col-lg-offset-0 rdbt" style="margin-top:5px;">
                                                <div class="table-responsive topsp">
                                                    <table class="table " style="margin-bottom:0px;" bgcolor="#00FF00" id="">
                                                        <thead>
                                                        <tr>
                                                            <th>Bill No</th>
                                                            <th>Bill Date</th>
                                                            <th>Costcentre</th>
                                                            <th>Bill Amount</th>
                                                            <th>Type</th>
                                                            <th>Branch</th>
                                                        </tr>
                                                        </thead>
                                                        <tbody class="main">
                                                        <tr>
                                                            <td width="15%">
                                                                <input  class="parent_text border-none"type="text" id="" name="billno" value="0" onchange="calcAmount();" onkeypress="return isDecimal(event,this)" onblur="return FormatNum(this, 2, true)"/>
                                                            </td>
                                                            <td width="15%">
                                                                <div class="col-lg-12 padlr0">
                                                                    <input type="text" name="billdate" id="" class="tbl_input date_picker" style="cursor:pointer;" value='<?php echo Date('d/m/Y'); ?>' />
                                                                    <span class="date_icon"><i class="fa fa-calendar"></i></span>
                                                                </div>
                                                            </td>
                                                            <td width="20%">
                                                                <select data-placeholder="" class="form-control single_dropdown2 lbl_box sortoption tbl_input" name="costcentre" id="">
                                                                    <option value="0">Costcentre</option>
                                                                    <option value="1">1</option>
                                                                </select>
                                                            </td>
                                                            <td width="15%">
                                                                <input class="parent_text border-none"type="text" id="" name="billamount" value="0" onchange="" onkeypress="" onblur=""/>
                                                            </td>
                                                            <td width="15%">
                                                                <select data-placeholder="" class="form-control single_dropdown2 lbl_box sortoption tbl_input" name="type" id="">
                                                                    <option value="0">Type</option>
                                                                    <option value="1">1</option>
                                                                </select>
                                                            </td>
                                                            <td width="15%">
                                                                <select data-placeholder="" class="form-control single_dropdown2 lbl_box sortoption tbl_input" name="branch" id="">
                                                                    <option value="0">Branch</option>
                                                                    <option value="1">1</option>
                                                                </select>
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td width="15%">
                                                                <input  class="parent_text border-none"type="text" id="" name="billno" value="0" onchange="calcAmount();" onkeypress="return isDecimal(event,this)" onblur="return FormatNum(this, 2, true)"/>
                                                            </td>
                                                            <td width="15%">
                                                                <div class="col-lg-12 padlr0">
                                                                    <input type="text" name="billdate" id="" class="tbl_input date_picker" style="cursor:pointer;" value='<?php echo Date('d/m/Y'); ?>' />
                                                                    <span class="date_icon"><i class="fa fa-calendar"></i></span>
                                                                </div>
                                                            </td>
                                                            <td width="20%">
                                                                <select data-placeholder="" class="form-control single_dropdown2 lbl_box sortoption tbl_input" name="costcentre" id="">
                                                                    <option value="0">Costcentre</option>
                                                                    <option value="1">1</option>
                                                                </select>
                                                            </td>
                                                            <td width="15%">
                                                                <input class="parent_text border-none"type="text" id="" name="billamount" value="0" onchange="" onkeypress="" onblur=""/>
                                                            </td>
                                                            <td width="15%">
                                                                <select data-placeholder="" class="form-control single_dropdown2 lbl_box sortoption tbl_input" name="type" id="">
                                                                    <option value="0">Type</option>
                                                                    <option value="1">1</option>
                                                                </select>
                                                            </td>
                                                            <td width="15%">
                                                                <select data-placeholder="" class="form-control single_dropdown2 lbl_box sortoption tbl_input" name="branch" id="">
                                                                    <option value="0">Branch</option>
                                                                    <option value="1">1</option>
                                                                </select>
                                                            </td>
                                                        </tr>
                                                        </tbody>
                                                        <tbody class="total">
                                                            <tr>
                                                                <td colspan="6">
                                                                    <button id="continue" class="nx-btn float_r"><a href="javascript:void(0);" onclick="submitForm()" class="ripple">Save</a></button>
                                                                </td>
                                                            </tr>
                                                        </tbody>
                                                        <input type="hidden" name="iow___rowid" id="iow___rowid" value="0"/>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </td>

                                </tr>

                                <tr>
                                    <td width="50%">
                                        <input class="parent_text border-none" type="text" id="" name="subledgername" value="0" onchange="" onkeypress="" onblur=""/>
                                    </td>
                                    <td width="20%">
                                        <input  class="parent_text border-none"type="text" id="" name="debit" value="0" onchange="" onkeypress="" onblur=""/>
                                    </td>
                                    <td width="20%">
                                        <input class="parent_text border-none" style="text-align:right;" type="text" name="credit" id="" value="0.0" readonly>
                                    </td>
                                    <td width="6%" align="center" class="action_btns_td" style="border:none !important;">
                                        <ul class="action_btns">
                                            <li><a href="#" class="mainTr" id="expandTr__" style="cursor:pointer;"><i class="fa fa-chevron-circle-down" data-toggle="tooltip" data-placement="left" data-original-title="" ></i></a> </li>
                                        </ul>
                                    </td>
                                </tr>
                                <tr class="subTr" style="display: none;">
                                    <td colspan="9" style="padding:0px !important;">
                                        <div class="subDiv" style="display: none;">
                                            <div class="col-lg-12 col-lg-offset-0 rdbt" style="margin-top:5px;">
                                                <div class="table-responsive topsp">
                                                    <table class="table " style="margin-bottom:0px;" bgcolor="#00FF00" id="">
                                                        <thead>
                                                        <tr>
                                                            <th>Bill No</th>
                                                            <th>Bill Date</th>
                                                            <th>Costcentre</th>
                                                            <th>Bill Amount</th>
                                                            <th>Type</th>
                                                            <th>Branch</th>
                                                        </tr>
                                                        </thead>
                                                        <tbody class="main">
                                                        <tr>
                                                            <td width="15%">
                                                                <input  class="parent_text border-none"type="text" id="" name="billno" value="0" onchange="calcAmount();" onkeypress="return isDecimal(event,this)" onblur="return FormatNum(this, 2, true)"/>
                                                            </td>
                                                            <td width="15%">
                                                                <div class="col-lg-12 padlr0">
                                                                    <input type="text" name="billdate" id="" class="tbl_input date_picker" style="cursor:pointer;" value='<?php echo Date('d/m/Y'); ?>' />
                                                                    <span class="date_icon"><i class="fa fa-calendar"></i></span>
                                                                </div>
                                                            </td>
                                                            <td width="20%">
                                                                <select data-placeholder="" class="form-control single_dropdown2 lbl_box sortoption tbl_input" name="costcentre" id="">
                                                                    <option value="0">Costcentre</option>
                                                                    <option value="1">1</option>
                                                                </select>
                                                            </td>
                                                            <td width="15%">
                                                                <input class="parent_text border-none"type="text" id="" name="billamount" value="0" onchange="" onkeypress="" onblur=""/>
                                                            </td>
                                                            <td width="15%">
                                                                <select data-placeholder="" class="form-control single_dropdown2 lbl_box sortoption tbl_input" name="type" id="">
                                                                    <option value="0">Type</option>
                                                                    <option value="1">1</option>
                                                                </select>
                                                            </td>
                                                            <td width="15%">
                                                                <select data-placeholder="" class="form-control single_dropdown2 lbl_box sortoption tbl_input" name="branch" id="">
                                                                    <option value="0">Branch</option>
                                                                    <option value="1">1</option>
                                                                </select>
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td width="15%">
                                                                <input  class="parent_text border-none"type="text" id="" name="billno" value="0" onchange="calcAmount();" onkeypress="return isDecimal(event,this)" onblur="return FormatNum(this, 2, true)"/>
                                                            </td>
                                                            <td width="15%">
                                                                <div class="col-lg-12 padlr0">
                                                                    <input type="text" name="billdate" id="" class="tbl_input date_picker" style="cursor:pointer;" value='<?php echo Date('d/m/Y'); ?>' />
                                                                    <span class="date_icon"><i class="fa fa-calendar"></i></span>
                                                                </div>
                                                            </td>
                                                            <td width="20%">
                                                                <select data-placeholder="" class="form-control single_dropdown2 lbl_box sortoption tbl_input" name="costcentre" id="">
                                                                    <option value="0">Costcentre</option>
                                                                    <option value="1">1</option>
                                                                </select>
                                                            </td>
                                                            <td width="15%">
                                                                <input class="parent_text border-none"type="text" id="" name="billamount" value="0" onchange="" onkeypress="" onblur=""/>
                                                            </td>
                                                            <td width="15%">
                                                                <select data-placeholder="" class="form-control single_dropdown2 lbl_box sortoption tbl_input" name="type" id="">
                                                                    <option value="0">Type</option>
                                                                    <option value="1">1</option>
                                                                </select>
                                                            </td>
                                                            <td width="15%">
                                                                <select data-placeholder="" class="form-control single_dropdown2 lbl_box sortoption tbl_input" name="branch" id="">
                                                                    <option value="0">Branch</option>
                                                                    <option value="1">1</option>
                                                                </select>
                                                            </td>
                                                        </tr>
                                                        </tbody>
                                                        <tbody class="total">
                                                        <tr>
                                                            <td colspan="6">
                                                                <button id="continue" class="nx-btn float_r"><a href="javascript:void(0);" onclick="submitForm()" class="ripple">Save</a></button>
                                                            </td>
                                                        </tr>
                                                        </tbody>
                                                        <input type="hidden" name="iow___rowid" id="iow___rowid" value="0"/>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </td>

                                </tr>
                                <tr>
                                    <td width="50%">
                                        <input class="parent_text border-none" type="text" id="" name="subledgername" value="0" onchange="" onkeypress="" onblur=""/>
                                    </td>
                                    <td width="20%">
                                        <input  class="parent_text border-none"type="text" id="" name="debit" value="0" onchange="" onkeypress="" onblur=""/>
                                    </td>
                                    <td width="20%">
                                        <input class="parent_text border-none" style="text-align:right;" type="text" name="credit" id="" value="0.0" readonly>
                                    </td>
                                    <td width="6%" align="center" class="action_btns_td" style="border:none !important;">
                                        <ul class="action_btns">
                                            <li><a href="#" class="mainTr" id="expandTr__" style="cursor:pointer;"><i class="fa fa-chevron-circle-down" data-toggle="tooltip" data-placement="left" data-original-title="" ></i></a> </li>
                                        </ul>
                                    </td>
                                </tr>
                                <tr class="subTr" style="display: none;">
                                    <td colspan="9" style="padding:0px !important;">
                                        <div class="subDiv" style="display: none;">
                                            <div class="col-lg-12 col-lg-offset-0 rdbt" style="margin-top:5px;">
                                                <div class="table-responsive topsp">
                                                    <table class="table " style="margin-bottom:0px;" bgcolor="#00FF00" id="">
                                                        <thead>
                                                        <tr>
                                                            <th>Bill No</th>
                                                            <th>Bill Date</th>
                                                            <th>Costcentre</th>
                                                            <th>Bill Amount</th>
                                                            <th>Type</th>
                                                            <th>Branch</th>
                                                        </tr>
                                                        </thead>
                                                        <tbody class="main">
                                                        <tr>
                                                            <td width="15%">
                                                                <input  class="parent_text border-none"type="text" id="" name="billno" value="0" onchange="calcAmount();" onkeypress="return isDecimal(event,this)" onblur="return FormatNum(this, 2, true)"/>
                                                            </td>
                                                            <td width="15%">
                                                                <div class="col-lg-12 padlr0">
                                                                    <input type="text" name="billdate" id="" class="tbl_input date_picker" style="cursor:pointer;" value='<?php echo Date('d/m/Y'); ?>' />
                                                                    <span class="date_icon"><i class="fa fa-calendar"></i></span>
                                                                </div>
                                                            </td>
                                                            <td width="20%">
                                                                <select data-placeholder="" class="form-control single_dropdown2 lbl_box sortoption tbl_input" name="costcentre" id="">
                                                                    <option value="0">Costcentre</option>
                                                                    <option value="1">1</option>
                                                                </select>
                                                            </td>
                                                            <td width="15%">
                                                                <input class="parent_text border-none"type="text" id="" name="billamount" value="0" onchange="" onkeypress="" onblur=""/>
                                                            </td>
                                                            <td width="15%">
                                                                <select data-placeholder="" class="form-control single_dropdown2 lbl_box sortoption tbl_input" name="type" id="">
                                                                    <option value="0">Type</option>
                                                                    <option value="1">1</option>
                                                                </select>
                                                            </td>
                                                            <td width="15%">
                                                                <select data-placeholder="" class="form-control single_dropdown2 lbl_box sortoption tbl_input" name="branch" id="">
                                                                    <option value="0">Branch</option>
                                                                    <option value="1">1</option>
                                                                </select>
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td width="15%">
                                                                <input  class="parent_text border-none"type="text" id="" name="billno" value="0" onchange="calcAmount();" onkeypress="return isDecimal(event,this)" onblur="return FormatNum(this, 2, true)"/>
                                                            </td>
                                                            <td width="15%">
                                                                <div class="col-lg-12 padlr0">
                                                                    <input type="text" name="billdate" id="" class="tbl_input date_picker" style="cursor:pointer;" value='<?php echo Date('d/m/Y'); ?>' />
                                                                    <span class="date_icon"><i class="fa fa-calendar"></i></span>
                                                                </div>
                                                            </td>
                                                            <td width="20%">
                                                                <select data-placeholder="" class="form-control single_dropdown2 lbl_box sortoption tbl_input" name="costcentre" id="">
                                                                    <option value="0">Costcentre</option>
                                                                    <option value="1">1</option>
                                                                </select>
                                                            </td>
                                                            <td width="15%">
                                                                <input class="parent_text border-none"type="text" id="" name="billamount" value="0" onchange="" onkeypress="" onblur=""/>
                                                            </td>
                                                            <td width="15%">
                                                                <select data-placeholder="" class="form-control single_dropdown2 lbl_box sortoption tbl_input" name="type" id="">
                                                                    <option value="0">Type</option>
                                                                    <option value="1">1</option>
                                                                </select>
                                                            </td>
                                                            <td width="15%">
                                                                <select data-placeholder="" class="form-control single_dropdown2 lbl_box sortoption tbl_input" name="branch" id="">
                                                                    <option value="0">Branch</option>
                                                                    <option value="1">1</option>
                                                                </select>
                                                            </td>
                                                        </tr>
                                                        </tbody>
                                                        <tbody class="total">
                                                        <tr>
                                                            <td colspan="6">
                                                                <button id="continue" class="nx-btn float_r"><a href="javascript:void(0);" onclick="submitForm()" class="ripple">Save</a></button>
                                                            </td>
                                                        </tr>
                                                        </tbody>
                                                        <input type="hidden" name="iow___rowid" id="iow___rowid" value="0"/>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </td>

                                </tr>
                                <tr>
                                    <td width="50%">
                                        <input class="parent_text border-none" type="text" id="" name="subledgername" value="0" onchange="" onkeypress="" onblur=""/>
                                    </td>
                                    <td width="20%">
                                        <input  class="parent_text border-none"type="text" id="" name="debit" value="0" onchange="" onkeypress="" onblur=""/>
                                    </td>
                                    <td width="20%">
                                        <input class="parent_text border-none" style="text-align:right;" type="text" name="credit" id="" value="0.0" readonly>
                                    </td>
                                    <td width="6%" align="center" class="action_btns_td" style="border:none !important;">
                                        <ul class="action_btns">
                                            <li><a href="#" class="mainTr" id="expandTr__" style="cursor:pointer;"><i class="fa fa-chevron-circle-down" data-toggle="tooltip" data-placement="left" data-original-title="" ></i></a> </li>
                                        </ul>
                                    </td>
                                </tr>
                                <tr class="subTr" style="display: none;">
                                    <td colspan="9" style="padding:0px !important;">
                                        <div class="subDiv" style="display: none;">
                                            <div class="col-lg-12 col-lg-offset-0 rdbt" style="margin-top:5px;">
                                                <div class="table-responsive topsp">
                                                    <table class="table " style="margin-bottom:0px;" bgcolor="#00FF00" id="">
                                                        <thead>
                                                        <tr>
                                                            <th>Bill No</th>
                                                            <th>Bill Date</th>
                                                            <th>Costcentre</th>
                                                            <th>Bill Amount</th>
                                                            <th>Type</th>
                                                            <th>Branch</th>
                                                        </tr>
                                                        </thead>
                                                        <tbody class="main">
                                                        <tr>
                                                            <td width="15%">
                                                                <input  class="parent_text border-none"type="text" id="" name="billno" value="0" onchange="calcAmount();" onkeypress="return isDecimal(event,this)" onblur="return FormatNum(this, 2, true)"/>
                                                            </td>
                                                            <td width="15%">
                                                                <div class="col-lg-12 padlr0">
                                                                    <input type="text" name="billdate" id="" class="tbl_input date_picker" style="cursor:pointer;" value='<?php echo Date('d/m/Y'); ?>' />
                                                                    <span class="date_icon"><i class="fa fa-calendar"></i></span>
                                                                </div>
                                                            </td>
                                                            <td width="20%">
                                                                <select data-placeholder="" class="form-control single_dropdown2 lbl_box sortoption tbl_input" name="costcentre" id="">
                                                                    <option value="0">Costcentre</option>
                                                                    <option value="1">1</option>
                                                                </select>
                                                            </td>
                                                            <td width="15%">
                                                                <input class="parent_text border-none"type="text" id="" name="billamount" value="0" onchange="" onkeypress="" onblur=""/>
                                                            </td>
                                                            <td width="15%">
                                                                <select data-placeholder="" class="form-control single_dropdown2 lbl_box sortoption tbl_input" name="type" id="">
                                                                    <option value="0">Type</option>
                                                                    <option value="1">1</option>
                                                                </select>
                                                            </td>
                                                            <td width="15%">
                                                                <select data-placeholder="" class="form-control single_dropdown2 lbl_box sortoption tbl_input" name="branch" id="">
                                                                    <option value="0">Branch</option>
                                                                    <option value="1">1</option>
                                                                </select>
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td width="15%">
                                                                <input  class="parent_text border-none"type="text" id="" name="billno" value="0" onchange="calcAmount();" onkeypress="return isDecimal(event,this)" onblur="return FormatNum(this, 2, true)"/>
                                                            </td>
                                                            <td width="15%">
                                                                <div class="col-lg-12 padlr0">
                                                                    <input type="text" name="billdate" id="" class="tbl_input date_picker" style="cursor:pointer;" value='<?php echo Date('d/m/Y'); ?>' />
                                                                    <span class="date_icon"><i class="fa fa-calendar"></i></span>
                                                                </div>
                                                            </td>
                                                            <td width="20%">
                                                                <select data-placeholder="" class="form-control single_dropdown2 lbl_box sortoption tbl_input" name="costcentre" id="">
                                                                    <option value="0">Costcentre</option>
                                                                    <option value="1">1</option>
                                                                </select>
                                                            </td>
                                                            <td width="15%">
                                                                <input class="parent_text border-none"type="text" id="" name="billamount" value="0" onchange="" onkeypress="" onblur=""/>
                                                            </td>
                                                            <td width="15%">
                                                                <select data-placeholder="" class="form-control single_dropdown2 lbl_box sortoption tbl_input" name="type" id="">
                                                                    <option value="0">Type</option>
                                                                    <option value="1">1</option>
                                                                </select>
                                                            </td>
                                                            <td width="15%">
                                                                <select data-placeholder="" class="form-control single_dropdown2 lbl_box sortoption tbl_input" name="branch" id="">
                                                                    <option value="0">Branch</option>
                                                                    <option value="1">1</option>
                                                                </select>
                                                            </td>
                                                        </tr>
                                                        </tbody>
                                                        <tbody class="total">
                                                        <tr>
                                                            <td colspan="6">
                                                                <button id="continue" class="nx-btn float_r"><a href="javascript:void(0);" onclick="submitForm()" class="ripple">Save</a></button>
                                                            </td>
                                                        </tr>
                                                        </tbody>
                                                        <input type="hidden" name="iow___rowid" id="iow___rowid" value="0"/>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </td>

                                </tr>
                                </tbody>
                                <tbody class="total">
                                <tr id="totalTD">
                                    <td align="right" class="t_amt">Total</td>
                                    <td width="25%">
                                        <input class="parent_text border-none" style="text-align:right;" type="text" name="totDebit" id="totDebit" value="0.0" readonly>
                                    </td>
                                    <td width="25%" colspan="4">
                                        <input class="parent_text border-none" style="text-align:right;" type="text" name="totCredit" id="totCredit" value="0.0" readonly>
                                    </td>
                                </tr>
                                <tr id="totalBalTD">
                                    <td align="right" class="t_amt">Overall Total</td>
                                    <td width="25%">
                                        <input class="parent_text border-none" style="text-align:right;" type="text" name="totAmount" id="totAmount" value="0.0" readonly>
                                    </td>
                                    <td colspan="4">&nbsp;</td>
                                </tr>
                                </tbody>
                            </table>
                            <input type="hidden" name="rowid" id="rowid" value="0"/>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="col-lg-12 savebtn_area">
    <ul>
        <li id="continue" class="dropdown save_btn float_r"><a href="javascript:void(0);" onclick="submitForm()" class="ripple">submit</a></li>
    </ul>
</div>
<script type="text/javascript">
    $(function(){
        bindExpandTrFn();
    });
    function bindExpandTrFn() {
        // expand tr
        var $mainTr = $(".mainTr");
        $mainTr.unbind('click');
        $mainTr.click(function(e){
            e.preventDefault();
            $mainTr.closest("tr").next(".subTr").find(".subDiv").slideUp("slow");
            $mainTr.closest("tr").next(".subTr").slideUp("slow");
            $mainTr.find("i").removeClass("tform");

            if(!$(this).closest("tr").next(".subTr").is(":visible")){
                $(this).closest("tr").next(".subTr").show();
                $(this).closest("tr").next(".subTr").find(".subDiv").slideDown("slow");
                $(this).find("i").addClass("tform");
            }
            else{
                $(this).closest("tr").next(".subTr").find(".subDiv").slideUp("slow");
                $(this).closest("tr").next(".subTr").slideUp("slow");
                $(this).find("i").removeClass("tform");
            }
        });
    }
</script>