<ul class="modl_lmenu">
    <h2>Workflow</h2>
    <li><a href="javascript:void(0);" class="ripple modlsub_open"><i class="fa fa-university"></i> <span class="nav-label">Organisation</span></a>
        <ul>
            <li><a href="<?php echo $this->basePath(); ?>/workflow/index/company-gridlist" class="ripple">Company</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/workflow/index/costcenter-gridlist" class="ripple">CostCentre</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/workflow/index/organisationposition" class="ripple">Position</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/workflow/index/organisationdepartment" class="ripple">Department</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/workflow/index/organisationlevel" class="ripple">Level</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/workflow/index/userlist" class="ripple">User</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/workflow/index/team" class="ripple">Team</a></li>
        </ul>
    </li>
    <li><a href="<?php echo $this->basePath(); ?>/workflow/activity" class="ripple"><i class="fa fa-newspaper-o"></i><span class="nav-label">Activity Process</span></a></li>
    <li><a href="<?php echo $this->basePath(); ?>/workflow/index/reminder" class="ripple"><i class="fa fa-bell-o"></i><span class="nav-label">Reminder</span></a></li>
    <li><a href="<?php echo $this->basePath(); ?>/workflow/index/news" class="ripple"><i class="fa fa-newspaper-o"></i><span class="nav-label">News</span></a></li>
    <li><a href="javascript:void(0);" class="ripple modlsub_open"><i class="fa fa-cog"></i> <span class="nav-label">Settings</span></a>
        <ul>
            <li><a href="<?php echo $this->basePath(); ?>/workflow/index/settings" class="ripple">General Settings</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/workflow/index/approval-settings" class="ripple">Approval Settings</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/workflow/index/currency-settings" class="ripple">Currency Settings</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/workflow/index/vouchertype-generation" class="ripple">Voucher Settings</a></li>

        </ul>
    </li>
</ul>