<style>
.lb{color:#000;padding-bottom:5px;font-size:15px;}
.spa{color:#b33333;margin-left:8px;text-align:right; padding-bottom:5px; font-size:15px;}
.float_l		{float:left;}
.float_r		{float:right;}
.float_rt		{float:right; margin-right:10px;}
.mtrl_txt:focus, .mtrl_txt.active {border: 1px solid #39F;}
.mtrl_txt{border:1px solid #CCC;padding:8px 4px;font-size:14px!important;font-weight:normal !important;width:100%;-webkit-transition: border-color 1s ease;-moz-transition:border-color 1s ease; -o-transition: border-color 1s ease;-ms-transition: border-color 1s ease;transition: border-color 1s ease;background:#fff;}
.show-on-hover:hover > ul.dropdown-menu {display: block;}
.show-on-hover> ul.dropdown-menu span{color:#3f6ac3;}
.btn_clr {margin-top:5px; padding:2px 7px;background:#fff; border:1px solid #3f6ac3;border-radius:25px; color:#3f6ac3;}
.det_box{right:-214px;width:200px;height:auto;padding:15px;background:#fff;border: 1px solid rgba(0,0,0,.15);border-radius: 4px;-webkit-box-shadow: 0 6px 8px rgba(0,0,0,.175);box-shadow: 0 6px 8px rgba(0,0,0,.175);}
</style>

<div class="content_wrapper padlr0">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12">
				<h1 class="txt_center form_main_h1 frmwrk_h1">Add Resourceitem</h1>
			</div>
			<div class="col-lg-12">
				<div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
					<div class="row">
						<div class="form-group col-lg-12" style="position:relative;">
							<select name="city" id="city" class="form-control selectpicker show-tick" data-size="5" title="Select Material">
							<option value=""></option>	
							</select>
						</div>
						<!--<div class="det_box" style="position:absolute;">
							<label class="lb">Type -<span class="spa">Material</span></label>
							<label class="lb">Group -<span class="spa">Purchase</span></label>
							<label class="lb">Code - <span class="spa">M01700013</span> </label>
							<label class="lb">Resource -<span class="spa">Agg 40mm</span></label>
							<label class="lb">Unit -<span class="spa">apts</span></label>
							<label class="lb">Base Rate -<span class="spa">1068.800</span></label>
							<label class="lb">Q.rate -<span class="spa">1202.400</span></label>
						</div>-->
					</div>
					<div class="row">
						<div class="form-group col-lg-12" style="position:relative;">
							<select name="city" id="city" class="form-control selectpicker show-tick" data-size="5" title="Select Material">
							<option value=""></option>	
							</select>
						</div>
					</div>
				</div>
			</div>
    	</div>
	</div>
</div> 
<div class="col-lg-12 savebtn_area">
    <ul>
        <li id="continue" class="dropdown save_btn float_r">
            <a href="<?php echo $this->basePath(); ?>/designer/purchase/materialelse" class="ripple">Save</a>
        </li>
        <li id="continue" class="dropdown save_btn  float_r">
            <a href="<?php echo $this->basePath(); ?>/designer/purchase/addmaterial" class="ripple">Save & New</a>
        </li>
        <li id="continue" class="dropdown save_btn  float_l">
            <a href="<?php echo $this->basePath(); ?>/designer/purchase/materialsetup" class="ripple">Skip</a>
        </li>
  	</ul>      
</div>
<script>
</script>
