<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css'; ?>" />
<style>
.prjt							{margin-bottom:30px;}
.tr_hot 						{background:#f9eaea;}
.tr_warm 						{background:#f8f1e4;}
.mar_10							{margin-top:10px;}
.mar_20							{margin-top:20px;}
.pagination-lg > li > a, .pagination-lg > li > span {font-size:15px !important; padding:5px 15px !important;}
#jqxGrid .jqx-grid-header 		{height:75px !important;}
.jqx_margn						{margin-top:30px;}
.bk-btn                        {text-align:left; margin-left:30px; margin-top:20px;}
.bk-btn a:hover                {border:1px solid #23bfee !important; background:#fff !important; color:#23bfee !important;}
.bk-btn a                      {background:#23bfee!important;border:1px solid #23bfee !important; font-weight:600;color:#fff!important; font-size:14px; padding: 5px 10px; text-align: center; transition: all 0.4s ease 0s;}
</style>

<div class="content_wrapper padlr0">
	<div class="container-fluid padlr0">
		<div class="col-lg-12">
			<h1 class="prjt">Project Setup</h1>
		</div>
        <div class="col-lg-12 clear">
			<ul class="breadcrumb_area ripple">
				<li><a href="<?php echo $this->basePath(); ?>/designer/purchase/project">Opening Stock</a></li>
				<li><a href="<?php echo $this->basePath(); ?>/designer/purchase/resource">Resource Required</a></li>
				<li><a href="#" class="active">Gate List</a></li>
			</ul>
        </div>
        <div class="fixed-action-btn active mar_15">
			<a class="btn-floating btn-large">
				<i class="fa fa-paperclip"></i>
			</a>
			<ul>
				<li>
					<a class="btn-floating hide-input-file" data-toggle="tooltip" data-placement="top" data-original-title="Import From Excel">
					<i class="fa fa-file-excel-o"></i>
					<input type="file" name="myfile" id="myfile" class="input-large" accept=".xls,.xlsx,application/vnd.  openxmlformats-officedocument.  		 	  				spreadsheetml.sheet, application/vnd.ms-excel" onchange="fileupload(this)" />
					</a>
				</li>
				<li>
					<a class="btn-floating" href="#" download data-toggle="tooltip" data-placement="top" data-original-title="Download Sample">
					<i class="fa fa-download"></i>
					</a>
				</li>
			</ul>
		</div>
        <div class="col-lg-4 col-lg-offset-2 mar_20">
        	<div class="form-group col-lg-12">
				<select name="" id="" class="form-control selectpicker show-tick" data-size="5" title="Gate Name">
					<option value=""></option>	
				</select>
			</div>
     	</div>              
      	<div class="col-lg-4 mar_20">
        	<div class="form-group col-lg-12">
				<select name="" id="" class="form-control selectpicker show-tick" data-size="5" title="Security Agency">
					<option value=""></option>	
				</select>
			</div>
   		</div>
        <div class="col-lg-2 mar_20">
        	<a title="Edit" href="#"><i class="fa fa-pencil-square-o reg-icon"></i></a>
        	<a title="Delete" onclick=""><i class="fa fa-trash-o reg-icon" style="margin-left:10px;"></i></a>
        </div>
        <div class="col-lg-4 col-lg-offset-2 mar_20">
        	<div class="form-group col-lg-12">
				<select name="" id="" class="form-control selectpicker show-tick" data-size="5" title="Gate Name">
					<option value=""></option>	
				</select>
			</div>
     	</div>              
      	<div class="col-lg-4 mar_20">
        	<div class="form-group col-lg-12">
				<select name="" id="" class="form-control selectpicker show-tick" data-size="5" title="Security Agency">
					<option value=""></option>	
				</select>
			</div>
   		</div>
        <div class="col-lg-2 mar_20">
        	<a title="Edit" href="#"><i class="fa fa-pencil-square-o reg-icon"></i></a>
        	<a title="Delete" onclick=""><i class="fa fa-trash-o reg-icon" style="margin-left:10px;"></i></a>
        </div>
        <div class="col-lg-4 col-lg-offset-2 mar_20">
        	<div class="form-group col-lg-12">
				<select name="" id="" class="form-control selectpicker show-tick" data-size="5" title="Gate Name">
					<option value=""></option>	
				</select>
			</div>
     	</div>              
      	<div class="col-lg-4 mar_20">
        	<div class="form-group col-lg-12">
				<select name="" id="" class="form-control selectpicker show-tick" data-size="5" title="Security Agency">
					<option value=""></option>	
				</select>
			</div>
   		</div>
        <div class="col-lg-2 mar_20">
        	<a title="Edit" href="#"><i class="fa fa-pencil-square-o reg-icon"></i></a>
        	<a title="Delete" onclick=""><i class="fa fa-trash-o reg-icon" style="margin-left:10px;"></i></a>
        </div>
        <div class="col-lg-4 col-lg-offset-2 mar_20">
        	<div class="form-group col-lg-12">
				<select name="" id="" class="form-control selectpicker show-tick" data-size="5" title="Gate Name">
					<option value=""></option>	
				</select>
			</div>
     	</div>              
      	<div class="col-lg-4 mar_20">
        	<div class="form-group col-lg-12">
				<select name="" id="" class="form-control selectpicker show-tick" data-size="5" title="Security Agency">
					<option value=""></option>	
				</select>
			</div>
   		</div>
        <div class="col-lg-2 mar_20">
        	<a title="Edit" href="#"><i class="fa fa-pencil-square-o reg-icon"></i></a>
        	<a title="Delete" onclick=""><i class="fa fa-trash-o reg-icon" style="margin-left:10px;"></i></a>
        </div>
        <div class="col-lg-12">
        	<div class="bk-btn">
			<a href="<?php echo $this->basePath(); ?>/designer/purchase/resource"><i class="fa fa-chevron-circle-left" style="margin-right:6px;"></i>Back</a>
    		</div>
      	</div>
        
    </div>
</div>
