<style>

.mms_h1				{margin-top:10px; color:}
.mms_h2				{margin-top:20px; color:#906;}
.mms_p				{text-align:center;padding-top:10px;color:#333; font-size:15px;}
.mar_40				{margin-top:40px;}

</style>


<div class="content_wrapper padlr0">
	<div class="container-fluid">
		<div class="col-lg-12 clear">
			<div class="row" id="">
				<h1 class="txt_center form_main_h1 mms_h1">Project Setup<?php ?></h1>
            </div>
            <div class="txt_center col-lg-12"> 
                <h2 class="mms_h2">Are you planning for project setup?</h2>
                <p class="mms_p">Please choose one of the below Cost Center and click proceed</p>
            </div>
     	</div>
		<div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
			<div class="row">   
				<div class="form-group col-lg-12 mar_40">
					<select name="cost_center" id="cost_center" class="form-control selectpicker show-tick" data-size="5" title="Select CostCenter">
						<option value=""></option>	
						<?php ?>
                  	</select>
                  	<div class="error_message"><p>Please enter Cost Center...</p></div> 
              	</div>
          	</div>
      	</div>
        <div class="col-lg-12 savebtn_area m_btm30 m_auto no_border">
        	<ul>
            	<li class="save_btn m_auto">
                	<a href="<?php echo $this->basePath(); ?>/designer/purchase/project" class="ripple">Proceed</a>
                </li>
         	</ul>
     	</div>
	</div>    
</div>
        
<script>
$(document).ready(function() {
	$(".single_dropdown").select2({
		placeholder: "",
		allowClear: true,
	});
});
</script>