><link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css'; ?>" />
<style>
.prjt							{margin-bottom:30px;}
.tr_hot 						{background:#f9eaea;}
.tr_warm 						{background:#f8f1e4;}
.mar_15							{margin-top:15px;}
.pagination-lg > li > a, .pagination-lg > li > span {font-size:15px !important; padding:5px 15px !important;}
#jqxGrid .jqx-grid-header 		{height:75px !important;}
.jqx_margn						{margin-top:30px;}
</style>


<div class="content_wrapper padlr0">
	<div class="container-fluid">
		<div class="row">
			<div class="form-group">
				<div class="col-lg-12">
					<h1 class="txt_center form_main_h1 frmwrk_h1">Resourceitem Entry</h1>
				</div>	
                <div class="col-lg-12 commargin_top clear">
            		<div class="table-responsive clear">
                		<div id="jqxGrid" class="jqx_margn">
                		</div>
            		</div>
        		</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
    var data = [{"S.No":"1","Resourceitem Name":"qwe","Resourceitem Code":"4","Resourcename":"3","Rate":"258","Unit":"1000"},{"S.No":"1","Resourceitem Name":"qwe","Resourceitem Code":"4","Resourcename":"3","Rate":"258","Unit":"1000"}],
        $jqxGrid = $("#jqxGrid");
    $(function () {
        var source = {
            localdata: data,
            dataType: "json",
            dataFields: [
                {name: 'S.No', type: 'int'},
                {name: 'Resourceitem Name', type: 'string'},
                {name: 'Resourceitem Code', type: 'sring'},
				{name: 'Resourcename', type: 'sring'},
                {name: 'Rate', type: 'int'},
                {name: 'Unit', type: 'int'},
            ],
            id: 'TargetId'
        };

        var dataAdapter = new $.jqx.dataAdapter(source);
        $jqxGrid.jqxGrid({
            width: "100%",
            source: dataAdapter,
            sortable: true,
            pagerButtonsCount: 6,
            filterable: true,
            pageable: true,
            rowDetails: true,
            autoheight: true,
			showfilterrow: true,
            editable: false,
            altrows: true,
            enabletooltips: true,
            columns: [
                {text: 'S.No', datafield: 'S.No', width:'10%'},
                {text: 'Resourceitem Name', datafield: 'Resourceitem Name',width:'20%'},
                {text: 'Resourceitem Code', datafield: 'Resourceitem Code', width: '20%'},
                {text: 'Resourcename', datafield: 'Resourcename', width: '19%'},
                {text: 'Rate', datafield: 'Rate', width: '19%'},
                {text: 'Unit', dataField: 'Unit', width:'12%'},

            ]
        });
    });
</script> 
<div class="col-lg-12 savebtn_area">
    <ul>
   		<li id="continue" class="save_btn float_r">
        	<a href="<?php echo $this->basePath(); ?>/designer/purchase/materialelse" class="ripple">Done</a>
       	</li>
 	</ul>
</div>
                    				


					
                    	




