<style>

.mms_h1							{margin-top:10px;}
.mms_h2							{margin-top:20px; color:#906;}
.mms_p							{text-align:center;padding-top:10px;color:#333; font-size:15px;}
.nxt-btn                        {text-align:right; margin-right:68%; margin-top:20px;}
.nxt-btn a:hover                {border:1px solid #23bfee !important; background:#fff !important; color:#23bfee !important;}
.nxt-btn a                      {background:#23bfee!important;border:1px solid #23bfee !important; font-weight:600;color:#fff!important; font-size:14px; padding: 5px 10px; text-align: center; transition: all 0.4s ease 0s;}
.bk-btn                        {text-align:left; margin-left:68%; margin-top:20px;}
.bk-btn a:hover                {border:1px solid #23bfee !important; background:#fff !important; color:#23bfee !important;}
.bk-btn a                      {background:#23bfee!important;border:1px solid #23bfee !important; font-weight:600;color:#fff!important; font-size:14px; padding: 5px 10px; text-align: center; transition: all 0.4s ease 0s;}
</style>


<div class="content_wrapper padlr0">
	<div class="container-fluid">
		<div class="col-lg-12 clear">
			<div class="row">
				<h1 class="txt_center form_main_h1 mms_h1">Material Setup</h1>
           	</div>
            <div class="txt_center col-lg-12"> 
            	<h2 class="mms_h2">Are you planning for MaterialItem create?</h2>
                <p class="mms_p">You want to proceed With</p>
          	</div>
            <div class="col-lg-4 col-lg-offset-6 col-md-5 col-lg-offset-5">  
				<div class="radio_check">
					<p class="stat_lbl">
						<input type="radio" value="1" id="rdio" name="rdio"/>
						<label for="rdio" class="ripple">Manual</label>
					</p>
					<p class="stat_lbl">
						<input type="radio" value="1" id="rdio" name="rdio"/>
						<label for="rdio" class="ripple">Report</label>
					</p>
				</div>
			</div>
            <div class="col-lg-3 col-lg-offset-3">
        		<div class="bk-btn">
					<a href="<?php echo $this->basePath(); ?>/designer/purchase/material">
                	<i class="fa fa-chevron-circle-left" style="margin-right:6px;"></i>Back</a>
                </div>
           	</div>
            <div class="col-lg-3">
    			<div class="nxt-btn">
        			<a href="<?php echo $this->basePath(); ?>/designer/purchase/resourcesetup">Next
                	<i class="fa fa-chevron-circle-right" style="margin-left:6px;"></i></a>
            	</div>
            </div>
		</div>
	</div>
</div>
