<style>
.mms_h1					{margin-top:10px;}
.mms_h2					{margin-top:20px; color:#906;}
.mms_p					{text-align:center;padding-top:10px;color:#333; font-size:15px;}
.edt_btn				{margin-top:30px;}
.edt_btn a:hover        {border:1px solid #23bfee !important; background:#fff !important; color:#23bfee !important;}
.edt_btn a              {background:#23bfee!important;border:1px solid #23bfee !important; font-weight:600;color:#fff!important; font-size:14px; padding: 5px 10px; text-align: center; margin-left:10px;margin-right:20px; transition: all 0.4s ease 0s;}}
</style>


<div class="content_wrapper padlr0">
	<div class="container-fluid">
		<div class="col-lg-12 clear">
			<div class="row">
				<h1 class="txt_center form_main_h1 mms_h1">Material Setup</h1>
           	</div>
            <div class="txt_center col-lg-12"> 
            	<h2 class="mms_h2">Are you planning for Material setup?</h2>
                <p class="mms_p">Do You Want To Create New ResourceItem or Edit Already Available ResourceItem Details?</p>
          	</div>
			<div class="col-lg-4 col-lg-offset-4">
            	<div class="txt_center edt_btn">
                	<a href="<?php echo $this->basePath(); ?>/designer/purchase/materialsetup">Create New MaterialItem</a>
           		</div>
            	<div class="txt_center edt_btn">
					<a href="<?php echo $this->basePath(); ?>/designer/purchase/materialedit">Edit MaterialItem </a>
                </div>
          	</div>  
		</div>
	</div>
</div>
