
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/wpm.css';?>"/>
<style>

/*.btn-info:hover::after{
    content: '';
    position: absolute;
    right: 0px;
    top: 32px;
    width: 0;
    height: 0;
    border-left: 11px solid transparent;
    border-right: 11px solid transparent;
    border-top: 17px solid #2aabd2;
}
.btn-primary:hover::after{
    content: '';
    position: absolute;
    right: 0px;
    top: 32px;
    width: 0;
    height: 0;
    border-left: 11px solid transparent;
    border-right: 11px solid transparent;
    border-top: 17px solid #265a88;
}

.btn-success:hover::after{
    content: '';
    position: absolute;
    right: 0px;
    top: 32px;
    width: 0;
    height: 0;
    border-left: 11px solid transparent;
    border-right: 11px solid transparent;
    border-top: 17px solid #419641;
}

.btn-danger:hover::after{
    content: '';
    position: absolute;
    right: 0px;
    top: 32px;
    width: 0;
    height: 0;
    border-left: 11px solid transparent;
    border-right: 11px solid transparent;
    border-top: 17px solid #cb3d39;
}

.btn-warning:hover::after{
    content: '';
    position: absolute;
    right: 0px;
    top: 32px;
    width: 0;
    height: 0;
    border-left: 11px solid transparent;
    border-right: 11px solid transparent;
    border-top: 17px solid #ec9923;
}
.brwn_bdr{
	border-bottom:3px solid #dccfc8;
}*/
.mar_30{margin-top:30px;}

.ovrcls .list-icon {
    border-radius: 100%;
    font-size: 32px;
	display:block;
    height: 60px;
    line-height: 55px;
    margin: auto;
    text-align: center;
    width: 60px;
	background:#fff;	
}
.ovrcls:hover .oval1 { background: #2aabd2;color:#fff;}
.ovrcls:hover .oval2 { background: #265a88;color:#fff;}
.ovrcls:hover .oval3 { background: #419641;color:#fff;}
.ovrcls:hover .oval4 { background: #cb3d39 ;color:#fff;}
.ovrcls:hover .oval5 { background:	#ec9923 ;color:#fff;}
.clrrndtxt					{font-size:15px; color:#1e1e1e;}
.ovrcls .oval1 {border: 1px solid #2aabd2; color: #2aabd2;}
.ovrcls .oval2{border: 1px solid #265a88; color: #265a88;}
.ovrcls .oval3{border: 1px solid #419641 ;color: #419641;}
.ovrcls .oval4{border: 1px solid #cb3d39;color: #cb3d39;}
.ovrcls .oval5{border: 1px solid #ec9923;color: #ec9923;}
ul,li{list-style:none;}
/*-----------------------inner module tab-----------------*/
.innermdl_tabs												{background-color:#e7e9ec; border-bottom:1px solid #2d74b4 !important;border:0px;}
.innermdl_tabs li											{margin:0px !important;width:20%!important;}
.innermdl_tabs li a											{color:#212121;text-align:center;padding:10px 22px 8px 22px; font-size:13px; font-weight:600;display:block;border-radius: 0px;margin:0px;border-bottom:3px solid #e7e9ec;border-top:0px !important; border-right:0px !important;border-left:0px !important;}
.innermdl_tabs li a:after									{content:''; width:1px; height:20px; background-color:#bccae7; position:absolute; right:0px;}
.innermdl_tabs li:last-child a:after						{content:''; width:0px;}
.innermdl_tabs li ul li a									{text-align:left;font-size:13px;border-bottom:0px !important;}
.innermdl_tabs li ul li a:after								{background:none !important;}
.innermdl_tabs>li>a:hover,.innermdl_tabs>li.active>a,.innermdl_tabs>li.active>a:focus,.innermdl_tabs>li.active>a:hover{background-color:#e1e3e7 !important;color:#3f6ac3;font-weight:600;border-bottom:3px solid #2d74b4 !important;border-top:0px !important; border-right:0px !important;border-left:0px !important;}
.innermdl_tabs li a span									{color:#3f6ac3;padding:0px 10px 0px 0px;}

/*---------------------Responsive css---------------------*/
@media screen and (max-width:1280px)						         {
}
@media only screen and (min-width : 769px) and (max-width : 800px) {
}
@media screen and (min-width : 361px) and (max-width : 768px){
.innermdl_tabs li				{margin:0px !important;width:100%!important;}
}
@media only screen and (min-width : 321px) and (max-width : 360px)	{
.innermdl_tabs li				{margin:0px !important; width:100%!important;}
}
@media only screen and (width : 320px)  {
.innermdl_tabs li				{ margin:0px !important;width:100%!important;}
}
@media only screen and (width : 480px)  {
.innermdl_tabs li				{margin:0px !important; width:100%!important;}
}
@media only screen and (width : 640px)  {
.innermdl_tabs li				{ margin:0px !important;}
}
@media only screen and (min-width : 320px) and (max-width : 1199px) 		{
.innermdl_tabs li				{margin:0px !important;margin:0px !important;}
}
@media only screen and (min-width : 981px) and (max-width : 1024px) {
}

/*---------------------/Responsive css\---------------------*/


</style>
<div class="content_wrapper padlr0">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
				<h1 class="text-center" data-bsfshare="BillReport List">Bill Report List</h1>
			</div>
        	<div class="clearfix"></div>
			<div class="col-lg-12 mar_30">
				<nav class="navbar inrmdltab_navbar navbar-default">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle mdlnvbr_tgl collapsed ripple" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand inrmdl_navbrand ripple" href="javascript:void(0);">Select Menus</a>
                    </div>
                    <div id="navbar" class="navbar-collapse padlr0 collapse">
                        <ul class="nav nav-tabs innermdl_tabs">
                            <li class="active"><a href="#po" class="ripple" data-toggle="tab">Purchase Order</a></li>
							<li><a href="#min" class="ripple" data-toggle="tab">Min</a></li>
							<li><a href="#pb" class="ripple" data-toggle="tab">Purchase Bill</a></li>
							<li><a href="#is" class="ripple" data-toggle="tab">Issue</a></li>
							<li><a href="#tr" class="ripple" data-toggle="tab">Transfer</a></li>
                        </ul>
                    </div>
                </nav>
				<!--<div class="brwn_bdr"></div>-->
			</div>
			<!----------Purchase Order Reports ----->
			<div class="tab-content">
				<div class="tab-pane active mar_30" id="po">
						<div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Projectwise Sales">
							<a href="" class="ovrcls" >
							<div class="col-lg-12 ovrcls"><span  class="list-icon text-center oval1"><i class="fa fa-shopping-cart icon-hvr"></i></span></div>
							<div class="col-lg-12 text-center clrrndtxt commargin_top5">Project wise Sales</div>
							</a>
						</div>		
						<div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Projectwise Sales">
							<a href="" class="ovrcls" >
							<div class="col-lg-12 ovrcls"><span  class="list-icon text-center oval1"><i class="fa fa-shopping-cart icon-hvr"></i></span></div>
							<div class="col-lg-12 text-center clrrndtxt commargin_top5">Project wise Sales</div>
							</a>
						</div>		
						<div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Projectwise Sales">
							<a href="" class="ovrcls" >
							<div class="col-lg-12 ovrcls"><span  class="list-icon text-center oval1"><i class="fa fa-shopping-cart icon-hvr"></i></span></div>
							<div class="col-lg-12 text-center clrrndtxt commargin_top5">Project wise Sales</div>
							</a>
						</div>		
						<div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Projectwise Sales">
							<a href="" class="ovrcls" >
							<div class="col-lg-12 ovrcls"><span  class="list-icon text-center oval1"><i class="fa fa-shopping-cart icon-hvr"></i></span></div>
							<div class="col-lg-12 text-center clrrndtxt commargin_top5">Project wise Sales</div>
							</a>
						</div>								
				</div>
				<!----------Min Reports ----->
				<div class="tab-pane mar_30" id="min">
					<div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Receivable Statement">
						<a href="" class="ovrcls">
							<div class="col-lg-12"><span  class="list-icon text-center oval2"><i class="fa fa-ticket icon-hvr"></i></span></div>
							<div class="col-lg-12 text-center clrrndtxt commargin_top5">Receivable Statement</div>
						</a>
					</div>
					<div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Receivable Statement">
						<a href="" class="ovrcls">
							<div class="col-lg-12"><span  class="list-icon text-center oval2"><i class="fa fa-ticket icon-hvr"></i></span></div>
							<div class="col-lg-12 text-center clrrndtxt commargin_top5">Receivable Statement</div>
						</a>
					</div>
					<div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Receivable Statement">
						<a href="" class="ovrcls">
							<div class="col-lg-12"><span  class="list-icon text-center oval2"><i class="fa fa-ticket icon-hvr"></i></span></div>
							<div class="col-lg-12 text-center clrrndtxt commargin_top5">Receivable Statement</div>
						</a>
					</div>
					<div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Receivable Statement">
						<a href="" class="ovrcls">
							<div class="col-lg-12"><span  class="list-icon text-center oval2"><i class="fa fa-ticket icon-hvr"></i></span></div>
							<div class="col-lg-12 text-center clrrndtxt commargin_top5">Receivable Statement</div>
						</a>
					</div>
				</div>
				
				<!----------Purchase Bill Reports ----->
	
				<div class="tab-pane mar_30" id="pb">
					<div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Projectwise Receivable">
						<a href="" class="ovrcls">
							<div class="col-lg-12"><span  class="list-icon text-center oval3"><i class="fa fa-file-text icon-hvr"></i></span></div>     
							<div class="col-lg-12 text-center clrrndtxt commargin_top5">Project wise Receivable</div>
						</a>
					</div>
					<div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Projectwise Receivable">
						<a href="" class="ovrcls">
							<div class="col-lg-12"><span  class="list-icon text-center oval3"><i class="fa fa-file-text icon-hvr"></i></span></div>     
							<div class="col-lg-12 text-center clrrndtxt commargin_top5">Project wise Receivable</div>
						</a>
					</div>
					<div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Projectwise Receivable">
						<a href="" class="ovrcls">
							<div class="col-lg-12"><span  class="list-icon text-center oval3"><i class="fa fa-file-text icon-hvr"></i></span></div>     
							<div class="col-lg-12 text-center clrrndtxt commargin_top5">Project wise Receivable</div>
						</a>
					</div>
					<div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Projectwise Receivable">
						<a href="" class="ovrcls">
							<div class="col-lg-12"><span  class="list-icon text-center oval3"><i class="fa fa-file-text icon-hvr"></i></span></div>     
							<div class="col-lg-12 text-center clrrndtxt commargin_top5">Project wise Receivable</div>
						</a>
					</div>
				</div>
				
				<!----------Issue Reports ----->
				
				<div class="tab-pane mar_30" id="is">
					<div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Project Status">
						<a href="" class="ovrcls">
							<div class="col-lg-12"><span  class="list-icon text-center oval4"><i class="fa fa-ils icon-hvr"></i></span></div>
							<div class="col-lg-12 text-center clrrndtxt commargin_top5">Project Status</div>
						</a>
					</div>
					<div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Project Status">
						<a href="" class="ovrcls">
							<div class="col-lg-12"><span  class="list-icon text-center oval4"><i class="fa fa-ils icon-hvr"></i></span></div>
							<div class="col-lg-12 text-center clrrndtxt commargin_top5">Project Status</div>
						</a>
					</div>
					<div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Project Status">
						<a href="" class="ovrcls">
							<div class="col-lg-12"><span  class="list-icon text-center oval4"><i class="fa fa-ils icon-hvr"></i></span></div>
							<div class="col-lg-12 text-center clrrndtxt commargin_top5">Project Status</div>
						</a>
					</div>
					<div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Project Status">
						<a href="" class="ovrcls">
							<div class="col-lg-12"><span  class="list-icon text-center oval4"><i class="fa fa-ils icon-hvr"></i></span></div>
							<div class="col-lg-12 text-center clrrndtxt commargin_top5">Project Status</div>
						</a>
					</div>					
				</div>
				
				<!----------Transfer Reports----->
				<div class="tab-pane mar_30" id="tr">
					<div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Projectwise Sales">
						<a href="" class="ovrcls" >
							<div class="col-lg-12 ovrclss"><span  class="list-icon text-center oval5"><i class="fa fa-exchange icon-hvr"></i></span></div>
							<div class="col-lg-12 text-center clrrndtxt commargin_top5">Project wise Sales</div>
						</a>
					</div>
					<div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Projectwise Sales">
						<a href="" class="ovrcls" >
							<div class="col-lg-12 ovrclss"><span  class="list-icon text-center oval5"><i class="fa fa-exchange icon-hvr"></i></span></div>
							<div class="col-lg-12 text-center clrrndtxt commargin_top5">Project wise Sales</div>
						</a>
					</div>
					<div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Projectwise Sales">
						<a href="" class="ovrcls" >
							<div class="col-lg-12 ovrclss"><span  class="list-icon text-center oval5"><i class="fa fa-exchange icon-hvr"></i></span></div>
							<div class="col-lg-12 text-center clrrndtxt commargin_top5">Project wise Sales</div>
						</a>
					</div>
					<div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Projectwise Sales">
						<a href="" class="ovrcls">
							<div class="col-lg-12 ovrclss"><span  class="list-icon text-center oval5"><i class="fa fa-exchange icon-hvr"></i></span></div>
							<div class="col-lg-12 text-center clrrndtxt commargin_top5">Project wise Sales</div>
						</a>
					</div>
				</div>
			</div>
        </div>
    </div>
</div>