<div class="content_wrapper min_h550 padlr0">
	<div class="container-fluid">
		<div class="row frmwrk_area">
			<div class="col-lg-12">
				<h1 class="txt_center frmwrk_h1">BSF Developer Framework</h1> 
			</div> 
			<div class="col-lg-12">
				<div class="row">
					<div class="step_by_liner animated slideInDown"></div>
					<ul class="step_by">
						<li class="opacity_08">
							<div class="step_by_sep animated slideInRight"><p>2</p></div>
						</li>
						<li>
							<div class="step_by_sep stepsep_active animated_1_5s slideInRight"><p>3</p></div>
						</li>
						<li>
							&nbsp;
						</li>
					</ul>
					<h5 class="frmwrk_h5">Choose below list of functionality to be included by default</h5>
					<form action="" id="functionForm" method="post"/>
						<div class="radio_check frmwrk_chkbox">
							<p>
								<input type="checkbox" readonly name="functions[]" checked value="log" id="log" />
								<label for="log1" class="ripple">Log</label>
							</p>
							<p>
								<input type="checkbox" name="functions[]" value="share" id="share" />
								<label for="share" class="ripple">Share</label>
							</p>
							<p>
								<input type="checkbox" name="functions[]" value="request" id="request" />
								<label for="request" class="ripple">Request</label>
							</p>
							<p>
								<input type="checkbox" name="functions[]" value="reminder" id="reminder" />
								<label for="reminder" class="ripple">Reminder</label>
							</p>
							<p>
								<input type="checkbox" name="functions[]" value="ask" id="ask" />
								<label for="ask" class="ripple">Ask</label>
							</p>
							<p>
								<input type="checkbox" name="functions[]" value="feed" id="feed" />
								<label for="feed" class="ripple">Feed</label>
							</p>
							<p>
								<input type="checkbox" readonly name="functions[]" checked value="activity_stream" id="activity_stream" />
								<label for="activity_stream1" class="ripple">Activity Stream</label>
							</p>
							<p>
								<input type="checkbox" name="functions[]" value="geo_location" id="geo_location" />
								<label for="geo_location" class="ripple">Geo location</label>
							</p>
							<p>
								<input type="checkbox" readonly name="functions[]" checked value="approve" id="approve" />
								<label for="approve1" class="ripple">Approve</label>
							</p>
							<input type="hidden" name="module_name" value="<?php echo $sessionValue->moduleName; ?>" />
							<input type="hidden" name="controller_name" value="<?php echo $sessionValue->controllerName; ?>" />
							<input type="hidden" name="action_name" value="<?php echo $sessionValue->actionName; ?>" />
						</div>
					</form>
					<div class="col-lg-12 savebtn_area m3_auto no_border clear">
						<ul>
							<li class="save_btn m_auto">
								<a href="javascript:void(0);" onclick="$('#functionForm').submit();" class="ripple">Complete</a>
							</li>
						</ul>
					</div>
				</div> 
			</div>
		</div>
	</div>
</div>