<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/wpm.css';?>"/>
<style>
    .mar_30{margin-top:30px;}
    .jqx-widget-content {z-index:999 !important;}
    ul,li{list-style:none;}
    /*-----------------------inner module tab-----------------*/
    .innermdl_tabs												{background-color:#e7e9ec; border-bottom:1px solid #2d74b4 !important;border:0px;}
    .innermdl_tabs li											{margin:0px !important;width:16%!important;}
    .innermdl_tabs li a											{color:#212121;text-align:center;padding:10px 22px 8px 22px; font-size:13px; font-weight:600;display:block;border-radius: 0px;margin:0px;border-bottom:3px solid #e7e9ec;border-top:0px !important; border-right:0px !important;border-left:0px !important;}
    .innermdl_tabs li a:after									{content:''; width:1px; height:20px; background-color:#bccae7; position:absolute; right:0px;}
    .innermdl_tabs li:last-child a:after						{content:''; width:0px;}
    .innermdl_tabs li ul li a									{text-align:left;font-size:13px;border-bottom:0px !important;}
    .innermdl_tabs li ul li a:after								{background:none !important;}
    .innermdl_tabs>li>a:hover,.innermdl_tabs>li.active>a,.innermdl_tabs>li.active>a:focus,.innermdl_tabs>li.active>a:hover{background-color:#e1e3e7 !important;color:#3f6ac3;font-weight:600;border-bottom:3px solid #2d74b4 !important;border-top:0px !important; border-right:0px !important;border-left:0px !important;}
    .innermdl_tabs li a span									{color:#3f6ac3;padding:0px 10px 0px 0px;}

    /*---------------------Responsive css---------------------*/
    @media screen and (max-width:1280px)						         {
    }
    @media only screen and (min-width : 769px) and (max-width : 800px) {
    }
    @media screen and (min-width : 361px) and (max-width : 768px){
        .innermdl_tabs li				{margin:0px !important;width:100%!important;}
    }
    @media only screen and (min-width : 321px) and (max-width : 360px)	{
        .innermdl_tabs li				{margin:0px !important; width:100%!important;}
    }
    @media only screen and (width : 320px)  {
        .innermdl_tabs li				{ margin:0px !important;width:100%!important;}
    }
    @media only screen and (width : 480px)  {
        .innermdl_tabs li				{margin:0px !important; width:100%!important;}
    }
    @media only screen and (width : 640px)  {
        .innermdl_tabs li				{ margin:0px !important;}
    }
    @media only screen and (min-width : 320px) and (max-width : 1199px) 		{
        .innermdl_tabs li				{margin:0px !important;margin:0px !important;}
    }
    @media only screen and (min-width : 981px) and (max-width : 1024px) {
    }
    .innermdl_tabs li {margin: 0px !important;width: 20%!important;}

    #grddetails .jqx-grid-header 	{height:40px !important;}
</style>
<div class="col-lg-12 padlr0" style="z-index: 999!important;">
    <nav class="navbar inrmdltab_navbar navbar-default">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle mdlnvbr_tgl collapsed ripple" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand inrmdl_navbrand ripple" href="javascript:void(0);">Select Menus</a>
        </div>
        <div id="navbar" class="navbar-collapse padlr0 collapse">
            <ul class="nav nav-tabs innermdl_tabs">
                <li id="slTypeDet" class="active"><a href="#dts" class="ripple" data-toggle="tab"><span id="tabText"></span></a></li>
                <!--<li id="whtab"  onclick="whtabclick();" ><a href="#whst" class="ripple" data-toggle="tab">WareHouse Stock</a></li>
                <li id="mbreaktab"  onclick="mbreaktabclick();" ><a href="#mbreak" class="ripple" data-toggle="tab">Month/Day-Wise BreakUp</a></li>-->
            </ul>
        </div>
    </nav>
</div>

<div class="tab-content">
    <div class="tab-pane active" id="dts">
        <div class="col-lg-12 clear padlr0">
            <div class="table-responsive clear">
                <div style='margin-top:10px;' id="grddetails"> </div>
            </div>
        </div>
    </div>
    <!--<div class="tab-pane active" id="whst">
        <div class="col-lg-12 clear padlr0">
            <div class="table-responsive clear">
                <div style='margin-top:10px;' id="grdwhstock"> </div>
            </div>
        </div>
    </div>-->
</div>
<script type="text/javascript">
    var slTransDet = <?php echo (isset($slTransDet)) ? json_encode($slTransDet) : '[]';?>;
    var SLTypeName= '<?php echo $SLTypeName;?>';
    var $grddetails=$('#grddetails');

    function renderRowDetail1(SLTypeId,SLId,SLName) {
        var dataValue = '';
        $.ajax({
            url: getBaseURL() + 'fa/report/slanalysisbilldet',
            type: 'POST',
            data: {'SLTypeId':SLTypeId,'SLId':SLId,'SLName':SLName,'fromDate': $('#fromDate').val(),'toDate':$('#toDate').val()},
            async: false,
            virtualmode: true,

            success: function(data,status, xhr) {
                if(xhr.status == 200)
                    dataValue = data;
            }, error: function(xhr, status, errorThrown) {
            }
        });
        return dataValue;
    }

    $(document).ready(function () {
        $('#tabText').text('Sub Ledger Detail : '+SLTypeName);
        //$('#tabText').text('Transaction Detail : '+SLName); next page tab text

        var source = {
            localdata: slTransDet,
            datatype: "json",
            pagesize:6,
            datafields:
                [
                    { name: "SLTypeId", type: "number" },
                    { name: "SLId", type: "number" },
                    { name: "SLName", type: "string" },
                    { name: "Debit", type: "number" },
                    { name: "Credit", type: "number" },
                    { name: "VType", type: "string" },
                    { name: "Group", type: "string" }
                ]
        };

        var dataAdapter = new $.jqx.dataAdapter(source);
        var initrowdetails = function (index, parentElement, gridElement, datarecord) {
            var $tabsdiv = $($(parentElement).children()[0]);

            $tabsdiv.append(renderRowDetail1(datarecord.SLTypeId,datarecord.SLId,datarecord.SLName));

        };

        $grddetails.jqxGrid(
            {
                width: "100%",
                source: dataAdapter,
                pageable: true,
                columnsresize: true,
                autoheight: true,
                sortable: true,
                altrows: true,
                enabletooltips: true,
                showfilterrow: false,
                filterable: true,
                groupable: true,
                showstatusbar: true,
                statusbarheight: 35,
                showaggregates: true,
                autorowheight: true,
                rowdetails:true,
                initrowdetails:initrowdetails,
                rowdetailstemplate: { rowdetails: "<div style='height:100%;overflow:auto; border:2px solid #de7762;'></div>", rowdetailsheight:400},
                columns: [
                    { text: 'SLTypeId', dataField: 'SLTypeId',hidden:true},
                    { text: 'SLId', dataField: 'SLId',hidden:true},
                    { text: 'Sub Ledger Name', dataField: 'SLName', align: 'left', cellsalign: 'left',width:'40%'},
                    { text: 'Debit', datafield: 'Debit', width: '30%',align:'left',
                        cellsrenderer: function (row) {
                            return '<div class="text-right" style="overflow: hidden; text-overflow: ellipsis; margin-right: 2px; margin-left: 10px; margin-top: 9.5px;">' + sanitizeNumber($grddetails.jqxGrid('getCellValue', row, 'Debit'),2,true) + '</div>';
                        },
                        aggregates:
                            [
                                { '<b>Debit</b>':
                                    function (aggregatedValue, currentValue, column, record) {
                                        var renderstring = "<div style='margin:8px;display:inline-block'>";
                                        var sumDebit = $grddetails.jqxGrid('getcolumnaggregateddata', 'Debit', ['sum']);
                                        renderstring += '<div><strong>' + sanitizeNumber(parseFloatVal(sumDebit.sum, 0), 2, true) + '</div></strong>';
                                        renderstring += "</div>";
                                        return renderstring;
                                    }
                                }
                            ]
                    },
                    { text: 'Credit', datafield: 'Credit', width: '30%',align:'left',
                        cellsrenderer: function (row) {
                            return '<div class="text-right" style="overflow: hidden; text-overflow: ellipsis; margin-right: 2px; margin-left: 10px; margin-top: 9.5px;">' + sanitizeNumber($grddetails.jqxGrid('getCellValue', row, 'Credit'),2,true) + '</div>';
                        },
                        aggregates:
                            [
                                { '<b>Credit</b>':
                                    function (aggregatedValue, currentValue, column, record) {
                                        var renderstring = "<div style='margin:8px;display:inline-block'>";
                                        var sumCredit = $grddetails.jqxGrid('getcolumnaggregateddata', 'Credit', ['sum']);
                                        renderstring += '<div><strong>' + sanitizeNumber(parseFloatVal(sumCredit.sum, 0), 2, true) + '</div></strong>';
                                        renderstring += "</div>";
                                        return renderstring;
                                    }
                                }
                            ]
                    }
                ]
            });
        $grddetails.jqxGrid('showgroupsheader', false);
        //Print option
        $("#excelExport").click(function () {
            $grddetails.jqxGrid('exportdata', 'xls', 'jqxGrid');
        });
        $("#csvExport").click(function () {
            $grddetails.jqxGrid('exportdata', 'csv', 'jqxGrid');
        });
        $("#htmlExport").click(function () {
            $grddetails.jqxGrid('exportdata', 'html', 'jqxGrid');
        });

        $("#print").click(function () {
            var gridContent = $grddetails.jqxGrid('exportdata', 'html');
            //var gridContent = $("#jqxgrid").jqxGrid('exportdata', 'html', 'jqxGrid', true, null, false);
            var newWindow = window.open('', '', 'width=800, height=500'),
                document = newWindow.document.open(),
                pageContent =
                    '<!DOCTYPE html>\n' +
                    '<html>\n' +
                    '<head>\n' +
                    '<meta charset="utf-8" />\n' +
                    '<title>Stock Details</title>\n' +
                    '<h1>Stock Details</h1>\n' +
                    '</head>\n' +
                    '<body>\n' + gridContent + '\n</body>\n</html>';
            document.write(pageContent);
            document.close();
            newWindow.print();

        });

        $grddetails.bind('rowselect', function (event) {
            var row = event.args.rowindex;
            var datarow = $grddetails.jqxGrid('getrowdata', row);

        });
    });
</script>