<style type="text/css">
    tr[data-role="row-details"] {
        display: none;
    }
    /*--------------Jqx Grid jqx All-------------------*/
    #treeGrid									{min-height:200px !important;}
    .jqx-widget .jqx-grid-columngroup-header	{border-top:0px !important;}
    .jqx-widget .jqx-grid-columngroup-header > div	{ margin-top:7px !important;}
    .jqx-dropdownlist-state-normal  			{margin:2px 4px !important;}
    .jqx-grid-pager .jqx-dropdownlist-state-normal  			{margin-top: 0 !important;}
    .jqx-widget-header							{border-bottom: 1px solid #5d9bb6 !important;border-top: 1px solid #ddd !important;}
    .jqx-grid-pager-input						{margin-top: 2px !important; padding: 2px;text-align: center !important; width: 35px;}
    .jqx-dropdownlist-state-normal				{display: block;  float: right;height: 16px;margin-right: 7px;margin-top: 0;  padding-bottom: 2px;padding-top: 2px; width: 40px;}
    .jqx-button									{cursor: pointer;float: right;margin-right: 3px !important;margin-top: 0 !important;padding: 0 !important;width: 20px !important;}
    .jqx-button > .jqx-icon-arrow-left,
    .jqx-button >.jqx-icon-arrow-right			{height: 21px !important;margin-left: 0 !important;width: 20px !important;}
    .jqx-listitem-element						{height: 25px !important;}
    .proname_btn .select2-container{ background-color:#efefef;color:#244996;}
    .proname_btn .select2-container .select2-selection--single .select2-selection__rendered{padding-top:0px; padding-bottom:5px;}
    .proname_btn .select2-container--default .select2-selection--single{font-size:26px; line-height:28px;}

    /* Excel Floating Icon */
    .fixed-action-btn          	    {position:fixed;top:85px;right:5px;padding-top:15px;margin-bottom:0;z-index:998;}
    .fixed-action-btn:hover ul li a.btn-floating{transform: scaleY(1) scaleX(1) translateX(0px);opacity: 1;}
    .btn-floating.btn-large         {width:45px;height:45px;}
    .fixed-action-btn ul 			{left:-142px;right:0;text-align:center;position:absolute;margin:0;top:22px;}
    .fixed-action-btn ul li 		{margin-left:8px;list-style-type:none;float:left;}
    .fixed-action-btn ul li a.btn-floating {transform: scaleY(0.4) scaleX(0.4) translateX(40px);opacity: 0;}
    .fixed-action-btn ul a.btn-floating i  {font-size: 17px;line-height: 37px;}
    .btn-floating                   {display:inline-block;color:#fff;position:relative;overflow:hidden;z-index:1;width:37px;height:37px;line-height:37px;padding: 0;
        background-color: #26a69a;border-radius:50%;cursor:pointer;vertical-align: middle;
        box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);text-decoration: none;transition: all .3s ease;
        -webkit-transition: all .3s ease; -moz-transition: all .3s ease; -o-transition: all .3s ease;}
    .btn-floating i                 {width: inherit;display: inline-block;text-align: center;color: #fff;font-size:20px;line-height: 45px; font-weight:normal; color:#fff;}
    .next-bt                        {text-align:center;}
    .next-bt a:hover                {border:1px solid #3580C4 !important; background:#fff !important; color:#3580C4 !important;}
    .next-bt a                      {background:#3580C4!important;border:1px solid #3580C4; border-radius: 4px;
        color:#fff!important; font-size:14px; padding: 5px 10px; text-align: center; transition: all 0.4s ease 0s;}
    .commargin_bottom				{margin-bottom:20px !important;}
    .req_addbtn a {padding: 6px 8px 9px 9px !important;}

    /* Excel Floating Icon end*/
</style>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqx-all.js"></script>
<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
        <div class="col-lg-12">
            <h1 class="col-lg-6 padlr0">
                Summary TB<?php echo (isset($companyName)) ? ' - '.$companyName : '';?>
            </h1>
            <input type="hidden" id="g_lCNYearId" name="g_lCNYearId" value="<?php echo $g_lCNYearId; ?>"/>
            <div class="form-group col-lg-12 clear padtop20 commargin_ttop_20 commargin_bottom">
                <div class=" col-lg-4" style="display: none;">
                    <span class="date_icon"><i class="fa fa-calendar"></i></span>
                    <input type="text" name="fromDate" id="fromDate" class="form-control lbl_move datepickerinput" onchange="loadTransfers()" label="From Date" value="<?php echo (isset($fromDate)) ? $fromDate : $prevMonth;?>" />
                </div>
                <div class="col-lg-4">
                    <span class="date_icon"><i class="fa fa-calendar"></i></span>
                    <input type="text" name="toDate" id="toDate" class="form-control lbl_move datepickerinput" onchange="loadTransfers()" label="As on Date" value="<?php echo (isset($toDate)) ? $toDate: $curDate;?>" />
                </div>
                <div class="col-lg-2">
                    <input type="hidden" id="accIds" name="accIds" />
                    <input type="hidden" id="accNames" name="accNames" />
                    <a class="btn btn-default" id="jqxbutton">Expand<i class="fa fa-sitemap" style="margin-left:5px;color:#337ab7;"></i></a>
                    <a class="btn btn-default"  id="jqxbuttorenn">Collapse<i class="fa fa-sitemap" style="margin-left:5px;color:#337ab7;"></i></a>
                    <!--<a class="btn btn-default" onclick="sendSelectedAccount()" id="selectedAcc">View Report for Selected Accounts<i class="fa fa-sitemap" style="margin-left:5px;color:#337ab7;"></i></a>-->
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6">
            <div class="fixed-action-btn active">
                <a class="btn-floating btn-large">
                    <i class="fa fa-print"></i>
                </a>
                <ul>
                    <li>
                        <a class="btn-floating hide-input-file" id="print" href="javascript:void(0);" data-toggle="tooltip" data-placement="top" data-original-title="Print Report">
                            <i class="fa fa-print"></i>
                        </a>
                    </li>
                    <li>
                        <a class="btn-floating" id="excelExport" href="javascript:void(0);" data-toggle="tooltip" data-placement="top" data-original-title="Download Excel">
                            <i class="fa fa-download"></i>
                        </a>
                    </li>
                    <li>
                        <a class="btn-floating" id="csvExport" href="javascript:void(0);" data-toggle="tooltip" data-placement="top" data-original-title="Export CSV">
                            <i class="fa fa-file-archive-o"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-lg-12 clear">
            <div class="table-responsive clear">
                <div id="treeGrid">
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var arr_Lists = <?php echo (isset($accDirectoryList)) ? json_encode($accDirectoryList) : "[]";?>;
    var accCheckedList = <?php echo (isset($accCheckedList)) ? json_encode($accCheckedList) : "[]";?>;
    var fYearId = <?php echo (isset($fYearId)) ? json_encode($fYearId) : "0";?>;
    var companyId = <?php echo (isset($companyId)) ? json_encode($companyId) : "0";?>;

    var startDate="<?php echo (isset($fiscalfromDate)) ? $fiscalfromDate : '';?>";
    var endDate="<?php echo (isset($fiscaltoDate)) ? $fiscaltoDate : '';?>";
    var start_date =startDate.split('-');
    var end_date =endDate.split('-');

    $('.datepickerinput').datepicker({
        'format': 'dd-mm-yyyy',
        startDate: new Date(start_date[2],start_date[1]-1,start_date[0]),
        endDate: new Date(end_date[2],end_date[1]-1,end_date[0])
    }).on('changeDate', function() {
        $('.datepicker').hide();
    }).data('datepicker');

    $treeGrid =$("#treeGrid");
    $('#jqxbuttorenn').hide();

    $(document).ready(function () {
        $(".single_dropdown").select2({
            placeholder: "",
            allowClear: true
        });
    });

    function loadTransfers(){
        window.location = getBaseURL() + 'fa/report/summarytbrpt/'+$('#fromDate').val()+'/'+$('#toDate').val();
    }

    if(arr_Lists == "[]"){
        $treeGrid.jqxTreeGrid('clear');
    } else {
        var source =
        {
            dataType: "json",
            dataFields: [

                /*
                 OBDebit=ISNULL(B.OBDebit,0),OBCredit=ISNULL
                 (B.OBCredit,0),TBDebit=ISNULL(B.TBDebit,0),TBCredit=ISNULL(B.TBCredit,0),CBDebit=
                 CASE WHEN ISNULL(B.OBDebit,0)+ISNULL(B.TBDebit,0)-ISNULL(B.OBCredit,0)-ISNULL(B.TBCredit,0)>0
                 THEN ISNULL(B.OBDebit,0)+ISNULL(B.TBDebit,0)-ISNULL(B.OBCredit,0)-ISNULL(B.TBCredit,0) ELSE 0 END ,

*/
                 { name: "AccountId", type: "number" },
                { name: "AccountName", type: "string" },
                { name: "ParentAccountId", type: "number" },
                { name: "LastLevel", type: "string" },
                { name: "OBDebit", type: "number" },
                { name: "OBCredit", type: "number" },
                { name: "TBDebit", type: "number" },
                { name: "TBCredit", type: "number" },
                { name: "CBDebit", type: "number" },
                { name: "CBCredit", type: "number" }
            ],
            hierarchy:
            {
                keyDataField: { name: 'AccountId' },
                parentDataField: { name: 'ParentAccountId' }
            },
            id: 'AccountId',
            localData: arr_Lists
        };
        var dataAdapter = new $.jqx.dataAdapter(source, {
            loadComplete: function () {
                // data is loaded.
            }
        });

        $treeGrid.jqxTreeGrid({
            width: "100%",
            source: dataAdapter,
            pageable: true,
            pagerMode: 'advanced',
            pagerHeight: 40,
            filterable: true,
            filterMode: 'simple',
            editable: false,
            showAggregates: true,
            aggregatesHeight: 35,
            altRows: true,
            ready: function()
            {
                $("#treeGrid").jqxTreeGrid('hideColumn', 'AccountId');
                $("#treeGrid").jqxTreeGrid('hideColumn', 'ParentAccountId');
            },
            columns: [
                { text: 'Account', dataField: "AccountName", align: 'left', cellsAlign: 'left' , width: '20%' },
                { text: 'AccountId', dataField: "AccountId", align: 'right', cellsAlign: 'right' , cellsFormat: 'd', hidden:true, filterable: false},
                { text: 'ParentAccountId', dataField: "ParentAccountId", align: 'right', cellsAlign: 'right' , cellsFormat: 'd', hidden:true, filterable: false },
                { text: 'LastLevel', dataField: "LastLevel", align: 'right', cellsAlign: 'right', hidden:true, filterable: false},
                { text: 'OBDebit', dataField: "OBDebit", align: 'right', cellsAlign: 'right' , cellsFormat: 'd2', width: '15%', aggregates: ['sum'],
                    aggregatesRenderer: function (aggregatesText, column, element, aggregates, type) {
                        if (type == "aggregates") {
                            var renderString = "<div style='margin: 8px; float: right;  height: 100%;'>";
                        } else {
                            var renderString = "<div style='float: right;  height: 100%;'>";
                        }
                        //var euro = dataAdapter.formatNumber(0.74 * aggregates.Total, "f2");;
                        var usd = 0;
                        if(aggregates != null){
                            usd = dataAdapter.formatNumber(aggregates.sum, "f2");
                        }
                        renderString += "<table><tr><td rowspan='2'></td><td align='right'><strong>" + sanitizeNumber(parseFloatVal(usd,0),2,true) + "</strong></td></table>";
                        return renderString;
                    }
                },
                { text: 'OBCredit', dataField: "OBCredit", align: 'right', cellsAlign: 'right' , cellsFormat: 'd2', width: '15%', aggregates: ['sum'],
                    aggregatesRenderer: function (aggregatesText, column, element, aggregates, type) {
                        if (type == "aggregates") {
                            var renderString = "<div style='margin: 8px; float: right;  height: 100%;'>";
                        } else {
                            var renderString = "<div style='float: right;  height: 100%;'>";
                        }
                        //var euro = dataAdapter.formatNumber(0.74 * aggregates.Total, "f2");;
                        var usd = 0;
                        if(aggregates != null){
                            usd = dataAdapter.formatNumber(aggregates.sum, "f2");
                        }
                        renderString += "<table><tr><td rowspan='2'></td><td align='right'><strong>" + sanitizeNumber(parseFloatVal(usd,0),2,true) + "</strong></td></table>";
                        return renderString;
                    }
                },
                { text: 'TBDebit', dataField: "TBDebit", align: 'right', cellsAlign: 'right' , cellsFormat: 'd2', width: '15%', aggregates: ['sum'],
                    aggregatesRenderer: function (aggregatesText, column, element, aggregates, type) {
                        if (type == "aggregates") {
                            var renderString = "<div style='margin: 8px; float: right;  height: 100%;'>";
                        } else {
                            var renderString = "<div style='float: right;  height: 100%;'>";
                        }
                        //var euro = dataAdapter.formatNumber(0.74 * aggregates.Total, "f2");;
                        var usd = 0;
                        if(aggregates != null){
                            usd = dataAdapter.formatNumber(aggregates.sum, "f2");
                        }
                        renderString += "<table><tr><td rowspan='2'></td><td align='right'><strong>" + sanitizeNumber(parseFloatVal(usd,0),2,true) + "</strong></td></table>";
                        return renderString;
                    }
                },
                { text: 'TBCredit', dataField: "TBCredit", align: 'right', cellsAlign: 'right' , cellsFormat: 'd2', width: '15%', aggregates: ['sum'],
                    aggregatesRenderer: function (aggregatesText, column, element, aggregates, type) {
                        if (type == "aggregates") {
                            var renderString = "<div style='margin: 8px; float: right;  height: 100%;'>";
                        } else {
                            var renderString = "<div style='float: right;  height: 100%;'>";
                        }
                        //var euro = dataAdapter.formatNumber(0.74 * aggregates.Total, "f2");;
                        var usd = 0;
                        if(aggregates != null){
                            usd = dataAdapter.formatNumber(aggregates.sum, "f2");
                        }
                        renderString += "<table><tr><td rowspan='2'></td><td align='right'><strong>" + sanitizeNumber(parseFloatVal(usd,0),2,true) + "</strong></td></table>";
                        return renderString;
                    }
                },
                { text: 'CBDebit', dataField: "CBDebit", align: 'right', cellsAlign: 'right' , cellsFormat: 'd2', width: '10%', aggregates: ['sum'],
                    aggregatesRenderer: function (aggregatesText, column, element, aggregates, type) {
                        if (type == "aggregates") {
                            var renderString = "<div style='margin: 8px; float: right;  height: 100%;'>";
                        } else {
                            var renderString = "<div style='float: right;  height: 100%;'>";
                        }
                        //var euro = dataAdapter.formatNumber(0.74 * aggregates.Total, "f2");;
                        var usd = 0;
                        if(aggregates != null){
                            usd = dataAdapter.formatNumber(aggregates.sum, "f2");
                        }
                        renderString += "<table><tr><td rowspan='2'></td><td align='right'><strong>" + sanitizeNumber(parseFloatVal(usd,0),2,true) + "</strong></td></table>";
                        return renderString;
                    }
                },
                { text: 'CBCredit', dataField: "CBCredit", align: 'right', cellsAlign: 'right' , cellsFormat: 'd2', width: '10%', aggregates: ['sum'],
                    aggregatesRenderer: function (aggregatesText, column, element, aggregates, type) {
                        if (type == "aggregates") {
                            var renderString = "<div style='margin: 8px; float: right;  height: 100%;'>";
                        } else {
                            var renderString = "<div style='float: right;  height: 100%;'>";
                        }
                        //var euro = dataAdapter.formatNumber(0.74 * aggregates.Total, "f2");;
                        var usd = 0;
                        if(aggregates != null){
                            usd = dataAdapter.formatNumber(aggregates.sum, "f2");
                        }
                        renderString += "<table><tr><td rowspan='2'></td><td align='right'><strong>" + sanitizeNumber(parseFloatVal(usd,0),2,true) + "</strong></td></table>";
                        return renderString;
                    }
                },
                { text: 'Action', sortable: false, filterable: false, align: 'left', width:'10%',
                    cellsrenderer: function (event) {
                        var editLink = '<a title="Edit" href="javascript:void(0);" onclick="viewReport('+event+');" style="padding-left: 15px;"><i class="fa fa-pencil-square-o reg-icon"></i></a>';
                        return editLink += "&nbsp;&nbsp;" + '<button style="background: transparent;" title="Delete" onclick="addReportList('+event+'); return false;"><i class="fa fa-trash-o reg-icon"></i></button>';
                        return editLink;
                    }
                }
            ]
        });

        /*$treeGrid.on('rowDoubleClick', function (event) {
         var args = event.args;
         var row = args.row;
         var fromSL=row.FromSL;
         var lastLevel=row.LastLevel;
         if(fromSL==0 && lastLevel=="Y") {
         var id = row.AccountId;
         var g_lCNYearId = $('#g_lCNYearId').val();
         window.location.replace(getBaseURL() + "fa/report/ccbalance/" + id +"/" + g_lCNYearId);
         } else if(fromSL==1 && lastLevel=="Y") {
         var id = row.AccountId;
         //var g_lCNYearId = $('#g_lCNYearId').val();
         window.location.replace(getBaseURL() + "fa/report/slbalance/" + id);
         }
         });*/

        //Print option
        $("#excelExport").click(function () {
            $("#treeGrid").jqxTreeGrid('exportData', 'xls');
        });
        $("#csvExport").click(function () {
            $("#treeGrid").jqxTreeGrid('exportData', 'csv');
        });
        $("#htmlExport").click(function () {
            $("#treeGrid").jqxTreeGrid('exportData', 'html');
        });

        $("#print").click(function () {
            $("#treeGrid").jqxTreeGrid('exportData', 'html');
        });

        $('#jqxbutton').click(function () {
            $("#treeGrid").jqxTreeGrid('expandAll');
            $('#jqxbutton').hide();
            $('#jqxbuttorenn').show();
        });

        $('#jqxbuttorenn').click(function () {
            $("#treeGrid").jqxTreeGrid('render');
            $('#jqxbutton').show();
            $('#jqxbuttorenn').hide();
        });
    }
    function viewReport(event) {
        var args = event.args;
        var AccountId=$treeGrid.jqxTreeGrid('getCellValue', event, 'AccountId');
        if(AccountId!=0){
            //        window.location.replace(getBaseURL() + "fa/index/summarytbtrans/" + AccountId + '/'+$('#fromDate').val()+'/'+$('#toDate').val());
            window.open(getBaseURL() + "fa/report/summarytbtrans/" + AccountId + '/'+$('#fromDate').val()+'/'+$('#toDate').val());
        }
    }
    var accountIds=[];
    var accountNames=[];
    function addReportList(event){
        var args = event.args;
        var AccountId=$treeGrid.jqxTreeGrid('getCellValue', event, 'AccountId');
        var AccountName=$treeGrid.jqxTreeGrid('getCellValue', event, 'AccountName');
        if($.inArray(AccountId,accountIds) === -1) {
            accountIds.push(AccountId);
            accountNames.push(AccountName);
        }
        $('#accIds').val(accountIds.toString());
        $('#accNames').val(accountNames);
    }
    function sendSelectedAccount(){
        var accIds=$('#accIds').val();
        if(accIds.length != 0){
//            window.location.replace(getBaseURL() + "fa/report/summarytbtrans/" + accIds + '/'+$('#fromDate').val()+'/'+$('#toDate').val());
            window.open(getBaseURL() + "fa/report/summarytbtrans/" + accIds + '/'+$('#fromDate').val()+'/'+$('#toDate').val());
        }
    }
</script>