<style>
    #vendorServiceListWrapper {
        display: none;
    }
    .pagination-lg > li > a, .pagination-lg > li > span {
        font-size:15px !important;
        padding:5px 15px !important;
    }
    /* Excel Floating Icon */
    .fixed-action-btn          	    {position:fixed;top:85px;right:5px;padding-top:15px;margin-bottom:0;z-index:998;}
    .fixed-action-btn:hover ul li a.btn-floating{transform: scaleY(1) scaleX(1) translateX(0px);opacity: 1;}
    .btn-floating.btn-large         {width:45px;height:45px;}
    .fixed-action-btn ul 			{left:-142px;right:0;text-align:center;position:absolute;margin:0;top:22px;}
    .fixed-action-btn ul li 		{margin-left:8px;list-style-type:none;float:left;}
    .fixed-action-btn ul li a.btn-floating {transform: scaleY(0.4) scaleX(0.4) translateX(40px);opacity: 0;}
    .fixed-action-btn ul a.btn-floating i  {font-size: 17px;line-height: 37px;}
    .btn-floating                   {display:inline-block;color:#fff;position:relative;overflow:hidden;z-index:1;width:37px;height:37px;line-height:37px;padding: 0;
        background-color: #26a69a;border-radius:50%;cursor:pointer;vertical-align: middle;
        box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);text-decoration: none;transition: all .3s ease;
        -webkit-transition: all .3s ease; -moz-transition: all .3s ease; -o-transition: all .3s ease;}
    .btn-floating i                 {width: inherit;display: inline-block;text-align: center;color: #fff;font-size:20px;line-height: 45px; font-weight:normal; color:#fff;}
    .next-bt                        {text-align:center;}
    .next-bt a:hover                {border:1px solid #3580C4 !important; background:#fff !important; color:#3580C4 !important;}
    .next-bt a                      {background:#3580C4!important;border:1px solid #3580C4; border-radius: 4px;
        color:#fff!important; font-size:14px; padding: 5px 10px; text-align: center; transition: all 0.4s ease 0s;}
    .commargin_top 					{margin-top: 30px;}

    /* Excel Floating Icon end*/
    /*--------------Jqx Grid jqx All-------------------*/
    #jqxgrid									{min-height:200px !important;}
    .jqx-grid-header                            {height:75px !important;}
    .jqx-grid-groups-row						{padding-left:5px !important;}
    .jqx-grid-pager-input						{padding: 2px; text-align: center !important; width: 35px;}
    .jqx-dropdownlist-state-normal				{display: block;  float: right;height: 16px !important;margin-right: 7px;margin-top: 0;  padding-bottom: 2px !important;padding-top: 2px !important; width: 40px;}
    .jqx-button									{cursor: pointer;float: right;margin-right: 3px !important;margin-top: 0 !important;padding: 0 !important;width: 20px !important;}
    .jqx-button > .jqx-icon-arrow-left,
    .jqx-button >.jqx-icon-arrow-right			{height: 21px !important;margin-left: 0 !important;width: 20px !important;}
    .jqx-listitem-element						{height: 25px !important;}
    .jqx-input									{height: 25px !important; margin:2px 4px !important;}
    .jqx-grid-pager .jqx-grid-pager-input		{height:20px !important; margin:0px 4px !important;}
    #jqxgrid .jqx-grid-cell-right-align 		{text-align:right !important; padding-right:8px;}
    #jqxgrid .jqx-grid-cell-left-align 			{padding-left:8px;}
    .jqx-grid-column-menubutton::after			{left:4px;top:10px;}
</style>

<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqx-all.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqxgrid.grouping.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqxgrid.aggregates.js"></script>

<div class="content_wrapper  padlr0">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 padlr0">
                <div class="col-lg-6 col-md-6 col-sm-6 padlr0">
                    <h1 class="col-lg-8 col-md-6 col-sm-6"> Stock Ledger</h1>
                    <div class="col-lg-6">
                        <div class="fixed-action-btn active">
                            <a class="btn-floating btn-large">
                                <i class="fa fa-print"></i>
                            </a>
                            <ul>
                                <li>
                                    <a class="btn-floating hide-input-file" id="print" href="javascript:void(0);" data-toggle="tooltip" data-placement="top" data-original-title="Print Report">
                                        <i class="fa fa-print"></i>

                                    </a>
                                </li>
                                <li>
                                    <a class="btn-floating" id="excelExport" href="javascript:void(0);" data-toggle="tooltip" data-placement="top" data-original-title="Download Excel">
                                        <i class="fa fa-download"></i>
                                    </a>
                                </li>
                                <li>
                                    <a class="btn-floating" id="csvExport" href="javascript:void(0);" data-toggle="tooltip" data-placement="top" data-original-title="Export CSV">
                                        <i class="fa fa-file-archive-o"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-12 commargin_top">

                <div class="col-lg-3">
                    <select label="Type" class="form-control single_dropdown lbl_move sortoption" tabindex="7" name="type" id="type" style="width:100%;">
                        <option value="0">CostCentre</option>
                        <option value="1">WareHouse</option>
                    </select>
                </div>

                <div class="col-lg-3">
                    <select class="form-control multiple_dropdown lbl_move" label="CostCentreName" multiple="multiple" tabindex="7" name="costcentre" id="costcentre">
                        <option value=""></option>
                        <?php if(isset($arr_costcentre)):
                            foreach($arr_costcentre as $costcentre): ?>
                                <option value="<?php echo $costcentre['CostCentreId'];?>"><?php echo $costcentre['CostCentreName'];?></option>
                            <?php endforeach;
                        endif; ?>
                    </select>
                </div>

                <div class="col-lg-3">
                    <select class="form-control multiple_dropdown lbl_move" label="WareHouseName" multiple="multiple" tabindex="7" name="warehouse" id="warehouse" disabled>
                        <option value=""></option>
                        <?php if(isset($arr_warehouse)):
                            foreach($arr_warehouse as $warehouse): ?>
                                <option value="<?php echo $warehouse['WareHouseId'];?>"><?php echo $warehouse['WareHouseName'];?></option>
                            <?php endforeach;
                        endif; ?>
                    </select>
                </div>

                <div class="col-lg-3">
                    <select name="resource" id="resource" class="form-control single_dropdown lbl_move" label="ResourceName" tabindex="7" style="width:100%;">
                    </select>
                </div>
            </div>
            <div class="col-lg-12 clear">
                <div class="table-responsive clear">
                    <div style='margin-top:10px;' id="resourceGrid"> </div>
                </div>
            </div>


            </div>
        </div>
    </div>
<div class="col-lg-12 savebtn_area">
    <ul>
        <li class="dropdown save_btn float_r">
            <a href="<?php echo $this->basePath();?>/mms/report/reportlist" class="ripple">Close</a>
        </li>
    </ul>
</div>

<script type="text/javascript">

    //validate the costcentre and warehouse
    $('#type').change(function() {
        var type = $(this).val();
        if(type == 1){
            $("#warehouse").prop("disabled", false);
            $("#costcentre").prop("disabled", true);
        }
        else{

            $("#costcentre").prop("disabled", false);
            $("#warehouse").prop("disabled", true);
        }
    });


    var tmpLocalData = [];
    var $resourceGrid = $("#resourceGrid");
    var resourceSource = {
        localdata: [],
        dataType: "json",
        dataFields: [
            { name: 'TransNo', type: 'string' },
            { name: 'ResourceId', type: 'string' },
            { name: 'ItemId', type: 'string' },
            { name: 'CostCentreId', type: 'string' },
            { name: 'Date', type: 'string' },
            { name: 'Project', type: 'string' },
            { name: 'Description', type: 'string' },
            { name: 'Type', type: 'string' },
            { name: 'Receipt', type: 'string' },
            { name: 'Issue', type: 'string' },
            { name: 'ClosingStock', type: 'string' },
            { name: 'Qty', type: 'string' },
            { name: 'CDate', type: 'string' }
        ]
    };
    var resourceAdapter = new $.jqx.dataAdapter(resourceSource);
    $resourceGrid.jqxGrid({
        width: '100%',
        pageable: true,
        rowsheight: 35,
        selectionMode: 'singleRow',
        pagerButtonsCount: 6,
        autoheight:true,
        filterable: true,
        showfilterrow: true,
        source: resourceAdapter,
        editable: true,
        pagerMode: 'advanced',
        pagerHeight: 40,
        sortable: true,
        altrows: false,
        enabletooltips: true,
        showaggregates: true,
        keyboardnavigation: true,
        autorowheight: true,

        columns: [
            { dataField: 'ResourceId', hidden: true},
            { dataField: 'ItemId', hidden: true},
            { dataField: 'CostCentreId', hidden: true},
            { text: 'TransNo', dataField: 'TransNo',width:'10%', editable:false},
            { text: 'Date', dataField: 'Date',width:'10%', editable:false},
            { text: 'Project', dataField: 'Project',width:'10%', editable:false},
            { text: 'Description', dataField: 'Description',width:'15%', editable:false},
            { text: 'Type', dataField: 'Type',width:'5%', editable:false},
            { text: 'Receipt', dataField: 'Receipt',width:'10%', editable:false},
            { text: 'Issue', dataField: 'Issue',width:'10%', editable:false},
            { text: 'ClosingStock', dataField: 'ClosingStock',width:'15%', editable:false},
            { text: 'Qty', dataField: 'Qty',hidden: true},
            { text: 'CDate', dataField: 'CDate',width:'15%', editable:false}
        ]
    });


    //ajax for populate costcentre
    $('#warehouse').change(function() {
        var whId = $(this).val();
        if($.trim(whId) == ''){
            $('#resource').html('');
        }
        else{
            $('#resource').html('');
            $.ajax({
                type: "POST",
                url: getBaseURL()+'mms/stockreport/stock-ledger',
                data: "warehouseId="+whId+"&Type=selectWarehouse",
                dataType: "json",
                success: function(data) {
                    var opHtml = '<option value=""></option>';
                    $.each(data['sel_whResource'], function (k, j) {
                        opHtml += '<option id = "' + j.ItemId + '" common = "' + j.WareHouseId + '" value="' + j.ResourceId + '">' + j.ResourceCode + '</option>';
                    });
                    $('#resource').html(opHtml);
                }
            });
        }
    });

    //ajax for populate costcentre
    $('#costcentre').change(function() {
        var ccId = $(this).val();
        if($.trim(ccId) == ''){
            $('#resource').html('');
        }
        else{
            $('#resource').html('');
            $.ajax({
                type: "POST",
                url: getBaseURL()+'mms/stockreport/stock-ledger',
                data: "costcentreId="+ccId+"&Type=selectCostcentre",
                dataType: "json",
                success: function(data) {
                    var opHtml = '<option value=""></option>';
                    $.each(data['arr_Resources'], function (i, o) {
                        opHtml += '<option id = "' + o.ItemId + '" common = "' + o.CostCentreId + '" value="' + o.ResourceId + '">' + o.ResourceCode + '</option>';
                    });
                    $('#resource').html(opHtml);
                }
            });
        }

    });

    //ajax for populate resource
    $('#resource').change(function() {
        var resId = $(this).val();
        var type= $('#type').val();
        var common = 0;
        var select;
        var itemid = $('#resource option:selected').attr('id');

        if(type == 0){
            console.log(type);
            common = $('#costcentre').val();
            select = "selectResource";
        }
        else{
            common = $('#warehouse').val();
            select = "selectwareResource";
        }
        $('.loading_area').show();
        $.ajax({
            type: "POST",
            url: getBaseURL()+'mms/stockreport/stock-ledger',
            data: "resourceId="+resId+"&itemid="+itemid+"&common="+common+"&Type="+select,
            success: function(data){
                $resourceGrid.jqxGrid('clear');
                data = JSON.parse(data);
                tmpLocalData = data;
                console.log(tmpLocalData);
                renderRequestResources(data);
            }, error: function (jqXHR, textStatus, errorThrown) {
                $('.loading_area').hide();
            }
        });
    });
    function renderRequestResources(data) {
        resourceSource.localdata = data;
        resourceAdapter.dataBind();
    }
    </script>