<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
    	
        <!--------------------About---------------->

    
        <div class="col-lg-12">
            <h1>Reminder
            	<div class="stgedit_btn req_addbtn brad_50">
                    <a href="javascript:void(0);" class="ripple addnew_reminder" data-toggle="tooltip" data-placement="right" title="Add&nbsp;New&nbsp;Reminder"><i class="fa fa-plus"></i></a>
                </div>
            </h1>
            <script>
			$(document).ready(function(){
				$('.addnew_reminder').click(function (){
					$('.adddprtmnt_box').show("slow");
				});
				$('.close').click(function(){
					$('.adddprtmnt_box').hide();
				});
			});
			</script>
        </div>
        <div class="col-lg-12 clear">
            <div class="col-lg-12 padlr0 adddprtmnt_box" style="display:none;">
            	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                <div class="col-lg-1 col-md-1 col-sm-1">
                	<label>
                        <input type="checkbox" name="checkbox" checked class="ios_checkbox"/>
                        <div class="ios_switch"><span></span></div>
                    </label>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 padlr0">
                    <div class="form-group col-lg-12">
                        <textarea id="reminder_descrption" class="form-control lbl_move" label="Reminder Descrption"/></textarea>
                    </div>
                </div>
                <div class="col-lg-2 col-md-3 col-sm-3 padlr0">
                    <div class="form-group col-lg-12">
                    	<span class="date_icon"><i class="fa fa-calendar"></i></span>
                    	<input type="text" name="date" id="date" class="form-control date_picker lbl_move" label="Date" value=""/>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-3 padlr0">
                    <div class="form-group col-lg-12">
                        <select class="form-control multiple_dropdown lbl_move"  multiple="multiple" label="Users..." style="width:100%;">
                            <option>User 1</option>
                            <option>User 2</option>
                            <option>User 3</option>
                            <option>User 4</option>
                            <option>User 5</option>
                        </select>
                    </div>
                </div>
                <div class="col-lg-2 col-md-1 col-sm-1">
                    <div class="col-lg-12">
                    	<button type="button" class="adddprtmnt_box_ok float_r brad_200 ripple" data-dismiss="modal" aria-label="Close"><span class="glyphicon glyphicon-ok"></span></button>
                    </div>
                </div>	
            </div>
        </div>
        <div class="col-lg-12 clear">
            <div class="table-responsive" style="min-height:200px;">
                <table class="table table-hover tbltop_bdr0">
                    <thead>
                        <tr>
                            <th width="5%">LIVE</th>
                            <th>Reminder Descrption</th>
                            <th width="5%">&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <label>
                                    <input type="checkbox" name="checkbox" checked class="ios_checkbox"/>
                                    <div class="ios_switch"><span></span></div>
                                </label>
							</td>
                            <td>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque. Duis vulpu...</td>
                            <td class="action_btns_td">
                                <ul class="action_btns">
                                    <li>
                                        <a href="#" data-toggle="tooltip" data-placement="left" data-original-title="Delete">
                                            <span><i class="fa fa-trash-o"></i></span>
                                        </a>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label>
                                    <input type="checkbox" name="checkbox" class="ios_checkbox"/>
                                    <div class="ios_switch"><span></span></div>
                                </label>
							</td>
                            <td>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque. Duis vulpu...</td>
                            <td class="action_btns_td">
                                <ul class="action_btns">
                                    <li>
                                        <a href="#" data-toggle="tooltip" data-placement="left" data-original-title="Delete">
                                            <span><i class="fa fa-trash-o"></i></span>
                                        </a>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label>
                                    <input type="checkbox" name="checkbox" class="ios_checkbox"/>
                                    <div class="ios_switch"><span></span></div>
                                </label>
							</td>
                            <td>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque. Duis vulpu...</td>
                            <td class="action_btns_td">
                                <ul class="action_btns">
                                    <li>
                                        <a href="#" data-toggle="tooltip" data-placement="left" data-original-title="Delete">
                                            <span><i class="fa fa-trash-o"></i></span>
                                        </a>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label>
                                    <input type="checkbox" name="checkbox" checked class="ios_checkbox"/>
                                    <div class="ios_switch"><span></span></div>
                                </label>
							</td>
                            <td>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque. Duis vulpu...</td>
                            <td class="action_btns_td">
                                <ul class="action_btns">
                                    <li>
                                        <a href="#" data-toggle="tooltip" data-placement="left" data-original-title="Delete">
                                            <span><i class="fa fa-trash-o"></i></span>
                                        </a>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label>
                                    <input type="checkbox" name="checkbox" checked class="ios_checkbox"/>
                                    <div class="ios_switch"><span></span></div>
                                </label>
							</td>
                            <td>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque. Duis vulpu...</td>
                            <td class="action_btns_td">
                                <ul class="action_btns">
                                    <li>
                                        <a href="#" data-toggle="tooltip" data-placement="left" data-original-title="Delete">
                                            <span><i class="fa fa-trash-o"></i></span>
                                        </a>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script>
$(document).ready(function() {
	$(".multiple_dropdown").select2({
	});
});
$('.addnew_reminder').click(function (){
	$('.adddprtmnt_box').show("slow");
});
$('.close').click(function(){
	$('.adddprtmnt_box').hide();
});
</script>