<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
        <div class="col-lg-12">
            <h1>Users
            	<div class="stgedit_btn req_addbtn brad_50">
                    <a href="javascript:void(0);" class="ripple" data-toggle="tooltip" data-placement="right" title="Add&nbsp;New&nbsp;Users"><i class="fa fa-plus"></i></a>
                </div>
            </h1>
        </div> 
        <div class="col-lg-12 clear">
            <div class="row">
                <ul class="col-lg-12 users_grid animated_0_6s fadeInUp">
                    <li class="col-lg-4 col-md-6 col-sm-6 padlr0">
                    	<div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
                        	<h3>Balaji Ulagananathan</h3>
                            <p>Senior Software Engineer</p>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                        	<span class="comp_arrowlink"><a href="#" class="brad_50" data-toggle="tooltip" data-placement="left" title="View&nbsp;Profile"><i class="fa fa-gg"></i></a></span>
                            <div class="user_editlink comp_editlink brad_50"><a href="#" class="ripple brad_50" data-toggle="tooltip" data-placement="top" title="Edit&nbsp;Profile"><i class="fa fa-pencil"></i></a></div>
                            <div class="usersgrid_logo compgrid_logo brad_50 m_auto">
                                <span><img class="brad_50" src="<?php echo $this->basePath();?>/images/flwup_proimg.png" /></span>
                            </div>
                        </div>
                        <ul>
                        	<li>Dev 2</li>
                            <li>Level 12</li>
                            <li>Supervisor 1</li>
                        </ul>
                    </li>
                    <li class="col-lg-4 col-md-6 col-sm-6 padlr0">
                    	<div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
                        	<h3>Flarexrider Mugesh</h3>
                            <p>Front-end Developer</p>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                        	<span class="comp_arrowlink"><a href="#" class="brad_50" data-toggle="tooltip" data-placement="left" title="View&nbsp;Profile"><i class="fa fa-gg"></i></a></span>
                            <div class="user_editlink comp_editlink brad_50"><a href="#" class="ripple brad_50" data-toggle="tooltip" data-placement="top" title="Edit&nbsp;Profile"><i class="fa fa-pencil"></i></a></div>
                            <div class="usersgrid_logo compgrid_logo brad_50 m_auto">
                                <span><img class="brad_50" src="<?php echo $this->basePath();?>/images/pro_img.jpg" /></span>
                            </div>
                        </div>
                        <ul>
                        	<li>Dev 2</li>
                            <li>Level 12</li>
                            <li>Supervisor 1</li>
                        </ul>
                    </li>
                    <li class="col-lg-4 col-md-6 col-sm-6 padlr0">
                    	<div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
                        	<h3>Harish Dhananjayan</h3>
                            <p>Software Engineer</p>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                        	<span class="comp_arrowlink"><a href="#" class="brad_50" data-toggle="tooltip" data-placement="left" title="View&nbsp;Profile"><i class="fa fa-gg"></i></a></span>
                            <div class="user_editlink comp_editlink brad_50"><a href="#" class="ripple brad_50" data-toggle="tooltip" data-placement="top" title="Edit&nbsp;Profile"><i class="fa fa-pencil"></i></a></div>
                            <div class="usersgrid_logo compgrid_logo brad_50 m_auto">
                                <span><img class="brad_50" src="<?php echo $this->basePath();?>/images/profile1.png" /></span>
                            </div>
                        </div>
                        <ul>
                        	<li>Dev 2</li>
                            <li>Level 12</li>
                            <li>Supervisor 1</li>
                        </ul>
                    </li>
                    <li class="col-lg-4 col-md-6 col-sm-6 padlr0">
                    	<div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
                        	<h3>Flarexrider Mugesh</h3>
                            <p>Front-end Developer</p>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                        	<span class="comp_arrowlink"><a href="#" class="brad_50" data-toggle="tooltip" data-placement="left" title="View&nbsp;Profile"><i class="fa fa-gg"></i></a></span>
                            <div class="user_editlink comp_editlink brad_50"><a href="#" class="ripple brad_50" data-toggle="tooltip" data-placement="top" title="Edit&nbsp;Profile"><i class="fa fa-pencil"></i></a></div>
                            <div class="usersgrid_logo compgrid_logo brad_50 m_auto">
                                <span><img class="brad_50" src="<?php echo $this->basePath();?>/images/pro_img.jpg" /></span>
                            </div>
                        </div>
                        <ul>
                        	<li>Dev 2</li>
                            <li>Level 12</li>
                            <li>Supervisor 1</li>
                        </ul>
                    </li>
                    <li class="col-lg-4 col-md-6 col-sm-6 padlr0">
                    	<div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
                        	<h3>Harish Dhananjayan</h3>
                            <p>Software Engineer</p>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                        	<span class="comp_arrowlink"><a href="#" class="brad_50" data-toggle="tooltip" data-placement="left" title="View&nbsp;Profile"><i class="fa fa-gg"></i></a></span>
                            <div class="user_editlink comp_editlink brad_50"><a href="#" class="ripple brad_50" data-toggle="tooltip" data-placement="top" title="Edit&nbsp;Profile"><i class="fa fa-pencil"></i></a></div>
                            <div class="usersgrid_logo compgrid_logo brad_50 m_auto">
                                <span><img class="brad_50" src="<?php echo $this->basePath();?>/images/profile1.png" /></span>
                            </div>
                        </div>
                        <ul>
                        	<li>Dev 2</li>
                            <li>Level 12</li>
                            <li>Supervisor 1</li>
                        </ul>
                    </li>
                    <li class="col-lg-4 col-md-6 col-sm-6 padlr0">
                    	<div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
                        	<h3>Balaji Ulagananathan</h3>
                            <p>Senior Software Engineer</p>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                        	<span class="comp_arrowlink"><a href="#" class="brad_50" data-toggle="tooltip" data-placement="left" title="View&nbsp;Profile"><i class="fa fa-gg"></i></a></span>
                            <div class="user_editlink comp_editlink brad_50"><a href="#" class="ripple brad_50" data-toggle="tooltip" data-placement="top" title="Edit&nbsp;Profile"><i class="fa fa-pencil"></i></a></div>
                            <div class="usersgrid_logo compgrid_logo brad_50 m_auto">
                                <span><img class="brad_50" src="<?php echo $this->basePath();?>/images/flwup_proimg.png" /></span>
                            </div>
                        </div>
                        <ul>
                        	<li>Dev 2</li>
                            <li>Level 12</li>
                            <li>Supervisor 1</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>