<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css';?>"/>
<style>
.table-fixed tbody{max-height:250px;min-height:20px; overflow-y:auto;width:100%}
    .table-fixed thead,.table-fixed tbody,.table-fixed tr,.table-fixed td,.table-fixed th{display:block}
    .table-fixed tbody td,.table-fixed thead>tr>th{float:left; border-bottom:0; position:relative; text-overflow:ellipsis;visible;display:inline-block;white-space:nowrap}
	.table-fixed tbody tr.done{background:#EBF5DA;border:1px solid #9AB56D;}
	.table-fixed tbody td.check{color:#067A06; font-weight:600}
	.parent_text{height:40px}
</style>
<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
 <div class="col-md-4 col-sm-4 savebtn_area" style="border-top:none;margin:0">
                    <ul>
                       <li class="list-btn">
                            <a href="#" data-toggle="modal" data-target="#newGroupModal"><i class="fa fa-plus"></i> Add New</a>
                        </li>  
                    </ul>
                </div>
           
    </div>
</div>
<div id="newGroupModal" class="modal fade" role="dialog" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog  modal-lg" style="width:1100px">
        <div class="modal-content" style="background:#F2F4F7">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><i class="fa fa-times-circle-o clpot"></i></button>
                <h1>dsfsdfsdfd</h1>
            </div>
            <div class="modal-body">
			<ul class="nav nav-tabs nav-controls" role="tablist">
        <li role="presentation" class="active"><a href="#complete-his" aria-controls="complete-his" role="tab" data-toggle="tab">complete History</a></li>
         <li role="presentation"><a href="#approval-sts" aria-controls="approval-sts" role="tab" data-toggle="tab">Approval status</a></li> </ul> 
			<div class="tab-content col-md-12" style="padding:0 !important">                        
                <div class="col-md-12 tab-pane active" role="tabpanel" id="complete-his" style="background:#fff;border:1px solid #93b78b;padding:10px 0 !important;border-top:none;">
                   <div class="col-md-12 col-sm-12 animated-panel zoomIn">
             <div class="table-responsive">
			 <h2>complete History</h2>
                <table class="table table-fixed">
                    <thead>
                        <tr class="col-xs-12" style="padding:0 !important">
                            <th class="col-xs-2">Log Time</th>
                             <th class="col-xs-2">Role Name</th>
                              <th class="col-xs-2">User Name</th>
							   <th class="col-xs-2">Log Type</th>
							    <th class="col-xs-2">Log Description</th>
								 <th class="col-xs-2">Done By</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="col-xs-12" style="padding:0 !important">
                            <td class="col-xs-2"><input class="parent_text" value="25-05-2017" type="text"></td>
							<td class="col-xs-2"><input class="parent_text" value="fgdg" type="text"></td>
							<td class="col-xs-2"><input class="parent_text" value="dfgdfg" type="text"></td>
							<td class="col-xs-2"><input class="parent_text" value="dfgdfg" type="text"></td>
							<td class="col-xs-2"><input class="parent_text" value="dfgdfg" type="text"></td>
							<td class="col-xs-2"><input class="parent_text" value="dfgdfgext" type="text"></td>
						</tr>
						<tr class="col-xs-12" style="padding:0 !important">
                            <td class="col-xs-2"><input class="parent_text" value="25-05-2017" type="text"></td>
							<td class="col-xs-2"><input class="parent_text" value="fgdg" type="text"></td>
							<td class="col-xs-2"><input class="parent_text" value="dfgdfg" type="text"></td>
							<td class="col-xs-2"><input class="parent_text" value="dfgdfg" type="text"></td>
							<td class="col-xs-2"><input class="parent_text" value="dfgdfg" type="text"></td>
							<td class="col-xs-2"><input class="parent_text" value="dfgdfgext" type="text"></td>
						</tr>
						</tbody>
						</table>	  
                 </div>
               </div>				 
			</div>
			<div class="col-md-12 tab-pane" role="tabpanel" id="approval-sts" style="background:#fff;border:1px solid #93b78b;padding:10px 0 !important;border-top:none;">
	           <div class="col-lg-12 animated-panel zoomIn" style="margin-bottom:10px;">
			    <h2>Approval status</h2>
			      <table class="table table-fixed">
                    <thead>
                        <tr class="col-xs-12" style="padding:0 !important">
                            <th class="col-xs-9">User Name</th>
                             <th class="col-xs-3">Status</th>
					    </tr>
					</thead>
						 <tbody>
                          <tr class="col-xs-12 done" style="padding:0 !important">
                            <td class="col-xs-9">fghf</td>
							<td class="col-xs-3 check"><i class="fa fa-check"></i>
&nbsp;Done</td>
						 </tr>
						 <tr class="col-xs-12" style="padding:0 !important">
                            <td class="col-xs-9">fghf</td>
							<td class="col-xs-3">fgh fgfg</td>
						 </tr>
					</tbody>
			</table>
			</div>				
			</div>
			</div>
			</div>
			<div class="clearfix"></div>
            <div class="modal-footer"> <a href="javascript:void(0);" class="md_cance" onclick="return newGroupClose();" data-toggle="tooltip" data-original-title="Cancel" style="position: relative; overflow: hidden;">Cancel<span class="ripple-wrapper"></span><span class="ripple-wrapper"></span></a>
                <button type="button" class="md_ok" onclick="return newGroupAdd();" data-toggle="tooltip" data-original-title="OK">OK</button>
            </div>
        </div>
    </div>
</div>