<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/workorder.css';?>"/>
<style>
.feedback-panel				   {padding:20px;width:250px;background:#e3edf1;border:#0aa699 1px solid;position:absolute;top:200px;left:-250px;}
.feedback-panel a.feedback-tab {background: url('<?php echo $this->basePath(); ?>/images/feedback.png') no-repeat;border-width: 1px 1px 1px 0;display:block;
                                height:99px;left:248px;outline:medium none;position:absolute;text-indent: -9999px;width:39px;top:-1px;}
textarea 					   {width:90%;padding:5px;}
#response-message 			   {background:#fff;border:1px solid #ccc;padding:50px;margin-top:30px;}
.cbfedbckbutn 				   {padding:7px;text-align:center;background-color:#0aa699 !important;color:#fff;font-weight:600;}
#treeGrid .jqx-grid-header     {height:75px !important;}

</style>
<div class="feedback-panel"> <a class="feedback-tab" href="#">Feedback</a>
  <h1 style="font-size:24px;font-weight: 400 !important;">Send Us Feedback</h1>
  <div id="form-wrap">
    <form class="form-horizontal">
      <div class="row">
        <div class="form-group col-lg-12 commargin_top_20">
          <div class="vendor_button">
            <select>
              <option value="">Contact Type</option>
              <option value="1">Primary Person</option>
              <option value="2">secondary Person</option>
              <option value="3">others</option>
            </select>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <div class="form-group">
            <textarea id="description" class="form-control lbl_move" label="Enter Your Feedback"/>
            </textarea>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <div class="form-group">
            <input type="submit"  value="Submit" class="button cbfedbckbutn"/>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
<div class="content_wrapper padlr0">
  <div class="container-fluid padlr0">
    <div class="col-lg-12">
      <h1 class="float_l">Client Master</h1>
      <div id="addBtnWrapper" class="edit_del commargin_top float_r <?php echo (isset($clientReg) && count($clientReg) >= $NoOfClientCount) ? 'hide' : ''; ?>">
        <ul>
          <li><a title="Add Client" href="javascript: clientAdd()" class="edit_al"><i class="fa fa-plus"></i> Add Client</a></li>
        </ul>
      </div>
    </div>
    <div class="col-lg-12 clear">
      <div class="table-responsive clear">
        <div id="treeGrid"></div>
      </div>
    </div>
  </div>
</div>

<!--Delete Confirmation Modal-->
<div class="modal fade" id="DeleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h1>Why do you want to delete <span id="delClientName" class="bld-txt"></span>?</h1>
      </div>
      <div class="modal-body">
        <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">
          <form class="form-horizontal">
            <div class="row m_tb40">
              <div class="col-lg-12 form-group req_flds">
                <textarea id="remarks" maxlength="250" class="form-control lbl_move" label="Enter the remarks"/>
                </textarea>
              </div>
            </div>
          </form>
        </div>
      </div>
      <div class="modal-footer clear">
        <div class="col-lg-12 savebtn_area no_border">
          <ul>
            <li class="save_btn float_r"> <a href="javascript:void(0);" id="btnDeleteYes" class="ripple">Delete</a> </li>
            <li class="cancel_btn float_r"><a href="javascript:void(0);" aria-hidden="true" data-dismiss="modal" class="ripple">Cancel</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<!--Edit Confirmation Modal-->
<div class="modal fade" id="EditModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h1>Edit Client</h1>
      </div>
      <div class="modal-body">
        <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">
          <form class="form-horizontal" id="editForm">
            <div class="row">
              <div class="form-group padtop20 col-lg-12">
                <input type="hidden" name="clientId" id="clientId" class="form-control"/>
                <input type="hidden" name="csrf" value="<?php echo isset($csrf)?$csrf:''; ?>">
                <input type="text" id="clientName" name="clientName" class="form-control lbl_move" label="Name"/>
              </div>
            </div>
            <div class="row">
              <div class="form-group req_flds col-lg-12">
                <input type="text" id="address"  name="address" class="form-control lbl_move" label="Address" placeholder=""/>
              </div>
            </div>
            <div class="row">
              <div class="form-group req_flds col-lg-12">
                <input type="text" id="city" name="city" class="form-control lbl_move" label="City" data-name="locality"/>
                <input type="hidden" id="state" name="state" class="form-control" data-name="administrative_area_level_1"/>
                <input type="hidden" id="country" name="country" class="form-control" data-name="country"/>
              </div>
            </div>
            <div class="row">
              <div class="form-group req_flds col-lg-12">
                <input type="text" id="email" name="email" class="form-control lbl_move" label="Email" onchange="validateEmailInput(this)" />
              </div>
            </div>
          </form>
        </div>
      </div>
      <div class="modal-footer clear">
        <div class="col-lg-12 savebtn_area no_border">
          <ul>
            <li class="save_btn float_r"> <a href="javascript:void(0);" id="btnEditYes" class="ripple">Update</a> </li>
            <li class="cancel_btn float_r"><a href="javascript:void(0);" aria-hidden="true" data-dismiss="modal" class="ripple">Cancel</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="AddModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h1>Create Client</h1>
      </div>
      <div class="modal-body">
        <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">
          <form class="form-horizontal" id="addForm" autocomplete="off">
            <div class="row">
              <div class="form-group padtop20 col-lg-12">
                <input type="hidden" name="csrf" value="<?php echo isset($csrf)?$csrf:''; ?>">
                <input type="text" id="clientNamenew" name="clientNamenew" autocomplete="off" class="form-control lbl_move" label="Name"/>
              </div>
            </div>
            <div class="row">
              <div class="form-group req_flds col-lg-12">
                <input type="text" id="addressnew" name="addressnew" autocomplete="off" class="form-control lbl_move" label="Address" placeholder=""/>
              </div>
            </div>
            <div class="row">
              <div class="form-group req_flds col-lg-12">
                <input type="text" id="citynew" name="citynew" autocomplete="off" class="form-control lbl_move" label="City" data-name="locality"/>
                <input type="hidden" id="statenew" name="statenew" class="form-control" data-name="administrative_area_level_1"/>
                <input type="hidden" id="countrynew" name="countrynew" class="form-control" data-name="country"/>
              </div>
            </div>
            <div class="row">
              <div class="form-group req_flds col-lg-12">
                <input type="text" id="emailnew" name="emailnew" autocomplete="off" class="form-control lbl_move" label="Email" onchange="validateEmailInput(this)" />
              </div>
            </div>
          </form>
        </div>
      </div>
      <div class="modal-footer clear">
        <div class="col-lg-12 savebtn_area no_border">
          <ul>
            <li class="save_btn float_r"> <a href="javascript:void(0);" id="btnAddYes" class="ripple">Create</a> </li>
            <li class="cancel_btn float_r"><a href="javascript:void(0);" aria-hidden="true" data-dismiss="modal" class="ripple">Cancel</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
var feedbackTab = {
        speed:300,
        containerWidth:$('.feedback-panel').outerWidth(),
        containerHeight:$('.feedback-panel').outerHeight(),
        tabWidth:$('.feedback-tab').outerWidth(),
 
        init:function(){
            $('.feedback-panel').css('height',feedbackTab.containerHeight + 'px');
 
            $('a.feedback-tab').click(function(event){
 
                if ($('.feedback-panel').hasClass('open')) {
                    $('.feedback-panel').animate({left:'-' + feedbackTab.containerWidth}, feedbackTab.speed)
                    .removeClass('open');
                } else {
                    $('.feedback-panel').animate({left:'0'},  feedbackTab.speed)
                    .addClass('open');
                }
                event.preventDefault();
            });
        }
    };
 
    feedbackTab.init();
 
    $(".button").click(function() {  
        var response_message = "Thank you for your Feedback, see ya!";
		$('#form-wrap').html("<div id='response-message'></div>");
            $('#response-message').html("<p>" + response_message +"</p>")
            .hide()
            .fadeIn(500)
            .animate({opacity: 1.0}, 1000)
            .fadeIn(0, function(){
                $('.feedback-panel')
                .animate({left:'-' + (feedbackTab.containerWidth + feedbackTab.tabWidth)}, 
                (feedbackTab.speed))
                .removeClass('open');
            })
		return false;
    });
var NoOfClientCount = <?php echo (isset($NoOfClientCount)) ? $NoOfClientCount : '0'?>;
var arr_clients = <?php echo (isset($clientReg)) ? json_encode($clientReg) : ''?>,
	$treeGrid = $("#treeGrid"),
	$deleteModal = $('#DeleteModal'),
	$editModal = $('#EditModal'),
	$addModal = $('#AddModal'),
	$editForm = $('#editForm'),
	$remarks = $('#remarks'),
	$clientName = $('#clientName'),
	$address = $('#address'),
	$city = $('#city'),
	$email = $('#email'),
	$clientNamenew = $('#clientNamenew'),
	$addressnew = $('#addressnew'),
	$citynew = $('#citynew'),
	$emailnew = $('#emailnew');
	$(function () {
		var source = {
			localdata:arr_clients,
			dataType: "json",
			dataFields: [
				{ name: 'ClientId', type: 'number' },
				{ name: 'ClientName', type: 'string' },
				{ name: 'Address', type: 'string' },
				{ name: 'CityName', type: 'string' },
				{ name: 'Email', type: 'string' }
			],
			id: 'ClientId'
		};

	var dataAdapter = new $.jqx.dataAdapter(source);
	$treeGrid.jqxGrid({
		width: "100%",
		source: dataAdapter,
		sortable: true,
		pagerButtonsCount: 6,
		filterable:true,
		pageable:true,
		rowDetails: true,
		autoheight: true,
		selectionmode: 'singlerow',
		showfilterrow: true,
		editable: false,
		altrows: true,
		enabletooltips: true,
		columns: [
			{ text: 'ClientId', datafield: 'ClientId', hidden: true, filterable: false},
			{ text: 'Name', dataField: 'ClientName', width:'18%'},
			{ text: 'Address', dataField: 'Address', width:'30%'},
			{ text: 'City', dataField: 'CityName', width:'18%'},
			{ text: 'Email', dataField: 'Email', width:'20%'},
			{ text: 'Action', sortable: false, filterable: false, align: 'center', width:'14%',
				cellsrenderer: function (row) {
					var editLink = '<button class="marg-70s" style="background: transparent; text-align-center;" title="Edit" onclick="clientEdit('+row+')"><i class="fa fa-pencil-square-o reg-icon"></i></button>';
					return editLink + "&nbsp;&nbsp;" + '<button style="background: transparent;" title="Delete" onclick="clientDelete(this,'+row+')"><i class="fa fa-trash-o reg-icon"></i></button>';
				}
			}
		]
	});

	$('#btnDeleteYes').on('click', function () {
		var remarks = $remarks.val();
		if(remarks.length == 0) {
			showError($remarks, 'Required!');
			return;
		} else {
			removeError($remarks);
		}

		$deleteModal.modal('hide');
		var rowData = $treeGrid.jqxGrid('getrowdata', $deleteModal.data('row'));
		$.ajax({
			url: getBaseURL() + 'cb/master/deleteclient',
			type: 'POST',
			data: {"ClientId": rowData.ClientId, "Remarks": remarks, "Type": 'update'},
            async: false,
			success:function(data, textStatus, jqXHR){
				if (jqXHR.status == 200) {
                    $treeGrid.jqxGrid("deleterow", rowData.uid);

                    if ($treeGrid.jqxGrid('getdatainformation').rowscount < NoOfClientCount)  {
                        $('#addBtnWrapper').show();
                    } else {
                        $('#addBtnWrapper').hide();
                    }
                } else
					alert('Cannot delete this client, it is already in use!');
			},
			error:function(jqXHR, textStatus, errorThrown){
                alert('Failed to delete the Client!');
			}
		});
		$remarks.val('');	
	});

	$('#btnEditYes').on('click', function () {
		var clientName = $clientName.val();
		var address = $address.val();
		var city = $city.val();
		var email = $email.val();
		
		validate(function(isSuccess) {
			if (isSuccess === false) {
				// validation failed
				return false;
			} else {
			
				$editModal.modal('hide');
				var rowData = $treeGrid.jqxGrid('getrowdata', $editModal.data('row'));
				$.ajax({
					url: getBaseURL() + 'cb/master/editclient',
					type: 'POST',
					data: $editForm.serialize(),
					success:function(data, textStatus, jqXHR){
						if (jqXHR.status == 200){
							$treeGrid.jqxGrid("setcellvalue", $editModal.data('row'), 'ClientName', clientName);
							$treeGrid.jqxGrid("setcellvalue", $editModal.data('row'), 'Address', address);
							$treeGrid.jqxGrid("setcellvalue", $editModal.data('row'), 'CityName', city);
							$treeGrid.jqxGrid("setcellvalue", $editModal.data('row'), 'Email', email);
						} else {
							alert('Failed to Edit the Client!');
						}
					},
					error:function(jqXHR, textStatus, errorThrown){
                        alert('Failed to Edit the Client!');
					}
				});	
				$clientName.val('');
				$address.val('');
				$email.val('');
			}
		});
		
		
		function validate(callback) {
		
			if(clientName.length == 0) {
				showError($clientName, 'Required!');
				callback(false);
				return false;
			} else {
				removeError($clientName);
			}
			
			if(address.length == 0) {
				showError($address, 'Required!');
				callback(false);
				return false;
			} else {
				removeError($address);
			}
            
            if(city.length == 0) {
				showError($city, 'Required!');
				callback(false);
				return false;
			} else {
				removeError($city);
			}
			
            if($email.hasClass('error')) {
				callback(false);
				return false;
			}
            
			//validate clientname already found for addMode
			$.ajax({
				url:getBaseURL()+ 'cb/master/checkclientFound',
				type:"post",
				data: $('#editForm').serialize(),
				dataType:"json",
				success:function(data, textStatus, jqXHR){
					//alert(data)
					if(data.results != false){
						showError($clientName, 'Client Name already found!');
						callback(false);
						return false;
					}
					else{
						removeError($clientName);
						callback(true);
					}
				},
				error:function(jqXHR, textStatus, errorThrown){
					callback(false);
					return false;
				}
			});
		}
	});
    //bindJqxGridAutoResize();
});

$('#btnAddYes').on('click', function () {
	var clientNamenew = $clientNamenew.val();
	var addressnew = $addressnew.val();
	var citynew = $citynew.val();
	var emailnew = $emailnew.val();

	validate(function(isSuccess) {
		if (isSuccess === false) {
			// validation failed
			return false;
		} else {		
			$addModal.modal('hide');	
			$.ajax({
				url: getBaseURL() + 'cb/master/addclient',
				type: 'POST',
				data: $('#addForm').serialize(),
				success:function(data, textStatus, jqXHR){
					if (jqXHR.status == 200){
					    $treeGrid.jqxGrid('addrow',null,JSON.parse(data));
                        if(NoOfClientCount >= $treeGrid.jqxGrid('getdatainformation').rowscount) {
                            $('#addBtnWrapper').hide();
                        } else {
                            $('#addBtnWrapper').show();
                        }
					} else if (jqXHR.status == 201) {
                        alert('Sorry, you are allowed to add only ' + NoOfClientCount + ' clients in this plan!');
                    } else {
						alert('Failed to Add Client!');
					}
				},
				error:function(jqXHR, textStatus, errorThrown){
                    alert('Failed to Add Client!');
				}
			});	
			$clientNamenew.val('');
			$addressnew.val('');
			$emailnew.val('');
		}
	});
		
	function validate(callback) {
		if(clientNamenew.length == 0) {
			showError($clientNamenew, 'Required!');
			callback(false);
			return false;
		} else {
			removeError($clientNamenew);
		}
		
		if(addressnew.length == 0) {
			showError($addressnew, 'Required!');
			callback(false);
			return false;
		} else {
			removeError($addressnew);
		}
        
        if(citynew.length == 0) {
            showError($citynew, 'Required!');
            callback(false);
            return false;
        } else {
            removeError($citynew);
        }

		if($emailnew.hasClass('error')) {
			callback(false);
			return false;
		}
		//validate clientname already found for addMode
		$.ajax({
			url:getBaseURL()+ 'cb/master/checkclientFound',
			type:"post",
			data: $('#addForm').serialize(),
			dataType:"json",
			success:function(data, textStatus, jqXHR){
				//alert(data)
				if(data.results != false){
					showError($clientNamenew, 'Client Name already found!');
					callback(false);
					return false;
				} else{
					removeError($clientNamenew);
					callback(true);
				}
			},
			error:function(jqXHR, textStatus, errorThrown){
				callback(false);
				return false;
			}
		});
	}
});

function clientDelete(x,row) {
    $(x).prop('disabled', true);
    var rowData = $treeGrid.jqxGrid('getrowdata', row);
    $.ajax({
        url: getBaseURL() + 'cb/master/deleteclient',
        type: 'POST',
        data: {"ClientId": rowData.ClientId, "Type": 'check'},
        async: false,
        success:function(data, textStatus, jqXHR){
            $(x).prop('disabled', false);
            if (jqXHR.status == 200) {
                $deleteModal.data('row', row).modal('show');
                $('#delClientName').html(rowData.ClientName);
                $("#remarks").val('');
            }else
                alert('Cannot delete this client, it is already in use!');
        },
        error:function(jqXHR, textStatus, errorThrown){
            $(x).prop('disabled', false);
            alert('Cannot delete the Client!');
        }
    });
}

function clientEdit(row) {
	var rowData = $treeGrid.jqxGrid('getrowdata', row);
	$editModal.data('row', row).modal('show');
	$clientName.val(rowData.ClientName);
	$clientName.trigger('change');
	$address.val(rowData.Address);
	$address.trigger('change');
	$city.val(rowData.CityName);
	$city.trigger('change');
	$email.val(rowData.Email);
	$email.trigger('change');
	$('#clientId').val(rowData.ClientId);
}

function clientAdd() {
	$addModal.modal('show');
	$('#addForm').trigger('reset');
}
</script> 
<script src="http://maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places&amp;key=AIzaSyDaNPyxJ7NKmZ4rC8awB-BlBh6ieH1Q9os"></script>
<script>
/*Mapping Address*/
navigator.geolocation.getCurrentPosition(showPosition);
$addressnew.geocomplete({
	details: "#addForm",
	types: ["geocode", "establishment"]
});

$address.geocomplete({
	details: "#EditModal",
	types: ["geocode", "establishment"]
});

function showPosition(position) {
	var coordinates = position.coords.latitude + "," + position.coords.longitude; 
	$addressnew.val(coordinates);
	$addressnew.trigger("geocode");
}
</script> 
