<!--<style>
	.upload-pf {border: 1px solid #ddd;box-shadow: 0 0 0 2px #ffffff, 0 0 0 3px #7b7eba;float: left;height: 113px;margin: -4px 10px 0 -9px;overflow: hidden;position: relative;width: 91%;}
    .upload-pf img {width: 100% !important;height: 118px !important;background:#fff; }
    .upload-pf .ovrly {position: absolute;background: rgba(0, 0, 0, 0.5);height: 100%;right: 100%;top: 0;width: 100%;     -webkit-transition: all 0.5s;-moz-transition: all 0.5s; -o-transition: all 0.5s;transition: all 0.5s;}
    .upload-pf .buttons {position: absolute;top: 50%;right: -100%;-webkit-transition: all 0.5s;-moz-transition: all 0.5s;
        -o-transition: all 0.5s;transition: all 0.5s;-webkit-transform: translate(50%, -50%);-moz-transform: translate(50%, -50%);-ms-transform: translate(50%, -50%);-o-transform: translate(50%, -50%);transform: translate(50%, -50%);}
    .upload-pf .buttons .fa {margin: 0 1px;background: rgba(256, 256, 256, 0.9);-webkit-box-shadow: 0 0 1px rgba(0, 0, 0, 0.3);-moz-box-shadow: 0 0 1px rgba(0, 0, 0, 0.3);box-shadow: 0 0 1px rgba(0, 0, 0, 0.3);-webkit-border-radius: 50%;  -moz-border-radius: 50%;border-radius: 50%;color: rgba(50, 50, 50, 0.9);display: inline-block;line-height: 40px;     font-size: 16px;text-align: center;text-decoration: none;width: 40px;cursor:pointer;height: 40px;}
    .upload-pf:hover .buttons {right: 50%;}
    .upload-pf:hover .ovrly {right: 0;}
    .proname_btn a{ color: #112c45; font-weight:600}
    .subs a:hover{color:#333 !important;}

    .subDiv                         {margin-left:10px; margin-top:10px;}
    .abt-iowt2 thead tr th          {background:#CAE1F9!important;font-size:11px; margin-top:20px;}
    .fntst                          {font-size:14px;font-family:'Open Sans', sans-serif !important;display:block !important;padding-left:12px !important;}
    .thscss 					    {font-family:'Open Sans', sans-serif !important;background-color:#E2EBEF !important;border-bottom:1px solid #5D9BB6 !important;	padding:8px !important;font-size:11px;}
    .tdpds 						    {border-top: 1px solid #EFEFEF!important;line-height:1.42857!important;padding:8px!important;vertical-align:top!important;font-family:'Open Sans', sans-serif !important;font-size:12px;}
    .bill-det 					    {font-size:14px;font-family:'Open Sans', sans-serif !important;display:block;padding-left:5px !important;}
    .date-bills					    { }
    .str-bill 					    {display:block !important;width:10px;padding-left:10px;}
    .date-shw 					    {font-size:14px;font-family:'Open Sans', sans-serif !important;display:block !important;padding-left:12px !important;}
    p							    {color:#000;font-size:14px;text-align:left;padding-top:-8px; line-height:24px !important;font-family:'Open Sans', sans-serif !important;}
    .su-t 						    {margin-left:13px !important}
    .sel-wets 					    {border:thin solid #c2c2c2 !important;margin-bottom:10px !important;width:95% !important;border-radius:0px !important;}
    .sel-wets select option 	    {padding-left:10px !important;padding-top:3px;padding-bottom:3px;}
    .sel-wets select option.thin    {outline-width:thin !important;}
    .sel-wets select option.thick   {outline-width:thick !important;}
    .sel-wets select option.thicker {outline-width:thicker !important;}
    .abst-curt                      {margin-left:13px;}
    .bill-cum                       {margin-left:10px;}
    .abt-iow                        {margin-left:10px;}
    .abt-all                        {margin-left:10px;}
    /*
    .thscss 					    {font-family:'Open Sans', sans-serif !important;background-color:#E2EBEF !important;border-bottom:1px solid #5D9BB6 !important;	padding:8px !important;font-size:11px;}
    .tdpds 						    {border-top: 1px solid #EFEFEF!important;line-height:1.42857!important;padding:8px!important;vertical-align:top!important;font-family:'Open Sans', sans-serif !important;font-size:12px;}
    .bill-det 					    {font-size:14px;font-family:'Open Sans', sans-serif !important;display:block;padding-left:5px !important;}
    .date-bills					    {font-family:'Open Sans', sans-serif !important;display:inline;clear:both; color:#000; }
    .str-bill 					    {display:block !important;width:10px;padding-left:10px;}
    .date-shw 					    {font-size:14px;font-family:'Open Sans', sans-serif !important;display:block !important;padding-left:12px !important;}
    p							    {color:#000;font-size:14px;text-align:left;padding-top:-8px;font-family:'Open Sans', sans-serif !important;}
    .su-t 						    {margin-left:13px !important}
    .sel-wets 					    {border:thin solid #c2c2c2 !important;margin-bottom:10px !important;width:95% !important;border-radius:0px !important;}
    .sel-wets select option 	    {padding-left:10px !important;padding-top:3px;padding-bottom:3px;}
    .sel-wets select option.thin    {outline-width:thin !important;}
    .sel-wets select option.thick   {outline-width:thick !important;}
    .sel-wets select option.thicker {outline-width:thicker !important;}
    .abst-curt                      {margin-left:13px;}
    .bill-cum                       {margin-left:10px;}
    .abt-iow                        {margin-left:10px;}
    .abt-all                        {margin-left:10px;}
    .abt-all3                       {margin-left:10px;}
    .subDiv                         {margin-left:10px; margin-top:10px;}
    .abt-iowt2 thead tr th          {background:#CAE1F9!important;font-size:11px; margin-top:20px;}
    .fntst                          {font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;}
    .drsElement                     {padding-left:5px;padding-right:5px;padding-top:8px;}

    .sel-wets select option.dotteds  {border-style:dotted;}
    .sel-wets select option.dasheds  {border-style:dashed;}
    .sel-wets select option.solids   {border-style:solid;}
    .sel-wets select option.doubles  {border-style:double;}
    .sel-wets select option.hiddens  {border-style:hidden;}	*/
</style>
<!---sample rabill report--->
<!--<div id="p_scents" style="height: 441px; position: relative; margin-top: 10px;"> 
	
	<div class="drsElement drsMoveHandle drsItem" data-name="Logo" style="left: 18px; top: 11px; width: 136px; height: 84px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border: 0px solid rgb(0, 0, 0); z-index: 2;">
		<div class="col-md-4 col-sm-5" id="browse_1" style="padding:0px !important; width:130px;" onclick="Imagebrowse(this);">
			<div class="upload-pf"> <img id="showpic_1" onerror="this.src='<?php echo $this->basePath(); ?>/images/nolgo.jpg';"> <img id="req_LogoPath" src="http://localhost/bsf_v1.1/public/images/nolgo.jpg" style="display:block;width:258px;height:280px">
				<input name="imageurl_1" id="imageurl_1" value="" type="hidden">
				<div class="ovrly"></div>
				<div class="buttons">
					<a href="#" class="fa fa-link"></a>
				</div>
			</div>
		</div>
		<input id="myfile_1" name="myfile_1" class="imageupload" accept="image/*" style="display: none;" type="file">
		<button style="font-size: 17px; display: none;" type="button" class="remScnt">
			<i style="font-size: 17px;" class="fa fa-trash-o"></i>
		</button>
	</div>
    <div class="drsElement drsMoveHandle drsItem" data-name="Header Info" style="left: 209px; top: 51px; width: 292px; height: 53px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 1px; border-style: hidden; border-color: rgb(0, 0, 0); z-index: 2; font-size: 24px;">
        <p style="display: inline; clear: both; font-family: &quot;Open Sans&quot;,sans-serif ! important; padding-left: 5px; font-weight: normal; font-size: 24px;" contenteditable="true">Purchase Order Details</p>
        <button style="font-size: 24px; display: none;" type="button" class="remScnt">
            <i style="font-size: 24px;" class="fa fa-trash-o"></i>
        </button>
	</div>
    <div class="drsElement drsMoveHandle drsItem" data-name="HireOrder Details" style="left: 12px; top: 130px; width: 680px; height: 264px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border: 1px solid rgb(0, 0, 0); z-index: 2;">
        <div class="drsElement drsMoveHandle drsGroupItem" data-name="PO Date" style="left: 360px; top: 20px; width: 300px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 1px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 2;">
            <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;" contenteditable="true">CostCentre Name :</p>
            <span id="req_CostCentreName" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
            <button style="display: none;" type="button" class="remScnt">
                <i class="fa fa-trash-o"></i>
            </button>
        
		</div>
        <div class="drsElement drsMoveHandle drsGroupItem" data-name="CostCentre Name" style="left: 10px; top: 20px; width: 300px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border: 1px solid rgb(0, 0, 0); z-index: 2;">
            <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;" contenteditable="true">PO Date :</p>
            <span id="req_PoDate" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
            <button style="display: none;" type="button" class="remScnt">
                <i class="fa fa-trash-o"></i>
            </button>
		</div>
        <div class="drsElement drsMoveHandle drsGroupItem" data-name="HO Type" style="left: 360px; top: 65px; width: 300px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 1px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 2;">
            <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;" contenteditable="true">Vendor Name :</p>
            <span id="req_VendorName" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
            <button style="display: none;" type="button" class="remScnt">
                <i class="fa fa-trash-o"></i>
            </button>
		</div>
        <div class="drsElement drsMoveHandle drsGroupItem" data-name="HOCC No" style="left: 10px; top: 65px; width: 300px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border: 1px solid rgb(0, 0, 0); z-index: 2;">
            <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;" contenteditable="true">PO No :</p>
            <span id="req_PoNo" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
            <button style="display: none;" type="button" class="remScnt">
                <i class="fa fa-trash-o"></i>
            </button>
		</div>
        <div class="drsElement drsMoveHandle drsGroupItem" data-name="Distributor Name" style="left: 360px; top: 151px; width: 303px; height: 77px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border: 1px solid rgb(0, 0, 0); z-index: 2;">
            <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">Distributor Name :</p>
            <span id="req_distName" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
            <button style="display: none;" type="button" class="remScnt">
                <i class="fa fa-trash-o"></i>
            </button>
        </div>
        <div class="drsElement drsMoveHandle drsGroupItem" data-name="Req No" style="left: 361px; top: 110px; width: 300px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 1px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 2;">
            <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">Req No:</p>
            <span id="req_reqno" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
            <button style="display: none;" type="button" class="remScnt">
                <i class="fa fa-trash-o"></i>
            </button>
        </div>
        <div class="drsElement drsMoveHandle drsGroupItem" data-name="ccpono" style="left: 9px; top: 110px; width: 302px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 1px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 2;">
            <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">CCPO No:</p>
            <span id="req_ccpono" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
            <button style="display: none;" type="button" class="remScnt">
                <i class="fa fa-trash-o"></i>
            </button>
        </div>
        <div class="drsElement drsMoveHandle drsGroupItem" data-name="cpono" style="left: 9px; top: 152px; width: 302px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 1px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 2;">
            <p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">CPO No:</p>
            <span id="req_cpono" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
            <button style="display: none;" type="button" class="remScnt">
                <i class="fa fa-trash-o"></i>
            </button>
        </div>
        <button style="display: none;" type="button" class="remScnt">
            <i class="fa fa-trash-o"></i>
        </button>
	</div>
	
</div>
<script>
    function Imagebrowse(id) {
        var id = $(id)[0].id;
		
        var arr = id.split('_')[1];
		$("#myfile_1").click();
        $('#myfile_1').change(function() {
            readURL(this,arr);
        });
    }
	function readURL(input, value) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            //var id = value;
            reader.onload = function(e) {
                $("#showpic_1").hide();
                $("#req_LogoPath").show();
                $('#req_LogoPath').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>
<!--table--> 

<style>
.upload-pf {border: 1px solid #ddd;box-shadow: 0 0 0 2px #ffffff, 0 0 0 3px #7b7eba;float: left;height: 113px;margin: -4px 10px 0 -9px;overflow: hidden;position: relative;width: 91%;}
    .upload-pf img {width: 100% !important;height: 118px !important;background:#fff; }
    .upload-pf .ovrly {position: absolute;background: rgba(0, 0, 0, 0.5);height: 100%;right: 100%;top: 0;width: 100%;     -webkit-transition: all 0.5s;-moz-transition: all 0.5s; -o-transition: all 0.5s;transition: all 0.5s;}
    .upload-pf .buttons {position: absolute;top: 50%;right: -100%;-webkit-transition: all 0.5s;-moz-transition: all 0.5s;
        -o-transition: all 0.5s;transition: all 0.5s;-webkit-transform: translate(50%, -50%);-moz-transform: translate(50%, -50%);-ms-transform: translate(50%, -50%);-o-transform: translate(50%, -50%);transform: translate(50%, -50%);}
    .upload-pf .buttons .fa {margin: 0 1px;background: rgba(256, 256, 256, 0.9);-webkit-box-shadow: 0 0 1px rgba(0, 0, 0, 0.3);-moz-box-shadow: 0 0 1px rgba(0, 0, 0, 0.3);box-shadow: 0 0 1px rgba(0, 0, 0, 0.3);-webkit-border-radius: 50%;  -moz-border-radius: 50%;border-radius: 50%;color: rgba(50, 50, 50, 0.9);display: inline-block;line-height: 40px;     font-size: 16px;text-align: center;text-decoration: none;width: 40px;cursor:pointer;height: 40px;}
    .upload-pf:hover .buttons {right: 50%;}
    .upload-pf:hover .ovrly {right: 0;}
    .proname_btn a{ color: #112c45; font-weight:600}
    .subs a:hover{color:#333 !important;}



.subDiv                         {margin-left:10px; margin-top:10px;}
.abt-iowt2 thead tr th          {background:#CAE1F9!important;font-size:11px; margin-top:20px;}
.fntst                          {font-size:14px;font-family:'Open Sans', sans-serif !important;display:block !important;padding-left:12px !important;}
.thscss 					    {font-family:'Open Sans', sans-serif !important;background-color:#E2EBEF !important;border-bottom:1px solid #5D9BB6 !important;	padding:8px !important;font-size:11px;}
.tdpds 						    {border-top: 1px solid #EFEFEF!important;line-height:1.42857!important;padding:8px!important;vertical-align:top!important;font-family:'Open Sans', sans-serif !important;font-size:12px;}
.bill-det 					    {font-size:14px;font-family:'Open Sans', sans-serif !important;display:block;padding-left:5px !important;}
.date-bills					    { }
.str-bill 					    {display:block !important;width:10px;padding-left:10px;}
.date-shw 					    {font-size:14px;font-family:'Open Sans', sans-serif !important;display:block !important;padding-left:12px !important;}
p							    {color:#000;font-size:14px;text-align:left;padding-top:-8px; line-height:24px !important;font-family:'Open Sans', sans-serif !important;}
.su-t 						    {margin-left:13px !important}
.sel-wets 					    {border:thin solid #c2c2c2 !important;margin-bottom:10px !important;width:95% !important;border-radius:0px !important;}
.sel-wets select option 	    {padding-left:10px !important;padding-top:3px;padding-bottom:3px;}
.sel-wets select option.thin    {outline-width:thin !important;}
.sel-wets select option.thick   {outline-width:thick !important;}
.sel-wets select option.thicker {outline-width:thicker !important;}
.abst-curt                      {margin-left:13px;}
.bill-cum                       {margin-left:10px;}
.abt-iow                        {margin-left:10px;}
.abt-all                        {margin-left:10px;}
/*
.thscss 					    {font-family:'Open Sans', sans-serif !important;background-color:#E2EBEF !important;border-bottom:1px solid #5D9BB6 !important;	padding:8px !important;font-size:11px;}
.tdpds 						    {border-top: 1px solid #EFEFEF!important;line-height:1.42857!important;padding:8px!important;vertical-align:top!important;font-family:'Open Sans', sans-serif !important;font-size:12px;}
.bill-det 					    {font-size:14px;font-family:'Open Sans', sans-serif !important;display:block;padding-left:5px !important;}
.date-bills					    {font-family:'Open Sans', sans-serif !important;display:inline;clear:both; color:#000; }
.str-bill 					    {display:block !important;width:10px;padding-left:10px;}
.date-shw 					    {font-size:14px;font-family:'Open Sans', sans-serif !important;display:block !important;padding-left:12px !important;}
p							    {color:#000;font-size:14px;text-align:left;padding-top:-8px;font-family:'Open Sans', sans-serif !important;}
.su-t 						    {margin-left:13px !important}
.sel-wets 					    {border:thin solid #c2c2c2 !important;margin-bottom:10px !important;width:95% !important;border-radius:0px !important;}
.sel-wets select option 	    {padding-left:10px !important;padding-top:3px;padding-bottom:3px;}
.sel-wets select option.thin    {outline-width:thin !important;}
.sel-wets select option.thick   {outline-width:thick !important;}
.sel-wets select option.thicker {outline-width:thicker !important;}
.abst-curt                      {margin-left:13px;}
.bill-cum                       {margin-left:10px;}
.abt-iow                        {margin-left:10px;}
.abt-all                        {margin-left:10px;}
.abt-all3                       {margin-left:10px;}
.subDiv                         {margin-left:10px; margin-top:10px;}
.abt-iowt2 thead tr th          {background:#CAE1F9!important;font-size:11px; margin-top:20px;}
.fntst                          {font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;}
.drsElement                     {padding-left:5px;padding-right:5px;padding-top:8px;}

.sel-wets select option.dotteds  {border-style:dotted;}	
.sel-wets select option.dasheds  {border-style:dashed;}	
.sel-wets select option.solids   {border-style:solid;}	
.sel-wets select option.doubles  {border-style:double;}	
.sel-wets select option.hiddens  {border-style:hidden;}	*/
</style>
<!---sample rabill report--->
<div id="p_scents" style="height: 630px; width:738px; position: relative; margin-top: 10px;">
	<div class="drsElement drsMoveHandle drsItem" data-name="Register Details" style="left: 8px; top: 8px; width: 721px; height: 123px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border: 1px solid rgb(0, 0, 0); z-index: 2;">
		<div class="drsElement drsMoveHandle drsItem" data-name="Logo" style="left: 8px; top: 8px; width: 136px; height: 84px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border: 0px solid rgb(0, 0, 0); z-index: 2;">
			<div class="col-md-4 col-sm-5" id="browse_1" style="padding:0px !important; width:130px;" onclick="Imagebrowse(this);">
				<div class="upload-pf"> <img id="showpic_1" onerror="this.src='<?php echo $this->basePath(); ?>/images/nolgo.jpg';"> <img id="req_LogoPath" src="http://localhost/bsf_v1.1/public/images/nolgo.jpg" style="display:block;width:258px;height:280px">
					<input name="imageurl_1" id="imageurl_1" value="" type="hidden">
					<div class="ovrly"></div>
					<div class="buttons">
						<a href="#" class="fa fa-link"></a>
					</div>
				</div>
			</div>
			<input id="myfile_1" name="myfile_1" class="imageupload" accept="image/*" style="display: none;" type="file">
			<button style="font-size: 17px; display: none;" type="button" class="remScnt">
				<i style="font-size: 17px;" class="fa fa-trash-o"></i>
			</button>
		</div>
		<div class="drsElement drsMoveHandle drsItem text-bold" data-name="PURCHASE ORDER" style="left: 231px; top: 91px; width: 237px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 1px; border-style: hidden; border-color: rgb(0, 0, 0); z-index: 2; font-size: 17px;">
			<p style="display: inline; clear: both; font-family: &quot;Open Sans&quot;,sans-serif ! important; padding-left: 55px; font-weight: normal; font-size: 17px;" contenteditable="true">PURCHASE ORDER<br></p>
			<button style="font-size: 17px; display: none;" type="button" class="remScnt">
				<i style="font-size: 17px;" class="fa fa-trash-o"></i>
			</button>
		</div>
		<button style="font-size: 17px; display: none;" type="button" class="remScnt">
			<i style="font-size: 17px;" class="fa fa-trash-o"></i>
		</button>
	</div>
	<div class="drsElement drsMoveHandle drsGroupItem" data-name="Company Name" style="left: 157px; top: 18px; width: 561px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 0px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 2;">
		<p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">Company Name :</p>
		<span id="req_CompanyName" style="font-family:'Open Sans', sans-serif !important; padding-left:180px !important; color:#000;font-size:14px; font-weight:normal;"></span>
		<button style="display: none;" type="button" class="remScnt">
			<i class="fa fa-trash-o"></i>
		</button>
	</div>
	<div class="drsElement drsMoveHandle drsGroupItem" data-name="Company Address" style="left: 157px; top: 52px; width: 561px; height: 53px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 0px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 2;">
		<p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">Company Address :</p>
		<span id="req_companyAddress" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:14px; font-weight:normal;"></span>
		<button style="display: none;" type="button" class="remScnt">
			<i class="fa fa-trash-o"></i>
		</button>
	</div>
	<div class="drsElement drsMoveHandle drsItem" data-name="INVOICE TO" style="left: 8px; top: 152px; width: 371px; height: 220px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border: 1px solid rgb(0, 0, 0); z-index: 2;">
		<div class="drsElement drsMoveHandle drsGroupItem style-center text-bold" data-name="Workorderno field" style="left: 8px; top: 8px; width: 358px; height: 30px; background-color: rgb(190, 190, 190); color: rgb(0, 0, 0); border: 1px solid rgb(0, 0, 0); z-index: 2;">
			<p style="display: inline; clear: both; font-family: &quot;Open Sans&quot;,sans-serif ! important; padding-left: 5px; font-weight: normal; background-color: rgb(190, 190, 190);" contenteditable="true">INVOICE TO<br style="background-color: rgb(190, 190, 190);"></p>
			<button style="background-color: rgb(190, 190, 190); display: none;" type="button" class="remScnt">
				<i style="background-color: rgb(190, 190, 190);" class="fa fa-trash-o"></i>
			</button>
		</div>
		
		<div class="drsElement drsMoveHandle drsGroupItem" data-name="CostCentre Name" style="left: 10px; top: 49px; width: 297px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 0px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 3; font-size: 11px;">
			<p style="display: inline; clear: both; font-family: &quot;Open Sans&quot;,sans-serif ! important; padding-left: 5px; font-weight: normal; font-size: 11px;" contenteditable="true">CostCentre Name :</p>
			<span id="req_CostCentreName" style="font-family: &quot;Open Sans&quot;,sans-serif ! important; padding-left: 10px ! important; color: rgb(0, 0, 0); font-size: 11px; font-weight: normal;"></span>
			<button style="font-size: 11px; display: none;" type="button" class="remScnt">
				<i style="font-size: 11px;" class="fa fa-trash-o"></i>
			</button>
		</div>
		
		<div class="drsElement drsMoveHandle drsGroupItem" data-name="CostCentre Address" style="left: 9px; top: 78px; width: 350px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 0px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 2; font-size: 11px;">
			<p style="display: inline; clear: both; font-family: &quot;Open Sans&quot;,sans-serif ! important; padding-left: 5px; font-weight: normal; font-size: 11px;" contenteditable="true">CostCentre Address :</p>
			<span id="req_costcentreAddress" style="font-family: &quot;Open Sans&quot;,sans-serif ! important; padding-left: 10px ! important; color: rgb(0, 0, 0); font-size: 11px; font-weight: normal;"></span>
			<button style="font-size: 11px; display: none;" type="button" class="remScnt">
				<i style="font-size: 11px;" class="fa fa-trash-o"></i>
			</button>
		</div>
		
		<div class="drsElement drsMoveHandle drsGroupItem" data-name="PAN No" style="left: 9px; top: 116px; width: 297px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 0px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 2; font-size: 11px;">
			<p style="display: inline; clear: both; font-family: &quot;Open Sans&quot;,sans-serif ! important; padding-left: 5px; font-weight: normal; font-size: 11px;" contenteditable="true">PAN No :</p>
			<span id="req_PANNo" style="font-family: &quot;Open Sans&quot;,sans-serif ! important; padding-left: 10px ! important; color: rgb(0, 0, 0); font-size: 11px; font-weight: normal;"></span>
			<button style="font-size: 11px; display: none;" type="button" class="remScnt">
				<i style="font-size: 11px;" class="fa fa-trash-o"></i>
			</button>
		</div>

		<div class="drsElement drsMoveHandle drsGroupItem" data-name="TAN No" style="left: 9px; top: 145px; width: 297px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 0px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 2; font-size: 11px;">
			<p style="display: inline; clear: both; font-family: &quot;Open Sans&quot;,sans-serif ! important; padding-left: 5px; font-weight: normal; font-size: 11px;" contenteditable="true">TAN No :</p>
			<span id="req_TANNo" style="font-family: &quot;Open Sans&quot;,sans-serif ! important; padding-left: 10px ! important; color: rgb(0, 0, 0); font-size: 11px; font-weight: normal;"></span>
			<button style="font-size: 11px; display: none;" type="button" class="remScnt">
				<i style="font-size: 11px;" class="fa fa-trash-o"></i>
			</button>
		</div>
		
		<div class="drsElement drsMoveHandle drsGroupItem" data-name="TIN No" style="left: 9px; top: 174px; width: 297px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 0px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 2; font-size: 11px;">
			<p style="display: inline; clear: both; font-family: &quot;Open Sans&quot;,sans-serif ! important; padding-left: 5px; font-weight: normal; font-size: 11px;" contenteditable="true">	TIN No :</p>
			<span id="req_TINNo" style="font-family: &quot;Open Sans&quot;,sans-serif ! important; padding-left: 10px ! important; color: rgb(0, 0, 0); font-size: 11px; font-weight: normal;"></span>
			<button style="font-size: 11px; display: none;" type="button" class="remScnt">
				<i style="font-size: 11px;" class="fa fa-trash-o"></i>
			</button>
		</div>

		<button style="display: none;" type="button" class="remScnt">
			<i class="fa fa-trash-o"></i>
		</button>
	</div>
  
	<div class="drsElement drsMoveHandle drsItem" data-name="SUPPLIER" style="left: 8px; top: 380px; width: 371px; height: 220px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 1px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 2;">
		<div class="drsElement drsMoveHandle drsGroupItem style-center text-bold" data-name="Projectname field" style="left: 8px; top: 8px; width: 358px; height: 30px; background-color: rgb(190, 190, 190); color: rgb(0, 0, 0); border-width: 1px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 2;">
			<p style="display: inline; clear: both; font-family: &quot;Open Sans&quot;,sans-serif ! important; padding-left: 5px; font-weight: normal; background-color: rgb(190, 190, 190);" contenteditable="true">SUPPLIER<br style="background-color: rgb(190, 190, 190);"></p>
			<button style="display: none; background-color: rgb(190, 190, 190);" type="button" class="remScnt">
				<i style="background-color: rgb(190, 190, 190);" class="fa fa-trash-o"></i>
			</button>
		</div>
		
		<div class="drsElement drsMoveHandle drsGroupItem" data-name="Vendor Name" style="left: 8px; top: 60px; width: 260px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 1px; border-style: hidden; border-color: rgb(0, 0, 0); z-index: 2;font-size: 11px; ">
			<p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal; font-size: 11px;">Vendor Name :</p>
			<span id="req_VendorName" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:11px; font-weight:normal;"></span>
			<button style="display: none;" type="button" class="remScnt">
				<i class="fa fa-trash-o"></i>
			</button>
		</div>
		
		<div class="drsElement drsMoveHandle drsGroupItem" data-name="Vendor Address" style="left: 8px; top: 98px; width: 300px; height: 53px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 0px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 2; font-size: 11px;">
			<p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal; font-size: 11px;">Vendor Address :</p>
			<span id="req_vendorAddress" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:11px; font-weight:normal;"></span>
			<button style="display: none;" type="button" class="remScnt">
				<i class="fa fa-trash-o"></i>
			</button>
		</div>
		
		<div class="drsElement drsMoveHandle drsGroupItem" data-name="Contact No" style="left: 8px; top: 143px; width: 300px; height: 53px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 0px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 2; font-size: 11px;">
			<p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal; font-size: 11px;">Contact No :</p>
			<span id="req_PhoneNumber" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:11px; font-weight:normal;"></span>
			<button style="display: none;" type="button" class="remScnt">
				<i class="fa fa-trash-o"></i>
			</button>
		</div>
		
		<button style="display: none;" type="button" class="remScnt">
			<i class="fa fa-trash-o"></i>
		</button>
	</div>
  
	<div class="drsElement drsMoveHandle drsItem" data-name="ORDER DETAILS" style="left: 384px; top: 152px; width: 345px; height: 220px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 1px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 2;">
		<div class="drsElement drsMoveHandle drsGroupItem text-bold style-center" data-name="BillNo field" style="left: 8px; top: 8px; width: 328px; height: 30px; background-color: rgb(190, 190, 190); color: rgb(0, 0, 0); border-width: 1px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 2;">
			<p style="display: inline; clear: both; font-family: &quot;Open Sans&quot;,sans-serif ! important; padding-left: 5px; font-weight: normal; background-color: rgb(190, 190, 190);" contenteditable="true"> ORDER DETAILS<br style="background-color: rgb(190, 190, 190);"></p>
			<button style="background-color: rgb(190, 190, 190); display: none;" type="button" class="remScnt">
				<i style="background-color: rgb(190, 190, 190);" class="fa fa-trash-o"></i>
			</button>
		</div>
		
		<div class="drsElement drsMoveHandle drsGroupItem" data-name="PO Date" style="left: 25px; top: 55px; width: 231px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 1px; border-style: hidden; border-color: rgb(0, 0, 0); z-index: 3; font-size:11px;">
			<p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal; font-size:11px;" contenteditable="true">PO Date :</p>
			<span id="req_PoDate" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:11px; font-weight:normal;"></span>
			<button style="display: none;" type="button" class="remScnt">
				<i class="fa fa-trash-o" style="!important"></i>
			</button>
		</div>
		
		<div class="drsElement drsMoveHandle drsGroupItem" data-name="PO NO" style="left: 25px; top: 91px; width: 231px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 1px; border-style: hidden; border-color: rgb(0, 0, 0); z-index: 2; font-size:11px;">
			<p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal; font-size:11px;" contenteditable="true">PO NO:</p>
			<span id="req_PoNo" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:11px; font-weight:normal;"></span>
			<button style="display: none;" type="button" class="remScnt">
				<i class="fa fa-trash-o"></i>
			</button>
		</div>
		
		<div class="drsElement drsMoveHandle drsGroupItem" data-name="CPO NO" style="left: 25px; top: 129px; width: 231px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 1px; border-style: hidden; border-color: rgb(0, 0, 0); z-index: 2; font-size:11px;">
			<p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal; font-size:11px;" contenteditable="true">CPO NO:</p>
			<span id="req_cpono" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:11px; font-weight:normal;"></span>
			<button style="display: none;" type="button" class="remScnt">
				<i class="fa fa-trash-o"></i>
			</button>
		</div>
    
		<div class="drsElement drsMoveHandle drsGroupItem" data-name="CCPO NO" style="left: 26px; top: 170px; width: 233px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border: 1px hidden rgb(0, 0, 0); z-index: 2; font-size:11px;">
			<p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal; font-size:11px;" contenteditable="true">CCPO NO :</p>
			<span id="req_ccpono" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:11px; font-weight:normal;"></span>
			<button style="display: none;" type="button" class="remScnt">
				<i class="fa fa-trash-o"></i>
			</button>
		</div>

		<button style="display: none;" type="button" class="remScnt">
		<i class="fa fa-trash-o"></i>
		</button>
	</div>
	<div class="drsElement drsMoveHandle drsItem" data-name="DELIVERY ADDRESS" style="left: 384px; top: 382px; width: 345px; height: 218px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 1px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 2;">
		<div class="drsElement drsMoveHandle drsGroupItem style-center text-bold" data-name="Companyaddress field" style="left: 8px; top: 8px; width: 328px; height: 30px; background-color: rgb(190, 190, 190); color: rgb(0, 0, 0); border-width: 1px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 2;">
			<p style="display: inline; clear: both; font-family: &quot;Open Sans&quot;,sans-serif ! important; padding-left: 5px; font-weight: normal; background-color: rgb(190, 190, 190);" contenteditable="true">&nbsp; DELIVERY ADDRESS :</p>
			<span id="bill_Address" style="font-family: &quot;Open Sans&quot;,sans-serif ! important; padding-left: 10px ! important; color: rgb(0, 0, 0); font-size: 14px; font-weight: normal; background-color: rgb(190, 190, 190);"></span>
			<button style="display: block; background-color: rgb(190, 190, 190);" type="button" class="remScnt">
				<i style="background-color: rgb(190, 190, 190);" class="fa fa-trash-o"></i>
			</button>
		</div>
		
		<div class="drsElement drsMoveHandle drsGroupItem" data-name="Name" style="left: 8px; top: 60px; width: 260px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 1px; border-style: hidden; border-color: rgb(0, 0, 0); z-index: 2; font-size: 11px;">
			<p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">Name :</p>
			<span id="req_Name" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:11px; font-weight:normal;"></span>
			<button style="display: none;" type="button" class="remScnt">
				<i class="fa fa-trash-o"></i>
			</button>
		</div>
		
		<div class="drsElement drsMoveHandle drsGroupItem" data-name="Delivery Address" style="left: 8px; top: 111px; width: 275px; height: 53px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 0px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 2; font-size: 11px;">
			<p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;">Delivery Address :</p>
			<span id="req_Deliveryaddress" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:11px; font-weight:normal;"></span>
			<button style="display: none;" type="button" class="remScnt">
				<i class="fa fa-trash-o"></i>
			</button>
		</div>
		
		<div class="drsElement drsMoveHandle drsGroupItem" data-name="ccname" style="left: 8px; top: 60px; width: 260px; height: 30px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 1px; border-style: hidden; border-color: rgb(0, 0, 0); z-index: 2; font-size: 11px;">
			<p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;"></p>
			<span id="req_ccname" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:11px; font-weight:normal;"></span>
			<button style="display: none;" type="button" class="remScnt">
				<i class="fa fa-trash-o"></i>
			</button>
		</div>
		
		<div class="drsElement drsMoveHandle drsGroupItem" data-name="ccaddress" style="left: 8px; top: 111px; width: 330px; height: 53px; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border-width: 0px; border-style: solid; border-color: rgb(0, 0, 0); z-index: 2; font-size: 11px;">
			<p style="display:inline;clear:both;font-family:'Open Sans', sans-serif !important; padding-left:5px; font-weight:normal;"></p>
			<span id="req_ccaddress" style="font-family:'Open Sans', sans-serif !important; padding-left:10px !important; color:#000;font-size:11px; font-weight:normal;"></span>
			<button style="display: none;" type="button" class="remScnt">
				<i class="fa fa-trash-o"></i>
			</button>
		</div>
		
		<button style="display: inline-block;" type="button" class="remScnt">
			<i class="fa fa-trash-o"></i>
		</button>
	</div>
</div>
<script>
    function Imagebrowse(id) {
        var id = $(id)[0].id;
		
        var arr = id.split('_')[1];
		$("#myfile_1").click();
        $('#myfile_1').change(function() {
            readURL(this,arr);
        });
    }
	function readURL(input, value) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            //var id = value;
            reader.onload = function(e) {
                $("#showpic_1").hide();
                $("#req_LogoPath").show();
                $('#req_LogoPath').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>
<!--table--> 