<!-- INLINE CSS -->
<style>
.tr_hot 						{background:#f9eaea;}
.tr_warm 						{background:#f8f1e4;}
.tr_cold 						{background:#e8f0f6;}
.flwup_proimg					{margin-top:12px;}
#dataTable .jqx-grid-header 	{height:75px !important;}
</style>
<!-- INLINE CSS -->
<div class="content_wrapper padlr0">
	<div class="container-fluid padlr0">
    	<div class="col-lg-12">
            <h1>Lead Followup Register</h1>
			
        </div>
        <div class="col-lg-12 padlr0 commargin_top commargin_bottom">
                <div class="col-lg-2 col-md-6 col-sm-6 col-xs-6 mnimumwidthres">
                    <div class="tagcardhdng pnl-overflow crmbrdrclr1">
                        <div class="icon-bg"><i class="fa fa-list-alt i-text-111"></i></div>
                        <h5 class="tetmuted tet-clr11 comnelips" id="MWorkOrderNo"><?php echo $FollowupCount['FollowupId'];?></h5>
                        <h2 class="comtex commargin_bottom_5 crmbrdrclrhed1 comnelips" style="font-weight:600 !important;padding-left: 3px !important;">Total Followup</h2>
                    </div>
                </div>
                <div class="col-lg-2 col-md-6 col-sm-6 col-xs-6 mnimumwidthres">
                    <div class="tagcardhdng pnl-overflow" style="border-bottom:1px solid #c22423">
                        <div class="icon-bg"><i class="fa fa-list-alt i-text-111"></i></div>
                        <h5 class="tetmuted tet-clr11 comnelips" id="MWorkOrderNo"><?php echo $statushot['CallTypeId'];?></h5>
                        <h2 class="comtex commargin_bottom_5  comnelips" style="font-weight:600 !important; color:#c22423 !important;padding-left: 3px !important;">Hot</h2>
                    </div>
                </div>
                <div class="col-lg-2 col-md-6 col-sm-6 col-xs-6 mnimumwidthres">
                    <div class="tagcardhdng pnl-overflow" style="border-bottom:1px solid #e19d26">
                        <div class="icon-bg"><i class="fa fa-list-alt i-text-111"></i></div>
                        <h5 class="tetmuted tet-clr11 comnelips" id="MWorkOrderNo"><?php echo $statuswarm['CallTypeId'];?></h5>
                        <h2 class="comtex commargin_bottom_5  comnelips" style="font-weight:600 !important;color:#e19d26 !important;padding-left: 3px !important;">Warm</h2>
                    </div>
                </div>
                <div class="col-lg-2 col-md-6 col-sm-6 col-xs-6 mnimumwidthres">
                    <div class="tagcardhdng pnl-overflow" style="border-bottom:1px solid #1d71b9">
                        <div class="icon-bg"><i class="fa fa-list-alt i-text-111"></i></div>
                        <h5 class="tetmuted tet-clr11 comnelips" id="MWorkOrderNo"><?php echo $statuscold['CallTypeId'];?></h5>
                        <h2 class="comtex commargin_bottom_5  comnelips" style="font-weight:600 !important;color:#1d71b9 !important;padding-left: 3px !important;">Cold</h2>
                    </div>
                </div>
                <div class="col-lg-2 col-md-6 col-sm-6 col-xs-6 mnimumwidthres">
                    <div class="tagcardhdng pnl-overflow crmbrdrclr3">
                        <div class="icon-bg"><i class="fa fa-user i-text-111"></i></div>
                        <h5 class="tetmuted tet-clr11 comnelips" id="MWOClientName"><?php echo $Finalise['CallTypeId'];?></h5>
                        <h2 class="comtex  commargin_bottom_5 crmbrdrclrhed3 comnelips" style="font-weight:600 !important;padding-left: 3px !important;">Finalize</h2>
                    </div>
                </div>
                <div class="col-lg-2 col-md-6 col-sm-6 col-xs-6 mnimumwidthres">
                    <div class="tagcardhdng pnl-overflow crmbrdrclr5">
                        <div class="icon-bg"><i class="fa fa-suitcase i-text-111"></i></div>
                        <h5 class="tetmuted tet-clr11 comnelips" id="MProjectName"><?php echo $drop['CallTypeId'];?></h5>
                        <h2 class="comtex commargin_bottom_5 crmbrdrclrhed5 comnelips" style="font-weight:600 !important;padding-left: 3px !important;">Drop</h2>
                    </div>
                </div>
        </div>
		<div class="col-lg-12 clear  commargin_ttop_20">
		<div class="col-lg-3 padlr0">
                	<div class="radio_check">
                        <p>
                           <input type="checkbox" id="cfilter" value="filter" onchange="changeGrid()"/>
                           <label for="cfilter" class="ripple ">Conditional Filter</label>
                       </p>
                    </div>
                </div>
        	<div id="dataTable"></div>
        </div>
	</div>
</div>
<!-- PAGE SCRIPTS-->
<script>
$(function(){
    $('.lead_table tr').click(function(){ 
		$('.right_lightbox').show();
		$('.left-panel').removeClass('collapsed');
		$('.l_menuicon_nav').removeClass('cross');
    });
	$('.right_lightbox_close').click(function(){
		$('.right_lightbox').hide();
		if ($(window).width() >=980){
			$('.left-panel').addClass('collapsed');	
			$('.l_menuicon_nav').addClass('cross');
		}
	});
});
$(function(){

      //Initialize card flip
      $('#flp').on('click', function() {
		$(this).addClass('flip');
       });
});
</script>
<script>
jQuery(document).ready(function($) {
    $(".clickable-row").click(function() {
        window.document.location = $(this).data("href");
    });
});

function changeGrid()
{
    if($("#cfilter").is(':checked')) {
        $("#dataTable").jqxGrid({
            showfilterrow: false
        });
        $("#dataTable .jqx-grid-header").css("cssText", "height: 40px !important;");
    } else {
        $("#dataTable").jqxGrid({
            showfilterrow: true
        });

    }
}

$(document).ready(function () {
    var data = <?php echo (isset($results)) ? json_encode($results) : ''?>;
    var source =
    {
        localData: data,
        dataType: "json",
        dataFields: [
            { name: 'FollowUpDate', type: "date"},
            { name: 'LeadName', type: 'string' },
            { name: 'Call', type: 'string' },
            { name: 'Projects', type: 'string' },
            { name: 'CallType', type: 'string' },
            { name: 'Nature', type: 'string' },
            { name: 'UserName', type: 'string' },
            { name: 'Mobile', type: 'string' },
            { name: 'NextCallDate', type: "date"},
			{ name: 'NextFollowUpType', type: 'string' },
            { name: 'StatusId', type: 'number' }

        ],
        id: 'EntryId'
    };

    var dataAdapter = new $.jqx.dataAdapter(source);

    var cellclassname = function (row, column, value, data) {
        if(data.StatusId == 1) {
            return 'tr_hot';
        } else if(data.StatusId == 2) {
            return 'tr_warm';
        } else if(data.StatusId == 3) {
            return 'tr_cold';
        }
    };

    $("#dataTable").jqxGrid({
        width: '100%',
        source: dataAdapter,
        pageable: true,
        selectionMode: 'singleRow',
        pagerButtonsCount: 6,
        autoheight:true,
        rowsheight:40,
        autorowheight: true,
        filterable: true,
        sortable: true,
        //filtermode: 'advanced',
        columnsResize: true,
        showfilterrow: true,
        ready:function(){
        },
        rendered: function () {
        },
        columns: [
          { text: 'Date', filtertype: 'date',width:110, dataField: 'FollowUpDate',cellsformat: 'dd-MM-yyyy', cellclassname: cellclassname},
          { text: 'Lead Name', dataField: 'LeadName', cellclassname: cellclassname},
          { text: 'Contact Number', dataField: 'Mobile', cellclassname: cellclassname},
          { text: 'Projects', dataField: 'Projects', cellclassname: cellclassname },
          { text: 'Call Type', dataField: 'CallType', cellclassname: cellclassname },
		  { text: 'Nature', dataField: 'Nature', cellclassname: cellclassname },
          { text: 'Executive', dataField: 'UserName', cellclassname: cellclassname },
          { text: 'Next Followup Date', filtertype: 'date',width:160, dataField: 'NextCallDate',cellsformat: 'dd-MM-yyyy', cellclassname: cellclassname},
          { text: 'Next Followup Type', dataField: 'NextFollowUpType', cellclassname: cellclassname},
          { text: 'Status', dataField: 'StatusId', cellclassname: cellclassname, hidden:true }
        ]
    });

    $('#dataTable').on('celldoubleclick', function (event){
        // event arguments.
        var args = event.args;
        // row's bound index.
        var rowBoundIndex = args.rowindex;
        // row's visible index.
        var rowVisibleIndex = args.visibleindex;
        // right click.
        var rightclick = args.rightclick;
        // original event.
        var ev = args.originalEvent;
        // column index.
        var columnindex = args.columnindex;
        // column data field.
        var dataField = args.datafield;
        // cell value
        var value = args.value;
        var data = $("#dataTable").jqxGrid("getrowdata", rowBoundIndex);
        if(dataField != '')
            location.replace("<?php echo $this->basePath(); ?>/crm/lead/followup-details/"+data.uid);
    });
}); 
</script>
<!-- PAGE SCRIPTS-->
