<?php
function nonZeroNumber($number) {
    if(!isset($number) || !is_numeric($number) || $number <= 0) {
        return '';
    } else {
        return round($number, 2);
    }
}
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/css/project.css" />

<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/select2.full.min.js"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/select2.min.css"/>
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/workorder.css"/>
<style>
    .totalright{font-weight:600; color:green; font-size:14px;}
    .left-rights label{ float:right; color:#244996;}
    .fnt14{ font-size:19px !important; float:left;  margin-left: -12px;}
    .left-rights h1 span{ float:right !important;margin-right: -12px;font-size:18px;}
</style>
<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
        <div class="col-lg-12">
            <h1>Post Sale Discount</h1>
        </div>
        <div class="col-lg-12 clear">
            <div class="col-lg-12 clear">
                <div class="kickoff_area col-lg-12 clear">
                    <div class="col-lg-12 clear padlr0">
                        <div class="col-lg-12 col-md-12 col-sm-12 cnt_sliders padlr0">
                            <?php if(isset($unitBooking)): ?>
                            <form id="postsalediscount-form" method="post">
                                <input type="hidden" name="csrf" value="<?php echo isset($csrf) ? $csrf : ''; ?>">
                                <input type="hidden" name="booking_id" value="<?php echo $unitBooking['BookingId']; ?>">
                                <input type="hidden" name="postsaleDiscountId" value="<?php echo $postsaleDiscountId; ?>">
                                <div id="carousel" class="carousel slide" data-ride="carousel">
                                    <!-- Wrapper for slides -->
                                    <div class="carousel-inner" role="listbox">
                                        <!--step 1-->
                                        <div class="item active">
                                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                                <div class="float_l">
                                                    <label for="booking_no" class="bk_lbl bk_lbl_inpt">Vocher no <span class="colon_r">:</span></label>
                                                    <input type="text" class="bk_lbl_inpt inputbg_ef bk_inpt1" name="booking_no" id="booking_no" value="<?php echo $svNo; ?>"/>
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 col-lg-pull-1 col-md-pull-1 col-sm-pull-1">
                                                <div class="col-lg-offset-1">
                                                    <label for="booking_date" class="bk_lbl bk_lbl_inpt"><span class="bkspan_calendar"><i class="fa fa-calendar-o"></i></span> Vocher Date <span class="colon_r">:</span></label>
                                                    <input type="text" class="date_picker bk_lbl_inpt bk_inpt inputbg_ef" name="booking_date" id="booking_date" value="<?php echo date('d-m-Y'); ?>"/>
                                                </div>
                                            </div>
                                            <div class="col-lg-6 m_tb10">
                                                <div class="col-lg-8 col-lg-offset-2">
                                                    <div class="row">
                                                        <div class="form-group m_top20 col-lg-12 padtop20">
                                                            <input type="text" name="project_name" class="form-control lbl_move" label="Project Name"
                                                                   value="<?php echo $unitBooking['ProjectName']; ?>" disabled>
                                                            <input type="hidden" name="project_id" id="project_id" value="<?php echo $unitBooking['ProjectId']; ?>">
                                                        </div>
                                                        <div class="form-group col-lg-12 padtop20">
                                                            <input type="text" name="unit_no" class="form-control lbl_move" label="Unit No"
                                                                   value="<?php echo $unitBooking['UnitNo']; ?>" disabled>
                                                            <input type="hidden" name="unit_id" id="unit_id" value="<?php echo $unitBooking['UnitId']; ?>">
                                                        </div>
                                                        <div class="form-group col-lg-12 padtop20">
                                                            <div class="radio_check col-lg-11 col-lg-offset-1 col-md-8 col-md-offset-2">
                                                                <?php if ($unitBooking['CustomerType'] == 'B') { ?>
                                                                    <p class="col-lg-6">
                                                                        <input type="radio" name="buyer_investor" id="buyer" value="B"
                                                                            <?php echo ($unitBooking['CustomerType'] == 'B')?'checked':''; ?>>
                                                                        <label for="buyer">Buyer</label>
                                                                    </p>
                                                                <?php } else { ?>
                                                                    <p class="col-lg-6">
                                                                        <input type="radio" name="buyer_investor" id="investor" value="I"
                                                                            <?php echo ($unitBooking['CustomerType'] == 'I')?'checked':''; ?>>
                                                                        <label for="investor">Investor</label>
                                                                    </p>
                                                                <?php }?>
                                                            </div>
                                                        </div>
                                                        <div id="unitprice-wrapper" class="form-group col-lg-12 padtop10">
                                                            <input type="text" name="unit_rate" id="unit_rate" class="form-control lbl_move"
                                                                   label="Unit Rate (Per Sq.ft)" readonly value="<?php echo $unitBooking['Rate']; ?>"/>
                                                        </div>
                                                        <div class="form-group col-lg-12 padtop20">
                                                            <label class="txt_left control-label">Post Sale Discount based on</label>
                                                            <div class="radio_check col-lg-11 col-lg-offset-1 col-md-8 col-md-offset-2">
                                                                <p class="col-lg-6">
                                                                    <input type="radio" name="post_discount_based" id="post_normal" value="N"
                                                                        <?php echo ($unitBooking['PostDiscountBased'] == 'N')?'checked':'checked'; ?>>
                                                                    <label for="post_normal">Normal</label>
                                                                </p>
                                                                <p class="col-lg-6">
                                                                    <input type="radio" name="post_discount_based" id="post_plan" value="P"
                                                                        <?php echo ($unitBooking['PostDiscountBased'] == 'P')?'checked':''; ?>>
                                                                    <label for="post_plan">Plan</label>
                                                                </p>
                                                            </div>
                                                        </div>
                                                        <div id="plan-list-wrapper" <?php if(isset($unitBooking)) { if($unitBooking['PostDiscountBased']=='P') { echo "style='display:block;'"; } else { echo "style='display:none;'"; } } ?> class="form-group col-lg-12 padtop10">
                                                            <select id="post_plan_list" name="post_plan_list" class="form-control single_dropdown lbl_move"
                                                                    data-bsfshare="PlanName" label="Select Plan" style="width:100%;" onchange="planDetails($(this).val());">
                                                                <option value=""></option>
                                                                <?php if(isset($planList)) {
                                                                    foreach ($planList as $planDetails) { ?>
                                                                        <option value="<?php echo $planDetails['PlanId']; ?>" <?php echo ($unitBooking['PostPlanId'] == $planDetails['PlanId']) ? 'selected' : ''; ?>><?php echo $planDetails['PlanName']; ?></option>
                                                                    <?php }
                                                                }?>
                                                            </select>
                                                        </div>
                                                        <div id="post-discount-type-wrapper" class="form-group col-lg-12 padtop10">
                                                            <select id="post_discount_type" name="post_discount_type" class="form-control single_dropdown lbl_move plan_disabled"
                                                                    label="Select Post Sale Discount Type" style="width:100%;">
                                                                <option value=""></option>
                                                                <option value="R" <?php echo ($unitBooking['PostDiscountType'] == 'R')?'selected':''; ?>>Rate/Sq.ft</option>
                                                                <option value="L" <?php echo ($unitBooking['PostDiscountType'] == 'L')?'selected':''; ?>>Lumpsum</option>
                                                                <option value="P" <?php echo ($unitBooking['PostDiscountType'] == 'P')?'selected':''; ?>>Percentage</option>
                                                            </select>
                                                        </div>
                                                        <div id="post-lumpsum-type-wrapper" class="form-group col-lg-12 padtop10 animated fadeInUp <?php echo ($unitBooking['PostDiscountType'] != 'L' && $unitBooking['PostDiscountType'] != 'L')?'hide':''; ?>">
                                                            <div class="radio_check col-lg-11 col-lg-offset-1 col-md-8 col-md-offset-2">
                                                                <p class="col-lg-6">
                                                                    <input type="radio" class="plan_disabled" name="post_lumpsum_type" id="post_lumpsum_type_overall" value="O" <?php echo ($unitBooking['PostLumpsumReceiptId'] == 0)?'checked':''; ?>>
                                                                    <label for="post_lumpsum_type_overall">OverAll</label>
                                                                </p>
                                                                <p class="col-lg-6">
                                                                    <input type="radio" class="plan_disabled" name="post_lumpsum_type" id="post_lumpsum_type_receiptwise" value="R" <?php echo ($unitBooking['PostLumpsumReceiptId'] != 0)?'checked':''; ?>>
                                                                    <label for="post_lumpsum_type_receiptwise">Receipt wise</label>
                                                                </p>
                                                            </div>
                                                        </div>
                                                        <div id="post-lumpsum-receipt-wise-wrapper" class="form-group col-lg-12 padtop10 animated fadeInUp <?php echo ($unitBooking['PostLumpsumReceiptId'] == 0)?'hide':''; ?>">
                                                            <select id="post_lumpsum_receipt_wise" name="post_lumpsum_receipt_wise" class="plan_disabled form-control single_dropdown lbl_move"
                                                                    label="Select Receipt Type" style="width:100%;">
                                                                <option value=""></option>
                                                                <?php foreach($arrReceiptTypes as $receipt): ?>
                                                                    <option value="<?php echo $receipt['ReceiptTypeId']; ?>" data-type="<?php echo $receipt['Type']; ?>" <?php echo ($unitBooking['PostLumpsumReceiptId'] == $receipt['ReceiptTypeId'])?'selected':''; ?>><?php echo $receipt['ReceiptTypeName']; ?></option>
                                                                <?php endforeach; ?>
                                                            </select>
                                                        </div>
                                                        <div id="post-discount-wrapper" class="form-group col-lg-12 padtop10 animated fadeInUp <?php echo ($unitBooking['PostDiscountType'] == '')?'hide':''; ?>">
                                                            <input type="text" name="post_discount" id="post_discount" class="plan_disabled form-control lbl_move"
                                                                   label="Post Sale Discount" onkeypress="return isDecimal(event, this)"
                                                                   value="<?php echo ($unitBooking['PostDiscount'] > 0)?$unitBooking['PostDiscount']:''; ?>"/>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div id="unit-detail-wrapper" class="col-lg-6 m_tb10">
                                                <div class="form-group">
                                                    <div class="col-lg-12">
                                                        <div class="stginner_h5">
                                                            <h5>Unit Detail</h5>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-lg-12">
                                                                <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Unit Type</label>
                                                                <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                                                    <p id="unitdetail_UnitTypeName"><?php echo $unitBooking['UnitTypeName'];?></p>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-lg-12">
                                                                <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Block Name</label>
                                                                <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                                                    <p id="unitdetail_BlockName"><?php echo $unitBooking['BlockName'];?></p>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-lg-12">
                                                                <label
                                                                    class="col-lg-5 padlr0 col-md-5 col-sm-5 col-md-4 txt_left control-label">Level</label>
                                                                <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                                                    <p id="unitdetail_FloorName"><?php echo $unitBooking['FloorName'];?></p>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-lg-12">
                                                                <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Area</label>
                                                                <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                                                    <p><span id="unitdetail_UnitArea"><?php echo $this->commonHelper()->sanitizeNumber($unitBooking['UnitArea'],2);?> </span></p>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="liner"></div>
                                                        <div class="row">
                                                            <div class="col-lg-12">
                                                                <label class="col-lg-4 padlr0 col-md-4 col-sm-4 control-label"></label>
                                                                <div class="col-lg-4 col-md-4 col-sm-4 padlr0 left-rights">
                                                                    <label class="control-label bk_lbl_inpt">Previous Value</label>
                                                                </div>
                                                                <div class="col-lg-4 col-md-4 col-sm-4 padlr0 left-rights">
                                                                    <label class="control-label bk_lbl_inpt">After Discount</label>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-lg-12">
                                                                <label class="col-lg-4 padlr0 col-md-4 col-sm-4 txt_left control-label">Rate</label>
                                                                <div class="col-lg-4 col-md-4 col-sm-4 padlr0">
                                                                    <p id="unitdetail_Rate" class="text-right"><?php echo $this->commonHelper()->sanitizeNumber($unitBooking['Rate'],2,true);?></p>
                                                                </div>
                                                                <div class="col-lg-4 col-md-4 col-sm-4 padlr0">
                                                                    <p id="unitdetail_disRate" class="text-right"><?php echo $this->commonHelper()->sanitizeNumber($unitBooking['DisRate'],2,true);?></p>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-lg-12">
                                                                <label class="col-lg-4 padlr0 col-md-4 col-sm-4 txt_left control-label">Base Amount</label>

                                                                <div class="col-lg-4 col-md-4 col-sm-4 padlr0">
                                                                    <p id="unitdetail_BaseAmt" class="text-right"><?php echo $this->commonHelper()->sanitizeNumber($unitBooking['BaseAmount'],2,true);?></p>
                                                                </div>
                                                                <div class="col-lg-4 col-md-4 col-sm-4 padlr0">
                                                                    <p id="unitdetail_disBaseAmt" class="text-right"><?php echo $this->commonHelper()->sanitizeNumber($unitBooking['DisBaseAmount'],2,true);?></p>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-lg-12">
                                                                <label class="col-lg-4 padlr0 col-md-4 col-sm-4 txt_left control-label">Land Amount</label>
                                                                <div class="col-lg-4 col-md-4 col-sm-4 padlr0">
                                                                    <p id="unitdetail_LandAmount" class="text-right"><?php echo $this->commonHelper()->sanitizeNumber($unitBooking['LandAmount'],2,true);?></p>
                                                                </div>
                                                                <div class="col-lg-4 col-md-4 col-sm-4 padlr0">
                                                                    <p id="unitdetail_disLandAmount" class="text-right"><?php echo $this->commonHelper()->sanitizeNumber($unitBooking['DisLandAmount'],2,true);?></p>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-lg-12">
                                                                <label class="col-lg-4 padlr0 col-md-4 col-sm-4 txt_left control-label">Construction Amount</label>
                                                                <div class="col-lg-4 col-md-4 col-sm-4 padlr0">
                                                                    <p id="unitdetail_ConstructionAmount" class="text-right"><?php echo $this->commonHelper()->sanitizeNumber($unitBooking['ConstructionAmount'],2,true);?></p>
                                                                </div>
                                                                <div class="col-lg-4 col-md-4 col-sm-4 padlr0">
                                                                    <p id="unitdetail_disConstructionAmount" class="text-right"><?php echo $this->commonHelper()->sanitizeNumber($unitBooking['DisConstructionAmount'],2,true);?></p>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-lg-12">
                                                                <label class="col-lg-4 padlr0 col-md-4 col-sm-4 txt_left control-label">Other Cost Amount</label>
                                                                <div class="col-lg-4 col-md-4 col-sm-4 padlr0">
                                                                    <p id="unitdet_OtherAmount" class="text-right"><?php echo $this->commonHelper()->sanitizeNumber($unitBooking['OtherCostAmount'],2,true);?></p>
                                                                </div>
                                                                <div class="col-lg-4 col-md-4 col-sm-4 padlr0">
                                                                    <p id="unitdet_disOtherAmount" class="text-right"><?php echo $this->commonHelper()->sanitizeNumber($unitBooking['DisOtherCostAmount'],2,true);?></p>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-lg-12">
                                                                <label class="col-lg-4 padlr0 col-md-4 col-sm-4 txt_left control-label">Gross Amount</label>

                                                                <div class="col-lg-4 col-md-4 col-sm-4 padlr0">
                                                                    <p id="unitdetail_GrossAmount" class="text-right"><?php echo $this->commonHelper()->sanitizeNumber($unitBooking['ConstructionAmount']+$unitBooking['LandAmount']+$unitBooking['OtherCostAmount'],2,true);?></p>
                                                                </div>
                                                                <div class="col-lg-4 col-md-4 col-sm-4 padlr0">
                                                                    <p id="unitdetail_disGrossAmount" class="text-right"><?php echo $this->commonHelper()->sanitizeNumber($unitBooking['DisConstructionAmount']+$unitBooking['DisLandAmount']+$unitBooking['DisOtherCostAmount'],2,true);?></p>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-lg-12">
                                                                <label class="col-lg-4 padlr0 col-md-4 col-sm-4 txt_left control-label">Qualifier Amount</label>
                                                                <div class="col-lg-4 col-md-4 col-sm-4 padlr0">
                                                                    <p id="unitdet_QualAmt" class="text-right"><?php echo $this->commonHelper()->sanitizeNumber($unitBooking['QualifierAmount'],2,true);?></p>
                                                                </div>
                                                                <div class="col-lg-4 col-md-4 col-sm-4 padlr0">
                                                                    <p id="unitdet_disQualAmt" class="text-right"><?php echo $this->commonHelper()->sanitizeNumber($unitBooking['DisQualifierAmount'],2,true);?></p>
                                                                </div>
                                                            </div>
                                                        </div>
<!--                                                        <div class="row">-->
<!--                                                            <div class="col-lg-12">-->
<!--                                                                <label class="col-lg-4 padlr0 col-md-4 col-sm-4 txt_left control-label">Land and Construction Amount</label>-->
<!--                                                                <div class="col-lg-4 col-md-4 col-sm-4 padlr0">-->
<!--                                                                    <p id="landconst" class="text-right">--><?php //echo $this->commonHelper()->sanitizeNumber($unitBooking['LandConsAmount'],2,true);?><!--</p>-->
<!--                                                                </div>-->
<!--                                                                <div class="col-lg-4 col-md-4 col-sm-4 padlr0">-->
<!--                                                                    <p id="dislandconst" class="text-right">--><?php //echo $this->commonHelper()->sanitizeNumber($unitBooking['DisLandConsAmount'],2,true);?><!--</p>-->
<!--                                                                </div>-->
<!--                                                            </div>-->
<!--                                                        </div>-->
                                                        <div class="row" id="lndcnst">
                                                            <div class="col-lg-12">
                                                                <label class="col-lg-4 padlr0 col-md-4 col-sm-4 txt_left control-label">Land and construction reg amount</label>
                                                                <div class="col-lg-4 col-md-4 col-sm-4 padlr0">
                                                                    <p id="unitdet_landconst" class="text-right"><?php echo $this->commonHelper()->sanitizeNumber($untld,2,true);?></p>
                                                                </div>
                                                                <div class="col-lg-4 col-md-4 col-sm-4 padlr0">
                                                                    <p id="unitdet_dislandconst" class="text-right">0</p>
                                                                </div>
                                                            </div>
                                                        </div>

                                                            <div class="net_amnt">
                                                            <div class="col-lg-12">
                                                                <div class="col-lg-4 col-md-4 col-sm-4 padlr0">
                                                                    <h1 class="fnt14">Net Amount</h1>
                                                                </div>
                                                                <div class="col-lg-4 col-md-4 col-sm-4 padlr0 left-rights">
                                                                    <h1><span id="unitdetail_NetAmt"><?php echo $this->commonHelper()->sanitizeNumber($unitBooking['NetAmount'],2,true);?></span></h1>
                                                                </div>
                                                                <div class="col-lg-4  col-md-4 col-sm-4 padlr0 left-rights">
                                                                    <h1><span id="unitdetail_disNetAmt"><?php echo $this->commonHelper()->sanitizeNumber($unitBooking['DisNetAmount'],2,true);?></span></h1>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <input type="hidden" name="prevRate" id="prevRate" value="">
                                                        <input type="hidden" name="prevBaseAmt" id="prevBaseAmt" value="">
                                                        <input type="hidden" name="prevLandAmt" id="prevLandAmt" value="">
                                                        <input type="hidden" name="prevConstructionAmt" id="prevConstructionAmt" value="">
                                                        <input type="hidden" name="prevOthercostAmt" id="prevOthercostAmt" value="">
                                                        <input type="hidden" name="prevGrossAmt" id="prevGrossAmt" value="">
                                                        <input type="hidden" name="prevqualAmt" id="prevqualAmt"  value="">
                                                        <input type="hidden" name="prevnetAmt" id="prevnetAmt" value="">

                                                        <input type="hidden" name="curdisRate" id="curdisRate" value="">
                                                        <input type="hidden" name="curdisBaseAmt" id="curdisBaseAmt" value="">
                                                        <input type="hidden" name="curdisLandAmt" id="curdisLandAmt" value="">
                                                        <input type="hidden" name="curdisConstructionAmt" id="curdisConstructionAmt" value="">
                                                        <input type="hidden" name="curdisOthercostAmt" id="curdisOthercostAmt" value="">
                                                        <input type="hidden" name="curdisGrossAmt" id="curdisGrossAmt" value="">
                                                        <input type="hidden" name="curdisqualAmt" id="curdisqualAmt"  value="">
                                                        <input type="hidden" name="curdisnetAmt" id="curdisnetAmt" value="">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-lg-12 savebtn_area padlr0 marg0 clear">
                                                <ul>
                                                    <li class="save_btn float_r">
                                                        <a href="#" data-slide="next" data-stepno="2" class="ripple carousel-next-btn">Next</a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                        <!--step 2-->
                                        <div class="item">
                                            <div class="col-lg-12 padlr0">
                                                <div class="col-lg-6 col-md-6 col-sm-8 padlr0">
                                                    <div class="form-group m_top20 col-lg-12">
                                                        <input type="text" name="payment_scheduleName" class="form-control lbl_move" label="Payment Schedule Name"
                                                               value="<?php echo $unitBooking['PaymentSchedule']; ?>" disabled>
                                                        <input type="hidden" name="payment_scheduleId" id="payment_scheduleId" value="<?php echo $unitBooking['PaymentScheduleId']; ?>">
                                                    </div>
                                                </div>
                                                <div id="payment-schedule-container" class="col-lg-12 animated fadeInUp">
                                                    <h1>Payment Schedule</h1>
                                                    <?php if(isset($arrPaymentScheduleDetails)): ?>
                                                        <div id="payment-schedule-wrapper" class="table-responsive m_btm20" style="min-height:200px;">
                                                            <table class="table payment-schedule" data-id="<?php echo $unitBooking['PaymentScheduleId']; ?>">
                                                                <thead>
                                                                <tr>
                                                                    <th>Description</th>
                                                                    <th>Date</th>
                                                                    <th>Round Off</th>
                                                                    <th>Schedule %</th>
                                                                    <th>Previous Amount</th>
                                                                    <th>Discount Amount</th>
                                                                    <th>After Discount</th>
                                                                    <th>Tax Amount</th>
                                                                    <th>Net Amount</th>
                                                                    <th></th>
                                                                </tr>
                                                                </thead>
                                                                <tbody>
                                                                <?php $i = 0; ; $recAmtTot = 0; $recTaxTot = 0; $shPer=0; $qid=0;
                                                                foreach($arrPaymentScheduleDetails as $paymentSchedule):
                                                                    $i++;
                                                                    $shPer += $paymentSchedule['Percentage'];
                                                                    $recAmtTot += $paymentSchedule['Amount'];
                                                                    $recTaxTot += $paymentSchedule['QualAmount'];

                                                                    $isReceiptsFound = isset($paymentSchedule['arrReceiptTypes'])?TRUE:FALSE;
                                                                    ?>
                                                                    <tr class="mainTr <?php echo ($paymentSchedule['BillPassed']==1)?'bill-passed':''; ?>">
                                                                        <td><input type="text" class="tbl_input txt_right" name="desc_<?php echo $i; ?>" value="<?php echo $paymentSchedule['StageName']; ?>" readonly />
                                                                        </td>
                                                                        <td><?php  if(date( 'd-m-Y', strtotime( $paymentSchedule[ 'SchDate' ] ) )=='01-01-1970'){ echo '-'; } else{
                                                                                echo date( 'd-m-Y', strtotime( $paymentSchedule[ 'SchDate' ] ) ); } ?> </td>
                                                                        <td><?php echo nonZeroNumber($paymentSchedule['RoundOff']); ?></td>
                                                                        <td><input type="text" class="tbl_input txt_right" name="schPer_<?php echo $i; ?>" value="<?php echo ($paymentSchedule['Percentage'] >0) ? $this->commonHelper()->sanitizeNumber($paymentSchedule['Percentage'],2).'%': ''; ?>" readonly /></td>
                                                                        <?php if ($postsaleDiscountId ==0) { ?>
                                                                            <td><input type="text" class="tbl_input txt_right" name = "schAmt_<?php echo $i; ?>" id="schAmt_<?php echo $i; ?>" value="<?php echo $this->commonHelper()->sanitizeNumber($paymentSchedule['Amount'],2,true); ?>" readonly /></td>
                                                                            <td><input type="text" class="tbl_input txt_right disnet" name = "schdis_<?php echo $i; ?>" id="schdis_<?php echo $i; ?>" value="" readonly /></td>
                                                                        <?php } else { ?>
                                                                            <td><input type="text" class="tbl_input txt_right" name = "schAmt_<?php echo $i; ?>" id="schAmt_<?php echo $i; ?>" value="<?php echo $this->commonHelper()->sanitizeNumber($paymentSchedule['PrevAmount'],2,true); ?>" readonly /></td>
                                                                            <td><input type="text" class="tbl_input txt_right disnet" name = "schdis_<?php echo $i; ?>" id="schdis_<?php echo $i; ?>" value="<?php echo $this->commonHelper()->sanitizeNumber($paymentSchedule['DiscountAmount'],2,true); ?>" readonly /></td>
                                                                        <?php } ?>
                                                                        <td><input type="text" class="tbl_input txt_right curnet" name = "CurAmt_<?php echo $i; ?>" id="CurAmt_<?php echo $i; ?>" value="<?php echo $this->commonHelper()->sanitizeNumber($paymentSchedule['Amount'],2,true); ?>" readonly /></td>
                                                                        <td><input type="text" class="tbl_input sch-tax txt_right taxnet" name = "TaxAmt_<?php echo $i; ?>" id="TaxAmt_<?php echo $i; ?>" value="<?php echo $this->commonHelper()->sanitizeNumber($paymentSchedule['QualAmount'],2,true); ?>" readonly /></td>
                                                                        <td><input type="text" class="tbl_input sch-net-amt txt_right netnet" name = "NetAmt_<?php echo $i; ?>" id="NetAmt_<?php echo $i; ?>" value="<?php echo $this->commonHelper()->sanitizeNumber($paymentSchedule['NetAmount'],2,true); ?>" readonly /></td>
                                                                        <input type="hidden" name="psScheduleId_<?php echo $i; ?>" value = "<?php echo $paymentSchedule['PaymentScheduleUnitTransId']; ?>"/>
                                                                        <input type="hidden" name="stageId_<?php echo $i; ?>" value = "<?php echo $paymentSchedule['StageId']; ?>"/>
                                                                        <input type="hidden" name="stageType_<?php echo $i; ?>" value = "<?php echo $paymentSchedule['StageType']; ?>"/>
                                                                        <input type="hidden" name="schDate_<?php echo $i; ?>" value = "<?php echo date('d-m-Y', strtotime($paymentSchedule['SchDate'])); ?>"/>
                                                                        <input type="hidden" name="schRound_<?php echo $i; ?>" value = "<?php echo nonZeroNumber($paymentSchedule['RoundOff']); ?>"/>
                                                                        <input type="hidden" name="schSortId_<?php echo $i; ?>" value = "<?php echo $paymentSchedule['SortId']; ?>"/>
                                                                        <td>
                                                                            <?php if($isReceiptsFound): ?>
                                                                                <ul class="action_btns">
                                                                                    <li><a href="#" class="subTr"><i class="fa fa-chevron-circle-down" data-toggle="tooltip" data-placement="top" data-original-title="Expand"></i></a></li>
                                                                                </ul>
                                                                            <?php endif; ?>
                                                                        </td>
                                                                    </tr>
                                                                    <?php if($isReceiptsFound): ?>

                                                                    <tr style="display: none;" class="subTr">
                                                                        <td colspan="11" style="padding:0px !important; ">
                                                                            <div class="subDiv" style="display: none;">
                                                                                <div class="col-lg-12 col-lg-offset-0 rdbt" style="margin-top:5px;"></div>
                                                                                <div class="col-lg-12">
                                                                                    <div class="table-responsive topsp">
                                                                                        <table class="table receipt-type-table" style="margin-bottom:0px;">
                                                                                            <thead>
                                                                                            <tr>
                                                                                                <th>Receipt Type</th>
                                                                                                <th>Before Discount</th>
                                                                                                <th>Discount</th>
                                                                                                <th>After Discount</th>
                                                                                                <th>Tax</th>
                                                                                                <th>Net Amount</th>
                                                                                                <th></th>
                                                                                            </tr>
                                                                                            </thead>
                                                                                            <tbody>
                                                                                            <?php $j = 0;
                                                                                            foreach($paymentSchedule['arrReceiptTypes'] as $receipt):
                                                                                                $isHavingQualifier = isset($receipt['qualHtmlTag'])?TRUE:FALSE;
                                                                                                $j++; $qid++;
                                                                                                ?>
                                                                                                <tr>
                                                                                                    <td><?php echo $receipt['ReceiptName']; ?></td>
                                                                                                    <?php if ($postsaleDiscountId ==0) { ?>
                                                                                                        <td><input type="text" name="BillAbs_<?php echo $i; ?>_shAmt_<?php echo $j; ?>" id="BillAbs_<?php echo $i; ?>_shAmt_<?php echo $j; ?>" class="sch-shamt tbl_input txt_right" value="<?php echo $this->commonHelper()->sanitizeNumber($receipt['Amount'],2,true); ?>" readonly></td>
                                                                                                        <td><input type="text" name="BillAbs_<?php echo $i; ?>_disAmt_<?php echo $j; ?>" id="BillAbs_<?php echo $i; ?>_disAmt_<?php echo $j; ?>" class="sch-dis tbl_input txt_right" value="" readonly></td>
                                                                                                    <?php } else { ?>
                                                                                                        <td><input type="text" name="BillAbs_<?php echo $i; ?>_shAmt_<?php echo $j; ?>" id="BillAbs_<?php echo $i; ?>_shAmt_<?php echo $j; ?>" class="sch-shamt tbl_input txt_right" value="<?php echo $this->commonHelper()->sanitizeNumber($receipt['PrevAmount'],2,true); ?>" readonly></td>
                                                                                                        <td><input type="text" name="BillAbs_<?php echo $i; ?>_disAmt_<?php echo $j; ?>" id="BillAbs_<?php echo $i; ?>_disAmt_<?php echo $j; ?>" class="sch-dis tbl_input txt_right" value="<?php echo $this->commonHelper()->sanitizeNumber($receipt['DiscountAmount'],2,true); ?>" readonly></td>
                                                                                                    <?php } ?>
                                                                                                    <td><input type="text" name="BillAbs_<?php echo $i; ?>_CurAmt_<?php echo $j; ?>" id="BillAbs_<?php echo $i; ?>_CurAmt_<?php echo $j; ?>" class="sch-amt tbl_input txt_right" value="<?php echo $this->commonHelper()->sanitizeNumber($receipt['Amount'],2,true); ?>" readonly></td>
                                                                                                    <td><input type="text" name="BillAbs_<?php echo $i; ?>_TaxAmt_<?php echo $j; ?>" id="BillAbs_<?php echo $i; ?>_TaxAmt_<?php echo $j; ?>" class="sch-tax tbl_input txt_right" value="<?php echo $this->commonHelper()->sanitizeNumber($receipt['QualAmount'],2,true); ?>" readonly></td>
                                                                                                    <td><input type="text" name = "BillAbs_<?php echo $i; ?>_NetAmt_<?php echo $j; ?>" id="BillAbs_<?php echo $i; ?>_NetAmt_<?php echo $j; ?>"  class="sch-net-amt tbl_input txt_right" value="<?php echo $this->commonHelper()->sanitizeNumber($receipt['NetAmount'],2,true); ?>" readonly></td>
                                                                                                    <td width="3%" align="center" class="action_btns_td">
                                                                                                        <?php if($isHavingQualifier): ?>
                                                                                                            <ul class="action_btns">
                                                                                                                <li><a href="#" class="rqualmainTr"><i class="fa fa-chevron-circle-down" data-toggle="tooltip" data-placement="top" data-original-title="Expand"></i></a></li>
                                                                                                            </ul>
                                                                                                        <?php endif; ?>
                                                                                                        <input type="hidden" class="qualRefId" name="BillAbs_<?php echo $i; ?>_QualRefId_<?php echo $j; ?>" id="BillAbs_<?php echo $i; ?>_QualRefId_<?php echo $j; ?>" value="<?php echo $qid; ?>" readonly>
                                                                                                    </td>
                                                                                                    <input type="hidden" name="BillAbs_<?php echo $i; ?>_receiptTypeId_<?php echo $j; ?>" id="BillAbs_<?php echo $i; ?>_receiptTypeId_<?php echo $j; ?>" value = "<?php echo $receipt['ReceiptTypeId']; ?>"/>
                                                                                                    <input type="hidden" name ="BillAbs_<?php echo $i; ?>_receiptType_<?php echo $j; ?>" id="BillAbs_<?php echo $i; ?>_receiptType_<?php echo $j; ?>" value = "<?php echo $receipt['ReceiptType']; ?>"/>
                                                                                                    <input type="hidden" name="BillAbs_<?php echo $i; ?>_BillPassed_<?php echo $j; ?>" id="BillAbs_<?php echo $i; ?>_BillPassed_<?php echo $j; ?>" value = "<?php echo $paymentSchedule['BillPassed']; ?>"/>
                                                                                                    <input type="hidden" name="BillAbs_<?php echo $i; ?>_PaidAmount_<?php echo $j; ?>" id="BillAbs_<?php echo $i; ?>_PaidAmount_<?php echo $j; ?>" value = "<?php echo $receipt['PaidAmount']; ?>"/>
                                                                                                </tr>
                                                                                                <?php if($isHavingQualifier): ?>
                                                                                                <tr class="subTr qualmainTr" style="display:none;">
                                                                                                    <?php $textHtml =  $receipt['qualHtmlTag'] ; $textHtml = str_replace('__1','_'.$qid,$textHtml);?>
                                                                                                    <td colspan="7"><div class="subDiv"><?php echo $textHtml; ?></div></td>
                                                                                                </tr>
                                                                                            <?php endif; ?>
                                                                                            <?php
                                                                                            endforeach; ?>
                                                                                            <input type="hidden" name="refRowId_<?php echo $i; ?>" id="refRowId_<?php echo $i; ?>" value = "<?php echo $j; ?>"/>
                                                                                            </tbody>
                                                                                        </table>
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                        </td>
                                                                    </tr>
                                                                <?php endif; ?>
                                                                <?php
                                                                endforeach; ?>
                                                                <input type="hidden" name="shRowId" id="shRowId" value = "<?php echo $i; ?>"/>
                                                                <tr>
                                                                    <td colspan="3" class="text-right rate_pri">Total</td>
                                                                    <td><input type="text" class="rec-tot-amt tbl_input txt_right totalright" value="<?php echo $this->commonHelper()->sanitizeNumber($shPer,2).'%'; ?>"></td>
                                                                    <td><input type="text" class="rec-tot-amt tbl_input txt_right totalright" value="<?php echo $this->commonHelper()->sanitizeNumber($recAmtTot,2,true); ?>"></td>
                                                                    <td><input type="text" class="rec-tot-amt tbl_input txt_right totalright" id ='distotal' value=""></td>
                                                                    <td><input type="text" class="rec-tot-amt tbl_input txt_right totalright" id ='curtotal' value="<?php echo $this->commonHelper()->sanitizeNumber($recAmtTot,2,true); ?>"></td>
                                                                    <td><input type="text" class="rec-tot-amt tbl_input txt_right totalright" id ='taxtotal' value="<?php echo $this->commonHelper()->sanitizeNumber($recTaxTot,2,true); ?>"></td>
                                                                    <td><input type="text" class="rec-tot-amt tbl_input txt_right totalright" id ='nettotal' value="<?php echo $this->commonHelper()->sanitizeNumber(($recAmtTot + $recTaxTot),2,true); ?>"></td>
                                                                    <td></td>
                                                                </tr>
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                            <div class="col-lg-12 savebtn_area padlr0 marg0 clear">
                                                <ul>
                                                    <li class="save_btn float_l">
                                                        <a href="#carousel" data-slide="prev" data-stepno="1" class="ripple steps_btn">Back</a>
                                                    </li>
                                                    <li class="save_btn float_r">
                                                        <!-- <a href="#" data-slide="next" data-stepno="3" class="ripple carousel-next-btn">Next</a>-->
                                                        <a id="update-btn" href="#" class="ripple">Update</a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                        </div>
                    </div>
                    </form>
                    <?php elseif(isset($err)): ?>
                        <h1 class="text-center" style="margin: 150px auto;">Error: <?php echo $err; ?></h1>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    var $carousel = $('#carousel'),
        $paymentScheduleWrapper = $('#payment-schedule-wrapper'),
        $booking_no = $('#booking_no'),
        $booking_date = $('#booking_date'),
    // $unitRate = $('#$unitRate'),
        $discount = $('#booking_date'),
        $post_discount = $('#post_discount'),
        $postDiscountWrapper = $('#post-discount-wrapper'),
        $post_discount_type = $('#post_discount_type'),
        $post_lumpsum_receipt_wise = $('#post_lumpsum_receipt_wise'),
        $postLumpsumTypeWrapper = $('#post-lumpsum-type-wrapper'),
        $postLumpsumReceiptWiseWrapper = $('#post-lumpsum-receipt-wise-wrapper'),
        $postLumpsumType = $postLumpsumTypeWrapper.find('input[name="post_lumpsum_type"]');
        $updateBtn = $('#update-btn'),
        $constructionAmt = $('#unitdetail_ConstructionAmount'),
        $landAmt = $('#unitdetail_LandAmount'),
        $unitdetail_UnitArea = $('#unitdetail_UnitArea'),
        $unitdetail_Rate = $('#unitdetail_Rate'),
        $unitdetail_BaseAmt = $('#unitdetail_BaseAmt'),
        $unitdetail_GrossAmt = $('#unitdetail_GrossAmount'),
        $unitdetail_OtherCostAmt = $('#unitdet_OtherAmount'),
        $unitdetail_NetAmt = $('#unitdetail_NetAmt'),
        arrOtherCost = <?php echo json_encode($arrOtherCost); ?>;

    $(function () {
        bindNextBtn_onClick();
        bindExpandMainTr();
        bindExpandMainTrInput();
        closeMainTr();
        bindRQualExpandTr();
        bindRQualExpandTrInput();
        closeRQualTr();
        bindQualExpandTr();
        bindQualExpandTrInput();
        closeQualTr();
        bindPostDiscountType_onChange();
        bindPostLumpsumType_onChange();
        bindPostLumpsumReceiptWise_onChange();
        bindPostDiscount_onChange();
        bindCustomQualRef();
        updateValue();
        bindUpdate_onClick();
    });

    function bindNextBtn_onClick() {
        $('.carousel-next-btn').on('click', function (ev) {
            ev.preventDefault();

            var stepno = parseInt($(this).attr('data-stepno'));

            switch (stepno) {
                case 2:
                    // $carousel.carousel('next');
                    validate_step1(function (isSuccess) {
                        if (isSuccess) {
                           // var discount = parseFloat($post_discount.val());
                          //  if (!isNaN(discount)) {
                            //    $post_discount.trigger('change');

                         //   }

                            //  $payment_schedule.trigger('change');
                            $carousel.carousel('next');

                        }
                    });
                    break;
            }
        });

    }
    $(function () {
        $("#carousel").carousel({
            interval: false
        });
    });
    $('input[type=radio][name=post_discount_based]').on('change',function() {
        if($(this).val()=="N") {
            $("#plan-list-wrapper").hide();
            $("#post_plan_list").val('').trigger('change');
            $("#post_discount_type").val('').trigger('change');
            $('.plan_disabled').prop("disabled",false);
            $("#post-discount-type-wrapper").show();
            $("#post_discount").val('').trigger('change');

        } else if($(this).val()=="P") {
            $("#post-discount-type-wrapper").hide();
            $("#post_discount_type").val('').trigger('change');
            $("#plan-list-wrapper").show();
            $("#post_discount").val('').trigger('change');
        }
        $post_discount.val('').trigger('change');
    });

    function bindPostDiscountType_onChange() {
        $post_discount_type.on('change', function() {

            var discountType = $post_discount_type.val().trim();

            $postDiscountWrapper.addClass('hide');
            $postLumpsumTypeWrapper.addClass('hide');
            $postLumpsumReceiptWiseWrapper.addClass('hide');

            // $post_discount.val('').trigger('change');
            $postLumpsumType.removeAttr('checked');
            if(discountType.length > 0 ) {
                if(discountType == 'L'||discountType == 'P') {
                    $postLumpsumTypeWrapper.removeClass('hide');
                } else {
                    $postDiscountWrapper.removeClass('hide');
                }
            }
            $post_discount.val('').trigger('change');
        });
    }

    function bindPostLumpsumType_onChange() {
        $postLumpsumType.on('change', function() {
            var lumpsumType = $(this).val();
            if(lumpsumType == 'O') {
                $postDiscountWrapper.removeClass('hide');
                $postLumpsumReceiptWiseWrapper.addClass('hide');
            } else {
                $postDiscountWrapper.addClass('hide');
                $postLumpsumReceiptWiseWrapper.removeClass('hide');
            }
            $post_lumpsum_receipt_wise.find('option').removeAttr('selected');
            $post_discount.val('').trigger('change');
        });
    }

    function bindPostLumpsumReceiptWise_onChange() {
        $post_lumpsum_receipt_wise.on('change', function() {

            removeError($post_lumpsum_receipt_wise);

            var receiptWise = $(this).val();
            if(receiptWise.length > 0) {
                $postDiscountWrapper.removeClass('hide');
            } else {
                $postDiscountWrapper.addClass('hide');
            }
            $post_discount.val('').trigger('change');
        });
    }



    function validate_step1(callback) {
        var booking_no = $booking_no.val().trim(),
            booking_date = $booking_date.val().trim(),
        // unitRate = parseFloat($unit_rate.val()),
            discount = parseFloat($post_discount.val());

        if (booking_no.length <= 0) {
            alert('Booking No is required!');
            $booking_no.focus();

            callback(false);
            return false;
        } else if ($booking_no.hasClass('already-exists')) {
            alert('Booking No already exists!');
            $booking_no.focus();

            callback(false);
            return false;
        } else if (booking_date.length <= 0) {
            alert('Booking Date is required!');
            $booking_date.focus();

            callback(false);
            return false;
        } else if ($post_discount_type.val() != '' && isNaN(discount)) {
            showError($post_discount, 'Discount is required!');
            $post_discount.focus();

            callback(false);
            return false;
        } else if ($post_discount_type.val() == 'P' && parseFloat($post_discount.val()) > 100) {
            showError($discount, 'Percentage Discount should not be > 100');
            $discount.focus();
            callback(false);
            return false;

        } else if ($post_discount.hasClass('error')) {
            callback(false);
            return false;
        }
        else if (($post_discount_type.val()==0)|| ($post_discount_type.val()=='')) { console.log(61);
            showError($post_discount_type, 'postDiscounttype is required!');
            callback(false);
            return false;

        }else {
            callback(true);
            return true;
        }
    }

    function bindExpandMainTr() {
        $paymentScheduleWrapper.on('click', '.mainTr', function(e){
            e.preventDefault();
            if (!$(this).closest("tr").next(".subTr").is(":visible")) {
                closeMainTr();
                $(this).closest("tr").next(".subTr").show();
                $(this).closest("tr").next(".subTr").find(".subDiv").slideDown("slow");
                $(this).find("i").addClass("tform");
            }
            else {
                $(this).closest("tr").next(".subTr").find(".subDiv").slideUp("slow");
                $(this).closest("tr").next(".subTr").slideUp("slow");
                $(this).find("i").removeClass("tform");
            }
        });
    }

    function bindExpandMainTrInput() {
        $paymentScheduleWrapper.on('focus', '.mainTrInput', function() {
            if (!$(this).closest("tr").next(".subTr").is(":visible")) {
                closeMainTr();
                $(this).closest("tr").next(".subTr").show();
                $(this).closest("tr").next(".subTr").find(".subDiv").slideDown("slow");
            }
        });
    }

    function closeMainTr() {
        var $mainTr = $(".mainTr");
        $.each($mainTr, function () {
            $(this).find('.tform').removeClass('tform');
            $(this).closest("tr").next(".subTr").find(".subDiv").slideUp("slow");
            $(this).closest("tr").next(".subTr").slideUp("slow");
        });
    }

    function bindRQualExpandTr() {
        $paymentScheduleWrapper.on('click', '.rqualmainTr', function (e) {
            e.preventDefault();
            if (!$(this).closest("tr").next(".qualmainTr").is(":visible")) {
                closeRQualTr();
                $(this).closest("tr").next(".qualmainTr").show();
                $(this).closest("tr").next(".qualmainTr").find(".subDiv").slideDown("slow");
                $(this).find("i").addClass("tform");
            }
            else {
                $(this).closest("tr").next(".qualmainTr").find(".subDiv").slideUp("slow");
                $(this).closest("tr").next(".qualmainTr").slideUp("slow");
                $(this).find("i").removeClass("tform");
            }
        });
    }

    function bindRQualExpandTrInput() {
        $paymentScheduleWrapper.on('focus', '.rqualmainTrInput', function (e) {
            if (!$(this).closest("tr").next(".qualmainTr").is(":visible")) {
                closeRQualTr();
                $(this).closest("tr").next(".qualmainTr").show();
                $(this).closest("tr").next(".qualmainTr").find(".subDiv").slideDown("slow");
            }
        });
    }

    function closeRQualTr() {
        var $mainTr = $(".rqualmainTr");
        $.each($mainTr, function () {
            $(this).closest("tr").next(".qualmainTr").find(".subDiv").slideUp("slow");
            $(this).closest("tr").next(".qualmainTr").slideUp("slow");
        });
    }


    function bindQualExpandTr() {
        $paymentScheduleWrapper.on('click', '.qualmainExp', function (e) {
            e.preventDefault();
            if (!$(this).closest("tr").next(".qualsubTr").is(":visible")) {
                closeQualTr();
                $(this).closest("tr").next(".qualsubTr").show();
                $(this).closest("tr").next(".qualsubTr").find(".subDiv").slideDown("slow");
                $(this).find("i").addClass("tform");
            }
            else {
                $(this).closest("tr").next(".qualsubTr").find(".subDiv").slideUp("slow");
                $(this).closest("tr").next(".qualsubTr").slideUp("slow");
                $(this).find("i").removeClass("tform");
            }
        });
    }

    function bindQualExpandTrInput() {
        $paymentScheduleWrapper.on('focus', '.qualmainTrInput', function (e) {
            if (!$(this).closest("tr").next(".qualsubTr").is(":visible")) {
                closeQualTr()
                $(this).closest("tr").next(".qualsubTr").show();
                $(this).closest("tr").next(".qualsubTr").find(".subDiv").slideDown("slow");
            }
        });
    }

    function closeQualTr() {
        var $mainTr = $(".qualmainExp");
        $.each($mainTr, function () {
            $(this).closest("tr").next(".qualsubTr").find(".subDiv").slideUp("slow");
            $(this).closest("tr").next(".qualsubTr").slideUp("slow");
        });
    }

    function planDetails(pId) {
        if(pId!="" && pId !=null) {
            $.ajax({
                url: getBaseURL() + 'crm/lead/finalisation-edit',
                data: {csrf: "<?php echo isset($csrf)?$csrf:''; ?>", PlanId: pId},
                type: 'POST',
                success: function (data, status, xhr) {
                    if (xhr.status == 200) {
                        var planDetails = JSON.parse(data);
                        if(planDetails!=false) {
                            removeError($('#post_lumpsum_receipt_wise'));
                            $('#post_discount_type').val(planDetails.DiscountType).trigger('change');
                            $('#post-discount-type-wrapper').show();
                            if(planDetails.DiscountType=="L" || planDetails.DiscountType=="P") {
                                $("input[name=post_lumpsum_type][value=" + planDetails.LumpsumType + "]").prop('checked', true).trigger('change');
                            }
                            if(planDetails.ReceiptType==0) {
                                $('#post_lumpsum_receipt_wise').val('').trigger('change');
                            } else {
                                $('#post_lumpsum_receipt_wise').val(planDetails.ReceiptType).trigger('change');
                            }
                            $('#post_discount').val(planDetails.Discount).trigger('change');
                            $('#post-discount-wrapper').removeClass('hide');
                            $('.plan_disabled').prop("disabled",true);
                        }
                    }
                },
                error: function (xhr, status, error) {
                    alert(xhr.responseText);
                }
            });
        } else {
            $('#discount-type-wrapper').hide();
            $('#discount_type').val('').trigger('change');
        }
    }

    function discountClear() {
        $('#unitdetail_disRate').text('');
        $('#unitdetail_disBaseAmt').text('');
        $('#unitdetail_disLandAmount').text('');
        $('#unitdetail_disConstructionAmount').text('');
        $('#unitdet_disOtherAmount').text('')
        $('#unitdetail_disGrossAmount').text('');
        $('#unitdet_disQualAmt').text('');
        $('#unitdetail_disNetAmt').text('');
    }

    function bindPostDiscount_onChange() {
        $post_discount.on('change', function () {
            removeError($post_discount);

            var discount = parseFloat(isNullCheck($post_discount.val(),'number')),
                area = parseFloat(isNullCheck($unitdetail_UnitArea.text(),'number')),
                rate = parseFloat(isNullCheck($unitdetail_Rate.text(),'number')),
                otherCostAmt = parseFloat(isNullCheck($unitdetail_OtherCostAmt.text(),'number')),
                landAmt = parseFloat(isNullCheck($landAmt.text(),'number')),
                constructionAmt = parseFloat(isNullCheck($constructionAmt.text(),'number')),
                baseAmt =parseFloat(isNullCheck($unitdetail_BaseAmt.text(),'number'));
            var dt=parseFloatVal($("#unitdet_landconst").text());

            var newRate= 0,newDiscount= 0,newBaseAmt= 0,newLandAmt= 0,newConstAmt= 0;

            discountClear();
            if (discount==0) return;

            if ($post_discount_type.val() == 'L') {
                var lumpsumType = $postLumpsumType.filter(':checked').val();
                if (lumpsumType == 'O') {
                    if(post_discount > baseAmt) {
                        showError($post_discount, 'Discount should be lesser than Base Amount!');
                        return;
                    }
                    newBaseAmt = baseAmt - discount;
                    newConstAmt = newBaseAmt-landAmt;

                    $('#unitdetail_disRate').text(sanitizeNumber(rate,2,true));
                    $('#unitdetail_disBaseAmt').text(sanitizeNumber(newBaseAmt,2,true));
                    $('#unitdetail_disLandAmount').text(sanitizeNumber(landAmt,2,true));
                    $('#unitdetail_disConstructionAmount').text(sanitizeNumber(newConstAmt,2,true));
                    $('#unitdet_disOtherAmount').text(sanitizeNumber(otherCostAmt,2,true))
                    $('#unitdetail_disGrossAmount').text(sanitizeNumber(landAmt+newConstAmt+otherCostAmt,2,true));
                    $('#unitdetail_disNetAmt').text(sanitizeNumber(landAmt+newConstAmt+otherCostAmt+dt,2,true));
                } else {
                    var receiptType = $post_lumpsum_receipt_wise.val();
                    if(receiptType.length <= 0) {
                        showError($post_lumpsum_receipt_wise, 'Select Receipt Type!');
                        return;
                    }

                    var $selReceiptType = $post_lumpsum_receipt_wise.find('option:selected'),
                        selReceipt = $selReceiptType.attr('data-type');

                    if(selReceipt == 'C') {
                        if(post_discount > constructionAmt) {
                            showError($post_discount, 'Discount should be lesser than Construction Amount!');
                            return;
                        }
                        newConstAmt =  constructionAmt - discount

                        $('#unitdetail_disRate').text(sanitizeNumber(rate,2,true));
                        $('#unitdetail_disBaseAmt').text(sanitizeNumber(baseAmt,2,true));
                        $('#unitdetail_disLandAmount').text(sanitizeNumber(landAmt,2,true));
                        $('#unitdetail_disConstructionAmount').text(sanitizeNumber(newConstAmt,2,true));
                        $('#unitdet_disOtherAmount').text(sanitizeNumber(otherCostAmt,2,true))
                        $('#unitdetail_disGrossAmount').text(sanitizeNumber(landAmt+newConstAmt+otherCostAmt,2,true));
                        $('#unitdetail_disNetAmt').text(sanitizeNumber(landAmt+newConstAmt+otherCostAmt+dt,2,true));

                    } else if(selReceipt == 'L') {
                        if(post_discount > landAmt) {
                            showError($post_discount, 'Discount should be lesser than Land Amount!');
                            return;
                        }
                        newLandAmt =  landAmt-discount;
                        $('#unitdetail_disRate').text(sanitizeNumber(rate,2,true));
                        $('#unitdetail_disBaseAmt').text(sanitizeNumber(baseAmt,2,true));
                        $('#unitdetail_disLandAmount').text(sanitizeNumber(newLandAmt,2,true));
                        $('#unitdetail_disConstructionAmount').text(sanitizeNumber(constructionAmt,2,true));
                        $('#unitdet_disOtherAmount').text(sanitizeNumber(otherCostAmt,2,true))
                        $('#unitdetail_disGrossAmount').text(sanitizeNumber(newLandAmt+constructionAmt+otherCostAmt,2,true));
                        $('#unitdetail_disNetAmt').text(sanitizeNumber(newLandAmt+constructionAmt+otherCostAmt+dt,2,true));
                    }
                }
            } else if ($post_discount_type.val() == 'R') {
                if (post_discount > rate) {
                    showError($post_discount, 'Discount should be lesser than Unit rate!');
                    return;
                } else {
                    newRate = rate - discount;
                    newBaseAmt = newRate * area;
                    newConstAmt = newBaseAmt-landAmt;

                    $('#unitdetail_disRate').text(sanitizeNumber(newRate,2,true));
                    $('#unitdetail_disBaseAmt').text(sanitizeNumber(newBaseAmt,2,true));
                    $('#unitdetail_disLandAmount').text(sanitizeNumber(landAmt,2,true));
                    $('#unitdetail_disConstructionAmount').text(sanitizeNumber(newConstAmt,2,true));
                    $('#unitdet_disOtherAmount').text(sanitizeNumber(otherCostAmt,2,true))
                    $('#unitdetail_disGrossAmount').text(sanitizeNumber(newBaseAmt+otherCostAmt,2,true));
                    $('#unitdetail_disNetAmt').text(sanitizeNumber(newBaseAmt+otherCostAmt+dt,2,true));
                }
            } else if($post_discount_type.val() =='P') {
                var lumpsumType = $postLumpsumType.filter(':checked').val();
                if (lumpsumType == 'O') {
                    newDiscount=baseAmt * (discount/100);
                    newBaseAmt = baseAmt - newDiscount;
                    newConstAmt =baseAmt-landAmt;

                    $('#unitdetail_disRate').text(sanitizeNumber(rate,2,true));
                    $('#unitdetail_disBaseAmt').text(sanitizeNumber(newBaseAmt,2,true));
                    $('#unitdetail_disLandAmount').text(sanitizeNumber(landAmt,2,true));
                    $('#unitdetail_disConstructionAmount').text(sanitizeNumber(newConstAmt,2,true));
                    $('#unitdet_disOtherAmount').text(sanitizeNumber(otherCostAmt,2,true))
                    $('#unitdetail_disGrossAmount').text(sanitizeNumber(newBaseAmt+otherCostAmt,2,true));
                    $('#unitdetail_disNetAmt').text(sanitizeNumber(newBaseAmt+otherCostAmt+dt,2,true));
                } else {
                    // receipt wise
                    var receiptType = $post_lumpsum_receipt_wise.val();
                    if(receiptType.length <= 0) {
                        showError($post_lumpsum_receipt_wise, 'Select Receipt Type!');
                        return;
                    }

                    var $selReceiptType = $post_lumpsum_receipt_wise.find('option:selected'),
                        selReceipt = $selReceiptType.attr('data-type');
                    if(selReceipt == 'C') {
                        newDiscount =constructionAmt * (discount/100);
                        newConstAmt = constructionAmt -newDiscount;

                        $('#unitdetail_disRate').text(sanitizeNumber(rate,2,true));
                        $('#unitdetail_disBaseAmt').text(sanitizeNumber(baseAmt,2,true));
                        $('#unitdetail_disLandAmount').text(sanitizeNumber(landAmt,2,true));
                        $('#unitdetail_disConstructionAmount').text(sanitizeNumber(newConstAmt,2,true));
                        $('#unitdet_disOtherAmount').text(sanitizeNumber(otherCostAmt,2,true))
                        $('#unitdetail_disGrossAmount').text(sanitizeNumber(landAmt+newConstAmt+otherCostAmt,2,true));
                        $('#unitdetail_disNetAmt').text(sanitizeNumber(landAmt+newConstAmt+otherCostAmt+dt,2,true));

                    } else if(selReceipt == 'L') {
                        newDiscount =landAmt* (discount/100);
                        newLandAmt = landAmt- newDiscount

                        $('#unitdetail_disRate').text(sanitizeNumber(rate,2,true));
                        $('#unitdetail_disBaseAmt').text(sanitizeNumber(baseAmt,2,true));
                        $('#unitdetail_disLandAmount').text(sanitizeNumber(newLandAmt,2,true));
                        $('#unitdetail_disConstructionAmount').text(sanitizeNumber(constructionAmt,2,true));
                        $('#unitdet_disOtherAmount').text(sanitizeNumber(otherCostAmt,2,true))
                        $('#unitdetail_disGrossAmount').text(sanitizeNumber(newLandAmt+constructionAmt+otherCostAmt,2,true));
                        $('#unitdetail_disNetAmt').text(sanitizeNumber(newLandAmt+constructionAmt+otherCostAmt+dt,2,true));
                    }
                }
            }

            $('#unitdet_dislandconst').text(sanitizeNumber(dt,2,true));
            getTax();
            fillDiscount();
        });
    }

    function getTax() {
        var dt=parseFloatVal($("#unitdet_landconst").text());

        var arrCost = [],dGrossAmt=0;
        var landAmt = parseFloatVal(isNullCheck($('#unitdetail_disLandAmount').text(),'number')),
            constructionAmt = parseFloatVal(isNullCheck($('#unitdetail_disConstructionAmount').text(),'number'));

        dGrossAmt = landAmt+ constructionAmt;

        arrCost.push({
            ReceiptType:'S',
            TypeId: 1,
            Amount: landAmt
        });

        arrCost.push({
            ReceiptType:'S',
            TypeId: 2,
            Amount: constructionAmt
        });


        //var sOC = isNullCheck($OtherCost.val(),'string');
        var sothercost ="", dOthercost=0;

        $.each(arrOtherCost, function (i, val) {
            arrCost.push({
                ReceiptType:'O',
                TypeId: arrOtherCost [i]['OtherCostId'],
                Amount: arrOtherCost [i]['Amount']
            });
            dGrossAmt = dGrossAmt + parseFloat(isNullCheck(arrOtherCost [i]['Amount'],'number'));
        });

        $('#unitdetail_disGrossAmount').text(sanitizeNumber(dGrossAmt,2,true));

        var dDate = new Date();
        var arrCost = JSON.stringify(arrCost);

        $.ajax({
            url: getBaseURL() + 'crm/lead/getTax',
            data: {csrf: "<?php echo isset($csrf)?$csrf:''; ?>",arrReceipt:arrCost, GrossAmt:dGrossAmt,shDate:dDate},
            async: false,
            type: 'POST',
            success: function (data, status, xhr) {

                var dTax= 0,sTax='';
                $.each(data.arrTax, function (index, tax) {
                    var dTaxAmt = parseFloatVal(isNullCheck(tax.Amount,'number'));
                    if (dTaxAmt !=0) {
                        dTax = dTax+dTaxAmt;
                        sTax = sTax +  tax.QualifierName + ': ' + dTaxAmt + '<br/>';
                    }
                });

                $('#unitdet_disQualAmt').text(sanitizeNumber(dTax, 2, true));
//                $('#arrQualAmt').attr('data-original-title',sTax);

                $('#unitdetail_disNetAmt').text(sanitizeNumber(dGrossAmt+dTax+dt, 2, true));
            },
            error: function (xhr, status, error) {
                alert(xhr.responseText);
            }
        });
    }

    function bindCustomQualRef() {
        $(".qualRefId").each(function () {
            var $z =$(this);
            akey1 = parseFloatVal($z[0].id.split('_')[1]);
            akey2 = parseFloatVal($z[0].id.split('_')[3]);

            var sname = 'BillAbs_' + akey1 + '_CurAmt_' + akey2;
            var key1 = $('#'+$z[0].id).val();
            $('#QualRowRef_' + key1).val(sname);
        });

//        $(".qualChange").each(function () {
//            CalculateTax($(this)[0].id);
//        });

//        var $q_ids = $('input[id*=QualTotalAmt_]');
//
//        $.each($q_ids, function (i, obj) {
//            var $tarReceiptTr = $(this).closest('.qualmainTr').prev('tr');
//
//            $tarReceiptTr.find('.sch-tax').val($(this).val());
//
//            calcReceiptTotal($tarReceiptTr.closest('tbody'));
//        });
    }

    //    function CalculateTax(id) {
    //        //if (bReady==false) return;
    //        var key1 = id.split('_')[1],
    //            key2 = id.split('_')[3];
    //
    //        var sname = $('#QualRowRef_' + key1).val();
    //        var dbaseAmt= parseFloatVal(isNullCheck($('#' + sname).val(),'number'));
    //
    //        CalculateQualifier(key1);
    //        var dTaxAmt = parseFloatVal(isNullCheck($('#QualTotalAmt_' + key1).val(),'number'));
    //
    //        var k1 = sname.split('_')[1],
    //            k2 = sname.split('_')[3];
    //
    //        $('#BillAbs_' + k1 + '_TaxAmt_' + k2).val(dTaxAmt);
    //        $('#BillAbs_' + k1 + '_NetAmt_' + k2).val(dTaxAmt+dbaseAmt);
    //
    ////        CalculateTot();
    //    }

    function fillDiscount() {
        var dLandAmt = parseFloat(isNullCheck($landAmt.text(),'number')),
            dConstructionAmt = parseFloat(isNullCheck($constructionAmt.text(),'number')),
            dLandDisAmt = parseFloat(isNullCheck($('#unitdetail_disLandAmount').text(),'number')),
            dConstDisAmt = parseFloat(isNullCheck($('#unitdetail_disConstructionAmount').text(),'number'));

        var dLandDiff = dLandAmt - dLandDisAmt,
            dConstDiff = dConstructionAmt - dConstDisAmt;

        var dTotConstAmt = 0,
            dTotLandAmt = 0;

        $(".sch-shamt").each(function () {
            var name = $(this)[0].id,
                key1 = parseInt(name.split('_')[1]),
                key2 = parseInt(name.split('_')[3]),
                iReceiptTypeId =   parseInt(isNullCheck($('#BillAbs_' + key1 + '_receiptTypeId_' + key2).val(),'number')),
                sReceiptType =  isNullCheck($('#BillAbs_' + key1 + '_receiptType_' + key2).val(),'string'),
                iBillPassed =  isNullCheck($('#BillAbs_' + key1 + '_BillPassed_' + key2).val(),'number'),
                dPaidAmount = parseFloat(isNullCheck($('#BillAbs_' + key1 + '_PaidAmount_' + key2).val(),'number'));

            if (iBillPassed ==0) {
                var dShAmt = parseFloat(isNullCheck($('#BillAbs_' + key1 + '_shAmt_' + key2).val(), 'number'))-dPaidAmount;
                if (dShAmt <0) dShAmt =0;

                if (sReceiptType == 'L')  dTotLandAmt = dTotLandAmt + dShAmt;
                if (sReceiptType == 'C')  dTotConstAmt = dTotConstAmt + dShAmt;
            }

        });

        var dLPer =  dLandDiff/dTotLandAmt,
            dCPer = dConstDiff/dTotConstAmt;

        var iPKey= 0,dDisTotal = 0,bAns=false,dCurTotal= 0,dTaxTotal=0,dNetTotal=0;

        $(".sch-shamt").each(function () {
            var name = $(this)[0].id,
                key1 = parseInt(name.split('_')[1]),
                key2 = parseInt(name.split('_')[3]),
                iReceiptTypeId =   parseInt(isNullCheck($('#BillAbs_' + key1 + '_receiptTypeId_' + key2).val(),'number')),
                sReceiptType =  isNullCheck($('#BillAbs_' + key1 + '_receiptType_' + key2).val(),'string'),
                iBillPassed =  isNullCheck($('#BillAbs_' + key1 + '_BillPassed_' + key2).val(),'number'),
                dPaidAmount = parseFloat(isNullCheck($('#BillAbs_' + key1 + '_PaidAmount_' + key2).val(),'number'));

            if (bAns==true) {
                if (iPKey != key1) {
                    $('#schdis_' + iPKey).val(sanitizeNumber(dDisTotal,2,true));
                    $('#CurAmt_' + iPKey).val(sanitizeNumber(dCurTotal,2,true));
                    $('#TaxAmt_' + iPKey).val(dTaxTotal);
                    $('#NetAmt_' + iPKey).val(dNetTotal);

                    dDisTotal=0;dCurTotal= 0;dTaxTotal=0;dNetTotal=0;

                    iPKey = key1;
                }
            } else iPKey = key1;


            if (iBillPassed ==0) {
                var dSchAmt = parseFloat(isNullCheck($('#BillAbs_' + key1 + '_shAmt_' + key2).val(), 'number')) - dPaidAmount,
                    dDisAmt = 0;
                if (dSchAmt < 0) dSchAmt = 0;
                if (sReceiptType == 'L' || sReceiptType == 'C') {
                    if (sReceiptType == 'L') dDisAmt = dSchAmt * dLPer;
                    if (sReceiptType == 'C') dDisAmt = dSchAmt * dCPer;

                    $('#BillAbs_' + key1 + '_disAmt_' + key2).val(sanitizeNumber(dDisAmt, 2, true));
                    $('#BillAbs_' + key1 + '_CurAmt_' + key2).val(sanitizeNumber(dSchAmt - dDisAmt, 2, true));

                    var iRefId = parseInt(isNullCheck($('#BillAbs_' + key1 + '_QualRefId_' + key2).val(), 'number'));

                    CalculateQualifier(iRefId);

                    var dTaxAmt = parseFloatVal(isNullCheck($('#QualTotalAmt_' + iRefId).val(), 'number'));
                    var dbaseAmt = (dSchAmt - dDisAmt);

                    $('#BillAbs_' + key1 + '_TaxAmt_' + key2).val(dTaxAmt);
                    $('#BillAbs_' + key1 + '_NetAmt_' + key2).val(dTaxAmt + dbaseAmt);
                }
            }

            dDisTotal = dDisTotal+ parseFloatVal(isNullCheck($('#BillAbs_' + key1 + '_disAmt_' + key2).val(),'number'));
            dCurTotal = dCurTotal+ parseFloatVal(isNullCheck($('#BillAbs_' + key1 + '_CurAmt_' + key2).val(),'number'));
            dTaxTotal = dTaxTotal+ parseFloatVal(isNullCheck($('#BillAbs_' + key1 + '_TaxAmt_' + key2).val(),'number'));
            dNetTotal = dNetTotal+ parseFloatVal(isNullCheck($('#BillAbs_' + key1 + '_NetAmt_' + key2).val(),'number'));

            bAns=true;

        });

        if (bAns==true) {
            $('#schdis_' + iPKey).val(sanitizeNumber(dDisTotal,2,true));
            $('#CurAmt_' + iPKey).val(sanitizeNumber(dCurTotal,2,true));
            $('#TaxAmt_' + iPKey).val(dTaxTotal);
            $('#NetAmt_' + iPKey).val(dNetTotal);
        }
        CalculateTot();
        updateValue();
    }


    function CalculateQualifier(key1) {

        var rows = $('#QualRowId_' + key1).val();
        var sformula="";
        var sname = $('#QualRowRef_' + key1).val();
        var dbaseAmt= parseFloatVal(isNullCheck($('#' + sname).val(),'number'));
        var dTotalQualAmt=0;

        for (i = 1; i <= rows; i++) {
            var sRef = $('#Qual_' + key1 + '_Ref_' + i).val().trim();
            var sFormula = $('#Qual_' + key1 + '_Exp_'+ i).val();

            var dPer = isNullCheck($('#Qual_' + key1 + '_ExpPer_'+ i).val(),'number');
            var sbaseRef = 'R0';
            if (parseFloatVal(dPer) ==0) dPer=100;
            sFormula = sFormula.replace(new RegExp(sbaseRef, 'g'), dbaseAmt);

            var fvaule = computeEval(sFormula);
            $('#Qual_' + key1 + '_ExpValue_' + i).val(sanitizeNumber(fvaule,2,true));

            var iQualTypeid = $('#Qual_' + key1 + '_TypeId_' + i).val();
            if (iQualTypeid==1)  {
                var dTaxablePer = parseFloatVal(isNullCheck($('#Qual_' + key1 + '_TaxablePer_' + i).val(), 'number'));
                var dTaxPer = parseFloatVal(isNullCheck($('#Qual_' + key1 + '_TaxPer_' + i).val(), 'number'));
                var dCess = parseFloatVal(isNullCheck($('#Qual_' + key1 + '_CessPer_' + i).val(), 'number'));
                var dEDCess = parseFloatVal(isNullCheck($('#Qual_' + key1 + '_EduCessPer_' + i).val(), 'number'));
                var dHEDCess = parseFloatVal(isNullCheck($('#Qual_' + key1 + '_HEduCessPer_' + i).val(), 'number'));
                var dNetPer = dTaxPer + (dTaxPer * (dCess + dEDCess + dHEDCess)) / 100;
                $('#Qual_' + key1 + '_NetPer_' + i).val(dNetPer);

                $('#Qual_' + key1 + '_NetPer_' + i).val(dNetPer);
                $('#Qual_' + key1 + '_ExpPer_' + i).val(sanitizeNumber(dNetPer, 2));

                var dTaxableAmt = fvaule * (dTaxablePer / 100);
                var dTaxAmt = dTaxableAmt * (dTaxPer / 100);
                var dCessAmt = dTaxAmt * (dCess / 100);
                var dEDAmt = dTaxAmt * (dEDCess / 100);
                var dHEDAmt = dTaxAmt * (dHEDCess / 100);
                var dNetAmt = dTaxAmt + dCessAmt + dEDAmt + dHEDAmt;

                $('#Qual_' + key1 + '_TaxableAmt_' + i).val(sanitizeNumber(dTaxableAmt, 2, true));
                $('#Qual_' + key1 + '_TaxPerAmt_' + i).val(sanitizeNumber(dTaxAmt, 2, true));
                $('#Qual_' + key1 + '_CessAmt_' + i).val(sanitizeNumber(dCessAmt, 2, true));
                $('#Qual_' + key1 + '_EduCessAmt_' + i).val(sanitizeNumber(dEDAmt, 2, true));
                $('#Qual_' + key1 + '_HEduCessAmt_' + i).val(sanitizeNumber(dHEDAmt, 2, true));
                $('#Qual_' + key1 + '_NetAmt_' + i).val(dNetAmt);

                dAmt = dNetAmt;
            } else if (iQualTypeid==2) {
                var dTaxablePer = parseFloatVal(isNullCheck($('#Qual_' + key1 + '_TaxablePer_' + i).val(), 'number'));
                var dTaxPer = parseFloatVal(isNullCheck($('#Qual_' + key1 + '_TaxPer_' + i).val(), 'number'));
                var dKKCess = parseFloatVal(isNullCheck($('#Qual_' + key1 + '_KKCessPer_' + i).val(), 'number'));
                var dSBCess = parseFloatVal(isNullCheck($('#Qual_' + key1 + '_SBCessPer_' + i).val(), 'number'));
                var dNetPer = dTaxPer + dKKCess + dSBCess;
                $('#Qual_' + key1 + '_NetPer_' + i).val(dNetPer);

                $('#Qual_' + key1 + '_NetPer_' + i).val(sanitizeNumber(dNetPer, 2));
                $('#Qual_' + key1 + '_ExpPer_' + i).val(sanitizeNumber(dNetPer, 2));

                var dTaxableAmt = fvaule * (dTaxablePer / 100);
                var dTaxAmt = dTaxableAmt * (dTaxPer / 100);
                var dKKCessAmt = dTaxableAmt * (dKKCess / 100);
                var dSBCessAmt = dTaxableAmt * (dSBCess / 100);

                var dNetAmt = dTaxAmt + dKKCessAmt + dSBCessAmt;

                $('#Qual_' + key1 + '_TaxableAmt_' + i).val(dTaxableAmt);
                $('#Qual_' + key1 + '_TaxPerAmt_' + i).val(dTaxAmt);
                $('#Qual_' + key1 + '_KKCessAmt_' + i).val(dKKCessAmt);
                $('#Qual_' + key1 + '_SBCessAmt_' + i).val(dSBCessAmt);
                $('#Qual_' + key1 + '_NetAmt_' + i).val(dNetAmt);

                dAmt = dNetAmt;
            } else {
                var dAmt = parseFloatVal(fvaule) * (parseFloatVal(dPer) / 100);
            }
            $('#Qual_' + key1 + '_Amount_' + i).val(dAmt);
            if ($('#Qual_' + key1 + '_YesNo_' + i).is(':checked') == true) dTotalQualAmt = dTotalQualAmt+ parseFloatVal(dAmt);
            for (j = i; j <= rows; j++) {
                var sFormula = $('#Qual_' + key1 + '_Exp_'+ i).val();
                sFormula = sFormula.replace(new RegExp(sRef, 'g'), dAmt);
            }
        }
        $('#QualTotalAmt_' + key1).val(dTotalQualAmt);
    }

    function CalculateTot() {
        var $mainTr = $(".disnet");
        var netamt =0;
        $.each($mainTr, function () {
            netamt += parseFloatVal(isNullCheck($(this)[0].value,'number'));
        });
        $('#distotal').val(sanitizeNumber(netamt,2,true));


        var $mainTax = $(".curnet");
        netamt =0;
        $.each($mainTax, function () {
            netamt += parseFloatVal(isNullCheck($(this)[0].value,'number'));
        });
        $('#curtotal').val(sanitizeNumber(netamt,2,true));

        var $mainTax = $(".taxnet");
        netamt =0;
        $.each($mainTax, function () {
            netamt += parseFloatVal(isNullCheck($(this)[0].value,'number'));
        });
        $('#taxtotal').val(sanitizeNumber(netamt,2,true));

        var $mainTax = $(".netnet");
        netamt =0;
        $.each($mainTax, function () {
            netamt += parseFloatVal(isNullCheck($(this)[0].value,'number'));
        });
        $('#nettotal').val(sanitizeNumber(netamt,2,true));

    }

    function updateValue() {
        $('#prevRate').val(parseFloatVal(isNullCheck($('#unitdetail_Rate').text(),'number')));
        $('#prevBaseAmt').val(parseFloatVal(isNullCheck($('#unitdetail_BaseAmt').text(),'number')));
        $('#prevLandAmt').val(parseFloatVal(isNullCheck($('#unitdetail_LandAmount').text(),'number')));
        $('#prevConstructionAmt').val(parseFloatVal(isNullCheck($('#unitdetail_ConstructionAmount').text(),'number')));
        $('#prevOthercostAmt').val(parseFloatVal(isNullCheck($('#unitdet_OtherAmount').text(),'number')));
        $('#prevGrossAmt').val(parseFloatVal(isNullCheck($('#unitdetail_GrossAmount').text(),'number')));
        $('#prevqualAmt').val(parseFloatVal(isNullCheck($('#unitdet_QualAmt').text(),'number')));
        $('#prevnetAmt').val(parseFloatVal(isNullCheck($('#unitdetail_NetAmt').text(),'number')));

        $('#curdisRate').val(parseFloatVal(isNullCheck($('#unitdetail_disRate').text(),'number')));
        $('#curdisBaseAmt').val(parseFloatVal(isNullCheck($('#unitdetail_disBaseAmt').text(),'number')));
        $('#curdisLandAmt').val(parseFloatVal(isNullCheck($('#unitdetail_disLandAmount').text(),'number')));
        $('#curdisConstructionAmt').val(parseFloatVal(isNullCheck($('#unitdetail_disConstructionAmount').text(),'number')));
        $('#curdisOthercostAmt').val(parseFloatVal(isNullCheck($('#unitdet_disOtherAmount').text(),'number')));
        $('#curdisGrossAmt').val(parseFloatVal(isNullCheck($('#unitdetail_disGrossAmount').text(),'number')));
        $('#curdisqualAmt').val(parseFloatVal(isNullCheck($('#unitdet_disQualAmt').text(),'number')));
        $('#curdisnetAmt').val(parseFloatVal(isNullCheck($('#unitdetail_disNetAmt').text(),'number')));
    }


    function bindUpdate_onClick() {
        $updateBtn.on('click', function (ev) {
            ev.preventDefault();

            validate(function (isSuccess) {
                if (isSuccess) {
                    updateValue();

                    $('.plan_disabled').prop("disabled", false);
                    $('#postsalediscount-form').submit();
                }
            });
        });

        function validate(callback) {

//            if (reg_name.length <= 0) {
//                showError($registration_name, 'Registration Name is required!');
//                callback(false);
//                return false;
//            }
////            else if (exe_name.length <= 0) {
////                showError($executive_name, 'Executive Name is required!');
////                callback(false);
////                return false;
////            }
//            else if (isNaN(exe_id)) {
//                showError($executive_name, 'Invalid Executive Name!');
//                callback(false);
//                return false;
//            } else if (isNaN(adv_amt)) {
//                showError($adv_amount, 'Advance amount is required!');
//                callback(false);
//                return false;
//            } else if(adv_amt > net_amt) {
//                showError($adv_amount, 'Advance amount should not exceed net amount!');
//                callback(false);
//                return false;
//            } else {
            callback(true);
            return true;
//            }
        }
    }
</script>
