<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css';?>"/>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/select2.full.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqx-all.js"></script>

<!-- INLINE CSS -->
<style>
    .tr_hot 						{background:#f9eaea;}
    .tr_warm 						{background:#f8f1e4;}
    .tr_cold 						{background:#e8f0f6;}
    .flwup_proimg					{margin-top:12px;}
    #dataTable .jqx-grid-header 	{height:75px !important;}
    .fixed-action-btn ul			{top:5px;}
    .bootstrap-select.btn-group .btn .filter-option	{ margin-top:-3px;}
</style>
<script id="excel_bind" type="text/template" class="hide">
    <tr id="excelrowid__" >
        <td><input class="parent_text" type="text" placeholder="Lead Name" name="excellead__" value = "" id="excellead__"/></td>
        <td><input class="parent_text" type="text" placeholder="Lead Date" name="exceldate__" value = "" id="exceldate__" /></td>
        <td><input class="parent_text excel-code-txt" type="text" placeholder="Executive" name="excelexecutive__" value = "" id="excelexecutive__" /></td>
        <td><input class="parent_text" type="text" placeholder="Mobile" name="excelmobile__" value = "" id="excelmobile__" onkeypress="return isNumberKey(event);" /></td>
        <td><input class="parent_text" type="text" placeholder="Email Address" name="excelemail__" value = "" id="excelemail__" /></td>
        <td><input class="parent_text" type="text" placeholder="Source" name="excelsource__" value = "" id="excelsource__" /></td>
        <td><input class="parent_text" type="text" placeholder="Project Name" name="excelproject__" value = "" id="excelproject__" /></td>
        <td><input class="parent_text" type="text" placeholder="Lead Type" name="excelleadtype__" value = "" id="excelleadtype__" /></td>
        <td align="center">
            <ul class="action_btns">
                <li>
                    <a href="#" id="excelTrDelete__" class="excelTrDelete" onclick="deleteRow(this);"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete" ></i></a>
                </li>
            </ul>
        </td>
    </tr>
</script>
<!-- INLINE CSS -->
<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
        <div class="col-lg-12">
            <h1 class="float_l">Lead Register
                <div class="stgedit_btn req_addbtn brad_50">
                    <a href="<?php echo $this->basePath(); ?>/crm/lead/entry" class="ripple" data-toggle="tooltip" data-placement="right" title="Add&nbsp;New&nbsp;Lead"><i class="fa fa-plus"></i></a>
                </div>
            </h1>
            <div class="fixed-action-btn padtop0">
                <a class="btn-floating btn-large"><i class="fa fa-paperclip"></i></a>
                <ul>
                    <li>
                        <a class="btn-floating hide-input-file" data-toggle="tooltip" data-placement="bottom" data-original-title="Import From Excel">
                            <i class="fa fa-file-excel-o"></i>
                            <input type="file" name="myfile" id="myfile" class="input-large" accept=".xls, .xlsx, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" onchange="getExcelField();">
                        </a>
                    </li>
                    <li>
                        <a class="btn-floating" href="javascript:void(0);" id="excelExport" download data-toggle="tooltip" data-placement="bottom" data-original-title="Download Sample">
                            <i class="fa fa-download"></i>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-6 col-lg-offset-6 col-md-8 col-md-offset-4 col-sm-10 col-sm-offset-2 clear padtop20 commargin_ttop_20 commargin_bottom">
                <div class="form-group col-lg-6 col-md-6 col-sm-6 commargin_top">
                    <span class="date_icon"><i class="fa fa-calendar"></i></span>
                    <input type="text" name="fromDate" id="fromDate" class="form-control date_picker lbl_move dFliter" readonly="readonly" label="From Date" value="<?php echo (isset($fromDate) && $fromDate != "") ? $fromDate : Date('d-m-Y'); ?>" />
                </div>
                <div class="form-group col-lg-6 col-md-6 col-sm-6 commargin_top">
                    <span class="date_icon"><i class="fa fa-calendar"></i></span>
                    <input type="text" name="toDate" id="toDate" class="form-control date_pickers lbl_move dFliter" readonly="readonly" label="To Date" value="<?php echo (isset($toDate) && $toDate != "") ? $toDate : Date('d-m-Y'); ?>" />
                </div>
            </div>
            <div class="col-lg-12">
                <div class="col-lg-3 padlr0">
                    <div class="radio_check">
                        <p>
                            <input type="checkbox" id="cfilter" value="filter" onchange="changeGrid()"/>
                            <label for="cfilter" class="ripple ">Conditional Filter</label>
                        </p>
                    </div>
                </div>
                <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
                    <label for="multiColumn" class="col-lg-6 col-md-6 col-sm-6 control-label txt_right">Column Chooser</label>
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        <?php
                        $arrGridColumn = array();
                        if(isset($GridColumn)) {
                            $arrGridColumn = explode(",", $GridColumn['ColumnName']);
                        } ?>
                        <select name="multiColumn[]" id="multiColumn" class="form-control selectpicker" data-size="5" multiple title="Choose Multiple Status">
                            <option value="LeadName" <?php echo (in_array('LeadName',$arrGridColumn)) ? '' :'selected'?>>Lead Name</option>
                            <option value="LeadDate"<?php echo (in_array('LeadDate',$arrGridColumn)) ? '' :'selected'?>>Lead Date</option>
                            <option value="LeadTypeName" <?php echo (in_array('LeadTypeName',$arrGridColumn)) ? '' :''?>>Lead Type</option>
                            <option value="Mobile" <?php echo (in_array('Mobile',$arrGridColumn)) ? '' :''?>>Contact No</option>
                            <option value="Projects" <?php echo (in_array('Projects',$arrGridColumn)) ? '' :''?>>Projects</option>
                            <option value="CityName" <?php echo (in_array('CityName',$arrGridColumn)) ? '' :''?>>Preffered Location</option>
                            <option value="ExecutiveName" <?php echo (in_array('UserName',$arrGridColumn)) ? '' :'selected'?>>Executive Name</option>
                            <option value="NRI" <?php echo (in_array('NRI',$arrGridColumn)) ? '' :''?>>NRI</option>
                            <option value="state" <?php echo (in_array('StatusId',$arrGridColumn)) ? '' :'selected'?>>Status</option>
                            <option value="VIP" <?php echo (in_array('VIP',$arrGridColumn)) ? '' :''?>>VIP</option>
                            <option value="CreatedBy" <?php echo (in_array('CreatedBy',$arrGridColumn)) ? '' :''?>>Created By</option>
                            <option value="SourceName" <?php echo (in_array('SourceName',$arrGridColumn)) ? '' :''?>>Source Name</option>
                            <option value="Budget" <?php echo (in_array('Budget',$arrGridColumn)) ? '' :''?>>Budget</option>
                            <option value="NextCallDate" <?php echo (in_array('NextCallDate',$arrGridColumn)) ? '' :'selected'?>>Next Followup Date</option>
                            <option value="Converted" <?php echo (in_array('Converted',$arrGridColumn)) ? '' :''?>>Converted</option>
                        </select>
                    </div>
                </div>

            </div>
        </div>

        <div class="col-lg-12 padtop10 clear">
            <div class="table-responsive m_btm30">
                <div id="dataTable"></div>
            </div>
        </div>
        <div class="right_lightbox">
            <div class="right_lightbox_close">
                <span class="right_lightbox_closeicon"><i class="fa fa-times"></i></span>
            </div>
            <div class="right_lbox_inner lead_register_rbox" id="lead_short_detail">
            </div>
        </div>
    </div>
</div>
<!--<!--Import Excel Selection Modal-->
<!--<div class="modal fade" id="importxlselmodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">-->
<!--	<div class="modal-dialog" role="document">-->
<!--		<div class="modal-content">-->
<!--			<div class="modal-header">-->
<!--				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>-->
<!--				<h1>Choose Bill Type</h1>-->
<!--			</div>-->
<!--			<div class="modal-body">-->
<!--				<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">-->
<!--					<div class="error_message"><p>please assign fields correctly...</p></div>-->
<!--					<form id="importForm" class="form-horizontal" method="post" enctype="multipart/form-data">-->
<!--						<div class="row padtop20">-->
<!--							<div class="form-group col-lg-12">-->
<!--								<select id="importField_1" name="leadName" class="single_dropdown lbl_move importExcel" style="width:100%;" label="Lead Name">-->
<!--								</select>-->
<!--							</div>-->
<!--						</div>-->
<!--						<div class="row commargin_top">-->
<!--							<div class="form-group col-lg-12">-->
<!--								<select id="importField_2" name="leadDate" class="single_dropdown lbl_move importExcel" style="width:100%;" label="Lead Date">-->
<!--								</select>-->
<!--							</div>-->
<!--						</div>-->
<!--					<!--	<div class="row commargin_top">-->
<!--							<div class="form-group col-lg-12">-->
<!--								<select id="importField_3" name="leadType" class="single_dropdown lbl_move importExcel" style="width:100%;" label="Lead Type">-->
<!--								</select>-->
<!--							</div>-->
<!--						</div>-->
<!--						<div class="row commargin_top">-->
<!--							<div class="form-group col-lg-12">-->
<!--								<select id="importField_4" name="mobile" class="single_dropdown lbl_move importExcel" style="width:100%;" label="Mobile">-->
<!--								</select>-->
<!--							</div>-->
<!--						</div>-->
<!--						<div class="row commargin_top">-->
<!--							<div class="form-group col-lg-12">-->
<!--								<select id="importField_5" name="email" class="single_dropdown lbl_move importExcel" style="width:100%;" label="Email">-->
<!--								</select>-->
<!--							</div>-->
<!--						</div>-->
<!--					</form>-->
<!--				</div>-->
<!--			</div>-->
<!--			<div class="modal-footer clear">-->
<!--				<div class="col-lg-12 savebtn_area no_border">-->
<!--					<ul>-->
<!--						<li class="save_btn float_r">-->
<!--							<a href="#" onclick="submitImportForm(); return false;" class="ripple">ok</a>-->
<!--						</li>-->
<!--					</ul>-->
<!--				</div>-->
<!--			</div>-->
<!--		</div>-->
<!--	</div>-->
<!--</div>-->
<div id="excelfieldmodal" class="modal fade" role="dialog" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h1>Lead Import Sheet - Assign Fields</h1>
            </div>
            <div class="modal-body">
                <div class="table-responsive popuptable">
                    <table class="table" width="100%" style=" margin-bottom:0px;">
                        <tbody>
                        <tr id="excelfieldTable"></tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="modal-footer"> <a href="#" class="md_cance" data-dismiss="modal" data-toggle="tooltip" title="" data-original-title="Cancel" style="position: relative; overflow: hidden;">Cancel<span class="ripple-wrapper"></span><span class="ripple-wrapper"></span></a>
                <button type="button" class="md_ok" onclick="return fileupload()" >Next</button>
            </div>
        </div>
    </div>
</div>
<div id="excelmodal" class="modal fade" role="dialog" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-lg" role="document" style="width:75%;">
        <form id="excel_model">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h1>Lead Import Sheet</h1>
                </div>
                <div class="modal-body">
                    <div id="error_data"></div>
                    <div class="table-responsive topsp">
                        <table class="table" style=" margin-bottom:0px;" id="excelTable">
                            <thead>
                            <tr>
                                <th width="15%" class="th-modal">Lead Name</th>
                                <th width="10%" class="th-modal excel-code-txt">Lead Date</th>
                                <th width="11%" class="th-modal">Executive</th>
                                <th width="15%" class="th-modal">Mobile</th>
                                <th width="15%" class="th-modal">Email Address</th>
                                <th width="10%" class="th-modal">Source</th>
                                <th width="12%" class="th-modal">Project</th>
                                <th width="10%" class="th-modal">Lead Type</th>
                                <th width="2%" class="th-modal">Action</th>
                            </tr>
                            </thead>
                            <tbody id="table_bind">

                            </tbody>
                            <input type="hidden" name="rowCount" value="0" id="rowCount" />
                            <input type="hidden" name="csrf" value="<?php echo (isset($csrf)) ? $csrf : "";?>" id="csrf" />
                            <input type="hidden" name="mode" value="validate" id="mode" />
                        </table>
                    </div>
                </div>
                <div class="modal-footer clear">
                    <a href="#" id="can_button" class="md_cance" data-dismiss="modal" data-toggle="tooltip" title="" data-original-title="Cancel" style="position: relative; overflow: hidden;">Cancel<span class="ripple-wrapper"></span><span class="ripple-wrapper"></span></a>
                    <button type="button" id="app_button" class="md_ok" onclick="return dataInsert()" >Apply</button>
                </div>
            </div>
        </form>
    </div>
</div>
<!-- PAGE SCRIPTS -->
<script>
    $(function(){
        $('.right_lightbox_close').click(function(){
            $('.right_lightbox').hide();
            if ($(window).width() >=980){
                $('.left-panel').addClass('collapsed');
                $('.l_menuicon_nav').addClass('cross');
            }
        });
    });

    $(document).ready(function() {
        $(".single_dropdown").select2({
            placeholder: "",
            allowClear: true
        });
    });
</script>
<!-- PAGE SCRIPTS -->

<script>
    var fdt=$('#fromDate').val();
    $('.date_pickers').datepicker({
        format: "dd-mm-yyyy",
        startDate: fdt,
        todayBtn: false,
        orientation: "top auto",
        autoclose: true
    });
    $(document).ready(function () {
        var LeadColumns = [];
        $.ajax({
            url:"<?php echo $this->basePath(); ?>/crm/lead/register",
            type:"post",
            data:{'fDate':$('#fromDate').val(),'tDate':$('#toDate').val()},
            async:false,
            dataType:"json",
            success:function(data, textStatus, jqXHR){
                // prepare the data
                var source =
                {
                    localdata:data,
                    dataType: "json",
                    dataFields: [
                        { name: 'LeadId', type: 'number' },
//					{ name: 'Photo', type: 'string' },
                        { name: 'LeadName', type: 'string' },
                        { name: 'LeadDate',type: 'date'},
                        { name: 'LeadTypeName', type: 'string' },
                        { name: 'Mobile', type: 'string' },
                        { name: 'CityName', type: 'string' },
                        { name: 'ExecutiveName', type: 'string' },
                        { name: 'state', type: 'string' },
                        { name: 'VIP', type: 'number' },
                        { name: 'CreatedBy', type: 'string' },
                        { name: 'Projects', type: 'string' },
                        { name: 'SourceName', type: 'string' },
                        { name: 'Budget', type: 'string' },
                        { name: 'Converted', type: 'string' },
                        { name: 'NextCallDate', type: 'date' },
                        { name: 'NRI', type: 'bool' }
                    ],
                    id: 'LeadId'
                };

                var dataAdapter = new $.jqx.dataAdapter(source);

//			var photorenderer = function (row, column, value, data) {
//				var vip = $('#dataTable').jqxGrid('getrowdata', row).VIP;
//				if(vip == 1) {
//					var vipImage = '<div class="img_star brad_50">' +
//										'<span class="glyphicon glyphicon-star txt_center"></span>' +
//									'</div>';
//				} else {
//					var vipImage = '';
//				}
//				var imgurl = $('#dataTable').jqxGrid('getrowdata', row).Photo;
//				var imgname="../"+imgurl;
//				if(imgname != '' && imgname != null) {
//					var imgur = '<?php //echo $this->basePath(); ?>///' + imgname + '';
//				} else {
//					var imgur = '<?php //echo $this->basePath(); ?>///images/avatar.jpg';
//				}
//
//				var img = '<div class="flwup_proimg ldrgstr_proimg brad_200">' + vipImage  +
//								'<img src="'+imgur+'" class="brad_200" alt="" title=""/>' +
//							'</div>';
//				return img;
//            };

                var cellclassname = function (row, column, value, data) {
                    if(data.StatusId == 1) {
                        return 'tr_hot';
                    } else if(data.StatusId == 2) {
                        return 'tr_warm';
                    } else if(data.StatusId == 3) {
                        return 'tr_cold';
                    }
                };

                var addfilter = function () {
                    var filtergroup = new $.jqx.filter();

                    var filter_or_operator = 1;
                    var filtervalue = 'Beate';
                    var filtercondition = 'contains';
                    var filter1 = filtergroup.createfilter('stringfilter', filtervalue, filtercondition);

                    filtervalue = 'Andrew';
                    filtercondition = 'starts_with';
                    var filter2 = filtergroup.createfilter('stringfilter', filtervalue, filtercondition);

                    filtergroup.addfilter(filter_or_operator, filter1);
                    filtergroup.addfilter(filter_or_operator, filter2);
                    // add the filters.
                    $("#dataTable").jqxGrid('addfilter', 'firstname', filtergroup);
                    // apply the filters.
                    $("#dataTable").jqxGrid('applyfilters');
                };

                var showhideColumns = function () {
                    $("#dataTable").jqxGrid('beginupdate');
                    $.each($('#multiColumn option'), function (i,o) {
                        if($(this).is(':selected')) {
                            $("#dataTable").jqxGrid('showcolumn', $(this).val());
                        } else {
                            $("#dataTable").jqxGrid('hidecolumn', $(this).val());
                        }
                    });
                    $("#dataTable").jqxGrid('endupdate');
                };

                $("#dataTable").jqxGrid({
                    width: '100%',
                    source: dataAdapter,
                    pageable: true,
                    selectionMode: 'singleRow',
                    pagerButtonsCount: 6,
                    rowsheight: 60,
                    autoheight:true,
                    autorowheight: true,
                    filterable: true,
                    sortable: true,
                    columnsResize: true,
                    showfilterrow: true,
                    rowDetails: true,
                    altrows: true,
                    ready: function () {
                        addfilter();
                        showhideColumns();
                    },
                    autoshowfiltericon: true,
                    rendered: function () {
                    },
                    columns: [
//					{ text: '', datafield: 'Image', width:70, cellsrenderer: photorenderer,	cellclassname: cellclassname, filterable: false },
                        { text: 'Lead Name', width:150,dataField: 'LeadName', cellclassname: cellclassname},
                        { text: 'Lead Date', filtertype: 'date', dataField: 'LeadDate',cellsformat: 'dd-MM-yyyy', cellclassname: cellclassname },
                        { text: 'Next Followup Date', filtertype: 'date', dataField: 'NextCallDate',cellsformat: 'dd-MM-yyyy', cellclassname: cellclassname },
                        { text: 'Lead Type', filtertype: 'list', dataField: 'LeadTypeName', cellclassname: cellclassname },
                        { text: 'Contact No', dataField: 'Mobile', cellclassname: cellclassname },
                        { text: 'Projects', width:220,dataField: 'Projects', cellclassname: cellclassname },
                        { text: 'Preffered Location', dataField: 'CityName', cellclassname: cellclassname },
                        { text: 'Executive Name', filtertype: 'list', dataField: 'ExecutiveName', cellclassname: cellclassname },
                        { text: 'NRI', width:50, columntype: 'checkbox', filtertype: 'bool', dataField: 'NRI', cellclassname: cellclassname },
                        { text: 'Converted', dataField: 'Converted', cellclassname: cellclassname },
                        { text: 'Status', dataField: 'state', cellclassname: cellclassname},
                        { text: 'VIP', dataField: 'VIP', cellclassname: cellclassname, width:50, columntype: 'checkbox', filtertype: 'bool' },
                        { text: 'Created By', filtertype: 'list', dataField: 'CreatedBy', cellclassname: cellclassname},
                        { text: 'Source Name', dataField: 'SourceName', cellclassname: cellclassname},
                        { text: 'Budget', dataField: 'Budget', cellclassname: cellclassname},
                        { text: 'LeadId', dataField: 'LeadId', cellclassname: cellclassname, hidden:true }
                    ]
                });

                $('#dataTable').on('cellclick', function (event){
                    // event arguments.
                    var args = event.args;
                    // row's bound index.
                    var rowBoundIndex = args.rowindex;
                    // row's visible index.
                    var rowVisibleIndex = args.visibleindex;
                    // right click.
                    var rightclick = args.rightclick;
                    // original event.
                    var ev = args.originalEvent;
                    // column index.
                    var columnindex = args.columnindex;
                    // column data field.
                    var dataField = args.datafield;
                    // cell value
                    var value = args.value;
                    var data = $("#dataTable").jqxGrid("getrowdata", rowBoundIndex);
                    if(dataField != '') {
                        $.ajax({
                            url:"<?php echo $this->basePath(); ?>/crm/lead/details",
                            type:"post",
                            //async:false,
                            data:"cid="+data.LeadId,
                            success:function(data, textStatus, jqXHR){
                                $('#lead_short_detail').html(data);
                                $('.right_lightbox').show();
                                $('.left-panel').removeClass('collapsed');
                                $('.l_menuicon_nav').removeClass('cross');
                            },
                            error:function(jqXHR, textStatus, errorThrown){
                                //$('.right_lightbox').hide();
                            }
                        });
                    }
                });

                /* $('#events').jqxPanel({ width: 300, height: 80});

                 $("#dataTable").on("filter", function (event) {
                 $("#events").jqxPanel('clearcontent');
                 var filterinfo = $("#dataTable").jqxGrid('getfilterinformation');

                 var eventData = "Triggered 'filter' event";
                 for (i = 0; i < filterinfo.length; i++) {
                 var eventData = "Filter Column: " + filterinfo[i].filtercolumntext;
                 $('#events').jqxPanel('prepend', '<div style="margin-top: 5px;">' + eventData + '</div>');
                 }
                 });

                 $('#clearfilteringbutton').jqxButton({ height: 25});
                 $('#filterbackground').jqxCheckBox({ checked: true, height: 25});
                 $('#filtericons').jqxCheckBox({ checked: false, height: 25});
                 // clear the filtering.
                 $('#clearfilteringbutton').click(function () {
                 $("#dataTable").jqxGrid('clearfilters');
                 });
                 // show/hide filter background
                 $('#filterbackground').on('change', function (event) {
                 $("#dataTable").jqxGrid({ showfiltercolumnbackground: event.args.checked });
                 });
                 // show/hide filter icons
                 $('#filtericons').on('change', function (event) {
                 $("#dataTable").jqxGrid({ autoshowfiltericon: !event.args.checked });
                 });*/
            },
            error:function(jqXHR, textStatus, errorThrown){
            }
        });

    });

    $('#multiColumn').on('change', function () {
        var unSelected = [];
        var Selected = [];
        $("#dataTable").jqxGrid('beginupdate');
        $.each($('#multiColumn option'), function (i,o) {
            if($(this).is(':selected')) {
                Selected.push($(this).val());
                $("#dataTable").jqxGrid('showcolumn', $(this).val());
            } else {
                unSelected.push($(this).val());
                $("#dataTable").jqxGrid('hidecolumn', $(this).val());
            }
        });
        $("#dataTable").jqxGrid('endupdate');

        $.ajax({
            url:"<?php echo $this->basePath(); ?>/crm/lead/register",
            type:"post",
            data:{'unCheckedColumnNames':unSelected.toString(),'type':'updateColumn'},
            success:function(data, textStatus, jqXHR){
            },
            error:function(jqXHR, textStatus, errorThrown){
            }
        });
    });

    function changeGrid()
    {
        if($("#cfilter").is(':checked')) {
            $("#dataTable").jqxGrid({
                showfilterrow: false
            });
            $("#dataTable .jqx-grid-header").css("cssText", "height: 40px !important;");
        } else {
            $("#dataTable").jqxGrid({
                showfilterrow: true
            });

        }
    }
    //new change
    var arrayField =[];
    arrayField = [{ data :1, value: 'LeadName' },
        { data :2, value: 'LeadDate' },
        { data :3, value: 'Executive' },
        { data :4, value: 'Mobile' },
        { data :5, value: 'EmailAddress' },
        { data :6, value: 'Source' },
        { data :7, value: 'ProjectName' },
        { data :8, value: 'LeadType' }
    ];
    var selectCol=[];
    var arrayFieldR = arrayField;
    function getExcelField(x) {
        $('#rowCount').val(0);
        $('#can_button').html('Cancel').attr('data-original-title','Cancel');
        $('#app_button').html('Apply');
        $('#error_data').html('');
        formData = new FormData();
        formData.append('file', $('#myfile').prop("files")[0]);
        formData.append('mode','title');
        formData.append('csrf', "<?php echo isset($csrf)?$csrf:''; ?>");

        $.ajax({
            url: getBaseURL() +"crm/lead/get-lead-field-data",
            async: false,
            dataType: 'script',
            cache: false,
            contentType: false,
            processData: false,
            data: formData,
            type: 'post',
            success: function(data,status, xhr) {
                var obj = jQuery.parseJSON(data);
                $("#excelfieldTable").find("th").remove();
                $("#excelfieldTable").find("td").remove();

                var sStr="Select Field";
                var data = "<option value=''></option>";
                for (var i = 0; i < obj.length; i++) {
                    var fieldName = $.trim(obj[i]['Field']);
                    if (fieldName != "") {
                        data +="<option value='"+ parseInt(i+1) +"'>"+fieldName+"</option>";
                    }
                }

                $.each(arrayFieldR,function(i,o) {
                    $("#excelfieldTable").append('<tr><th width="20%"><input id="efield_' + i + '" class="text-reon text-right" type="text" value="'+ o.value+'" style="background: transparent;"/></th><td width="70"><select id="field_' + i + '" class="single_dropdown lbl_move data_bind" style="width:100%;" label="' + sStr + '"></select></td></tr>');
                    $('#efield_' + i).prop('readonly', true);
                    $('#field_' + i).html(data);
                });
                $(".single_dropdown").select2({
                    placeholder: "",
                    allowClear: true
                });
                //bindexcelFieldComplete();
                $("#excelfieldmodal").modal('show');
            },
            error: function(xhr, status, errorThrown) {
                if (xhr.status == 400)
                    alert(xhr.responseText);
                else
                    alert(errorThrown);
            }
        });
        clearInputFile($('#myfile'));
    }

    function clearInputFile(file){
        var f = file[0];
        if(f.value){
            try{
                f.value = '';
            }catch(err){ }
            if(f.value){
                var form = document.createElement('form'),
                    parentNode = f.parentNode, ref = f.nextSibling;
                form.appendChild(f);
                form.reset();
                parentNode.insertBefore(f,ref);
            }
        }
    }
    function fileupload() {
        var isValid=true;
        $.each(arrayField,function(e,f){
            if($.trim($('#field_'+e).val())=="") {
                var check = parseInt(e)+1;
                if(check==1 || check==4 || check==5){
                    alert('Map the '+f.value);
                    isValid=false;
                }
            }

        });
        if (isValid==false) { return;}
        $("body").removeClass('modal-open');
        $("#excelfieldmodal").modal('hide');
        var arrHeader =[];
        for (var i = 0; i < $("#excelfieldTable").find("th").length; i++) {
            if($('#field_'+i).val()!="") {
                arrHeader.push({efield: $('#field_' + i +' option:selected').text(), field: $('#efield_' + i).val()});
            }
        }
        arrHeader =  JSON.stringify(arrHeader);
        formData.append('arrHeader', arrHeader);
        formData.append('mode', 'body');
        formData.append('csrf', "<?php echo isset($csrf)?$csrf:''; ?>");
        $.ajax({
            url: getBaseURL() +"crm/lead/get-lead-field-data",
            async: false,
            dataType: 'script',
            cache: false,
            contentType: false,
            processData: false,
            data:  formData,
            type: 'post',
            success: function(data,status, xhr) {
                var obj = jQuery.parseJSON(data);
                var template = $('#excel_bind').html();
                $('#table_bind').html('');
                if(obj.length>0) {
                    for (var j = 0; j < obj.length; j++) {
                        $('#table_bind').append(template.replace(/__/g, '_' + j));
                        $('#rowCount').val(j);
                        if (obj[j].Valid == true) {
                            $("#excellead_" + j).val(isNullCheck(obj[j].LeadName, 'string'));
                            $("#exceldate_" + j).val(isNullCheck(obj[j].LeadDate, 'string'));
                            $("#excelexecutive_" + j).val(isNullCheck(obj[j].Executive, 'string'));
                            $("#excelmobile_" + j).val(isNullCheck(obj[j].Mobile, 'number'));
                            $("#excelemail_" + j).val(isNullCheck(obj[j].EmailAddress, 'string'));
                            $("#excelsource_" + j).val(isNullCheck(obj[j].Source, 'string'));
                            $("#excelproject_" + j).val(isNullCheck(obj[j].ProjectName, 'string'));
                            $("#excelleadtype_" + j).val(isNullCheck(obj[j].LeadType, 'string'));
                        }

                    }
                    $("#excelmodal").modal('show');
                    setTimeout(function() { $("body").addClass('modal-open');}, 200);

                } else {
                    alert("Contains No Data");
                }
            },
            error: function(xhr, status, errorThrown) {
                if (xhr.status == 400) {
                    alert(xhr.responseText);
                }
                else {
                    alert('Invalid Excel allocation');
                }
            }
        });
        clearInputFile($('#myfile'));
    }
    $("#excelExport").click(function () {
        $("#dataTable").jqxGrid('exportdata', 'xls', 'jqxGrid');
    });

    function dataInsert() {
        //$("#excelmodal").modal('hide');
        $("body").removeClass('modal-open');

        $.ajax({
            url: getBaseURL() + 'crm/lead/get-lead-field-data',
            type: 'POST',
            data: $('#excel_model').serialize(),
            success: function (data, textStatus, jqXHR) {
                var obj = jQuery.parseJSON(data);
                var template = $('#excel_bind').html();
                if(obj.length>0) {
                    $('#table_bind').html('');
                    $('#error_data').html('Error Data:');
                    for (var j = 0; j < obj.length; j++) {
                        $('#table_bind').append(template.replace(/__/g, '_' + j));
                        removeError($("#excellead_" + j));
                        removeError($("#exceldate_" + j));
                        removeError($("#excelexecutive_" + j));
                        removeError($("#excelmobile_" + j));
                        removeError($("#excelemail_" + j));
                        removeError($("#excelsource_" + j));
                        removeError($("#excelproject_" + j));
                        removeError($("#excelleadtype_" + j));
                        $("#excellead_" + j).val(isNullCheck(obj[j].LeadName[0], 'string'));
                        $("#exceldate_" + j).val(isNullCheck(obj[j].LeadDate[0], 'string'));
                        $("#excelexecutive_" + j).val(isNullCheck(obj[j].Executive[0], 'string'));
                        $("#excelmobile_" + j).val(isNullCheck(obj[j].Mobile[0], 'string'));
                        $("#excelemail_" + j).val(isNullCheck(obj[j].EmailAddress[0], 'string'));
                        $("#excelsource_" + j).val(isNullCheck(obj[j].Source[0], 'string'));
                        $("#excelproject_" + j).val(isNullCheck(obj[j].ProjectName[0], 'string'));
                        $("#excelleadtype_" + j).val(isNullCheck(obj[j].LeadType[0], 'string'));

                        if(obj[j].LeadName[1]==1) {
                            showError($("#excellead_" + j),'');
                        }
                        if(obj[j].LeadDate[1]==1) {
                            showError($("#exceldate_" + j),'');
                        }
                        if(obj[j].Executive[1]==1) {
                            showError($("#excelexecutive_" + j),'');
                        }
                        if(obj[j].Mobile[1]==1) {
                            showError($("#excelmobile_" + j),'');
                        }
                        if(obj[j].EmailAddress[1]==1) {
                            showError($("#excelemail_" + j),'');
                        }
                        if(obj[j].Source[1]==1) {
                            showError($("#excelsource_" + j),'');
                        }
                        if(obj[j].ProjectName[1]==1) {
                            showError($("#excelproject_" + j),'');
                        }
                        if(obj[j].LeadType[1]==1) {
                            showError($("#excelleadtype_" + j),'');
                        }

                    }
                    $('#rowCount').val(parseInt(obj.length)-1);
                    $('#can_button').html('Discard').attr('data-original-title','Discard');
                    $('#app_button').html('Correct');
                    $("#excelmodal").modal('show');
                    setTimeout(function() { $("body").addClass('modal-open');}, 200);

                } else {
                    alert("Lead Import Successful");
                    $('#table_bind').html('');
                    $("#excelmodal").modal('hide');
					location.reload();
                }

            },
            error: function (jqXHR, textStatus, errorThrown) {
                if (jqXHR.status == 400)
                    alert(jqXHR.responseText);
                else
                    alert("Request Failed");
            }
        });
    }
    function deleteRow(val){
        var rId = $(val).attr('id');
        rId = rId.split('_')[1];
        if (confirm('Do you want to Delete')) {
            $('#excelrowid_'+rId).remove();
        }
    }
    $(document).on("change",".dFliter",function(){
        var fDate=$("#fromDate").val();
        var tDate=$("#toDate").val();
        window.location.replace(getBaseURL() + "crm/lead/register/0/" + fDate + "/" + tDate);
    });
</script>