<style type="text/css">
    #treeGrid .jqx-grid-header 	{
        height:75px !important;
    }
</style>

<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
        <div class="col-lg-12">
            <div class="col-lg-12 padlr0">
            	<h1>Unit Transfer</h1>
            </div>
            <div class="col-lg-12 padlr0 tmss commargin_top clear">
                <div class="table-responsive clear">
                    <div id="treeGrid"> </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(function() {
        var $treeGrid = $('#treeGrid');
        var source = {
            localdata:<?php echo (isset($jsonUnitTrans))?$jsonUnitTrans:'[]'; ?>,
            dataType: "json",
            dataFields: [
                { name: 'RefNo', type: 'string' },
                { name: 'RefDate', type: "date", format: 'dd/MM/yyyy' },
                { name: 'OldUnitName', type: 'string' },
                { name: 'NewUnitName', type: 'string' },
                { name: 'BookingId', type: 'number' },
                { name: 'LeadName', type: 'string' }
            ],
            id: 'TransferId'
        };

        var dataAdapter = new $.jqx.dataAdapter(source);

        $treeGrid.jqxGrid({
            width: '100%',
            pageable: true,
            selectionMode: 'singleRow',
            pagerButtonsCount: 6,
            autoheight:true,
            //rowsheight:60,
            autorowheight: true,
            filterable: true,
            sortable: true,
            //filtermode: 'advanced',
            columnsResize: true,
            showfilterrow: true,
            ready:function(){
                var localizationobj = {};
                localizationobj.emptydatastring = "No Unit Transfers found!";
                $treeGrid.jqxGrid('localizestrings', localizationobj);
            },
            source:dataAdapter,
            columns: [
                { text: 'TransferId', dataField: 'TransferId',hidden: true, filterable: false},
                { text: 'RefNo', dataField: 'RefNo',width:'20%'},
                { text: 'RefDate', filtertype: 'date', cellsformat: 'dd-MM-yyyy', dataField: 'RefDate',width:'20%'},
                { text: 'Buyer Name', dataField: 'LeadName',width:'20%'},
                { text: 'Old UnitName', dataField: 'OldUnitName',width:'20%'},
                { text: 'New UnitName', dataField: 'NewUnitName',width:'20%'},
                
            ]
        });
    });
</script>