<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/workorder.css';?>"/>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/select2.full.min.js"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/select2.min.css" />
<style>
    .form-control {
        box-shadow:none !important
    }
    .panel {
        border-radius:0px !important;
    }
    .panel-info {
        border:none;
        border-top:none;
    }
    #mainWrapper {
        display: none;
    }
    .form-control {
        box-shadow:none !important;
    }
    .opt-listed ul li p{ height:30px !important; padding-top:0px !important;}
</style>

<div class="content_wrapper padlr0">
    <form  id="formWrapper"  method="post">
        <input type="hidden" name="campaignid" id="campaignid" value="<?php echo (isset($campaignid)) ? $campaignid  : 0; ?>"/>
        <input type="hidden" name="mode" id="mode" value="<?php echo (isset($mode)) ? $mode  : 'add'; ?>"/>
        <div class="container-fluid padlr0">
            <div class="col-lg-12">
                <div align="center" class="col-lg-12">
                    <h1 data-bsfhead="Campaign Entry" >Campaign Entry</h1>
                </div>
                
                <div class="col-lg-12 clear padlr0">
                    <div class="col-lg-5 col-md-5 col-sm-5 col-xs-6">
                        <div class="col-lg-offset-4">
                            <label for="campaignNo" class="bk_lbl bk_lbl_inpt splcharc">Campaign No <span class="colon_r">:</span></label>
                            <input type="text" class="bk_lbl_inpt inputbg_ef bk_inpt1 splcharc" name="campaignNo" data-bsfshare="campaignNo" id="campaignNo" onchange="" value="<?php  if ($campaignid!=0) { echo (isset($campaign)) ? $campaign['CampaignNo'] : '';}  else { echo $svNo; } ?>" <?php if ($genType==true) { ?> readonly <?php } ?> />
                        </div>
                    </div>
                    <div class="col-lg-7 col-md-7 col-sm-7 col-xs-6 ">
                        <div class="col-lg-offset-4">
                        	<div class="col-lg-12">
                            <label for="campaigndate" class="bk_lbl bk_lbl_inpt"><span class="bkspan_calendar"><i class="fa fa-calendar-o"></i></span> Campaign Date <span class="colon_r">:</span></label>
                            <input type="text" class="date_picker bk_lbl_inpt no_bg bk_inpt inputbg_ef" name="campaigndate" data-bsfshare="campaigndate" readonly id="campaigndate" onchange="validateDate(this);" value="<?php echo (isset($campaign)) ? $campaign['CampaignDate'] : date('d-m-Y');?>" />
                           </div>
                        </div>
                    </div>
                </div>
                
                <div class="col-lg-12 padlr0">
                    <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-12 prt-next">
                        <div id="level-1" class="col-lg-6 col-lg-offset-3 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 top-next">
                            <div class="form-horizontal">
                                <div class="row">
                                    <div class="form-group lgroup1 commargin_ttop_20">
                                        <input type="text" name="campaignName" data-bsfshare="Campaign Name" id="campaignName" class="form-control lbl_move" label="What is the Campaign Name?" value="<?php echo (isset($campaign)) ? $campaign['CampaignName'] : '';?>"/>
                                        <input type="hidden" name="campaignNo" id="campaignNo" value="<?php echo (isset($campaign)) ? $campaign['CampaignNo'] : '';?>"/>
                                    </div>
                                    <div class="form-group lgroup1">
                                        <strong class="new-pg" id="newcategoryName">New</strong>
                                        <input type="text" name="categoryName" data-bsfshare="Category Name" id="categoryName" class="form-control lbl_move" label="What is the Campaign Category?" value="<?php echo (isset($campaign)) ? $campaign['OpportunityName'] : '';?>"/>
                                        <input type="hidden" name="categoryId" id="categoryId" value="<?php echo (isset($campaign)) ? $campaign['OpportunityId'] : '';?>"/>
                                    </div>
                                    <!--                                    <div class="form-group lgroup1">-->
                                    <!--                                        <select name="periority" id="periority" class="form-control single_dropdown lbl_move apprnc" style="width:100%;" label="What is the Periority?">-->
                                    <!--                                            <option></option>-->
                                    <!--                                            <option value="H" --><?php //echo (isset($campaign) && $campaign['Periority'] == 'H') ? 'selected' : '';?><!--High</option>-->
                                    <!--                                            <option value="M" --><?php //echo (isset($campaign) && $campaign['Periority'] == 'M') ? 'selected' : '';?><!--Medium</option>-->
                                    <!--                                            <option value="L" --><?php //echo (isset($campaign) && $campaign['Periority'] == 'L') ? 'selected' : '';?><!--Low</option>-->
                                    <!--                                        </select>-->
                                    <!--                                    </div>-->
                                    <div class="form-group lgroup1">
                                        <input type="text" name="sourceName" data-bsfshare="Source Name" id="sourceName" class="form-control lbl_move" label="What is the Promoting Source?" value="<?php echo (isset($campaign)) ? $campaign['SourceName'] : '';?>"/>
                                    </div>
                                    <div class="form-group lgroup1">
                                        <select name="externalAgency" data-bsfshare="External Agency" id="externalAgency" class="form-control single_dropdown lbl_move apprnc" style="width:100%;" label="Executed by External Agency?">
                                            <option></option>
                                            <option value="Y" <?php echo (isset($campaign) && $campaign['ExternalAgency'] == '1') ? 'selected' : '';?>>Yes</option>
                                            <option value="N" <?php echo (isset($campaign) && $campaign['ExternalAgency'] == '0') ? 'selected' : '';?>>No</option>
                                        </select>
                                    </div>
                                    <div class="form-group" id="dserviceProviderName">
                                        <input type="text" name="serviceProviderName" data-bsfshare="ServiceProviderName" id="serviceProviderName" class="form-control lbl_move" label="Who is the Service Provider?" value="<?php echo (isset($campaign)) ? $campaign['ServiceProviderName'] : '';?>"/>
                                    </div>
                                    <div class="lgroup1" id ="dcost">
                                        <div>
                                            <input type="text" name="budget" data-bsfshare="budget" id="budget" class="form-control lbl_move text-right seperate" label="What is the Campaign Cost?" value="<?php echo (isset($campaign)) ? $campaign['CampaignCost'] : '';?>" readonly maxlength="18" onblur="return FormatNum(this, 3, true)"/>
                                        </div>

                                        <div class="table-responsive clear commargin_bottom" id="dtable" style="display: none">
                                            <table id="budgettable" class="table table-hover clear" style="margin-bottom: 0px ! important;">
                                                <thead>
                                                <tr>
                                                    <th>Project</th>
                                                    <th>Campaign Cost</th>
                                                    <th></th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                <?php $i=1; if(isset($campaigntrans)):
                                                    foreach($campaigntrans as $trans): ?>
                                                        <tr>
                                                            <td><input class="parent_text" type="text" name="budgetprojectName_<?php echo $i; ?>" id="budgetprojectName_<?php echo $i; ?>" value="<?php echo $trans['ProjectName'];?>" onchange="addProjectRow(this)" onfocus="return checkProjectFocus(this.id)" onblur="checkProjectFound(this.id)" />
                                                                <input type="hidden" name="projectId_<?php echo $i; ?>" id="projectId_<?php echo $i; ?>" value="<?php echo $trans['ProjectId'];?>"/>
                                                                <input type="hidden" name="overallBudget_<?php echo $i; ?>" id="overallBudget_<?php echo $i; ?>" value="<?php echo $trans['BalanceBudget']; ?>" onblur="return FormatNum(this, 3, true)"/>
                                                            <td><input type="text" class="parent_text text-right"  name="pbudget_<?php echo $i; ?>" id="pbudget_<?php echo $i; ?>"  value="<?php echo $trans['Amount'];?>" onfocus="checkProjectFound(this.id)" onchange="addProjectRow(this)" onblur="return FormatNum(this, 3, true)"  maxlength="18" readonly></td>
                                                            <td width="1%" class="action_btns_td"><ul class="action_btns">
                                                                    <li style="float:left;"> <a class="projectDeleteTr_<?php echo $i; ?>" href="#"  onclick="deleteProjectRow(this, event);"> <span data-toggle="tooltip" data-placement="right" data-original-title="Delete"><i class="fa fa-trash-o"></i></span> </a> </li>
                                                                </ul></td>
                                                        </tr>
                                                        <?php $i=$i+1; endforeach;?>
                                                <?php endif; ?>
                                                <tr>
                                                    <td><input class="parent_text" type="text" name="budgetprojectName_<?php echo $i; ?>" id="budgetprojectName_<?php echo $i; ?>" value=""  onchange="addProjectRow(this)" onfocus="return checkProjectFocus(this.id)" onblur="checkProjectFound(this.id)"/>
                                                        <input type="hidden" name="projectId_<?php echo $i; ?>" id="projectId_<?php echo $i; ?>" value="0"/>
                                                        <input type="hidden" name="overallBudget_<?php echo $i; ?>" id="overallBudget_<?php echo $i; ?>" value="0"/>

                                                    <td><input type="text" class="parent_text text-right"  name="pbudget_<?php echo $i; ?>" id="pbudget_<?php echo $i; ?>" value="0"  onfocus="checkProjectFound(this.id)" onchange="addProjectRow(this)"  onblur="return FormatNum(this, 3, true)"  maxlength="18" readonly></td>
                                                    <td width="1%" class="action_btns_td"><ul class="action_btns">
                                                            <li style="float:left;"> <a class="projectDeleteTr_<?php echo $i; ?>" href="#"  onclick="deleteProjectRow(this, event);"> <span data-toggle="tooltip" data-placement="right" data-original-title="Delete"><i class="fa fa-trash-o"></i></span> </a> </li>
                                                        </ul></td>
                                                </tr>
                                                </tbody>
                                            </table>
                                            <input type="hidden" name="projectrowid" id="projectrowid" value="<?php echo $i;?>"/>
                                        </div>
                                    </div>
                                    <div class="next-bt commargin_ttop_20"><a href="#" id="show-next-level" class="pull-right">Next <i class="fa fa-chevron-circle-right"></i></a></div>
                                    <?php if(isset($campaign)) {?>
                                        <div class="back-bt"><a href="<?php echo $this->basePath(); ?>/crm/campaign/register" id="back-bttn" class="pull-left"><i class="fa fa-chevron-circle-left"></i> Back</a></div>
                                    <?php } ?>
                                </div>
                            </div>
                        </div>

                        <div id="level-2" class="col-sm-6 col-sm-offset-3 top-next hide">
                            <div class="form-horizontal">
                                <div class="row">
                                    <div class="form-group lgroup2">
                                        <select name="multiTimes" id="multiTimes" class="form-control single_dropdown lbl_move apprnc" style="width:100%;" label="To be Executed by  Multiple times?">
                                            <option></option>
                                            <option value="Y" <?php echo (isset($campaign) && $campaign['MultiTimes'] == '1') ? 'selected' : '';?>>Yes</option>
                                            <option value="N" <?php echo (isset($campaign) && $campaign['MultiTimes'] == '0') ? 'selected' : '';?>>No</option>
                                        </select>
                                    </div>
                                    <div class="form-group lgroup2">
                                        <input type="text" name="startDate" data-bsfshare="Start Date" id="startDate" class="form-control date_picker lbl_move" readonly="readonly" label="Start Date" onchange="validateDate(this)"  value="<?php echo (isset($campaign)) ? $campaign['StartDate'] : date('d-m-Y');?>"/>
                                    </div>
                                    <div class="form-group lgroup2">
                                        <input type="text" name="endDate" data-bsfshare="End Date" id="endDate" class="form-control date_picker lbl_move" readonly="readonly" label="End Date" onchange="validateDate(this)"  value="<?php echo (isset($campaign)) ? $campaign['EndDate'] : date('d-m-Y');?>"/>
                                    </div>
                                    <div class="form-group" id="dplan">
                                        <div>
                                            <table>
                                                <tr>
                                                    <td  colspan="3" class="commargin_bottom"> <label class="placeholder commargin_bottom" style="font-size:15px !important;">What is the Plan of Execution?</label> </td>
                                                </tr>
                                                <tr>
                                                    <td style="width:37%;"> <input type="text" name="noOfTimes" id="noOfTimes" class="form-control" value="<?php echo (isset($campaign)) ? $campaign['NoOfTimes'] : '';?>" onblur="return FormatNum(this, 0)" onkeypress="return isNumberKey(event,this)"/> </td>
                                                    <td> <label class="placeholder"> &nbsp; Time(s) </label> </td>
                                                    <td> <select name="timesPer" style="width:100%;" id="timesPer" class="form-control single_dropdown apprnc">
                                                            <option></option>
                                                            <option value="H" <?php echo (isset($campaign) && $campaign['TimesPer'] == 'H') ? 'selected' : '';?>>Per Hour</option>
                                                            <option value="D" <?php echo (isset($campaign) && $campaign['TimesPer'] == 'D') ? 'selected' : '';?>>Per Day</option>
                                                            <option value="W" <?php echo (isset($campaign) && $campaign['TimesPer'] == 'W') ? 'selected' : '';?>>Per Week</option>
                                                            <option value="M" <?php echo (isset($campaign) && $campaign['TimesPer'] == 'M') ? 'selected' : '';?>>Per Month</option>
                                                        </select>
                                                    </td>
                                                </tr>
                                            </table>
                                        </div>
                                    </div>
                                    <div class="form-group lgroup2">
                                        <input type="text" name="lead" data-bsfshare="Lead" id="lead" class="form-control lbl_move text-left special" label="How many No of Leads Expected?" value="<?php echo (isset($campaign)) ? $campaign['ExpectedLeads'] : '';?>"  maxlength="10"/>
                                    </div>
                                    <div class="form-group lgroup2">
                                        <input type="text" name="income" data-bsfshare="Income" id="income" class="form-control lbl_move text-left special seperate" label="What is the Expected Income?" value="<?php echo (isset($campaign)) ? $campaign['ExpectedIncome'] : '';?>" onblur="return FormatNum(this, 3, true)"  maxlength="10"/>
                                    </div>
                                    <div class="form-group lgroup2">
                                        <input type="text" name="ContactPerson" data-bsfshare="Contact Person" id="ContactPerson" class="form-control lbl_move" label="Contact Person" value="<?php echo (isset($campaign)) ? $campaign['ContactPerson'] : '';?>"/>
                                    </div>
                                    <div class="form-group lgroup2">
                                        <input type="text" name="ContactNo" data-bsfshare="Contact No" id="ContactNo" class="form-control lbl_move text-left special" label="Contact Number" value="<?php echo (isset($campaign)) ? $campaign['ContactNo'] : '';?>" onKeyPress="return isNumberKey(event)"  maxlength="10" />
                                    </div>
                                    <div class="form-group lgroup2">
                                        <input type="text" name="callno" data-bsfshare="CallNo" id="phoneno" class="form-control lbl_move text-left special" label="What is Campaign Contact No?" value="<?php echo (isset($campaign)) ? $campaign['CampaignCallNo'] : '';?>"  onKeyPress="return isNumberKey(event)" maxlength="10"/>
                                    </div>
                                    <div class="form-group lgroup2">
                                        <select name="discountRequired" onchange="showDiscount()" data-bsfshare="Discount Required" id="discountRequired" class="form-control single_dropdown lbl_move apprnc" style="width:100%;" label="Any Discount Required?">
                                            <option></option>
                                            <option value="Y" <?php echo (isset($campaign) && $campaign['DiscountRequired'] == '1') ? 'selected' : '';?> >Yes</option>
                                            <option value="N" <?php echo (isset($campaign) && $campaign['DiscountRequired'] == '0') ? 'selected' : '';?> >No</option>
                                        </select>
                                    </div>
                                    <div class="form-group" id="divDiscount" style="display: none;">
                                        <div id="discount-type-wrapper" class="form-group">
                                            <select id="discount_type" name="discount_type" class="form-control single_dropdown lbl_move plan_disabled" onchange="showDiscountType()"
                                                    label="Select Discount Type" style="width:100%;" >
                                                <option value=""> </option>
                                                <option value="R" <?php echo (isset($campaign) && $campaign['DiscountType'] == 'R') ? 'selected' : '';?>  >Rate/Sq.ft</option>
                                                <option value="L" <?php echo (isset($campaign) && $campaign['DiscountType'] == 'L') ? 'selected' : '';?>  >Lumpsum</option>
                                            </select>
                                        </div>
                                        <div class="form-group" id="divrate" style="display: none;">
                                            <input type="text" name="discountrate" data-bsfshare="Rate" id="discountrate" class="form-control lbl_move text-left special" label="Dicount Rate" value="<?php echo (isset($campaign)) ? $campaign['DiscountRate'] : '';?>"  onKeyPress="return isNumberKey(event)" maxlength="10"/>
                                        </div>
                                        <div class="form-group" id="divamount" style="display: none;">
                                            <input type="text" name="discountAmount" data-bsfshare="Discount Amount" id="discountAmount" class="form-control lbl_move text-left special" label="Discount Amount" value="<?php echo (isset($campaign)) ? $campaign['DiscountAmount'] : '';?>"  onKeyPress="return isNumberKey(event)" maxlength="10"/>
                                        </div>
                                        <div class="form-group" id="diveffectiveFrom" style="display: none;">
                                            <input type="text" placeholder="DD-MM-YYYY" name="discountFrom" data-bsfshare="Discount Effective From Date" id="discountFrom" class="date_picker form-control lbl_move text-left special" label="Discount Effective From Date" value="<?php echo (isset($campaign)) ? $campaign['DiscountFrom'] : date('d-m-Y');?>" readonly/>
                                        </div>
                                        <div class="form-group" id="diveffectiveTo" style="display: none;">
                                            <input type="text" placeholder="DD-MM-YYYY" name="discountTo" data-bsfshare="Discount Effective To Date" id="discountTo" class="date_picker form-control lbl_move text-left special" label="Discount Effective To Date" value="<?php echo (isset($campaign)) ? $campaign['DiscountTo'] : date('d-m-Y');?>" readonly/>
                                        </div>
                                    </div>

                                    <div class="form-group lgroup2">
                                        <textarea class="form-control lbl_move" label="Remarks" name="remarks" data-bsfshare="Remarks" maxlength="255" id="remarks"><?php echo (isset($campaign)) ? $campaign['Remarks'] : '';?></textarea>
                                    </div>
                                    <!--                                  <!--  <div class="form-group lgroup2">
                                    <!--                                        <select name="status" id="status" class="form-control single_dropdown lbl_move apprnc" style="width:100%;" label="What is Current Status?">-->
                                    <!--                                            <option></option>
                                    <!--                                            <option value="A" --><?php //echo (isset($campaign) && $campaign['Status'] == 'A') ? 'selected' : '';?><!--Active</option>-->
                                    <!--                                            <option value="D" --><?php //echo (isset($campaign) && $campaign['Status'] == 'D') ? 'selected' : '';?><!--Deactive</option>-->
                                    <!--                                        </select>
                                    <!--                                    </div>-->

                                    <div class="back-bt"><a href="#" id="back-btn" class="pull-left"><i class="fa fa-chevron-circle-left"></i> Back</a></div>
                                    <div align="center" class="col-lg-12 commargin_top commargin_bottom" id="divsubmit" >
                                        <div class="save_btn" id="savebt"><a href="#" onclick="submitCampaign(); return false;">Submit <i class="ripple"></i></a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <table id="dummy-project" style="display: none;">
                            <tbody>
                            <td><input class="parent_text" type="text" name="budgetprojectName__1" id="budgetprojectName__1" value="" onchange="addProjectRow(this)" onfocus="return checkProjectFocus(this.id)" onblur="checkProjectFound(this.id)"/>
                                <input type="hidden" name="projectId__1" id="projectId__1" value="0"/>
                                <input type="hidden" name="overallBudget__1" id="overallBudget__1" value="0"/>
                            <td><input type="text" class="parent_text text-right"  name="pbudget__1" id="pbudget__1" value="0"  onfocus="checkProjectFound(this.id)" onchange="addProjectRow(this)" onblur="return FormatNum(this, 3, true)"   maxlength="18" readonly></td>
                            <td width="1%" class="action_btns_td"><ul class="action_btns">
                                    <li style="float:left;"> <a class="projectDeleteTr__1" href="#"  onclick="deleteProjectRow(this, event);"> <span data-toggle="tooltip" data-placement="right" data-original-title="Delete"><i class="fa fa-trash-o"></i></span> </a> </li>
                                </ul></td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<div id="msgBox" class="modal fade" role="dialog">
    <div class="modal-dialog ">
        <div class="modal-content">
            <div class="modal-header">
                <h1 id="myModalLabel">Alert Message</h1>
            </div>
            <div class="modal-body modal_body_min_h100">
                <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">
                    <div class="success_box animated fadeIn">
                        <h5 id="alertMsg" class="txt_center animated fadeInDown clear">

                        </h5>
                    </div>
                </div>
            </div>
            <div class="modal-footer clear">
                <div class="col-lg-12 savebtn_area no_border">
                    <ul>
                        <li class="save_btn float_r">
                            <a href="javascript:void(0);" class="ripple saves_ok" onclick="return closePop();">Ok</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    var arr_category = <?php echo (isset($categoryList)) ? json_encode($categoryList) : '[]';?>,
        projectList = <?php echo (isset($projectList)) ? json_encode($projectList) : '[]';?>,
        arr_project =projectList;
    $categoryName = $('#categoryName'),
        $categoryId = $('#categoryId');
    $level1 = $('#level-1'),
        $level2 = $('#level-2'),
        $showNextLevelBtn = $('#show-next-level'),
        $categoryName .autocomplete({
            lookup: arr_category,
            //showNoSuggestionNotice: false,
            lookupFilter: function (suggestion, originalQuery, queryLowerCase) {
                if (queryLowerCase == '*') {
                    return suggestion.value;
                } else {
                    var re = new RegExp($.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
                    return re.test(suggestion.value);
                }
            }, onSelect: function (suggestion) {
                if (suggestion) {
                    $categoryId.val(suggestion.data);
                    //$(this).removeClass('error');
                    $('#newcategoryName').hide();
                }
            }, onSearchStart: function (suggestion) {
                $categoryId.val(0);
            }, onSearchComplete: function (query, suggestions) {
                if (!suggestions.length) {
                    $categoryId.val(0);
                    //$(this).addClass('error');
                    $('#newcategoryName').show();
                    $categoryId.val('new');
                } else {
                    //$(this).removeClass('error');
                    $('#newcategoryName').hide();
                }
            }
        });

    $('input, select, textarea').on('focus', function() {
        var that = $(this);
        $('html, body').animate({
            scrollTop: that.offset().top + that.height() / 2 - $(window).height() / 2
        }, 2000);
    });

    $('input, select, textarea').on('change', function() {
        entryShow();
        entryShow2();
    });

    $(function () {
        bindProjectAutoComplete();
        bindShowNextLevel();
        bindBackBtn();
        entryShow();
        entryShow2();
        $(document).keydown(function(e) {
            if (e.keyCode==9) {
                entryShow();
                entryShow2();
            }
        });
    });

    $( "input[type=text]" ).focus(function() {
        $this = $(this);
        if (($this[0].id).indexOf('budget') <0) {
            $('#dtable').hide();
            $('#dcost').removeClass('clckchngbck');
        } else {
            $('#dtable').show();
            $('#dcost').addClass('clckchngbck');
        }
    });

    function entryShow() {
        $('#divsubmit').hide();
        $('.next-bt').hide();
        $('#dserviceProviderName').hide();
//        $('#divDiscount').hide();

        var $mainTRs = $("[class*=lgroup1]");
        var bShow=true;
        $.each($mainTRs, function (i, obj) {
            var $this = $(this);
            if (bShow==true) { $this.show();  $this.focus();}
            else $this.hide();
            $this.find("input:text").each(function () {
                name = $(this)[0].id;
                if ($('#'+name).val().length ==0) bShow=false;
            });
            $this.find("textarea").each(function () {
                alert("1");
                name = $(this)[0].id;
                if ($('#'+name).val().length ==0) bShow=false;
            });
            $this.find("select").each(function () {
                name = $(this)[0].id;
                if ($('#'+name).val().length ==0) bShow=false;
            });
        });
        if (parseFloat(isNullCheck($('#budget').val(),'number')) >0) bShow=true;
        if (bShow==true) $('.next-bt').show();
        if ($('#externalAgency').val() == 'Y') $('#dserviceProviderName').show();

        if ($('#discountRequired').val() == 'Y') $('#divDiscount').show();

        var DiscountType = $('#discount_type').val();
        if(DiscountType == 'R') {
            $('#divamount').hide();
            $('#divrate').show();
            $('#diveffectiveFrom').show();
            $('#diveffectiveTo').show();
        } else if(DiscountType == 'L') {
            $('#divrate').hide();
            $('#divamount').show();
            $('#diveffectiveFrom').show();
            $('#diveffectiveTo').show();
        }


        //if (bShow==true) $('#divsubmit').show();
    }
    function showDiscount() {
        if ($('#discountRequired').val() == 'Y') $('#divDiscount').show();
        if ($('#discountRequired').val() == 'N') $('#divDiscount').hide();
    }
    function showDiscountType() {
        var DiscountType = $('#discount_type').val();
        if(DiscountType == 'R') {
            $('#divamount').hide();
            $('#divrate').show();
            $('#diveffectiveFrom').show();
            $('#diveffectiveTo').show();
        } else if(DiscountType == 'L') {
            $('#divrate').hide();
            $('#divamount').show();
            $('#diveffectiveFrom').show();
            $('#diveffectiveTo').show();
        }
    }

    function entryShow2() {
        $('#divsubmit').hide();
        //$('.next-bt').hide();
        $('#dplan').hide();

        var $mainTRs = $("[class*=lgroup2]");
        var bShow=true;
        $.each($mainTRs, function (i, obj) {
            var $this = $(this);
            if (bShow==true) { $this.show();  $this.focus();}
            else $this.hide();
            $this.find("input:text").each(function () {
                name = $(this)[0].id;
                if ($('#'+name).val().length ==0){ bShow=false;}
            });
            $this.find("select").each(function () {
                name = $(this)[0].id;
                if ($('#'+name).val().length ==0){ bShow=false;}
            });
            $this.find("textarea").each(function () {
                name = $(this)[0].id;
                if ($('#'+name).val().trim().length ==0){ bShow=false;}
            });

        });

        //if (bShow==true) $('.next-bt').show();
        if (bShow==true) {$('#divsubmit').show();}
        if ($('#multiTimes').val() =='Y')  $('#dplan').show();
    }

    function bindShowNextLevel() {

        $showNextLevelBtn.on('click', function(ev) {
            ev.preventDefault();
            var rowCount = parseInt($('#projectrowid').val());
            var errCount=0;
            if(rowCount>0) {
                var count = 0 ;
                for(var i=1;i<=rowCount; i++) {
                    $('#pbudget_' + i).removeClass('red_bdr');
                    $('#budgetprojectName_' + i).removeClass('red_bdr');
                    if($('#projectId_'+i).val()!=0) {
                        count++;
                        if (parseFloat($('#pbudget_' + i).val()) == 0 || $('#pbudget_' + i).val() == "") {
                            $('#pbudget_' + i).addClass('red_bdr');
                            errCount++;
                            return false;
                        } else if (parseFloat($('#pbudget_' + i).val()) > parseFloat($('#overallBudget_' + i).val())) {
                            errCount++;
                            var projectName = $('#budgetprojectName_' + i).val();
                            $('#budgetprojectName_' + i).addClass('red_bdr');
                            $('#pbudget_' + i).removeClass('red_bdr');
                            $('#alertMsg').html("Campaign Cost for the Project <span id='projName'></span> Exceeded.. Please ask Admin to Increase the Budget...");
                            $('#projName').text(projectName);
                            $("#msgBox").modal('show');
                            return false;
                        } else {
                            $('#pbudget_' + i).removeClass('red_bdr');
                            $('#budgetprojectName_' + i).removeClass('red_bdr');
                        }
                    }
                }
                if(count==0) {
                    $('#alertMsg').html("Select atleast One Project in Campaign Cost");
                    $("#msgBox").modal('show');
                    errCount=1;
                }
            } else {
                $('#alertMsg').html("Select atleast One Project in Campaign Cost");
                $("#msgBox").modal('show');
                errCount=1;
            }
            if(errCount==0) {
                $level1.addClass('hide');
                $level2.removeClass('hide');
            }

//            var ProjectName = $ProjectName.val().trim(),
//                ProjectId = $ProjectId.val().trim(),
//                BlockName = $BlockName.val().trim(),
//                FloorName = $FloorName.val().trim(),
//                $selUnits = $Units.find('option:selected');
//
//            if(ProjectName.length <= 0 || /^\d+$/.test(ProjectId) == false) {
//                showError($ProjectName, 'Project is required!');
//            } else if(BlockName.length <= 0 && FloorName.length <= 0 && $selUnits.length <= 0) {
//                alert('Block or Floor or Units is required!');
//            } else if(!$ProjectName.hasClass('error') && !$BlockName.hasClass('error')
//                && !$FloorName.hasClass('error') && !$Units.hasClass('error')) {
//                bindStagesAutoComplete();
//                bindStageType_onChange();
//
//                $level1.addClass('hide');
//                $level2.removeClass('hide');
//            }
        });
    }

    function bindBackBtn() {
        $('#back-btn').on('click', function(ev) {
            ev.preventDefault();

            $level1.removeClass('hide');
            $level2.addClass('hide');

        });
    }


    function bindProjectAutoComplete() {
        var $projectName = $('input[id^=budgetprojectName_]');
        $projectName.unbind('autocomplete');
        $.each($projectName, function () {
            var $this = $(this),
                name = $this[0].id;
            if (name.indexOf('__') != -1 || name.indexOf('excel') != -1) return;
            var arrname = name.split('_');
            var key1 = arrname[1];
            checkProjectUsed(key1);
            $this.autocomplete({
                lookup: arr_project,
//                showNoSuggestionNotice:true,
//                noSuggestionNotice: 'Do you want to Create New <input type="button" style="font-weight:bold" class="btn btn-link" id="matpricenew_' + key1+'" value="Material" onclick="return AddNewMaterial(this.id)">',
                lookupFilter: function (suggestion, originalQuery, queryLowerCase) {
                    if (queryLowerCase == '*') {
                        return suggestion.value;
                    } else {
                        var re = new RegExp($.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
                        return re.test(suggestion.value);
                    }
                }, onSelect: function(suggestion) {
                    if(suggestion) {
                        $('#projectId_'+key1).val(suggestion.data);
                        if(campaignTransCheck.length!=0) {
                            //for edit mode project campaign cost amount split
                            $.each(campaignTransCheck, function (i, o) {
                                if (parseInt(suggestion.data) == parseInt(o.ProjectId)) {
                                    $('#overallBudget_' + key1).val(sanitizeNumber(parseFloat(o.BalanceBudget),2,true));
                                } else if (parseFloat(suggestion.amount) > 0) {
                                    $('#overallBudget_' + key1).val(sanitizeNumber(parseFloat(suggestion.amount),2,true));
                                } else {
                                    $('#overallBudget_' + key1).val(0);
                                }
                            });
                        } else {
                            if (parseFloat(suggestion.amount) > 0) {
                                $('#overallBudget_' + key1).val(sanitizeNumber(parseFloat(suggestion.amount),2,true));
                            } else {
                                $('#overallBudget_' + key1).val(0);
                            }
                        }
                        removeError($(this));
                    }
                }, onSearchStart: function(suggestion) {
                    $("#projectId_" + key1).val(0);
                    $('#overallBudget_'+key1).val(0);
                }, onSearchComplete: function (query, suggestions) {
                    if(!suggestions.length){
                        showError($(this), 'Required');
                        $("#projectId_" + key1).val(0);
                        $('#overallBudget_'+key1).val(0);
                    } else
                        removeError($(this));
                }
            });
        });
    }

    function checkProjectFocus(x) {
        var arrname = x.split('_');
        var key1 = arrname[1];
        checkProjectUsed(key1);
    }

    function checkProjectUsed(id) {
        var projectid = $('input[id*=projectId_]');
        arr_project = projectList;
        arr_project = $.grep(projectList, function (element, index) {
            var is_selected = true;
            $.each(projectid, function (i, obj) {
                var $this = $(this),
                    name = $this[0].id;
                var arrname = name.split('_');
                var key1 = arrname[1];
                if (key1 != id) {
                    if (element.data == $this.val()) {
                        is_selected = false;
                        return is_selected;
                    }
                }
            });
            return is_selected;
        });
    }

    function checkProjectFound(x) {
        var key = x.split('_')[1];
        if ($('#budgetprojectName_' + key).val().length == 0 || $('#projectId_' + key).val() == 0) {
            $('#pbudget_' + key).prop('readonly',true);
            $('#pbudget_' + key).val('');
            calculateBudgetCost();

        } else {
            $('#pbudget_' + key).prop('readonly',false);
        }
    }

    function addProjectRow(x) {
        calculateBudgetCost();

        var $x = $(x),
            $tr = $x.closest('tr'),
            key = $x[0].id.split('_')[1];

        if ($('#budgetprojectName_' + key).val().length == 0 || $('#projectId_' + key).val() == 0) {
            $('#pbudget_' + key).prop('readonly',true);
        } else {
            $('#pbudget_' + key).prop('readonly',false);
        }

        if ($tr.next('tr').length != 0)
            return;

        if ($('#budgetprojectName_' + key).val().length == 0 || $('#projectId_' + key).val() == 0 || $('#pbudget_' + key).val().length == 0)
            return;

        var $rowid = $('#projectrowid'),
            rowid = parseInt($rowid.val());
        $('.projectDeleteTr_' + rowid).show();
        var count = rowid + 1,
            template = $('#dummy-project tbody').html();

        template = template.replace(/__1/g, '_' + count);
        $tr.parent('tbody').append(template);
        $rowid.val(count);
        bindProjectAutoComplete();


    }

    function calculateBudgetCost() {
        var dBudget=0;
        var $pbudget = $('input[id^=pbudget_]');
        $.each($pbudget, function () {
            var $this = $(this),
                name = $this[0].id;

            if (name.indexOf('__') != -1 || name.indexOf('excel') != -1) return;

            dBudget = dBudget + parseFloat(isNullCheck($('#'+name).val(),'number'));
        });
        $('#budget').val(sanitizeNumber(parseFloat(dBudget),2,true));

    }


    function deleteProjectRow(x,e) {

        e.preventDefault();
        if (!confirm('Do you want to Delete'))
            return false;

        var $tr = $(x).closest('tr'),
            $tbody = $tr.parent('tbody');

        if ($tbody.find('> tr').length == 1) {
            var template = $('#dummy-project tbody').html();
            template = template.replace(/__1/g, '_' + 1);
            $tbody.append(template);
            $('#projectrowid').val(1);
        }
        $tr.remove();
        setPageChanges(true);
        bindProjectAutoComplete();
        calculateBudgetCost();
        return false;
    }
    function submitCampaign() {
        var $error = $('.error');
        if($error.length != 0) {
            alert('Kindly notice the error notifications!');

            $error.parents('.collapse:not(.in)').siblings('.panel-heading').trigger('click');
            return false;
        }
        $('#formWrapper').submit();
    }


    $(".special").keydown(function (e) {
        var key = e.which || e.keyCode;

        if (!e.shiftKey && !e.altKey && !e.ctrlKey &&
                // numbers
            key >= 48 && key <= 57 ||
                // Numeric keypad
            key >= 96 && key <= 105 ||

                // Backspace and Tab and Enter
            key == 8 || key == 9 || key == 13 ||
                // Home and End
            key == 35 || key == 36 ||
                // left and right arrows
            key == 37 || key == 39 ||
                // Del and Ins
            key == 46 || key == 45){
            return true;}
        else{

            return false;}
    });
    $(document).ready(function() {
        campaignTransCheck = <?php echo (isset($campaigntrans)) ? json_encode($campaigntrans) : '[]';?>;
    });

    function closePop() {
            $('#msgBox').modal('toggle');
    }


        $('.seperate').on('keyup', function () {

            var x = $('#income').val();
            $('.seperate').val(addCommas(x));
        });


    function addCommas(x) {
        console.log(x);
        var parts = x.toString().split(".");
        parts[0] = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, ",");
        return parts.join(".");
    }

    $("#phoneno").change(function(){
        var number=$(this).val();
        var fromDate=$("#startDate").val();
        var toDate=$("#endDate").val();
        $.ajax({
        url: getBaseURL() + 'crm/campaign/index',
        type: "post",
        data: {numbermob: number,startdt:fromDate,endedt:toDate,'mode':'check'},
        async: false,
        success: function (data, textStatus, jqXHR) {

            if(data== "failed"){
              alert("Campaign mobile number already found between two dates");
                return false;
            }
            else{

                return true;
            }


        }, error: function (jqXHR, textStatus, errorThrown) {
            $('.loading_area').hide();
        }

    });
    })




</script>