<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/amcharts/amcharts.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/amcharts/pie.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/amcharts/serial.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/amcharts/themes/light.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/amcharts/themes/dark.js"></script>
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/workorder.css';?>"/>

<style>
#chartdiv,#analGrid {
    width		: 100%;
    height		: 500px;
    font-size	: 11px;
}
#analGrid {font-size	: 13px  !important;}
.pagination-lg > li > a, .pagination-lg > li > span {
    font-size:15px !important;
    padding:5px 15px !important;
}

#treeGrid .jqx-grid-header 	{
    height:75px !important;
}
#jqxgridtwo .jqx-grid-header 	{
    height:75px !important;
}
#analGrid .jqx-grid-header 	{
    height:50px !important;
}
.mini-stat {
    background: #fff none repeat scroll 0 0;
    border-radius: 3px;
    margin-bottom: 20px;
    padding: 10px;
    -webkit-box-shadow: 1px 1px 0px 0px rgba(50, 50, 50, 0.23);
    -moz-box-shadow:    1px 1px 0px 0px rgba(50, 50, 50, 0.23);
    box-shadow:         1px 1px 0px 0px rgba(50, 50, 50, 0.23);
}
.mini-stat-icon {
    border-radius: 100%;
    color: #fff;
    display: inline-block;
    float: left;
    font-size: 20px;
    height: 40px;
    line-height: 40px;
    text-align: center;
    width: 40px;
	margin-top: 7px;
}
.mini-stat-info {
    font-size: 13px !important;
    padding-top: 10px;
    text-align:right;
}
.mini-stat-info span {
    display: block;
    font-size: 15px;
    font-weight: 600;
}
.orange {
    background: #fa8564!important;
}
.tar {
    background: #1fb5ac!important;
}
.pink {
    background: #a48ad4!important;
}
.green {
    background: #aec785!important;
}
.box {
    background-attachment: scroll, scroll, scroll, scroll;
    background-clip: border-box, border-box, border-box, border-box;
    background-color: rgba(0, 0, 0, 0);
    background-image: linear-gradient(135deg, transparent 0px, #e8e9ed 0px), linear-gradient(225deg, transparent 0px, #e8e9ed 0px), linear-gradient(315deg, transparent 15px, #e8e9ed 0px), linear-gradient(45deg, transparent 0px, #e8e9ed 0px);
    background-origin: padding-box, padding-box, padding-box, padding-box;
    background-position: left top, right top, right bottom, left bottom;
    background-repeat: no-repeat;
    background-size: 52% 52%;
    margin-bottom: 20px;
    position: relative;
    width: 100%;
}
.box .box-body::before {
    background: transparent none repeat scroll 0 0;
    border-color: #dbe3e9 transparent transparent #dbe3e9;
    border-style: solid;
    border-width: 20px 20px 0 0;
    bottom: 0;
    content: "";
    display: block;
    position: absolute;
    right: 0;
    width: 0;
}
.news-widget {
    border-radius: 0;
    margin: -40px -20px 0;
    padding: 0 0 8px;
}
.news-widget h2 span {
    background: #000 none repeat scroll 0 0;
    border-radius: 2px 0 0;
    color: #fff;
    display: inline-block;
    font-size: 13px;
    padding: 3px 15px;
    position: relative;
    right: 15px;
    top: 1px;
}
.bg-green {
    background-color: #88bbc8  !important;
}
#firstchartdiv {
    width	: 100%;
    height	: 300px;
}
#secchartdiv {
    width		: 100%;
    font-size	: 11px;
    height	: 300px;
}
#thirdchartdiv {
    width		: 100%;
    height		: 300px;
    font-size	: 11px;
}
#fourchartdiv {
    width: 100%;
    height: 500px;
}
#sixchartdiv {
    width		: 100%;
    height		: 338px;
    font-size	: 11px;
}
.panel {
    background-color: #fff;
    border: 1px solid #ddd;
    border-radius: 4px;
    box-shadow:0 1px 1px rgba(0, 0, 0, 0.05)!important;
    margin-bottom: 20px;
}
.panel-body {
    padding: 15px;
}
.panel-heading {
    border-bottom: 1px solid #ddd;
    border-top-left-radius: 3px;
    border-top-right-radius: 3px;
    padding: 10px 15px;
    color:#06528c;
}
.panel-headingone{border-bottom: 1px solid #ddd;color:#06528c; padding:2px;}
.region-earning-stats {
    color: #6d6d6d;
    font-family: "Open Sans",sans-serif;
    font-weight: 600;
    padding: 20px 30px;
    text-align: center;
    text-transform: uppercase;
}
.region-earning-stats span {
    color: #a48ad4 ;
    display: block;
    font-size: 20px;
}
.location-earning-stats {
    font-family: "Open Sans",sans-serif;
    font-weight: 600;
    margin-bottom: 30px;
    padding-left: 0;
    text-align: center;
}
.location-earning-stats li {
    padding: 0 15px;
}
.location-earning-stats li {
    display: inline-block;
    font-size: 12px;
    text-transform: uppercase;
}
.location-earning-stats li span {
    display: block;
    font-size: 14px;
}
.stat-divider {
    border-right: 1px dashed #dadada;
}
.event-calendar {
    background: #1fb5ac none repeat scroll 0 0; margin-bottom:25px;
    border-radius: 6px;
    min-height: 340px;
    margin-top: 18px;
}
.calendar-block {
    background: #fff none repeat scroll 0 0;
    border-radius: 0 5px 5px 0;
    float: right !important;
    min-height: 340px;
    -webkit-box-shadow: 1px 1px 0px 0px rgba(50, 50, 50, 0.23);
    -moz-box-shadow:    1px 1px 0px 0px rgba(50, 50, 50, 0.23);
    box-shadow:         1px 1px 0px 0px rgba(50, 50, 50, 0.23);
    z-index: 99;
}
.event-list-block {
    border-radius: 5px 0 0 5px;
}

.cal-day span {
    display: block;
    font-size: 14px;
}
.event-list {
    padding-left: 0;
}
.event-list li {
    background: rgba(255, 255, 255, 0.2) none repeat scroll 0 0;
    border-radius: 3px;
    color: #fff;
    list-style: outside none none;
    margin-bottom: 5px;
    padding: 10px 30px 10px 10px;
    position: relative;
}
.event-close {
    color: #fff;
    display: inline-block;
    font-size: 20px;
    position: absolute;
    right: 4px;
    top: 8px;
}
.evnt-input, .evnt-input:focus {
    -moz-border-bottom-colors: none;
    -moz-border-left-colors: none;
    -moz-border-right-colors: none;
    -moz-border-top-colors: none;
    background: rgba(0, 0, 0, 0) none repeat scroll 0 0;
    border-color: -moz-use-text-color -moz-use-text-color #fff;
    border-image: none;
    border-radius: 0;
    border-style: none none solid;
    border-width: medium medium 1px;
    color: #fff;
    margin-top: 10px;
    padding-left: 0;
}
.bckactv{background:#ff6c60;color:#fff;font-size:13px;font-weight:600;padding:3px 10px; border-radius:10px;
    text-align: center;
    white-space: nowrap;}
.cal-day label{ text-align:center; font-size:20px; color:#fff; padding-bottom:10px; padding-top:10px;}
.crmdlticn{color:#fff; font-size:20px;}
.crmedticn{color:#fff; font-size:20px;}
.number-pb {
    position: relative;
    height: 5px;
    background-color: #ddd;
    margin: 40px 0;
    font-size: 13px;
    font-weight: bold;
}
.number-pb .number-pb-shown {
    position: absolute;
    background-color: #41C3AC;
    top: -1px;
    left: 0;
    height: 5px;
}
.number-pb .number-pb-num {
    position: absolute;
    background-color: #B7C1D3;
    left: 0;
    top: -0.45em;
    padding: 0 5px;
    min-width: 20px;
    color: #fff;
    border-radius: 4px;
}
.number-pb-shown.dream {
    background: #4F9AC1;
}
.number-pb-shown.sun {
    background: #FC763C;
}
.commargin_top p{  color:#000; font-weight:600;float: left;
    font-size: 14px;
    font-weight: 600;
    line-height: 19px;
    text-align: right;
    width: 141px ; }
.add-necm a.but-add-cm{ font-size:13px; padding:6px 9px; margin-top:10px; background:#188c85; color:#fff; font-weight:600; display:block; border-radius:2px;}
.add-necm a{ float:left; padding-left:8px; padding-bottom:17px; padding-top:12px; color:#1A5A94 !;}
.add-necm a.but-add-cm:hover{ background:#4CC4BD; color:#333;}
.campn_amnt_span			{ font-size:16px; cursor:pointer;}
</style>
<div class="content_wrapper padlr0">
<div class="container-fluid padlr0">
<div class="col-lg-12">

<form method="post" onSubmit="return formValidate();">
    <div class="col-lg-12 clear padtop10 m_btm30">
        <div class="row">
            <div class="form-group">
                <div class="col-lg-8 col-lg-offset-3 col-md-8 col-md-offset-4 col-sm-10 col-sm-offset-2 col-xs-12 ">
                	<label class="col-lg-2 col-sm-2 control-label">Select Project</label>
                    <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">
                    <select name="projectId" id="projectId" class="single_dropdown lbl_move" style="width:100%;">
                        <option value="">Select Project</option>
                        <?php foreach($projects as $project){ ?>
                            <option value="<?php echo $project['ProjectId'] ?>" <?php if($projectId == $project['ProjectId']) { ?>selected<?php } ?>><?php echo $project['ProjectName'] ?></option>
                        <?php } ?>
                    </select>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                        <ul>
                            <li class="save_btn m_auto padtop5 width_auto">
                                <input type="submit" class="ripple" name="projectSubmit" value="Search" />
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="right_lightbox">
            <div class="right_lightbox_close">
                <span class="right_lightbox_closeicon"><i class="fa fa-times"></i></span>
            </div>
            <div class="right_lbox_inner lead_register_rbox">
                <h2 id="userName"></h2>
                <div class="right_lbox_inner_cnt">
                    <div class="ldrgstr_detail_pro padtop0">
                        <div class="col-lg-8 col-md-12 flwup_procnt">
                            <h1 class="name" id="projectName">Leads from Campaign:</h1>
                        </div>
                        <div id='jqxWidget'>
                            <div id="jqxgridtwo"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>


<!--head-->
<div class="col-lg-12">
    <div class="row">
        <div class="col-lg-4 col-md-6 col-sm-6 col-xs-6 mnimumwidthres  ">
            <div class="mini-stat clearfix">
                <span class="mini-stat-icon orange"><i class="fa fa-usd"></i></span>
                <div class="mini-stat-info comnelips">
                    <span class="comnelips"><?php echo (isset($campaignExpense)) ? 'Rs.'. $this->commonHelper()->sanitizeNumber((double)$campaignExpense['Amount'],2,true) : '';?></span>
                    Campaign Budget
                </div>
            </div>
        </div>
    	<div class="col-lg-4 col-md-6 col-sm-6 col-xs-6 mnimumwidthres  ">
            <div class="mini-stat clearfix" data-bsfshare="Campaign Cost">
                <span class="mini-stat-icon tet-cllr4"><i class="fa fa-gavel"></i></span>
                <div class="mini-stat-info comnelips">
                    <span class="comnelips"><?php echo (isset($campaignBudgetCost)) ? 'Rs.'. $this->commonHelper()->sanitizeNumber((double)$campaignBudgetCost['Amount'],2,true) : '';?></span>
                   Actual Spent
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-6 col-xs-6 mnimumwidthres ">
            <div class="mini-stat  clearfix" data-bsfshare="Lead Generated">
                <span class="mini-stat-icon green"><i class="fa fa-tag"></i></span>
                <div class="mini-stat-info comnelips">
                    <span class="comnelips"><?php echo (isset($campaigleads)) ? $this->commonHelper()->sanitizeNumber((double)$campaigleads['LeadCount'],0): '';?></span>
                    Lead Generated
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-6 col-xs-6 mnimumwidthres  ">
            <div class="mini-stat clearfix" data-bsfshare="Lead Expense">
                <span class="mini-stat-icon crmbrdrclrbck8"><i class="fa fa-inr"></i></span>
                <div class="mini-stat-info comnelips">
                    <span class="comnelips"><?php echo (isset($expectedLeads)) ?  $expectedLeads['Leads'] : '';?></span>
                   Expected Lead
                </div>
            </div>
        </div>
       <div class="col-lg-4 col-md-6 col-sm-6 col-xs-6 mnimumwidthres  ">
            <div class="mini-stat clearfix" data-bsfshare="Expected Revenue">
                <span class="mini-stat-icon tar"><i class="fa fa-bolt"></i></span>
                <div class="mini-stat-info comnelips">
                    <span class="comnelips"><?php echo (isset($campaignExpectedIncome)) ? 'Rs.'.$this->commonHelper()->sanitizeNumber((double)$campaignExpectedIncome['Amount'],2,true) : '';?></span>
                    Expected Revenue
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-6 col-xs-6 mnimumwidthres  ">
            <div class="mini-stat  clearfix">
                <span class="mini-stat-icon pink"><i class="fa fa-magic"></i></span>
                <div class="mini-stat-info comnelips">
                    <span class="comnelips"><?php echo (isset($campaignwon)) ? 'Rs.'.$this->commonHelper()->sanitizeNumber((double)$campaignwon['Amount'],2,true) : '';?></span>
                    Actual Revenue
                </div>
            </div>
        </div>

    </div>
</div>
<!--end head-->

<div class="col-lg-12 padlr0">
    <div class="col-lg-9 tmss">
        <div class="table-responsive clear">
            <div id="treeGrid"> </div>
        </div>
    </div>
    <!--side bar--->
    <div class="col-lg-3 ">
    	<div class="col-lg-12">
        	<div class="col-lg-12 event-calendar">
            <div class="col-lg-12 commargin_top" align="right"><span class="bckactv" id="refId">RefNo : </span></div>
            <div class="event-list-block">
                <div class="cal-day"> <label id="cname">Advertisement</label></div>
                <ul class="event-list">
                    <li id="campListAmount">Campaign Amount <span class="float_r campn_amnt_span" data-placement="left" data-toggle="tooltip" data-html="true" data-original-title=""><i class="fa fa-briefcase" aria-hidden="true"></i></span></li>
                    <li id="eIncome">Expected Income:</li>
                    <li id="sName">Source Name:</li>
                    <li id="cPerson">Contact Person:</li>
                    <li id="contactNo">Contact No:</li>
                    <li id="eLeads">ExpectedLeads:</li>
					<li id="remarks">Remarks:<span style="text-align:right;"></span></li>
                </ul>
                <div class="add-necm">
                    <a href="#" class="but-add-cm" onclick="newCampaign();">Add New Campaign</a>
                    <a href="#" onclick="editCampaign();" ><span class="crmdlticn"><i class="fa fa-pencil-square-o"></i></span></a> &nbsp;
                    <a href="#" onclick="campaignDelete();"><span class="crmedticn"><i class="fa fa-trash-o"></i></span></a>
                </div>
            </div>
        </div>
        </div>
    </div>
</div>
<!--end of side bar--->
<!--Start Chart-->
<!--            <div class="col-lg-12">-->
<!--                <div class="">-->
<!--                    <section class="panel">-->
<!--                        <header class="panel-heading">Campaign Revenue</header>-->
<!--                        <div class="panel-body">-->
<!--                            <div id="firstchartdiv"></div>-->
<!--                        </div>-->
<!--                    </section>-->
<!--                </div>-->
<!--            </div>-->
<div class="col-lg-12 padlr0 commargin_top">
    <div class="col-lg-6">
        <section class="panel">
            <header class="panel-heading">Campaign Budget Analysis</header>
            <div class="panel-body">
                <div id="secchartdiv"></div>
            </div>
        </section>
    </div>
    <div class="col-lg-6">
        <section class="panel">
            <header class="panel-heading">Lead Won Analysis</header>
            <div class="panel-body">
                <div id="thirdchartdiv"></div>
            </div>
        </section>
    </div>
    <!--                <div class="col-lg-12 padlr0">-->
    <!--                	<div class="col-lg-4">-->
    <!--                    	<div class="mini-stat" style="padding: 8px !important">-->
    <!--                        	<p class="panel-headingone">Direct Search</p>-->
    <!--                            <div>-->
    <!--                            	<div class="chart-block" style="padding:28px">-->
    <!--  									120-->
    <!--                                    <div id="line1" style="vertical-align: middle; display: inline-block; width: 100px; height: 30px;"></div>-->
    <!--                                    6% -->
    <!--                                    <div id="column1" style="vertical-align: middle;display: inline-block; width: 110px; height: 30px;"></div>-->
    <!--								</div>-->
    <!--                            </div>-->
    <!--                        </div>-->
    <!--                    </div>-->
    <!--                    <div class="col-lg-4">-->
    <!--                    	<div class="mini-stat" style="padding: 8px !important">-->
    <!--                        	<p class="panel-headingone">Organic Search</p>-->
    <!--                            <div>-->
    <!--                                <div class="chart-block" style="padding:28px">-->
    <!--                                  120 <div id="line2" style="vertical-align: middle; display: inline-block; width: 100px; height: 30px;"></div> 6% <div id="column2" style="vertical-align: middle;display: inline-block; width: 110px; height: 30px;"></div>-->
    <!--                                </div>		-->
    <!--                            </div>-->
    <!--                        </div>-->
    <!--                    </div>-->
    <!--                    <div class="col-lg-4">-->
    <!--                    	<div class="mini-stat" style="padding: 8px !important">-->
    <!--                        	<p class="panel-headingone">Paid Search</p>-->
    <!--                            <div>-->
    <!--                            	<div class="chart-blockn" style="padding:28px">-->
    <!--  									120-->
    <!--                                    <div id="lineee" style="vertical-align: middle; display: inline-block; width: 100px; height: 30px;"></div>-->
    <!--                                    6% -->
    <!--                                    <div id="columnnn" style="vertical-align: middle;display: inline-block; width: 110px; height: 30px;"></div>-->
    <!--								</div>-->
    <!--                            </div>-->
    <!--                        </div>-->
    <!--                    </div>-->
    <!--                </div>-->
    <!--                <div class="col-lg-12 commargin_top padlr0">-->
    <!--                	<div class="col-lg-6">-->
    <!--                        <section class="panel">-->
    <!--                            <header class="panel-heading">Campaign Analysis</header>-->
    <!--                            <div class="panel-body">-->
    <!--                                <div class="table-responsive">-->
    <!--                                    <table class="table" style="margin-bottom:0px !important;">-->
    <!--                                        <tbody>-->
    <!--                                            <tr>-->
    <!--                                                <td style="width:180px">-->
    <!--                                                    <strong style="font-size:12px !important;">Direct page value</strong>-->
    <!--                                                    <br>Averga Persetance-->
    <!--                                                </td>-->
    <!--                                                <td>-->
    <!--                                                    <div id="step">-->
    <!--                                                        <div style="margin: 15px 0 0;" class="number-pb">-->
    <!--                                                            <div class="number-pb-shown sun"></div>-->
    <!--                                                            <div class="number-pb-num">0/0</div>-->
    <!--                                                        </div>-->
    <!--                                                    </div>-->
    <!--                                                </td>-->
    <!--                                                <td style="width:100px">-->
    <!--                                                    <div class="pull-right text-red" style="color:#67b7dc !important;">-->
    <!--                                                        <small>$</small>7,086,050</div>-->
    <!--                                                    <br>-->
    <!--                                                    <small class="pull-right">21,00%</small>-->
    <!--                                                </td>-->
    <!--                                            </tr>-->
    <!--                                            <tr>-->
    <!---->
    <!--                                                <td>-->
    <!--                                                    <strong style="font-size:12px !important;">Organic page value</strong>-->
    <!--                                                    <br>Averga Persetance</td>-->
    <!--                                                <td>-->
    <!--                                                    <div id="basic">-->
    <!--                                                        <div style="margin: 15px 0 0;" class="number-pb">-->
    <!--                                                            <div class="number-pb-shown"></div>-->
    <!--                                                            <div class="number-pb-num">0</div>-->
    <!--                                                        </div>-->
    <!--                                                    </div>-->
    <!--                                                </td>-->
    <!--                                                <td>-->
    <!--                                                    <div class="pull-right text-green" style="color:#fdd400 !important;">-->
    <!--                                                        <small>$</small>1,346,232</div>-->
    <!--                                                    <br>-->
    <!--                                                    <small class="pull-right">56,00%</small>-->
    <!--                                                </td>-->
    <!--                                            </tr>-->
    <!--                                            <tr>-->
    <!---->
    <!--                                                <td>-->
    <!--                                                    <strong style="font-size:12px !important;">Paid page value</strong>-->
    <!--                                                    <br>Averga Persetance</td>-->
    <!--                                                <td>-->
    <!--                                                    <div id="percentage">-->
    <!--                                                        <div style="margin: 15px 0 0;" class="number-pb">-->
    <!--                                                            <div class="number-pb-shown dream"></div>-->
    <!--                                                            <div class="number-pb-num">0%</div>-->
    <!--                                                        </div>-->
    <!--                                                    </div>-->
    <!--                                                </td>-->
    <!--                                                <td>-->
    <!--                                                    <div class="pull-right text-aqua" style="color:#84b761 !important;">-->
    <!--                                                        <small>$</small>3,734,858</div>-->
    <!--                                                    <br>-->
    <!--                                                    <small class="pull-right">78,00%</small>-->
    <!--                                                </td>-->
    <!--                                            </tr>-->
    <!--                                        </tbody>-->
    <!--                                	</table>-->
    <!--                                </div>-->
    <!--                                <div>-->
    <!--                                <div class="region-earning-stats">-->
    <!--                                    This year total earning <span>$68,4545,454</span>-->
    <!--                                </div>-->
    <!--                               <ul class="clearfix location-earning-stats">-->
    <!--                                    <li class="stat-divider">-->
    <!--                                        <span class="first-city" style="color:#67b7dc !important;">$734503</span>-->
    <!--                                        Values/X </li>-->
    <!--                                    <li class="stat-divider">-->
    <!--                                        <span class="second-city" style="color:#fdd400 !important;">$734503</span>-->
    <!--                                        Values/Y </li>-->
    <!--                                    <li>-->
    <!--                                        <span class="third-city" style="color:#84b761 !important;">$734503</span>-->
    <!--                                        Values/Z </li>-->
    <!--                                </ul>-->
    <!--                            </div>-->
    <!--                            </div>-->
    <!--                        </section>-->
    <!--                    </div>-->
    <!--                    <div class="col-lg-6">-->
    <!--                        <section class="panel">-->
    <!--                            <header class="panel-heading">Lead Analysis</header>-->
    <!--                            <div class="panel-body">-->
    <!--                                <div id="sixchartdiv"></div>-->
    <!--                            </div>-->
    <!--                        </section>-->
    <!--                    </div>-->
</div>
<div class="col-lg-12 commargin_top">
    <section class="panel">
        <header class="panel-heading">Campaign Analysis</header>
        <div class="panel-body" style="padding: 12px !important;">
            <div class="table-responsive clear">
                <div id="analGrid"> </div>
            </div>
        </div>
    </section>
</div>
<div class="col-lg-12 commargin_top">
    <section class="panel">
        <header class="panel-heading">Campaign ROI</header>
        <div class="panel-body" style="padding: 12px !important;">
            <div id="fourchartdiv" style="background: #3f3f4f;color:#ffffff;"></div>
        </div>
    </section>
</div>
</div>
<!--end Chart-->
</div>
</div>

<div class="modal fade" id="DeleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button data-dismiss="modal" aria-hidden="true" class="close"><i class="fa fa-times-circle-o clpot"></i></button>
                <h1>Why do you want to delete Campaign No : <span id="delEntryName" class="bld-txt"></span>?</h1>
            </div>
            <div class="modal-body">
                <div class="padlr0">
                    <div class="container-fluid">
                        <div class="">
                            <div class="col-lg-12 commargin_top_20">
                                <form class="form-horizontal">
                                    <div class="row">
                                        <div class="form-group req_flds">
                                            <textarea id="remarks" maxlength="250" class="form-control lbl_move" label="Remarks">
                                            </textarea>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="commargin_top commargin_bottom">
                    <a href="#" data-dismiss="modal" aria-hidden="true" class="md_cance">Cancel</a>
                    <a href="#" id="btnDeleteYes" class="md_ok">Delete</a></div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function(){
        $('.right_lightbox_close').click(function(){
            $('.block_panel').removeClass('block_panel_open');
            $('.right_lightbox').hide();
            if ($(window).width() >=980){
                $('.left-panel').addClass('collapsed');
                $('.l_menuicon_nav').addClass('cross');
            }
        });
    });

    var data = <?php echo (isset($campaignRegister)) ? json_encode($campaignRegister) : ''?>,
        dataanal = <?php echo (isset($campaignAnal)) ? json_encode($campaignAnal) : ''?>;


        $treeGrid = $("#treeGrid");
        $analGrid = $("#analGrid");
        $deleteModal = $('#DeleteModal');
        $remarks = $('#remarks');
        iRowIndex=0;

    $(function () {

        var source = {
            localdata: data,
            dataType: "json",
            dataFields: [
                {name: 'Projects', type: 'string'},
                {name: 'CampaignId', type: 'number'},
                {name: 'CampaignNo', type: 'string'},
                {name: 'CampaignDate', type: 'string'},
                {name: 'CampaignName', type: 'string'},
                {name: 'Category', type: 'string'},
                {name: 'StartDate', type: 'string'},
                {name: 'EndDate', type: 'string'},
                {name: 'ExpectedIncome', type: 'number'},
                {name: 'CampaignCost', type: 'number'},
                {name: 'Status', type: 'string'},
                {name: 'Remarks', type: 'string'},
				{name: 'OpportunityName', type: 'string'},
				{name: 'SourceName', type: 'string'},
				{name: 'ExpectedLeads', type: 'string'},
				{name: 'ContactPerson', type: 'string'},
				{name: 'ContactNo', type: 'nu'}
            ],
            id: 'CampaignId'
        };

        var dataAdapter = new $.jqx.dataAdapter(source);
        $treeGrid.jqxGrid({
            width: "100%",
            source: dataAdapter,
            sortable: true,
            pagerButtonsCount: 6,
            showfilterrow: true,
            filterable: true,
            pageable: true,
            rowDetails: true,
            autoheight: true,
            selectionmode: 'singlerow',
            editable: false,
            altrows: true,
            enabletooltips: true,
            columns: [
                {text: 'CampaignId', datafield: 'CampaignId', hidden: true},
                {text: 'Ref No.', dataField: 'CampaignNo', width: '10%'},
                {text: 'Date', dataField: 'CampaignDate', width: '10%'},
                {text: 'Projects', dataField: 'Projects',width: '20%'},
                {text: 'Campaign Name', dataField: 'CampaignName', width: '20%'},
                {text: 'Category', dataField: 'Category', width: '10%'},
                {text: 'Start Date', dataField: 'StartDate', width: '10%'},
                {text: 'End Date', dataField: 'EndDate', width: '10%'},
                {text: 'Campaign Cost', dataField: 'CampaignCost', width: '10%', cellsalign: 'right', cellsformat: 'd2'},
                {text: 'ExpectedIncome', dataField: 'ExpectedIncome', hidden: true, cellsalign: 'right', cellsformat: 'd2'},
                {text: 'Status', dataField: 'Status', hidden: true},
                {text: 'Remarks', dataField: 'Remarks', hidden: true},
				{text: 'OpportunityName', dataField: 'OpportunityName', hidden: true},
				{text: 'SourceName', dataField: 'SourceName', hidden: true},
				{text: 'ExpectedLeads', dataField: 'ExpectedLeads', hidden: true},
				{text: 'ContactPerson', dataField: 'ContactPerson', hidden: true},
				{text: 'ContactNo', dataField: 'ContactNo', hidden: true},
                {
                    text: 'Action', sortable: false, filterable: false, hidden: true, align: 'left',
                    cellsrenderer: function (row) {
                        var ReceiptId = $treeGrid.jqxGrid('getCellValue', row, 'CampaignId'),
                            editLink = '<a title="Edit" href="' + getBaseURL() + 'crm/campaign/index/edit/' + ReceiptId + '" style="padding-left: 15px; margin-top:8px;"><i class="fa fa-pencil-square-o reg-icon"></i></a>';
                        return editLink + "&nbsp;&nbsp;" + '<a title="Delete" href="javascript: campaignDelete(' + row + ')"><i class="fa fa-trash-o reg-icon"></i></a>';
                    }
                }
            ]
        });
        $("#treeGrid").bind('rowselect', function (event) {
            var row = event.args.rowindex;
            var datarow = $("#treeGrid").jqxGrid('getrowdata', row);
            iRowIndex=row ;
			
            $('#refId').html('RefNo: ' + datarow.CampaignNo);
            $('#cname').html(datarow.CampaignName);
            $('#eIncome').html('Expected Income: ' + datarow.ExpectedIncome);
            $('#sName').html('Source Name: ' + datarow.SourceName);
            $('#cPerson').html('Contact Person: ' + datarow.ContactPerson);
            $('#contactNo').html('Contact No: ' + datarow.ContactNo);
            $('#eLeads').html('Expected Leads: ' + datarow.ExpectedLeads);
            $('#remarks').html('Remarks:<span style="text-align:right;"> ' + datarow.Remarks + '</span>');
			
			var campaignId = datarow.CampaignId;
			var target = 'campaignId=' + campaignId;
			$.ajax({
                url:getBaseURL()+"crm/campaign/register",
                type:"post",
                data:target,
                success:function(data,textStatus,jqXHR){
					$('#campListAmount').html('');
					var toAppend = 'Campaign Amount <span class="float_r campn_amnt_span" data-placement="left" data-toggle="tooltip" data-html="true" data-original-title="';
					var valu = JSON.parse(data);
					$.each(valu,function(i,o){
						toAppend +=  o.ProjectName+ ' : ' + sanitizeNumber(o.Amount,2,true)+' <br/>';
					});			
					toAppend += '"><i class="fa fa-briefcase" aria-hidden="true"></i></span>';
					$('#campListAmount').html(toAppend);				
					$('[data-toggle="tooltip"]').tooltip();
				},
					error:function(jqXHR, textStatus, errorThrown){
					alert(textStatus+"-----"+errorThrown);
				}
			});		
        });

        var analsource = {
            localdata: dataanal,
            dataType: "json",
            dataFields: [
                {name: 'CampaignId', type: 'number'},
                {name: 'CampaignName', type: 'string'},
                {name: 'CampaignCost', type: 'number'},
                {name: 'LeadWonAmount', type: 'number'},
                {name: 'LeadCount', type: 'number'},
                {name: 'CostPerLead', type: 'number'},
                {name: 'SiteVisitCount', type: 'number'},
                {name: 'CostPerVisit', type: 'number'},
                {name: 'CostPerCLead', type: 'number'},
                {name: 'LeadWonCount', type: 'number'},
                {name: 'ROI', type: 'number'}

            ],
            id: 'CampaignId'
        };

        var columnsrenderer = function (value) {
            return '<div style="text-align: right; margin-top: 5px;">' + value + '</div>';
        };

        var dataAdaptera = new $.jqx.dataAdapter(analsource);
        $analGrid.jqxGrid({
            width: "100%",
            source: dataAdaptera,
            sortable: true,
            pagerButtonsCount: 6,
            //showfilterrow: true,
            filterable: true,
            pageable: true,
            rowDetails: true,
            autoheight: true,
            selectionmode: 'singlerow',
            editable: false,
            altrows: true,
            enabletooltips: true,
            columns: [
                {text: 'CampaignId', datafield: 'CampaignId', hidden: true},
                {text: 'Campaign Name', dataField: 'CampaignName', width: '10%'},
                { text: 'Campaign<br/>Cost', dataField: 'CampaignCost', cellsalign: 'right',width: '11%',renderer: columnsrenderer,
                    cellsrenderer: function (row) {
                        return '<div class="text-right">' + sanitizeNumber($analGrid.jqxGrid('getCellValue', row, 'CampaignCost'),2,true) + '</div>';
                }},
                {text: 'No Of <br/>Leads', dataField: 'LeadCount', width: '10%',cellsalign: 'right',renderer: columnsrenderer},
                {text: 'Cost Per<br/>Lead', dataField: 'CostPerLead', width: '10%',cellsalign: 'right',renderer: columnsrenderer,
                    cellsrenderer: function (row) {
                        return '<div class="text-right">' + sanitizeNumber($analGrid.jqxGrid('getCellValue', row, 'CostPerLead'), 2, true) + '</div>';
                    }
                },
                {text: 'No of<br/>Conversion', dataField: 'LeadWonCount', width: '10%', cellsalign: 'right',renderer: columnsrenderer},
                {text: 'Cost per <br/> Convertion', dataField: 'CostPerCLead', width: '10%',cellsalign: 'right',renderer: columnsrenderer,
                    cellsrenderer: function (row) {
                        return '<div class="text-right">' + sanitizeNumber($analGrid.jqxGrid('getCellValue', row, 'CostPerCLead'), 2, true) + '</div>';
                    }
                },
                {text: 'No of<br/>Sitevisit', dataField: 'SiteVisitCount', width: '8%', cellsalign: 'right',renderer: columnsrenderer},
                {text: 'Cost per <br/>Sitevisit', dataField: 'CostPerVisit', width: '10%',cellsalign: 'right',renderer: columnsrenderer,
                    cellsrenderer: function (row) {
                        return '<div class="text-right">' + sanitizeNumber($analGrid.jqxGrid('getCellValue', row, 'CostPerCLead'), 2, true) + '</div>';
                    }
                },
                {text: 'Sale<br/>Value', dataField: 'LeadWonAmount', width: '11%',renderer: columnsrenderer,
                    cellsrenderer: function (row) {
                        return '<div class="text-right">' + sanitizeNumber($analGrid.jqxGrid('getCellValue', row, 'LeadWonAmount'), 2, true) + '</div>';
                    }
                },
                {text: 'ROI<br/>%', dataField: 'ROI', width: '10%',renderer: columnsrenderer,
                    cellsrenderer: function (row) {
                        return '<div class="text-right">' + sanitizeNumber($analGrid.jqxGrid('getCellValue', row, 'ROI'), 2) + '</div>';
                    }
                }
            ]
        });
        $("#analGrid").on('cellclick', function (event) {
            // event arguments.
            var args = event.args;
            // row's bound index.
            var rowBoundIndex = args.rowindex;
            // row's visible index.
            var rowVisibleIndex = args.visibleindex;
            // right click.
            var rightclick = args.rightclick;
            // original event.
            var ev = args.originalEvent;
            // column index.
            var columnindex = args.columnindex;
            // column data field.
            var dataField = args.datafield;
            // cell value
            var value = args.value;
            var data = $("#analGrid").jqxGrid("getrowdata", rowBoundIndex);
            var cName=data.CampaignName;


            $.ajax({
                url:getBaseURL()+"crm/campaign/leadname",
                type:"post",
                data:"cid="+data.CampaignId,
                success:function(data, textStatus, jqXHR){
                $('.right_lightbox').show();

                $('.left-panel').removeClass('collapsed');
                $('.l_menuicon_nav').removeClass('cross');
                    $('#projectName').html('Leads from Campaign: '  + cName);
                var source =
                {
                    localdata:data,
                    dataType: "json",
                    dataFields: [
                        { text: 'LeadId', type:'number'},
                        { name: 'LeadName', type: 'string' },
                        { name: 'LeadF', type: "string"},
                        { name: 'UnitName', type: "string"}

                    ],
                    id: 'LeadId'
                };

                var dataAdapter = new $.jqx.dataAdapter(source);
                $("#jqxgridtwo").jqxGrid({
                    width: '100%',
                    source: dataAdapter,
                    pageable: true,
                    columnsresize: true,
                    autoheight: true,
                    sortable: true,
                    altrows: true,
                    autorowheight: true,
                    showfilterrow: true,
                    filterable: true,
                   // groupable: true,
                    showstatusbar: true,
                    statusbarheight: 25,
                    ready:function(){
                    },
                    rendered: function () {
                    },
                    columns: [

                        { text: 'Lead Id', dataField: 'LeadId',hidden: true},
                        { text: 'Lead Name', dataField: 'LeadName',width:'25%',  filterable: true},
                        { text: 'Converted',dataField: 'LeadF',width:'10%',  filterable: true},
                        { text: 'Details',dataField: 'UnitName',width:'65%',  filterable: true},

                    ]
                });


            },
            error:function(jqXHR, textStatus, errorThrown){

            alert(textStatus+"-----"+errorThrown);
        }
    });
        });


    });


    $('#btnDeleteYes').on('click', function () {
        var remarks = $remarks.val();
        if (remarks.length == 0) {
            showError($remarks, 'Required!');
            return;
        } else
            removeError($remarks);

        $deleteModal.modal('hide');
        var rowData = $treeGrid.jqxGrid('getrowdata', $deleteModal.data('row'));

        $.ajax({
            url: getBaseURL() + 'crm/campaign/deletecampaign',
            type: 'POST',
            data: {"CampaignId": rowData.CampaignId, "Remarks": remarks},
            success: function (data, textStatus, jqXHR) {
                if (jqXHR.status == 200){
                    $treeGrid.jqxGrid("deleterow", rowData.uid);
                    window.location.href= getBaseURL() + "crm/campaign/register";}
                else{
                    alert('Failed to delete the receipt!');}
            },
            error: function (jqXHR, textStatus, errorThrown) {
                if (jqXHR.status == 403)
                    alert(jqXHR.responseText);
                else
                    alert(textStatus + "-----" + errorThrown);
            }
        });
        $remarks.val('');
    });

    function editCampaign() {
        if (iRowIndex<0) return;
        var rowData = $treeGrid.jqxGrid('getrowdata', iRowIndex);
        var iCId = rowData.CampaignId;
        window.open(getBaseURL() + 'crm/campaign/index/edit/' + iCId);
    }

    function newCampaign() {
        window.open(getBaseURL() + 'crm/campaign/index');
    }

    function campaignDelete() {
        if (iRowIndex<0) return;
        var rowData = $treeGrid.jqxGrid('getrowdata', iRowIndex);
        $deleteModal.data('row', iRowIndex).modal('show');
        $('#delEntryName').html(rowData.ReceiptNo);
        $("#remarks").val('');
    }

var chart = AmCharts.makeChart("firstchartdiv", {
    "type": "serial",
    "theme": "light",
    "titles": [{
        "text": "Campaign Revenue",
        "size": 15
    }],
    "legend": {
        "align": "center",
        "equalWidths": false,
        "periodValueText": "total: [[value.sum]]",
        "valueAlign": "left",
        "valueText": "[[value]] ([[percents]]%)",
        "valueWidth": 100
    },
    "dataProvider": [{
        "year": "2000",
        "cars": 1587,
        "motorcycles": 650,
        "bicycles": 121
    }, {
        "year": "1995",
        "cars": 1567,
        "motorcycles": 683,
        "bicycles": 146
    }, {
        "year": "1996",
        "cars": 1617,
        "motorcycles": 691,
        "bicycles": 138
    }, {
        "year": "1997",
        "cars": 1630,
        "motorcycles": 642,
        "bicycles": 127
    }, {
        "year": "1998",
        "cars": 1660,
        "motorcycles": 699,
        "bicycles": 105
    }, {
        "year": "1999",
        "cars": 1683,
        "motorcycles": 721,
        "bicycles": 109
    }, {
        "year": "2000",
        "cars": 1691,
        "motorcycles": 737,
        "bicycles": 112
    }, {
        "year": "2001",
        "cars": 1298,
        "motorcycles": 680,


        "bicycles": 101
    }, {
        "year": "2002",
        "cars": 1275,
        "motorcycles": 664,
        "bicycles": 97
    }, {
        "year": "2003",
        "cars": 1246,
        "motorcycles": 648,
        "bicycles": 93
    }, {
        "year": "2004",
        "cars": 1218,
        "motorcycles": 637,
        "bicycles": 101
    }, {
        "year": "2005",
        "cars": 1213,
        "motorcycles": 633,
        "bicycles": 87
    }, {
        "year": "2006",
        "cars": 1199,
        "motorcycles": 621,
        "bicycles": 79
    }, {
        "year": "2007",
        "cars": 1110,
        "motorcycles": 210,
        "bicycles": 81
    }, {
        "year": "2008",
        "cars": 1165,
        "motorcycles": 232,
        "bicycles": 75
    }, {
        "year": "2009",
        "cars": 1145,
        "motorcycles": 219,
        "bicycles": 88
    }, {
        "year": "2010",
        "cars": 1163,
        "motorcycles": 201,
        "bicycles": 82
    }, {
        "year": "2011",
        "cars": 1180,
        "motorcycles": 285,
        "bicycles": 87
    }, {
        "year": "2012",
        "cars": 1159,
        "motorcycles": 277,
        "bicycles": 71
    }],
    "valueAxes": [{
        "stackType": "100%",
        "gridAlpha": 0.07,
        "position": "left",
        "title": "percent"
    }],
    "graphs": [{
        "balloonText": "<img src='<?php echo $this->basePath(); ?>/images/iconn1.png' style='vertical-align:bottom; margin-right: 10px; width:28px; height:21px;'><span style='font-size:14px; color:#000000;'><b>[[value]]</b></span>",
        "fillAlphas": 0.5,
        "lineAlpha": 0.5,
        "title": "Paid",
        "valueField": "cars"
    }, {
        "balloonText": "<img src='<?php echo $this->basePath(); ?>/images/iconn2.png' style='vertical-align:bottom; margin-right: 10px; width:28px; height:21px;'><span style='font-size:14px; color:#000000;'><b>[[value]]</b></span>",
        "fillAlphas": 0.5,
        "lineAlpha": 0.5,
        "title": "organic",
        "valueField": "motorcycles"
    }, {
        "balloonText": "<img src='<?php echo $this->basePath(); ?>/images/iconn3.png' style='vertical-align:bottom; margin-right: 10px; width:28px; height:21px;'><span style='font-size:14px; color:#000000;'><b>[[value]]</b></span>",
        "fillAlphas": 0.5,
        "lineAlpha": 0.5,
        "title": "Direct",
        "valueField": "bicycles"
    }],
    "plotAreaBorderAlpha": 0,
    "marginLeft": 0,
    "marginBottom": 0,
    "chartCursor": {
        "cursorAlpha": 0,
        "zoomable": false
    },
    "categoryField": "year",
    "categoryAxis": {
        "startOnAxis": true,
        "axisColor": "#DADADA",
        "gridAlpha": 0.07
    },
    "export": {
        "enabled": true
    }
});

var chart = AmCharts.makeChart("secchartdiv", {
    "type": "pie",
    "theme": "light",
    "innerRadius": "40%",
    "gradientRatio": [-0.4, -0.4, -0.4, -0.4, -0.4, -0.4, 0, 0.1, 0.2, 0.1, 0, -0.2, -0.5],
    "dataProvider": <?php echo $campaignanal;?>,
    "valueField": "Amount",
    "titleField": "OpportunityName",
    "balloonText": "[[title]]<br><span style='font-size:14px'><b>[[value]]</b> ([[percents]]%)</span>",
//    "balloon": {
//        "drop": true,
//        "adjustBorderColor": false,
//        "color": "#FFFFFF",
//        "fontSize": 12
//    },
    "export": {
        "enabled": true
    }
});

var arrColors = [ "#62d5ce", "#bdb3d2", "#d4e3bd", "#fddcc1" ];
var serialData = <?php echo (isset($leadanal))?$leadanal:'[]';?>

    $.each(serialData, function(index, data) {
        var colorsCnt = arrColors.length,
            key = ( index % colorsCnt);
        data.color = arrColors[key];
    });

var chart = AmCharts.makeChart("thirdchartdiv", {
    "theme": "light",
    "type": "serial",
    "startDuration": 2,
    "dataProvider": serialData,
    "valueAxes": [{
        "position": "left",
        "axisAlpha":0,
        "gridAlpha":0
    }],
    "graphs": [{
        "balloonText": "[[category]]: <b>[[value]]</b>",
        "fillAlphas": 0.85,
        "lineAlpha": 0.1,
        "type": "column",
        "topRadius":1,
        "valueField": "Amount",
        "fillColorsField": "color"
    }],
    "depth3D": 40,
    "angle": 30,
    "chartCursor": {
        "categoryBalloonEnabled": false,
        "cursorAlpha": 0,
        "zoomable": false
    },
    "categoryField": "OpportunityName",
    "categoryAxis": {
        "gridPosition": "start",
        "axisAlpha":0,
        "gridAlpha":0

    },
    "export": {
        "enabled": true
    }

},0);

jQuery('.chart-input').off().on('input change',function() {
    var property	= jQuery(this).data('property');
    var target		= chart;
    chart.startDuration = 0;

    if ( property == 'topRadius') {
        target = chart.graphs[0];
    }

    target[property] = this.value;
    chart.validateNow();
});

var chart = AmCharts.makeChart("fourchartdiv", {
    "type": "serial",
    "theme": "dark",
    "valueAxes": [{
        "id": "v1",
        "title": "Cost",
        "position": "left",
        "autoGridCount": false,
        "labelFunction": function(value) {
            return + Math.round(value) ;
        }
    }, {
        "id": "v2",
        "title": "Leads",
        "gridAlpha": 0,
        "position": "right",
        "autoGridCount": false
    }],
    "graphs": [{
        "id": "g3",
        "valueAxis": "v1",
        "lineColor": "#e1ede9",
        "fillColors": "#e1ede9",
        "fillAlphas": 1,
        "type": "column",
        "title": "Campaign Cost",
        "valueField": "CampaignCost",
        "clustered": false,
        "columnWidth": 0.5,
        "legendValueText": "[[value]]",
        "balloonText":"[[value]]",
        "balloonFunction": function(graphDataItem, graph) {
            var val = graphDataItem.values.value;
            if(val >= 10000000) {
                val = (val/10000000).toFixed(2) + ' Cr';
            } else if(val >= 100000) {
                val = (val / 100000).toFixed(2) + ' Lac';
            } else {
                val=val.toFixed(2);
            }
            return "Campaign Cost<br/><b style='font-size: 130%'>"+val+"</b>";
        }
    }, {
        "id": "g4",
        "valueAxis": "v1",
        "lineColor": "#62cf73",
        "fillColors": "#62cf73",
        "fillAlphas": 1,
        "type": "column",
        "title": "Sales",
        "valueField": "LeadWonAmount",
        "clustered": false,
        "columnWidth": 0.3,
        "legendValueText": "[[value]]",
        "balloonText": "[[value]]",
        "balloonFunction": function(graphDataItem, graph) {
            var val = graphDataItem.values.value;
            if(val >= 10000000) {
                val = (val/10000000).toFixed(2) + ' Cr';
            } else if(val >= 100000) {
                val = (val / 100000).toFixed(2) + ' Lac';
            } else {
                val=val.toFixed(2);
            }
            return "Sales<br/><b style='font-size: 130%'>"+val+"</b>";
        }
    }, {
        "id": "g1",
        "valueAxis": "v2",
        "bullet": "round",
        "bulletBorderAlpha": 1,
        "bulletColor": "#FFFFFF",
        "bulletSize": 5,
        "hideBulletsCount": 50,
        "lineThickness": 2,
        "lineColor": "#20acd4",
        "type": "smoothedLine",
        "title": "Total Leads",
        "useLineColorForBulletBorder": true,
        "valueField": "LeadCount",
        "balloonText": "[[value]]",
        "balloonFunction": function(graphDataItem, graph) {
            var val = sanitizeNumber(graphDataItem.values.value,0);
            return "Total Leads<br/><b style='font-size: 130%'>"+val+"</b>";
        }
    }, {
        "id": "g2",
        "valueAxis": "v2",
        "bullet": "round",
        "bulletBorderAlpha": 1,
        "bulletColor": "#FFFFFF",
        "bulletSize": 5,
        "hideBulletsCount": 50,
        "lineThickness": 2,
        "lineColor": "#e1ede9",
        "type": "smoothedLine",
        "dashLength": 5,
        "title": "Converted Leads",
        "useLineColorForBulletBorder": true,
        "valueField": "LeadWonCount",
        "balloonText": "[[value]]",
        "balloonFunction": function(graphDataItem, graph) {
            var val = sanitizeNumber(graphDataItem.values.value,0);
            return "Converted Leads<br/><b style='font-size: 130%'>"+val+"</b>";
        }
    }],
    "chartScrollbar": {},
    "chartCursor": {
        "cursorPosition": "mouse"
    },

//    "chartScrollbar": {
//        "graph": "g1",
//        "oppositeAxis": false,
//        "offset": 30,
//        "scrollbarHeight": 50,
//        "backgroundAlpha": 0,
//        "selectedBackgroundAlpha": 0.1,
//        "selectedBackgroundColor": "#888888",
//        "graphFillAlpha": 0,
//        "graphLineAlpha": 0.5,
//        "selectedGraphFillAlpha": 0,
//        "selectedGraphLineAlpha": 1,
//        "autoGridCount": true,
//        "color": "#AAAAAA"
//    },
//    "chartCursor": {
//        "pan": true,
//        "valueLineEnabled": true,
//        "valueLineBalloonEnabled": true,
//        "cursorAlpha": 0,
//        "valueLineAlpha": 0.2
//    },
    "categoryField": "Mondata",
    "categoryAxis": {
        "dashLength": 1,
        "minorGridEnabled": true
    },

    "legend": {
        "useGraphSettings": true,
        "position": "top",
        "valueText": ""
    },
    "balloon": {
        "borderThickness": 1,
        "shadowAlpha": 0
    },
    "export": {
        "enabled": true
    },
    "dataProvider": <?php echo $campaigndetails;?>
});
    //AmCharts.ready(function() {
//
//    // line chart, with a bullet at the end
//    var chart = new AmCharts.AmSerialChart(AmCharts.themes.none);
//    chart.dataProvider = [{
//        day: 1,
//        value: 120
//    }, {
//        day: 2,
//        value: 124
//    }, {
//        day: 3,
//        value: 127
//    }, {
//        day: 4,
//        value: 122
//    }, {
//        day: 5,
//        value: 121
//    }, {
//        day: 6,
//        value: 123
//    }, {
//        day: 7,
//        value: 118
//    }, {
//        day: 8,
//        value: 113
//    }, {
//        day: 9,
//        value: 122
//    }, {
//        day: 10,
//        value: 125,
//        bullet: "round"
//    }];
//    chart.categoryField = "day";
//    chart.autoMargins = false;
//    chart.marginLeft = 0;
//    chart.marginRight = 5;
//    chart.marginTop = 0;
//    chart.marginBottom = 0;
//
//    var graph = new AmCharts.AmGraph();
//    graph.valueField = "value";
//    graph.bulletField = "bullet";
//    graph.showBalloon = true;
//    graph.lineColor = "#aec785";
//    chart.addGraph(graph);
//
//    var valueAxis = new AmCharts.ValueAxis();
//    valueAxis.gridAlpha = 0;
//    valueAxis.axisAlpha = 0;
//    chart.addValueAxis(valueAxis);
//
//    var categoryAxis = chart.categoryAxis;
//    categoryAxis.gridAlpha = 0;
//    categoryAxis.axisAlpha = 0;
//    categoryAxis.startOnAxis = true;
//    chart.write("line1");
//
//
//    // small column chart
//    var chart = new AmCharts.AmSerialChart(AmCharts.themes.none);
//    chart.dataProvider = [{
//        day: 1,
//        value: -5
//    }, {
//        day: 2,
//        value: 3
//    }, {
//        day: 3,
//        value: 7
//    }, {
//        day: 4,
//        value: -3
//    }, {
//        day: 5,
//        value: 3
//    }, {
//        day: 6,
//        value: 4
//    }, {
//        day: 7,
//        value: 6
//    }, {
//        day: 8,
//        value: -3
//    }, {
//        day: 9,
//        value: -2
//    }, {
//        day: 10,
//        value: 6
//    }];
//    chart.categoryField = "day";
//    chart.autoMargins = false;
//    chart.marginLeft = 0;
//    chart.marginRight = 0;
//    chart.marginTop = 0;
//    chart.marginBottom = 0;
//
//    var graph = new AmCharts.AmGraph();
//    graph.valueField = "value";
//    graph.type = "column";
//    graph.fillAlphas = 1;
//    graph.lineColor = "#aec785 ";
//    graph.showBalloon = true;
//    chart.addGraph(graph);
//
//    var valueAxis = new AmCharts.ValueAxis();
//    valueAxis.gridAlpha = 0;
//    valueAxis.axisAlpha = 0;
//    chart.addValueAxis(valueAxis);
//
//    var categoryAxis = chart.categoryAxis;
//    categoryAxis.gridAlpha = 0;
//    categoryAxis.axisAlpha = 0;
//    chart.write("column1");
//
//// line chart, with a bullet at the end
//    var chart = new AmCharts.AmSerialChart(AmCharts.themes.none);
//    chart.dataProvider = [{
//        day: 1,
//        value: 120
//    }, {
//        day: 2,
//        value: 124
//    }, {
//        day: 3,
//        value: 127
//    }, {
//        day: 4,
//        value: 122
//    }, {
//        day: 5,
//        value: 121
//    }, {
//        day: 6,
//        value: 123
//    }, {
//        day: 7,
//        value: 118
//    }, {
//        day: 8,
//        value: 113
//    }, {
//        day: 9,
//        value: 122
//    }, {
//        day: 10,
//        value: 125,
//        bullet: "round"
//    }];
//    chart.categoryField = "day";
//    chart.autoMargins = false;
//    chart.marginLeft = 0;
//    chart.marginRight = 5;
//    chart.marginTop = 0;
//    chart.marginBottom = 0;
//
//    var graph = new AmCharts.AmGraph();
//    graph.valueField = "value";
//    graph.bulletField = "bullet";
//    graph.showBalloon = true;
//    graph.lineColor = "#a48ad4";
//    chart.addGraph(graph);
//
//    var valueAxis = new AmCharts.ValueAxis();
//    valueAxis.gridAlpha = 0;
//    valueAxis.axisAlpha = 0;
//    chart.addValueAxis(valueAxis);
//
//    var categoryAxis = chart.categoryAxis;
//    categoryAxis.gridAlpha = 0;
//    categoryAxis.axisAlpha = 0;
//    categoryAxis.startOnAxis = true;
//    chart.write("lineee");
//
//
//    // small column chart
//    var chart = new AmCharts.AmSerialChart(AmCharts.themes.none);
//    chart.dataProvider = [{
//        day: 1,
//        value: -5
//    }, {
//        day: 2,
//        value: 3
//    }, {
//        day: 3,
//        value: 7
//    }, {
//        day: 4,
//        value: -3
//    }, {
//        day: 5,
//        value: 3
//    }, {
//        day: 6,
//        value: 4
//    }, {
//        day: 7,
//        value: 6
//    }, {
//        day: 8,
//        value: -3
//    }, {
//        day: 9,
//        value: -2
//    }, {
//        day: 10,
//        value: 6
//    }];
//    chart.categoryField = "day";
//    chart.autoMargins = false;
//    chart.marginLeft = 0;
//    chart.marginRight = 0;
//    chart.marginTop = 0;
//    chart.marginBottom = 0;
//
//    var graph = new AmCharts.AmGraph();
//    graph.valueField = "value";
//    graph.type = "column";
//    graph.fillAlphas = 1;
//    graph.lineColor = "#a48ad4 ";
//    graph.showBalloon = true;
//    chart.addGraph(graph);
//
//    var valueAxis = new AmCharts.ValueAxis();
//    valueAxis.gridAlpha = 0;
//    valueAxis.axisAlpha = 0;
//    chart.addValueAxis(valueAxis);
//
//    var categoryAxis = chart.categoryAxis;
//    categoryAxis.gridAlpha = 0;
//    categoryAxis.axisAlpha = 0;
//    chart.write("columnnn");
//
//
//    // line chart, with different line color below zero
//    var chart = new AmCharts.AmSerialChart(AmCharts.themes.none);
//    chart.dataProvider = [{
//        day: 1,
//        value: 120
//    }, {
//        day: 2,
//        value: 54
//    }, {
//        day: 3,
//        value: -18
//    }, {
//        day: 4,
//        value: -12
//    }, {
//        day: 5,
//        value: -51
//    }, {
//        day: 6,
//        value: 12
//    }, {
//        day: 7,
//        value: 56
//    }, {
//        day: 8,
//        value: 113
//    }, {
//        day: 9,
//        value: 142
//    }, {
//        day: 10,
//        value: 125
//    }];
//    chart.categoryField = "day";
//    chart.autoMargins = false;
//    chart.marginLeft = 0;
//    chart.marginRight = 5;
//    chart.marginTop = 0;
//    chart.marginBottom = 0;
//
//    var graph = new AmCharts.AmGraph();
//    graph.valueField = "value";
//    graph.showBalloon = true;
//    graph.lineColor = "#ffbf63";
//    graph.negativeLineColor = "#289eaf";
//    chart.addGraph(graph);
//
//    var valueAxis = new AmCharts.ValueAxis();
//    valueAxis.gridAlpha = 0;
//    valueAxis.axisAlpha = 0;
//    chart.addValueAxis(valueAxis);
//
//    var categoryAxis = chart.categoryAxis;
//    categoryAxis.gridAlpha = 0;
//    categoryAxis.axisAlpha = 0;
//    categoryAxis.startOnAxis = true;
//
//    // using guide to show 0 grid
//    var guide = new AmCharts.Guide();
//    guide.value = 0;
//    guide.lineAlpha = 0.1;
//    valueAxis.addGuide(guide);
//    chart.write("line2");
//
//
//    // column chart with different negative colors
//    var chart = new AmCharts.AmSerialChart(AmCharts.themes.none);
//    chart.dataProvider = [{
//        day: 1,
//        value: -5
//    }, {
//        day: 2,
//        value: 3
//    }, {
//        day: 3,
//        value: 7
//    }, {
//        day: 4,
//        value: -3
//    }, {
//        day: 5,
//        value: 3
//    }, {
//        day: 6,
//        value: 4
//    }, {
//        day: 7,
//        value: 6
//    }, {
//        day: 8,
//        value: -3
//    }, {
//        day: 9,
//        value: -2
//    }, {
//        day: 10,
//        value: 6
//    }];
//    chart.categoryField = "day";
//    chart.autoMargins = false;
//    chart.marginLeft = 0;
//    chart.marginRight = 0;
//    chart.marginTop = 0;
//    chart.marginBottom = 0;
//
//    var graph = new AmCharts.AmGraph();
//    graph.valueField = "value";
//    graph.type = "column";
//    graph.fillAlphas = 1;
//    graph.showBalloon = true;
//    graph.lineColor = "#ffbf63";
//    graph.negativeFillColors = "#289eaf";
//    graph.negativeLineColor = "#289eaf";
//    chart.addGraph(graph);
//
//    var valueAxis = new AmCharts.ValueAxis();
//    valueAxis.gridAlpha = 0;
//    valueAxis.axisAlpha = 0;
//    chart.addValueAxis(valueAxis);
//
//    var categoryAxis = chart.categoryAxis;
//    categoryAxis.gridAlpha = 0;
//    categoryAxis.axisAlpha = 0;
//    chart.write("column2");
//});
var chart = AmCharts.makeChart("sixchartdiv", {
    "theme": "light",
    "type": "serial",
    "dataProvider": [{
        "year": 2005,
        "income": 23.5
    }, {
        "year": 2006,
        "income": 26.2
    }, {
        "year": 2007,
        "income": 30.1
    }, {
        "year": 2008,
        "income": 29.5
    }, {
        "year": 2009,
        "income": 24.6
    }],
    "valueAxes": [{
        "title": "Estimated Budget for every year"
    }],
    "graphs": [{
        "balloonText": "Income in [[category]]:[[value]]",
        "fillAlphas": 1,
        "lineAlpha": 0.2,
        "title": "Income",
        "type": "column",
        "valueField": "income"
    }],
    "depth3D": 20,
    "angle": 30,
    "rotate": true,
    "categoryField": "year",
    "categoryAxis": {
        "gridPosition": "start",
        "fillAlpha": 0.05,
        "position": "left"
    },
    "export": {
        "enabled": true
    }
});
jQuery('.chart-input').off().on('input change',function() {
    var property	= jQuery(this).data('property');
    var target		= chart;
    chart.startDuration = 0;

    if ( property == 'topRadius') {
        target = chart.graphs[0];
        if ( this.value == 0 ) {
            this.value = undefined;
        }
    }

    target[property] = this.value;
    chart.validateNow();
});
</script>
<script>
    //Weather Icons
    (function($) {
        "use strict";
        var icons = new Skycons({
                "stroke": 0.08,
                "color": "Gray",
                "cloudColor": "#65C3DF",
                "sunColor": "#0090d9",
                "moonColor": "DodgerBlue",
                "rainColor": "RoyalBlue",
                "snowColor": "LightGray",
                "windColor": "LightSteelBlue",
                "fogColor": "#65C3DF"
            }),
            list = [
                "clear-day", "clear-night", "partly-cloudy-day",
                "partly-cloudy-night", "cloudy", "rain", "sleet", "snow", "wind",
                "fog"
            ],
            i;

        for (i = list.length; i--;)
            icons.set(list[i], list[i]);
        icons.play();
    })(jQuery);

    //Animation Slider
    $(function() {
        function randomPercentage() {
            return Math.floor(Math.random() * 100);
        }

        function randomInterval() {
            var min = Math.floor(Math.random() * 30);
            var max = min + (Math.floor(Math.random() * 40) + 70);
            return [min, max];
        }

        function randomStep() {
            return Math.floor(Math.random() * 10) + 5;
        }

        // setup
        var $basic = $('#basic');
        var interval = randomInterval();
        var basicBar = $basic.find('.number-pb').NumberProgressBar({
            style: 'basic',
            min: interval[0],
            max: interval[1]
        })
        $basic.find('.title span').text('[Min: ' + interval[0] + ', Max: ' + interval[1] + ']');

        var percentageBar = $('#percentage .number-pb').NumberProgressBar({
            style: 'percentage'
        })

        var $step = $('#step');
        var maxStep = randomStep()
        var stepBar = $('#step .number-pb').NumberProgressBar({
            style: 'step',
            max: maxStep
        })
        $step.find('.title span').text('[Max step: ' + maxStep + ']');

        // loop
        var basicLoop = function() {
            basicBar.reach(undefined, {
                complete: percentageLoop
            });
        }

        var percentageLoop = function() {
            percentageBar.reach(undefined, {
                complete: stepLoop
            });
        }

        var stepLoop = function() {
            stepBar.reach(undefined, {
                complete: basicLoop
            });
        }

        // start
        basicLoop();
    });

/*function formValidate() {
    var errorFlag = 0;
    var errorFlagCount = 0;
    if($('#projectId').val() == "" || $('#projectId').val() == null){
        errorFlagCount = errorFlagCount + 1;
        errorFlag = 1;
        if(errorFlagCount == 1) {
            $('#projectId').focus();
        }
    }

    if(errorFlag == 0) {
        return true;
    } else {
        return false;
    }
}*/
</script>