<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css';?>" />
<div class="content_wrapper padlr0">
	<div class="container-fluid padlr0">
		<div class="col-lg-12 clear">
			<h1>Documents </h1>
			<!--Documents start-->
			<div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0">
				<h2 class="ava">Available</h2>
				<div class="table-responsive topsp" style="margin-top:10px;">
					<table class="table tableWithFloatingHeader" style=" margin-bottom:0px;">
						<thead>
							<tr>
								<th width="15%">Document Name</th>
								<th width="15%">Document Type</th>
								<th width="3%">Action</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td width="15%"><input class="parent_text" type="text" /></td>
								<td width="15%"><input class="parent_text" type="text" /></td>
								<td width="4%" class="action_btns_td">
									<ul class="action_btns">
										<li style="float:left;">
											<a class="mainTrDelete_1" href="#">
												<span data-toggle="tooltip" data-placement="left" data-original-title="Documents Attached" class="btn-file butclr_imp">
													<i class="fa fa-paperclip dcm_atch"></i>
													<input type="file">
												</span>
											</a>
										</li>
										<li style="float:left;">
											<a class="mainTr_1" href="#">
												<span data-toggle="tooltip" data-placement="left" data-original-title="Document Views">
													<i class="fa fa-eye"></i>
												</span>
											</a>
										</li>
										<li style="float:left;">
											<a class="mainTr_1" href="#">
												<span data-toggle="tooltip" data-placement="left" data-original-title="Document Delete">
													<i class="fa fa-trash-o"></i>
												</span>
											</a>
										</li>
									</ul>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
				<h2 class="ava">Required</h2>
				<div class="table-responsive topsp" style="margin-top:10px;">
					<table class="table tableWithFloatingHeader" style=" margin-bottom:0px;">
						<thead>
							<tr>
								<th width="15%">Document Name</th>
								<th width="15%">Document Type</th>
								<th width="3%">Action</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td width="15%"><input class="parent_text" type="text" /></td>
								<td width="15%"><input class="parent_text" type="text" /></td>
								<td width="4%" class="action_btns_td">
									<ul class="action_btns">
										<li style="float:left;">
											<a class="mainTrDelete_1" href="#">
												<span data-toggle="tooltip" data-placement="left" data-original-title="Documents Attached" class="btn-file butclr_imp">
													<i class="fa fa-paperclip dcm_atch"></i>
													<input type="file">
												</span>
											</a>
										</li>
										<li style="float:left;">
											<a class="mainTr_1" href="#">
												<span data-toggle="tooltip" data-placement="left" data-original-title="Document Views">
													<i class="fa fa-eye"></i>
												</span>
											</a>
										</li>
										<li style="float:left;">
											<a class="mainTr_1" href="#">
												<span data-toggle="tooltip" data-placement="left" data-original-title="Document Delete">
													<i class="fa fa-trash-o"></i>
												</span>
											</a>
										</li>
									</ul>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
				<div class="cont_bt col-lg-5 col-lg-offset-7 col-md-9 col-md-offset-3 col-sm-7 col-sm-offset-3 col-xs-7 col-xs-offset-4">
					<ul>
						<li><a href="#"><i class="fa fa-check-circle"></i> Done</a></li>
					</ul>
				</div>
			</div>
			<!--Documents end-->
		</div>
	</div>
</div>