<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/css/project.css" />
<style>
    .info-dets										{min-height:115px; max-height:100%;}
    .edit-btn 										{cursor:pointer;float:right;font-weight:100;padding:6px 13px !important;overflow:hidden;font-size:13px;position:relative;text-align:center;margin-right: 5px;margin-top: 10px; width:auto;z-index: 1;}
    ul.bor-left li{margin-bottom:5px}
    ul.bor-left li label{width:50%;}
	.proname_btn a{font-size:18px; font-weight:600}
</style>
<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
        <form onsubmit="return entryValidate()" method="post" id="landfollowup" enctype="multipart/form-data">
            <input type="hidden" id="formfrom" name="formfrom" />
            <input type="hidden" id="EnquiryId" name="EnquiryId" value = "<?php echo $EnquiryId; ?>"/>
            <input type="hidden" id="EnquiryName" name="EnquiryName" value = "<?php echo $EnquiryName; ?>"/>
            <input type="hidden" id="QuoteType" name="QuoteType" value = "<?php echo $enquiry['QuoteType']; ?>"/>
            <?php if ($EnquiryId ==0) { ?>
                <div class="col-lg-12 clear">
                    <div class="row">
                        <div class="col-lg-12 top_ct zoomIn animated" id="MainWrapper">
                            <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 prt-next">
                                <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 top-nexts">
                                    <div class="form-group">
                                        <input type="text" name="TenderName" id="TenderName" class="form-control lbl_move" label="Enquiry Name" onkeypress="return enterButton(event);" />
                                    </div>
                                    <div class="next-bt"><a href="javascript:submitProperty();">Next <i class="fa fa-chevron-circle-right"></i></a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <?php } else { ?>
            <div class="col-lg-12 clear">
                <div class="col-lg-12">
                    <h1 data-bsfhead="Followup Details" style="color:#333">Followup Details
                        <div class="btn-group proname_btn"> <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"><?php echo ucfirst($EnquiryName);?> <span class="edit_symbols" data-placement="right" data-toggle="tooltip" data-original-title="Change&nbsp;Followup&nbsp;Name"><i class="fa fa-caret-down "></i></span></a>
                            <div class="dropdown-menu toolbar_ddown proname_ddown arrow" role="menu">
                                <ul>
                                    <?php
                                    foreach($enquiryNames as $landData){?>
                                        <li><a href="javascript:void(0);" class="followupId" data-index="<?php echo $landData['data'];?>"><?php echo ucfirst($landData['value']);?></a></li>
                                    <?php }	?>
                                </ul>
                            </div>
                        </div>
                    </h1>
                </div>
            </div>
    </div>
    <div class="col-lg-12  col-lg-offset-0 clear">
        <div class="land-regi">
            <div class="col-lg-7">
                <h1 class="top-add"><?php echo $enquiry['NameOfWork'];?></h1>
            </div>
            <div class="col-lg-5">
                <ul>
                    <li style="<?php if ($woApprove=='Y') echo 'display:none';?>"><a class="edit-btn edit_al" href='javascript:callfollowup(103);'> <i class="fa fa-plus-circle"></i>Quotation Revision</a></li>
                    <!--                        <li><a class="edit-btn edit_al" href='javascript:callfollowup(103);'> <i class="fa fa-plus-circle"></i>Quotation Revision</a></li>-->
                    <li style="<?php if ($woApprove!='Y') echo 'display:none';?>"><a class="edit-btn edit_al" href='javascript:callfollowup(104);'> <i class="fa fa-plus-circle"></i>WO Terms Amendment</a></li>
                </ul>
            </div>
            <!--				<div class="col-md-3" align="center" >-->
            <!--	             <div class="admin-panel" style="--><?php //if ($quoteApprove!='Y') echo 'display:none';?><!--">Quotation<b style="float:right;padding-right:8px"><i class="fa fa-cog"></i></b>-->
            <!--	                 <div class="revision">-->
            <!--		                 <div class="arrow-rev"></div>-->
            <!--			               <a href="#">Revision Quotation</a>-->
            <!--			                <a href="#">Additional Items</a>-->
            <!--			                <a href="#">Non-Aggrement Items</a>-->
            <!--		                 </div>-->
            <!--                       </div>-->
            <!--	               </div>-->
            <div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0">
                <div class="col-lg-9>
                    <span class="info-dets">
                <ul class="bor-left col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-4 col-sm-offset-0 col-xs-12 col-xs-offset-0">
                    <li>
                        <label>Enquiry No</label>
                        <span>:&nbsp;&nbsp;<a href="<?php echo $this->basePath().'/project/tender/enquiry/'. $enquiry['TenderEnquiryId'];?>"><?php echo $enquiry['RefNo'];?></a></span> </li>
                    <li>
                        <label>Enquiry Date</label>
                        <span>:&nbsp;&nbsp;<?php echo date('d-m-Y', strtotime($enquiry['RefDate']));?></span> </li>
                    <li>
                        <label>ClientName</label>
                        <span>:&nbsp;&nbsp;<?php echo $enquiry['ClientName'];?></span> </li>
                    <li style="<?php echo ($enquiry['EnquiryType'] =='E') ? 'display: none' : '';?>" >
                        <label>Proposal Cost</label>
                        <span>:&nbsp;&nbsp;<?php echo $this->commonHelper()->sanitizeNumber($enquiry['ProposalCost'],2,true);?></span>
                    </li>
                    <li style="<?php echo ($enquiry['EnquiryType'] !='E') ? 'display: none' : '';?>" >
                        <label>Quote Type</label>
                        <span>:&nbsp;&nbsp;<?php echo $enquiry['QType'];?></span>
                    </li>
                </ul>
                <ul class="bor-left col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-4 col-sm-offset-0 col-xs-12 col-xs-offset-0"  style="<?php echo ($enquiry['EnquiryType'] =='E') ? 'display: none' : '';?>">
                    <li>
                        <label>Project Duration</label>
                            <span>:&nbsp;&nbsp;<?php echo round($enquiry['ProjectDuration'],3);?> <?php if($enquiry['Duration'] == 1) { echo "Days";}?>
                                <?php if($enquiry['Duration'] == 2) { echo "Weeks";}?>
                                <?php if($enquiry['Duration'] == 3) { echo "Months";}?>
                                <?php if($enquiry['Duration'] == 4) { echo "Years";}?>
                            </span> </li>
                    <li>
                        <label>Bid Submit on</label>
                        <!--                            <span>:&nbsp;&nbsp;--><?php //echo $enquiry['QuoteType'];?><!--</span>-->
                    </li>
                    <li>
                        <label>Bid Open on</label>
                        <!--                            <span>:&nbsp;&nbsp;--><?php //echo $enquiry['QuoteType'];?><!--</span>-->
                    </li>
                </ul>
                <ul class="bor-left col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-4 col-sm-offset-0 col-xs-12 col-xs-offset-0"  style="<?php echo ($enquiry['EnquiryType'] !='E') ? 'display: none' : '';?>">
                    <li>
                        <label>Project Name</label>
                        <span>:&nbsp;&nbsp;<?php echo $enquiry['CostCentreName'];?></span>
                    <li>
                        <label>Ref Work Order No</label>
                        <span>:&nbsp;&nbsp;<?php echo $enquiry['WONo'];?></span>
                    </li>
                    <li>
                        <label>Ref Work Order Date</label>
                        <span>:&nbsp;&nbsp;<?php echo date('d-m-Y', strtotime($enquiry['WODate'])); ?></span>
                    </li>
                </ul>
                </span>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-lg-12 wizards">
            <section>
                <nav>
                    <ul class="cd-multi-steps text-center">
                        <?php
                        if(count($processSteps) > 0) {
                            foreach ($processSteps as $pstrans) {
                                ?>
                                <li class="<?php if ($pstrans['Flag'] == 1)  echo 'completed'; else echo 'prog-ress'; ?>"><a href="#" onclick="callfollowup(<?php echo $pstrans['TenderProcessId']; ?>)" ><?php echo $pstrans['ProcessName']; ?></a></li>
                            <?php
                            }
                        }
                        ?>
                        <li style="<?php echo ($enquiry['EnquiryType'] =='E') ? 'display: none' : '';?>" class="<?php if ($quoteApprove=='Y') echo 'completed'; else echo 'prog-ress';?>"><a href="#" onclick="callfollowup(101)" >Quotation</a></li>
                        <li style="<?php echo ($enquiry['EnquiryType'] =='E') ? 'display: none' : '';?>" class="prog-ress"><a href="#" onclick="callfollowup(106)" >Submit Form</a></li>
                        <li style="<?php echo ($enquiry['EnquiryType'] =='E') ? 'display: none' : '';?>" class="<?php if ($woApprove=='Y') echo 'completed'; else echo 'prog-ress';?>"><a href="#" onclick="callfollowup(102)" >Work Order</a></li>
                        <li style="<?php echo ($enquiry['EnquiryType'] =='E' && $enquiry['QuoteType']=='N') ? '' : 'display: none';?>" class="<?php if ($quoteApprove=='Y') echo 'completed'; else echo 'prog-ress';?>"><a href="#" onclick="callfollowup(101)" >Quotation</a></li>
                        <li style="<?php echo ($enquiry['EnquiryType'] =='E' && $quoteApprove=='Y') ? '' : 'display: none';?>" class="<?php if ($woApprove=='Y') echo 'completed'; else echo 'prog-ress';?>"><a href="#" onclick="callfollowup(105)" >Work Order Update</a></li>
                    </ul>
                </nav>
            </section>
        </div>
    </div>
</div>
<div class="clearfix"></div>
<div class="col-lg-12">
    <div class="col-sm-6 col-md-6 col-lg-6 col-xs-12 m_tb10" id="followWrapper">
        <h1 class="text-center m-top5" style="color:#244996">Follow Up</h1>
        <div class="col-lg-10 col-lg-offset-1">
            <div class="form-horizontal">
                <div class="row">
                    <div class="form-group">
                        <div class="col-lg-12"> <span class="date_icon"><i class="fa fa-calendar"></i></span>
                            <input type="text" name="RefDate" id="RefDate" class="form-control lbl_move date_picker" label="Ref Date" value="<?php echo date("d-m-Y");?>" />
                        </div>
                    </div>
                    <div class="form-group" id="divCallType">
                        <div class="col-lg-12">
                            <select name="EnquiryCallType" id="EnquiryCallType" onchange="FollowupType();" class="single_dropdown lbl_move" data-size="5" label="Followup Type" style=" width:100%;">
                                <option value="">Select Followup Type</option>
                                <?php foreach($enquiryCallType as $trans) { ?>
                                    <option value="<?php echo $trans['CallTypeId']; ?>"><?php echo $trans['CallTypeName']; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group" id ="divChecklistAssign" style="display: none">
                        <div class="col-lg-12"> <!--onchange="FollowupType();"-->
                            <select name="TenderAssignChecklist" id="TenderAssignChecklist" onchange="checklist();" class="single_dropdown lbl_move" data-size="5" label="Tender-Checklist" style=" width:100%;">
                                <option value="" >Select Tender - Assign Checklist </option>
                                <?php foreach($AssignTenderList as $value) { ?>
                                    <option value="<?php echo $value['CheckListId']; ?>"><?php echo $value['CheckListName']; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group" id ="divChecklistAction" style="display: none">
                        <div class="col-lg-12"> <!--onchange="FollowupType();"-->
                            <select name="TenderActionChecklist" id="TenderActionChecklist" onchange="checklist();" class="form-control selectpicker show-tick" data-size="5" label="Tender-Checklist">
                                <option value="" >Select Tender - Action Checklist </option>
                                <?php foreach($ActionTenderList as $value) { ?>
                                    <option value="<?php echo $value['CheckListId']; ?>"><?php echo $value['CheckListName']; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group" id ="divUser" style="display: none">
                        <div class="col-lg-12">
                            <select name="checklistUser" id="checklistUser" onchange="checklist();" class="form-control selectpicker show-tick" data-size="5" label="Username">
                                <option value="" >Select UserName</option>
                                <?php foreach($UserName as $value) { ?>
                                    <option value="<?php echo $value['UserId']; ?>"><?php echo $value['UserName']; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group" id = "divChecklistDate" style="display: none">
                        <div class="col-lg-12"> <span class="date_icon"><i class="fa fa-calendar"></i></span>
                            <input type="text" readonly name="checklistDate" id="checklistDate" onchange="ShowRemarks();" class="form-control lbl_move date_picker" label="Checklist Date" value="" />
                        </div>
                    </div>
                    <div class="form-group" id ="divProgress" style="display: none">
                        <div class="col-lg-12">
                            <select name="Progress" id="Progress" class="form-control selectpicker show-tick" data-size="5" label="Progress">
                                <option value="" >Select Progress</option>
                                <option value="In-Progress">In-Progress</option>
                                <option value="Done">Done</option>
                                <option value="Closed">Closed</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group" style="display:none;">
                        <div class="col-lg-12">
                            <input type="text" name="NatureOfEnquiryName" id="NatureOfEnquiryName" class="form-control lbl_move" label="Nature of Enquiry" />
                            <input type="hidden" id="CallNatureId" name="CallNatureId" />
                        </div>
                    </div>
                    <div class="form-group" id="divRemarks" style="margin-bottom:15px !important;display:none;">
                        <div class="col-lg-12">
                            <textarea id="Remarks" name="Remarks" class="form-control lbl_move" label="Remarks" />
                            </textarea>
                        </div>
                    </div>
                    <div class="form-group" id="divReason" style="margin-bottom:15px !important;display:none;">
                        <div class="col-lg-12">
                            <input type="text" id="Reason" name="Reason" class="form-control lbl_move" label="Reason" />
                        </div>
                    </div>
                    <div class="radio_check col-lg-12" id="divNextCallRequired" style="display:none;">
                        <p>
                            <input type="checkbox" id="NextCallRequired" name="NextCallRequired" value="1" onchange="ToggleDiv(this,'1');">
                            <label style="position: relative; overflow: hidden;" class="ripple has-ripple" for="NextCallRequired">Next Followup Required<span class="ripple-wrapper"></span><span class="ripple-wrapper"></span></label>
                        </p>
                    </div>
                    <div class="form-group" id="divNextCallDate" style="display:none;">
                        <div class="col-lg-12"> <span class="date_icon"><i class="fa fa-calendar"></i></span>
                            <input type="text" name="NextCallDate" id="NextCallDate" class="form-control lbl_move date_picker" label="Next Call Date" />
                        </div>
                    </div>
                    <div class="form-group" id="divNextCallType" style="display:none;">
                        <div class="col-lg-12">
                            <select name="NextEnquiryCallType" id="NextEnquiryCallType" class="form-control selectpicker show-tick" data-size="5" label="Next Enquiry Call Type">
                                <option value="">Select Next Enquiry Call Type</option>
                                <?php foreach($enquiryCallType as $trans) { ?>
                                    <option value="<?php echo $trans['CallTypeId']; ?>"><?php echo $trans['CallTypeName']; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group" id="divNextCallRemarks" style="margin-bottom:15px !important; display: none">
                        <div class="col-lg-12">
                            <textarea id="NextCallRemarks" name="NextCallRemarks" class="form-control lbl_move" label="Next Call Remarks"></textarea>
                        </div>
                    </div>
                    <div class="form-group" id="divRequestSubject" style="margin-bottom:15px !important; display: none">
                        <div class="col-lg-12">
                            <input type="text" maxlength="50" name="RequestSubject" id="RequestSubject" class="form-control lbl_move" label="Subject" />
                        </div>
                    </div>
                    <div class="form-group" id="divRequestNote" style="margin-bottom:15px !important; display: none">
                        <div class="col-lg-12">
                            <textarea id="RequestNote" maxlength="255" name="RequestNote" class="form-control lbl_move" label="Note"></textarea>
                        </div>
                    </div>
                    <div class="form-group" id="divRequestDocuments" style="margin-bottom:15px !important; display: none">
                        <div class="col-lg-12">
                            <input type="file" name="RequestDocuments[]" multiple/>
                        </div>
                    </div>
                    <div class="cont_bt-list">
                        <ul>
                            <li><a href="<?php echo $this->basePath() . '/project/followup/followup';?>" class="steps_btn ripple">Cancel</a></li>
                            <li><a onclick="submitForm();" class="cbtn ripple">Submit <i class="fa fa-check-circle"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-md-6 col-lg-6 col-xs-12" id="historyWrapper">
        <div class="widget-box">
            <div class="widget-header">
                <h1 class="widget-title"><i class="fa fa-history hisico"></i> History </h1>
                <!--              <a href="javascript:hideHistory();"><i class="fa fa-times"></i></a> </div>-->
                <?php if(!empty($history)) { ?>
                    <div class="widget-body">
                        <div class="widget-main no-padding">
                            <div class="dialogs" id="historyDetails"> </div>
                        </div>
                    </div>
                    <div class="view-more"><a href="#">View more <i class="fa fa-eye"></i> </a></div>
                <?php } ?>
            </div>
        </div>
    </div>
    <?php } ?>
    </form>
</div>
</div>
<script type="text/javascript">
function showComments(e, id)
{
    e.preventDefault();
    $('#comments').addClass('show');
}
function closeComment()
{
    $('#comments').removeClass('show');
}
function submitForm() {
    $('#landfollowup').submit();
}

function ToggleDiv(x,type)
{
    if($(x).is(':checked')) {
        if(type==1) {
            $('#divNextCallDate').fadeIn();
            $('#divNextCallType').fadeIn();
            $('#divNextCallRemarks').fadeIn();
        }
        else if(type==2) {
            $('#divAttachDoc').fadeIn();
        }
    } else {
        if(type==1) {
            $('#divNextCallDate').fadeOut();
            $('#divNextCallType').fadeOut();
            $('#divNextCallRemarks').fadeOut();
        }
        else if(type==2) {
            $('#divAttachDoc').fadeOut();
        }
    }
}

var arrEnquiryNames = <?php echo json_encode($enquiryNames);?>;
var arrNatureEnquiry = <?php echo json_encode($natureEnquiry);?>;
var arrReason = <?php echo json_encode($Reason);?>;
//var arrAssignTenderList = <?php //echo json_encode($AssignTenderList);?>//;
//var arrEditEnquiry = <?php //echo json_encode($EditEnquiry);?>//;
//var refdate = <?php //echo json_encode(date('d-m-Y', strtotime($EditEnquiry['RefDate'])));?>//;
var $enquiryName = $('#EnquiryName'),
    $enquiryId = $('#EnquiryId'),
    $natureEnquiry = $('#NatureOfEnquiryName'),
    $natureEnquiryId = $('#CallNatureId'),
    $Reason = $('#Reason'),
    $callType = $('#EnquiryCallType'),
    $nextCallType = $('#NextEnquiryCallType'),
    $remarks = $('#Remarks'),
    $nextCallRemarks = $('#NextCallRemarks'),
    $nextCallDate = $('#NextCallDate'),
    $RefDate = $('#RefDate'),
    $nextCallRequired = $('#NextCallRequired'),
    $TenderAssignChecklist = $('#TenderAssignChecklist');
$TenderActionChecklist = $('#TenderActionChecklist');
$checklistUser = $('#checklistUser');
$checklistDate = $('#checklistDate');
$Progress = $('#Progress');
$RequestSubject = $('#RequestSubject');
$RequestNote = $('#RequestNote');

function ShowCallType() {
    $('#divCallType').fadeIn();
}
function ShowRemarks() {
    //Display Remarks
    $('#divRemarks').fadeIn();
    $('#divNextCallRequired').fadeIn();
}
function FollowupType() {
    var enquiryId = $enquiryId.val();
    var CallTypeId = $callType.val();
    var Date = $RefDate.val();

    if ($RefDate.val().length == 0) {
        alert('Ref Date is Required!');
        $RefDate.focus();
        return;
    }


    if($callType.val() == 1) {
        //Action Checklist - 1
        $('#divReason').fadeOut();
        $('#divRequestSubject').fadeOut();
        $('#divRequestNote').fadeOut();
        $('#divRequestDocuments').fadeOut();
        $('#divUser').fadeOut();
        $('#divChecklistDate').fadeOut();
        $('#divChecklistAssign').fadeOut();
        $('#divProgress').fadeOut();
        $('#divChecklistAction').fadeIn();
    } else if($callType.val() == 2) {
        //Request For Information - 2
        $('#divUser').fadeOut();
        $('#divChecklistDate').fadeOut();
        $('#divChecklistAssign').fadeOut();
        $('#divProgress').fadeOut();
        $('#divChecklistAction').fadeOut();

        $('#divRemarks').fadeOut();
        $('#divNextCallDate').fadeOut();
        $('#divNextCallType').fadeOut();
        $('#divNextCallRemarks').fadeOut();
        $('#divReason').fadeOut();

        $('#divRequestSubject').fadeIn();
        $('#divRequestNote').fadeIn();
        $('#divRequestDocuments').fadeIn();
    } else if($callType.val() == 3) {
        //Request Responce - 3
        $('#divUser').fadeOut();
        $('#divChecklistDate').fadeOut();
        $('#divChecklistAssign').fadeOut();
        $('#divProgress').fadeOut();
        $('#divChecklistAction').fadeOut();

        $('#divRemarks').fadeOut();
        $('#divNextCallDate').fadeOut();
        $('#divNextCallType').fadeOut();
        $('#divNextCallRemarks').fadeOut();
        $('#divReason').fadeOut();

        $('#divRequestSubject').fadeIn();
        $('#divRequestNote').fadeIn();
        $('#divRequestDocuments').fadeIn();
    } else if($callType.val() == 4) {
        //Closed - 4
        showClosed();
    }


//    if ($callType.val() == 1) {
//        //Document Purchase - 1
//        window.location.href = getBaseURL() + "project/followup/document-purchase/" + enquiryId + "/" + CallTypeId + "/" + Date;
//
//
//    } else if ($callType.val()==2) {
//        //Document - 2
//        window.location.href = getBaseURL() + "project/tender/document/" + enquiryId;
//    } else if($callType.val() == 13) {
//        //Assgin Checklist - 13
//        $('#divReason').fadeOut();
//        $('#divRequestSubject').fadeOut();
//        $('#divRequestNote').fadeOut();
//        $('#divRequestDocuments').fadeOut();
//        $('#divUser').fadeOut();
//        $('#divChecklistDate').fadeOut();
//        $('#divChecklistAssign').fadeOut();
//        $('#divProgress').fadeOut();
//        $('#divChecklistAction').fadeOut();
//        $('#divChecklistAssign').fadeIn();
//    } else if($callType.val() == 14) {
//        //Action Checklist - 14
//        $('#divReason').fadeOut();
//        $('#divRequestSubject').fadeOut();
//        $('#divRequestNote').fadeOut();
//        $('#divRequestDocuments').fadeOut();
//        $('#divUser').fadeOut();
//        $('#divChecklistDate').fadeOut();
//        $('#divChecklistAssign').fadeOut();
//        $('#divProgress').fadeOut();
//        $('#divChecklistAction').fadeIn();
//    } else if($callType.val() == 3) {
//        //Site Visit / Investigation - 3
//        window.location.href = getBaseURL() + "project/followup/site-investigation/"+enquiryId;
//    } else if($callType.val() == 15) {
//        //Technical Specification - 11
//        window.location.href = getBaseURL() + "project/followup/technical-specification/"+enquiryId;
//    } else if($callType.val() == 9) {
//        //Commercial Bid - Opening - 9
//        window.location.href = getBaseURL() + "project/tender/bidstatus/" + enquiryId + "/" + Date;
//    } else if($callType.val() == 7) {
//        //Pre-Qualification - 7
//        window.location.href = getBaseURL() + "project/tender/pre-qualstatus/" + enquiryId + "/" + Date + "/" + CallTypeId;
//    } else if($callType.val() == 8) {
//        //Technical - Bid Opening - 8
//        window.location.href = getBaseURL() + "project/tender/pre-qualstatus/" + enquiryId + "/" + Date + "/" + CallTypeId;
//    } else if($callType.val() == 4) {
//        //Pre-Bid Meeting - 4
//        window.location.href = getBaseURL() + "project/tender/meeting/" + enquiryId + "/" + Date + "/" + CallTypeId;
//    } else if($callType.val() == 10) {
//        //Negotiation Meeting - 10
//        window.location.href = getBaseURL() + "project/tender/meeting/" + enquiryId + "/" + Date + "/" + CallTypeId;
//    } else if($callType.val() == 16) {
//        //Request For Information - 16
//        $('#divUser').fadeOut();
//        $('#divChecklistDate').fadeOut();
//        $('#divChecklistAssign').fadeOut();
//        $('#divProgress').fadeOut();
//        $('#divChecklistAction').fadeOut();
//
//        $('#divRemarks').fadeOut();
//        $('#divNextCallDate').fadeOut();
//        $('#divNextCallType').fadeOut();
//        $('#divNextCallRemarks').fadeOut();
//        $('#divReason').fadeOut();
//
//        $('#divRequestSubject').fadeIn();
//        $('#divRequestNote').fadeIn();
//        $('#divRequestDocuments').fadeIn();
//    } else if($callType.val() == 17) {
//        //Request Responce - 17
//        $('#divUser').fadeOut();
//        $('#divChecklistDate').fadeOut();
//        $('#divChecklistAssign').fadeOut();
//        $('#divProgress').fadeOut();
//        $('#divChecklistAction').fadeOut();
//
//        $('#divRemarks').fadeOut();
//        $('#divNextCallDate').fadeOut();
//        $('#divNextCallType').fadeOut();
//        $('#divNextCallRemarks').fadeOut();
//        $('#divReason').fadeOut();
//
//        $('#divRequestSubject').fadeIn();
//        $('#divRequestNote').fadeIn();
//        $('#divRequestDocuments').fadeIn();
//    } else if($callType.val() == 18) {
//      //Closed - 18
//        showClosed();
//    }

}
function showClosed() {
    //Remarks and reason

    $('#divUser').fadeOut();
    $('#divChecklistDate').fadeOut();
    $('#divChecklistAssign').fadeOut();
    $('#divProgress').fadeOut();
    $('#divChecklistAction').fadeOut();

    /*$('#divRemarks').fadeOut();*/
    $('#divNextCallDate').fadeOut();
    $('#divNextCallType').fadeOut();
    $('#divNextCallRemarks').fadeOut();
    $('#divRequestSubject').fadeOut();
    $('#divRequestNote').fadeOut();
    $('#divRequestDocuments').fadeOut();

    $('#divRemarks').fadeIn();
    $('#divReason').fadeIn();
}
function checklist() {
    $('#divUser').fadeIn();
    if($callType.val() == 13) {
        //Assign Checklist
        $('#divChecklistDate').fadeIn();
    } else if ($callType.val() == 14) {
        //Action Checklist
        $('#divProgress').fadeIn();
    }
}
$(function() {
    // bind property name autocomplete
    $('#TenderName').autocomplete({
        lookup: arrEnquiryNames,
        showNoSuggestionNotice: false,
        lookupFilter: function (suggestion, originalQuery, queryLowerCase) {
            if (queryLowerCase == '*') {
                return suggestion.value;
            } else {
                var re = new RegExp($.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
                return re.test(suggestion.value);
            }
        },
        onSelect: function (suggestion) {
            if (suggestion) {
                $enquiryId.val(suggestion.data);
                $enquiryName.val(suggestion.value);
                ShowCallType();
                //updateDetails(suggestion.data);
                $(this).removeClass('error');
            }
        },
        onSearchStart: function (suggestion) {
            $enquiryId.val(0);
            $enquiryName.val('');
        },
        onSearchComplete: function (query, suggestions) {
            if (!suggestions.length) {
                $(this).addClass('error');
                $enquiryId.val(0);
                $enquiryName.val('');
            } else
                $(this).removeClass('error');
        }
    });

    $natureEnquiry.autocomplete({
        lookup: arrNatureEnquiry,
        showNoSuggestionNotice: false,
        lookupFilter: function (suggestion, originalQuery, queryLowerCase) {
            if (queryLowerCase == '*') {
                return suggestion.value;
            } else {
                var re = new RegExp($.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
                return re.test(suggestion.value);
            }
        },
        onSelect: function (suggestion) {
            if (suggestion) {
                $natureEnquiryId.val(suggestion.data);
                $(this).removeClass('error');
            }
        },
        onSearchStart: function (suggestion) {
            $natureEnquiryId.val(0);
        },
        onSearchComplete: function (query, suggestions) {
            if (!suggestions.length) {
                $(this).addClass('error');
                $natureEnquiryId.val(0);
            } else
                $(this).removeClass('error');
        }
    });

    //Reason Input auto completed
    $Reason.autocomplete({
        lookup: arrReason,
        showNoSuggestionNotice: false,
        lookupFilter: function (suggestion, originalQuery, queryLowerCase) {
            if (queryLowerCase == '*') {
                return suggestion.value;
            } else {
                var re = new RegExp($.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
                return re.test(suggestion.value);
            }
        }
    });

    var iEnquiryId = <?php if(isset($EnquiryId)) echo json_encode($EnquiryId); else echo "0";?>;
    if (parseInt(iEnquiryId) !=0) updateDetails(iEnquiryId);
});

$('#EnquiryName').on('change', function() {
    var iEnquiryId = isNullCheck($('#EnquiryId').val(),'number');
    if ($enquiryId !=0)$('#divCallType').show();
});

$("#submitData").click(function(){
    $("form").submit();
});

function entryValidate()
{
    if ($('#formfrom').val() == "title") return true;

    var enquiryId = $enquiryId.val();

    if($RefDate.val().length == 0) {
        alert('Ref Date is Required!');
        return false;
    }

    if($enquiryName.val().length == 0 || enquiryId.length == 0 || enquiryId == 0) {
        alert('Choose Enquiry Name!');
        return false;
    }

    var natureEnquiryId = $natureEnquiryId.val();
    if($natureEnquiry.val().length == 0 || natureEnquiryId.length == 0 || natureEnquiryId == 0) {
//		alert('Choose Nature of Enquiry!');
//		return false;
    }

    if($callType.find('option:selected').val().length == 0) {
        alert('Choose Enquiry Call Type!');
        return false;
    }

    if($callType.find('option:selected').val().length != 0 ) {

        //Assign CheckList
        if($callType.val() == 10 && $TenderAssignChecklist.find('option:selected').val().length == 0) {
            alert("Choose Tender Checklist");
            return false;
        }
        if($callType.val() == 9 && $TenderAssignChecklist.find('option:selected').val().length != 0) {
            if($checklistUser.find('option:selected').val().length == 0) {
                alert("Username is Required");
                return false;
            }
            if($checklistDate.val().length == 0) {
                alert("Checklist Date is Required");
                return false;
            }
        }
        //CheckList Action
        if($callType.val() == 10 && $TenderActionChecklist.find('option:selected').val().length == 0) {
            alert("Choose Tender Checklist");
            return false;
        }
        if($callType.val() == 10 && $TenderActionChecklist.find('option:selected').val().length != 0) {
            if($checklistUser.find('option:selected').val().length == 0) {
                alert("Username is Required");
                return false;
            }
            if($Progress.find('option:selected').val().length == 0) {
                alert("Progress is Required");
                return false;
            }
        }
        if($callType.val() == 16 && $RequestSubject.val().length == 0) {
            alert("Subject is Required");
            return false;
        }
        if($callType.val() == 16 && $RequestNote.val().length == 0) {
            alert("Note is Required");
            return false;
        }
        if($callType.val() == 17 && $RequestSubject.val().length == 0) {
            alert("Subject is Required");
            return false;
        }
        if($callType.val() == 17 && $RequestNote.val().length == 0) {
            alert("Note is Required");
            return false;
        }
    }
    if($remarks.val().length == 0) {
//		alert('Remarks is Required!');
//		return false;
    }

    if($nextCallRequired.is(':checked') && $nextCallDate.val().length == 0) {
        alert('Next Call Date is Required!');
        return false;
    }

    if($nextCallRequired.is(':checked') && $nextCallType.find('option:selected').val().length == 0) {
        alert('Next Call Type is Required!');
        return false;
    }

    if($nextCallRequired.is(':checked') && $nextCallRemarks.val().length == 0) {
        alert('Remarks for Next Call is Required!');
        return false;
    }
}

function hideHistory()
{
    $('#followWrapper').addClass('col-lg-offset-3');
    $('#historyWrapper').removeClass('active');
}

function updateDetails(id) {
    $.ajax({
        url: getBaseURL() + "project/followup/followup",
        async: false,
        data: {'EnquiryId': id},
        type: 'post',
        success: function (data, status) {
            if(!data)
                return;

            $('#historyDetails').html(data);
        }
    });
}

function enterButton(e)
{
    if (!e) e = window.event;
    var keyCode = e.keyCode || e.which;
    if (keyCode == '13') {
        submitProperty();
    }
}

function submitProperty() {
    var id = $enquiryId.val();
    if(id == 0) {
        alert('Select a property!');
        return;
    } else {
        $('#formfrom').val("title");
        $('#landfollowup').submit();
    }
}
$('.followupId').on('click',function(){
    var urlId = $(this).attr('data-index');
    $enquiryId.val(urlId);
    $('#EnquiryName').val($(this).text());
    $('#formfrom').val("title");
    $('#landfollowup').submit();
});
function callfollowup(id) {
    var enquiryId = $enquiryId.val();
    var CallTypeId = id;
    var Date = $RefDate.val();

    if ($RefDate.val().length == 0) {
        alert('Ref Date is Required!');
        $RefDate.focus();
        return;
    }
    if (id == 1) {
        //Document Purchase - 1
        window.location.href = getBaseURL() + "project/followup/document-purchase/" + enquiryId + "/" + CallTypeId;
    } else if (id==2) {
        //Document - 2
        window.location.href = getBaseURL() + "project/tender/document/" + enquiryId;
    } else if(id == 3) {
        //Site Visit / Investigation - 3
        window.location.href = getBaseURL() + "project/followup/site-investigation/"+enquiryId;
    } else if(id == 4) {
        //Technical Specification - 4
        window.location.href = getBaseURL() + "project/followup/technical-specification/"+enquiryId;
    } else if(id == 5) {
        //Pre-Bid Meeting - 5
        window.location.href = getBaseURL() + "project/tender/meeting/" + enquiryId + "/" + CallTypeId;
    } else if(id == 6) {
        //Pre-Qualification - 6
        window.location.href = getBaseURL() + "project/tender/pre-qualstatus/" + enquiryId + "/" + CallTypeId;
    } else if(id == 7) {
        //Technical - Bid Opening - 7
        window.location.href = getBaseURL() + "project/tender/pre-qualstatus/" + enquiryId + "/" + CallTypeId;
    } else if(id == 8) {
        //Commercial Bid - Opening - 8
        window.location.href = getBaseURL() + "project/tender/bidstatus/" + enquiryId;
    } else if(id == 9) {
        //Negotiation Meeting - 9
        window.location.href = getBaseURL() + "project/tender/meeting/" + enquiryId + "/" + CallTypeId;
    } else if(id == 101) {
        //Quotation - 101
        window.location.href = getBaseURL() + "project/tender/tender-quotation/" + enquiryId;
    } else if(id == 102) {
        //Order - 18
        window.location.href = getBaseURL() + "project/tender/workorder/" + enquiryId;
    } else if(id == 103) {
        //Order - 18
        var sQType =  isNullCheck($('#QuoteType').val(),'string');
        if (sQType =="Q") window.location.href = getBaseURL() + "project/tender/quantity-revision/" + enquiryId;
        else window.location.href = getBaseURL() + "project/tender/tender-quotation/" + enquiryId + "/0/revise";

    } else if(id == 104) {
        //Order - 18
        window.location.href = getBaseURL() + "project/tender/workorder/" + enquiryId + "/Amendment";
    } else if(id == 106) {
        //Order - 18
        window.location.href = getBaseURL() + "project/tender/tendersubmitform/" + enquiryId;
    }
}
</script>