<?php echo $this->doctype(); ?>
<!--[if lt IE 7 ]><html class="no-js ie ie6" lang="en"><![endif]-->
<!--[if IE 7 ]><html class="no-js ie ie7" lang="en"><![endif]-->
<!--[if IE 8 ]><html class="no-js ie ie8" lang="en"><![endif]-->
<!--[if IE 9 ]><html class="no-js ie ie9" lang="en"><![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->
    <head>
		<!-- Meta Tags -->
		<?php echo $this->headMeta()
			->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8')
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0')
			->appendName('apple-mobile-web-app-capable', 'yes')
			->appendName('apple-mobile-web-app-status-bar-style', 'black')
            ->appendHttpEquiv('Cache-control', 'no-cache')
			->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
		<!-- Meta Tags -->
		
		<!-- Title -->
		<?php echo $this->headTitle()->setPrefix('BSF - '); ?>
		<!-- Title -->
       
        <!-- Css styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
			->appendStylesheet($this->basePath() . '/css/style.css')
			->appendStylesheet($this->basePath() . '/css/jquery_urlive.css')
			->appendStylesheet($this->basePath() . '/css/lightGallery.css')
			->appendStylesheet($this->basePath() . '/css/select2.min.css');
		?>
		<!-- Css styles -->
        <!-- JS Scripts -->
        <?php echo $this->headScript()
			/*Grid start*/
			->appendFile($this->basePath() . '/js/jquery-1.11.1.min.js')
			->appendFile($this->basePath() . '/js/bootstrap.min.js')
			->appendFile($this->basePath() . '/js/global.js')
			->appendFile($this->basePath() . '/js/slimscroll.js')
			->appendFile($this->basePath() . '/js/jquery_urlive.min.js')
			->appendFile($this->basePath() . '/js/lightGallery.min.js')
			->appendFile($this->basePath() . '/js/jquery.materialripple.js')
			->appendFile($this->basePath() . '/js/select2.full.min.js')
			//->appendFile('http://www.ip-api.com/json?callback=GetUserGeo')
            ->prependFile($this->basePath() . '/js/html5','text/javascript', array('conditional' => 'lt IE',));	
        ?>
		<!-- JS Scripts -->
    </head>
    <body>
		<div class="wrapper">
			<!------------------------loader area------------------------>
			<div class="loading_area">
				<div class="loading_circle"></div>
			</div>
			<!------------------------loader area------------------------>
			
			<!------------------------header area------------------------>
				<?php echo $this->partial('application/partial/header.phtml', array()); ?>
			<!------------------------header area------------------------>
			
			<!------------------------content section------------------------>
			<section class="content actvt_content actvt_top90">
				<?php echo $this->content; ?>
				<?php echo $this->partial('application/partial/footer.phtml', array()); ?>
			</section>
			<!------------------------content section------------------------>
		</div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
