<aside class="left-panel open <?php if($this->currentRequest()->get('module') == 'Application' && $this->currentRequest()->get('action') == 'dashboard') { echo 'actvt_top90'; } ?>">
	<nav class="navigation" id="hint-step5">
		<?php if($this->currentRequest()->get('module') != 'Cb') { ?>
		<ul>
			<li><a href="<?php echo $this->basePath(); ?>/application/index/activity-stream" class="ripple"><i class="fa fa-book"></i><span class="nav-label">Activity Stream</span></a></li>
			<li><a href="<?php echo $this->basePath(); ?>/application/index/dashboard" class="ripple"><i class="fa fa-tachometer"></i><span class="nav-label">Dashboard</span></a></li>
			<!--li class="current"><a href="javascript:void(0);" class="ripple"><i class="fa fa-pencil-square-o"></i><span class="nav-label">New Lead</span></a></li>
			<li><a href="javascript:void(0);" class="ripple"><i class="fa fa-university"></i><span class="nav-label">Organization</span></a></li>
			<li><a href="javascript:void(0);" class="ripple"><i class="fa fa-flag"></i><span class="nav-label">Favorites</span></a></li>
			<li><a href="javascript:void(0);" class="ripple"><i class="fa fa-calendar-o "></i><span class="nav-label">Calendar</span></a></li>
			<li><a href="javascript:void(0);" class="ripple"><i class="fa fa-camera"></i><span class="nav-label">Project images</span></a></li-->
		</ul>
		<?php } ?>
		<?php 
			$moduleNavPath = lcfirst($this->currentRequest()->get('module')).'/partial/module-navigation.phtml';
			echo $this->partial($moduleNavPath, array()); 
		?>
	</nav>
</aside>