<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/select2.full.min.js"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/select2.min.css" />
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/workorder.css';?>"/>
<form name="followup-details" class="form-horizontal stginner_cnt" method="post">
    <div>
        <input type="hidden" name="entryId" id="EntryId" value="<?php echo $responseFollow['EntryId']?>"/>
        <input type="hidden" name="unitidCount" id="unitidCount" value="<?php echo $unitCount['Count']?>"/>
        <input type="hidden" name="caller_sid" id="caller_sid" value="<?php echo (isset($callSid)) ? $callSid : ''?>" />



        <div class="showDiv" id="Details">
            <div class="content_wrapper padlr0">
                <div class="container-fluid padlr0">
                    <div class="col-lg-12">
                        <h1>Followup Details
                            <div class="btn-group proname_btn">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"><?php echo ucfirst($responseLead['LeadName']);?> <span class="edit_symbols" data-placement="right" data-toggle="tooltip" data-original-title="Change&nbsp;Followup&nbsp;Name"><i class="fa fa-caret-down "></i></span></a>
                                <div class="dropdown-menu toolbar_ddown proname_ddown arrow" role="menu">
                                    <ul>
                                        <?php
                                        foreach($resultsLeadData as $leadData){?>
                                            <li><a href="javascript:void(0);" class="followupId" data-index="<?php echo $leadData['LeadId'];?>"><?php echo ucfirst($leadData['LeadName']);?></a></li>
                                        <?php }	?>
                                    </ul>
                                </div>
                            </div>
                        </h1>
                    </div>
                    <div class="col-lg-12 flwup_topcnt clear" id="followDetails">
                        <div class="col-lg-6 col-md-6 col-sm-12 padlr0">
                            <div class="col-lg-4 flwup_proimg_area">
                                <div class="flwup_proimg brad_200">
                                    <?php
                                    if($responseLead['VIP'] == 1){ ?>
                                        <div class="img_star brad_50">
                                            <span class="glyphicon glyphicon-star txt_center"></span>
                                        </div>
                                    <?php }
                                    if( $responseLead['Photo'] != '') {
                                        $photo="../".$responseLead['Photo'];
                                        ?>
                                        <img src="<?php echo $this->basePath(); ?>/<?php echo $photo;?>" class="brad_200" alt="" title=""/>
                                    <?php } else { ?>
                                        <img src="<?php echo $this->basePath(); ?>/images/avatar.jpg" class="brad_200" alt="" title=""/>
                                    <?php } ?>
                                </div>
                                <p class="txt_center"><span class="p_label">Type :</span> <?php if(!empty($responseLead['LeadTypeName'])){echo $responseLead['LeadTypeName'];}else{echo"-";}?></p>
                            </div>
                            <div class="col-lg-8 col-md-12 flwup_procnt">
                                <input type="hidden" name="leadId" id="LeadId"  value="<?php echo $responseLead['LeadId']; ?>">
                                <h1><?php if(!empty($responseLead['LeadName'])){echo ucfirst($responseLead['LeadName']);}else{echo"-";}?><br />
                                    <span><?php if(!empty($responseLead['LeadDate'])){echo $responseLead['LeadDate'];}else{echo"-";}?></span>
                                </h1>
                                <p><span class="p_label">Executive Name :</span> <?php if(!empty($responseLead['UserName'])){echo $responseLead['UserName'];}else{echo"-";}?></p>
                                <ul>
                                    <li><a href="javascript:void(0);" class="fullDetails" data-index="<?php echo $responseLead['LeadId'];?>"><span><i class="fa fa-search-plus"></i></span> View Details</a></li>
                                    <li><a href="javascript:void(0);" class="editId" data-index="<?php echo $responseLead['LeadId'];?>"><span><i class="fa fa-edit"></i></span>View Buyer History</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-6 flwup_rightcnt">
                            <h2>Contact Details
                                <div class="stgedit_btn h2_circle brad_50"><span><i class="fa fa-book"></i></span></div>
                            </h2>
                            <div class="clr_bbdr"></div>
                            <div class="flwup_rightcnt_inner">
                                <ul class="flwup_rcnt_inrdetail">
                                    <li><a href="javascript:void(0);" onclick="callModal('<?php echo $responseLead['Mobile']; ?>');" data-toggle="modal" style="color:#3f4c5e;">+91<span class="flwup_rcnt_num"><?php if(!empty($responseLead['Mobile'])){echo $responseLead['Mobile'];}else{echo"-";}?></span><span class="inner_ricon inr_ri_mt7 float_r"><i class="fa fa-phone"></i></span></a></li>
                                    <li><span class="flwup_rcnt_mail" id="flwup_mail"> </span><?php if(!empty($responseLead['Email'])){echo $responseLead['Email'];}else{echo"-";}?><span class="inner_ricon float_r"><i class="fa fa-envelope"></i></span></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-6 flwup_rightcnt">
                            <h2>Projects
                                <div class="stgedit_btn h2_circle brad_50"><span><i class="fa fa-briefcase"></i></span></div>
                            </h2>
                            <div class="clr_bbdr"></div>
                            <div class="flwup_rightcnt_inner">
                                <?php if(!empty($resultMultiProject) > 0){?>
                                    <ul class="flwup_rcnt_inrproject">
                                        <?php
                                        foreach($resultMultiProject as $resuCC){?>
                                            <li class="white_inner">
                                                <span class="pad_t3"><?php echo ucfirst($resuCC['ProjectName']['0']);?></span><p><?php echo $resuCC['ProjectName'];?></p>
                                            </li>
                                        <?php }	?>
                                    </ul>
                                <?php }else{echo'-';}?>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12 clear">
                        <div class="col-lg-6 m_tb10">
                            <div class="col-lg-8 col-lg-offset-2">
                                <div class="row">
                                    <div class="form-group">
                                        <div class="col-lg-12">
                                            <span class="date_icon"><i class="fa fa-calendar"></i></span>
                                            <input type="text" name="leadDate" id="LeadDate" readonly="readonly" class="form-control lbl_move datepickerinput" label="Date" value="<?php echo date("d-m-Y"); ?>" />
                                            <!--<div class="error_message"><p>please enter date...</p></div>-->
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-lg-12">
                                            <select name="callType" id="UnitTypeId" class="single_dropdown2 lbl_move" style="width:100%;" data-size="5" label="Call Type">
                                                <option value="">Choose Call Type</option>
                                                <?php
                                                foreach($resultsCall as $type){ ?>
                                                    <option value="<?php echo $type['CallTypeId'] ?>" ><?php echo $type['Description'] ?></option>
                                                <?php } ?>
                                            </select>
                                            <div class="error_message"><p>please select call type...</p></div>
                                        </div>
                                    </div>
                                    <div class="form-group"  id="unit" style="display:none;">
                                        <div class="col-lg-12">
                                            <select name="unitNo" id="unitNoId" onchange="valFunc($(this).val());" class="single_dropdown2 lbl_move" style="width:100%;" data-size="5" label="UnitName">

                                            </select>
                                            <div class="error_message"><p>please select unitname...</p></div>
                                        </div>
                                    </div>
                                    <div id="sam">
                                        <div class="form-group">
                                            <div class="col-lg-12">
                                                <select name="natureId" id="natureId" class="single_dropdown2 lbl_move" style="width:100%;" data-size="5" label="Nature">
                                                    <option value="">Choose Nature</option>
                                                    <?php
                                                    foreach($resultsNature as $type){ ?>
                                                        <option value="<?php echo $type['NatureId'] ?>" ><?php echo $type['Description'] ?></option>
                                                    <?php } ?>
                                                </select>
                                                <div class="error_message"><p>please select Nature...</p></div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-lg-12">
                                                <span class="date_icon"><i class="fa fa-calendar"></i></span>
                                                <input type="text" name="nextCallDate" readonly="readonly" id="NextCallDate" class="form-control lbl_move datepickerinput" label="Next Followup Date" />
                                                <!-- <div class="error_message"><p>please enter next followup date...</p></div>-->
                                            </div>
                                        </div>
                                        <div class="form-group sam">
                                            <div class="col-lg-12">
                                                <select name="nextFollowUpTypeId" id="FollowUp" class="single_dropdown2 lbl_move" style="width:100%;" data-size="5" label="Next Followup Type">
                                                    <option value="">Choose Next Followup Type</option>
                                                    <?php
                                                    foreach($resultsCall as $type){ ?>
                                                        <option value="<?php echo $type['CallTypeId'] ?>" ><?php echo $type['Description'] ?></option>
                                                    <?php } ?>
                                                </select>
                                                <div class="error_message"><p>please select next followup type...</p></div>
                                            </div>
                                        </div>
                                        <div class="form-group" id="radios">
                                            <div class="col-lg-12">
                                                <label for="buyer" class="col-lg-6 txt_left col-md-6 control-label">Vehicle Required?</label>
                                                <div class="radio_check">
                                                    <p>
                                                        <input type="radio" value="1" id="yes" name="vehicleAllocation" onclick="return showData();" />
                                                        <label for="yes" class="ripple">Yes</label>
                                                    </p>
                                                    <p>
                                                        <input type="radio" value="2" id="no" name="vehicleAllocation" onclick="return removeData();" />
                                                        <label for="no" class="ripple">No</label>
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group" id="pkTime">
                                            <div class="col-lg-12">
                                                <input type="text" name="pickUpTime" id="PickUpTime" style="width:100%;" class="form-control lbl_move" label="Enter Pickup Time" />
                                                <div class="error_message"><p>please enter pickup time...</p></div>
                                            </div>
                                        </div>
                                        <div class="form-group" id="pkAddress">
                                            <div class="col-lg-12">
                                                <input type="text" name="pickUpAddress" id="address" style="width:100%;" class="form-control lbl_move" label="Enter Pickup Address" />
                                                <div class="error_message"><p>please enter pickup address...</p></div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-lg-12">
                                                <textarea name="nextfollowremarks" id="nextfollowremarks" style="width:100%;" class="form-control lbl_move" label="NextFollowupRemarks"></textarea>
                                                <div class="error_message"><p>please enter remarks...</p></div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-lg-12">
                                                <select name="actionRequiredBy" id="ActionRequiredBy" style="width:100%;" class="single_dropdown2 lbl_move" data-size="5" label=" Next Followup Executive">
                                                    <option value="">Choose Next Followup Executive</option>
                                                    <?php
                                                    foreach($resultsExecutive as $type){
                                                        if(count($responseLead) > 0){
                                                            echo "<option ".($responseLead['ExecutiveId']== $type['UserId']? 'selected':'')." value='".$type['UserId']."' >".$type['UserName']."</option>";
                                                        }
                                                        else{
                                                            echo "<option value='".$type['UserId']."' >".$type['UserName']."</option>";
                                                        }
                                                    }
                                                    ?>
                                                </select>
                                                <div class="error_message"><p>please select executive name...</p></div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <textarea id="remarks" name="remarks" class="form-control lbl_move" label="Remarks"/></textarea>
                                        <div class="error_message"><p>please enter remarks...</p></div>
                                    </div>
                                    <div class="col-lg-12 savebtn_area m3_auto no_border">
                                        <ul>
                                            <!--<li class="save_btn m_auto">
                                                <!----<a class="ripple continue" id="continue" name="continue" href="javascript:void(0);">Proceed</a>
                                                <button type="button" class="continue ripple" id="continue" name="continue">Continue</button>
                                                 <a href="javascript:void(0);" class="ripple continue">Proceed</a>
                                            </li>-->
                                            <li>
                                                <div class="next-bt">
                                                    <a  href="<?php echo $this->basePath(); ?>/crm/buyer/followup-entry"  id="back-btn" class="pull-left"><i class="fa fa-times-circle"></i> Close</a>
                                                    <a id="save-btn" href="javascript:void(0);" class="pull-right continue">Proceed <i class="fa fa-chevron-circle-right"></i></a>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 m_tb10">
                            <div class="form-group">
                                <div class="col-lg-12">
                                    <div class="stginner_h5">
                                        <h5>Last Followup Details
                                            <div class="stgedit_btn brad_50"><a href="javascript:void(0);" class="ripple personal" data-index="<?php echo $responseFollow['EntryId'];?>"><span><i class="fa fa-pencil"></i></span></a></div>
                                        </h5>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <label for="first_name" class="col-lg-4 padlr0 col-md-4 txt_left control-label">Executive Name</label>
                                            <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                                <p><?php if(!empty($responseFollow['UserName'])){echo $responseFollow['UserName'];}else{echo"-";}?></p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <label for="first_name"  class="col-lg-4 padlr0 col-md-4 txt_left control-label">Call Type</label>
                                            <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                                <p><?php if(!empty($responseFollow['call'])){echo $responseFollow['call'];}else{echo"-";}?></p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <label for="first_name"  class="col-lg-4 padlr0 col-md-4 txt_left control-label">Status</label>
                                            <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                                <p><?php if(!empty($responseFollow['state'])){echo $responseFollow['state'];}else{echo"-";}?></p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <label for="first_name"  class="col-lg-4 padlr0 col-md-4 txt_left control-label">Nature Type</label>
                                            <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                                <p><?php if(!empty($responseFollow['Nat'])){echo $responseFollow['Nat'];}else{echo"-";}?></p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <label for="first_name"  class="col-lg-4 padlr0 col-md-4 txt_left control-label">Followup Date</label>
                                            <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                                <p><?php if(!empty($responseFollow['NextCallDate'])){echo $responseFollow['NextCallDate'];}else{echo"-";}?></p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <label for="first_name"  class="col-lg-4 padlr0 col-md-4 txt_left control-label">Followup Type</label>
                                            <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                                <p><?php if(!empty($responseFollow['Nature'])){echo $responseFollow['Nature'];}else{echo"-";}?></p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <label for="first_name"  class="col-lg-4 padlr0 col-md-4 txt_left control-label">Followup Remarks</label>
                                            <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                                <p><?php if(!empty($responseFollow['NextFollowupRemarks'])){echo $responseFollow['NextFollowupRemarks'];}else{echo"-";}?></p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <label for="first_name"  class="col-lg-4 padlr0 col-md-4 txt_left control-label">Remarks</label>
                                            <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                                <p><?php if(!empty($responseFollow['Remarks'])){echo $responseFollow['Remarks'];}else{echo"-";}?></p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

</form>


<script>
    $(".showDiv").hide();
    $("#Details").show();
    $("#LeadId").hide();

    $('#ProjectsId').on('change', function() {
        //alert("hi");
        var id = $(this).val();
        if(id !=-1){
            $('#LeadId').show();
        }
        else{
            $('#LeadId').hide();
        }
    });
    $(document).ready(function() {
        $("#unitNoId").hide();
        $('#UnitTypeId').on('change',function() {
            var callTypeId = parseInt($(this).val());
            if(callTypeId==12) {
                $(location).attr('href', "<?php echo $this->basePath(); ?>/crm/buyer/agreement-generation/<?php echo $BuyerId; ?>/5");

            }else if(callTypeId==14) {
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/buyer/agreement-generation/<?php echo $BuyerId; ?>/6");

            } else if(callTypeId==16) {
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/buyer/agreement-generation/<?php echo $BuyerId;?>/7");

            }else if(callTypeId==21) {
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/buyer/allotment-letter/<?php echo $BuyerId;?>");

            } else if(callTypeId==19) {
                if( $('#unitidCount').val()== 0){
                    alert('No data for unitType');
                    $('#UnitTypeId').trigger('select');
                    return;
                }
                else{
                    $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/buyer/handingover/<?php echo $BuyerId; ?>/"+ callTypeId);
                }
            }
        });
    });

    $('.datepickerinput').datepicker({
        format: "dd-mm-yyyy",
        startDate: new Date(),
        todayBtn: true,
        orientation: "top auto",
        autoclose: true
    });
    $('.datepickerlead').datepicker({
        format: "dd-mm-yyyy",
        endDate: new Date(),
        todayBtn: true,
        autoclose: true
    });
</script>
<script>
    /* Page Validate and others */
    $(".continue").click(function(){
        $('.error_message').hide();
        var ele = $(".showDiv:visible");
        $(".error").text("");
        var bool = true;
        ele.find("input,checkbox, select, textarea").each(function(){
            var tagname = $(this).prop("tagName").toLowerCase();
            if(tagname == 'input'){
                var type = $(this).attr("type");
                if(type == 'text'){
                    if($(this).is(":visible") && $(this).val().trim() == ''){
                        bool=false;
                        $(this).closest('.polymer-form').next(".error_message").show();
                        $(this).focus();
                        return false;
                    }
                }  else if(type == 'radio'){
                    if($(this).is(":visible") && $(this).val().trim() == ''){
                        bool=false;
                        $(this).closest('.polymer-form').next(".error_message").show();
                        $(this).focus();
                        return false;
                    }
                }
            } else if(tagname == 'select'){
                if($(this).is(":visible")){
                    if ($(this).val() == "" || $(this).val() == null){
                        bool = false;
                        $(this).closest('.form-group').find(".error_message").show();
                        $(this).focus();
                        return false;

                    }}
            } else if(tagname == 'textarea'){
                if($(this).is(":visible")){
                    if($(this).val().trim().length == 0){
                        bool = false;
                        $(this).closest("div").next(".error_message").text($(this).attr("error_message"));
                        $(this).focus();
                        return false;
                    }
                }
            } else {
                $(".error_message").remove();
            }
        });
        if(bool){
            if($(".showDiv:visible").index() != $(".showDiv:last").index()){
                $(".showDiv:visible").next(".showDiv").show();
                ele.hide();
                if($(".showDiv:Visible").index()){
                    $(this).text("submit");
                }
            }
            else{
                $('form').submit();
            }
        }
    });
</script>

<script>

    $('#FollowUp').on('change', function() {
        var sname = $("#FollowUp option:selected").text();
        if(sname=='Sitevisit'){
            $('#radios').show();
        } else {
            $('#radios').hide().find('radio').val('');
            $('#pkTime').hide().find('input:text').val('');
            $('#pkAddress').hide().find('textarea').val('');
        }
    }).change();

    $('#UnitTypeId').on('change', function() {
        var leadId=$("#LeadId").val();
        var cname = $("#UnitTypeId").val();
        if(cname==10 || cname==11) {
            var mode = "getunit";
            $('#sam').hide();
            $('#unit').show();
        }else if(cname=='13') {
            var  mode="construct";
            $('#sam').hide();
            $('#unit').show();
        }else  if(cname=='15') {
            var  mode="land";
            $('#sam').hide();
            $('#unit').show();
        }else if(cname == '17'){
            var  mode="sale";
            $('#sam').hide();
            $('#unit').show();
        }else if(cname == '20'){
            var mode="new";
            $('#sam').hide();
            $('#unit').show();
        }else if(cname == '18') {
            var mode = "reg";
            $('#sam').hide();
            $('#unit').show();
        } else{
            var mode = "";
            $('#sam').show();
            $('#unit').hide();
        }
        if(mode != ''){
            $.ajax({
                url:getBaseURL()+"crm/buyer/followup",
                type: "post",
                data: {'mode':mode,'LeadId': leadId},
                success: function (data, textStatus, jqXHR) {
                    $('#unitNoId').html('');
                    var opHtml = '<option value=""></option>';
                    var valu = JSON.parse(data);
                    $.each(valu,function(i,o){
                        opHtml += '<option value="'+o.UnitId+'">' +o.UnitNo+'</option>';
                    });
                    $('#unitNoId').html(opHtml);
                }
            });
        }
    });
    function valFunc(val) {
        if(val!="") {
            var leadId=$("#LeadId").val();
            var cname = $("#UnitTypeId").val();
            if(cname==10) {
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/lead/unit-transfer/"+val+"/0/"+cname);

            } else if(cname==11) {
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/lead/unit-cancellation/"+leadId+"/"+val);

            }
        }
    }
    function showData(){
        $('#pkTime').show();
        $('#pkAddress').show();
    }
    function removeData(){
        $('#pkTime').hide().find('input:text').val('');
        $('#pkAddress').hide().find('textarea').val('');
    }

    $(document).ready(function() {
        $(".single_dropdown2").select2({
            placeholder: "",
            allowClear: true
        });
    });
</script>



<script>
    $('.fullDetails').on('click',function(){
        var urlId = $(this).attr('data-index');
        location.replace("<?php echo $this->basePath(); ?>/crm/buyer/full-details/"+urlId);
    });
    $('.editId').on('click',function(){
        var urlId = $(this).attr('data-index');
        location.replace("<?php echo $this->basePath(); ?>/crm/lead/followup-history/"+urlId);
    });
    $('.personal').on('click',function(){
        var urlId = $(this).attr('data-index');
        location.replace("<?php echo $this->basePath(); ?>/crm/buyer/followup-details/"+urlId);
    });
    $('.followupId').on('click',function(){
        var urlId = $(this).attr('data-index');
        location.replace("<?php echo $this->basePath(); ?>/crm/buyer/followup/"+urlId);
    });


</script>
