
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/mms.css';?>"/>
<style type="text/css">

.icon-bg {line-height: 77px !important;right: 4px !important;}
	/*---------0----------*/
.card {
  position: relative;
  float: left;
  padding-bottom: 30%;
  width: 100%;
}

/* card text */
.card__text {
	width:100%;
}
	
/* card fronts and backs */
.card__front,
.card__back {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}

.card__front,
.card__back {
  -webkit-backface-visibility: hidden;
          backface-visibility: hidden;
  -webkit-transition: -webkit-transform 0.5s;
          transition: transform 0.5s;
}

.card__front {
  background-color: #F18F01;
}

.card__back {
  background-color: #F18F01;
  -webkit-transform: rotateX(-180deg);
          transform: rotateX(-180deg);
}
/* random effect */
.card.effect__random.flipped .card__front {
  -webkit-transform: rotateX(-180deg);
          transform: rotateX(-180deg);

}

.card.effect__random.flipped .card__back {
  -webkit-transform: rotateX(0);
          transform: rotateX(0);
}
/*---------0----------*/
/*---------1----------*/
.card1 {
  position: relative;
  float: left;
  padding-bottom: 30%;
  width: 100%;
  text-align: center;
}

/* card text */
.card1__text {
	width:100%;
}

/* card fronts and backs */
.card1__front,
.card1__back {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  text-align:center;
}

.card1__front,
.card1__back {
  -webkit-backface-visibility: hidden;
          backface-visibility: hidden;
  -webkit-transition: -webkit-transform 0.5s;
          transition: transform 0.5s;
}

.card1__front {
  background-color: #006e90;
}

.card1__back {
  background-color: #006e90;
  -webkit-transform: rotateX(-180deg);
          transform: rotateX(-180deg);
}

/* random effect */
.card.effect__random.flipped .card1__front {
  -webkit-transform: rotateX(-180deg);
          transform: rotateX(-180deg);
}

.card.effect__random.flipped .card1__back {
  -webkit-transform: rotateX(0);
          transform: rotateX(0);
}
/*---------1----------*/
.rolly{float:right;color:#f0b866;font-size:60px;margin-right:4px;margin-top:10px;}
.rollb{float:right;color:#59a9c1;font-size:60px;margin-right:4px;margin-top:10px;}
.pro_det{font-size:17px;float:left;padding-top:25px;font-weight:600!important;}
.pro_no{font-size:16px;text-align:center;font-weight:600!important;padding-top:25px;}
.pro_dety{color:#f0b866;}
.pro_noy{color:#f0b866;}
.pro_detb{color:#59a9c1;}
.pro_nob{color:#59a9c1;}

.detcardhdng {
    background: #fff;
    margin-bottom: 5px;
    position: relative;
    padding: 10px 13px 0;
    border-radius: 2px;
}
.g{color:#558b08;}
.p{color:#9743c1;}
.y{color:#e29f27;}
.b{color:#4399d6 ;}
pnnal-heading

</style>

<div class="container-fluid">
<h1 class="commargin_ttop_20">Dashboard</h1>
<div class="tagcrd">
	<ul>
		<li class="mnimumwidthres90">
			<div class="detcardhdng pnl-overflow mmsbrdrclr1">
				<div class="icon-bg g"><i class="fa fa-cog fa-spn"></i></div>
				<h2 class="comtex mmsbrdrclrhed1 commargin_bottom_5 comnelips" style="font-weight:600 !important;">Project Name</h2>
				<h5 class="tetmuted tet-clr11 comnelips">1</h5>
			</div>
		</li>
		<li class="mnimumwidthres90">
			<div class="detcardhdng pnl-overflow mmsbrdrclr2">
				<div class="icon-bg p"><i class="fa fa-minus-circle fa-spin"></i></div>
				<h2 class="comtex mmsbrdrclrhed2 commargin_bottom_5 comnelips" style="font-weight:600 !important;">Vendor Name</h2>
				<h5 class="tetmuted tet-clr11 comnelips">2</h5>
			</div>
		</li>
		<li class="mnimumwidthres90">
			<div class="detcardhdng pnl-overflow mmsbrdrclr3">
				<div class="icon-bg y"><i class="fa fa-superpowers fa-spin"></i></div>
				<h2 class="comtex mmsbrdrclrhed3 commargin_bottom_5 comnelips" style="font-weight:600 !important;">Project No</h2>
				<h5 class="tetmuted tet-clr11 comnelips">3</h5>
			</div>
		</li>
		<li class="mnimumwidthres90">
			<div class="detcardhdng pnl-overflow mmsbrdrclr4">
				<div class="icon-bg b"><i class="fa fa-crosshairs fa-spin"></i></div>
				<h2 class="comtex mmsbrdrclrhed4 commargin_bottom_5 comnelips" style="font-weight:600 !important;">Vendor No</h2>
				<h5 class="tetmuted tet-clr11 comnelips">4</h5>
			</div>
		</li>
	</ul>
</div>
<div class="col-lg-12 commargin_ttop_20 clear">
	<div class="col-lg-6">
		<section class="pnnal">
			<header class="pnnal-heading"><i class="fa fa-sitemap"></i>MMS</header>
			<div class="pnnal-body">
			Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
			Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
			when an unknown printer took a galley of type and scrambled it to make a type specimen book. 
			It has survived not only five centuries, but also the leap into electronic typesetting, 
			remaining essentially unchanged. It was popularised in the 1960s with the release of 
			Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing 
			software like Aldus PageMaker including versions of Lorem Ipsum.
				<div id="secchartdiv"></div>
			</div>
		</section>
	</div>
	<div class="col-lg-6">
		<section class="pnnal">
			<header class="pnnal-heading"><i class="fa fa-external-link"></i>@site</header>
			<div class="pnnal-body">
			Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
			Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
			when an unknown printer took a galley of type and scrambled it to make a type specimen book. 
			It has survived not only five centuries, but also the leap into electronic typesetting, 
			remaining essentially unchanged. It was popularised in the 1960s with the release of 
			Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing 
			software like Aldus PageMaker including versions of Lorem Ipsum.
				<div id="thrdchartdiv"></div>
			</div>
		</section>
	</div>
</div>
<div class="col-lg-12 commargin_ttop_20 clear">
	<div class="col-lg-12">
		<section class="pnnal">
			<header class="pnnal-heading"><i class="fa fa-database"></i>Ats</header>
			<div class="pnnal-body">
			Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
			Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
			when an unknown printer took a galley of type and scrambled it to make a type specimen book. 
			It has survived not only five centuries, but also the leap into electronic typesetting, 
			remaining essentially unchanged. It was popularised in the 1960s with the release of 
			Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing 
			software like Aldus PageMaker including versions of Lorem Ipsum.
				<div id="secchartdiv"></div>
			</div>
		</section>
	</div>
</div>
<!--<div class="col-lg-12">
	<div class="col-lg-3">
		<div class="card effect__random" data-id="1">
			<div class="card__front">
				<span class="card__text">
				<h2 class="pro_det pro_dety">TOTAL PROJECTS</h2>
				<i class="fa fa-snowflake-o fa-spin fa-3x fa-fw rolly"></i>
				</span>
			</div>
			<div class="card__back">
				<span class="card__text">
				<h5 class="pro_no pro_noy">25881</h5>
				</span>
			</div>
		</div>
	</div>
	<div class="col-lg-3">
		<div class="card effect__random" data-id="2">
			<div class="card1__front">
				<span class="card1__text">
				<h2 class="pro_det pro_detb">PROJECT COST</h2>
				<i class="fa fa-life-ring fa-spin fa-3x fa-fw rollb"></i>
				</span>
			</div>
			<div class="card1__back">
				<span class="card1__text">
				<h5 class="pro_no pro_nob">1,20,000</h5>
				</span>
			</div>
		</div>
	</div>
</div>-->
</div>