
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/mms.css';?>"/>
<style type="text/css">

.newlead_notifi									{color:#1f1f20; border:1px solid #f6e39e; background-color:#f7eecb; margin-top:3px; margin-bottom:15px;font-size:14px; padding:2px 10px 2px 4px !important;}
.newlead_notifi span 							{padding:2px 8px; margin-right:5px; color:#fff; display:inline-block; background-color:#58a756;}
/*-----------------------crm Dashboard---------------------*/
.pnl 														{margin-bottom: 20px;position: relative;background: #fff;box-shadow: 1px 1px 0 0 rgba(50, 50, 50, 0.23);}
.pnl-overflow 												{overflow: hidden;}
.icon-bg 													{font-size: 100px;line-height: 121px;opacity: 0.5;position: absolute;right: 0;top: 0; z-index:9;}
.i-text-one													{color: #a8e9ea  !important;}
.i-text-two													{color: #f1c9a9    !important;}
.i-text-thr													{color: #c1db9c   !important;}
.i-text-four												{color: #c7b7e5   !important; }
.i-text-five 												{color: #e2c7d7    !important; }
.i-text-six 												{color: #bad2dc   !important; }
.comtex														{line-height: 0 px !important;color: #000;font-size: 15px !important;padding: 6px 0 6px !important; font-weight:500 !important; position:relative; z-index:99;}
.tet-clr1													{color: #000 !important;}
.tet-clr2													{color: #000 !important;}
.tet-clr3													{color: #000 !important;}
.tet-clr4													{color: #000 !important;}
.tet-cllr1													{background-color: #2dc5c7  !important;}
.tet-cllr2													{background-color: #fbb882  !important;}
.tet-cllr3													{background-color: #a8c77b   !important;}
.tet-cllr4													{background-color: #d099b9  !important;}
.tet-muted													{font-size: 20px;color: #777;font-weight: 600 !important;padding: 10px 3px 9px !important; position:relative; z-index:99;}
.tet-mutedclr1												{color:#0b9395;}
.tet-mutedclr2												{color:#d38241;}
.tet-mutedclr3												{color:#586a3e;}
.tet-mutedclr4												{color:#685788;}
.tet-mutedclr5												{color:#ab7393;}

	/*panel*/
	.flip {width:100%;cursor:pointer;padding: 5px; text-align:center;background-color: #aee024;border: solid 1px #71960a;}
	.pane {display: none;width:100%;height:240px;cursor:pointer;padding: 5px;text-align: center;background-color: #04456e;border: solid 1px #3580c4;border-radius:0px !important;}
	.pane ul {width:100%; float:left;}
    .pane ul li  {width:100%; padding-bottom:5px; float:left;}
    .pane ul li label {font-size:13px; color:#fff;  float:left; text-align:left; width:60px; padding-left: 6px;}
    .pane ul li span input[type=text] {border:none;font-size:13px; color:#266aa8; width:100px;white-space: nowrap;overflow: hidden;text-overflow:ellipsis; }
	/**/
	.flt_rt{float:right !important;}

.vendor_subscriber {
    padding-top:15px;
	height: 200%!important;
	
}
.pref_vendor {
    background: #ccc none repeat scroll 0 0;
    float: left;
    margin: 3px;
    padding: 10px !important;
    width: 100%;
	min-height: 253px !important;
	max-height: 520px !important;
    opacity: 0.5;
	text-align:center;
	cursor:pointer;
	}

.pref_vendor:hover {
    background: #fff none repeat scroll 0 0;
}
.info{height:343px !important;}
.hed{color:#f00;font-size:16px;}
.par{color:#000;font-size:14px;font-weight:bold;}
.panel-body {
    height: 200px !important;
	background:#3580c4;
}
.info-tooltip {
  background-color: #4183D7;
  color: #fff;
  vertical-align: baseline;
  font-size: 12px;
  padding: 0px 6px;
  border: 2px solid #4183D7;
  position: relative;
}
.info-tooltip:before {
  position: absolute;
  background-color: #fff;
  border: 1px solid #4183D7;
  padding: 5px 10px;
  min-width: 200px;
  max-width: 250px;
  height:25px;
  bottom: 78%;
  left: 180%;
  transform: translateY(70%);
  content: attr(data-content);
  color: #f00;
  display: none;
  font-size: 13px;
  font-weight:600;
  border-radius: 2px;
  z-index: 100;
  text-align: center;
  line-height: 1;
  -webkit-animation: swooshUp 200ms cubic-bezier(0.25, 0.5, 0.5, 0.9);
  animation: swooshUp 200ms cubic-bezier(0.25, 0.5, 0.5, 0.9);
}
.info-tooltip:after {
  position: absolute;
  right: auto;
  bottom:50%;
  left: 60%;
  transform: translateY(60%);
  border-width: 10px 15px 10px 10px;
  border-color: transparent #4183D7 transparent transparent ;
  content: " ";
  display: none;
  margin: 0;
  border-style: solid;
  z-index: 3;
  -webkit-animation: swooshUp 200ms cubic-bezier(0.25, 0.5, 0.5, 0.9);
  animation: swooshUp 200ms cubic-bezier(0.25, 0.5, 0.5, 0.9);
}
.info-tooltip:hover, .info-tooltip:focus {
  background-color: #fff;
}
.info-tooltip:hover:before, .info-tooltip:hover:after, .info-tooltip:focus:before, .info-tooltip:focus:after {
  display: block;}

@-webkit-keyframes swooshUp {
  0% {
    -webkit-transform: translate(-180%, 90%);
    -khtml-box-shadow: translate(-180%, 90%);
    -moz-box-shadow: translate(-180%, 90%);
    -ms-transform: translate(-180%, 90%);
    -o-transform: translate(-180%, 90%);
    transform: translate(-180%, 90%);
    opacity: 0;
  }
  39.44% {
    opacity: 0;
  }
  100% {
    -webkit-transform: translate(-50%, 0);
    -khtml-box-shadow: translate(-50%, 0);
    -moz-box-shadow: translate(-50%, 0);
    -ms-transform: translate(-50%, 0);
    -o-transform: translate(-50%, 0);
    transform: translate(-50%, 0);
    opacity: 1;
  }
}
@-moz-keyframes swooshUp {
  0% {
    -webkit-transform: translate(-50%, 50%);
    -khtml-box-shadow: translate(-50%, 50%);
    -moz-box-shadow: translate(-50%, 50%);
    -ms-transform: translate(-50%, 50%);
    -o-transform: translate(-50%, 50%);
    transform: translate(-50%, 50%);
    opacity: 0;
  }
  39.44% {
    opacity: 0;
  }
  100% {
    -webkit-transform: translate(-50%, 0);
    -khtml-box-shadow: translate(-50%, 0);
    -moz-box-shadow: translate(-50%, 0);
    -ms-transform: translate(-50%, 0);
    -o-transform: translate(-50%, 0);
    transform: translate(-50%, 0);
    opacity: 1;
  }
}
@keyframes swooshUp {
  0% {
    -webkit-transform: translate(-50%, 50%);
    -khtml-box-shadow: translate(-50%, 50%);
    -moz-box-shadow: translate(-50%, 50%);
    -ms-transform: translate(-50%, 50%);
    -o-transform: translate(-50%, 50%);
    transform: translate(-50%, 50%);
    opacity: 0;
  }
  39.44% {
    opacity: 0;
  }
  100% {
    -webkit-transform: translate(-50%, 0);
    -khtml-box-shadow: translate(-50%, 0);
    -moz-box-shadow: translate(-50%, 0);
    -ms-transform: translate(-50%, 0);
    -o-transform: translate(-50%, 0);
    transform: translate(-50%, 0);
    opacity: 1;
  }
}
/*------x-button--------*/
.mobile-menu-btn {
  display: inline-block;
  position: relative;
  width: 18px;
  height: 14px;
  cursor: pointer;
}
.mobile-menu-btn span {
  display: inline-block;
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
  width: 18px;
  height: 2px;
  background-color: black;
  opacity: 1;
  transition: opacity .5s ease;
}
.mobile-menu-btn:before, .mobile-menu-btn:after {
  content: '';
  display: inline-block;
  width: 18px;
  height: 2px;
  background-color: black;
  position: absolute;
}
.mobile-menu-btn:before {
  top: 0;
  transform: rotate(0deg);
  transition: transform .25s ease, top .25s ease .25s;
}
.mobile-menu-btn:after {
  bottom: 0;
  transform: rotate(0deg);
  transition: transform .25s ease, bottom .25s ease .25s;
}
.mobile-menu-btn.open span {
  opacity: 0;
  transition: opacity .5s ease;
}
.mobile-menu-btn.open:before {
  top: 6px;
  transform: rotate(45deg);
  transition: transform .25s ease .25s, top .25s ease;
}
.mobile-menu-btn.open:after {
  bottom: 6px;
  transform: rotate(-45deg);
  transition: transform .25s ease .25s, bottom .25s ease;
}


</style>
<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
		<!--<div class="col-lg-12">
			<div class="col-lg-3 col-lg-offset-0 col-md-3 col-md-offset-0 col-sm-3 col-sm-offset-0 col-xs-12 col-xs-offset-0 form-group">
				<div class="pane0">
					<select data-placeholder="Order Type" class="form-control single_dropdown lbl_move sortoption" tabindex="7" name="OrderType" id="OrderType" style="width:100%;">
						<option value=""></option>
						<option value="material">Material</option>
						<option value="asset">Asset</option>
					</select>	
				</div>
			</div>
			<div class="col-lg-1 flip0">
				<i class="fa fa-retweet" data-toggle="tooltip" data-placement="right" data-original-title="Toggle" style="font-size:22px !important;cursor:pointer;"></i>
			</div>
			<div class="col-lg-3 col-lg-offset-0 col-md-3 col-md-offset-0 col-sm-3 col-sm-offset-0 col-xs-12 col-xs-offset-0 form-group">
				<div class="pane1">
					<select data-placeholder="Po Type" class="form-control single_dropdown lbl_move sortoption" tabindex="7" name="OrderType" id="OrderType" style="width:100%;">
						<option value=""></option>
						<option value="material">Material</option>
						<option value="asset">Asset</option>
					</select>	
				</div>
			</div>
			<div class="col-lg-1 flip1">
				<i class="fa fa-retweet" data-toggle="tooltip" data-placement="right" data-original-title="Toggle" style="font-size:22px !important;cursor:pointer;"></i>
			</div>
			<div class="col-lg-2 col-lg-offset-0 col-md-3 col-md-offset-0 col-sm-3 col-sm-offset-0 col-xs-12 col-xs-offset-0 form-group">
				<select data-placeholder="Date" class="form-control single_dropdown lbl_move sortoption" tabindex="7" name="OrderType" id="OrderType" style="width:100%;">
					<option value=""></option>
					<option value="material">Material</option>
					<option value="asset">Asset</option>
				</select>	
			</div>		
			<div class="col-lg-2 col-lg-offset-0 col-md-3 col-md-offset-0 col-sm-3 col-sm-offset-0 col-xs-12 col-xs-offset-0 form-group">
				<select data-placeholder="Date 1" class="form-control single_dropdown lbl_move sortoption" tabindex="7" name="OrderType" id="OrderType" style="width:100%;">
					<option value=""></option>
					<option value="material">Material</option>
					<option value="asset">Asset</option>
				</select>	
			</div>		
		</div>
		<div class="col-lg-12">
			<div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 mnimumwidthres">
				<div class="pnl pnl-overflow" style=" border-left:2px solid #d38241;">
					<a href="#" >
					<div style="padding-left: 15px !important;">
						<div class="icon-bg"><i class="fa fa-tasks i-text-two"></i></div>
						<h2 class="comtex tet-clr2 comnelips">T</h2>
						<h5 class="tet-muted tet-mutedclr comnelips">34</h5>
					</div>
					</a>
				</div>
			</div>
			<div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 mnimumwidthres">
				<div class="pnl pnl-overflow" style=" border-left:2px solid #d38241;">
					<a href="#" >
					<div style="padding-left: 15px !important;">
						<div class="icon-bg"><i class="fa fa-tasks i-text-two"></i></div>
						<h2 class="comtex tet-clr2 comnelips">T</h2>
						<h5 class="tet-muted tet-mutedclr2 comnelips">3</h5>
					</div>
					</a>
				</div>
			</div>
			<div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 mnimumwidthres">
				<div class="pnl pnl-overflow" style=" border-left:2px solid #d38241;">
					<a href="#" >
					<div style="padding-left: 15px !important;">
						<div class="icon-bg"><i class="fa fa-tasks i-text-two"></i></div>
						<h2 class="comtex tet-clr2 comnelips">T</h2>
						<h5 class="tet-muted tet-mutedclr2 comnelips">3</h5>
					</div>
					</a>
				</div>
			</div>
			<div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 mnimumwidthres">
				<div class="pnl pnl-overflow" style=" border-left:2px solid #d38241;">
					<a href="#" >
					<div style="padding-left: 15px !important;">
						<div class="icon-bg"><i class="fa fa-tasks i-text-two"></i></div>
						<h2 class="comtex tet-clr2 comnelips">T</h2>
						<h5 class="tet-muted tet-mutedclr2 comnelips">5</h5>
					</div>
					</a>
				</div>
			</div>
		</div>-->
	<div class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0 col-xs-12 col-xs-offset-0">
		<div class="col-md-12">
			<div class="bubble">
				<div class="rectangle">
					<div class="mobile-menu-btn">
						<span></span>
					</div>
					<h2>Prefered Vendor</h2>
				</div>
				<div class="info">							
					<div class="vendor_subscriber" id="">									
						<div class="pref_vendor">
							<b class="hed">M03 SAND</b>
							<p class="par"> Apple</p>
							<p class="par"> Apple apple</p>
							<p class="par"> Chennai,<span>Tamilnadu,</span><span>India.</span></p>
							<p class="par"> Pincode</p>
							<p class="par"> Contact Person:<span>...............</span></p>
							<p class="par"> Phone:<span>......................</span></p>
							<p class="par"> Mobile:<span>..................</span></p>
							<p class="par"> Apple</p>
							<p class="par"> Apple apple</p>
							<p class="par"> Chennai,<span>Tamilnadu,</span><span>India.</span></p>
							<p class="par"> Pincode</p>
							<p class="par"> Contact Person:<span>...............</span></p>
							<p class="par"> Phone:<span>......................</span></p>
							<p class="par"> Mobile:<span>..................</span></p>
						</div>	
						<div class="pref_vendor">
							<b class="hed">M03 SAND</b>
							<p class="par"> Apple</p>
							<p class="par"> Apple apple</p>
							<p class="par"> Chennai,<span>Tamilnadu,</span><span>India.</span></p>
							<p class="par"> Pincode</p>
							<p class="par"> Contact Person:<span>...............</span></p>
							<p class="par"> Phone:<span>......................</span></p>
							<p class="par"> Mobile:<span>..................</span></p>
						</div>	
					</div>						
				</div>
			</div>
		</div>
	</div>
						<!--</div>
					</div>
				</div>
			</div>
		</div>-->	
	</div>		
</div>
<script> 
$(document).ready(function(){
    $(".flip0").click(function(){
        $(".pane0").slideToggle("slow");
    });
	$(".flip1").click(function(){
        $(".pane1").slideToggle("slow");
    });

});
</script>
<script>
	function myFunction(x) {
		x.classList.toggle("change");
	}
</script>
<script>
	var menuButton = document.querySelector('.mobile-menu-btn');

var toggleMobile = function() {
  menuButton.classList.toggle('open');
  menu.classList.toggle('visible');
}

menuButton.addEventListener('click', toggleMobile);
</script>
<script>
/**
 * Do the random stuff
 *
 */
(function() {

  // cache vars
  var cards = document.querySelectorAll(".card.effect__random");
  var timeMin = 2;
  var timeMax = 4;
  var timeouts = [];

  // loop through cards
  for ( var i = 0, len = cards.length; i < len; i++ ) {
    var card = cards[i];
    var cardID = card.getAttribute("data-id");
    var id = "timeoutID" + cardID;
    var time = randomNum( timeMin, timeMax ) * 1200;
    cardsTimeout( id, time, card );
  }

  // timeout listener
  function cardsTimeout( id, time, card ) {
    if (id in timeouts) {
      clearTimeout(timeouts[id]);
    }
    timeouts[id] = setTimeout( function() {
      var c = card.classList;
      var newTime = randomNum( timeMin, timeMax ) * 1200;
      c.contains("flipped") === true ? c.remove("flipped") : c.add("flipped");
      cardsTimeout( id, newTime, card );
    }, time );
  }

  // random number generator given min and max
  function randomNum( min, max ) {
    return Math.random() * (max - min) + min;
  }

})();


</script>
<!--/*---------2----------*/
.card2__front {
  background-color: #8aaf45;
}

.card2__back {
  background-color: #8aaf45;
  -webkit-transform: rotateY(-180deg);
          transform: rotateY(-180deg);
}
/*---------2----------*/
/*---------3----------*/
.card3__front {
  background-color: #a4bfca;
}

.card3__back {
  background-color: #a4bfca;
  -webkit-transform: rotateY(-90deg);
          transform: rotateY(-90deg);
}
/*---------3----------*/-->

<!--<body oncontextmenu="return false;">-->