
<style type="text/css">
.multiselect {
  min-width: 100px;
  min-height: 1.2em;
  display: inline-block;
  border: 1px solid grey;
}

div.multiselect label.down-arrow, input.show-hide {
  float: right;
}

div.multiselect label.down-arrow:hover {
  color: #444;
}

div.multiselect input.show-hide {
  display: none;
}

div.multiselect label.down-arrow:before {
  content: '\25BC';
  vertical-align: top;
}

div.multiselect input.show-hide:checked + label.down-arrow:before {
  content: '\25B2';
  vertical-align: top;
}

div.multiselect ul {
  display: none;
  list-style-type: none;
  list-style-position: outside;
  padding-left: 2px;
}

div.multiselect input.show-hide:checked ~ ul {
  display: block;
}
input[type="radio"] {
  appearance: none;
  margin: 0 40px;
  width: 24px;
  height: 24px;
  background: #eeeeee;
  box-shadow: inset 0 0 0 .4em white, 0 0 0 .3em;
  border-radius: 50%;
  transition: .2s;
  cursor: pointer;
  color: #363945;
}
input[type="radio"]:hover, input[type="radio"]:checked {
  background: #363945;
  box-shadow: inset 0 0 0 .6em white, 0 0 0 .3em;
}
input[type="radio"]:checked {
  background: #56be8e;
  box-shadow: inset 0 0 0 .4em white, 0 0 0 .3em #56be8e;
}
input[type="radio"]:focus {
  outline: 0;
}

.bg{background:#c2ecfd;width:100%;height:100%;padding:2px;}
.fltlft{float:left;}
</style>
<div class="content_wrapper">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12">
				<div class="col-lg-4 col-lg-offset-1">
					<div class="" id="statutorydetail3">
						<h1 class="txt_center mar_btm">Excise Details</h1>		
							<div class="b">
								
								<label for="statutorydetail3" class="stat">Excise Details</label>	
								<input class="medium" type="radio" name="a"/>								
								<!--<div class="radio_check" style="">
									<p class="stat_lbl">
										<input type="radio" value="1" id="availExciseYes" name="availExcise" <?php if(isset($statutoryResults) && $statutoryResults['AvailExcise'] == 1) { echo "checked"; } ?> />
										<label for="availExciseYes" class="ripple">Yes</label>
									</p>
									<p class="stat_lbl">
										<input type="radio" value="0" id="availExciseNo" name="availExcise" <?php if(isset($statutoryResults) && $statutoryResults['AvailExcise'] == 0) { echo "checked"; } if(!isset($statutoryResults)){ echo "checked";} ?> />
										<label for="availExciseNo" class="ripple">No</label>
									</p>
								</div>-->
							</div>
						<div id="q1"> 
							<div class="form-group req_flds">
								<input type="text" class="form-control lbl_move" onkeypress="return alphaNumeric(event)" label="Excise RegNo" maxlength='20' name="exciseregno" value="<?php if($statutoryResults) { echo $statutoryResults['ExciseRegNo']; } ?> ">
							</div>
						</div>
						<div class="" style="margin-top:5px;margin-bottom:5px;">
							<label for="statutorydetail3" class="stat">VAT Remittence</label>
							<div class="radio_check">
								<p class="stat_lbl">
									<input type="radio" value="1" id="vatYes" name="vatRemittance" <?php if(isset($statutoryResults) && $statutoryResults['VatRemittance'] == 1) { echo "checked"; } ?> />
									<label for="vatYes" class="ripple">Yes</label>
								</p>
								<p class="stat_lbl">
									<input type="radio" value="0" id="vatNo" name="vatRemittance" <?php if(isset($statutoryResults) && $statutoryResults['VatRemittance'] == 0) { echo "checked"; } if(!isset($statutoryResults)){ echo "checked";} ?> />
									<label for="vatNo" class="ripple">No</label>
								</p>
							</div>
						</div>
						<div id="q5">
							<div class="form-group req_flds col-lg-12 padlr0">
								<span class="date_icon"><i class="fa fa-calendar"></i></span>
								<input type="text" name="remittanceDate" id="RemittanceDate" value="<?php echo (($statutoryResults)?date("d-m-y",strtotime($statutoryResults['RemittanceDate'])): date("d-m-Y")); ?>" readonly class="form-control lbl_move datepickerinput"   label="Remittence Effects From" />
							</div>
						</div>
					</div>
				</div>
				<!--<select class="multiselect" style="width:50%;">
					<option disabled>Auswählen</option>
					<option value="1">1</option>
					<option value="2">2</option>
				</select>-->
			</div>
		</div>
		<div>
			<i class="glyphicon glyphicon-hourglass"></i>
		</div>
	</div>
</div>

<script type="text/script">
$('body').append(
  $('<div />').attr('class','multiselect').append(
    $('<input />').attr({
      'type':'checkbox',
      'class': 'show-hide',
      'id': 'show-hide'
    })
  )
);
$('.multiselect').append(
    $('<label />').attr({
      'class':'down-arrow',
      'for': 'show-hide'
    })
);
$('.multiselect').append(
  $('<ul />')
);

$('select.multiselect').prop('multiple',true).hide();

$('select.multiselect option').each(function(key, val) {
  console.log(key,val);
  $('div.multiselect ul').append(
    $('<li />').attr('id',key).append(
      $(val).prop('disabled') ? '' : $('<input />').attr('type','checkbox')
    )
  );
	$(val).prop('disabled') ? $('li#' + key).css('font-style', 'italic') : null;
  	$('div.multiselect ul li#' + key).append(val.innerHTML);
});

$('div.multiselect ul li input[type=checkbox]').click(function() {
  console.log($('div.multiselect ul li input[type=checkbox]:checked'));
  $('div.multiselect ul li input[type=checkbox]:checked').each(function(key, val) {
    $('select.multiselect option[value="' + $(val).parents().attr('id') + '"]').prop('selected',true)
  })
});
</script>