<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/select2.full.min.js"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/select2.min.css" />
<?php
		$url = $this->serverUrl(true);
		$url = array_pop(explode("/", $url));
		$url1 = array_pop(explode("/", $url));
?>
<form name="followup" class="form-horizontal stginner_cnt" method="post">
<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
        <div class="col-lg-12">
            <h1 data-bsfhead="Broker Followup Entry">Broker Followup</h1>
        </div> 
        <div class="col-lg-12 clear">
            <div class="row">
               <div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                
					<div id="followup" class="showDiv">
					   <div class="row" id="ProjectsId">  
							<div class="form-group padtop20 col-lg-12">
								<select name="brokerId" data-bsfshare="Broker Id" id="brokerId" class="form-control single_dropdown2 lbl_move" label="Select Broker" style="width:100%;">
									<option value="">SelectBroker</option>

									<?php
										foreach($resultBroker as $type){ 
											echo "<option value='".$type['BrokerId']."' >".$type['BrokerName']."</option>";
										} 
									?>
								</select>
								<div class="error_message"><p>please select broker...</p></div>
				</div>
						</div>
						
						<div class="col-lg-12 savebtn_area no_border">
                            <ul>
                                <li class="save_btn m_auto">
                                    <a href="javascript:void(0);" class="ripple continue" id="continue" value="Continue" onclick="validate()">proceed</a>
                                </li>
                            </ul>
						</div>
					</div>
				
                </div>
            </div>
        </div>
    </div>
</div>
</form>


  <script>
  $(".continue").click(function(){
	var ele = $(".showDiv:visible");
	var bool = true;
	ele.find("input,checkbox, select, textarea").each(function(){
	var tagname = $(this).prop("tagName").toLowerCase();
		if(tagname =='input'){
								
	}
	else if(tagname =='select'){
		if($(this).val() == ""){
			bool = false;
			$(this).closest('.form-group').find(".error_message").show();
			$(this).focus();
			return false;		
		}
		else{
			$(this).closest('.polymer-form').next(".error_message").hide();	
			}	
		
	}
	
});
if(bool){
	if($(".showDiv:visible").index() != $(".showDiv:last").index()){
		$(".showDiv:visible").next(".showDiv").show();
		ele.hide();
		if($(".showDiv:Visible").index()){
			$(this).text("submit");
		}
	}
	else{
		$('form').submit(); 
	}
}
});
</script>
<script>
$(document).ready(function() {
		$(".single_dropdown2").select2({
			placeholder: "",
			allowClear: true
		});
	});
</script>