<h2>Broker Details</h2>
<div class="right_lbox_inner_cnt">
	<div class="col-lg-12 ldrgstr_detail_pro padlr0">
		<div class="stgedit_btn topright_6 brad_50">
			<a href="<?php echo $this->basePath(); ?>/crm/broker/entry/<?php echo $resp['BrokerId'];?>" class="ripple"><span><i class="fa fa-pencil"></i></span></a>
		</div>
		<div class="col-lg-4 flwup_proimg_area">
			<div class="flwup_proimg brad_200 m_top0">
				
			</div>
		</div>
		<div class="col-lg-8 col-md-12 flwup_procnt">
			<h1 class="name"><?php echo ucfirst($resp['BrokerName']);?>
	</div>
	</div>
	<div class="col-lg-12 padlr0">
		<div class="form-horizontal stginner_cnt">
		<div class="row">   
				<div class="col-lg-12">
					<label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label"><span class="p_lbl_icon"><i class="glyphicon glyphicon-calendar"></i></span>Broker Date</label>
					<div class="col-lg-7 col-md-7 col-sm-7 padlr0">
						<p><?php echo date("m-d-Y",strtotime($resp['BrokerDate']));?></p> 
					</div>
				</div>
			</div>
			<div class="row">   
				<div class="col-lg-12">
					<label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label"><span class="p_lbl_icon"><i class="fa fa-suitcase"></i></span>Prefered Projects</label>
					<div class="col-lg-7 col-md-7 col-sm-7 padlr0">
						<ul class="flwup_rcnt_inrproject">
							<?php
						foreach($resultMultiProject as $resuCC){
						?>
						<li class="white_inner">
								<span class="pad_t3"><?php echo ucfirst($resuCC['ProjectName']['0']);?></span><p><?php echo $resuCC['ProjectName'];?></p>
							</li>						
						<?php }	?>							
						</ul>  
						</ul>  
					</div>
				</div>
			</div>
			
			<div class="row">   
				<div class="col-lg-12">
					<label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label"><span class="p_lbl_icon"><i class="fa fa-user"></i></span>Mobile</label>
					<div class="col-lg-7 col-md-7 col-sm-7 padlr0"><p>
						<?php echo $resp['Mobile'];?><span><i class="fa fa-phone"></i></span></p>
					</div>
				</div>
			</div>
			<div class="row">   
				<div class="col-lg-12">
					<label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label"><span class="p_lbl_icon"><i class="fa fa-user-secret"></i></span>Email</label>
					<div class="col-lg-7 col-md-7 col-sm-7 padlr0">
						<p><?php echo $resp['EmailId'];?></p>
					</div>
				</div>
			</div>
			
			<div class="row">   
				<div class="col-lg-12">
					<label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label"><span class="p_lbl_icon"><i class="glyphicon glyphicon-calendar"></i></span>Address</label>
					<div class="col-lg-7 col-md-7 col-sm-7 padlr0">
						<p><?php echo $resp['Address'];?></p> 
					</div>
				</div>
			</div>
			 
	</div>
	<p class="rightlbox_btn">
		<a href="<?php echo $this->basePath(); ?>/crm/broker/followup/<?php echo $resp['BrokerId']?>" class="ripple">Follow up</a>
		<a href="<?php echo $this->basePath(); ?>/crm/broker/history/<?php echo $resp['BrokerId']?>" class="ripple">Follow up history</a>
		<a href="<?php echo $this->basePath(); ?>/crm/broker/full-details/<?php echo $resp['BrokerId']?>" class="ripple">View more details</a>
	</p>
</div>
</div>