<!-- INLINE CSS -->
<style>
.tr_hot 						{background:#f9eaea;}
.tr_warm 						{background:#f8f1e4;}
.tr_cold 						{background:#e8f0f6;}
.flwup_proimg					{margin-top:12px;}
#dataTable .jqx-grid-header 	{height:75px !important;}
</style>
<!-- INLINE CSS -->
<div class="content_wrapper padlr0">
	<div class="container-fluid padlr0">
    	<div class="col-lg-12">
			<h1>Broker FollowUp Register</h1>
        </div>
        <div class="col-lg-12">
			<div id="dataTable"></div>
        </div>
	</div>
</div>
<script>
$(function(){
    $('.lead_table tr').click(function(){ 
		$('.right_lightbox').show();
		$('.left-panel').removeClass('collapsed');
		$('.l_menuicon_nav').removeClass('cross');
    });
	$('.right_lightbox_close').click(function(){
		$('.right_lightbox').hide();
		if ($(window).width() >=980){
			$('.left-panel').addClass('collapsed');	
			$('.l_menuicon_nav').addClass('cross');
		}
	});
});
</script>
<script>
jQuery(document).ready(function($) {
    $(".clickable-row").click(function() {
        window.document.location = $(this).data("href");
    });
});

$(document).ready(function () {
    var data = <?php echo (isset($followupRegister)) ? json_encode($followupRegister) : ''?>;
    var source =
    {
        localData: data,
        dataType: "json",
        dataFields: [
           { name: 'FollowupId', type: 'number' },
					{ name: 'RefDate', type: "date", format: 'DD-MM-yyyy' },
					{ name: 'BrokerName', type: 'string' },
					{ name: 'ProjectName', type: 'string' },
					{ name: 'LeadName', type: 'string' },
					{ name: 'Remarks', type: 'string' },
					

        ],
        id: 'FollowupId',
    };

    var dataAdapter = new $.jqx.dataAdapter(source);

    var cellclassname = function (row, column, value, data) {
        if(data.StatusId == 1) {
            return 'tr_hot';
        } else if(data.StatusId == 2) {
            return 'tr_warm';
        } else if(data.StatusId == 3) {
            return 'tr_cold';
        }
    };

    $("#dataTable").jqxGrid({
        width: '100%',
        source: dataAdapter,
        pageable: true,
        selectionMode: 'singleRow',
        pagerButtonsCount: 6,
        autoheight:true,
        rowsheight:40,
        autorowheight: true,
        filterable: true,
        sortable: true,
        //filtermode: 'advanced',
        columnsResize: true,
        showfilterrow: true,
        ready:function(){
        },
        rendered: function () {
        },
        columns: [
				  { text: 'RefDate', filtertype: 'date',width:110, dataField: 'RefDate',  cellsformat: 'd', cellclassname: cellclassname},
				  { text: 'Broker', dataField: 'BrokerName', cellclassname: cellclassname},
				  { text: 'Project', dataField: 'ProjectName', cellclassname: cellclassname},
				  { text: 'Lead', dataField: 'LeadName', cellclassname: cellclassname },
				  { text: 'Remarks', dataField: 'Remarks', cellclassname: cellclassname },
				  
				]
    });

    $('#dataTable').on('celldoubleclick', function (event){
        // event arguments.
        var args = event.args;
        // row's bound index.
        var rowBoundIndex = args.rowindex;
        // row's visible index.
        var rowVisibleIndex = args.visibleindex;
        // right click.
        var rightclick = args.rightclick;
        // original event.
        var ev = args.originalEvent;
        // column index.
        var columnindex = args.columnindex;
        // column data field.
        var dataField = args.datafield;
        // cell value
        var value = args.value;
        var data = $("#dataTable").jqxGrid("getrowdata", rowBoundIndex);
        if(dataField != '')
            location.replace("<?php echo $this->basePath(); ?>/crm/broker/followup-details/"+data.uid);
    });
}); 
</script>

