<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
        <div class="col-lg-12">
		<div class="mometer cold">
                <div class="meter_bg"></div>
                <div class="meter_head"><?php //echo $resultsLead['state'];?></div> 
			</div>
            <h1>Lead Details of
                <div class="btn-group proname_btn">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"><?php echo $fullDetails['BrokerName'];?><span class="edit_symbols" data-placement="right" data-toggle="tooltip" data-original-title="Change&nbsp;project&nbsp;name"><i class="fa fa-caret-down "></i></span></a> 							
					<div class="dropdown-menu toolbar_ddown proname_ddown arrow" role="menu">
								<ul>
								<?php 
								foreach($responseBro as $broker){?>
									<li><a href="javascript:void(0);" class="followupId" data-index="<?php echo $broker['BrokerId'];?>"><?php echo ucfirst($broker['BrokerName']);?></a></li>
								<?php }	?>
								</ul>
							</div>
                </div>
            </h1>
        </div> 
        <div class="col-lg-12 flwup_topcnt clear">
            <div class="col-lg-6 col-md-6 col-sm-12 padlr0">
            	<div class="col-lg-4 flwup_proimg_area">
                    <div class="flwup_proimg brad_200">
						
					</div>
                   
                </div> 
            	<div class="col-lg-8 col-md-12 flwup_procnt">
                    <h1><?php echo $fullDetails['BrokerName'];?>
                    </h1>
                    
                   <ul>
                       <li><a href="javascript:void(0);" class="followup" data-index="<?php  echo $fullDetails['BrokerId'];?>"><span><i class="fa fa-search-plus"></i></span>Followup</a></li>
                       <li><a href="javascript:void(0);" class="edit" data-index="<?php  echo $fullDetails['BrokerId'];?>"><span><i class="fa fa-pencil"></i></span> Edit Details</a></li>
					</ul>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6 flwup_rightcnt">
            	<h2>Contact details
                	<div class="stgedit_btn h2_circle brad_50"><span><i class="fa fa-book"></i></span></div>
                </h2>
                <div class="clr_bbdr"></div>
                <div class="flwup_rightcnt_inner">
                	<ul class="flwup_rcnt_inrdetail">
					<li>+91<span class="flwup_rcnt_num"> <?php echo $fullDetails['Mobile'];?></span><span class="inner_ricon inr_ri_mt7 float_r"><i class="fa fa-phone"></i></span></li>
                    	<li><?php echo $fullDetails['EmailId'];?> <span class="inner_ricon float_r"><i class="fa fa-envelope"></i></span></li>
                    </ul>
                </div>
            </div>
			<div class="col-lg-3 col-md-6 col-sm-6 flwup_rightcnt">
				<h2 data-bsfshare="Next Followup">Next Followup
					<div class="stgedit_btn h2_circle brad_50"><span><i class="fa fa-hand-o-right"></i></span></div>
				</h2>
				<div class="clr_bbdr"></div>
				<div class="flwup_rightcnt_inner">
					<ul class="flwup_rcnt_inrdetail">
						<li data-bsfshare="Next Call Date"><span class="flwup_rcnt_num flwup_rcnt_date"><?php if(!empty($fullDetails['NextCallDate'])){echo date("d-m-Y",strtotime($fullDetails['NextCallDate']));}else{echo"-";}?></span>
							</li>
					</ul>
				</div>
			</div>
            
        </div>
        <div class="col-lg-12 clear">
        	<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
            	<div class="panel panel-default">
                	<div class="panel-heading accordion_head accordion_head_crnt" role="tab" id="headingOne" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    	<h4>General</h4>
                   	</div>
                    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                    	<div class="panel-body">
                            <div class="col-lg-12 padlr0">
                                <div class="form-horizontal stginner_cnt">
                                   
                                    <div class="col-lg-6 col-md-6 padlr0">
                                        <div class="row">     
                                            <div class="col-lg-12">
                                                <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Address</label>
                                                <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                                    <p><?php echo $fullDetails['Address'];?></p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                   
                                </div>  
                             </div>                          
                    	</div>
                    </div>
                </div>
                </div>
						
                    </div>
                </div>
                </div>
                </div>
                    </div>
                </div>
				</div>
				 
				
            </div>
        </div>
    </div>
</div>
<script>
$('.followup').on('click',function(){
	var urlId = $(this).attr('data-index');
	location.replace("<?php echo $this->basePath(); ?>/crm/broker/followup/"+urlId);
});
$('.edit').on('click',function(){
	var urlId = $(this).attr('data-index');
	location.replace("<?php echo $this->basePath(); ?>/crm/broker/entry/"+urlId);
});
//onchange broker
$('.followupId').on('click',function(){
var urlId = $(this).attr('data-index');
location.replace("<?php echo $this->basePath(); ?>/crm/broker/full-details/"+urlId);
});
</script>