<style>
    .pagination-lg > li > a, .pagination-lg > li > span {
        font-size:15px !important;
        padding:5px 15px !important;
    }
    /* Excel Floating Icon */
    .fixed-action-btn          	    {position:fixed;top:85px;right:5px;padding-top:15px;margin-bottom:0;z-index:998;}
    .fixed-action-btn:hover ul li a.btn-floating{transform: scaleY(1) scaleX(1) translateX(0px);opacity: 1;}
    .btn-floating.btn-large         {width:45px;height:45px;}
    .fixed-action-btn ul 			{left:-142px;right:0;text-align:center;position:absolute;margin:0;top:22px;}
    .fixed-action-btn ul li 		{margin-left:8px;list-style-type:none;float:left;}
    .fixed-action-btn ul li a.btn-floating {transform: scaleY(0.4) scaleX(0.4) translateX(40px);opacity: 0;}
    .fixed-action-btn ul a.btn-floating i  {font-size: 17px;line-height: 37px;}
    .btn-floating                   {display:inline-block;color:#fff;position:relative;overflow:hidden;z-index:1;width:37px;height:37px;line-height:37px;padding: 0;
        background-color: #26a69a;border-radius:50%;cursor:pointer;vertical-align: middle;
        box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);text-decoration: none;transition: all .3s ease;
        -webkit-transition: all .3s ease; -moz-transition: all .3s ease; -o-transition: all .3s ease;}
    .btn-floating i                 {width: inherit;display: inline-block;text-align: center;color: #fff;font-size:20px;line-height: 45px; font-weight:normal; color:#fff;}
    .next-bt                        {text-align:center;}
    .next-bt a:hover                {border:1px solid #3580C4 !important; background:#fff !important; color:#3580C4 !important;}
    .next-bt a                      {background:#3580C4!important;border:1px solid #3580C4; border-radius: 4px;
        color:#fff!important; font-size:14px; padding: 5px 10px; text-align: center; transition: all 0.4s ease 0s;}
    .commargin_top 					{margin-top: 30px;}

    /* Excel Floating Icon end*/
    /*--------------Jqx Grid jqx All-------------------*/
    #jqxgrid									{min-height:200px !important;}
    #jqxgrid .jqx-grid-header 					{height:60px !important;}
    .jqx-grid-groups-row						{padding-left:5px !important;}
    .jqx-grid-pager-input						{padding: 2px; text-align: center !important; width: 35px;}
    .jqx-dropdownlist-state-normal				{display: block;  float: right;height: 16px !important;margin-right: 7px;margin-top: 0;  padding-bottom: 2px !important;padding-top: 2px !important; width: 40px;}
    .jqx-button									{cursor: pointer;float: right;margin-right: 3px !important;margin-top: 0 !important;padding: 0 !important;width: 20px !important;}
    .jqx-button > .jqx-icon-arrow-left,
    .jqx-button >.jqx-icon-arrow-right			{height: 21px !important;margin-left: 0 !important;width: 20px !important;}
    .jqx-listitem-element						{height: 25px !important;}
    .jqx-input									{height: 25px !important; margin:2px 4px !important;}
    .jqx-grid-pager .jqx-grid-pager-input		{height:20px !important; margin:0px 4px !important;}
    #jqxgrid .jqx-grid-cell-right-align 		{text-align:right !important; padding-right:8px;}
    #jqxgrid .jqx-grid-cell-left-align 			{padding-left:8px;}
    .jqx-grid-column-menubutton::after			{left:4px;top:10px;}

</style>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqxgrid.grouping.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqxgrid.aggregates.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqx-all.js"></script>
<div class="content_wrapper  padlr0">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 padlr0">
                <div class="col-lg-6 col-md-6 col-sm-6 padlr0">
                    <h1 class="col-lg-9 col-md-9 col-sm-9"><strong>Material Storage Type Setup</strong></h1>
                </div>
            </div>
            <div class="col-lg-12 clear">
                <div class="table-responsive clear">
                    <div style='margin-top:10px;' id="jqxgrid"> </div>
                </div>

            </div>
        </div>
    </div>
</div>
<div class="col-lg-12 savebtn_area">
    <ul>
        <li class="cancel_btn cancel_btn_bluecolor float_l" id="Home"><a href="<?php echo $this->basePath();?>/mms/master/resourceview" class="ripple">back</a></li>
    </ul>
</div>
<script type="text/javascript">
    var arr_matstorage = <?php echo (isset($arr_matstorage)) ? json_encode($arr_matstorage) : '[]';?>;
    var cellsrenderer = function (row, column, value) {
        return '<div style="text-align: center; margin-top: 5px;">' + value + '</div>';
    }
    var columnsrenderer = function (value) {
        return '<div style="text-align: center; margin-top: 5px;">' + value + '</div>';
    }
    var types = { '1': 'Section', '2': 'Rack', '3': 'Bulk',
        '4': 'Open', '5': 'Bin' };
    $(document).ready(function () {
        var source = {
            localData: arr_matstorage,
            datatype: "json",
            pagesize: 9,
            datafields:
                [
                    { name: "ResourceId", type: "string" },
                    { name: "ItemId", type: "string" },
                    { name: "Code", type: "string" },
                    { name: "Resource", type: "string" },
                    { name: "Unit", type: "string" },
                    { name: "StorageType", type: "string" }

                ]
        };

        dataAdapter = new $.jqx.dataAdapter(source);
        $("#jqxgrid").jqxGrid(
            {
                width: "100%",
                source: dataAdapter,
                pageable: true,
                pagerMode: 'advanced',
                pagerHeight: 40,
                rowsheight:40,
                columnsresize: true,
                autoheight: true,
                sortable: true,
                altrows: true,
                enabletooltips: true,
                showfilterrow: true,
                filterable: true,
                groupable: true,
                showstatusbar: true,
                statusbarheight: 35,
                showaggregates: true,
                autorowheight: true,
                editable:true,
                columns: [
                    { text: 'ResourceId', datafield: 'ResourceId', hidden: true, filterable: false},
                    { text: 'ItemId', datafield: 'ItemId', hidden: true, filterable: false},
                    { text: 'Code', dataField: 'Code', pinned:'true', align: 'center', cellsalign: 'left',width:"25%",editable:false },
                    { text: 'Resource', dataField: 'Resource', pinned:'true',align: 'center', cellsalign: 'left',width:"25%",editable:false},
                    { text: 'Unit', dataField: 'Unit', pinned:'true', align: 'center', cellsalign: 'left',renderer: columnsrenderer, cellsrenderer: cellsrenderer,width:"25%",editable:false},
//                    { text: 'StorageType', index: 'StorageType', pinned:'true', align: 'center', cellsalign: 'left',width:"25%",edittype: 'select',formatter: 'select',editoptions:{value: getAllSelectOptions()}}

                    { text: 'StorageType', dataField: 'StorageType', width: '25%',align: 'center',renderer: columnsrenderer, cellsrenderer: cellsrenderer, columnType: "template",editable:true, cellEdit:true,
                        createEditor: function (row, cellvalue, editor, cellText, width, height) {
                        // construct the editor.
                        var source = ["None","Section", "Rack", "Bulk", "Open", "Bin"];
                        editor.jqxDropDownList({autoDropDownHeight: true, source: source, width: '100%', height: '100%',selectedIndex: 0 });
                         },
                        initEditor: function (row, cellvalue, editor, celltext, width, height) {
                            // set the editor's current value. The callback is called each time the editor is displayed.
                            editor.jqxDropDownList('selectItem', cellvalue);
                        },
                        getEditorValue: function (row, cellvalue, editor) {
                        // return the editor's value.
                        //alert(editor.val());
                        return editor.val();
                    }
                    }

                ]
            });
        $("#jqxgrid").on('cellbeginedit', function (event) {
            var args = event.args;
            //$("#eventLog").text("Event Type: cellbeginedit, Column: " + args.datafield + ", Row: " + (1 + args.rowindex) + ", Value: " + args.value);
        });
        $("#jqxgrid").on('cellendedit', function (event) {
            var args = event.args;
            var ResourceId= event.args.row["ResourceId"];
            var ItemId = event.args.row["ItemId"];
            var stype = args.value;

            $.ajax({
                url: getBaseURL() + 'warehouse/index/materialstorage',
                type: "post",
                data: "ResourceId=" + ResourceId + "&ItemId=" + ItemId +"&stype=" + stype,
                async: false,
                success: function (data, textStatus, jqXHR) {
                    if (jqXHR.status == 200) {
                       // reply=true;
                    }
                }, error: function (jqXHR, textStatus, errorThrown) {
                    //reply=false;

                }
            });
        });
//        $("#jqxgrid").on('cellendedit', function (event) {
//            var ResourceId=event.args.row["ResourceId"];
//            var ItemId = event.args.row["ItemId"];
//            var StorageType = event.args.value;
//
//            console.log(ResourceId + "-" + ItemId + "-" + StorageType);
//
////            var row = event.args.rowindex;
////            //var datarow = $("#jqxgrid").jqxGrid('getrowdata', row);
////          console.log(event.args.row["ResourceId"]);
////            var column = $("#jqxgrid").jqxGrid('getcolumn', event.args.datafield);
////
////            if (column.displayfield != column.datafield) {
////                $("#eventLog").html("<div>Cell Edited:<br/>Index: " + event.args.rowindex + ", Column: " + column.text + "<br/>Value: " + event.args.value.value + ", Label: " + event.args.value.label
////                    + "<br/>Old Value: " + event.args.oldvalue.value + ", Old Label: " + event.args.oldvalue.label + "</div>"
////                );
////            }
////            else {
////                $("#eventLog").html("<div>Cell Edited:<br/>Row: " + event.args.rowindex + ", Column: " + column.text + "<br/>Value: " + event.args.value
////                    + "<br/>Old Value: " + event.args.oldvalue + "</div>"
////                );
////            }
//        });

        function getAllSelectOptions(){
            var types = { '1': 'Section', '2': 'Rack', '3': 'Bulk',
                '4': 'Open', '5': 'Bin' };

            return types;

        }
        $("#jqxgrid").jqxGrid('showgroupsheader', false);

        $("#jqxgrid").bind('rowselect', function (event) {
            var row = event.args.rowindex;
            var datarow = $("#jqxgrid").jqxGrid('getrowdata', row);

        });
    });

</script>