<div class="content_wrapper padlr0">
	<div class="container-fluid">
		<div class="col-lg-12 clear">
        	<form class="form-horizontal" method="post">
                <div class="form-group">
                	<h1 class="txt_center commargin_top animated fadeInDown">Warehouse Management</h1>
                	<div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                        <div class="row commargin_top_70 ">   
                            <div class="form-group req_flds col-lg-12 animated fadeInDown">
                                <input type="text" name="manageby" id="manageby"  label="Enter the name of Warehouse Management" class="form-control lbl_move " />
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
	</div>
</div>
<div class="col-lg-12 savebtn_area">
        <ul>
            <li id="continueButton" class="dropdown save_btn float_r">
                <a href="javascript:void(0);" class="ripple">Continue</a>
            </li>
            <li id="backButton" class="cancel_btn float_r" style="display:none;"><a href="javascript:void(0);" class="ripple">back</a></li>
            <li class="cancel_btn cancel_btn_bluecolor float_l"><a id="cancelbutton" class="ripple" onclick="alert confirm();">cancel</a></li>
        </ul>
</div>