<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/select2.full.min.js"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/select2.min.css" />
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/workorder.css"/>
<style type="text/css">
    .totalright{font-weight:600; color:green; font-size:14px;}
</style>
<form method="post" action="" onsubmit="return validate();">
<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
        <div class="col-lg-12">
            <h1>Progress Bill</h1>
        </div>
        <div class="col-lg-12 clear">
            <div class="tagcrd">
                <ul>
                    <li class="mnimumwidthres90">
                        <div class="tagcardhdng pnl-overflow crmbrdrclr1">
                            <h2 class="comtex crmbrdrclrhed1 comnelips" style="font-weight:600 !important;">Bill Date</h2>
                            <input type="text"  name="BillDate" id="target_period" class="form-control date_picker" value="<?php echo $progressBill['BillDate'];?>" style="width:100%;cursor:pointer;"  />
                        </div>
                    </li>
                    <li class="mnimumwidthres90">
                        <div class="tagcardhdng pnl-overflow crmbrdrclr2">
                            <h2 class="comtex crmbrdrclrhed2 comnelips" style="font-weight:600 !important;">Generation No.</h2>
                            <input class="form-control "  name="ProgressNo"  <?php if($arrVNo['genType'] == true){ echo "Readonly"; } ?> id="Generation No" style="width:100%;cursor:pointer;" value="<?php echo $progressBill['ProgressNo'];?>" />
                        </div>
                    </li>
                    <li class="mnimumwidthres90">
                        <div class="tagcardhdng pnl-overflow crmbrdrclr3">
                            <div class="icon-bg"><i class="fa fa-suitcase i-text-111"></i></div>
                            <h2 class="comtex crmbrdrclrhed3 commargin_bottom_5 comnelips" style="font-weight:600 !important;">Project</h2>
                            <h5 class="tetmuted tet-clr11 comnelips"><?php echo $progressBill['ProjectName'];?></h5>
                        </div>
                    </li>
                    <li class="mnimumwidthres90">
                        <div class="tagcardhdng pnl-overflow crmbrdrclr4">
                            <div class="icon-bg"><i class="fa fa-tasks i-text-111"></i></div>
                            <h2 class="comtex crmbrdrclrhed4 commargin_bottom_5 comnelips" style="font-weight:600 !important;">Stage Name</h2>
                            <h5 class="tetmuted tet-clr11 comnelips"><?php echo $progressBill['StageName'];?></h5>
                        </div>
                    </li>
                    <li class="mnimumwidthres90">
                        <div class="tagcardhdng pnl-overflow crmbrdrclr5">
                            <div class="icon-bg"><i class="fa fa-ban  i-text-111"></i></div>
                            <h2 class="comtex crmbrdrclrhed5 commargin_bottom_5 comnelips" style="font-weight:600 !important;">Block Name</h2>
                            <h5 class="tetmuted tet-clr11 comnelips"><?php if($progressBill['BlockName']!="") { echo $progressBill['BlockName']; } else { echo "--"; }?></h5>
                        </div>
                    </li>
                    <li class="mnimumwidthres90">
                        <div class="tagcardhdng pnl-overflow crmbrdrclr6">
                            <div class="icon-bg"><i class="fa fa-building i-text-111"></i></div>
                            <h2 class="comtex crmbrdrclrhed6 commargin_bottom_5 comnelips" style="font-weight:600 !important;">Floor Name</h2>
                            <h5 class="tetmuted tet-clr11 comnelips"><?php if($progressBill['FloorName']!="") { echo $progressBill['FloorName']; } else { echo "--"; } ?></h5>
                        </div>
                    </li>
                    <li class="mnimumwidthres90">
                        <div class="tagcardhdng pnl-overflow crmbrdrclr7">
                            <div class="icon-bg"><i class="fa fa-gavel i-text-111"></i></div>
                            <h2 class="comtex crmbrdrclrhed7 commargin_bottom_5 comnelips" style="font-weight:600 !important;">Stage Type</h2>
                            <h5 class="tetmuted tet-clr11 comnelips"><?php if($progressBill['Stage']!="") { echo $progressBill['Stage']; } else { echo"--"; } ?></h5>
                        </div>
                    </li>
                    <li class="mnimumwidthres90">
                        <div class="tagcardhdng pnl-overflow crmbrdrclr8">
                            <h2 class="comtex crmbrdrclrhed8 comnelips" style="font-weight:600 !important;">Credit Days</h2>
                            <input class="form-control" name="CreditDays" id="CreditDays" style="width:100%;cursor:pointer;" value="<?php if($progressBill['CreditDays'] != "") { echo $progressBill['CreditDays']; } ?>" onKeyPress="return isNumberKey(event)" />
                        </div>
                    </li>
                </ul>
            </div>
            <input value="<?php echo $progressBill['ProjectId'];?>" type="hidden" name="ProjectId" />
            <input value="<?php echo $progressBill['BlockId'];?>" type="hidden" name="BlockId" />
            <input value="<?php echo $progressBill['FloorId'];?>" type="hidden" name="FloorId" />
            <input value="<?php echo $progressBill['StageType'];?>" type="hidden" name="StageType"/>
            <input value="<?php echo $progressBill['StageId'];?>" type="hidden" name="StageId"/>
        </div>
        <div class="col-lg-12 clear">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                    <tr>
                        <th width="3%">Unit No</th>
                        <th width="8%">PB No</th>
                        <th width="16%">Description</th>
                        <th width="10%">Buyer Name</th>
                        <th width="12%">Amount</th>
                        <th width="10%">Tax Amount</th>
                        <th width="10%">Paid Amount</th>
                        <th width="10%">LateFee Amount</th>
                        <th width="13%">Net Amount</th>
                        <th width="3%">&nbsp; </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    $i=1;
                    $vN = $this->CommonHelper()->getVoucherNo(803, date('Y-m-d'), 0, 0, $adb, "");
                    foreach($unit as $Unit):
                        $j=1; ?>
                        <tr>
                            <td><?php echo $Unit['UnitNo'];?>
                                <input type="hidden" name="UnitId[<?php echo $i;?>]" value="<?php echo $Unit['UnitId'];?>" ><input type="hidden" name="ProgressBillTransId[<?php echo $i;?>]" value="<?php echo $Unit['ProgressBillTransId'];?>" ></td>
                            <input type="hidden" name="LeadId" value="<?php echo $Unit['LeadId'];?>" ></td>
                            <td ><input type="text" name="PBNo[<?php echo $i;?>]" <?php if($vN['genType']== true ) { echo "Readonly "; } ?> value="<?php echo $Unit['PBNo'];?>"/> </td>
                            <td><?php echo $Unit['StageName'];?><input type="hidden" name="StageTransId[<?php echo $i;?>]" value="<?php echo $Unit['StageId'];?>" ></td>
                            <td  class="tbl_input_td"><input class="tbl_input" type="text" value="<?php echo $Unit['BuyerName'];?>" readonly /></td>
                            <td class="tbl_input_td"><input class="tbl_input txt_right unit-amt" id="CurAmt_<?php echo $i;?>" type="text" name="Amount[<?php echo $i;?>]" value="<?php echo $this->commonHelper()->sanitizeNumber($Unit['Amount'],2,true);?>" readonly  /></td>
                            <td  class="tbl_input_td"><input class="tbl_input txt_right unit-qual-amt" id="TaxAmt_<?php echo $i;?>" type="text" name="QualAmount[<?php echo $i;?>]" value="<?php echo $this->commonHelper()->sanitizeNumber($Unit['QualAmount'],2,true);?>" readonly  /></td>
                            <td  class="tbl_input_td"><input class="tbl_input txt_right unit-paid-amt" id="PaidAmt_<?php echo $i;?>" type="text" name="PaidAmount[<?php echo $i;?>]" value="<?php echo $this->commonHelper()->sanitizeNumber($Unit['PaidAmount'],2,true);?>" readonly  /></td>
                            <td class="tbl_input_td"><input class="tbl_input txt_right unit-late-amt" type="text" id="interestAmt_<?php echo $i;?>" name="interestAmt[<?php echo $i;?>]" readonly value="<?php echo $this->commonHelper()->sanitizeNumber($Unit['LateFee'],2,true);?>" /></td>
                            <td  class="tbl_input_td"><input class="tbl_input txt_right unit-net-amt" id="NetAmt_<?php echo $i;?>" type="text" name="NetAmount[<?php echo $i;?>]" value="<?php echo $this->commonHelper()->sanitizeNumber($Unit['NetAmount'],2,true);?>" readonly  /></td>
                            <td  align="center" class="action_btns_td">
                                <ul class="action_btns">
                                    <!--li>
                                    	<a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i></a>
                                    </li-->
                                    <li>
                                        <a href="#" class="mainTr"><i class="fa fa-chevron-circle-down" data-toggle="tooltip" data-placement="top" data-original-title="Expand"></i></a>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                        <!--Add lines table-->
                        <tr style="display:none;" class="subTr">
                            <td colspan="9" style="padding:0px !important; ">
                                <div class="subDiv" style="display:none;">
                                    <div class="col-lg-12 col-lg-offset-0 rdbt" style="margin-top:5px;"></div>
                                    <div class="col-lg-12">
                                        <div class="table-responsive topsp">
                                            <table class="table m_btm0 receipt-type-table">
                                                <thead>
                                                <tr>
                                                    <th width="20%">Receipt Type</th>
                                                    <!--th>Percentage</th-->
                                                    <th width="10%">Amount</th>
                                                    <th width="10%">Tax</th>
                                                    <th width="10%">Net Amount</th>
                                                    <th width="3%"></th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                <?php foreach($Unit['ReceiptTypeTrans'] as $ReceiptTypeTrans):?>
                                                    <tr>
                                                        <input type="hidden" name="ReceiptTypeId[<?php echo $i;?>][<?php echo $j;?>]" value="<?php echo $ReceiptTypeTrans['ReceiptTypeId'];?>"/>
                                                        <input type="hidden" name="ReceiptType[<?php echo $i;?>][<?php echo $j;?>]" value="<?php echo $ReceiptTypeTrans['ReceiptType'];?>"/>
                                                        <input type="hidden" name="PBReceiptTypeTransId[<?php echo $i;?>][<?php echo $j;?>]" value="<?php echo $ReceiptTypeTrans['PBReceiptTypeTransId'];?>"/>
                                                        <td ><?php echo $ReceiptTypeTrans['ReceiptTypeName'];?></td>
                                                        <!--td width="1%" class="tbl_input_td percntg_input"><input class="tbl_input" type="text" name="ReceiptTypePercentage[</?php echo $i;?>][</?php echo $j;?>]" readonly value="</?php echo $ReceiptTypeTrans['Percentage'];?>"/><span><i class="fa fa-percent"></i></span></td-->
                                                        <td  class="tbl_input_td"><input id="BillAbs_<?php echo $i;?>_CurAmt_<?php echo $j ;?>" class="tbl_input txt_right amount" type="text" name="ReceiptTypeAmount[<?php echo $i;?>][<?php echo $j;?>]" readonly value="<?php echo $this->commonHelper()->sanitizeNumber($ReceiptTypeTrans['Amount'],2,true);?>" /></td>
                                                        <td  class="tbl_input_td"><input class="tbl_input txt_right qual-amount" id="BillAbs_<?php echo $i;?>_TaxAmt_<?php echo $j;?> " type="text" name="ReceiptTypeQualAmount[<?php echo $i;?>][<?php echo $j;?>]" readonly value="<?php echo $this->commonHelper()->sanitizeNumber($ReceiptTypeTrans['QualAmount'],2,true);?>" /></td>
                                                        <td  class="tbl_input_td"><input class="tbl_input txt_right net-amount" type="text" name="ReceiptTypeNetAmount[<?php echo $i;?>][<?php echo $j;?>]"  readonly value="<?php echo $this->commonHelper()->sanitizeNumber($ReceiptTypeTrans['NetAmount'],2,true);?>" /></td>
                                                        <td  align="center" class="action_btns_td">
                                                            <ul class="action_btns">
                                                                <li><a href="#" class="mainTr rqualmainTr"><i class="fa fa-chevron-circle-down" data-toggle="tooltip" data-placement="top" data-original-title="Expand"></i></a></li>
                                                            </ul>
                                                        </td>
                                                        <input type="hidden" class="qualRefId" name="BillAbs_<?php echo $i;?>_QualRefId_<?php echo $j;?>" id="BillAbs_<?php echo $i;?>_QualRefId_<?php echo $j;?>" value="0"/>
                                                    </tr>
                                                    <tr style="display:none;" class="subTr qualmainTr">
                                                        <td colspan="8" style="padding:0px !important; "><div class="subDiv" style="display:none;">
                                                                <?php echo $ReceiptTypeTrans['HtmlTag'];?>
                                                        </td>
                                                    </tr>
                                                    <?php
                                                    $j++;
                                                endforeach; ?>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        <?php $i++;
                    endforeach; ?>
                    <tr>
                        <td  align="right" colspan="4" class="rate_pri">Total</td>
                        <td  class="tbl_input_td"><input class="tbl_input txt_right totalright total_input" id="BillCurTotal" type="text" value="" readonly/></td>
                        <td class="tbl_input_td"><input class="tbl_input txt_right totalright total_input" id="BillTaxTotal" type="text" value="" readonly/></td>
                        <td class="tbl_input_td"><input class="tbl_input txt_right totalright total_input" id="BillPaidTotal" type="text" value="" readonly/></td>
                        <td class="tbl_input_td"><input class="tbl_input txt_right totalright interest_input" id="BilllateTotal" type="text" value="" /></td>
                        <td class="tbl_input_td"><input class="tbl_input txt_right totalright total_input" id ="BillNetTotal" type="text" value="" readonly/></td>
                        <td >&nbsp;</td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="form-group col-lg-12">
                <p class="col-lg-6 col-md-6 col-sm-6 radio_label" style="padding-top:7px;"><label for="uds">Do you want to send demand letter on approval</label>

                </p>
                <div class="radio_check col-lg-4 col-md-4 col-sm-4">
                    <p>
                        <input type="radio" <?php if($progressBill['DemandApproval']== 1 ) { ;?> checked="checked" <?php } ?> value="1" id="yes" name="DemandApproval">
                        <label for="yes" class="ripple">Yes</label>
                    </p>
                    <p>
                        <input type="radio" <?php if($progressBill['DemandApproval']== 0 ) { ;?> checked="checked" <?php } ?> value="0" id="no" name="DemandApproval">
                        <label for="no" class="ripple">No</label>
                    </p>
                </div>
            </div>
        </div>

    </div>
</div>
<!--button-->
<div class="col-lg-12 savebtn_area clear">
    <ul>
        <li class="dropdown save_btn float_l">
            <a href="<?php echo $this->basePath();?>/crm/bill/progress-print/<?php echo $PBId;?>" class="ripple">Print</a>
        </li>
        <li class="dropdown save_btn float_r" >
            <input type="submit" class="ripple" value="Update Bill"/>
        </li>
        <li class="cancel_btn float_r">
            <a title="" class="ripple has-ripple" data-toggle="tooltip" href="<?php echo $this->basePath();?>/crm/bill/progress-register" data-original-title="Go back!" style="position: relative; overflow: hidden;">Back<span class="ripple-wrapper"></span></a>
        </li>
    </ul>
</div>
</form>
<script>
    $(document).ready(function() {
        $(".multiple_dropdown").select2({
        });

        //calculateTotal();

//        function calculateTotal(){
//            var totamount=0,totqual=0,totnetamount=0;
//            $('.receipt-type-table').find('> tbody > tr').each(function(){
//                if($(this).find('.amount').length > 0){
//                    totamount += parseFloat(isNullCheck($(this).find('.amount').val(),'number'));
//                    totqual += parseFloat(isNullCheck($(this).find('.qual-amount').val(),'number'));
//                    totnetamount += parseFloat(isNullCheck($(this).find('.net-amount').val(),'number'));
//
//                    var $tar_receiptTable = $(this).closest('.receipt-type-table');
//                    $tar_receiptTable.find('.total-amount').val(sanitizeNumber(totamount,2,true));
//                    $tar_receiptTable.find('.total-qual-amount').val(sanitizeNumber(totqual,2,true));
//                    $tar_receiptTable.find('.total-net-amount').val(sanitizeNumber(totnetamount,2,true));
//                }
//            });
//
//        }

        $(".single_dropdown").select2({
            placeholder: "",
            allowClear: true
        });

        bindExpandMainTr();
        bindExpandMainTrInput();

        bindRQualExpandTr();
        bindRQualExpandTrInput();

        bindQualExpandTr();
        bindQualExpandTrInput();
        fillRowRefEditMode();
        calcTotal();
        //bindTaxCalculation();

    });
</script>
<!--table Add lines start-->
<script>
$(".mainTr").click(function(e){
    e.preventDefault();
    if(!$(this).closest("tr").next(".subTr").is(":visible")){
        $(this).closest("tr").next(".subTr").show();
        $(this).closest("tr").next(".subTr").find(".subDiv").slideDown("slow");
        $(this).find("i").addClass("tform");
    }
    else{
        $(this).closest("tr").next(".subTr").find(".subDiv").slideUp("slow");
        $(this).closest("tr").next(".subTr").slideUp("slow");
        $(this).find("i").removeClass("tform");
    }
})
function validate(){
    if($('#ProgressNo').val()==""){
        alert("Please Enter Progress No");
        $('#ProgressNo').focus();
        return false
    }
}
function bindExpandMainTr() {
    var $mainTr = $(".mainTr");
    $mainTr.unbind('click');
    $mainTr.click(function (e) {
        e.preventDefault();
        if (!$(this).closest("tr").next(".subTr").is(":visible")) {
            closeMainTr();
            $(this).closest("tr").next(".subTr").show();
            $(this).closest("tr").next(".subTr").find(".subDiv").slideDown("slow");
        }
        else {
            $(this).closest("tr").next(".subTr").find(".subDiv").slideUp("slow");
            $(this).closest("tr").next(".subTr").slideUp("slow");
        }
    });
}

function bindExpandMainTrInput() {
    var $mainTr = $(".mainTrInput");
    $mainTr.focus(function (e) {
        if (!$(this).closest("tr").next(".subTr").is(":visible")) {
            closeMainTr();
            $(this).closest("tr").next(".subTr").show();
            $(this).closest("tr").next(".subTr").find(".subDiv").slideDown("slow");
        }
//        $(this).closest("tr").find(".mainTr").trigger('click');
    });
}

function closeMainTr() {
    var $mainTr = $(".mainTr");
    $.each($mainTr, function () {
        $(this).closest("tr").next(".subTr").find(".subDiv").slideUp("slow");
        $(this).closest("tr").next(".subTr").slideUp("slow");
    });
}

function bindRQualExpandTr() {
    var $mainTr = $(".rqualmainTr");
    $mainTr.unbind('click');
    $mainTr.click(function (e) {
        e.preventDefault();
        if (!$(this).closest("tr").next(".qualmainTr").is(":visible")) {
            closeRQualTr();
            $(this).closest("tr").next(".qualmainTr").show();
            $(this).closest("tr").next(".qualmainTr").find(".subDiv").slideDown("slow");
        }
        else {
            $(this).closest("tr").next(".qualmainTr").find(".subDiv").slideUp("slow");
            $(this).closest("tr").next(".qualmainTr").slideUp("slow");
        }
    });
}

function bindRQualExpandTrInput() {
    var $mainTr = $(".rqualmainTrInput");
    $mainTr.focus(function (e) {
        if (!$(this).closest("tr").next(".qualmainTr").is(":visible")) {
            closeRQualTr();
            $(this).closest("tr").next(".qualmainTr").show();
            $(this).closest("tr").next(".qualmainTr").find(".subDiv").slideDown("slow");
        }
    });
}

function closeRQualTr() {
    var $mainTr = $(".rqualmainTr");
    $.each($mainTr, function () {
        $(this).closest("tr").next(".qualmainTr").find(".subDiv").slideUp("slow");
        $(this).closest("tr").next(".qualmainTr").slideUp("slow");
    });
}


function bindQualExpandTr() {
    var $mainTr = $(".qualmainExp");
    $mainTr.unbind('click');
    $mainTr.click(function (e) {
        e.preventDefault();
        if (!$(this).closest("tr").next(".qualsubTr").is(":visible")) {
            closeQualTr();
            $(this).closest("tr").next(".qualsubTr").show();
            $(this).closest("tr").next(".qualsubTr").find(".subDiv").slideDown("slow");
        }
        else {
            $(this).closest("tr").next(".qualsubTr").find(".subDiv").slideUp("slow");
            $(this).closest("tr").next(".qualsubTr").slideUp("slow");
        }
    });
}

function bindQualExpandTrInput() {
    var $mainTr = $(".qualmainTrInput");
    $mainTr.focus(function (e) {
        if (!$(this).closest("tr").next(".qualsubTr").is(":visible")) {
            closeQualTr()
            $(this).closest("tr").next(".qualsubTr").show();
            $(this).closest("tr").next(".qualsubTr").find(".subDiv").slideDown("slow");
        }
    });
}

function closeQualTr() {
    var $mainTr = $(".qualmainExp");
    $.each($mainTr, function () {
        $(this).closest("tr").next(".qualsubTr").find(".subDiv").slideUp("slow");
        $(this).closest("tr").next(".qualsubTr").slideUp("slow");
    });
}
function bindTaxCalculation() {
    $(".qualChange").each(function () {
        CalculateTax($(this)[0].id);
    });
}

function CalculateTax(id) {
    //if (bReady==false) return;
    var key1 = id.split('_')[1],
        key2 = id.split('_')[3];

    var sname = $('#QualRowRef_' + key1).val();
    var dbaseAmt= parseFloatVal(isNullCheck($('#' + sname).val(),'number'));

    CalculateQualifier(dbaseAmt,key1);
    var dTaxAmt = parseFloatVal(isNullCheck($('#QualTotalAmt_' + key1).val(),'number'));

    var k1 = sname.split('_')[1],
        k2 = sname.split('_')[3];

    $('#BillAbs_' + k1 + '_TaxAmt_' + k2).val(dTaxAmt);
    $('#BillAbs_' + k1 + '_NetAmt_' + k2).val(dTaxAmt+dbaseAmt);

//    calcTotal();
}

function calcTotal() {
    var $curAmt = $('input[id^=CurAmt_]'),
        gcurTotal = 0,
        gtaxTotal= 0,
        gnetTotal= 0,
        glateTotal= 0,
        gpaidTotal= 0;
    $.each($curAmt, function () {
        var acurTotal = 0,
            ataxTotal= 0,
            anetTotal= 0,
            alateTotal= 0,
            apaidTotal= 0;

        var $this = $(this),
            name = $this[0].id,
            key = name.split('_')[1];
        if (name.indexOf('__') != -1 || name.indexOf('_CurAmt_') != -1 || name.indexOf('excel') != -1) return;

        acurTotal = parseFloatVal(isNullCheck($('#CurAmt_' + key).val(),'number'));
        ataxTotal = parseFloatVal(isNullCheck($('#TaxAmt_' + key).val(),'number'));
        anetTotal = parseFloatVal(isNullCheck($('#NetAmt_' + key).val(),'number'));
        alateTotal = parseFloatVal(isNullCheck($('#interestAmt_' + key).val(),'number'));
        apaidTotal = parseFloatVal(isNullCheck($('#PaidAmt_' + key).val(),'number'));

        gcurTotal = gcurTotal+ acurTotal;
        gtaxTotal = gtaxTotal+ ataxTotal;
        gnetTotal = gnetTotal+ anetTotal;
        gpaidTotal = gpaidTotal+ apaidTotal;
        glateTotal = glateTotal+ alateTotal;

    });

    $('#BillCurTotal').val(sanitizeNumber(gcurTotal,2,true));
    $('#BillTaxTotal').val(sanitizeNumber(gtaxTotal,2,true));
    $('#BillNetTotal').val(sanitizeNumber(gnetTotal,2,true));
    $('#BilllateTotal').val(sanitizeNumber(glateTotal,2,true));
    $('#BillPaidTotal').val(sanitizeNumber(gpaidTotal,2,true));
}


function fillRowRefEditMode() {
    var $mainTr = $(".qualmainTr"),
        iTotalCount= 0,
        ikey =0;
    $.each($mainTr, function () {
        var $x =$(this),
            $y = $x.prev(),
            akey1 = 0,
            akey2 = 0;
        $y.find(".qualRefId").each(function () {
            var $z =$(this);
            akey1 = parseFloatVal($z[0].id.split('_')[1]);
            akey2 = parseFloatVal($z[0].id.split('_')[3]);
        });
        $x.find(".qualTypeId").each(function () {
            var $n =$(this),
                key1 = parseFloatVal($n[0].id.split('_')[1]);
            if (iTotalCount < key1) iTotalCount = key1;
            if (ikey != key1) {
                ikey = key1;
                var sname = 'BillAbs_' + akey1 + '_CurAmt_' + akey2;
                $('#QualRowRef_' + key1).val(sname);
                $('#BillAbs_' + akey1 + '_QualRefId_' + akey2).val(key1);
            }
        });
    });
    $('#QualTotalRowId').val(iTotalCount);
}


function CalculateQualifier(baseValue, key1) {
    //alert(baseValue);
    var rows = $('#QualRowId_' + key1).val();
    var sformula="";
    var sname = $('#QualRowRef_' + key1).val();
    var dbaseAmt= parseFloatVal(isNullCheck($('#' + sname).val(),'number'));
    var dTotalQualAmt=0;

    for (i = 1; i <= rows; i++) {
        var sRef = $('#Qual_' + key1 + '_Ref_' + i).val().trim();
        var sFormula = $('#Qual_' + key1 + '_Exp_'+ i).val();

        var dPer = isNullCheck($('#Qual_' + key1 + '_ExpPer_'+ i).val(),'number');
        var sbaseRef = 'R0';
        if (parseFloatVal(dPer) ==0) dPer=100;
        sFormula = sFormula.replace(new RegExp(sbaseRef, 'g'), dbaseAmt);

        var fvaule = computeEval(sFormula);
        $('#Qual_' + key1 + '_ExpValue_' + i).val(sanitizeNumber(fvaule,2,true));

        var iQualTypeid = $('#Qual_' + key1 + '_TypeId_' + i).val();
        if (iQualTypeid==1) {
            var dTaxablePer = parseFloatVal(isNullCheck($('#Qual_' + key1 + '_TaxablePer_' + i).val(),'number'));
            var dTaxPer = parseFloatVal(isNullCheck($('#Qual_' + key1 + '_TaxPer_' + i).val(),'number'));
            var dCess = parseFloatVal(isNullCheck($('#Qual_' + key1 + '_CessPer_' + i).val(),'number'));
            var dEDCess = parseFloatVal(isNullCheck($('#Qual_' + key1 + '_EduCessPer_' + i).val(),'number'));
            var dHEDCess = parseFloatVal(isNullCheck($('#Qual_' + key1 + '_HEduCessPer_' + i).val(),'number'));
            var dNetPer = dTaxPer + (dTaxPer * (dCess +  dEDCess + dHEDCess))/100;
            $('#Qual_' + key1 + '_NetPer_' + i).val(dNetPer);

            $('#Qual_' + key1 + '_NetPer_' + i).val(sanitizeNumber(dNetPer,2,true));
            $('#Qual_' + key1 + '_ExpPer_'+ i).val(sanitizeNumber(dNetPer,2,true));

            var dTaxableAmt =  fvaule* (dTaxablePer/100);
            var dTaxAmt =  dTaxableAmt* (dTaxPer/100);
            var dCessAmt =  dTaxAmt* (dCess/100);
            var dEDAmt =  dTaxAmt* (dEDCess/100);
            var dHEDAmt =  dTaxAmt* (dHEDCess/100);
            var dNetAmt = dTaxAmt+dCessAmt+dEDAmt+dHEDAmt;

            $('#Qual_' + key1 + '_TaxableAmt_'+ i).val(sanitizeNumber(dTaxableAmt,2,true));
            $('#Qual_' + key1 + '_TaxPerAmt_'+ i).val(sanitizeNumber(dTaxAmt,2,true));
            $('#Qual_' + key1 + '_CessAmt_'+ i).val(sanitizeNumber(dCessAmt,2,true));
            $('#Qual_' + key1 + '_EduCessAmt_'+ i).val(sanitizeNumber(dEDAmt,2,true));
            $('#Qual_' + key1 + '_HEduCessAmt_'+ i).val(sanitizeNumber(dHEDAmt,2,true));
            $('#Qual_' + key1 + '_NetAmt_'+ i).val(sanitizeNumber(dNetAmt,2,true));

            dAmt = dNetAmt;
        } else if (iQualTypeid==2) {
            var dTaxablePer = parseFloatVal(isNullCheck($('#Qual_' + key1 + '_TaxablePer_' + i).val(),'number'));
            var dTaxPer = parseFloatVal(isNullCheck($('#Qual_' + key1 + '_TaxPer_' + i).val(),'number'));
            var dKKCess = parseFloatVal(isNullCheck($('#Qual_' + key1 + '_KKCessPer_' + i).val(),'number'));
            var dSBCess = parseFloatVal(isNullCheck($('#Qual_' + key1 + '_SBCessPer_' + i).val(),'number'));

            var dNetPer = dTaxPer + dKKCess + dSBCess;

            $('#Qual_' + key1 + '_NetPer_' + i).val(dNetPer);
            $('#Qual_' + key1 + '_NetPer_' + i).val(sanitizeNumber(dNetPer,2,true));
            $('#Qual_' + key1 + '_ExpPer_'+ i).val(sanitizeNumber(dNetPer,2,true));

            var dTaxableAmt =  fvaule* (dTaxablePer/100);
            var dTaxAmt =  dTaxableAmt* (dTaxPer/100);
            var dKKCessAmt = dTaxableAmt * (dKKCess / 100);
            var dSBCessAmt = dTaxableAmt * (dSBCess / 100);

            var dNetAmt = dTaxAmt + dKKCessAmt + dSBCessAmt;

            $('#Qual_' + key1 + '_TaxableAmt_'+ i).val(sanitizeNumber(dTaxableAmt,2,true));
            $('#Qual_' + key1 + '_TaxPerAmt_'+ i).val(sanitizeNumber(dTaxAmt,2,true));
            $('#Qual_' + key1 + '_KKCessAmt_' + i).val(sanitizeNumber(dKKCessAmt, 2, true));
            $('#Qual_' + key1 + '_SBCessAmt_' + i).val(sanitizeNumber(dSBCessAmt, 2, true));
            $('#Qual_' + key1 + '_NetAmt_'+ i).val(sanitizeNumber(dNetAmt,2,true));

            dAmt = dNetAmt;
        } else {
            var dAmt = parseFloatVal(fvaule) * (parseFloatVal(dPer) / 100);
        }
        $('#Qual_' + key1 + '_Amount_' + i).val(sanitizeNumber(dAmt,2,true));
        if ($('#Qual_' + key1 + '_YesNo_' + i).is(':checked') == true) dTotalQualAmt = dTotalQualAmt+ parseFloatVal(dAmt);
        for (j = i; j <= rows; j++) {
            var sFormula = $('#Qual_' + key1 + '_Exp_'+ i).val();
            sFormula = sFormula.replace(new RegExp(sRef, 'g'), dAmt);
        }
    }
    $('#QualTotalAmt_' + key1).val(sanitizeNumber(dTotalQualAmt,2,true)).trigger('change');
    qualTotal();
}
function computeEval(formula) {
    with (document.forms){
        with (Math) {
            A = eval((formula));
        }
    } return A;
}

function signChange(x) {
    var $this = $(x);
    if ($this.hasClass( "fa-plus" )) {
        $this.removeClass('fa-plus clr-gre');
        $this.addClass('fa-minus clr-red');
        var key1 = $this[0].id.split('_')[1],
            key2 = $this[0].id.split('_')[3];
        $('#Qual_' + key1 + '_Sign_' + key2).val('-');
    } else {
        $this.removeClass('fa-minus clr-red');
        $this.addClass('fa-plus clr-gre');
        var key1 = $this[0].id.split('_')[1],
            key2 = $this[0].id.split('_')[3];
        $('#Qual_' + key1 + '_Sign_' + key2).val('+');
    }
}

function qualTotal() {
    var iRows = $('#QualTotalRowId').val();
    var arrQual =[];
    for (i = 1; i <= iRows; i++) {
        $qualrows = $('input[id*=Qual_'+i+'_Ref_]'),
            $.each($qualrows, function () {
                var $this = $(this),
                    name = $this[0].id,
                    keys = name.split('_'),
                    key1 = keys[1],
                    key2 = keys[3];

                var sQualName = $('#Qual_' + key1 + '_Desc_' + key2).val();
                var iQualifierId = $('#Qual_' + key1 + '_Id_' + key2).val();
                var dAmt =  parseFloatVal(isNullCheck($('#Qual_' + key1 + '_Amount_' + key2).val(),'number'));
                var sSign = $('#Qual_' + key1 + '_Sign_' + key2).val();
                if (sSign =="") sSign ="+";

                if (sSign =="-") { dAmt = dAmt*(-1); }

                if (dAmt !=0) {
                    arrQual.push({QualifierId:iQualifierId, QualName: sQualName, Amount: dAmt});
                }
            });
    }

    var result = [];
    arrQual.reduce(function (res, value) {
        if (!res[value.QualifierId]) {
            res[value.QualifierId] = {
                Amount: 0,
                QualName: value.QualName,
                QualifierId: value.QualifierId
            };
            result.push(res[value.QualifierId])
        }
        res[value.QualifierId].Amount += value.Amount
        return res;
    }, {});

    var iCount=0;

    $("#totaltaxTable tbody").empty();
    $('#billqualrowid').val(iCount);
    $.each(result,function(index,element){
        iCount = +iCount+1;
        var $tbody = $('#totaltaxTable tbody');
        var template = $('#dummy-totaltaxTable tbody').html();
        $tbody.append(template.replace(/__1/g, '_' + iCount));

        $('#QualName_' + iCount).val(element.QualName);
        $('#QualAmt_' + iCount).val(numberFormat(element.Amount,'C'));
        $('#QualifierId_' + iCount).val(element.QualifierId);

        $('#billqualrowid').val(iCount);
    });
}

bindUpdateReceiptTax_onChange();
bindUpdateReceiptTaxTotal_onChange();
bindUpdateNetAmount_onChange();

function bindUpdateReceiptTax_onChange() {
    $('.receipt-type-table').on('change', 'input[id^="QualTotalAmt_"]', function() {
        var $this = $(this),
            curTax = parseFloatVal($this.val());

        var $tarTr = $this.closest('table').closest('tr').prev('tr');
        var curAmt = parseFloatVal($tarTr.find('.amount').val()),
            netAmt = curAmt + curTax;
        $tarTr.find('.net-amount').val(netAmt.toFixed(2));
        $tarTr.find('.qual-amount').val(curTax.toFixed(2)).trigger('change');
    });
}

function bindUpdateReceiptTaxTotal_onChange() {
    $('.receipt-type-table').on('change', 'input.qual-amount', function() {

        var $tarTable = $(this).closest('table'),
            totAmt = 0;

        $tarTable.find('.qual-amount').each(function() {
            totAmt += parseFloatVal($(this).val());
        });

        var curAmt =  parseFloatVal($tarTable.find('.total-amount').val()),
            netAmt = curAmt + totAmt;
        $tarTable.find('.total-net-amount').val(netAmt.toFixed(2));
        $tarTable.find('.total-qual-amount').val(totAmt.toFixed(2)).trigger('change');
    });
}

function bindUpdateNetAmount_onChange() {
    $('.receipt-type-table').on('change', 'input.total-qual-amount', function() {

        var $tarTable = $(this).closest('table');
        var totTax = 0;
        $tarTable.find('input.total-qual-amount').each(function() {
            totTax += parseFloatVal($(this).val());
        });

        var $tarTaxTr = $tarTable.closest('tr').prev('tr');
        $tarTaxTr.find('.unit-qual-amt').val(totTax.toFixed(2));

        var unitAmt = parseFloatVal($tarTaxTr.find('.unit-amt').val()),
            netAmt = unitAmt + totTax;

        $tarTaxTr.find('.unit-net-amt').val(netAmt.toFixed(2));

    });
}
</script>