<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css';?>" />
<style>
    .form-group1 {margin-bottom:5px; }
    .upload-pf {border: 1px solid #ddd; box-shadow: 0 0 0 2px #ffffff, 0 0 0 3px #7B7EBA; height: 118px; margin: 25px 10px 0 20px;overflow: hidden;float: left;position: relative;width: 80%;}
    .upload-pf img {width: 100% !important;height: 118px !important;background:#fff; }
    .upload-pf .ovrly {position: absolute;background: rgba(0, 0, 0, 0.5);height: 100%;right: 100%;top: 0;width: 100%;     -webkit-transition: all 0.5s;-moz-transition: all 0.5s; -o-transition: all 0.5s;transition: all 0.5s;}
    .upload-pf .buttons {position: absolute;top: 50%;right: -100%;-webkit-transition: all 0.5s;-moz-transition: all 0.5s;
        -o-transition: all 0.5s;transition: all 0.5s;-webkit-transform: translate(50%, -50%);-moz-transform: translate(50%, -50%);-ms-transform: translate(50%, -50%);-o-transform: translate(50%, -50%);transform: translate(50%, -50%);}
    .upload-pf .buttons .fa {margin: 0 1px;background: rgba(256, 256, 256, 0.9);-webkit-box-shadow: 0 0 1px rgba(0, 0, 0, 0.3);-moz-box-shadow: 0 0 1px rgba(0, 0, 0, 0.3);box-shadow: 0 0 1px rgba(0, 0, 0, 0.3);-webkit-border-radius: 50%;  -moz-border-radius: 50%;border-radius: 50%;color: rgba(50, 50, 50, 0.9);display: inline-block;line-height: 40px;     font-size: 16px;text-align: center;text-decoration: none;width: 40px;cursor:pointer;height: 40px;}
    .upload-pf:hover .buttons {right: 50%;}
    .upload-pf:hover .ovrly {right: 0;}
    .proname_btn a{ color: #112c45; font-weight:600}
    .subs a:hover{color:#333 !important;}
</style>
<div class="content_wrapper padlr0">
    <input type="hidden" id="labourRegId" name="labourRegId" value="<?php echo $labourRegId; ?>" />
    <input type="hidden" id="labourId" name="labourId" value="<?php echo $labourId; ?>" />
    <input type="hidden" id="mode" name="mode" value="<?php echo $mode; ?>" />


    <div id="divcc" class="container-fluid" style="<?php echo ($labourRegId !=0 || $labourId!=0) ? 'display:none' : ''; ?>">
        <div class="row">
            <div class="col-lg-12 page_tittle">
                <div class="col-lg-12">
                    <h1 class="text-center">Labour Master -  Add New Labours</h1>
                </div>
            </div>
            <div class="col-lg-12 top_ct zoomIn animated" id="MainWrapper">
                <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 prt-next">
                    <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 top-next">
                        <div class="col-lg-12 frmwrk_div" id="projects_list">
                            <!--                            <input type="text" name="CostCentre" id="CostCentre" class="form-control lbl_move" style="height:30px !important" value="--><?php //echo (isset($costCentreName)) ? $costCentreName : '';?><!--" --><?php //echo (isset($costCentreName) &&  $costCentreName!='') ? 'readonly': '';?><!-- />-->
                            <input class="parent_text form-control lbl_move" type="text" value="<?php echo (isset($costCentreName)) ? $costCentreName : '';?>" name="CostCentre" id="CostCentre" label="Select Cost Centre" />

                        </div>
                        <div class="savebtn_areas col-lg-9 col-sm-9 col-sm-offset-3 col-xs-offset-4 col-lg-offset-3">
                            <ul>
                                <li class="subs"><a style="background:#3399ff !important;padding:5px 13px;" onclick="showEntry();" id="continue">Next<i style="margin-left:4px" class="fa fa-arrow-right"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>

    <div id="divdetails" style="<?php echo ($labourRegId ==0 && $labourId==0) ? 'display:none' : ''; ?>">
        <form method="post" id="formWrapper" enctype="multipart/form-data">
            <input type="hidden" name="CostCentreId" id="CostCentreId" value="<?php echo (isset($costCentreId)) ? $costCentreId : '';?>" />
            <div class="container-fluid">
                <h1 class="col-md-12 text-left animated growIn">Labour Master - Entry</h1>
                <div class="col-sm-3">
                    <label for="refNo" class="bk_lbl bk_lbl_inpt splcharc">Ref No <span class="colon_r">:</span></label>
                    <input class="bk_lbl_inpt inputbg_ef bk_inpt1 splcharc" style="font-weight:600 !important" name="refNo" data-bsfshare="refNo" id="refNo" onchange="" value="<?php echo (!isset($labRegister) && $genType) ? $refNo : ''; echo (isset($labRegister)) ? $labRegister['RefNo'] : '';?>" readonly="" type="text" />
                </div>
                <div class="col-sm-4">
                    <label for="refDate" class="bk_lbl bk_lbl_inpt"><span class="bkspan_calendar"><i class="fa fa-calendar-o"></i></span> Ref Date <span class="colon_r">:</span></label>
                    <input class="date_picker bk_lbl_inpt no_bg bk_inpt inputbg_ef"style="font-weight:600 !important" name="refDate" data-bsfshare="refDate" readonly="" id="refDate" onchange="validateDate(this);" value="<?php if(isset($labRegister) && ($labRegister['RefDate'] != NULL)) { echo date(" d-m-Y ", strtotime($labRegister['RefDate'])); } else { echo date("d-m-Y "); } ?>" type="text" />
                </div>
                <div class="col-sm-5" style="margin-bottom:7px">
                    <label class="" style="text-align:left;color: #244996;font-weight:400">Cost Centre<span class="colon_r">:</span></label>
                    <div class="btn-group proname_btn"> <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"><span class="edit_symbols" data-placement="right" data-toggle="tooltip" data-original-title="Change&nbsp;CostCentre&nbsp;Name"><i class="fa fa-caret-down "></i></span></a>
                        <div class="dropdown-menu toolbar_ddown proname_ddown arrow" role="menu">
                            <ul>
                                <?php
                                foreach($inarr_costcenter as $data){?>
                                    <li><a href="javascript:void(0);" class="followupId" data-index="<?php echo $data['data'];?>" ><?php echo ucfirst($data['value']);?></a></li>
                                <?php }	?>
                            </ul>
                        </div>
                    </div>

                    <!--                    <div class="btn-group proname_btn"> <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"><span class="edit_symbols" data-placement="right" data-toggle="tooltip" data-original-title="Change&nbsp;Followup&nbsp;Name"><i class="fa fa-caret-down "></i></span></a>-->
                    <!--                        <div class="dropdown-menu toolbar_ddown proname_ddown arrow" role="menu">-->
                    <!--                            <ul>-->
                    <!--                                <li><a href="javascript:void(0);" class="followupId">dfg</a></li>-->
                    <!--                            </ul>-->
                    <!--                        </div>-->
                    <!--                    </div>-->

                    <!--                <div class="col-sm-8">-->
                    <!--                    <input type="text" name="CostCentre" id="CostCentre" class="form-control lbl_move" style="height:30px !important" value="--><?php //echo (isset($costCentreName)) ? $costCentreName : '';?><!--" --><?php //echo (isset($costCentreName) &&  $costCentreName!='') ? 'readonly': '';?><!-- />-->
                    <!--                    <input type="hidden" name="CostCentreId" id="CostCentreId" value="--><?php //echo (isset($costCentreId)) ? $costCentreId : '';?><!--" />-->
                    <!--                </div>-->
                </div>
                <div class="col-lg-12 form-group">
                    <!--<div class="error_message selOne" style="padding-right: 10px;"></div>-->
                    <div class="table-responsive topsp animated-panel zoomIn" style="animation-delay: 0.2s;">
                        <table id="labourTable" class="table" style=" margin-bottom:0px; ">
                            <thead>
                            <tr class="popuptable-topfix">
                                <th width="11%">Contractor</th>
                                <th width="11%">Labour Name</th>
                                <th width="8%">Labour Type</th>
                                <th width="4%">&nbsp;</th>
                            </tr>
                            </thead>
                            <tbody id="mainBody">
                            <?php
                            $i = 0;
                            if (isset($labTrans)) {
                                foreach($labTrans as $lTrans) { $i++; $iltransid = $lTrans['LabourTransId']; ?>
                                    <tr>
                                        <td width="11%">
                                            <input class="parent_text groupSuggest" type="text" name="groupName_<?php echo $i; ?>" id="groupName_<?php echo $i; ?>" value="<?php echo $lTrans['LabourGroupName']; ?>" readonly />
                                            <input type="hidden" name="groupId_<?php echo $i; ?>" id="groupId_<?php echo $i; ?>" value="<?php echo $lTrans['LabourGroupId']; ?>" />
                                            <input type="hidden" name="vendorId_<?php echo $i; ?>" id="vendorId_<?php echo $i; ?>" value="<?php echo $lTrans['VendorId']; ?>" />
                                            <input type="hidden" name="labourId_<?php echo $i; ?>" id="labourId_<?php echo $i; ?>" value="<?php echo $lTrans['LabourId']; ?>" />
                                        </td>
                                        <td width="11%" align="center">
                                            <input class="parent_text mainTrName" type="text" maxlength="200" name="labourName_<?php echo $i; ?>" id="labourName_<?php echo $i; ?>" value="<?php echo $lTrans['LabourName']; ?>" readonly />
                                        </td>
                                        <td width="5%">
                                            <input class="parent_text typeSuggest" type="text" name="typeName_<?php echo $i; ?>" id="typeName_<?php echo $i; ?>" value="<?php echo $lTrans['ResourceName']; ?>" readonly />
                                            <input type="hidden" name="typeId_<?php echo $i; ?>" id="typeId_<?php echo $i; ?>" value="<?php echo $lTrans['LabourTypeId']; ?>" />
                                        </td>
                                        <td width="4%">
                                            <ul class="action_btns">
                                                <li> <a href="javascript:void(0);" class="mainTr" id="exptr_<?php echo $i; ?>" ><i style="text-align:center" class="fa fa-chevron-circle-down" data-toggle="tooltip" data-placement="top" data-original-title="Expand"></i></a> </li>
                                                <li> <a href="javascript:void(0);" class="rowDelete_<?php echo $i; ?>" onclick="deleteRow(this, event);"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i></a> </li>
                                            </ul>
                                        </td>
                                    </tr>
                                    <tr class="subTr" style="display:none;">
                                        <td colspan="4">
                                            <div class="subDiv">
                                                <div class="col-lg-12 col-xs-12 slidingDiv1 animated fadeInUp" style="padding-top:30px;">
                                                    <div class="col-lg-6 col-lg-offset-0 col-xs-12 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0 mar-35">
                                                        <div class="col-sm-12 col-xs-12 form-group1">
                                                            <label>Id No</label>
                                                            <input type="text" class="form-control lbl_move" maxlength="50" id="idNo_<?php echo $i; ?>" data-idajax="" name="idNo_<?php echo $i; ?>" value="<?php echo $lTrans['Code']; ?>"  />
                                                        </div>
                                                        <div class="col-sm-12 col-xs-12 form-group1">
                                                            <label>Address</label>
                                                            <input class="form-control lbl_move" style="width:100%; height:45px !important;" maxlength="255" id="address_<?php echo $i; ?>" name="address_<?php echo $i; ?>" onKeyPress="return locationpicker(this);" value="<?php echo $lTrans['Address']; ?>">
                                                        </div>
                                                        <div class="col-sm-12 col-xs-12 form-group1">
                                                            <label>City</label>
                                                            <input type="text" class="form-control lbl_move citySuggest" name="city_<?php echo $i; ?>" id="city_<?php echo $i; ?>" value="<?php echo $lTrans['CityName']; ?>" data-name="locality" readonly />
                                                            <input type="hidden" name="cityId_<?php echo $i; ?>" id="cityId_<?php echo $i; ?>" value="<?php echo $lTrans['CityId']; ?>" />
                                                        </div>
                                                        <div class="col-sm-12 col-xs-12 form-group1">
                                                            <label>State</label>
                                                            <input type="text" class="form-control lbl_move" name="state_<?php echo $i; ?>" id="state_<?php echo $i; ?>" value="<?php echo $lTrans['StateName']; ?>" data-name="administrative_area_level_1"  readonly />
                                                        </div>
                                                        <div class="col-sm-6 col-xs-6 form-group1">
                                                            <label>Country</label>
                                                            <input type="text" class="form-control lbl_move"  name="country_<?php echo $i; ?>" id="country_<?php echo $i; ?>" value="<?php echo $lTrans['CountryName']; ?>" data-name="country" readonly />
                                                        </div>
                                                        <div class="col-sm-6 col-xs-6 form-group1">
                                                            <label>Pin Code</label>
                                                            <input type="text" class="form-control lbl_move" id="pinCode_<?php echo $i; ?>" name="pinCode_<?php echo $i; ?>" onKeyPress="return isNumberKey(event);" maxlength="6" value="<?php echo $lTrans['PinCode']; ?>"
                                                                   data-name="postal_code" />
                                                        </div>
                                                    </div>
                                                    <div class="col-lg-6 col-lg-offset-0 col-xs-12 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0 mar-35">
                                                        <div class="col-md-8 col-sm-7 col-xs-12">
                                                            <div class="col-sm-12 col-xs-12 form-group1" style="padding:0 !important">
                                                                <label>Mobile</label>
                                                                <input type="text" class="form-control lbl_move" id="mobile_<?php echo $i; ?>" name="mobile_<?php echo $i; ?>" onKeyPress="return isNumberKey(event);" maxlength="15" value="<?php echo $lTrans['Mobile']; ?>" />
                                                            </div>
                                                            <div class="col-sm-12 col-xs-12 form-group1" style="padding:0 !important">
                                                                <label>Email</label>
                                                                <input type="text" class="form-control lbl_move" id="email_<?php echo $i; ?>" maxlength="100" name="email_<?php echo $i; ?>" value="<?php echo $lTrans['Email']; ?>" />
                                                            </div>
                                                        </div>
                                                        <div class="col-md-4 col-sm-5 col-xs-12" id="browse_<?php echo $i; ?>" style="padding:0 !important" onclick="Imagebrowse(this);">
                                                            <div class="upload-pf"> <img id="showpic_<?php echo $i; ?>" src="<?php echo $this->basePath(); ?><?php echo "/";?><?php echo $lTrans['LabourProfile'];?>" onerror="this.src='<?php echo $this->basePath(); ?>/images/avatar.jpg';" /> <img id="blah_<?php echo $i; ?>" src="#" alt="your image" style="display:block;width:258px;height:280px" />
                                                                <input type="hidden" name="imageurl_<?php echo $i;?>" id="imageurl_<?php echo $i;?>" value="<?php echo $lTrans['LabourProfile']; ?>">
                                                                <div class="ovrly"></div>
                                                                <div class="buttons">
                                                                    <a href="#" class="fa fa-link"></a>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <input type="file" id="my_file_<?php echo $i; ?>" name="my_file_<?php echo $i; ?>" class="imageupload" accept="image/*" style="display: none;" />
                                                        <div class="col-sm-12 col-xs-12 form-group1">
                                                            <label>PF No</label>
                                                            <input type="text" class="form-control lbl_move" id="pfNo_<?php echo $i; ?>" name="pfNo_<?php echo $i; ?>" maxlength="50" value="<?php echo $lTrans['PFNo']; ?>" data-ajax=""  />
                                                        </div>
                                                        <div class="col-sm-12 col-xs-12 form-group1">
                                                            <label>Aadhaar No</label>
                                                            <input type="text" class="form-control lbl_move" id="adharNo_<?php echo $i; ?>" name="adharNo_<?php echo $i; ?>" value="<?php echo $lTrans['PFNo']; ?>" data-adharajax="" onKeyPress="return isNumberKey(event);" maxlength="12" />
                                                        </div>
                                                        <div class="col-sm-12 col-xs-12 form-group1">
                                                            <label>ESI No</label>
                                                            <input type="text" class="form-control lbl_move" id="esiNo_<?php echo $i; ?>" maxlength="50" name="esiNo_<?php echo $i; ?>" value="<?php echo $lTrans['ESINo']; ?>" data-esnoajax=""  />
                                                        </div>
                                                    </div>
                                                    <div class="clearfix"></div>
                                                    <div class="col-lg-12 col-xs-12">
                                                        <table class="table" style=" margin-bottom:10px;">
                                                            <thead>
                                                            <tr>
                                                                <th>Document Type</th>
                                                                <th>Document Description</th>
                                                                <th>&nbsp;</th>
                                                            </tr>
                                                            </thead>
                                                            <tbody>
                                                            <?php
                                                            $arrDoc = array_filter($documents, function($v) use($iltransid) { return $v['LabourTransId'] == $iltransid; });
                                                            $j=1;
                                                            foreach($arrDoc as $make) {
                                                                ?>
                                                                <tr>
                                                                    <td width="45%">
                                                                        <input class="parent_text docmentauto" name="document_<?php echo $i; ?>_type_<?php echo $j;?>" id="document_<?php echo $i; ?>_type_<?php echo $j;?>" type="text" value="<?php echo $make['Doc']; ?>"onkeypress="bindDocAutocomplete()">
                                                                        <input type="hidden"  value="<?php echo $make['DocumentId']; ?>" id="doctype_<?php echo $i;?>_auto_<?php echo $j;?>" name="doctype_<?php echo $i; ?>_auto_<?php echo $j;?>" onkeypress="bindDocAutocomplete()">
                                                                    </td>
                                                                    <td width="45%">
                                                                        <textarea class="parent_texts"  maxlength="255" name="document_<?php echo $i; ?>_desc_<?php echo $j;?>" id="document_<?php echo $i; ?>_desc_<?php echo $j;?>" onchange="addNewTenderDocRow(this)" ><?php echo $make['DocumentName'] ?></textarea></td>
                                                                    <td width="8%">
                                                                        <ul class="action_btns">
                                                                            <?php if(trim($make['DocumentURL']) !=''){?>
                                                                                <li style="float:left;"> <a download href="<?php echo  $this->basePath().'/'. $make['DocumentURL']; ?>"> <span data-toggle="tooltip" data-placement="left" data-original-title="View"><i class="fa fa-eye"></i></span> </a> </li>
                                                                                <input type="hidden" name="document_<?php echo $i; ?>_url_<?php echo $j; ?>" id="document_<?php echo $i; ?>_url_<?php echo $j; ?>" value="<?php echo $make['DocumentURL'];?>">
                                                                            <?php } else { ?>
                                                                                <li style="float:left;">
                                                                                    <a href="#" class="deleteTenderDoc_<?php echo $i; ?>_del_<?php echo $j;?>" style="display: none;"> <span data-toggle="tooltip" data-placement="left" data-original-title="Document Delete"><i class="fa fa-trash-o"></i></span> </a>
                                                                                </li>
                                                                            <?php } ?>
                                                                            <li style="float:left;"> <a href="#" onclick="deleteTenderDoc(this, event);"> <span data-toggle="tooltip" data-placement="left" data-original-title="Delete"><i class="fa fa-trash-o"></i></span> </a> </li>
                                                                        </ul>
                                                                    </td>
                                                                </tr>
                                                                <?php $j++; } ?>
                                                            <tr>
                                                                <td width="45%">
                                                                    <input class="parent_text docmentauto" name="document_<?php echo $i; ?>_type_<?php echo $j;?>" id="document_<?php echo $i; ?>_type_<?php echo $j;?>" type="text" onkeypress="bindDocAutocomplete()">
                                                                    <input type="hidden"   id="doctype_<?php echo $i;?>_auto_<?php echo $j;?>" name="doctype_<?php echo $i; ?>_auto_<?php echo $j;?>" onkeypress="bindDocAutocomplete()">
                                                                </td>
                                                                <td width="45%">
                                                                    <textarea class="parent_texts"  maxlength="255" name="document_<?php echo $i; ?>_desc_<?php echo $j;?>" id="document_<?php echo $i; ?>_desc_<?php echo $j;?>" onchange="addNewTenderDocRowupdate(this)" ></textarea></td>
                                                                <td width="8%">
                                                                    <ul class="action_btns">
                                                                        <li style="float:left;">
                                                                            <a href="#"> <span data-toggle="tooltip" data-placement="left" data-original-title="Click to attach documents" class="btn-file butclr_imp"> <i class="fa fa-paperclip dcm_atch"></i>
                                                                  <input type="file"  name="tenderDocFile_<?php echo $i; ?>_ttol_<?php echo $j;?>" id="tenderDocFile_<?php echo $i; ?>_ttol_<?php echo $j;?>">
                                                                  <input type="hidden" name="document_<?php echo $i; ?>_url_<?php echo $j; ?>" id="document_<?php echo $i; ?>_url_<?php echo $j; ?>" value="">
                                                                 </span> </a>
                                                                        </li>
                                                                        <li style="float:left;">
                                                                            <a href="#" class="deleteTenderDoc_<?php echo $i; ?>_del_<?php echo $j;?>" style="display: none;"> <span data-toggle="tooltip" data-placement="left" data-original-title="Document Delete"><i class="fa fa-trash-o"></i></span> </a>
                                                                        </li>
                                                                    </ul>
                                                                </td>
                                                            </tr>
                                                            <input type="hidden" name="tenderdocumentrowid_<?php echo $i ?>" id="tenderdocumentrowid_<?php echo $i ?>" value="<?php echo $j; ?>" />
                                                        </table>
                                                        <input type="hidden" name="tenderdocumentrowiddelete" id="tenderdocumentrowiddelete" value="<?php echo (isset($arrDoc) && count($arrDoc) != 0) ? count($arrDoc) : 1; ?>" />
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    <?php
                                } } if ($labourId ==0) { $i++; ?>
                                <tr>
                                    <td width="11%">
                                        <input class="parent_text groupSuggest" type="text" name="groupName_<?php echo $i; ?>" id="groupName_<?php echo $i; ?>" />
                                        <input type="hidden" name="groupId_<?php echo $i; ?>" id="groupId_<?php echo $i; ?>" />
                                        <input type="hidden" name="vendorId_<?php echo $i; ?>" id="vendorId_<?php echo $i; ?>" />
                                        <input type="hidden" name="labourId_<?php echo $i; ?>" id="labourId_<?php echo $i; ?>"/>
                                    </td>
                                    <td width="11%" align="center">
                                        <input class="parent_text mainTrName" type="text" maxlength="200" name="labourName_<?php echo $i; ?>" id="labourName_<?php echo $i; ?>" />
                                    </td>
                                    <td width="5%">
                                        <input class="parent_text typeSuggest" type="text" name="typeName_<?php echo $i; ?>" id="typeName_<?php echo $i; ?>" />
                                        <input type="hidden" name="typeId_<?php echo $i; ?>" id="typeId_<?php echo $i; ?>" />
                                    </td>
                                    <td width="4%">
                                        <ul class="action_btns">
                                            <li> <a href="javascript:void(0);" class="mainTr" id="exptr_<?php echo $i; ?>"><i style="text-align:center" class="fa fa-chevron-circle-down" data-toggle="tooltip" data-placement="top" data-original-title="Expand"></i></a> </li>
                                            <li> <a href="javascript:void(0);" class="rowDelete_<?php echo $i; ?>" onclick="deleteRow(this, event);" style="display:none;"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i></a> </li>
                                        </ul>
                                    </td>
                                </tr>
                                <tr class="subTr" style="display:none;">
                                    <td colspan="4">
                                        <div class="subDiv">
                                            <div class="col-lg-12 slidingDiv1 animated fadeInUp" style="padding-top:30px;">
                                                <div class="col-sm-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0 mar-35">
                                                    <div class="col-sm-12 col-xs-12 form-group1">
                                                        <label>Id No</label>
                                                        <input type="text" class="form-control lbl_move blur" maxlength="50" id="idNo_<?php echo $i; ?>" data-idajax="" name="idNo_<?php echo $i; ?>"  />
                                                    </div>
                                                    <div class="col-sm-12 col-xs-12 form-group1">
                                                        <label>Address</label>
                                                        <input type="text" class="form-control lbl_move" style="width:100%; height:45px !important;" maxlength="255" id="address_<?php echo $i; ?>" name="address_<?php echo $i; ?>" onKeyPress="return locationpicker(this);">
                                                    </div>
                                                    <div class="col-sm-12 col-xs-12 form-group1">
                                                        <label> City</label>
                                                        <input type="text" class="form-control lbl_move citySuggest" name="city_<?php echo $i; ?>" id="city_<?php echo $i; ?>" data-name="locality" readonly  />
                                                        <input type="hidden" class="form-control lbl_move citySuggest" name="cityId_<?php echo $i; ?>" id="cityId_<?php echo $i; ?>" />
                                                    </div>
                                                    <div class="col-sm-12 col-xs-12 form-group1">
                                                        <label> State</label>
                                                        <input type="text" class="form-control lbl_move" name="state_<?php echo $i; ?>" id="state_<?php echo $i; ?>" data-name="administrative_area_level_1" readonly />
                                                    </div>
                                                    <div class="col-sm-6 col-xs-6 form-group1">
                                                        <label>Country</label>
                                                        <input type="text" class="form-control lbl_move" name="country_<?php echo $i; ?>" id="country_<?php echo $i; ?>" data-name="country" readonly />
                                                    </div>
                                                    <div class="col-sm-6 col-xs-6 form-group1">
                                                        <label> Pin Code</label>
                                                        <input type="text" class="form-control lbl_move" id="pinCode_<?php echo $i; ?>" name="pinCode_<?php echo $i; ?>" data-name="postal_code" onKeyPress="return isNumberKey(event);" maxlength="6"/>
                                                    </div>
                                                </div>
                                                <div class="col-sm-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0 mar-35">
                                                    <div class="col-sm-7 col-md-8 col-xs-12" style="padding:0 !important">
                                                        <div class="col-sm-12 col-xs-12 form-group1">
                                                            <label> Mobile</label>
                                                            <input type="text" class="form-control lbl_move" id="mobile_<?php echo $i; ?>" name="mobile_<?php echo $i; ?>" onKeyPress="return isNumberKey(event);" maxlength="15" />
                                                        </div>
                                                        <div class="col-sm-12 col-xs-12 form-group1">
                                                            <label> Email</label>
                                                            <input type="text" class="form-control lbl_move" id="email_<?php echo $i; ?>" maxlength="100" name="email_<?php echo $i; ?>" />
                                                        </div>
                                                    </div>
                                                    <div class="col-md-4 col-sm-5 col-xs-12" id="browse_<?php echo $i; ?>" style="padding:0 !important" onclick="Imagebrowse(this);">
                                                        <div class="upload-pf"> <img id="showpic_<?php echo $i; ?>" src="<?php echo $this->basePath(); ?>/images/avatar.jpg" onerror="this.src='<?php echo $this->basePath(); ?>/images/avatar.jpg';" /> <img id="blah_<?php echo $i; ?>" src="#" alt="your image" style="display: none;width:258px;height:280px" />
                                                            <input type="hidden" name="imageurl_<?php echo $i;?>" id="imageurl_<?php echo $i;?>" >
                                                            <div class="ovrly"></div>
                                                            <div class="buttons">
                                                                <a href="#" class="fa fa-link"></a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <input type="file" id="my_file_<?php echo $i; ?>" name="my_file_<?php echo $i; ?>" class="imageupload" accept="image/*" style="display: none;" />

                                                    <div class="col-sm-12 col-xs-12 form-group1">
                                                        <label> PF No</label>
                                                        <input type="text" class="form-control lbl_move" id="pfNo_<?php echo $i; ?>" maxlength="50" name="pfNo_<?php echo $i; ?>" data-ajax=""  />
                                                    </div>
                                                    <div class="col-sm-12 col-xs-12 form-group1">
                                                        <label>Aadhaar No</label>
                                                        <input type="text" class="form-control lbl_move" id="adharNo_<?php echo $i; ?>" name="adharNo_<?php echo $i; ?>" data-adharajax="" onKeyPress="return isNumberKey(event);" maxlength="12"  />
                                                    </div>
                                                    <div class="col-sm-12 col-xs-12 form-group1">
                                                        <label> ESI No</label>
                                                        <input type="text" class="form-control lbl_move" id="esiNo_<?php echo $i; ?>" maxlength="50" name="esiNo_<?php echo $i; ?>" data-esnoajax=""  />
                                                    </div>
                                                </div>
												<div class="clearfix"></div>
                                                <div class="col-lg-12">
                                                    <table class="table" style=" margin-bottom:10px;" id="documenttable">
                                                        <thead>
                                                        <tr>
                                                            <th>Document Type</th>
                                                            <th>Document Description</th>
                                                            <th>&nbsp;</th>
                                                        </tr>
                                                        </thead>
                                                        <tbody>
                                                        <tr>
                                                            <td width="15%">
                                                                <input class="parent_text docmentauto" type="text" name="document_<?php echo $i; ?>_type_1" id="document_<?php echo $i; ?>_type_1" onkeypress="bindDocAutocomplete()" >
                                                                <input type="hidden" id="doctype_<?php echo $i; ?>_auto_1" name="doctype_<?php echo $i; ?>_auto_1" >
                                                            </td>
                                                            <td width="15%">
                                                                <textarea class="parent_texts" maxlength="255" name="document_<?php echo $i; ?>_desc_1" id="document_<?php echo $i; ?>_desc_1" onchange="addNewTenderDocRow(this)"></textarea>
                                                            </td>
                                                            <td class="action_btns_td" width="4%">
                                                                <ul class="action_btns">
                                                                    <li style="float:left;">
                                                                        <a href="#"> <span data-toggle="tooltip" data-placement="left" data-original-title="Click to attach documents" class="btn-file butclr_imp"> <i class="fa fa-paperclip dcm_atch"></i>
                                                                                  <input type="file"  name="tenderDocFile_<?php echo $i; ?>_ttol_1" id="tenderDocFile_<?php echo $i; ?>_ttol_1">
                                                                                  <input type="hidden" name="document_<?php echo $i; ?>_url_1" id="document_<?php echo $i; ?>_url_1" value="">
                                                                                 </span> </a>
                                                                    </li>
                                                                    <li style="float:left;">
                                                                        <a href="#" class="deleteTenderDoc_<?php echo $i; ?>_del_1" style="display: none;"> <span data-toggle="tooltip" data-placement="left" data-original-title="Document Delete"><i class="fa fa-trash-o"></i></span> </a>
                                                                    </li>
                                                                </ul>
                                                            </td>

                                                        </tr>
                                                        <input type="hidden" name="tenderdocumentrowid_<?php echo $i; ?>" id="tenderdocumentrowid_<?php echo $i; ?>" value="1" />
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            <?php } ?>
                            </tbody>
                            <tbody>
                            <tr>
                                <td colspan="4">
                                    <textarea class="remrk element" placeholder="Enter Remarks" maxlength="255" name="remarks" id="remarks"><?php echo (isset($labRegister)) ? $labRegister['Remarks'] : ''; ?></textarea>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                        <input type="hidden" name="rows" id="rows" value="<?php echo $i; ?>" />
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="col-lg-12 savebtn_area">
                    <ul>
                        <?php if(!isset($labRegister) || isset($labRegister) && ($labRegister['Approve'] != 'Y')) { ?>
                            <li id="submit-btn" class="dropdown save_btn float_r" style=""> <a class="ripple has-ripple" id="disablesubmit" href="javascript:void(0);" data-toggle="tooltip" title="" data-original-title="Submit!" style="position: relative; overflow: hidden;" onclick="return submitForm();">Submit <span class="ripple-wrapper"></span></a> </li>
                            <div class="error_message selOne col-lg-3 col-lg-offset-5" style="padding-right: 10px;margin-top:10px !important;float:left;left:0"></div>
                        <?php } ?>
                        <li class="can_btn float_l" style="padding-bottom:10px;"> <a style="padding:6px 15px !important;" href="<?php echo $this->basePath().'/wpm/labourstrength/labour-register'; ?>">Cancel</a> </li>
                    </ul>
                </div>
            </div>
        </form>
        <div class="fixed-action-btn active" data-toggle="tooltip" data-placement="left" id="divExcelImport" title="Import From Excel">
         <span class="butclr-ns btn-file">
              <p class="sam-up"><i class="fa fa-folder-open sap"></i></p>
              <input type="file" name="myfile" id="myfile" class="input-large filestyle" accept=".xls, .xlsx, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" onchange="getexcelfield(this)">
         </span>
        </div>
    </div>
</div>
<div class="clearfix"></div>

<table id="dummy-row" style="display:none;">
    <tbody>
    <tr>
        <td width="11%">
            <input class="parent_text groupSuggest" type="text" name="groupName__1" id="groupName__1" />
            <input type="hidden" name="groupId__1" id="groupId__1" />
            <input type="hidden" name="vendorId__1" id="vendorId__1" />
            <input type="hidden" name="labourId__1" id="labourId__1" />
        </td>
        <td width="11%" align="center">
            <input class="parent_text mainTrName" type="text" maxlength="200" name="labourName__1" id="labourName__1" />
        </td>
        <td width="5%">
            <input class="parent_text typeSuggest" type="text" name="typeName__1" id="typeName__1" />
            <input type="hidden" name="typeId__1" id="typeId__1" />
        </td>
        <td width="4%">
            <ul class="action_btns">
                <li> <a href="javascript:void(0);" class="mainTr" id="exptr__1"><i style="text-align:center" class="fa fa-chevron-circle-down"  data-toggle="tooltip" data-placement="top" data-original-title="Expand"></i></a> </li>
                <li> <a href="javascript:void(0);" class="rowDelete__1" onclick="deleteRow(this, event);" style="display:none;"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i></a> </li>
            </ul>
        </td>
    </tr>
    <tr class="subTr" style="display:none;">
        <td colspan="4">
            <div class="subDiv">
                <div class="col-lg-12 col-xs-12 slidingDiv1 animated fadeInUp" style="padding-top:30px;">
                    <div class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0 mar-35">
                        <div class="col-lg-12 col-xs-12 form-group1">
                            <label>Id No</label>
                            <input type="text" class="form-control lbl_move blur" maxlength="50" id="idNo__1" name="idNo__1" data-idajax=""  />
                        </div>
                        <div class="col-lg-12 col-xs-12 form-group1">
                            <label>Address</label>
                            <input type="text" class="form-control lbl_move" style="width:100%; height:45px !important;"  maxlength="255" id="address__1" name="address__1" onKeyPress="return locationpicker(this);" >
                        </div>
                        <div class="col-lg-12 col-xs-12 form-group1">
                            <label>City</label>
                            <input type="text" class="form-control lbl_move citySuggest" name="city__1" id="city__1" data-name="locality" readonly/>
                            <input type="hidden" class="form-control lbl_move citySuggest" name="cityId__1" id="cityId__1"  />
                        </div>
                        <div class="col-lg-12 col-xs-12 form-group1">
                            <label>State</label>
                            <input type="text" class="form-control lbl_move" name="state__1" id="state__1" data-name="administrative_area_level_1" readonly />
                        </div>
                        <div class="col-lg-6 col-xs-6 form-group1">
                            <label>Country</label>
                            <input type="text" class="form-control lbl_move" name="country__1" id="country__1" data-name="country" readonly />
                        </div>
                        <div class="col-lg-6 col-xs-6 form-group1">
                            <label>Pin Code</label>
                            <input type="text" class="form-control lbl_move" id="pinCode__1" name="pinCode__1" onKeyPress="return isNumberKey(event);" data-name="postal_code"  maxlength="6"/>
                        </div>
                    </div>
                    <div class="col-sm-6 col-xs-12 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0 mar-35">
                        <div class="col-sm-7 col-xs-12 col-md-8" style="padding:0 !important">
                            <div class="col-sm-12 col-xs-12 form-group1">
                                <label> Mobile</label>
                                <input type="text" class="form-control lbl_move" id="mobile__1" name="mobile__1" onKeyPress="return isNumberKey(event);" maxlength="15" />
                            </div>
                            <div class="col-sm-12 col-xs-12 form-group1">
                                <label> Email</label>
                                <input type="text" class="form-control lbl_move" id="email__1" maxlength="100" name="email__1" />
                            </div>
                        </div>
                        <div class="col-md-4 col-xs-12 col-sm-5" id="browse__1" style="padding:0 !important" onclick="Imagebrowse(this);">
                            <div class="upload-pf"> <img id="showpic__1" src="<?php echo $this->basePath(); ?>/images/avatar.jpg" onerror="this.src='<?php echo $this->basePath(); ?>/images/avatar.jpg';" /> <img id="blah__1" src="#" alt="your image" style="display: none;width:258px;height:280px" />
                                <input type="hidden" name="imageurl__1" id="imageurl__1" value="">
                                <div class="ovrly"></div>
                                <div class="buttons">
                                    <a class="fa fa-link"></a>
                                </div>
                            </div>
                        </div>
                        <input type="file" class="imageupload" id="my_file__1" name="my_file__1" accept="image/*" style="display: none;" />
                        <div class="col-sm-12 col-xs-12 form-group1">
                            <label> PF No</label>
                            <input type="text" class="form-control lbl_move" id="pfNo__1" name="pfNo__1" maxlength="50"  data-ajax=""  />
                        </div>
                        <div class="col-sm-12 col-xs-12 form-group1">
                            <label>Aadhaar No</label>
                            <input type="text" class="form-control lbl_move" id="adharNo__1" name="adharNo__1" onKeyPress="return isNumberKey(event);" maxlength="12" />
                        </div>
                        <div class="col-sm-12 col-xs-12 form-group1">
                            <label> ESI No</label>
                            <input type="text" class="form-control lbl_move" id="esiNo__1" name="esiNo__1"  maxlength="50"/>
                        </div>
                    </div>
                    <div class="col-lg-12 col-xs-12">
                        <table class="table" style=" margin-bottom:10px;">
                            <thead>
                            <tr>
                                <th>Document Type</th>
                                <th>Document Description</th>
                                <th>&nbsp;</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td width="15%">
                                    <input class="parent_text docmentauto" type="text" name="document__1_type_1" id="document__1_type_1" data-id="qwqrr"  onkeypress="bindDocAutocomplete()">
                                    <input type="hidden" id="doctype__1_auto_1" name="doctype__1_auto_1">
                                </td>
                                <td width="15%">
                                    <textarea class="parent_texts" maxlength="255" name="document__1_desc_1" id="document__1_desc_1" onchange="addNewTenderDocRow(this)"></textarea>
                                </td>
                                <td class="action_btns_td" width="4%">
                                    <ul class="action_btns">
                                        <li style="float:left;">
                                            <a href="#"> <span data-toggle="tooltip" data-placement="left" data-original-title="Click to attach documents" class="btn-file butclr_imp"> <i class="fa fa-paperclip dcm_atch"></i>
                                                      <input type="file"  name="tenderDocFile__1_ttol_1" id="tenderDocFile__1_ttol_1">
                                                      <input type="hidden" name="document__1_url_1" id="document__1_url_1" >
                                            </span> </a>
                                        </li>
                                        <li style="float:left;">
                                            <a href="#" class="deleteTenderDoc__1_del_1" style="display: none;"> <span data-toggle="tooltip" data-placement="left" data-original-title="Document Delete"><i class="fa fa-trash-o"></i></span> </a>
                                        </li>
                                    </ul>
                                </td>
                            </tr>
                            <input type="hidden" name="tenderdocumentrowid__1" id="tenderdocumentrowid__1" value="1"  />
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </td>
    </tr>
    </tbody>
</table>
<table id="dummy-tenderdoctype" style="display: none;">
    <tbody>
    <tr>
        <td width="15%">
            <input class="parent_text docmentauto" type="text" id="document__1_type__9" name="document__1_type__9" maxlength="155"  />
            <input type="hidden" id="doctype__1_auto__9" name="doctype__1_auto__9">
        </td>
        <td width="15%">
            <textarea class="parent_texts" maxlength="255" name="document__1_desc__9" id="document__1_desc__9" onchange="addNewTenderDocRow(this)"></textarea>
        </td>
        <td width="4%" class="action_btns_td">
            <ul class="action_btns">
                <li style="float:left;">
                    <a href="#"> <span data-toggle="tooltip" data-placement="left" data-original-title="Click to attach documents" class="btn-file butclr_imp"> <i class="fa fa-paperclip dcm_atch" ></i>
            <input type="file" name="tenderDocFile__1_ttol__9" id="tenderDocFile__1_ttol__9">
            </span> </a>
                </li>
                <li style="float:left;">
                    <a href="#" class="deleteTenderDoc__1_del__9" onclick="deleteTenderDoc(this, event);" style="display: none;"> <span data-toggle="tooltip" data-placement="left" data-original-title="Document Delete"><i class="fa fa-trash-o"></i></span> </a>
                </li>
            </ul>
        </td>
    </tr>
    </tbody>
</table>
<div id="excelfieldmodal" class="modal fade" role="dialog" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-lg" style="width: 50%">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><i class="fa fa-times-circle-o clpot"></i></button>
                <h1>Resource Import Sheet - Assign Fields</h1>
            </div>
            <div class="modal-body">
                <div class="table-responsive popuptable animated-panel zoomIn" style="overflow:visible;animation-delay: 0.2s;">
                    <table class="table" width="100%" style=" margin-bottom:0px;">
                        <tbody>
                        <tr id="excelfieldTable">
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="modal-footer"> <a href="javascript:void(0);" class="md_cance" data-dismiss="modal" data-toggle="tooltip" title="" data-original-title="Cancel" style="position: relative; overflow: hidden;">Cancel<span class="ripple-wrapper"></span><span class="ripple-wrapper"></span></a>
                <button type="button" class="md_ok" onclick="return fileupload()" >Next</button>
            </div>
        </div>
    </div>
</div>
<div id="newGroupModal" class="modal fade" role="dialog" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><i class="fa fa-times-circle-o clpot"></i></button>
                <h1>Add New Internal Labour Group</h1>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label style="margin-bottom: 10px;">Internal Group Name</label>
                    <input type="hidden" id="gpCurId" />
                    <input type="text" maxlength="255" class="parent_text" id="gpName" />
                </div>
                <div class="form-group"> </div>
                <div class="clearfix"></div>
            </div>
            <div class="modal-footer"> <a href="javascript:void(0);" class="md_cance" onclick="return newGroupClose();" data-toggle="tooltip" data-original-title="Cancel" style="position: relative; overflow: hidden;">Cancel<span class="ripple-wrapper"></span><span class="ripple-wrapper"></span></a>
                <button type="button" class="md_ok" onclick="return newGroupAdd();" data-toggle="tooltip" data-original-title="OK">OK</button>
            </div>
        </div>
    </div>
</div>
<div id="excelmodal" class="modal fade" role="dialog" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-lg" style="width: 75%">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><i class="fa fa-times-circle-o clpot"></i></button>
                <h1>Resource Import Sheet</h1>
            </div>
            <div class="modal-body">
                <div class="table-responsive parent-scroll">
                    <table class="fixTable table" style="margin-bottom:0px; margin-top:8px;" id="excelTable">
                        <thead>
                        <tr>
                            <th class="th-modal">LabourName</th>
                            <th class="th-modal">InernalGroup</th>
                            <th class="th-modal">VendorName</th>
                            <th class="th-modal">LabourType</th>
                            <th class="th-modal">IDNo</th>
                            <th class="th-modal">Address</th>
                            <th class="th-modal">City</th>
                            <th class="th-modal">PinCode</th>
                            <th class="th-modal">Mobile</th>
                            <th class="th-modal">Email</th>
                            <th class="th-modal">PFNo</th>
                            <th class="th-modal">AadhaarNo</th>
                            <th class="th-modal">ESINo</th>
                            <th class="th-modal">&nbsp;</th>
                        </tr>
                        </thead>
                        <tbody >
                        <tr>
                            <td style="width:15%"><input type="text" class="parent_text"  name="excellabourname_1" id="excellabourname_1"></td>
                            <td style="width:10%"><input type="text" class="parent_text"  name="excelgroupname_1" id="excelgroupname_1"></td>
                            <td style="width:8%"><input type="text" class="parent_text"  name="excellabourtype_1" id="excellabourtype_1"></td>
                            <td style="width:8%"><input type="text" class="parent_text"  name="excelidno_1" id="excelidno_1"></td>
                            <td style="width:8%"><input type="text" class="parent_text"  name="exceladdress_1" id="exceladdress_1"></td>
                            <td style="width:8%"><input type="text" class="parent_text"  name="excelcity_1" id="excelcity_1"></td>
                            <td style="width:8%"><input type="text" class="parent_text"  name="excelpincode_1" id="excelpincode_1"></td>
                            <td style="width:8%"><input type="text" class="parent_text"  name="excelmobile_1" id="excelmobile_1"></td>
                            <td style="width:8%"><input type="text" class="parent_text"  name="excelemail_1" id="excelemail_1"></td>
                            <td style="width:8%"><input type="text" class="parent_text"  name="excelpfno_1" id="excelpfno_1"></td>
                            <td style="width:8%"><input type="text" class="parent_text"  name="exceladharno_1" id="exceladharno_1"></td>
                            <td style="width:8%"><input type="text" class="parent_text"  name="excelesino_1" id="excelesino_1"></td>
                            <td width="2%" align="center">
                                <ul class="action_btns">
                                    <li>
                                        <a href="javascript:void(0);" class="excelTrDelete"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete" ></i></a>
                                    </li>
                                </ul> </td>
                            <input type="hidden" name="excelstatename_1" id="excelstatename_1" >
                            <input type="hidden" name="excelcountryname_1" id="excelcountryname_1" >
                            <input type="hidden" name="excelcityid_1" id="excelcityid_1" >
                            <input type="hidden" name="excelgroupid_1" id="excelgroupid_1" >
                            <input type="hidden" name="excelvendorid_1" id="excelvendorid_1" >
                            <input type="hidden" name="excellabourtypeid_1" id="excellabourtypeid_1" >
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="modal-footer"> <a href="javascript:void(0);" class="md_cance" data-dismiss="modal"  data-toggle="tooltip"  title="" data-original-title="Cancel" style="position: relative; overflow: hidden;">Cancel<span class="ripple-wrapper"></span><span class="ripple-wrapper"></span></a>
                <button type="button" class="md_ok" onclick="return excellabourUpdate()" >Apply</button>
            </div>
        </div>
    </div>
</div>
<script src="http://maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places&amp;key=AIzaSyDaNPyxJ7NKmZ4rC8awB-BlBh6ieH1Q9os"></script>
<script>
    var CostCentreList = <?php echo (isset($inarr_costcenter)) ? json_encode($inarr_costcenter) : '[]'; ?>;
    var groupMaster = <?php echo (isset($groupMaster)) ? json_encode($groupMaster) : '[]'; ?>;
    var vendorMaster = <?php echo (isset($vendorMaster)) ? json_encode($vendorMaster) : '[]'; ?>;
    var typeMaster = <?php echo (isset($typeMaster)) ? json_encode($typeMaster) : '[]'; ?>;
    var cityMaster = <?php echo (isset($cityMaster)) ? json_encode($cityMaster) : '[]'; ?>;
    var docType    = <?php echo (isset($doctype)) ? json_encode($doctype) : '[]'; ?>;
    var code =<?php echo (isset($code)) ? json_encode($code) : '[]'; ?>;
    var labourcode=<?php echo (isset($labourcode)) ? json_encode($labourcode) : '[]'; ?>;
    var templabourcode=[];
    $.each(labourcode,function(i,o){
        templabourcode.push(o.Code);
    });
    // code default palcing
    var resCode="";
    var iVNo = 0;
    var arrayList1 = $.map(groupMaster, function(obj) {
        return {
            value: obj.value,
            id: obj.id,
            type: obj.type,
            data: {
                category: 'Internal'
            }
        };
    });
    var arrayList2 = $.map(vendorMaster, function(obj) {
        return {
            value: obj.value,
            id: obj.id,
            type: obj.type,
            data: {
                category: 'Vendor'
            }
        };
    });
    var arrayList = arrayList1.concat(arrayList2);
    var $CostCentre = $('#CostCentre');

    var bExcelIDNo = false,
        bExcelLabourName = false,
        bExcelGroupName = false,
        bExcelVendorName = false,
        bExcelLabourTypeName = false,
        bExcelMobile = false,
        bExcelAddress = false,
        bExcelCity = false,
        bExcelEmail =false,
        bExcelPFNo =false,
        bExcelAdharNo =false,
        bExcelESINo =false,
        bExcelPinCode =false;


    var formData = new FormData();
    var arrayField =[];
    arrayField = [{ data :1, value: 'LabourName' },
        { data :2, value: 'InternalGroupName' },
        { data :3, value: 'VendorName' },
        { data :4, value: 'LabourType' },
        { data :5, value: 'IDNo' },
        { data :6, value: 'Address' },
        { data :7, value: 'City' },
        { data :8, value: 'PinCode' },
        { data :9, value: 'Mobile' },
        { data :10, value: 'EMail' },
        { data :11, value: 'PFNo' },
        { data :12, value: 'AadhaarNo' },
        { data :13, value: 'ESINo' }
    ];

    var arrayFieldR = arrayField;

    $(function () {
        iVNo = 0;
        var sCCName = $('#CostCentre').val();
        $('.followupId').parents('.btn-group').find('.dropdown-toggle').html(sCCName+'<span class="caret"></span>');
        generateIDNo(1);
    });

    $('#upFile').on('change', function() {
        if ($(this).val() != '') {
            $('#upFormWrapper').submit();
        }
    });

    function showEntry() {
        var sCCName = $('#CostCentre').val(),
            iCCId = isNullCheck($('#CostCentreId').val(),'number');
        if (iCCId==0) return;
        $('.followupId').parents('.btn-group').find('.dropdown-toggle').html(sCCName+'<span class="caret"></span>');
        $('#divcc').hide();
        $('#divdetails').show();
    }

    $('.content_wrapper').on('click', '.mainTrName', function(e) {
        e.preventDefault();
        var id = this.id;
        var larr = id.split('_');
        if($('#labourName_'+larr[1]).val() !="")
        {
            $(this).closest("tr").next(".subTr").show();
            $(this).closest("tr").next(".subTr").find(".subDiv").slideDown("slow");
            $(this).find("i").addClass("tform");
        }
    });

    $('.content_wrapper').on('click', '.mainTr', function(e) {
        e.preventDefault();
        if (!$(this).closest("tr").next(".subTr").is(":visible")) {
            $(this).closest("tr").next(".subTr").show();
            $(this).closest("tr").next(".subTr").find(".subDiv").slideDown("slow");
            $(this).find("i").addClass("tform");
            closedetails($(this)[0].id)
        } else {
            $(this).closest("tr").next(".subTr").find(".subDiv").slideUp("slow");
            $(this).closest("tr").next(".subTr").slideUp("slow");
            $(this).find("i").removeClass("tform");
        }
    });

    $('.followupId').on('click',function(){
        var urlId = $(this).attr('data-index');
        $('#CostCentreId').val(urlId);
        var selText = $(this).text();
        $('#CostCentre').val(selText);
        $(this).parents('.btn-group').find('.dropdown-toggle').html(selText+'<span class="caret"></span>');
    });


    bindGroupAutocomplete(parseInt($('#rows').val()));
    bindTypeAutocomplete();
    bindDocAutocomplete();
    function addRow(x) {
        var $x = $(x),
            $tr = $x.closest('tr'),
            key = $x[0].id.split('_')[1];
        var index=parseInt(key)+1;

//        if ($tr.next('tr').length != 0) return;

        if ($tr.next('tr:not(.subTr)').length != 0)
            return;

        if ($('#labourName_' + key).val().length == 0 && ($('#groupId_' + key).val().length == 0 || $('#vendorId_' + key).val().length == 0) && $('#typeId_' + key).val().length == 0)
            return;

        var iRowid = isNullCheck($('#rows').val(),'number');

        if ($('#labourName_' + iRowid).val().length == 0 || $('#typeId_' + iRowid).val() == 0) return;
        if ($('#groupName_' + iRowid).hasClass('error')) return;



        var $rowid = $('#rows'),
            count = parseInt($rowid.val()) + 1,
            template = $('#dummy-row tbody').html();

        template = template.replace(/__1/g, '_' + count);


        $tr.parent('tbody').append(template);
        $rowid.val(count);
//        var resCode = sPrefix+sTPrefix+sGPrefix+sSperator+sPre+iVNo+sSuffix;
        generateIDNo(count);
//        $('#idNo_'+index).val(resCode);
        // var iVNo=parseInt(iVNo) +1;
        //alert(iVNo);
        $('.rowDelete_' + key).show();
        $('#groupName_' + count).val($('#groupName_' + key).val());
        $('#groupId_' + count).val($('#groupId_' + key).val());
        $('#labourName_' + count).focus();
        $('#vendorId_' + count).val($('#vendorId_' + key).val());
        bindGroupAutocomplete(count);
        bindTypeAutocomplete();
        //bindCityAutocomplete()
    }

    function closedetails(name) {
        var $mainTRs = $("a[class*=mainTr]");
        $.each($mainTRs, function (i, obj) {
            var $this = $(this);
            if (name != $this[0].id) {
                if ($(this).closest("tr").next(".subTr").is(":visible")) {
                    $(this).closest("tr").next(".subTr").find(".subDiv").slideUp("slow");
                    $(this).closest("tr").next(".subTr").slideUp("slow");
                    $(this).find("i").removeClass("tform");
                }
            }
        });
    }

    function generateIDNo(key) {
        if (code.GenType == 1) {
            var sPrefix = code.Prefix,
                sSuffix  = code.Suffix,
                iWidth = code.Width,
                sSperator = code.Separator,
                sTPrefix = "",
                sGPrefix = "";

            if (iVNo < code.MaxNo)  iVNo = code.MaxNo + 1;
            else iVNo = iVNo+1;

            var iLen = iWidth - iVNo.toString().length;
            var sPre = "";
            for (i = 1; i < iLen; i++) {
                sPre = sPre+'0';
            }
            var resCode = sPrefix+sTPrefix+sGPrefix+sSperator+sPre+iVNo+sSuffix;
            //alert(resCode);
            $('#idNo_'+ key).attr('readonly',true);
            $('#idNo_'+ key).val(resCode);
        }
    }


    function insertNewRow() {
        var $rowid = $('#rows'),
            count = parseInt($rowid.val()) + 1,
            template = $('#dummy-row tbody').html();

        template = template.replace(/__1/g, '_' + count);
        $('#labourTable tbody#mainBody').append(template);
        $rowid.val(count);
        bindGroupAutocomplete(count);
        bindTypeAutocomplete();
        //bindCityAutocomplete()
    }

    function deleteRow(x, e) {
        e.preventDefault();
        if (!confirm('Do you want to Delete'))
            return false;

        var $tr = $(x).closest('tr'),
            $tbody = $tr.parent('tbody');

        if ($tbody.find('> tr').length == 1) {
            var template = $('#dummy-row tbody').html();
            template = template.replace(/__1/g, '_' + 1);
            $tbody.append(template);
            $('#rows').val(1);
        }

        $tr.next('.subTr').remove();
        $tr.remove();
        return false;
    }

    function bindGroupAutocomplete(rowVal) {
        $('#labourTable .groupSuggest').autocomplete({
            lookup: arrayList,
            groupBy: 'category',
            showNoSuggestionNotice: true,
            noSuggestionNotice: 'Do you want to Create New <input type="button" font-weight:bold" class="btn btn-link" value="Group" onclick="return AddNewGroup(' + rowVal + ')">',
            lookupFilter: function(suggestion, originalQuery, queryLowerCase) {
                if (queryLowerCase =='*') return suggestion.value;
                else {
                    var re = new RegExp($.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
                    return re.test(suggestion.value);
                }
            },
            onSelect: function(suggestion) {
                if (suggestion) {
                    var $this = $(this);
                    //$this.prop('readonly', true).addClass('border-none');
                    var rowid = $this[0].id.split('_')[1];
                    if (suggestion.type == 'G') {
                        $('#groupId_' + rowid).val(suggestion.id);
                    } else if (suggestion.type == 'V') {
                        $('#vendorId_' + rowid).val(suggestion.id);
                    }
                }
            },
            onSearchStart: function(suggestion) {
                var rowid = $(this)[0].id.split('_')[1];
                $('#groupId_' + rowid).val(0);
                $('#vendorId_' + rowid).val(0);
            },
            onSearchComplete: function(query, suggestions) {
                if (!suggestions.length) {
                    var rowid = $(this)[0].id.split('_')[1];
                    $('#groupId_' + rowid).val(0);
                    $('#vendorId_' + rowid).val(0);
                }
            }
        });
    }

    function bindTypeAutocomplete() {
        $('#labourTable .typeSuggest').autocomplete({
            lookup: typeMaster,
            lookupFilter: function(suggestion, originalQuery, queryLowerCase) {
                if (queryLowerCase == '*') {
                    return suggestion.value;
                } else {
                    var re = new RegExp($.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
                    return re.test(suggestion.value);
                }
            },
            onSelect: function(suggestion) {
                if (suggestion) {
                    var $this = $(this);
//                    $this.prop('readonly', true).addClass('border-none');
                    var rowid = $this[0].id.split('_')[1];
                    $('#typeId_' + rowid).val(suggestion.data);
                    $(this).removeClass('error');
                    addRow($this);
                }
            },
            onSearchStart: function(suggestion) {
                var rowid = $(this)[0].id.split('_')[1];
                $('#typeId_' + rowid).val('');
            },
            onSearchComplete: function(query, suggestions) {
                if (!suggestions.length) {
                    var rowid = $(this)[0].id.split('_')[1];
                    $('#typeId_' + rowid).val('');
                    $(this).addClass('error');
                } else  $(this).removeClass('error');
            }
        });
    }
    function bindDocAutocomplete() {
        $('.docmentauto').autocomplete({
            lookup: docType,
            lookupFilter: function(suggestion, originalQuery, queryLowerCase) {
                if (queryLowerCase == '*') {
                    return suggestion.value;
                } else {
                    var re = new RegExp($.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
                    return re.test(suggestion.value);
                }
            },
            onSelect: function(suggestion) {
                if (suggestion) {
                    var $this = $(this);

                    $this.prop('readonly', true).addClass('border-none');
                    var rowid = $this[0].id.split('_')[1];
                    var firstid=$this[0].id.split('_')[1];
                    var secondid=$this[0].id.split('_')[3];
                    $('#doctype_'+firstid+'_auto_'+secondid).val(suggestion.data);
                }
            },
            onSearchStart: function(suggestion) {

            },
            onSearchComplete: function(query, suggestions) {
                if (!suggestions.length) {
                    var rowid = $(this)[0].id.split('_')[1];
                    //$('#typeId_' + rowid).val('');
                }
            }
        });
    }


    var errorCheck = 0;

    function submitForm() {

        var errFlag = 0;
        var tRows = $('#rows').val();
        var tCnt = 0;
        var idArr = [];
        var idArrnew=templabourcode;
        var idFlag = 0;

        $('.error_message').hide();
        $('.red_bdr').removeClass('red_bdr');

        for (var i = 1; i <= tRows; i++) {
            if ($('#labourName_' + i).val() == '' && ($('#groupId_' + i).val() == '' || $('#vendorId_' + i).val() == '') && $('#typeId_' + i).val() == '') {
                tCnt = tCnt + 1;
            }

            if (i == 1) {
                if ($.trim($('#labourName_' + i).val()) == '') {
                    $('#labourName_' + i).addClass('red_bdr');
                    errFlag = 1;
                }
                if ($.trim($('#groupName_' + i).val()) == '') {
                    $('#groupName_' + i).addClass('red_bdr');
                    errFlag = 1;
                }
                if ($.trim($('#typeId_' + i).val()) == '') {
                    $('#typeName_' + i).addClass('red_bdr');
                    errFlag = 1;
                }
            } else {
                if ($.trim($('#labourName_' + i).val()) == '' && $.trim($('#groupName_' + i).val()) != '' && $.trim($('#typeId_' + i).val()) != '') {
                    $('#labourName_' + i).addClass('red_bdr');
                    errFlag = 1;
                }
                if ($.trim($('#labourName_' + i).val()) != '' && $.trim($('#groupName_' + i).val()) != '' && $.trim($('#typeId_' + i).val()) == '') {
                    $('#typeName_' + i).addClass('red_bdr');
                    errFlag = 1;
                }
            }

            if ($('#labourName_' + i).val() != '' && $('#groupName_' + i).val() != '' && $('#typeId_' + i).val() != '') {
                if ($.trim($('#labourName_' + i).val()) == '') {
                    $('#labourName_' + i).addClass('red_bdr');
                    errFlag = 1;
                }
                if ($.trim($('#idNo_' + i).val()) == '') {
                    $('#idNo_' + i).addClass('red_bdr');
                    errFlag = 1;
                }

            }

            if ($("#CostCentreId").val() == '' || $("#CostCentreId").val() == 0  ) {
                $("#CostCentre").addClass('red_bdr');
                errFlag = 1;
                return false;
            }

            if ($('#idNo_' + i).val() != '') {
                if (($.inArray($('#idNo_' + i).val(), idArr) != -1) && ($.inArray($('#idNo_' + i).val(), idArrnew) != -1) )  {
                    idFlag = 1;
                } else {
                    idArr.push($('#idNo_' + i).val());
                    idArrnew.push($('#idNo_' + i).val());
                }
            }

        }
        if (tRows == tCnt) {
            $(".selOne").html('<p>please enter the required fields</p>');
            $(".selOne").show();
            errFlag = 1;
            return false;
        }
        if (idFlag == 1) {
            $(".selOne").html('<p>Id No should not be same</p>');
            $(".selOne").show();
            errFlag = 1;
            return false;
        }
        if (errFlag == 0) {
            $('#formWrapper').submit();
        }
    }

    function AddNewGroup(rowVal) {
        $("#gpCurId").val(rowVal);
        $('#gpName').val($('#groupName_' + rowVal).val());
        $("#newGroupModal").modal('show');
    }

    function newGroupClose() {
        var rowVal = $("#gpCurId").val();
        $('#groupName_' + rowVal).val('');
        $("#gpCurId").val('');
        $('#newGroupModal').modal('toggle');
    }

    function newGroupAdd() {
        var rowVal = $("#gpCurId").val();
        $('#groupName_' + rowVal).val($("#gpName").val());
        arrayList.push({
            value: $("#gpName").val(),
            id: 0,
            type: 'G',
            data: {
                category: 'Internal'
            }
        });
        $('#groupName_' + rowVal).prop('readonly', true).addClass('border-none');
        $('#newGroupModal').modal('toggle');
        $('#typeName_' + rowVal).focus();
    }
    /* function checkcode(id) {

     var id = $(id)[0].id;
     var arr = id.split('_');
     var idno = $('#idNo_' + arr['1']).val();
     if ($('#groupId_' + arr['1']).val() != 0 || $('#vendorId_' + arr['1']).val() != 0) {

     if ($('#groupId_' + arr['1']).val() != 0) {
     var lgvType = 1;
     var chkId = $('#groupId_' + arr['1']).val();
     } else {
     var lgvType = 3;
     var chkId = $('#vendorId_' + arr['1']).val();
     }
     $.post(getBaseURL() + 'wpm/labourstrength/checklabourcode', {
     code: idno,
     id: chkId,
     lType: lgvType
     },
     function(data) {
     var chkCount = JSON.parse(data);
     if (chkCount.Count != 0) {
     $('#idNo_' + arr['1']).addClass('red_bdr');
     $('#idNo_' + arr['1']).attr('data-idajax', 'iderror');
     errorCheck = 1;
     } else if (chkCount.Count == 0) {
     $('#idNo_' + arr['1']).removeClass('red_bdr');
     $('#idNo_' + arr['1']).attr('data-idajax', '')
     }
     });

     }
     }*/
    // Cost Centre AutoComplte
    $(function() {
        // select2 initialize
        $(".single_dropdown2").select2({
            placeholder: "",
            minimumResultsForSearch: -1
        });
        $CostCentre.autocomplete({
            lookup: CostCentreList,
            showNoSuggestionNotice: false,
            lookupFilter: function(suggestion, originalQuery, queryLowerCase) {
                if (queryLowerCase == '*') {
                    return suggestion.value;
                } else {
                    var re = new RegExp($.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
                    return re.test(suggestion.value);
                }
            },
            onSelect: function(suggestion) {
                if (suggestion) {
                    $('#CostCentreId').val(suggestion.data);
                    $(this).removeClass('error');
                }
            },
            onSearchStart: function(suggestion) {

                $('#CostCentreId').val(0);
            },
            onSearchComplete: function(query, suggestions) {
                if (!suggestions.length) {
                    $(this).addClass('error');
                } else $(this).removeClass('error');

            }
        });
    });

    /*  function pfnumbercheck(id) {
     var id = $(id)[0].id;
     var arr = id.split('_');
     var idno = $('#pfNo_' + arr['1']).val();
     if (($('#groupId_' + arr['1']).val() != 0 || $('#vendorId_' + arr['1']).val() != 0) && idno != '') {

     if ($('#groupId_' + arr['1']).val() != 0) {
     var lgvType = 1;
     var chkId = $('#groupId_' + arr['1']).val();
     } else {
     var lgvType = 3;
     var chkId = $('#vendorId_' + arr['1']).val();
     }
     $.post(getBaseURL() + 'wpm/labourstrength/checklabourcodePf', {
     code: idno,
     id: chkId,
     lType: lgvType
     },
     function(data) {
     var chkCount = JSON.parse(data);
     if (chkCount.Count != 0) {
     $('#pfNo_' + arr['1']).addClass('red_bdr');
     $('#pfNo_' + arr['1']).attr('data-ajax', 'error')
     return false;
     } else if (chkCount.Count == 0) {
     $('#pfNo_' + arr['1']).removeClass('red_bdr');
     $('#pfNo_' + arr['1']).attr('data-ajax', '')
     }
     });

     }
     }*/

    /* function esnonumbercheck(id) {
     var id = $(id)[0].id;
     var arr = id.split('_');
     var idno = $('#esiNo_' + arr['1']).val();
     if (($('#groupId_' + arr['1']).val() != 0 || $('#vendorId_' + arr['1']).val() != 0) && idno != '') {
     $.post(getBaseURL() + 'wpm/labourstrength/checklabouresi', {
     code: idno,
     },
     function(data) {
     var chkCount = JSON.parse(data);
     if (chkCount.Count != 0) {
     $('#esiNo_' + arr['1']).addClass('red_bdr');
     $('#esiNo_' + arr['1']).attr('data-esnoajax', 'esnoerror')
     return false;
     } else if (chkCount.Count == 0) {
     $('#esiNo_' + arr['1']).removeClass('red_bdr');
     $('#esiNo_' + arr['1']).attr('data-esnoajax', '')
     }
     });

     }
     }*/

    function Imagebrowse(id) {
        var id = $(id)[0].id;
        var arr = id.split('_');
        $("#my_file_" + arr['1']).click();
        $('#my_file_' + arr['1']).change(function() {
            readURL(this, arr['1']);
        });
    }

    function readURL(input, value) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            var id = value;
            reader.onload = function(e) {
                $("#showpic_" + id).hide();
                $("#blah_" + id).show();
                $('#blah_' + id).attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
    function addNewTenderDocRow(x) {
        var $x = $(x),
            $tr = $(x).closest('tr'),
            key1 = $x[0].id.split('_')[1];
        key2 = $x[0].id.split('_')[3];

        if ($tr.next('tr').length != 0)
            return;

        var $rowid = $('#tenderdocumentrowid_'+key1),
            rowid = parseInt($rowid.val());
        $('.deleteTenderDoc_' + rowid).show();

        var count = parseInt($rowid.val()) + 1,
            template = $('#dummy-tenderdoctype tbody').html();



        template = template.replace(/__1/g, '_' + key1);
        template = template.replace(/__9/g, '_' + count);
        var $tr = $(x).closest('tr'),
            $tbody = $tr.parent('tbody');
        $tbody.append(template);
        var $rowidfinal = $('#tenderdocumentrowid_'+key1).val();
        bindDocAutocomplete();
        bindDocAttached();
        $rowid.val(count);
    }
    function addNewTenderDocRowupdate(x) {

        var $x = $(x),
            $tr = $(x).closest('tr'),
            key1 = $x[0].id.split('_')[1];
        key2 = $x[0].id.split('_')[3];


        if ($tr.next('tr').length != 0)
            return;

        var $rowid = $('#tenderdocumentrowid_'+key1),
            rowid = parseInt($rowid.val());
        $('.deleteTenderDoc_' + rowid).show();

        var count = parseInt($rowid.val()) + 1,
            template = $('#dummy-tenderdoctype tbody').html();



        template = template.replace(/__1/g, '_' + key1);
        template = template.replace(/__9/g, '_' + count);
        var $tr = $(x).closest('tr'),
            $tbody = $tr.parent('tbody');
        $tbody.append(template);
        var $rowidfinal = $('#tenderdocumentrowid_'+key1).val();
        var $rowidfinal = $('#tenderdocumentrowid_'+key1).val();
        bindDocAutocomplete();
        bindDocAttached();
        $rowid.val(count);
    }
    function bindDocAttached() {
        var tenderDocFiles = $('input[id^=tenderDocFile_]');
        tenderDocFiles.unbind('change');

        tenderDocFiles.on('change', function() {
            var $this = $(this);
            var $tarEl = $(this).siblings('i');
            var $tooltip = $tarEl.parent('span');
            var $tarA = $tarEl.closest('a');
            if($(this).val() != '') {
                $tarA.addClass('pull-left');
                $tarEl.removeClass('fa-paperclip').addClass('fa-file-o file-do');
                $tooltip.attr('data-original-title', 'Document Attached');

                if($tarA.next('i.brkn').length == 0)
                    $('<i class="fa fa-chain-broken brkn" onclick="removeAttachment($(this));"></i>').insertAfter($tarA);

            } else {
                $tarA.next('i.brkn').remove();
                $tarEl.addClass('fa-paperclip').removeClass('fa-file-o file-do');
                $tooltip.attr('data-original-title', 'Click to attach documents');
            }
        });
        bindDocAutocomplete();
    }

    function removeAttachment($tarEl) {

        if (!confirm('Do you want to Remove')) {
            return false;
        }

        var $tarLi = $tarEl.closest('li');
        var $tarA = $tarLi.find('a');
        var $tarI = $tarA.find('i.fa-file-o');
        var $tarIp = $tarLi.find('input[type="hidden"]');

        $tarIp.attr('type', 'file').removeAttr('value');
        //        $tarA.attr('href', '#').removeAttr('download').removeAttr('target');
        $tarI.addClass('fa-paperclip').removeClass('fa-file-o file-do');
        $tarA.html('<span class="btn-file butclr_imp">' + $tarA.html() + '</span>');
        bindDocAttached();
        bindDocAutocomplete();
        $tarEl.remove();
    }

    function deleteTenderDoc(x,e) {
        e.preventDefault();
        if (!confirm('Do you want to Delete'))
            return false;

        var $tr = $(x).closest('tr'),
            $tbody = $tr.parent('tbody');

        if ($tbody.find('> tr').length == 1) {
            var template = $('#dummy-tenderdoctype tbody').html();
            template = template.replace(/__1/g, '_' + 1);
            $tbody.append(template);
            $('#tenderdocumentrowiddelete').val(1);

//            bindExpandTr();
        }

        $tr.next('tr.subTr').remove();
        $tr.remove();

        $('input[id^=DocType_]').trigger('blur');
        return false;
    }
    function locationpicker(id)
    {
        console.log($(id)[0].id);
        var id = $(id)[0].id;
        var arr = id.split('_');
        var $addressnew=$('#address_'+arr[1]);
        /*Mapping Address*/
        navigator.geolocation.getCurrentPosition(showPosition);
        $addressnew.geocomplete({
            details: "#formWrapper",
            types: ["geocode", "establishment"]
        });
    }
    function showPosition(position) {
        var coordinates = position.coords.latitude + "," + position.coords.longitude;
        $addressnew.val(coordinates);
    }
    function getexcelfield(x) {
        var bValid=true;

        bExcelIDNo = false;
        bExcelLabourName = false;
        bExcelGroupName = false;
        bExcelVendorName = false;
        bExcelLabourTypeName = false;
        bExcelMobile = false;
        bExcelAddress = false;
        bExcelCity = false;
        bExcelEmail =false;
        bExcelPFNo =false;
        bExcelAdharNo =false;
        bExcelESINo =false;
        bExcelPinCode =false;

        formData = new FormData();
        formData.append('file', $('#myfile').prop("files")[0]);
        $.ajax({
            url: getBaseURL() +"wpm/labourstrength/getlabourfielddata",
            async: false,
            dataType: 'script',
            cache: false,
            contentType: false,
            processData: false,
            data: formData,
            type: 'post',
            success: function(data,status, xhr) {
                var obj = jQuery.parseJSON(data);

                $("#excelfieldTable").find("th").remove();
                $("#excelfieldTable").find("td").remove();
//            $("#excelfield").find("td").remove();

                var sStr="Select Field";
                for (var i = 0; i < obj.length; i++) {
                    $("#excelfieldTable").append('<tr><th width="20%"><input id="efield_'+i+'" class="text-reon text-right" type="text" value="'+obj[i]['Field']+'" style="background: transparent;"/></th> <td width="70%"><input id="field_'+i+'" class="parent_text" type="text"'+sStr+' onfocus="checkexcelFieldFocus(this.id)"</td></tr>');
//                $("#excelfield").append('<td><input id="field_'+i+'" class="parent_text" type="text"'+sStr+' onfocus="checkexcelFieldFocus(this.id)"</td>');
                    $('#efield_'+i).prop('readonly', true);

                    if (obj[i]['Field'].trim().toUpperCase() == 'LABOURNAME') { $('#field_'+i).val('LabourName'); bExcelLabourName=true; }
                    if (obj[i]['Field'].trim().toUpperCase() == 'INTERNALGROUPNAME') { $('#field_'+i).val('InternalGroupName'); bExcelGroupName=true;}
                    if (obj[i]['Field'].trim().toUpperCase() == 'VENDORNAME') { $('#field_'+i).val('VendorName'); bExcelVendorName=true;}
                    if (obj[i]['Field'].trim().toUpperCase() == 'IDNO') { $('#field_'+i).val('IDNo'); bExcelIDNo=true;}
                    if (obj[i]['Field'].trim().toUpperCase() == 'ADDRESS') { $('#field_'+i).val('Address'); bExcelAddress=true;}
                    if (obj[i]['Field'].trim().toUpperCase() == 'CITY') { $('#field_'+i).val('City'); bExcelCity=true;}
                    if (obj[i]['Field'].trim().toUpperCase() == 'PINCODE') { $('#field_'+i).val('PinCode'); bExcelPinCode=true;}
                    if (obj[i]['Field'].trim().toUpperCase() == 'MOBILE') { $('#field_'+i).val('Mobile'); bExcelMobile=true;}
                    if (obj[i]['Field'].trim().toUpperCase() == 'EMAIL') { $('#field_'+i).val('EMail'); bExcelEmail=true;}
                    if (obj[i]['Field'].trim().toUpperCase() == 'PFNO') { $('#field_'+i).val('PFNo'); bExcelPFNo=true;}
                    if (obj[i]['Field'].trim().toUpperCase() == 'AADHAARNO') { $('#field_'+i).val('AadhaarNo'); bExcelAdharNo=true;}
                    if (obj[i]['Field'].trim().toUpperCase() == 'ESINO') { $('#field_'+i).val('ESINo'); bExcelESINo=true;}
                }

                bindexcelFieldComplete();
                $("#excelfieldmodal").modal('show');
            },
            error: function(xhr, status, errorThrown) {
                if (xhr.status == 400)
                    alert(xhr.responseText);
                else
                    alert(errorThrown);
            }
        });
        clearInputFile($('#myfile'));
    }
    function bindexcelFieldComplete() {
        var $excelfield = $('input[id^=field_]');
        $excelfield.unbind('autocomplete');
        $.each($excelfield, function () {
            var $this = $(this),
                name = $this[0].id;
            if (name.indexOf('__') != -1 || name.indexOf('excel') != -1) return;
            var arrname = name.split('_');
            var key1 = arrname[1];
            checkexcelFieldUsed(key1);
            $this.autocomplete({
                lookup: arrayFieldR,
                lookupFilter: function (suggestion, originalQuery, queryLowerCase) {
                    if (queryLowerCase == '*') {
                        return suggestion.value;
                    } else {
                        var re = new RegExp($.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
                        return re.test(suggestion.value);
                    }
                }, onSelect: function(suggestion) {
                    if(suggestion) removeError($(this));
                }, onSearchStart: function(suggestion) {
                    //$("#materialAdvId_" + key1).val(0);
                }, onSearchComplete: function (query, suggestions) {
                    if(!suggestions.length) showError($(this), 'Invalid');
                    else removeError($(this));
                }
            });
        });
    }

    function bindexcelFieldRowComplete(x) {
        $('#'+ x).autocomplete({
            lookup: arrayFieldR,
            lookupFilter: function (suggestion, originalQuery, queryLowerCase) {
                if (queryLowerCase == '*') {
                    return suggestion.value;
                } else {
                    var re = new RegExp($.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
                    return re.test(suggestion.value);
                }
            }, onSelect: function(suggestion) {
                if(suggestion) removeError($(this));
            }, onSearchStart: function(suggestion) {
                //$("#materialAdvId_" + key1).val(0);
            }, onSearchComplete: function (query, suggestions) {
                if(!suggestions.length) showError($(this), 'Invalid');
                else removeError($(this));
            }
        });
    }


    function clearInputFile(file){
        var f = file[0];
        if(f.value){
            try{
                f.value = '';
            }catch(err){ }
            if(f.value){
                var form = document.createElement('form'),
                    parentNode = f.parentNode, ref = f.nextSibling;
                form.appendChild(f);
                form.reset();
                parentNode.insertBefore(f,ref);
            }
        }
    }
    function checkexcelFieldFocus(x) {
        var arrname = x.split('_');
        var key1 = arrname[1];
        checkexcelFieldUsed(key1);
        bindexcelFieldRowComplete(x);

    }
    function checkexcelFieldUsed(id) {
        var reskeyid = $('input[id*=field_]');
        arrayFieldR = arrayField;
        arrayFieldR= $.grep(arrayField, function (element, index) {
            var is_selected = true;
            $.each(reskeyid, function (i, obj) {
                var $this = $(this),
                    name = $this[0].id;
                var arrname = name.split('_');
                var key1 = arrname[1];
                if (key1 != id) {
                    if (element.value == $this.val()) {
                        is_selected = false;
                    }
                }
            });
            return is_selected;
        });
    }
    function fileupload() {
        var isValid=true;
        var $excelpids = $('input[id^=field_]');
        $.each($excelpids, function (i, obj) {
            var $this = $(this),
                name = $this[0].id;
            var key1 = name.split('_')[1];
            if ($('#field_' + key1).hasClass('error')) {
                isValid=false;
                return;
            }
        });
        if (isValid==false) {alert ("Please Assign Fields Correctly"); return;}

        $("#excelfieldmodal").modal('hide');
        var bValid=true;
        var arrHeader =[];
        for (var i = 0; i < $("#excelfieldTable").find("th").length; i++) {
            arrHeader.push({efield: $('#efield_'+i).val(), field: $('#field_'+i).val()});
        }
        arrHeader =  JSON.stringify(arrHeader);
        formData.append('arrHeader', arrHeader);
        formData.append('csrf', "<?php echo isset($csrf)?$csrf:''; ?>");
        $.ajax({
            url: getBaseURL() +"wpm/labourstrength/uploadlabourdata",
            async: false,
            dataType: 'script',
            cache: false,
            contentType: false,
            processData: false,
            data:  formData,
            type: 'post',
            success: function(data,status, xhr) {
                var obj = jQuery.parseJSON(data);
                var key1=1;
                if (obj[0].Valid==true) {
                    $('#excelTable tr:gt(1)').remove();
                    var $excelagtnos = $('input[id^=excellabourname_]');
                    $.each($excelagtnos, function (i, obj) {
                        var $this = $(this),
                            name = $this[0].id;
                        key1 = name.split('_')[1];
                    });
                    var irow = key1;

                    $("#excellabourname_"+irow).val('');
                    $("#excelgroupname_"+irow).val('');
                    $("#excellabourtype_"+irow).val('');
                    $("#excelidno_"+irow).val('');
                    $("#exceladdress_"+irow).val('');
                    $("#excelcity_"+irow).val('');
                    $("#excelpincode_"+irow).val('');
                    $("#excelmobile_"+irow).val('');
                    $("#excelemail_"+irow).val('');
                    $("#excelpfno_"+irow).val('');
                    $("#exceladharno_"+irow).val('');
                    $("#excelesino_"+irow).val('');
                    $("#excelstatename_"+irow).val('');
                    $("#excelcountryname_"+irow).val('');
                    $("#excelcityid_"+irow).val('');
                    $("#excelgroupid_"+irow).val('');
                    $("#excelvendorid_"+irow).val('');
                    $("#excellabourtypeid_"+irow).val('');

                    for (var i = 0; i < obj.length; i++) {
                        if (irow != key1)  {
                            $("#excelTable tbody tr:last").after('<tr>' + $("#excelTable tbody tr:first").html() + "</tr>");
                            var $tr = $("#excelTable tbody tr:last");
                            $tr.find("input").each(function () {
                                $(this).attr("id", $(this).attr("id").replace( "_" + key1, "_" + irow));
                            });
//                            $tr.find("select").each(function () {
//                                $(this).attr("id", $(this).attr("id").replace( "_" + key1, "_" + irow));
//                            });
//                            $tr.find("textarea").each(function () {
//                                $(this).attr("id", $(this).attr("id").replace( "_" + key1, "_" + irow));
//                            });
                        }

                        $("#excellabourname_"+irow).val(isNullCheck(obj[i].LabourName,'string'));
                        $("#excelgroupname_"+irow).val(isNullCheck(obj[i].GroupName,'string'));
                        $("#excellabourtype_"+irow).val(isNullCheck(obj[i].LabourType,'string'));
                        $("#excelidno_"+irow).val(isNullCheck(obj[i].IDNo,'string'));
                        $("#exceladdress_"+irow).val(isNullCheck(obj[i].Address,'string'));
                        $("#excelcity_"+irow).val(isNullCheck(obj[i].City,'string'));
                        $("#excelpincode_"+irow).val(isNullCheck(obj[i].Pincode,'string'));
                        $("#excelmobile_"+irow).val(isNullCheck(obj[i].Mobile,'string'));
                        $("#excelemail_"+irow).val(isNullCheck(obj[i].Email,'string'));
                        $("#excelpfno_"+irow).val(isNullCheck(obj[i].PFNo,'string'));
                        $("#exceladharno_"+irow).val(isNullCheck(obj[i].AdharNo,'string'));
                        $("#excelesino_"+irow).val(isNullCheck(obj[i].ESINo,'string'));

                        $("#excelstatename_"+irow).val(isNullCheck(obj[i].StateName,'string'));
                        $("#excelcountryname_"+irow).val(isNullCheck(obj[i].CountryName,'string'));
                        $("#excelcityid_"+irow).val(isNullCheck(obj[i].CityId,'number'));
                        $("#excelgroupid_"+irow).val(isNullCheck(obj[i].GroupId,'number'));
                        $("#excelvendorid_"+irow).val(isNullCheck(obj[i].VendorId,'number'));
                        $("#excellabourtypeid_"+irow).val(isNullCheck(obj[i].LabourTypeId,'number'));

                        //$(".th:contains('None')") .remove();
                        irow = +irow + 1;
                    }
                } else {
                    bValid=false;
                }
                bindExcelDeleteFn();
                if (bValid==true)
                    $("#excelmodal").modal('show');
                else
                    alert("Invalid File Format");
            },
            error: function(xhr, status, errorThrown) {
                if (xhr.status == 400)
                    alert(xhr.responseText);
                else
                    alert(errorThrown);
            }
        });

//    if (bExcelCode==false) $('.excel-code-txt').hide();
        clearInputFile($('#myfile'));
    }

    function bindExcelDeleteFn(reset) {
        var $trDelete = $('a[class*=excelTrDelete]');
        if (typeof reset !== 'undefined' && reset === true) $trDelete.unbind('click');
        $.each($trDelete, function (i, obj) {
            var $this = $(this),
                name = $this[0].className;
            $this.on('click', function(e) {
                e.preventDefault();
                if (confirm('Do you want to Delete')) {
                    var tr_length = $('#excelTable tr').length;
                    if (tr_length ==2) {
                        var $excelpids = $('input[id*=excellabourname_]');
                        $.each($excelpids, function (i, obj) {
                            var $this = $(this),
                                name = $this[0].id;
                            var key1 = name.split('_')[1];

                            $("#excellabourname_"+key1).val('');
                            $("#excelgroupname_"+key1).val('');
                            $("#excellabourtype_"+key1).val('');
                            $("#excelidno_"+key1).val('');
                            $("#exceladdress_"+key1).val('');
                            $("#excelcity_"+key1).val('');
                            $("#excelpincode_"+key1).val('');
                            $("#excelmobile_"+key1).val('');
                            $("#excelemail_"+key1).val('');
                            $("#excelpfno_"+key1).val('');
                            $("#exceladharno_"+key1).val('');
                            $("#excelesino_"+key1).val('');
                            $("#excelstatename_"+key1).val('');
                            $("#excelcountryname_"+key1).val('');
                            $("#excelcityid_"+key1).val('');
                            $("#excelgroupid_"+key1).val('');
                            $("#excelvendorid_"+key1).val('');
                            $("#excellabourtypeid_"+key1).val('');
                        });
                    } else {
                        $this.closest('tr').remove();
                    }
                }
                return false;
            });
        });
    }

    function excellabourUpdate() {

        $('.loading_area').show();
//        if (excelSheetValid()==false) {
//            $('.loading_area').hide();
//            alert("Invalid Sheet");
//            return;
//        }
        bExcelUpdate =true;
        var iMRowId = $('#rows').val();
        ioRowId = iMRowId;
        var $excelpids = $('input[id*=excellabourname_]');
        $.each($excelpids, function (i, obj) {
            var $this = $(this),
                name = $this[0].id,
                key1 = name.split('_')[1];
            ioRowId = iMRowId;
            if ($('#labourName_' + iMRowId).val() != "") { iMRowId = + iMRowId+1;}
            if (iMRowId !=1) {
                var sStr = $('#dummy-row tbody').html();
                sStr = sStr.replace(/__1/g, '_' + iMRowId);
                sStr = sStr.replace(/__9/g, '_1');
                if (ioRowId !=1) {ioRowId = (ioRowId*2)-1 ;}
                $('#labourTable > tbody > tr').eq(ioRowId).after(sStr);
            }
            $('#groupName_' + iMRowId).val($("#excelgroupname_"+key1).val());
            $('#labourName_' + iMRowId).val($("#excellabourname_"+key1).val());
            $('#typeName_' + iMRowId).val($("#excellabourtype_"+key1).val());
            $('#idNo_' + iMRowId).val($("#excelidno_"+key1).val());
            $('#address_' + iMRowId).val($("#exceladdress_"+key1).val());
            $('#city_' + iMRowId).val($("#excelcity_"+key1).val());

            $('#state_' + iMRowId).val($("#excelstatename_"+key1).val());
            $('#country_' + iMRowId).val($("#excelcountryname_"+key1).val());
            $('#groupId_' + iMRowId).val($("#excelgroupid_"+key1).val());
            $('#vendorId_' + iMRowId).val($("#excelvendorid_"+key1).val());
            $('#typeId_' + iMRowId).val($("#excellabourtypeid_"+key1).val());
            $('#cityId_' + iMRowId).val($("#excelcityid_"+key1).val());

            $('#pinCode_' + iMRowId).val($("#excelpincode_"+key1).val());
            $('#mobile_' + iMRowId).val($("#excelmobile_"+key1).val());
            $('#email_' + iMRowId).val($("#excelemail_"+key1).val());
            $('#pfNo_' + iMRowId).val($("#excelpfno_"+key1).val());
            $('#adharNo_' + iMRowId).val($("#exceladharno_"+key1).val());
            $('#esiNo_' + iMRowId).val($("#excelesino_"+key1).val());

        });

        $('#rows').val(iMRowId);
        if (iMRowId > 1) addRow($('#labourName_' + iMRowId));
        $('#excelmodal').modal('toggle');
        $('.loading_area').hide();
        bExcelUpdate =false;
        excelimportvalid();
    }
    function excelimportvalid() {
        var $excelpids = $('input[id^=labourName_]');
        $.each($excelpids, function (i, obj) {
            var $this = $(this),
                name = $this[0].id;
            var ikey = name.split('_')[1];
            var iGroupId = isNullCheck($('#groupId_' + ikey).val(),'number'),
                iVendorId= isNullCheck($('#vendorId_' + ikey).val(),'number'),
                iLabourTypeId  = isNullCheck($('#typeId_' + ikey).val(),'number');

            if ($('#groupName_' + ikey).val().length > 0) {
                if (iGroupId ==0 && iVendorId==0)  $('#groupName_' + ikey).addClass('error');
            }
            if ($('#typeName_' + ikey).val().length > 0) {
                if (iLabourTypeId == 0)  $('#typeName_' + ikey).addClass('error');
            }
        });
    }
</script>