<link href="/buildsuperfast_v0.1/public/css/ej.widgets.all.min.css" rel="stylesheet">
<link href="/buildsuperfast_v0.1/public/css/ej.theme.min.css" rel="stylesheet">
<link href="/buildsuperfast_v0.1/public/css/ej.widgets.core.min.css" rel="stylesheet">
<link href="/buildsuperfast_v0.1/public/css/font-awesome.css" rel="stylesheet">
<link href="/buildsuperfast_v0.1/public/css/font-awesome.min.css" rel="stylesheet">

<script src="/buildsuperfast_v0.1/public/js/jquery-1.10.2.min.js"></script>
<script src="/buildsuperfast_v0.1/public/js/jquery.globalize.min.js"></script>
<script src="/buildsuperfast_v0.1/public/js/jquery.easing-1.3.min.js"></script>
<script src="/buildsuperfast_v0.1/public/js/jsrender.min.js"></script>
<script src="/buildsuperfast_v0.1/public/js/ej.web.all.min.js"></script>
<script src="/buildsuperfast_v0.1/public/js/data.js"></script>

<!--<body style="overflow: hidden; position: static; margin: 0px; padding: 0px;">-->

<div id="gantt" style="position: absolute; height: 85%; width: 91%;"><a href="javascript:void(0);" id="overallUpdate">Save All</a></div>
<script type="text/javascript">
    //DATA SOURCE DECLARATION OF GANTT CONTROL
    var data = [
        <?php echo $strText;?>
    ];

    $(function () {
        $("#gantt").ejGantt({
            dataSource: data,
            allowColumnResize: true,
            allowSorting: true,
            allowSelection: true,
            enableResize:true,
            enableContextMenu:true,
            taskIdMapping: "TaskID",
            taskNameMapping: "TaskName",
            startDateMapping: "StartDate",
            progressMapping: "Progress",
            durationMapping: "Duration",
            endDateMapping: "EndDate",
            childMapping: "Children",  // "subtasks", //Children
            enableVirtualization: false,
            highlightWeekEnds: true,
            includeWeekend: false,

            <?php
              echo 'scheduleStartDate: "' .$stdate. '" ,';
              echo 'scheduleEndDate: "' .$eddate. '" ,';
            ?>
            //scheduleStartDate: "12/01/2014",
            //scheduleEndDate: "03/30/2015",

            //Resources mapping
            resourceInfoMapping: "resourceId",
            resourceNameMapping: "resourceName",
            resourceIdMapping: "resourceId",
            resources: projectResources,
            predecessorMapping: "Predecessor",

            //beginEdit:beginEdit,

            showResourceNames:true,
            toolbarSettings: {
                showToolbar: true,
                toolbarItems: [ej.Gantt.ToolbarItems.Add,
                    ej.Gantt.ToolbarItems.Edit,
                    ej.Gantt.ToolbarItems.Delete,
                    ej.Gantt.ToolbarItems.Update,
                    ej.Gantt.ToolbarItems.Cancel,
                    //ej.Gantt.ToolbarItems.Indent,
                    //ej.Gantt.ToolbarItems.Outdent,
                    ej.Gantt.ToolbarItems.ExpandAll,
                    ej.Gantt.ToolbarItems.CollapseAll,
                    ej.Gantt.ToolbarItems.Search]
            },

            editSettings: {
                allowEditing: true,
                allowAdding: true,
                allowDeleting: true,
                editMode: "cellEditing"
            },
            showGridCellTooltip: true,
            treeColumnIndex:1,
            //Adding column in Gantt
            load: function () {
                var columns = this.getColumns();
                columns.splice(9, 0,
                    {
                        field: "parent",
                        headerText: "parent",
                        width: "60px",
                        visible: false
                    });
            }
            //End Adding column in Gantt
        });
    });

    //Non Edit taskname Column
    //function beginEdit(args) {
    //    if (this.getColumns()[args.columnIndex].field === "parent") {
    //      args.cancel = true;
    //  }
    // }

</script>
<!--</body>-->