<div class="content_wrapper  padlr0">
    <div class="container-fluid ">
        <div class="row">
            <div class="col-lg-12 ">
				<form class="form-horizontal" enctype="multipart/form-data" method="post">
					<input type="hidden" name="rfqId" id="rfqId" value="<?php echo $resultsVen['RFQId']; ?>">
					<input type="hidden" name="regId" id="regId" value="<?php echo $regId; ?>">
					<div class="col-lg-12 heading_vendorfrom ">
						<h1 class="text-center vendorrequest_textnormal">Responsed From Vendor-<?php echo $resultsVen['RFQNo']; ?></h1>	
					</div>
					<div class="col-lg-12 fullbackground_white  clear">
						<div class="col-lg-12 commargin_top commargin_bottom clear">
							<div class="col-lg-6">
								<h1 class="vendorrequest_text ">Please Enter Your Bid Below</h1>
							</div>
							<div class="col-lg-2 col-lg-offset-4">
								<div class="vendor_button"> 
									<input type="hidden" name="VendorId" id="VendorId" value="<?php echo $resultsVen['VendorId']; ?>">
									<select name="VendorIdSelect" id="VendorIdSelect" disabled>
										<option value="0">Select Vendor</option>
										<?php foreach($rfqVendorResult as $rs){ ?>
												<option <?php echo (($resultsVen['VendorId'] == $rs['VendorId'])?'selected':''); ?> value="<?php echo $rs['VendorId']; ?>"><?php echo $rs['VendorName']; ?></option>
										<?php } ?>
									</select>
								</div>
							</div>
						</div>         
						<div class="col-lg-10 col-lg-offset-1 clear">
							<div class="table-responsive clear">
							<input type="hidden" name="hidResTrans" id="hidResTrans" value='<?php echo json_encode(array_column($resResult, 'ResourceId')); ?>'>								
								<table class="table table-hover clear" id="resourceTable">
									<thead>
										<tr>
											<th>Resource Code</th>
											<th>Description</th>
											<th>Unit</th>
											<th>Rate</th>
											<th>Quantity</th>
										</tr>
									</thead>
									<tbody>
										<?php foreach($resResult as $res){?>
										<tr>
											<td class="gray_bckgrd gray_bckgrdbold"><?php echo $res['Code']; ?></td>
											<td class="gray_bckgrd"><?php echo $res['ResourceName']; ?></td>
											<td class="gray_bckgrd"><?php echo $res['UnitName']; ?></td>
											<td class="tbl_input_td gray_bckgrd">
												<input class="parent_txts tbl_input" name="rate_<?php echo $res['ResourceId']; ?>" value="<?php echo $res['Rate']; ?>" placeholder="" type="text" onblur="return FormatNum(this, 2)" onkeypress="return isDecimal(event,this);" />
												<input class="parent_txts tbl_input" name="quantity_<?php echo $res['ResourceId']; ?>" value="<?php echo $res['Quantity']; ?>" placeholder="" type="hidden" />
											</td>
											<td class="gray_bckgrd"><?php echo $res['Quantity']; ?></td>
										</tr>											
										<?php } ?>									
									</tbody>
								</table>
							</div>
						</div>
						<div class="col-lg-12 clear">
							<h1 class="vendorrequest_text commargin_bottom">Terms and conditions</h1>
							<div class="col-lg-10 col-lg-offset-1 clear">
								<div class="table-responsive clear">
									<input type="hidden" name="hidTerms" id="hidTerms" value='<?php echo json_encode(array_column($resultsFillTermdet, 'TermsId')); ?>'>
									<table class="table table-hover clear" id="table">
										 <tbody>
											<?php foreach($resultsFillTermdet as $term){ ?>
											  <tr>
												<td class="gray_bckgrd gray_bckgrdbold" width="11%" >
													<?php echo $term['Terms']; ?>
													<input class="parent_txts tbl_input" name="valueFromNet_<?php echo $term['TermsId']; ?>" type="hidden"  value="0" />
												</td>
												<td class="gray_bckgrd tbl_input_td" width="11%">
													<input class="parent_txts tbl_input" name="percentage_<?php echo $term['TermsId']; ?>" placeholder="Percentage" <?php echo (($term['IsPer']== 0)?"readonly":""); ?> type="text"  value="<?php echo $term['Per']; ?>" onblur="return FormatNum(this, 2)" onkeypress="return isDecimal(event,this);" />
												</td>
												<td class="gray_bckgrd tbl_input_td" width="11%"><input class="parent_txts tbl_input" name="value_<?php echo $term['TermsId']; ?>" placeholder="Value" <?php echo (($term['IsValue']== 0)?"readonly":""); ?> type="text" value="<?php echo $term['Value']; ?>" onblur="return FormatNum(this, 2)" onkeypress="return isDecimal(event,this);" /></td>
												<td class="gray_bckgrd tbl_input_td" width="11%"><input class="parent_txts tbl_input" name="period_<?php echo $term['TermsId']; ?>" placeholder="Period" <?php echo (($term['IsPeriod']== 0)?"readonly":""); ?>  type="text" value="<?php echo $term['Period']; ?>" onkeypress="return isDecimal(event,this);" /></td>
											  </tr>
											<?php } ?> 
										 </tbody>
									</table>
								</div>
							</div>
						</div>
						<div class="col-lg-12 commargin_bottom clear"><h1 class=" text-center padbtm0">Please enter addition information about bid</h1></div>
						<div class="col-lg-12 commargin_bottom commargin_top clear">
						  <h1 class="vendorrequest_text">Bid Comments</h1>
						  <div class="col-lg-6 col-lg-offset-3">
								<div class="row">
									<textarea id="bidComments" name="bidComments" class="form-control lbl_move" label="Comments about the Bid.."/><?php echo $resultsVen['BidComments']; ?></textarea>
								</div> 
						  </div>
						</div>
						<div class="col-lg-12 commargin_bottom commargin_top clear">
							<h1 class="vendorrequest_text">Requested Submittals</h1>
							<div class="col-lg-6 col-lg-offset-3">								  
								<input type="hidden" name="hidSubmittal" id="hidSubmittal" value='<?php echo json_encode(array_column($rfqSubmittalResult, 'TransId')); ?>'>
								<?php foreach($rfqSubmittalResult as $submittal){?>
									<div class="col-lg-12 commargin_bottom clear">
										<div class="form-group req_flds">
											<label class="col-lg-6 fontsize_label"><?php echo $submittal['SubmittalName']; ?><span class="colon_r">:</span></label>
											<input type="hidden" name="submittalName_<?php echo $submittal['TransId']; ?>" value="<?php echo $submittal['SubmittalName']; ?>">
											<input type="hidden" name="submittalPath_<?php echo $submittal['TransId']; ?>" value="<?php echo $submittal['SubmittalDocPath']; ?>">
											<div class="col-lg-6">
												<div class="row">
													<div class="form-group col-lg-12">
														<div class="upload_file">
															<input id="fileupload"  class="hide_file_input fileload"  name="files_<?php echo $submittal['TransId']; ?>" value="<?php if($submittal){ echo $rfqSubmittalResult['SubmittalDocPath'];} ?>" type="file" onchange="getExcelField(this.value,this);">
															<div class="upload_file_div">
																<?php $path=$submittal['SubmittalDocPath'];
																$path1=basename($path);?>
																<input type="text" class="upload_file_input uploadedFile" value="<?php if($submittal){ echo $path1;} ?>"  name="uploadedFile" label="Select File" />
																<div class="upload_file_text"><span data-toggle="tooltip" data-position="top" data-original-title="Upload"><i class="fa fa-upload"></i></span></div>
															</div>
														</div>
													</div>
												</div>
											</div>
											<!--<div class="col-lg-6">
												<span class=" parent_txts vendor_requestupload btn-file"> 
													<i class="fa fa-folder-open"></i> 
													Upload your document
													<input type="file" name="files_<?php //echo $submittal['TransId']; ?>" style="font-size:unset !important;">
												</span>
											</div>-->
										</div>
									</div>
								<?php } ?>							
							</div>
						</div>
						<div class="col-lg-12 commargin_bottom commargin_top clear">							 
							<h1 class="vendorrequest_text commargin_bottom">Bid Additional Documents</h1>
							<div class="col-lg-6 col-lg-offset-3">
								<div class="col-lg-12 clear">
									<div class="form-group req_flds col-lg-12">
										<input type="text" class="form-control lbl_move" label="Document Name or purpose" name="addDocumentName" id="addDocumentName" value="<?php echo $resultsVen['AddDocumentName']; ?>">
									</div>
								</div>
								<div class="col-lg-12 commargin_bottom clear">
									<div class="form-group req_flds">
										<label class="col-lg-6 fontsize_label">Bid Additional Documents<span class="colon_r">:</span></label>
										<input type="hidden" name="addDocumentPath" value="<?php echo $resultsVen['AddDocumentPath']; ?>">
										<div class="col-lg-6">
											<div class="row">
												<div class="form-group col-lg-12">
													<div class="upload_file">
														<input id="upload" name="additional_files"  class="hide_file_input fileload"  type="file" value="<?php if($resultsVen){ echo $resultsVen['AddDocumentPath'];} ?>" onchange="getExcelField(this.value,this);">
														<div class="upload_file_div">
															<?php $path=$resultsVen['AddDocumentPath'];
															$path1=basename($path);?>
															<input type="text" class="upload_file_input uploadedFile" name="uploadedFile" value="<?php if($resultsVen){ echo $path1;} ?>" label="Select File" />
															<div class="upload_file_text"><span data-toggle="tooltip" data-position="top" data-original-title="Upload"><i class="fa fa-upload"></i></span></div>
														</div>
													</div>
												</div>
											</div>
										</div>
										<!--<div class="col-lg-6">
											<span class=" parent_txts vendor_requestupload btn-file"> 
												<i class="fa fa-folder-open"></i> 
												Upload your document
												<input type="file" name="additional_files" style="font-size:unset !important;">
											</span>
										</div>-->
									</div>
								</div>
							</div>					  					  					  
						</div>						
					</div>         					
				</form>
				<div class="col-lg-12 commargin_bottom commargin_top">
					<ul>
						<li class="dropdown save_btn float_r"> <a href="javascript:void(0);" class="ripple  continueButton">Continue</a> </li>
					</ul>
				</div>
			</div> 
        </div>
    </div>
</div>
<script>
$(document).ready(function(){
	$('.continueButton').click(function(){
		var bool  = true;
		$('#resourceTable input:text').each(function(){
			if($(this).val() <= 0){
				bool = false;
				$(this).focus();
				return false;
			}
		});
		
		if(bool){
			$('form').submit();
		}
		
	});
});
</script>
<script>
$(document).ready(function(){
	$('.continueButton').click(function(){
		var bool  = true;
		$('#resourceTable input:text').each(function(){
			if($(this).val() <= 0){
				bool = false;
				$(this).focus();
				return false;
			}
		});
		
		if(bool){
			$('form').submit();
		}
		
	});
});
function getExcelField(x,y){
	$(y).next('div').children('input').val(x);
}
</script>