<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/mms.css'; ?>" />
	
<style type="text/css">
	.mar_20{margin-top:20px!important;}
	.blubg{background : #B0C3EB !important;}
</style>

<div class="container-fluid">
	<div class="row">
		<div class="col-lg-12 mar_20">
			<h1 style="margin-left:10px;">Gate Pass Detail<span class="edit_symbl">_<?php echo $GateregId;?></span>&nbsp;&nbsp; </h1> 
		</div>
		<div class="col-lg-12">
			<div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0 clear padlr0">
				<div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 mnimumwidthres" id="ProjectName">
					<div class="cbpln cbpln-default bx-wte cbpln-status cbpln-status3">
						<div class="padding-none">
							<div class="row">
								<div class="col-xs-3">
									<i class="fa fa-bandcamp fa-5x cbpln-status-icon"></i>
								</div>
								<div class="col-xs-9 text-right">
									<div class="cbhuge comnelips fntwt600"><?php echo $ProjectName; ?></div>
									<div class="cbhuge comnelips">Project Name</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 mnimumwidthres" id="SupplierName">
					<div class="cbpln cbpln-default bx-wte cbpln-status cbpln-status4">
						<div class="padding-none">
							<div class="row">
								<div class="col-xs-3">
									<i class="fa fa-certificate fa-5x cbpln-status-icon"></i>
								</div>
								<div class="col-xs-9 text-right">
									<div class="cbhuge comnelips fntwt600"><?php echo $SupplierName; ?></div>
									<div class="cbhuge comnelips">Vendor Name</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 mnimumwidthres" id="TimeIn">
					<div class="cbpln cbpln-default  bx-wte cbpln-status cbpln-status1">
						<div class="padding-none">
							<div class="row">
								<div class="col-xs-3">
									<i class="fa fa-retweet fa-5x cbpln-status-icon"></i>
								</div>
								<div class="col-xs-9 text-right">
									<div class="cbhuge comnelips fntwt600"><?php echo $TimeIn; ?></div>
									<div class="cbhuge comnelips">Time In</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 mnimumwidthres" id="TimeOut" >
					<div class="cbpln cbpln-default  bx-wte cbpln-status cbpln-status1">
						<div class="padding-none">
							<div class="row">
								<div class="col-xs-3">
									<i class="fa fa-retweet fa-5x cbpln-status-icon"></i>
								</div>
								<div class="col-xs-9 text-right">
									<div class="cbhuge comnelips fntwt600"><?php echo $TimeOut; ?></div>
									<div class="cbhuge comnelips">Time Out</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 mnimumwidthres" id="GDate">
					<div class="cbpln cbpln-default  bx-wte cbpln-status cbpln-status1">
						<div class="padding-none">
							<div class="row">
								<div class="col-xs-3">
									<i class="fa fa-retweet fa-5x cbpln-status-icon"></i>
								</div>
								<div class="col-xs-9 text-right">
									<div class="cbhuge comnelips fntwt600"><?php echo $GDate; ?></div>
									<div class="cbhuge comnelips">Date</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 mnimumwidthres" id="GateName">
					<div class="cbpln cbpln-default  bx-wte cbpln-status cbpln-status2">
						<div class="padding-none">
							<div class="row">
								<div class="col-xs-3">
									<i class="fa fa-calendar fa-5x cbpln-status-icon"></i>
								</div>
								<div class="col-xs-9 text-right">
									<div class="cbhuge comnelips fntwt600"><?php echo $GateName; ?></div>
									<div class="cbhuge comnelips">Gate Name</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 mnimumwidthres " id="SecurityName">
					<div class="cbpln cbpln-default  bx-wte cbpln-status cbpln-status5">
						<div class="padding-none">
							<div class="row">
								<div class="col-xs-3">
									<i class="fa fa-registered fa-5x cbpln-status-icon"></i>
								</div>
								<div class="col-xs-9 text-right">
									<div class="cbhuge comnelips fntwt600"><?php echo $SecurityName; ?></div>
									<div class="cbhuge comnelips">Security Name</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 mnimumwidthres " id="VehicleType">
					<div class="cbpln cbpln-default  bx-wte cbpln-status cbpln-status6">
						<div class="padding-none">
							<div class="row">
								<div class="col-xs-3">
									<i class="fa fa-money fa-5x cbpln-status-icon"></i>
								</div>
								<div class="col-xs-9 text-right">
									<div class="cbhuge comnelips fntwt600"><?php echo $VehicleType; ?></div>
									<div class="cbhuge comnelips">Vehicle Type</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 mnimumwidthres " id="DriverName">
					<div class="cbpln cbpln-default bx-wte cbpln-status cbpln-status7">
						<div class="padding-none">
							<div class="row">
								<div class="col-xs-3">
									<i class="fa fa-cube fa-5x cbpln-status-icon"></i>
								</div>
								<div class="col-xs-9 text-right">
									<div class="cbhuge comnelips fntwt600"><?php echo $DriverName; ?></div>
									<div class="cbhuge comnelips">Driver Name</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 mnimumwidthres " id="Type">
					<div class="cbpln cbpln-default bx-wte cbpln-status cbpln-status8">
						<div class="padding-none">
							<div class="row">
								<div class="col-xs-2">
									<i class="fa fa-share fa-5x cbpln-status-icon"></i>
								</div>
								<div class="col-xs-10 text-right">
									<div class="cbhuge comnelips fntwt600"><?php echo $Type; ?></div>
									<div class="cbhuge comnelips">Type</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 mnimumwidthres " id="VehicleRegNo">
					<div class="cbpln cbpln-default bx-wte cbpln-status cbpln-status3">
						<div class="padding-none">
							<div class="row">
								<div class="col-xs-2">
									<i class="fa fa-star-half-o fa-5x cbpln-status-icon"></i>
								</div>
								<div class="col-xs-10 text-right">
									<div class="cbhuge comnelips fntwt600"><?php echo $VehicleRegNo; ?></div>
									<div class="cbhuge comnelips">Vehicle Reg No</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 mnimumwidthres " id="CGateEntryNo">
					<div class="cbpln cbpln-default bx-wte cbpln-status cbpln-status4">
						<div class="padding-none">
							<div class="row">
								<div class="col-xs-2">
									<i class="fa fa-ticket fa-5x cbpln-status-icon"></i>
								</div>
								<div class="col-xs-10 text-right">
									<div class="cbhuge comnelips fntwt600"><?php echo $CGateEntryNo; ?></div>
									<div class="cbhuge comnelips">CGateEntry No</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 mnimumwidthres " id="CCGateEntryNo">
					<div class="cbpln cbpln-default bx-wte cbpln-status cbpln-status7">
						<div class="padding-none">
							<div class="row">
								<div class="col-xs-3">
									<i class="fa fa-cube fa-5x cbpln-status-icon"></i>
								</div>
								<div class="col-xs-9 text-right">
									<div class="cbhuge comnelips fntwt600"><?php echo $CCGateEntryNo; ?></div>
									<div class="cbhuge comnelips">CCGateEntry No</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 mnimumwidthres " id="GatePassNo">
					<div class="cbpln cbpln-default bx-wte cbpln-status cbpln-status8">
						<div class="padding-none">
							<div class="row">
								<div class="col-xs-2">
									<i class="fa fa-share fa-5x cbpln-status-icon"></i>
								</div>
								<div class="col-xs-10 text-right">
									<div class="cbhuge comnelips fntwt600"><?php echo $GatePassNo; ?></div>
									<div class="cbhuge comnelips">GatePassNo</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 mnimumwidthres " id="Approve">
					<div class="cbpln cbpln-default bx-wte cbpln-status cbpln-status3">
						<div class="padding-none">
							<div class="row">
								<div class="col-xs-2">
									<i class="fa fa-star-half-o fa-5x cbpln-status-icon"></i>
								</div>
								<div class="col-xs-10 text-right">
									<div class="cbhuge comnelips fntwt600"><?php echo $Approve; ?></div>
									<div class="cbhuge comnelips">Approve</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 mnimumwidthres " id="CGateEntryNo">
					<div class="cbpln cbpln-default bx-wte cbpln-status cbpln-status4">
						<div class="padding-none">
							<div class="row">
								<div class="col-xs-2">
									<i class="fa fa-ticket fa-5x cbpln-status-icon"></i>
								</div>
								<div class="col-xs-10 text-right">
									<div class="cbhuge comnelips fntwt600"><?php echo $CGateEntryNo; ?></div>
									<div class="cbhuge comnelips">CGateEntry No</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<!-------------------------------Detail------------------------------->
	<div class="col-lg-12">
		<div class="table-responsive top-30">
			<table class="table table-bordered" style=" margin-bottom:25px;" id="workorderTable">
				<thead>
				<tr>
					<th class="blubg">Code</th>
					<th class="blubg">Description</th>
					<th class="blubg">Unit</th>
					<th class="blubg">Required Date</th>
					<th class="blubg" style="text-align:center;">Qty</th>
				</tr>
				</thead>
				<tbody class="main"></tbody>
			</table>
			<input type="hidden" name="rowid" id="rowid" value="0"/>
		</div>
	</div>
	<!-------------------------------Detail------------------------------->
	<!-------------------------------Narration------------------------------->
	<div class="col-lg-12">
		<div id="nar">
			<div data-target="#collapseTwo" data-parent="#accordion" data-toggle="collapse" class="panel-heading collapsed panel_heads blubg" id="panelheading-2">
				<h4 class="panel-title accordion-toggle defa_panels">Narration</h4>
			</div>
			<div class="panel-collapse collapse" id="collapseTwo" style="height: 0px;">
				<div class="panel-body bgcolr">
					<div class="clearfix"></div>
					<div class="col-lg-12">
						<div class="card">
							<div class="tab-pane" id="Note">
								<p>
								<div class="col-lg-12">
									<textarea class="exp-tex" name="Notes" id="Notes" disabled > <?php echo (isset($Notes)) ? $Notes : '';?> </textarea>
								</div>
								</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-------------------------------Narration------------------------------->
</div>
<div class="col-lg-12 savebtn_area">
    <ul>
        <li class="dropdown save_btn float_r">
            <a href="<?php echo $this->basePath("/mms/master/gatepassregister");?>" class="ripple">Close</a>
        </li>
    </ul>
</div>
<script id="resource-template"  type="text/template" class="hide">
    <tr class="count-tr">
		
        <td class="mar_20 border-none" width="15%" name="code__" id="code__" ></td>
        <td width="25%" name="desc__" id="desc__" class="border-none">
            <input type="hidden" name="gatetransid__" id="gatetransid__" value=""/>
            <input type="hidden" name="resourceid__" id="resourceid__"/>
            <input type="hidden" name="itemid__" id="itemid__"/>
        </td>
        <td width="20%" name="unitname__" id="unitname__" class="border-none">
            <input type="hidden" name="unitid__" id="unitid__"/>
        </td>
        <td width="15%"  name="GDate__" id="rGDate__" class="border-none"></td>
        <td width="25%" name="qty__" id="qty__" class="border-none" style="text-align:center;">
            <input type="hidden" name="gateinqty__" id="gateinqty__"  />
        </td>
    </tr>
	<tr style="display:none;" class="subTr count-tr">
	</tr>
</script>
<script type="text/javascript">
var arr_requestResources = <?php echo (isset($arr_requestResources)) ? json_encode($arr_requestResources) : '[]';?>;
$(function () { 
    var $rowid = $('#rowid');
    var template = $('#resource-template').html();
    var iowtemplate = $('#iow-template').html();
    var rowid = 0;
    var $tbody = $('#workorderTable').find('> tbody.main');

		if(arr_requestResources.length != 0) {
			$.each(arr_requestResources, function(i, o) {
				rowid += 1;
				$tbody.append(template.replace(/__/g, '_' + rowid));

				$('#code_' + rowid).html(o.Code);
				$('#desc_' + rowid).html(o.ResourceName);
				$('#resourceid_' + rowid).val(o.ResourceId);
				$('#itemid_' + rowid).val(o.ItemId);
				$('#unitname_' + rowid).html(o.UnitName);
				$('#unitid_' + rowid).val(o.UnitId);
				$('#qty_' + rowid).html(o.Qty);
                $('#gateinqty_' + rowid).html(o.GateInQty);
                $('#gatetransid_' + rowid).val(o.GateTransId);
			});
		}
		rowid += 1;
		$rowid.val(rowid);
		nextAccordian();
	var Narration= <?php echo json_encode ($Notes) ;?>;
	if($.trim(Narration) == ''|| $.trim(Narration) == null) {
		$('#nar').hide();
	}
});

function nextAccordian(id) {
	$('#panelheading-2').trigger('click');
}
var ProjectName= <?php echo json_encode ($ProjectName);?>;
var SupplierName= <?php echo json_encode ($SupplierName);?>;
var TimeIn= <?php echo json_encode ($TimeIn);?>;
var TimeOut= <?php echo json_encode ($TimeOut);?>;
var GDate= <?php echo json_encode ($GDate);?>;
var GateName= <?php echo json_encode ($GateName);?>;
var SecurityName= <?php echo json_encode ($SecurityName);?>;
var VehicleType= <?php echo json_encode ($VehicleType);?>;
var DriverName= <?php echo json_encode ($DriverName);?>;
var Type= <?php echo json_encode ($Type);?>;
var VehicleRegNo= <?php echo json_encode ($VehicleRegNo);?>;
var CGateEntryNo= <?php echo json_encode ($CGateEntryNo);?>;
var CCGateEntryNo= <?php echo json_encode ($CCGateEntryNo);?>;
var GatePassNo= <?php echo json_encode ($GatePassNo);?>;
var Approve= <?php echo json_encode ($Approve);?>;
var CGateEntryNo= <?php echo json_encode ($CGateEntryNo);?>;
if(ProjectName == ''|| ProjectName == null) {
	$('#ProjectName').hide();
} 
if(SupplierName == ''|| SupplierName == null){
	$('#SupplierName').hide();
} 
if(TimeIn == ''|| TimeIn == null){
	$('#TimeIn').hide();
} 
if(TimeOut == ''|| TimeOut == null){
	$('#TimeOut').hide();
} 
if(GDate == ''|| GDate == null){
	$('#GDate').hide();
} 
if(GateName == ''|| GateName == null){
	$('#GateName').hide();
} 
if(SecurityName == ''|| SecurityName == null){
	$('#SecurityName').hide();
} 
if(VehicleType == ''|| VehicleType == null){
	$('#VehicleType').hide();
}
if(DriverName == ''|| DriverName == null){
	$('#DriverName').hide();
}
if(Type == ''|| Type == null){
	$('#Type').hide();
}
if(VehicleRegNo == ''|| VehicleRegNo == null){
	$('#VehicleRegNo').hide();
}
if(CGateEntryNo == ''|| CGateEntryNo == null){
	$('#CGateEntryNo').hide();
}
if(CCGateEntryNo == ''|| CCGateEntryNo == null){
	$('#CCGateEntryNo').hide();
}
if(GatePassNo == ''|| GatePassNo == null){
	$('#GatePassNo').hide();
}
if(Approve == ''|| Approve == null){
	$('#Approve').hide();
}
if(CGateEntryNo == ''|| CGateEntryNo == null){
	$('#CGateEntryNo').hide();
}

</script>