<?php
$url = $this->serverUrl(true);
$url = array_pop(explode("/", $url));
?>
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css'; ?>" />


<style type="text/css">
.prjt							{margin-bottom:30px;}
.tr_hot 						{background:#f9eaea;}
.tr_warm 						{background:#f8f1e4;}
.mar_15							{margin-top:15px;}
.pagination-lg > li > a, .pagination-lg > li > span {font-size:15px !important; padding:5px 15px !important;}
#jqxGrid .jqx-grid-header 		{height:75px !important;}
.jqx_margn						{margin-top:30px;margin-bottom:20px;}
.nx-btn a:hover                {border:1px solid #23bfee !important; background:#fff !important; color:#23bfee !important;}
.nx-btn a                      {background:#23bfee!important;border:1px solid #23bfee !important; font-weight:600;color:#fff!important; font-size:14px; padding: 5px 10px; text-align: center; transition: all 0.4s ease 0s;}
.nx-btn							{margin-top:15px !important; margin-bottom:15px!important;margin-right:15px !important;}
.b-btn						   {margin-top:15px !important; margin-bottom:15px!important;margin-left:15px !important;}
.b-btn a:hover                {border:1px solid #23bfee !important; background:#fff !important; color:#23bfee!important;}
.b-btn a                      {background:#23bfee!important;border:1px solid #23bfee !important; font-weight:600;color:#fff!important; font-size:14px; padding: 5px 10px; text-align: center; transition: all 0.4s ease 0s;}
.prjt							{margin-bottom:30px;}
.prfon                          {font-size: 15px;font-weight: bold;color:#b92c28;!important;}
</style>

<div class="content_wrapper padlr0">
	<div class="container-fluid padlr0">
		<div class="col-lg-12">
            <h1 class="prjt"><strong>Resource Priority</strong>
			<div class="btn-group prfon">
				<a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"><?php if(isset($project)) { echo $CostCenter['CostCentreName'];  } else{ echo "";} ?><span class="edit_symbols" data-placement="right" data-toggle="tooltip" data-original-title="Cost&nbsp;Centre&nbsp"><i class="fa fa-caret-down "></i></span></a> 							
				<div class="dropdown-menu toolbar_ddown proname_ddown arrow" role="menu">
					<ul>
						<?php foreach($arr_costcenter as $costcentre){?>
						 <li><a href="javascript:void(0);" class="projId" data-index="<?php echo $costcentre['CostCentreId'];?>"><?php echo ucfirst($costcentre['CostCentreName']);?></a></li>
					   <?php }	?>
						<li><a href="<?php echo $this->basePath(); ?>/mms/master/<?php echo $this->currentRequest()->get('action'); ?>">All</a></li>
					</ul>
				</div>
			</div>
			</h1>
		</div>
        <div class="col-lg-12 clear">
			<ul class="breadcrumb_area ripple">
			    <?php if(isset($project) && intval($project)>0) { ?>
				<li><a href="<?php echo $this->basePath(); ?>/mms/master/opening-stock/<?php echo $url; ?>">Opening Stock</a></li>
				<li><a href="<?php echo $this->basePath(); ?>/mms/master/resource-register/<?php echo $url; ?>">Resource Required</a></li>
				<li><a href="#" class="active">Resource Priority</a></li>
				<li><a href="<?php echo $this->basePath(); ?>/mms/master/gate-list/<?php echo $url; ?>">Gate List</a></li>
			   <?php } else { ?>
			    <li><a href="<?php echo $this->basePath(); ?>/mms/master/opening-stock">Opening Stock</a></li>
				<li><a href="<?php echo $this->basePath(); ?>/mms/master/resource-register">Resource Required</a></li>
				<li><a href="#" class="active">Resource Priority</a></li>
			   <li><a href="<?php echo $this->basePath(); ?>/mms/master/gate-list">Gate List</a></li> <?php } ?>
			</ul>
        </div>
        <div class="fixed-action-btn active mar_15">
			<a class="btn-floating btn-large">
				<i class="fa fa-paperclip"></i>
			</a>
			<ul>
				<li>
					<a class="btn-floating hide-input-file" data-toggle="tooltip" data-placement="top" data-original-title="Import From Excel">
					<i class="fa fa-file-excel-o"></i>
					<input type="file" name="myfile" id="myfile" class="input-large" accept=".xls,.xlsx,application/vnd.  openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" onchange="fileupload(this)" />
					</a>
				</li>
				<li>
					<a class="btn-floating" href="#" download data-toggle="tooltip" data-placement="top" data-original-title="Download Sample">
					<i class="fa fa-download"></i>
					</a>
				</li>
			</ul>
		</div>
		<div class="col-lg-12 commargin_top clear">
            <div class="table-responsive clear">
                <div id="jqxGrid" style="margin-top:30px;margin-bottom:20px;"></div>
            </div>
        </div>
        <div class="col-lg-12 savebtn_area">
			<ul>
				<?php if(isset($project) && intval($project)>0) { ?>
				<li class="b-btn float_l"><a href="<?php echo $this->basePath(); ?>/mms/master/resource-register/<?php echo $url; ?>"><i class="fa fa-chevron-circle-left" style="padding-right:6px;"></i>Back</a>
				<?php } else { ?>
				<li class="b-btn float_l"><a href="<?php echo $this->basePath(); ?>/mms/master/opening-stock"><i class="fa fa-chevron-circle-left" style="padding-right:6px;"></i>Back</a></li>
				<?php } ?>
				<?php if(isset($project) && intval($project)>0) { ?>
				<li class="nx-btn float_r"><a  href="<?php echo $this->basePath(); ?>/mms/master/gate-list/<?php echo $url; ?>">Next<i class="fa fa-chevron-circle-right" style="padding-left:6px;"></i></a><?php } else{ ?></li>
				<li class="nx-btn float_r"><a  href="<?php echo $this->basePath(); ?>/mms/master/gate-list">Next<i class="fa fa-chevron-circle-right" style="padding-left:6px;"></i></a><?php } ?></li>
			</ul>
		</div>
    </div>
</div>
<script type="text/javascript">
    var data = <?php echo (isset($priority)) ? json_encode($priority) : ''?>;
        $jqxGrid = $("#jqxGrid");
    $(function () {
		
		var source = {
            localdata: data,
            dataType: "json",
            dataFields: [
                {name: 'ResourceId', type: 'int'},
                {name: 'Code', type: 'string'},
                {name: 'Resource', type: 'int'},
                {name: 'Priority', type: 'string'},
			],
            id: 'ResourceId'
        };
		var list = ['None', 'High','Medium' ,'Low'];
		var dataAdapter = new $.jqx.dataAdapter(source);
		var list = new $.jqx.dataAdapter(list, { autoBind: true, async: false });
		
        $jqxGrid.jqxGrid({
            width: "100%",
            source: dataAdapter,
            sortable: true,
            pagerButtonsCount: 6,
            filterable: true,
            pageable: true,
            rowDetails: true,
            autoheight: true,
			showfilterrow: true,
			editmode: 'click',
            editable: true,
            altrows: true,
			selectionmode: 'singlecell',
			selectionmode: 'multiplecelladvanced',
			
            //enabletooltips: true,
            columns: [
                {text: 'ResourceId', datafield: 'ResourceId',hidden: false, width:100,editable: false},
                {text: 'Code', datafield: 'Code', width:100,editable: false},
                {text: 'Resource', datafield: 'Resource', editable: false},
                {text: 'Priority',  columntype: 'dropdownlist', datafield: 'Priority',
			     initeditor: function (row, column, editor) {
					editor.jqxDropDownList('Open'); 
					editor.jqxDropDownList({ displayMember: 'Priority', source: list});
				}
                }
		]
		});
		 $("#jqxGrid").on('cellvaluechanged', function (event) 
{
	           var args = event.args;
				// column data field.
				var dataField = event.args.datafield;
				// row's bound index.
				var rowBoundIndex = event.args.rowindex;
				// cell value
				var value = args.value;
				// row's data.
				var rowData = args.row;
				//console.log(rowData);
				var data = $("#jqxGrid").jqxGrid("getrowdata", rowBoundIndex);
				var dt=data.ResourceId;
				var prior=data.Priority;
				$.ajax({
					url:"<?php echo $this->basePath(); ?>/mms/master/priority",
							type:"post",
							data:{'dat':dt,'selectedIndex':prior},
							success:function(data, textStatus, jqXHR){
							}
							// error:function(jqXHR, textStatus, errorThrown){
								// //$('.right_lightbox').hide();
								// alert(textStatus+"-----"+errorThrown);
							// }
					});
});
				
		 
    });
$('.projId').on('click',function(){
var urlId = $(this).attr('data-index');
location.replace("<?php echo $this->basePath(); ?>/mms/master/priority/"+urlId);
});	
</script>