<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/mms.css" />
<style type="text/css">
    .back-img {min-height:380px; min-height:100%; margin-bottom:20px;background:#DBEAF8;border:1px solid #fff;}
    .cnt_slider	{min-height:400px;margin-top:10px;margin-bottom:30px; padding:25px 0px 10px 0px;border:1px solid #ddd;-webkit-box-shadow:0 1px 2px rgba(0,0,0,.075);-moz-box-shadow:0 1px 2px rgba(0,0,0,.075);box-shadow:0 1px 2px rgba(0,0,0,.075);}
    .txt_center{text-align:center!important;}
    .wpm-next li a {background: #4caf50;padding: 5px;margin-left: 5px;color: #fff;}
    .mar_btm {padding-bottom:20px;}
    .mar_lt{margin-left:10px;}
    .pad_tp{padding-bottom:10px;}
    .dropdown-menu {left:-146px!important;z-index: 1 !important;}
    .mms_h1				{margin-top:10px;}
    .mms_h2				{margin-top:20px; color:#906;}
    .mms_p				{text-align:center;padding-top:10px;color:#333; padding-bottom:30px;font-size:15px;}
    .mar_tp30			{margin-top:30px;}
    .mms_h1							{margin-top:10px;}
    .mms_h2							{margin-top:20px; color:#906;}
    .mms_p							{text-align:center;padding-top:10px;color:#333; font-size:15px;}
    .nxt-btn                        {text-align:right; margin-right:68%; margin-top:20px;}
    .nxt-btn a:hover                {border:1px solid #367d39 !important; background:#fff !important; color:#367d39 !important;}
    .nxt-btn a                      {background:#367d39!important;border:1px solid #367d39 !important; font-weight:600;color:#fff!important; font-size:14px; padding: 5px 10px; text-align: center; transition: all 0.4s ease 0s;}
    .bk-btn                        {text-align:left; margin-left:68%; margin-top:20px;}
    .bk-btn a:hover                {border:1px solid #367d39!important; background:#fff !important; color:#367d39 !important;}
    .bk-btn a                      {background:#367d39!important;border:1px solid #367d39 !important; font-weight:600;color:#fff!important; font-size:14px; padding: 5px 10px; text-align: center; transition: all 0.4s ease 0s;}
    .col-md-offset-5 {
        margin-left: 38.666667% !important;}
    .container-fluid h1{
        color: #244996;
        font-size: 2em;
        padding-bottom: 15px;
    }
    .lb{color:#000;padding-bottom:5px;font-size:15px;}
    .spa{color:#b33333;margin-left:8px;text-align:right; padding-bottom:5px; font-size:15px;}
    .float_l		{float:left;}
    .float_r		{float:right;}
    .float_rt		{float:right; margin-right:10px;}
    .mtrl_txt:focus, .mtrl_txt.active {border: 1px solid #39F;}
    .mtrl_txt{border:1px solid #CCC;padding:8px 4px;font-size:14px!important;font-weight:normal !important;width:100%;-webkit-transition: border-color 1s ease;-moz-transition:border-color 1s ease; -o-transition: border-color 1s ease;-ms-transition: border-color 1s ease;transition: border-color 1s ease;background:#fff;}
    .show-on-hover:hover > ul.dropdown-menu {display: block;}
    .show-on-hover> ul.dropdown-menu span{color:#3f6ac3;}
    .btn_clr {margin-top:5px; padding:2px 7px;background:#fff; border:1px solid #3f6ac3;border-radius:25px; color:#3f6ac3;}
    .det_box{right:-214px;width:200px;height:auto;padding:15px;background:#fff;border: 1px solid rgba(0,0,0,.15);border-radius: 4px;-webkit-box-shadow: 3px 4px 6px rgba(0,0,0,.175);box-shadow: 3px 4px 6px rgba(0,0,0,.175);}
    .vendor_button select {background-color: white !important;height: 32px !important;border-radius: 0px !important;}

</style>
<!--main-->

<div class="content_wrapper padlr0 main">
    <div class="container-fluid">
        <div class="col-lg-12">
            <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 cnt_slider back-img">
                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                    <!-- Wrapper for slides -->
                    <div class="carousel-inner" role="listbox">
                        <div class="item active">
                            <div class="txt_center col-lg-12">
                                <div class="row">
                                    <h1 class="txt_center">Material Setup</h1>
                                    <h2 class="mms_h2">Are you planning for MaterialItem create?</h2>
                                    <p class="mms_p">You want to proceed With</p>
                                </div>
                                <div class="col-md-3 col-md-offset-5">
                                    <div class="radio_check" style="text-align:center !important;">
                                        <p class="stat_lbl">
                                            <input type="radio" value="1" id="manual" name="rdio" checked />
                                            <label for="manual" class="ripple">Manual</label>
                                        </p>
                                        <p class="stat_lbl">
                                            <input type="radio" value="2" id="report" name="rdio" />
                                            <label for="report" class="ripple">Import</label>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="item second">
                            <div class="col-lg-12 clear">
                                <div class="row">
                                    <h1 class="txt_center">Resource Setup<?php ?></h1>
                                </div>
                                <div class="txt_center col-lg-12">
                                    <h2 class="mms_h2">Are you planning for Resource setup?</h2>
                                    <p class="mms_p">Do You Want To Create one ResourceItem or multiple ResourceItem Details?</p>
                                </div>
                                <div class="col-md-3 col-md-offset-5">
                                    <div class="radio_check">
                                        <p class="stat_lbl">
                                            <input type="radio" value="0" id="single" name="rdi" checked="checked"/>
                                            <label for="single" class="ripple">Single</label>
                                        </p>
                                        <p class="stat_lbl">
                                            <input type="radio" value="1" id="multiple" name="rdi"/>
                                            <label for="multiple" class="ripple">Multiple</label>
                                        </p>
                                    </div>
                                </div>
                                <div class="col-lg-12 savebtn_area m_btm30 m_auto no_border">
                                    <ul class=" mar_tp30">
                                        <li class="save_btn m_auto">
                                            <a  href="javascript:void(0);"  onclick="sample1(this);" data-rid="1" class="ripple">Proceed</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <div class="col-lg-12">
                                <div class="row">
                                    <h1 class="txt_center form_main_h1 mms_h1">Material Setup</h1>
                                </div>
                            </div>
                            <div class="txt_center col-lg-12">
                                <h2 class="mms_h2">Are you planning for MaterialItem Import?</h2>
                                <p class="mms_p mar_30">You want to proceed With</p>
                            </div>
                            <div class="txt_center col-lg-6 col-lg-offset-3">
                                <div class="upload_file">
                                    <input type="file" name="myfile" id="myfile" class="hide_file_input" accept=".xls, .xlsx, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" onchange="getExcelField(this.value);">
                                    <div class="upload_file_div">
                                        <input type="text" class="upload_file_input"  name="uploadedFile" id="uploadedFile" label="Select File" />
                                        <div class="upload_file_text">Upload</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="txt_center">
                        <ul class="prev_next wpm-next">
                            <li id="backPrev" style="display: none;"><a href="javascript:void(0);" onclick="return goBack(0);"><span><i class="fa fa-arrow-left"></i></span> Back</a></li>
                            <li><a href="javascript:void(0);" role="button" onclick="return validateStg();" id="nextBtn">Next <span><i class="fa fa-arrow-right"></i></span></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--Multiple-->
<form method="post" id="forSingle">
<div id="resourceentry_2" style="display:none">
    <!--    <form method="post" id="forSingle">-->
    <div class="col-lg-12">
        <h1 class="txt_center" style="color: #244996;font-size: 2em;padding-bottom: 30px;padding-top: 15px;">Add New Resource Item</h1>
    </div>
    <input type="hidden" name="type" id="type">
    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2" style="position:relative;">
                <div class="form-group col-lg-12">
<!--                    <select name="resource" id="cboResource1" class=" lbl_move single_dropdown select2-hidden-accessible" data-size="5"-->
                    <select name="resource" id="cboResource1" class="lbl_move single_dropdown" data-size="5"
                            title="Select Resource" style="width:100%;" label="Select Resource" tabindex="-1" aria-hidden="true" >
                        <option value=""> Select Resource </option>
                        <?php foreach($this->resourceList as $resource): ?>
                            <option <?php if(isset($brandDetail)){ if($brandDetail['ResourceId'] == $resource['value']){ echo"selected"; } } ?> value="<?php echo $resource['value'];?>" data-measure="<?php echo $resource['MeasureType']; ?>"  data-value="<?php echo $resource['value']; ?>" ><?php echo $resource['data'];?></option>
                        <?php endforeach; ?>
                    </select>
                    <div class="error_message">
                        <p>Please select the Resource...</p>
                    </div>
                </div>
            </div>

            <div class="btn-group show-on-hover mar_lt pad_tp" style="position:absolute;top:7px;">
                <button type="button" class="btn_clr" data-toggle="dropdown">
                    <span class="?"><i class="fa fa-file-text-o"></i></span>
                    <span class=""></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Type -<span id="material1"  class="det">&nbsp;<?php if(isset($brandDetail)){ echo $brandDetail['MeasureType']; } ?></span></a></li>
                    <li><a href="#">Group -<span  id="group1"  class="det">&nbsp;<?php if(isset($brandDetail)){ echo $brandDetail['ResourceGroupName']; } ?></span></a></li>
                    <li><a href="#">Code - <span id="code1"  class="det">&nbsp;<?php if(isset($brandDetail)){ echo $brandDetail['Code']; } ?></span></a></li>
                    <li><a href="#">Unit -<span  id="unit1"  class="det">&nbsp;<?php if(isset($brandDetail)){ echo $brandDetail['UnitName']; } ?></span></a></li>
                    <li><a href="#">Base Rate - <span id="baserate1"  class="det">&nbsp;<?php if(isset($brandDetail)){ echo $brandDetail['Rate']; } ?></span></a></li>
                    <li><a href="#">Q.rate -<span id="qrate1"  class="det">&nbsp;</span></a></li>
                </ul>
            </div>
            <div class="col-lg-12 commargin_top clear">
                <div class="table-responsive clear">
                    <table id="resourcelist" class="table table-hover">
                        <thead>
                        <tr>
                            <th width='13%'>Item Name</th>
                            <th width='13%'>Item Code</th>
                            <th width='13%'>Rate</th>
                            <th width='13%'>Unit Name</th>
                            <th width='13%'>Length</th>
                            <th width='13%'>Breadth</th>
                            <th width='13%'>Depth</th>
                            <th width='13%'>Total</th>
                            <th>&nbsp;</th>
                            <th>&nbsp;</th>
                        </tr>
                        <tbody>

                        </tbody>
                        </thead>
                    </table>
                    <input type="hidden" class="parent_txts" name="RowCount1" id="RowCount1" value="1"/>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-12 savebtn_area">
        <ul>
            <li id="submit" class="save_btn float_r">
                <input type="button" class="parent_txts" name="saveNew" id="saveNew" value="Save"/>
                <!--                <button class="parent_txts" name="saveNew" id="saveNew"  value="forsingle">Save</button>-->
            </li>
            <li id="submit1" class="save_btn float_r">
                <input type="button" class="parent_txts" name="saveExit" id="saveExit" value="Save &amp; New"/>
                <!--                <button class="parent_txts" name="saveExit" id="saveExit"  value="forsingle">Save &amp; New</button>-->
            </li>
            <li class="cancel_btn cancel_btn_bluecolor float_l">
                <a class="ripple has-ripple" style="position: relative; overflow: hidden; cursor:pointer;" button type="button" onclick="backmuiti(this)" data-rid="1" id="backRid" class="ripple">back<span class="ripple-wrapper"></span></a>
            </li>
            <li class="cancel_btn cancel_btn_bluecolor float_l">
                <a class="ripple has-ripple" style="position: relative; overflow: hidden; cursor:pointer;" button type="button" href="<?php echo $this->basePath() . '/mms/master/resourceview';?>"  class="ripple">Cancel<span class="ripple-wrapper"></span></a>
            </li>
        </ul>
    </div>
    <!--    </form>-->
</div>
<!--End-->
<!--Single-->
<div id="resourceentry_1" style="display:none">
    <!--    <form method="post" id="forSingle">-->
    <div class="col-lg-12">
        <h1 class="txt_center" style="color: #244996;font-size: 2em;padding-bottom: 30px;padding-top: 15px;">Add New Resource Item</h1>
    </div>
    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2" style="position:relative;">
				<input type="hidden" name="CodeType" value="<?php echo (isset($CodeType)) ? $CodeType : "";?>"/>
                <div class="form-group col-lg-12">
<!--                    <select name="resourceId" id="cboResource" class=" lbl_move single_dropdown" data-size="5"-->
                    <select name="resourceId" id="cboResource" class=" lbl_move single_dropdown " data-size="5"
                            title="Select Resource" style="width:100%;" label="Select Resource" tabindex="-1" aria-hidden="true" >
                        <option value=""> Select Resource </option>
                        <?php foreach($this->resourceList as $resource): ?>
                            <option <?php if(isset($brandDetail)){ if($brandDetail['ResourceId'] == $resource['value']){ echo"selected"; } } ?> value="<?php echo $resource['value'];?>" data-measure="<?php echo $resource['MeasureType']; ?>"  data-value="<?php echo $resource['value']; ?>" ><?php echo $resource['data'];?></option>
                        <?php endforeach; ?>
                    </select>
                    <div class="error_message">
                        <p>Please select the Resource...</p>
                    </div>
                </div>
                <div class="btn-group show-on-hover mar_lt pad_tp" style="position:absolute;top:7px;">
                    <button type="button" class="btn_clr" data-toggle="dropdown">
                        <span class="?"><i class="fa fa-file-text-o"></i></span>
                        <span class=""></span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#">Type -<span id="material"  class="det">&nbsp;<?php if(isset($brandDetail)){ echo $brandDetail['MeasureType']; } ?></span></a></li>
                        <li><a href="#">Group -<span  id="group"  class="det">&nbsp;<?php if(isset($brandDetail)){ echo $brandDetail['ResourceGroupName']; } ?></span></a></li>
                        <li><a href="#">Code - <span id="code"  class="det">&nbsp;<?php if(isset($brandDetail)){ echo $brandDetail['Code']; } ?></span></a></li>
                        <li><a href="#">Unit -<span  id="unit"  class="det">&nbsp;<?php if(isset($brandDetail)){ echo $brandDetail['UnitName']; } ?></span></a></li>
                        <li><a href="#">Base Rate - <span id="baserate"  class="det">&nbsp;<?php if(isset($brandDetail)){ echo $brandDetail['Rate']; } ?></span></a></li>
                        <li><a href="#">Q.rate -<span id="qrate"  class="det">&nbsp;</span></a></li>
                    </ul>
                </div>
                <!--<div class="det_box" style="position:absolute;">
								<ul>
									<li><label class="lb">Type -<span id="material" class="spa">&nbsp;<?php if(isset($brandDetail)){ echo $brandDetail['MeasureType']; } ?></span></label></li>
									<li><label class="lb">Group -<span id="group" class="spa">&nbsp;<?php if(isset($brandDetail)){ echo $brandDetail['ResourceGroupName']; } ?></span></label></li>
									<li><label class="lb">Code - <span id="code" class="spa">&nbsp;<?php if(isset($brandDetail)){ echo $brandDetail['Code']; } ?></span> </label></li>
									<li><label class="lb">Unit -<span id="unit" class="spa">&nbsp;<?php if(isset($brandDetail)){ echo $brandDetail['UnitName']; } ?></span></label></li>
									<li><label class="lb">Base Rate -<span id="baserate" class="spa">&nbsp;<?php if(isset($brandDetail)){ echo $brandDetail['Rate']; } ?></span></label></li>
									<li><label class="lb">Q.rate -<span class="spa">&nbsp;</span></label>
								</ul>
							</div>-->
                <div class="form-group col-lg-12">
                    <input type="text" class="form-control lbl_move" label="ItemName" id="txtItemName" name="txtItemName" value="<?php echo (isset($brandDetail)?$brandDetail['ItemName']:"");?>"/>
                    <div class="error_message">
                        <p>Please Enter Item Name...</p>
                    </div>
                </div>
                <div class="form-group col-lg-12">
                    <input type="text" class="form-control lbl_move" label="ItemCode" id="txtItemCode" name="txtItemCode" value=""/>
                    <div class="error_message">
                        <p>Please Enter ItemCode...</p>
                    </div>
                </div>
                <div class="form-group col-lg-12">
                    <input type="text" class="form-control lbl_move" label="Rate" id="txtRate" name="txtRate" value="<?php echo (isset($brandDetail)?$brandDetail['Rate']:"");?>" onkeypress="return isDecimal(event,this)" />
                    <div class="error_message">
                        <p>Please Enter Rate...</p>
                    </div>
                </div>
                <div class="form-group col-lg-12">
                    <select name="cboUnit" id="cboUnit" class="lbl_move single_dropdown" label="Select Unit" data-size="5" title="Select Resource" style="width:100%;" label="" tabindex="-1" aria-hidden="true" disabled />
                    <option value=""> Select Unit </option>
                    <?php foreach($unitList as $unit):?>
                        <option <?php if(isset($brandDetail)){ if($brandDetail['UnitId'] == $unit['value']){ echo"selected"; } } ?> value="<?php echo $unit['value']; ?>" ><?php echo $unit['data']; ?></option>
                    <?php endforeach;?>
                    </select>
                    <div class="error_message">
                        <p>Please select Unit...</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div id="measurement">
                    <div class="form-group col-lg-12">
                        <input type="text" name="length" id="Length" class="diff_txt" onchange = "btotal();" placeholder="Length" onkeypress="return isDecimal(event,this)" value="<?php echo (isset($brandDetail)?$brandDetail['Length']:0);?>" />
                    </div>
                    <div class="form-group col-lg-12">
                        <input type="text" name="breadth" id="Breadth" class="diff_txt" onchange = "btotal();"  placeholder="Breadth" onkeypress="return isDecimal(event,this)" value="<?php echo (isset($brandDetail)?$brandDetail['Breadth']:0);?>" />
                    </div>
                    <div class="form-group col-lg-12">
                        <input type="text" name="depth" id="Depth" class="diff_txt" onchange = "btotal();"  placeholder="Depth" onkeypress="return isDecimal(event,this)" value="<?php echo (isset($brandDetail)?$brandDetail['Depth']:0);?>" />
                    </div>
                    <div class="form-group col-lg-12">
                        <input type="text" name="total" id="total" readonly class="diff_txt" placeholder="L*B*D" value="<?php echo (isset($brandDetail)?$brandDetail['LBDTotal']:0);?>" />
                    </div>
                </div>
            </div>
            <div class="col-lg-12 savebtn_area">
                <ul>
                    <li id="continue" class="save_btn float_r">
                        <input type="button" class="parent_txts" name="saveNew" id="saveNew" value="Save"/>
                        <!--                                                    <button class="parent_txts" name="saveNew" id="saveNew" type="button"  value="forsingle">Save</button>-->
                        <!--                            <a class="parent_txts" button type="button" name="saveNew" id="saveNew" value="forsingle" >Save</a>-->
                        <!--                                    <a data-toggle="tooltip" class="ripple" title="Save to Continue">Save</a>-->
                    </li>
                    <li id="continue1" class="save_btn float_r">
                        <input type="button" class="parent_txts" name="saveExit" id="saveExit" value="Save &amp; New" />
                        <!--                        <button class="parent_txts" name="saveExit" id="saveExit"  value="forsingle">Save &amp; New</button>-->

                    </li>
                    <li class="cancel_btn cancel_btn_bluecolor float_l">
                        <a class="ripple has-ripple" style="position: relative; overflow: hidden; cursor:pointer;" button type="button" onclick="backsingle(this)" data-rid="1" id="backRid" class="ripple">back<span class="ripple-wrapper"></span></a>
                    </li>

                    <li class="cancel_btn cancel_btn_bluecolor float_l">
                        <a class="ripple has-ripple" style="position: relative; overflow: hidden; cursor:pointer;" button type="button" href="<?php echo $this->basePath() . '/mms/master/resourceview';?>" class="ripple">cancel<span class="ripple-wrapper"></span></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!--    </form>-->
</div>
</form>
<!--Import-->
<div id="excelfieldmodal" class="modal fade" role="dialog" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h1>Resource Import Sheet - Assign Fields</h1>
            </div>
            <div class="modal-body">
                <div class="table-responsive popuptable">
                    <table class="table" width="100%" style=" margin-bottom:0px;">
                        <tbody>
                        <tr id="excelfieldTable"></tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="modal-footer"> <a href="#" class="md_cance" data-dismiss="modal" data-toggle="tooltip" title="" data-original-title="Cancel" style="position: relative; overflow: hidden;">Cancel<span class="ripple-wrapper"></span><span class="ripple-wrapper"></span></a>
                <button type="button" class="md_ok" onclick="return fileupload()" >Next</button>
            </div>
        </div>
    </div>
</div>
<div id="excelmodal" class="modal fade" role="dialog" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-lg" role="document" style="width:75%;">
        <form id="excel_model">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h1>Resource Import Sheet</h1>
                </div>
                <div class="modal-body">
                    <div id="error_data"></div>
                    <div class="table-responsive topsp">
                        <table class="table" style=" margin-bottom:0px;" id="excelTable">
                            <thead>
                            <tr>
                                <th width="13%" class="th-modal">Code</th>
                                <th width="13%" class="th-modal">Resource</th>
                                <th width="15%" class="th-modal">ItemCode</th>
                                <th width="15%" class="th-modal">ItemDescription</th>
                                <th width="15%" class="th-modal">Unit</th>
                                <th width="14%" class="th-modal">Rate</th>
                            </tr>
                            </thead>
                            <tbody id="table_bind">

                            </tbody>
                            <input type="hidden" name="rowCount" value="0" id="rowCount" />
                            <input type="hidden" name="csrf" value="<?php echo (isset($csrf)) ? $csrf : "";?>" id="csrf" />
                            <input type="hidden" name="mode" value="validate" id="mode" />
                        </table>
                    </div>
                </div>
                <div class="modal-footer clear">
                    <a href="#" id="can_button" class="md_cance" data-dismiss="modal" data-toggle="tooltip" title="" data-original-title="Cancel" style="position: relative; overflow: hidden;">Cancel<span class="ripple-wrapper"></span><span class="ripple-wrapper"></span></a>
                    <button type="button" id="app_button" class="md_ok" onclick="return dataInsert()" >Apply</button>
                </div>
            </div>
        </form>
    </div>
</div>

<script id="excel_bind" type="text/template" class="hide">
    <tr id="excelrowid__" >
        <td><input class="parent_text" type="text" placeholder="Code" name="excelcode__" value = "" id="excelcode__"/></td>
        <td><input class="parent_text" type="text" placeholder="Resource" name="excelresource__" value = "" id="excelresource__" /></td>
        <td><input class="parent_text" type="text" placeholder="ItemCode" name="excelitemcode__" value = "" id="excelitemcode__" /></td>
        <td><input class="parent_text" type="text" placeholder="ItemDescription" name="excelitemdescription__" value = "" id="excelitemdescription__"/></td>
        <td><input class="parent_text" type="text" placeholder="Unit" name="excelunit__" value = "" id="excelunit__" /></td>
        <td><input class="parent_text" type="text" placeholder="Rate" name="excelrate__" value = "" id="excelrate__" /></td>
        <td align="center">
            <ul class="action_btns">
                <li>
                    <a href="#" id="excelTrDelete__" class="excelTrDelete" onclick="deleteRow(this);"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete" ></i></a>
                </li>
            </ul>
        </td>
    </tr>
</script>
<!--End-->
<script>
errorFlag = 0;
function backmuiti(val){
    $('.content_wrapper').show();
    $('#resourceentry_2').hide();
}
function backsingle(val){
    $('.content_wrapper').show();
    $('#resourceentry_1').hide();
}
$(document).ready(function() {
//    $(".single_dropdown").select2({
//        placeholder: "",
//        allowClear: true
//    });

    $("#measurement").hide();
    <?php if(isset($brandDetail) && $brandDetail['MeasureType'] == 'L'){ ?>
    $("#measurement").show();
    <?php }?>

    var val= <?php echo (isset($brandId)) ? json_encode($brandId) : ''?>;
    if(val>0){
        $('.content_wrapper').hide();
        $('#resourceentry_1').show();
    }

});

var arrayField =[];
arrayField = [{ data :1, value: 'Code' },
    { data :2, value: 'Resource' },
    { data :3, value: 'ItemCode' },
    { data :4, value: 'ItemDescription' },
    { data :5, value: 'Unit' },
    { data :6, value: 'Rate' }
];
var selectCol=[];
var arrayFieldR = arrayField;
function getExcelField(x,y) {
    $('#uploadedFile').val(x);
    $('#rowCount').val(0);
    $('#can_button').html('Cancel').attr('data-original-title','Cancel');
    $('#app_button').html('Apply');
    $('#error_data').html('');
    formData = new FormData();
    formData.append('file', $('#myfile').prop("files")[0]);
    formData.append('mode','title');
    formData.append('csrf', "<?php echo isset($csrf)?$csrf:''; ?>");

    $.ajax({
        url: getBaseURL() +"mms/master/get-resource-field-data",
        async: false,
        dataType: 'script',
        cache: false,
        contentType: false,
        processData: false,
        data: formData,
        type: 'post',
        success: function(data,status, xhr) {
            var obj = jQuery.parseJSON(data);
            $("#excelfieldTable").find("th").remove();
            $("#excelfieldTable").find("td").remove();

            var sStr="Select Field";
            var data = "<option value=''></option>";
            for (var i = 0; i < obj.length; i++) {
                var fieldName = $.trim(obj[i]['Field']);
                if (fieldName != "") {
                    data +="<option value='"+ parseInt(i+1) +"'>"+fieldName+"</option>";
                }
            }

            $.each(arrayFieldR,function(i,o) {
                $("#excelfieldTable").append('<tr><th width="20%"><input id="efield_' + i + '" class="text-reon text-right" type="text" value="'+ o.value+'" style="background: transparent;"/></th><td width="70"><select id="field_' + i + '" class="single_dropdown lbl_move data_bind" style="width:100%;" label="'+sStr+'"></select></td></tr>');
                $('#efield_' + i).prop('readonly', true);
                $('#field_' + i).html(data);
            });
            $(".single_dropdown").select2({
                placeholder: "",
                allowClear: true
            });
            //bindexcelFieldComplete();
            $("#excelfieldmodal").modal('show');
        },
        error: function(xhr, status, errorThrown) {
            if (xhr.status == 400)
                alert(xhr.responseText);
            else
                alert(errorThrown);
        }
    });
    clearInputFile($('#myfile'));
}
function clearInputFile(file){
    var f = file[0];
    if(f.value){
        try{
            f.value = '';
        }catch(err){ }
        if(f.value){
            var form = document.createElement('form'),
                parentNode = f.parentNode, ref = f.nextSibling;
            form.appendChild(f);
            form.reset();
            parentNode.insertBefore(f,ref);
        }
    }
}
function fileupload() {
    var isValid=true;
    $.each(arrayField,function(e,f){
        if($.trim($('#field_'+e).val())=="") {
            var check = parseInt(e)+1;
            if(check==1 || check==2 || check==3 || check==4 || check==5 || check==6){
                alert('Map the '+f.value);
                isValid=false;
            }
        }

    });
    if (isValid==false) { return;}
    $("body").removeClass('modal-open');
    $("#excelfieldmodal").modal('hide');
    var arrHeader =[];
    for (var i = 0; i < $("#excelfieldTable").find("th").length; i++) {
        if($('#field_'+i).val()!="") {
            arrHeader.push({efield: $('#field_' + i +' option:selected').text(), field: $('#efield_' + i).val()});
        }
    }
    arrHeader =  JSON.stringify(arrHeader);
    formData.append('arrHeader', arrHeader);
    formData.append('mode', 'body');
    formData.append('csrf', "<?php echo isset($csrf)?$csrf:''; ?>");
    $.ajax({
        url: getBaseURL() +"mms/master/get-resource-field-data",
        async: false,
        dataType: 'script',
        cache: false,
        contentType: false,
        processData: false,
        data:  formData,
        type: 'post',
        success: function(data,status, xhr) {
            var obj = jQuery.parseJSON(data);
            var template = $('#excel_bind').html();
            $('#table_bind').html('');
            if(obj.length>0) {
                for (var j = 0; j < obj.length; j++) {
                    $('#table_bind').append(template.replace(/__/g, '_' + j));
                    $('#rowCount').val(j);
                    if (obj[j].Valid == true) {
                        $("#excelcode_" + j).val(isNullCheck(obj[j].Code, 'string'));
                        $("#excelresource_" + j).val(isNullCheck(obj[j].Resource, 'string'));
                        $("#excelitemcode_" + j).val(isNullCheck(obj[j].ItemCode, 'string'));
                        $("#excelitemdescription_" + j).val(isNullCheck(obj[j].ItemDescription, 'string'));
                        $("#excelunit_" + j).val(isNullCheck(obj[j].Unit, 'string'));
                        $("#excelrate_" + j).val(isNullCheck(obj[j].Rate, 'string'));
                        //$("#excelproject_" + j).val(isNullCheck(obj[j].ProjectName, 'string'));
                    }

                }
                $("#excelmodal").modal('show');
                setTimeout(function() { $("body").addClass('modal-open');}, 200);

            } else {
                alert("Contains No Data");
            }
        },
        error: function(xhr, status, errorThrown) {
            if (xhr.status == 400) {
                alert(xhr.responseText);
            }
            else {
                alert('Invalid Excel allocation');
            }
        }
    });
    clearInputFile($('#myfile'));
}
function dataInsert() {
    //$("#excelmodal").modal('hide');
    $("body").removeClass('modal-open');

    $.ajax({
        url: getBaseURL() + 'mms/master/get-resource-field-data',
        type: 'POST',
        data: $('#excel_model').serialize(),
        success: function (data, textStatus, jqXHR) {
            var obj = jQuery.parseJSON(data);
            var template = $('#excel_bind').html();
            if(obj.length>0) {
                $('#table_bind').html('');
                $('#error_data').html('Error Data:');
                for (var j = 0; j < obj.length; j++) {
                    $('#table_bind').append(template.replace(/__/g, '_' + j));
                    removeError($("#excelcode_" + j));
                    removeError($("#excelresource_" + j));
                    removeError($("#excelitemcode_" + j));
                    removeError($("#excelitemdescription_" + j));
                    removeError($("#excelunit_" + j));
                    removeError($("#excelrate_" + j));
                    $("#excelcode_" + j).val(isNullCheck(obj[j].Code[0], 'string'));
                    $("#excelresource_" + j).val(isNullCheck(obj[j].Resource[0], 'string'));
                    $("#excelitemcode_" + j).val(isNullCheck(obj[j].ItemCode[0], 'string'));
                    $("#excelitemdescription_" + j).val(isNullCheck(obj[j].ItemDescription[0], 'string'));
                    $("#excelunit_" + j).val(isNullCheck(obj[j].Unit[0], 'string'));
                    $("#excelrate_" + j).val(isNullCheck(obj[j].Rate[0], 'string'));

                    if(obj[j].Code[1]==1) {
                        showError($("#excelcode_" + j),'');
                    }
                    if(obj[j].Resource[1]==1) {
                        showError($("#excelresource_" + j),'');
                    }
                    if(obj[j].ItemCode[1]==1) {
                        showError($("#excelitemcode_" + j),'');
                    }
                    if(obj[j].ItemDescription[1]==1) {
                        showError($("#excelitemdescription_" + j),'');
                    }
                    if(obj[j].Unit[1]==1) {
                        showError($("#excelunit_" + j),'');
                    }
                    if(obj[j].Rate[1]==1) {
                        showError($("#excelrate_" + j),'');
                    }
                }
                $('#rowCount').val(parseInt(obj.length)-1);
                $('#can_button').html('Discard').attr('data-original-title','Discard');
                $('#app_button').html('Correct');
                $("#excelmodal").modal('show');
                setTimeout(function() { $("body").addClass('modal-open');}, 200);

            } else {
                alert("Resource Import Successful");
                $('#table_bind').html('');
                $("#excelmodal").modal('hide');
                location.reload();
            }

        },
        error: function (jqXHR, textStatus, errorThrown) {
            if (jqXHR.status == 400)
                alert(jqXHR.responseText);
            else
                alert("Request Failed");
        }
    });
}
function deleteRow(val){
    var rId = $(val).attr('id');
    rId = rId.split('_')[1];
    if (confirm('Do you want to Delete')) {
        $('#excelrowid_'+rId).remove();
    }
}

function sample1(val){
    var dt = parseInt($(val).data('rid'));
    if(dt==1) {
        if($('input[name=rdi]:checked').val() == 0) {
            $('.main').hide();
            $('#resourceentry_1').show();
            $('#resourceentry_2').hide();
        }else if($('input[name=rdi]:checked').val() == 1){
            $('.main').hide();
            $('#resourceentry_1').hide();
            $('#resourceentry_2').show();
        }
    }
}

$(function () {
    $('.carousel').carousel({
        interval: false
    });
});
function goBack(index) {
    $('#nextBtn').html('Next <i class="fa fa-arrow-right"></i>');
    getValueOfSlider('prev');
    if(typeof index != 'undefined'){
        $('#carousel-example-generic').carousel(index);
        $("#nextBtn").show();
        $("#backPrev").hide();
    } else {
        $('#carousel-example-generic').carousel({
            slide: "prev"
        });

    }
}

function getValueOfSlider(slType) {
    var curIndex = $('#carousel-example-generic .item.active').index();
    if(slType == 'next') {
        $("#backPrev").show();
    }
    if(curIndex == 1 && slType == 'prev') {
        $("#backPrev").hide();
    } else {
        $("#backPrev").show();
        $("#nextBtn").hide();
    }
}

function validateStg() {
    $('.error_message').hide();
    var currentIndex = $('#carousel-example-generic .item.active').index();
    switch (currentIndex) {
        case 0:
            var $type = $('input[type=radio][name=rdio]:checked');
            if($type.length==0){
                alert('Choose Any Option to Continue');
                return;
            }
            getValueOfSlider('next');
            $('#carousel-example-generic').carousel(parseInt($type.val()));
            break;
        case 1:
            getValueOfSlider('prev');
            $('#carousel-example-generic').carousel(0);
            break;
    }
}

$("#continue1").click(function(){
    validation(1);
    $('#forSingle').submit();
});

$("#continue").click(function(){
    validation(2);
    $('#forSingle').submit();
});
$("#submit1").click(function(){
    multiValidate(1);
    //$('#forSingle').submit();
});

$("#submit").click(function(){
    multiValidate(2);
   // $('#forSingle').submit();

});
removetr();
function deleteRow(x,e) {
    e.preventDefault();
    var $x = $(x),
        key = $x[0].className.split('_')[1];
    if (confirm('Do you want to Delete')) {
        removetr();
    }
}

function removetr(){
    $('.remove').click(function(){
        if($(this).closest('tr').parent().find('tr').length != 1){
            $(this).closest('tr').remove();
            $('#documentTable tbody tr').each(function(){
                var index=$(this).index() + 1;
                $(this).find('select, input:text').each(function(){
                    $(this).attr('name', $(this).attr('tagname')+'_'+index);
                    $(this).attr('id', $(this).attr('tagname')+'_'+index);
                })
            });
        } else {
            $('.delFirst').val('');
        }
    });
}
addRow();
function addRow(){
    $( ".newRow" ).unbind();
    $( ".newRow" ).bind('keyup', function() {

        $('#itemcode_').attr("disabled",false);
        $('#rate_').attr("disabled",false);

        if($(this).val().length>0 && $(this).closest("tr").index() == $("#resourcelist tbody tr:last").index()){
            $("#resourcelist tbody").append("<tr>"+$("#resourcelist tbody tr:first").html()+"</tr>");
            $("#resourcelist tbody tr").each(function(){
                var index=$(this).index() + 1;
                var lastIndex=$("#resourcelist tbody tr:last").index() + 1;
                $(this).find("select, input:text").each(function(){
                    if(index==lastIndex){
                        var unitid = $("#unitname_").val();
                        if($(this).prop("tagName").toLowerCase() == 'input')
                            $(this).val("");
                        else
                            $(this).val(unitid);
                    }
                    $(this).attr("name", $(this).attr("tagname")+'_'+index);
                    $(this).attr("id", $(this).attr("tagname")+'_'+index);
                    $("#RowCount1").val(index);
                    $("#resourcelist tbody tr:last").find('.del').hide();
                })
            });
            removetr();
            addRow();
        }
    });
}
function validation(type){
    var resId = $('#cboResource').val();
    var txtItemName = $('#txtItemName').val();
    var txtItemCode = $('#txtItemCode').val();
    var txtRate = $('#txtRate').val();
    var cboUnit = $('#cboUnit').val();
    $("#type").val(type);

    if(resId == 0 || resId==""){
        $('#cboResource').closest('.form-group').find('.error_message').show();
        $('#cboResource').focus();
        errorFlag = 1;
        return false;
    } else {
        $('#cboResource').closest('.form-group').find('.error_message').hide();
    }
    if(txtItemName == 0 || txtItemName==""){
        $('#txtItemName').closest('.form-group').find('.error_message').show();
        $('#txtItemName').focus();
        errorFlag = 1;
        return false;
    } else {
        $('#txtItemName').closest('.form-group').find('.error_message').hide();
    }
    if(txtItemCode == 0 || txtItemCode==""){
        $('#txtItemCode').closest('.form-group').find('.error_message').show();
        $('#txtItemCode').focus();
        errorFlag = 1;
        return false;
    } else {
        $('#txtItemCode').closest('.form-group').find('.error_message').hide();
    }
    if(txtRate == 0 || txtRate==""){
        $('#txtRate').closest('.form-group').find('.error_message').show();
        $('#txtRate').focus();
        errorFlag = 1;
        return false;
    } else {
        $('#txtRate').closest('.form-group').find('.error_message').hide();
    }
    if(errorFlag == 0 ){
        $('#forSingle').submit();
    }
}
function btotal(){
    var length = parseFloatVal($("#Length").val());
    var breadth = parseFloatVal($("#Breadth").val());
    var depth = parseFloatVal($("#Depth").val());
    var tot = parseFloatVal(length * breadth * depth);
    $("#total").val(sanitizeNumber(tot,3,true));
}
function mulTotal(x){
    var $x = $(x);
    var ids = $x[0].id.split('_');
    var rId = ids[1];

    var length = parseFloatVal($('#length_' + rId ).val());
    var breadth = parseFloatVal($('#breadth_' + rId).val());
    var depth = parseFloatVal($('#depth_' + rId).val());

   var tot = parseFloatVal(length * breadth * depth);
   $('#total_'+ rId).val(sanitizeNumber(tot,3,true));
}

function multiValidate(type) {
    var res = $('#cboResource1').val();
    var error1 = 0;
    $("#type").val(type);
    if(res == 0 || res==""){
        $('#cboResource1').closest('.form-group').find('.error_message').show();
        $('#cboResource1').focus();
        error1 = 1;
        return false;
    } else {
        $('#cboResource1').closest('.form-group').find('.error_message').hide();
    }
    if(($('#itemname_').val() == '')){
        alert("enter the itemname");
        error1 = 1;
    }
    var rId = parseInt($('#RowCount1').val()-1);
    if(rId > 0){
        for(var k = 1; k <= rId ; k++ ){
           if(($('#itemname_' + k).val() != '') && ($('#itemcode_' + k).val() == 0 || '')){
                showError($('#itemcode_' + k),"enter the itemcode");
               error1 = 1;
               return false;
            } else {
               removeError($('#itemcode_' + k));
               error1 = 0;
            }
            if(($('#itemname_' + k).val() != '') && ($('#rate_' + k).val() == 0 || '')){
                showError($('#rate_' + k),"enter the rate");
                error1 = 1;
                return false;
            } else {
                removeError($('#rate_' + k));
                error1 = 0;
            }
        }
    }
    if(error1 == 0 ){
       $('#forSingle').submit();
    }
}
$(function(){
    $('#cboResource').change(function(){
        $('.tab').show();
        var selected = $(this).find('option:selected');
        var measure = selected.data('measure');
        var value = selected.data('value');
        $('.det').html('');
        $('#cboUnit').val('');
        $.ajax({
            url:getBaseURL()+"mms/master/resource-item",
            type:"post",
            data:{'resourceId':value},
            success:function(data,textStatus,jqXHR){
                var data = JSON.parse(data);
				data1 = data['result'];
				sCode = data['sCode'];
				CodeType = data['CodeType'];

                if(data1.UnitId != 0 && data1.MaterialType != "O"){
                    var toAppend = '<option value="' + data1.UnitId + '" selected="selected">' + data1.UnitName + '</option>';
                    $('#cboUnit').append(toAppend);
                    $('#cboUnit').prop("disabled",false);
                    $('#cboUnit').trigger('change');
                } else {
                    var toAppend = '<option value="' + data1.UnitId + '" selected="selected">' + data1.UnitName + '</option>';
                    $('#cboUnit').append(toAppend);
                    $('#cboUnit').prop("disabled",true);
                    $('#cboUnit').trigger('change');
                }
                $("#material").append(data1.MeasureType);
                $("#group").append(data1.ResourceGroupName);
                $("#code").append(data1.Code);
                $("#unit").append(data1.UnitName);
                $("#baserate").append(data1.Rate);
                $("#txtItemCode").val(sCode);
				if(CodeType == 1){
					$('#txtItemCode').prop("readonly",true);
				}
                // $("#qrate").append(data.Code);
            }
        });
        if(measure =="L"){
            $('#measurement').show();
        } else {
            $('#measurement').hide();
        }
    });
});
$(function(){
    $('#cboResource1').change(function(){
        var selected = $(this).find('option:selected');
        var measure = selected.data('measure');
        var value = selected.data('value');
        $('.det').html('');
        var rule = 0;
        var checkFlag = 0;

        var at='';
        $.ajax({
            url:getBaseURL()+"mms/master/resource-item",
            type:"post",
            data:{'resourceId':value},
            success:function(data,textStatus,jqXHR){
                var data = JSON.parse(data);

                at = '<tr> <td width="15%" class="tbl_input_td"> ' +
                    '<input type="text" class="tbl_input delFirst newRow" tagname="itemname"  name="itemname_"  id="itemname_" value="" disabled /> ' +
                    '</td> ' +
                    '<td width="13%" class="tbl_input_td"><input type="text" class="tbl_input delFirst"  tagname="itemcode" name="itemcode_" id="itemcode_" disabled /></td> ' +
                    '<td width="13%" class="tbl_input_td"><input type="text" class="tbl_input delFirst forDel"  tagname="rate" name="rate_" id="rate_" onkeypress="return isNumberKey(event);" disabled /></td> ' +
                    '<td width="13%"  class="nr"> ' +
                    '<div class="vendor_button ch1"> ' +
                    '<select name="unitname_" id="unitname_" label="Select Unit" tagname="unitname" disabled /> ' +
                    '<option value="0"></option> ' ;
                <?php foreach($unitList as $unit):?>
                at += '<option value="<?php echo $unit['value']; ?>" ><?php echo $unit['data']; ?></option>';
                <?php endforeach;?>
                at += '</select> </div> </td> <td width="13%" class="tbl_input_td"><input type="text" class="tbl_input delFirst"  tagname="length" onchange="mulTotal(this);"  name="length_" id="length_"  />' +
                '</td> ' +
                '<td width="13%" class="tbl_input_td"><input type="text" class="tbl_input delFirst" tagname="breadth"  onchange="mulTotal(this);" name="breadth_" id="breadth_" >' +
                '</td> ' +
                '<td width="13%" class="tbl_input_td"><input type="text" class="tbl_input delFirst" tagname="depth"  onchange="mulTotal(this);" name="depth_" id="depth_" >' +
                '</td> ' +
                '<td width="16%" class="tbl_input_td"><input type="text" class="tbl_input delFirst" tagname="total" name="total_" disabled id="total_" >' +
                '</td> ' +
                '<td  class="del" style="display:none;"><a href="#" class="remove" id="remove_" onclick="deleteRow(this, event);"  ><span class="glyphicon glyphicon-trash" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></span></a>' +
                '</td> </tr> ';

                var check1 =  $('#resourcelist tbody tr').length;

                if(check1 == 0){
                    checkFlag = 2;
                } else if (check1 != '' || check1 > 0){
                    var items = $('#itemname_').val();
                    if( items == ''){
                        $('#resourcelist tbody').html(at);
                        addRow();
                    } else {
                        if(!confirm('All entered details will be delete!!!!' +
                            'Do you want to Change the ResourceName?'))
                            return false;
                        $('#resourcelist tbody').html('');
                        checkFlag = 2;
                    }
                } else {
                    checkFlag = 2;
                }

                if(checkFlag == 2) {
                    $('#resourcelist tbody').html(at);
                    addRow();
                }
                if(data.UnitId != 0 && data.MaterialType != "O"){
                    var toAppend = '<option value="' + data.UnitId + '" selected="selected">' + data.UnitName + '</option>';
                   // $('select, input:text').val("");
                    $("#unitname_").append(toAppend);
                    $('#unitname_').trigger('change');
                    $('#unitname_').prop("disabled",false);
                } else {
                    var toAppend = '<option value="' + data.UnitId + '" selected="selected">' + data.UnitName + '</option>';
                    $('#unitname_').append(toAppend);
                    $('#unitname_').trigger('change');
                    $('#unitname_').prop("disabled",true);
                }
                $("#material1").append(data.MeasureType);
                $("#group1").append(data.ResourceGroupName);
                $("#code1").append(data.Code);
                $("#unit1").append(data.UnitName);
                $("#baserate1").append(data.Rate);
                if(value !="") {
                    $('#itemname_').attr("disabled",false);
                }
                if(measure !="L"){
                    $('#length_').prop("disabled",true);
                    $('#breadth_').prop("disabled",true);
                    $('#depth_').prop("disabled",true);
                }
            }
        });

    });
    $(document).on('change','.forDel',function(){
        if($(this).val() != ''){
            $(this).parent().parent().find('.del').show();

        } else {
            $(this).parent().parent().find('.del').hide();
        }
    });
});
</script>