<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/mms.css';?>"/>
<style type="text/css">
	.content_wrapper{min-height:515px !important;}
</style>
<div class="content_wrapper">
	<div class="container-fluid">
		<div class="row">
			<div id="divnewpagetittle" >
				<h1 class="text-center">Project Setup </h1>
			</div>
			<form id="formSubmit" action="" method="post">
				<div class="col-lg-12 top_ct zoomIn animated" id="MainWrapper">
					<div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 prt-next">
						<div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 top-next">
							<div class="col-lg-12 frmwrk_div req_flds" id="projects_list">
								<select name="project_idNew" id="project_selectNew" label="Select Project" class="form-control single_dropdown lbl_move" data-size="6" title="Select Project..." style="width:100%;" onchange="showOptions2(this)">
									<option value="">Select Project</option>
									<?php if(isset($projectlists)):?>
										<?php foreach ( $projectlists as $project ):?>
											<option value="<?php echo $project[ 'CostCentreId' ];?>"><?php echo $project[ 'CostCentreName' ];?></option>
										<?php endforeach; ?>
									<?php  endif; ?>
								</select>
								<div class="error_message"><p>Please Select the project..</p></div>
							</div>
							<div class="savebtn_areas col-lg-8 col-sm-7 col-sm-offset-3 col-xs-offset-4 col-lg-offset-3">
								<ul>
									<li class="subs"><a onclick="submitForm()" href="javascript:void(0);" id="continue">Next</a></li>
								</ul>
							</div>
						
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
<script>
function showOptions2(s){
 var adVALUE =s[s.selectedIndex].value; 
 $('#continue').attr('href',"<?php echo $this->basePath(); ?>/mms/master/opening-stock/"+adVALUE);
}
function submitForm() {
	$('.error_message').hide();
	if ($('#project_selectNew').val() == '') { 	
		$('#project_selectNew').closest('.req_flds').find('.error_message').show();
		return false;
	}
}
</script>
