<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/wpm.css';?>"/>
<style>
    .mar_30{margin-top:30px;}
    .jqx-widget-content {z-index:999 !important;}

    ul,li{list-style:none;}
    /*-----------------------inner module tab-----------------*/
    .innermdl_tabs												{background-color:#e7e9ec; border-bottom:1px solid #2d74b4 !important;border:0px;}
    .innermdl_tabs li											{margin:0px !important;width:16%!important;}
    .innermdl_tabs li a											{color:#212121;text-align:center;padding:10px 22px 8px 22px; font-size:13px; font-weight:600;display:block;border-radius: 0px;margin:0px;border-bottom:3px solid #e7e9ec;border-top:0px !important; border-right:0px !important;border-left:0px !important;}
    .innermdl_tabs li a:after									{content:''; width:1px; height:20px; background-color:#bccae7; position:absolute; right:0px;}
    .innermdl_tabs li:last-child a:after						{content:''; width:0px;}
    .innermdl_tabs li ul li a									{text-align:left;font-size:13px;border-bottom:0px !important;}
    .innermdl_tabs li ul li a:after								{background:none !important;}
    .innermdl_tabs>li>a:hover,.innermdl_tabs>li.active>a,.innermdl_tabs>li.active>a:focus,.innermdl_tabs>li.active>a:hover{background-color:#e1e3e7 !important;color:#3f6ac3;font-weight:600;border-bottom:3px solid #2d74b4 !important;border-top:0px !important; border-right:0px !important;border-left:0px !important;}
    .innermdl_tabs li a span									{color:#3f6ac3;padding:0px 10px 0px 0px;}

    /*---------------------Responsive css---------------------*/
    @media screen and (max-width:1280px)						         {
    }
    @media only screen and (min-width : 769px) and (max-width : 800px) {
    }
    @media screen and (min-width : 361px) and (max-width : 768px){
        .innermdl_tabs li				{margin:0px !important;width:100%!important;}
    }
    @media only screen and (min-width : 321px) and (max-width : 360px)	{
        .innermdl_tabs li				{margin:0px !important; width:100%!important;}
    }
    @media only screen and (width : 320px)  {
        .innermdl_tabs li				{ margin:0px !important;width:100%!important;}
    }
    @media only screen and (width : 480px)  {
        .innermdl_tabs li				{margin:0px !important; width:100%!important;}
    }
    @media only screen and (width : 640px)  {
        .innermdl_tabs li				{ margin:0px !important;}
    }
    @media only screen and (min-width : 320px) and (max-width : 1199px) 		{
        .innermdl_tabs li				{margin:0px !important;margin:0px !important;}
    }
    @media only screen and (min-width : 981px) and (max-width : 1024px) {
    }
	.innermdl_tabs li {margin: 0px !important;width: 20%!important;}
</style>
<!--<div class="content_wrapper padlr0">-->
<!--<div class="container-fluid">-->
<!--<div class="row">-->
<!---->
<!--<div class="clearfix"></div>-->
<div class="col-lg-12 padlr0" style="z-index: 999!important;">
    <nav class="navbar inrmdltab_navbar navbar-default">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle mdlnvbr_tgl collapsed ripple" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand inrmdl_navbrand ripple" href="javascript:void(0);">Select Menus</a>
        </div>
        <div id="navbar1" class="navbar-collapse padlr0 collapse">
            <ul class="nav nav-tabs innermdl_tabs">
                <li id="dbtab" class="active"><a href="#dbreak" class="ripple" data-toggle="tab">Day-Wise BreakUp</a></li>
            </ul>
        </div>
    </nav>
</div>

<div class="tab-content">
    <div class="tab-pane active" id="dts">
        <div class="col-lg-12 clear padlr0">
            <div class="table-responsive clear">
                <div style='margin-top:10px;' id="grddaybreak"> </div>
            </div>
        </div>
    </div>
</div>
<!--</div>-->
<!--</div>-->
<!--</div>-->
<script type="text/javascript">
var arr_Lists = <?php echo (isset($dbreak)) ? json_encode($dbreak) : '[]';?>;
$(document).ready(function () {

    // details grid start
    var source = {
        localdata: arr_Lists,
        datatype: "json",
        pagesize:6,
        datafields:
            [
                { name: "ResourceId", type: "string" },
                { name: "ItemId", type: "string" },
                { name: "CostCentreId", type: "string" },
                { name: "Month", type: "string" },
                { name: "CDate", type: "string"},
                { name: "CDay", type: "number" },
                { name: "MRank", type: "number" },
                { name: "Op.Balance", type: "number" },
                { name: "Receipt", type: "number" },
                { name: "BillReturn", type: "number" },
                { name: "Transfer", type: "number" },
                { name: "Issue/Return", type: "string" },
                { name: "Cl.Balance", type: "string" }
            ]
    };

    var dataAdapter = new $.jqx.dataAdapter(source);
    var qTot=0;
    var aTot=0;
    var rTot=0;
    var qTot1=0;
    var aTot1=0;
    var rTot1=0;


    $("#grddaybreak").jqxGrid(
        {
            width: "100%",
            source: dataAdapter,
            pageable: true,
            columnsresize: true,
            autoheight: true,
            sortable: true,
            altrows: true,
            enabletooltips: true,
            showfilterrow: true,
            filterable: true,
            groupable: true,
            showstatusbar: true,
            statusbarheight: 35,
            showaggregates: true,
            autorowheight: true,
            columns: [
                { text: 'ResourceId', dataField: 'ResourceId', hidden:true},
                { text: 'ItemId', dataField: 'ItemId', hidden:true},
                { text: 'CostCentreId', dataField: 'CostCentreId', hidden:true},
                { text: 'Month', dataField: 'Month', hidden:true},
                { text: 'CDate', dataField: 'CDate', hidden:true},
                { text: 'MRank', dataField: 'MRank', hidden:true},
                { text: 'CDay', dataField: 'CDay', align: 'left', cellsalign: 'left',width:'10%'},
                { text: 'Op.Balance', dataField: 'Op.Balance', align: 'center', cellsalign: 'right',width:'15%',cellsformat: 'F3'},
                { text: 'Receipt', dataField: 'Receipt', align: 'center', cellsalign: 'right',width:'15%',cellsformat: 'F3'},
                { text: 'Bill Return', dataField: 'BillReturn', align: 'center', cellsalign: 'right',width:'15%',cellsformat: 'F3'},
                { text: 'Transfer', dataField: 'Transfer', align: 'center', cellsalign: 'right',width:'15%',cellsformat: 'F3'},
                { text: 'Issue/Return', dataField: 'Issue/Return', align: 'center', cellsalign: 'right',width:'15%',cellsformat: 'F3'},
                { text: 'Cl.Balance', dataField: 'Cl.Balance', align: 'center', cellsalign: 'right',width:'15%',cellsformat: 'F3'}
            ]
        });
    $("#grddaybreak").jqxGrid('showgroupsheader', false);
    //Print option
    $("#excelExport").click(function () {
        $("#grddaybreak").jqxGrid('exportdata', 'xls', 'jqxGrid');
    });
    $("#csvExport").click(function () {
        $("#grddaybreak").jqxGrid('exportdata', 'csv', 'jqxGrid');
    });
    $("#htmlExport").click(function () {
        $("#grddaybreak").jqxGrid('exportdata', 'html', 'jqxGrid');
    });

    $("#print").click(function () {
        var gridContent = $("#grddaybreak").jqxGrid('exportdata', 'html');
        //var gridContent = $("#jqxgrid").jqxGrid('exportdata', 'html', 'jqxGrid', true, null, false);
        var newWindow = window.open('', '', 'width=800, height=500'),
            document = newWindow.document.open(),
            pageContent =
                '<!DOCTYPE html>\n' +
                '<html>\n' +
                '<head>\n' +
                '<meta charset="utf-8" />\n' +
                '<title>Stock Details</title>\n' +
                '<h1>Stock Details</h1>\n' +
                '</head>\n' +
                '<body>\n' + gridContent + '\n</body>\n</html>';
        document.write(pageContent);
        document.close();
        newWindow.print();

    });

    $("#grddaybreak").bind('rowselect', function (event) {
        var row = event.args.rowindex;
        var datarow = $("#grddaybreak").jqxGrid('getrowdata', row);

    });
    //details grid end
});




</script>