<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/css/project.css" />
<style type="text/css">
.table-responsive table.table tr td.td_prnt_text	{padding:4px 0px !important; border-top:0px !important;}
.td_prnt_text .action_btns li a						{padding-top:3px;}
</style>
<div class="content_wrapper padlr0">
	<div class="container-fluid padlr0">
		<div class="col-lg-12">
			<h1>Project Kickoff</h1>
		</div>
		<form onsubmit="return entryValidate()" method="post" id="formWrapper">
			<div class="col-lg-12 flwup_topcnt fmg_topcnt clear">
				<div class="col-lg-3 form-group">
					<span class="date_icon"><i class="fa fa-calendar"></i></span>
					<input type="text" name="refDate" id="refDate" class="form-control date_picker lbl_move" value="<?php echo date("d-m-Y", strtotime($kickoffRes['RefDate'])); ?>" label="Ref Date" onkeypress="return isDate(event);" />
				</div>
				<div class="col-lg-3 form-group">
					<input type="text" name="refNo" id="refNo" class="form-control lbl_move" value="<?php echo $kickoffRes['RefNo']; ?>" label="Ref No" />
				</div>
				<div class="col-lg-6 form-group">
					<input type="text" name="propertyName" id="propertyName" class="form-control lbl_move" value="<?php echo $kickoffRes['ProjectName']; ?>" label="Name of the Property" />
				</div>
			</div>
			<div class="col-lg-12 clear">
				<ul class="breadcrumb_area">
					<li><a href="<?php echo $this->basePath(); ?>/kickoff/index/conception/<?php if ($kickoffId != 0) { echo $kickoffId; } else { echo ''; } ?>">Conception</a></li>
					<li><a href="<?php echo $this->basePath().$unitUrl; ?>">Unit</a></li>
<!--					<li><a href="--><?php //echo $this->basePath(); ?><!--/kickoff/index/wbs/--><?php //if ($kickoffId != 0) { echo $kickoffId; } else { echo ''; } ?><!--">WBS</a></li>-->
					<li><a href="<?php echo $this->basePath(); ?>/kickoff/index/turnaround/<?php if ($kickoffId != 0) { echo $kickoffId; } else { echo ''; } ?>">Turnaround Cost & Schedule</a></li>
					<li><a href="<?php echo $this->basePath(); ?>/kickoff/index/team/<?php if ($kickoffId != 0) { echo $kickoffId; } else { echo ''; } ?>">Team</a></li>
					<li><a href="#" class="active">Critical Area</a></li>
					<li><a href="<?php echo $this->basePath(); ?>/kickoff/index/make-brand/<?php if ($kickoffId != 0) { echo $kickoffId; } else { echo ''; } ?>">Make/Brand</a></li>
					<li><a href="<?php echo $this->basePath(); ?>/kickoff/index/documents/<?php if ($kickoffId != 0) { echo $kickoffId; } else { echo ''; } ?>">Documents</a></li>
					<li><a href="<?php echo $this->basePath(); ?>/kickoff/index/setup/<?php if ($kickoffId != 0) { echo $kickoffId; } else { echo ''; } ?>">Setup</a></li>
				</ul>
			</div>
			<div class="col-lg-12 clear">
				<div class="col-lg-12 clear">
					<div class="kickoff_area col-lg-12 clear">
						<div class="col-lg-12 padlr0">
							<div class="col-lg-4 col-md-4 col-sm-12">
								<div class="col-lg-12 padlr0">
									<h1>Check List</h1>
									<input type="hidden" name="kickOffId" id="kickOffId" value="<?php if ($kickoffId != 0) { echo $kickoffId; } else { echo ''; } ?>" />
									<input type="hidden" name="criticalAreaId" id="criticalAreaId" value="<?php if ($kfCriticalAreaId != 0) { echo $kfCriticalAreaId; } else { echo ''; } ?>" />
									<div class="radio_check dpblk_rdock m_btm20">
										<p>
											<input type="checkbox" id="criticalWorks" name="criticalWorks" value="1" <?php echo (isset($kfCriticalArea) && $kfCriticalArea['CriticalWorks'] == '1') ? 'checked' : ''; ?> />
											<label for="criticalWorks" class="ripple">Critical Works Identified</label>
										</p>
										<p>
											<input type="checkbox" id="criticalResource" name="criticalResource" value="1" <?php echo (isset($kfCriticalArea) && $kfCriticalArea['CriticalResource'] == '1') ? 'checked' : ''; ?> />
											<label for="criticalResource" class="ripple">Critical Resource Identified</label>
										</p>
										<p>
											<input type="checkbox" id="criticalMachinery" name="criticalMachinery" value="1" <?php echo (isset($kfCriticalArea) && $kfCriticalArea['CriticalMachinery'] == '1') ? 'checked' : ''; ?> />
											<label for="criticalMachinery" class="ripple">Critical Machinery Identified</label>
										</p>
										<p>
											<input type="checkbox" id="labourShed" name="labourShed" value="1" <?php echo (isset($kfCriticalArea) && $kfCriticalArea['LabourShed'] == '1') ? 'checked' : ''; ?> />
											<label for="labourShed" class="ripple">Labour Shed Identified</label>
										</p>
										<p>
											<input type="checkbox" id="siteOffice" name="siteOffice" value="1" <?php echo (isset($kfCriticalArea) && $kfCriticalArea['SiteOffice'] == '1') ? 'checked' : ''; ?> />
											<label for="siteOffice" class="ripple">Site Office Identified</label>
										</p>
										<p>
											<input type="checkbox" id="materialStorage" name="materialStorage" value="1" <?php echo (isset($kfCriticalArea) && $kfCriticalArea['MaterialStorage'] == '1') ? 'checked' : ''; ?> />
											<label for="materialStorage" class="ripple">Material Storage Place Identified</label>
										</p>
										<p>
											<input type="checkbox" id="machineryInstallation" name="machineryInstallation" value="1" <?php echo (isset($kfCriticalArea) && $kfCriticalArea['MachineryInstallation'] == '1') ? 'checked' : ''; ?> />
											<label for="machineryInstallation" class="ripple">Machinery Installation Area Identified</label>
										</p>
										<p>
											<input type="checkbox" id="labourLicence" name="labourLicence" value="1" <?php echo (isset($kfCriticalArea) && $kfCriticalArea['LabourLicence'] == '1') ? 'checked' : ''; ?> />
											<label for="labourLicence" class="ripple">Labour Licence Received</label>
										</p>
									</div>
								</div>
							</div>
							<div class="col-lg-8 col-md-8 col-sm-12">
								<div class="col-lg-12 list-div">
									<div class="col-lg-6 col-md-6">
										<h1>Critical Works</h1>
										<div class="table-responsive">
											<table class="table">
												<tbody>
													<?php
													if(isset($kfCriticalAreaWork) && count($kfCriticalAreaWork) != 0) {
														$i = 1;
														foreach($kfCriticalAreaWork as $caWork) { ?>
													<tr>
														<td class="td_prnt_text"><input class="parent_text" type="text" id="workSpec_<?php echo $i; ?>" name="workSpec_<?php echo $i; ?>" placeholder="Work Specification" onblur="addWorkSpecRow(this)" value="<?php echo $caWork['SpecificationName']; ?>" /></td>
														<td width="1%" class="action_btns_td td_prnt_text">
															<ul class="action_btns">
																<li>
																	<a class="workSpecDelete_<?php echo $i; ?>" href="#" onclick="deleteWorkSpec(this, event);">
																		<span data-toggle="tooltip" data-placement="left" data-original-title="Delete"><i class="fa fa-trash-o"></i></span>
																	</a>
																</li>
															</ul>
														</td>
													</tr>
													<?php $i++;
														}
													} else { ?>
													<tr>
														<td class="td_prnt_text"><input class="parent_text" type="text" id="workSpec_1" name="workSpec_1" placeholder="Work Specification" onchange="addWorkSpecRow(this)" /></td>
														<td width="1%" class="action_btns_td td_prnt_text">
															<ul class="action_btns">
																<li>
																	<a class="workSpecDelete_1" href="#" onclick="deleteWorkSpec(this, event);" style="display: none;">
																		<span data-toggle="tooltip" data-placement="left" data-original-title="Delete"><i class="fa fa-trash-o"></i></span>
																	</a>
																</li>
															</ul>
														</td>
													</tr>
													<?php } ?>
												</tbody>
											</table>
											<input type="hidden" name="workspecrowid" id="workspecrowid" value="<?php echo (isset($kfCriticalAreaWork) && count($kfCriticalAreaWork) != 0) ? count($kfCriticalAreaWork) : 1; ?>" />
										</div>
									</div>
									<div class="col-lg-6 col-md-6">
										<h1>Critical Machinery</h1>
										<div class="table-responsive">
											<table class="table">
												<tbody>
													<?php
													if(isset($kfCriticalAreaMachinery) && count($kfCriticalAreaMachinery) != 0) {
														$i = 1;
														foreach($kfCriticalAreaMachinery as $caMachinery) { ?>
													<tr>
														<td class="td_prnt_text"><input class="parent_text" type="text" id="machinery_<?php echo $i; ?>" name="machinery_<?php echo $i; ?>" placeholder="Machinery" onblur="addMachineryRow(this)" value="<?php echo $caMachinery['MachineryName']; ?>" /></td>
														<td width="1%" class="action_btns_td td_prnt_text">
															<ul class="action_btns">
																<li>
																	<a class="machineryDelete_<?php echo $i; ?>" href="#" onclick="deleteMachinery(this, event);">
																		<span data-toggle="tooltip" data-placement="left" data-original-title="Delete"><i class="fa fa-trash-o"></i></span>
																	</a>
																</li>
															</ul>
														</td>
													</tr>
													<?php $i++;
														}
													} else { ?>
													<tr>
														<td class="td_prnt_text"><input class="parent_text" type="text" id="machinery_1" name="machinery_1" placeholder="Machinery" onchange="addMachineryRow(this)" /></td>
														<td width="1%" class="action_btns_td td_prnt_text">
															<ul class="action_btns">
																<li>
																	<a class="machineryDelete_1" href="#" onclick="deleteMachinery(this, event);" style="display: none;">
																		<span data-toggle="tooltip" data-placement="left" data-original-title="Delete"><i class="fa fa-trash-o"></i></span>
																	</a>
																</li>
															</ul>
														</td>
													</tr>
													<?php } ?>
												</tbody>
											</table>
											<input type="hidden" name="machineryrowid" id="machineryrowid" value="<?php echo (isset($kfCriticalAreaMachinery) && count($kfCriticalAreaMachinery) != 0) ? count($kfCriticalAreaMachinery) : 1; ?>" />
										</div>
									</div>
								</div>
								<div class="col-lg-12 list-div">
									<div class="col-lg-6 col-md-6">
										<h1>Critical Resource</h1>
										<div class="table-responsive">
											<table class="table">
												<tbody>
													<?php
													if(isset($kfCriticalAreaResource) && count($kfCriticalAreaResource) != 0) {
														$i = 1;
														foreach($kfCriticalAreaResource as $caResource) { ?>
													<tr>
														<td class="td_prnt_text"><input class="parent_text" type="text" id="resource_<?php echo $i; ?>" name="resource_<?php echo $i; ?>" placeholder="Resource" onblur="addResourceRow(this)" value="<?php echo $caResource['ResourceName']; ?>" /></td>
														<td width="1%" class="action_btns_td td_prnt_text">
															<ul class="action_btns">
																<li>
																	<a class="resourceDelete_<?php echo $i; ?>" href="#" onclick="deleteResource(this, event);">
																		<span data-toggle="tooltip" data-placement="left" data-original-title="Delete"><i class="fa fa-trash-o"></i></span>
																	</a>
																</li>
															</ul>
														</td>
													</tr>
													<?php $i++;
														}
													} else { ?>
													<tr>
														<td class="td_prnt_text"><input class="parent_text" type="text" id="resource_1" name="resource_1" placeholder="Resource" onchange="addResourceRow(this)" /></td>
														<td width="1%" class="action_btns_td td_prnt_text">
															<ul class="action_btns">
																<li>
																	<a class="resourceDelete_1" href="#" onclick="deleteResource(this, event);" style="display: none;">
																		<span data-toggle="tooltip" data-placement="left" data-original-title="Delete"><i class="fa fa-trash-o"></i></span>
																	</a>
																</li>
															</ul>
														</td>
													</tr>
													<?php } ?>
												</tbody>
											</table>
											<input type="hidden" name="resourcerowid" id="resourcerowid" value="<?php echo (isset($kfCriticalAreaResource) && count($kfCriticalAreaResource) != 0) ? count($kfCriticalAreaResource) : 1; ?>" />
										</div>
									</div>
									<div class="col-lg-6 col-md-6">
										<h1>General Notes</h1>
										<div class="table-responsive">
											<table class="table">
												<tbody>
													<?php
													if(isset($kfCriticalAreaNotes) && count($kfCriticalAreaNotes) != 0) {
														$i = 1;
														foreach($kfCriticalAreaNotes as $caNotes) { ?>
													<tr>
														<td class="td_prnt_text"><input class="parent_text" type="text" id="notes_<?php echo $i; ?>" name="notes_<?php echo $i; ?>" placeholder="Notes" onblur="addNotesRow(this)" value="<?php echo $caNotes['Notes']; ?>" /></td>
														<td width="1%" class="action_btns_td td_prnt_text">
															<ul class="action_btns">
																<li>
																	<a class="notesDelete_<?php echo $i; ?>" href="#" onclick="deleteNotes(this, event);">
																		<span data-toggle="tooltip" data-placement="left" data-original-title="Delete"><i class="fa fa-trash-o"></i></span>
																	</a>
																</li>
															</ul>
														</td>
													</tr>
													<?php $i++;
														}
													} else { ?>
													<tr>
														<td class="td_prnt_text"><input class="parent_text" type="text" id="notes_1" name="notes_1" placeholder="Notes" onchange="addNotesRow(this)" /></td>
														<td width="1%" class="action_btns_td td_prnt_text">
															<ul class="action_btns">
																<li>
																	<a class="notesDelete_1" href="#" onclick="deleteNotes(this, event);" style="display: none;">
																		<span data-toggle="tooltip" data-placement="left" data-original-title="Delete"><i class="fa fa-trash-o"></i></span>
																	</a>
																</li>
															</ul>
														</td>
													</tr>
													<?php } ?>
												</tbody>
											</table>
											<input type="hidden" name="notesrowid" id="notesrowid" value="<?php echo (isset($kfCriticalAreaNotes) && count($kfCriticalAreaNotes) != 0) ? count($kfCriticalAreaNotes) : 1; ?>" />
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="cont_bt-list">
							<ul>
								<li><a href="<?php echo $this->basePath(); ?>/kickoff/index/team/<?php if ($kickoffId != 0) { echo $kickoffId; } else { echo ''; } ?>" class="steps_btn"><i class="fa fa-chevron-circle-left"></i> Back</a></li>
								<li><a href="javascript:submitForm();" class="cbtn">Continue <i class="fa fa-check-circle"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>

<!--Dummy Tables-->
<table id="dummy-workspec" style="display: none;">
	<tbody>
		<tr>
			<td class="td_prnt_text"><input class="parent_text" type="text" id="workSpec__1" name="workSpec__1" placeholder="Work Specification" onchange="addWorkSpecRow(this)" /></td>
			<td width="1%" class="action_btns_td td_prnt_text">
				<ul class="action_btns">
					<li>
						<a class="workSpecDelete__1" href="#" onclick="deleteWorkSpec(this, event);" style="display: none;">
							<span data-toggle="tooltip" data-placement="left" data-original-title="Delete"><i class="fa fa-trash-o"></i></span>
						</a>
					</li>
				</ul>
			</td>
		</tr>
	</tbody>
</table>

<table id="dummy-machinery" style="display: none;">
	<tbody>
		<tr>
			<td class="td_prnt_text"><input class="parent_text" type="text" id="machinery__1" name="machinery__1" placeholder="Machinery" onchange="addMachineryRow(this)" /></td>
			<td width="1%" class="action_btns_td td_prnt_text">
				<ul class="action_btns">
					<li>
						<a class="machineryDelete__1" href="#" onclick="deleteMachinery(this, event);" style="display: none;">
							<span data-toggle="tooltip" data-placement="left" data-original-title="Delete"><i class="fa fa-trash-o"></i></span>
						</a>
					</li>
				</ul>
			</td>
		</tr>
	</tbody>
</table>

<table id="dummy-resource" style="display: none;">
	<tbody>
		<tr>
			<td class="td_prnt_text"><input class="parent_text" type="text" id="resource__1" name="resource__1" placeholder="Resource" onchange="addResourceRow(this)" /></td>
			<td width="1%" class="action_btns_td td_prnt_text">
				<ul class="action_btns">
					<li>
						<a class="resourceDelete__1" href="#" onclick="deleteResource(this, event);" style="display: none;">
							<span data-toggle="tooltip" data-placement="left" data-original-title="Delete"><i class="fa fa-trash-o"></i></span>
						</a>
					</li>
				</ul>
			</td>
		</tr>
	</tbody>
</table>

<table id="dummy-notes" style="display: none;">
	<tbody>
		<tr>
			<td class="td_prnt_text"><input class="parent_text" type="text" id="notes__1" name="notes__1" placeholder="Notes" onchange="addNotesRow(this)" /></td>
			<td width="1%" class="action_btns_td td_prnt_text">
				<ul class="action_btns">
					<li>
						<a class="notesDelete__1" href="#" onclick="deleteNotes(this, event);" style="display: none;">
							<span data-toggle="tooltip" data-placement="left" data-original-title="Delete"><i class="fa fa-trash-o"></i></span>
						</a>
					</li>
				</ul>
			</td>
		</tr>
	</tbody>
</table>

<script type="text/javascript">
var workList = <?php echo (isset($kfCAWork)) ? json_encode($kfCAWork) : '[]'; ?>;
var machineryList = <?php echo (isset($kfCAMachinery)) ? json_encode($kfCAMachinery) : '[]'; ?>;
var resourceList = <?php echo (isset($kfCAResource)) ? json_encode($kfCAResource) : '[]'; ?>;
var notesList = <?php echo (isset($kfCANotes)) ? json_encode($kfCANotes) : '[]'; ?>;

bindWorkAutoComplete(1);
bindMachineryAutoComplete(1);
bindResourceAutoComplete(1);
bindNotesAutoComplete(1);

function addWorkSpecRow(x)
{
	var $x = $(x),
		$tr = $x.closest('tr'),
		key = $x[0].id.split('_')[1];
	
	if ($tr.next('tr').length != 0)
		return;
	
	if ($('#workSpec_' + key).val().length == 0)
		return;
	
	var $rowid = $('#workspecrowid'),
		count = parseInt($rowid.val()) + 1,
		template = $('#dummy-workspec tbody').html();
	
	template = template.replace(/__1/g, '_' + count);
	$tr.parent('tbody').append(template);
	$rowid.val(count);
	$('.workSpecDelete_' + key).show();
	bindWorkAutoComplete(count);
}

function deleteWorkSpec(x,e)
{
	e.preventDefault();
	if (!confirm('Do you want to Delete'))
		return false;
	
	var $tr = $(x).closest('tr'),
		$tbody = $tr.parent('tbody');
	
	if ($tbody.find('> tr').length == 1) {
		var template = $('#dummy-workspec tbody').html();
		template = template.replace(/__1/g, '_' + 1);
		$tbody.append(template);
		$('#workspecrowid').val(1);
	}
	
	$tr.next('tr.subTr').remove();
	$tr.remove();
	return false;
}
	
function addMachineryRow(x)
{
	var $x = $(x),
		$tr = $x.closest('tr'),
		key = $x[0].id.split('_')[1];
	
	if ($tr.next('tr').length != 0)
		return;
	
	if ($('#machinery_' + key).val().length == 0)
		return;
	
	var $rowid = $('#machineryrowid'),
		count = parseInt($rowid.val()) + 1,
		template = $('#dummy-machinery tbody').html();
	
	template = template.replace(/__1/g, '_' + count);
	$tr.parent('tbody').append(template);
	$rowid.val(count);
	$('.machineryDelete_' + key).show();
	bindMachineryAutoComplete(count);
}

function deleteMachinery(x,e)
{
	e.preventDefault();
	if (!confirm('Do you want to Delete'))
		return false;
	
	var $tr = $(x).closest('tr'),
		$tbody = $tr.parent('tbody');
	
	if ($tbody.find('> tr').length == 1) {
		var template = $('#dummy-machinery tbody').html();
		template = template.replace(/__1/g, '_' + 1);
		$tbody.append(template);
		$('#machineryrowid').val(1);
	}
	
	$tr.next('tr.subTr').remove();
	$tr.remove();
	return false;
}

function addResourceRow(x)
{
	var $x = $(x),
		$tr = $x.closest('tr'),
		key = $x[0].id.split('_')[1];
	
	if ($tr.next('tr').length != 0)
		return;
	
	if ($('#resource_' + key).val().length == 0)
		return;
	
	var $rowid = $('#resourcerowid'),
		count = parseInt($rowid.val()) + 1,
		template = $('#dummy-resource tbody').html();
	
	template = template.replace(/__1/g, '_' + count);
	$tr.parent('tbody').append(template);
	$rowid.val(count);
	$('.resourceDelete_' + key).show();
	bindResourceAutoComplete(count);
}

function deleteResource(x,e)
{
	e.preventDefault();
	if (!confirm('Do you want to Delete'))
		return false;
	
	var $tr = $(x).closest('tr'),
		$tbody = $tr.parent('tbody');
	
	if ($tbody.find('> tr').length == 1) {
		var template = $('#dummy-resource tbody').html();
		template = template.replace(/__1/g, '_' + 1);
		$tbody.append(template);
		$('#resourcerowid').val(1);
	}
	
	$tr.next('tr.subTr').remove();
	$tr.remove();
	return false;
}

function addNotesRow(x)
{
	var $x = $(x),
		$tr = $x.closest('tr'),
		key = $x[0].id.split('_')[1];
	
	if ($tr.next('tr').length != 0)
		return;
	
	if ($('#notes_' + key).val().length == 0)
		return;
	
	var $rowid = $('#notesrowid'),
		count = parseInt($rowid.val()) + 1,
		template = $('#dummy-notes tbody').html();
	
	template = template.replace(/__1/g, '_' + count);
	$tr.parent('tbody').append(template);
	$rowid.val(count);
	$('.notesDelete_' + key).show();
	bindNotesAutoComplete(count);
}

function deleteNotes(x,e)
{
	e.preventDefault();
	if (!confirm('Do you want to Delete'))
		return false;
	
	var $tr = $(x).closest('tr'),
		$tbody = $tr.parent('tbody');
	
	if ($tbody.find('> tr').length == 1) {
		var template = $('#dummy-notes tbody').html();
		template = template.replace(/__1/g, '_' + 1);
		$tbody.append(template);
		$('#notesrowid').val(1);
	}
	
	$tr.next('tr.subTr').remove();
	$tr.remove();
	return false;
}

function bindWorkAutoComplete(rowId)
{
	$('#workSpec_' + rowId).autocomplete({
		lookup: workList,
		showNoSuggestionNotice: false,
		lookupFilter: function (suggestion, originalQuery, queryLowerCase) {
			if (queryLowerCase == '*') {
				return suggestion.value;
			} else {
				var re = new RegExp($.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
				return re.test(suggestion.value);
			}
		}
	});
}

function bindMachineryAutoComplete(rowId)
{
	$('#machinery_' + rowId).autocomplete({
		lookup: machineryList,
		showNoSuggestionNotice: false,
		lookupFilter: function (suggestion, originalQuery, queryLowerCase) {
			if (queryLowerCase == '*') {
				return suggestion.value;
			} else {
				var re = new RegExp($.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
				return re.test(suggestion.value);
			}
		}
	});
}

function bindResourceAutoComplete(rowId)
{
	$('#resource_' + rowId).autocomplete({
		lookup: resourceList,
		showNoSuggestionNotice: false,
		lookupFilter: function (suggestion, originalQuery, queryLowerCase) {
			if (queryLowerCase == '*') {
				return suggestion.value;
			} else {
				var re = new RegExp($.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
				return re.test(suggestion.value);
			}
		}
	});
}

function bindNotesAutoComplete(rowId)
{
	$('#notes_' + rowId).autocomplete({
		lookup: notesList,
		showNoSuggestionNotice: false,
		lookupFilter: function (suggestion, originalQuery, queryLowerCase) {
			if (queryLowerCase == '*') {
				return suggestion.value;
			} else {
				var re = new RegExp($.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
				return re.test(suggestion.value);
			}
		}
	});
}

function submitForm()
{
	$('#formWrapper').submit();
}

function entryValidate()
{
	return true;
}
</script>