<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/amcharts/amcharts.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/amcharts/pie.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/amcharts/serial.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/amcharts/themes/light.js"></script>
<style>
.pagination-lg > li > a, .pagination-lg > li > span {
	font-size:15px !important;
	padding:5px 15px !important;
}
/*--------------Jqx Grid jqx All-------------------*/
#jqxgrid									{min-height:200px !important;}
#jqxgrid .jqx-grid-header 					{height:60px !important;}
.jqx-grid-groups-row						{padding-left:5px !important;}
.jqx-grid-pager-input						{padding: 2px; text-align: center !important; width: 35px;}
.jqx-dropdownlist-state-normal				{display: block;  float: right;height: 16px !important;margin-right: 7px;margin-top: 0;  padding-bottom: 2px !important;padding-top: 2px !important; width: 40px;}
.jqx-button									{cursor: pointer;float: right;margin-right: 3px !important;margin-top: 0 !important;padding: 0 !important;width: 20px !important;}
.jqx-button > .jqx-icon-arrow-left,
.jqx-button >.jqx-icon-arrow-right			{height: 21px !important;margin-left: 0 !important;width: 20px !important;}
.jqx-listitem-element						{height: 25px !important;}
.jqx-input									{height: 25px !important; margin:2px 4px !important;}
.jqx-grid-pager .jqx-grid-pager-input		{height:20px !important; margin:0px 4px !important;}
#jqxgrid .jqx-grid-cell-right-align 		{text-align:right !important; padding-right:8px;}
#jqxgrid .jqx-grid-cell-left-align 			{padding-left:8px;}
.jqx-grid-column-menubutton::after			{left:4px;top:10px;}
.proname_btn .select2-container{ background-color:#efefef;color:#244996;}
.proname_btn .select2-container .select2-selection--single .select2-selection__rendered{padding-top:0px; padding-bottom:5px;}
.proname_btn .select2-container--default .select2-selection--single{font-size:26px; line-height:28px;}
</style>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqxgrid.grouping.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqxgrid.aggregates.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqx-all.js"></script>
<div class="content_wrapper  padlr0">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="col-lg-12 padlr0">
          <h1 class="col-lg-6 col-md-6 col-sm-6 padlr0"><div class="btn-group proname_btn">
                  <select name="project_filter"  id="project_filter"  class="form-control single_dropdown" onchange="reportSearch($(this).val());" style="width:auto; min-width:260px !important;max-width:360px !important;">
                      <option <?php if(isset($reportId) && $reportId==1) { echo 'selected'; } ?> value="1">Project Wise Sales</option>
                      <option <?php if(isset($reportId) && $reportId==2) { echo 'selected'; } ?> value="2">Stage Wise Receivable Statement</option>
                      <option <?php if(isset($reportId) && $reportId==3) { echo 'selected'; } ?> value="3">Executive Analysis</option>
                      <option <?php if(isset($reportId) && $reportId==4) { echo 'selected'; } ?> value="4">Rent Receivable</option>
                      <option <?php if(isset($reportId) && $reportId==5) { echo 'selected'; } ?> value="5">Unit Transfer History</option>
                      <option <?php if(isset($reportId) && $reportId==6) { echo 'selected'; } ?> value="6">Receivable Statement</option>
                      <option <?php if(isset($reportId) && $reportId==7) { echo 'selected'; } ?> value="7">Ageing Report</option>
                      <option <?php if(isset($reportId) && $reportId==8) { echo 'selected'; } ?> value="8">Marketing Analysis</option>
                      <option <?php if(isset($reportId) && $reportId==9) { echo 'selected'; } ?> value="9">Maintenance Receivable</option>
                      <option <?php if(isset($reportId) && $reportId==10) { echo 'selected'; } ?> value="10">Unit Cancel History</option>
                      <option <?php if(isset($reportId) && $reportId==11) { echo 'selected'; } ?> value="11">Project Wise Receivable</option>
                      <option <?php if(isset($reportId) && $reportId==12) { echo 'selected'; } ?> value="12">Buyer Wise Receivable</option>
                      <option <?php if(isset($reportId) && $reportId==13) { echo 'selected'; } ?> value="13">Customer Info Report</option>
                      <option <?php if(isset($reportId) && $reportId==14) { echo 'selected'; } ?> value="14">Payable to Broker</option>
                      <option <?php if(isset($reportId) && $reportId==15) { echo 'selected'; } ?> value="15">Unit Block History</option>
                      <option <?php if(isset($reportId) && $reportId==16) { echo 'selected'; } ?> value="16">Project Status</option>
                      <option <?php if(isset($reportId) && $reportId==17) { echo 'selected'; } ?> value="17">Sales Team Performance</option>
                      <option <?php if(isset($reportId) && $reportId==18) { echo 'selected'; } ?> value="18">Customer Classification Report</option>
                      <option <?php if(isset($reportId) && $reportId==19) { echo 'selected'; } ?> value="19">Campaign Budget vs Expense</option>
                      <option <?php if(isset($reportId) && $reportId==20) { echo 'selected'; } ?> value="20">Unit PreBook History</option>
                      <option <?php if(isset($reportId) && $reportId==21) { echo 'selected'; } ?> value="21">Executive Wise Next Followup Analysis</option>
					  <option <?php if(isset($reportId) && $reportId==22) { echo 'selected'; } ?> value="22">Cost Impact</option> 
                  </select>
              </div>
          </h1>
          <div class="col-lg-6 col-md-6 col-sm-6">
            <ul>
              <li class="float_r" style="padding: 0px 5px;"><a href="javascript:void(0);" class="ripple"  id="print" data-original-title="ExportPrint" data-placement="left" data-toggle="tooltip"><img src="<?php echo $this->basePath(); ?>/images/icons-394.png" /></a></li>
              <li class="float_r" style="padding: 0px 5px;"><a href="javascript:void(0);" class="ripple" id="excelExport" data-original-title="ExportExcel" data-placement="left" data-toggle="tooltip"><img src="<?php echo $this->basePath(); ?>/images/icons-393.png" /></a></li>
              <li class="float_r" style="padding: 0px 5px;"><a href="javascript:void(0);" class="ripple" id="csvExport" data-original-title="ExportCSV" data-placement="left" data-toggle="tooltip"><img src="<?php echo $this->basePath(); ?>/images/icons-392.png" /></a></li>
              <!--<li class="float_r"><a href="#" class="crmcmnbtn crmcmnbtn4  ripple" id="htmlExport">Export to HTML</a></li>-->
            </ul>
          </div>
            <div class="col-lg-5 col-md-8 col-sm-8 col-xs-12 pull-right padlr0 m_btm10">
                <label class="col-lg-3 col-lg-offset-3 col-md-3 col-md-offset-3 col-sm-4 col-sm-offset-2 control-label text-right">Filter</label>
                <div class="col-lg-6 col-md-6 col-sm-6 m_btm10">
                    <select name="reportFilter" id="reportFilter" class="form-control single_dropdown lbl_move" style="width:100%;" onchange="executiveFilter(this);" title="Report Filter">
                        <option value="0" <?php if(isset($filterWise) && $filterWise==0) { echo 'selected'; } ?> >default</option>
                        <option value="1" <?php if(isset($filterWise) && $filterWise==1) { echo 'selected'; } ?> >Last 3 Days</option>
                        <option value="2" <?php if(isset($filterWise) && $filterWise==2) { echo 'selected'; } ?> >Last Week</option>
                        <option value="3" <?php if(isset($filterWise) && $filterWise==3) { echo 'selected'; } ?> >Last Month</option>
                        <option value="4" <?php if(isset($filterWise) && $filterWise==4) { echo 'selected'; } ?> >Last 3 Months</option>
                        <option value="5" <?php if(isset($filterWise) && $filterWise==5) { echo 'selected'; } ?> >Last 6 Months</option>
                        <option value="6" <?php if(isset($filterWise) && $filterWise==6) { echo 'selected'; } ?> >Last Year</option>
                    </select>
                </div>
            </div>
        </div>
          <div class="col-lg-6 col-lg-offset-6 col-md-8 col-md-offset-4 col-sm-10 col-sm-offset-2 clear padtop20 commargin_ttop_20 commargin_bottom">
              <div class="form-group col-lg-6 col-md-6 col-sm-6 commargin_top">
                  <span class="date_icon"><i class="fa fa-calendar"></i></span>
                  <input type="text" name="fromDate" id="fromDate" class="form-control date_picker lbl_move" readonly="readonly" label="From Date" onchange="PopulateFromData(this.value)"  value="<?php echo (isset($fromdat) && $fromdat != "") ? $fromdat : Date('d-m-Y'); ?>" />
              </div>
              <div class="form-group col-lg-6 col-md-6 col-sm-6 commargin_top">
                  <span class="date_icon"><i class="fa fa-calendar"></i></span>
                  <input type="text" name="toDate" id="toDate" class="form-control date_picker_end lbl_move" readonly="readonly" label="To Date" onchange="PopulateToData(this.value)"  value="<?php echo (isset($todat) && $todat != "") ? $todat : Date('d-m-Y'); ?>" />
              </div>
          </div>
      </div>
      <div class="col-lg-12 clear">
        <div class="table-responsive clear">
          <div style='margin-top: 10px;' id="jqxgrid"> </div>
        </div>
      </div>
      <div class="col-lg-6 col-lg-offset-3 commargin_ttop_20" id="chart">
        <section class="pnnal">
          <header class="pnnal-heading"><i class="fa fa-bar-chart"></i> <span class="fntsz16" id="exeName">&nbsp;Executive Analysis</span></header>
          <div class="pnnal-body">
            <div id="seccchartdiv" class="wdthhtchartdiv"></div>
          </div>
        </section>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
$(document).ready(function() {
    var fdate= '<?php echo (isset($fromdat) && $fromdat != "") ? $fromdat : Date('d-m-Y'); ?>';

    var sDate = fdate.split('-');
    var aDate = new Date((sDate[1])+'/'+ sDate[0] +'/'+sDate[2]);

    $('.date_picker_end').datepicker({
        format: "dd-mm-yyyy",
        startDate: aDate,
        orientation: "top auto",
        autoclose: true
    });
});


function executiveFilter(id) {
    var val = parseInt($(id).val());

    window.location.replace(getBaseURL() + "crm/report/executiveanalysisrpt/" + $('#fromDate').val() + "/" + $('#toDate').val() + "/" + val);

}
var arr_Lists = <?php echo (isset($arrUnitLists)) ? json_encode($arrUnitLists) : '[]';?>;
$("#chart").hide();
function reportSearch(rId) {

    switch (parseInt($.trim(rId))) {
        case 1:
            $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/projectwisesalesrpt");
            break;
        case 2:
            $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/stagewisereceivablerpt/0/0");
            break;

        case 3:
            $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/executiveanalysisrpt");
            break;
        case 4:
            $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/rentreceivablerpt");
            break;
        case 5:
            $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/unittransferhistory");
            break;
        case 6:
            $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/receivablestatementrpt");
            break;
        case 7:
            $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/ageingrpt");
            break;
        case 8:
            $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/marketinganalysisrpt");
            break;
        case 9:
            $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/maintenancereceivablerpt");
            break;
        case 10:
            $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/unitcancelhistory");
            break;
        case 11:
            $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/projectwisereceivablerpt");
            break;
        case 12:
            $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/buyerwisereceivablerpt");
            break;
        case 13:
            $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/customerinforpt");
            break;
        case 14:
            $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/payabletobrokerrpt");
            break;
        case 15:
            $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/block-history");
            break;
        case 16:
            $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/projectstatus");
            break;
        case 17:
            $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/salesteamperformancerpt");
            break;
        case 18:
            $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/customerclasificationrpt");
            break;
        case 19:
            $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/campaignbudgetvsexpenserpt");
            break;
        case 20:
            $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/prebook-history");
            break;
        case 21:
            $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/executive-next-followup");
            break;
        default :
            $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/reportlist");
            break;
    }

}
$(document).ready(function () {
	// Load Grid
	var source = {
		localdata: arr_Lists,
		datatype: "json",
		pagesize: 15,
		datafields:
		[	
			{ name: "UserId", type: "number" },
			{ name: "ExecutiveName", type: "string" },
			{ name: "UnitNo", type: "string" },
			{ name: "TotalLeads", type: "number" },
			{ name: "NoofSiteVisit", type: "number" },
			{ name: "ClientFollowed", type: "number" },
			{ name: "Finalizations", type: "number" },
			{ name: "SaleValue", type: "number" }
		]
	};

	var dataAdapter = new $.jqx.dataAdapter(source);
	$("#jqxgrid").jqxGrid(
	{
		width: "100%",
		source: dataAdapter,
		pageable: true,
		pagerMode: 'advanced',
    	pagerHeight: 40,
		rowsheight:40,
		columnsresize: true,
		autoheight: true,
		sortable: true,
		altrows: true,
		enabletooltips: true,
		showfilterrow: true,
		filterable: true,
		groupable: true,
		showstatusbar: true,
		statusbarheight: 35,
		showaggregates: true,
		autorowheight: true,
		columns: [	
			{ text: 'UserId', dataField: 'UserId', align: 'center' , pinned: true, hidden:true },
			{ text: 'Executive Name', dataField: 'ExecutiveName', align: 'center', pinned: true ,width:"25%",
                      aggregatesrenderer: function (aggregates, column, element, summaryData) {
                          var renderstring = "<div style='margin:8px;'><b>Total </b>";
                          renderstring += "</div>";
                          return renderstring;
                      } },
			{ text: 'Total Leads', dataField: 'TotalLeads', align: 'left', cellsalign: 'right',width:"15%", cellsformat: "d", aggregates: ['sum'],
                      aggregatesrenderer: function (aggregates, column, element, summaryData) {
                          var renderstring = "<div style='margin:8px;'>";
                          $.each(aggregates, function (key, value) {
                              var name = key == 'price';
                              renderstring += '<div><strong>' + value + '</div></strong>';
                          });
                          renderstring += "</div>";
                          return renderstring;
                      }
			},
			{ text: 'No of SiteVisit', dataField: 'NoofSiteVisit', align: 'left', cellsalign: 'right',width:"15%", cellsformat: "d", aggregates: ['sum'],
                      aggregatesrenderer: function (aggregates, column, element, summaryData) {
                          var renderstring = "<div style='margin:8px;'>";
                          $.each(aggregates, function (key, value) {
                              var name = key == 'price';
                              renderstring += '<div><strong>' + value + '</div></strong>';
                          });
                          renderstring += "</div>";
                          return renderstring;
                      }
			},
			{ text: 'Client FollowUp', dataField: 'ClientFollowed', align: 'left', cellsalign: 'right',width:"15%", cellsformat: "d", aggregates: ['sum'],
                      aggregatesrenderer: function (aggregates, column, element, summaryData) {
                          var renderstring = "<div style='margin:8px;'>";
                          $.each(aggregates, function (key, value) {
                              var name = key == 'price';
                              renderstring += '<div><strong>' + value + '</div></strong>';
                          });
                          renderstring += "</div>";
                          return renderstring;
                      }
			},
			{ text: 'Finalizations', dataField: 'Finalizations', align: 'left', cellsalign: 'right',width:"15%", cellsformat: "d", aggregates: ['sum'],
                      aggregatesrenderer: function (aggregates, column, element, summaryData) {
                          var renderstring = "<div style='margin:8px;'>";
                          $.each(aggregates, function (key, value) {
                              var name = key == 'price';
                              renderstring += '<div><strong>' + value + '</div></strong>';
                          });
                          renderstring += "</div>";
                          return renderstring;
                      }
			},
			{ text: 'Sale Value', dataField: 'SaleValue', align: 'left', cellsalign: 'right',width:"15%", cellsformat: "d2", aggregates: ['sum'],
                      aggregatesrenderer: function (aggregates, column, element, summaryData) {
                          var renderstring = "<div style='margin:8px;'>";
                          $.each(aggregates, function (key, value) {
                              var name = key == 'price';
                              renderstring += '<div><strong>' + value + '</div></strong>';
                          });
                          renderstring += "</div>";
                          return renderstring;
                      }
			}
		]
	});
			
	//Print option
	$("#excelExport").click(function () {
		$("#jqxgrid").jqxGrid('exportdata', 'xls', 'jqxGrid');
	});
	$("#csvExport").click(function () {
		$("#jqxgrid").jqxGrid('exportdata', 'csv', 'jqxGrid');
	});
	$("#htmlExport").click(function () {
		$("#jqxgrid").jqxGrid('exportdata', 'html', 'jqxGrid');
	});

	$("#print").click(function () {
		var gridContent = $("#jqxgrid").jqxGrid('exportdata', 'html');
		//var gridContent = $("#jqxgrid").jqxGrid('exportdata', 'html', 'jqxGrid', true, null, false);
		var newWindow = window.open('', '', 'width=800, height=500'),
		document = newWindow.document.open(),
		pageContent =
			'<!DOCTYPE html>\n' +
			'<html>\n' +
			'<head>\n' +
			'<meta charset="utf-8" />\n' +
			'<title>Executive Analysis</title>\n' +				
			'<h1>Executive Analysis</h1>\n' +
			'</head>\n' +
			'<body>\n' + gridContent + '\n</body>\n</html>';
		document.write(pageContent);
		document.close();
		newWindow.print();
		
		/*$("#jqxgrid").jqxGrid('exportdata', 'html', 'jqxGrid', true, null, false);*/
	});
	
	$("#jqxgrid").bind('rowselect', function (event) {
		var row = event.args.rowindex;
		var datarow = $("#jqxgrid").jqxGrid('getrowdata', row);
		
		var executiveName = 'Executive Analysis (' + datarow.ExecutiveName + ')';
		var TotalLeads =datarow.TotalLeads;
		var NoofSiteVisit =datarow.NoofSiteVisit;
		var ClientFollowed =datarow.ClientFollowed;
		var Finalizations =datarow.Finalizations;
		$("#exeName").text(executiveName);
		var chart = AmCharts.makeChart("seccchartdiv", {
			"type": "pie",
			"theme": "light",
			"innerRadius": "40%",
			"gradientRatio": [-0.4, -0.4, -0.4, -0.4, -0.4, -0.4, 0, 0.1, 0.2, 0.1, 0, -0.2, -0.5],
			"dataProvider": [{
				"type": "Total Leads",
				"count": TotalLeads
			}, {
				"type": "No of Site Visit",
				"count": NoofSiteVisit
			}, {
				"type": "Client FollowUp",
				"count": ClientFollowed
			}, {
				"type": "Finalizations",
				"count": Finalizations	
			}],
			//"balloonText": "[[value]]",
			"balloonText": "[[title]]<br><span style='font-size:14px'><b>[[value]]</b> ([[percents]]%)</span>",
			"valueField": "count",
			"titleField": "type",
			/*"balloon": {
				"drop": true,
				"adjustBorderColor": false,
				"color": "#FFFFFF",
				"fontSize": 16
			},*/
			"export": {
				"enabled": true
			}
		});
		$("#chart").show();
	});
	//bindJqxGridAutoResize();
});

function PopulateFromData(value) {
    //console.log(value);
    var toDate = $('#toDate').val();
    if(value !=  '') {
        window.location.replace(getBaseURL() + "crm/report/executiveanalysisrpt/" + value + "/" + toDate);
    } /*else{
     window.location.replace(getBaseURL() + "crm/report/executiveanalysisrpt");
     }*/
}

function PopulateToData(value) {
    //console.log(value);
    var fromDate = $('#fromDate').val();
    if(value !=  '') {
        window.location.replace(getBaseURL() + "crm/report/executiveanalysisrpt/" + fromDate + "/" + value);
    } /*else{
     window.location.replace(getBaseURL() + "crm/report/executiveanalysisrpt");
     }*/
}



</script>