<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/select2.full.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqxgrid.grouping.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqxgrid.aggregates.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqx-all.js"></script>
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/project.css';?>"/>
<style type="text/css">
/*--------------Jqx Grid jqx All-------------------*/
#treeGrid									{min-height:200px !important;}
#treeGrid .jqx-grid-header 					{height:60px !important;}
.jqx-grid-groups-row						{padding-left:5px !important;}
.jqx-grid-pager-input						{padding: 2px; text-align: center !important; width: 35px;}
.jqx-dropdownlist-state-normal				{display: block;  float: right;height: 16px !important;margin-right: 7px;margin-top: 0;  padding-bottom: 2px !important;padding-top: 2px !important; width: 40px;}
.jqx-button									{cursor: pointer;float: right;margin-right: 3px !important;margin-top: 0 !important;padding: 0 !important;width: 20px !important;}
.jqx-button > .jqx-icon-arrow-left,
.jqx-button >.jqx-icon-arrow-right			{height: 21px !important;margin-left: 0 !important;width: 20px !important;}
.jqx-listitem-element						{height: 25px !important;}
.jqx-input									{height: 25px !important; margin:2px 4px !important;}
.jqx-grid-pager .jqx-grid-pager-input		{height:20px !important; margin:0px 4px !important;}
#treeGrid .jqx-grid-cell-right-align 		{text-align:right !important; padding-right:8px;}
#treeGrid .jqx-grid-cell-left-align 		{padding-left:8px;}
.jqx-grid-column-menubutton::after			{left:4px;top:10px;}
.proname_btn .select2-container{ background-color:#efefef;color:#244996;}
.proname_btn .select2-container .select2-selection--single .select2-selection__rendered{padding-top:0px; padding-bottom:5px;}
.proname_btn .select2-container--default .select2-selection--single{font-size:26px; line-height:28px;}</style>

<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
        <div class="col-lg-12">
            <div class="col-lg-12 padlr0">
                <h1 class="col-lg-6 col-md-6 col-sm-5 padlr0"><div class="btn-group proname_btn">
                        <select name="project_filter"  id="project_filter"  class="form-control single_dropdown" onchange="reportSearch($(this).val());" style="width:auto; min-width:300px !important;max-width:360px !important;">
                            <option <?php if(isset($reportId) && $reportId==1) { echo 'selected'; } ?> value="1">Project Wise Sales</option>
                            <option <?php if(isset($reportId) && $reportId==2) { echo 'selected'; } ?> value="2">Stage Wise Receivable Statement</option>
                            <option <?php if(isset($reportId) && $reportId==3) { echo 'selected'; } ?> value="3">Executive Analysis</option>
                            <option <?php if(isset($reportId) && $reportId==4) { echo 'selected'; } ?> value="4">Rent Receivable</option>
                            <option <?php if(isset($reportId) && $reportId==5) { echo 'selected'; } ?> value="5">Unit Transfer History</option>
                            <option <?php if(isset($reportId) && $reportId==6) { echo 'selected'; } ?> value="6">Receivable Statement</option>
                            <option <?php if(isset($reportId) && $reportId==7) { echo 'selected'; } ?> value="7">Ageing Report</option>
                            <option <?php if(isset($reportId) && $reportId==8) { echo 'selected'; } ?> value="8">Marketing Analysis</option>
                            <option <?php if(isset($reportId) && $reportId==9) { echo 'selected'; } ?> value="9">Maintenance Receivable</option>
                            <option <?php if(isset($reportId) && $reportId==10) { echo 'selected'; } ?> value="10">Unit Cancel History</option>
                            <option <?php if(isset($reportId) && $reportId==11) { echo 'selected'; } ?> value="11">Project Wise Receivable</option>
                            <option <?php if(isset($reportId) && $reportId==12) { echo 'selected'; } ?> value="12">Buyer Wise Receivable</option>
                            <option <?php if(isset($reportId) && $reportId==13) { echo 'selected'; } ?> value="13">Customer Info Report</option>
                            <option <?php if(isset($reportId) && $reportId==14) { echo 'selected'; } ?> value="14">Payable to Broker</option>
                            <option <?php if(isset($reportId) && $reportId==15) { echo 'selected'; } ?> value="15">Unit Block History</option>
                            <option <?php if(isset($reportId) && $reportId==16) { echo 'selected'; } ?> value="16">Project Status</option>
                            <option <?php if(isset($reportId) && $reportId==17) { echo 'selected'; } ?> value="17">Sales Team Performance</option>
                            <option <?php if(isset($reportId) && $reportId==18) { echo 'selected'; } ?> value="18">Customer Classification Report</option>
                            <option <?php if(isset($reportId) && $reportId==19) { echo 'selected'; } ?> value="19">Campaign Budget vs Expense</option>
                            <option <?php if(isset($reportId) && $reportId==20) { echo 'selected'; } ?> value="20">Unit PreBook History</option>
                            <option <?php if(isset($reportId) && $reportId==21) { echo 'selected'; } ?> value="21">Executive Wise Next Followup Analysis</option>
							<option <?php if(isset($reportId) && $reportId==22) { echo 'selected'; } ?> value="22">Cost Impact</option>

                        </select>
                    </div></h1>
                <div class="col-lg-6 col-md-6 col-sm-7 padlr0">
                    <label class="col-lg-3 col-lg-offset-3 col-md-3 col-md-offset-3 col-sm-4 col-sm-offset-2 control-label text-right">Filter</label>
                    <div class="col-lg-6 col-md-6 col-sm-6 m_btm10">
                        <select name="block_type" id="block_type" onchange="filterSearch(this);" class="form-control lbl_move single_dropdown" style="width:100%;">
                            <option <?php echo (isset($preBookType) && $preBookType==0) ? "selected" : ""; ?> value="0">Pre-Book</option>
                            <option <?php echo (isset($preBookType) && $preBookType==1) ? "selected" : ""; ?> value="1">Pre-Book Cancelled</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-lg-12 padlr0 tmss commargin_top clear">
                <div class="table-responsive clear">
                    <div id="treeGrid"> </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    function reportSearch(rId) {

        switch (parseInt($.trim(rId))) {
            case 1:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/projectwisesalesrpt");
                break;
            case 2:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/stagewisereceivablerpt/0/0");
                break;

            case 3:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/executiveanalysisrpt");
                break;
            case 4:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/rentreceivablerpt");
                break;
            case 5:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/unittransferhistory");
                break;
            case 6:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/receivablestatementrpt");
                break;
            case 7:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/ageingrpt");
                break;
            case 8:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/marketinganalysisrpt");
                break;
            case 9:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/maintenancereceivablerpt");
                break;
            case 10:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/unitcancelhistory");
                break;
            case 11:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/projectwisereceivablerpt");
                break;
            case 12:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/buyerwisereceivablerpt");
                break;
            case 13:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/customerinforpt");
                break;
            case 14:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/payabletobrokerrpt");
                break;
            case 15:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/block-history");
                break;
            case 16:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/projectstatus");
                break;
            case 17:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/salesteamperformancerpt");
                break;
            case 18:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/customerclasificationrpt");
                break;
            case 19:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/campaignbudgetvsexpenserpt");
                break;
            case 20:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/prebook-history");
                break;
            default :
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/reportlist");
                break;
        }

    }

    $(function() {
        var $treeGrid = $('#treeGrid');
        var source = {
            localdata:<?php echo (isset($jsonPreBookings))?$jsonPreBookings:'[]'; ?>,
            dataType: "json",
            dataFields: [
                { name: 'PreBookingId', type: 'number' },
                { name: 'BookingNo', type: 'string' },
                { name: 'BookingDate', type: "date", format: 'dd/MM/yyyy' },
                { name: 'UnitNo', type: 'string' },
                { name: 'UnitId', type: 'string' },
                { name: 'LeadName', type: 'string' },
                { name: 'PRate', type: 'string' },
                { name: 'LeadId', type: 'number' },
                { name: 'NetAmount', type: 'string' },
                { name: 'ProjectName', type: 'string' },
                { name: 'ValidUpTo', type: "date", format: 'dd/MM/yyyy' }

            ],
            id: 'PreBookingId'
        };

        var dataAdapter = new $.jqx.dataAdapter(source);

        $treeGrid.jqxGrid({
            width: '100%',
            pageable: true,
            selectionMode: 'singleRow',
            pagerButtonsCount: 6,
            autoheight:true,
            pagerMode: 'advanced',
    		pagerHeight: 40,
			rowsheight:40,
            autorowheight: true,
            filterable: true,
            sortable: true,
            //filtermode: 'advanced',
            columnsResize: true,
            showfilterrow: true,
            ready:function(){
                var localizationobj = {};
                localizationobj.emptydatastring = "No Unit Transfers found!";
                $treeGrid.jqxGrid('localizestrings', localizationobj);
            },
            source:dataAdapter,
            columns: [
                { text: 'PreBookingId', dataField: 'PreBookingId',hidden: true, filterable: false},
                { text: 'LeadId', dataField: 'LeadId',hidden: true, filterable: false},
                { text: 'Booking No', dataField: 'BookingNo',width:'15%'},
                { text: 'BookingDate', filtertype: 'date', dataField: 'BookingDate',hidden: true, cellsformat: 'd' },
                { text: 'UnitName', dataField: 'UnitNo',width:'15%'},
                { text: 'UnitId', dataField: 'UnitId',hidden: true},
                { text: 'Buyer Name', dataField: 'LeadName',width:'15%'},
                { text: 'Project Name', dataField: 'ProjectName',width:'15%'},
                { text: 'Rate', align: 'right', cellsalign: 'right',dataField: 'PRate',width:'15%',
				cellsrenderer: function (row) {
                        return '<div class="text-right" style="margin:10px;">' + sanitizeNumber($treeGrid.jqxGrid('getCellValue', row, 'PRate'),2,true) + '</div>';
                    }
				},
                { text: 'Valid UpTo', align: 'right', cellsalign: 'right', filtertype: 'date', cellsformat: 'dd-MM-yyyy', dataField: 'ValidUpTo', width:'10%' },
				{ text: 'Net Amount', align: 'right', cellsalign: 'right', dataField: 'NetAmount',width:'15%',
				cellsrenderer: function (row) {
                        return '<div class="text-right" style="margin:10px;">' + sanitizeNumber($treeGrid.jqxGrid('getCellValue', row, 'NetAmount'),2,true) + '</div>';
                    }
				},
				 
            ]
        });
    });
    function filterSearch(val) {
        $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/prebook-history/"+parseInt($(val).val()));
    }
</script>