<style>
    #treeGrid									{min-height:200px !important;}
    .jqx-widget .jqx-grid-columngroup-header	{border-top:0px !important;}
    .jqx-widget .jqx-grid-columngroup-header > div	{ margin-top:7px !important;}
    .jqx-dropdownlist-state-normal  			{margin:2px 4px !important;}
    .jqx-grid-pager .jqx-dropdownlist-state-normal  			{margin-top: 0 !important;}
    .jqx-widget-header							{border-bottom: 1px solid #5d9bb6 !important;border-top: 1px solid #ddd !important;}
    .jqx-grid-pager-input						{margin-top:2px !important; padding: 2px;text-align: center !important; width: 35px;}
    .jqx-dropdownlist-state-normal				{display: block;  float: right;height: 16px;margin-right: 7px;margin-top: 0;  padding-bottom: 2px;padding-top: 2px; width: 40px;}
    .jqx-button									{cursor: pointer;float: right;margin-right: 3px !important;margin-top: 0 !important;padding: 0 !important;width: 20px !important;}
    .jqx-button > .jqx-icon-arrow-left,
    .jqx-button >.jqx-icon-arrow-right			{height: 21px !important;margin-left: 0 !important;width: 20px !important;}
    .jqx-listitem-element						{height: 25px !important;}
    .proname_btn .select2-container{ background-color:#efefef;color:#244996;}
    .proname_btn .select2-container .select2-selection--single .select2-selection__rendered{padding-top:0px; padding-bottom:5px;}
    .proname_btn .select2-container--default .select2-selection--single{font-size:26px; line-height:28px;}
</style>

<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqx-all.js"></script>
<div class="content_wrapper  padlr0">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 padlr0">
                <div class="col-lg-12 padlr0">
                    <h1 class="col-lg-6 col-md-6 col-sm-6 float_l"><div class="btn-group proname_btn">
                            <select name="project_filter"  id="project_filter"  class="form-control single_dropdown" onchange="reportSearch($(this).val());" style="width:auto; min-width:260px !important;max-width:360px !important;">
                                <option <?php if(isset($reportId) && $reportId==1) { echo 'selected'; } ?> value="1">Project Wise Sales</option>
                                <option <?php if(isset($reportId) && $reportId==2) { echo 'selected'; } ?> value="2">Stage Wise Receivable Statement</option>
                                <option <?php if(isset($reportId) && $reportId==3) { echo 'selected'; } ?> value="3">Executive Analysis</option>
                                <option <?php if(isset($reportId) && $reportId==4) { echo 'selected'; } ?> value="4">Rent Receivable</option>
                                <option <?php if(isset($reportId) && $reportId==5) { echo 'selected'; } ?> value="5">Unit Transfer History</option>
                                <option <?php if(isset($reportId) && $reportId==6) { echo 'selected'; } ?> value="6">Receivable Statement</option>
                                <option <?php if(isset($reportId) && $reportId==7) { echo 'selected'; } ?> value="7">Ageing Report</option>
                                <option <?php if(isset($reportId) && $reportId==8) { echo 'selected'; } ?> value="8">Marketing Analysis</option>
                                <option <?php if(isset($reportId) && $reportId==9) { echo 'selected'; } ?> value="9">Maintenance Receivable</option>
                                <option <?php if(isset($reportId) && $reportId==10) { echo 'selected'; } ?> value="10">Unit Cancel History</option>
                                <option <?php if(isset($reportId) && $reportId==11) { echo 'selected'; } ?> value="11">Project Wise Receivable</option>
                                <option <?php if(isset($reportId) && $reportId==12) { echo 'selected'; } ?> value="12">Buyer Wise Receivable</option>
                                <option <?php if(isset($reportId) && $reportId==13) { echo 'selected'; } ?> value="13">Customer Info Report</option>
                                <option <?php if(isset($reportId) && $reportId==14) { echo 'selected'; } ?> value="14">Payable to Broker</option>
                                <option <?php if(isset($reportId) && $reportId==15) { echo 'selected'; } ?> value="15">Unit Block History</option>
                                <option <?php if(isset($reportId) && $reportId==16) { echo 'selected'; } ?> value="16">Project Status</option>
                                <option <?php if(isset($reportId) && $reportId==17) { echo 'selected'; } ?> value="17">Sales Team Performance</option>
                                <option <?php if(isset($reportId) && $reportId==18) { echo 'selected'; } ?> value="18">Customer Classification Report</option>
                                <option <?php if(isset($reportId) && $reportId==19) { echo 'selected'; } ?> value="19">Campaign Budget vs Expense</option>
                                <option <?php if(isset($reportId) && $reportId==20) { echo 'selected'; } ?> value="20">Unit PreBook History</option>
                                <option <?php if(isset($reportId) && $reportId==21) { echo 'selected'; } ?> value="21">Executive Wise Next Followup Analysis
								<option <?php if(isset($reportId) && $reportId==22) { echo 'selected'; } ?> value="22">Cost Impact</option>
								</option>

                            </select>
                        </div></h1>
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        <ul>
                            <li class="float_r" style="padding: 0px 5px;"><a href="javascript:void(0);" class="ripple"  id="print" data-original-title="ExportPrint" data-placement="left" data-toggle="tooltip"><img src="<?php echo $this->basePath(); ?>/images/icons-394.png" /></a></li>
                            <li class="float_r" style="padding: 0px 5px;"><a href="javascript:void(0);" class="ripple" id="excelExport" data-original-title="ExportExcel" data-placement="left" data-toggle="tooltip"><img src="<?php echo $this->basePath(); ?>/images/icons-393.png" /></a></li>
                            <li class="float_r" style="padding: 0px 5px;"><a href="javascript:void(0);" class="ripple" id="csvExport" data-original-title="ExportCSV" data-placement="left" data-toggle="tooltip"><img src="<?php echo $this->basePath(); ?>/images/icons-392.png" /></a></li>
                            <!--<li class="float_r"><a href="#" class="crmcmnbtn crmcmnbtn4  ripple" id="htmlExport">Export to HTML</a></li>-->
                        </ul>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-lg-offset-6 col-md-offset-6 col-sm-offset-6 padlr0 commargin_ttop_20 commargin_bottom">
                    <div class="col-lg-6 commargin_top">
                    </div>
                    <div class="col-lg-6 commargin_top">
                        <span class="date_icon"><i class="fa fa-calendar"></i></span>
                        <input type="text" name="asonDate" id="asonDate" class="form-control date_picker lbl_move" readonly="readonly" label="As on Date" onchange="PopulateData(this.value)"  value="<?php echo Date('d-m-Y'); ?>" />
                    </div>
                </div>
            </div>
            <div class="col-lg-12 clear">
                <div class="table-responsive clear">
                    <div id="treeGrid">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
echo $this->inlineScript()->appendFile($this->basePath('/js/warehouse.js'));
?>
<script type="text/javascript">
    var arr_Lists = <?php echo (isset($arrUnitLists)) ? json_encode($arrUnitLists) : '[]';?>;
    // prepare the data
    if(arr_Lists == "[]"){
        $("#treeGrid").jqxTreeGrid('clear');
    } else {
        var source =
        {
            dataType: "json",  //"json",
            dataFields: [
                { name: "Id", type: "number" },
                { name: "Description", type: "string" },
                { name: "ParentId", type: "number" },
                { name: "NoofFlat", type: "number" },
                { name: "SoldFlat", type: "number" },
                { name: "UnsoldFlat", type: "number" },
                { name: "BlockFlat", type: "number" },
                { name: "SoldArea", type: "number" },
                { name: "UnsoldArea", type: "number" },
                { name: "TotalArea", type: "number" },
                { name: "SoldAmt", type: "number" },
                { name: "UnsoldAmt", type: "number" },
                { name: "TotalNetAmt", type: "number" },
                { name: "AvgRate", type: "number" },
                { name: "expanded", type: "bool" }
            ],
            hierarchy:
            {
                keyDataField: { name: 'Id' },
                parentDataField: { name: 'ParentId' }
            },
            id: 'Id',
            localData: arr_Lists
        };
        var dataAdapter = new $.jqx.dataAdapter(source, {
            loadComplete: function () {
                // data is loaded.
            }
        });

        $("#treeGrid").jqxTreeGrid({
            width: "100%",
            source: dataAdapter,
            pageable: true,
            pagerMode: 'advanced',
            pagerHeight: 40,
            filterable: true,
            columnsResize: true,
            editable: false,
            showAggregates: true,
            aggregatesHeight: 35,
            altRows: true,
            ready: function()
            {
                $("#treeGrid").jqxTreeGrid('hideColumn', 'Id');
                $("#treeGrid").jqxTreeGrid('hideColumn', 'ParentId');
            },
            toolbarHeight: 35,
            columns: [
                { text: 'Description', dataField: "Description", align: 'center', width: '15%' },
                { text: 'Id', dataField: "Id", align: 'right', cellsAlign: 'right' , cellsFormat: 'd', hidden:true, filterable: false },
                { text: 'ParentId', dataField: "ParentId", align: 'right', cellsAlign: 'right' , cellsFormat: 'd', hidden:true, filterable: false },
                { text: 'No of Flat', dataField: "NoofFlat", align: 'right', cellsAlign: 'right' , cellsFormat: 'd', width: '8%' },
                { text: 'Sold', dataField: "SoldFlat", align: 'right', cellsAlign: 'right' , cellsFormat: 'd', width: '5%' },
                { text: 'Unsold', dataField: "UnsoldFlat", align: 'right', cellsAlign: 'right' , cellsFormat: 'd', width: '5%' },
                { text: 'Block', dataField: "BlockFlat", align: 'right', cellsAlign: 'right' , cellsFormat: 'd', width: '5%' },
                { text: 'Sold Area', dataField: "SoldArea", align: 'right', cellsAlign: 'right' , cellsFormat: 'd2', width: '9%' },
                { text: 'Unsold Area', dataField: "UnsoldArea", align: 'right', cellsAlign: 'right' , cellsFormat: 'd2', width: '9%' },
                { text: 'Total Area', dataField: "TotalArea", align: 'right', cellsAlign: 'right' , cellsFormat: 'd2', width: '9%' },
                { text: 'Sold Amt', dataField: "SoldAmt", align: 'right', cellsAlign: 'right' , cellsFormat: 'd2', width: '9%',
                    aggregates: ['sum'],
                    aggregatesRenderer: function (aggregatesText, column, element, aggregates, type) {
                        if (type == "aggregates") {
                            var renderString = "<div style='margin: 8px; float: right;  height: 100%;'>";
                        }
                        else {
                            var renderString = "<div style='float: right;  height: 100%;'>";
                        }
                        var usd = 0;
                        if(aggregates != null){

                            usd =  sanitizeNumber(parseFloat(aggregates.sum),2,true);
                        }
                        renderString += "<table><tr><td rowspan='2'></td><td align='right'><strong>" + usd + "</strong></td></table>";
                        return renderString;
                    },
                    cellsrenderer: function (row) {
                        var iowId = $("#treeGrid").jqxTreeGrid('getCellValue', row, 'SoldAmt');
                            return '<div class="text-right">' + sanitizeNumber(iowId,2,true) + '</div>';
                    }
                },
                { text: 'Unsold Amt', dataField: "UnsoldAmt", align: 'right', cellsAlign: 'right' , cellsFormat: 'd2', width: '9%', aggregates: ['sum'],
                    aggregatesRenderer: function (aggregatesText, column, element, aggregates, type) {
                        if (type == "aggregates") {
                            var renderString = "<div style='margin: 8px; float: right;  height: 100%;'>";
                        }
                        else {
                            var renderString = "<div style='float: right;  height: 100%;'>";
                        }
                        var usd = 0;
                        if(aggregates != null){
                            usd =  sanitizeNumber(parseFloat(aggregates.sum),2,true);
                        }
                        renderString += "<table><tr><td rowspan='2'></td><td align='right'><strong>" + usd + "</strong></td></table>";
                        return renderString;
                    },
                    cellsrenderer: function (row) {
                        var iowId = $("#treeGrid").jqxTreeGrid('getCellValue', row, 'UnsoldAmt');
                        return '<div class="text-right">' + sanitizeNumber(iowId,2,true) + '</div>';
                    }
                },
                { text: 'Total NetAmt', dataField: "TotalNetAmt", align: 'right', cellsAlign: 'right' , cellsFormat: 'd2', width: '9%', aggregates: ['sum'],
                    aggregatesRenderer: function (aggregatesText, column, element, aggregates, type) {
                        if (type == "aggregates") {
                            var renderString = "<div style='margin: 8px; float: right;  height: 100%;'>";
                        }
                        else {
                            var renderString = "<div style='float: right;  height: 100%;'>";
                        }
                        var usd = 0;
                        if(aggregates != null){
                            usd =  sanitizeNumber(parseFloat(aggregates.sum),2,true);
                        }
                        renderString += "<table><tr><td rowspan='2'></td><td align='right'><strong>" + usd + "</strong></td></table>";
                        return renderString;
                    },
                    cellsrenderer: function (row) {
                        var iowId = $("#treeGrid").jqxTreeGrid('getCellValue', row, 'TotalNetAmt');
                        return '<div class="text-right">' + sanitizeNumber(iowId,2,true) + '</div>';
                    }
                },
                { text: 'Avg Rate', dataField: "AvgRate", align: 'right', cellsAlign: 'right' , cellsFormat: 'd3', width: '8%'}

            ]
        });
    }
    $("#excelExport").click(function () {
        $("#treeGrid").jqxTreeGrid('exportData', 'xls');
    });
    $("#csvExport").click(function () {
        $("#treeGrid").jqxTreeGrid('exportData', 'csv');
    });
    $("#htmlExport").click(function () {
        $("#treeGrid").jqxTreeGrid('exportData', 'html');
    });

    $("#print").click(function () {
        $("#treeGrid").jqxTreeGrid('exportData', 'html');
    });

    function PopulateData(value) {
        //console.log(value);
        bindLoadGrid(value);
    }
    function reportSearch(rId) {

        switch (parseInt($.trim(rId))) {
            case 1:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/projectwisesalesrpt");
                break;
            case 2:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/stagewisereceivablerpt/0/0");
                break;

            case 3:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/executiveanalysisrpt");
                break;
            case 4:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/rentreceivablerpt");
                break;
            case 5:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/unittransferhistory");
                break;
            case 6:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/receivablestatementrpt");
                break;
            case 7:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/ageingrpt");
                break;
            case 8:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/marketinganalysisrpt");
                break;
            case 9:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/maintenancereceivablerpt");
                break;
            case 10:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/unitcancelhistory");
                break;
            case 11:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/projectwisereceivablerpt");
                break;
            case 12:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/buyerwisereceivablerpt");
                break;
            case 13:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/customerinforpt");
                break;
            case 14:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/payabletobrokerrpt");
                break;
            case 15:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/block-history");
                break;
            case 16:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/projectstatus");
                break;
            case 17:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/salesteamperformancerpt");
                break;
            case 18:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/customerclasificationrpt");
                break;
            case 19:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/campaignbudgetvsexpenserpt");
                break;
            case 20:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/prebook-history");
                break;
            case 21:
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/executive-next-followup");
                break;
            default :
                $(location).attr('href',"<?php echo $this->basePath(); ?>/crm/report/reportlist");
                break;
        }

    }

    function bindLoadGrid(value) {
        $.ajax({
            url: getBaseURL() + "crm/report/projectwisesalesrpt",
            data: {rtype:'getLoad', data: value, csrf: "<?php echo isset($csrf)?$csrf:''; ?>"},
            async: false,
            type: 'post',
            success: function(data,status, xhr) {
                if(data == "[]"){
                    $("#treeGrid").jqxTreeGrid('clear');
                } else {
                    var source =
                    {
                        dataType: "json",
                        dataFields: [
                            { name: "Id", type: "number" },
                            { name: "Description", type: "string" },
                            { name: "ParentId", type: "number" },
                            { name: "NoofFlat", type: "number" },
                            { name: "SoldFlat", type: "number" },
                            { name: "UnsoldFlat", type: "number" },
                            { name: "BlockFlat", type: "number" },
                            { name: "SoldArea", type: "number" },
                            { name: "UnsoldArea", type: "number" },
                            { name: "TotalArea", type: "number" },
                            { name: "SoldAmt", type: "number" },
                            { name: "UnsoldAmt", type: "number" },
                            { name: "TotalNetAmt", type: "number" },
                            { name: "AvgRate", type: "number" },
                            { name: "expanded", type: "bool" }
                        ],
                        hierarchy:
                        {
                            keyDataField: { name: 'Id' },
                            parentDataField: { name: 'ParentId' }
                        },
                        id: 'Id',
                        localData: data
                    };

                    var dataAdapter = new $.jqx.dataAdapter(source, {
                        loadComplete: function () {
                            // data is loaded.
                        }
                    });

                    $("#treeGrid").jqxTreeGrid({
                        width: "100%",
                        source: dataAdapter,
                        pageable: true,
                        pagerMode: 'advanced',
                        pagerHeight: 40,
                        filterable: true,
                        columnsResize: true,
                        editable: false,
                        showAggregates: true,
                        aggregatesHeight: 35,
                        altRows: true,
                        ready: function()
                        {
                            $("#treeGrid").jqxTreeGrid('hideColumn', 'Id');
                            $("#treeGrid").jqxTreeGrid('hideColumn', 'ParentId');
                        },
                        toolbarHeight: 35,
                        columns: [
                            { text: 'Description', dataField: "Description", align: 'center', width: '15%' },
                            { text: 'Id', dataField: "Id", align: 'right', cellsAlign: 'right' , cellsFormat: 'd', hidden:true, filterable: false },
                            { text: 'ParentId', dataField: "ParentId", align: 'right', cellsAlign: 'right' , cellsFormat: 'd', hidden:true, filterable: false },
                            { text: 'No of Flat', dataField: "NoofFlat", align: 'right', cellsAlign: 'right' , cellsFormat: 'd', width: '8%' },
                            { text: 'Sold', dataField: "SoldFlat", align: 'right', cellsAlign: 'right' , cellsFormat: 'd', width: '5%' },
                            { text: 'Unsold', dataField: "UnsoldFlat", align: 'right', cellsAlign: 'right' , cellsFormat: 'd', width: '5%' },
                            { text: 'Block', dataField: "BlockFlat", align: 'right', cellsAlign: 'right' , cellsFormat: 'd', width: '5%' },
                            { text: 'Sold Area', dataField: "SoldArea", align: 'right', cellsAlign: 'right' , cellsFormat: 'd2', width: '9%' },
                            { text: 'Unsold Area', dataField: "UnsoldArea", align: 'right', cellsAlign: 'right' , cellsFormat: 'd2', width: '9%' },
                            { text: 'Total Area', dataField: "TotalArea", align: 'right', cellsAlign: 'right' , cellsFormat: 'd2', width: '9%' },
                            { text: 'Sold Amt', dataField: "SoldAmt", align: 'right', cellsAlign: 'right' , cellsFormat: 'd2', width: '9%', aggregates: ['sum'],
                                aggregatesRenderer: function (aggregatesText, column, element, aggregates, type) {
                                    if (type == "aggregates") {
                                        var renderString = "<div style='margin: 8px; float: right;  height: 100%;'>";
                                    }
                                    else {
                                        var renderString = "<div style='float: right;  height: 100%;'>";
                                    }
                                    var usd = 0;
                                    if(aggregates != null){
                                        usd =  sanitizeNumber(parseFloat(aggregates.sum),2,true);
                                    }
                                    renderString += "<table><tr><td rowspan='2'></td><td align='right'><strong>" + usd + "</strong></td></table>";
                                    return renderString;
                                },
                                cellsrenderer: function (row) {
                                    var iowId = $("#treeGrid").jqxTreeGrid('getCellValue', row, 'SoldAmt');
                                    return '<div class="text-right">' + sanitizeNumber(iowId,2,true) + '</div>';
                                }
                            },
                            { text: 'Unsold Amt', dataField: "UnsoldAmt", align: 'right', cellsAlign: 'right' , cellsFormat: 'd2', width: '9%', aggregates: ['sum'],
                                aggregatesRenderer: function (aggregatesText, column, element, aggregates, type) {
                                    if (type == "aggregates") {
                                        var renderString = "<div style='margin: 8px; float: right;  height: 100%;'>";
                                    }
                                    else {
                                        var renderString = "<div style='float: right;  height: 100%;'>";
                                    }
                                    var usd = 0;
                                    if(aggregates != null){
                                        usd = sanitizeNumber(parseFloat(aggregates.sum),2,true);
                                    }
                                    renderString += "<table><tr><td rowspan='2'></td><td align='right'><strong>" + usd + "</strong></td></table>";
                                    return renderString;
                                },
                                cellsrenderer: function (row) {
                                    var iowId = $("#treeGrid").jqxTreeGrid('getCellValue', row, 'UnsoldAmt');
                                    return '<div class="text-right">' + sanitizeNumber(iowId,2,true) + '</div>';
                                }
                            },
                            { text: 'Total NetAmt', dataField: "TotalNetAmt", align: 'right', cellsAlign: 'right' , cellsFormat: 'd2', width: '9%', aggregates: ['sum'],
                                aggregatesRenderer: function (aggregatesText, column, element, aggregates, type) {
                                    if (type == "aggregates") {
                                        var renderString = "<div style='margin: 8px; float: right;  height: 100%;'>";
                                    }
                                    else {
                                        var renderString = "<div style='float: right;  height: 100%;'>";
                                    }
                                    var usd = 0;
                                    if(aggregates != null){
                                        usd = sanitizeNumber(parseFloat(aggregates.sum),2,true);
                                    }
                                    renderString += "<table><tr><td rowspan='2'></td><td align='right'><strong>" + usd + "</strong></td></table>";
                                    return renderString;
                                },
                                cellsrenderer: function (row) {
                                    var iowId = $("#treeGrid").jqxTreeGrid('getCellValue', row, 'TotalNetAmt');
                                    return '<div class="text-right">' + sanitizeNumber(iowId,2,true) + '</div>';
                                }
                            },
                            { text: 'Avg Rate', dataField: "AvgRate", align: 'right', cellsAlign: 'right' , cellsFormat: 'd3', width: '8%'}

                        ]
                    });
                }
            }
        });
    }

</script>