<style>

.h2clr_bbdr {
    background-color: #dccfc8;
    clear: both !important;
    height: 1px;
    width: 100%;
}
.h2clr_bbdr::after {
    background-color: #762b00;
    content: "";
    height: 2px;
    margin: -1px 0 0;
    position: absolute;
    width: 18%;
}
.h2alignmt{color: #555;
    font-size: 18px;
    font-weight: 400 !important;
    padding: 8px 4px;}
.ovrcls .list-icon {
    border-radius: 100%;
    font-size: 32px;
	display:block;
    height: 60px;
    line-height: 55px;
    margin: auto;
    text-align: center;
    width: 60px;
	background:#fff;
	
}
.ovrcls:hover .brdrrndclr1 { background: #6ac4f6;color:#fff;}
.ovrcls:hover .brdrrndclr2 { background: #af91c2;color:#fff;}
.ovrcls:hover .brdrrndclr3 { background: #83572e;color:#fff;}
.ovrcls:hover .brdrrndclr4 { background: #8c93ab ;color:#fff;}
.clrrndtxt					{font-size:15px; color:#1e1e1e;}
.ovrcls .brdrrndclr1 {border: 1px solid #6ac4f6; color: #6ac4f6;}
.ovrcls .brdrrndclr2{border: 1px solid #af91c2; color: #af91c2;}
.ovrcls .brdrrndclr3{border: 1px solid #83572e ;color: #83572e;}
.ovrcls .brdrrndclr4{border: 1px solid #8c93ab;color: #8c93ab;}
</style>
<div class="content_wrapper padlr0">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12"><h1 class="text-center" data-bsfshare="BillReport List">Bill Report List</h1></div>
        	<div class="clearfix"></div>
            <div class="col-lg-12 clear" style="margin-top:10px;">
            	<div class="col-lg-12"><h2 class="h2alignmt">Report List</h2><div class="h2clr_bbdr"></div></div>
                <div class="clear"></div>
                <div class="col-lg-12 m_btm30">
                    <div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Projectwise Sales">
                    	<a href="<?php echo $this->basePath(); ?>/crm/report/projectwisesalesrpt" class="ovrcls" >
                            <div class="col-lg-12 ovrclss"><span  class="list-icon text-center brdrrndclr1"><i class="fa fa fa-street-view icon-hvr"></i></span></div>
                            <div class="col-lg-12 text-center clrrndtxt commargin_top5">Project wise Sales</div>
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Receivable Statement">
                    	<a href="<?php echo $this->basePath(); ?>/crm/report/receivablestatementrpt" class="ovrcls">
                            <div class="col-lg-12"><span  class="list-icon text-center brdrrndclr2"><i class="fa fa-ticket icon-hvr"></i></span></div>
                            <div class="col-lg-12 text-center clrrndtxt commargin_top5">Receivable Statement</div>
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Projectwise Receivable">
                    	<a href="<?php echo $this->basePath(); ?>/crm/report/projectwisereceivablerpt" class="ovrcls">
                            <div class="col-lg-12"><span  class="list-icon text-center brdrrndclr3"><i class="fa fa-comments-o icon-hvr"></i></span></div>     
                            <div class="col-lg-12 text-center clrrndtxt commargin_top5">Project wise Receivable</div>
                        </a>
                    </div>
					<div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Project Status">
                    	<a href="<?php echo $this->basePath(); ?>/crm/report/projectstatus" class="ovrcls">
                            <div class="col-lg-12"><span  class="list-icon text-center brdrrndclr4"><i class="fa fa-magic icon-hvr"></i></span></div>
                            <div class="col-lg-12 text-center clrrndtxt commargin_top5">Project Status</div>
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Stagewise Receivable">
                    	<a href="<?php echo $this->basePath(); ?>/crm/report/stagewisereceivablerpt/0/0" class="ovrcls">
                            <div class="col-lg-12"><span  class="list-icon text-center brdrrndclr1"><i class="fa fa-magic icon-hvr"></i></span></div>
                            <div class="col-lg-12 text-center clrrndtxt commargin_top5">Stage wise Receivable</div>
                        </a>
                    </div>
					
					 <div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Ageing">
                    	<a href="<?php echo $this->basePath(); ?>/crm/report/ageingrpt" class="ovrcls" >
                            <div class="col-lg-12 ovrclss"><span  class="list-icon text-center brdrrndclr2"><i class="fa fa-line-chart icon-hvr"></i></span></div>
                            <div class="col-lg-12 text-center clrrndtxt commargin_top5">Ageing</div>
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Buyerwise Receivable">
                    	<a href="<?php echo $this->basePath(); ?>/crm/report/buyerwisereceivablerpt" class="ovrcls">
                            <div class="col-lg-12 ovrclss"><span  class="list-icon text-center brdrrndclr3"><i class="fa fa-users icon-hvr"></i></span></div>
                            <div class="col-lg-12 text-center clrrndtxt commargin_top5">Buyer wise Receivable</div>
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="SalesTeamPerformance">
                    	<a href="<?php echo $this->basePath(); ?>/crm/report/salesteamperformancerpt" class="ovrcls">
                            <div class="col-lg-12 ovrclss"><span  class="list-icon text-center brdrrndclr4"><i class="fa fa-retweet icon-hvr"></i></span></div>
                            <div class="col-lg-12 text-center clrrndtxt commargin_top5">Sales Team Performance</div>
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Executive Analysis">
                    	<a href="<?php echo $this->basePath(); ?>/crm/report/executiveanalysisrpt" class="ovrcls">
                            <div class="col-lg-12 ovrclss"><span  class="list-icon text-center brdrrndclr1"><i class="fa fa-registered icon-hvr"></i></span></div>
                            <div class="col-lg-12 text-center clrrndtxt commargin_top5">Executive Analysis</div>
                        </a>
                    </div>	
					
					<div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Marketting Analysis">
                    	<a href="<?php echo $this->basePath(); ?>/crm/report/marketinganalysisrpt" class="ovrcls">
                            <div class="col-lg-12 ovrclss"><span  class="list-icon text-center brdrrndclr2"><i class="fa fa-puzzle-piece icon-hvr"></i></span></div>
                            <div class="col-lg-12 text-center clrrndtxt commargin_top5">Marketing Analysis</div>
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Customer Info Report">
                    	<a href="<?php echo $this->basePath(); ?>/crm/report/customerinforpt" class="ovrcls">
                            <div class="col-lg-12 ovrclss"><span  class="list-icon text-center brdrrndclr3"><i class="fa fa-check-square-o icon-hvr"></i></span></div>
                            <div class="col-lg-12 text-center clrrndtxt commargin_top5">Customer Info Report</div>
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Clasification Report">
                    	<a href="<?php echo $this->basePath(); ?>/crm/report/customerclasificationrpt" class="ovrcls">
                            <div class="col-lg-12 ovrclss"><span  class="list-icon text-center brdrrndclr4"><i class="fa fa-gavel icon-hvr"></i></span></div>
                            <div class="col-lg-12 text-center clrrndtxt commargin_top5">Customer Classification Report</div>
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Rent Receivable">
                    	<a href="<?php echo $this->basePath(); ?>/crm/report/rentreceivablerpt" class="ovrcls">
                            <div class="col-lg-12 ovrclss"><span  class="list-icon text-center brdrrndclr1"><i class="fa fa-archive icon-hvr"></i></span></div>
                            <div class="col-lg-12 text-center clrrndtxt commargin_top5">Rent Receivable</div>
                        </a>
                    </div>
					
					<div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Maintenance Receivable">
                    	<a href="<?php echo $this->basePath(); ?>/crm/report/maintenancereceivablerpt" class="ovrcls" >
                            <div class="col-lg-12 ovrclss"><span  class="list-icon text-center brdrrndclr2"><i class="fa fa fa-street-view icon-hvr"></i></span></div>
                            <div class="col-lg-12 text-center clrrndtxt commargin_top5">Maintenance Receivable</div>
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Payable to Broker">
                    	<a href="<?php echo $this->basePath(); ?>/crm/report/payabletobrokerrpt" class="ovrcls">
                            <div class="col-lg-12"><span  class="list-icon text-center brdrrndclr3"><i class="fa fa-ticket icon-hvr"></i></span></div>
                            <div class="col-lg-12 text-center clrrndtxt commargin_top5">Payable to Broker</div>
                        </a>
                    </div>
					<div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Budget Vs Expense">
                    	<a href="<?php echo $this->basePath(); ?>/crm/report/campaignbudgetvsexpenserpt" class="ovrcls">
                            <div class="col-lg-12"><span  class="list-icon text-center brdrrndclr4"><i class="fa fa-comments-o icon-hvr"></i></span></div>     
                            <div class="col-lg-12 text-center clrrndtxt commargin_top5">Campaign Budget Vs Expense</div>
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Unit Transfer History">
                        <a href="<?php echo $this->basePath(); ?>/crm/report/unittransferhistory" class="ovrcls">
                            <div class="col-lg-12"><span  class="list-icon text-center brdrrndclr1"><i class="fa fa-transgender icon-hvr"></i></span></div>
                            <div class="col-lg-12 text-center clrrndtxt commargin_top5">Unit Transfer History</div>
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Unit Cancel History">
                        <a href="<?php echo $this->basePath(); ?>/crm/report/unitcancelhistory" class="ovrcls">
                            <div class="col-lg-12"><span  class="list-icon text-center brdrrndclr2"><i class="fa fa-file-o"></i></span></div>
                            <div class="col-lg-12 text-center clrrndtxt commargin_top5">Unit Cancel History</div>
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Unit Cancel History">
                        <a href="<?php echo $this->basePath(); ?>/crm/report/block-history" class="ovrcls">
                            <div class="col-lg-12"><span  class="list-icon text-center brdrrndclr3"><i class="fa fa-file-o"></i></span></div>
                            <div class="col-lg-12 text-center clrrndtxt commargin_top5">Unit Block History</div>
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Unit Cancel History">
                        <a href="<?php echo $this->basePath(); ?>/crm/report/prebook-history" class="ovrcls">
                            <div class="col-lg-12"><span  class="list-icon text-center brdrrndclr4"><i class="fa fa-file-o"></i></span></div>
                            <div class="col-lg-12 text-center clrrndtxt commargin_top5">Unit PreBook History</div>
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Marketting Analysis">
                        <a href="<?php echo $this->basePath(); ?>/crm/report/executive-next-followup" class="ovrcls">
                            <div class="col-lg-12 ovrclss"><span  class="list-icon text-center brdrrndclr1"><i class="fa fa-puzzle-piece icon-hvr"></i></span></div>
                            <div class="col-lg-12 text-center clrrndtxt commargin_top5">Executive Wise <br/>Next Followup Analysis</div>
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6 padtop20" data-bsfshare="Cost Impact">
                        <a href="<?php echo $this->basePath(); ?>/crm/report/unit-discount" class="ovrcls">
                            <div class="col-lg-12 ovrclss"><span  class="list-icon text-center brdrrndclr1"><i class="fa fa-archive icon-hvr"></i></span></div>
                            <div class="col-lg-12 text-center clrrndtxt commargin_top5">Cost Impact</div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

