<?php $bsf = new \BuildsuperfastClass(); ?>
<form method="post" id="form">
<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
        <div class="col-lg-12">
        	<h1 class="float_l">Project Info of
					<div class="btn-group proname_btn">
						<a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"><?php echo ucfirst($projectDetail['ProjectName']);?> <span class="edit_symbols" data-placement="right" data-toggle="tooltip" data-original-title="Choose&nbsp;your&nbsp;project"><i class="fa fa-caret-down "></i></span></a> 							
						<div class="dropdown-menu toolbar_ddown proname_ddown arrow" role="menu">
							<ul>
								<?php foreach($projects as $project){?>
									<li><a href="<?php echo $this->basePath(); ?>/crm/project/<?php echo $this->currentRequest()->get('action'); ?>/<?php echo $bsf->encode($project['ProjectId']); ?>"><?php echo ucfirst($project['ProjectName']);?></a></li>
								<?php }	?>
							</ul>
						</div>
					</div>
				</h1>
            <div class="promote_social float_r">
                <ul>
                    <span>Promote Project</span>
                    <li><a href="#" class="fb_c ripple"><i class="fa fa-facebook-square"></i></a></li>
                    <li><a href="#" class="twt_c ripple"><i class="fa fa-twitter-square"></i></a></li>
                    <li><a href="#" class="g_c ripple"><i class="fa fa-google-plus-square"></i></a></li>
                </ul>
            </div>
        </div>
    	<div class="col-lg-12 clear">
        	<div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
          		<div class="col-lg-12">
                    <div class="row">
                    	<div class="step_by_liner animated slideInDown"></div>
                        <ul class="step_by stepby_mb60">
                        	<li>
                            	<div class="step_by_sep animated_0_4s slideInRight"><p>7</p></div>
                                <p class="stepli_p1">Facility Management</p>
                            </li>
                            <li>
                                <div class="step_by_sep stepsep_active animated slideInRight"><p>8</p></div>
                                <p class="stepli_p2">Check List Management</p>
                            </li>
                            <li class="opacity_08">
                                <div class="step_by_sep animated_1_5s slideInRight"><p>9</p></div>
                                <p class="stepli_p3">Penality &amp; Interest Rate</p>
                            </li>
                        </ul>
          			</div>
        		</div>
        	</div>	
            <div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            	<div class="col-lg-12">
                    <div class="row">
                        <div class="form-group col-lg-12">
                            <select name="CheckListTypeId" id="CheckListType" class="form-control single_dropdown lbl_move" label="Select Check List Type.." style="width:100%;">
								<option value="" ></option>
								<?php foreach($checklistType as $type): ?>
                                <option value="<?php echo $type['TypeId'];?>" ><?php echo $type['CheckListName'];?></option>
								<?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
  		</div>
        <div class="col-lg-12 clear" >
			<div class="hide" id="workarea">
				<table class="table table-hover m_btm0 clear" id="paySchTable">
					<thead>
						<tr>														
							<th>CheckListName</th>
							<th style="width:300px;">TimeLine Required</th>
							<th style="width:300px;"></th>
							<th></th>
						</tr>
					</thead>
					<tbody id="check-list-wrapper" class="psSorting">
					</tbody>
				</table>
				<input type="hidden" id="psCount" name="psCount" value="0" />
				<a id="addNewId" class="onbrd_addnew ripple float_l" href="javascript:void(0);" onclick="return addNewRow();">Add New</a>
			</div>
		</div>
	</div>
</div>
<div class="col-lg-12 savebtn_area">
	<ul>
		<li class="save_btn m_right10 float_r"><input type="submit" name="saveExit float_r" class="ripple continue" value="Save &amp; Exit"/></li>
		<li class="save_btn m_right10 float_r"><input type="submit" name="saveNext" class="ripple continue float_l" value="Save &amp; Next"/></li>
		<li class="goto">
			<label for="go_to" class="float_l">Go to</label> 
			<select id="projectSteps" name="go_to" class="float_l goto_select">
                <option value="general" <?php if($this->currentRequest()->get('action') == 'general') { echo 'selected'; } ?>>General</option>
                <option value="land-area" <?php if($this->currentRequest()->get('action') == 'land-area') { echo 'selected'; } ?>>Area Details</option>
                <option value="land-cost" <?php if($this->currentRequest()->get('action') == 'land-cost') { echo 'selected'; } ?>>Land Cost Calculation</option>
                <option value="other-cost" <?php if($this->currentRequest()->get('action') == 'other-cost') { echo 'selected'; } ?>>Other Cost Details</option>
                <option value="payment" <?php if($this->currentRequest()->get('action') == 'payment-schedule' || $this->currentRequest()->get('action') == 'payment-schedule-edit' || $this->currentRequest()->get('action') == 'payment-schedule-register' || $this->currentRequest()->get('action') == 'payment') { echo 'selected'; } ?>>Payment Schedule</option>
                <option value="unit-type-register" <?php if($this->currentRequest()->get('action') == 'unit-type-register' || $this->currentRequest()->get('action') == 'unit-type' || $this->currentRequest()->get('action') == 'unit-type-edit') { echo 'selected'; } ?>>Unit Type</option>
                <option value="facility" <?php if($this->currentRequest()->get('action') == 'facility' || $this->currentRequest()->get('action') == 'car-park' || $this->currentRequest()->get('action') == 'other-facility') { echo 'selected'; } ?>>Facility Management</option>
                <option value="checklist" <?php if($this->currentRequest()->get('action') == 'checklist') { echo 'selected'; } ?>>Check List Management</option>
                <option value="penality-interestrate" <?php if($this->currentRequest()->get('action') == 'penality-interestrate') { echo 'selected'; } ?>>Penality & Interest Rate</option>
                <option value="incentive-register" <?php if($this->currentRequest()->get('action') == 'incentive-register') { echo 'selected'; } ?>>Incentive Management</option>
                <option value="property-management" <?php if($this->currentRequest()->get('action') == 'property-management') { echo 'selected'; } ?>>Property Management</option>
		   </select>
			<p class="donecngs_p">Done With Your Changes ?</p>
		</li>
	</ul>
</div>
</form>
<!--Page Scripts-->
<script>
$(document).ready(function() {
	$(".single_dropdown").select2({
		placeholder: "",
		allowClear: true
	});
});
$("#projectSteps").change(function(){
	window.location.href= getBaseURL() + "crm/project/"+this.value+"/<?php echo $bsf->encode($projectId); ?>";
});

var $checkListType = $('#CheckListType'),
    $checkListWrapper = $('#check-list-wrapper'),
    $workarea = $('#workarea'),
    $psCnt = $('#psCount'),
    checkListData = [];

$(function() {

    $checkListType.on('change', function() {

        var typeId = $checkListType.val();
        $psCnt.val(0);
        if(typeId != '') {
            selectType(typeId);
        } else {
            $checkListWrapper.html('');
            $workarea.addClass('hide');
        }
    });

    // delete check list
    $checkListWrapper.on('click', '.delete-checklist', function(ev) {
        ev.preventDefault();
        $(this).closest('tr').remove();
    });
});

function bindCheckList_autoComplete() {

    $checkListWrapper.find('input.check-list-name').each(function () {
        bindAutoCompleted($(this));
    });
}

function bindAutoCompleted($tarCheckListIp) {

    var $tarCheckListId = $tarCheckListIp.prev('.check-list-id'),
        arrCheckListCopy = $.extend(true, [], checkListData);

    removeUsedCheckList(arrCheckListCopy, function (checkListData) {

        $tarCheckListIp.autocomplete({
            lookup: checkListData,
            lookupFilter: function (suggestion, originalQuery, queryLowerCase) {
                if (queryLowerCase == '*') {
                    return suggestion.value;
                } else {
                    var re = new RegExp($.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
                    return re.test(suggestion.value);
                }
            }, onSelect: function (suggestion) {
                if (suggestion) {
                    $tarCheckListId.val(suggestion.data);
                    removeError($(this));
                }
            }, onSearchStart: function (suggestion) {
                $tarCheckListId.val('');
            }, onSearchComplete: function (query, suggestions) {
                if (!suggestions.length) {
                    if($tarCheckListIp.val().trim().length <= 0) {
                        $tarCheckListId.val('');
                        showError($(this), 'Check List not found!');
                    } else {

                    }
                } else {
                    removeError($(this));
                }
            }
        }).blur(function () {
            var checkListName = $tarCheckListIp.val().trim();

            if (checkListName.length <= 0) {
                $tarCheckListIp.val('');
            } else {
                checkForDuplicateCheckList($tarCheckListIp);
            }
        });

        function checkForDuplicateCheckList($tarCheckListIp) {
            var checkListName = $tarCheckListIp.val().trim();

            $tarCheckListIp.closest('tr').siblings('tr').each(function() {

                if($(this).find('input.check-list-name').val().trim().toLowerCase() == checkListName.toLowerCase()) {
                    showError($tarCheckListIp, 'Check list Already added!');
                    $tarCheckListId.val('');
                    return false;
                }
            });

        }

    });

}

function removeUsedCheckList(arrCheckListCopy, callBack) {
    var $arrUsedCheckList = $checkListWrapper.find('input.check-list-name');

    if ($arrUsedCheckList.length <= 0) {
        callBack(arrCheckListCopy);
        return;
    } else {
        var arrCheckList = [];
        $.each(arrCheckListCopy, function (index, checkList) {
            var isExists = false;
            $arrUsedCheckList.each(function () {
                if ($(this).val().trim().length > 0 && $(this).val().trim().toLowerCase() == checkList.value.toLowerCase()) {
                    isExists = true;
                    return false;
                }
            })

            if (isExists === false) {
                arrCheckList.push(checkList);
            }
        });

        callBack(arrCheckList);
        return;
    }
}

function selectType(typeId){

	$('#workarea').removeClass('hide');
	var psc = $('#psCount').val();
	var tpsc = (parseInt(psc) + parseInt(1));
	$.ajax({	
		url: getBaseURL() + 'crm/project/selectTypeChecklist',
		data: {typeId: typeId, projectId: <?php echo $projectId; ?>},
		type: 'POST',
		success: function(data, status, xhr) {
            $('#paySchTable tbody').html("");
            if(data.arrProjectCheckList == '') {
                addNewRow();
            } else {
                var cntnt = "";
                $.each(data.arrProjectCheckList,function(index, value){

                    cntnt += '<tr class="psClass" id="psRowId_'+tpsc+'">'+
                        '<td class="tbl_input_td"><input type="hidden" id="CheckListId_'+tpsc+'" class="check-list-id" name="CheckList_Id_'+tpsc+'" value="'+value.CheckListId+'" /> <input type="text" id="CheckListName_'+tpsc+'" class="tbl_input check-list-name" name="CheckList_Name_'+tpsc+'" value="'+value.CheckListName+'"/></td>'+
                        '<td class="tbl_input_td">'+
                            '<div class="radio_check">'+
                                '<p>'+
                                    '<input type="radio" value="1" id="timeNeed_'+tpsc+'" name="CheckList_TimeNeed_'+tpsc+'" onclick="return showHideDivShow(\''+tpsc+'\');"';
                    if(value.TimeLine==1) { cntnt += ' checked'; }
                    cntnt +='/>'+
                                    '<label for="timeNeed_'+tpsc+'" class="ripple" style="width:100%;">Yes</label>'+
                                '</p>'+
                                '<p>'+
                                    '<input type="radio" value="0" id="notimeNeed_'+tpsc+'" name="CheckList_TimeNeed_'+tpsc+'" onclick="return showHideDivAll(\''+tpsc+'\');"';
                    if(value.TimeLine==0){ cntnt += ' checked'; }
                    cntnt +='/>'+
                                    '<label for="notimeNeed_'+tpsc+'" class="ripple" style="width:100%;">No</label>'+
                                '</p>'+
                            '</div>'+
                        '</td>'+
                        '<td class="tbl_input_td">'+
                            '<a class="choosendate_a" id="showTag_'+tpsc+'" href="javascript:void(0);" onclick="return showHideDiv(\''+tpsc+'\', \'1\');" ';
                            if(value.TimeLine==0){ cntnt += 'style="display:none;"' ; }
                            cntnt += '"><span><i class="fa fa-pencil-square-o"></i></span> Edit</a>'+
                            '<div id="paySch_'+tpsc+'" class="choosendate_div" style="display:none;">'+
                                '<ul>'+
                                    '<li>'+
                                        '<label for="dateFrom_'+tpsc+'">Date From</label>'+
                                        '<select id="dateFrom_'+tpsc+'" name="CheckList_DateFrom_'+tpsc+'" class="dateFrom" onchange="return dateFromFn(\''+tpsc+'\', this.value)">'+
                                            '<option';
                                            if(value.DateFrom==""){ cntnt += ' selected'; }
                                            cntnt += ' value="0">None</option>'+
                                            '<option ';
                                            if(value.DateFrom=="F"){ cntnt += ' selected'; }
                                            cntnt += ' value="F">Finalize Date</option>'+
                                            '<option';
                                            if(value.DateFrom=="S"){ cntnt += ' selected'; }
                                            cntnt += ' value="S">Start Date</option>'+
                                            '<option';
                                            if(value.DateFrom=="E"){ cntnt += ' selected'; }
                                            cntnt += ' value="E">End Date</option>'+
                                        '</select>'+
                                    '</li>'+
                                    '<li id="radioDiv_'+tpsc+'" style="display:none;">'+
                                        '<div class="radio_check">'+
                                            '<p>'+
                                                '<input type="radio" value="1" id="dateAf_'+tpsc+'" ';
                                                if(value.DateAfterBefore==0){ cntnt +=" checked "; }
                                                cntnt +='name="CheckList_DateAfBef_'+tpsc+'" />'+
                                                '<label for="dateAf_'+tpsc+'" class="ripple" style="width:100%;">Date After</label>'+
                                            '</p>'+
                                            '<p>'+
                                                '<input type="radio" value="2" id="dateBef_'+tpsc+'"  ';
                                                if(value.DateAfterBefore==1){ cntnt +=" checked "; }
                                                cntnt +=' name="CheckList_DateAfBef_'+tpsc+'" />'+
                                                '<label for="dateBef_'+tpsc+'" class="ripple" style="width:100%;">Date Before</label>'+
                                            '</p>'+
                                        '</div>'+
                                    '</li>'+
                                    '<li id="durationDiv_'+tpsc+'" style="display:none;">'+
                                        '<label>Duration</label>'+
                                        '<select tagname="duration" id="duration_'+tpsc+'" name="CheckList_Duration_'+tpsc+'" style="width:80px;">'+
                                            '<option';
                                        if(value.DurationType == 0){ cntnt += ' selected'; }
                                            cntnt +=' value="0">None</option>'+
                                            '<option';
                                        if(value.DurationType == 1){ cntnt += ' selected'; }
                                            cntnt +=' value="1">Day</option>'+
                                            '<option';
                                        if(value.DurationType == 2){ cntnt += ' selected'; }
                                            cntnt += ' value="2">Month</option>'+
                                        '</select>'+
                                        '<input type="text" id="days_'+tpsc+'" class="tbl_input dy_mn_input" name="CheckList_Days_'+tpsc+'" onKeyDown="return special(event);" value="'+value.DurationDays+'" />'+
                                    '</li>'+
                                    '<li id="dateDiv_'+tpsc+'">'+
                                        '<div class="dt_input_div">'+
                                            '<span class="date_icon"><i class="fa fa-calendar"></i></span>'+
                                            '<input type="text" id="date_'+tpsc+'" name="CheckList_Date_'+tpsc+'" class="date_picker tbl_input dt_input" value="'+value.Date+'" />'+
                                        '</div>'+
                                    '</li>'+
                                '</ul>'+
                            '</div>'+
                            '<a class="choosendate_a" id="hideTag_'+tpsc+'" href="javascript:void(0);" onclick="return showHideDiv(\''+tpsc+'\', \'0\');" style="display:none;"><span><i class="fa fa-check-square"></i><span> Ok</a>'+
                        '</td>'+
                        '<td class="action_btns_td">';
                    if(typeof value.isUsed == 'undefined') {
                        cntnt += '<ul class="action_btns">'
                        + '<li>'
                        + '<a href="#" class="delete-checklist">'
                        + '<span data-original-title="Delete" data-placement="left" data-toggle="tooltip"><i class="fa fa-trash-o"></i></span>'
                        + '</a>'
                        + '</li>'
                        + '</ul>';
                    }
                    cntnt += '</td>'
                    + '</tr>';
                    tpsc++;

                })
                $checkListWrapper.append(cntnt);
                bindDatePicker();
                $('#paySchTable .dateFrom').trigger('change');
                $('#psCount').val(tpsc);
            }

            if(data.arrCheckList.length != '') {
                checkListData = data.arrCheckList;
                bindCheckList_autoComplete();
            }
			
		},
		error: function(xhr, status, error) {
			alert(xhr.responseText);
		}
	});
}

function addNewRow() {
	var psc = $psCnt.val();
	var tpsc = (parseInt(psc) + 1);
	$psCnt.val(tpsc);

    $checkListWrapper.append(
		'<tr class="psClass" id="psRowId_'+tpsc+'">'+
			'<td class="tbl_input_td"><input type="hidden" id="CheckListId_'+tpsc+'" class="check-list-id" name="CheckList_Id_'+tpsc+'" value="" /> <input type="text" id="CheckListName_'+tpsc+'" class="tbl_input check-list-name" name="CheckList_Name_'+tpsc+'" value=""/></td>'+
			'<td class="tbl_input_td">'+
				'<div class="radio_check">'+
					'<p>'+
						'<input type="radio" value="1" id="timeNeed_'+tpsc+'" name="CheckList_TimeNeed_'+tpsc+'" onclick="return showHideDivShow(\''+tpsc+'\');" checked/>'+
						'<label for="timeNeed_'+tpsc+'" class="ripple" style="width:100%;">Yes</label>'+
					'</p>'+
					'<p>'+
						'<input type="radio" value="0" id="notimeNeed_'+tpsc+'" name="CheckList_TimeNeed_'+tpsc+'" onclick="return showHideDivAll(\''+tpsc+'\');"/>'+
						'<label for="notimeNeed_'+tpsc+'" class="ripple" style="width:100%;">No</label>'+
					'</p>'+
				'</div>'+
			'</td>'+
			'<td class="tbl_input_td">'+
				'<a class="choosendate_a" id="showTag_'+tpsc+'" href="javascript:void(0);" onclick="return showHideDiv(\''+tpsc+'\', \'1\');"><span><i class="fa fa-pencil-square-o"></i></span> Edit</a>'+
				'<div id="paySch_'+tpsc+'" class="choosendate_div" style="display:none;">'+
					'<ul>'+
						'<li>'+
							'<label for="dateFrom_'+tpsc+'">Date From</label>'+
							'<select id="dateFrom_'+tpsc+'" name="CheckList_DateFrom_'+tpsc+'" class="dateFrom" onchange="return dateFromFn(\''+tpsc+'\', this.value)">'+
								'<option value="0">None</option>'+
								'<option value="F">Finalize Date</option>'+
								'<option value="S">Start Date</option>'+
								'<option value="E">End Date</option>'+
							'</select>'+
						'</li>'+
						'<li id="radioDiv_'+tpsc+'" style="display:none;">'+
							'<div class="radio_check">'+
								'<p>'+
									'<input type="radio" value="1" id="dateAf_'+tpsc+'" name="CheckList_DateAfBef_'+tpsc+'" tagname="dateAfBef" checked />'+
									'<label for="dateAf_'+tpsc+'" class="ripple" style="width:100%;">Date After</label>'+
								'</p>'+
								'<p>'+
									'<input type="radio" value="2" id="dateBef_'+tpsc+'" name="CheckList_DateAfBef_'+tpsc+'" tagname="dateAfBef" />'+
									'<label for="dateBef_'+tpsc+'" class="ripple" style="width:100%;">Date Before</label>'+
								'</p>'+
							'</div>'+
						'</li>'+
						'<li id="durationDiv_'+tpsc+'" style="display:none;">'+
							'<label>Duration</label>'+
							'<select tagname="duration" id="duration_'+tpsc+'" name="CheckList_Duration_'+tpsc+'" style="width:80px;">'+
								'<option value="0">None</option>'+
								'<option value="1">Day</option>'+
								'<option value="2">Month</option>'+
							'</select>'+
							'<input type="text" id="days_'+tpsc+'" class="tbl_input dy_mn_input" onKeyDown="return special(event);" name="CheckList_Days_'+tpsc+'" value="" tagname="days" />'+
						'</li>'+
						'<li id="dateDiv_'+tpsc+'">'+
							'<div class="dt_input_div">'+
								'<span class="date_icon"><i class="fa fa-calendar"></i></span>'+
								'<input type="text" id="date_'+tpsc+'" name="CheckList_Date_'+tpsc+'" class="date_picker tbl_input dt_input" value="" tagname="date" />'+
							'</div>'+
						'</li>'+
					'</ul>'+
				'</div>'+
				'<a class="choosendate_a" id="hideTag_'+tpsc+'" href="javascript:void(0);" onclick="return showHideDiv(\''+tpsc+'\', \'0\');" style="display:none;"><span><i class="fa fa-check-square"></i><span> Ok</a>'+
			'</td>'+
            '<td class="action_btns_td">'
            + '<ul class="action_btns">'
            + '<li>'
            + '<a href="#" class="delete-checklist">'
            + '<span data-original-title="Delete" data-placement="left" data-toggle="tooltip"><i class="fa fa-trash-o"></i></span>'
            + '</a>'
            + '</li>'
            + '</ul>'
            + '</td>'
		+ '</tr>'
	);
	bindDatePicker();

    var $tarCheckListIp = $checkListWrapper.find('#psRowId_'+tpsc+' .check-list-name');
    bindAutoCompleted($tarCheckListIp)
}

function bindDatePicker()
{
	$(".date_picker").datepicker({
		format: 'dd-mm-yyyy'
	});
}
function dateFromFn(tagId, selVal)
{
	if(selVal == 'S' || selVal == 'E') {
		$('#radioDiv_'+tagId).show();
	} else {
		$('#radioDiv_'+tagId).hide();
	}
	
	if(selVal == 0) {
		$('#durationDiv_'+tagId).hide();
		$('#dateDiv_'+tagId).show();
		
		$('#duration_'+tagId).val(0);
		$('#days_'+tagId).val('');
	} else {
		$('#dateDiv_'+tagId).hide();
		$('#durationDiv_'+tagId).show();
		
		$('#date_'+tagId).val('');
	}
}
function showHideDiv(tagId, tagType)
{
	var psc = $('#psCount').val();
	
	if(tagType == 1) {
		for(i=1;i<=psc;i++) {
			if(tagId == i) {
				$('#showTag_'+tagId).hide();
				$('#hideTag_'+tagId).show();
				$('#paySch_'+tagId).show();
			} else {
				$('#paySch_'+i).hide();
				$('#hideTag_'+i).hide();
				$('#showTag_'+i).show();
			}
		}
	} else {
		$('#date_'+tagId).removeClass('red_bdr');
		$('#duration_'+tagId).removeClass('red_bdr');
		$('#days_'+tagId).removeClass('red_bdr');
		if($('#dateFrom_'+tagId).val()=='0') {
			if($('#date_'+tagId).val() == '') {
				$('#date_'+tagId).addClass('red_bdr');
				$('#date_'+tagId).focus();
				return false;
			}
		} else {
			if($('#duration_'+tagId).val() == '0') {
				$('#duration_'+tagId).addClass('red_bdr');
				$('#duration_'+tagId).focus();
				return false;
			} else {
				if($('#days_'+tagId).val() == '') {
					$('#days_'+tagId).addClass('red_bdr');
					$('#days_'+tagId).focus();
					return false;
				}
			}
		}
		
		$('#paySch_'+tagId).hide();
		$('#hideTag_'+tagId).hide();
		$('#showTag_'+tagId).show();
	}
}

function showHideDivAll(tagId)
{
	$('#paySch_'+tagId).hide();
	$('#hideTag_'+tagId).hide();
	$('#showTag_'+tagId).hide();
}
function showHideDivShow(tagId)
{
	var psc = $('#psCount').val();
	for(i=1;i<=psc;i++) {
		if(tagId == i) {
			$('#showTag_'+tagId).hide();
			$('#hideTag_'+tagId).show();
			$('#paySch_'+tagId).show();
		} else {
			var ifYes = $("input[name='timeNeed_"+i+"']:checked").val();
			if(ifYes == 1) {
				$('#paySch_'+i).hide();
				$('#hideTag_'+i).hide();
				$('#showTag_'+i).show();
			}
		}
	}
}

function showReceipt(tagId, tagType)
{
	var psc = $('#psCount').val();
	if(tagType == 1) {
		for(i=1;i<=psc;i++) {
			if(tagId == i) {
				$('#receiptDiv_'+tagId).show();
				$('#hidePerTag_'+tagId).show();
			} else {
				$('#receiptDiv_'+i).hide();
				$('#hidePerTag_'+i).hide();
			}
		}
	} else {
		$('#percentage_'+tagId).removeClass('red_bdr');
		if($('#percentage_'+tagId).val() == '') {
			$('#percentage_'+tagId).addClass('red_bdr');
			$('#percentage_'+tagId).focus();
			return false;
		}
		$('#receiptDiv_'+tagId).hide();
		$('#hidePerTag_'+tagId).hide();
	}
}

function special(e){
	  var key = e.which || e.keyCode;
            if (!e.shiftKey && !e.altKey && !e.ctrlKey &&
                     // numbers   
                         key >= 48 && key <= 57 ||
                     // Numeric keypad
                         key >= 96 && key <= 105 ||
                     // Backspace and Tab and Enter
                        key == 8 || key == 9 || key == 13 ||
                     // Home and End
                        key == 35 || key == 36 ||
                     // left and right arrows
                        key == 37 || key == 39 ||
                     // Del and Ins
                        key == 46 || key == 45){
						return true;}
			else{
                       return false;}
}
</script>
<!--Page Scripts-->
