<?php $bsf = new \BuildsuperfastClass(); ?>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/select2.full.min.js"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/select2.min.css" />
<form action="" method="post" id="form">
    <!--LandCost Calculation-->				
	<div class="content_wrapper padlr0">
		<div class="container-fluid padlr0">
			<div class="col-lg-12">
				<h1 class="float_l">Project Info of
                    <div class="btn-group proname_btn">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"><?php echo ucfirst($projectDetail['ProjectName']);?> <span class="edit_symbols" data-placement="right" data-toggle="tooltip" data-original-title="Choose&nbsp;your&nbsp;project"><i class="fa fa-caret-down "></i></span></a> 							
                        <div class="dropdown-menu toolbar_ddown proname_ddown arrow" role="menu">
                            <ul>
                                <?php foreach($projects as $project){?>
                                    <li><a href="<?php echo $this->basePath(); ?>/crm/project/<?php echo $this->currentRequest()->get('action'); ?>/<?php echo $bsf->encode($project['ProjectId']); ?>"><?php echo ucfirst($project['ProjectName']);?></a></li>
                                <?php }	?>
                            </ul>
                        </div>
                    </div>
				</h1>
                <div class="promote_social float_r">
					<ul>
						<span>Promote Project</span>
						<li><a href="#" class="fb_c ripple"><i class="fa fa-facebook-square"></i></a></li>
						<li><a href="#" class="twt_c ripple"><i class="fa fa-twitter-square"></i></a></li>
						<li><a href="#" class="g_c ripple"><i class="fa fa-google-plus-square"></i></a></li>
					</ul>
				</div>
			</div>
			<div class="col-lg-12 clear">
                <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
                    <div class="col-lg-12">
                        <div class="row">
                            <div class="step_by_liner animated slideInDown"></div>
                            <ul class="step_by stepby_mb60">
                                <li>
                                    <div class="step_by_sep animated_0_4s slideInRight"><p>2</p></div>
                                    <p class="stepli_p1">Area Details</p>
                                </li>
                                <li>
                                    <div class="step_by_sep stepsep_active animated slideInRight"><p>3</p></div>
                                    <p class="stepli_p2">Land Cost Calculation</p>
                                </li>
                                <li class="opacity_08">
                                    <div class="step_by_sep animated_1_5s slideInRight"><p>4</p></div>
                                    <p class="stepli_p3">Other Cost Details</p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="row">
                        <?php if(isset($resultsinfo)&& $resultsinfo['BusinessTypeId']!=3) {?>
                       <div class="form-group col-lg-12">
                            <p class="radio_label txt_center"><label for="UDS">Land Cost - Area based on</label></p>
                            <div class="radio_check col-lg-11 col-lg-offset-1 col-md-8 col-md-offset-2">
                                <p class="col-lg-6">
                                    <input type="radio" name="lcAreaBasedon" id="uds" value="U" <?php if($resultDetail['LCAreaBasedon'] == 'U' || trim($resultDetail['LCAreaBasedon']) == '') { echo 'checked'; } ?>>
                                    <label for="uds">UDS</label>
                                </p>
                                <p class="col-lg-6">
                                    <input type="radio" name="lcAreaBasedon" id="carpetArea" value="C" <?php if($resultDetail['LCAreaBasedon'] == 'C') { echo 'checked'; } ?>>
                                    <label for="carpetArea">Carpet Area</label>
                                </p>
                            </div>
                        </div>
                        <?php } ?>
                    </div>


                    <div class="row">
                       <div class="form-group col-lg-12">
                            <p class="radio_label txt_center"><label class="radio_label" for="guide">Land Cost - Rate based on</label></p>
                            <div class="radio_check col-lg-11 col-lg-offset-1 col-md-8 col-md-offset-2">
                                <p class="col-lg-6">
                                    <input type="radio" name="lcRateBasedon" id="giudeLineValue" value="G" <?php if($resultDetail['LCRateBasedon'] == 'G' || trim($resultDetail['LCRateBasedon']) == '') { echo 'checked'; } ?> >
                                    <label for="giudeLineValue">Guideline Value</label>
                                </p>
                                <p class="col-lg-6">
                                    <input type="radio" name="lcRateBasedon" id="marketValue" value="M" <?php if($resultDetail['LCRateBasedon'] == 'M') { echo 'checked'; } ?>>
                                    <label for="marketValue">Market Value</label>
                                </p>
                            </div>
                        </div>    
                    </div>
                </div>
			</div>
		</div>
	</div>
    <div class="col-lg-12 savebtn_area">
        <ul>
        	<li class="save_btn m_right10 float_r"><input type="submit" name="saveExit" class="ripple continue" value="Save &amp; Exit"/></li>
            <li class="save_btn m_right10 float_r"><input type="submit" name="saveNext" class="ripple continue" value="Save &amp; Next"/></li>
            <li class="goto">
                <label for="go_to" class="float_l">Go to</label> 
                <select id="projectSteps" name="go_to" class="float_l goto_select">
					<option value="general" <?php if($this->currentRequest()->get('action') == 'general') { echo 'selected'; } ?>>General</option>
					<option value="land-area" <?php if($this->currentRequest()->get('action') == 'land-area') { echo 'selected'; } ?>>Area Details</option>
					<option value="land-cost" <?php if($this->currentRequest()->get('action') == 'land-cost') { echo 'selected'; } ?>>Land Cost Calculation</option>
					<option value="other-cost" <?php if($this->currentRequest()->get('action') == 'other-cost') { echo 'selected'; } ?>>Other Cost Details</option>
					<option value="payment" <?php if($this->currentRequest()->get('action') == 'payment-schedule' || $this->currentRequest()->get('action') == 'payment-schedule-edit' || $this->currentRequest()->get('action') == 'payment-schedule-register' || $this->currentRequest()->get('action') == 'payment') { echo 'selected'; } ?>>Payment Schedule</option>
                    <option value="unit-type-register" <?php if($this->currentRequest()->get('action') == 'unit-type-register' || $this->currentRequest()->get('action') == 'unit-type') { echo 'selected'; } ?>>Unit Type</option>
                    <option value="facility" <?php if($this->currentRequest()->get('action') == 'facility' || $this->currentRequest()->get('action') == 'car-park' || $this->currentRequest()->get('action') == 'other-facility') { echo 'selected'; } ?>>Facility Management</option>
					<option value="checklist" <?php if($this->currentRequest()->get('action') == 'checklist') { echo 'selected'; } ?>>Check List Management</option>
					<option value="penality-interestrate" <?php if($this->currentRequest()->get('action') == 'penality-interestrate') { echo 'selected'; } ?>>Penality & Interest Rate</option>
					<option value="incentive-register" <?php if($this->currentRequest()->get('action') == 'incentive-register') { echo 'selected'; } ?>>Incentive Management</option>
				    <option value="property-management" <?php if($this->currentRequest()->get('action') == 'property-management') { echo 'selected'; } ?>>Property Management</option>
				</select> 
                <p class="donecngs_p">Done With Your Changes ?</p>
            </li>
    	</ul>
    </div>
</form>
<script>
//drop down link script//
$("#projectSteps").change(function(){
	window.location.href= getBaseURL() + "crm/project/"+this.value+"/<?php echo $bsf->encode($projectId); ?>";
});
</script>