<style>
    .error_message{
        position:fixed;
    }
</style>

<?php $bsf = new \BuildsuperfastClass(); ?>
<div class="content_wrapper padlr0">
	<div class="container-fluid padlr0">
		<div class="col-lg-12">
			<h1 class="float_l">Project Info of
                <div class="btn-group proname_btn">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"><?php echo ucfirst($projectDetail['ProjectName']);?> <span class="edit_symbols" data-placement="right" data-toggle="tooltip" data-original-title="Choose&nbsp;your&nbsp;project"><i class="fa fa-caret-down "></i></span></a> 							
                    <div class="dropdown-menu toolbar_ddown proname_ddown arrow" role="menu">
                        <ul>
                            <?php foreach($projects as $project){?>
                                <li><a href="<?php echo $this->basePath(); ?>/crm/project/<?php echo $this->currentRequest()->get('action'); ?>/<?php echo $bsf->encode($project['ProjectId']); ?>"><?php echo ucfirst($project['ProjectName']);?></a></li>
                            <?php }	?>
                        </ul>
                    </div>
                </div>
			</h1>
            <div class="promote_social float_r">
                <ul>
                    <span>Promote Project</span>
                    <li><a href="#" class="fb_c ripple"><i class="fa fa-facebook-square"></i></a></li>
                    <li><a href="#" class="twt_c ripple"><i class="fa fa-twitter-square"></i></a></li>
                    <li><a href="#" class="g_c ripple"><i class="fa fa-google-plus-square"></i></a></li>
                </ul>
            </div>
		</div>
		<div class="col-lg-12">
            <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">
                <div class="col-lg-12">
                    <div class="row">
                        <div class="step_by_liner animated slideInDown"></div>
                        <ul class="step_by stepby_mb60">
                            <li>
                                <div class="step_by_sep animated_0_4s slideInRight"><p>4</p></div>
                                <p class="stepli_p1">Other Cost Details</p>
                            </li>
                            <li>
                                <div class="step_by_sep stepsep_active animated slideInRight"><p>5</p></div>
                                <p class="stepli_p2">Payment Schedule</p>
                            </li>
                            <li class="opacity_08">
                                <div class="step_by_sep animated_1_5s slideInRight"><p>6</p></div>
                                <p class="stepli_p3">Unit Type</p>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
		</div>
		<div class="col-lg-12 clear">
			<div class="col-lg-12">
                <div class="kickoff_area col-lg-12 clear cnt_slider" style="min-height:400px;">
                    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                        <!-- Wrapper for slides -->
                        <form class="form-horizontal" method="post" id="paymentScheduleForm">
                            <div class="carousel-inner" role="listbox">
                                <div class="item active">
                                    <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 padlr0 m_btm20 unit_kickoff">
                                    	<div class="unitkkoff_topimg unit_topimg_ps"></div>
                                        <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1 padlr0 m_btm20">
                                            <div class="form-group padtop20">
                                                <input type="text" id="paymentSchedule" name="paymentSchedule" class="form-control lbl_move m_top10" label="Schedule Name" />
                                                <div class="error_message"><p>please enter schedule name...</p></div>
                                            </div>
                                            <div class="form-group">
                                                <select id="scheduleType" name="scheduleType" class="form-control single_dropdown lbl_move" label="Select Schedule Type" style="width:100%;">
                                                    <option value=""></option>
                                                    <?php foreach($scheduleType as $schType) { ?>
                                                        <option value="<?php echo $schType['ScheduleTypeId']; ?>"><?php echo $schType['ScheduleTypeName']; ?></option>
                                                    <?php } ?>
                                                </select>
                                                <div class="error_message"><p>please select schedule type...</p></div>
                                            </div>
											<div class="form-group">
												<select id="roTypes" name="roTypes[]" multiple="multiple" class="form-control multiple_dropdown lbl_move" label="Select Receipt Types" style="width:100%;">
													<?php foreach($receiptTypeMaster as $receiptType) { ?>
													<option value="<?php echo $receiptType['ReceiptTypeId']; ?>#S"><?php echo $receiptType['ReceiptTypeName']; ?></option>
													<?php } ?>
													<?php foreach($otherCostMaster as $otherCost) { ?>
													<option value="<?php echo $otherCost['OtherCostId']; ?>#O"><?php echo $otherCost['OtherCostName']; ?></option>
													<?php } ?>
                                                    <?php if(isset($OtherCostnew)){?>
                                                      <?php foreach($OtherCostnew as $otherCost) { ?>
                                                        <option value="<?php echo $otherCost['OtherCostId']; ?>#O"><?php echo $otherCost['OtherCostName']; ?></option>
                                                    <?php }} ?>

												</select>
												<div class="error_message"><p>please select receipt types...</p></div>
											</div>
											<div class="form-group">
												<label>Booking Advance Included?</label>
												<div class="radio_check">
													<p>
														<input type="radio" value="1" id="advanceIncludedYes" name="advanceIncluded" checked />
														<label for="advanceIncludedYes" class="ripple" style="width:100%;">Yes</label>
													</p>
													<p>
														<input type="radio" value="0" id="advanceIncludedNo" name="advanceIncluded" />
														<label for="advanceIncludedNo" class="ripple" style="width:100%;">No</label>
													</p>
												</div>
											</div>
                                    	</div>    
                                        <div class="col-lg-12 savebtn_area padlr0 marg0 clear">
                                            <ul>
                                                <li class="dropdown save_btn float_r">
                                                    <a class="ripple" href="javascript:void(0);" onclick="return paymentScheduleValidate();" data-toggle="tooltip" data-placement="left" title="Continue">Continue</a>
												</li>	
                                            </ul>
                                        </div>    
                                    </div>
                                </div>
								<div class="item">
									<div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
                                        <div class="table-responsive clear">
											<h1>Selected Receipt Types</h1>
											<table class="table table-hover m_btm0 clear" id="receiptTypeTable">
                                                <thead>
                                                    <tr>
                                                        <th style="width:50px;">Sl. No.</th>
                                                        <th>Name</th>
														<th style="display:none;"></th>
                                                    </tr>
                                                </thead>
                                                <tbody class="sorting">
                                                </tbody>
                                            </table>
										</div>
										<div class="col-lg-12 savebtn_area padlr0 marg0 clear">
                                            <ul>
                                                <li class="dropdown save_btn float_r">
                                                    <a class="ripple" href="javascript:void(0);" onclick="return continueNow();" data-toggle="tooltip" data-placement="left" title="Continue">Continue</a>
												</li>	
                                            </ul>
                                        </div>
									</div>
								</div>
                                <div class="item">
									<div id="percentError" class="error_message" style="right:15px;top:9px;position:fixed;"><p>(it should be equal to 100%...)</p></div>
									<div id="chkboxError" class="error_message" style="position:inherit !important;"><p>(please check booking advance deductible in any one of the stages)</p></div>
									<div class="col-lg-12">
                                        <div id="mainTableDiv" class="table-responsive clear">
                                            <table class="table table-hover m_btm0 clear" id="paySchTable">
                                                <thead>
                                                    <tr>
														<th width="3%">Sl. No.</th>
                                                        <th width="23%">Description</th>
                                                        <th width="8%">Date</th>
                                                        <th width="8%">Round Off</th>
                                                        <th width="15%">Schedule %</th>
														<th width="3%"></th>
                                                    </tr>
                                                </thead>
                                                <tbody class="psSorting">
                                                </tbody>
                                            </table>
                                        </div>
                                        <input type="hidden" id="psCount" name="psCount" value="0" />
										<input type="hidden" id="projectId" name="projectId" value="<?php echo $projectId; ?>" />
										<input type="hidden" id="advBookId" name="advBookId" value="<?php echo $bookingAdvanceMaster['BookingAdvanceId']; ?>" />
										<input type="hidden" id="advBookName" name="advBookName" value="<?php echo $bookingAdvanceMaster['BookingAdvanceName']; ?>" />
                                        <?php $psId = array(); ?>
                                        <div>
                                            <table class="table table-hover m_btm0 clear">
                                                <tbody>
                                                    <tr>
                                                        <td colspan="4"width="48%" style="text-align:right;font-weight:bold;">% Total</td>
                                                        <td width="15%" ><input type="text" class="tbl_input" id="totalPercent" value="" readonly /></td>
                                                        <td width="3%" ></td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                        <a id="addNewId" class="onbrd_addnew ripple float_l" href="javascript:void(0);" onclick="return addNewRow();">Add New</a>
                                        <div class="col-lg-12 savebtn_area padlr0 marg0 clear">
                                            <ul>
                                                <li class="save_btn float_r">
                                                    <a id="submitId" href="#" onclick="return paySchValidate();" data-toggle="tooltip" data-placement="left" class="ripple" title="Submit">submit</a>
                                                    <div id="submit-loader" class="post_loader ask_post_loader brad_50">
                                                        <img title="" alt="" src="/bsf_v1.1/public/images/post-loader.gif">
                                                    </div>
                                                </li>
                                     </ul>
                                        </div>
                                    </div>
                                </div>
								<!-- Controls -->
                                <ul class="prev_next">
                                    <li class="float_l" id="backPrev">
                                        <a href="#carousel-example-generic" data-slide="prev" onclick="return getValueOfSlider('prev');">
                                            <span><i class="fa fa-arrow-left"></i></span>
                                        </a>
                                    </li>
                                    <li class="float_r" id="backNext">
                                        <a href="#carousel-example-generic" role="button" data-slide="next" onclick="return getValueOfSlider('next');">
                                            <span><i class="fa fa-arrow-right"></i></span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>
<div class="col-lg-12 savebtn_area">
	<ul>
		<li class="goto">
			<label for="go_to" class="float_l">Go to</label> 
			<select id="projectSteps" name="go_to" class="float_l goto_select">
				<option value="general" <?php if($this->currentRequest()->get('action') == 'general') { echo 'selected'; } ?>>General</option>
				<option value="land-area" <?php if($this->currentRequest()->get('action') == 'land-area') { echo 'selected'; } ?>>Area Details</option>
				<option value="land-cost" <?php if($this->currentRequest()->get('action') == 'land-cost') { echo 'selected'; } ?>>Land Cost Calculation</option>
				<option value="other-cost" <?php if($this->currentRequest()->get('action') == 'other-cost') { echo 'selected'; } ?>>Other Cost Details</option>
				<option value="payment" <?php if($this->currentRequest()->get('action') == 'payment-schedule' || $this->currentRequest()->get('action') == 'payment-schedule-edit' || $this->currentRequest()->get('action') == 'payment-schedule-register' || $this->currentRequest()->get('action') == 'payment') { echo 'selected'; } ?>>Payment Schedule</option>
                <option value="unit-type-register" <?php if($this->currentRequest()->get('action') == 'unit-type-register' || $this->currentRequest()->get('action') == 'unit-type') { echo 'selected'; } ?>>Unit Type</option>
				<option value="facility" <?php if($this->currentRequest()->get('action') == 'facility' || $this->currentRequest()->get('action') == 'car-park' || $this->currentRequest()->get('action') == 'other-facility') { echo 'selected'; } ?>>Facility Management</option>
				<option value="checklist" <?php if($this->currentRequest()->get('action') == 'checklist') { echo 'selected'; } ?>>Check List Management</option>
				<option value="penality-interestrate" <?php if($this->currentRequest()->get('action') == 'penality-interestrate') { echo 'selected'; } ?>>Penality & Interest Rate</option>
				<option value="incentive-register" <?php if($this->currentRequest()->get('action') == 'incentive-register') { echo 'selected'; } ?>>Incentive Management</option>
			    <option value="property-management" <?php if($this->currentRequest()->get('action') == 'property-management') { echo 'selected'; } ?>>Property Management</option>
			</select>  
		</li>
	</ul>
</div>
<script type="text/javascript">
$('.cnt_slider .carousel').carousel({
	interval: false
});
$(document).ready(function() {
	$(".single_dropdown").select2({
		placeholder: "",
		allowClear: true,
	});
	$(".multiple_dropdown").select2({
	});
});

var paySchA = [];

function paymentScheduleValidate()
{
	$('.error_message').hide();
	var sFlag = 0;
	if($.trim($('#paymentSchedule').val()) == '') {
		$('#paymentSchedule').closest('.form-group').find(".error_message").show();
		$('#paymentSchedule').focus();
		sFlag = 1;
		return false;
	}
	if($('#scheduleType').val() == '') {
		$('#scheduleType').closest('.form-group').find(".error_message").show();
		$('#scheduleType').focus();
		sFlag = 1;
		return false;
	}
	if($("#roTypes option:selected").length == 0){
		$('#roTypes').closest('.form-group').find(".error_message").show();
		$('#roTypes').focus();
		sFlag = 1;
		return false;
	}
	
	if(sFlag == 0) {
		$.post(getBaseURL()+'crm/project/check-name', { psName: $('#paymentSchedule').val() },
		function(data) {
			var chkCount = JSON.parse(data);
			if(chkCount.Count != 0) {
                $('#paymentSchedule').closest('.form-group').find(".error_message").show();
				$('#paymentSchedule').closest('.form-group').find(".error_message").html('<p>Schedule name already exists!</p>');
				$('#paymentSchedule').focus();
			} else {
				getValueOfSlider('next');
				continueNowRT();
				$('#carousel-example-generic').carousel({
					slide: "next"
				});
			}
		});
	}
	return false;
}

function continueNowRT()
{
	$('#receiptTypeTable tbody').html('');
	var rti = 1;
	$('#roTypes :selected').each(function(){
		var roTypo = $(this).val().split("#");
		if(roTypo[1] == 'O') {
			paySchA.push($(this).text());
		}
		$('#receiptTypeTable tbody').append(
			'<tr id="rtRowId_'+rti+'">'+
				'<input type="hidden" id="rtSortId_'+rti+'" name="rtSortId_'+rti+'" value="'+rti+'" />'+
				'<input type="hidden" id="rtTypeId_'+rti+'" name="rtTypeId_'+rti+'" value="'+roTypo[0]+'" />'+
				'<input type="hidden" id="rtTypeType_'+rti+'" name="rtTypeType_'+rti+'" value="'+roTypo[1]+'" />'+
				'<td id="rtRowSlNo_'+rti+'" style="width:50px;">'+rti+'</td>'+
				'<td>'+$(this).text()+'</td>'+
				'<td style="display:none;">'+$(this).val()+'</td>'+
			'</tr>'
		);
		rti++;
	});
}

function continueNow()
{
	$('#paySchTable tbody.psSorting').html('');
	$('#psCount').val(parseInt(0));
	if($('#scheduleType').val() == '1') {
		var advInc = $("input[name='advanceIncluded']:checked").val();
		if(advInc == 1) {
			$('#psCount').val(parseInt(1));
			var tpsc = $('#psCount').val();
			
			var advId = $('#advBookId').val();
			var advName = $('#advBookName').val();
			
			var rta = 1;
			var receiptTypeData = '';
			receiptTypeData += '<div class="choosendate_div">'+
							'<table class="table table-hover m_btm0 clear" id="eachStageTable_'+tpsc+'">'+
								'<tbody class="esSorting">';
			$('#receiptTypeTable tbody tr').each(function() {
				var rtName = $(this).find("td").eq(1).text();
				var rtIddd = $(this).find("td:last").text();
				
				receiptTypeData += '<tr id="esRowId_'+tpsc+'_'+rta+'">'+
										'<input type="hidden" id="receiptType_'+tpsc+'_'+rta+'" name="receiptType_'+tpsc+'_'+rta+'" value="'+rtIddd+'" tagname="receiptType_'+tpsc+'" />'+
										'<input type="hidden" id="esSortId_'+tpsc+'_'+rta+'" name="esSortId_'+tpsc+'_'+rta+'" value="'+rta+'" tagname="esSortId_'+tpsc+'" />'+
										'<td>'+rtName+'</td>'+
									'</tr>';
				rta++;
			});
			receiptTypeData += '</tbody>'+
							'</table>'+
						'</div>';
			
			$('#paySchTable tbody.psSorting').append(
				'<tr class="psClass" id="psRowId_'+tpsc+'">'+
					'<td id="psRowSlNo_'+tpsc+'" style="width:50px;">'+tpsc+'</td>'+
					'<td><input type="hidden" id="scheduleId_'+tpsc+'" name="scheduleId_'+tpsc+'" value="'+advId+'" /> <input type="hidden" id="description_'+tpsc+'" name="description_'+tpsc+'" value="'+advName+'" class="auto-complete" /> '+advName+'</td>'+
					'<td class="tbl_input_td">'+
						'<input type="hidden" id="psSortId_'+tpsc+'" name="psSortId_'+tpsc+'" value="'+tpsc+'" />'+
						'<div class="radio_check">'+
							'<p>'+
								'<input type="radio" value="1" id="advPercent_'+tpsc+'" name="advAmount_'+tpsc+'" checked onclick="return changeType(\'1\');" />'+
								'<label for="advPercent_'+tpsc+'" class="ripple" style="width:100%;">Percentage</label>'+
							'</p>'+
							'<p>'+
								'<input type="radio" value="2" id="advAmt_'+tpsc+'" name="advAmount_'+tpsc+'" onclick="return changeType(\'2\');" />'+
								'<label for="advAmt_'+tpsc+'" class="ripple" style="width:100%;">Amount</label>'+
							'</p>'+
						'</div>'+
					'</td>'+
					'<td class="tbl_input_td"><input type="hidden" id="chosenType_'+tpsc+'" name="chosenType_'+tpsc+'" value="A" /></td>'+
					'<td class="tbl_input_td">'+
						'<div id="amountDiv_'+tpsc+'" style="display:none;"><input type="text" class="tbl_input" id="amount_'+tpsc+'" name="amount_'+tpsc+'" value="" onKeyPress="return isNumberKey(event);" onfocus="return showReceipt(\''+tpsc+'\', \'1\')" /></div>'+
						'<div id="percentDiv_'+tpsc+'">'+
							'<input type="text" class="tbl_input" id="percentage_'+tpsc+'" name="percentage_'+tpsc+'" value="" onfocus="return showReceipt(\''+tpsc+'\', \'1\')" onKeyPress="return isDecimal(event,this);" onblur="return calPercent();" />'+
						'</div>'+	
						'<div id="receiptDiv_'+tpsc+'" style="display:none;">'+
							receiptTypeData+
						'</div>'+
						'<a class="choosendate_a" id="hidePerTag_'+tpsc+'" href="javascript:void(0);" onclick="return showReceipt(\''+tpsc+'\', \'0\');" style="display:none;"><span><i class="fa fa-check-square"></i><span> OK</a>'+
					'</td>'+
					'<td class="tbl_input_td"></td>'+
				'</tr>'
			);
			
			var $esBody = $('table[id*=eachStageTable_'+tpsc+'] tbody.esSorting');
			$esBody.sortable({
				helper: fixHelperModified,
				stop: updateIndex,
				axis: 'y',
				distance: 40,
				update: function( event, ui ) {
					var ifrow = event.target.children[0].id.split("_")[1];
					esSortOrder(tpsc);
				}
			});
		}
		getValueOfSlider('next');
		$('#carousel-example-generic').carousel({
			slide: "next"
		});
	} else {
		$("#paymentScheduleForm").submit();
	}
	bindDatePicker();
}

function addNewRow()
{
	var advInc = $("input[name='advanceIncluded']:checked").val();
	
	var psc = $('#psCount').val();
	var tpsc = (parseInt(psc) + parseInt(1));
	$('#psCount').val(tpsc);
	
	var dateFromData = '';
	var receiptTypeData = '';
	var rta = 1;
	receiptTypeData += '<div class="choosendate_div">'+
							'<table class="table table-hover m_btm0 clear" id="eachStageTable_'+tpsc+'">'+
								'<tbody class="esSorting">';
				$('#receiptTypeTable tbody tr').each(function() {
					var rtName = $(this).find("td").eq(1).text();
					var rtIddd = $(this).find("td:last").text();
					
					receiptTypeData += '<tr id="esRowId_'+tpsc+'_'+rta+'">'+
										'<input type="hidden" id="receiptType_'+tpsc+'_'+rta+'" name="receiptType_'+tpsc+'_'+rta+'" value="'+rtIddd+'" tagname="receiptType_'+tpsc+'" />'+
										'<input type="hidden" id="esSortId_'+tpsc+'_'+rta+'" name="esSortId_'+tpsc+'_'+rta+'" value="'+rta+'" tagname="esSortId_'+tpsc+'" />'+
										'<td>'+rtName+'</td>'+
									'</tr>';
					rta++;
				});
			receiptTypeData += '</tbody>'+
							'</table>';
			if(advInc == 0) {
				receiptTypeData += '<ul><li><div class="radio_check"><p><input type="checkbox" class="tbl_input" id="isAdvanceDeductible_'+tpsc+'" name="isAdvanceDeductible_'+tpsc+'" value="1" tagname="isAdvanceDeductible" /> <label class="ripple" for="isAdvanceDeductible_'+tpsc+'" style="width:100%;">Booking Advance Deductible?</label></p></div></li></ul>';
			}
			receiptTypeData += '</div>';
	
	if(advInc == 0) {
		var idfd = 1;
	} else {
		var idfd = 2;
	}
	if(tpsc > 1) {
		for(dfd=idfd;dfd<(tpsc);dfd++) {
			if($('#scheduleId_'+dfd).val() != '') {
				dateFromData += '<option value="'+$('#scheduleId_'+dfd).val()+'#'+$('#chosenType_'+dfd).val()+'">'+$('#description_'+dfd).val()+'</option>';
			}
		}
	}
	
	$('#paySchTable tbody.psSorting').append(
		'<tr class="psClass" id="psRowId_'+tpsc+'">'+
			'<td id="psRowSlNo_'+tpsc+'">'+tpsc+'</td>'+
			'<td class="tbl_input_td"><input type="hidden" id="scheduleId_'+tpsc+'" name="scheduleId_'+tpsc+'" value="" tagname="scheduleId" /> <input type="text" id="description_'+tpsc+'" name="description_'+tpsc+'" value="" class="auto-complete tbl_input" tagname="description" /></td>'+
			'<td class="tbl_input_td">'+
				'<input type="hidden" id="psSortId_'+tpsc+'" name="psSortId_'+tpsc+'" value="'+tpsc+'" />'+
				'<a class="choosendate_a" id="showTag_'+tpsc+'" href="javascript:void(0);" onclick="return showHideDiv(\''+tpsc+'\', \'1\');"><span><i class="fa fa-pencil-square-o"></i></span> Edit</a>'+
				'<div id="paySch_'+tpsc+'" class="choosendate_div" style="display:none;">'+
					'<ul>'+
						'<li>'+
							'<label for="dateFrom_'+tpsc+'">Date From</label>'+
							'<select id="dateFrom_'+tpsc+'" name="dateFrom_'+tpsc+'" onchange="return dateFromFn(\''+tpsc+'\', this.value)">'+
								'<option value="0">None</option>'+
								'<option value="F">Finalize Date</option>'+
								'<option value="S">Start Date</option>'+
								'<option value="E">End Date</option>'+
								dateFromData+
							'</select>'+
						'</li>'+
						'<li id="radioDiv_'+tpsc+'" style="display:none;">'+
							'<div class="radio_check">'+
								'<p>'+
									'<input type="radio" value="1" id="dateAf_'+tpsc+'" name="dateAfBef_'+tpsc+'" tagname="dateAfBef" checked />'+
									'<label for="dateAf_'+tpsc+'" class="ripple" style="width:100%;">Date After</label>'+
								'</p>'+
								'<p>'+
									'<input type="radio" value="2" id="dateBef_'+tpsc+'" name="dateAfBef_'+tpsc+'" tagname="dateAfBef" />'+
									'<label for="dateBef_'+tpsc+'" class="ripple" style="width:100%;">Date Before</label>'+
								'</p>'+
							'</div>'+
						'</li>'+
						'<li id="durationDiv_'+tpsc+'" style="display:none;">'+
							'<label>Duration</label>'+
							'<select tagname="duration" id="duration_'+tpsc+'" name="duration_'+tpsc+'" style="width:80px;">'+
								'<option value="0">None</option>'+
								'<option value="1">Day</option>'+
								'<option value="2">Month</option>'+
							'</select>'+
							'<input type="text" id="days_'+tpsc+'" class="tbl_input dy_mn_input" name="days_'+tpsc+'" value="" tagname="days" />'+
						'</li>'+
						'<li id="dateDiv_'+tpsc+'">'+
							'<div class="dt_input_div">'+
								'<span class="date_icon"><i class="fa fa-calendar"></i></span>'+
								'<input type="text" id="date_'+tpsc+'" name="date_'+tpsc+'" class="date_picker tbl_input dt_input" value="" tagname="date" />'+
							'</div>'+
						'</li>'+
					'</ul>'+
				'</div>'+
				'<a class="choosendate_a" id="hideTag_'+tpsc+'" href="javascript:void(0);" onclick="return showHideDiv(\''+tpsc+'\', \'0\');" style="display:none;"><span><i class="fa fa-check-square"></i><span> OK</a>'+
			'</td>'+
			'<td class="tbl_input_td"><input type="hidden" id="chosenType_'+tpsc+'" name="chosenType_'+tpsc+'" value="" tagname="chosenType" /><input type="text" class="tbl_input" id="roundOff_'+tpsc+'" name="roundOff_'+tpsc+'" value="" onKeyPress="return isNumberKey(event);" tagname="roundOff" /></td>'+
			'<td class="tbl_input_td">'+
				'<div id="percentDiv_'+tpsc+'">'+
					'<input type="text" class="tbl_input" id="percentage_'+tpsc+'" name="percentage_'+tpsc+'" value="" onfocus="return showReceipt(\''+tpsc+'\', \'1\')" onKeyPress="return isDecimal(event,this);" onblur="return calPercent();" tagname="percentage" />'+
				'</div>'+
				'<div id="receiptDiv_'+tpsc+'" style="display:none;">'+
					'<div id="receiptPerError_'+tpsc+'" class="error_message" style="right:15px;"><p>please select atleast one receipt type...</p></div>'+
					receiptTypeData+
				'</div>'+
				'<a class="choosendate_a" id="hidePerTag_'+tpsc+'" href="javascript:void(0);" onclick="return showReceipt(\''+tpsc+'\', \'0\');" style="display:none;"><span><i class="fa fa-check-square"></i><span> OK</a>'+
			'</td>'+
			'<td class="tbl_input_td">'+
				'<select class="descript_select" id="chooseInsType_'+tpsc+'" name="chooseInsType_'+tpsc+'">'+
					'<option value="0">None</option>'+
					'<option value="S">Stage</option>'+
					'<option value="D">Description</option>'+
				'</select>'+
			'</td>'+
		'</tr>'
	);
	
	var $esBody = $('table[id*=eachStageTable_'+tpsc+'] tbody.esSorting');
	$esBody.sortable({
		helper: fixHelperModified,
		stop: updateIndex,
		axis: 'y',
		distance: 40,
		update: function( event, ui ) {
			var ifrow = event.target.children[0].id.split("_")[1];
			esSortOrder(tpsc);
		}
	});
	
	bindDatePicker();
	bindAutoComplete();
}

function changeType(chTy)
{
	if(chTy==1) {
        $('#amount_1').val('');
		$('#amountDiv_1').hide();
		$('#percentDiv_1').show();
	} else if(chTy==2) {
        $('#percentage_1').val('');
        calPercent();
		$('#percentDiv_1').hide();
		$('#amountDiv_1').show();
	}
}

function showHideDiv(tagId, tagType)
{
	var psc = $('#psCount').val();
	if(tagType == 1) {
		for(i=1;i<=psc;i++) {
			if(tagId == i) {
				$('#showTag_'+tagId).hide();
				$('#hideTag_'+tagId).show();
				$('#paySch_'+tagId).show();
			} else {
				$('#paySch_'+i).hide();
				$('#hideTag_'+i).hide();
				$('#showTag_'+i).show();
			}
		}
	} else {
		$('#date_'+tagId).removeClass('red_bdr');
		$('#duration_'+tagId).removeClass('red_bdr');
		$('#days_'+tagId).removeClass('red_bdr');
		if($('#dateFrom_'+tagId).val() !='0') {
            if($('#date_'+tagId).val() == '0' ){

				$('#date_'+tagId).addClass('red_bdr');
				$('#date_'+tagId).focus();
				return false;
			}
		else {
			if($('#duration_'+tagId).val() == '0') {

				$('#duration_'+tagId).addClass('red_bdr');
				$('#duration_'+tagId).focus();
				return false;
			}
            else if($('#days_'+tagId).val() == '' || 0) {
                    $('#days_'+tagId).addClass('red_bdr');
					$('#days_'+tagId).focus();
					return false;
				}



		}}
       $('#paySch_'+tagId).hide();
		$('#hideTag_'+tagId).hide();
		$('#showTag_'+tagId).show();
	}

}

function dateFromFn(tagId, selVal)
{
	if(selVal == 'S' || selVal == 'E') {
		$('#radioDiv_'+tagId).show();
	} else {
		$('#radioDiv_'+tagId).hide();
	}
	
	if(selVal == 0) {
		$('#durationDiv_'+tagId).hide();
		$('#dateDiv_'+tagId).show();
		
		$('#duration_'+tagId).val(0);
		$('#days_'+tagId).val('');
	} else {
		$('#dateDiv_'+tagId).hide();
		$('#durationDiv_'+tagId).show();
		
		$('#date_'+tagId).val('');
	}
}

function showReceipt(tagId, tagType)
{
	var psc = $('#psCount').val();
	if(tagType == 1) {
		for(i=1;i<=psc;i++) {
			if(tagId == i) {
				$('#receiptDiv_'+tagId).show();
				$('#hidePerTag_'+tagId).show();
			} else {
				$('#receiptDiv_'+i).hide();
				$('#hidePerTag_'+i).hide();
			}
		}
	} else {
		$('#percentage_'+tagId).removeClass('red_bdr');
		if($('#percentage_'+tagId).val() == '') {
			$('#percentage_'+tagId).addClass('red_bdr');
			$('#percentage_'+tagId).focus();
			return false;
		}
		$('#receiptDiv_'+tagId).hide();
		$('#hidePerTag_'+tagId).hide();
	}
}

function bindDatePicker()
{
	$(".date_picker").datepicker({
		format: 'dd-mm-yyyy'
	});
}


function paySchValidate()
{
    // ev.preventDefault();
    $('#submitId').hide();
    $('#submit-loader').show();
   $('.error_message').hide();
	var errFlag = 0;
	var chkFlag = 0;
	if($('#scheduleType').val() == '1') {
		var psc = $('#psCount').val();
		var perCheck = 0;
		var advInc = $("input[name='advanceIncluded']:checked").val();
		
		for(i=1;i<=psc;i++) {
			var perFlag = 0;
			$('#date_'+i).removeClass('red_bdr');
			$('#duration_'+i).removeClass('red_bdr');
			$('#days_'+i).removeClass('red_bdr');
			
			if(i == 1) {
				$('#amount_'+i).removeClass('red_bdr');
				if(advInc == 1) {
					if($("input[name='advAmount_"+i+"']:checked").val() == 2) {
						if($('#amount_'+i).val() == '') {
							$('#amount_'+i).addClass('red_bdr');
							$('#amount_'+i).focus();
							errFlag = 1;
                            $('#submitId').show();
                            $('#submit-loader').hide();
						}
					}
				}
			}
			if($('#description_'+i).val() != '') {
                if($('#scheduleId_'+i).val() == '') {
                    $.post(getBaseURL()+'crm/project/check-stage-name', { descName: $('#description_'+i).val() },
                    function(data) {
                        console.log(data);
                        var chkCount = JSON.parse(data);
                        if(chkCount.dCount != 0 || chkCount.sCount != 0 || chkCount.oCount != 0) {
                            $('#description_'+i).addClass('red_bdr');
                            $('#description_'+i).focus();
                            errFlag = 1;
                            $('#submitId').show();
                            $('#submit-loader').hide();
                        }
                    });
                }
				/*if($('#dateFrom_'+i).val()=='0') {
					if($('#date_'+i).val() == '') {
						$('#date_'+i).addClass('red_bdr');
						$('#date_'+i).focus();
						errFlag = 1;
						$('#showTag_'+i).hide();
						$('#hideTag_'+i).show();
						$('#paySch_'+i).show();
					} else {
						$('#showTag_'+i).show();
						$('#hideTag_'+i).hide();
						$('#paySch_'+i).hide();
					}
				} else {*/
//				if($('#dateFrom_'+i).val()!='0') {
//					if($('#duration_'+i).val() == '0') {
//						$('#duration_'+i).addClass('red_bdr');
//						$('#duration_'+i).focus();
//                        $('#submitId').show();
//                        $('#submit-loader').hide();
//						errFlag = 1;
//						$('#showTag_'+i).hide();
//						$('#hideTag_'+i).show();
//						$('#paySch_'+i).show();
//					} else {
//						if($('#days_'+i).val() == '') {
//							$('#days_'+i).addClass('red_bdr');
//							$('#days_'+i).focus();
//							errFlag = 1;
//							$('#showTag_'+i).hide();
//							$('#hideTag_'+i).show();
//							$('#paySch_'+i).show();
//                            $('#submitId').show();
//                            $('#submit-loader').hide();
//						} else {
//							$('#showTag_'+i).show();
//							$('#hideTag_'+i).hide();
//							$('#paySch_'+i).hide();
//						}
				//	}
			//	}
				
				if($('#percentage_'+i).length > 0 && $('#chosenType_'+i).val() != 'O') {
					if(i == 1 && advInc == 1 && $("input[name='advAmount_"+i+"']:checked").val() == 2) {
						perFlag = 1;
					}
					if(perFlag == 0) {
						if($('#percentage_'+i).val() != '') {
							perCheck = (parseFloat($('#percentage_'+i).val()) + parseFloat(perCheck));
							$('#percentage_'+i).removeClass('red_bdr');

						} else {
							$('#percentage_'+i).addClass('red_bdr');
							$('#percentage_'+i).focus();
                            $('#submitId').show();
                            $('#submit-loader').hide();
							errFlag = 1;
						}
					}
				}
				
				if(advInc == 0) {
					if($('#receiptDiv_'+i).length > 0) {
						if($("input[name='isAdvanceDeductible_"+i+"']:checked").length == 0) {
							chkFlag = chkFlag + 1;
						}
					}
				}
				
				if($('#chooseInsType_'+i).length > 0) {
					if($('#scheduleId_'+i).val() == '') {
						if($('#chooseInsType_'+i).val() == 0) {
							$('#chooseInsType_'+i).addClass('red_bdr');
							$('#chooseInsType_'+i).focus();
							errFlag = 1;
                            $('#submitId').show();
                            $('#submit-loader').hide();
						} else {
							$('#chooseInsType_'+i).removeClass('red_bdr');
						}
					}
				}
			}
		}
		
		if(chkFlag == psc) {
            $('#percentError').show();
            $('#submitId').show();
			$('#chkboxError').show();
			errFlag = 1;
		}
		
		if(errFlag == 0) {
			if(perFlag == 0 && (perCheck > 100 || perCheck < 100)) {
				$('#percentError').show();
                $('#submitId').show();
                $('#submit-loader').hide();
				return false;
			} else {

                $("#paymentScheduleForm").submit();
			}
		}
	} else {
		$("#paymentScheduleForm").submit();
	}

}

/*schedule autocomplete start*/
var psArr = <?php echo json_encode($psResult); ?>;
var psArrCopy = [];
var psId = <?php echo json_encode($psId); ?>;

bindAutoComplete();
function sliceJson(curVal)
{
	$("#paySchTable tbody.psSorting tr.psClass").each(function(){
		var val = $(this).find(".auto-complete").val().trim();
		if(val != "")
			paySchA.push($(this).find(".auto-complete").val());
	});
	
	psArrCopy = $.grep(psArr, function(element, index) {
		if($.inArray(element.value, paySchA) != -1 && element.value != curVal)
			return false;
		return true;
	});
}
function fillPs(json, invoker, mode)
{
	var tr = $(invoker).closest("tr");
	if(mode == 1) {
		if($.inArray(json.data, psId) == -1) {
			psId.push(json.data);
		}
        var curId = tr.find("td:nth-child(1)").html();
		tr.find("td:nth-child(2) input:hidden").val(json.data);
		tr.find("td:nth-child(4) input:hidden").val(json.Type);
		if(json.Type == 'O') {
			//tr.find("td:nth-child(5)").html('');
            $('#percentDiv_'+curId).hide();
            $('#receiptDiv_'+curId).hide();
            $('#hidePerTag_'+curId).hide();
		} else {
            $('#percentDiv_'+curId).show();
            $('#receiptDiv_'+curId).show();
            $('#hidePerTag_'+curId).show();
        }
	} else {
		var hidVal = tr.find("td:nth-child(2) input:hidden").val();
		if(hidVal != '') {
			psId.splice($.inArray(hidVal, psId),1);
		}
		tr.find("td:nth-child(2) input:hidden").val('');
		tr.find("td:nth-child(4) input:hidden").val('');
		//tr.find("td:nth-child(5)").html('');
	}
}
function bindAutoComplete()
{
	$('.auto-complete').unbind();
	$('.auto-complete').autocomplete({
		lookup: <?php echo json_encode($psResult); ?>,
		lookupFilter: function(suggestion, originalQuery, queryLowerCase){
			var re = new RegExp('\\b' + $.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
			return re.test(suggestion.value);
		},
		onSelect: function(suggestion){
			if(suggestion) {
				fillPs(suggestion, this, 1);
				$(this).removeClass('error');
			}
		},
		onSearchStart: function(suggestion) {
		
		},
		onSearchComplete: function (query, suggestion){
			if(!suggestion.length) {
				fillPs('', this, 2);
				$(this).addClass('error');
			} else {
				$(this).removeClass('error');
			}
		}
	});
	
	$('.auto-complete').bind("focus", function(){
		sliceJson($(this).val().trim());
		$(this).autocomplete().setOptions({
			lookup: psArrCopy
		});
	});
	
	/*$('.auto-complete').bind("blur", function(){
		if($.inArray($(this).val(), psArr) == -1){
			fillPs('', this, 2);
			$(this).addClass("error");
		}
	});*/
}
/*schedule autocomplete end*/

$("#projectSteps").change(function(){
	window.location.href= getBaseURL() + "crm/project/"+this.value+"/<?php echo $bsf->encode($projectId); ?>";
});

//receipt type sorting
var $rtBody = $('table[id*=receiptTypeTable] tbody.sorting');

$rtBody.sortable({
	helper: fixHelperModified,
	stop: updateIndex,
	axis: 'y',
	distance: 40,
	update: function( event, ui ) {
		var ifrow = event.target.children[0].id.split("_")[1];
		rtSortOrder();
	}
});

function rtSortOrder()
{
	var rows = $('tr[id*=rtRowId_]');
	var irefid = 1;
	$.each(rows, function() {
		var id = $(this)[0].id;
		var irow = id.split("_")[1];
		$('#rtSortId_'+ irow).val(irefid);
		$('#rtRowSlNo_'+ irow).html(irefid);
		irefid = + irefid+1;
	});
}

//payment schedule sorting
var $psBody = $('table[id*=paySchTable] tbody.psSorting');

$psBody.sortable({
	helper: fixHelperModified,
	stop: updateIndex,
	axis: 'y',
	distance: 40,
	update: function( event, ui ) {
		var ifrow = event.target.children[0].id.split("_")[1];
		psSortOrder();
	}
});

function psSortOrder()
{
	var rows = $('tr[id*=psRowId_]');
	var irefid = 1;
	$.each(rows, function() {
		var id = $(this)[0].id;
		var irow = id.split("_")[1];
		$('#psSortId_'+ irow).val(irefid);
		$('#psRowSlNo_'+ irow).html(irefid);
		irefid = + irefid+1;
	});
}

//Each Stage sorting
function esSortOrder(stId)
{
	var rows = $('tr[id*=esRowId_'+stId+'_]');
	var irefid = 1;
	$.each(rows, function() {
		var id = $(this)[0].id;
		var irow = id.split("_")[2];
		$('#esSortId_'+stId+'_'+ irow).val(irefid);
		irefid = + irefid+1;
	});
}

var fixHelperModified = function(e, tr) {
	var $originals = tr.children();
	var $helper = tr.clone();
	$helper.children().each(function(index) {
		$(this).width($originals.eq(index).width())
	});
	return $helper;
},
updateIndex = function(e, ui) {
	$('td.index', ui.item.parent()).each(function (i) {
		$(this).html(i + 1);
	});
};

function getValueOfSlider(slType)
{
	var currentIndex = $('#carousel-example-generic .item.active').index();
	if(currentIndex == 1 && slType == 'next') {
		$("#backNext").hide();
	} else {
		$("#backNext").show();
	}
	if(currentIndex == 1 && slType == 'prev') {
		$("#backPrev").hide();
	} else {
		$("#backPrev").show();
	}
}

function calPercent(){
    var psc = $('#psCount').val();
    var perCheck = 0;
    for(i=1;i<=psc;i++) {
        if($('#percentage_'+i).length > 0) {
            if($('#percentage_'+i).val() != '') {
                perCheck = (parseFloat($('#percentage_' + i).val()) + parseFloat(perCheck));
                $('#totalPercent').val(parseFloat(perCheck));
            }
        }
    }
}

$("#backPrev").hide();







</script>