<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/select2.full.min.js"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/select2.min.css" />

<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/workorder.css';?>"/>
<style type="text/css">
    .upld_photo_a				{padding:5px 15px; color:#141215; font-size:15px; border:1px solid #141215; display:inline-block;}
    .upld_photo					{width:100%; min-height:150px; float:left; background-color:#fff; display:none;}
    .upld_photo	.thumb_photos 	{width: 31.4%;height: 100px;float: left;margin: 5px 0px 0px 5px;border: 1px solid #e4e4e4;object-fit: cover;}
</style>
<div class="content_wrapper padlr0">
    <div class="container-fluid">
        <div class="row">
            <form id="formWrapper" method="post" enctype="multipart/form-data">
                <input type="hidden" name="csrf" value="<?php echo isset($csrf) ? $csrf : ''; ?>">
                <div class="col-lg-12">
                    <h1 class="text-center" data-bsfhead="Stage Completion">Stage Completion</h1>
                </div>
                <div class="col-lg-12">
                    <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2  prt-next">
                        <div id="level-1" class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 top-next">
                            <div class="form-horizontal">
                                <div class="row">
                                    <div class="form-group">
                                        <div class="col-lg-12">
                                            <input type="text" name="StageCompletionNo" id="StageCompletionNo" class="form-control lbl_move" data-bsfshare="Stage CompletionNo" label="Stage Completion No" value="<?php echo $svNo; ?>" <?php if ($genType==true) { ?> readonly <?php } ?> />
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-lg-12">
                                            <?php if(isset($saveproj)) {  ?>
                                                <input type="text" name="ProjectName" id="ProjectName" class="form-control lbl_move"  data-bsfshare="ProjectName" label="Project Name" value="<?php echo $saveproj['ProjectName']; ?>" disabled  />
                                                <input type="hidden" name="ProjectId" id="ProjectId" value="<?php echo $saveproj['ProjectId']; ?>" />
                                            <?php } else {   ?>

                                                <input type="text" name="ProjectName" id="ProjectName" data-bsfshare="ProjectName" class="form-control lbl_move" label="Project Name"/>
                                                <input type="hidden" name="ProjectId" id="ProjectId"/>
                                            <?php } ?>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-lg-12">
                                            <select name="StageType" id="StageType" class="form-control single_dropdown lbl_move" style="width:100%;" data-bsfshare="Type" label="Select Type">
                                                <option value="S">Stage Wise</option>
                                                <option value="D">Description</option>
                                                <option value="O">Other Cost</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-lg-12">
                                            <input type="text" name="StageName" id="StageName" data-bsfshare="StageName" class="form-control lbl_move" label="Stage Name"/>
                                            <input type="hidden" id="StageId" name="StageId" value="0">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="next-bt"><a href="#" id="show-next-level" class="pull-right">Next <i class="fa fa-chevron-circle-right"></i></a></div>
                        </div>

                        <div id="level-2"
                             class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 top-next hide">
                            <div class="form-horizontal">
                                <div class="row">
                                    <div class="form-group">
                                        <div class="col-lg-12">
                                            <?php if(isset($saveproj)) {  ?>
                                                <input type="text" name="BlockName" id="BlockName" class="form-control lbl_move"  data-bsfshare="BlockName" label="Block Name" value="<?php echo $saveproj['BlockName']; ?>" disabled  />
                                                <input type="hidden" name="BlockId" id="BlockId" value="<?php echo $saveproj['BlockId']; ?>" />
                                            <?php } else {   ?>
                                                <input type="text" name="BlockName" id="BlockName" data-bsfshare="BlockName" class="form-control lbl_move" label="Block Name"/>
                                                <input type="hidden" id="BlockId" name="BlockId" value="0">
                                            <?php } ?>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-lg-12">
                                            <?php if(isset($saveproj)) {  ?>
                                                <input type="text" name="FloorName"  id="FloorName" class="form-control lbl_move"  data-bsfshare="FloorName" label="Floor Name" value="<?php echo $saveproj['FloorName']; ?>" disabled  />
                                                <input type="hidden" name="FloorId" id="FloorId" value="<?php echo $saveproj['FloorId']; ?>" />
                                            <?php } else {   ?>
                                                <input type="text" name="FloorName" id="FloorName" data-bsfshare="FloorName" class="form-control lbl_move" label="Floor Name"/>
                                                <input type="hidden" id="FloorId" name="FloorId" value="0">
                                            <?php } ?>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-lg-12">
                                            <?php if (isset($saveproj)) {  ?>
                                                <input type="text" name="unit_name" class="form-control lbl_move" label="Unit No" data-bsfshare="UnitNo" value="<?php echo $saveproj['UnitNo']; ?>" >
                                                <!--                                                <input type="hidden" name="unit_id" id="unit_id" value="--><?php //echo $saveproj['UnitId']; ?><!--">-->
                                                <input type="hidden" name="Units[]" id="units" value="<?php echo $saveproj['UnitId']; ?>">
                                            <?php } else {  ?>
                                                <select name="Units[]" id="Units" class="form-control multiple_dropdown selectpicker lbl_move nextVal" data-bsfshare="Units" multiple="multiple" label="Select Units" style="width:100%;"></select>
                                            <?php } ?>
                                        </div>
                                        <div style="display:none;" class="pull-right">
                                            <div class="radio_check">
                                                <p>
                                                    <input type="checkbox" value="1" id="select_all_units"/>
                                                    <label for="select_all_units" class="ripple">Select all</label>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                    <!--                                    <div class="form-group">-->
                                    <!--                                        <div class="col-lg-12">-->
                                    <!--                                            <span class="date_icon"><i class="fa fa-calendar"></i></span>-->
                                    <!--                                            <input type="text" name="DueDate" id="DueDate" onchange="validateDate(this)"-->
                                    <!--                                                   class="form-control date_picker lbl_move" label="DueDate"/>-->
                                    <!--                                        </div>-->
                                    <!--                                    </div>-->
                                    <div class="form-group">
                                        <div class="col-lg-12">
                                            <span class="date_icon"><i class="fa fa-calendar"></i></span>
                                            <input type="text" name="CompletionDate" id="CompletionDate" data-bsfshare="CompletionDate" onchange="validateDate(this)"
                                                   class="form-control datepickerinput lbl_move" label="Completed Date"/>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-lg-12">
                                            <label for="buyer" class="txt_left control-label">Do you want to generate progress bill now?</label>
                                            <div class="col-lg-10 col-lg-offset-1">
                                                <div class="radio_check">
                                                    <p>
                                                        <input type="radio" id="buyer" name="ProgressBill" value="1" checked />
                                                        <label for="buyer" class="ripple">Yes</label>
                                                    </p>
                                                    <p>
                                                        <input type="radio" id="investor" name="ProgressBill" value="0"/>
                                                        <label for="investor" class="No">No</label>
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-lg-12">
                                            <a href="#upload_photo" class="file_link ripple upld_photo_a"><span><i class="fa fa-camera"></i></span>
                                                Upload Photo
                                            </a><input type="file" class="file_input" id="files" name="files[]" multiple />
                                            <div id="upload_photo" class="upld_photo">
                                                <div id="upload_photos" class="upload_photos">
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                            <div class="next-bt"><a href="#" id="back-btn" class="pull-left"><i class="fa fa-chevron-circle-left"></i> Back</a> <a id="save-btn" href="#" class="pull-right">Save <i class="fa fa-chevron-circle-right"></i></a>
                                <div id="submit-loader1" class="post_loader ask_post_loader brad_50">
                                    <img title="" alt="" src="/bsf_v1.1/public/images/post-loader.gif">
                                </div></div>
                        </div>

                    </div>
                </div>

            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('.datepickerinput').datepicker({
        format: "dd-mm-yyyy",
        todayBtn: true,
        orientation: "top auto",
        autoclose: true
    });
    $('.date_icon').click(function() {
        var input = $(this).parent().find('input').datepicker('show');
    });
    $(function () {
        // document ready

        var $ProjectName = $('#ProjectName'),
            $ProjectId = $('#ProjectId'),
            $BlockId = $('#BlockId'),
            $BlockName = $('#BlockName'),
            $FloorId = $('#FloorId'),
            $FloorName = $('#FloorName'),
            $Units = $('#Units'),
            $level1 = $('#level-1'),
            $level2 = $('#level-2'),
            $showNextLevelBtn = $('#show-next-level'),
            $StageType = $('#StageType'),
            $StageName = $('#StageName'),
            $StageId = $('#StageId'),
            $CompletionDate = $('#CompletionDate'),
//            $DueDate = $('#DueDate'),
            $saveBtn = $('#save-btn'),
            $stageCompNo = $('#StageCompletionNo');

        $(".single_dropdown").select2({
            placeholder: "",
            allowClear: true
        });

        <?php if(isset($saveproj)){?>
        $ProjectId.trigger('change');
        bindStagesAutoComplete();

        bindStageType_onChange();
        $StageType.trigger('change');


        <?php } ?>

        bindProjectsAutoComplete();
        bindShowNextLevel();
        bindSaveBtn();
        bindBackBtn();
        bindStageCompletionNo_onChange();
        bindStageType_onChange();

        function bindProjectsAutoComplete() {

            disableOtherIps();

            $ProjectName.autocomplete({
                lookup: <?php echo (isset($jsonProjects))?$jsonProjects:'[]'; ?>,
                lookupFilter: function (suggestion, originalQuery, queryLowerCase) {
                    if (queryLowerCase == '*') {
                        return suggestion.value;
                    } else {
                        var re = new RegExp($.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
                        return re.test(suggestion.value);
                    }
                }, onSelect: function (suggestion) {
                    if (suggestion) {
                        $ProjectId.val(suggestion.data);
                        bindStagesAutoComplete();
                        bindStageType_onChange();

                        //  bindBlocksAutoComplete();
                        //  bindLevelsAutoComplete();
                        //  bindUnitsAutoComplete();

                        removeError($(this));
                        enableOtherIps();
                    }
                }, onSearchStart: function (suggestion) {
                    $ProjectId.val('');
                    disableOtherIps();
                }, onSearchComplete: function (query, suggestions) {
                    if (!suggestions.length) {
                        $ProjectId.val('');
                        showError($(this), 'Project not found!');
                        clearOtherIps();
                        disableOtherIps();
                    } else {
                        removeError($(this));
                    }
                }
            }).blur(function () {

                var ProjectName = $ProjectName.val().trim();

                if($ProjectName.hasClass('error')) {
                    $ProjectId.val('0');
                    clearOtherIps();
                }

                if(ProjectName.length <= 0){
                    $ProjectId.val('0');
                    showError($ProjectName, 'Project is required!');
                    clearOtherIps();
                    disableOtherIps();
                }
            }).keypress(function() {
                clearOtherIps();
            });

            function disableOtherIps() {
                $BlockName.attr('disabled', true);
                $FloorName.attr('disabled', true);
                $Units.attr('disabled', true);
            }

            function enableOtherIps() {
                $BlockName.removeAttr('disabled');
                $FloorName.removeAttr('disabled');
                $Units.removeAttr('disabled');
            }

            function clearOtherIps() {
                $BlockName.val('');
                $BlockId.val('');
                $FloorName.val('');
                $FloorId.val('');
                $Units.html('');
                $Units.select2();
            }
        }

        function bindBlocksAutoComplete() {

            var ProjectId = $ProjectId.val();
            var stageId = $StageId.val();

            if (/^\d+$/.test(ProjectId) === false) {
                return;
            }

            $.ajax({
                url: getBaseURL() + 'crm/project/blocks',
                data: { csrf: "<?php echo isset($csrf)?$csrf:''; ?>", ProjectId: ProjectId},
                type: 'POST',
                success: function(data, status, xhr) {
                    bindAutoComplete(data.blocks);
                },
                error: function(xhr, status, error) {
                    alert(xhr.responseText);
                }
            });

            function bindAutoComplete(blocks) {
                // reset data
                $BlockName.unbind('autocomplete');

                $BlockName.autocomplete({
                    lookup: blocks,
                    lookupFilter: function (suggestion, originalQuery, queryLowerCase) {
                        if (queryLowerCase == '*') {
                            return suggestion.value;
                        } else {
                            var re = new RegExp($.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
                            return re.test(suggestion.value);
                        }
                    }, onSelect: function (suggestion) {
                        if (suggestion) {
                            $BlockId.val(suggestion.data);
                            removeError($(this));
                            bindLevelsAutoComplete();
                        }
                    }, onSearchStart: function (suggestion) {
                        $BlockId.val('0');
                    }, onSearchComplete: function (query, suggestions) {
                        if (!suggestions.length) {
                            $BlockId.val('0');
                            clearOtherIps();
                            showError($(this), 'Block not found!');
                        } else {
                            removeError($(this));
                        }
                    }
                }).blur(function () {

                    var BlockName = $BlockName.val().trim();

                    if($BlockName.hasClass('error')) {
                        clearOtherIps();
                        $BlockId.val('0');
                    }

                    if(BlockName.length <= 0){
                        $BlockId.val('0');
                        clearOtherIps();
                        removeError($BlockName);
                    }


                }).keypress(function() {
                    clearOtherIps();
                });

                function clearOtherIps() {
                    $FloorName.val('');
                    $FloorId.val('');
                    $Units.html('');
                    $Units.select2();

                    // bindUnitsAutoComplete();
                }
            }
        }

        function bindLevelsAutoComplete() {

            var ProjectId = $ProjectId.val(),
                BlockId = $BlockId.val();

            if (/^\d+$/.test(ProjectId) === false) {
                return;
            }

            $.ajax({
                url: getBaseURL() + 'crm/project/levels',
                data: { csrf: "<?php echo isset($csrf)?$csrf:''; ?>", ProjectId: ProjectId, BlockId: BlockId },
                type: 'POST',
                success: function(data, status, xhr) {
                    bindAutoComplete(data.levels);
                },
                error: function(xhr, status, error) {
                    alert(xhr.responseText);
                }
            });

            function bindAutoComplete(levels) {
                var temp = new Object();
                temp["data"] = "0";
                temp["value"] = "All";
                levels.push(temp);

                // reset data
                $FloorName.unbind('autocomplete');

                $FloorName.autocomplete({
                    lookup: levels,
                    lookupFilter: function (suggestion, originalQuery, queryLowerCase) {
                        if (queryLowerCase == '*') {
                            return suggestion.value;
                        } else {
                            var re = new RegExp($.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
                            return re.test(suggestion.value);
                        }
                    }, onSelect: function (suggestion) {
                        if (suggestion) {
                            $FloorId.val(suggestion.data);
                            removeError($(this));
                            bindUnitsAutoComplete();
                        }
                    }, onSearchStart: function (suggestion) {
                        $FloorId.val('0');
                    }, onSearchComplete: function (query, suggestions) {
                        if (!suggestions.length) {
                            $FloorId.val('0');
                            clearOtherIps();
                            showError($(this), 'Level not found!');
                        } else {
                            removeError($(this));
                        }
                    }
                }).blur(function () {

                    var FloorName = $FloorName.val().trim();
                    if($FloorName.hasClass('error')) {
                        clearOtherIps();
                        $FloorId.val('0');
                    }

                    if (FloorName.length <= 0 ) {
                        $FloorId.val('0');
                        clearOtherIps();
                        removeError($FloorName);
                    }


                }).keypress(function() {
                    clearOtherIps();
                });

                function clearOtherIps() {
                    $Units.html('');
                    $Units.select2();

                    // bindUnitsAutoComplete();
                }
            }
        }

        function bindUnitsAutoComplete() {

            var ProjectId = $ProjectId.val(),
                BlockId = $BlockId.val(),
                FloorId = $FloorId.val(),
                StageId = $StageId.val(),
                StageType=  $StageType.val();

            if (/^\d+$/.test(ProjectId) === false) {
                return;
            }

            $Units.attr('disabled', true);

            $.ajax({
                url: getBaseURL() + 'crm/project/units',
                data: { csrf: "<?php echo isset($csrf)?$csrf:''; ?>", ProjectId: ProjectId, BlockId: BlockId, FloorId: FloorId ,StageId:StageId,StageType:StageType},
                type: 'POST',
                success: function(data, status, xhr) {
                    if(data.units !=''){
                        bindAutoComplete(data.units);
                    }
                    else{
                        alert("no units found for stage completion");
                    }
                },
                error: function(xhr, status, error) {
                    alert(xhr.responseText);
                }
            });

            function bindAutoComplete(units) {
                // reset data
                $Units.html('');
                $.each(units, function(index, unit) {
                    $Units.append('<option value="' + unit.data +'">' + unit.value +'</option>');
                    $('.pull-right').show();

                });

                $Units.removeAttr('disabled');
            }
        }

        function bindShowNextLevel() {

            $showNextLevelBtn.on('click', function(ev) {
                ev.preventDefault();

                var ProjectName = $ProjectName.val().trim(),
                    ProjectId = $ProjectId.val().trim(),
                    StageCompNo = $stageCompNo.val().trim(),
                    StageName = $StageName.val().trim(),
                    StageId = parseInt($StageId.val());

                $stageCompNo.trigger('change');
                if($stageCompNo.hasClass('error')) {
                    return false;
                } else if(ProjectName.length <= 0 || /^\d+$/.test(ProjectId) == false) {
                    showError($ProjectName, 'Project is required!');}

                else if($stageCompNo.hasClass('error')) {
                    return false;
                }else if (StageName.length <= 0) {
                    showError($StageName, 'Required!');
                    callBack(false);
                    return false;
                } else if(isNaN(StageId)) {
                    showError($StageName, 'Invalid!');
                    callBack(false);
                    return false;

                }
                else if(!$stageCompNo.hasClass('error') && !$StageName.hasClass('error')
                ) {
                    $level1.addClass('hide');
                    $level2.removeClass('hide');
                    bindBlocksAutoComplete();
                }
            });
        }

        function bindBackBtn() {
            $('#back-btn').on('click', function(ev) {
                ev.preventDefault();

                $level1.removeClass('hide');
                $level2.addClass('hide');
            });
        }

        function bindStageType_onChange() {

            $StageType.on('change', function()
            {
                var StageType = $StageType.val();


                switch (StageType) {
                    case 'S':
                        $StageName.siblings('label').text('Stage Name');
                        break;
                    case 'O':
                        $StageName.siblings('label').text('Other Cost Name');
                        break;
                    case 'D':
                        $StageName.siblings('label').text('Description Name');
                        break;
                }

                bindStagesAutoComplete();
            });
        }

        function bindStagesAutoComplete() {

            var ProjectId = $ProjectId.val(),
                BlockId = $BlockId.val(),
                FloorId = $FloorId.val(),
                StageType = $StageType.val(),
                Units = $Units.val();


            if (/^\d+$/.test(ProjectId) === false) {
                return;
            }

            if(StageType.length <= 0) {
                return;
            }

            $.ajax({
                url: getBaseURL() + 'crm/project/stages',
                data: { csrf: "<?php echo isset($csrf)?$csrf:''; ?>", ProjectId: ProjectId, BlockId: BlockId, FloorId: FloorId, StageType: StageType, Units: Units },
                type: 'POST',
                success: function(data, status, xhr) {
                    bindAutoComplete(data.stages);
                },
                error: function(xhr, status, error) {
                    alert(xhr.responseText);
                }
            });


            function bindAutoComplete(stages) {
                // reset data
                $StageName.unbind('autocomplete');
                $StageName.val('');

                $StageName.autocomplete({
                    lookup: stages,
                    lookupFilter: function (suggestion, originalQuery, queryLowerCase) {
                        if (queryLowerCase == '*') {
                            return suggestion.value;
                        } else {
                            var re = new RegExp($.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
                            return re.test(suggestion.value);
                        }
                    }, onSelect: function (suggestion) {
                        if (suggestion) {
                            $StageId.val(suggestion.data);
                            removeError($(this));
                        }
                    }, onSearchStart: function (suggestion) {
                        $StageId.val('0');
                    }, onSearchComplete: function (query, suggestions) {
                        if (!suggestions.length) {
                            $StageId.val('0');
                            showError($(this), 'Name not found!');
                        } else {
                            removeError($(this));
                        }
                    }
                }).blur(function () {
                    var StageName = $StageName.val().trim();

                    if($StageName.hasClass('error')) {
                        $StageId.val('0');
                    }

                    if(StageName.length <= 0) {
                        $StageId.val('0');
                        showError($StageName, 'Required!');
                    }
                });
            }
        }

        function bindSaveBtn() {
            $saveBtn.on('click', function (ev) {

                $('#save-btn').hide();
                $('#submit-loader1').show();
                ev.preventDefault();

                validateForm(function (isSuccess) {

                    if (isSuccess) {

                        $('#formWrapper').submit();
                    }
                    else{
                        $('#save-btn').show();
                        $('#submit-loader1').hide();
                    }
                })
            });

            function validateForm(callBack) {

                var BlockName = $BlockName.val().trim(),
                    FloorName = $FloorName.val().trim(),
                    selUnits = $Units.find('option:selected'),
                    CompletionDate = $CompletionDate.val().trim();

                <?php if(!isset($saveproj)) {  ?>

                if (BlockName.length <= 0) {

                    showError($BlockName, 'Required!');
                    callBack(false);
                    return false;
                }
                else if (FloorName.length <= 0) {

                    showError($FloorName, 'Required!');
                    callBack(false);
                    return false;
                }
                else if (selUnits.length <= 0) {

                    alert('Pls select units');
                    $("#units").focus();
                    callBack(false);
                    return false;
                }

                else if (CompletionDate.length <= 0) {
                    showError($CompletionDate, 'Invalid Completed Date!');
                    callBack(false);
                    return false;

                } else {
                    var photoStatus = $('#photo_status').val();
                    var len = $('#files').prop("files");
                    var length = len.length;
                    var imgCount = 0;
                    if (length == 0) {
                        callBack(true);
                        return true;
                    } else {
                        $.each(len, function (key, input) {
                            var extension = (input.name).split('.').pop().toUpperCase();
                            if (extension != "PNG" && extension != "JPG" && extension != "GIF" && extension != "JPEG") {
                                imgCount = +1;
                            }
                        });
                        if (imgCount == length) {
                            alert('Invalid File Selection');
                            callBack(false);
                            return false;
                        } else if (imgCount > 0) {
                            alert(imgCount + 'Image Upload Failed');
                            callBack(true);
                            return true;
                        } else {
                            callBack(true);
                            return true;
                        }
                    }

                }
                <?php } else {  ?>

                var unitno= $('#unit_no').val();
                console.log(unitno);
                if(unitno==''|| unitno==0 ) {
                    alert("unit no is required");
                    callBack(true);
                    return true;
                }
                else {
                    callBack(true);
                    return true;

                }
                <?php   } ?>
            }}

        function bindStageCompletionNo_onChange() {
            $stageCompNo.on('change', function () {
                var stageCompNo = $stageCompNo.val().trim();

                removeError($stageCompNo);

                if (stageCompNo.length <= 0) {
                    showError($stageCompNo, 'Stage Completion No is Required!');
                    return false;
                }

                $.ajax({
                    url: getBaseURL() + 'crm/project/checkStageCompletionNo',
                    data: {csrf: "<?php echo isset($csrf)?$csrf:''; ?>", StageCompletionNo: stageCompNo},
                    type: 'POST',
                    success: function (data, status, xhr) {
                        if (data.hasOwnProperty('stageCompletion') && data.stageCompletion != false) {
                            showError($stageCompNo, 'Stage Completion No already exists!');
                        }
                    },
                    error: function (xhr, status, error) {
                        alert(xhr.responseText);
                    }
                });
            });
        }

    });
    $(document).on('click','#select_all_units',function() {
        if($("#select_all_units").is(':checked') ){
            $("#Units > option").prop("selected","selected");
            $("#Units").trigger("change");
        }else{
            $("#Units > option").removeAttr("selected");
            $("#Units").trigger("change");
        }
    });
    $(document).on('change','#Units',function() {
        if($('#Units option:selected').length != $('#Units option').length) {
            $("#select_all_units").prop('checked',false);
        } else {
            $("#select_all_units").prop('checked',true);
        }
    });
    function handleFileSelect(evt) {
        $('.upld_photo').hide();
        $('#upload_photos').html('');
        var files = evt.target.files; // FileList object
        // Loop through the FileList and render image files as thumbnails.
        for (var i = 0, f; f = files[i]; i++) {
            // Only process image files.
            if (!f.type.match('image.*')) {
                continue;
            }
            var reader = new FileReader();
            // Closure to capture the file information.
            reader.onload = (function(theFile) {
                return function(e) {
                    // Render thumbnail.
                    var span = document.createElement('span');
                    span.innerHTML = ['<img class="thumb_photos" src="', e.target.result,'" title="', escape(theFile.name), '"/>'].join('');
                    document.getElementById('upload_photos').insertBefore(span, null);
                };
            })(f);
            // Read in the image file as a data URL.
            reader.readAsDataURL(f);
        }
        $('.upld_photo').show();
    }
    document.getElementById('files').addEventListener('change', handleFileSelect, false);
</script>