<?php
$bsf = new \BuildsuperfastClass();
	$url = $this->serverUrl(true);
	$url = array_pop(explode("/", $url));
?>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/select2.full.min.js"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/select2.min.css" />
<?php if(isset($projectDetail)): ?>

<form method="post" role="form" id="unit-type-generation-form">
<input type="hidden" name="csrf" value="<?php echo isset($csrf) ? $csrf : ''; ?>">
<input type="hidden" name="ProjectId" value="<?php echo isset($projectDetail['ProjectId']) ? $projectDetail['ProjectId'] : ''; ?>">
<input type="hidden" name="lcAreaBase" value="<?php echo isset($resultDetail['LCAreaBasedon']) ? $resultDetail['LCAreaBasedon'] : ''; ?>">
<input type="hidden" name="lcRateBase" value="<?php echo isset($resultDetail['LCRateBasedon']) ? $resultDetail['LCRateBasedon'] : ''; ?>">

<input type="hidden" name="redirectUrl" id="redirectUrl" value="">
<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">

        <div class="col-lg-12">
            <h1 class="float_l">Project Info of
                <div class="btn-group proname_btn">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"><?php echo ucfirst($projectDetail['ProjectName']);?> <span class="edit_symbols" data-placement="right" data-toggle="tooltip" data-original-title="Choose&nbsp;your&nbsp;project"><i class="fa fa-caret-down "></i></span></a>
                    <div class="dropdown-menu toolbar_ddown proname_ddown arrow" role="menu">
                        <ul>
                            <?php foreach($projects as $project){?>
                                <li><a href="<?php echo $this->basePath(); ?>/crm/project/<?php echo $this->currentRequest()->get('action'); ?>/<?php echo $bsf->encode($project['ProjectId']); ?>"><?php echo ucfirst($project['ProjectName']);?></a></li>
                            <?php }	?>
                        </ul>
                    </div>
                </div>
			</h1>
            <div class="promote_social float_r">
                <ul>
                    <span>Promote Project</span>
                    <li><a href="#" class="fb_c ripple"><i class="fa fa-facebook-square"></i></a></li>
                    <li><a href="#" class="twt_c ripple"><i class="fa fa-twitter-square"></i></a></li>
                    <li><a href="#" class="g_c ripple"><i class="fa fa-google-plus-square"></i></a></li>
                </ul>
            </div>
        </div> 
        <div class="col-lg-12 clear">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">
                    <div class="col-lg-12">
                        <div class="row">
                            <div class="step_by_liner animated slideInDown"></div>
                            <ul class="step_by stepby_mb60">
                                 <li>
                                    <div class="step_by_sep animated_0_4s slideInRight"><p>5</p></div>
                                    <p class="stepli_p1">Payment Schedule</p>
                                </li>
								<li>
                                    <div class="step_by_sep stepsep_active animated slideInRight"><p>6</p></div>
                                    <p class="stepli_p2">Unit Type</p>
                                </li>
								<li>
                                    <div class="step_by_sep animated_1_5s slideInRight"><p>7</p></div>
                                    <p class="stepli_p3">Facility Management</p>
                                </li>
                                
                               <!-- <li class="opacity_08">
                                    <div class="step_by_sep animated_1_5s slideInRight"><p>3</p></div>
                                    <p class="stepli_p3">Car Park management</p>
                                </li>-->
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 cnt_slider">	
                    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                        <!-- Wrapper for slides -->
                        <div class="carousel-inner" role="listbox">
                            <div class="item active" data-id="1">
                                <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                                    <h1 class="txt_center form_main_h1">Unit Type Area Details</h1>
                                    <?php if(count($arrExistingUnitTypes)>0) {?>
                                    <div class="row">
                                        <div class="form-group col-lg-12">
                                            <select name="copy_unit" id="copy_unit" class="form-control single_dropdown lbl_move" data-size="5" style="width:100%;" onchange="copyUnitType($(this).val());" label="To Copy Existing UnitType...">
                                                <option value="">Select UnitType</option>
                                                <?php if(isset($arrExistingUnitTypes)):
                                                    foreach($arrExistingUnitTypes as $existingUnitTypes): ?>
                                                        <option value="<?php echo $existingUnitTypes['UnitTypeId']; ?>"><?php echo $existingUnitTypes['UnitTypeName']; ?></option>
                                                    <?php endforeach;
                                                endif;?>
                                            </select>
                                        </div>
                                    </div>
                                    <?php } ?>
									<div class="row">   
										<div class="form-group col-lg-12 req_flds">
											<input type="text" id="UnitTypeName" name="UnitTypeName" class="form-control lbl_move" label="Unit Type">
                                            <div class="error_message"><p>Please Enter Unit Type Name...</p></div>
										</div>
									</div>
									<div class="row">   
										<div class="form-group col-lg-12 req_flds">
											<input type="text" class="form-control lbl_move" name="Area" id="Area" label="Area" onKeyPress="return isNumberKey(event)">
											<div class="error_message"><p>Please type the Area...</p></div>
										</div>
									</div>
									<div class="row">   
										<div class="form-group col-lg-12 req_flds">
											<input type="text" class="form-control lbl_move"  name="CarpetArea" id="CarpetArea" onKeyPress="return isNumberKey(event)" label="Carpet Area">
											<div class="error_message"><p>Please type the Carpet Area...</p></div>
										</div>
									</div>
									<div class="row">   
										<div class="form-group col-lg-12 req_flds">
											<input type="text" class="form-control lbl_move"  name="UDSLandArea" id="UDSLandArea" onKeyPress="return isNumberKey(event)" label="UDS Land Area">
											<div class="error_message"><p>Please type the UDS Land Area...</p></div>
										</div>
									</div>
                                </div>
                            </div>
                            <div class="item" data-id="2">
                                <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                                    <h1 class="txt_center form_main_h1"><span class="unittype-name"></span> - Unit Type Cost Details</h1>
									<div class="row">   
										<div class="form-group col-lg-12 req_flds">
											<input type="text" name="Rate" id ="Rate" class="form-control lbl_move"
                                                   label="Rate" onKeyPress="return isNumberKey(event)">
											<div class="error_message"><p>Please Enter the Rate...</p></div>
										</div>
									</div>
<!--									<div class="row">   -->
<!--										<div class="form-group col-lg-12">-->
<!--											<select name="LevelwiseRate" id="LevelwiseRate" class="single_dropdown lbl_move" data-size="5" style="width:100%;" label="Select Level...">-->
<!--											   <option value="">Select Level</option>-->
<!--											   --><?php
//											   foreach($resultsLevel as $level){
//											   echo "<option value='".$level['LevelId']."'>".$level['LevelName']."</option>";
//										}?>
<!--											</select>-->
<!--											<div class="error_message"><p>Please Select the LevelwiseRate...</p></div>-->
<!--										</div>-->
<!--									</div> -->
									<div class="row">   
										<div class="form-group col-lg-12">
											<input type="text" name="BaseAmount" id="BaseAmount"
                                                   class="form-control lbl_move"
                                                   label="Calculated Base Amount" readonly>
										</div>
									</div>
									 <div class="row">   
										<div class="form-group col-lg-12">
                                            <select name="OtherCost[]" id="OtherCost" class="form-control multiple_dropdown lbl_move" multiple="multiple" style="width:100%;" label="Select OtherCost...">
<!--                                                <option value=""></option>-->
                                                <?php if(isset($arrOtherCosts)):
                                                   foreach($arrOtherCosts as $otherCost): ?>
                                                   <option value="<?php echo $otherCost['OtherCostId']; ?>" data-amt="<?php echo $otherCost['Amount']; ?>"> <?php echo $otherCost['OtherCostName']; ?></option>
                                                <?php endforeach;
                                                    endif; ?>
                                            </select>
											<div class="error_message"><p>Please Select the OtherCost...</p></div>
										</div>
									</div>
									<div class="row">   
										<div class="form-group col-lg-12 req_flds">
											<input type="text" name="GuideLineValue" id="GuideLineValue" class="gross form-control lbl_move" onKeyPress="return isNumberKey(event)" label="GuideLineValue">  
											<div class="error_message"><p>Please Enter the GuideLineValue...</p></div>
										</div>
									</div>
									<div class="row">   
										<div class="form-group col-lg-12 req_flds">
											<input type="text" name="MarketLandValue" id="MarketLandValue" class="gross form-control lbl_move" onKeyPress="return isNumberKey(event)" label="MarketLandValue">  
											<div class="error_message"><p>Please Enter the MarketLandValue...</p></div>
										</div>
									</div>
									<div class="row">   
										<div class="form-group col-lg-12">
											<input type="text" name="LandAmount" id="LandAmount" class="form-control lbl_move"
                                                   onKeyPress="return isNumberKey(event)" label="Calculated LandAmount" readonly>
										</div>
									</div>
									<div class="row">   
										<div class="form-group col-lg-12">
											<input type="text" name="ConstructionAmount" id="ConstructionAmount"
                                                   class="form-control lbl_move" onKeyPress="return isNumberKey(event)"
                                                   label="Calculated Construction Amount" readonly>
										</div>
									</div>
									<div class="row">   
										<div class="form-group col-lg-12">
											<input type="text" name="GrossAmount" id="GrossAmount" class="form-control lbl_move"
                                                   onKeyPress="return isNumberKey(event)" label="Calculated Gross Amount" readonly>
											<div class="error_message"><p>Please Enter the GrossAmount...</p></div>
										</div>
									</div>
                                </div>
                            </div>
                            <div class="item" data-id="3">
                                <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                                    <h1 class="txt_center form_main_h1"><span class="unittype-name"></span> - Payable Amount Details</h1>
									<div class="row">   
										<div class="form-group col-lg-12 req_flds">
											<input type="text" name="AdvanceAmount" id="AdvanceAmount" class="Percent form-control lbl_move"
                                                   onKeyPress="return isNumberKey(event)" label="Advance Amount">
											<div class="error_message"><p>Please Enter the AdvanceAmount...</p></div>
										</div>
									</div>
									 <div class="row">   
										<div class="form-group col-lg-12 req_flds">
											<input type="text" name="AdvancePercent" id="AdvancePercent" class="Percent form-control lbl_move"
                                                   onKeyPress="return isNumberKey(event)" label="Advance Percent">
											<div class="error_message"><p>Please Enter the AdvancePercent...</p></div>
										</div>
									</div>
									<div class="row">   
										<div class="form-group col-lg-12 req_flds">
											<input type="text" name="LateInterest" id="LateInterest" class="form-control lbl_move"
                                                   onKeyPress="return isNumberKey(event)" label="Late Interest % (Per Annum)">
											<div class="error_message"><p>Please Enter Late Interest...</p></div>
										</div>
									</div>
									<div class="row">   
										<div class="form-group col-lg-12 req_flds">
											<select name="PaymentSchedule" id="PaymentSchedule" class="single_dropdown lbl_move" data-size="5" style="width:100%;"
                                                    label="Select the PaymentSchedule...">
											    <option value=""></option>
                                                <?php if(isset($arrPaymentSchedules)):
                                                    foreach($arrPaymentSchedules as $paymentSchedule): ?>
                                                        <option value="<?php echo $paymentSchedule['PaymentScheduleId']; ?>"> <?php echo $paymentSchedule['PaymentSchedule']; ?></option>
                                                    <?php endforeach;
                                                endif; ?>
											</select>
											<div class="error_message"><p>Please Select the paymentschedule...</p></div>
										</div>
									</div>
									   <div class="row">   
										<div class="form-group col-lg-12 req_flds">
											<input name="CreditDays" id="CreditDays" type="text" class="form-control lbl_move" label="Credit Days" onKeyPress="return isNumberKey(event)">
											<div class="error_message"><p>Please Enter Credit Days...</p></div>
										</div>
									</div>
                                </div>
                            </div>
                            <!-- Indicators -->
                           <!---- <ol class="carousel-indicators">
                                <li data-target="#carousel-example-generic" data-index="0" class="active"></li>
                                <li data-target="#carousel-example-generic" data-index="1"></li>
                                <li data-target="#carousel-example-generic" data-index="2"></li>
                                <!----<li data-target="#carousel-example-generic" data-slide-to="3"></li>---->
                           <!---- </ol>---->
                            <!-- Controls -->
                            <ul class="prev_next">
                                <li class="float_l">
                                    <a href="javascript:void(0)" class="prevSlide hide">
                                        <span><i class="fa fa-arrow-left"></i></span>
                                    </a>
                                </li>
                              <li class="float_r">
                                    <a href="javascript:void(0)" class="nextSlide" role="button">
                                        <span><i class="fa fa-arrow-right"></i></span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>	
                </div>
            </div>
        </div>
		
    </div>
</div>
<div class="col-lg-12 savebtn_area">
    <ul>
		<li class="dropdown save_btn float_r hide">
			<a href="javascript:void(0);" class="ripple">Save</a>
			<div class="save_trigger">
				<a href="javascript:void(0);" class="ripple" data-toggle="dropdown">
					<i class="fa fa-angle-down"></i>
				</a>
				<ul class="ang_down_ul save_down_ul dropdown-menu dropdown-menu-right">
					<li><a href="car-park" class="ripple continue">Save &amp; Next</a></li>
					<li><a href="" class="ripple continue">Save &amp; Exit</a></li>
				</ul>
			</div>
		</li>
		<li class="cancel_btn float_r">
					<a href="<?php echo $this->basePath(); ?>/crm/index/payment-schedule/<?php echo $bsf->encode($projectId); ?>" class="ripple back">back</a>
		</li>
        <li class="goto">
            <label for="go_to" class="float_l">Go to</label>
            <select id="projectSteps" name="go_to" class="float_l goto_select">
				<option value="general" <?php if($this->currentRequest()->get('action') == 'general') { echo 'selected'; } ?>>General</option>
				<option value="land-area" <?php if($this->currentRequest()->get('action') == 'land-area') { echo 'selected'; } ?>>Area Details</option>
				<option value="land-cost" <?php if($this->currentRequest()->get('action') == 'land-cost') { echo 'selected'; } ?>>Land Cost Calculation</option>
				<option value="other-cost" <?php if($this->currentRequest()->get('action') == 'other-cost') { echo 'selected'; } ?>>Other Cost Details</option>
				<option value="payment" <?php if($this->currentRequest()->get('action') == 'payment-schedule' || $this->currentRequest()->get('action') == 'payment-schedule-edit' || $this->currentRequest()->get('action') == 'payment-schedule-register' || $this->currentRequest()->get('action') == 'payment') { echo 'selected'; } ?>>Payment Schedule</option>
				<option value="unit-type-register" <?php if($this->currentRequest()->get('action') == 'unit-type-generation' || $this->currentRequest()->get('action') == 'unit-type') { echo 'selected'; } ?>>Unit Type</option>
				<option value="facility" <?php if($this->currentRequest()->get('action') == 'facility' || $this->currentRequest()->get('action') == 'car-park' || $this->currentRequest()->get('action') == 'other-facility') { echo 'selected'; } ?>>Facility Management</option>
				<option value="checklist" <?php if($this->currentRequest()->get('action') == 'checklist') { echo 'selected'; } ?>>Check List Management</option>
				<option value="penality-interestrate" <?php if($this->currentRequest()->get('action') == 'penality-interestrate') { echo 'selected'; } ?>>Penality & Interest Rate</option>
				<option value="incentive-register" <?php if($this->currentRequest()->get('action') == 'incentive-register') { echo 'selected'; } ?>>Incentive Management</option>
			    <option value="property-management" <?php if($this->currentRequest()->get('action') == 'property-management') { echo 'selected'; } ?>>Property Management</option>
			</select>
        </li>
    </ul>
</div>
</form>
<?php endif; ?>
<script type="text/javascript">
$('.cnt_slider .carousel').carousel({
 interval: false
})

$('.carousel-indicators li').click(function(){


});

$("#projectSteps").change(function(){
	if(this.value=="unit-type-generation"){
		window.location.href= getBaseURL() + "crm/index/"+this.value+"/<?php echo $bsf->encode($projectId); ?>";
	} else {
		window.location.href= getBaseURL() + "crm/project/"+this.value+"/<?php echo $bsf->encode($projectId); ?>";
	}	
});
</script>

<script type="text/javascript">
    $(function() {

        var $unitTypeName = $('#UnitTypeName'),
            arrExistingUnitTypeNames = <?php echo (isset($jsonExistingUnitTypeNames))?$jsonExistingUnitTypeNames:'[]' ?>,
            $carousel = $('#carousel-example-generic'),
            $Area = $('#Area'),
            $CarpetArea = $('#CarpetArea'),
            $UDSLandArea = $('#UDSLandArea'),
            $BaseAmt = $("#BaseAmount"),
            $GrossAmt = $("#GrossAmount"),
            $MarketLandValue = $("#MarketLandValue"),
            $GuideLineValue = $("#GuideLineValue"),
            $OtherCost = $("#OtherCost"),
            $ConstAmt = $("#ConstructionAmount"),
            $LandAmt = $("#LandAmount"),
            $Rate = $('#Rate'),
            $nextSlide = $('.nextSlide'),
            $prevSlide = $('.prevSlide'),
            $advanceAmt = $('#AdvanceAmount'),
            $advancePercent = $('#AdvancePercent'),
            $LateInt = $('#LateInterest'),
            $PaymentSchedule = $('#PaymentSchedule'),
            $CreditDays = $('#CreditDays');

        init();
        bindUnitTypeName_onChange();
        bindContinue_onClick();
        bindPrev_onClick();
        bindCalculation_onChange();
        bindSaveBtn_onClick();

        function init() {
            $(".single_dropdown").select2({
                placeholder: "",
                allowClear: true
            });

            $OtherCost.select2({
                tags: true
            });
        }

        function bindUnitTypeName_onChange() {
            $unitTypeName.on('change', function() {
                validateUnitTypeName(function(){});
            });
        }

        function validateUnitTypeName(callback) {
            var unitTypeName = $unitTypeName.val().trim();

            removeErrorMsg($unitTypeName);
            if(unitTypeName === '') {
                showErrorMsg($unitTypeName, 'Please Enter Unit Type Name...');
                callback(false);
                return false;
            } else if($.inArray(unitTypeName.toLowerCase(), arrExistingUnitTypeNames) >= 0) {
                showErrorMsg($unitTypeName, 'Unit Type Name already exists...');
                callback(false);
                return false;
            } else {
                callback(true);
                return true;
            }
        }

        function showErrorMsg($tarIp, msg) {
            var $tarErrorMsg = $tarIp.closest('.form-group').find('.error_message');
            $tarErrorMsg.find('p').text(msg);
            $tarErrorMsg.show();
        }

        function removeErrorMsg($tarIp) {
            var $tarErrorMsg = $tarIp.closest('.form-group').find('.error_message');
            $tarErrorMsg.find('p').text('Please Enter ' + $tarIp.attr('label') + '...');
            $tarErrorMsg.hide();
        }

        function bindContinue_onClick() {
            $nextSlide.click(function() {

                var $curActiveItem = $carousel.find('.item.active'),
                    curItemId = $curActiveItem.attr('data-id');

                switch (curItemId) {
                    case '1':
                        validate_step1(function(isSuccess) {
                            if(isSuccess) {
                                $carousel.carousel('next');

                                var unittypeName = $unitTypeName.val().trim();
                                $('.unittype-name').text(unittypeName);

                                $prevSlide.removeClass('hide');
                            }
                        });
                        break;
                    case '2':
                        validate_step2(function(isSuccess) {
                            if(isSuccess) {
                                $carousel.carousel('next');

                                $nextSlide.addClass('hide');

                                $('.save_btn').removeClass('hide');
                            }
                        });
                        break;
                    default :
                        $carousel.carousel('next');
                }
            });
        }

        function bindPrev_onClick() {
            $prevSlide.click(function() {
                var $curActiveItem = $carousel.find('.item.active'),
                    curItemId = $curActiveItem.attr('data-id');

                if(curItemId == '2') {
                    $prevSlide.addClass('hide');
                }

                $nextSlide.removeClass('hide');
                $carousel.carousel('prev');
            });
        }

        function validate_step1(callback) {

            validateUnitTypeName(function(isSuccess) {
                var Area = $Area.val().trim(),
                    CarpetArea = $CarpetArea.val().trim(),
                    UDSLandArea = $UDSLandArea.val().trim();

                if(Area.length <= 0) {
                    showErrorMsg($Area, 'Please Enter Area...');
                    isSuccess = false;
                } else {
                    removeErrorMsg($Area);
                }
                if(CarpetArea.length <= 0) {
                    showErrorMsg($CarpetArea, 'Please Enter Carpet Area...');
                    isSuccess = false;
                } else {
                    removeErrorMsg($CarpetArea);
                }
                if(UDSLandArea.length <= 0) {
                    showErrorMsg($UDSLandArea, 'Please Enter UDS Land Area...');
                    isSuccess = false;
                } else {
                    removeErrorMsg($UDSLandArea);
                }

                callback(isSuccess);
                return isSuccess;

            });
        }

        function validate_step2(callback) {
            var rate = parseFloat($Rate.val()),
                guideLineVal = parseFloat($GuideLineValue.val()),
                marketLandVal = parseFloat($MarketLandValue.val()),
                isSuccess = true;

            if(isNaN(rate)) {
                showErrorMsg($Rate, 'Please Enter Rate...');
                isSuccess = false;
            } else {
                removeErrorMsg($Rate);
            }
            if(isNaN(guideLineVal)) {
                showErrorMsg($GuideLineValue, 'Please Enter Guide Line Value...');
                isSuccess = false;
            } else {
                removeErrorMsg($GuideLineValue);
            }
            if(isNaN(marketLandVal)) {
                showErrorMsg($MarketLandValue, 'Please Enter Market Land Value...');
                isSuccess = false;
            } else {
                removeErrorMsg($MarketLandValue);
            }

            callback(isSuccess);
            return isSuccess;
        }

        function bindCalculation_onChange() {

            $Area.on('change', function() {
                $Rate.trigger('change');
                $CarpetArea.trigger('change');
            });

            // Rate
            $Rate.on('change', function() {
                var BaseAmt = 0,
                    Rate = parseFloat($Rate.val()),
                    Area = parseFloat($Area.val());

                if(!isNaN(Rate) && !isNaN(Area)) {
                    BaseAmt = Area * Rate;
                }
                $BaseAmt.val(BaseAmt.toFixed(2));

                calcConsAmt();
                calcGrossAmt();
            });

            // UDS Land
            $CarpetArea.on('change', function() {
                calcConsAmt();
                calcGrossAmt();
            });

            // Carpet Area
            $UDSLandArea.on('change', function() {
                calcConsAmt();
                calcGrossAmt();
            });

            // Market value
            $MarketLandValue.on('change', function () {
                calcConsAmt();
                calcGrossAmt();
            });

            // Guide line
            $GuideLineValue.on('change', function() {
                calcConsAmt();
                calcGrossAmt();
            });

            $OtherCost.on('change', function() {
                calcGrossAmt();
            });


            function calcConsAmt() {
                var GuideLineVal = parseFloat( isNullCheck($GuideLineValue.val(),'number')),
                    MarketVal = parseFloat(isNullCheck($MarketLandValue.val(),'number')),
                    UDSLandArea = parseFloat(isNullCheck($UDSLandArea.val(),'number')),
                    dCarpetLandArea = parseFloat(isNullCheck($CarpetArea.val(),'number')),
                    LandAmt= 0,
                    dArea= 0,
                    dRate=0;

                if ($('#lcAreaBase').val() == "C") dArea =dCarpetLandArea;
                else dArea = UDSLandArea;

                if ($('#lcRateBase').val() == "M") dRate = MarketVal;
                else dRate = GuideLineVal;

                LandAmt = dArea * dRate;
                $LandAmt.val(LandAmt.toFixed(2));

                var dBaseAmt = parseFloat(isNullCheck($BaseAmt.val(),'number'));
                var dContAmt = dBaseAmt - LandAmt;
                if (dContAmt <0)  dContAmt=0;
                $ConstAmt.val(dContAmt.toFixed(2));
            }


            function calcGrossAmt() {
                var LandAmt = parseFloat(isNullCheck($LandAmt.val(),'number')),
                    ConstAmt = parseFloat(isNullCheck($ConstAmt.val(),'number'));

                var $arrSelOptions = $OtherCost.find('option:selected');
                var totOtherCosts = 0;
                $arrSelOptions.each(function() {
                    totOtherCosts += parseFloat($(this).attr('data-amt'));
                });

                if(isNaN(LandAmt)) {
                    LandAmt = 0;
                }

                if(isNaN(ConstAmt)) {
                    ConstAmt = 0;
                }

                var GrossAmt = LandAmt + ConstAmt + totOtherCosts;
                $GrossAmt.val(GrossAmt.toFixed(3));
            }

            $advanceAmt.on('change', function() {
                var BaseAmt = parseFloat($BaseAmt.val()),
                    advAmt = parseFloat($advanceAmt.val()),
                    advPercentage = 0;

                if(BaseAmt < advAmt) {
                    showErrorMsg($advanceAmt, 'Advance Amount cannot exceed Base Amount...');
                } else {
                    removeErrorMsg($advanceAmt);
                    if(!isNaN(BaseAmt) && !isNaN(advAmt) && BaseAmt != 0) {
                        advPercentage = (advAmt / BaseAmt) * 100;
                    }
                }

                $advancePercent.val(advPercentage.toFixed(2));
            });

            $advancePercent.on('change', function() {
                var BaseAmt = parseFloat($BaseAmt.val()),
                    advAmt = 0,
                    advPercentage = parseFloat($advancePercent.val());

                if (advPercentage > 100) {
                    showErrorMsg($advancePercent, 'Advance Percent cannot exceed 100...');
                } else {
                    removeErrorMsg($advancePercent);
                    if (!isNaN(BaseAmt) && !isNaN(advPercentage)) {
                        advAmt = (BaseAmt * advPercentage) / 100;
                    }
                }

                $advanceAmt.val(advAmt.toFixed(2));
            });
        }


        function bindSaveBtn_onClick() {
            $('.continue').on('click', function(ev) {
                ev.preventDefault();

                var $this = $(this),
                    $unitTypeGenForm = $('#unit-type-generation-form');
                validate_step3(function(isSuccess) {
                    if(isSuccess) {
                        if($this.attr('href') != '#') {
                            $('#redirectUrl').val($this.attr('href'));
                        }
                        $unitTypeGenForm.submit();
                    }
                });

            });
        }

        function validate_step3(callback) {
            var advAmt = parseFloat($advanceAmt.val()),
                advPer = parseFloat($advancePercent.val()),
                LateInt = parseFloat($LateInt.val()),
                PaymentSchedule = $PaymentSchedule.val(),
                CreditDays = parseInt($CreditDays.val()),
                isSuccess = true;

            if (isNaN(advAmt)) {
                isSuccess = false;
                showErrorMsg($advanceAmt, 'Please Enter Advance Amount...');
            } else {
                removeErrorMsg($advanceAmt);
            }

            if (isNaN(advPer)) {
                isSuccess = false;
                showErrorMsg($advancePercent, 'Please Enter Advance Percentage...');
            } else {
                removeErrorMsg($advancePercent);
            }

            if (isNaN(LateInt)) {
                isSuccess = false;
                showErrorMsg($LateInt, 'Please Enter Late Interest...');
            } else {
                removeErrorMsg($LateInt);
            }

            if (PaymentSchedule.length <= 0) {
                isSuccess = false;
                showErrorMsg($PaymentSchedule, 'Please Select Payment Schedule...');
            } else {
                removeErrorMsg($PaymentSchedule);
            }

            if (isNaN(CreditDays)) {
                isSuccess = false;
                showErrorMsg($CreditDays, 'Please Enter Credit Days...');
            } else {
                removeErrorMsg($CreditDays);
            }

            callback(isSuccess);
            return isSuccess;

        }
    });
    function copyUnitType(unitTypeId) {
        if(unitTypeId!="") {
            $.ajax({
                url: getBaseURL() + "crm/project/unit-type-generation",
                type: "POST",
                data: {'copyUnitTypeId': unitTypeId ,csrf: "<?php echo isset($csrf)?$csrf:''; ?>"},
                success: function (data, textStatus, jqXHR) {
                    if (jqXHR.status == 200) {
                        var result = JSON.parse(data);
                        var unitTypeMaster = result[0];
                        var unitTypeDetails = result[1];
                        var unitTypeOtherCost = result[2];
                        if(unitTypeMaster!=false && unitTypeMaster!=null) {
                            $('#Area').val(unitTypeMaster['Area']);
                        }
                        if(unitTypeDetails!=false && unitTypeDetails!=null) {
                            $('#CarpetArea').val(unitTypeDetails['CarpetArea']);
                            $('#UDSLandArea').val(unitTypeDetails['UDSLandArea']);
                            $('#Rate').val(unitTypeDetails['Rate']);
                            $('#BaseAmount').val(unitTypeDetails['BaseAmt']);
                            $("#GuideLineValue").val(unitTypeDetails['GuideLineValue']);
                            $("#MarketLandValue").val(unitTypeDetails['MarketLandValue']);
                            $("#LandAmount").val(unitTypeDetails['LandAmount']);
                            $("#ConstructionAmount").val(unitTypeDetails['ConstructionAmount']);
                            $("#GrossAmount").val(unitTypeDetails['GrossAmt']);
                            $("#AdvanceAmount").val(unitTypeDetails['AdvAmount']);
                            $("#AdvancePercent").val(unitTypeDetails['AdvPercent']);
                            $("#LateInterest").val(unitTypeDetails['IntPercent']);
                            $("#PaymentSchedule option[value="+unitTypeDetails['PaymentScheduleId']+"]").attr("selected", true).trigger('change');
                            $("#CreditDays").val(unitTypeDetails['CreditDays']);
                        }
                        if(unitTypeOtherCost.length>0) {
                            $.each(unitTypeOtherCost,function(i,o) {
                                $("#OtherCost option[value="+ o.OtherCostId+"]").attr("selected", true);
                            });
                            $("#OtherCost").trigger('change');
                        }

                    } else
                        alert(jqXHR.responseText);
                },
                error:function(jqXHR, textStatus, errorThrown){
                    alert('Failed to Process....');
                }

            });
        }
    }

</script>