<?php
	$url = $this->serverUrl(true);
	$url = array_pop(explode("/", $url));
?>
<div class="content_wrapper  padlr0">
	<div class="container-fluid">
		<form name="unit-type-generation" action="" method="post" role="form" id="unit-type-generation">
			<!----START---->
			<input type="hidden" name="unitTypeId" id="unitTypeId" value="<?php echo $unitTypeId; ?>">
			<div class="panel-group commargin_top" id="accordion" role="tablist" aria-multiselectable="true">
				<div class="panel panel-default">
					<div class="panel-heading accordion_head " style="cursor:pointer" role="tab" id="heading11"  data-toggle="collapse" data-parent="#accordion" href="#collapse11" aria-expanded="false" aria-controls="collapse11">
						<h4>Select Checklist...</h4>
					</div>
					<div id="collapse11" class="panel-collapse collapse" role="tabpanel" style="height:485px; overflow: hidden;" aria-labelledby="heading11">
						<div class="panel-body">
							<div class="col-lg-12 col-md-8">									
								<div class="card">
									<div class="card-body">
									<!--checkboxtabel-->              
										<ul class="vendor_subscriber appendDiv" id="checkListAppend" >			
											<?php	$loc = array();
											foreach($checkResult as $city){	?>
											<li>
												<div class="rdochck_subscrb radio_check">
													<p style="padding:0px !important;">
														<input type="checkbox" class="listCheck check<?php echo $city['CheckListId'];?>"  cname="<?php echo $city['CheckListName'];?>" name="customize1_<?php echo $city['CheckListId'];?>" id="customize1_<?php echo $city['CheckListId'];?>" value="<?php echo $city['CheckListId'];?>" <?php echo (($city['Sel'] == 'Y')?'checked="checked"': '');?>/>
														<?php
														if($city['Sel'] == 'Y'){
															array_push($loc, $city['CheckListId']);
														}
														?>
														<label for="customize1_<?php echo $city['CheckListId'];?>" class="ripple"><?php echo $city['CheckListName'];?>													
														</label>
													</p>																							
												</div>											
											</li>						  						  
											<?php	}
												$locArr = implode(",", $loc);?>	
											<input type="hidden" name="hidlocId" id="hidlocId" value="<?php echo $locArr; ?>">									
										</ul>
										<!--end of checkboxtabel-->               
									</div>
								</div>
								<div class="col-lg-12" style="margin-top:23px; margin-bottom:28px;">
									<a href="javascript:void(0);" class="vendor_addnew" id="addChecklistView">Add CheckList</a>
								</div> 
								<div class="col-lg-12 clear" id="addCheckList" style="display:none;">
									<div class="table-responsive clear">
										<!--<div class="col-lg-12">
										<a href="#" class=" vendor_addnew" id="addCert">Addnew</a>
										</div>-->
										<div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
											<table class="table table-hover vendar_bottom clear" id="CheckListTable">
												<thead>
													<tr>
														<th>Description</th>
														<th></th>
													</tr>
												</thead>
												<tbody>									
												</tbody>
											</table>
											<div class="row">   
												<div class="form-group col-lg-12">
													<div class="col-lg-6 col-md-6">
														<a href="javascript:void(0);" class="vendor_addnew float_l" onClick="$('#addCheckList').slideUp('slow');">Cancel</a>
													</div>
													<div class="col-lg-6 col-md-6">   
														<a href="javascript:void(0);" class="vendor_addnew float_r addExternal" id="newCheckList" >Submit</a> 
													</div>     
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class='row'>
									<div class='col-lg-12'>
										<table id="appendTableCheck" class="table table-bordered table-hover">
											<thead>
											</thead>
											<tbody>
												<?php
													//$check = array();
													foreach($responseCheck as $check){
														echo"<tr id='demo_".$check['CheckListId']."'>
																<th>".$check['CheckListName']."</th>
																<td><input class='form-control' type='hidden' name='CheckListName_".$check['CheckListId']."' id='CheckListName_".$check['CheckListId']."'value='".$check['CheckListName']."'/>
																	<input class='form-control' type='text' name='ExpCompletionDate_".$check['CheckListId']."' id='ExpCompletionDate' value='".$check['ExpCompletionDate']."'/></td>
																<td><input class='form-control' type='text' name='CompletionDate_".$check['CheckListId']."' id='CompletionDate' value='".$check['CompletionDate']."'/></td>
																<td><input class='form-control' type='text' name='RefNo_".$check['CheckListId']."' id='RefNo' value='".$check['RefNo']."'/></td>
														</tr>";
														//if($city['Sel'] == 'Y')
														//	array_push($check, $city['CheckListId']);
													}
													//$locArr = implode(",", $check);
												?>
											</tbody>
										</table>
									</div>
								</div>
							</div>           
							<!--end of scrollbar-->        
						</div>
						<!--end .card-body -->
					</div>
					<!--end .card -->
				</div>
				<div class="panel panel-default">
					<div class="panel-heading accordion_head " style="cursor:pointer" role="tab" id="heading12" data-toggle="collapse" data-parent="#accordion" href="#collapse12" aria-expanded="false" aria-controls="collapse12">
						<h4>Select ExtraItems</h4>
					</div>
					<div id="collapse12" class="panel-collapse collapse" role="tabpanel" style="height:485px; overflow: hidden;" aria-labelledby="heading11">
						<div class="panel-body">
							<div class="col-lg-12 col-md-8">									
								<div class="card">
									<div class="card-body">
									<!--checkboxtabel-->              
										<ul class="vendor_subscriber appendDiv" id="extraItemAppend" >			
											<?php
											$extr = array();
												foreach($extraResult as $extra){
											?>																
											<li class="<?php  //echo (($extra['Sel'] == 'Y')?'subscriber_active': '');?>">
												<div class="rdochck_subscrb radio_check">
													<p style="padding:0px !important;">
														<input type="checkbox" class="extraCheck extra<?php echo $extra['ExtraItemId'];?>"  ename="<?php echo $extra['ItemDescription'];?>" name="customize1_<?php echo $extra['ExtraItemId'];?>" id="customize1_<?php echo $extra['ExtraItemId'];?>" value="<?php echo $extra['ExtraItemId'];?>" <?php echo (($extra['Sel'] == 'Y')?'checked="checked"': '');?>/>
														<?php
														if($extra['Sel'] == 'Y')
														{
															array_push($extr, $extra['ExtraItemId']);
														}
														?>
														<label for="customize1_<?php echo $extra['ExtraItemId'];?>" class="ripple"><?php echo $extra['ItemDescription'];?>													
														</label>
													</p>																							
												</div>											
											</li>						  						  
											<?php
											}
											$extrArr = implode(",", $extr);
											?>	
											<input type="hidden" name="hidextraId" id="hidextraId" value="<?php echo $extrArr; ?>">
										</ul>
										<!--end of checkboxtabel-->               
									</div>
								</div>
								<div class="col-lg-12" style="margin-top:23px; margin-bottom:28px;">
									<a href="javascript:void(0);" class="vendor_addnew" id="addExtraItemView">Add Extra Items</a>
								</div> 
								<div class="col-lg-12 clear" id="addExtraItems" style="display:none;">
									<div class="table-responsive clear">
										<!--<div class="col-lg-12">
										<a href="#" class=" vendor_addnew" id="addCert">Addnew</a>
										</div>-->
										<div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
											<table class="table table-hover vendar_bottom clear" id="extraItemTable">
											<thead>
											<tr>
											<th>Description</th>
											<th></th>
											</tr>
											</thead>
											<tbody>									
											</tbody>
											</table>
											<div class="row">   
												<div class="form-group col-lg-12">
													<div class="col-lg-6 col-md-6">
														<a href="javascript:void(0);" class="vendor_addnew float_l" onClick="$('#addExtraItems').slideUp('slow');">Cancel</a>
													</div>
													<div class="col-lg-6 col-md-6">   
														<a href="javascript:void(0);" class="vendor_addnew float_r addExternal" id="newExtraItem" >Submit</a> 
													</div>     
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class='row'>
							<div class='col-lg-12'>
								<table id="appendTableExtra" class="table table-bordered table-hover">
									<thead>
									</thead>
									<tbody>
									<?php
										//$check = array();
										// print_r($responseExtra);
										foreach($responseExtra as $extra){
														echo"<tr id='ext_".$extra['ExtraItemId']."'>
																<th>".$extra['ItemDescription']."</th>
																<td><input class='form-control' type='hidden' name='ItemDescription_".$extra['ExtraItemId']."' id='ItemDescription' value='".$extra['ItemDescription']."'/>
																	<input class='form-control' type='text' name='ExtraRate_".$extra['ExtraItemId']."' id='ExtraRate' value='".$extra['ExtraRate']."'/></td>
																<td><input class='form-control' type='text' name='Qty_".$extra['ExtraItemId']."' id='Qty' value='".$extra['Qty']."'/></td>
																<td><input class='form-control' type='text' name='Amount_".$extra['ExtraItemId']."' id='Amount' value='".$extra['Amount']."'/></td>
																<td><input class='form-control' type='text' name='NetAmount_".$extra['ExtraItemId']."' id='NetAmount' value='".$extra['NetAmount']."'/></td>
														</tr>";
											//if($city['Sel'] == 'Y')
											//	array_push($check, $city['CheckListId']);
										}
										//$locArr = implode(",", $check);
									?>
									</tbody>
								</table>
							</div>
						</div>
							</div>           
							<!--end of scrollbar-->        
						</div>
						<!--end .card-body -->
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading accordion_head " style="cursor:pointer" role="tab" id="heading13"  data-toggle="collapse" data-parent="#accordion" href="#collapse13" aria-expanded="false" aria-controls="collapse13">
						<h4>Select Feature</h4>
					</div>
					<div id="collapse13" class="panel-collapse collapse" role="tabpanel" style="height:485px; overflow: hidden;" aria-labelledby="heading13">
						<div class="panel-body">
							<div class="col-lg-12 col-md-8">
								<div class="card">
									<div class="card-body">
									<!--checkboxtabel-->              
										<ul class="vendor_subscriber appendDiv" id="featureAppend">
											<?php
											$fer = array();
											foreach($featureResult as $feature){
											?>																
											<li>
												<div class="rdochck_subscrb radio_check">
													<p style="padding:0px !important;">
														<input type="checkbox" class="featureCheck feature<?php echo $feature['FeatureId'];?>" fname="<?php echo $feature['FeatureDesc'];?>" name="customize2_<?php echo $feature['FeatureId'];?>" id="customize2_<?php echo $feature['FeatureId'];?>" value="<?php echo $feature['FeatureId'];?>" <?php echo (($feature['Sel'] == 'Y')?'checked="checked"': '');?>/>
														<?php
														if($feature['Sel'] == 'Y')
														{
															array_push($fer, $feature['FeatureId']);
														}
														?>
														<label for="customize2_<?php echo $feature['FeatureId'];?>" class="ripple"><?php echo $feature['FeatureDesc'];?>													
														</label>
													</p>																					
												</div>											
											</li>						  						  
											<?php
											}
											$featArr = implode(",", $fer);
											?>	
											<input type="hidden" name="hidFeatureId" id="hidFeatureId" value="<?php echo $featArr; ?>">																	
										</ul>
										<!--end of checkboxtabel-->               
									</div>
								</div>
								<div class="col-lg-12" style="margin-top:23px; margin-bottom:28px;">
									<a href="javascript:void(0);" class="vendor_addnew" id="addFeatureView">Add Feature</a>
								</div> 
								<div class="col-lg-12 clear" id="addFeature" style="display:none;">
									<div class="table-responsive clear">
										<!--<div class="col-lg-12">
											<a href="#" class=" vendor_addnew" id="addTrans">Add</a>
										</div>-->
										<div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
											<table class="table table-hover vendar_bottom clear" id="featureTable1">
												<thead>
													<tr>
													<th>Description</th>
													<th></th>
													</tr>
												</thead>
												<tbody>
												</tbody>
											</table>
											<div class="row">   
												<div class="form-group col-lg-12">
													<div class="col-lg-6 col-md-6">
														<a href="javascript:void(0);" class="vendor_addnew float_l" onClick="$('#addFeature').slideUp('slow');">Cancel</a>
													</div>
													<div class="col-lg-6 col-md-6">   
														<a href="javascript:void(0);" class="vendor_addnew float_r addExternal" id="newFeatureItem" >Save</a> 
													</div>     
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class='row'>
									<div class='col-lg-12'>
										<table id="featureTable" class="table table-bordered table-hover">
											<thead>
											</thead>
											<tbody>
												<?php
													//$check = array();
													foreach($responseCheck as $check){
														echo"<tr id='fxt_".$check['CheckListId']."'>
																<th>".$check['CheckListName']."</th>
																<td><input class='form-control' type='hidden' name='CheckListName_".$check['CheckListId']."' id='CheckListName_".$check['CheckListId']."'value='".$check['CheckListName']."'/>
																	<input class='form-control' type='text' name='ExpCompletionDate_".$check['CheckListId']."' id='ExpCompletionDate' value='".$check['ExpCompletionDate']."'/></td>
																<td><input class='form-control' type='text' name='CompletionDate_".$check['CheckListId']."' id='CompletionDate' value='".$check['CompletionDate']."'/></td>
																<td><input class='form-control' type='text' name='RefNo_".$check['CheckListId']."' id='RefNo' value='".$check['RefNo']."'/></td>
														</tr>";
														//if($city['Sel'] == 'Y')
														//	array_push($check, $city['CheckListId']);
													}
													//$locArr = implode(",", $check);
												?>
											</tbody>
										</table>
									</div>
								</div>
							</div>           
							<!--end of scrollbar-->        
						</div>
						<!--end .card-body -->
					</div>
					<!--end .card -->
				</div>
			</div>
			<!---END----->
			<!----<div class="bottom">
				<div class="row row-centered">
					<div class="col-xs-4 col-centered">
						<div class="form-group">
							<input type="button" name="next" class="back save_btn m_auto" value="back">
							<button type="button" name="save" onclick= "validate()" class="continue save_btn m_auto" value="Continue">Continue</button>
						</div>
					</div>
				</div>
			</div>---->
		</form>
	</div>
</div>
<div class="col-lg-12 savebtn_area">
    <ul>
        <li id="submitData" class="dropdown save_btn float_r">
            <a href="javascript:void(0);" class="ripple">Continue</a>
        </li>
        <li id="back" class="cancel_btn float_r" ><a href="#" class="ripple">back</a></li>
    </ul>
</div>
<script>
	checkClick();
	var locId = [];
	var extraId = [];
	var featureId = [];
	/*location id*/
	var val = $("#hidlocId").val().split(",");
	for(var i=0; i<val.length; i++){
		if(val[i] != ''){
			locId.push(val[i]);
		}
	}
	/*extra id*/
	var val = $("#hidextraId").val().split(",");
	for(var i=0; i<val.length; i++){
		if(val[i] != ''){
			extraId.push(val[i]);
		}
	}
	/*feature id*/
	var val = $("#hidFeatureId").val().split(",");
	for(var i=0; i<val.length; i++){
		if(val[i] != ''){
			featureId.push(val[i]);
		}
	}
	
	function checkClick(){
		$("input:checkbox").unbind("click");
		$("input:checkbox").bind("click", function(){
			var cls = $(this).attr("class").split(" ")[0];
			if($(this).is(":checked")){
				if(cls == 'listCheck'){
					locId.push($(this).val());
					var cname = $(this).attr('cname');
					if($(this).attr("sel") == 'Y'){
						$.ajax({
							url:getBaseURL()+"crm/project/utg",
							type:"post",
							data:"id="+$(this).val()+"&mode=checkSelect",
							dataType:"json",
							success:function(data, textStatus, jqXHR){
								$.each(data, function(i,v){
									$("#appendTableCheck tbody").append("<tr id='demo_"+v.CheckListId+"'>"+
																			"<th>"+cname+"</th>"+
																			"<td><input class='form-control' type='text' placeholder ='ExpCompletionDate' name='ExpCompletionDate_"+v.CheckListId+"' id='ExpCompletionDate"+v.CheckListId+"' value='"+v.ExpCompletionDate+"'/></td>"+
																			"<td><input class='form-control' type='text' placeholder ='CompletionDate' name='CompletionDate_"+v.CheckListId+"' id='CompletionDate"+v.CheckListId+"' value='"+v.CompletionDate+"'/></td>"+
																			"<td><input class='form-control' type='text' placeholder ='RefNo' name='RefNo_"+v.CheckListId+"' id='RefNo"+v.CheckListId+"' value='"+v.RefNo+"'/></td>"+
																	"</tr>");
								});
											
							},
							error:function(jqXHR, textStatus, errorThrown){
								alert(textstatus+"--------------"+errorThrown);
							}
						});			
					}
					else{
						//alert($(this).val())
						$("#appendTableCheck tbody").append("<tr id='demo_"+$(this).val()+"'>"+
																"<th>"+$(this).attr('cname')+"</th>"+
																"<input class='form-control' type='hidden' name='CheckListName_"+$(this).val()+"' id='CheckListName_"+$(this).val()+"'value='"+$(this).attr('cname')+"'/>"+
																"<td><input class='form-control' type='text' placeholder ='ExpCompletionDate' name='ExpCompletionDate_"+$(this).val()+"' id='ExpCompletionDate"+$(this).val()+"'/></td>"+
																"<td><input class='form-control' type='text' placeholder ='CompletionDate' name='CompletionDate_"+$(this).val()+"' id='CompletionDate"+$(this).val()+"'/></td>"+
																"<td><input class='form-control' type='text' placeholder ='RefNo' name='RefNo_"+$(this).val()+"' id='RefNo"+$(this).val()+"'/></td>"+
														"</tr>");
					}
				}
				else if(cls == 'extraCheck'){
					extraId.push($(this).val());
					var ename = $(this).attr('ename');
					//alert(ename);
					if($(this).attr("sel") == 'Y'){
						$.ajax({
							url:getBaseURL()+"crm/project/utg",
							type:"post",
							data:"id="+$(this).val()+"&mode=extraSelect",
							dataType:"json",
							success:function(data, textStatus, jqXHR){
								alert(JSON.stringify(data));
								$.each(data, function(i,v){
									$("#appendTableExtra tbody").append("<tr id='ext_"+v.ExtraItemId+"'>"+
																			"<th>"+ename+"</th>"+
																			"<td>"+
																			"<input class='form-control' type='hidden' name='ItemDescription_"+v.ExtraItemId+"' id='ItemDescription"+v.ExtraItemId+"' value='"+v.ItemDescription+"'/></td>"+
																			"<input class='form-control' type='text' placeholder ='ExtraRate' name='ExtraRate_"+v.ExtraItemId+"' id='ExtraRate"+v.ExtraItemId+"' value='"+v.ExtraRate+"'/></td>"+
																			"<td><input class='form-control' type='text' placeholder ='Qty' name='Qty_"+v.ExtraItemId+"' id='Qty"+v.ExtraItemId+"' value='"+v.Qty+"'/></td>"+
																			"<td><input class='form-control' type='text' placeholder ='Amount' name='Amount_"+v.ExtraItemId+"' id='Amount"+v.ExtraItemId+"' value='"+v.Amount+"'/></td>"+
																			"<td><input class='form-control' type='text' placeholder ='NetAmount' name='NetAmount_"+v.ExtraItemId+"' id='NetAmount"+v.ExtraItemId+"' value='"+v.NetAmount+"'/></td>"+
																	"</tr>");
								});
											
							},
							error:function(jqXHR, textStatus, errorThrown){
								alert(textstatus+"--------------"+errorThrown);
							}
						});			
					}
					else{
						//alert($(this).val())
						$("#appendTableExtra tbody").append("<tr id='ext_"+$(this).val()+"'>"+
																"<th>"+$(this).attr('ename')+"</th>"+
																//"<input class='form-control' type='hidden' name='ItemDescription_"+v.ExtraItemId+"' id='ItemDescription"+v.ExtraItemId+"' value='"+v.ItemDescription+"'/></td>"+
																"<input class='form-control' type='hidden' name='ItemDescription_"+$(this).val()+"' id='ItemDescription_"+$(this).val()+"'value='"+$(this).attr('ename')+"'/>"+
																"<td><input class='form-control' type='text' placeholder ='ExtraRate' name='ExtraRate_"+$(this).val()+"' id='ExtraRate"+$(this).val()+"'/></td>"+
																"<td><input class='form-control' type='text' placeholder ='Qty' name='Qty_"+$(this).val()+"' id='Qty"+$(this).val()+"'/></td>"+
																"<td><input class='form-control' type='text' placeholder ='Amount' name='Amount_"+$(this).val()+"' id='Amount"+$(this).val()+"'/></td>"+
																"<td><input class='form-control' type='text' placeholder ='NetAmount' name='NetAmount_"+$(this).val()+"' id='NetAmount"+$(this).val()+"'/></td>"+
														"</tr>");
					}
				}
				else if(cls == 'featureCheck'){
					featureId.push($(this).val());
					var fname = $(this).attr('fname');
					//alert(fname);
					if($(this).attr("sel") == 'Y'){
						$.ajax({
							url:getBaseURL()+"crm/project/utg",
							type:"post",
							data:"id="+$(this).val()+"&mode=featureSelect",
							dataType:"json",
							success:function(data, textStatus, jqXHR){
								// alert(JSON.stringify(data));
								$.each(data, function(i,v){
									$("#featureTable tbody").append("<tr id='fxt_"+v.ExtraItemId+"'>"+
																			"<th>"+fname+"</th>"+
																			"<td><input class='form-control' type='text' placeholder ='ExtraRate' name='ExtraRate_"+v.ExtraItemId+"' id='ExtraRate"+v.ExtraItemId+"' value='"+v.ExtraRate+"'/></td>"+
																			"<td><input class='form-control' type='text' placeholder ='Qty' name='Qty_"+v.ExtraItemId+"' id='Qty"+v.ExtraItemId+"' value='"+v.Qty+"'/></td>"+
																			"<td><input class='form-control' type='text' placeholder ='Amount' name='Amount_"+v.ExtraItemId+"' id='Amount"+v.ExtraItemId+"' value='"+v.Amount+"'/></td>"+
																			"<td><input class='form-control' type='text' placeholder ='NetAmount' name='NetAmount_"+v.ExtraItemId+"' id='NetAmount"+v.ExtraItemId+"' value='"+v.NetAmount+"'/></td>"+
																	"</tr>");
								});
											
							},
							error:function(jqXHR, textStatus, errorThrown){
								alert(textstatus+"--------------"+errorThrown);
							}
						});			
					}
					else{
						//alert($(this).val())
						$("#featureTable tbody").append("<tr id='fxt_"+$(this).val()+"'>"+
																"<th>"+$(this).attr('fname')+"</th>"+
																//"<input class='form-control' type='hidden' name='CheckListName_"+$(this).val()+"' id='CheckListName_"+$(this).val()+"'value='"+$(this).attr('ename')+"'/>"+
																"<td><input class='form-control' type='text' placeholder ='ExtraRate' name='ExtraRate_"+$(this).val()+"' id='ExtraRate"+$(this).val()+"'/></td>"+
																"<td><input class='form-control' type='text' placeholder ='Qty' name='Qty_"+$(this).val()+"' id='Qty"+$(this).val()+"'/></td>"+
																"<td><input class='form-control' type='text' placeholder ='Amount' name='Amount_"+$(this).val()+"' id='Amount"+$(this).val()+"'/></td>"+
																"<td><input class='form-control' type='text' placeholder ='NetAmount' name='NetAmount_"+$(this).val()+"' id='NetAmount"+$(this).val()+"'/></td>"+
														"</tr>");
					}
				}					
			}
			else{
				if(cls == 'listCheck'){
					locId.splice($.inArray($(this).val(), locId),1);
					$("#demo_"+$(this).val()).remove();
				}
				else if(cls == 'extraCheck'){
					extraId.splice($.inArray($(this).val(), extraId),1);
					$("#ext_"+$(this).val()).remove();
				}
				else if(cls == 'featureCheck'){
					//alert('1')
					featureId.splice($.inArray($(this).val(), featureId),1);
					$("#fxt_"+$(this).val()).remove();
				}
			}
		});	
	}
	$(".addExternal").click(function(){
		//alert($(this).attr("id"));
		var id = $(this).attr("id");
		if(id == "newCheckList"){
			var formData = $("#addCheckList").find("input:text,input:hidden").serializeArray();
			formData.push({name: "mode", value: "CheckList" });
		}
		else if(id == "newExtraItem"){
			var formData = $("#addExtraItems").find("input:text, select, input:hidden").serializeArray();
			formData.push({name: "mode", value: "extraItem" });
			//formData.push({name: "len", value: $("#addExtraItem tbody tr").length });
		}
		else if(id == "newFeatureItem"){
			var formData = $("#addFeature").find("input:text, select, input:hidden").serializeArray();
			formData.push({name: "mode", value: "featureItem" });
			//formData.push({name: "len", value: $("#addExtraItem tbody tr").length });
		}
		//alert(JSON.stringify(formData));
		//alert(formData[1].value)
		$.ajax({
			url:getBaseURL()+"crm/project/utg",
			type:"post",
			data:formData,
			success:function(data, textStatus, jqXHR){
				//alert(data);
				if(id == "newCheckList"){
				$("#checkListAppend").append("<li class=''>"+
												"<div class='rdochck_subscrb radio_check'>"+
													"<p style='padding:0px !important;'>"+
														"<input class='listCheck check' type='checkbox' name='customize_"+data['data']+"' id='customize_"+data['data']+"' sid='"+formData[1].value+"' cid='"+formData[2].value+"' value='"+data['data']+"' />"+														
														"<label for='customize_"+data['data']+"' class='ripple'>"+formData[0].value+"</label>"+
													"</p>"+																							
												"</div>"+										
											"</li>");
					$("#addCheckList").find("input:text").val('');
					checkClick();
				}
				else if(id == "newExtraItem"){
					  // alert(data);
					$("#extraItemAppend").append("<li class=''>"+
												"<div class='rdochck_subscrb radio_check'>"+
													"<p style='padding:0px !important;'>"+
														"<input class='extraCheck extra' type='checkbox' name='customize1_"+data['data']+"' id='customize1_"+data['data']+"' sid='"+formData[1].value+"' cid='"+formData[2].value+"' value='"+data['data']+"' />"+														
														"<label for='customize1_"+data['data']+"' class='ripple'>"+formData[0].value+"</label>"+
													"</p>"+																							
												"</div>"+										
											"</li>");
					$("#addExtraItems").find("input:text").val('');
					checkClick();
				}
				else if(id == "newFeatureItem"){
					//alert(data);
					$("#featureAppend").append("<li class=''>"+
												"<div class='rdochck_subscrb radio_check'>"+
													"<p style='padding:0px !important;'>"+
														"<input class='featureCheck feature' type='checkbox' name='customize1_"+data['data']+"' id='customize1_"+data['data']+"' sid='"+formData[1].value+"' cid='"+formData[2].value+"' value='"+data['data']+"' />"+														
														"<label for='customize1_"+data['data']+"' class='ripple'>"+formData[0].value+"</label>"+
													"</p>"+
												"</div>"+
											"</li>");
					$("#addFeature").find("input:text").val('');
					checkClick();
				}
			},
			error:function(jqXHR, textStatus, errorThrown){
				alert(textstatus+"--------------"+errorThrown);
			}
		});
	});
	$("#addChecklistView").click(function(){
		$("#addCheckList").slideDown("slow");
			$("#CheckListTable tbody").append("<tr cid='0'><td><input type='text' class='parent_txts newRow' name='CheckList' id='CheckList' tagname='CheckListName' cid='0' class='form-control'><input type='hidden' name='hidcid_1' id='hidcid_1' tagname='hidcid' value='0'></td>"+
														"<td><a href='javascript:void(0);' class='vendar_styles float_r removeCert'><span class='glyphicon glyphicon-trash' data-toggle='tooltip' data-placement='top' data-original-title='Delete'></span></a></td>"+
													"</tr>");
	});
	$("#addExtraItemView").click(function(){
		$("#addExtraItems").slideDown("slow");
			$("#extraItemTable tbody").append("<tr cid='0'><td><input type='text' class='parent_txts newRow' name='extraItem' id='extraItem' tagname='ExtraItemName' cid='0' class='form-control'><input type='hidden' name='hidcid_1' id='hidcid_1' tagname='hidcid' value='0'></td>"+
												"<td><a href='javascript:void(0);' class='vendar_styles float_r removeCert'><span class='glyphicon glyphicon-trash' data-toggle='tooltip' data-placement='top' data-original-title='Delete'></span></a></td>"+
											"</tr>");
	});
	$("#addFeatureView").click(function(){
		$("#addFeature").slideDown("slow");
			$("#featureTable1 tbody").append("<tr cid='0'><td><input type='text' class='parent_txts newRow' name='featureItem' id='featureItem' tagname='FeatureItemName' cid='0' class='form-control'><input type='hidden' name='hidcid_1' id='hidcid_1' tagname='hidcid' value='0'></td>"+
												"<td><a href='javascript:void(0);' class='vendar_styles float_r removeCert'><span class='glyphicon glyphicon-trash' data-toggle='tooltip' data-placement='top' data-original-title='Delete'></span></a></td>"+
											"</tr>");
	});
	$("#submitData").click(function(){
		$("#hidlocId").val(locId);
		$("#hidextraId").val(extraId);
		$("#hidFeatureId").val(featureId);
		$("form").submit();
	});
</script>
