<style>
    .pagination-lg > li > a, .pagination-lg > li > span {
        font-size:15px !important;
        padding:5px 15px !important;
    }
    /* Excel Floating Icon */
    .fixed-action-btn          	    {position:fixed;top:85px;right:5px;padding-top:15px;margin-bottom:0;z-index:998;}
    .fixed-action-btn:hover ul li a.btn-floating{transform: scaleY(1) scaleX(1) translateX(0px);opacity: 1;}
    .btn-floating.btn-large         {width:45px;height:45px;}
    .fixed-action-btn ul 			{left:-142px;right:0;text-align:center;position:absolute;margin:0;top:22px;}
    .fixed-action-btn ul li 		{margin-left:8px;list-style-type:none;float:left;}
    .fixed-action-btn ul li a.btn-floating {transform: scaleY(0.4) scaleX(0.4) translateX(40px);opacity: 0;}
    .fixed-action-btn ul a.btn-floating i  {font-size: 17px;line-height: 37px;}
    .btn-floating                   {display:inline-block;color:#fff;position:relative;overflow:hidden;z-index:1;width:37px;height:37px;line-height:37px;padding: 0;
        background-color: #26a69a;border-radius:50%;cursor:pointer;vertical-align: middle;
        box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);text-decoration: none;transition: all .3s ease;
        -webkit-transition: all .3s ease; -moz-transition: all .3s ease; -o-transition: all .3s ease;}
    .btn-floating i                 {width: inherit;display: inline-block;text-align: center;color: #fff;font-size:20px;line-height: 45px; font-weight:normal; color:#fff;}
    .next-bt                        {text-align:center;}
    .next-bt a:hover                {border:1px solid #3580C4 !important; background:#fff !important; color:#3580C4 !important;}
    .next-bt a                      {background:#3580C4!important;border:1px solid #3580C4; border-radius: 4px;
        color:#fff!important; font-size:14px; padding: 5px 10px; text-align: center; transition: all 0.4s ease 0s;}
    .commargin_top 					{margin-top: 30px;}

    /* Excel Floating Icon end*/
    /*--------------Jqx Grid jqx All-------------------*/
    #jqxgrid									{min-height:200px !important;}
    #jqxgrid .jqx-grid-header 					{height:60px !important;}
    .jqx-grid-groups-row						{padding-left:5px !important;}
    .jqx-grid-pager-input						{padding: 2px; text-align: center !important; width: 35px;}
    .jqx-dropdownlist-state-normal				{display: block;  float: right;height: 16px !important;margin-right: 7px;margin-top: 0;  padding-bottom: 2px !important;padding-top: 2px !important; width: 40px;}
    .jqx-button									{cursor: pointer;float: right;margin-right: 3px !important;margin-top: 0 !important;padding: 0 !important;width: 20px !important;}
    .jqx-button > .jqx-icon-arrow-left,
    .jqx-button >.jqx-icon-arrow-right			{height: 21px !important;margin-left: 0 !important;width: 20px !important;}
    .jqx-listitem-element						{height: 25px !important;}
    .jqx-input									{height: 25px !important; margin:2px 4px !important;}
    .jqx-grid-pager .jqx-grid-pager-input		{height:20px !important; margin:0px 4px !important;}
    #jqxgrid .jqx-grid-cell-right-align 		{text-align:right !important; padding-right:8px;}
    #jqxgrid .jqx-grid-cell-left-align 			{padding-left:8px;}
    .jqx-grid-column-menubutton::after			{left:4px;top:10px;}
</style>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqxgrid.grouping.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqxgrid.aggregates.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqx-all.js"></script>
<div class="content_wrapper  padlr0">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 padlr0">
                <div class="col-lg-6 col-md-6 col-sm-6 padlr0">
                    <h1 class="col-lg-6 col-md-6 col-sm-6">Pending History</h1>
                    <div class="col-lg-6">
                        <div class="fixed-action-btn active">
                            <a class="btn-floating btn-large">
                                <i class="fa fa-print"></i>
                            </a>
                            <ul>
                                <li>
                                    <a class="btn-floating hide-input-file" id="print" href="javascript:void(0);" data-toggle="tooltip" data-placement="top" data-original-title="Print Report">
                                        <i class="fa fa-print"></i>

                                    </a>
                                </li>
                                <li>
                                    <a class="btn-floating" id="excelExport" href="javascript:void(0);" data-toggle="tooltip" data-placement="top" data-original-title="Download Excel">
                                        <i class="fa fa-download"></i>
                                    </a>
                                </li>
                                <li>
                                    <a class="btn-floating" id="csvExport" href="javascript:void(0);" data-toggle="tooltip" data-placement="top" data-original-title="Export CSV">
                                        <i class="fa fa-file-archive-o"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="col-lg-3">
                    <div class="req_flds" id="cost">
                        <select data-placeholder="Cost Centre" style="width:100%;" class="single_dropdown lbl_move"
                                name="CostCentre" onchange="PopulateToData(this.value)" id="CostCentre">
                            <option value="0">None</option>
                            <?php if(isset($arr_costcenter)):
                                foreach($arr_costcenter as $costcenter): ?>
                                    <option value="<?php echo $costcenter['CostCentreId'];?>"<?php echo ( (isset($CostCentreId) && $costcenter['CostCentreId'] == $CostCentreId) ) ? 'selected' : ''; ?>><?php echo $costcenter['CostCentreName'];?></option>
                                <?php endforeach;
                            endif; ?>
                        </select>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="req_flds" id="ware">
                        <select data-placeholder="WareHouse" style="width:100%;" class="single_dropdown lbl_move"
                                name="WareHouse" onchange="PopulateToData(this.value)"  id="WareHouse">
                            <option value="0">None</option>
                            <?php if(isset($arr_WareHouse)):
                                foreach($arr_WareHouse as $WareHouse): ?>
                                    <option value="<?php echo $WareHouse['WareHouseId'];?>"<?php echo ( (isset($WareHouseId) && $WareHouse['WareHouseId'] == $WareHouseId) ) ? 'selected' : ''; ?>><?php echo $WareHouse['WareHouseName'];?></option>
                                <?php endforeach;
                            endif; ?>
                        </select>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="form-group">
                        <span class="date_icon"><i class="fa fa-calendar"></i></span>
                        <input type="text" name="fromDate" id="fromDate" class="form-control date_picker lbl_move" readonly="readonly" label="From Date" value="<?php echo (isset($fromdat) && $fromdat != "") ? $fromdat : Date('d-m-Y',strtotime("-3 months")); ?>" />
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="form-group">
                        <span class="date_icon"><i class="fa fa-calendar"></i></span>
                        <input type="text" name="toDate" id="toDate" class="form-control date_picker lbl_move" readonly="readonly" label="To Date" onchange="PopulateToData(this.value)" value="<?php echo (isset($todat) && $todat != "") ? $todat : Date('d-m-Y'); ?>"/>
                    </div>
                </div>
            </div>
            <div class="col-lg-12 clear">
                <div class="table-responsive clear">
                    <div style='margin-top:10px;' id="jqxgrid"> </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-lg-12 savebtn_area">
    <ul>
        <li class="dropdown save_btn float_r">
            <a href="<?php echo $this->basePath();?>/mms/report/reportlist" class="ripple">Close</a>
        </li>
    </ul>
</div>
<script>
    var arr_Lists = <?php echo (isset($arrUnitLists)) ? json_encode($arrUnitLists) : '[]';?>;
    $(document).ready(function () {
       var source = {
            localData: arr_Lists,
            datatype: "json",
            pagesize: 15,
            datafields:
                [
                    { name: "ItemId", type: "string" },
                   // { name: "CostCentreId", type: "string" },
                    { name: "Resource", type: "string" },
                    { name: "Unit", type: "string" },
                    { name: "Code", type: "string" },
                    <?php foreach($arr_datedet as $datedets) { ?>
                    { name: "Qty_<?php echo $datedets['Month'].$datedets['Year']; ?>", type: "number" },
                    <?php } ?>
                    { name: "ResourceId", type: "string" },
                    { name: "AvgQty", type: "number" }
                ]
        };

        dataAdapter = new $.jqx.dataAdapter(source);
        $("#jqxgrid").jqxGrid(
            {
                width: "100%",
                source: dataAdapter,
                pageable: true,
                pagerMode: 'advanced',
                pagerHeight: 40,
                rowsheight:40,
                columnsresize: true,
                autoheight: true,
                sortable: true,
                altrows: true,
                enabletooltips: true,
                showfilterrow: true,
                filterable: true,
                groupable: true,
                showstatusbar: true,
                statusbarheight: 35,
                showaggregates: true,
                autorowheight: true,
                columns: [
                    { text: 'ItemId', datafield: 'ItemId', hidden: true, filterable: false},
                    //{ text: 'CostCentreId', datafield: 'CostCentreId', hidden: true, filterable: false},
                    { text: 'Resource', dataField: 'Resource', pinned:'true',align: 'center', cellsalign: 'left',width:"25%"},
                    { text: 'Code', dataField: 'Code', pinned:'true', align: 'center', cellsalign: 'left',width:"25%"},
                    { text: 'Unit', dataField: 'Unit', pinned:'true', align: 'center', cellsalign: 'left',width:"25%"},
                    <?php foreach($arr_datedet as $datedets) { ?>
                    { text: "<?php echo $datedets['MonthDesc']. "-" .$datedets['Year']; ?>",dataField: "Qty_<?php echo $datedets['Month'].$datedets['Year']; ?>",align: 'center', cellsalign: 'left',width:"25%"},
                    <?php } ?>
                    { text: 'ResourceId', datafield: 'ResourceId', hidden: true, filterable: false},
                    { text: 'Avg', dataField: "AvgQty", align: 'center', cellsalign: 'left',width:"25%"}

                ]
                //,
                //columngroups: [
                //    { text:'wbs', align: 'center', name:'wbs'},
                //    ]
            });
        $("#jqxgrid").jqxGrid('showgroupsheader', false);
        //Print option
        $("#excelExport").click(function () {
            $("#jqxgrid").jqxGrid('exportdata', 'xls', 'jqxGrid');
        });
        $("#csvExport").click(function () {
            $("#jqxgrid").jqxGrid('exportdata', 'csv', 'jqxGrid');
        });
        $("#htmlExport").click(function () {
            $("#jqxgrid").jqxGrid('exportdata', 'html', 'jqxGrid');
        });

        $("#print").click(function () {
            var gridContent = $("#jqxgrid").jqxGrid('exportdata', 'html');
            //var gridContent = $("#jqxgrid").jqxGrid('exportdata', 'html', 'jqxGrid', true, null, false);
            var newWindow = window.open('', '', 'width=800, height=500'),
                document = newWindow.document.open(),
                pageContent =
                    '<!DOCTYPE html>\n' +
                    '<html>\n' +
                    '<head>\n' +
                    '<meta charset="utf-8" />\n' +
                    '<title>PO History</title>\n' +
                    '<h1>PO History</h1>\n' +
                    '</head>\n' +
                    '<body>\n' + gridContent + '\n</body>\n</html>';
            document.write(pageContent);
            document.close();
            newWindow.print();

            /*$("#jqxgrid").jqxGrid('exportdata', 'html', 'jqxGrid', true, null, false);*/
        });

        $("#jqxgrid").bind('rowselect', function (event) {
            var row = event.args.rowindex;
            var datarow = $("#jqxgrid").jqxGrid('getrowdata', row);

        });
        //bindJqxGridAutoResize();
    });

//    $(document).ready(function() {
//        $(".multiple_dropdown").select2({
//        });
//    });
//    $('#CostCentre').on('change',function(){
//        bindRequests();
//    }).change();
//    $('#WareHouse').on('change',function(){
//        bindRequests();
//    }).change();
//    function  bindRequests(){
//        var costCentreId = $('#CostCentre').val();
//        var WareHouseId = $('#WareHouse').val();
//        var fromDate=$('#fromDate').val();
//        var toDate=$('#toDate').val();
//        var sname = $("#CostCentre option:selected").text();
//        if(sname=="None"){
//            $('#ware').show();
//        } else {
//            $('#ware').hide();
//        }
//        var vname = $("#WareHouse option:selected").text();
//        if(vname=="None"){
//            $('#cost').show();
//        } else {
//            $('#cost').hide();
//        }
//        $.ajax({
//            url:getBaseURL()+'mms/general/fast-moving',
//            type:"post",
//            data:"CostCentreId="+costCentreId+"&toDate="+toDate+"&fromDate="+fromDate+"&WareHouseId="+WareHouseId+"&Type=company",
//            dataType:"json",
//            success:function(data, textStatus, jqXHR){
//                if(jqXHR.status == 200) {
//                    renderRequestResources(data);
//                }
//            }
//        });
//    }
//    function renderRequestResources(data) {
//        source.localdata = data;
//        dataAdapter.dataBind();
//    }
       $('#CostCentre').on('change',function(){
           var sname = $("#CostCentre option:selected").text();
           if(sname=="None"){
               $('#ware').show();
           } else {
               $('#ware').hide();
           }
       });
        $('#WareHouse').on('change',function(){
            var vname = $("#WareHouse option:selected").text();
            if(vname=="None"){
                $('#cost').show();
            } else {
                $('#cost').hide();
            }
        });
    function PopulateToData(value) {
        //console.log(value);
        var CostCentreId=$("#CostCentre").val();
        var WareHouseId=$("#WareHouse").val();
        var toDate=$("#toDate").val();
        var fromDate = $('#fromDate').val();
        if(WareHouseId !=  '' ||toDate !=  '' ||CostCentreId !=  ''  ) {
            window.location.replace(getBaseURL() + "mms/general/fast-moving/" + fromDate + "/" + toDate+"/"+CostCentreId+"/"+WareHouseId);
        } /*else{
         window.location.replace(getBaseURL() + "crm/report/executiveanalysisrpt");
         }*/
    }

</script>