<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/workorder.css';?>"/>
<style type="text/css">
    /*border: 1px solid #333;*/
    /*DragResize*/

    /* Required CSS classes: must be included in all pages using this script */
    /* Apply the element you want to drag/resize */
    .drsElement{position: absolute;border: 1px solid #333;}
    /*
     The main mouse handle that moves the whole element.
     You can apply to the same tag as drsElement if you want.
    */
    .drsMoveHandle{height:20px;background-color:#CCC;border-bottom:1px solid #666;cursor:move;}
    /*
     The DragResize object name is automatically applied to all generated
     corner resize handles, as well as one of the individual classes below.
    */
    .dragresize{position:absolute;width:5px;height:5px;font-size:1px;background:#EEE;border:1px solid #333;}
    /*
     Individual corner classes - required for resize support.
     These are based on the object name plus the handle ID.
    */
    .dragresize-tl{top:-8px;left:-8px;cursor:nw-resize;}
    .dragresize-tm{top:-8px;left:50%;margin-left:-4px;cursor:n-resize;}
    .dragresize-tr{top:-8px;right:-8px;cursor:ne-resize;}
    .dragresize-ml{top:50%;margin-top:-4px;left:-8px;cursor:w-resize;}
    .dragresize-mr{top:50%;margin-top:-4px;right:-8px;cursor:e-resize;}
    .dragresize-bl{bottom:-8px;left:-8px;cursor:sw-resize;}
    .dragresize-bm{bottom:-8px;left:50%;margin-left:-4px;cursor:s-resize;}
    .dragresize-br{bottom:-8px;right:-8px;cursor:se-resize;}
    /*DragResize End*/
    /*Main*/
    .text-bold, .text-bold * {ont-weight: bold !important;}
    .text-italic, .text-italic * {font-style: italic !important;}
    .text-underline, .text-underline * {text-decoration: underline !important;}
    .style-left, .style-left * {text-align: left;}
    .style-center, .style-center * {text-align: center;}
    .style-right, .style-right * {text-align: right;}
    .style-justify, .style-justify * {text-align: justify;}
    #styleOptions {display:  none;}
    #ElementTemplate,
    .remScnt {
        display:none;
    }
    .remScnt{position:absolute; right:5px; top:3px; background:none; color:#990; font-size:14px;}
    .remScnt > .fa.fa-trash-o {
        text-decoration: none !important;
        font-style: normal !important;
        font-size: 14px !important;
        font-weight: normal !important;
        color: #000 !important;
        background: transparent !important;
        border: none !important;
    }
    .up-buttm-10					{margin-top:8px; margin-bottom:8px;}
    /*------ scroll top
    .navbar-fixed-top + .content-container {
        margin-top: 70px;
    }
    .content-container {
        margin: 0 130px;
    }



    #top-link-block.affix-top {
        position: absolute;
        bottom: -82px;
        right: 10px;
    }
    #top-link-block.affix {
        position: fixed;
        bottom:60px;
        right: 10px;
    }
    scroll top ------*/
</style>
<form method="post" action="<?php echo $this->basePath(); ?>/application/print" target="_blank">
    <input type="hidden" name="htmlcontent" id="htmlcontent" />
    <input type="hidden" name="RequestId" id="RequestId" value="<?php echo (isset($reqregister)) ? $reqregister['RequestId'] : 0;?>"  />
    <input type="hidden" name="csrf" value="<?php echo isset($csrf)?$csrf:''; ?>">
</form>

<div class="col-lg-12" style=" margin:auto; padding-top:20px; position:relative;">
    <div id="htmlwrapper">
        <?php echo (isset($template)) ? $template : '';?>
		<!--Main-->
        <div style="margin-bottom:30px; margin-top:20px; display:block">
            <table class="table bill-cum" style=" margin-bottom:0px; margin-top:10px;" id="EntryTable" cellpadding="0" cellspacing="0" width="520">
                <thead>
					<tr>
						<th class="thscss text-left" align="left">S.No</th>
						<th class="thscss text-left" align="left">Code</th>
						<th class="thscss text-left" align="left">Resource Name</th>
						<th class="thscss text-left" align="left">Unit Name</th>
						<th class="thscss text-left" align="left">PV Date</th>
						<th class="thscss text-left" align="left">Bill Qty</th>
						<th class="thscss text-left" align="left">Actual Qty</th>
						<th class="thscss text-left" align="left">Rate</th>
						<th class="thscss text-left" align="left">QRate</th>
						<th class="thscss text-left" align="left">Amount</th>
						<th class="thscss text-left" align="left">QAmount</th>
					</tr>
                </thead>			
                <tbody class="main">    
					<?php
                       $baseAmount = 0;
						$CurQAmtTotal = 0;
						if(isset($register)):
						foreach($register as $reg):
                            $CurQAmtTotal += $reg['QAmount'];
                            $baseAmount = $reg['Amount'];
						    $NetAmount = $reg['BillAmount'];

					?>
                        <tr class="padi05">
							<td width="5%" class="tdpds text-left" align="left"><?php echo $reg['SNo'];?></td>
							<td width="5%" class="tdpds text-left" align="left"><?php echo $reg['Code'];?></td>
							<td width="5%" class="tdpds text-left" align="left"><?php echo $reg['ResourceName'];?></td>
							<td width="5%" class="tdpds text-left" align="left"><?php echo $reg['UnitName'];?></td>
							<td width="5%" class="tdpds text-left" align="left"><?php echo $reg['PVDate'];?></td>
							<td width="5%" class="tdpds text-left" align="left"><?php echo $reg['BillQty'];?></td>
							<td width="5%" class="tdpds text-left" align="left"><?php echo $reg['ActualQty'];?></td>
							<td width="5%" class="tdpds text-left" align="left"><?php echo $reg['Rate'];?></td>
							<td width="5%" class="tdpds text-left" align="left"><?php echo $reg['QRate'];?></td>
							<td width="5%" class="tdpds text-left" align="left"><?php echo $reg['Amount'];?></td>
							<td width="5%" class="tdpds text-left" align="left"><?php echo $reg['QAmount'];?></td>
							<?php if($reg['QCount'] > 0){ ?>
								<div class="row" id="termsTable">					
									<thead>
										<tr>
											<th>&nbsp;</th>
											<th>&nbsp;</th>
											<th class="thscss text-left" align="left">Description</th>
											<th class="thscss text-left" align="left">Expression</th>
											<th class="thscss text-left" align="left">Percentage</th>
											<th class="thscss text-left" align="left">Amount</th>
											<th class="thscss text-left" align="left">Sign</th>
											<th>&nbsp;</th>
											<th>&nbsp;</th>
											<th>&nbsp;</th>
											<th>&nbsp;</th>
										</tr>
									</thead>
									<tbody class="main">  
										<?php
											if(isset($register1)):
											foreach($register1 as $reg1):
											if($reg['PVGroupId']==$reg1['PVGroupId']){
										?>
										<tr class="padi05">
											<td>&nbsp;</td>
											<td>&nbsp;</td>
											<td  class="tdpds text-left" align="left"><?php echo $reg1['QualifierName'];?></td>
											<td  class="tdpds text-left" align="left"><?php echo $reg1['Expression'];?></td>
											<td  class="tdpds text-left" align="left"><?php echo $reg1['ExpPer'];?></td>
											<td  class="tdpds text-left" align="left"><?php echo $reg1['NetAmt'];?></td>
											<td  class="tdpds text-left" align="left"><?php echo $reg1['Sign'];?></td>
											<td>&nbsp;</td>
											<td>&nbsp;</td>
										</tr>
										<?php } endforeach; endif;?>
									</tbody>
								
								</div>
							<?php } ?>
                        </tr>
				<?php endforeach; endif;?>
                </tbody>   
				<tbody class="total">
					<tr>
						<td width="5" class="tdpds">&nbsp;</td>
						<td colspan="7" align="right" class="tdpds text-right">Total</td>
						<td width="5%" class="tdpds text-right" align="right"><?php echo $this->commonHelper()->sanitizeNumber($CurQAmtTotal, 2, true);?></td>
					</tr>
				</tbody>
				<tbody class="total">
					<tr>
						<td width="5" class="tdpds">&nbsp;</td>
						<td colspan="7" align="right" class="tdpds text-right">Base Amount</td>
						<td width="5%" class="tdpds text-right" align="right"><?php echo $baseAmount ;?></td>
					</tr>
				</tbody>
                <tbody class="total">
                <tr>
                    <td width="5" class="tdpds">&nbsp;</td>
                    <td colspan="7" align="right" class="tdpds text-right">Net Amount</td>
                    <td width="5%" class="tdpds text-right" align="right"><?php echo $NetAmount ;?></td>
                </tr>
                </tbody>
            </table>
        </div>
		<!--End-->
		
		<!--Terms And Conditions-->
		<div class="panel panel-info row1">
			<div class="panel-heading  panel_heads">
				<h4 class="panel-title ">Terms And Conditions</h4>
			</div>
			<div style="margin-bottom:20px; margin-left:20px; margin-right:20px; margin-top:20px; display:block">
				<table id="termsTable1" class="table bill-cum" style=" margin-bottom:10px; margin-top:10px;" cellpadding="0" cellspacing="0" width="520">
					<thead>
						<tr>
							<th class="thscss text-left" align="left">S.No</th>
							<th class="thscss text-left" align="left">Terms</th>
							<th class="thscss text-left" align="left">Value</th>
							<th class="thscss text-left" align="left">Account</th>
						</tr>
					</thead>			
					<tbody class="main">    
						<?php
							if(isset($register2)):
							foreach($register2 as $reg2):
						?>
							<tr class="padi05">
								<td width="5%" class="tdpds text-left" align="left"><?php echo $reg2['SNo'];?></td>
								<td width="5%" class="tdpds text-left" align="left"><?php echo $reg2['Title'];?></td>
								<td width="5%" class="tdpds text-left" align="left"><?php echo $reg2['Value'];?></td>
								<td width="5%" class="tdpds text-left" align="left"><?php echo $reg2['AccountName'];?></td>
							</tr>
						<?php endforeach; endif;?>
					</tbody>           
				</table>
			</div>
		</div>
		<!--End-->

        <!--Qualifier Details-->
        <div class="panel panel-info row2">
            <div class="panel-heading  panel_heads">
                <h4 class="panel-title">Qualifier Details</h4>
            </div>
            <div style="margin-bottom:20px; margin-left:20px; margin-right:20px; margin-top:20px; display:block">
                <table id="termsTable2" class="table bill-cum" style=" margin-bottom:10px; margin-top:10px;" cellpadding="0" cellspacing="0" width="520">
                    <thead>
                    <tr>
                        <th class="thscss text-left" align="left">Qualifier Name</th>
                        <th class="thscss text-left" align="left">Account Name</th>
                        <th class="thscss text-left" align="left">Sign</th>
                        <th class="thscss text-left" align="left">%</th>
                        <th class="thscss text-left" align="left">Amount</th>
                    </tr>
                    </thead>
                    <tbody class="main">
                    <?php
                    if(isset($register2)):
                        foreach($register2 as $reg2):
                            ?>
                            <tr class="padi05">
<!--                                <td width="5%" class="tdpds text-left" align="left">--><?php //echo $reg2['SNo'];?><!--</td>-->
<!--                                <td width="5%" class="tdpds text-left" align="left">--><?php //echo $reg2['Title'];?><!--</td>-->
<!--                                <td width="5%" class="tdpds text-left" align="left">--><?php //echo $reg2['Value'];?><!--</td>-->
<!--                                <td width="5%" class="tdpds text-left" align="left">--><?php //echo $reg2['AccountName'];?><!--</td>-->
                            </tr>
                        <?php endforeach; endif;?>
                    </tbody>
                </table>
            </div>
        </div>
        <!--End-->

		
		<!--Avance Adjustment-->
		<div class="panel panel-info row3">
			<div class="panel-heading  panel_heads">
				<h4 class="panel-title">Advance Adjustment</h4>
			</div>
			<div class="panel-body">
			<div style="margin-bottom:20px; margin-left:20px; margin-right:20px; margin-top:20px; display:block">
				<table id="termsTable3" class="table bill-cum" style=" margin-bottom:10px; margin-top:10px;" cellpadding="0" cellspacing="0" >
					<thead>
						<tr>
							<th class="thscss text-left" align="left">S.No</th>
							<th class="thscss text-left" align="left">PO NO</th>
							<th class="thscss text-left" align="left">PO Date</th>
							<th class="thscss text-left" align="left">Title</th>
							<th class="thscss text-left" align="left">Amount</th>
							<th class="thscss text-left" align="left">Paid Amount</th>
							<th class="thscss text-left" align="left">Balance</th>
							<th class="thscss text-left" align="left">Current Amount</th>
						</tr>
					</thead>			
					<tbody class="main">    
						<?php
							if(isset($register3)):
							foreach($register3 as $reg3):
						?>
							<tr class="padi05">
								<td  class="tdpds text-left" align="left"><?php echo $reg3['SNo'];?></td>
								<td  class="tdpds text-left" align="left"><?php echo $reg3['PONo'];?></td>
								<td  class="tdpds text-left" align="left"><?php echo $reg3['PODate'];?></td>
								<td width="5%" class="tdpds text-left" align="left"><?php echo $reg3['Title'];?></td>
								<td width="5%" class="tdpds text-left" align="left"><?php echo $reg3['Amount'];?></td>
								<td width="5%" class="tdpds text-left" align="left"><?php echo $reg3['PaidAmount'];?></td>
								<td width="5%" class="tdpds text-left" align="left"><?php echo $reg3['Balance'];?></td>
								<td width="5%" class="tdpds text-left" align="left"><?php echo $reg3['CurrentAmount'];?></td>
							</tr>
						<?php endforeach; endif;?>
					</tbody>           
				</table>
			</div>
			</div>
		</div>
		<!--End-->
		<?php echo (isset($footertemplate)) ? $footertemplate : '';?>
    </div>
    <div class="fixed-action-btn-ra active">
        <a exportName="pdf" class="exportAction btn-floating-ra btn-large-ra" download data-toggle="tooltip" data-placement="top" data-original-title="Print"><i class="fa fa-print"></i></a>
    </div>
</div>
<script type="text/javascript">
    $(function() {
        var reqregister = <?php echo (isset($reqregister))?json_encode($reqregister):'[]'; ?>;
        var currentdate = '<?php echo date('d-m-Y'); ?>';
        var $p_scents = $('#p_scents');
        var $g_scents = $('#g_scents');
        $p_scents.find('.remScnt').remove();
        $g_scents.find('.remScnt').remove();

        $.each(reqregister, function(index, value) {
            if(value != null && value != '') {
                console.log(value)
                $p_scents.find('#req_' + index).text(value);
                $g_scents.find('#req_' + index).text(value);
            }
        });
        $p_scents.find('#req_Date').text(currentdate);

        $(".exportAction").click(function(){
            $('#htmlcontent').val($('#htmlwrapper').html());
            $('form').submit();
        });
    });
</script>
<script>
var tCount1 =  $('#termsTable1 tbody tr').length;
if(tCount1 ==0){
	$('.row1').hide();
}
var tCount2 =  $('#termsTable2 tbody tr').length;
if(tCount2 ==0){
	$('.row2').hide();
}
var tCount3 =  $('#termsTable3 tbody tr').length;
if(tCount3 ==0){
    $('.row3').hide();
}
</script>
