<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/jquery.rowsorter.min.js"></script>
<script type="text/javascript">
$(document).ready(function () {  
	$("#table1").rowSorter();          
	$(".jqxtable").jqxDataTable(
	{
		width:"100%",
		altRows: true,
		sortable: true,
		editable: true,
		selectionMode: 'singleRow',
		columns: [
		  { text: 'S.No', dataField: 'S.No',width:'50px'},
		  { text: 'Company Name', dataField: 'Company Name'}
		]
	});
});
</script>
<style type="text/css">
table td.sorter {width:3px;cursor:move;}
table td.sorter:after{font-family:'FontAwesome';content:'\f142'; line-height:1; color:#ddd; font-size:14px;}
table.sorting-table tbody tr:not(.sorting-row) td {opacity: 0.2;}
</style>
<div class="content_wrapper padlr0">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
            	<h1>Organization</h1> 
                <nav class="navbar inrmdltab_navbar navbar-default">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle mdlnvbr_tgl collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand inrmdl_navbrand ripple" href="javascript:void(0);" > Select Menus</a>
                    </div>
                    <div id="navbar" class="navbar-collapse padlr0 collapse">
                        <ul class="nav nav-tabs innermdl_tabs">
                            <li class="active"><a href="#company" data-toggle="tab" class="ripple">Company</a></li>
                            <li><a href="#costcentre" data-toggle="tab" class="ripple">CostCentre</a></li>
                            <li><a href="#department" data-toggle="tab" class="ripple">Department</a></li>
                            <li><a href="#level" data-toggle="tab" class="ripple">Level</a></li>
                            <li><a href="#position" data-toggle="tab" class="ripple">Position</a></li>
                            <li><a href="#user" data-toggle="tab" class="ripple">User</a></li>
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle ripple" data-toggle="dropdown"><span><i class="fa fa-ellipsis-h"></i></span>More</a>
                                <ul class="dropdown-menu">
                                    <li><a href="javascript:void(0);">Settings</a></li>
                                    <li><a href="#company" data-toggle="tab">Company</a></li>
                                    <li><a href="#costcentre" data-toggle="tab">CostCentre</a></li>
                                    <li><a href="#department" data-toggle="tab">Department</a></li>
                                    <li><a href="#level" data-toggle="tab">Level</a></li>
                                    <li><a href="#position" data-toggle="tab">Position</a></li>
                                    <li><a href="#user" data-toggle="tab" class="ripple">User</a></li>
                                </ul>
                            </li>
                        </ul>
                  </div>
                </nav>
                <div class="tab-content">
                    <div class="tab-pane fade in active" id="company">
                        <div class="table-responsive">
                            <table class="table table-hover tbltop_bdr0 jqxtable">
                                <thead>
                                    <tr>
                                        <th>S.No</th>
                                        <th>Company Name</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>1</td>
                                        <td>Bajaj Holdings and Investment Ltd</td>
                                    </tr>
                                    <tr>
                                        <td>2</td>
                                        <td>Bajaj Holdings and Investment Ltd</td>
                                    </tr>
                                    <tr>
                                        <td>3</td>
                                        <td>Balmer Lawrie &amp; Co. Ltd</td>
                                    </tr>
                                    <tr>
                                        <td>4</td>
                                        <td>C &amp; C Constructions Ltd</td>
                                    </tr>
                                    <tr>
                                        <td>5</td>
                                        <td>Carborundum Universal Ltd (Murugappa Group)</td>
                                    </tr>
                                    <tr>
                                        <td>6</td>
                                        <td>Century Plyboards India Ltd</td>
                                    </tr>
                                    <tr>
                                        <td>7</td>
                                        <td>Edelweiss Financial Services Ltd</td>
                                    </tr>
                                    <tr>
                                        <td>8</td>
                                        <td>Entertainment Network India Ltd</td>
                                    </tr>
                                    <tr>
                                        <td>9</td>
                                        <td>Gateway Distriparks Ltd</td>
                                    </tr>
                                    <tr>
                                        <td>10</td>
                                        <td>India Tourism Development Corporation Ltd (ITDC)</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="costcentre">
                        <div class="table-responsive">
                            <table class="table table-hover tbltop_bdr0 jqxtable1" id="table1">
                                <thead>
                                    <tr>
                                        <th>&nbsp</th>
                                        <th>S.No</th>
                                        <th>Company Name</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td class="sorter"></td>
                                        <td>1</td>
                                        <td>Bajaj Holdings and Investment Ltd</td>
                                    </tr>
                                    <tr>
                                        <td class="sorter"></td>
                                        <td>2</td>
                                        <td>Bajaj Holdings and Investment Ltd</td>
                                    </tr>
                                    <tr>
                                        <td class="sorter"></td>
                                        <td>3</td>
                                        <td>Balmer Lawrie &amp; Co. Ltd</td>
                                    </tr>
                                    <tr>
                                        <td class="sorter"></td>
                                        <td>4</td>
                                        <td>C &amp; C Constructions Ltd</td>
                                    </tr>
                                    <tr>
                                        <td class="sorter"></td>
                                        <td>5</td>
                                        <td>Carborundum Universal Ltd (Murugappa Group)</td>
                                    </tr>
                                    <tr>
                                        <td class="sorter"></td>
                                        <td>6</td>
                                        <td>Century Plyboards India Ltd</td>
                                    </tr>
                                    <tr>
                                        <td class="sorter"></td>
                                        <td>7</td>
                                        <td>Edelweiss Financial Services Ltd</td>
                                    </tr>
                                    <tr>
                                        <td class="sorter"></td>
                                        <td>8</td>
                                        <td>Entertainment Network India Ltd</td>
                                    </tr>
                                    <tr>
                                        <td class="sorter"></td>
                                        <td>9</td>
                                        <td>Gateway Distriparks Ltd</td>
                                    </tr>
                                    <tr>
                                        <td class="sorter"></td>
                                        <td>10</td>
                                        <td>India Tourism Development Corporation Ltd (ITDC)</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="department">
                        <p>Department</p>
                    </div>
                    <div class="tab-pane fade" id="level">
                        <p>Level</p>
                    </div>
                    <div class="tab-pane fade" id="position">
                        <p>Position</p>
                    </div>
                    <div class="tab-pane fade" id="user">
                        <p>User</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--<p class="strm_loader txt_center clear"><span></span>Loading...</p>-->
<div class="col-lg-12 savebtn_area">
    <ul>
        <li class="dropdown save_btn float_r">
            <a href="javascript:void(0);" class="ripple">Save</a>
            <div class="save_trigger">
                <a href="javascript:void(0);" class="ripple" data-toggle="dropdown">
                    <i class="fa fa-angle-down"></i>
                </a>
                <ul class="ang_down_ul save_down_ul dropdown-menu dropdown-menu-right">
                    <li><a href="javascript:void(0);">Save As</a></li>
                    <li><a href="javascript:void(0);">Exit</a></li>
                </ul>
            </div>
        </li>
        <li class="cancel_btn float_r"><a href="#" class="ripple">Cancel</a></li>
    </ul>
</div>