<div class="content_wrapper padlr0">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1>General settings</h1>
            </div>
            <div class="col-lg-12 clear">
                <div class="stgcmpny_logo m_auto">
                    <img src="<?php echo $this->basePath(); ?>/images/profile/profile1.jpg" class="m_auto" alt="" title=""/>
                </div>
                <h1 class="txt_center stg_cmpnyname">D.Mugeshkumar</h1>
                <div class="form-group">
                    <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
                        <div class="stginner_h5">
                            <h5>Personal info 
                                <div class="stgedit_btn brad_50"><a href="javascript:void(0);" class="ripple"><span><i class="fa fa-pencil"></i></span></a></div>
                            </h5>
                        </div>
                        <form class="form-horizontal stginner_cnt">
                            <div class="row">   
                                <div class="col-lg-12">
                                    <label for="first_name" class="col-lg-4 padlr0 col-md-4 txt_left control-label">First Name</label>
                                    <div class="col-lg-7 col-md-7">
                                        <p>D Mugesh</p>
                                        <!--<input type="text" name="first_name" id="first_name" class="form-control lbl_move" placeholder="First Name"/>-->    
                                    </div>
                                </div>
                            </div>
                            <div class="row">   
                                <div class="col-lg-12">
                                    <label for="first_name" class="col-lg-4 padlr0 col-md-4 txt_left control-label">Last Name</label>
                                    <div class="col-lg-7 col-md-7">
                                        <p>Kumar</p>
                                        <!--<input type="text" name="first_name" id="first_name" class="form-control lbl_move" placeholder="First Name"/>--> 
                                    </div>
                                </div>
                            </div>
                            <div class="row">   
                                <div class="col-lg-12">
                                    <label for="first_name" class="col-lg-4 padlr0 col-md-4 txt_left control-label">Gender</label>
                                    <div class="col-lg-7 col-md-7">
                                        <p>Male</p> 
                                        <!--<select name="named[]" id="gender" class="form-control selectpicker show-tick">
                                            <option>Male</option>
                                            <option>Female</option>
                                        </select>-->  
                                    </div>
                                </div>
                            </div>
                        </form>  
                    </div>
                    <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
                        <div class="stginner_h5">
                            <h5>Organization
                                <div class="stgedit_btn brad_50"><a href="javascript:void(0);" class="ripple"><span><i class="fa fa-pencil"></i></span></a></div>
                            </h5>
                        </div>
                        <form class="form-horizontal stginner_cnt">
                            <div class="row">   
                                <div class="col-lg-12">
                                    <label for="first_name" class="col-lg-4 padlr0 col-md-4 txt_left control-label">Company  Name</label>
                                    <div class="col-lg-7 col-md-7">
                                        <p>Casa Grande Private Limited</p>
                                        <!--<input type="text" name="first_name" id="first_name" class="form-control lbl_move" placeholder="First Name"/>-->    
                                    </div>
                                </div>
                            </div>
                            <div class="row">   
                                <div class="col-lg-12">
                                    <label for="first_name" class="col-lg-4 padlr0 col-md-4 txt_left control-label">Address 1</label>
                                    <div class="col-lg-7 col-md-7">
                                        <p>795 Folsom Ave, Suite 600</p>
                                        <!--<input type="text" name="first_name" id="first_name" class="form-control lbl_move" placeholder="First Name"/>-->
                                    </div>
                                </div>
                            </div>
                            <div class="row">   
                                <div class="col-lg-12">
                                    <label for="first_name" class="col-lg-4 padlr0 col-md-4 txt_left control-label">Address 2</label>
                                    <div class="col-lg-7 col-md-7">
                                        <p>
                                            San Francisco, CA 94107<br>
                                            Phone: (123) 456-7890
                                        </p>
                                        <!--<input type="text" name="first_name" id="first_name" class="form-control lbl_move" placeholder="First Name"/>-->
                                    </div>
                                </div>
                            </div>
                        </form>  
                    </div>
                    <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
                        <div class="stginner_h5">
                            <h5>Communication
                                <div class="stgedit_btn brad_50"><a href="javascript:void(0);" class="ripple"><span><i class="fa fa-pencil"></i></span></a></div>
                            </h5>
                        </div>
                        <form class="form-horizontal stginner_cnt">
                            <div class="row">   
                                <div class="col-lg-12">
                                    <label for="first_name" class="col-lg-4 padlr0 col-md-4 txt_left control-label">Email</label>
                                    <div class="col-lg-7 col-md-7">
                                        <p>dmugeshkmr02@gmail.com</p>
                                        <!--<input type="text" name="first_name" id="first_name" class="form-control lbl_move" placeholder="First Name"/>-->    
                                    </div>
                                </div>
                            </div>
                            <div class="row">   
                                <div class="col-lg-12">
                                    <label for="first_name" class="col-lg-4 padlr0 col-md-4 txt_left control-label">Phone</label>
                                    <div class="col-lg-7 col-md-7">
                                        <p>(123) 456-7890</p>
                                        <!--<input type="text" name="first_name" id="first_name" class="form-control lbl_move" placeholder="First Name"/>-->
                                    </div>
                                </div>
                            </div>
                            <div class="row">   
                                <div class="col-lg-12">
                                    <label for="first_name" class="col-lg-4 padlr0 col-md-4 txt_left control-label">Fax</label>
                                    <div class="col-lg-7 col-md-7">
                                        <p>(123) - 456-7890</p>
                                        <!--<input type="text" name="first_name" id="first_name" class="form-control lbl_move" placeholder="First Name"/>-->
                                    </div>
                                </div>
                            </div>
                        </form>  
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--<p class="strm_loader txt_center clear"><span></span>Loading</p>-->
<div class="col-lg-12 savebtn_area">
    <ul>
        <li class="dropdown save_btn float_r">
            <a href="javascript:void(0);" class="ripple">Save</a>
        </li>
        <li class="cancel_btn float_r"><a href="javascript:void(0);" class="ripple">Cancel</a></li>
    </ul>
</div>