<ul class="modl_lmenu">
	<h2>Workflow</h2>
	<li><a href="javascript:void(0);" class="ripple modlsub_open"><i class="fa fa-university"></i> <span class="nav-label">Master Setup</span></a>
		<ul>
			<li><a href="dashboard.php" class="ripple">Organization 1</a></li>
			<li><a href="javascript:void(0);" class="ripple">Organization 2</a></li>
			<li><a href="javascript:void(0);" class="ripple">Organization 3</a></li>
		</ul>
	</li>
	<li><a href="javascript:void(0);" class="ripple modlsub_open"><i class="fa fa-exchange"></i> <span class="nav-label">Transaction</span></a>
		<ul>
			<li><a href="javascript:void(0);" class="ripple">Organization 1</a></li>
			<li><a href="javascript:void(0);" class="ripple">Organization 2</a></li>
			<li><a href="javascript:void(0);" class="ripple">Organization 3</a></li>
		</ul>
	</li>
	<li><a href="organization.php" class="ripple"><i class="fa fa-camera"></i><span class="nav-label">Project images</span></a></li>
</ul>