<script type="text/javascript">
$(document).ready(function () {           
	var data = [
		{Date:"28/12/2014", CreatedBy:"Balaji", LeadName:"Lead Name 1",Status:"Follow up", OrderID:"1", available:true},
		{Date:"29/12/2014", CreatedBy:"Harish", LeadName:"Lead Name 2",Status:"Follow up", OrderID:"2", available:true},
		{Date:"30/12/2014", CreatedBy:"Mugesh", LeadName:"Lead Name 3",Status:"Follow up", OrderID:"3", available:false},
		{Date:"1/1/2015", CreatedBy:"Senthil", LeadName:"Lead Name 4",Status:"Follow up", OrderID:"4", available:true},
		{Date:"2/1/2015", CreatedBy:"Ranga", LeadName:"Lead Name 5",Status:"Follow up", OrderID:"5", available:true},
		{Date:"26/12/2014", CreatedBy:"Balaji1", LeadName:"Lead Name 1",Status:"Follow up", OrderID:"1", available:true},
		{Date:"25/12/2014", CreatedBy:"Harish1", LeadName:"Lead Name 2",Status:"Follow up", OrderID:"2", available:true},
		{Date:"24/12/2014", CreatedBy:"Mugesh1", LeadName:"Lead Name 3",Status:"Follow up", OrderID:"3", available:false},
		{Date:"3/1/2015", CreatedBy:"Senthil1", LeadName:"Lead Name 4",Status:"Follow up", OrderID:"4", available:true},
		{Date:"4/1/2015", CreatedBy:"Ranga1", LeadName:"Lead Name 5",Status:"Follow up", OrderID:"5", available:true},
		{Date:"28/12/2014", CreatedBy:"Balaji", LeadName:"Lead Name 1",Status:"Follow up", OrderID:"1", available:true},
		{Date:"29/12/2014", CreatedBy:"Harish", LeadName:"Lead Name 2",Status:"Follow up", OrderID:"2", available:true},
		{Date:"30/12/2014", CreatedBy:"Mugesh", LeadName:"Lead Name 3",Status:"Follow up", OrderID:"3", available:false},
		{Date:"1/1/2015", CreatedBy:"Senthil", LeadName:"Lead Name 4",Status:"Follow up", OrderID:"4", available:true},
		{Date:"2/1/2015", CreatedBy:"Ranga", LeadName:"Lead Name 5",Status:"Follow up", OrderID:"5", available:true},
		{Date:"26/12/2014", CreatedBy:"Balaji1", LeadName:"Lead Name 1",Status:"Follow up", OrderID:"1", available:true},
		{Date:"25/12/2014", CreatedBy:"Harish1", LeadName:"Lead Name 2",Status:"Follow up", OrderID:"2", available:true},
		{Date:"24/12/2014", CreatedBy:"Mugesh1", LeadName:"Lead Name 3",Status:"Follow up", OrderID:"3", available:false},
		{Date:"3/1/2015", CreatedBy:"Senthil1", LeadName:"Lead Name 4",Status:"Follow up", OrderID:"4", available:true},
		{Date:"4/1/2015", CreatedBy:"Ranga1", LeadName:"Lead Name 5",Status:"Follow up", OrderID:"5", available:true}
	]
	// prepare the data
	var source =
	{
		localdata:data,	
		datafields: [
		{ name: 'Date'},
		{ name: 'CreatedBy'},
		{ name: 'LeadName'},
		{ name: 'Status'}
		],
		id: 'OrderID',
		pager: function (pagenum, pagesize, oldpagenum) {
		// callback called when a page or page size is changed.
		}
	};
	var dataAdapter = new $.jqx.dataAdapter(source);
	$("#jqxgridtwo").jqxGrid(
	{
		width:'100%',
		source: source,
		selectionmode: 'multiplecellsextended',
		sortable: true,
		pageable: true,
		autoheight: true,
		autoloadstate: false,
		autosavestate: false,
		columnsresize: true,
		columnsreorder: true,
		columns: [
		{ text: 'Date', datafield: 'Date',width:'20%'},
		{ text: 'Created by', datafield: 'CreatedBy'},
		{ text: 'Lead name', datafield: 'LeadName'},
		{ text: 'Status', datafield: 'Status'}
		]
	});
});
</script>
<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
    	<div class="right_lightbox">
        	<div class="right_lightbox_close">
                <span class="right_lightbox_closeicon"><i class="fa fa-times"></i></span>
            </div>
            <div class="right_lbox_inner lead_register_rbox">
                <h2>Leads Of Mugesh Devaraj</h2>
                <div class="right_lbox_inner_cnt">
                    <div class="ldrgstr_detail_pro padtop0">
                    	<div class="col-lg-8 col-md-12 flwup_procnt">
                            <h1 class="name">Project : <span>Project1</span></h1>
                        </div>
                        <div id='jqxWidget'>
                            <div id="jqxgridtwo"></div>
                        </div>
                    </div>
                </div>
            </div>            
        </div>
        <div class="col-lg-12">
            <h1>Allocation Register</h1>
        </div> 
        <div class="col-lg-12 block_panel clear">
            <div class="table-responsive clear col-lg-12">
                <table class="table clear">
                    <thead>
                        <tr>
                            <th>Executive Name</th>
                            <th>Project Name</th>
                            <th class="txt_center" style="width:15%;">Total Leads</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td rowspan="5">Mugesh Devaraj</td>
                            <td>Project 1</td>
                            <td class="txt_center totallead_trigger">25</a></td>
                        </tr>
                        <tr>
                            <td>Project 1</td>
                            <td class="txt_center totallead_trigger">25</td>
                        </tr>
                        <tr>
                            <td>Project 1</td>
                            <td class="txt_center totallead_trigger">25</td>
                        </tr>
                        <tr>
                            <td>Project 1</td>
                            <td class="txt_center totallead_trigger">25</td>
                        </tr>
                        <tr>
                            <td>Project 1</td>
                            <td class="txt_center totallead_trigger">25</td>
                        </tr>
                        <tr>
                            <td rowspan="3">Harish Dhanazhaliyan</td>
                            <td>Project 1</td>
                            <td class="txt_center totallead_trigger">25</td>
                        </tr>
                        <tr>
                            <td>Project 1</td>
                            <td class="txt_center totallead_trigger">25</td>
                        </tr>
                        <tr>
                            <td>Project 1</td>
                            <td class="txt_center totallead_trigger">25</td>
                        </tr>
                        <tr>
                            <td rowspan="5">Mugesh Devaraj</td>
                            <td>Project 1</td>
                            <td class="txt_center totallead_trigger">25</td>
                        </tr>
                        <tr>
                            <td>Project 1</td>
                            <td class="txt_center totallead_trigger">25</td>
                        </tr>
                        <tr>
                            <td>Project 1</td>
                            <td class="txt_center totallead_trigger">25</td>
                        </tr>
                        <tr>
                            <td>Project 1</td>
                            <td class="txt_center totallead_trigger">25</td>
                        </tr>
                        <tr>
                            <td>Project 1</td>
                            <td class="txt_center totallead_trigger">25</td>
                        </tr>
                    </tbody>
                </table>
            </div>    
        </div>
    </div>
</div>
<script>
$(function(){
    $('.totallead_trigger').click(function(){ 
		$('.block_panel').addClass('block_panel_open');
		$('.right_lightbox').show();
		$('.left-panel').removeClass('collapsed');
		$('.l_menuicon_nav').removeClass('cross');
    });
	$('.right_lightbox_close').click(function(){
		$('.block_panel').removeClass('block_panel_open');
		$('.right_lightbox').hide();
		if ($(window).width() >=980){
			$('.left-panel').addClass('collapsed');	
			$('.l_menuicon_nav').addClass('cross');
		}
	});
});
</script>