<div class="content_wrapper padlr0">
  <div class="container-fluid">
    <div class="col-lg-12">
      <h1>Project Info of
        <div class="btn-group proname_btn"> <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">ArunBuilders <span class="edit_symbols" data-placement="right" data-toggle="tooltip" data-original-title="Change&nbsp;project&nbsp;name"><i class="fa fa-caret-down "></i></span></a>
          <div class="dropdown-menu toolbar_ddown proname_ddown arrow" role="menu">
            <ul>
              <li><a href="#">Mayflower Mayflower</a></li>
              <li><a href="#">AkashManor</a></li>
              <li><a href="#">Isha</a></li>
              <li><a href="#">RMZ Millenia</a></li>
              <li><a href="#">APS Avenue</a></li>
              <li><a href="#">Aura One</a></li>
              <li><a href="#">HO - Micromen Properties Ltd</a></li>
              <li><a href="#">HO - Isha Homes PVT LTD</a></li>
              <li><a href="#">BO - APS - Chennai</a></li>
              <li><a href="#">ArunBuilders</a></li>
              <li><a href="#">Aura One</a></li>
              <li><a href="#">HO - Prince Foundation Ltd</a></li>
              <li><a href="#">Prince Block 1</a></li>
              <li><a href="#">Prince Block 2</a></li>
            </ul>
          </div>
        </div>
      </h1>
    </div>
    <div class="col-lg-12 clear">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
          <div class="col-lg-12">
            <div class="row">
              <div class="step_by_liner animated slideInDown"></div>
              <ul class="step_by stepby_mb60">
                <li>
                  <div class="step_by_sep animated_0_4s slideInRight">
                    <p>1</p>
                  </div>
                  <p class="stepli_p1">Car Park management</p>
                </li>
                <li>
                  <div class="step_by_sep stepsep_active animated slideInRight">
                    <p>2</p>
                  </div>
                  <p class="stepli_p2">Check list mangement</p>
                </li>
                <li class="opacity_08">
                  <div class="step_by_sep animated_1_5s slideInRight">
                    <p>3</p>
                  </div>
                  <p class="stepli_p3">Penality &amp; Interest Rate</p>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
          <form class="form-horizontal">
            <div class="row">
              <div class="form-group col-lg-12">
                <select name="named[]" id="unit_type" class="form-control selectpicker show-tick" data-size="5" title="Check List Type..">
                  <option>Select Check List Type</option>
                  <option>1</option>
                  <option>2</option>
                  <option>3</option>
                  <option>4</option>
                </select>
              </div>
            </div>
            <div class="row">
              <div class="form-group col-lg-12 req_flds">
                <input type="text" class="form-control lbl_move" label="Pancard">
              </div>
            </div>
            <div class="row">
              <div class="form-group col-lg-12">
                <input type="text" class="form-control lbl_move" label="Registration Document">
              </div>
            </div>
            <div class="row">
              <div class="form-group col-lg-12">
                <input type="text" class="form-control lbl_move" label="Addre">
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="col-lg-12 savebtn_area">
  <ul>
    <li class="dropdown save_btn float_r"> <a href="penality-interest" class="ripple">Save</a>
      <div class="save_trigger"> <a href="javascript:void(0);" class="ripple" data-toggle="dropdown"> <i class="fa fa-angle-down"></i> </a>
        <ul class="ang_down_ul save_down_ul dropdown-menu dropdown-menu-right">
          <li><a href="javascript:void(0);">Save &amp; Next</a></li>
          <li><a href="javascript:void(0);">Save &amp; Exit</a></li>
        </ul>
      </div>
    </li>
    <li class="cancel_btn float_r"><a href="javascript:void(0);" class="ripple">back</a></li>
    <li class="goto">
      <label for="go_to" class="float_l">Go to</label>
      <select id="go_to" name="go_to" class="float_l goto_select" title="Choose Page to go....">
        <option>General</option>
        <option>Land Area Details</option>
        <option>Land Cost Calculation</option>
        <option>Car Park</option>
        <option>General</option>
        <option>Land Area Details</option>
        <option>Land Cost Calculation</option>
        <option>Car Park</option>
      </select>
    </li>
  </ul>
</div>
