<style>
.info-tiles{
    border-radius: 1px;
    display: block;
    margin: 0 0 20px;
	color: #ffffff !important;
	 text-transform: uppercase;
}


.info-tiles .tiles-heading {
    border-top-left-radius: 1px;
    border-top-right-radius: 1px;
    font-size: 11px;
    letter-spacing: 0.1em;
    padding: 6px 10px;
    text-align: center;
}
.info-tiles .tiles-body-alt, .info-tiles .tiles-body {
    font-weight: 300;
    padding: 10px;
}
.info-tiles .tiles-body-alt i, .info-tiles .tiles-body i {
    color: rgba(255, 255, 255, 0.5);
    font-size: 29px;
    transition: all 0.06s ease-in 0s;
}
.nofnt{font-size:20px; font-weight: 600;}
.info-tiles .tiles-footer {
    border-bottom-left-radius: 1px;
    border-bottom-right-radius: 1px;
    color: #fff;
    padding: 5px 10px;
	font-weight:600;
}
.info-tiles .tiles-footer::after {
    border-color: rgba(0, 0, 0, 0.35) #f7f8fa #f7f8fa rgba(0, 0, 0, 0.35);
    border-style: solid;
    border-top-left-radius: 1px;
    border-width: 5px;
    bottom: 0;
    content: "";
    height: 0;
    margin-bottom: 20px;
    margin-right: 11px;
    position: absolute;
    right: -1px;
    width: 0;
}
.bg-color-green {
    background-color: #fff;
    color: #5ac8d6;
}
.bg-color-green p{
    color: #42536d  ;font-size:25px;text-align: center;
}
.bg-color-green h3{
    color: #6b82a4 ;margin-bottom: 5px;margin-top: 7px; font-size:20px;
}
.no-boder {
    border: 1px solid #f3f3f3;
}
.back-footer-green {
    background-color: #556b8d ;
	font-size:16px;
	padding:7px !important;
}
.back-footer-green p {
    color: #fff ;
	font-size:15px;
	font-weight:600;
}
.badgebck{color: #fff; background:#38465c ; letter-spacing: 1px;}
.circular_icon {
    display: block;
    height: 40px;
    margin: 0 39px;
    padding: 28px;
    position: relative;
    transition: all 0.15s ease-in-out 0s;
    width: 40px;
}
.circular_icon::before {
    background: #32a8b7 none repeat scroll 0 0;
    border-radius: 100% 100% 0;
    content: "";
    display: block;
    height: 100%;
    position: absolute;
    transform: translate(50px) rotate(45deg);
    transform-origin: 34px -64px 0;
    width: 100%;
}
.circular_icon .icon {
    bottom: 21px;
    color: #fff;
    display: block;
    font-size: 25px;
    left: 1px;
    margin: 0 auto !important;
    position: relative;
}
.circular_icon .number {
    bottom: 18px;
    display: block;
    font-size: 16px;
    font-weight: 600;
    margin: 0 auto !important;
    position: relative;
    right: 4px;
}
.rectptag {
    background: #fcc none repeat scroll 0 0;
    border-radius: 4px;
    padding: 5px;
    text-align: center;
}
.circle-tile {
    margin-bottom: 30px;
    text-align: center;
}
.circle-tile-heading {
    border-radius: 100%;
    color: #fff;
    font-size: 18px;
    height: 40px;
    margin: 0 0 -19px;
    position: relative;
    transition: all 0.3s ease-in-out 0s;
    width: 40px;
}
.circle-tile-heading .fa {
    line-height: 38px;
}
.dark-blue {
    background-color: #de577b ;
}
.dark-blueone {
    background-color:#1fb5ad ;
}
.circle-tile-content {
    border-radius: 4px;
    padding-top: 11px;
}
.circle-tile-number {
    font-size: 26px;
    font-weight: 700;
    line-height: 1;
    padding: 5px 0 10px;
}
.circle-tile-description {
    text-transform: uppercase;
}
.text-faded {
    color: #fff;
}
</style>
<div class="content_wrapper padlr0">
	<div class="container-fluid ">
    	<div class="col-lg-12 padlr0">
        	<div class="col-lg-12 padlr0">
                <div class="col-lg-2 col-md-6 col-sm-6 col-xs-6 mnimumwidthres">
                    <div class="info-tiles tiles-orange">
                        <div class="tiles-body-alt bckgrnd1">
                            <span class="float_l"><i class="fa fa-question-circle"></i></span>
                            <span class="float_r nofnt">10889</span>
                            <div class="clear"></div>
                        </div>
                        <div class="tiles-footer bckgrnd11">Unresolved</div>
                    </div>
                </div>
                <div class="col-lg-2 col-md-6 col-sm-6 col-xs-6 mnimumwidthres">
                    <div class="info-tiles tiles-orange">
                        <div class="tiles-body-alt bckgrnd2">
                            <span class="float_l"><i class="fa fa-exclamation-triangle"></i></span>
                            <span class="float_r nofnt">10889</span>
                            <div class="clear"></div>
                        </div>
                        <div class="tiles-footer bckgrnd12">Over Due</div>
                    </div>
                </div>
                <div class="col-lg-2 col-md-6 col-sm-6 col-xs-6 mnimumwidthres">
                    <div class="info-tiles tiles-orange">
                        <div class="tiles-body-alt bckgrnd3">
                            <span class="float_l"><i class="fa fa-clock-o"></i></span>
                            <span class="float_r nofnt">10889</span>
                            <div class="clear"></div>
                        </div>
                        <div class="tiles-footer bckgrnd13">Due Today</div>
                    </div>
                </div>
                <div class="col-lg-2 col-md-6 col-sm-6 col-xs-6 mnimumwidthres">
                    <div class="info-tiles tiles-orange">
                        <div class="tiles-body-alt bckgrnd4">
                            <span class="float_l"><i class="fa fa-unlock"></i></span>
                            <span class="float_r nofnt">10889</span>
                            <div class="clear"></div>
                        </div>
                        <div class="tiles-footer bckgrnd14">Open</div>
                    </div>
                </div>
                <div class="col-lg-2 col-md-6 col-sm-6 col-xs-6 mnimumwidthres">
                    <div class="info-tiles tiles-orange">
                        <div class="tiles-body-alt bckgrnd5">
                            <span class="float_l"><i class="fa fa-hand-paper-o"></i></span>
                            <span class="float_r nofnt">10889</span>
                            <div class="clear"></div>
                        </div>
                        <div class="tiles-footer bckgrnd15">On Hold</div>
                    </div>
                </div>
                <div class="col-lg-2 col-md-6 col-sm-6 col-xs-6 mnimumwidthres">
                    <div class="info-tiles tiles-orange">
                        <div class="tiles-body-alt bckgrnd6">
                            <span class="float_l"><i class="fa fa-user-times"></i></span>
                            <span class="float_r nofnt">10889</span>
                            <div class="clear"></div>
                        </div>
                        <div class="tiles-footer bckgrnd16">UnAssigned</div>
                    </div>
                </div>
            </div>
            <div class="clear"></div>
            <div class="col-lg-12 padlr0">
            	<div class="col-lg-6">
                    <section class="pnnal">
                        <header class="pnnal-heading"> <i class="fa fa-list-alt"></i> <span class="fntsz16">&nbsp;To Do List </span><span class="ng-binding" style="font-size:12px !important; font-weight:normal !important; color: #878484;"> (2 of 0 remaining)</span></header>
                        <div class="pnnal-body scrlcrm" style="height:350px; width:100%;">
                            <ul class="todo-list-item" id="todo-list">
                                <li class="clearfix">
                                    <div class="rdochck_subscrbone radio_check">
                                        <a href="#">
                                            <p style="padding:0px !important;">
                                                <input type="checkbox"/>
											<!--<label class="ripple">--><!--</label>-->
                                                <label class="ripple">Ticket #58642: Is due today</label>
                                            </p>
                                        </a>
                                    </div>
                                </li>
                                <li class="clearfix">
                                    <div class="rdochck_subscrbone radio_check">
                                        <a href="#">
                                            <p style="padding:0px !important;">
                                                <input type="checkbox"/>
											<!--<label class="ripple">--><!--</label>-->
                                                <label class="ripple">Ticket #58412: Received Response from customer</label>
                                            </p>
                                        </a>
                                    </div>
                                </li>
                                <li class="clearfix">
                                    <div class="rdochck_subscrbone radio_check">
                                        <a href="#">
                                            <p style="padding:0px !important;">
                                                <input type="checkbox"/>
											<!--<label class="ripple">--><!--</label>-->
                                                <label class="ripple">Ticket #58112: Received Response from customer</label>
                                            </p>
                                        </a>
                                    </div>
                                </li>
                                <li class="clearfix">
                                    <div class="rdochck_subscrbone radio_check">
                                        <a href="#">
                                            <p style="padding:0px !important;">
                                                <input type="checkbox"/>
											<!--<label class="ripple">--><!--</label>-->
                                                <label class="ripple">Arnika - bgfbhgbh</label>
                                            </p>
                                        </a>
                                    </div>
                                </li>
                                <li class="clearfix">
                                    <div class="rdochck_subscrbone radio_check">
                                        <a href="#">
                                            <p style="padding:0px !important;">
                                                <input type="checkbox"/>
											<!--<label class="ripple">--><!--</label>-->
                                                <label class="ripple">Ticket #58112: Received Response from customer</label>
                                            </p>
                                        </a>
                                    </div>
                                </li>
                                <li class="clearfix">
                                    <div class="rdochck_subscrbone radio_check">
                                        <a href="#">
                                            <p style="padding:0px !important;">
                                                <input type="checkbox"/>
											<!--<label class="ripple">--><!--</label>-->
                                                <label class="ripple">Ticket #58112: Received Response from customer</label>
                                            </p>
                                        </a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </section>
                </div>
                <div class="col-lg-6">
                    <section class="pnnal">
                        <header class="pnnal-heading"><i class="fa fa-comments-o"></i> <span class="fntsz16">&nbsp;Live Chat</span></header>
                        <div class="pnnal-body">
                        	<div align="center" style=" width:100%;">
                            	<div align="center" style="width:80%;">
                                	<div class="panel text-center bg-color-green commargin_bottom_0" style="border: 1px solid #ddd; ">
                                        <div class="panel-body" style="padding: 15px 5px 5px !important;">
                                            <p>8,457</p>
                                            <h3>Chats in Conversation</h3>
                                        </div>
                                        <div class="panel-footer back-footer-green">
                                        	<p class="float_l">New Visitors : <span class="badge badgebck"> 33 </span></p>
                                            <p class="float_r">Returning Visitors : <span class="badge badgebck"> 3 </span></p>
                                            <div class="clear"></div>
                                        </div>
                                    </div> 
                                </div>
                            </div>
                		</div>
                    </section>
                    <section class="pnnal">
                       <header class="pnnal-heading"><i class="fa fa-simplybuilt"></i> <span class="fntsz16">&nbsp;Forum Moderation</span></header>
                        <div class="pnnal-body">
                        	<div align="center" style="width: 100%; min-height: 100px;">
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 mnimumwidthres">
                                    <div class="circle-tile">
                                            <div class="circle-tile-heading dark-blue">
                                                <i class="fa fa-file-text fa-fw"></i>
                                            </div>
                                        <div class="circle-tile-content dark-blue">
                                            <div class="circle-tile-description text-faded">
                                                New Threads
                                            </div>
                                            <div class="circle-tile-number text-faded">
                                                265
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 mnimumwidthres">
                                    <div class="circle-tile">
                                            <div class="circle-tile-heading dark-blueone">
                                                <i class="fa fa-exclamation-circle fa-fw"></i>
                                            </div>
                                        <div class="circle-tile-content dark-blueone">
                                            <div class="circle-tile-description text-faded">
                                                UnApproved
                                            </div>
                                            <div class="circle-tile-number text-faded">
                                                265
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                		</div>
                    </section>
                </div>
            </div>
        </div>
    </div>
</div>