<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/css/project.css" />
<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
        <div class="col-lg-12">
            <h1>Project Kickoff</h1>
        </div> 
        <div class="col-lg-12 flwup_topcnt fmg_topcnt clear">
        	<div class="col-lg-3 form-group">
            	<span class="date_icon"><i class="fa fa-calendar"></i></span>
                <input type="text" name="ref_date" id="ref_date" class="form-control date_picker lbl_move" value=""  label="Ref Date"/>
            </div>
            <div class="col-lg-3 form-group">
                <input type="text" name="ref_no" id="ref_no" class="form-control lbl_move" value=""  label="Ref No"/>
            </div>
            <div class="col-lg-6 form-group">
                <input type="text" name="nameofthe_property" id="nameofthe_property" class="form-control lbl_move" value=""  label="Name of the Property"/>
            </div>
        </div>
        <div class="col-lg-12 clear">
            <ul class="breadcrumb_area">
                <li><a href="#" class="active">Conception</a></li>
                <li><a href="unit">Unit</a></li>
                <li><a href="#">WBS</a></li>
                <li><a href="turnaround-cost">Turnaround Cost</a></li>
                <li><a href="turnaround-schedule">Turnaround Schedule</a></li>
                <li><a href="#">Team</a></li>
                <li><a href="critical-area">Critical Area</a></li>
                <li><a href="make-brand">Make/Brand</a></li>
                <li><a href="documents">Documents</a></li>
                <li><a href="setup">Setup</a></li>
            </ul>
        </div>
        <div class="col-lg-12 clear">
            <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">
                <div class="col-lg-12">
                    <div class="row">
                        <div class="step_by_liner animated slideInDown"></div>
                        <ul class="step_by">
                            <li>
                                &nbsp;
                            </li>
                            <li>
                                <div class="step_by_sep stepsep_active animated_0_4s slideInRight"><p>1</p></div>
                                <p class="stepli_p2">Selection</p>
                            </li>
                            <li>
                                <div class="step_by_sep animated slideInRight"><p>2</p></div>
                                <p class="stepli_p3">Concept</p>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-12 clear">
            	<div class="kickoff_area col-lg-12 clear">
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <div class="pro_select_box">
                        	<a href="conception-detail" class="ripple">
                            <div class="pro_select pro-land">
                            	<div class="img" style="background-image:url('<?php echo $this->basePath(); ?>/images/flat-img2.jpg');"></div>
                            </div>
                            <div class="info-det">
                                <p class="det_title">Commercial Complex</p>
                                <ul> 
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">No. of Blocks</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 padlr0">
                                            <p>1</p>   
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">No. of Floors</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 padlr0">
                                            <p>2</p>   
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">No. of Flats</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 padlr0">
                                            <p>3</p>   
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">Total Area</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 padlr0">
                                            <p>3200 sq.ft</p>   
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">Saleable Area</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 padlr0">
                                            <p>3000 sq.ft</p>   
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <div class="pro_select_box">
                        	<a href="conception-detail" class="ripple">
                            <div class="pro_select pro-land">
                            	<div class="img" style="background-image:url('<?php echo $this->basePath(); ?>/images/flat-img2.jpg');"></div>
                            </div>
                            <div class="info-det">
                                <p class="det_title">Commercial Complex</p>
                                <ul> 
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">No. of Blocks</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 padlr0">
                                            <p>1</p>   
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">No. of Floors</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 padlr0">
                                            <p>2</p>   
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">No. of Flats</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 padlr0">
                                            <p>3</p>   
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">Total Area</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 padlr0">
                                            <p>3200 sq.ft</p>   
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">Saleable Area</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 padlr0">
                                            <p>3000 sq.ft</p>   
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <div class="pro_select_box">
                        	<a href="conception-detail" class="ripple">
                            <div class="pro_select pro-land">
                            	<div class="img" style="background-image:url('<?php echo $this->basePath(); ?>/images/flat-img2.jpg');"></div>
                            </div>
                            <div class="info-det">
                                <p class="det_title">Commercial Complex</p>
                                <ul> 
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">No. of Blocks</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 padlr0">
                                            <p>1</p>   
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">No. of Floors</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 padlr0">
                                            <p>2</p>   
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">No. of Flats</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 padlr0">
                                            <p>3</p>   
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">Total Area</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 padlr0">
                                            <p>3200 sq.ft</p>   
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">Saleable Area</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 padlr0">
                                            <p>3000 sq.ft</p>   
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <div class="pro_select_box">
                        	<a href="conception-detail" class="ripple">
                            <div class="pro_select pro-land">
                            	<div class="img" style="background-image:url('<?php echo $this->basePath(); ?>/images/flat-img2.jpg');"></div>
                            </div>
                            <div class="info-det">
                                <p class="det_title">Commercial Complex</p>
                                <ul> 
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">No. of Blocks</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 padlr0">
                                            <p>1</p>   
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">No. of Floors</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 padlr0">
                                            <p>2</p>   
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">No. of Flats</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 padlr0">
                                            <p>3</p>   
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">Total Area</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 padlr0">
                                            <p>3200 sq.ft</p>   
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">Saleable Area</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 padlr0">
                                            <p>3000 sq.ft</p>   
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <div class="pro_select_box">
                        	<a href="conception-detail" class="ripple">
                            <div class="pro_select pro-land">
                            	<div class="img" style="background-image:url('<?php echo $this->basePath(); ?>/images/flat-img2.jpg');"></div>
                            </div>
                            <div class="info-det">
                                <p class="det_title">Commercial Complex</p>
                                <ul> 
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">No. of Blocks</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 padlr0">
                                            <p>1</p>   
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">No. of Floors</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 padlr0">
                                            <p>2</p>   
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">No. of Flats</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 padlr0">
                                            <p>3</p>   
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">Total Area</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 padlr0">
                                            <p>3200 sq.ft</p>   
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">Saleable Area</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 padlr0">
                                            <p>3000 sq.ft</p>   
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <div class="pro_select_box">
                        	<a href="conception-detail" class="ripple">
                            <div class="pro_select pro-land">
                            	<div class="img" style="background-image:url('<?php echo $this->basePath(); ?>/images/flat-img2.jpg');"></div>
                            </div>
                            <div class="info-det">
                                <p class="det_title">Commercial Complex</p>
                                <ul> 
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">No. of Blocks</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 padlr0">
                                            <p>1</p>   
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">No. of Floors</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 padlr0">
                                            <p>2</p>   
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">No. of Flats</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 padlr0">
                                            <p>3</p>   
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">Total Area</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 padlr0">
                                            <p>3200 sq.ft</p>   
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">Saleable Area</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 padlr0">
                                            <p>3000 sq.ft</p>   
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <div class="pro_select_box">
                        	<a href="conception-detail" class="ripple">
                            <div class="pro_select pro-land">
                            	<div class="img" style="background-image:url('<?php echo $this->basePath(); ?>/images/flat-img2.jpg');"></div>
                            </div>
                            <div class="info-det">
                                <p class="det_title">Commercial Complex</p>
                                <ul> 
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">No. of Blocks</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 padlr0">
                                            <p>1</p>   
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">No. of Floors</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 padlr0">
                                            <p>2</p>   
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">No. of Flats</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 padlr0">
                                            <p>3</p>   
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">Total Area</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 padlr0">
                                            <p>3200 sq.ft</p>   
                                        </div>
                                    </li>
                                    <li>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 txt_left padlr0"><p><span class="p_label">Saleable Area</span></p></div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 padlr0">
                                            <p>3000 sq.ft</p>   
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>       
        </div>
    </div>
</div>