<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/select2.full.min.js"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/select2.min.css" />
<div class="content_wrapper padlr0">
    <div class="container-fluid">
    	<div class="row">
            <div class="col-lg-12">
                <h1>Lead Allocation Transfer</h1> 
            </div> 
            <div class="col-lg-12 clear">
            	<h1 class="txt_center form_main_h1">Executive Wise</h1>
                <div class="form-group">
                    <div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                        <form class="form-horizontal">
                        <div class="row">   
                            <div class="form-group col-lg-12">
                                <!---------------multiple text tag---------------->
                                <div class="form-group col-lg-12" style="margin:30px 0px;">
                                    <select class="form-control multiple_dropdown lbl_move"  multiple="multiple" label="From Executive..." style="width:100%;">
                                        <option>Practical Guide</option>
                                        <option>Formula-based Manufacturers</option>
                                        <option>Practical ERP </option>
                                        <option>Evolving ERP Strategy</option>
                                        <option>Maximum usability</option>
                                        <option>Practical Guide454</option>
                                        <option>Formulas4545</option>
                                        <option>Prac ERP4545 </option>
                                        <option>Evoltegytrt445</option>
                                        <option>Mait45454y</option>
                                    </select>
                                </div>
                                <div class="form-group col-lg-12" style="margin:30px 0px;">
                                    <select class="form-control multiple_dropdown lbl_move"  multiple="multiple" label="To Executive..." style="width:100%;">
                                        <option>Practical Guide</option>
                                        <option>Formula-based Manufacturers</option>
                                        <option>Practical ERP </option>
                                        <option>Evolving ERP Strategy</option>
                                        <option>Maximum usability</option>
                                        <option>Practical Guide454</option>
                                        <option>Formulas4545</option>
                                        <option>Prac ERP4545 </option>
                                        <option>Evoltegytrt445</option>
                                        <option>Mait45454y</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        </form>
                        <div class="col-lg-12 savebtn_area m_btm30 m_auto no_border">
                            <ul>
                                <li class="save_btn m_auto">
                                    <a href="javascript:void(0);" class="ripple">Transfer</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                
            </div>
    	</div>
    </div>
</div>
<script>
	$(document).ready(function() {
		$(".multiple_dropdown").select2({
		});
	});
</script>