<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/select2.full.min.js"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/select2.min.css" />
<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
        <div class="col-lg-12">
            <h1>Finalisation</h1>
        </div>
        <div class="col-lg-12 clear">
            <div class="col-lg-12 clear">
            	<div class="kickoff_area col-lg-12 clear">
                    <div class="col-lg-12 clear padlr0">
                    	<div class="col-lg-12 col-md-12 col-sm-12 cnt_sliders padlr0">
                    		<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <!-- Wrapper for slides -->
                            <div class="carousel-inner" role="listbox">
                    		<!--step 1-->
                    			<div class="item active">
                                	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                        <div class="">
                                        	<label for="booking_no" class="bk_lbl bk_lbl_inpt">Booking no <span class="colon_r">:</span></label>
                                            <input type="text" class="bk_lbl_inpt bk_inpt1" name="booking_no" id="booking_no" value="007" /> 
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 col-lg-pull-1 col-md-pull-1 col-sm-pull-1">
                                        <div class="col-lg-offset-1">
                                        	<label for="booking_date" class="bk_lbl bk_lbl_inpt"><span class="bkspan_calendar"><i class="fa fa-calendar-o"></i></span> Booking Date <span class="colon_r">:</span></label>
                                            <input type="text" class="date_picker bk_lbl_inpt bk_inpt" name="booking_date" id="booking_date" value="26/01/2016" />
                                        </div>
                                    </div>
                                	<div class="col-lg-6 m_tb10 clear">
                                        <div class="col-lg-8 col-lg-offset-2 clear">
                                            <form class="form-horizontal">
                                                <div class="row">
                                                    <div class="form-group m_top20 col-lg-12 padtop20">
                                                        <select class="form-control single_dropdown lbl_move" label="Select Project..." style="width:100%;">
                                                            <option value=""> <option>
                                                            <option>MIC Anaya1</option>
                                                            <option>MIC Anaya2</option>
                                                            <option>MIC Anaya3</option>
                                                            <option>MIC Anaya4</option>
                                                            <option>MIC Anaya5</option>
                                                            <option>MIC Anaya6</option>
                                                            <option>MIC Anaya7</option>
                                                        </select>
                                                    </div>
                                                    <div class="form-group col-lg-12 padtop20">
                                                        <select class="form-control single_dropdown lbl_move" label="Select Unit No..." style="width:100%;">
                                                            <option value=""> <option>
                                                            <option>A001</option>
                                                            <option>A0012</option>
                                                            <option>A0013</option>
                                                            <option>A0014</option>
                                                            <option>A0015</option>
                                                            <option>A0016</option>
                                                            <option>A0017</option>
                                                        </select>
                                                    </div>
                                                    <div class="form-group col-lg-12 padtop20">
                                                        <div class="radio_check col-lg-11 col-lg-offset-1 col-md-8 col-md-offset-2">
                                                            <p class="col-lg-6">
                                                                <input type="radio" name="buyer_investor" id="buyer" value="buyer" checked="checked">
                                                                <label for="buyer">Buyer</label>
                                                            </p>
                                                            <p class="col-lg-6">
                                                                <input type="radio" name="buyer_investor" id="investor" value="investor">
                                                                <label for="investor">Investor</label>
                                                            </p>
                                                        </div>
                                                    </div>    
                                                    <div class="form-group col-lg-12 padtop10">
                                                    	<input type="text" name="unit_rate" id="unit_rate" class="form-control lbl_move" label="Unit Rate (Per Sq.ft)" />
                                                    </div>
                                                </div> 
                                            </form>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 m_tb10">
                                        <div class="form-group">
                                            <div class="col-lg-12">
                                                <div class="stginner_h5">
                                                    <h5>Unit Detail</h5>
                                                </div>
                                                <form class="form-horizontal stginner_cnt">
                                                    <div class="row">   
                                                        <div class="col-lg-12">
                                                            <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Unit Type</label>
                                                            <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                                                <p>2 BHK</p>   
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row">   
                                                        <div class="col-lg-12">
                                                            <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Block Name</label>
                                                            <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                                                <p>Block A</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row">   
                                                        <div class="col-lg-12">
                                                            <label class="col-lg-5 padlr0 col-md-5 col-sm-5 col-md-4 txt_left control-label">Level</label>
                                                            <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                                                <p>Second Floor</p> 
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row">   
                                                        <div class="col-lg-12">
                                                            <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Area</label>
                                                            <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                                                <p>850.00 Sq.ft</p> 
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row">   
                                                        <div class="col-lg-12">
                                                            <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Rate</label>
                                                            <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                                                <p>3145.00</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row">   
                                                        <div class="col-lg-12">
                                                            <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Base Amount</label>
                                                            <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                                                <p>2673250.00</p> 
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row">   
                                                        <div class="col-lg-12">
                                                            <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Advance Amount</label>
                                                            <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                                                <p>100000.00</p> 
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row">   
                                                        <div class="col-lg-12">
                                                            <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">UDS Land Amount</label>
                                                            <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                                                <p>83452.00</p> 
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row">   
                                                        <div class="col-lg-12">
                                                            <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Other Cost Amount</label>
                                                            <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                                                <p>200000.00</p> 
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row">   
                                                        <div class="col-lg-12">
                                                            <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Gross Amont</label>
                                                            <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                                                <p>2956702.00</p> 
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row">   
                                                        <div class="col-lg-12">
                                                            <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Qualifier Amount</label>
                                                            <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                                                <p>9802.00</p> 
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="net_amnt">
                                                    	<h2>Net Amount</h2>
                                                        <h1>Rs. 2966504.00</h1>
                                                    </div>
                                                </form>  
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-12 savebtn_area padlr0 marg0 clear">
                                    	<ul>
                                        	<li class="save_btn float_r">
                                            	<a href="#carousel-example-generic" data-slide="next" data-stepno="2" data-toggle="tooltip" data-placement="left" class="ripple" title="Next">Next</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                    			<!--step 2-->
                                <div class="item">
                                    <div class="col-lg-12 padlr0">
                                        <div class="col-lg-6 col-md-6 col-sm-8 padlr0">
                                            <div class="form-group m_top20 col-lg-12">
                                                <select class="form-control single_dropdown lbl_move" label="Select Payment Schedule..." style="width:100%;">
                                                    <option value=""> <option>
                                                    <option>Payment Schedule1</option>
                                                    <option>Payment Schedule2</option>
                                                    <option>Payment Schedule3</option>
                                                    <option>Payment Schedule4</option>
                                                    <option>Payment Schedule5</option>
                                                </select>
                                            </div>
                                        </div>				
                                        <div class="col-lg-6 col-md-8 clear">
                                            <p class="heading_checkbox">Select Other Cost</p>
                                            <div class="card">
                                                <div class="card-body" style="min-height:50px; max-height:310px;">
                                                   <!--checkboxtabel-->              
                                                    <ul class="sampleUI list ui-sortable" data-sortable="true" id="unCheckedUl">
                                                    	<li class="tile ui-sortable-handle">
                                                            <div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">
                                                                <label>
                                                                    <input type="checkbox" name="customize_2" tagname='cid' cid="2" id="customize_2" value="2_S">												
                                                                    <span>Car Park</span>
                                                                </label>
                                                            </div>									
                                                        </li>                                                           
                                                        <li class="tile ui-sortable-handle">
                                                            <div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">
                                                                <label>
                                                                    <input type="checkbox" name="customize_4" tagname='cid' cid="4" id="customize_4" value="4_S">												
                                                                    <span>EB Charges</span>
                                                                </label>
                                                            </div>									
                                                        </li>                                                     
                                                        <li class="tile ui-sortable-handle">
                                                            <div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">
                                                                <label>
                                                                    <input type="checkbox" name="customize_11" tagname='cid' cid="11" id="customize_11" value="11_S">												
                                                                    <span>Maintainance</span>
                                                                </label>
                                                            </div>									
                                                        </li>  
                                                        <li class="tile ui-sortable-handle">
                                                            <div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">
                                                                <label>
                                                                    <input type="checkbox" name="customize_11" tagname='cid' cid="11" id="customize_11" value="11_S">												
                                                                    <span>Car Park (Covered)</span>
                                                                </label>
                                                            </div>									
                                                        </li>                                      
                                                    </ul>
                                                   <!--end of checkboxtabel-->               
                                                </div>
                                            </div>
                                        </div>           
                                        <!--end of scrollbar-->
                                        <div class="col-lg-6 col-md-8">
                                            <p class="heading_checkbox">Selected Other Cost</p>
                                            <div class="card">
                                                <div class="card-body" style="min-height:50px; max-height:310px;">
                                                   <!--checkboxtabel-->              
                                                    <ul class="sampleUI list ui-sortable" data-sortable="true" id="checkedUl">
                                                    	<li class="tile ui-sortable-handle check_vendor_background">
                                                            <div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">
                                                                <label>
                                                                    <input type="checkbox" name="customize_1" tagname='cid' cid="1" id="customize_1" value="1_S" checked="checked">
                                                                    <span>Registration</span>
                                                                </label>
                                                            </div>									
                                                        </li>                                                          
                                                        <li class="tile ui-sortable-handle check_vendor_background">
                                                            <div class="checkbox checkbox-styled tile-text vendor_checkboxborder_gray">
                                                                <label>
                                                                    <input type="checkbox" name="customize_3" tagname='cid' cid="3" id="customize_3" value="3_S" checked="checked">
                                                                    <span>Project Development</span>
                                                                </label>
                                                            </div>									
                                                        </li>                                                
                                                    </ul>
                                                   <!--end of checkboxtabel-->               
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-12">
                                            <h1>Payment Schedule</h1>
                                            <div class="table-responsive m_btm20" style="min-height:200px;">
                                                <table class="table table-hover">
                                                    <thead>
                                                        <tr>
                                                            <th>Description</th>
                                                            <th>Date</th>
                                                            <th>Round Off</th>
                                                            <th>Schedule %</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        <tr>
                                                            <td>Booking</td>
                                                            <td>12/05/2012</td>
                                                            <td>0.00</td>
                                                            <td>10%</td>
                                                        </tr>
                                                        <tr>
                                                            <td>Booking</td>
                                                            <td>12/05/2012</td>
                                                            <td>0.00</td>
                                                            <td>10%</td>
                                                        </tr>
                                                        <tr>
                                                            <td>Booking</td>
                                                            <td>12/05/2012</td>
                                                            <td>0.00</td>
                                                            <td>10%</td>
                                                        </tr>
                                                        <tr>
                                                            <td>Booking</td>
                                                            <td>12/05/2012</td>
                                                            <td>0.00</td>
                                                            <td>10%</td>
                                                        </tr>
                                                        <tr>
                                                            <td>Booking</td>
                                                            <td>12/05/2012</td>
                                                            <td>0.00</td>
                                                            <td>10%</td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                    	</div>   
                                    </div>
                                    <div class="col-lg-12 savebtn_area padlr0 marg0 clear">
                                    	<ul>
                                        	<li class="save_btn float_l">
                                            	<a href="#carousel-example-generic"  data-slide="prev" data-stepno="2" data-toggle="tooltip" data-placement="right" class="ripple steps_btn" title="Back">Back</a>
                                            </li>
                                        	<li class="save_btn float_r">
                                            	<a href="#carousel-example-generic" data-slide="next" data-stepno="3" data-toggle="tooltip" data-placement="left" class="ripple" title="Next">Next</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <!--step 3-->
                                <div class="item">
                                    <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 padlr0 m_btm20 unit_kickoff">
                                    	<div class="unitkkoff_topimg"></div>
                                        <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 padlr0 m_btm20">
                                            <div class="form-group padtop20">
                                                <h1 class="txt_center">Finalising through Broker?</h1>
                                                <div class="radio_check col-lg-11 col-lg-offset-1 col-md-8 col-md-offset-2 m_btm20">
                                                    <p class="col-lg-6">
                                                        <input type="radio" name="buyer_yes_no" id="buyer_yes" value="buyer_yes" checked="checked">
                                                        <label for="buyer_yes">Yes</label>
                                                    </p>
                                                    <p class="col-lg-6">
                                                        <input type="radio" name="buyer_yes_no" id="buyer_no" value="buyer_no">
                                                        <label for="buyer_no">No</label>
                                                    </p>
                                                </div>
                                            </div>    
                                            <div class="form-group padtop20 clear">
                                                <input type="text" name="broker_name" id="broker_name" class="form-control lbl_move" label="Broker Name" value="Santhosh" />
                                            </div>
                                            <div class="form-group padtop10">
                                                <input type="text" name="commission" id="commission" class="form-control lbl_move" label="Commission %" value="1.5" />
                                            </div>
                                            <div class="form-group padtop10">
                                                <input type="text" name="amount" id="amount" class="form-control lbl_move" label="Amount" value="3145.00" />
                                            </div>
                                        </div>
                                        <div class="col-lg-12 savebtn_area padlr0 marg0 clear">
                                            <ul>
                                            	<li class="save_btn float_l">
                                                	<a href="#carousel-example-generic"  data-slide="prev" data-stepno="2" data-toggle="tooltip" data-placement="right" class="ripple steps_btn" title="Back">Back</a>
                                                </li>
                                                <li class="save_btn float_r">
                                                	<a href="#carousel-example-generic" data-slide="next" data-stepno="3" data-toggle="tooltip" data-placement="left" class="ripple" title="Continue">Continue</a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <!--step 4-->
                                <div class="item">
                                    <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 padlr0 m_btm20 unit_kickoff">
                                    	<div class="unitkkoff_topimg"></div>
                                        <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 padlr0 m_btm20">
                                            <div class="form-group padtop20">
                                                <h1 class="txt_center">Applying for Loan?</h1>
                                                <div class="radio_check col-lg-11 col-lg-offset-1 col-md-8 col-md-offset-2 m_btm20">
                                                    <p class="col-lg-6">
                                                        <input type="radio" name="loan_yes_no" id="loan_yes" value="loan_yes" checked="checked">
                                                        <label for="loan_yes">Yes</label>
                                                    </p>
                                                    <p class="col-lg-6">
                                                        <input type="radio" name="loan_yes_no" id="loan_no" value="loan_no">
                                                        <label for="loan_no">No</label>
                                                    </p>
                                                </div>
                                            </div>
                                            <div class="form-group padtop20">
                                                <h1 class="txt_center">Did loan got Approved / Sanctioned ?</h1>
                                                <div class="radio_check col-lg-11 col-lg-offset-1 col-md-8 col-md-offset-2 m_btm20">
                                                    <p class="col-lg-6">
                                                        <input type="radio" name="loan_approved_yes_no" id="loan_approved_yes" value="loan_approved_yes" checked="checked">
                                                        <label for="loan_approved_yes">Yes</label>
                                                    </p>
                                                    <p class="col-lg-6">
                                                        <input type="radio" name="loan_approved_yes_no" id="loan_approved_no" value="loan_approved_no">
                                                        <label for="loan_approved_no">No</label>
                                                    </p>
                                                </div>
                                            </div>    
                                            <div class="form-group padtop20 clear">
                                                <input type="text" name="proposal_no" id="proposal_no" class="form-control lbl_move" label="Proposal No" value="456461248941" />
                                            </div>
                                            <div class="form-group padtop10">
                                                <input type="text" name="bank_name" id="bank_name" class="form-control lbl_move" label="Bank Name" value="HDFC BANK" />
                                            </div>
                                            <div class="form-group padtop10">
                                                <input type="text" name="amount" id="amount" class="form-control lbl_move" label="Amount" value="314504464.00" />
                                            </div>
                                            <div class="form-group padtop10">
                                            	<div class="col-lg-12 padlr0">
                                                    <span class="date_icon"><i class="fa fa-calendar"></i></span>
                                                    <input type="text" name="sanction_date" id="sanction_date" class="form-control date_picker lbl_move" label="Sanction Date" value="28/08/2015" />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-12 savebtn_area padlr0 marg0 clear">
                                            <ul>
                                            	<li class="save_btn float_l">
                                                	<a href="#carousel-example-generic"  data-slide="prev" data-stepno="3" data-toggle="tooltip" data-placement="right" class="ripple steps_btn" title="Back">Back</a>
                                                </li>
                                                <li class="save_btn float_r">
                                                	<a href="#carousel-example-generic" data-slide="next" data-stepno="4" data-toggle="tooltip" data-placement="left" class="ripple" title="Continue">Continue</a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <!--step 5-->
                                <div class="item">
                                    <div class="col-lg-12">
                                        <h1>Check List</h1>
                                        <div class="table-responsive m_btm20" style="min-height:200px;">
                                            <table class="table table-hover">
                                                <thead>
                                                    <tr>
                                                        <th width="4%">Select</th>
                                                        <th>Description</th>
                                                        <th>Date</th>
                                                        <th>Collection Status</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr>
                                                        <td class="tbl_input_td">
                                                        	<div class="radio_check">
                                                                <p>
                                                                    <input type="checkbox" value="" id="select1" name="select1" />
                                                                    <label for="select1" class="ripple"></label>
                                                                </p>
                                                            </div>
                                                        </td>
                                                        <td>Booking Check Sheet</td>
                                                        <td>12/05/2012</td>
                                                        <td>Status</td>
                                                    </tr>
                                                    <tr>
                                                        <td class="tbl_input_td">
                                                        	<div class="radio_check">
                                                                <p>
                                                                    <input type="checkbox" value="" id="select2" name="select2" />
                                                                    <label for="select2" class="ripple"></label>
                                                                </p>
                                                            </div>
                                                        </td>
                                                        <td>Registration Details</td>
                                                        <td>12/05/2012</td>
                                                        <td>Status</td>
                                                    </tr>
                                                    <tr>
                                                        <td class="tbl_input_td">
                                                        	<div class="radio_check">
                                                                <p>
                                                                    <input type="checkbox" value="" id="select3" name="select3" />
                                                                    <label for="select3" class="ripple"></label>
                                                                </p>
                                                            </div>
                                                        </td>
                                                        <td>Address Proof</td>
                                                        <td>12/05/2012</td>
                                                        <td>Status</td>
                                                    </tr>
                                                    <tr>
                                                        <td class="tbl_input_td">
                                                        	<div class="radio_check">
                                                                <p>
                                                                    <input type="checkbox" value="" id="select4" name="select4" />
                                                                    <label for="select4" class="ripple"></label>
                                                                </p>
                                                            </div>
                                                        </td>
                                                        <td>Check List 4</td>
                                                        <td>12/05/2012</td>
                                                        <td>Status</td>
                                                    </tr>
                                                    <tr>
                                                        <td class="tbl_input_td">
                                                        	<div class="radio_check">
                                                                <p>
                                                                    <input type="checkbox" value="" id="select5" name="select5" />
                                                                    <label for="select5" class="ripple"></label>
                                                                </p>
                                                            </div>
                                                        </td>
                                                        <td>Check List 5</td>
                                                        <td>12/05/2012</td>
                                                        <td>Status</td>
                                                    </tr>
                                                    <tr>
                                                        <td class="tbl_input_td">
                                                        	<div class="radio_check">
                                                                <p>
                                                                    <input type="checkbox" value="" id="select6" name="select6" />
                                                                    <label for="select6" class="ripple"></label>
                                                                </p>
                                                            </div>
                                                        </td>
                                                        <td>Check List 6</td>
                                                        <td>12/05/2012</td>
                                                        <td>Status</td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                    <div class="col-lg-12 savebtn_area padlr0 marg0 clear">
                                        <ul>
                                            <li class="save_btn float_l">
                                                <a href="#carousel-example-generic"  data-slide="prev" data-stepno="4" data-toggle="tooltip" data-placement="right" class="ripple steps_btn" title="Back">Back</a>
                                            </li>
                                            <li class="save_btn float_r">
                                                <a href="#carousel-example-generic" data-slide="next" data-stepno="5" data-toggle="tooltip" data-placement="left" class="ripple" title="Continue">Continue</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <!--step 6-->
                                <div class="item">
                                    <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 padlr0 m_btm20 unit_kickoff">
                                    	<div class="unitkkoff_topimg"></div>
                                        <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 padlr0 m_btm20">
                                            <div class="form-group m_top20 padtop20 clear">
                                                <input type="text" name="registration_name" id="registration_name" class="form-control lbl_move" label="Registration Name" value="Santhosh Narayanan" />
                                            </div>
                                            <div class="form-group padtop10">
                                                <input type="text" name="post_sale" id="post_sale" class="form-control lbl_move" label="Post Sale Executive" value="Mugesh Kumar" />
                                            </div>
                                            <div class="form-group padtop10">
                                                <input type="text" name="adv_amount" id="adv_amount" class="form-control lbl_move" label="Advance Amount" value="100000.00" />
                                            </div>
                                        </div>
                                        
                                        <div class="col-lg-12 savebtn_area padlr0 marg0 clear">
                                            <ul>
                                            	<li class="save_btn float_l">
                                                	<a href="#carousel-example-generic"  data-slide="prev" data-stepno="5" data-toggle="tooltip" data-placement="right" class="ripple steps_btn" title="Back">Back</a>
                                                </li>
                                                <li class="save_btn float_r">
                                                	<a href="javascript:void(0);" data-toggle="tooltip" data-placement="left" class="ripple" title="Finalise">Finalise</a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                
                    		</div>
                    	</div>
                    </div>
            	</div>
            </div>       
        </div>
    </div>
</div>
<script type="text/javascript">
	$(document).ready(function() {
		$(".single_dropdown").select2({
			placeholder: "",
			allowClear: true,
		});
	});
	$('.cnt_sliders .carousel').carousel({
		interval: false
	})
</script>