<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
    	<div class="right_lightbox">
        	<div class="right_lightbox_close">
                <span class="right_lightbox_closeicon"><i class="fa fa-times"></i></span>
            </div>
            <div class="right_lbox_inner lead_register_rbox">
                <h2>Lead Register</h2>
                <div class="right_lbox_inner_cnt">
                    <div class="col-lg-12 ldrgstr_detail_pro padlr0">
                    	<div class="stgedit_btn topright_6 brad_50"><a href="javascript:void(0);" class="ripple"><span><i class="fa fa-pencil"></i></span></a></div>
                    	<div class="col-lg-4 flwup_proimg_area">
                            <div class="flwup_proimg brad_200">
                                <div class="img_star brad_50">
                                    <span class="glyphicon glyphicon-star txt_center"></span>
                                </div>
                                <img src="<?php echo $this->basePath(); ?>/images/flwup_proimg.png" class="brad_200" alt="" title=""/>
                            </div>
                        </div>
                        <div class="col-lg-8 col-md-12 flwup_procnt">
                            <h1 class="name">Balaji ulaganathan.U <br />
                            	<span>14/05/2015</span>
                            </h1>
                            <p class="rwd_textcenter"><span class="p_label">Type :</span> Buyer</p>
                        </div>
                        <ul class="col-lg-12 ldrgstr_detail_pro_ul clear">
                            <li>
                                <div class="col-lg-6">
                                    <h3><a href="#" class="phone"><span><i class="fa fa-phone"></i></span>+91 7205 525 658</a></h3>
                                </div>
                                <div class="col-lg-6">
                                    <h3><a href="#" class="mail"><span><i class="glyphicon glyphicon-envelope"></i></span>dddswedew02@gmail.com</a></h3>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="col-lg-12 padlr0">
                        <div class="form-horizontal stginner_cnt">
                            <div class="row">   
                                <div class="col-lg-12">
                                    <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label"><span class="p_lbl_icon"><i class="fa fa-suitcase"></i></span>Projects</label>
                                    <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                        <ul class="flwup_rcnt_inrproject">
                                            <li class="white_inner"><span class="pad_t3">m</span><p>Mic Anaya</p></li>
                                            <li class="white_inner"><span><img src="<?php echo $this->basePath(); ?>/images/flat-img2.jpg" alt="" title=""/></span><p>Mic City</p></li>
                                            <li class="white_inner"><span><img src="<?php echo $this->basePath(); ?>/images/test_img1.jpg" alt="" title=""/></span><p>Mic Anaya Phase 2</p></li>
                                        </ul>  
                                    </div>
                                </div>
                            </div>
                            <div class="row">   
                                <div class="col-lg-12">
                                    <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label"><span class="p_lbl_icon"><i class="fa fa-map-marker"></i></span>Prefered Locations</label>
                                    <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                        <ul class="flwup_rcnt_inrproject">
                                            <li class="white_inner"><span><img src="<?php echo $this->basePath(); ?>/images/test_img1.jpg" alt="" title=""/></span><p>Chennai</p></li>
                                            <li class="white_inner"><span><img src="<?php echo $this->basePath(); ?>/images/flat-img2.jpg" alt="" title=""/></span><p>Bangalore City</p></li>
                                            <li class="white_inner"><span class="pad_t3">t</span><p>Trichy</p></li>
                                            <li class="white_inner"><span><img src="<?php echo $this->basePath(); ?>/images/test_img1.jpg" alt="" title=""/></span><p>Pondicherry</p></li>
                                            <li class="white_inner"><span><img src="<?php echo $this->basePath(); ?>/images/flat-img2.jpg" alt="" title=""/></span><p>Hyderabad</p></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="row">   
                                <div class="col-lg-12">
                                    <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label"><span class="p_lbl_icon"><i class="fa fa-magic"></i></span>Lead Source</label>
                                    <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                        <ul class="flwup_rcnt_inrproject">
                                            <li class="white_inner"><span><img src="<?php echo $this->basePath(); ?>/images/test_img1.jpg" alt="" title=""/></span><p>word of Mouth</p></li>
                                            <li class="white_inner"><span><img src="<?php echo $this->basePath(); ?>/images/flat-img2.jpg" alt="" title=""/></span><p>friends</p></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="row">   
                                <div class="col-lg-12">
                                    <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label"><span class="p_lbl_icon"><i class="fa fa-user"></i></span>Reference buyer name</label>
                                    <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                        <p>Balaji ulaganathan</p> 
                                    </div>
                                </div>
                            </div>
                            <div class="row">   
                                <div class="col-lg-12">
                                    <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label"><span class="p_lbl_icon"><i class="fa fa-user-secret"></i></span>Executive</label>
                                    <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                        <p>Ranganathan Mohanraj</p>
                                    </div>
                                </div>
                            </div>
                            <div class="row">   
                                <div class="col-lg-12">
                                    <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label"><span class="p_lbl_icon"><i class="glyphicon glyphicon-flag"></i></span>Status</label>
                                    <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                        <p>Warm</p> 
                                    </div>
                                </div>
                            </div>
                            <div class="row">   
                                <div class="col-lg-12">
                                    <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label"><span class="p_lbl_icon"><i class="glyphicon glyphicon-calendar"></i></span>Next Call Date</label>
                                    <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                        <p>01/08/2015</p> 
                                    </div>
                                </div>
                            </div>
                            <div class="row">   
                                <div class="col-lg-12">
                                    <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label"><span class="p_lbl_icon"><i class="glyphicon glyphicon-phone-alt"></i></span>Next Call Type</label>
                                    <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                        <p>Visit</p> 
                                    </div>
                                </div>
                            </div>
                        </div>  
                    </div>
                    <p class="rightlbox_btn">
                    	<a href="followup" class="ripple">Follow up</a>
                        <a href="#" class="ripple">Follow up history</a>
                    	<a href="followup-details" class="ripple">View more details</a>
                    </p>
                </div>
            </div>            
        </div>
        <div class="col-lg-12">
            <h1>Lead Register</h1>
        </div>
        <div class="col-lg-12">
            <div class="table-responsive">                            
                <table class="table lead_table table-hover">
                    <thead>
                        <tr>
                            <th>&nbsp;</th>
                            <th>Lead name</th>
                            <th>Lead date</th>
                            <th>Lead type</th>
                            <th>Contact number</th>
                            <th>Projects</th>
                            <th>Preffered location</th>
                            <th>Executive</th>
                            <th>Created by</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="tr_hot">
                            <td>
                                <div class="flwup_proimg ldrgstr_proimg brad_200">
                                    <div class="img_star brad_50">
                                        <span class="glyphicon glyphicon-star txt_center"></span>
                                    </div>
                                    <img src="<?php echo $this->basePath(); ?>/images/flat-img2.jpg" class="brad_200" alt="" title=""/>
                                </div>
                            </td>
                            <td>Ranganathan Mohanraj</td>
                            <td>11/07/2015</td>
                            <td>Buyer</td>
                            <td>7206565611</td>
                            <td>Mic Anaya, Mic new city </td>
                            <td>Chennai,Bangalore</td>
                            <td>Senthil Kumaran</td>
                            <td>Harish Dhananjayan</td>
                        </tr>
                        <tr class="tr_warm">
                            <td>
                                <div class="flwup_proimg ldrgstr_proimg brad_200">
                                    <div class="img_star brad_50">
                                        <span class="glyphicon glyphicon-star txt_center"></span>
                                    </div>
                                    <img src="<?php echo $this->basePath(); ?>/images/flwup_proimg.png" class="brad_200" alt="" title=""/>
                                </div>
                            </td>
                            <td>Balaji ulaganathan</td>
                            <td>11/07/2015</td>
                            <td>Site visit</td>
                            <td>7206565611</td>
                            <td>Mic Anaya </td>
                            <td>Seattle, USA</td>
                            <td>Senthil Kumaran</td>
                            <td>Ranganathan Mohanraj</td>
                        </tr>
                        <tr class="tr_cold">
                            <td>
                                <div class="flwup_proimg ldrgstr_proimg brad_200">
                                    <div class="img_star brad_50">
                                        <span class="glyphicon glyphicon-star txt_center"></span>
                                    </div>
                                    <img src="<?php echo $this->basePath(); ?>/images/pro_img.jpg" class="brad_200" alt="" title=""/>
                                </div>
                            </td>
                            <td>Harish Dhananjayan</td>
                            <td>11/07/2015</td>
                            <td>Seller</td>
                            <td>7206565611</td>
                            <td>Mic Anaya, Mic new city </td>
                            <td>West Bengal, Thiruvananthapuram</td>
                            <td>Balaji ulaganathan</td>
                            <td>Senthil Kumaran</td>
                        </tr>
                        <tr class="tr_warm">
                            <td>
                                <div class="flwup_proimg ldrgstr_proimg brad_200">
                                    <div class="img_star brad_50">
                                        <span class="glyphicon glyphicon-star txt_center"></span>
                                    </div>
                                    <img src="<?php echo $this->basePath(); ?>/images/avatar.jpg" class="brad_200" alt="" title=""/>
                                </div>
                            </td>
                            <td>Senthil Kumaran</td>
                            <td>11/07/2015</td>
                            <td>Buyer</td>
                            <td>7206565611</td>
                            <td>Mic Anaya, Mic new city </td>
                            <td>Andhra Pradesh, Uttar Pradesh</td>
                            <td>Harish Dhananjayan</td>
                            <td>Balaji ulaganathan</td>
                        </tr>
                        <tr class="tr_hot">
                            <td>
                                <div class="flwup_proimg ldrgstr_proimg brad_200">
                                    <div class="img_star brad_50">
                                        <span class="glyphicon glyphicon-star txt_center"></span>
                                    </div>
                                    <img src="<?php echo $this->basePath(); ?>/images/flat-img2.jpg" class="brad_200" alt="" title=""/>
                                </div>
                            </td>
                            <td>Ranganathan Mohanraj</td>
                            <td>11/07/2015</td>
                            <td>Buyer</td>
                            <td>7206565611</td>
                            <td>Mic Anaya, Mic new city </td>
                            <td>Chennai,Bangalore</td>
                            <td>Senthil Kumaran</td>
                            <td>Harish Dhananjayan</td>
                        </tr>
                        <tr class="tr_warm">
                            <td>
                                <div class="flwup_proimg ldrgstr_proimg brad_200">
                                    <div class="img_star brad_50">
                                        <span class="glyphicon glyphicon-star txt_center"></span>
                                    </div>
                                    <img src="<?php echo $this->basePath(); ?>/images/flwup_proimg.png" class="brad_200" alt="" title=""/>
                                </div>
                            </td>
                            <td>Balaji ulaganathan</td>
                            <td>11/07/2015</td>
                            <td>Site visit</td>
                            <td>7206565611</td>
                            <td>Mic Anaya </td>
                            <td>Seattle, USA</td>
                            <td>Senthil Kumaran</td>
                            <td>Ranganathan Mohanraj</td>
                        </tr>
                        <tr class="tr_warm">
                            <td>
                                <div class="flwup_proimg ldrgstr_proimg brad_200">
                                    <div class="img_star brad_50">
                                        <span class="glyphicon glyphicon-star txt_center"></span>
                                    </div>
                                    <img src="<?php echo $this->basePath(); ?>/images/flwup_proimg.png" class="brad_200" alt="" title=""/>
                                </div>
                            </td>
                            <td>Balaji ulaganathan</td>
                            <td>11/07/2015</td>
                            <td>Site visit</td>
                            <td>7206565611</td>
                            <td>Mic Anaya </td>
                            <td>Seattle, USA</td>
                            <td>Senthil Kumaran</td>
                            <td>Ranganathan Mohanraj</td>
                        </tr>
                        <tr class="tr_cold">
                            <td>
                                <div class="flwup_proimg ldrgstr_proimg brad_200">
                                    <div class="img_star brad_50">
                                        <span class="glyphicon glyphicon-star txt_center"></span>
                                    </div>
                                    <img src="<?php echo $this->basePath(); ?>/images/pro_img.jpg" class="brad_200" alt="" title=""/>
                                </div>
                            </td>
                            <td>Harish Dhananjayan</td>
                            <td>11/07/2015</td>
                            <td>Seller</td>
                            <td>7206565611</td>
                            <td>Mic Anaya, Mic new city </td>
                            <td>West Bengal, Thiruvananthapuram</td>
                            <td>Balaji ulaganathan</td>
                            <td>Senthil Kumaran</td>
                        </tr>
                        <tr class="tr_cold">
                            <td>
                                <div class="flwup_proimg ldrgstr_proimg brad_200">
                                    <div class="img_star brad_50">
                                        <span class="glyphicon glyphicon-star txt_center"></span>
                                    </div>
                                    <img src="<?php echo $this->basePath(); ?>/images/pro_img.jpg" class="brad_200" alt="" title=""/>
                                </div>
                            </td>
                            <td>Harish Dhananjayan</td>
                            <td>11/07/2015</td>
                            <td>Seller</td>
                            <td>7206565611</td>
                            <td>Mic Anaya, Mic new city </td>
                            <td>West Bengal, Thiruvananthapuram</td>
                            <td>Balaji ulaganathan</td>
                            <td>Senthil Kumaran</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div> 
    </div>
</div>
<script>
$(function(){
    $('.lead_table tr').click(function(){ 
		$('.right_lightbox').show();
		$('.left-panel').removeClass('collapsed');
		$('.l_menuicon_nav').removeClass('cross');
    });
	$('.right_lightbox_close').click(function(){
		$('.right_lightbox').hide();
		if ($(window).width() >=980){
			$('.left-panel').addClass('collapsed');	
			$('.l_menuicon_nav').addClass('cross');
		}
	});
});
</script>