<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
        <div class="col-lg-12">
        	<h1>Lead Allocation</h1>
        </div>
        <div class="col-lg-12">
        	<div class="leadallocation_tab col-lg-8 col-lg-offset-2">
            	<nav class="navbar inrmdltab_navbar navbar-default">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle mdlnvbr_tgl collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand inrmdl_navbrand ripple" href="javascript:void(0);" > Select Menus</a>
                    </div>
                    <div id="navbar" class="navbar-collapse padlr0 collapse">
                        <!-- Nav tabs -->
                        <ul class="nav nav-tabs allocate_tabs" role="tablist">
                            <li role="presentation" class="active col-lg-6 padlr0">
                                <a href="#bulk_allocation" aria-controls="home" role="tab" data-toggle="tab"><span class="brad_50"><i class="fa fa-cubes"></i></span> Bulk Allocation / Transfer</a>
                            </li>
                            <li role="presentation" class="col-lg-6 padlr0">
                                <a href="#invidual_allocation" aria-controls="profile" role="tab" data-toggle="tab"><span class="brad_50"><i class="fa fa-cube"></i></span> Individual Allocation / Transfer</a>
                            </li>
                        </ul>
                    </div>
                </nav>
                <!-- Tab panes -->
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane animated fadeInUp active" id="bulk_allocation">
                        <ul class="leadallocation_ul">
                            <li class="col-lg-6 col-md-6 col-sm-6">
                            	<a href="javascript:void(0);" class="ripple">
                                    <span></span>
                                    <p class="txt_center">Project Wise Allocation Transfer</p>
                                </a>
                            </li> 
                            <li class="col-lg-6 col-md-6 col-sm-6">
                            	<a href="javascript:void(0);" class="ripple">
                                    <span style="background-position:118px 0px;"></span>
                                    <p class="txt_center">Executive Wise Allocation Transfer</p>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div role="tabpanel" class="tab-pane animated fadeInUp" id="invidual_allocation">
                        <ul class="leadallocation_ul">
                        	<li class="col-lg-6 col-md-6 col-sm-6">
                            	<a href="javascript:void(0);" class="ripple">
                                    <span style="background-position:0px 124px;"></span>
                                    <p class="txt_center">Lead Base Allocation</p>
                                </a>
                            </li>
                            <li class="col-lg-6 col-md-6 col-sm-6">
                            	<a href="javascript:void(0);" class="ripple">
                                    <span style="background-position:118px 124px;"></span>
                                    <p class="txt_center">VIP Lead Allocation</p>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>    
        </div> 
    </div>
</div>