<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/select2.full.min.js"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/select2.min.css" />
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/workorder.css"/>
<div class="content_wrapper padlr0">
  <div class="container-fluid padlr0">
    <div class="col-lg-12">
      <h1>Lease / Rental Bill</h1>
    </div>
    <div class="col-lg-12">
      <ul class="edit-lbl">
        <li class="col-lg-4">
          <label>Date : </label>
          <p class="edit-abl">30/05/2016</p>
        </li>
        <li class="col-lg-5">
          <label>Voucher No : </label>
          <p class="edit-abl">HYT4566</p>
        </li>
      </ul>
    </div>
    <!---------------------------Form Area--------------------------->
        <div class="clearfix"></div>
    <div class="col-lg-12 flwup_topcnt fmg_topcnt clear" style="margin-bottom:10px;">
      <div class="col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-4 col-sm-offset-0 form-group">
        <input type="text" name="target_period"  class="form-control lbl_move" value=""  label="Property Name"/>
      </div>
      <div class="col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-4 col-sm-offset-0 form-group">
        <input type="text" name="target_period"  class="form-control lbl_move" value=""  label="Name of the Tenant"/>
      </div>
      <div class="col-lg-4 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-4 col-sm-offset-0 form-group">
        <input type="text" name="target_period"  class="form-control lbl_move" value=""  label="Rent Period"/>
      </div>
    </div>
    
    <!---------------------------Form Area---------------------------> 
    <!---------------------------Particulars Detalis--------------------------->
        <div class="clearfix"></div>
    <div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0"> 
      <!---------------------------Particulars Detalis left--------------------------->
       <div class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0">
        <div class="par-lessbill">
          <h1>Particulars</h1>
          <ul>
            <h2>Current Due</h2>
            <li>
              <label>Rental Charges</label>
              <i class="fa fa-inr cur-css"></i>
              <input class="parent_text" type="text" value="20,000.00" placeholder="00.00" name="">
            </li>
            <li>
              <label>Maintenance Bill</label>
              <i class="fa fa-inr cur-css"></i>
              <input class="parent_text" type="text" value="20,000.00" placeholder="00.00" name="">
            </li>
            <li>
              <label>EB Charges</label>
              <i class="fa fa-inr cur-css"></i>
              <input class="parent_text" type="text" value="20,000.00" placeholder="00.00" name="">
            </li>
            <li>
              <label>Telephone Charges</label>
              <i class="fa fa-inr cur-css"></i>
              <input class="parent_text" type="text" value="20,000.00" placeholder="00.00" name="">
            </li>
          </ul>
          <ul class="bgs-grs">
            <li>
              <label>Gross Amount</label>
              <i class="fa fa-inr cur-css"></i>
              <input class="parent_text" type="text" value="20,000.00" placeholder="00.00" name="" readonly="readonly">
            </li>
            <li>
              <label>Service Tax 14.5%</label>
              <i class="fa fa-inr cur-css"></i>
              <input class="parent_text" type="text" value="20,000.00" placeholder="00.00" name="">
            </li>
            <li>
              <label>Total Amount</label>
              <i class="fa fa-inr cur-css"></i>
              <input class="parent_text" type="text" value="20,000.00" placeholder="00.00" name="" readonly="readonly">
            </li>
          </ul>
          <ul>
            <h2>Previous Bill Due</h2>
            <li>
              <label>Bill No.08 on 05/02/2016</label>
              <i class="fa fa-inr cur-css"></i>
              <input class="parent_text" type="text" value="20,000.00" placeholder="00.00" name="">
            </li>
            <li>
              <label>Late Fess</label>
              <i class="fa fa-inr cur-css"></i>
              <input class="parent_text" type="text" value="20,000.00" placeholder="00.00" name="">
            </li>
            <li>
              <label>Total Payable</label>
              <i class="fa fa-inr cur-css"></i>
              <input class="parent_text" type="text" value="20,000.00" placeholder="00.00" name="">
            </li>
          </ul>
        </div>
        <div class="pei-rem">
          <label>Remarks</label>
          <textarea></textarea>
        </div>
      </div>
      <!---------------------------Particulars Detalis left end---------------------------> 
      <!---------------------------Previous Detalis right --------------------------->
      <div class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-6 col-sm-offset-0">
        <div class="par-lessbill par-prew">
          <h1>Previous Detalis</h1>
          <ul>
            <li>
              <label>Previouse Paid</label>
              <span>Rs.18,150.00 on 05/02/2016</span> </li>
            <li>
              <label>Previouse Due</label>
              <span>Bill No.08 on 05/02/2016 for Rs.8,150.00</span> </li>
            <li>
              <label>Late Fees</label>
              <span>Rs.850.00</span> </li>
            <li>
              <label>Next Due</label>
              <span>Rs.17,175.00 on 05/03/2016</span> </li>
            <li>
              <label>Security Deposit</label>
              <span>Rs.10,00,000</span> </li>
            <li>
              <label>Reminders</label>
              <span>Sample Reminders</span> </li>
            <li>
              <label>Note</label>
              <span>Sample Notes</span> </li>
            <li>
              <label>Others1</label>
              <span>Sample Others</span> </li>
            <li>
              <label>Others2</label>
              <span>Sample Others</span> </li>
          </ul>
        </div>
        <div class="totalpay">
          <label>Total Amount Payable</label>
          <i class="fa fa-inr cur-css-tol"></i>
          <p>on before 05/03/2016</p>
          <span>56,000.00</span> </div>
      </div>
      <!---------------------------Previous Detalis right end---------------------------> 
    </div>
      <div class="col-lg-12 m_tb40 padlr0 clear">
       
    
      </div>
  </div>
</div>
<!---------------------------button--------------------------->
<div class="col-lg-12 savebtn_area clear">
  <ul>
    <li class="dropdown save_btn float_r waves-effect waves-light"> <a href="javascript:void(0);" class="ripple">Submit</a> </li>
  </ul>
</div>
<!---------------------------button---------------------------> 
<script>
$('.edit-abl').bind('click',
               function(){
                   $(this).attr('contentEditable',true);
               });
</script>