<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/select2.full.min.js"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/select2.min.css" />
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/workorder.css"/>
<div class="content_wrapper padlr0">
  <div class="container-fluid padlr0">
    <div class="col-lg-12">
      <h1>Maintenance Bill</h1>
    </div>
    <div class="col-lg-12"> 
  <ul class="edit-lbl">
    <li class="col-lg-4">
    <label>Bill Date : </label><p class="edit-abl">30/05/2016</p>
    </li>
        <li class="col-lg-4">
    <label>BillNo : </label><p class="edit-abl">HYT4566</p>
    </li>
      </ul>
    
    </div>
    <!---------------------------Form Area--------------------------->
    <div class="col-lg-12 flwup_topcnt fmg_topcnt clear" style="margin-bottom:10px;">
      <div class="col-lg-5 col-lg-offset-0 col-md-5 col-md-offset-0 col-sm-5 col-sm-offset-0 form-group">
        <input type="text" name="target_period"  class="form-control lbl_move" value="CRM / Cum / Ravi"  label="Project / Unit / Buyer"/>
      </div>
      <div class="col-lg-3 col-lg-offset-0 col-md-3 col-md-offset-0 col-sm-3 col-sm-offset-0 form-group"> <span class="date_icon"><i class="fa fa-calendar"></i></span>
        <input type="text" name="target_period" id="target_period" class="form-control lbl_move" value="17/03/2016"  label="From Date"/>
      </div>
      <div class="col-lg-3 col-lg-offset-0 col-md-3 col-md-offset-0 col-sm-3 col-lg-offset-0 col-md-5 col-md-offset-0 col-sm-5 col-sm-offset-0 form-group"> <span class="date_icon"><i class="fa fa-calendar"></i></span>
        <input type="text" name="target_period" id="target_period" class="form-control lbl_move" value="30/03/2016"  label="To Date"/>
      </div>
    </div>
    
    <!---------------------------Form Area--------------------------->
    <div class="col-lg-12 clear">
    <!---------------------------table area--------------------------->
      <div class="table-responsive animated fadeInUp">
        <table class="table tbltop_bdr0">
          <thead>
            <tr>
              <th>Service Name</th>
              <th>Unit</th>
              <th class="text-right">Qty</th>
              <th class="text-right">Rate</th>
              <th class="text-right">Amount</th>
              <th>&nbsp; </th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td width="15%"><input class="tbl_input" type="text" value="Service 0" /></td>
              <td width="5%"><b class="amnt-rat">Cum</b></td>
              <td width="5%"><input class="tbl_input text-right" type="text" value="5" /></td>
              <td width="6%"><input class="tbl_input text-right" type="text" value="540.05" /></td>
              <td width="7%"><b class="amnt-rat text-right">2700.25</b></td>
              <td width="2%" align="center" class="action_btns_td"><ul class="action_btns">
                  <li> <a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="left" data-original-title="Delete"></i></a> </li>
                </ul></td>
            </tr>
            <tr>
              <td width="15%"><input class="tbl_input" type="text" value="Service 0" /></td>
              <td width="5%"><b class="amnt-rat">Cum</b></td>
              <td width="5%"><input class="tbl_input text-right" type="text" value="5" /></td>
              <td width="6%"><input class="tbl_input text-right" type="text" value="540.05" /></td>
              <td width="7%"><b class="amnt-rat text-right">2700.25</b></td>
              <td width="2%" align="center" class="action_btns_td"><ul class="action_btns">
                  <li> <a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="left" data-original-title="Delete"></i></a> </li>
                </ul></td>
            </tr>
            <tr>
              <td width="15%"><input class="tbl_input" type="text" value="Service 0" /></td>
              <td width="5%"><b class="amnt-rat">Cum</b></td>
              <td width="5%"><input class="tbl_input text-right" type="text" value="5" /></td>
              <td width="6%"><input class="tbl_input text-right" type="text" value="540.05" /></td>
              <td width="7%"><b class="amnt-rat text-right">2700.25</b></td>
              <td width="2%" align="center" class="action_btns_td"><ul class="action_btns">
                  <li> <a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="left" data-original-title="Delete"></i></a> </li>
                </ul></td>
            </tr>
            <tr>
              <td colspan="3"></td>
              <td align="right" class="rate_pri">Total</td>
              <td width="7%"><b class="amnt-rat text-right">2700.25</b></td>
              <td>&nbsp;</td>
            </tr>
          </tbody>
        </table>
      </div>
        <!---------------------------table area--------------------------->
        
      <!---------------------------Overall amount area--------------------------->
      <div class="col-lg-12 m_tb40 padlr0 clear">
        <div class="col-lg-7 col-lg-offset-0 col-md-7 col-md-offset-0 col-sm-7">
          <textarea rows="3" class="narration_textarea" placeholder="Maintenance Bill Remarks..."></textarea>
        </div>
        <div class="col-lg-5 col-lg-offset-0 col-md-5 col-md-offset-0 col-sm-5 padlr0">
   <ul class="nt-pay">
   <li><label>Service Tax 14.5% : </label> <i class="fa fa-inr cur-cs"></i><b>1500.02</b></li>
    <li><label>Net Amount : </label> <i class="fa fa-inr cur-cs"></i><b>1500.02</b></li>
     <li><label>Bill Amount : </label> <i class="fa fa-inr cur-cs"></i><b>2700.25</b></li>
   </ul>
        </div>
      </div>
     <!---------------------------Overall amount area end--------------------------->
    </div>
  </div>
</div>
<!---------------------------button--------------------------->
<div class="col-lg-12 savebtn_area clear">
  <ul>
    <li class="dropdown save_btn float_r"> <a href="javascript:void(0);" class="ripple">Submit</a> </li>
  </ul>
</div>
<!---------------------------button--------------------------->
<script>
$('.edit-abl').bind('click',
               function(){
                   $(this).attr('contentEditable',true);
               });
</script>