<div class="content_wrapper padlr0">
    <div class="container-fluid">
        <div class="col-lg-12">
            <h1>Project Info of 
                <div class="btn-group proname_btn">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">RMZ Millenia <span class="edit_symbols" data-placement="right" data-toggle="tooltip" data-original-title="Change&nbsp;project&nbsp;name"><i class="fa fa-caret-down "></i></span></a> 							
                    <div class="dropdown-menu toolbar_ddown proname_ddown arrow" role="menu">
                        <ul>
                           <li><a href="#">Mayflower Mayflower</a></li>
                           <li><a href="#">AkashManor</a></li>
                           <li><a href="#">Isha</a></li>
                           <li><a href="#">RMZ Millenia</a></li>
                           <li><a href="#">APS Avenue</a></li>
                           <li><a href="#">Aura One</a></li>
                           <li><a href="#">HO - Micromen Properties Ltd</a></li>
                           <li><a href="#">HO - Isha Homes PVT LTD</a></li>
                           <li><a href="#">BO - APS - Chennai</a></li>
                           <li><a href="#">ArunBuilders</a></li>
                           <li><a href="#">Aura One</a></li>
                           <li><a href="#">HO - Prince Foundation Ltd</a></li>
                           <li><a href="#">Prince Block 1</a></li>
                           <li><a href="#">Prince Block 2</a></li>
                        </ul>
                    </div>
                </div>
            </h1>
        </div> 
        <div class="col-lg-12 clear">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">
                    <div class="col-lg-12">
                        <div class="row">
                            <div class="step_by_liner animated slideInDown"></div>
                            <ul class="step_by stepby_mb60">
                                <li>
                                    <div class="step_by_sep animated_0_4s slideInRight"><p>1</p></div>
                                    <p class="stepli_p1">Land Cost Calculation</p>
                                </li>
                                <li>
                                    <div class="step_by_sep stepsep_active animated slideInRight"><p>2</p></div>
                                    <p class="stepli_p2">Other Cost Details</p>
                                </li>
                                <li class="opacity_08">
                                    <div class="step_by_sep animated_1_5s slideInRight"><p>3</p></div>
                                    <p class="stepli_p3">Payment Schedule</p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <form class="form-horizontal">
                    <div class="row">   
                        <div class="form-group col-lg-12">
                            <select name="named[]" id="unit_type" class="form-control selectpicker show-tick" data-size="5" title="Select Other Cost..">
                                <option>Select Other Cost</option>
                                <option>1</option>
                                <option>2</option>
                                <option>3</option>
                                <option>4</option>
                            </select> 
                        </div>
                    </div> 
                    <div class="row">   
                        <div class="form-group col-lg-12">
                            <input type="text" class="form-control lbl_move" label="Land Registration Value in %">  
                        </div>
                    </div>
                    <div class="row">   
                        <div class="form-group col-lg-12">
                            <input type="text" class="form-control lbl_move" label="Construction Registration Value in %">  
                        </div>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-lg-12 savebtn_area">
    <ul>
        <li class="dropdown save_btn float_r">
            <a href="payment-schedule" class="ripple">Save</a>
            <div class="save_trigger">
                <a href="javascript:void(0);" class="ripple" data-toggle="dropdown">
                    <i class="fa fa-angle-down"></i>
                </a>
                <ul class="ang_down_ul save_down_ul dropdown-menu dropdown-menu-right">
                    <li><a href="javascript:void(0);">Save &amp; Next</a></li>
                    <li><a href="javascript:void(0);">Save &amp; Exit</a></li>
                </ul>
            </div>
        </li>
        <li class="cancel_btn float_r"><a href="javascript:void(0);" class="ripple">back</a></li>
        <li class="goto">
            <label for="go_to" class="float_l">Go to</label> 
            <select id="go_to" name="go_to" class="float_l goto_select" title="Choose Page to go....">
                <option>General</option>
                <option>Land Area Details</option>
                <option>Land Cost Calculation</option>
                <option>Car Park</option>
                <option>General</option>
                <option>Land Area Details</option>
                <option>Land Cost Calculation</option>
                <option>Car Park</option>
            </select>  
        </li>
    </ul>
</div>