<script type="text/javascript">
$(document).ready(function () {           
	$(".jqxtable").jqxDataTable(
	{
		width:"100%",
		altRows: true,
		sortable: true,
		editable: true,
		selectionMode: 'singleRow',
		columns: [
		  { text: 'Description', dataField: 'Description'},
		  { text: 'Date', dataField: 'Date'},
		  { text: 'Round Off', dataField: 'Round Off',width:'11%'},
		  { text: 'Schedule %', dataField: 'Schedule %',width:'11%'}
		]
	});
});
</script>
<div class="content_wrapper padlr0">
    <div class="container-fluid">
        <div class="col-lg-12">
            <h1>Project Info of 
                <div class="btn-group proname_btn">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">Prince Block 1 <span class="edit_symbols" data-placement="right" data-toggle="tooltip" data-original-title="Change&nbsp;project&nbsp;name"><i class="fa fa-caret-down "></i></span></a> 							
                    <div class="dropdown-menu toolbar_ddown proname_ddown arrow" role="menu">
                        <ul>
                           <li><a href="#">Mayflower Mayflower</a></li>
                           <li><a href="#">AkashManor</a></li>
                           <li><a href="#">Isha</a></li>
                           <li><a href="#">RMZ Millenia</a></li>
                           <li><a href="#">APS Avenue</a></li>
                           <li><a href="#">Aura One</a></li>
                           <li><a href="#">HO - Micromen Properties Ltd</a></li>
                           <li><a href="#">HO - Isha Homes PVT LTD</a></li>
                           <li><a href="#">BO - APS - Chennai</a></li>
                           <li><a href="#">ArunBuilders</a></li>
                           <li><a href="#">Aura One</a></li>
                           <li><a href="#">HO - Prince Foundation Ltd</a></li>
                           <li><a href="#">Prince Block 1</a></li>
                           <li><a href="#">Prince Block 2</a></li>
                        </ul>
                    </div>
                </div>
            </h1>
        </div> 
        <div class="col-lg-12 clear">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">
                    <div class="col-lg-12">
                        <div class="row">
                            <div class="step_by_liner animated slideInDown"></div>
                            <ul class="step_by stepby_mb60">
                                <li>
                                    <div class="step_by_sep animated_0_4s slideInRight"><p>1</p></div>
                                    <p class="stepli_p1">Other Cost Details</p>
                                </li>
                                <li>
                                    <div class="step_by_sep stepsep_active animated slideInRight"><p>2</p></div>
                                    <p class="stepli_p2">Payment Schedule</p>
                                </li>
                                <li class="opacity_08">
                                    <div class="step_by_sep animated_1_5s slideInRight"><p>3</p></div>
                                    <p class="stepli_p3">Unit type generation</p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 cnt_slider">	
                    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                        <!-- Wrapper for slides -->
                        <div class="carousel-inner" role="listbox">
                            <div class="item active">
                                <ul class="onbrd_rdo_box">
                                    <li>
                                        <a href="#carousel-example-generic" role="button" data-slide="next">
                                            <div class="rdo_box_icon brad_50">
                                                <img src="<?php echo $this->basePath(); ?>/images/rdo_box_icon1.png" class="m_auto"/>
                                            </div>
                                            <h2>Do you want to create a New Schedule ?</h2>
                                            <div class="rdo_box_link brad_50"><span><i class="fa fa-external-link"></i></span></div>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="payment_schedule_exist.php">
                                            <div class="rdo_box_icon brad_50">
                                                <img src="<?php echo $this->basePath(); ?>/images/rdo_box_icon2.png" class="m_auto"/>
                                            </div>
                                            <h2>Do you want to view Existing Schedule ?</h2>
                                            <div class="rdo_box_link brad_50"><span><i class="fa fa-external-link"></i></span></div>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <div class="item min_h550">
                                <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                                <form class="form-horizontal">
                                    <div class="row">   
                                        <div class="form-group col-lg-12">
                                            <input type="text" class="form-control lbl_move" label="Payment Schedule">  
                                        </div>
                                    </div>
                                    <div class="row">   
                                        <div class="form-group col-lg-12">
                                            <select name="named[]" id="unit_type" class="form-control selectpicker show-tick" data-size="5" title="Select Unit type..">
                                                <option>Select Unit type</option>
                                                <option>1</option>
                                                <option>2</option>
                                                <option>3</option>
                                                <option>4</option>
                                            </select> 
                                        </div>
                                    </div> 
                                    <div class="row">   
                                        <div class="form-group col-lg-12">
                                            <select name="named[]" id="block_name" class="form-control selectpicker show-tick" data-size="5" title="Select Block Name..">
                                                <option>Select Block Name</option>
                                                <option>1</option>
                                                <option>2</option>
                                                <option>3</option>
                                                <option>4</option>
                                            </select> 
                                        </div>
                                    </div> 
                                    <div class="row">   
                                        <div class="form-group col-lg-12">
                                            <select name="named[]" id="schedule_type" class="form-control selectpicker show-tick" data-size="5" title="Select Schedule Type..">
                                                <option>Select Schedule Type</option>
                                                <option>1</option>
                                                <option>2</option>
                                                <option>3</option>
                                                <option>4</option>
                                            </select> 
                                        </div>
                                    </div> 
                                    <div class="row">   
                                        <div class="form-group col-lg-12">
                                            <select name="named[]" id="emi_type" class="form-control selectpicker show-tick" data-size="5" title="Select EMI Type..">
                                                <option>Select EMI Type</option>
                                                <option>1</option>
                                                <option>2</option>
                                                <option>3</option>
                                                <option>4</option>
                                            </select> 
                                        </div>
                                    </div> 
                                    <div class="row">
                                        <div class="col-lg-6 col-md-6"> 
                                            <div class="form-group col-lg-12">
                                                <span class="date_icon"><i class="fa fa-calendar"></i></span>
                                                <input type="text" name="lead_date" id="start_date" class="form-control date_picker lbl_move" label="Start Date" />
                                            </div>
                                         </div>
                                         <div class="col-lg-6 col-md-6"> 
                                            <div class="form-group col-lg-12">
                                                <span class="date_icon"><i class="fa fa-calendar"></i></span>
                                                <input type="text" name="lead_date" id="end_date" class="form-control date_picker lbl_move" label="End Date" />
                                            </div>
                                        </div>          
                                   </div> 
                                </form>
                                 </div>
                            </div>
                            <div class="item">
                                <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                                <form class="form-horizontal">
                                    <div class="row">   
                                        <div class="form-group col-lg-12">
                                            <select name="named[]" id="stages" class="form-control selectpicker show-tick" data-size="5" title="Select Stages..">
                                                <option>Select Stages</option>
                                                <option>1</option>
                                                <option>2</option>
                                                <option>3</option>
                                                <option>4</option>
                                            </select> 
                                        </div>
                                    </div> 
                                    <div class="row">   
                                        <div class="form-group col-lg-12">
                                            <select name="named[]" id="receipt" class="form-control selectpicker show-tick" data-size="5" title="Select Receipt..">
                                                <option>Select Receipt</option>
                                                <option>1</option>
                                                <option>2</option>
                                                <option>3</option>
                                                <option>4</option>
                                            </select> 
                                        </div>
                                    </div> 
                                    <div class="row">   
                                        <div class="form-group col-lg-12">
                                            <select name="named[]" id="month_quater_yearly" class="form-control selectpicker show-tick" data-size="5" title="Select Month/Quater/Yearly..">
                                                <option>Select Month/Quater/Yearly</option>
                                                <option>1</option>
                                                <option>2</option>
                                                <option>3</option>
                                                <option>4</option>
                                            </select> 
                                        </div>
                                    </div> 
                                </form>
                                 </div>
                            </div>
                            <div class="item">
                                <div class="col-lg-12">
                                    <div class="table-responsive clear">
                                        <table class="table table-hover clear jqxtable" id="table">
                                            <thead>
                                                <tr>
                                                    <th>Description</th>
                                                    <th>Date</th>
                                                    <th>Round Off</th>
                                                    <th>Schedule %</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>Booking</td>
                                                    <td>12/12/15</td>
                                                    <td>0.00</td>
                                                    <td>10%</td>
                                                </tr>
                                                <tr>
                                                    <td>Booking</td>
                                                    <td>12/12/15</td>
                                                    <td>0.00</td>
                                                    <td>10%</td>
                                                </tr>
                                                <tr>
                                                    <td>Booking</td>
                                                    <td>12/12/15</td>
                                                    <td>0.00</td>
                                                    <td>10%</td>
                                                </tr>
                                                <tr>
                                                    <td>Booking</td>
                                                    <td>12/12/15</td>
                                                    <td>0.00</td>
                                                    <td>10%</td>
                                                </tr><tr>
                                                    <td>Booking</td>
                                                    <td>12/12/15</td>
                                                    <td>0.00</td>
                                                    <td>10%</td>
                                                </tr>
                                                <tr>
                                                    <td>Booking</td>
                                                    <td>12/12/15</td>
                                                    <td>0.00</td>
                                                    <td>10%</td>
                                                </tr>
                                                <tr>
                                                    <td>Booking</td>
                                                    <td>12/12/15</td>
                                                    <td>0.00</td>
                                                    <td>10%</td>
                                                </tr>
                                                <tr>
                                                    <td>Booking</td>
                                                    <td>12/12/15</td>
                                                    <td>0.00</td>
                                                    <td>10%</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                    <a class="onbrd_addnew" href="unittype-generation">Addnew</a>
                                 </div>
                            </div>
                            <!-- Indicators -->
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="3"></li>
                            </ol>
                            <!-- Controls -->
                            <ul class="prev_next">
                                <li class="float_l">
                                    <a href="#carousel-example-generic" data-slide="prev">
                                        <span><i class="fa fa-arrow-left"></i></span>
                                    </a>
                                </li>
                                <li class="float_r">
                                    <a href="#carousel-example-generic" role="button" data-slide="next">
                                        <span><i class="fa fa-arrow-right"></i></span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>	
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-lg-12 savebtn_area">
    <ul>
        <li class="goto">
            <label for="go_to" class="float_l">Go to</label> 
            <select id="go_to" name="go_to" class="float_l goto_select" title="Choose Page to go....">
                <option>General</option>
                <option>Land Area Details</option>
                <option>Land Cost Calculation</option>
                <option>Car Park</option>
                <option>General</option>
                <option>Land Area Details</option>
                <option>Land Cost Calculation</option>
                <option>Car Park</option>
            </select>  
        </li>
    </ul>
</div>
<script type="text/javascript">
$('.cnt_slider .carousel').carousel({
 interval: false
})
</script>