<style>
    .invoice-box{
        max-width:800px;
        margin:auto;
        padding:10px;
        border:1px solid #eee;
        box-shadow:0 0 10px rgba(0, 0, 0, .15);
        font-size:16px;
        line-height:24px;
        color:#555;
		background:#e2ebef;
    }
    
    .invoice-box table{
        width:100%;
        line-height:inherit;
        text-align:left;
		background:#fff !important;
		padding:10px;
    }
    
    .invoice-box table td{
        padding:5px;
        vertical-align:top;
    }
    
    .invoice-box table tr td:nth-child(2){
        text-align:right;
    }
    
    .invoice-box table tr.heading td{
        background:#eee;
        border-bottom:1px solid #ddd;
        font-weight:bold;
		font-size:14px;
    }
    .invoice-box table tr.item td{
        border-bottom:1px solid #eee;
		font-size:14px;
    }
    
    .invoice-box table tr.item.last td{
        border-bottom:none;
    }
    
    .invoice-box table tr.total td:nth-child(2){
        border-top:2px solid #eee;
        font-weight:bold;
    }
</style>
<div class="content_wrapper padlr0">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 clear">
            	 <div class="invoice-box">
                    <table cellpadding="0" cellspacing="0">
                        <tr class="mainheading">
                            <td colspan="2" class="" style="color:#244996; font-size:25px; font-weight:500; text-align:center; padding:10px 0px 22px 0px;">Finalisation</td>
                        </tr>
                        <tr class="heading">
                            <td >
                                <div><span>Booking No : </span> &nbsp; <span> 56f0d6086d150 </span></div>
                            </td>
                            
                            <td>
                                 <div><span> Booking Date : </span> &nbsp; <span> 31-03-2016 </span></div>
                            </td>
                        </tr>
                        <tr class="item">
                            <td>
                                Project Name
                            </td>
                            
                            <td>
                                Test
                            </td>
                        </tr>
                        <tr class="item">
                            <td>
                                Unit No
                            </td>
                            
                            <td>
                                0013P2 Block1P2 Block1 Floor1unit type 2
                            </td>
                        </tr>
                        <tr class="heading">
                            <td colspan="2">
                                Unit Detail
                            </td>
                        </tr>
                        
                        <tr class="item">
                            <td>
                                Block Name
                            </td>
                            
                            <td>
                                Harish P2 Block1
                            </td>
                        </tr>
                        
                        <tr class="item">
                            <td>
                                Level
                            </td>
                            
                            <td>
                                 P2 Block1 Floor1
                            </td>
                        </tr>
                        
                        <tr class="item">
                            <td>
                                Area
                            </td>
                            
                            <td>
                                4000.000
                            </td>
                        </tr>
                        <tr class="item">
                            <td>
                                Rate
                            </td>
                            
                            <td>
                                4000.000
                            </td>
                        </tr>
                        <tr class="item">
                            <td>
                                Base Amount
                            </td>
                            
                            <td>
                                166500.000
                            </td>
                        </tr>
                        <tr class="item">
                            <td>
                                Land Amount
                            </td>
                            
                            <td>
                                345.0000
                            </td>
                        </tr>
                        <tr class="item">
                            <td>
                                Construction Amount
                            </td>
                            
                            <td>
                                163500.000
                            </td>
                        </tr>
                        <tr class="item">
                            <td>
                                Gross Amount
                            </td>
                            
                            <td>
                                163835.000
                            </td>
                        </tr>
                        <tr class="item">
                            <td>
                                Qualifier Amount
                            </td>
                            
                            <td>
                                970.000
                            </td>
                        </tr>
                        <tr class="total">
                            <td colspan="2" style="color:#098833 !important; text-align:right;">
                               Net Amount : 163835.000
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>