<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/select2.full.min.js"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/select2.min.css" />
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/workorder.css"/>
<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
        <div class="col-lg-12">
            <h1>Progress Bill</h1>
        </div> 
        <div class="col-lg-12 flwup_topcnt fmg_topcnt clear">
        	<div class="col-lg-4 form-group">
            	<span class="date_icon"><i class="fa fa-calendar"></i></span>
                <input type="text" name="target_period" id="target_period" class="form-control date_picker lbl_move" value="period1"  label="Bill Date"/>
            </div>
            <div class="col-lg-4 form-group">
                <select class="form-control multiple_dropdown lbl_move"  name="project" id="project" multiple="multiple" label="Project" style="width:100%;">
                    <option value="">project test1</option>
                    <option value="">project test2</option>
                    <option value="">project test3</option>
                    <option value="">project test1</option>
                    <option value="">project test2</option>
                    <option value="">project test3</option>
                    <option value="">project test1</option>
                    <option value="">project test2</option>
                    <option value="">project test3</option>
                    <option value="">project test1</option>
                    <option value="">project test2</option>
                    <option value="">project test3</option>
                </select>
            </div>
            <div class="col-lg-4 form-group">
                <select class="form-control single_dropdown lbl_move" label="Block Name..." style="width:100%;">
                    <option></option>
                    <option>Block A</option>
                    <option>Formula-based Manufacturers</option>
                    <option>Practical ERP </option>
                    <option>Evolving ERP Strategy</option>
                    <option>Maximum usability</option>
                    <option>Practical Guide454</option>
                    <option>Formulas4545</option>
                    <option>Prac ERP4545 </option>
                    <option>Evoltegytrt445</option>
                    <option>Mait45454y</option>
                </select>
            </div>
            <div class="col-lg-4 form-group clear">
                <select class="form-control single_dropdown lbl_move" label="Level Name..." style="width:100%;">
                    <option></option>
                    <option>Ground Floor</option>
                    <option>Floor1</option>
                    <option>Floor2</option>
                    <option>Floor3</option>
                    <option>Floor4</option>
                </select>
            </div>
            <div class="col-lg-4 form-group">
                <select class="form-control single_dropdown lbl_move" label="Stage Type..." style="width:100%;">
                    <option></option>
                    <option>Practical Guide</option>
                    <option>Formula-based Manufacturers</option>
                    <option>Practical ERP </option>
                    <option>Evolving ERP Strategy</option>
                    <option>Maximum usability</option>
                    <option>Practical Guide454</option>
                    <option>Formulas4545</option>
                    <option>Prac ERP4545 </option>
                    <option>Evoltegytrt445</option>
                    <option>Mait45454y</option>
                </select>
            </div> 
            <div class="col-lg-4 form-group">
                <select class="form-control single_dropdown lbl_move" label="Stage Name..." style="width:100%;">
                    <option></option>
                    <option>Block A</option>
                    <option>Formula-based Manufacturers</option>
                    <option>Practical ERP </option>
                    <option>Evolving ERP Strategy</option>
                    <option>Maximum usability</option>
                    <option>Practical Guide454</option>
                    <option>Formulas4545</option>
                    <option>Prac ERP4545 </option>
                    <option>Evoltegytrt445</option>
                    <option>Mait45454y</option>
                </select>
            </div>
        </div>
        <div class="col-lg-12 clear">
        	<div class="table-responsive animated fadeInUp">
                <table class="table tbltop_bdr0">
                    <thead>
                        <tr>
                            <th>Unit No</th>
                            <th>Description</th>
                            <th>Buyer</th>
                            <th>Amount</th>
                            <th>Net Amount</th>
                            <th>&nbsp; </th>
                    	</tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td width="3%"><b class="ra-t">A001</b></td>
                            <td width="10%"><p class="dec-ptr">On completion of First Floor</p></td>
                            <td width="10%"><input class="tbl_input" type="text" value="Balaji" /></td>
                            <td width="10%"><input class="tbl_input" type="text" value="399000.00" /></td>
                            <td width="10%"><input class="tbl_input" type="text" value="300000.00" /></td>
                        	<td width="3%" align="center" class="action_btns_td">
                        		<ul class="action_btns">
                                    <li>
                                    	<a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i></a>
                                    </li>
                                    <li>
                                    	<a href="#" class="mainTr"><i class="fa fa-chevron-circle-down" data-toggle="tooltip" data-placement="top" data-original-title="Expand"></i></a>
                                    </li>
                        		</ul>
                        	</td>
                        </tr>
                    	<!--Add lines table-->
                    	<tr style="display:none;" class="subTr">
                    		<td colspan="9" style="padding:0px !important; ">
                            <div class="subDiv" style="display:none;">
                    			<div class="col-lg-12 col-lg-offset-0 rdbt" style="margin-top:5px;"></div>
                                <div class="col-lg-12">
                                    <div class="table-responsive topsp">
                                        <table class="table" style="margin-bottom:0px;">
                                            <thead>
                                                <tr>
                                                    <th>&nbsp;</th>
                                                    <th>Receipt Type</th>
                                                    <th>Percentage</th>
                                                    <th>Amount</th>
                                                    <th>Net Amount</th>
                                                    <th>&nbsp;</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td width="3%"><label class="ripple"><input class="ios_checkbox" checked type="checkbox"/><div class="ios_switch"><span></span></div></label></td>
                                                    <td width="17%"><p class="dec-ptr">Land Value</p></td>
                                                    <td width="7%"><input class="tbl_input" type="text" value="100%"/></td>
                                                    <td width="7%"><input class="tbl_input" type="text" value="399000.00" /></td>
                                                    <td width="8%"><input class="tbl_input" type="text" value="399000.00" /></td>
                                                    <td width="3%" align="center" class="action_btns_td">
                                                        <ul class="action_btns">
                                                            <li><a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i> </a> </li>
                                                        </ul>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td width="3%"><label class="ripple"><input class="ios_checkbox" checked type="checkbox"/><div class="ios_switch"><span></span></div></label></td>
                                                    <td width="17%"><p class="dec-ptr">Construction Value</p></td>
                                                    <td width="7%"><input class="tbl_input" type="text" value="0%"/></td>
                                                    <td width="7%"><input class="tbl_input" type="text" value="0.00" /></td>
                                                    <td width="8%"><input class="tbl_input" type="text" value="00.00" /></td>
                                                    <td width="3%" align="center" class="action_btns_td">
                                                        <ul class="action_btns">
                                                            <li><a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i> </a> </li>
                                                        </ul>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td colspan="3"></td>
                                                    <td align="right" class="rate_pri">Total</td>
                                                    <td width="5%"><input class="tbl_input" type="text" value="350000.00" /></td>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <td colspan="3"></td>
                                                    <td align="right" class="rate_pri">Service Tax 14%</td>
                                                    <td width="5%"><input class="tbl_input" type="text" value="49000.00"/></td>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <td colspan="3"></td>
                                                    <td align="right" class="rate_pri">Grand Total</td>
                                                    <td width="5%"><input class="tbl_input" type="text" value="399000.00" /></td>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <td colspan="3"></td>
                                                    <td align="right" class="rate_pri">Receipt Adjectment (Advance)</td>
                                                    <td width="5%"><input class="tbl_input" type="text" value="99000.00" /></td>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <td colspan="3"></td>
                                                    <td align="right" class="rate_pri">Balance</td>
                                                    <td width="5%"><input class="tbl_input" type="text" value="300000.00" /></td>
                                                    <td>&nbsp;</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
							</div>
							</td>
						</tr>
                        <tr>
                            <td width="3%"><b class="ra-t">A001</b></td>
                            <td width="10%"><p class="dec-ptr">On completion of First Floor</p></td>
                            <td width="10%"><input class="tbl_input" type="text" value="Balaji" /></td>
                            <td width="10%"><input class="tbl_input" type="text" value="399000.00" /></td>
                            <td width="10%"><input class="tbl_input" type="text" value="300000.00" /></td>
                        	<td width="3%" align="center" class="action_btns_td">
                        		<ul class="action_btns">
                                    <li>
                                    	<a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i></a>
                                    </li>
                                    <li>
                                    	<a href="#" class="mainTr"><i class="fa fa-chevron-circle-down" data-toggle="tooltip" data-placement="top" data-original-title="Expand"></i></a>
                                    </li>
                        		</ul>
                        	</td>
                        </tr>
                    	<!--Add lines table-->
                    	<tr style="display:none;" class="subTr">
                    		<td colspan="9" style="padding:0px !important; ">
                            <div class="subDiv" style="display:none;">
                    			<div class="col-lg-12 col-lg-offset-0 rdbt" style="margin-top:5px;"></div>
                                <div class="col-lg-12">
                                    <div class="table-responsive topsp">
                                        <table class="table" style="margin-bottom:0px;">
                                            <thead>
                                                <tr>
                                                    <th>&nbsp;</th>
                                                    <th>Receipt Type</th>
                                                    <th>Percentage</th>
                                                    <th>Amount</th>
                                                    <th>Net Amount</th>
                                                    <th>&nbsp;</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td width="3%"><label class="ripple"><input class="ios_checkbox" checked type="checkbox"/><div class="ios_switch"><span></span></div></label></td>
                                                    <td width="17%"><p class="dec-ptr">Land Value</p></td>
                                                    <td width="7%"><input class="tbl_input" type="text" value="100%"/></td>
                                                    <td width="7%"><input class="tbl_input" type="text" value="399000.00" /></td>
                                                    <td width="8%"><input class="tbl_input" type="text" value="399000.00" /></td>
                                                    <td width="3%" align="center" class="action_btns_td">
                                                        <ul class="action_btns">
                                                            <li><a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i> </a> </li>
                                                        </ul>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td width="3%"><label class="ripple"><input class="ios_checkbox" checked type="checkbox"/><div class="ios_switch"><span></span></div></label></td>
                                                    <td width="17%"><p class="dec-ptr">Construction Value</p></td>
                                                    <td width="7%"><input class="tbl_input" type="text" value="0%"/></td>
                                                    <td width="7%"><input class="tbl_input" type="text" value="0.00" /></td>
                                                    <td width="8%"><input class="tbl_input" type="text" value="00.00" /></td>
                                                    <td width="3%" align="center" class="action_btns_td">
                                                        <ul class="action_btns">
                                                            <li><a href="#"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i> </a> </li>
                                                        </ul>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td colspan="3"></td>
                                                    <td align="right" class="rate_pri">Total</td>
                                                    <td width="5%"><input class="tbl_input" type="text" value="350000.00" /></td>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <td colspan="3"></td>
                                                    <td align="right" class="rate_pri">Service Tax 14%</td>
                                                    <td width="5%"><input class="tbl_input" type="text" value="49000.00"/></td>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <td colspan="3"></td>
                                                    <td align="right" class="rate_pri">Grand Total</td>
                                                    <td width="5%"><input class="tbl_input" type="text" value="399000.00" /></td>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <td colspan="3"></td>
                                                    <td align="right" class="rate_pri">Receipt Adjectment (Advance)</td>
                                                    <td width="5%"><input class="tbl_input" type="text" value="99000.00" /></td>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <td colspan="3"></td>
                                                    <td align="right" class="rate_pri">Balance</td>
                                                    <td width="5%"><input class="tbl_input" type="text" value="300000.00" /></td>
                                                    <td>&nbsp;</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
							</div>
							</td>
						</tr>
					<!--Add lines end-->
					</tbody>
                    <!--<tbody>
                        <tr>
                            <td>&nbsp;</td>
                            <td width="10%" align="right" class="nt-am"><b>Net Amount</b></td>
                            <td width="10%" ><input class="tbl_input" type="text"/></td>
                            <td width="10%"><input class="tbl_input" type="text" /></td>
                            <td width="10%"><input class="tbl_input" type="text" /></td>
                            <td>&nbsp;</td>
                        </tr>
                    </tbody>-->
				</table>
            </div>
            <div class="form-group col-lg-12">
                <p class="col-lg-6 radio_label txt_right" style="padding-top:7px;"><label for="uds">Do you want to send demand letter on approval</label>
                    
                </p>
                <div class="radio_check col-lg-4">
                    <p>
                        <input type="radio" checked="checked" value="yes" id="yes" name="approval">
                        <label for="yes" class="ripple">Yes</label>
                    </p>
                    <p>
                        <input type="radio" value="no" id="no" name="approval">
                        <label for="no" class="ripple">No</label>
                    </p>
                </div>
            </div>
        </div>
	</div>
</div>
<!--button-->
<div class="col-lg-12 savebtn_area clear">
    <ul>
        <li class="dropdown save_btn float_r">
            <a href="javascript:void(0);" class="ripple">Generate Bill</a>
        </li>
    </ul>
</div>
<script>
$(document).ready(function() {
	$(".multiple_dropdown").select2({
	});
});
</script>
<script>
$(document).ready(function() {
	$(".single_dropdown").select2({
		placeholder: "",
		allowClear: true
	});
});
</script>
<!--table Add lines start--> 
<script>
$(".mainTr").click(function(e){
	e.preventDefault();
	if(!$(this).closest("tr").next(".subTr").is(":visible")){
		$(this).closest("tr").next(".subTr").show();
		$(this).closest("tr").next(".subTr").find(".subDiv").slideDown("slow");	
		$(this).find("i").addClass("tform");
	}
		else{
		$(this).closest("tr").next(".subTr").find(".subDiv").slideUp("slow");
		$(this).closest("tr").next(".subTr").slideUp("slow");
		$(this).find("i").removeClass("tform");
	}
})
</script>