<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/cb.css" />
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/select2.full.min.js"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/select2.min.css" />
<script>
	$(document).ready(function() {
		$(".single_dropdown").select2({
			placeholder: "",
			allowClear: true,
		});
	});
</script>
<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
        <div class="col-lg-12">
            <h1 class="txt_center">Property Management</h1>
        </div>
        <div class="col-lg-12 clear padlr0">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                <div class="col-lg-offset-3">
                    <label for="refno" class="bk_lbl bk_lbl_inpt">Ref No <span class="colon_r">:</span></label>
                    <input type="text" class="bk_lbl_inpt inputbg_ef bk_inpt1" name="refno" id="refno" value="" /> 
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 col-lg-pull-1 col-md-pull-1 col-sm-pull-1">
                <div class="col-lg-offset-6">
                    <label for="refdate" class="bk_lbl bk_lbl_inpt"><span class="bkspan_calendar"><i class="fa fa-calendar-o"></i></span> Ref Date <span class="colon_r">:</span></label>
                    <input type="text" class="date_picker bk_lbl_inpt bk_inpt inputbg_ef" name="refdate" id="refdate" value="" />
                </div>
            </div>
        </div>
        <div class="col-lg-12 clear">
        	<div class="liner"></div>
        </div>
        <div class="col-lg-12 clear" style="background-color:#fff;">
        	<div class="col-lg-6 padlr0 m_top10">
                <div class="signup_onebyone_content">
                    <div class="setup_form prop_mnmt_form">
                        <div class="flwup_rightcnt"><h2>Unit Details</h2></div>
                        <form method="post" >
                            <ul class="onebyone_form">										
                                <li id="q1" class="active focus">
                                    <div class="onebyone_wrapper">
                                        <div class="li_number">
                                            <span><i class="fa fa-flag-checkered" aria-hidden="true"></i></span>
                                            <div class="arrow">
                                                <span><i class="fa fa-arrow-right"></i></span>
                                            </div>
                                        </div>
                                        <div class="onebyone_question">
                                            <span class="span_b">What is the Project/Unit/Owner?</span>
                                        </div>
                                        <div class="onebyone_content">
                                            <div class="input">
                                                <input type="text" id="projectname" name="projectname" value="" placeholder="Project/ Unit/ Buyer"  class="inputSetup" autocomplete="off" />
                                            </div>
                                            <div class="col-lg-12 error_message"><p>Required</p></div>
                                        </div>
                                    </div>
                                </li>
                                <li id="q2" class="">
                                    <div class="onebyone_wrapper">
                                        <div class="li_number">
                                            <span><i class="fa fa-flag-checkered" aria-hidden="true"></i></span>
                                            <div class="arrow">
                                                <span><i class="fa fa-arrow-right"></i></span>
                                            </div>
                                        </div>
                                        <div class="onebyone_question">
                                            <span class="span_b">What is their Permanent Address?</span>
                                        </div>
                                        <div class="onebyone_content">
                                            <div class="input">
                                                <input type="text" id="address" name="address" autocomplete="off" placeholder="Address" value="" class="inputSetup"/>
                                            </div>
                                            <div class="col-lg-12 error_message"><p>Required</p></div>
                                        </div>
                                    </div>
                                </li>
                                <li id="q3" class="">
                                    <div class="onebyone_wrapper">
                                        <div class="li_number">
                                            <span><i class="fa fa-flag-checkered" aria-hidden="true"></i></span>
                                            <div class="arrow">
                                                <span><i class="fa fa-arrow-right"></i></span>
                                            </div>
                                        </div>
                                        <div class="onebyone_question">
                                            <span class="span_b">Has this Property is Ready for occupation?</span>
                                        </div>
                                        <div class="onebyone_content">
                                        	<div class="radio_check">
                                                <p>
                                                    <input type="radio" value="yes" id="yes" name="readyforoccupation" checked/>
                                                    <label for="yes" class="ripple">Yes</label>
                                                </p>
                                                <p>
                                                    <input type="radio" value="no" id="no" name="readyforoccupation" />
                                                    <label for="no" class="ripple">No</label>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li id="q4" class="">
                                    <div class="onebyone_wrapper">
                                        <div class="li_number">
                                            <span><i class="fa fa-flag-checkered" aria-hidden="true"></i></span>
                                            <div class="arrow">
                                                <span><i class="fa fa-arrow-right"></i></span>
                                            </div>
                                        </div>
                                        <div class="onebyone_question">
                                            <span class="span_b">When will Start under Maintenance Service?</span>
                                        </div>
                                        <div class="onebyone_content">
                                            <div class="input col-lg-12 padlr0">
                                            	<span class="date_icon"><i class="fa fa-calendar"></i></span>
                                                <input type="text" id="Date" name="Date" autocomplete="off" placeholder="dd/mm/yyyy" value="" class="inputSetup date_picker"/>
                                            </div>
                                            <div class="col-lg-12 error_message"><p>Required</p></div>
                                        </div>
                                    </div>
                                </li>
                                <li id="q5" class="">
                                    <div class="onebyone_wrapper">
                                        <div class="li_number">
                                            <span><i class="fa fa-flag-checkered" aria-hidden="true"></i></span>
                                            <div class="arrow">
                                                <span><i class="fa fa-arrow-right"></i></span>
                                            </div>
                                        </div>
                                        <div class="onebyone_question">
                                            <span class="span_b">What is the Furnishing details of the Property?</span>
                                        </div>
                                        <div class="onebyone_content">
                                        	<div class="radio_check">
                                                <p>
                                                    <input type="radio" value="fullyfurnishing" id="fullyfurnishing" name="Furnishing" checked/>
                                                    <label for="fullyfurnishing" class="ripple">Fully Furnishing</label>
                                                </p>
                                                <p>
                                                    <input type="radio" value="semifurnishing" id="semifurnishing" name="Furnishing" />
                                                    <label for="semifurnishing" class="ripple">Semi Furnishing</label>
                                                </p>
                                                <p>
                                                    <input type="radio" value="unfurnishing" id="unfurnishing" name="Furnishing" />
                                                    <label for="unfurnishing" class="ripple">Un Furnishing</label>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li id="q6" class="">
                                    <div class="onebyone_wrapper">
                                        <div class="li_number">
                                            <span><i class="fa fa-flag-checkered" aria-hidden="true"></i></span>
                                            <div class="arrow">
                                                <span><i class="fa fa-arrow-right"></i></span>
                                            </div>
                                        </div>
                                        <div class="onebyone_question">
                                            <span class="span_b">What are the Services Covered Under Maintenance Service?</span>
                                        </div>
                                        <div class="onebyone_content">
                                        	<div class="input">
                                            	<div class="col-lg-12 m_btm10 padlr0">
                                                    <div class="col-lg-6 col-md-6 col-sm-6 padlr0"><input type="text" class="inputSetup" name="" id="" value="services1" /></div>
                                                    <div class="col-lg-3 col-md-3 col-sm-3 padlr0"><input type="text" class="inputSetup" name="" id="" value="1 time" /></div>
                                                    <div class="col-lg-3 col-md-3 col-sm-3 padlr0">
                                                        <select style="width:100%;" class="single_dropdown">
                                                            <option>per day</option>
                                                            <option>per week</option>
                                                            <option>per month</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="col-lg-12 m_btm10 padlr0">
                                                    <div class="col-lg-6 col-md-6 col-sm-6 padlr0"><input type="text" class="inputSetup" name="" id="" value="services1" /></div>
                                                    <div class="col-lg-3 col-md-3 col-sm-3 padlr0"><input type="text" class="inputSetup" name="" id="" value="Amount" /></div>
                                                    <div class="col-lg-3 col-md-3 col-sm-3 padlr0">
                                                        <select style="width:100%;" class="single_dropdown">
                                                            <option>As required</option>
                                                            <option>As required1</option>
                                                            <option>As required2</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="col-lg-12 m_btm10 padlr0">
                                                    <div class="col-lg-8 col-md-8 col-sm-8 padlr0"><input type="text" class="inputSetup" name="" id="" value="services1" /></div>
                                                    <div class="col-lg-4 col-md-4 col-sm-4 padlr0">
                                                        <select style="width:100%;" class="single_dropdown">
                                                            <option>As per reading</option>
                                                            <option>As per reading</option>
                                                            <option>As per reading</option>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li id="q7" class="">
                                    <div class="onebyone_wrapper">
                                        <div class="li_number">
                                            <span><i class="fa fa-flag-checkered" aria-hidden="true"></i></span>
                                            <div class="arrow">
                                                <span><i class="fa fa-arrow-right"></i></span>
                                            </div>
                                        </div>
                                        <div class="onebyone_question">
                                            <span class="span_b">What are the Documents submitted?</span>
                                        </div>
                                        <div class="onebyone_content">
                                        	<div class="input">
                                            	<div class="col-lg-12 m_btm10 padlr0">
                                                    <div class="col-lg-8 col-md-8 col-sm-8 padlr0"><input type="text" class="inputSetup" name="" id="" value="Documents1" /></div>
                                                    <div class="col-lg-4 col-md-4 col-sm-4 padlr0">
                                                    <ul class="action_btns">
                                                        <li>
                                                        	<a href="#"><span data-original-title="Document Views" data-placement="left" data-toggle="tooltip"><i class="fa fa-eye"></i></span></a>
                                                        </li>
                                                        <li>
                                                        	<a href="#"><span class="btn-file butclr_imp" data-original-title="Documents Attached" data-placement="left" data-toggle="tooltip"><i class="fa fa-paperclip dcm_atch"></i><input type="file"></span></a>
                                                        </li>
                                                    </ul>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                            <div class="col-lg-12 savebtn_area m_btm20 no_border clear">
                                <ul>
                                	<!--<li class="save_btn float_l">
                                        <a class="ripple" href="javascript:void(0);"  data-toggle="tooltip" data-placement="right" title="back">Back</a>
                                    </li>-->
                                    <li class="save_btn float_r">
                                        <a class="ripple" href="javascript:void(0);"  data-toggle="tooltip" data-placement="left" title="to&nbsp;fill&nbsp;deposit&nbsp;and&nbsp;fees&nbsp;details">Continue</a>
                                    </li>
                                </ul>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="clear"></div>
        	</div>
            <div class="col-lg-6 m_top20">
            	<div class="form-group clear">
                    <div class="col-lg-12">
                        <form class="form-horizontal stginner_cnt">
                            <div class="row">   
                                <div class="col-lg-12 clear">
                                    <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label ">Project Name</label>
                                    <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                        <p>Test</p>   
                                    </div>
                                </div>
                            </div>
                            <div class="row">   
                                <div class="col-lg-12">
                                    <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Block No</label>
                                    <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                        <p>32</p>
                                    </div>
                                </div>
                            </div>
                            <div class="row">   
                                <div class="col-lg-12">
                                    <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Floor No</label>
                                    <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                        <p>43</p> 
                                    </div>
                                </div>
                            </div>
                            <div class="row">   
                                <div class="col-lg-12">
                                    <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Unit Type</label>
                                    <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                        <p>43</p> 
                                    </div>
                                </div>
                            </div>
                            <div class="row">   
                                <div class="col-lg-12">
                                    <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Unit No</label>
                                    <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                        <p>33</p>
                                    </div>
                                </div>
                            </div>
                            <div class="row">   
                                <div class="col-lg-12">
                                    <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Area</label>
                                    <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                        <p>1267</p> 
                                    </div>
                                </div>
                            </div>
                            <div class="row">   
                                <div class="col-lg-12">
                                    <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Area</label>
                                    <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                        <p>10,000.00</p> 
                                    </div>
                                </div>
                            </div>
                            <div class="row">   
                                <div class="col-lg-12">
                                    <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Face</label>
                                    <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                        <p>South</p> 
                                    </div>
                                </div>
                            </div>
                            <div class="row">   
                                <div class="col-lg-12">
                                    <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Owner Name</label>
                                    <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                        <p>Harish Dhananjayan</p> 
                                    </div>
                                </div>
                            </div>
                            <div class="row">   
                                <div class="col-lg-12">
                                    <label class="col-lg-5 padlr0 col-md-5 col-sm-5 txt_left control-label">Address</label>
                                    <div class="col-lg-7 col-md-7 col-sm-7 padlr0">
                                        <p>1355 Market Street, Suite 900 San Francisco, CA 94103</p> 
                                    </div>
                                </div>
                            </div>
                        </form>  
                    </div>
                </div>
            </div>
        </div>
        
    </div>
</div>
<script>
$("li").hover(
	function () {
		$(this).addClass("active focus").parent().next().addClass("active focus");
	},
	function () {
		$(this).removeClass("active focus").parent().next().removeClass("active focus");
	}
);

$(".inputSetup").focus(function(){
	$('.focus').removeClass('active focus');
	$(this).closest('li').addClass('active focus');
	scrollPoint = $(this).closest('li').offset().top - 150;
	$('body,html').animate({
		scrollTop: scrollPoint
	}, 600);
});
</script>