<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/css/project.css" />
<style>
.rdochck_subscrbcrm p > input[type="checkbox"] + label {
    background-position: 0 -80px !important;
}
.rdochck_subscrbcrm p > input[type="checkbox"]:checked + label {
    background-position: 0 -260px !important;
}
</style>
<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
        <div class="col-lg-12">
            <h1 class="vendorrequest_textnormal">Qualifier</h1>
            <div class="col-lg-12 commargin_top_20">
            	<div class="col-lg-12">
                    <div class="form-horizontal stginner_cnt">
                        <div class=" ">
                            <div class="table-responsive topsp">
                                <table class="table table-hover m_btm0">
                                    <tbody>
                                        <tr>
                                            <td colspan="2" class="nedchnginsubmital" style=" border-bottom:none !important; border-top:none !important; font-weight:500 !important; color: #104e73 !important;">Reference : R1</td>
                                            <td colspan="2" style=" border-bottom:none !important; border-top:none !important;background:#e6f9ff !important; ">Description : Sales Tax</td>
                                            <td style=" border-bottom:none !important; border-top:none !important;background:#e6f9ff !important; color:#3580c4;">Amount</td>
                                        </tr>
                                        <tr>
                                            <td style="padding: 8px 0px 8px 9px ! important;">
                                                <div class="rdochck_subscrbcrm radio_check mainTr">
                                                    <p style="padding:0px !important;">
                                                        <input type="checkbox" value="" id="EarthWork" />
                                                        <label for="EarthWork" class="ripple" style="padding-left: 25px !important;"></label>
                                                    </p>
                                                </div>
                                            </td>
                                            <td class="tbl_input_td" style="padding:4px 4px 3px !important;"><input type="text" class="tbl_input" name="quantity" value=""/></td>
                                            <td class="tbl_input_td" style="padding:4px 4px 3px !important;"><input type="text" class="tbl_input" name="quantity" value=""/></td>
                                            <td class="tbl_input_td" style="padding:4px 4px 3px !important;"><input type="text" class="tbl_input" name="quantity" value=""/></td>
                                            <td style="padding:8px !important;">36,000.00</td>
                                        </tr>
                                        <!--expand table-->
                                        <tr style="display:none;" class="subTr">
                                            <td colspan="5" class="pad0" style="background: #fff!important;">
                                                <div class="subDiv" style="display:none;">
                                                    <div class="col-lg-12">
                                                        <div class="table-responsive topsp">
                                                            <table class="table m_btm0">
                                                                <thead>
                                                                    <tr>
                                                                        <th width="17%">Section Name</th>
                                                                        <th width="10%">percentage</th>
                                                                        <th width="10%">Amount</th>
                                                                    </tr>
                                                                </thead>
                                                                <tbody>
                                                                    <tr>
                                                                        <td>Taxable</td>
                                                                        <td><input type="text" class="parent_text" name="" value=""></td>
                                                                        <td><input type="text" class="parent_text" name="" value=""></td>
                                                                    </tr>
                                                                     <tr>
                                                                        <td>Gross</td>
                                                                        <td><input type="text" class="parent_text" name="" value=""></td>
                                                                        <td><input type="text" class="parent_text" name="" value=""></td>
                                                                    </tr>
                                                                     <tr>
                                                                        <td>Surcharge</td>
                                                                        <td><input type="text" class="parent_text" name="" value=""></td>
                                                                        <td><input type="text" class="parent_text" name="" value=""></td>
                                                                    </tr>
                                                                     <tr>
                                                                        <td>Education Cess</td>
                                                                        <td><input type="text" class="parent_text" name="" value=""></td>
                                                                        <td><input type="text" class="parent_text" name="" value=""></td>
                                                                    </tr>
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                        <!--expand end-->
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>    
<script>
$(".mainTr").click(function(e){
	e.preventDefault();
	if(!$(this).closest("tr").next(".subTr").is(":visible")){
		$(this).closest("tr").next(".subTr").show();
		$(this).closest("tr").next(".subTr").find(".subDiv").slideDown("slow");	
		$(this).find("i").addClass("tform");
	}
		else{
		$(this).closest("tr").next(".subTr").find(".subDiv").slideUp("slow");
		$(this).closest("tr").next(".subTr").slideUp("slow");
		$(this).find("i").removeClass("tform");
	}
})

</script>