<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/select2.full.min.js"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/select2.min.css" />
<div class="content_wrapper padlr0">
    <div class="container-fluid">
    	<div class="row">
            <div class="col-lg-12">
                <h1 class="m_btm30">Stage Completion</h1> 
            </div> 
            <div class="col-lg-12 clear">
                <div class="form-group">
                    <div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                        <form class="form-horizontal">
                        <div class="row">   
                            <div class="form-group col-lg-12">
                            	<div class="form-group col-lg-12">
                                	<span class="date_icon"><i class="fa fa-calendar"></i></span>
                                	<input type="text" class="form-control date_picker lbl_move" label="Completion Date"> 
                                </div>
                                <!---------------multiple text tag---------------->
                                <div class="form-group col-lg-12">
                                    <select class="form-control single_dropdown lbl_move" label="Stage Type..." style="width:100%;">
                                    	<option></option>
                                        <option>Practical Guide</option>
                                        <option>Formula-based Manufacturers</option>
                                        <option>Practical ERP </option>
                                        <option>Evolving ERP Strategy</option>
                                        <option>Maximum usability</option>
                                        <option>Practical Guide454</option>
                                        <option>Formulas4545</option>
                                        <option>Prac ERP4545 </option>
                                        <option>Evoltegytrt445</option>
                                        <option>Mait45454y</option>
                                    </select>
                                </div>
                                <div class="form-group col-lg-12" >
                                    <select class="form-control single_dropdown lbl_move" label="Stage Name..." style="width:100%;">
                                    	<option></option>
                                        <option>Block A</option>
                                        <option>Formula-based Manufacturers</option>
                                        <option>Practical ERP </option>
                                        <option>Evolving ERP Strategy</option>
                                        <option>Maximum usability</option>
                                        <option>Practical Guide454</option>
                                        <option>Formulas4545</option>
                                        <option>Prac ERP4545 </option>
                                        <option>Evoltegytrt445</option>
                                        <option>Mait45454y</option>
                                    </select>
                                </div>
                                <div class="col-lg-12">
                                	<span class="date_icon"><i class="fa fa-calendar"></i></span>
                                	<input type="text" class="form-control date_picker lbl_move" label="Due Date">
                                </div>
                                <div class="col-lg-12">
                                	<div class="radio_check">
                                        <p>
                                           <input type="checkbox" checked="" id="auto_generate" value="">
                                           <label class="ripple" for="auto_generate">Auto Generate Progress bill</label>
                                       </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        </form>
                        <div class="col-lg-12 savebtn_area m_btm30 m_auto no_border">
                            <ul>
                                <li class="save_btn m_auto">
                                    <a href="javascript:void(0);" class="ripple">Save</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                
            </div>
    	</div>
    </div>
</div>
<script>
$(document).ready(function() {
	$(".single_dropdown").select2({
		placeholder: "",
		allowClear: true,
	});
});
</script>