<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/css/project.css" />
<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
        <div class="col-lg-12">
            <h1>Project Kickoff</h1>
        </div> 
        <div class="col-lg-12 flwup_topcnt fmg_topcnt clear">
        	<div class="col-lg-3 form-group">
            	<span class="date_icon"><i class="fa fa-calendar"></i></span>
                <input type="text" name="ref_date" id="ref_date" class="form-control date_picker lbl_move" value=""  label="Ref Date"/>
            </div>
            <div class="col-lg-3 form-group">
                <input type="text" name="ref_no" id="ref_no" class="form-control lbl_move" value=""  label="Ref No"/>
            </div>
            <div class="col-lg-6 form-group">
                <input type="text" name="nameofthe_property" id="nameofthe_property" class="form-control lbl_move" value=""  label="Name of the Property"/>
            </div>
        </div>
        <div class="col-lg-12 clear">
            <ul class="breadcrumb_area">
                <li><a href="conception">Conception</a></li>
                <li><a href="unit" class="active">Unit</a></li>
                <li><a href="#">WBS</a></li>
                <li><a href="turnaround-cost">Turnaround Cost</a></li>
                <li><a href="turnaround-schedule">Turnaround Schedule</a></li>
                <li><a href="#">Team</a></li>
                <li><a href="critical-area">Critical Area</a></li>
                <li><a href="make-brand">Make/Brand</a></li>
                <li><a href="documents">Documents</a></li>
                <li><a href="setup">Setup</a></li>
            </ul>
        </div>
        <div class="col-lg-12 clear">
            <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">
                <div class="col-lg-12">
                    <div class="row">
                        <div class="step_by_liner animated slideInDown"></div>
                        <ul class="step_by">
                            <li>
                                <div class="step_by_sep animated_0_4s slideInRight"><p>1</p></div>
                                <p class="stepli_p1">Phase</p>
                            </li>
                            <li>
                                <div class="step_by_sep stepsep_active animated slideInRight"><p>2</p></div>
                                <p class="stepli_p2">Block</p>
                            </li>
                            <li>
                                <div class="step_by_sep animated_1_5s slideInRight"><p>3</p></div>
                                <p class="stepli_p3">Floor</p>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-12 clear">
            	<div class="kickoff_area col-lg-12 clear">
                    <div class="col-lg-12 clear">
                        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                            <div class="panel panel-default">
                                <div class="panel-heading accordion_head accordion_head_crnt" role="tab" id="heading1" data-toggle="collapse" data-parent="#accordion" href="#collapse1" aria-expanded="true" aria-controls="collapse1">
                                    <h4><input type="text" class="pnl_head_input" name="" value="Phase1" placeholder="Phase name..." data-original-title="Phase name..." data-placement="right" data-toggle="tooltip"/></h4>
                                </div>
                                <div id="collapse1" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading1">
                                    <div class="panel-body">
                                    	<!--Main table start-->
                                        <div class="col-lg-12 padr0">
                                        	<div class="table-responsive topsp">
                                        		<table class="table table-hover m_btm0">
                                                    <thead>
                                                        <tr>
                                                            <th width="11%">Block Name</th>
                                                            <th width="5%">No of Floors</th>
                                                            <th width="10%">Title</th>
                                                            <th width="10%">WBS</th>
                                                            <th width="2%">Action</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                    	<tr>
                                                            <td><input type="text" class="parent_text" name="" value=""/></td>
                                                            <td><input type="text" class="parent_text" name="" value=""/></td>
                                                            <td><input type="text" class="parent_text" name="" value=""/></td>
                                                            <td><input type="text" class="parent_text" name="" value=""/></td>
                                                            <td class="action_btns_td">
                                                                <ul class="action_btns">
                                                                    <li>
                                                                        <a href="#" class="">
                                                                            <span data-original-title="Delete" data-placement="left" data-toggle="tooltip"><i class="fa fa-trash-o"></i></span>
                                                                        </a>
                                                                    </li>
                                                                    <li>
                                                                        <a href="#" class="mainTr">
                                                                            <span data-original-title="Add lines" data-placement="left" data-toggle="tooltip"><i class="fa fa-chevron-circle-down"></i></span>
                                                                        </a>
                                                                    </li>
                                                                </ul>
                                                            </td>
                                                        </tr>
                                                        <!--expand table-->
                                                        <tr style="display:none;" class="subTr">
                                        					<td colspan="5" class="pad0">
                                                        		<div class="subDiv" style="display:none;">
                                        							<div class="col-lg-12">
                                                                        <div class="table-responsive topsp">
                                                                            <table class="table m_btm0">
                                                                                <thead>
                                                                                    <tr>
                                                                                        <th width="17%">Floor Name</th>
                                                                                        <th width="10%">Title</th>
                                                                                        <th width="10%">WBS</th>
                                                                                        <th width="2%">Action</th>
                                                                                    </tr>
                                                                                </thead>
                                                                                <tbody>
                                                                                    <tr>
                                                                                        <td><input type="text" class="parent_text" name="" value=""></td>
                                                                                        <td><input type="text" class="parent_text" name="" value=""></td>
                                                                                        <td><input type="text" class="parent_text" name="" value=""></td>
                                                                                        <td class="action_btns_td">
                                                                                            <ul class="action_btns">
                                                                                                <li>
                                                                                                    <a href="#" class="">
                                                                                                        <span data-original-title="Delete" data-placement="left" data-toggle="tooltip"><i class="fa fa-trash-o"></i></span>
                                                                                                    </a>
                                                                                                </li>
                                                                                                <li>
                                                                                                    <a href="#" class="mainTr">
                                                                                                        <span data-original-title="Add lines" data-placement="left" data-toggle="tooltip"><i class="fa fa-chevron-circle-down"></i></span>
                                                                                                    </a>
                                                                                                </li>
                                                                                            </ul>
                                                                                        </td>
                                                                                    </tr>
                                                                                    <!--expand table-->
                                                                                    <tr style="display:none;" class="subTr">
                                                                                        <td colspan="4" class="pad0">
                                                                                            <div class="subDiv" style="display:none;">
                                                                                                <div class="col-lg-12">
                                                                                                    <div class="table-responsive topsp">
                                                                                                        <table class="table m_btm0">
                                                                                                            <thead>
                                                                                                                <tr>
                                                                                                                    <th width="12%">Flat Type</th>
                                                                                                                    <th width="10%">Title</th>
                                                                                                                    <th width="10%">Area</th>
                                                                                                                    <th width="5%">No of Flats</th>
                                                                                                                    <th width="2%">Action</th>
                                                                                                                </tr>
                                                                                                            </thead>
                                                                                                            <tbody>
                                                                                                                <tr>
                                                                                                                    <td><input type="text" class="parent_text" name="" value=""></td>
                                                                                                                    <td><input type="text" class="parent_text" name="" value=""></td>
                                                                                                                    <td><input type="text" class="parent_text" name="" value=""></td>
                                                                                                                    <td><input type="text" class="parent_text" name="" value=""></td>
                                                                                                                    <td class="action_btns_td">
                                                                                                                        <ul class="action_btns">
                                                                                                                            <li>
                                                                                                                                <a href="#" class="">
                                                                                                                                    <span data-original-title="Delete" data-placement="left" data-toggle="tooltip"><i class="fa fa-trash-o"></i></span>
                                                                                                                                </a>
                                                                                                                            </li>
                                                                                                                            <li>
                                                                                                                                <a href="#" class="mainTr">
                                                                                                                                    <span data-original-title="Add lines" data-placement="left" data-toggle="tooltip"><i class="fa fa-chevron-circle-down"></i></span>
                                                                                                                                </a>
                                                                                                                            </li>
                                                                                                                        </ul>
                                                                                                                    </td>
                                                                                                                </tr>
                                                                                                                <!--expand table-->
                                                                                                                <tr style="display:none;" class="subTr">
                                                                                                                    <td colspan="5" class="pad0">
                                                                                                                        <div class="subDiv" style="display:none;">
                                                                                                                            <div class="col-lg-12">
                                                                                                                                <div class="table-responsive topsp">
                                                                                                                                    <table class="table m_btm0">
                                                                                                                                        <thead>
                                                                                                                                            <tr>
                                                                                                                                                <th width="12%">Flat Name</th>
                                                                                                                                                <th width="10%">Area</th>
                                                                                                                                                <th width="2%">Action</th>
                                                                                                                                            </tr>
                                                                                                                                        </thead>
                                                                                                                                        <tbody>
                                                                                                                                            <tr>
                                                                                                                                                <td><input type="text" class="parent_text" name="" value=""></td>
                                                                                                                                                <td><input type="text" class="parent_text" name="" value=""></td>
                                                                                                                                                <td class="action_btns_td">
                                                                                                                                                    <ul class="action_btns">
                                                                                                                                                        <li>
                                                                                                                                                            <a href="#" class="">
                                                                                                                                                                <span data-original-title="Delete" data-placement="left" data-toggle="tooltip"><i class="fa fa-trash-o"></i></span>
                                                                                                                                                            </a>
                                                                                                                                                        </li>
                                                                                                                                                    </ul>
                                                                                                                                                </td>
                                                                                                                                            </tr>
                                                                                                                                        </tbody>
                                                                                                                                    </table>
                                                                                                                                </div>
                                                                                                                            </div>
                                                                                                                        </div>
                                                                                                                    </td>
                                                                                                                </tr>
                                                                                                                <!--expand end-->
                                                                                                            </tbody>
                                                                                                        </table>
                                                                                                    </div>
                                                                                                </div>
                                                                                            </div>
                                                                                        </td>
                                                                                    </tr>
                                                                                    <!--expand end-->
                                                                                </tbody>
                                                                            </table>
                                        								</div>
                                        							</div>
                                        						</div>
                                        					</td>
                                        				</tr>
                                        				<!--expand end-->
                                        			</tbody>
                                        		</table>
                                        	</div>
                                        </div>
                                        <!--Main table End-->
                                    </div>
                                </div>
                            </div>
                            <div class="panel panel-default">
                                <div class="panel-heading accordion_head" role="tab" id="heading2"  data-toggle="collapse" data-parent="#accordion" href="#collapse2" aria-expanded="false" aria-controls="collapse2">
                                    <h4><input type="text" class="pnl_head_input" name="" value="Phase2" placeholder="Phase name..." data-original-title="Phase name..." data-placement="right" data-toggle="tooltip"/></h4>
                                </div>
                                <div id="collapse2" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading2">
                                    <div class="panel-body">
                                        <!--Main table start-->
                                        <div class="col-lg-12 padr0">
                                        	<div class="table-responsive topsp">
                                        		<table class="table table-hover m_btm0">
                                                    <thead>
                                                        <tr>
                                                            <th width="11%">Block Name</th>
                                                            <th width="5%">No of Floors</th>
                                                            <th width="10%">Title</th>
                                                            <th width="10%">WBS</th>
                                                            <th width="2%">Action</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                    	<tr>
                                                            <td><input type="text" class="parent_text" name="" value=""/></td>
                                                            <td><input type="text" class="parent_text" name="" value=""/></td>
                                                            <td><input type="text" class="parent_text" name="" value=""/></td>
                                                            <td><input type="text" class="parent_text" name="" value=""/></td>
                                                            <td class="action_btns_td">
                                                                <ul class="action_btns">
                                                                    <li>
                                                                        <a href="#" class="">
                                                                            <span data-original-title="Delete" data-placement="left" data-toggle="tooltip"><i class="fa fa-trash-o"></i></span>
                                                                        </a>
                                                                    </li>
                                                                    <li>
                                                                        <a href="#" class="mainTr">
                                                                            <span data-original-title="Add lines" data-placement="left" data-toggle="tooltip"><i class="fa fa-chevron-circle-down"></i></span>
                                                                        </a>
                                                                    </li>
                                                                </ul>
                                                            </td>
                                                        </tr>
                                                        <!--expand table-->
                                                        <tr style="display:none;" class="subTr">
                                        					<td colspan="5" class="pad0">
                                                        		<div class="subDiv" style="display:none;">
                                        							<div class="col-lg-12">
                                                                        <div class="table-responsive topsp">
                                                                            <table class="table m_btm0">
                                                                                <thead>
                                                                                    <tr>
                                                                                        <th width="17%">Floor Name</th>
                                                                                        <th width="10%">Title</th>
                                                                                        <th width="10%">WBS</th>
                                                                                        <th width="2%">Action</th>
                                                                                    </tr>
                                                                                </thead>
                                                                                <tbody>
                                                                                    <tr>
                                                                                        <td><input type="text" class="parent_text" name="" value=""></td>
                                                                                        <td><input type="text" class="parent_text" name="" value=""></td>
                                                                                        <td><input type="text" class="parent_text" name="" value=""></td>
                                                                                        <td class="action_btns_td">
                                                                                            <ul class="action_btns">
                                                                                                <li>
                                                                                                    <a href="#" class="">
                                                                                                        <span data-original-title="Delete" data-placement="left" data-toggle="tooltip"><i class="fa fa-trash-o"></i></span>
                                                                                                    </a>
                                                                                                </li>
                                                                                                <li>
                                                                                                    <a href="#" class="mainTr">
                                                                                                        <span data-original-title="Add lines" data-placement="left" data-toggle="tooltip"><i class="fa fa-chevron-circle-down"></i></span>
                                                                                                    </a>
                                                                                                </li>
                                                                                            </ul>
                                                                                        </td>
                                                                                    </tr>
                                                                                    <!--expand table-->
                                                                                    <tr style="display:none;" class="subTr">
                                                                                        <td colspan="4" class="pad0">
                                                                                            <div class="subDiv" style="display:none;">
                                                                                                <div class="col-lg-12">
                                                                                                    <div class="table-responsive topsp">
                                                                                                        <table class="table m_btm0">
                                                                                                            <thead>
                                                                                                                <tr>
                                                                                                                    <th width="12%">Flat Type</th>
                                                                                                                    <th width="10%">Title</th>
                                                                                                                    <th width="10%">Area</th>
                                                                                                                    <th width="5%">No of Flats</th>
                                                                                                                    <th width="2%">Action</th>
                                                                                                                </tr>
                                                                                                            </thead>
                                                                                                            <tbody>
                                                                                                                <tr>
                                                                                                                    <td><input type="text" class="parent_text" name="" value=""></td>
                                                                                                                    <td><input type="text" class="parent_text" name="" value=""></td>
                                                                                                                    <td><input type="text" class="parent_text" name="" value=""></td>
                                                                                                                    <td><input type="text" class="parent_text" name="" value=""></td>
                                                                                                                    <td class="action_btns_td">
                                                                                                                        <ul class="action_btns">
                                                                                                                            <li>
                                                                                                                                <a href="#" class="">
                                                                                                                                    <span data-original-title="Delete" data-placement="left" data-toggle="tooltip"><i class="fa fa-trash-o"></i></span>
                                                                                                                                </a>
                                                                                                                            </li>
                                                                                                                            <li>
                                                                                                                                <a href="#" class="mainTr">
                                                                                                                                    <span data-original-title="Add lines" data-placement="left" data-toggle="tooltip"><i class="fa fa-chevron-circle-down"></i></span>
                                                                                                                                </a>
                                                                                                                            </li>
                                                                                                                        </ul>
                                                                                                                    </td>
                                                                                                                </tr>
                                                                                                                <!--expand table-->
                                                                                                                <tr style="display:none;" class="subTr">
                                                                                                                    <td colspan="5" class="pad0">
                                                                                                                        <div class="subDiv" style="display:none;">
                                                                                                                            <div class="col-lg-12">
                                                                                                                                <div class="table-responsive topsp">
                                                                                                                                    <table class="table m_btm0">
                                                                                                                                        <thead>
                                                                                                                                            <tr>
                                                                                                                                                <th width="12%">Flat Name</th>
                                                                                                                                                <th width="10%">Area</th>
                                                                                                                                                <th width="2%">Action</th>
                                                                                                                                            </tr>
                                                                                                                                        </thead>
                                                                                                                                        <tbody>
                                                                                                                                            <tr>
                                                                                                                                                <td><input type="text" class="parent_text" name="" value=""></td>
                                                                                                                                                <td><input type="text" class="parent_text" name="" value=""></td>
                                                                                                                                                <td class="action_btns_td">
                                                                                                                                                    <ul class="action_btns">
                                                                                                                                                        <li>
                                                                                                                                                            <a href="#" class="">
                                                                                                                                                                <span data-original-title="Delete" data-placement="left" data-toggle="tooltip"><i class="fa fa-trash-o"></i></span>
                                                                                                                                                            </a>
                                                                                                                                                        </li>
                                                                                                                                                    </ul>
                                                                                                                                                </td>
                                                                                                                                            </tr>
                                                                                                                                        </tbody>
                                                                                                                                    </table>
                                                                                                                                </div>
                                                                                                                            </div>
                                                                                                                        </div>
                                                                                                                    </td>
                                                                                                                </tr>
                                                                                                                <!--expand end-->
                                                                                                            </tbody>
                                                                                                        </table>
                                                                                                    </div>
                                                                                                </div>
                                                                                            </div>
                                                                                        </td>
                                                                                    </tr>
                                                                                    <!--expand end-->
                                                                                </tbody>
                                                                            </table>
                                        								</div>
                                        							</div>
                                        						</div>
                                        					</td>
                                        				</tr>
                                        				<!--expand end-->
                                        			</tbody>
                                        		</table>
                                        	</div>
                                        </div>
                                        <!--Main table End-->
                                    </div>
                                </div>
                            </div>
                            <div class="panel panel-default">
                                <div class="panel-heading accordion_head" role="tab" id="heading3" data-toggle="collapse" data-parent="#accordion" href="#collapse3" aria-expanded="false" aria-controls="collapse3">
                                    <h4><input type="text" class="pnl_head_input" name="" value="Phase3" placeholder="Phase name..." data-original-title="Phase name..." data-placement="right" data-toggle="tooltip"/></h4>
                                </div>
                                <div id="collapse3" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading3">
                                    <div class="panel-body">
                                        <h4>Phase3</h4>
                                    </div>
                                </div>
                            </div>
                            <div class="panel panel-default">
                                <div class="panel-heading accordion_head" role="tab" id="heading4" data-toggle="collapse" data-parent="#accordion" href="#collapse4" aria-expanded="false" aria-controls="collapse4">
                                    <h4><input type="text" class="pnl_head_input" name="" value="Phase4" placeholder="Phase name..." data-original-title="Phase name..." data-placement="right" data-toggle="tooltip"/></h4>
                                </div>
                                <div id="collapse4" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading4">
                                    <div class="panel-body">
                                        <h4>Phase4</h4>
                                    </div>
                                </div>
                            </div>
                            <div class="panel panel-default">
                                <div class="panel-heading accordion_head" role="tab" id="heading5" data-toggle="collapse" data-parent="#accordion" href="#collapse5" aria-expanded="false" aria-controls="collapse5">
                                    <h4><input type="text" class="pnl_head_input" name="" value="Phase5" placeholder="Phase name..." data-original-title="Phase name..." data-placement="right" data-toggle="tooltip"/></h4>
                                </div>
                                <div id="collapse5" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading5">
                                    <div class="panel-body">
                                        <h4>Phase5</h4>
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                    </div>
            	</div>
            </div>       
        </div>
    </div>
</div>
<script>
$(".mainTr").click(function(e){
	e.preventDefault();
	if(!$(this).closest("tr").next(".subTr").is(":visible")){
		$(this).closest("tr").next(".subTr").show();
		$(this).closest("tr").next(".subTr").find(".subDiv").slideDown("slow");	
		$(this).find("i").addClass("tform");
	}
		else{
		$(this).closest("tr").next(".subTr").find(".subDiv").slideUp("slow");
		$(this).closest("tr").next(".subTr").slideUp("slow");
		$(this).find("i").removeClass("tform");
	}
})
</script> 
