<style>
    .autocomplete-suggestions {z-index: 999999 !important;}
	.rt_bx-clr{color:#07549b;font-size:16px;padding-bottom:6px;}
</style>
<form id="formWrapper" method="post" onsubmit="return entryValidate();">
	<h2 class="vendordetail_change">New Bank / Cash Book</h2>                                  
	<div class="right_lbox_inner_cnt">
		<div class="col-lg-12" style="margin-top:10px;">
			<div class="form-horizontal">
				<div class="row">
					<div class="form-group">
						<div class="col-lg-12">
							<input type="hidden" name="cashBankId" id="cashBankId" value="<?php echo (isset($cashBankdet)) ? $cashBankdet['CashBankId'] : '0';?>">
							<input type="hidden" name="type" id="type" value="">
							<input type="text" name="bankCompanyName" id="bankCompanyName" class="form-control lbl_move" value="<?php echo (isset($cashBankdet)) ? $cashBankdet['CompanyName'] : '';?>" label="Company" />
							<input type="hidden" name="bankCompanyNameId" id="bankCompanyNameId" value="<?php echo (isset($cashBankdet)) ? $cashBankdet['CompanyId'] : '0';?>" >
							<span class="error" id="errorbankCompanyName"></span>
						</div>
					</div>
					<div class="form-group">
						<div class="col-lg-12">
							<label class="rt_bx-clr">What Type of Book is this ?</label>
							<div class="radio_check">
								<p>
								<input type="radio" name="bankBookType" <?php echo (isset($cashBankdet) && $cashBankdet['CashOrBank']=='B') ? 'checked' : '';?> id="bankBookTypeBank" value="B" onchange="showBookType()" />
								<label for="bankBookTypeBank" class="ripple has-ripple">Bank</label>
								</p>
							</div>
							<div class="radio_check">
								<p>
								<input type="radio" name="bankBookType" <?php echo (isset($cashBankdet) && $cashBankdet['CashOrBank'] == 'C') ? 'checked' : '';?> id="bankBookTypeCash" value="C" onchange="showBookType()" />
								<label for="bankBookTypeCash" class="ripple has-ripple">Cash</label>
								</p>
							</div>
						</div>
					</div>
					<div id="divBank" <?php echo (isset($cashBankdet) && $cashBankdet['CashOrBank'] == 'B') ? '' : 'style="display: none"';?>>
						<div class="form-group " >
							<div class="col-lg-12">
								<label class="rt_bx-clr">Is this book comes under any group of book ?</label>
								<div class="radio_check">
									<p>
									<input type="radio" name="bankBookGroup" <?php echo (isset($cashBankdet) && $cashBankdet['CashOrBank'] == 'B' && $cashBankdet['AccountType']=='Y') ? 'checked' : '';?> id="bankBookGroupYes" checked />
									<label for="bankBookGroupYes" class="ripple has-ripple">Yes</label>
									</p>
								</div>
								<div class="radio_check">
									<p>
									<input type="radio" name="bankBookGroup" <?php echo (isset($cashBankdet) && $cashBankdet['CashOrBank'] == 'B' && $cashBankdet['AccountType']=='N') ? 'checked' : '';?> id="bankBookGroupNos" />
									<label for="bankBookGroupNos" class="ripple has-ripple">No</label>
									</p>
								</div>
							</div>
						</div>
						<div class="form-group">
							<div class="col-lg-12">
								<label class="rt_bx-clr">Bank Name</label>
								<input type="text" name="bankName" value="<?php echo (isset($cashBankdet) && $cashBankdet['CashOrBank'] == 'B') ? $cashBankdet['CashBankName'] : '';?>" id="bankName" class="form-control lbl_move" label="Bank Name" />
								<span class="error" id="errorbankName"></span>
							</div>
						</div>
						<div class="form-group ">
							<div class="col-lg-12">
								<label class="rt_bx-clr">Bank Branch Name</label>
								<input type="text" name="bankBranchName" value="<?php echo (isset($cashBankdet) && $cashBankdet['CashOrBank'] == 'B') ? $cashBankdet['Branch'] : '';?>" id="bankBranchName" class="form-control lbl_move" label="Branch Name" />
								<span class="error" id="errorbankBranchName"></span>
							</div>
						</div>
						<div class="form-group ">
							<div class="col-lg-12">
								<label class="rt_bx-clr">Bank Acc No</label>
								<input type="text" name="bankAccNo" value="<?php echo (isset($cashBankdet) && $cashBankdet['CashOrBank'] == 'B') ? $cashBankdet['AccountNo'] : '';?>" id="bankAccNo" class="form-control lbl_move" label="Account Number" />
								<span class="error" id="errorbankAccNo"></span>
							</div>
						</div>
						<div class="form-group ">
							<div class="col-lg-12">
								<label class="rt_bx-clr">Bank IFSC Code</label>
								<input type="text" name="bankIFSCCode" value="<?php echo (isset($cashBankdet) && $cashBankdet['CashOrBank'] == 'B') ? $cashBankdet['IFSCCode'] : '';?>" id="bankIFSCCode" class="form-control lbl_move" label="IFSC Code" />
								<span class="error" id="errorbankIFSCCode"></span>
							</div>
						</div>
						<div class="form-group ">
							<div class="col-lg-12">
								<label class="rt_bx-clr">Bank Address</label>
								<input type="text" name="bankAddr" value="<?php echo (isset($cashBankdet) && $cashBankdet['CashOrBank'] == 'B') ? $cashBankdet['Address1'] : '';?>" id="bankAddr" class="form-control lbl_move" label="Address" />
							</div>
						</div>
						<div class="form-group ">
							<div class="col-lg-12">
								<label class="rt_bx-clr">Bank Contact Person</label>
								<input type="text" name="bankContactPerson" id="bankContactPerson" value="<?php echo (isset($cashBankdet) && $cashBankdet['CashOrBank'] == 'B') ? $cashBankdet['ContactPerson'] : '';?>"  class="form-control lbl_move" label="Contact Person" />
							</div>
						</div>
						<div class="form-group ">
							<div class="col-lg-12">
								<label class="rt_bx-clr">Bank Contact No</label>
								<input type="text" name="bankContactNo" value="<?php echo (isset($cashBankdet) && $cashBankdet['CashOrBank'] == 'B') ? $cashBankdet['Mobile'] : '';?>" id="bankContactNo" class="form-control lbl_move" label="Contact Number" onkeypress="return isNumberKey(event);" />
								<span class="error" id="errorbankContactNo"></span>
							</div>
						</div>
						<div class="form-group ">
							<div class="col-lg-12">
								<label class="rt_bx-clr">Bank Under Group</label>
								<input type="text" name="bankunderGroup" value="<?php echo (isset($cashBankdet) && $cashBankdet['CashOrBank'] == 'B') ? $cashBankdet['AccountName'] : '';?>" id="bankunderGroup" class="form-control lbl_move" label="Under Group" />
								<input type="hidden" name="bankunderGroupId" id="bankunderGroupId" value="<?php echo (isset($cashBankdet) && $cashBankdet['CashOrBank'] == 'B') ? $cashBankdet['AccountId'] : '0';?>" >
							</div>
						</div>
						<div class="form-group ">
							<div class="col-lg-12">
								<label class="rt_bx-clr">Bank CA Limit</label>
								<input type="text" name="bankCALimit" value="<?php echo (isset($cashBankdet) && $cashBankdet['CashOrBank'] == 'B') ? $cashBankdet['CALimit'] : '';?>" id="bankCALimit" class="form-control lbl_move" label="CA Limit"  onblur="return FormatNum(this, 2)" onkeypress="return isDecimal(event,this)" />
							</div>
						</div>
						<div class="form-group ">
							<div class="col-lg-12">
								<label class="rt_bx-clr">Bank BG Limit</label>
								<input type="text" name="bankBGLimit" value="<?php echo (isset($cashBankdet) && $cashBankdet['CashOrBank'] == 'B') ? $cashBankdet['BGLimit'] : '';?>" id="bankBGLimit" class="form-control lbl_move" label="BG Limit"  onblur="return FormatNum(this, 2)" onkeypress="return isDecimal(event,this)" />
							</div>
						</div>
						<div class="form-group ">
							<div class="col-lg-12">
								<label class="rt_bx-clr">Bank LC Limit</label>
								<input type="text" name="bankLCLimit" value="<?php echo (isset($cashBankdet) && $cashBankdet['CashOrBank'] == 'B') ? $cashBankdet['LCLimit'] : '';?>" id="bankLCLimit" class="form-control lbl_move" label="LC Limit"  onblur="return FormatNum(this, 2)" onkeypress="return isDecimal(event,this)" />
							</div>
						</div>
					</div>
					<div id="divCash" <?php echo (isset($cashBankdet) && $cashBankdet['CashOrBank'] == 'C') ? '' : 'style="display: none"';?> >
						<div class="form-group">
							<div class="col-lg-12">
								<label class="rt_bx-clr">Cash Name</label>
								<input type="text" name="cashName" value="<?php echo (isset($cashBankdet) && $cashBankdet['CashOrBank'] == 'C') ? $cashBankdet['CashBankName'] : '';?>" id="cashName" class="form-control lbl_move" label="Cash Name"  />
								<span class="error" id="errorcashName"></span>
							</div>
						</div>
						<div class="form-group">
							<div class="col-lg-12">
								<label class="rt_bx-clr">Cash Under Group</label>
								<input type="text" name="cashunderGroup" id="cashunderGroup" value="<?php echo (isset($cashBankdet) && $cashBankdet['CashOrBank'] == 'C') ? $cashBankdet['AccountName'] : '';?>" class="form-control lbl_move" label="Under Group" />
								<input type="hidden" name="cashunderGroupId" id="cashunderGroupId" value="<?php echo (isset($cashBankdet) && $cashBankdet['CashOrBank'] == 'C') ? $cashBankdet['AccountId'] : '0';?>">
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
		<p>
		<p class="rightlbox_btn rightlbox_btnchng">
			<a href="javascript:void(0);" onclick="submitForm();" id="submitFId" data-toggle="tooltip" class="ripple" title="Submit">Submit</a>
			<a href="javascript:void(0)" onclick="closeRightBox();" data-toggle="tooltip" class="ripple" title="Cancel">Cancel</a>
			<div id="submit-loaderF" class="post_loader ask_post_loader brad_50">
				<img title="" alt="" src="/bsf_v1.1/public/images/post-loader.gif">
			</div>
		</p>
	</div>
</form>

<script type="text/javascript">
    $(".single_dropdown2").select2({
        placeholder: ""
    });
    $(document).ready(function() {
        $(".single_dropdown").select2({
            placeholder: "",
            allowClear: true
        });
    });
    var bankData=<?php echo (isset($accBankMasterList)) ? json_encode($accBankMasterList) : '[]';?>;
    var cashData=<?php echo (isset($accCashMasterList)) ? json_encode($accCashMasterList) : '[]';?>;
    var companyData=<?php echo (isset($companyMasterList)) ? json_encode($companyMasterList) : '[]';?>;

    $(function () {
        $('.right_lightbox').attr('pageRefresh','0');
        bindCompanyAutoComplete(companyData);
        bindBankGroupAutoComplete(bankData);
        bindCashGroupAutoComplete(cashData);
    });
    function showBookType() {
        var bookType=$('input[name=bankBookType]:checked').val();
        switch (bookType) {
            case 'B':
                $('#divCash').hide();
                $('#divFinancial').hide();
                $('#divBank').show().find('input').val('').attr('checked',false).trigger('change');
                $('#divBank').find('select').val('').select2();
                $('.error').text('');
                break;
            case 'C':
                $('#divFinancial').hide();
                $('#divBank').hide();
                $('#divCash').show().find('input').val('').attr('checked',false).trigger('change');
                $('#divCash').find('select').val('').select2();
                $('.error').text('');
                break;
            default :
                $('#divCash').hide();
                $('#divFinancial').hide();
                $('#divBank').show().find('input').val('').attr('checked',false).trigger('change');
                $('#divBank').find('select').val('').select2();
                $('.error').text('');
                break;
        }
    }
    function entryValidate(){
        var bookType=$('input[name=bankBookType]:checked').val();

        if($('#bankCompanyNameId').val() == 0) {
            $('#bankCompanyName').focus();
            $('#errorbankCompanyName').text('Select Valid Company Name ');
            return false;
        }else{
            $('#errorbankCompanyName').text('');
        }
        if(bookType == 'B'){
            if($('#bankName').val() == 0) {
                $('#bankName').focus();
                $('#errorbankName').text('Bank Name is Required!');
                return false;
            }else{
                $('#errorbankName').text('');
            }

            if($('#bankBranchName').val().length == 0) {
                $('#bankBranchName').focus();
                $('#errorbankBranchName').text('Branch Name is Required!');
                return false;
            }else{
                $('#errorbankBranchName').text('');
            }

            if($('#bankAccNo').val().length == 0) {
                $('#bankAccNo').focus();
                $('#errorbankAccNo').text('Account Number is Required!');
                return false;
            }else{
                $('#errorbankAccNo').text('');
            }

            if($('#bankIFSCCode').val().length == 0) {
                $('#bankIFSCCode').focus();
                $('#errorbankIFSCCode').text('IFSC Code is Required!');
                return false;
            }else{
                $('#errorbankIFSCCode').text('');
            }

            if($('#bankContactNo').val().length == 0) {
                $('#bankContactNo').focus();
                $('#errorbankContactNo').text('Contact Number is Required!');
                return false;
            }else{
                $('#errorbankContactNo').text('');
            }
        } else   if(bookType == 'C'){
            if($('#cashName').val().length == 0) {
                $('#cashName').focus();
                $('#errorcashName').text('Name is Required!');
                return false;
            }else{
                $('#errorcashName').text('');
            }
        }
    }
    function closeRightBox(){
        $('.right_lightbox').hide();
    }
    function submitForm(){
        $('#type').val('addEditDetails')
        $.ajax({
            url:"<?php echo $this->basePath(); ?>/fa/index/cashbankdetailentry",
            type:"post",
            //async:false,
            data:$('#formWrapper').serialize(),
            success:function(data, textStatus, jqXHR){
                $('.right_lightbox').hide().attr('pageRefresh','1').trigger('change');
            },
            error:function(jqXHR, textStatus, errorThrown){
            }
        });
    }

    function bindBankGroupAutoComplete(groupData) {
        var $rowid = $('#bankunderGroupId'),
            rowid = parseInt($rowid.val());
        var $groupName = $('#bankunderGroup');
        $groupName.autocomplete({
            lookup: groupData,
            showNoSuggestionNotice: false,
            lookupFilter: function (suggestion, originalQuery, queryLowerCase) {
                if (queryLowerCase == '*') {
                    return suggestion.value;
                } else {
                    var re = new RegExp($.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
                    return re.test(suggestion.value);
                }
            } /*,onSelect: function (suggestion) {
                if (suggestion) {
                    $rowid.val(suggestion.data);
                }
            },onSearchComplete: function (query, suggestions) {
                if (!suggestions.length) {
                    $rowid.val(suggestion.data);
                }else{
                    $rowid.val(0);
                }
            }*/
            , onSelect: function (suggestion) {
            if (suggestion) {
                $rowid.val(suggestion.data);
                //$(this).removeClass('error');
            }
        }, onSearchStart: function (suggestion) {
                $rowid.val(0);
            }, onSearchComplete: function (query, suggestions) {
            if (!suggestions.length) {
                $rowid.val(suggestion.data);
               // $(this).addClass('error');
            }
        }

        });
    }
    function bindCashGroupAutoComplete(groupData) {
        // bind property name autocomplete
        var $rowid = $('#cashunderGroupId'),
            rowid = parseInt($rowid.val());
        var $groupName = $('#cashunderGroup');
        $groupName.autocomplete({
            lookup: groupData,
            showNoSuggestionNotice: false,
            lookupFilter: function (suggestion, originalQuery, queryLowerCase) {
                if (queryLowerCase == '*') {
                    return suggestion.value;
                } else {
                    var re = new RegExp($.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
                    return re.test(suggestion.value);
                }
            }/*, onSelect: function (suggestion) {
                if (suggestion) {
                    $rowid.val(suggestion.data);
                }
            },onSearchComplete: function (query, suggestions) {
                if (!suggestions.length) {
                    $rowid.val(suggestion.data);
                }else{
                    $rowid.val(0);
                }
            }*/
            , onSelect: function (suggestion) {
                if (suggestion) {
                    $rowid.val(suggestion.data);
                    //$(this).removeClass('error');
                }
            }, onSearchStart: function (suggestion) {
                $rowid.val(0);
            }, onSearchComplete: function (query, suggestions) {
                if (!suggestions.length) {
                    $rowid.val(suggestion.data);
                    // $(this).addClass('error');
                }
            }
        });
    }

    function bindCompanyAutoComplete(companyList) {
        var $companyName = $('#bankCompanyName');
        var $companyId = $('#bankCompanyNameId');
        $companyName.unbind('autocomplete');
        $companyName.autocomplete({
            lookup: companyList,
            showNoSuggestionNotice: false,
            lookupFilter: function (suggestion, originalQuery, queryLowerCase) {
                if (queryLowerCase == '*') {
                    return suggestion.value;
                } else {
                    var re = new RegExp($.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
                    return re.test(suggestion.value);
                }
            }, onSelect: function (suggestion) {
                if (suggestion) {
                    $companyId.val(suggestion.data);
                    $(this).removeClass('error');
                }
            }, onSearchStart: function (suggestion) {
                $companyId.val(0);
            }, onSearchComplete: function (query, suggestions) {
                if (!suggestions.length) {
                    $companyId.val(0);
                    $(this).addClass('error');
                } else $(this).removeClass('error');
            }
        });
    }
</script>