<style>
    #jqxGrid .jqx-grid-header {
        height:75px !important;
    }
    /* Excel Floating Icon */
    .fixed-action-btn          	    {position:fixed;top:85px;right:5px;padding-top:15px;margin-bottom:0;z-index:998;}
    .fixed-action-btn:hover ul li a.btn-floating{transform: scaleY(1) scaleX(1) translateX(0px);opacity: 1;}
    .btn-floating.btn-large         {width:45px;height:45px;}
    .fixed-action-btn ul 			{left:-142px;right:0;text-align:center;position:absolute;margin:0;top:22px;}
    .fixed-action-btn ul li 		{margin-left:8px;list-style-type:none;float:left;}
    .fixed-action-btn ul li a.btn-floating {transform: scaleY(0.4) scaleX(0.4) translateX(40px);opacity: 0;}
    .fixed-action-btn ul a.btn-floating i  {font-size: 17px;line-height: 37px;}
    .btn-floating                   {display:inline-block;color:#fff;position:relative;overflow:hidden;z-index:1;width:37px;height:37px;line-height:37px;padding: 0;
        background-color: #26a69a;border-radius:50%;cursor:pointer;vertical-align: middle;
        box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);text-decoration: none;transition: all .3s ease;
        -webkit-transition: all .3s ease; -moz-transition: all .3s ease; -o-transition: all .3s ease;}
    .btn-floating i                 {width: inherit;display: inline-block;text-align: center;color: #fff;font-size:20px;line-height: 45px; font-weight:normal; color:#fff;}
    .next-bt                        {text-align:center;}
    .next-bt a:hover                {border:1px solid #3580C4 !important; background:#fff !important; color:#3580C4 !important;}
    .next-bt a                      {background:#3580C4!important;border:1px solid #3580C4; border-radius: 4px;
        color:#fff!important; font-size:14px; padding: 5px 10px; text-align: center; transition: all 0.4s ease 0s;}
    .commargin_bottom				{margin-bottom:20px !important;}
    .req_addbtn a {padding: 6px 8px 9px 9px !important;}
    .jqx-grid-cell-right-align {text-align: right;}
    /*.jqx-grid-cell-left-align {text-align: left;}*/
    .jqx-grid-cell { text-align: center; }

    /* Excel Floating Icon end*/
</style>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqx-all.js"></script>
<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
        <div class="col-lg-12">
            <h1 class="col-lg-6 padlr0">
                Receipt Journal Register<div class="stgedit_btn req_addbtn brad_50"><!--Deposit Entry-->
                    <a href="<?php echo $this->basePath(); ?>/fa/index/depositentry" class="ripple" data-toggle="tooltip" data-placement="right" title="Add&nbsp;New&nbsp;Account"><i class="fa fa-plus"></i></a>
                </div>
            </h1>
            <input type="hidden" name="FYearId" id="FYearId" value="<?php echo (isset($FYearId)) ? $FYearId : '0';?>">
            <input type="hidden" name="companyId" id="companyId" value="<?php echo (isset($companyId)) ? $companyId : '0';?>">
            <div class="form-group col-lg-12 clear padtop20 commargin_ttop_20 commargin_bottom">
                <div class="form-group col-lg-12">
                    <div class="radio_check" style="" label="select">
                        <p class="stat_lbl">
                            <input type="radio" id="bankBook" class="paymentBook" value="BA" <?php echo (isset($bookType) && $bookType != 'CA') ? 'checked' : '' ?> checked name="paymentBook" onchange="bookType();" />
                            <label for="bankBook" class="ripple has-ripple" style="position: relative; overflow: hidden;">Bank Book<span class="ripple-wrapper animated"></span></label>
                        </p>
                        <p class="stat_lbl">
                            <input type="radio" id="cashBook" class="paymentBook" value="CA" <?php echo (isset($bookType) && $bookType == 'CA') ? 'checked' : '' ?> name="paymentBook" onchange="bookType();"/>
                            <label for="cashBook" class="ripple has-ripple" style="position: relative; overflow: hidden;">Cash Book<span class="ripple-wrapper animated"></span></label>
                        </p>
                    </div>
                </div>
                <div class=" col-lg-4" >
                    <select name="bookId" id="bookId" class="single_dropdown lbl_move" style="width:100%;" onchange="loadTransfers()" label="Select Book..." >
                        <option value="0" <?php if($accountId ==0) { echo "selected";} ?>>Select Book</option>
                        <?php foreach($fromBookList as $bookList){ ?>
                            <option value="<?php echo $bookList['AccountID'] ?>" <?php if($bookList['AccountID'] == $accountId) { echo "selected";} ?> ><?php echo $bookList['AccountName'] ?></option>
                        <?php } ?>
                    </select>
                </div>
                <?php $prevMonth=date('d-m-Y', strtotime('-30 day', strtotime(date('d-m-Y'))));
                $curDate=date('d-m-Y'); ?>
                <div class="col-lg-4">
                    <span class="date_icon"><i class="fa fa-calendar"></i></span>
                    <input type="text" name="fromDate" id="fromDate" class="form-control lbl_move datepickerinput" onchange="loadTransfers()" label="From Date" value="<?php echo (isset($fromDate)) ? $fromDate : $prevMonth;?>" />
                </div>
                <div class="col-lg-4">
                    <span class="date_icon"><i class="fa fa-calendar"></i></span>
                    <input type="text" name="toDate" id="toDate" class="form-control lbl_move datepickerinput" onchange="loadTransfers()" label="To Date" value="<?php echo (isset($toDate)) ? $toDate: $curDate;?>" />
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6">
            <div class="fixed-action-btn active">
                <a class="btn-floating btn-large">
                    <i class="fa fa-print"></i>
                </a>
                <ul>
                    <li>
                        <a class="btn-floating hide-input-file" id="print" href="javascript:void(0);" data-toggle="tooltip" data-placement="top" data-original-title="Print Report">
                            <i class="fa fa-print"></i>
                        </a>
                    </li>
                    <li>
                        <a class="btn-floating" id="excelExport" href="javascript:void(0);" data-toggle="tooltip" data-placement="top" data-original-title="Download Excel">
                            <i class="fa fa-download"></i>
                        </a>
                    </li>
                    <li>
                        <a class="btn-floating" id="csvExport" href="javascript:void(0);" data-toggle="tooltip" data-placement="top" data-original-title="Export CSV">
                            <i class="fa fa-file-archive-o"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-lg-12 clear">
            <div class="table-responsive clear">
                <div id="jqxGrid">
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var $jqxGrid = $("#jqxGrid");
    var regList=<?php echo (isset($regList)) ? json_encode($regList) : '[]';?>;
    var startDate="<?php echo (isset($fiscalfromDate)) ? $fiscalfromDate : '';?>";
    var endDate="<?php echo (isset($fiscaltoDate)) ? $fiscaltoDate : '';?>";
    var start_date =startDate.split('-');
    var end_date =endDate.split('-');

    $('.datepickerinput').datepicker({
        'format': 'dd-mm-yyyy',
        startDate: new Date(start_date[2],start_date[1]-1,start_date[0]),
        endDate: new Date(end_date[2],end_date[1]-1,end_date[0])
    }).on('changeDate', function() {
        $('.datepicker').hide();
    }).data('datepicker');

    $(function () {
        bindGrid(regList);
    });

    function loadTransfers(){
        var paymentBook = $("input[name=paymentBook]:checked").val();
        var bookId=0;
        if($('#bookId').val() == '' || $('#bookId').val() ==null){
            bookId=0;
        }else{
            bookId=$('#bookId').val();
        }
        window.location = getBaseURL() + 'fa/index/depositregister/'+bookId+'/'+$('#fromDate').val()+'/'+$('#toDate').val()+'/'+paymentBook;
    }

    function bindGrid(data){
        var source = {
            localdata:data,
            async: false,
            dataType: "json",
            dataFields: [
                { name: 'EntryId', type: 'number' },
                { name: 'VoucherDate', type: 'string' },
                { name: 'VoucherNo', type: 'string' },
                { name: 'RefNo', type: 'string' },
                { name: 'RelatedRefNo', type: 'string' },
                { name: 'AccountName', type: 'string' },
                { name: 'SubLedgerName', type: 'string' },
                { name: 'EntryType', type: 'string' },
                { name: 'JournalType', type: 'string' },
                { name: 'Debit', type: 'number' },
                { name: 'Credit', type: 'number' },
                { name: 'PDCDebit', type: 'number' },
                { name: 'PDCCredit', type: 'number' },
                { name: 'Narration', type: 'string' },
                { name: 'ChequeNo', type: 'string' },
                { name: 'ChequeDate', type: 'string' },
                { name: 'ChequeDescription', type: 'string' },
                { name: 'CostCentreName', type: 'string' },
                { name: 'IsLock', type: 'string' },
                { name: 'PDC', type: 'string' },
                { name: 'IsAppReady', type: 'string' },
                { name: 'Document', type: 'string' },
                { name: 'Approve', type: 'string' },
                { name: 'TypeId', type: 'string' },
                { name: 'SubLedgerTypeId', type: 'number' },
                { name: 'Print', type: 'string' },
                { name: 'FromAdjust', type: 'string' }

            ]
        };
        var dataAdapter = new $.jqx.dataAdapter(source);
        $jqxGrid.jqxGrid({
            width: "100%",
            source: dataAdapter,
            autoheight: true,
            filterable: true,
            showfilterrow: true,
            sortable: true,
            pageable:true,
            rowDetails: true,
            columns: [
                { text: 'EntryId', datafield: 'EntryId', hidden: true, filterable: false},
                { text: 'Voucher Date', dataField: 'VoucherDate', width:'10%'},
                { text: 'Voucher No', dataField: 'VoucherNo', width:'10%'},
                { text: 'RefNo', dataField: 'RefNo', width:'10%'},
                { text: 'Related RefNo', dataField: 'RelatedRefNo', hidden: true, filterable: false},
                { text: 'Account', dataField: 'AccountName', width:'10%'},
                { text: 'SubLedger', dataField: 'SubLedgerName', width:'10%'},
                { text: 'Entry Type', datafield: 'EntryType', hidden: true, filterable: false},
                { text: 'Type', datafield: 'JournalType', width:'10%'},
                { text: 'Debit', dataField: 'Debit', width:'10%'},
                { text: 'Credit', dataField: 'Credit', width:'10%'},
                { text: 'ChequeNo', dataField: 'ChequeNo', hidden: true, filterable: false},
                { text: 'IsAppReady', dataField: 'IsAppReady', hidden: true, filterable: false},
                { text: 'Approve', dataField: 'Approve', width:'10%'},
                { text: 'Action', sortable: false, filterable: false, align: 'left', width:'10%',
                    cellsrenderer: function (row) {
                        var editLink = '<a title="Edit" href="javascript:void(0);" onclick="billEdit('+row+'); return false;" style="padding-left: 15px;"><i class="fa fa-pencil-square-o reg-icon"></i></a>';
                        return editLink += "&nbsp;&nbsp;" + '<button style="background: transparent;" title="Delete" onclick="billDelete('+row+'); return false;"><i class="fa fa-trash-o reg-icon"></i></button>';
                        return editLink;
                        //return editLink += "&nbsp;&nbsp;" + '<a title="Report" href="#" onclick="billReport('+row+'); return false;"><i class="fa fa-file-text-o reg-icon-file"></i></a>';
                    }
                }
            ]
        });
        $jqxGrid.on('celldoubleclick', function (event){
            // event arguments.
            var args = event.args;
            // row's bound index.
            var rowBoundIndex = args.rowindex;
            var dataField = args.datafield;
            var data = $jqxGrid.jqxGrid("getrowdata", rowBoundIndex);
            var iEntryId=data.EntryId;
            if(iEntryId!=0){
                window.location.replace(getBaseURL() + "fa/index/depositentry/" + iEntryId);
            }
        });
    }

    function billEdit(row) {
        var iEntryId= $jqxGrid.jqxGrid('getCellValue', row, 'EntryId');
        var EntryType= $jqxGrid.jqxGrid('getCellValue', row, 'EntryType ');
        var JournalType= $jqxGrid.jqxGrid('getCellValue', row, 'JournalType');
        if(iEntryId!=0){
            window.location.replace(getBaseURL() + "fa/index/depositentry/" + iEntryId);
        }
    }

    function billDelete(row) {
        alert('Delete Not Done');
        /*var ReceiptId = $jqxGrid.jqxGrid('getCellValue', row, 'ReceiptId');
        $.ajax({
            url: getBaseURL() + 'fa/index/depositentryregister',
            async: false,
            type: 'POST',
            data: {"paymentAdviceNo": ReceiptId},
            success:function(data, textStatus, jqXHR){

            }
        });*/
    }
    function bookType(){
        var paymentBook = $("input[name=paymentBook]:checked").val();
        $('#bookId').html('');
        //$("#bookId").val('').select2();
        $.ajax({
            url:"<?php echo $this->basePath(); ?>/fa/index/depositregister",
            type:"post",
            //async:false,
            data:{'paymentBookType':paymentBook,'type':'loadBookName'},
            success:function(data, textStatus, jqXHR){
                var BookList = JSON.parse(data);
                BookList = BookList['BookList'];
                if(BookList){
                    $('#bookId').append('<option value=""></option>');
                    $.each(BookList,function(i,o){
                        $('#bookId').append('<option value='+ o.AccountID+'>'+ o.AccountName+'<option>');
                    });
                }
            },
            error:function(jqXHR, textStatus, errorThrown){
            }
        });
    }
</script>