<style>
    #jqxGrid .jqx-grid-header {
        height:75px !important;
    }
    /* Excel Floating Icon */
    .fixed-action-btn          	    {position:fixed;top:85px;right:5px;padding-top:15px;margin-bottom:0;z-index:998;}
    .fixed-action-btn:hover ul li a.btn-floating{transform: scaleY(1) scaleX(1) translateX(0px);opacity: 1;}
    .btn-floating.btn-large         {width:45px;height:45px;}
    .fixed-action-btn ul 			{left:-142px;right:0;text-align:center;position:absolute;margin:0;top:22px;}
    .fixed-action-btn ul li 		{margin-left:8px;list-style-type:none;float:left;}
    .fixed-action-btn ul li a.btn-floating {transform: scaleY(0.4) scaleX(0.4) translateX(40px);opacity: 0;}
    .fixed-action-btn ul a.btn-floating i  {font-size: 17px;line-height: 37px;}
    .btn-floating                   {display:inline-block;color:#fff;position:relative;overflow:hidden;z-index:1;width:37px;height:37px;line-height:37px;padding: 0;
        background-color: #26a69a;border-radius:50%;cursor:pointer;vertical-align: middle;
        box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);text-decoration: none;transition: all .3s ease;
        -webkit-transition: all .3s ease; -moz-transition: all .3s ease; -o-transition: all .3s ease;}
    .btn-floating i                 {width: inherit;display: inline-block;text-align: center;color: #fff;font-size:20px;line-height: 45px; font-weight:normal; color:#fff;}
    .next-bt                        {text-align:center;}
    .next-bt a:hover                {border:1px solid #3580C4 !important; background:#fff !important; color:#3580C4 !important;}
    .next-bt a                      {background:#3580C4!important;border:1px solid #3580C4; border-radius: 4px;
        color:#fff!important; font-size:14px; padding: 5px 10px; text-align: center; transition: all 0.4s ease 0s;}
    .commargin_bottom				{margin-bottom:20px !important;}
    .req_addbtn a {padding: 6px 8px 9px 9px !important;}
    .jqx-grid-cell-right-align {text-align: right;}
    /*.jqx-grid-cell-left-align {text-align: left;}*/
    .jqx-grid-cell { text-align: center; }

    /* Excel Floating Icon end*/
</style>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqx-all.js"></script>
<div class="content_wrapper padlr0">
    <div class="container-fluid padlr0">
        <div class="col-lg-12">
            <h1 class="col-lg-6 padlr0">
                Payment Advice Register<div class="stgedit_btn req_addbtn brad_50">
                    <a href="<?php echo $this->basePath(); ?>/fa/index/paymentadvice" class="ripple" data-toggle="tooltip" data-placement="right" title="Add&nbsp;New&nbsp;Account"><i class="fa fa-plus"></i></a>
                </div>
            </h1>
            <input type="hidden" name="FYearId" id="FYearId" value="<?php echo (isset($FYearId)) ? $FYearId : '0';?>">
            <input type="hidden" name="companyId" id="companyId" value="<?php echo (isset($companyId)) ? $companyId : '0';?>">
            <div class="form-group col-lg-12 clear padtop20 commargin_ttop_20 commargin_bottom">
                <div class=" col-lg-4">
                    <select name="subLedger" id="subLedger" class="single_dropdown lbl_move" onchange="SLType();" style="width:100%;"  label="Select SubLedger..." >
                        <option value="0" > select </option>
                        <?php foreach($slList as $slLists){ ?>
                            <option value="<?php echo $slLists['SubLedgerTypeId'] ?>" ><?php echo $slLists['SubLedgerTypeName'] ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6">
            <div class="fixed-action-btn active">
                <a class="btn-floating btn-large">
                    <i class="fa fa-print"></i>
                </a>
                <ul>
                    <li>
                        <a class="btn-floating hide-input-file" id="print" href="javascript:void(0);" data-toggle="tooltip" data-placement="top" data-original-title="Print Report">
                            <i class="fa fa-print"></i>
                        </a>
                    </li>
                    <li>
                        <a class="btn-floating" id="excelExport" href="javascript:void(0);" data-toggle="tooltip" data-placement="top" data-original-title="Download Excel">
                            <i class="fa fa-download"></i>
                        </a>
                    </li>
                    <li>
                        <a class="btn-floating" id="csvExport" href="javascript:void(0);" data-toggle="tooltip" data-placement="top" data-original-title="Export CSV">
                            <i class="fa fa-file-archive-o"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-lg-12 clear">
            <div class="table-responsive clear">
                <div id="jqxGrid">
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var $jqxGrid = $("#jqxGrid");
    var paymentadviceList=<?php echo (isset($paymentadviceList)) ? json_encode($paymentadviceList) : '[]';?>

        $('.datepickerinput').datepicker({
            'format': 'dd-mm-yyyy'
        }).on('changeDate', function() {
            $('.datepicker').hide();
        }).data('datepicker');

    $(function () {
        bindGrid(paymentadviceList);
    });

    function bindGrid(paymentadviceList){
        var source = {
            localdata:paymentadviceList,
            async: false,
            dataType: "json",
            dataFields: [
                { name: 'PayAdviceId', type: 'number' },
                { name: 'PayAdviceDate', type: 'datetime' },
                { name: 'PayAdviceNo', type: 'string' },
                { name: 'SLedgerId', type: 'number' },
                { name: 'SubLedgerTypeName', type: 'string' },
                { name: 'BillAmount', type: 'number' },
                { name: 'TotalAmount', type: 'number' },
                { name: 'BillType', type: 'string' },
                { name: 'Approve', type: 'string' }
            ]
        };
        var dataAdapter = new $.jqx.dataAdapter(source);
        $jqxGrid.jqxGrid({
            width: "100%",
            source: dataAdapter,
            autoheight: true,
            filterable: true,
            showfilterrow: true,
            sortable: true,
            pageable:true,
            rowDetails: true,
            columns: [
                { text: 'PayAdviceId', dataField: 'PayAdviceId',hidden: true},
                { text: 'TotalAmount', dataField: 'TotalAmount',hidden: true},
                { text: 'Payment Advice Date', dataField: 'PayAdviceDate', filterable: true, width:'18%'},
                { text: 'Payment AdviceNo', dataField: 'PayAdviceNo', width:'18%'},
                { text: 'SubLedgerTypeId', dataField: 'SLedgerId', hidden: true },
                { text: 'SubLedger TypeName', dataField: 'SubLedgerTypeName', width:'28%'},
                { text: 'Bill Amount', dataField: 'BillAmount', width:'10%',cellsalign: 'right'},
                { text: 'Bill Type', dataField: 'BillType', width:'10%',cellsalign: 'right'},
                { text: 'Approve', dataField: 'Approve', width:'10%',cellsalign: 'center'},
                { text: 'Action', sortable: false, filterable: false, width:'6%',
                    cellsrenderer: function (row) {
                        var editLink = '<a title="Edit" href="javascript:void(0);" onclick="billEdit('+row+'); return false;" style="padding-left: 15px;"><i class="fa fa-pencil-square-o reg-icon"></i></a>';
                        return editLink += "&nbsp;&nbsp;" + '<button style="background: transparent;" title="Delete" onclick="billDelete('+row+'); return false;"><i class="fa fa-trash-o reg-icon"></i></button>';
                        return editLink;
                        //return editLink += "&nbsp;&nbsp;" + '<a title="Report" href="#" onclick="billReport('+row+'); return false;"><i class="fa fa-file-text-o reg-icon-file"></i></a>';
                    }
                }
            ]
        });
    }

    function billEdit(row) {
        var PayAdviceId = $jqxGrid.jqxGrid('getCellValue', row, 'PayAdviceId');
//        console.log(PayAdviceId);
        if(PayAdviceId!=0){
            window.location.replace(getBaseURL() + "fa/index/paymentadvice/" + PayAdviceId);
        }else{
            window.location.replace(getBaseURL() + "fa/index/paymentadvice/" + PayAdviceId);
        }
    }
    function billDelete(row) {
        var PayAdviceId = $jqxGrid.jqxGrid('getCellValue', row, 'PayAdviceId');
        $.ajax({
            url: getBaseURL() + 'fa/index/payment-advice-register',
            async: false,
            type: 'POST',
            data: {"paymentAdviceNo": PayAdviceId},
            success:function(data, textStatus, jqXHR){

            }
        });
    }

    function  SLType(){
        var slId = $("#subLedger").val();

        if(slId != ''){
            slId = slId;
        }else{
            slId=0;
        }
        $.ajax({
            url: getBaseURL()+'fa/index/payment-advice-register',
            type: 'POST',
            async: false,
            data:{"slTypeId":slId,"mode":"getSLList" },
            success:function(data, textStatus, jqXHR){
                bindGrid(data);
            }
        });

    }
</script>