<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/mms.css" />
<style type="text/css">
    .lbl_move{height:40px !important;}
</style>
<div class="content_wrapper">
    <div class="container-fluid">
        <div class="col-lg-12">
            <h1 class="txt_center">Transfer Entry</h1>
            <div class="col-lg-3">
                <div class="form-group req_flds col-lg-12">
                    <input type="text" name="Voucher No" id="Voucher No" style="width:100%;" class="form-control lbl_move" label="Voucher No" />
                    <div class="error_message"><p>please enter Voucher No...</p></div>
                </div>
            </div>
            <div class="col-lg-3 col-lg-offset-6">
                <div class="form-group req_flds col-lg-12">
                    <span class="date_icon"><i class="fa fa-calendar"></i></span>
                    <input type="text" name="Voucher date" id="Voucher date" class="form-control lbl_move datepickerinput" label="Voucher Date" value="" />
                    <div class="error_message"><p>Please enter Voucher date...</p></div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="form-group col-lg-12">
                        <select style="width:100%;" class="single_dropdown lbl_move" label="From Book Name" name="fromBookName" id="fromBookName" onchange="showToBookName()">
                            <option value="">Select Project</option>
                            <?php if(isset($bookNameSelect)):?>
                                <?php foreach ( $bookNameSelect as $bookName ):?>
                                    <option value="<?php echo $bookName[ 'CashBankId' ];?>"><?php echo $bookName[ 'CashBankName' ];?></option>
                                <?php endforeach; ?>
                            <?php  endif; ?>
                        </select>
                        <input type="hidden" name="CompanyId" id="CompanyId" value="">
                        <div><p style="color:#266aa8;float:right;">BALANCE: 15428485.00 DR</p></div>
                    </div>
                </div>
                <div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 ">
                    <div class="form-group col-lg-12">
                        <select style="width:100%;" class="single_dropdown lbl_move" label="To Book Name" name="toBookName" id="toBookName" >
                            <option value=""></option>
                        </select>
                    </div>
                </div>
                <div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="form-group col-lg-12">
                        <select style="width:100%;" class="single_dropdown lbl_move" label="Payment Mode" name="Payment Mode" id="Payment Mode">
                            <option value=""></option>
                            <option value="C">Cash</option>
                            <option value="Ch">Check</option>
                            <option value="N">NEFT</option>
                        </select>
                    </div>
                </div>
                <div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="form-group col-lg-12">
                        <span class="date_icon"><i class="fa fa-calendar"></i></span>
                        <input type="text" name="Voucher date" id="Transaction date" class="form-control lbl_move datepickerinput" label="Transaction date" value="" />
                        <div class="error_message"><p>Please enter Transaction date...</p></div>
                    </div>
                </div>
                <div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="form-group col-lg-12">
                        <input type="text" class="form-control lbl_move" label="Transaction No" id="Transaction No" name="Transaction No" value="">
                    </div>
                </div>
                <div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="form-group col-lg-12">
                        <input type="text" class="form-control lbl_move" label="Amount" id="Amount" name="Amount" value="">
                    </div>
                </div>
                <div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="form-group col-lg-12">
                        <textarea class="exp-tex" name="Narration" id="remarks"></textarea>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-lg-12 savebtn_area">
    <ul>
        <li id="continue" class="dropdown save_btn float_r"><a href="javascript:void(0);" class="ripple">Add</a></li>
        <li class="cancel_btn cancel_btn_bluecolor float_r">
            <a class="ripple has-ripple" style="cursor:pointer;" button type="button" onclick="" id="backRid" class="ripple">Cancel<span class="ripple-wrapper"></span></a></li>
        </li>
    </ul>
</div>

<script type="text/javascript">
    var $toNameSelect;
    function showToBookName() {
        var fromBookName = $("#fromBookName").val();
        $.ajax({
            url:"<?php echo $this->basePath(); ?>/fa/index/samecompanytransfer",
            data: {'fromName':fromBookName},
            type:"post",
            //async:false,
            success:function(data, textStatus, jqXHR){

            },
            error:function(jqXHR, textStatus, errorThrown){
            }
        });
    }
</script>