<!--STYLE-->
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/select2.min.css" />
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/select2.full.min.js"></script>
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/workorder.css';?>"/>
<style>
    .pagination-lg > li > a, .pagination-lg > li > span {
        font-size:15px !important;
        padding:5px 15px !important;
    }
    #jqxGrid .jqx-grid-header {
        height:75px !important;
    }
</style>

<div class="content_wrapper padlr0">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 top-btm">
                <h1>Special Journal Details
                    <div class="stgedit_btn req_addbtn brad_50">
                        <a href="<?php echo $this->basePath(); ?>/fa/index/specialjournal/0" class="ripple" data-toggle="tooltip" data-placement="right" title="Add&nbsp;New&nbsp;Special Journal"><i class="fa fa-plus"></i></a>
                    </div>
                </h1>
            </div>
            <div class="col-lg-12 top_ct">
                <div class="clearfix"></div>
                <div class="col-lg-12 col-lg-offset-0 tmss">
                    <div class="table-responsive clear">
                        <div id="jqxGrid"> </div>
                    </div>
                </div>
                <input type="hidden" name="typeFlow" id="typeFlow" value="">
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var data = <?php echo (isset($entryList)) ? json_encode($entryList) : ''?>,
        $jqxGrid = $("#jqxGrid");

    $(function () {
        $(".single_dropdown2").select2({
            placeholder: "",
            minimumResultsForSearch: -1
        });
        bindGrid(data);
    });

    function bindGrid(gridData){
        var source = {
            localdata:gridData,
            async: false,
            dataType: "json",
            dataFields: [
                { name: 'JournalEntryId', type: 'number' },
                { name: 'JVDate', type: 'string' },
                { name: 'JVNo', type: 'string' },
                { name: 'JVType', type: 'string' },
                { name: 'Debit', type: 'number' },
                { name: 'Credit', type: 'number' }
            ],
            id: 'JournalEntryId'
        };
        var dataAdapter = new $.jqx.dataAdapter(source);
        $jqxGrid.jqxGrid({
            width: "100%",
            source: dataAdapter,
            autoheight: true,
            filterable: true,
            pagerButtonsCount: 6,
            showfilterrow: true,
            sortable: true,
            pageable:true,
            rowDetails: true,
            columns: [
                { text: 'JournalEntryId', datafield: 'JournalEntryId', hidden: true, filterable: false},
                { text: 'JVNo', datafield: 'JVNo', width:'10%'},
                { text: 'JVDate', dataField: 'JVDate', width:'20%'},
                { text: 'JVType', dataField: 'JVType', width:'30%'},
                { text: 'Debit', dataField: 'Debit', width:'15%'},
                { text: 'Credit', dataField: 'Credit', width:'15%'},
                { text: 'Action', sortable: false, filterable: false, align: 'left', width:'10%',
                    cellsrenderer: function (row) {
                        var editLink = '<a title="Edit" href="#" onclick="billEdit('+row+'); return false;" style="padding-left: 15px;"><i class="fa fa-pencil-square-o reg-icon"></i></a>';
                        //return editLink += "&nbsp;&nbsp;" + '<button style="background: transparent;" title="Delete" onclick="billDelete('+row+'); return false;"><i class="fa fa-trash-o reg-icon"></i></button>';
                        return editLink;
                        //return editLink += "&nbsp;&nbsp;" + '<a title="Report" href="#" onclick="billReport('+row+'); return false;"><i class="fa fa-file-text-o reg-icon-file"></i></a>';
                    }
                }
            ]
        });
        $jqxGrid.on('celldoubleclick', function (event){//cellclick
            // event arguments.
            var args = event.args;
            // row's bound index.
            var rowBoundIndex = args.rowindex;
            var dataField = args.datafield;
            var data = $jqxGrid.jqxGrid("getrowdata", rowBoundIndex);
            var iJournalEntryId=data.JournalEntryId;
            if(iJournalEntryId!=0){
                window.location.replace(getBaseURL() + "fa/index/specialjournal/" + iJournalEntryId);
            }
        });
    }

    function billEdit(row) {
        var iJournalEntryId = $jqxGrid.jqxGrid('getCellValue', row, 'JournalEntryId');
        if(iJournalEntryId!=0){
            window.location.replace(getBaseURL() + "fa/index/specialjournal/" + iJournalEntryId);
        }
    }

    /*function billDelete(row) {
     if (confirm("Are you sure you want to delete this?")) {
     var rowData = $jqxGrid.jqxGrid('getrowdata', row);
     var FYearId = $jqxGrid.jqxGrid('getCellValue', row, 'FYearId');
     //console.log("delete");
     //console.log(FYearId);
     $.ajax({
     url: getBaseURL() + 'fa/index/fiscalyearregister',
     type: 'POST',
     data:"FYearId="+FYearId+"&mode=delete",
     success:function(data, textStatus, jqXHR){
     if (jqXHR.status == 200)
     $jqxGrid.jqxGrid("deleterow", rowData.uid);
     else
     alert('Cannot delete this Entry, it is already in use!');
     },
     error:function(jqXHR, textStatus, errorThrown){
     alert('Failed to delete the Entry!');
     }
     });
     } else {
     false;
     }
     }*/

</script>
