<style>
    #vendorServiceListWrapper {
        display: none;
    }
    .pagination-lg > li > a, .pagination-lg > li > span {
        font-size:15px !important;
        padding:5px 15px !important;
    }
    /* Excel Floating Icon */
    .fixed-action-btn          	    {position:fixed;top:85px;right:5px;padding-top:15px;margin-bottom:0;z-index:998;}
    .fixed-action-btn:hover ul li a.btn-floating{transform: scaleY(1) scaleX(1) translateX(0px);opacity: 1;}
    .btn-floating.btn-large         {width:45px;height:45px;}
    .fixed-action-btn ul 			{left:-142px;right:0;text-align:center;position:absolute;margin:0;top:22px;}
    .fixed-action-btn ul li 		{margin-left:8px;list-style-type:none;float:left;}
    .fixed-action-btn ul li a.btn-floating {transform: scaleY(0.4) scaleX(0.4) translateX(40px);opacity: 0;}
    .fixed-action-btn ul a.btn-floating i  {font-size: 17px;line-height: 37px;}
    .btn-floating                   {display:inline-block;color:#fff;position:relative;overflow:hidden;z-index:1;width:37px;height:37px;line-height:37px;padding: 0;
        background-color: #26a69a;border-radius:50%;cursor:pointer;vertical-align: middle;
        box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);text-decoration: none;transition: all .3s ease;
        -webkit-transition: all .3s ease; -moz-transition: all .3s ease; -o-transition: all .3s ease;}
    .btn-floating i                 {width: inherit;display: inline-block;text-align: center;color: #fff;font-size:20px;line-height: 45px; font-weight:normal; color:#fff;}
    .next-bt                        {text-align:center;}
    .next-bt a:hover                {border:1px solid #3580C4 !important; background:#fff !important; color:#3580C4 !important;}
    .next-bt a                      {background:#3580C4!important;border:1px solid #3580C4; border-radius: 4px;
        color:#fff!important; font-size:14px; padding: 5px 10px; text-align: center; transition: all 0.4s ease 0s;}
    .commargin_top 					{margin-top: 30px;}

    /* Excel Floating Icon end*/
    /*--------------Jqx Grid jqx All-------------------*/
	.jqx-widget .jqx-grid-column-header 	{border: 1px solid #c7c7c7 !important;}
	#jqxgrid								{min-height:200px !important;}
	#jqxgrid .jqx-grid-header 					{height:90px !important;}
	.jqx-grid-groups-row						{padding-left:5px !important;}
	.jqx-grid-pager-input						{padding: 2px; text-align: center !important; width: 35px;}
	.jqx-dropdownlist-state-normal				{display: block;  float: right;height: 16px !important;margin-right: 7px;margin-top: 0;  padding-bottom: 2px !important;padding-top: 2px !important; width: 40px;}
	.jqx-button									{cursor: pointer;float: right;margin-right: 3px !important;margin-top: 0 !important;padding: 0 !important;width: 20px !important;}
	.jqx-button > .jqx-icon-arrow-left,
	.jqx-button >.jqx-icon-arrow-right			{height: 21px !important;margin-left: 0 !important;width: 20px !important;}
	.jqx-listitem-element						{height: 25px !important;}
	.jqx-input									{height: 25px !important; margin:2px 4px !important;}
	.jqx-grid-pager .jqx-grid-pager-input		{height:20px !important; margin:0px 4px !important;}
	#jqxgrid .jqx-grid-cell-right-align 		{text-align:right !important; padding-right:8px;}
	#jqxgrid .jqx-grid-cell-left-align 			{padding-left:8px;}
	.jqx-grid-column-menubutton::after			{left:4px;top:10px;}

</style>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqxgrid.grouping.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqxgrid.aggregates.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqx-all.js"></script>
<div class="content_wrapper  padlr0">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 padlr0">
				<h1 class="col-lg-6 col-md-6 col-sm-6"> Purchasebill Deviation </h1>
				<div class="col-lg-6">
					<div class="fixed-action-btn active">
						<a class="btn-floating btn-large">
							<i class="fa fa-print"></i>
						</a>
						<ul>
							<li>
								<a class="btn-floating hide-input-file" id="print" href="javascript:void(0);" data-toggle="tooltip" data-placement="top" data-original-title="Print Report">
									<i class="fa fa-print"></i>

								</a>
							</li>
							<li>
								<a class="btn-floating" id="excelExport" href="javascript:void(0);" data-toggle="tooltip" data-placement="top" data-original-title="Download Excel">
									<i class="fa fa-download"></i>
								</a>
							</li>
							<li>
								<a class="btn-floating" id="csvExport" href="javascript:void(0);" data-toggle="tooltip" data-placement="top" data-original-title="Export CSV">
									<i class="fa fa-file-archive-o"></i>
								</a>
							</li>
						</ul>
					</div>
				</div>
            </div>
            <div class="col-lg-12 commargin_top">
                <div class="col-lg-4">
                    <select data-placeholder="Cost Centre" class="form-control multiple_dropdown lbl_move sortoption" multiple="multiple" tabindex="7" name="CostCentre[]" id="CostCentre">
                        <option value=""></option>
                        <?php if(isset($arr_costcenter)):
                            foreach($arr_costcenter as $costcenter): ?>
                                <option value="<?php echo $costcenter['CostCentreId'];?>"><?php echo $costcenter['CostCentreName'];?></option>
                            <?php endforeach;
                        endif; ?>
                    </select>
                </div>
            </div>
            <div class="col-lg-12 clear">
                <div class="table-responsive clear">
                    <div style='margin-top:10px;' id="jqxgrid"> </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-lg-12 savebtn_area">
    <ul>
        <li class="dropdown save_btn float_r">
            <a href="<?php echo $this->basePath();?>/mms/report/reportlist" class="ripple">Close</a>
        </li>
    </ul>
</div>
<script type="text/javascript">

    $(document).ready(function () {
        source = {
            localdata: [],
            datatype: "json",
            pagesize: 15,
            datafields:
                [
                    { name: "Code", type: "string" },
                    { name: "ResourceId", type: "string" },
                    { name: "Resource", type: "string" },
                    { name: "ResourceGroup", type: "string" },
                    { name: "Unit", type: "string" },
                    { name: "EstQty", type: "number" },
                    { name: "EstRate", type: "number" },
                    { name: "EstAmount", type: "number" },
                    { name: "PUQty", type: "number" },
                    { name: "PURate", type: "number" },
                    { name: "PUAmount", type: "number" },
                    { name: "PDQty", type: "number" },
                    { name: "PDRate", type: "number" },
                    { name: "PDAmount", type: "number" },
                    { name: "TQty", type: "number" },
                    { name: "TAmount", type: "number" },
                    { name: "BQty", type: "number" },
                    { name: "BAmount", type: "number" },
                    { name: "PurAmount", type: "number" },
                    { name: "DeviationAmt", type: "number" },
                    { name: "DeviationPer", type: "number" }
                ]
        };

        dataAdapter = new $.jqx.dataAdapter(source);
        $("#jqxgrid").jqxGrid(
            {
                width: "100%",
                source: dataAdapter,
                pageable: true,
                pagerMode: 'advanced',
                pagerHeight: 40,
                columnsresize: true,
                autoheight: true,
                rowsheight:40,
                sortable: true,
                altrows: true,
                enabletooltips: true,
                showfilterrow: true,
                filterable: true,
                groupable: true,
                showstatusbar: true,
                statusbarheight: 40,
                showAggregates: true,
                autorowheight: true,
                columns: [
                    { text: 'ResourceId', dataField: 'ResourceId',hidden:true },
                    { text: 'ResourceGroup', pinned: true, dataField: 'ResourceGroup', align: 'Left', width:"12%"},
                    { text: 'Code', pinned: true, dataField: 'Code', align: 'Left', width:"12%"},
                    { text: 'Resource', pinned: true, dataField: 'Resource', align: 'Left', width:"12%"},
                    { text: 'Unit',  pinned: true,dataField: 'Unit', align: 'Left',width:"12%"},
                    { text: 'Qty', columnGroup: 'Estimate', dataField: 'EstQty', align: 'Left', width:"12%"},
                    { text: 'Rate', columnGroup: 'Estimate', dataField: 'EstRate', align: 'Left', width:"12%"},
                    { text: 'Amount', columnGroup: 'Estimate', dataField: 'EstAmount', align: 'Left',width:"12%"},
                    { text: 'Qty', columnGroup: 'Purchase UpTo Previous Month', dataField: 'PUQty', align: 'Left', width:"12%"},
                    { text: 'Rate', columnGroup: 'Purchase UpTo Previous Month', dataField: 'PURate', align: 'Left', width:"12%"},
                    { text: 'Amount', columnGroup: 'Purchase UpTo Previous Month', dataField: 'PUAmount', align: 'Left', width:"12%"},
                    { text: 'Qty', columnGroup: 'Purchase During This Month', dataField: 'PDQty', align: 'Left', width:"12%"},
                    { text: 'Rate', columnGroup: 'Purchase During This Month', dataField: 'PDRate', align: 'Left', width:"12%"},
                    { text: 'Amount', columnGroup: 'Purchase During This Month', dataField: 'PDAmount', align: 'Left', width:"12%"},
                    { text: 'Qty', columnGroup: 'Total Purchase', dataField: 'TQty', align: 'Left', width:"12%"},
                    { text: 'Amount', columnGroup: 'Total Purchase', dataField: 'TAmount', align: 'Left', width:"12%"},
                    { text: 'Qty', columnGroup: 'Balance Purchase', dataField: 'BQty', align: 'Left', width:"12%"},
                    { text: 'Amount', columnGroup: 'Balance Purchase', dataField: 'BAmount', align: 'Left', width:"12%"},
                    { text: 'Amount', columnGroup: 'Purchase Amount As Per Estimate Rate', dataField: 'PurAmount', align: 'left', width:"25%"},
                    { text: 'Amount', columnGroup: 'Deviation', dataField: 'DeviationAmt', align: 'Left', width:"12%"},
                    { text: 'Per(%)', columnGroup: 'Deviation', dataField: 'DeviationPer', align: 'Left', width:"12%"}
                ],
                columngroups: [
                    { text: 'general', align: 'center', name: 'general'},
                    { text: 'Estimate', align: 'center', name: 'Estimate' },
                    { text: 'Purchase UpTo Previous Month', align: 'center', name: 'Purchase UpTo Previous Month' },
                    { text: 'Purchase During This Month', align: 'center', name: 'Purchase During This Month' },
                    { text: 'Total Purchase', align: 'center', name: 'Total Purchase' },
                    { text: 'Balance Purchase', align: 'center', name: 'Balance Purchase' },
                    { text: 'Purchase Amount As Per Estimate Rate', align: 'center', name: 'Purchase Amount As Per Estimate Rate' },
                    { text: 'Deviation', align: 'center', name: 'Deviation' }
                ]
            });
        $("#jqxgrid").jqxGrid('showgroupsheader', false);
        //Print option
        $("#excelExport").click(function () {
            $("#jqxgrid").jqxGrid('exportdata', 'xls', 'jqxGrid');
        });
        $("#csvExport").click(function () {
            $("#jqxgrid").jqxGrid('exportdata', 'csv', 'jqxGrid');
        });
        $("#htmlExport").click(function () {
            $("#jqxgrid").jqxGrid('exportdata', 'html', 'jqxGrid');
        });

        $("#print").click(function () {
            var gridContent = $("#jqxgrid").jqxGrid('exportdata', 'html');
            //var gridContent = $("#jqxgrid").jqxGrid('exportdata', 'html', 'jqxGrid', true, null, false);
            var newWindow = window.open('', '', 'width=800, height=500'),
                document = newWindow.document.open(),
                pageContent =
                    '<!DOCTYPE html>\n' +
                    '<html>\n' +
                    '<head>\n' +
                    '<meta charset="utf-8" />\n' +
                    '<title> PurchaseBill Deviation </title>\n' +
                    '<h1> PurchaseBill Deviation </h1>\n' +
                    '</head>\n' +
                    '<body>\n' + gridContent + '\n</body>\n</html>';
            document.write(pageContent);
            document.close();
            newWindow.print();

            /*$("#jqxgrid").jqxGrid('exportdata', 'html', 'jqxGrid', true, null, false);*/
        });

        $("#jqxgrid").bind('rowselect', function (event) {
            var row = event.args.rowindex;
            var datarow = $("#jqxgrid").jqxGrid('getrowdata', row);

        });
        //bindJqxGridAutoResize();
    });
    $(document).ready(function() {
        $(".multiple_dropdown").select2({
        });
    });

    $('#CostCentre').on('change',function(){
        bindRequests();
    });


    function bindRequests() {
        var costCentreId = $('#CostCentre').val();
        $.ajax({
            url:getBaseURL()+'mms/purchasebillreport/purchasebill-deviation',
            type:"post",
            data:"CostCentreId="+costCentreId+"&Type=cost",
            dataType:"json",
            success:function(data, textStatus, jqXHR){
                if(jqXHR.status == 200) {
                    renderRequestResources(data);
                }
            }
        });
    }
    function renderRequestResources(data) {
        source.localdata = data;
        dataAdapter.dataBind();
    }

</script>