<?php $bsf = new \BuildsuperfastClass(); 
if(isset($feedResult) && count($feedResult) > 0) {
	foreach($feedResult as $feeds) {
		if($feeds['UserAvatar'] != '' && $feeds['UserAvatar'] != Null) {
			$feedAvatar = $this->basePath()."/".$feeds['UserAvatar'];
		} else {
			$feedAvatar = $this->basePath()."/images/avatar.jpg";
		}
		if($feeds['FeedType'] == 'status') { 
			?>
			<li>
				<div class="strm_pstr_pp">
					<div><img src="<?php echo $feedAvatar; ?>" alt="" title=""></div>
				</div>
				<div id="strm_news_<?php echo $feeds['FeedId'];?>" class="strm_news">
					<div class="strm_news_cnt">
						<div class="m_strm_pstr_pp">
							<div><img src="<?php echo $feedAvatar; ?>" alt="" title=""></div>
						</div>
						<h4><span><?php if($feeds['UserId'] == $this->identity()->UserId) { echo 'You'; } else { echo $feeds['UserName']; } ?></span> shared a status</h4>
						<ul class="tmplc_summary">
							<li><span><i class="fa fa-clock-o"></i></span><?php  echo $bsf::timeAgo($feeds['CreatedDate']); ?></li>
							<li><span><i class="fa fa-map-marker"></i></span><?php echo $feeds['Location']; ?></li>
						</ul>
						<p><?php echo nl2br($feeds['Message']); ?></p>
						<ul class="lkcmt_btn">
							<li><a href="javascript:void(0);" id="like_<?php echo $feeds['FeedId']; ?>" class="like_hover" data-placement="right" data-toggle="tooltip" data-html="true" data-original-title="" onclick="likeFunc('<?php echo $feeds['FeedId']; ?>','<?php echo $this->identity()->UserId; ?>','<?php echo $feeds['UserLike']; ?>');"><span><i class="fa fa-thumbs-o-up"></i></span><span id="like_name_<?php echo $feeds['FeedId']; ?>"><?php if($feeds['UserLike'] == '1') { echo 'You Likes'; } else { echo 'Like'; } ?></span><span id="like_count_<?php echo $feeds['FeedId']; ?>">(<?php echo $feeds['FeedLikesCount']; ?>)</span></a></li>
							<li><a href="javascript:void(0);" id="comment" class="comment_a" onclick="commentClick('<?php echo $feeds['FeedId']; ?>');"><span><i class="fa fa-comments-o"></i></span>Comment&nbsp;<span id="comment_count_<?php echo $feeds['FeedId']; ?>">(<?php echo $feeds['FeedCommentsCount']; ?>)</span></a></li>
							<li><a href="javascript:void(0);"><span><i class="fa fa-share-alt"></i></span>Share</a></li>
						</ul>
					</div>
					<div id="strm_cnt_cmt_<?php echo $feeds['FeedId']; ?>" class="strm_cnt_cmt">
						<span class="v_morecmt"><!--a href="javascript:void(0);">View more comments</a--></span>
						<ul id="commentli_<?php echo $feeds['FeedId']; ?>">

						</ul>
						<div class="cmtinput_area">
							<div class="cmtinput_box">
								<input id="comment_text_<?php echo $feeds['FeedId']; ?>" type="text" Placeholder="Write your comments here..."/>
							</div>
							<a href="javascript:void(0);" class="cmtsend_btn_a">
								<div onclick="commentPost('<?php echo $feeds['FeedId']; ?>','<?php echo $this->identity()->UserId; ?>');" class="cmtsend_btn">
									<span><i class="fa fa-share"></i></span>
								</div>
							</a>
						</div>
					</div>
				</div>
			</li>
		<?php } else if($feeds['FeedType'] == 'birthday') { ?>
			<li>
				<div class="strm_pstr_pp">
					<div><img src="<?php echo $feedAvatar; ?>" alt="" title=""></div>
				</div>
				<div id="strm_news_<?php echo $feeds['FeedId'];?>" class="strm_news">
					<div class="strm_news_cnt">
						<div class="m_strm_pstr_pp">
							<div><img src="<?php echo $feedAvatar; ?>" alt="" title=""></div>
						</div>
						<h4><span><?php if($feeds['UserId'] == $this->identity()->UserId) { echo 'You'; } else { echo $feeds['UserName']; } ?></span> posted on <?php if($userDetails['UserId'] == $this->identity()->UserId) { echo 'your'; } else { echo $userDetails['EmployeeName']."'s"; } ?> timeline</h4>
						<ul class="tmplc_summary">
							<li><span><i class="fa fa-clock-o"></i></span><?php  echo $bsf::timeAgo($feeds['CreatedDate']); ?></li>
							<li><span><i class="fa fa-map-marker"></i></span><?php echo $feeds['Location']; ?></li>
						</ul>
						<p><?php echo nl2br($feeds['BdayWish']); ?></p>
						<ul class="lkcmt_btn">
							<li><a href="javascript:void(0);" id="like_<?php echo $feeds['FeedId']; ?>" class="like_hover" data-placement="right" data-toggle="tooltip" data-html="true" data-original-title="" onclick="likeFunc('<?php echo $feeds['FeedId']; ?>','<?php echo $this->identity()->UserId; ?>','<?php echo $feeds['UserLike']; ?>');"><span><i class="fa fa-thumbs-o-up"></i></span><span id="like_name_<?php echo $feeds['FeedId']; ?>"><?php if($feeds['UserLike'] == '1') { echo 'You Likes'; } else { echo 'Like'; } ?></span><span id="like_count_<?php echo $feeds['FeedId']; ?>">(<?php echo $feeds['FeedLikesCount']; ?>)</span></a></li>
							<li><a href="javascript:void(0);" id="comment" class="comment_a" onclick="commentClick('<?php echo $feeds['FeedId']; ?>');"><span><i class="fa fa-comments-o"></i></span>Comment&nbsp;<span id="comment_count_<?php echo $feeds['FeedId']; ?>">(<?php echo $feeds['FeedCommentsCount']; ?>)</span></a></li>
							<li><a href="javascript:void(0);"><span><i class="fa fa-share-alt"></i></span>Share</a></li>
						</ul>
					</div>
					<div id="strm_cnt_cmt_<?php echo $feeds['FeedId']; ?>" class="strm_cnt_cmt">
						<span class="v_morecmt"><!--a href="javascript:void(0);">View more comments</a--></span>
						<ul id="commentli_<?php echo $feeds['FeedId']; ?>">

						</ul>
						<div class="cmtinput_area">
							<div class="cmtinput_box">
								<input id="comment_text_<?php echo $feeds['FeedId']; ?>" type="text" Placeholder="Write your comments here..."/>
							</div>
							<a href="javascript:void(0);" class="cmtsend_btn_a">
								<div onclick="commentPost('<?php echo $feeds['FeedId']; ?>','<?php echo $this->identity()->UserId; ?>');" class="cmtsend_btn">
									<span><i class="fa fa-share"></i></span>
								</div>
							</a>
						</div>
					</div>
				</div>
			</li>
		<?php } else if($feeds['FeedType'] == 'photo') { 
			$photoShareDetails = $this->BsfShareHelper()->getMultiImage($feeds['PhotoShareId']);?>
			<li>
				<div class="strm_pstr_pp">
					<div><img src="<?php echo $feedAvatar; ?>" alt="" title=""></div>
				</div>
				<div id="strm_news_<?php echo $feeds['FeedId'];?>" class="strm_news">
					<div class="strm_news_cnt">
						<div class="m_strm_pstr_pp">
							<div><img src="<?php echo $feedAvatar; ?>" alt="" title=""></div>
						</div>
						<h4><span><?php if($feeds['UserId'] == $this->identity()->UserId) { echo 'You'; } else { echo $feeds['UserName']; } ?></span> shared (<?php echo count($photoShareDetails); ?>) new photos</h4>
						<ul class="tmplc_summary">
							<li><span><i class="fa fa-clock-o"></i></span><?php  echo $bsf::timeAgo($feeds['CreatedDate']); ?></li>
							<li><span><i class="fa fa-map-marker"></i></span><?php echo $feeds['Location']; ?></li>
						</ul>
						<p><?php echo nl2br($feeds['PhotoMessage']); ?></p>
						<section class="post_photos clear">
							<section class="lightGallery">
								<?php if (isset($photoShareDetails)) {
										$count=1;
										foreach ($photoShareDetails as $dispMatch) {
											if($count<4){?>
												<a href="javascript:void(0);" data-src="<?php echo $this->basePath(); ?>/<?php echo $dispMatch['ImageUrl']; ?>"><img src="<?php echo $this->basePath(); ?>/<?php echo $dispMatch['ImageUrl']; ?>"/></a>
										<?php } else { ?>
												<a href="javascript:void(0);" style="display:none;" data-src="<?php echo $this->basePath(); ?>/<?php echo $dispMatch['ImageUrl']; ?>"><img src="<?php echo $this->basePath(); ?>/<?php echo $dispMatch['ImageUrl']; ?>"/></a>
											<?php  }
											$count++;
										}
								} ?>
							</section>
							<?php if($count>4) { ?>
								<a class="more_photos_a"><span><i class="fa fa-picture-o" aria-hidden="true"></i></span> <?php echo $count=$count-4; ?> more photos</a>
							<?php } ?>
						</section>
						<ul class="lkcmt_btn">
							<li><a href="javascript:void(0);" id="like_<?php echo $feeds['FeedId']; ?>" class="like_hover" data-placement="right" data-toggle="tooltip" data-html="true" data-original-title="" onclick="likeFunc('<?php echo $feeds['FeedId']; ?>','<?php echo $this->identity()->UserId; ?>','<?php echo $feeds['UserLike']; ?>');"><span><i class="fa fa-thumbs-o-up"></i></span><span id="like_name_<?php echo $feeds['FeedId']; ?>"><?php if($feeds['UserLike'] == '1') { echo 'You Likes'; } else { echo 'Like'; } ?></span><span id="like_count_<?php echo $feeds['FeedId']; ?>">(<?php echo $feeds['FeedLikesCount']; ?>)</span></a></li>
							<li><a href="javascript:void(0);" id="comment" class="comment_a" onclick="commentClick('<?php echo $feeds['FeedId']; ?>');"><span><i class="fa fa-comments-o"></i></span>Comment&nbsp;<span id="comment_count_<?php echo $feeds['FeedId']; ?>">(<?php echo $feeds['FeedCommentsCount']; ?>)</span></a></li>
							<li><a href="javascript:void(0);"><span><i class="fa fa-share-alt"></i></span>Share</a></li>
						</ul>
					</div>
					<div id="strm_cnt_cmt_<?php echo $feeds['FeedId']; ?>" class="strm_cnt_cmt">
						<span class="v_morecmt"><!--a href="javascript:void(0);">View more comments</a--></span>
						<ul id="commentli_<?php echo $feeds['FeedId']; ?>">

						</ul>
						<div class="cmtinput_area">
							<div class="cmtinput_box">
								<input id="comment_text_<?php echo $feeds['FeedId']; ?>" type="text" Placeholder="Write your comments here..."/>
							</div>
							<a href="javascript:void(0);" class="cmtsend_btn_a">
								<div onclick="commentPost('<?php echo $feeds['FeedId']; ?>','<?php echo $this->identity()->UserId; ?>');" class="cmtsend_btn">
									<span><i class="fa fa-share"></i></span>
								</div>
							</a>
						</div>
					</div>
				</div>
			</li>
		<?php } else if($feeds['FeedType'] == 'ask') { ?>
			<li>
				<div class="strm_pstr_pp">
					<div><img src="<?php echo $feedAvatar; ?>" alt="" title=""></div>
				</div>
				<div id="strm_news_<?php echo $feeds['FeedId'];?>" class="strm_news">
					<div class="strm_news_cnt">
						<div class="m_strm_pstr_pp">
							<div><img src="<?php echo $feedAvatar; ?>" alt="" title=""></div>
						</div>
						<h4>
							<span><?php if($feeds['UserId'] == $this->identity()->UserId) { echo 'You'; } else { echo $feeds['UserName']; } ?></span> asks you to/for <?php echo $feeds['AskFor']; ?> - 
							<a href="<?php echo (isset($feeds['AskUrl'])) ? $feeds['AskUrl'].'?AskId='.$feeds['AskId'].'&FeedId='.$feeds['FeedId'].'&type=ask' : '';?>"><?php echo (isset($feeds['AskTitle'])) ? $feeds['AskTitle'] : '';?></a>
						</h4>
						<ul class="tmplc_summary">
							<li><span><i class="fa fa-clock-o"></i></span><?php  echo $bsf::timeAgo($feeds['CreatedDate']); ?></li>
							<li><span><i class="fa fa-map-marker"></i></span><?php echo $feeds['Location']; ?></li>
						</ul>
						<p><?php echo nl2br($feeds['AskMessage']); ?></p>
						<ul class="lkcmt_btn">
							<li><a href="javascript:void(0);" id="like_<?php echo $feeds['FeedId']; ?>" class="like_hover" data-placement="right" data-toggle="tooltip" data-html="true" data-original-title="" onclick="likeFunc('<?php echo $feeds['FeedId']; ?>','<?php echo $this->identity()->UserId; ?>','<?php echo $feeds['UserLike']; ?>');"><span><i class="fa fa-thumbs-o-up"></i></span><span id="like_name_<?php echo $feeds['FeedId']; ?>"><?php if($feeds['UserLike'] == '1') { echo 'You Likes'; } else { echo 'Like'; } ?></span><span id="like_count_<?php echo $feeds['FeedId']; ?>">(<?php echo $feeds['FeedLikesCount']; ?>)</span></a></li>
							<li><a href="javascript:void(0);" id="comment" class="comment_a" onclick="commentClick('<?php echo $feeds['FeedId']; ?>');"><span><i class="fa fa-comments-o"></i></span>Comment&nbsp;<span id="comment_count_<?php echo $feeds['FeedId']; ?>">(<?php echo $feeds['FeedCommentsCount']; ?>)</span></a></li>
							<?php  if($feeds['AskFor']=='Information'){ ?>
								<li><a href="javascript:void(0);" onclick="showrespond();"><span><i class="fa fa-share-alt"></i></span>Respond</a></li>
							<?php } else { ?>
								<li><a href="<?php echo (isset($feeds['AskUrl'])) ? $feeds['AskUrl'].'?AskId='.$feeds['AskId'].'&FeedId='.$feeds['FeedId'].'&type=ask' : '';?>"><span><i class="fa fa-share-alt"></i></span>Respond</a></li>
							<?php } ?>
						</ul>
					</div>
					<div id="strm_cnt_cmt_<?php echo $feeds['FeedId']; ?>" class="strm_cnt_cmt">
						<span class="v_morecmt"><!--a href="javascript:void(0);">View more comments</a--></span>
						<ul id="commentli_<?php echo $feeds['FeedId']; ?>">

						</ul>
						<div class="cmtinput_area">
							<div class="cmtinput_box">
								<input id="comment_text_<?php echo $feeds['FeedId']; ?>" type="text" Placeholder="Write your comments here..."/>
							</div>
							<a href="javascript:void(0);" class="cmtsend_btn_a">
								<div onclick="commentPost('<?php echo $feeds['FeedId']; ?>','<?php echo $this->identity()->UserId; ?>');" class="cmtsend_btn">
									<span><i class="fa fa-share"></i></span>
								</div>
							</a>
						</div>
					</div>
				</div>
			</li>
		<?php } else if($feeds['FeedType'] == 'response') { ?>
			<li>
				<div class="strm_pstr_pp">
					<div><img src="<?php echo $feedAvatar; ?>" alt="" title=""></div>
				</div>
				<div id="strm_news_<?php echo $feeds['FeedId'];?>" class="strm_news">
					<div class="strm_news_cnt">
						<div class="m_strm_pstr_pp">
							<div><img src="<?php echo $feedAvatar; ?>" alt="" title=""></div>
						</div>
						<h4>
							<span><?php if($feeds['UserId'] == $this->identity()->UserId) { echo 'You'; } else { echo $feeds['UserName']; } ?></span> responded to <?php echo $feeds['AskToName']; ?>'s query on - <?php echo (isset($feeds['AskTitle'])) ? $feeds['AskTitle'] : '';?>
						</h4>
						<ul class="tmplc_summary">
							<li><span><i class="fa fa-clock-o"></i></span><?php  echo $bsf::timeAgo($feeds['CreatedDate']); ?></li>
							<li><span><i class="fa fa-map-marker"></i></span><?php echo $feeds['Location']; ?></li>
						</ul>
						<p><?php echo nl2br($feeds['RespondMessage']); ?></p>
						<ul class="lkcmt_btn">
							<li><a href="javascript:void(0);" id="like_<?php echo $feeds['FeedId']; ?>" class="like_hover" data-placement="right" data-toggle="tooltip" data-html="true" data-original-title="" onclick="likeFunc('<?php echo $feeds['FeedId']; ?>','<?php echo $this->identity()->UserId; ?>','<?php echo $feeds['UserLike']; ?>');"><span><i class="fa fa-thumbs-o-up"></i></span><span id="like_name_<?php echo $feeds['FeedId']; ?>"><?php if($feeds['UserLike'] == '1') { echo 'You Likes'; } else { echo 'Like'; } ?></span><span id="like_count_<?php echo $feeds['FeedId']; ?>">(<?php echo $feeds['FeedLikesCount']; ?>)</span></a></li>
							<li><a href="javascript:void(0);" id="comment" class="comment_a" onclick="commentClick('<?php echo $feeds['FeedId']; ?>');"><span><i class="fa fa-comments-o"></i></span>Comment&nbsp;<span id="comment_count_<?php echo $feeds['FeedId']; ?>">(<?php echo $feeds['FeedCommentsCount']; ?>)</span></a></li>
						</ul>
					</div>
					<div id="strm_cnt_cmt_<?php echo $feeds['FeedId']; ?>" class="strm_cnt_cmt">
						<span class="v_morecmt"><!--a href="javascript:void(0);">View more comments</a--></span>
						<ul id="commentli_<?php echo $feeds['FeedId']; ?>">

						</ul>
						<div class="cmtinput_area">
							<div class="cmtinput_box">
								<input id="comment_text_<?php echo $feeds['FeedId']; ?>" type="text" Placeholder="Write your comments here..."/>
							</div>
							<a href="javascript:void(0);" class="cmtsend_btn_a">
								<div onclick="commentPost('<?php echo $feeds['FeedId']; ?>','<?php echo $this->identity()->UserId; ?>');" class="cmtsend_btn">
									<span><i class="fa fa-share"></i></span>
								</div>
							</a>
						</div>
					</div>
				</div>
			</li>
		<?php } else if($feeds['FeedType'] == 'reminder') { ?>
			<li>
				<div class="strm_pstr_pp">
					<div><img src="<?php echo $feedAvatar; ?>" alt="" title=""></div>
				</div>
				<div id="strm_news_<?php echo $feeds['FeedId'];?>" class="strm_news">
					<div class="strm_news_cnt">
						<div class="m_strm_pstr_pp">
							<div><img src="<?php echo $feedAvatar; ?>" alt="" title=""></div>
						</div>
						<h4>
							<span><?php if($feeds['UserId'] == $this->identity()->UserId) { echo 'You'; } else { echo $feeds['UserName']; } ?></span> reminds you to/for <?php echo $feeds['AskFor']; ?> - <?php echo (isset($feeds['AskTitle'])) ? $feeds['AskTitle'] : '';?>
						</h4>
						<ul class="tmplc_summary">
							<li><span><i class="fa fa-clock-o"></i></span><?php  echo $bsf::timeAgo($feeds['CreatedDate']); ?></li>
							<li><span><i class="fa fa-map-marker"></i></span><?php echo $feeds['Location']; ?></li>
						</ul>
						<p><?php echo nl2br($feeds['RemindMessage']); ?></p>
						<ul class="lkcmt_btn">
							<li><a href="javascript:void(0);" id="like_<?php echo $feeds['FeedId']; ?>" class="like_hover" data-placement="right" data-toggle="tooltip" data-html="true" data-original-title="" onclick="likeFunc('<?php echo $feeds['FeedId']; ?>','<?php echo $this->identity()->UserId; ?>','<?php echo $feeds['UserLike']; ?>');"><span><i class="fa fa-thumbs-o-up"></i></span><span id="like_name_<?php echo $feeds['FeedId']; ?>"><?php if($feeds['UserLike'] == '1') { echo 'You Likes'; } else { echo 'Like'; } ?></span><span id="like_count_<?php echo $feeds['FeedId']; ?>">(<?php echo $feeds['FeedLikesCount']; ?>)</span></a></li>
							<li><a href="javascript:void(0);" id="comment" class="comment_a" onclick="commentClick('<?php echo $feeds['FeedId']; ?>');"><span><i class="fa fa-comments-o"></i></span>Comment&nbsp;<span id="comment_count_<?php echo $feeds['FeedId']; ?>">(<?php echo $feeds['FeedCommentsCount']; ?>)</span></a></li>
						</ul>
					</div>
					<div id="strm_cnt_cmt_<?php echo $feeds['FeedId']; ?>" class="strm_cnt_cmt">
						<span class="v_morecmt"><!--a href="javascript:void(0);">View more comments</a--></span>
						<ul id="commentli_<?php echo $feeds['FeedId']; ?>">

						</ul>
						<div class="cmtinput_area">
							<div class="cmtinput_box">
								<input id="comment_text_<?php echo $feeds['FeedId']; ?>" type="text" Placeholder="Write your comments here..."/>
							</div>
							<a href="javascript:void(0);" class="cmtsend_btn_a">
								<div onclick="commentPost('<?php echo $feeds['FeedId']; ?>','<?php echo $this->identity()->UserId; ?>');" class="cmtsend_btn">
									<span><i class="fa fa-share"></i></span>
								</div>
							</a>
						</div>
					</div>
				</div>
			</li>
		<?php } else if($feeds['FeedType'] == 'share') { ?>
			<li>
				<div class="strm_pstr_pp">
					<div><img src="<?php echo $feedAvatar; ?>" alt="" title=""></div>
				</div>
				<div id="strm_news_<?php echo $feeds['FeedId'];?>" class="strm_news">
					<div class="strm_news_cnt">
						<div class="m_strm_pstr_pp">
							<div><img src="<?php echo $feedAvatar; ?>" alt="" title=""></div>
						</div>
						<h4>
							<span><?php if($feeds['UserId'] == $this->identity()->UserId) { echo 'You'; } else { echo $feeds['UserName']; } ?></span> shared you a info - 
							<a href="<?php echo (isset($feeds['ShareUrl'])) ? $feeds['ShareUrl'].'?ShareId='.$feeds['ShareId'].'&FeedId='.$feeds['FeedId'].'&type=share' : '';?>"><?php echo (isset($feeds['ShareTitle'])) ? $feeds['ShareTitle'] : '';?></a>
						</h4>
						<ul class="tmplc_summary">
							<li><span><i class="fa fa-clock-o"></i></span><?php  echo $bsf::timeAgo($feeds['CreatedDate']); ?></li>
							<li><span><i class="fa fa-map-marker"></i></span><?php echo $feeds['Location']; ?></li>
						</ul>
						<p><?php echo nl2br($feeds['ShareMessage']); ?></p>
						<ul class="lkcmt_btn">
							<li><a href="javascript:void(0);" id="like_<?php echo $feeds['FeedId']; ?>" class="like_hover" data-placement="right" data-toggle="tooltip" data-html="true" data-original-title="" onclick="likeFunc('<?php echo $feeds['FeedId']; ?>','<?php echo $this->identity()->UserId; ?>','<?php echo $feeds['UserLike']; ?>');"><span><i class="fa fa-thumbs-o-up"></i></span><span id="like_name_<?php echo $feeds['FeedId']; ?>"><?php if($feeds['UserLike'] == '1') { echo 'You Likes'; } else { echo 'Like'; } ?></span><span id="like_count_<?php echo $feeds['FeedId']; ?>">(<?php echo $feeds['FeedLikesCount']; ?>)</span></a></li>
							<li><a href="javascript:void(0);" id="comment" class="comment_a" onclick="commentClick('<?php echo $feeds['FeedId']; ?>');"><span><i class="fa fa-comments-o"></i></span>Comment&nbsp;<span id="comment_count_<?php echo $feeds['FeedId']; ?>">(<?php echo $feeds['FeedCommentsCount']; ?>)</span></a></li>
							<li><a href="<?php echo (isset($feeds['ShareUrl'])) ? $feeds['ShareUrl'].'?ShareId='.$feeds['ShareId'].'&FeedId='.$feeds['FeedId'].'&type=share' : '';?>"><span><i class="fa fa-share-alt"></i></span>Respond</a></li>
						</ul>
					</div>
					<div id="strm_cnt_cmt_<?php echo $feeds['FeedId']; ?>" class="strm_cnt_cmt">
						<span class="v_morecmt"><!--a href="javascript:void(0);">View more comments</a--></span>
						<ul id="commentli_<?php echo $feeds['FeedId']; ?>">

						</ul>
						<div class="cmtinput_area">
							<div class="cmtinput_box">
								<input id="comment_text_<?php echo $feeds['FeedId']; ?>" type="text" Placeholder="Write your comments here..."/>
							</div>
							<a href="javascript:void(0);" class="cmtsend_btn_a">
								<div onclick="commentPost('<?php echo $feeds['FeedId']; ?>','<?php echo $this->identity()->UserId; ?>');" class="cmtsend_btn">
									<span><i class="fa fa-share"></i></span>
								</div>
							</a>
						</div>
					</div>
				</div>
			</li>
		<?php } else if($feeds['FeedType'] == 'approval') { ?>
			<li>
				<div class="strm_pstr_pp">
					<div><img src="<?php echo $feedAvatar; ?>" alt="" title=""></div>
				</div>
				<div id="strm_news_<?php echo $feeds['FeedId'];?>" class="strm_news">
					<div class="strm_news_cnt">
						<div class="m_strm_pstr_pp">
							<div><img src="<?php echo $feedAvatar; ?>" alt="" title=""></div>
						</div>
						<h4><span><?php echo $feeds['UserName']; ?></span></h4>
						<ul class="tmplc_summary">
							<li><span><i class="fa fa-clock-o"></i></span><?php  echo $bsf::timeAgo($feeds['CreatedDate']); ?></li>
							<li><span><i class="fa fa-map-marker"></i></span><?php echo $feeds['Location']; ?></li>
						</ul>
						<h5><?php echo $feeds['FeedParentCount']; ?> New Approvals  Remaining in this time period</h5>
						<ul class="strm_appro">
							<?php if($feeds['FeedParentCount'] > 0) {
								echo $this->BsfShareHelper()->getPendingWorks($feeds['FeedId']);
							} ?>
						</ul>
					</div>
			 </div>
			</li>
		<?php }
	}
}
?>
<script>
	$(".lightGallery").lightGallery({
        loop : true
    });
</script>