<img src="<?php echo $this->basePath(); ?>/images/bsflogo.jpg" class="login_logo" alt="" title="BuildSuperFast">
<div class="login_area brad_2">
    <h1>Forget Password ??</h1>
    <form id="loginForm" method="post">
        <ul class="login_form">
            <li class="login_input">
                <span class="label_icon"><label for="username"><span><i class="fa fa-envelope-o"></i></span></label></span>
                <input type="text" id="username" name="userName" value="" placeholder="Email"/>
            </li>
            <li>
                <div class="login_load brad_2"><p><img src="<?php echo $this->basePath(); ?>/images/loading.gif" alt="" />Loading... &nbsp;&nbsp;&nbsp;Please Wait!</p></div>
                <button type="button" onClick="return validateLogin();" name="submit" class="signin_btn brad_2" value=""><span><img src="<?php echo $this->basePath(); ?>/images/signin_key.png" class="signin_key" alt="" title="Sign in"></span></button>
            </li>
        </ul>
    </form>
</div>
<script>
    function validateLogin() {
        var userName = $('#username'),
            passWord = $('#password');
        userName.removeClass('red_bdr');
        removeLoginError(userName);
        var emailVal = $.trim(userName.val());
        if(emailVal=="") {
            userName.addClass('red_bdr');
            showLoginError(userName,"Email is Empty");
            return false;
        }
        var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
        if(!regex.test(emailVal)) {
            userName.addClass('red_bdr');
            showLoginError(userName,"Email is Invalid");
            return false;
        }
        $('.login_load').show().addClass('animated_1_5s flipInX');
        $('.signin_btn').hide();
        $('.login_input,.keepme_log,.keepme_area,.forgetpwd_p').css('opacity','0.3');

        $.ajax({
            url:getBaseURL()+'application/index/forgetpassword',
            type:'POST',
            data:{email : emailVal },
            success:function(data, textStatus, jqXHR){
                if (jqXHR.status != 200) {
                    alert('Your Password reset request process Failed !!!');
                    return false;
                }
                else
                {
                    if(data=='success') {
                        alert('Your Password reset link send to your email successfully !!');
                        $(location).attr('href', "<?php echo $this->basePath(); ?>/application/index/index");
                    } else {
                        $('.login_load').hide().removeClass('animated_1_5s flipInX');
                        $('.signin_btn').show();
                        $('.login_input,.keepme_log,.keepme_area,.forgetpwd_p').css('opacity','1');
                        userName.addClass('red_bdr');
                        showLoginError(userName,"Email is Invalid");
                    }

                }
            },
            error:function(jqXHR, textStatus, errorThrown){
                alert('Your Password reset request process Failed !!!!');
                $('.login_load').hide().removeClass('animated_1_5s flipInX');
                $('.signin_btn').show();
                $('.login_input,.keepme_log,.keepme_area,.forgetpwd_p').css('opacity','1');

            }
        });
    }
    function showLoginError($input, msg) {
        $input.closest('li').addClass('error').attr('data-original-title', msg).attr('data-toggle', 'tooltip');
        $input.closest('li').tooltip('show');
    }
    function removeLoginError($input) {
        if (typeof $input.attr('data-toggle') !== 'undefined') {
            $input.closest('li').tooltip('destroy');
        }
        $input.closest('li').removeClass('error').removeAttr('data-original-title').removeAttr('data-toggle');
    }
</script>