<script src="http://www.amcharts.com/lib/3/amcharts.js"></script>
<script src="http://www.amcharts.com/lib/3/serial.js"></script>
<script src="http://www.amcharts.com/lib/3/themes/light.js"></script>
<style>
.tiles.green {
    background-color: #0aa699;
}
.tiles {
    background-color: #bcbcbc;
    color: #ffffff;
    position: relative;
}

.tiles .tiles-body {
    padding: 6px 18px 15px 18px;
}
.widget-stats {
    padding-left: 0;
}
.widget-stats .wrapper.transparent {
    border-right: 1px solid rgba(0, 0, 0, 0.2);
}
.widget-stats .wrapper {
    border-right: 1px solid #363a41;
    margin: 5px 7px 5px 0;
    padding-left: 18px;
    padding-right: 5px;
}
.widget-stats .item-title {
    font-size: 15px;
}
.widget-stats .item-count {
    color: #ffffff;
    font-size: 15px;
    font-weight: bold;
}
.semi-bold {
    font-weight: 600;
}
.tiles > .tiles-body > .description {
    color: #ffffff;
    display: table-cell;
    font-size: 12px;
    vertical-align: middle;
}
.tiles .description .mini-description {
    position: relative;
    top: -5px;
}
.text-white {
    color: #ffffff !important;
}
.cards .blend {
    color: #000;
}
.cards.purple {
    background-color: #896897;
}
.cards.blue {
    background-color: #32c5d2;
}
.portlet{border: 1px solid #D3D3D3 !important;background-color: #e2ebef;
    padding: 12px 0px 0px;}
.aboveportlet{border: 1px solid #e7ecf1 !important;background-color: #bedbda;
    padding: 12px;}	
.portlet-title {
    margin-bottom: 10px;
}	
.simplebarchartdiv {
	width		: 100%;
	height		: 350px;
	font-size	: 11px;
}					
#linechartdiv {
	width	: 100%;
	height	: 500px;
	background:#fff !important;}
	
	
	
	

@import "http://fonts.googleapis.com/css?family=Ubuntu+Mono|Roboto:400,100,300,500,700,300italic|Roboto+Condensed:300,400,700|Roboto+Slab:400,700&subset=latin,latin-ext";

.card-container .card {
    cursor: pointer;
    height: 100%;
    perspective: 600px;
    position: relative;
    width: 100%;
    z-index: 9;
}
.card-container .card .front {
    backface-visibility: hidden;
    background-color: #f2f2f2;
    box-shadow: 0 3px 0 rgba(0, 0, 0, 0.05);
    height: 100%;
    left: 0;
    min-height: 115px;
    padding: 4px 15px 10px;
    position: relative;
    top: 0;
    transform: rotateX(0deg) rotateY(0deg);
    transform-style: preserve-3d;
    transition: all 0.4s ease-in-out 0s;
    width: 100%;
    z-index: 900;
}
.card-container .card .front .media {
    margin-bottom: 10px;
}
.card-container .card .front .media .media-object {
    font-size: 48px;
    margin-top: 5px;
}
.card-container .card .front .media .media-body small {
    color: rgba(255, 255, 255, 0.5);
    font-size: 12px;
    font-weight: 300;
    text-transform: uppercase;
}
.card-container .card .front .media .media-body h2 {
    font-family: "Roboto","Arial",sans-serif;
    font-weight: 400;
}
.card-container .card .front .progress-list .details .title {
    color: rgba(255, 255, 255, 0.5);
    font-size: 11px;
    font-weight: 400;
    line-height: normal;
    text-transform: uppercase;
}
.card-container .card .front .progress-list .status {
    border-radius: 2px;
    font-size: 9px;
    padding: 3px 6px;
}
.card-container .card .front .progress-list .clearfix {
    height: 20px;
}
.card-container .card .front .progress-list .progress {
    margin-bottom: 0;
}
.card-container .card.flip .front {
    transform: rotateY(180deg);
    z-index: 900;
}
.card-container .card.flip .back {
    transform: rotateX(0deg) rotateY(0deg);
    z-index: 1000;
}
.card-container .card .back {
    backface-visibility: hidden;
    background-color: white !important;
    border: 0 none;
    box-shadow: 0 3px 0 rgba(0, 0, 0, 0.05);
    color: inherit !important;
    height: auto;
    left: 0;
    padding:15%;
    position: absolute;
    text-align: center;
    top: 0;
    transform: rotateY(-179deg);
    transform-style: preserve-3d;
    transition: all 0.4s ease-in-out 0s;
    width: 100%;
    z-index: 800;
}
.card-container .card .back > a {
    color: #717171;
    display: block;
    font-size: 18px;
    font-weight: 300;
    line-height: 30px;
}
.card-container .card .back > a > span{font-size:23px !important; font-weight:bold !important;}
.card-container .card .back > a:hover {
    color: #418bca;
    text-decoration: none;
}
.card-container .card .back > a > i {
    display: block;
}
.card-container .card.card-greensea .front {
    background-color: #16a085;
    color: white;
}
.card-container .card.card-greensea .back p {
    color: #16a085;
}
.card-container .card.card-redbrown .front {
    background-color: #0aa699;
    color: white;
}
.card-container .card.card-redbrown .back p {
    color: #d9544f;
}
.card-container .card.card-blue .front {
    background-color: #418bca;
    color: white;
}
.card-container .card.card-blue .back p {
    color: #418bca;
}

</style>
<div class="content_wrapper padlr0">
	<div class="container-fluid">
		<div class="col-lg-12 clear">
            <div class="row cards">
                <div class="card-container col-md-4 col-vlg-3 col-sm-6">
                    <div class="card card-redbrown hover  commargin_bottom">
                        <div class="front"> 
                        	<h1 class="commoncdhone">RECEIPT</h1>
                                <div class="widget-stats">
                                    <div class="wrapper transparent">
                                    	<span class="item-title">Total Received</span> <span class="float_r item-count animate-number semi-bold" data-value="5695" data-animation-duration="700"><i class="fa fa-inr"></i> 5695</span>
                                    </div>
                                </div>
                            <div class="widget-stats">
                                <div class="wrapper transparent">
                                	<span class="item-title">Receivable</span> <span class="float_r item-count animate-number semi-bold" data-value="568" data-animation-duration="700"><i class="fa fa-inr"></i> 678</span>
                                </div>
                            </div>
                            <div class="widget-stats">
                                <div class="wrapper transparent">
                                	<span class="item-title">Advance Payable</span> <span class="float_r item-count animate-number semi-bold" data-value="568" data-animation-duration="700"><i class="fa fa-inr"></i> 568</span>
                                </div>
                            </div>
                            <div class="widget-stats ">
                                <div class="wrapper transparent">
                                	<span class="item-title">Retrive/With held</span> <span class="float_r item-count animate-number semi-bold" data-value="12459" data-animation-duration="700"><i class="fa fa-inr"></i> 12459</span>
                                </div>
                            </div>
                            <div class="progress commargin_top commargin_bottom" style="border-radius:0px !important; height: 4px !important;width:100% ; background:rgba(0, 0, 0, 0.28);">
                                <div class="progress-bar" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:70% ; border-radius: 0px; background: #fff !important;">
                                </div>
                             </div>
                        	<div class="description"> <span class="text-white mini-description ">4% higher <span class="blend">than last month</span></span></div>
                  		</div>
                        <div class="back">
                            <a href="#">
                                <i class="fa fa-bar-chart-o fa-4x"></i>
                                <span>Check Receipt</span>
                            </a>  
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-vlg-3 col-sm-6">
                    <div class="tiles purple commargin_bottom">
                        <div class="tiles-body">
                        	<h1 class="commoncdhone">BILL</h1>
                            <div class="widget-stats">
                                <div class="wrapper transparent">
                                	<span class="item-title">Total Submittals</span> <span class="float_r item-count animate-number semi-bold" data-value="15489" data- animation-duration="700"><i class="fa fa-inr"></i> 15489</span>
                                </div>
                            </div>
                            <div class="widget-stats">
                                <div class="wrapper transparent">
                                	<span class="item-title">Bill certified</span> <span class="float_r item-count animate-number semi-bold" data-value="551" data-animation-duration="700"><i class="fa fa-inr"></i> 551</span>
                                </div>
                            </div>
                            <div class="widget-stats">
                                <div class="wrapper transparent">
                                	<span class="item-title">Balanced</span> <span class="float_r item-count animate-number semi-bold" data-value="551" data-animation-duration="700"><i class="fa fa-inr"></i> 524</span>
                                </div>
                            </div>
                            <div class="widget-stats ">
                                <div class="wrapper transparent">
                                	<span class="item-title">Bill Value</span> <span class="float_r item-count animate-number semi-bold" data-value="1450" data-animation-duration="700"><i class="fa fa-inr"></i> 1450</span>
                                </div>
                            </div>
                            <div class="progress commargin_top commargin_bottom" style="border-radius:0px !important; height: 4px !important;width:100% ; background:rgba(0, 0, 0, 0.28);">
                                <div class="progress-bar" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:70% ; border-radius: 0px; background: #fff !important;">
                                </div>
                            </div>
                        	<div class="description"> <span class="text-white mini-description ">4% higher <span class="blend">than last month</span></span></div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-vlg-3 col-sm-6">
                    <div class="tiles blue  commargin_bottom">
                        <div class="tiles-body">
                        	<h1 class="commoncdhone">RECEIPT</h1>
                                <div class="widget-stats">
                                    <div class="wrapper transparent">
                                    	<span class="item-title">Total Received</span> <span class="float_r item-count animate-number semi-bold" data-value="5695" data-animation-duration="700"><i class="fa fa-inr"></i> 5695</span>
                                    </div>
                                </div>
                            <div class="widget-stats">
                                <div class="wrapper transparent">
                                	<span class="item-title">Receivable</span> <span class="float_r item-count animate-number semi-bold" data-value="568" data-animation-duration="700"><i class="fa fa-inr"></i> 678</span>
                                </div>
                            </div>
                            <div class="widget-stats">
                                <div class="wrapper transparent">
                                	<span class="item-title">Advance Payable</span> <span class="float_r item-count animate-number semi-bold" data-value="568" data-animation-duration="700"><i class="fa fa-inr"></i> 568</span>
                                </div>
                            </div>
                            <div class="widget-stats ">
                                <div class="wrapper transparent">
                                	<span class="item-title">Retrive/With held</span> <span class="float_r item-count animate-number semi-bold" data-value="12459" data-animation-duration="700"><i class="fa fa-inr"></i> 12459</span>
                                </div>
                            </div>
                            <div class="progress commargin_top commargin_bottom" style="border-radius:0px !important; height: 4px !important;width:100% ; background:rgba(0, 0, 0, 0.28);">
                                <div class="progress-bar" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:70% ; border-radius: 0px; background: #fff !important;">
                                </div>
                             </div>
                        	<div class="description"> <span class="text-white mini-description ">4% higher <span class="blend">than last month</span></span></div>
                        </div>
                    </div>
                </div>
			</div>
            <div class="col-lg-12 clear">
                <div class="row aboveportlet">
					<div id="linechartdiv"></div>							
                </div>
            </div>
            <div class="col-lg-12 clear commargin_ttop_20 commargin_bottom">
                <div class="row portlet">
                    <div class="portlet-title">
                    	<div class="col-lg-12">
                        	<h1 class="col-lg-3" style="color:#676565  !important; font-weight:400 !important;">Monthly Variation</h1>
                            <div class="col-lg-6">
                                <div class="progress animated-bar" style="margin-bottom:0px !important; margin-top:10px !important;">
                                    <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:50%; color:#fff!important; background-color:#9fc569 !important;">
                                    	50% Complete (info)
                                    </div>
                                </div>	
                             </div>
                            <div class="col-lg-2 col-lg-offset-1 ">
                            	<div class="vendor_button"> 
                                    <select>
                                        <option value="">Contact Type</option>
                                        <option value="1">Primary Person</option>
                                        <option value="2">secondary Person</option>
                                        <option value="3">others</option>
                                    </select>
                                </div>  
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="col-lg-12 commargin_bottom" style="background: #fff!important;">
                                <div class="col-lg-4">
                                    <div  class="simplebarchartdiv" id="simplebaronechartdiv"></div>
                                    <span class="col-lg-12 txt_center commargin_bottom" style="color:#676565;">Average <b>60%</b> of the Receipt</span>
                                    <h1 class="commoncdhonechng col-lg-12 float_l txt_center">Receipt</h1>
                                </div>
                                <div class="col-lg-4">
                                    <div class="simplebarchartdiv" id="simplebartwochartdiv"></div>
                                    <span class="col-lg-12 txt_center commargin_bottom" style="color:#676565;">Average <b>60%</b> of the Bill</span>	
                                     <h1 class="commoncdhonechng col-lg-12 float_l txt_center">Bill</h1>		
                                </div>
                                <div class="col-lg-4">
                                    <div class="simplebarchartdiv" id="simplebarthreechartdiv"></div>
                                    <span class="col-lg-12 txt_center commargin_bottom" style="color:#676565;">Average <b>60%</b> of the Work</span>
                                    <h1 class="commoncdhonechng col-lg-12 float_l txt_center">Work</h1>			
                                </div>
                            </div>
                        </div>							
                    </div>
                </div>
            </div>
		</div>
    </div>
</div>
<script>
$(function(){

      // Initialize card flip
      $('.card.hover').hover(function(){
        $(this).addClass('flip');
      },function(){
        $(this).removeClass('flip');
      });
});
var chart;
            var chartData = [
                {
                    "date": "2015-01-01",
                    "distance": 227,
                    "duration": 408,
					"test":500
                },
                {
                    "date": "2015-02-02",
                    "distance": 371,
                    "duration": 482,
					"test":490
                },
                {
                    "date": "2015-03-03",
                    "distance": 433,
                    "duration": 562,
					"test":520
                },
                {
                    "date": "2015-04-04",
                    "distance": 345,
                    "duration": 379,
					"test":530
                },
                {
                    "date": "2015-05-05",
                    "distance": 480,
                    "duration": 501,
					"test":495
                },
                {
                    "date": "2015-06-06",
                    "distance": 386,
                    "duration": 443,
					"test":515
                },
                {
                    "date": "2015-07-07",
                    "distance": 348,
                    "duration": 405,
					"test":555
                },
                {
                    "date": "2015-08-08",
                    "distance": 238,
                    "duration": 309,
					"test":480
                },
                {
                    "date": "2015-09-09",
                    "distance": 218,
                    "duration": 287,
					"test":300
                },
                {
                    "date": "2015-10-10",
                    "distance": 349,
                    "duration": 485,
					"test":500
                },
                {
                    "date": "2015-11-11",
                    "distance": 603,
                    "duration": 890,
					"test":900
                },
                {
                    "date": "2015-12-12",
                    "distance": 534,
                    "duration": 810,
					"test":500
                }
            ];

           AmCharts.ready(function () {

               // SERIAL CHART
               //chart = new AmCharts.AmSerialChart(AmCharts.themes.dark);
			   chart = new AmCharts.AmSerialChart();
               chart.dataProvider = chartData;
               chart.categoryField = "date";

               // AXES
               // category
               var categoryAxis = chart.categoryAxis;
               categoryAxis.parseDates = true; // as our data is date-based, we set parseDates to true
               categoryAxis.minPeriod = "DD"; // our data is daily, so we set minPeriod to DD
               categoryAxis.minorGridEnabled = true;
               categoryAxis.axisColor = "#DADADA";
               categoryAxis.twoLineMode = true;
               categoryAxis.dateFormats = [{
                    period: 'fff',
                    format: 'JJ:NN:SS'
                }, {
                    period: 'ss',
                    format: 'JJ:NN:SS'
                }, {
                    period: 'mm',
                    format: 'JJ:NN'
                }, {
                    period: 'hh',
                    format: 'JJ:NN'
                }, {
                    period: 'DD',
                    format: 'DD'
                }, {
                    period: 'WW',
                    format: 'DD'
                }, {
                    period: 'MM',
                    format: 'MMM'
                }, {
                    period: 'YYYY',
                    format: 'YYYY'
                }];

               // first value axis (on the left)
               var valueAxis1 = new AmCharts.ValueAxis();
               valueAxis1.axisColor = "#FF6600";
               valueAxis1.axisThickness = 2;
               valueAxis1.gridAlpha = 0;
               chart.addValueAxis(valueAxis1);

               // GRAPHS
               // first graph
               var graph1 = new AmCharts.AmGraph();
               graph1.valueAxis = valueAxis1; // we have to indicate which value axis should be used
               graph1.title = "Receipt";
               graph1.valueField = "distance";
               graph1.bullet = "round";
			   graph1.lineThickness = 2;
               graph1.hideBulletsCount = 30;
               graph1.bulletBorderThickness = 1;
               chart.addGraph(graph1);

               // second graph
               var graph2 = new AmCharts.AmGraph();
               //graph2.valueAxis = valueAxis2; // we have to indicate which value axis should be used
               graph2.title = "Bill";
               graph2.valueField = "duration";
			   graph2.lineThickness = 2;
               graph2.bullet = "square";
               graph2.hideBulletsCount = 30;
               graph2.bulletBorderThickness = 1;
               chart.addGraph(graph2);

               // third graph
               var graph3 = new AmCharts.AmGraph();
               //graph3.valueAxis = valueAxis3; // we have to indicate which value axis should be used
               graph3.valueField = "test";
               graph3.title = "Work";
               graph3.bullet = "triangleUp";
               graph3.hideBulletsCount = 30;
			   graph3.lineThickness = 2;
               graph3.bulletBorderThickness = 1;
               chart.addGraph(graph3);

               // CURSOR
               var chartCursor = new AmCharts.ChartCursor();
               chartCursor.cursorAlpha = 0.1;
               chartCursor.fullWidth = true;
               chart.addChartCursor(chartCursor);

               // SCROLLBAR
               var chartScrollbar = new AmCharts.ChartScrollbar();
               chart.addChartScrollbar(chartScrollbar);

               // LEGEND
               var legend = new AmCharts.AmLegend();
               legend.marginLeft = 110;
               legend.useGraphSettings = true;
               chart.addLegend(legend);

               // WRITE
               chart.write("linechartdiv");
           });


/*bar chart*/
function zoomChart(){
    chart.zoomToIndexes(chart.dataProvider.length - 20, chart.dataProvider.length - 1);
}
var chart = AmCharts.makeChart( "simplebaronechartdiv", {
  "type": "serial",
  "theme": "light",
  "dataProvider": [ {
    "month": "Jan",
    "receipt": 2025
  }, {
    "month": "Feb",
    "receipt": 1882
  }, {
    "month": "Mar",
    "receipt": 1809
  }, {
    "month": "Apr",
    "receipt": 1322
  }, {
    "month": "May",
    "receipt": 1122
  }, {
    "month": "Jun",
    "receipt": 1114
  }, {
    "month": "July",
    "receipt": 984
  }, {
    "month": "Aug",
    "receipt": 711
  }, {
    "month": "Sept",
    "receipt": 665
  }, {
    "month": "OCT",
    "receipt": 580
  }, {
    "month": "Nov",
    "receipt": 443
  }, {
    "month": "Dec",
    "receipt": 441
  }],
  "valueAxes": [ {
    "gridColor": "#FFFFFF",
    "gridAlpha": 0.2,
    "dashLength": 0
  } ],
  "gridAboveGraphs": true,
  "startDuration": 1,
  "graphs": [ {
    "balloonText": "[[category]]: <b>[[value]]</b>",
    "fillAlphas": 0.8,
    "lineAlpha": 0.2,
    "type": "column",
    "valueField": "receipt"
  } ],
  "chartCursor": {
    "categoryBalloonEnabled": false,
    "cursorAlpha": 0,
    "zoomable": false
  },
  "categoryField": "month",
  "categoryAxis": {
    "gridPosition": "start",
    "gridAlpha": 0,
    "tickPosition": "start",
    "tickLength": 20
  },
  "export": {
    "enabled": true
  }

} );
var chart = AmCharts.makeChart( "simplebartwochartdiv", {
  "type": "serial",
  "theme": "light",
  "dataProvider": [ {
    "month": "Jan",
    "bill": 2025
  }, {
    "month": "Feb",
    "bill": 1882
  }, {
    "month": "Mar",
    "bill": 1809
  }, {
    "month": "Apr",
    "bill": 1322
  }, {
    "month": "May",
    "bill": 1122
  }, {
    "month": "Jun",
    "bill": 1114
  }, {
    "month": "July",
    "bill": 984
  }, {
    "month": "Aug",
    "bill": 711
  }, {
    "month": "Sept",
    "bill": 665
  }, {
    "month": "OCT",
    "bill": 580
  }, {
    "month": "Nov",
    "bill": 443
  }, {
    "month": "Dec",
    "bill": 441
  }],
  "valueAxes": [ {
    "gridColor": "#FFFFFF",
    "gridAlpha": 0.2,
    "dashLength": 0
  } ],
  "gridAboveGraphs": true,
  "startDuration": 1,
  "graphs": [ {
    "balloonText": "[[category]]: <b>[[value]]</b>",
    "fillAlphas": 0.8,
    "lineAlpha": 0.2,
    "type": "column",
    "valueField": "bill"
  } ],
  "chartCursor": {
    "categoryBalloonEnabled": false,
    "cursorAlpha": 0,
    "zoomable": false
  },
  "categoryField": "month",
  "categoryAxis": {
    "gridPosition": "start",
    "gridAlpha": 0,
    "tickPosition": "start",
    "tickLength": 20
  },
  "export": {
    "enabled": true
  }

} );
var chart = AmCharts.makeChart( "simplebarthreechartdiv", {
  "type": "serial",
  "theme": "light",
  "dataProvider": [ {
    "month": "Jan",
    "work": 2025
  }, {
    "month": "Feb",
    "work": 1882
  }, {
    "month": "Mar",
    "work": 1809
  }, {
    "month": "Apr",
    "work": 1322
  }, {
    "month": "May",
    "work": 1122
  }, {
    "month": "Jun",
    "work": 1114
  }, {
    "month": "July",
    "work": 984
  }, {
    "month": "Aug",
    "work": 711
  }, {
    "month": "Sept",
    "work": 665
  }, {
    "month": "OCT",
    "work": 580
  }, {
    "month": "Nov",
    "work": 443
  }, {
    "month": "Dec",
    "work": 441
  }],
  "gridAboveGraphs": true,
  "startDuration": 1,
  "graphs": [ {
    "balloonText": "[[category]]: <b>[[value]]</b>",
    "fillAlphas": 0.8,
    "lineAlpha": 0.2,
    "type": "column",
    "valueField": "work"
  } ],
  "chartCursor": {
    "categoryBalloonEnabled": false,
    "cursorAlpha": 0,
    "zoomable": false
  },
  "categoryField": "month",
  "categoryAxis": {
    "gridPosition": "start",
    "gridAlpha": 0,
    "tickPosition": "start",
    "tickLength": 20
  },
  "export": {
    "enabled": true
  }

} );

</script>