<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/select2.full.min.js"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/select2.min.css" />
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/workorder.css"/>
<!-- dummy row -->
<script id="dummy-row"  type="text/template" class="hide">
	<tr>
		<td width="10%" class="tbl_input_td"><input type="hidden" name="extraItemId__" id="extraItemId__"/>
		<input class="tbl_input" type="text" value="" name="desc__" id="desc__"/>
		<td width="2%"><input class="tbl_input txt_right rate" type="text" value="" readonly name="transRate__" id="transRate__"/></td>
		<td width="2%"><input class="tbl_input txt_right quantity" type="text" value="" name="transQuantity__" id="transQuantity__" onKeyPress="return isDecimal(event,this);" onchange = "calcAmount(this);" /></td>
		<td width="2%"  class="tbl_input_td" ><input class="tbl_input txt_right amount" readonly type="text" value="" name="transAmount__" id="transAmount__" /></td></td>
		<td width="2%" align="center" class="action_btns_td">
			<ul class="action_btns">
				<li>
					<a class="deleteTr__" onclick="deleteRow(this, event);" style="display: none;"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i></a>
				</li>
			</ul>
		</td>
	</tr>
</script>
<!-- dummy row -->
<div class="content_wrapper padlr0">
	<div class="container-fluid">
    	<div class="row">
			<!-- newly addind Div-->
			<form action="" method="post" onSubmit="return validate();">
                <div id="Step1">
                    <div class="col-lg-12">
                        <h1 data-bsfhead="Extra Item Done" class="txt_center">Extra Item Done</h1>
                    </div>
                    <div class="col-lg-12 clear padlr0">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                            <div class="col-lg-offset-3">
                                <label for="booking_no" class="bk_lbl bk_lbl_inpt">Extra Item Done No <span class="colon_r">:</span></label>
                                <input data-bsfshare="Extra Item Done No" type="text" class="bk_lbl_inpt inputbg_ef bk_inpt1" <?php if ($arrVNo["genType"] == true){ ?> readonly <?php } ?> name="extraitemNo" readonly id="booking_no" value="<?php echo $unitList['ExtraItemDoneNo'];?>" />
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 col-lg-pull-1 col-md-pull-1 col-sm-pull-1">
                            <div class="col-lg-offset-5">
                                <label for="booking_date" class="bk_lbl bk_lbl_inpt"><span class="bkspan_calendar"><i class="fa fa-calendar-o"></i></span> Service Done Date <span class="colon_r">:</span></label>
                                <input data-bsfshare="Extra Item Date" type="text" class="date_picker bk_lbl_inpt bk_inpt inputbg_ef" name="extraitem_date" id="booking_date" disabled value="<?php echo date('d-m-Y', strtotime($unitList['ExtratItemDoneDate'])); ?>" />
							</div>
							 <input type="hidden"  name="extraItemDoneReg_id" id="extraItemDoneReg_id" value="<?php echo (isset($unitList['ExtraItemDoneRegId']))?$unitList['ExtraItemDoneRegId'] : 0 ; ?>" />
                        </div>
                    </div>
                    <div class="col-lg-12 clear">
                        <div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                            <div class="row form-group">   
                                <div class="form-group col-lg-12 m3_auto padtop20">
                                    <input data-bsfshare="Unit Name" type="text" name="unitname" id="unitname" class="form-control lbl_move" label="Project/Unit/Buyer" readonly value="<?php echo $unitList['value'];?>" />
                                    <input type="hidden" name="unitId" id="unitid" value="<?php echo $unitList['data']; ?>"/>
                                </div>
                            </div>
                            <div  id="continueBtn" class="col-lg-12 savebtn_area no_border">
                                <ul>
                                    <li class="save_btn m_auto">
                                        <a href="javascript:void(0);" id="conti" class="ripple" onclick="show_step2();">Continue</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div id="Step2">
                    <input type="hidden" name="count" id="count" value="<?php echo (isset($unitTrans))? count($unitTrans) : 0 ; ?>" />
                    <input type="hidden" name="finalCount" id="finalCount" value="<?php echo (isset($unitTrans))? count($unitTrans) : 0 ; ?>" />
                    <div class="col-lg-12 clear">
                        <div class="table-responsive">
                            <table id="extra-workdone-table" class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Extra Item</th>
										 <th>Rate</th>
										  <th>Quantity</th>
                                        <th class="txt_center">Amount</th>
                                        <th>&nbsp; </th>
                                    </tr>
                                </thead>
                                <tbody id="startcount" data-count="0">
									<?php $i = 0;
									foreach($unitTrans as $trans): ?>
                                    <tr>
                                        <td width="10%" class="tbl_input_td"><input type="hidden" name="extraItemId_<?php echo $i; ?>" id="extraItemId_<?php echo $i; ?>" value="<?php echo $trans['ExtraItemId']?>"/>
											<input class="tbl_input" type="text" value="<?php echo $trans['ItemDescription']?>" name="desc_<?php echo $i; ?>" id="desc_<?php echo $i; ?>"/>
                                        </td>
										<td width="2%">
											<input class="tbl_input txt_right rate" type="text" value="<?php echo $trans['Rate']?>" name="transRate_<?php echo $i; ?>" readonly id="transRate_<?php echo $i; ?>" />
										</td>
										<td width="2%">
											<input class="tbl_input txt_right quantity" type="text" value="<?php echo $trans['Quantity']?>" name="transQuantity_<?php echo $i; ?>" id="transQuantity_<?php echo $i; ?>" onKeyPress="return isDecimal(event,this);" onchange = "calcAmount(this);"/>
										</td>
                                        <td width="2%">
											<input class="tbl_input txt_right amount" type="text" readonly value="<?php echo $trans['Amount']?>" name="transAmount_<?php echo $i; ?>" id="transAmount_<?php echo $i; ?>"/>
										</td>
                                        
                                        <td width="1%" align="center" class="action_btns_td">
                                            <ul class="action_btns">
                                                <li>
                                                    <a class="deleteTr_<?php echo $i; ?>" onclick="deleteRow(this, event);"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" data-original-title="Delete"></i></a>
                                                </li>
                                            </ul>
                                        </td>
                                    </tr>
									
									<?php $i++; 
									endforeach; ?>
									<tfoot>
									<tr>
                                        <td align="right" colspan="3" class="rate_pri">Gross Total</td>
                                        <td width="5%" class="tbl_input_td"><input data-bsfshare="Gross Total" id="gross-total" readonly class="tbl_input txt_right grossAmount" name="grossAmount" type="text"/></td>
                                        <td>&nbsp;</td>
                                    </tr>
								</tfoot>
									<!--
                                    <tr>
                                        <td align="right" colspan="5" class="rate_pri">Gross Total</td>
                                        <td width="5%" class="tbl_input_td"><input id="gross-total" readonly class="tbl_input txt_right" name="grossAmount" type="text"/></td>
                                        <td>&nbsp;</td>
                                    </tr>
									<tr>
                                        <td align="right" colspan="5" class="rate_pri">Tax Amount</td>
                                        <td width="5%" class="tbl_input_td"><input id="tax-amount" readonly class="tbl_input mainTr txt_right" name="taxAmount" type="text"/></td>
                                        <td>&nbsp;</td>
                                    </tr>
									<tr style="display:none;" class="subTr qualmainTr">
										<td colspan="8" style="padding:0px !important; "><div class="subDiv" style="display:none;">
										<?php// echo $qualHtml;?>
										</td>
									</tr>
                                    <tr>
                                        <td align="right" colspan="5" class="rate_pri">NET Total</td>
                                        <td width="5%" class="tbl_input_td"><input id="net-total" readonly class="tbl_input txt_right total_input" name="netAmount" type="text"/></td>
                                        <td>&nbsp;</td>
                                    </tr>-->
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="col-lg-12 savebtn_area clear">
                        <ul>
                            <li class="dropdown save_btn float_l">
                                <a href="<?php echo $this->basePath(); ?>/crm/extraitem/done-register" class="ripple">cancel</a>
                            </li>
                            <li class="dropdown save_btn float_r">
                            	<input type="submit" name="submit" class="ripple" value="Save"/>
                            </li>
                        </ul>
                    </div>
                </div>
		  	</form>
        </div>
	</div>
</div>
<script>
function validate(){
	if($('#finalCount').val()==0){
		alert("Atlease one Extra Item Must be Selected");
		return false
	}
}

$(document).ready(function() {
	$('#Step1').show();
	$('#Step2').hide();
	$('#continueBtn').hide();
	$("#transQuantity_0").trigger('change');
	$("#conti").trigger('onclick');
   // bindTaxCalculation();

});
var extraItemData,tmpExtraItemData;
$(document).ready(function() {
	$(".multiple_dropdown").select2({
	});
});
function bindOtherCostAutoComplete() {
    var $otherCost = $('input[id^=desc_');
	$.each($otherCost, function () {
		
        var $this = $(this),
            name = $this[0].id;
        if (name.indexOf('__') != -1) return;
        var arrname = name.split('_');
        var key1 = arrname[1];
        checkOtherCost(name);
        $this.unbind('autocomplete');
        $this.autocomplete({
            lookup: tmpExtraItemData,
            lookupFilter: function (suggestion, originalQuery, queryLowerCase) {
                if (queryLowerCase == '*') {
                    return suggestion.value;
                } else {
                    var re = new RegExp($.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
                    return re.test(suggestion.value);
                }
            }, onSelect: function(suggestion) {
                if(suggestion) {
                     
                    $("#extraItemId_" + key1).val(suggestion.data);
					$("#transRate_" + key1).val(sanitizeNumber(suggestion.Rate));
					$("#transQuantity_" + key1).val(sanitizeNumber(suggestion.Quantity));
					var amount = sanitizeNumber(suggestion.Rate) * sanitizeNumber(suggestion.Quantity);
                    $("#transAmount_" + key1).val(sanitizeNumber(amount));
					
					$("#transQuantity_" + key1).trigger('change');
                    removeError($(this));

                    $(this).prop('disabled', true);
                    addNewRow($(this));
                }
            }, onSearchStart: function(suggestion) {
                $("#extraItemId_" + key1).val(0);
                removeError($(this));
            }, onSearchComplete: function (query, suggestions) {
                if(!suggestions.length && query.length > 1){
                    showError($(this), 'Required');
                    $("#extraItemId_" + key1).val(0);
                } else
                    removeError($(this));
            }
        });
    });
}
function addNewRow(x) {
    //var $tr = $(x).closest('tr');
    /* if ($tr.next('tr').length != 0)
        return; */
    //count = parseInt($('#startcount').attr('data-count'));
    count = parseInt($('#count').val());
    $('.deleteTr_' + count).show();
    template = $('#dummy-row').html();
    count++;
    template = template.replace(/__/g, '_' + count);
    $('#startcount').append(template); //.insertAfter($tr);
    $('#count').val(count);
    var finalvalue =  parseInt($('#finalCount').val());
    console.log(finalvalue);
	finalvalue++;
    $('#finalCount').val(finalvalue);
    bindOtherCostAutoComplete();

    //calcNetTotal();
}
function deleteRow(x,e) {
    e.preventDefault();
    if (!confirm('Do you want to Delete'))
        return false;

	var $x = $(x),
        $tr = $x.closest('tr');
    $tr.remove();
	var finalCount = parseInt($('#finalCount').val());
	finalCount--;
	$('#finalCount').val(finalCount);
   // bindOtherCostAutoComplete();

    //calcNetTotal();
    return false;
}
	
function checkOtherCost(x) {
    var arrname = x.split('_'),
        id= arrname[1],
        extraid = $('input[id^=extraItemId_]');
    tmpExtraItemData = extraItemData;
    tmpExtraItemData = $.grep(extraItemData, function (element, index) {
        var is_selected = true;
        $.each(extraid, function (i, obj) {
            var $this = $(this),
                key = $this[0].id.split('_')[1];
            if (key != id) {
                if (element.data == $this.val()) {
                    is_selected = false;
                }
            }
        });
        return is_selected;
    });
}

function show_step2() {	
	if($('#booking_no').val()==0){
		alert("Please Enter Voucher Number");
		return false
	}
	if($('#unitid').val()!=""){
		load_extraItemList(function(isSuccess) {
			if(isSuccess){
				addNewRow();
				//$('#Step1').hide();

				$('continueBtn').hide();
				$('#Step2').show();
				
			}
		});
		} else {
		alert("Please Select Project/unit/buyer");
		}
}
function calcAmount(x){
	var quantity = parseFloat($(x).val());
	var $tarTr = $(x).closest('tr');
	var $tarAmt = $tarTr.find('.amount');
	var rate = parseFloat($tarTr.find('.rate').val());

	var amt = 0;
	if(!isNaN(rate) && !isNaN(quantity)) {
		amt = rate * quantity;
	}
	var grossAmount = 0;
	$tarAmt.val(amt.toFixed(2));
	$('#extra-workdone-table').find('tbody tr .amount').each(function( index ) {
		var totAmt = parseFloat($( this ).val());
		if(!isNaN(totAmt)){
			grossAmount += totAmt;
		}
	});
	//alert(grossAmount);
	$('#gross-total').val(grossAmount.toFixed(2));
}

function load_extraItemList(callback) {
    var unit_id = $('#unitid').val();
    var reg_id = $('#extraItemDoneReg_id').val();
	
    if (/^\d+$/.test(unit_id) === false) {
        return;
    }

    $.ajax({
        url: getBaseURL() + 'crm/extraitem/extraItemList',
        data: {csrf: "<?php echo isset($csrf)?$csrf:''; ?>", UnitId: unit_id,regId:reg_id},
        type: 'POST',
        success: function (data, status, xhr) {
			if (data.extraitem_list.length > 0) {
                extraItemData = data.extraitem_list;
                tmpExtraItemData = data.extraitem_list;
				bindOtherCostAutoComplete();
				if (callback) {
					callback(true);
					return true;
				}
            } else {
				alert("ExtraItem Not Available");
				if (callback) {
					callback(false);
					return false;
				}
			}

            
        },
        error: function (xhr, status, error) {
            alert(xhr.responseText);
        }
    });
}


</script>
<script>
$(document).ready(function() {
	$(".single_dropdown").select2({
		placeholder: "",
		allowClear: true
	});

});

</script>