<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/select2.full.min.js"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/select2.min.css" />

<style>
#allResource .jqx-grid-header 	{height:75px !important;}
#mostResource .jqx-grid-header 	{height:75px !important;}
#recentResource .jqx-grid-header 	{height:75px !important;}
#wbsGrid .jqx-grid-header 	{height:75px !important;}

.jqx-grid-column-header .jqx-checkbox-default{
	display:none;
}
.input-group-addon{
	background-color:#fff !important;
	border:none !important;
}
.error{
	border-color:red;
	background-color:red !important;
}
.nav-list{padding-right:15px;padding-left:15px;margin-bottom:0;}
.nav-list-main{padding-left:0px;padding-right:0px;margin-bottom:0;}
span.nav-toggle-icon{font-size:7px !important;top:-2px !important;color:#888 !important;}
.rmks_ara { border: 1px dashed #afbecc; font-size: 15px; height: 158px;padding: 10px;resize: none;width: 100% !important;margin-top:10px;margin-bottom:10px;}
.btn-pop{ float:right;padding:6px 12px !important; font-size:14px; margin-right:20px; background:#d1eaff; color:#054d6b; border-radius:10px; margin-bottom:20px !important;}
.btn-pop:hover{background:#87ceeb;}

/**.nav-list-main li>label.nav-toggle::before {
  position: absolute;
  top: 6px;
  right: 10px;
  display: inline-block;
  border-bottom: 4px solid transparent;
  border-top: 4px solid transparent;
  border-left: 4px solid #ccc;
  border-left-color: rgba(0, 0, 0, 0.4);
  content: '';
}
.nav-list-main li>label.nav-toggle::after {
  position: absolute;
  top: 0px;
  right: 10px;
  display: inline-block;
  border-left: 4px solid transparent;
  border-right: 4px solid transparent;
  border-top: 4px solid red;
  border-left-color: rgba(0, 0, 0, 0.4);
  content: '';
}*/

</style>

<!--
<div class="container">
  <div class="col-md-12"><h2>Bootstrap 3 Left Multilevel Menu (Treeview)</h2></div>
  <div class="col-md-12">

    <ul class="nav nav-list-main">
      <li><label class="nav-toggle nav-header"><span class="nav-toggle-icon glyphicon glyphicon-chevron-right"></span> <a href="javascript:void(0)">Header 1<input type="text"style="height:30px;" ></a></label>
            <ul class="nav nav-list nav-left-ml" style="padding-top: 20px;">
                <li><label class="nav-toggle nav-header"><span class="nav-toggle-icon glyphicon glyphicon-chevron-right"></span> <a href="javascript:void(0)">Header 1.1</a><input type="text"></label>
                    <ul class="nav nav-list nav-left-ml" style="padding-top: 20px;">
                        <li><label class="nav-toggle nav-header"><span class="nav-toggle-icon glyphicon glyphicon-chevron-right"></span> <a href="javascript:void(0)">Header 1.1.1</a><input type="text"></label>
                            <ul class="nav nav-list nav-left-ml">
                                <li><a href="#">Link</a></li>
                                <li><a href="#">Link</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li style="padding-top: 20px;"><label class="nav-toggle nav-header"><span class="nav-toggle-icon glyphicon glyphicon-chevron-right"></span> <a href="javascript:void(0)">Header 1.1</a><input type="text"></label>
                    <ul class="nav nav-list nav-left-ml" style="padding-top: 20px;">
                        <li><label class="nav-toggle nav-header"><span class="nav-toggle-icon glyphicon glyphicon-chevron-right"></span> <a href="javascript:void(0)">Header 1.1.1</a><input type="text"></label>
                            <ul class="nav nav-list nav-left-ml">
                                <li><a href="#">Link</a></li>
                                <li><a href="#">Link</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li style="padding-top: 20px;"><label class="nav-toggle nav-header"><span class="nav-toggle-icon glyphicon glyphicon-chevron-right"></span> <a href="javascript:void(0)">Header 1.1</a><input type="text"></label>
                    <ul class="nav nav-list nav-left-ml" style="padding-top: 20px;">
                        <li><label class="nav-toggle nav-header"><span class="nav-toggle-icon glyphicon glyphicon-chevron-right"></span> <a href="javascript:void(0)">Header 1.1.1</a><input type="text"></label>
                            <ul class="nav nav-list nav-left-ml">
                                <li><a href="#">Link</a></li>
                                <li><a href="#">Link</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>				
            </ul>
        </li>
        <li class="nav-divider"></li>
        <li><label class="nav-toggle nav-header"><span>Header 2</span></label>
            <ul class="nav nav-list nav-left-ml" style="padding-top: 20px;">
                <li><a href="#">Link</a></li>
                <li><a href="#">Link</a></li>
                <li><label class="nav-toggle nav-header"><span>Header 2.1</span></label>
                    <ul class="nav nav-list nav-left-ml">
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                      <li><label class="nav-toggle nav-header"><span>Header 2.1.1</span></label>
                            <ul class="nav nav-list nav-left-ml">
                                <li><a href="#">Link</a></li>
                                <li><a href="#">Link</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
              <li><label class="nav-toggle nav-header"><span>Header 2.2</span></label>
                    <ul class="nav nav-list nav-left-ml">
                        <li><a href="#">Link</a></li>
                        <li><a href="#">Link</a></li>
                      <li><label class="nav-toggle nav-header"><span>Header 2.2.1</span></label>
                            <ul class="nav nav-list nav-left-ml">
                                <li><a href="#">Link</a></li>
                                <li><a href="#">Link</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
            </ul>
        </li>
    </ul>
  </div>
</div>
-->


<div class="content_wrapper padlr0">
	<div class="container-fluid">
		<div class="col-lg-12 clear">
			<form class="form-horizontal" method="post">
				<div class="row" id="firstStep">
					<h1 class="txt_center form_main_h1 frmwrk_h1">Request Entry<?php echo ($genType==true) ? '-' : ''; ?><?php echo $vNo['voucherNo']; ?></h1>
					<div class="form-group">
						<div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
							<div class="row" style="<?php echo ($genType==true) ? 'display:none' : ''; ?>">
								<div class="form-group req_flds col-lg-12">
									<input type="text" name="voucherNo" id="voucherNo" class="form-control lbl_move" label="Enter voucherNo" value="<?php echo $svNo; ?>" >
									<div class="error_message" style="display:none;"><p>Please enter VoucherNo...</p> </div> 
								</div>
							</div>
							<div class="row">
								<div class="form-group req_flds col-lg-12">
									<select name="project_name" id="project_name" class="single_dropdown2 lbl_move" value="Select Required Projects" style="width:100%;">
									<?php
									foreach($projResults as $d){
										echo '<option value="'.$d['data'].'">'.$d['value'].'</option>';
									}
									?>
									</select>
									<div class="error_message"><p>Please enter project name...</p> </div> 
								</div>
							</div>
							<div class="row">   
								<div class="form-group req_flds col-lg-12">
									<select name="request_type" id="request_type" class="single_dropdown2 lbl_move" label="Select Request Type" style="width:100%;">
										<option value="None">None</option>
										<option value="Activity">Activity</option>
										<option value="Asset">Asset</option>
										<option value="IOW">IOW</option>
										<option value="Labour">Labour</option>
										<option value="Material">Material</option>
										<option value="Sub-IOW">Sub-IOW</option>
										<option value="Service">Service</option>
										<option value="TurnKey">TurnKey</option>
									</select>
									<div class="error_message"><p>Please enter request type...</p> </div> 
								</div>
							</div>
							<div class="row">   
								<div class="form-group req_flds col-lg-12">
									<span class="date_icon"><i class="fa fa-calendar"></i></span>
									<input type="text" name="project_date" id="project_date" class="form-control lbl_move datepickerinput" label="Request date" value='<?php echo Date('d-m-Y'); ?>' />									
									<div class="error_message"><p>Please enter Request date...</p> </div> 
								</div>
							</div>
							<div class="row">   
								<div class="form-group req_flds col-lg-12">
									<select class="form-control selectpicker show-tick" name="priority" id="priority" title="Choose priority...">
										<option value="-1" selected>Select Priority</option>
										<option value="1">Low</option>
										<option value="2">Medium</option>
										<option value="3">High</option>
									</select>
									<div class="error_message"><p>Please select the priority...</p> </div> 
								</div>
							</div>
							<div class="row">   
								<div class="form-group col-lg-12">
									<div class="radio_check">
										<p>
											<input type="radio" value="1" id="buyer" name="customize"/>
											<label for="buyer">Yes,Customize</label>
										</p>
										<p>
											<input type="radio" value="2" id="investor" name="customize" checked/>
											<label for="investor">Default</label>
										</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="row" id="excludeFirst" style="display:none;">
				   <div class="col-lg-12">
						<h1>Request Entry-<span id="VoucherSpan"><?php echo $vNo['voucherNo']; ?></span></h1> 
						<div class="col-lg-12 clear" style="margin:10px;">
							<div class="col-lg-6 col-md-6">
								<div class="row">
									<div class=" col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p">Project<span class="colon_r">:</span></p></div>
									<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p" id="projectSpan"> RDC0001</p></div> 
								</div>
								<div class="row">
									<div class=" col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p">Selected Type<span class="colon_r">:</span></p></div>
									<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p" id="materialSpan">Material</p></div> 
							   </div>
							</div>
							<div class="col-lg-6 col-md-6">
								<div class="row">
									<div class=" col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p">Request Date<span class="colon_r">:</span></p></div>
									<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p" id="dateSpan"><?php echo Date('d-m-Y'); ?></p></div> 
								</div>
								<div class="row">
									<div class=" col-lg-6 col-md-6 col-sm-6 col-xs-6"><p class="space_p">Priority<span class="colon_r">:</span></p></div>
									<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6"> <p class="space_p" id="prioritySpan">Partially Approved</p></div> 
								</div>
							</div>  
						</div>
					</div>
				</div>						
				<div id="secondStep" style="display:none;">
					<div class="row">
						<div class="col-lg-12">
							<div class="col-lg-12 clear" style="margin:10px;">
								<div class="col-lg-5 col-md-8 col-lg-offset-4">
									<div>
										<div>
											<!--checkboxtabel-->              
											<ul class="list ui-sortable" data-sortable="true">
												<li class="tile ui-sortable-handle">
													<div class="checkbox checkbox-styled tile-text">
														<label>
															<input type="checkbox" class="setting_check" name="all_resource" id="all_resource" value="1">
															<span>Do you want to load all resources?</span>
														</label>
													</div>
												</li>
												<li class="tile ui-sortable-handle">
													<div class="checkbox checkbox-styled tile-text">
														<label>
															<input type="checkbox" class="setting_check" name="sub_group" id="sub_group" value="1">
															<span>Do you want to group resources by sub group?</span>
														</label>
													</div>
												</li>
												<li class="tile ui-sortable-handle">
													<div class="checkbox checkbox-styled tile-text">
														<label>
															<input type="checkbox" class="setting_check" name="selected_wbs" id="selected_wbs" value="1">
															<span>Yes,I like to select particular WBS for this request</span>
														</label>
													</div>
												</li>
												<li class="tile ui-sortable-handle">
													<div class="checkbox checkbox-styled tile-text">
														<label>
															<input type="checkbox" class="setting_check" name="all_remarks" id="all_remarks" value="1">
															<span>No,I didn't like to add remarks for each material</span>
														</label>
													</div>
												</li>
												<li class="tile ui-sortable-handle">
													<div class="checkbox checkbox-styled tile-text">
														<label>
															<input type="checkbox" class="setting_check" name="all_date" id="all_date" value="1">
															<span>No,I didn't like to add requried date for each material </span>
														</label>
													</div>
												</li>
											</ul>
										<!--end of checkboxtabel-->               
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-5 col-md-8 col-lg-offset-4" style="display:none;">
						<div class="form-group">
							<label class="col-lg-5 col-md-6" style="font-size: 16px; font-weight:normal !important;margin-left:19px;">Select Resources From</label>
							<div class="col-lg-6 col-md-6">
								<label class="radio-inline radio-styled">
									<input type="radio" name="inlineRadioOptions" value="option1"><span style="font-size: 16px; font-weight:normal !important;">Project</span>
								</label>
								<label class="radio-inline radio-styled">
									<input type="radio" name="inlineRadioOptions" value="option2"><span style="font-size: 16px; font-weight:normal !important;">Library</span>
								</label>
							</div><!--end .col -->
						</div>
						<div class="form-group" style="display:none;">
							<select id="select1" name="select1" class="form-control">
								<option value="">&nbsp;</option>
								<option value="30">30</option>
								<option value="40">40</option>
								<option value="50">50</option>
								<option value="60">60</option>
								<option value="70">70</option>
							</select>
							<label for="select1">Select</label>
						</div>
				   </div>					
				</div>
				<div class="row" id="thirdStep" style="display:none;">
					<div class="col-lg-12">
						<input type="hidden" name="sel_wbsId" id="sel_wbsId" value="none">
						<div id="jqxWidget">
							<div id="wbsGrid" style="width:100%;">
							</div>
						</div>
					</div>	
				</div>						
				<div class="row" id="fourthStep" style="display:none;">
					<input type="hidden" name="resourceId" id="resourceId">
					<div class="col-lg-12">
						<nav class="navbar inrmdltab_navbar navbar-default">
							<div class="navbar-header">
								<button type="button" class="navbar-toggle mdlnvbr_tgl collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
								</button>
								<a class="navbar-brand inrmdl_navbrand" href="javascript:void(0);">Select Menus</a>
							</div>
							<div id="navbar" class="navbar-collapse padlr0 collapse">
								<ul class="nav nav-tabs innermdl_tabs">
									<li class="active"><a href="#allresources" data-toggle="tab">All Resource</a></li>
									<li><a href="#mostused" data-toggle="tab">Most used</a></li>
									<li><a href="#recent" data-toggle="tab">Recent</a></li>
								</ul>
							</div>
						</nav>
						<div class="tab-content">
							<div class="tab-pane fade in active" id="allresources">
								<div class="table-responsive">
									<div id="jqxWidget">
										<div id="allResource" style="width:100%;">
										</div>
									</div>
								</div>
							</div>
							<div class="tab-pane fade" id="mostused">
								<div class="table-responsive">
									<div id="jqxWidget">
										<div id="mostResource" style="width:100%;">
										</div>
									</div>
								</div>
							</div>
							<div class="tab-pane fade" id="recent">
							   <div class="table-responsive">
									<div id="jqxWidget">
										<div id="recentResource" style="width:100%;">
										</div>
									</div>
								</div> 
							</div>
						</div>								
					</div>
				</div>
				<div class="row" id="fifthStep" style="display:none;">
					<div class="col-lg-12">
						<input type="hidden" name="all_wbsId" id="all_wbsId">
						<div class="col-lg-1 col-lg-offset-11">
							<div class="form-group">
								<ul class="grid_change">
									<li class="matrixView"><a class="grid_change_line grid_change_active" data-original-title="Grid View" href="javascript:void(0)" data-placement="top" data-toggle="tooltip"><span><i class="fa fa-th"></i></span></a></li>
								</ul>
							</div>		
						</div>
                        <div class="form-group hideView" style="margin-top:20px;display:none;" id="sequentialViewDiv">
                            <div>
                                <div class="col-lg-12 clear">
                                    <div class="table-responsive clear">						
										<table id="sequentialView" class="table table-bordered tableView" style="width:100%;">
											<thead>
												<tr>
													<th>Code</th>
													<th>Description</th>
													<th>Unit</th>
													<th>Required Date</th>
													<th>Remarks</th>
													<th>Quantity</th>
												</tr>
											</thead>
											<tbody class="appendData">
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
						<div class="table-responsive clear col-lg-12 hideView" id="matrixView">
							<div class="matrix_table_area">
								<table class="table matrix_table clear">
									<thead>
										<tr>
											<th class="headcol_l headcol_l1">Resource Description</th>
										</tr>
									</thead>
									<tbody class="appendDataMatrix">
									</tbody>
								</table>
							</div>
						</div>
						<table id="sequentialViewSub" class="table table-bordered table-hover tableView" style="margin-top:20px;display:none;">
							<thead>
								<tr>
									<th>Sample</th>
								</tr>
							</thead>
							<tbody class="subTable">
							</tbody>
						</table>							
					</div>
                    <div class="col-lg-12">
					<textarea name="narration" id="narration" rows="3" class="rmks_ara"></textarea>
					</div>
					<div class="col-lg-12">
                    	<button type="button" class="btn-pop" data-toggle="modal" data-target="#myModal">View More</button>
                    	<div class="modal fade" id="myModal" role="dialog">
                    		<div class="modal-dialog"> 
                    			<div class="modal-content">
                    				<div class="modal-header">
                    					<button type="button" class="close" data-dismiss="modal">&times;</button>
                    					<h4 class="modal-title" style="color:#244996;">Pop-Up</h4>
                    				</div>
                    				<div class="modal-body">
                                        <div class="radio_check">
                                        <?php  $i=0;
										foreach($narration as $nar): ?>
                                        <p>
                                        	<?php if(strlen($nar['Description'])>100){ ?>											
                                            <input type="checkbox" class="checkboxNarration" tagname="cid" cid="1" id="customize_1<?php echo $i;?>" name="narSel" value="<?php echo $nar['Description']; ?>" /> 
        		                            <label class="ripple" for="customize_1<?php echo $i;?>"> 
                		                    <?php  echo substr($nar['Description'],0,100)."..."; ?>
											</label>
                        	                <?php } else { ?>
		                                    <input type="checkbox" class="checkboxNarration" id="radio_check<?php echo $i;?>" name="narSel" value="<?php echo $nar['Description']; ?>" /> 
											<?php echo substr($nar['Description'],0,100); ?>                
											</label>
											<?php  } $i++;?>
                                     	</p>
                                           <?php endforeach; ?>
                                        </div>
                                    </div>
                    				<div class="modal-footer clear"> 
                    				</div>
                    			</div>  
                    		</div>
                    	</div>   
                    </div> 
            	</div>
			</form>
		</div>
	</div>
</div>
<div class="col-lg-12 savebtn_area">
    <ul>
        <li id="continueButton" class="dropdown save_btn float_r">
            <a href="javascript:void(0);" class="ripple">Continue</a>
        </li>
        <li id="backButton" class="cancel_btn float_r" style="display:none;"><a href="javascript:void(0);" class="ripple">back</a></li>
		 <li class="cancel_btn cancel_btn_bluecolor float_l"><a id="cancelbutton" class="ripple" onclick="alert confirm();">cancel</a></li>
    </ul>
</div>
<script>
var apptextare="";
/* $('#narration').change(function(){
	apptextare = $('#narration').html();
	alert(apptextare);
}); */
$(".checkboxNarration").change(function() {
    if(this.checked) {
		apptextare += this.value+'&#13';
		$('#narration').html(apptextare);
    } else {
		if(apptextare !=""){
			var isIn = apptextare.indexOf(this.value+'&#13');
			if(isIn != -1){
				apptextare = apptextare.replace(this.value+'&#13','');
				$('#narration').html(apptextare);
			}
		}
	}
});
$("#cancelbutton").click(function(){
    if(confirm("Are you sure you want to Cancel this entry?")){
        $("#cancelbutton").attr("href", "<?php echo $this->basePath();?>/ats/index/display-register");
    }
    else{
        return false;
    }
});
/*Tree view*/
/* $('ul.nav-left-ml').toggle();
$('label.nav-toggle').click(function () {
  $(this).parent().children('ul.nav-left-ml').toggle(300);
  var cs = $(this).find("span").attr("class");
  if(cs == 'nav-toggle-icon glyphicon glyphicon-chevron-right') {
    $(this).find("span").removeClass('glyphicon-chevron-right').addClass('glyphicon-chevron-down');
  }
  if(cs == 'nav-toggle-icon glyphicon glyphicon-chevron-down') {
    $(this).find("span").removeClass('glyphicon-chevron-down').addClass('glyphicon-chevron-right');
  }
}); */

	$(".error_message").hide();
	var allWbs=[];
	var oTable = $("#sequentialView").dataTable({"aLengthMenu": [[1, 5, 10], [1, 5, 10]], "order": [],
		"initComplete": function(settings, json) {
			$("select[name=sequentialView_length]").addClass("show-tick").selectpicker();
		},	
		"drawCallback": function( settings ){
			//alert($(this).find(".datepickerinput").attr("class"))
			$(this).find("tr.mainTr .totQuantity").trigger('click');
			if($('#sequentialView_next').hasClass('disabled') && $('#fifthStep').is(':visible'))
				$("#continueButton a").text("Submit");
			else
				$("#continueButton a").text("Continue");
		}	
	});
	$("#voucherNo").blur(function(){
		$("#VoucherSpan").text($(this).val());
	});
	$("#priority").change(function(){
		$("#prioritySpan").text($("#priority option:selected").text());
	});
  var change=false;
	//var oTable = $("#decisionTable").dataTable();
	var request='';
	var requestold='';

	$(".grid_change li").click(function(){
		if($(this).find("a").hasClass("grid_change_box")){
			$(".grid_change li a").removeClass("grid_change_box").addClass("grid_change_line").attr("data-original-title",'Sequential View');
			$(".grid_change li a span i").removeClass("fa-th").addClass("fa-list-ul");
			$(".hideView").hide();
			$("#matrixView").show();
			$('#continueButton a').text('submit');
		}
		else {
			$(".grid_change li a").removeClass("grid_change_line").addClass("grid_change_box").attr("data-original-title",'Grid View');
			$(".grid_change li a span i").removeClass("fa-list-ul").addClass("fa-th");
			$(".hideView").hide();
			$("#sequentialViewDiv").show();
			if($('#sequentialView_next').hasClass('disabled'))
				$("#continueButton a").text("Submit");
			else
				$("#continueButton a").text("Continue");			
		}
	});
	$('.datepickerinput').datepicker({
		format: "dd-mm-yyyy",
		startDate: new Date(),
		todayBtn: true,
		orientation: "top auto",
		autoclose: true
	}).on("changeDate", function(e){
		$("#dateSpan").text($(this).val());
	});	
	$('.date_icon').click(function() {
		var input = $(this).parent().find('input').datepicker('show');
	});	
	/* $('.mainmdl_m').bind('mousewheel DOMMouseScroll', function(e){
			$(".more").hide();
			$(".mainmdl_mg2").show();
			
		var scrollTo = null;

		if (e.type == 'mousewheel') {
			scrollTo = (e.originalEvent.wheelDelta * -1);
		}
		else if (e.type == 'DOMMouseScroll') {
			scrollTo = 40 * e.originalEvent.detail;
		}

		if (scrollTo) {
			e.preventDefault();
			$(this).scrollTop(scrollTo + $(this).scrollTop());
		}
	});	
	$('.body').bind('keyup', function(e){
		var scrollTo = null;
		scrollTo = (e.originalEvent.wheelDelta * -1);
		scrollTo = 40 * e.originalEvent.detail;

		if (scrollTo) {
			e.preventDefault();
			$(this).scrollTop(scrollTo + $(this).scrollTop());
		}
	});	 */	
	var parseInput = function(val) {
		var floatValue = parseFloat(val);
		return isNaN(floatValue) ? '' : floatValue;
	}
	function trimNumber(s){
	  while (s.substr(0,1) == '0' && s.length>1) { s = s.substr(1,9999); }
	  return s;
	}	
	function changePage(){
		$(".quantityVal").unbind();
		/* $(".quantityVal").bind('focusin', function(e){
			$(this).val(parseInput($(this).val()));
			$(this).select();
		}); */
		$(".quantityVal").bind('keyup keydown', function(e){
			var name = $(this).attr("name");
			var eleName = $(this).attr("elename");
			var key = e.which || e.keyCode;
			if(key != 9){
				var sum = 0;
				if($(this).val().indexOf(' ') > -1){
					$(this).val($(this).val().trim());
				}
				if(isNaN($(this).val())){
					this.value = this.value.replace(/[^0-9\.]/g,'');
					if($(this).val().indexOf('.') > -1){
						var index = $(this).val().indexOf( '.' );
						this.value = this.value.substr( 0, index + 1 ) + this.value.slice( index ).replace( /\./g, '' );
					}
				}
				
				var ex = /^\d*(\.\d{0,6})?$/;
				if(!ex.test($(this).val())){
					$(this).val($(this).val().substring(0,$(this).val().length-1));
				}
				var currVal = $(this).val();
				if(!$('#matrixView').is(':visible')){
					$("#matrixView input[name="+name+"]").attr("value", currVal);
					$("#matrixView input[name="+name+"]").val(currVal);
				}
				$("#sequentialViewSub input[name="+name+"]").attr("value", currVal);
				$("#sequentialViewSub input[name="+name+"]").val(currVal);
				
				$('#sequentialViewSub').find('input[name='+name+']').closest('.subDiv').find(".quantityVal").each(function() {
					//add only if the value is number
					if (!isNaN(this.value) && this.value.length != 0) {
						sum += parseFloat(this.value);
					}
				});
				$("input[name="+eleName+"]").val(sum.toFixed(6));
				oTable.$("tr.mainTr").find("input[name="+eleName+"]").val(sum.toFixed(6));
			}
		});
		$(".quantityVal").bind('blur', function(){
			var name = $(this).attr("name");
			var eleName = $(this).attr("elename");
			
			var sum = 0;
			if (!isNaN($(this).val()) && $(this).val().length != 0) {

			}
			else{
				$(this).val($(this).val().substring(0,$(this).val().length-1));
			}
			var ex = /^\d*(\.\d{0,6})?$/;
			if(!ex.test($(this).val())){
				$(this).val($(this).val().substring(0,$(this).val().length-1));
			}
			
			$('#sequentialViewSub').find('input[name='+name+']').closest('.subDiv').find(".quantityVal").each(function() {
				//add only if the value is number
				if (!isNaN(this.value) && this.value.length != 0) {
					sum += parseFloat(this.value);
				}
			});
			$("input[name="+eleName+"]").val(sum.toFixed(6));
			oTable.$("tr.mainTr").find("input[name="+eleName+"]").val(sum.toFixed(6));
			
			var val = 0;
			if($(this).val() == '' || $(this).val() == 0){
				val = val+'.000000';
			}
			else{
				$(this).val(trimNumber($(this).val()));
				val1 = $(this).val();
				var str = '000000';
				var splitVal = val1.split('.');
				var len = 6;
				if(splitVal[1]){
					len -= splitVal[1].length;
				}
				if(len == 6)
					val = val1+'.000000';
				else if(len < 0)
					val = splitVal[0]+'.'+splitVal[1].substring(0,6);
				else
					val = val1+str.substring(0,len);
			}
			if(val.substring(0,1) == '.')
				val = '0' + val;
			
			$("input[name="+name+"]").attr("value", val);
			$("input[name="+name+"]").val(val);			
		});
	}
	function trClick(){
		oTable.$("tr.mainTr").find(".totQuantity").unbind();
		oTable.$("tr.mainTr").find(".totQuantity").bind('click', function(){
			if(!($(this).closest("tr.mainTr").next("tr").hasClass("duplicateTr"))){
				$(this).closest("tr.mainTr").after("<tr class='duplicateTr'>"+$(".subTr_"+$(this).closest("tr.mainTr").attr("id")).html()+"</tr>");
				changePage();
			}
		});
		oTable.$("tr.mainTr").find('.date_icon').unbind('click');
		oTable.$("tr.mainTr").find(".changeVal").unbind('change');
		$(".changeVal").unbind('blur');
		
		oTable.$("tr.mainTr").find('.date_icon').bind('click', function() {
			var input = $(this).parent().find('input').datepicker('show');
		});
		oTable.$("tr.mainTr").find(".changeVal").bind('change', function(){
			var bname = $(this).attr("name");
			$("input[name="+bname+"]").val($(this).val());
		});
		$(".changeVal").bind('blur', function(){
			var bname = $(this).attr("name");
			oTable.$("tr.mainTr").find("input[name="+bname+"]").val($(this).val());
		});		
	}	
	function checkClick(id, mode){
		var rid=id;
		if(mode == 1){
			//$("#allResource").jqxGrid('selectrow', rid);						
			$.ajax({
				url:getBaseURL()+"ats/index/resource",
				type:"post",
				data:"rid="+rid+"&mode=pickList&ccid="+$("#project_name").val()+"",
				dataType:"json",
				success:function(data, textStatus, jqXHR){
					//alert(JSON.stringify(data))
					//alert(data);
					//$("#sequentialView tbody").append(data);
					//$("#matrixView thead tr").html("<th class='headcol_l headcol_l1'>Resource <br />Description</th>");

					var trlength = 	$("#matrixView thead tr th").length;	
					$.each(data['results'], function(i,v){
							var ai = oTable.fnAddData([v.Code+"<input type='hidden' name='resourceCode_"+v.ResourceId+" id='resourceCode_"+v.ResourceId+"' value='"+v.Code+"'>",
												v.ResourceName+"<input type='hidden' name='resourceName_"+v.ResourceId+"' id='resourceName_"+v.ResourceId+"' value='"+v.ResourceName+"'>",
												v.UnitName+"<input type='hidden' name='unitName_"+v.ResourceId+"' id='unitName_"+v.ResourceId+"' value='"+v.UnitName+"'><input type='hidden' name='unitId_"+v.ResourceId+"' id='unitId_"+v.ResourceId+"' value='"+v.UnitId+" '>",
												"<div class='row'>"+
													"<div class='form-group col-lg-12'>"+
														"<span class='date_icon'><i class='fa fa-calendar'></i></span>"+
														"<input type='text' name='requireddate_"+v.ResourceId+"' id='seq_requireddate_"+v.ResourceId+"' class='tbl_input datepickerinput' value='<?php echo Date('d-m-Y'); ?>' />"+
													"</div>"+
												"</div>",
												"<input type='text' class='tbl_input changeVal' name='remarks_"+v.ResourceId+"' id='remarks_"+v.ResourceId+"'>",
												"<input type='text' class='tbl_input totQuantity' value='"+parseFloat(0).toFixed(6)+"' "+((data['wbsResults'].length>0)?'readonly':'')+" name='quantity_"+v.ResourceId+"_"+v.ItemId+"' id='quantity_"+v.ResourceId+"'>",
												]);	
							
							var n = oTable.fnSettings().aoData[ai[0]].nTr;
							n.setAttribute('id', v.ResourceId);
							n.setAttribute('class', 'mainTr deleteTr_'+v.ResourceId);
							//alert(JSON.stringify(n))
					$("#sequentialViewSub tbody:first").append("<tr res_id='"+v.ResourceId+"_"+ v.ItemId+"'  class='deleteTr_"+v.ResourceId+" subTr_"+v.ResourceId+"' style=''>"+
																	"<td colspan=7>"+
																		"<div class='subDiv' style=''>"+
																			"<table class='table table-bordered table-hover col-lg-6 quanTable'>"+
																				"<thead>"+
																					"<tr>"+
																						"<th>WBS Name</th>"+
																						"<th>Quantity</th>"+
																					"</tr>"+
																				"</thead>"+
																				"<tbody>");

						/*Matrix view*/														
						$("#matrixView tbody").append("<tr res_id='"+v.ResourceId+"' id='quantityRow_"+v.ResourceId+"' class='deleteTr_"+v.ResourceId+" showData'>"+
															"<td class='headcol_l'>"+v.ResourceName+"<input type='hidden' name='resourceName_"+v.ResourceId+"' id='resourceName_"+v.ResourceId+"' value='"+v.ResourceName+"'>");
												
									$.each(data['wbsResults'], function(wbsi,wv){
										var style = 'display:none;';
										if($.inArray(wv.WbsId, allWbs) != -1)
												style="";
										
										$("#sequentialViewSub tbody:last").append("<tr style='"+((allWbs.length > 0)? style: '')+"'>"+
																					"<td width='76%'>"+wv.WbsName+" <input type='hidden' class='tbl_input' name='wbsName_"+v.ResourceId+"_"+wv.WbsId+"' value='"+wv.WbsName+"'></td>"+
																					"<td class='tbl_input_td' width='24%'><input type='text' resourceId='"+v.ResourceId+"' elename='quantity_"+v.ResourceId+"_"+ v.ItemId+"'  class='tbl_input quantityVal' name='wbsQuantity_"+v.ResourceId+"_"+v.ItemId+"_"+wv.WbsId+"' value='"+parseFloat(0).toFixed(6)+"' autocomplete='off'></td>"+
																				"</tr>");

																				
										$("#sequentialViewSub tbody:last").append("</tbody>"+
																			"</table>"+
																		"</div>"+
																	"</td>"+
																"</tr>");

										/*Matrix view*/
										if(trlength == 1){
											$("#matrixView thead tr").append("<th style='"+((allWbs.length > 0)? style: '')+"'><span data-placement='bottom' data-toggle='tooltip' data-original-title='"+wv.WbsName+"'>"+wv.WbsName+"</span></th>");
										}
										
										
										
										$("#matrixView tbody tr:last").append("<td class='tbl_input_td' style='"+((allWbs.length > 0)? style: '')+"'><input type='text' resourceId='"+v.ResourceId+"' elename='quantity_"+v.ResourceId+"_"+ v.ItemId+"' class='form-control quantityVal' name='wbsQuantity_"+v.ResourceId+"_"+wv.WbsId+"' value='"+parseFloat(0).toFixed(6)+"' autocomplete='off'></td>");
										
									});

						/*Matrix view*/				
						$("#matrixView tbody tr:last").append("<td class='bdr_left1ddd'>"+v.Code+"<input type='hidden' name='resourceCode_"+v.ResourceId+"' id='resourceCode_"+v.ResourceId+"' value='"+v.Code+"'></td>"+
																"<td class='bdr_left1ddd'>"+v.UnitName+"<input type='hidden' name='unitName_"+v.ResourceId+"' id='unitName_"+v.ResourceId+"' value='"+v.UnitName+"'>"+
																"<input type='hidden' name='unitId_"+v.ResourceId+"' id='unitId_"+v.ResourceId+"' value='"+v.UnitId+" '></td>"+
																"<td class='all_date tbl_input_td'>"+
																	"<div class='col-lg-12'>"+
																		"<span class='date_icon matrix_date_icon'><i class='fa fa-calendar'></i></span>"+
																		"<input type='text' name='requireddate_"+v.ResourceId+"' id='mat_requireddate_"+v.ResourceId+"' class='datepickerinput date_picker matrix_date_input' value='<?php echo Date('d-m-Y'); ?>' />"+
																	"</div>"+
																"</td>"+
																"<td class='all_remarks tbl_input_td'><input type='text' class='changeVal matrix_remarks_input' name='remarks_"+v.ResourceId+"' id='remarks_"+v.ResourceId+"'></td>"+
																"<td class='tbl_input_td'><input type='text' class='quantityCheck matrix_total_input' value='"+parseFloat(0).toFixed(6)+"' readonly name='quantity_"+v.ResourceId+"' id='quantity_"+v.ResourceId+"'></td>"+
															"</tr>");
															
										$("#mat_requireddate_"+v.ResourceId).datepicker({
											format: "dd-mm-yyyy",
											startDate: new Date(),
											todayBtn: true,
											orientation: "top auto",
											autoclose: true
										}).on("changeDate", function(e){
											if($(this).is(":visible"))
												oTable.$("tr.mainTr").find("input[name="+$(this).attr('name')+"]").datepicker("setDate", $(this).val());
										});
										
										oTable.$("tr.mainTr").find("#seq_requireddate_"+v.ResourceId).datepicker({
											format: "dd-mm-yyyy",
											startDate: new Date(),
											todayBtn: true,
											orientation: "top auto",
											autoclose: true
										}).on("changeDate", function(e){
											if($(this).is(":visible"))
												$("#matrixView input[name="+$(this).attr('name')+"]").datepicker("setDate", $(this).val());
										});								
									
					});
						// newly added line for spec
						$("#sequentialViewSub tr:last").append("<tr><td class='tbl_input_td'  colspan='2' width='100%'><input type='text' class='tbl_input' name='specs_s_"+rid+"' value='' resourceid='"+rid+"'/></td></tr>");

					if(trlength == 1)
						$("#matrixView thead tr").append("<th>Code</th><th>Unit</th><th class='all_date'>Date</th><th class='all_remarks'>Remarks</th><th>Total</th>");
					trClick();
				},
				complete:function(data){
					$('.date_icon').unbind("click");
					$(".changeVal").unbind("change");
				
					$('.date_icon').bind('click', function() {
						var input = $(this).parent().find('input').datepicker('show');
					});
					$(".changeVal").bind('change', function(){
						var bname = $(this).attr("name");
						$("input[name="+bname+"]").val($(this).val());
					});
				},
				error:function(jqXHR, textStatus, errorThrown){
					alert(textStatus+"-----"+errorThrown);
				}
			});
		}
		else{
			$("#sequentialViewSub .deleteTr_"+rid).remove();
			$("#matrixView .deleteTr_"+rid).remove();
			oTable.$("tr.deleteTr_"+rid).each(function(){
				var target_row = $(this).get(0); 
				var aPos = oTable.fnGetPosition(target_row); 
				oTable.fnDeleteRow(aPos);
			});
			changePage();	
		}
	}
	$("input[name=customize]").change(function(){
		allWbs=[];
		$("#selected_wbs").prop("checked", false);
		var index1 = $('#wbsGrid').jqxGrid('selectedrowindexes'); 
		if(index1.length > 0)
			$('#wbsGrid').jqxGrid('clearselection');
		
		oTable.fnClearTable();
		$("#fifthStep table .subTable").html("");
		$("#fifthStep table .appendDataMatrix").html("");

		if($("#matrixView thead tr th").lenght != 1)
			$("#matrixView thead tr").html("<th class='headcol_l headcol_l1'>Resource <br />Description</th>");
	
		var index2 = $('#mostResource').jqxGrid('selectedrowindexes'); 
		if(index2.length > 0)
			$('#mostResource').jqxGrid('clearselection');

		var index3 = $('#recentResource').jqxGrid('selectedrowindexes'); 
		if(index3.length > 0)
			$('#recentResource').jqxGrid('clearselection');	

		var index1 = $('#allResource').jqxGrid('selectedrowindexes'); 
		if(index1.length > 0)
			$('#allResource').jqxGrid('clearselection');
		
					
	});
	$(".setting_check").click(function(){
		var id = $(this).attr("id");
		if(id == "selected_wbs"){
			$("#sequentialViewSub .subDiv tbody tr").hide();
			if($(this).is(":checked")){
				if($("#matrixView tbody tr").length > 0){
					$("#sequentialViewSub .subDiv tbody tr").hide();
					$("#matrixView tbody tr td:not(:last-child) input:text").prop("readonly", true);
				}
			}
			else{
				allWbs=[];
				if($("#matrixView tbody tr").length > 0){
					$("#sequentialViewSub .subDiv tbody tr").show();
					$("#matrixView tbody tr td:not(:last-child) input:text").prop("readonly", false);
				}
				
				$("#sel_wbsId").val("none");
				var index1 = $('#wbsGrid').jqxGrid('selectedrowindexes'); 
				if(index1.length > 0)
					$('#wbsGrid').jqxGrid('clearselection');
			}
		}
	});
	$("#continueButton").click(function(){
		$(".error_message").hide();
		if($("#firstStep").is(":visible")){
			bool=false;
			if($("#voucherNo").val() == ""){
				$("#voucherNo").closest(".req_flds").children(".error_message").show().find("p").text("Enter voucher no...");
				$("#voucherNo").focus();
				bool=false;
			}
			else if($("#project_name").val() == null){
				//$("#project_name").closest(".req_flds").find('input[type="search"]').focus();
				project.select2('open');
				$("#project_name").closest(".req_flds").find(".error_message").show();
				bool=false;				
			}
			else if($("#request_type").val() == null){
				type.select2('open');
				$("#request_type").closest(".req_flds").find(".error_message").show();
				bool=false;				
			}			
			else if($("#project_date").val() == ""){
				$("#project_date").closest(".req_flds").find(".error_message").show();
				$("#project_date").focus();
				bool=false;
			}
			else if($("#priority").val() == '-1'){
				$("#priority").closest("div").find(".error_message").show();
				$("#priority").focus();
				bool=false;
			}
			else if($("#voucherNo").val() != '' && !<?php echo $genType; ?>){
				$.ajax({
					url:getBaseURL()+"ats/index/resource",
					type:"post",
					data:"voucherno="+$('#voucherNo').val()+"&mode=voucherValid",
					dataType:"json",
					success:function(data, textStatus, jqXHR){
						//alert(data)
						if(data['data'].length != 0){
							$("#voucherNo").closest(".req_flds").children(".error_message").show().find("p").text("The voucher no already used");
							$("#voucherNo").focus();
						}
						else{
							if($("input[name=customize]:checked").val() == 1){
								$("#firstStep").hide();
								$("#secondStep").show();
								$("#backButton").show();
								$("#excludeFirst").show();
							}
							else{
								$("#excludeFirst").show();
								$("#firstStep").hide();
								$("#fourthStep").show();
								$("#backButton").show();	
								pageNext();
							}							
						}
					},
					error:function(jqXHR, textStatus, errorThrown){
						alert(textStatus+"-----"+errorThrown);
					}
				});				
			}
			else{
				if($("input[name=customize]:checked").val() == 1){
					$("#firstStep").hide();
					$("#secondStep").show();
					$("#backButton").show();
					$("#excludeFirst").show();
				}
				else{
					$("#excludeFirst").show();
					$("#firstStep").hide();
					$("#fourthStep").show();
					$("#backButton").show();	
					pageNext();
				}				
			}			
		}
		else if($("#secondStep").is(":visible")){
			$("#secondStep").hide();
			if($("#selected_wbs").is(":checked")){
				$("#thirdStep").show();
			}
			else{
				$("#fourthStep").show();
				pageNext();
			}
		}
		else if($("#thirdStep").is(":visible")){
			//sel_wbsId
			var selWbsId=[];
			var index = $("#wbsGrid").jqxGrid("getselectedrowindexes");
			//alert(JSON.stringify(index))
			for(var i in index){
				selWbsId.push($("#wbsGrid").jqxGrid("getrowid", index[i]));
			}
			$("#sel_wbsId").val(selWbsId);
			$("#thirdStep").hide();
			$("#fourthStep").show();
			pageNext();
		}		
		else if($("#fourthStep").is(":visible")){
			var index = $('#allResource').jqxGrid('getselectedrowindex');
			if(index==-1){
				alert('Atleast select one Resource')
			}
			else{
				oTable.fnSetColumnVis(3, true);
				oTable.fnSetColumnVis(4, true);
				$(".all_remarks").show();
				$(".all_date").show();
				
				resourceId=[];
				var index = $("#allResource").jqxGrid("getselectedrowindexes");
				for(var i in index){
					resourceId.push($("#allResource").jqxGrid("getrowid", index[i]));
				}
				$("#resourceId").val(resourceId);
				//alert(JSON.stringify(resourceId))
				$("#fourthStep").hide();
				$("#fifthStep").show();
				
				if($("#all_remarks").is(":checked")){
					oTable.fnSetColumnVis(4, false);
					$(".all_remarks").hide();
				}
				if($("#all_date").is(":checked")){
					oTable.fnSetColumnVis(3, false);
					$(".all_date").hide();
				}
				$("#continueButton a").text("Submit");
				
				oTable.$("tr.mainTr").find(".totQuantity").trigger("click");
				if(!$('#sequentialView_next').hasClass('disabled') && $('#sequentialViewDiv').is(':visible'))
					$("#continueButton a").text("Continue");
			}
		}
		else if($("#fifthStep").is(":visible")){
			if(!$('#sequentialView_next').hasClass('disabled')){
				$('#sequentialView_next').trigger('click');
				if($('#sequentialView_next').hasClass('disabled'))
					$("#continueButton a").text("Submit");
			}
			else{
				oTable.$("tr.mainTr").find("input:text").removeClass("error");
				$("input:text").removeClass("error");
				
				/*Restt to default setting in datatable*/
				oTable.fnFilter('');
				 var oSettings = oTable.fnSettings();
				 oSettings.aaSorting = [];
				/* Sort display arrays so we get them in numerical order */
				oSettings.aiDisplay.sort(function (x,y) {
					return x-y;
				});
				oSettings.aiDisplayMaster.sort(function (x,y) {
					return x-y;
				});
				oTable.fnDraw();
				
				$("select[name=sequentialView_length]").val(1).trigger("change");
				$('select[name=sequentialView_length]').selectpicker('refresh');
				var bool = true;
				$(".quantityCheck").each(function(){
					var val = $(this).val();
					var name = $(this).attr("name");
					if(val <= 0 || val.length == 0 ){
						//if($("#sequentialView").is(":visible")){
							//oTable.$("tr.mainTr").find("input[name="+name+"]").each(function(){
								var target_row = oTable.$("tr.mainTr").find("input[name="+name+"]").closest('tr').get(0);
								var aPos = oTable.fnGetPosition(target_row);
								oTable.fnPageChange(parseInt(aPos));
							//});
						//}
						bool=false;
						$("input[name="+name+"]").focus();
						oTable.$("tr.mainTr").find("input[name="+name+"]").addClass("error");
						$("input[name="+name+"]").addClass("error");
						return false;
					}
				});
				if(bool){
					if(allWbs.length > 0){
						$("#all_wbsId").val(allWbs);
					}
					else{
						var rows = $('#wbsGrid').jqxGrid('getrows');
						for(var i = 0; i < rows.length; i++){
							var row = rows[i];
							allWbs.push(row.uid);
						}
						$("#all_wbsId").val(allWbs);
					}
					oTable.fnClearTable();
					$("form").submit();
				}				
			}
		}
	});

	$("#backButton").click(function(){
		if($("#secondStep").is(":visible")){
			$("#secondStep").hide();
			$("#firstStep").show();
			$("#backButton").hide();
			$("#excludeFirst").hide();
		}
		if($("#thirdStep").is(":visible")){
			$("#thirdStep").hide();
			$("#secondStep").show();
		}
		if($("#fourthStep").is(":visible")){
			$("#fourthStep").hide();
			if($("#selected_wbs").is(":checked")){
				$("#thirdStep").show();
			}
			else if($("input[name=customize]:checked").val() == 1){
				$("#secondStep").show();
			}
			else{
				$("#firstStep").show();
				$("#backButton").hide();
				$("#excludeFirst").hide();
			}
		}
		else if($("#fifthStep").is(":visible")){
			$("#continueButton a").text("Continue");	
			$("#fifthStep").hide();
			$("#fourthStep").show();
		}
	});


    // Initialize ajax autocomplete:
	var project = $('#project_name').select2();
	var type = $('#request_type').select2();
	
  
    

	/*WBS select start*/
		var source =
		{
			localData: <?php echo json_encode($wbsResult); ?>,
			dataType: "json",
			dataFields:
			[
				{ name: 'WbsName', type: 'string' },
			],
			id:'WbsId'
		};

		var dataAdapter = new $.jqx.dataAdapter(source,{
			loadComplete: function (data) {
				
			},
			loadError: function (xhr, status, error) {
				
			}
		});
   
		$("#wbsGrid").jqxGrid({
			width: '100%',
			pageable: true,
			selectionMode: 'singleRow',
			pagerButtonsCount: 6,
			autoheight:true,
			//rowsheight:60,
			autorowheight: true,
			filterable: true,
			sortable: true,
			//filtermode: 'advanced',				
			columnsResize: true,
			showfilterrow: true,
			ready: function(){
				var localizationobj = {};
				localizationobj.emptydatastring = "No Wbs to display";
				$("#wbsGrid").jqxGrid('localizestrings', localizationobj);								
			},
			selectionmode: 'checkbox',						
			source: dataAdapter,
			columns: [
			  { text: 'Wbs Name', editable: false,datafield: 'WbsName'},
			]
		});	
									

	
	$("#wbsGrid").on('rowselect', function (event){
		if($(this).is(":visible")){
			// event arguments.
			var args = event.args;
			// row's bound index.
			var rowBoundIndex = args.rowindex;
			// row's data. The row's data object or null(when all rows are being selected or unselected with a single action). If you have a datafield called "firstName", to access the row's firstName, use var firstName = rowData.firstName;
			var rowData = args.row; 
			var rid = rowData.uid;
			allWbs.push(rid);
			//alert(JSON.stringify(allWbs))
			if($("#matrixView tbody tr").length > 0){
				var res_id = '';
				$("#sequentialViewSub .subDiv").each(function(){
					res_id = $(this).closest("tr").attr("res_id");
					$("#sequentialViewSub input[name=wbsQuantity_"+res_id+"_"+rowData.uid+"]").closest("tr").show();
					alert('tatata');
				});
				
				var tdIndex = $("#matrixView tbody").find("input[name=wbsQuantity_"+res_id+"_"+rowData.uid+"]").closest('td').index() + 1;
				$("#matrixView tr th:nth-child("+tdIndex+")").show();
				$("#matrixView tr td:nth-child("+tdIndex+")").show();
				
			}
		}
		
	});	

	$('#wbsGrid').on('rowunselect', function (event){
		if($(this).is(":visible")){
			// event arguments.
			var args = event.args;
			// row's bound index.
			var rowBoundIndex = args.rowindex;
			// row's data. The row's data object or null(when all rows are being selected or unselected with a single action). If you have a datafield called "firstName", to access the row's firstName, use var firstName = rowData.firstName;
			var rowData = args.row;
			var rid = rowData.uid;
			allWbs.splice($.inArray(rid, allWbs),1);
			//alert(JSON.stringify(allWbs))
			if($("#matrixView tbody tr").length > 0){
				var res_id = '';
				$("#sequentialViewSub .subDiv").each(function(){
					res_id = $(this).closest("tr").attr("res_id");
					$("#sequentialViewSub input[name=wbsQuantity_"+res_id+"_"+rowData.uid+"]").val(0).attr('value', 0).trigger('blur').closest("tr").hide();
				});
				var tdIndex = $("#matrixView tbody").find("input[name=wbsQuantity_"+res_id+"_"+rowData.uid+"]").closest('td').index() + 1;
				$("#matrixView tr th:nth-child("+tdIndex+")").hide();
				$("#matrixView tr td:nth-child("+tdIndex+")").hide();					
			}
		}								

	});
	
	$('#wbsGrid').on('rowclick', function (event){
		var args = event.args;
		// row's bound index.
		var boundIndex = args.rowindex;
		var index = $('#wbsGrid').jqxGrid('selectedrowindexes'); 
		//alert($.inArray(boundIndex, index))
		if($.inArray(boundIndex, index) == -1)
			$('#wbsGrid').jqxGrid('selectrow', boundIndex);
		else
			$('#wbsGrid').jqxGrid('unselectrow', boundIndex);
	});							
	
	/*WBS select end*/
	
	
	/*grid start*/
	var sourceAllRes =
	{
		localData: [],
		dataType: "json",
		dataFields:
		[
			
			{ name: 'Code', type: 'string' },
			{ name: 'ResourceName', type: 'string' },
			{ name: 'ResourceGroupName', type: 'string' }
			
		],
        jsonReader: { repeatitem: false},
		id:'ResourceId'
	};

	var dataAdapterAllRes = new $.jqx.dataAdapter(sourceAllRes,{
		autoBind: true,
		loadComplete: function (data) {
			
		},
		loadError: function (xhr, status, error) {
			
		}
	});

	$("#allResource").jqxGrid({
		width: '100%',
		pageable: true,
		selectionMode: 'singleRow',
		pagerButtonsCount: 6,
		autoheight:true,
		//rowsheight:60,
		autorowheight: true,
		filterable: true,
		sortable: true,
		//filtermode: 'advanced',				
		columnsResize: true,
		showfilterrow: true,
		ready: function(){
			/*$("#allResource").find('.jqx-grid-column-header .jqx-checkbox-default').hide();
			// called when the Grid is loaded. Call methods or set properties here.      
			 $("#allResource").find('.jqx-grid-column-header .jqx-checkbox-default').parent().on('mousedown', function (event){
				if($(this).attr("aria-checked") == 'true'){
					$('#mostResource').jqxGrid('selectallrows');
					$('#recentResource').jqxGrid('selectallrows');
					
					var decsId = new Array();
					var rowid = $('#allResource').jqxGrid('getrows');
					//alert(JSON.stringify(rowid))
					for(var i = 0; i<rowid.length; i++){
						decsId.push(rowid[i].uid)
					}
					checkClick(decsId, '1');
					//alert(JSON.stringify(decsId))
				}
				else{
					$('#mostResource').jqxGrid('clearselection');
					$('#recentResource').jqxGrid('clearselection');
					//alert("1")
					oTable.fnClearTable();
					$("#matrixView tbody").html('');
				}										
			}); */
			var localizationobj = {};
			localizationobj.emptydatastring = "No resource to display";
			$("#allResource").jqxGrid('localizestrings', localizationobj);
		},
		selectionmode: 'checkbox',						
		source: dataAdapterAllRes,
		columns: [
					
				  { text: 'Code', editable: false,datafield: 'Code'},
				  { text: 'ResourceName', editable: false,datafield: 'ResourceName'},
				  { text: 'ResourceGroupName', editable: false,datafield: 'ResourceGroupName'}
		  
		]
	});
	
	$("#allResource").on('rowselect', function (event){
		if($(this).is(":visible")){
			// event arguments.
			var args = event.args;
			// row's bound index.
			var rowBoundIndex = args.rowindex;
			// row's data. The row's data object or null(when all rows are being selected or unselected with a single action). If you have a datafield called "firstName", to access the row's firstName, use var firstName = rowData.firstName;
			var rowData = args.row; 
			var rid = rowData.uid;
			
			checkClick(rid, '1');	
			var mindex = $('#mostResource').jqxGrid('getrowboundindexbyid', rid);
			if(mindex!=-1)
				$('#mostResource').jqxGrid('selectrow', mindex);
			var rindex = $('#recentResource').jqxGrid('getrowboundindexbyid', rid);
			if(rindex!=-1)
				$('#recentResource').jqxGrid('selectrow', rindex);							
		}
		
	});	

	$('#allResource').on('rowunselect', function (event){
		if($(this).is(":visible")){
			// event arguments.
			var args = event.args;
			// row's bound index.
			var rowBoundIndex = args.rowindex;
			// row's data. The row's data object or null(when all rows are being selected or unselected with a single action). If you have a datafield called "firstName", to access the row's firstName, use var firstName = rowData.firstName;
			var rowData = args.row;
			var rid = rowData.uid;
			
			checkClick(rid, '2');
			var mindex = $('#mostResource').jqxGrid('getrowboundindexbyid', rid);
			if(mindex!=-1)
				$('#mostResource').jqxGrid('unselectrow', mindex);
			var rindex = $('#recentResource').jqxGrid('getrowboundindexbyid', rid);
			if(rindex!=-1)
				$('#recentResource').jqxGrid('unselectrow', rindex);	
		}								
	});
	$('#allResource').on('rowclick', function (event){
		var args = event.args;
		// row's bound index.
		var boundIndex = args.rowindex;
		var index = $('#allResource').jqxGrid('selectedrowindexes'); 
		//alert($.inArray(boundIndex, index))
		if($.inArray(boundIndex, index) == -1)
			$('#allResource').jqxGrid('selectrow', boundIndex);
		else
			$('#allResource').jqxGrid('unselectrow', boundIndex);
	});					


	/*2.mostResource*/
	var sourceMostRes =
	{
		localData: [],
		dataType: "json",
		dataFields:
		[
			
			{ name: 'Code', type: 'string' },
			{ name: 'ResourceName', type: 'string' },
			{ name: 'ResourceGroupName', type: 'string' }
			
		],
		id:'ResourceId'
	};

	var dataAdapterMostRes = new $.jqx.dataAdapter(sourceMostRes,{
		autoBind: true,
		loadComplete: function (data) {
			
		},
		loadError: function (xhr, status, error) {
			
		}						
	
	});

	$("#mostResource").jqxGrid({
		width: '100%',
		pageable: true,
		selectionMode: 'singleRow',
		pagerButtonsCount: 6,
		autoheight:true,
		//rowsheight:60,
		autorowheight: true,
		filterable: true,
		sortable: true,
		//filtermode: 'advanced',				
		columnsResize: true,
		showfilterrow: true,
		ready: function(){
			var localizationobj = {};
			localizationobj.emptydatastring = "No resource to display";
			$("#mostResource").jqxGrid('localizestrings', localizationobj);
		},							
		selectionmode: 'checkbox',						
		source: dataAdapterMostRes,
		columns: [
					
				  { text: 'Code', editable: false,datafield: 'Code'},
				  { text: 'ResourceName', editable: false,datafield: 'ResourceName'},
				  { text: 'ResourceGroupName', editable: false,datafield: 'ResourceGroupName'}
		  
		]
	});
	


	$("#mostResource").on('rowselect', function (event){
		if($(this).is(":visible")){
			// event arguments.
			var args = event.args;
			// row's bound index.
			var rowBoundIndex = args.rowindex;
			// row's data. The row's data object or null(when all rows are being selected or unselected with a single action). If you have a datafield called "firstName", to access the row's firstName, use var firstName = rowData.firstName;
			var rowData = args.row; 
			var rid = rowData.uid;
			checkClick(rid, '1');
			var mindex = $('#allResource').jqxGrid('getrowboundindexbyid', rid);
			if(mindex!=-1)
				$('#allResource').jqxGrid('selectrow', mindex);
			var rindex = $('#recentResource').jqxGrid('getrowboundindexbyid', rid);
			if(rindex!=-1)
				$('#recentResource').jqxGrid('selectrow', rindex);			
		}								
	});	

	$('#mostResource').on('rowunselect', function (event){
		if($(this).is(":visible")){
			// event arguments.
			var args = event.args;
			// row's bound index.
			var rowBoundIndex = args.rowindex;
			// row's data. The row's data object or null(when all rows are being selected or unselected with a single action). If you have a datafield called "firstName", to access the row's firstName, use var firstName = rowData.firstName;
			var rowData = args.row;
			var rid = rowData.uid;
			checkClick(rid, '2');
			var mindex = $('#allResource').jqxGrid('getrowboundindexbyid', rid);
			if(mindex!=-1)
				$('#allResource').jqxGrid('unselectrow', mindex);
			var rindex = $('#recentResource').jqxGrid('getrowboundindexbyid', rid);
			if(rindex!=-1)
				$('#recentResource').jqxGrid('unselectrow', rindex);
		}								
	});

	$('#mostResource').on('rowclick', function (event){
		var args = event.args;
		// row's bound index.
		var boundIndex = args.rowindex;
		var index = $('#mostResource').jqxGrid('selectedrowindexes'); 
		//alert($.inArray(boundIndex, index))
		if($.inArray(boundIndex, index) == -1)
			$('#mostResource').jqxGrid('selectrow', boundIndex);
		else
			$('#mostResource').jqxGrid('unselectrow', boundIndex);
	});						

	/*3.recentResource*/
	var sourceRecentRes =
	{
		localData: [],
		dataType: "json",
		dataFields:
		[
			
			{ name: 'Code', type: 'string' },
			{ name: 'ResourceName', type: 'string' },
			{ name: 'ResourceGroupName', type: 'string' }
			
		],
		id:'ResourceId'
	};

	var dataAdapterRecentRes = new $.jqx.dataAdapter(sourceRecentRes,{
		autoBind: true,
		loadComplete: function (data) {
			
		},
		loadError: function (xhr, status, error) {
			
		}						
	});

	$("#recentResource").jqxGrid({
		width: '100%',
		pageable: true,
		selectionMode: 'singleRow',
		pagerButtonsCount: 6,
		autoheight:true,
		//rowsheight:60,
		autorowheight: true,
		filterable: true,
		sortable: true,
		//filtermode: 'advanced',				
		columnsResize: true,
		showfilterrow: true,
		ready: function(){
			var localizationobj = {};
			localizationobj.emptydatastring = "No resource to display";
			$("#recentResource").jqxGrid('localizestrings', localizationobj);
		},								
		selectionmode: 'checkbox',						
		source: dataAdapterRecentRes,
		columns: [
					
				  { text: 'Code', editable: false,datafield: 'Code'},
				  { text: 'ResourceName', editable: false,datafield: 'ResourceName'},
				  { text: 'ResourceGroupName', editable: false,datafield: 'ResourceGroupName'}
		  
		]
	});
	

	
	$("#recentResource").on('rowselect', function (event){
		if($(this).is(":visible")){
			// event arguments.
			var args = event.args;
			// row's bound index.
			var rowBoundIndex = args.rowindex;
			// row's data. The row's data object or null(when all rows are being selected or unselected with a single action). If you have a datafield called "firstName", to access the row's firstName, use var firstName = rowData.firstName;
			var rowData = args.row; 
			var rid = rowData.uid;
			checkClick(rid, '1');	
			var mindex = $('#allResource').jqxGrid('getrowboundindexbyid', rid);
			if(mindex!=-1)
				$('#allResource').jqxGrid('selectrow', mindex);
			var rindex = $('#mostResource').jqxGrid('getrowboundindexbyid', rid);
			if(rindex!=-1)
				$('#mostResource').jqxGrid('selectrow', rindex);	
		}								
	});	

	$('#recentResource').on('rowunselect', function (event){
		if($(this).is(":visible")){
			// event arguments.
			var args = event.args;
			// row's bound index.
			var rowBoundIndex = args.rowindex;
			// row's data. The row's data object or null(when all rows are being selected or unselected with a single action). If you have a datafield called "firstName", to access the row's firstName, use var firstName = rowData.firstName;
			var rowData = args.row;
			var rid = rowData.uid;
			checkClick(rid, '2');
			var mindex = $('#allResource').jqxGrid('getrowboundindexbyid', rid);
			if(mindex!=-1)
				$('#allResource').jqxGrid('unselectrow', mindex);
			var rindex = $('#mostResource').jqxGrid('getrowboundindexbyid', rid);
			if(rindex!=-1)
				$('#mostResource').jqxGrid('unselectrow', rindex);		
		}								
	});

	$('#recentResource').on('rowclick', function (event){
		var args = event.args;
		// row's bound index.
		var boundIndex = args.rowindex;
		var index = $('#recentResource').jqxGrid('selectedrowindexes'); 
		//alert($.inArray(boundIndex, index))
		if($.inArray(boundIndex, index) == -1)
			$('#recentResource').jqxGrid('selectrow', boundIndex);
		else
			$('#recentResource').jqxGrid('unselectrow', boundIndex);
	});							

						

	/*grid end*/
	function pageNext(){
		//alert(JSON.stringify(formData))
		$("#navbar li:first a").trigger("click");
		request = $('#project_name').val();
		if(request != requestold){
			oTable.fnClearTable();
			$("#fifthStep table .subTable").html("");
			$("#fifthStep table .appendDataMatrix").html("");			
			
			var formData = $("form").serializeArray();
			formData.push({name:"mode", value:"firstStep"});
			requestold = request;
			//$('.loading_area').show();
			$("#allResource").jqxGrid("showloadelement");
			$.ajax({
				url:getBaseURL()+"ats/index/resource",
				type:"post",
				data:formData,
				dataType:"json",
				success:function(data, textStatus, jqXHR){
					//alert(JSON.stringify(data))
					//alert(data)
					sourceAllRes.localdata = data['first'];
					dataAdapterAllRes.dataBind();
					$('#allResource').jqxGrid({ source: dataAdapterAllRes});
					
					sourceMostRes.localdata = data['second'];
					dataAdapterMostRes.dataBind();
					//$('#mostResource').jqxGrid({ source: dataAdapterMostRes,selectedrowindexes: [] });

					sourceRecentRes.localdata = data['third'];
					dataAdapterRecentRes.dataBind();
					//$('#recentResource').jqxGrid({ source: dataAdapterRecentRes, selectedrowindexes: [] });

					var index1 = $('#allResource').jqxGrid('selectedrowindexes'); 
					if(index1.length > 0)
						$('#allResource').jqxGrid('clearselection');
					
					var index2 = $('#mostResource').jqxGrid('selectedrowindexes'); 
					if(index2.length > 0)
						$('#mostResource').jqxGrid('clearselection');

					var index3 = $('#recentResource').jqxGrid('selectedrowindexes'); 
					if(index3.length > 0)
						$('#recentResource').jqxGrid('clearselection');					
				},
				complete:function(data){
					/* $('.loading_area').fadeOut(1000, function() {
						$(this).hide();
					}); */
					$("#allResource").jqxGrid("hideloadelement");
				},
				error:function(jqXHR, textStatus, errorThrown){
					alert(textStatus+"-----"+errorThrown);
				}
			});
		}
	}
	/*
	$('#container').hover(function() {
		$(document).bind('mousewheel DOMMouseScroll',function(){ 
			stopWheel(); 
		});
	}, function() {
		$(document).unbind('mousewheel DOMMouseScroll');
	});

	 
	function stopWheel(e){
		if(!e){ // IE7, IE8, Chrome, Safari 
			e = window.event; 
		}
		if(e.preventDefault) { // Chrome, Safari, Firefox 
			e.preventDefault(); 
		} 
		e.returnValue = false; // IE7, IE8
	}	
	*/
</script>