<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/mms.css';?>"/>

<style>
    .mar_30{margin-top:30px;}
    .jqx-widget-content {z-index:999 !important;}
    .jqx-grid-header {height:75px !important;}
    .ovrcls .list-icon {
        border-radius: 100%;
        font-size: 32px;
        display:block;
        height: 60px;
        line-height: 55px;
        margin: auto;
        text-align: center;
        width: 60px;
        background:#fff;
    }
    .ovrcls:hover .oval1 { background: #2aabd2;color:#fff;}
    .ovrcls:hover .oval2 { background: #265a88;color:#fff;}
    .ovrcls:hover .oval3 { background: #419641;color:#fff;}
    .ovrcls:hover .oval4 { background: #cb3d39 ;color:#fff;}
    .ovrcls:hover .oval5 { background:	#ec9923 ;color:#fff;}
    .ovrcls:hover .oval6 { background:	#35f9a9 ;color:#fff;}
    .clrrndtxt					{font-size:15px; color:#1e1e1e;}
    .ovrcls .oval1 {border: 1px solid #2aabd2; color: #2aabd2;}
    .ovrcls .oval2{border: 1px solid #265a88; color: #265a88;}
    .ovrcls .oval3{border: 1px solid #419641 ;color: #419641;}
    .ovrcls .oval4{border: 1px solid #cb3d39;color: #cb3d39;}
    .ovrcls .oval5{border: 1px solid #ec9923;color: #ec9923;}
    .ovrcls .oval6{border: 1px solid #35f9a9;color: #35f9a9;}
    ul,li{list-style:none;}
    /*-----------------------inner module tab-----------------*/
    .innermdl_tabs												{background-color:#e7e9ec; border-bottom:1px solid #2d74b4 !important;border:0px;}
    .innermdl_tabs li											{margin:0px !important;width:16%!important;}
    .innermdl_tabs li a											{color:#212121;text-align:center;padding:10px 22px 8px 22px; font-size:13px; font-weight:600;display:block;border-radius: 0px;margin:0px;border-bottom:3px solid #e7e9ec;border-top:0px !important; border-right:0px !important;border-left:0px !important;}
    .innermdl_tabs li a:after									{content:''; width:1px; height:20px; background-color:#bccae7; position:absolute; right:0px;}
    .innermdl_tabs li:last-child a:after						{content:''; width:0px;}
    .innermdl_tabs li ul li a									{text-align:left;font-size:13px;border-bottom:0px !important;}
    .innermdl_tabs li ul li a:after								{background:none !important;}
    .innermdl_tabs>li>a:hover,.innermdl_tabs>li.active>a,.innermdl_tabs>li.active>a:focus,.innermdl_tabs>li.active>a:hover{background-color:#e1e3e7 !important;color:#3f6ac3;font-weight:600;border-bottom:3px solid #2d74b4 !important;border-top:0px !important; border-right:0px !important;border-left:0px !important;}
    .innermdl_tabs li a span									{color:#3f6ac3;padding:0px 10px 0px 0px;}

    /*---------------------Responsive css---------------------*/
    @media screen and (max-width:1280px)						         {
    }
    @media only screen and (min-width : 769px) and (max-width : 800px) {
    }
    @media screen and (min-width : 361px) and (max-width : 768px){
        .innermdl_tabs li				{margin:0px !important;width:100%!important;}
    }
    @media only screen and (min-width : 321px) and (max-width : 360px)	{
        .innermdl_tabs li				{margin:0px !important; width:100%!important;}
    }
    @media only screen and (width : 320px)  {
        .innermdl_tabs li				{ margin:0px !important;width:100%!important;}
    }
    @media only screen and (width : 480px)  {
        .innermdl_tabs li				{margin:0px !important; width:100%!important;}
    }
    @media only screen and (width : 640px)  {
        .innermdl_tabs li				{ margin:0px !important;}
    }
    @media only screen and (min-width : 320px) and (max-width : 1199px) 		{
        .innermdl_tabs li				{margin:0px !important;margin:0px !important;}
    }
    @media only screen and (min-width : 981px) and (max-width : 1024px) {
    }

</style>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqxgrid.grouping.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqxgrid.aggregates.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqx-all.js"></script>

<div class="">
    <div class="" id="resourceGrid"></div>
</div>
<form method="post" action="<?php echo $this->basePath(); ?>/mms/min/minentry/1/0" id="formWrapper">
    <div id="requestTransInputsWrapper" class="hide"></div>
    <input type="hidden" name="frm_index" value="1"/>
    <input type="hidden" name="approve" id="approve" value="<?php echo (isset($Approve)) ? $Approve : '';?>">
    <input type="hidden" name="balAva" id="balAva" value="<?php echo (isset($balAva)) ? $balAva : '';?>">
    <input type="hidden" name="minOnly" id="minOnly" value="<?php echo (isset($minOnly)) ? $minOnly : '';?>">
</form>

<form method="post" action="<?php echo $this->basePath(); ?>/mms/purchasebill/billentry/1/0" id="formWrapper1">
    <div id="requestTransInputsWrapper1" class="hide"></div>
    <input type="hidden" name="frm_index" value="1"/>
</form>
<div class="col-lg-12 savebtn_area">
    <ul>
        <li class="dropdown save_btn float_r">
            <a onclick="checkForm(this)" href="javascript:void(0);" class="ripple" id="continue1">Continue to Bill</a>
        </li>
        <li class="dropdown save_btn float_r">
            <a onclick="checkForm(this)" href="javascript:void(0);"class="ripple" id="continue">Continue to Min</a>
        </li>
    </ul>
</div>

<script type="text/javascript">
    var arr_Lists = <?php echo (isset($poDetails)) ? json_encode($poDetails) : '[]';?>;
    $(document).ready(function () {
        // details grid start
        var source = {
            localdata: arr_Lists,
            datatype: "json",
            pagesize:6,
            datafields:
                [
                    { name: "PORegisterId", type: "string" },
                    { name: "POTransId", type: "string" },
                    { name: "ResourceName", type: "string" },
                    { name: "UnitName", type: "string" },
                    { name: "POQty", type: "string" },
                    { name: "CancelQty", type: "string" },
                    { name: "DCQty", type: "string"},
                    { name: "AcceptQty", type: "string" },
                    { name: "RejectQty", type: "string" },
                    { name: "BillQty", type: "string" },
                    { name: "BalQty", type: "string" },
                    { name: "QRate", type: "string" },
                    { name: "QAmount", type: "string" }
                ]
        };
        var cellsrenderer = function (row, column, value) {
            return '<div style="text-align: right; margin-top: 5px;">' + value + '</div>';
        };
        var cellsrenderer1 = function (row, column, value) {
            return '<div style="text-align: center; margin-top: 5px;">' + value + '</div>';
        };
        var dataAdapter = new $.jqx.dataAdapter(source);
        $("#resourceGrid").jqxGrid({

            width: "100%",
            source: dataAdapter,
            pageable: true,
            columnsresize: true,
            autoheight: true,
            sortable: true,
            altrows: true,
            enabletooltips: true,
            showfilterrow: false,
            filterable: true,
            groupable: true,
            showstatusbar: true,
            statusbarheight: 35,
            showaggregates: true,
            autorowheight: true,
            columns: [
                {text: 'PORegisterId', datafield: 'PORegisterId',  hidden: true, filterable: false},
                {text: 'POTransId', datafield: 'POTransId',  hidden: true, filterable: false},
                {text: 'Resource', dataField: 'ResourceName', align: 'left', cellsalign: 'left', width: '25%'},
                {text: 'Unit', dataField: 'UnitName', cellsrenderer: cellsrenderer1, align: 'centre', width: '5%'},
                {text: 'PO Qty', dataField: 'POQty', cellsrenderer: cellsrenderer,align: 'centre',cellsalign: 'centre', width: '10%'},
                {text: 'Cancel Qty', dataField: 'CancelQty',cellsrenderer: cellsrenderer, align: 'centre', width: '10%'},
                //{text: 'MIN Qty', dataField: 'DCQty', align: 'centre', cellsalign: 'right', width: '9%'},
                {text: 'Accept Qty', dataField: 'AcceptQty',cellsrenderer: cellsrenderer, align: 'centre',  width: '10%'},
                //{text: 'Reject Qty', dataField: 'RejectQty', align: 'centre', cellsalign: 'right', width: '9%'},
                {text: 'Bill Qty', dataField: 'BillQty',cellsrenderer: cellsrenderer, align: 'centre',  width: '10%'},
                {text: 'Bal Qty', dataField: 'BalQty',cellsrenderer: cellsrenderer, align: 'centre', width: '10%'},
                {text: 'Rate', dataField: 'QRate',cellsrenderer: cellsrenderer, align: 'centre',  width: '10%'},
                {text: 'Amount', dataField: 'QAmount', cellsrenderer: cellsrenderer,align: 'centre',  width: '10%'}
            ]
        });

        $("#resourceGrid").jqxGrid('showgroupsheader', false);
        //Print option
        $("#excelExport").click(function () {
            $("#resourceGrid").jqxGrid('exportdata', 'xls', 'jqxGrid');
        });
        $("#csvExport").click(function () {
            $("#resourceGrid").jqxGrid('exportdata', 'csv', 'jqxGrid');
        });
        $("#htmlExport").click(function () {
            $("#resourceGrid").jqxGrid('exportdata', 'html', 'jqxGrid');
        });
        $("#resourceGrid").on('click', function () {

        });

        $("#print").click(function () {
            var gridContent = $("#resourceGrid").jqxGrid('exportdata', 'html');
            var newWindow = window.open('', '', 'width=800, height=500'),
                document = newWindow.document.open(),
                pageContent =
                    '<!DOCTYPE html>\n' +
                    '<html>\n' +
                    '<head>\n' +
                    '<meta charset="utf-8" />\n' +
                    '<title>Pending Po</title>\n' +
                    '<h1>Pending Po</h1>\n' +
                    '</head>\n' +
                    '<body>\n' + gridContent + '\n</body>\n</html>';
            document.write(pageContent);
            document.close();
            newWindow.print();
        });

    });

    function checkForm(x){
        var condition = x.id;
        var displayedRows =  $("#resourceGrid").jqxGrid('getboundrows');
        var $inputs = '';
        var errorflag = 0;

        if($('#approve').val() == 'Partial' || $('#approve').val() == 'No') {
            alert("Approval Pending");
            return false;
        }
        if($('#balAva').val() == 'No') {
            alert("PO Balance not available");
            return false;
        }
        $.each(displayedRows, function (i, o) {
            if(o.BalQty > 0){
                $inputs += '<input type="hidden" name="poTransIds[]" class="poTransIds" value="' + o.POTransId + '"/>';
            } else {
                errorflag = 1;
            }
        });

        if(errorflag == 1){
            alert("Your BalanceQuantity is zero");
            return false;
        }

        if(condition == 'continue'){
            $('#requestTransInputsWrapper').html($inputs);
            $('#formWrapper').submit();
        } else {
            if($('#minOnly').val() == 'Yes') {
                alert("Partially min done. Cannot continue to direct bill.");
                return false;
            }
            $('#requestTransInputsWrapper1').html($inputs);
            $('#formWrapper1').submit();
        }
    }

    $("document").ready(function() {
        $('#resourceGrid').trigger('click');
    });

</script>