<style>
    #vendorServiceListWrapper {
        display: none;
    }
    .pagination-lg > li > a, .pagination-lg > li > span {
        font-size:15px !important;
        padding:5px 15px !important;
    }
    /* Excel Floating Icon */
    .fixed-action-btn          	    {position:fixed;top:85px;right:5px;padding-top:15px;margin-bottom:0;z-index:998;}
    .fixed-action-btn:hover ul li a.btn-floating{transform: scaleY(1) scaleX(1) translateX(0px);opacity: 1;}
    .btn-floating.btn-large         {width:45px;height:45px;}
    .fixed-action-btn ul 			{left:-142px;right:0;text-align:center;position:absolute;margin:0;top:22px;}
    .fixed-action-btn ul li 		{margin-left:8px;list-style-type:none;float:left;}
    .fixed-action-btn ul li a.btn-floating {transform: scaleY(0.4) scaleX(0.4) translateX(40px);opacity: 0;}
    .fixed-action-btn ul a.btn-floating i  {font-size: 17px;line-height: 37px;}
    .btn-floating                   {display:inline-block;color:#fff;position:relative;overflow:hidden;z-index:1;width:37px;height:37px;line-height:37px;padding: 0;
        background-color: #26a69a;border-radius:50%;cursor:pointer;vertical-align: middle;
        box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);text-decoration: none;transition: all .3s ease;
        -webkit-transition: all .3s ease; -moz-transition: all .3s ease; -o-transition: all .3s ease;}
    .btn-floating i                 {width: inherit;display: inline-block;text-align: center;color: #fff;font-size:20px;line-height: 45px; font-weight:normal; color:#fff;}
    .next-bt                        {text-align:center;}
    .next-bt a:hover                {border:1px solid #3580C4 !important; background:#fff !important; color:#3580C4 !important;}
    .next-bt a                      {background:#3580C4!important;border:1px solid #3580C4; border-radius: 4px;
        color:#fff!important; font-size:14px; padding: 5px 10px; text-align: center; transition: all 0.4s ease 0s;}
    .commargin_top 					{margin-top: 30px;}

    /* Excel Floating Icon end*/
    /*--------------Jqx Grid jqx All-------------------*/
    #jqxgrid									{min-height:200px !important;}
    .jqx-grid-header                             {height:75px !important;}
    .jqx-grid-groups-row						{padding-left:5px !important;}
    .jqx-grid-pager-input						{padding: 2px; text-align: center !important; width: 35px;}
    .jqx-dropdownlist-state-normal				{display: block;  float: right;height: 16px !important;margin-right: 7px;margin-top: 0;  padding-bottom: 2px !important;padding-top: 2px !important; width: 40px;}
    .jqx-button									{cursor: pointer;float: right;margin-right: 3px !important;margin-top: 0 !important;padding: 0 !important;width: 20px !important;}
    .jqx-button > .jqx-icon-arrow-left,
    .jqx-button >.jqx-icon-arrow-right			{height: 21px !important;margin-left: 0 !important;width: 20px !important;}
    .jqx-listitem-element						{height: 25px !important;}
    .jqx-input									{height: 25px !important; margin:2px 4px !important;}
    .jqx-grid-pager .jqx-grid-pager-input		{height:20px !important; margin:0px 4px !important;}
    #jqxgrid .jqx-grid-cell-right-align 		{text-align:right !important; padding-right:8px;}
    #jqxgrid .jqx-grid-cell-left-align 			{padding-left:8px;}
    .jqx-grid-column-menubutton::after			{left:4px;top:10px;}
    .jqx-widget-content{z-index:999 !important;}
</style>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqxgrid.grouping.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqxgrid.aggregates.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/library/jqwidgets/jqx-all.js"></script>
<div class="content_wrapper  padlr0">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 padlr0">
                <div class="col-lg-6 col-md-6 col-sm-6 padlr0">
                    <h1 class="col-lg-6 col-md-6 col-sm-6">Request History</h1>
                    <div class="col-lg-6">
                        <div class="fixed-action-btn active">
                            <a class="btn-floating btn-large">
                                <i class="fa fa-print"></i>
                            </a>
                            <ul>
                                <li>
                                    <a class="btn-floating hide-input-file" id="print" href="javascript:void(0);" data-toggle="tooltip" data-placement="top" data-original-title="Print Report">
                                        <i class="fa fa-print"></i>

                                    </a>
                                </li>
                                <li>
                                    <a class="btn-floating" id="excelExport" href="javascript:void(0);" data-toggle="tooltip" data-placement="top" data-original-title="Download Excel">
                                        <i class="fa fa-download"></i>
                                    </a>
                                </li>
                                <li>
                                    <a class="btn-floating" id="csvExport" href="javascript:void(0);" data-toggle="tooltip" data-placement="top" data-original-title="Export CSV">
                                        <i class="fa fa-file-archive-o"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-12 commargin_top">
                <div class="col-lg-3">
                    <select data-placeholder="Request Type" class="form-control single_dropdown lbl_move sortoption" tabindex="7" name="RequestType" id="RequestType">
                        <option value=""></option>
                        <option value="Activity">Activity</option>
                        <option value="Asset">Asset</option>
                        <option value="Labour">Labour</option>
                        <option value="Material">Material</option>
                    </select>
                </div>
                <div class="col-lg-3">
                    <select data-placeholder="Cost Centre" class="form-control multiple_dropdown lbl_move sortoption"  multiple="multiple" tabindex="7" name="CostCentre[]" id="CostCentre">
                        <option value=""></option>
                        <?php if(isset($arr_costcenter)):
                            foreach($arr_costcenter as $costcenter): ?>
                                <option value="<?php echo $costcenter['CostCentreId'];?>"><?php echo $costcenter['CostCentreName'];?></option>
                            <?php endforeach;
                        endif; ?>
                    </select>
                </div>
                <div class="col-lg-3">
                    <div class="form-group">
                        <span class="date_icon"><i class="fa fa-calendar"></i></span>
                        <input type="text" name="fromDate" id="fromDate" class="form-control date_picker lbl_move" readonly="readonly" label="From Date" onchange="bindRequests(this.value)" value="<?php echo (isset($fromDat) && $fromDat != 0) ? Date('d-m-Y',strtotime($fromDat)) : Date('d-m-Y',strtotime("-3 months")); ?>"/>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="form-group">
                        <span class="date_icon"><i class="fa fa-calendar"></i></span>
                        <input type="text" name="toDate" id="toDate" class="form-control date_picker lbl_move" readonly="readonly" label="To Date" onchange="bindRequests(this.value)" value="<?php echo (isset($toDat) && $toDat != 0) ? Date('d-m-Y',strtotime($toDat)) : Date('d-m-Y'); ?>"/>
                    </div>
                </div>
            </div>
            <div class="col-lg-12 clear">
                <div class="table-responsive clear">
                    <div id="jqxgrid"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-lg-12 savebtn_area">
    <ul>
        <li class="dropdown save_btn float_r">
            <a href="<?php echo $this->basePath();?>/ats/report/reportlist" class="ripple">Close</a>
        </li>
    </ul>
</div>
<script type="text/javascript">
$(document).ready(function() {
    $(".multiple_dropdown").select2({
    });
});
$('#CostCentre').on('change',function(){
    bindRequests();
});
$('#RequestType').on('change',function(){
    bindRequests();
});

function bindRequests() {
    var costCentreId = $('#CostCentre').val();
    var RequestType = $('#RequestType').val();
    var fromDate=$('#fromDate').val();
    var toDate=$('#toDate').val();
    $.ajax({
        url:getBaseURL()+'ats/report/request-history',
        type:"post",
        data:{'CostCentreId':costCentreId, 'RequestType': RequestType,'fromDate':fromDate,'toDate':toDate},
        dataType:"json",
        success:function(data, textStatus, jqXHR){
            $("#jqxgrid").jqxGrid('clear');
            var source =
            {
                dataFields: [
                    { name: 'RequestId', type: 'string'},
                    { name: 'RequestDate', type: 'string'},
                    { name: 'RequestNo', type: 'string'},
                    { name: 'RefNo', type: 'string'},
                    { name: 'CostCentre', type: 'string'}
                ],
                localdata:data['resource'],
                id: 'RequestId',
                datatype: "json",
                async: false

            };
            //alert(JSON.stringify(source))
            var employeesAdapter = new $.jqx.dataAdapter(source);


            /*Decision start*/
            var ordersSource1 =
            {
                localdata:data['decision'],
                dataFields: [
                    { name: 'RequestId', type: 'string'},
                    { name: 'RequestTransId', type: 'string'},
                    { name: 'Code', type: 'string'},
                    { name: 'Resource', type: 'string'},
                    { name: 'Unit', type: 'string'},
                    { name: 'ReqQty', type: 'string'},
                    { name: 'POQty', type: 'string'},
                    { name: 'TransferQty', type: 'string'},
                    { name: 'BalQty', type: 'string'}
                ],
                datatype: "json",
                async: false
            };

            var ordersDataAdapter1 = new $.jqx.dataAdapter(ordersSource1, { autoBind: true });
            orders1 = ordersDataAdapter1.records;
            //alert(JSON.stringify(orders1))
            var nestedGrids1 = new Array();

            // create nested grid.
            var initrowdetails1 = function (index, parentElement, gridElement, record) {
                //alert(JSON.stringify(record))
                var id = record.uid.toString();
                var grid = $($(parentElement).children()[0]);
                $(grid).attr('id', 'nestedGrid_' + id);
                nestedGrids1[index] = grid;
                var filtergroup = new $.jqx.filter();
                var filter_or_operator = 1;
                var filtervalue = id;
                var filtercondition = 'equal';
                var filter = filtergroup.createfilter('stringfilter', filtervalue, filtercondition);
                // fill the orders1 depending on the id.
                var ordersbyid = [];
                for (var m = 0; m < orders1.length; m++) {
                    var result = filter.evaluate(orders1[m]["RequestId"]);
                    if (result)
                        ordersbyid.push(orders1[m]);
                }
                //alert(JSON.stringify(ordersbyid))
                var orderssource1 = { dataFields: [
                    { name: 'RequestId', type: 'string'},
                    { name: 'RequestTransId', type: 'string'},
                    { name: 'Code', type: 'string'},
                    { name: 'Resource', type: 'string'},
                    { name: 'Unit', type: 'string'},
                    { name: 'ReqQty', type: 'string'},
                    { name: 'POQty', type: 'string'},
                    { name: 'TransferQty', type: 'string'},
                    { name: 'BalQty', type: 'string'}
                ],
                    id: 'RequestTransId',
                    localdata: ordersbyid
                };
                //alert(JSON.stringify(orderssource1))
                var nestedGridAdapter1 = new $.jqx.dataAdapter(orderssource1);

                if (grid != null) {
                    grid.jqxGrid({
                        source: nestedGridAdapter1,
                        width: '90%',
                        height:700,
                        sortable: true,
                        //editable:true,
                        filterable: true,
                        pageable: true,
                        //autoheight:true,
                        rowdetails: true,
                        //rowsheight: 35,
                        columnsresize: true,
                        columnsreorder: true,
                        initrowdetails: initrowdetails2,
                        rowdetailstemplate: { rowdetails: "<div id='grid' style='margin: 10px;'></div>", rowdetailsheight: 500, rowdetailshidden: true },
                        ready: function () {
                            //$("#jqxgrid").jqxGrid('showrowdetails', 1);
                        },

                        columns: [
                            { text: 'Code', dataField: 'Code'},
                            { text: 'Resource', dataField: 'Resource'},
                            { text: 'Unit', dataField: 'Unit'},
                            { text: 'Req Qty', dataField: 'ReqQty'},
                            { text: 'POQty', dataField: 'POQty'},
                            { text: 'TransferQty', dataField: 'TransferQty'},
                            { text: 'Bal Qty', dataField: 'BalQty'},
                            { text: 'RequestTransId', dataField: 'RequestTransId',hidden:true}
                        ]
                    });

                }
            }
            /*Decision end*/


            //alert(JSON.stringify(data))

            /*Cost centre start*/
            var ordersSource2 =
            {
                localdata:data['project'],
                dataFields: [
                    { name: 'RequestTransId', type: 'string'},
                    { name: 'DecisionId', type: 'string'},
                    { name: 'DecTransId', type: 'string'},
                    { name: 'DecisionNo', type: 'string'},
                    { name: 'DecisionDate', type: 'string'}
                ],
                datatype: "json",
                async: false
            };
            //alert(JSON.stringify(ordersSource2))
            var ordersDataAdapter2 = new $.jqx.dataAdapter(ordersSource2, { autoBind: true });
            orders2 = ordersDataAdapter2.records;
            var nestedGrids2 = new Array();

            // create nested grid.
            var initrowdetails2 = function (index, parentElement, gridElement, record) {
                //alert(JSON.stringify(record))
                var id = record.uid.toString();
                //alert(uid)
                var grid = $($(parentElement).children()[0]);
                $(grid).attr('id', 'projectGrid_' + id);
                nestedGrids2[index] = grid;
                var filtergroup = new $.jqx.filter();
                var filter_or_operator = 1;
                var filtervalue = id;
                var filtercondition = 'equal';
                var filter = filtergroup.createfilter('stringfilter', filtervalue, filtercondition);
                // fill the orders2 depending on the id.
                var ordersbyid = [];
                for (var m = 0; m < orders2.length; m++) {
                    var result = filter.evaluate(orders2[m]["RequestTransId"]);
                    if (result)
                        ordersbyid.push(orders2[m]);
                }

                var orderssource2 = { dataFields: [
                    { name: 'RequestTransId', type: 'string'},
                    { name: 'DecisionId', type: 'string'},
                    { name: 'DecTransId', type: 'string'},
                    { name: 'DecisionNo', type: 'string'},
                    { name: 'DecisionDate', type: 'string'}
                ],
                    id: 'DecTransId',
                    localdata: ordersbyid
                };

                var nestedGridAdapter2 = new $.jqx.dataAdapter(orderssource2);

                if (grid != null) {
                    grid.jqxGrid({
                        source: nestedGridAdapter2,
                        width: '90%',
                        height:400,
                        sortable: true,
                        //editable:true,
                        filterable: true,
                        pageable: true,
                        rowdetails: true,
                        rowsheight: 35,
                        columnsresize: true,
                        columnsreorder: true,
                        initrowdetails: initrowdetails3,
                        rowdetailstemplate: { rowdetails: "<div id='grid' style='margin: 10px;'></div>", rowdetailsheight: 300, rowdetailshidden: true },
                        ready: function () {
                            //$("#jqxgrid").jqxGrid('showrowdetails', 1);
                        },

                        columns: [
                            { text: 'DecisionId', dataField: 'DecisionId',hidden:true},
                            { text: 'DecisionNo', dataField: 'DecisionNo'},
                            { text: 'DecisionDate', dataField: 'DecisionDate'},
                            { text: 'DecTransId', dataField: 'DecTransId',hidden:true}
                        ]
                    });

                }
            }
            /*Cost centre end*/


            /*Wbs start*/
            var ordersSource3 =
            {
                localdata:data['wbs'],
                dataFields: [
                    { name: 'DecTransId', type: 'string'},
                    { name: 'TransNo', type: 'string'},
                    { name: 'TransDate', type: 'string'},
                    { name: 'Qty', type: 'string'},
                    { name: 'EntryType', type: 'string'},
                    { name: 'CostCentre', type: 'string'}

                ],
                datatype: "json",
                async: false
            };

            var ordersDataAdapter3 = new $.jqx.dataAdapter(ordersSource3, { autoBind: true });
            orders3 = ordersDataAdapter3.records;
            var nestedGrids3 = new Array();
            // create nested grid.
            var initrowdetails3 = function (index, parentElement, gridElement, record) {
                //alert(JSON.stringify(record))
                var id = record.uid.toString();
                var grid = $($(parentElement).children()[0]);
                $(grid).attr('id', 'wbsGrid_' + id);
                nestedGrids3[index] = grid;
                var filtergroup = new $.jqx.filter();
                var filter_or_operator = 1;
                var filtervalue = id;
                var filtercondition = 'equal';
                var filter = filtergroup.createfilter('stringfilter', filtervalue, filtercondition);
                // fill the orders3 depending on the id.
                var ordersbyid = [];
                for (var m = 0; m < orders3.length; m++) {
                    var result = filter.evaluate(orders3[m]["DecTransId"]);
                    if (result)
                        ordersbyid.push(orders3[m]);
                }

                var orderssource3 = {
                    dataFields: [
                        { name: 'DecTransID', type: 'string'},
                        { name: 'TransNo', type: 'string'},
                        { name: 'TransDate', type: 'string'},
                        { name: 'Qty', type: 'string'},
                        { name: 'EntryType', type: 'string'},
                        { name: 'CostCentre', type: 'string'}
                    ],
                    //id:'RequestId'
                    localdata: ordersbyid
                };

                var nestedGridAdapter3 = new $.jqx.dataAdapter(orderssource3);

                if (grid != null) {
                    grid.jqxGrid({
                        source: nestedGridAdapter3,
                        width: '90%',
                        height:200,
                        sortable: true,
                        //editable:true,
                        filterable: true,
                        pageable: true,
                        columnsresize: true,
                        columnsreorder: true,
                        ready: function () {
                            //$("#jqxgrid").jqxGrid('showrowdetails', 1);
                        },

                        columns: [
                            { text: 'TransNo', dataField: 'TransNo'},
                            { text: 'FromCostCentre', dataField: 'CostCentre'},
                            { text: 'TransDate', dataField: 'TransDate'},
                            { text: 'Qty', dataField: 'Qty'},
                            { text: 'EntryType', dataField: 'EntryType'}
                        ]
                    });

                }
            }
            /*wbs end*/




            // creage jqxgrid
            $("#jqxgrid").jqxGrid(
                {
                    width: '100%',
                    autoheight:true,
                    source: source,
                    sortable: true,
                    pagerMode: 'advanced',
                    pagerHeight: 40,
                    //editable:true,
                    filterable: true,
                    pageable: true,
                    rowdetails: true,
                    rowsheight: 35,
                    altrows: false,
                    enabletooltips: true,
                 //   showfilterrow: true,
                    showaggregates: true,
                    pagerButtonsCount: 6,
                    keyboardnavigation: true,
                    autorowheight: true,
                    columnsresize: true,
                    columnsreorder: true,
                    initrowdetails: initrowdetails1,
                    rowdetailstemplate: {
                        rowdetails: "<div id='grid' style='margin: 10px;'></div>", rowdetailsheight: 1000, rowdetailshidden: true
                    },
                    ready: function () {
                        //$("#jqxgrid").jqxGrid('showrowdetails', 1);
                    },
                    columns: [
                        { text: 'RequestDate', dataField: 'RequestDate'},
                        { text: 'RequestNo', dataField: 'RequestNo'},
                        { text: 'RefNo', dataField: 'RefNo'},
                        { text: 'CostCentre Name', dataField: 'CostCentre'},
                        { text: 'RequestId', dataField: 'RequestId',hidden:true}
                    ]
                });
            $("#jqxgrid").jqxGrid('showgroupsheader', false);
            //Print option
            $("#excelExport").click(function () {
                $("#jqxgrid").jqxGrid('exportdata', 'xls', 'jqxGrid');
            });
            $("#csvExport").click(function () {
                $("#jqxgrid").jqxGrid('exportdata', 'csv', 'jqxGrid');
            });
            $("#htmlExport").click(function () {
                $("#jqxgrid").jqxGrid('exportdata', 'html', 'jqxGrid');
            });

            $("#print").click(function () {
                var gridContent = $("#jqxgrid").jqxGrid('exportdata', 'html');
                //var gridContent = $("#jqxgrid").jqxGrid('exportdata', 'html', 'jqxGrid', true, null, false);
                var newWindow = window.open('', '', 'width=800, height=500'),
                    document = newWindow.document.open(),
                    pageContent =
                        '<!DOCTYPE html>\n' +
                        '<html>\n' +
                        '<head>\n' +
                        '<meta charset="utf-8" />\n' +
                        '<title> Request History</title>\n' +
                        '<h1> Request History</h1>\n' +
                        '</head>\n' +
                        '<body>\n' + gridContent + '\n</body>\n</html>';
                document.write(pageContent);
                document.close();
                newWindow.print();

                /*$("#jqxgrid").jqxGrid('exportdata', 'html', 'jqxGrid', true, null, false);*/
            });

            $("#jqxgrid").bind('rowselect', function (event) {
                var row = event.args.rowindex;
                var datarow = $("#jqxgrid").jqxGrid('getrowdata', row);

            });
        }
    });
}
</script>